### ISSUE TITLE
USER ISSUE: Fishtrap not accessable

### ISSUE THREAD

**Issue by fame1991** [StrangeLoopGames/EcoIssues#5144]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Place fishtrap in deep water
Try to access it

**Expected behavior:**
Menu opens, I can take the fish out

**Actual behavior:**
As soon as the menu is open Im floating up which closes the menu again -> can't take the fish out

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4275
