### ISSUE TITLE
USER ISSUE: Fishtrap could contain anything

### ISSUE THREAD

**Issue by fame1991** [StrangeLoopGames/EcoIssues#5145]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Place fishtrap
Add random item (e.g. corn seeds)

**Expected behavior:**
Not accepted by fishtrap

**Actual behavior:**
Fishtrap model appears with fishs inside
Item stored in fishtrap

**Comment by MarjieAVolk** [comment]
@craig-jong Can make the inventory remove only with AuthorizationInventory flags maybe

**Comment by craig-jong** [comment]
That's a good point. Plus it would stop people from trying to bait their fish traps.... >_>

**Comment by elfl0rd** [comment]
Adding this to 8.1 and close my dupe.
