### ISSUE TITLE
USER ISSUE: Hotbar Drag&Drop

### ISSUE THREAD

**Issue by nickhunter93** [StrangeLoopGames/EcoIssues#5147]
#**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1.Tutorial Axe : Drag to a different position on hotbar
Possible cause could be that my mouse button sometimes does multiple clicks at once...
So maybe the drop gets broken because it gets a new click before the process is finished

That is all xD

**Expected behavior:**
Switched to a different place on the Hotbar

**Actual behavior:**
Not switch and the Icon of the Axe bugged

**Comment by nickhunter93** [comment]
Fix for User is tab to windows and then back into game

**Comment by nickhunter93** [comment]
Possible cause could be that my mouse button sometimes does multiple clicks at once...

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841
