### ISSUE TITLE
USER ISSUE: Player appearing in Objective List (Does Not Exist)

### ISSUE THREAD

**Issue by ZeelNightwolf** [StrangeLoopGames/EcoIssues#5148]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Open Objective List
2. Hover over each player until find one that says "Not Found this object no longer exists"
3. Attempt to click on reputation

**Expected behavior:**
Not appeared in first place or not lost the reference to the player.

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC HandleLinkClicked on Player!

Reputation of null user requested.


Stack:
   at Eco.Gameplay.Economy.ReputationManager.OpenGiveRepUI(Player player, String targetUser)
   at Eco.Gameplay.Systems.TextLinks.TextLinkManager.OnLinkClicked(Player player, String linkId)

```

**Comment by MarjieAVolk** [comment]
Had your server deleted any user files from their save manually?

**Comment by ZeelNightwolf** [comment]
No, I'm pretty sure we haven't as of yet.

**Comment by MarjieAVolk** [comment]
Could you pass over your save file?

**Comment by Tinytina79** [comment]
do you wont the whole game file or just the user file please? then i can post

**Comment by MarjieAVolk** [comment]
The whole .eco file I suppose

**Comment by ZeelNightwolf** [comment]
![image](https://user-images.githubusercontent.com/29911902/36836416-5cd9e158-1d8d-11e8-8499-11717f9ff314.png)
Another name that is doing the same. 
Tina has emailed the file this morning.

**Comment by MarjieAVolk** [comment]
Ohhh okay, this is because of a special character in the name.  Seems the link parser does not like the '>'.  @Nanders can you xml/html escape usernames in their UILinkContent?

**Comment by ZeelNightwolf** [comment]
![image](https://user-images.githubusercontent.com/29911902/36901611-e3d5c818-1e7b-11e8-807a-db493116c919.png)

**Comment by ZeelNightwolf** [comment]
There is at least 3 on the server now and some dont seem to have special characters

**Comment by ZeelNightwolf** [comment]
Actually, Ive found a way to check if they do but its not appearing. Using the Laws.

**Comment by ZeelNightwolf** [comment]
![image](https://user-images.githubusercontent.com/29911902/36901692-29e75f92-1e7c-11e8-8ef5-cb0c25302c73.png)

**Comment by ZeelNightwolf** [comment]
![image](https://user-images.githubusercontent.com/29911902/36901733-4da6c774-1e7c-11e8-814b-405dc74bec6d.png)
![image](https://user-images.githubusercontent.com/29911902/36901759-5b481928-1e7c-11e8-8947-f92918e15b75.png)
This is the one that doesnt have a special character I think...

**Comment by MarjieAVolk** [comment]
Think those quotes might not play nice either.

**Comment by Deantwo** [comment]
I guess this is similar to what I reported. Title of this issue could maybe have been better.
See: #8261

**Comment by WeaselDog** [comment]
Looks like this was fixed with the related issue. Thanks for the detailed report and let us know if you experience this issue again.
