### ISSUE TITLE
USER ISSUE: Game requires login

### ISSUE THREAD

**Issue by siobhan-j** [StrangeLoopGames/EcoIssues#5149]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Launch the game from steam	

**Expected behavior:**
Brought me to the main menu	

**Actual behavior:**
requires me to login with my Strange Loop account. After repeatedly closing and reopening the game eventually it will show the main menu. Probably 7 out of 8 times it asks for login rather than display the menu. I also registered an account just in case and it would not recognize my credentials, but that's separate.

**Comment by alecpura** [comment]
+1

**Comment by MarjieAVolk** [comment]
Upping priority as we've had several reports of steam login failing now.

**Comment by siobhan-j** [comment]
An update for this: the failure seems to only occur when I open the game from the taskbar (which it's pinned to - Windows 8.1 Pro) vs opening it from the Steam app.

**Comment by MarjieAVolk** [comment]
Ah, well that's something.  I forgot you could do that.  I am not sure if we even can support that?

**Comment by Nanders** [comment]
This should be improved.

Shortcuts directly to the .exe isn't explicitly supported, but you can still launch it through steam this way by modifying the shortcut to point to `"...\Steam\steamapps\common\Eco\Eco.exe" -steam`

Or pin steams' shortcut (except for the .exe)
