### ISSUE TITLE
USER ISSUE: logged in as BLUE

### ISSUE THREAD

**Issue by brandenthomas** [StrangeLoopGames/EcoIssues#5150]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
log in		

**Expected behavior:**
logged in as Darkadia

**Actual behavior:**
logged in as blue

I have done everything I can think of.
Restarted computer
loaded into another server
changed my user name ect

**Comment by brandenthomas** [comment]
I even uninstalled the game and re-installed it please move this up in priority can't play!

**Comment by MarjieAVolk** [comment]
So you were named 'blue' on every server you joined?  Are you playing on steam?  Do you also have a Strange Loop account?

**Comment by MarjieAVolk** [comment]
Closing due to no response.
