### ISSUE TITLE
Carts appear on the most highest point after server restart

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5153]
We have the issue that carts that have been left in the mine appear on top of the mine at the exact same coordinates (despite height coordinates, there it takes the highest) after a server restart. Not critical, but enerving.

**Comment by MarjieAVolk** [comment]
@SeanAtr0n might be related to all those other cart bugs, I got mixed up with all these cart bugs now lol

**Comment by D3nnis3n** [comment]
That bug reminded me of a bug i once had in another game. There the issue was with the height coordinate being set to the top-most block. Because of that, my guess on the cause.

**Comment by LiaungYip** [comment]
I believe this happens with all vehicles, including Excavators (!).

**Comment by SeanAtr0n** [comment]
fixed 7.2
