### ISSUE TITLE
SUGGESTIONS: Large list of suggestions, mostly QOL changes

### ISSUE THREAD

**Issue by Skelun** [StrangeLoopGames/EcoIssues#5154]
This is one of the best games I've ever played. But there are a lot of improvements that I think can be made.

#### Interactions

- Hold `E` to pick up things on the ground
- Click, drag, if it has space it will fit automacally (*You don't need to drag to a specific slot*)
	- Or just `Alt + Click` or `Ctrl + Click` and it will move to the closest available space
- Easily choose in which storage the object will be when finished
- Another key to consume food (*So you don't accidentaly eat it when trying to store in a chest, or any other storage object*)

#### Status

- When the item durability is running low it will have a different sound when used, or will trigger a sound
- When calories are running low it will trigger a sound

#### Items & Furniture

- Bookshelfs now store books
- You can put back the scroll on the book, or stack a pile of it
	- Deeds also can be stacked
- Icebox works. You can store food there
- More object interactions
	- You are able to sit on the chair
	- You are able to lay on bed
	- Etc.
- Objects will remember Deeds!

#### House & Construction

- You can have a shared house with a limited amount of people (*You +1 would be ok*)
- You can place the carpet under some mobile
- Improved snapping

#### Reutilization

- You can use objects made of wood as fuel, but some objects will leave tailing

#### Menu

- `ESC` closes open menus
- Search bar
- Scroll bar is wider and faster
- Sort by availabilty (*Which recipes you can make*)
- Windows with few informations will be smaller
- It now shows which furnish is disabled in the same list as your active furnishes, but with the red color

#### Hit Boxes

- Smaller hitboxes on a lot of objects to prevent accidentaly openning it
*Examples of large annoying hitboxes: Stockpile, Wood Carts.*

#### Carts

- You can pull it in both directions without self-turning.

#### New Objects

- Ladder (*Vertical*)

#### Graphics

- Better color palette (less saturated) with more harmonizing colors

![Grass color comparison](https://i.imgur.com/VADb6jC.gif)

- Better textures and some texture variations on very repetable objects (like Grass, Dirt, Dirt Road, Hewn Logs, Bricks, etc.)
- Better Terrain and Foliage interaction

![Foliage out of terrain](https://i.imgur.com/R6c8uwf.jpg)

- Better models (*Some are well made, others are boring ~~wood carts~~*)
- Models variations

**Comment by D3nnis3n** [comment]
> Hold E to pick up things on the ground

Please do not do this. This is already enerving in all the new games with that feature. I hate it to have to hold a button to do something. Pressing "E" shortly is absoluteley okay.

**Comment by MarjieAVolk** [comment]
I think they are asking for the option to hold down 'E' in order to pick up many items.  It wouldn't affect you if you didn't want to use it.

**Comment by D3nnis3n** [comment]
Alright. Sounded like the new "feature" recent games have. English is not my main language, though.

**Comment by Skelun** [comment]
@D3nnis3n I had to dig a 12x12x20 hole with basic tools to store tailing. I was wishing so hard for some sort of hold-to-pick button.

**Comment by D3nnis3n** [comment]
I do now understand what you meant. I interpreted it as the new feature of recent games that force you to hold down e for a longer time to really do that action. (I suppose it's meant as something like a "do you really want to do this and not accidentally pressed the button)

Seems like you mean a vacuum cleaner like feature - i'd be happy about this.

**Comment by D3nnis3n** [comment]
Ah, and, of course, he settled down hell lot away of the capital and made his 1200 Iron he could have made for free in my blast furnace with his bloomery. I somehow raged when i saw this. I hope the 7.2.0 patch comes soon. We already had thought about banning the player until the patch comes out, as we were fully unable to explain him how he has to store the tailings - e.g. he just did not understand.

**Comment by johnkslg** [comment]
Great suggestions. Shared housing is on the list, as are a lot of these. Thank you!  Will get to these over time.
