### ISSUE TITLE
Cart Flying

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5156]
I'm pretty confident this has been reported before, but under some rare circumstances i was not really able to reproduce yet the cart starts flying into the orbit and bounces off the earth. Two days ago i hit several benches with my cart and also fell down a ramp when my cart was launched into orbit (i saw the earth as small as in a satellite) and then bounced for a good 15 minutes as everytime i landed somewhere - e.g. in a ocean i was bounced off again.

With CTRL i somehow was able to steer a bit and to land near a road where i could get off the cart before bouncing off (which stopped the bouncing immediatly) and then driving home with sickness (for christmas).

**Comment by SeanAtr0n** [comment]
Fixed in 7.2
