### ISSUE TITLE
USER ISSUE: Broken Crafting Stations

### ISSUE THREAD

**Issue by Elduderiino** [StrangeLoopGames/EcoIssues#5159]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Not sure why it happens, but occasionally my crafting stations will completly break. It usually results in a game breaking issue. I tried to create a second crafting station (Kiln) but it too did not work.

**Expected behavior:**
Started the time uppon placing the materials in any crafting station.

**Actual behavior:**
Recieved the materials I had placed but the timer never started.

**Comment by Thyriel** [comment]
Is there a red dot in the upper left corner of the station when this happens ? If yes check the tables status tab for details on whats wrong.

**Comment by MarjieAVolk** [comment]
^ When your table is not crafting, check the Status tab first.

What kind of game breaking issues do you see alongside this?

**Comment by Elduderiino** [comment]
Thank you very much! New to the game and nobody to play with. I appreciate
you taking the time to respond to my thread! You have my gratitude good sir!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
