### ISSUE TITLE
Chest placement issue 4.2

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#516]
http://ecoforum.strangeloopgames.com/topic/772/chest-placement-must-be-inside-a-structure

**Comment by craig-jong** [comment]
Unless I assign it negative occupancy, I believe the mesh must be moved. 

Keegan, let me know if thats not the case and I'll look into it.

**Comment by keegan-o** [comment]
Just needs the occupancy x and z reversed and should be good now. (In svn)
