### ISSUE TITLE
USER ISSUE: Duplicate Carrying Resources

### ISSUE THREAD

**Issue by Trenix** [StrangeLoopGames/EcoIssues#5160]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Got disconnected from server.
2. Logged into server.
3. Two of my stockpiles were ontop of each other.
4. Move a pile of any resource in the stock pile into the other stockpile that is ontop of it and the resources duplicate indefinitely.

**Expected behavior:**
Two stockpiles should never be allowed to be ontop of each other. When they overlap in any way, blocks get duplicated.

**Actual behavior:**
Stockpiles were ontop of each other and allowed me to duplicate my resources.

**Comment by MarjieAVolk** [comment]
This sounds like something that would happen when the server crashes and is reloaded - Did the server go down, in addition to you disconnecting?

**Comment by Trenix** [comment]
Yes the server went down.

**Comment by metachronism** [comment]
closing as dupe of #5090
