### ISSUE TITLE
USER ISSUE: Server Filter

### ISSUE THREAD

**Issue by brandenthomas** [StrangeLoopGames/EcoIssues#5162]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Try to find a server wait an hour for the list to load spend several hours trying to find a server. 		

**Expected behavior:**
Use filters to find the type of server your looking for. Day 1 server for example with more then 5 active people.	

**Actual behavior:**
Dont find a good server. get frusterated spending all day trying ot find one.

**Comment by MarjieAVolk** [comment]
I am planning to work on improving this window soon.

**Comment by LiaungYip** [comment]
Wanted: Sort by number of active trades, laws, contracts. (These values are a good meter-stick for how seriously a server takes the "Economy" aspect of Eco.)

**Comment by MarjieAVolk** [comment]
This will be much improved in 7.4
