### ISSUE TITLE
USER ISSUE: Picking up underwater plants will create a block of water

### ISSUE THREAD

**Issue by Skelun** [StrangeLoopGames/EcoIssues#5164]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Go underwater
2. Pick a plant

**Expected behavior:**
No block of water

**Actual behavior:**
Picking up an underwater plant will creat a block of water

Also, if you open-up the Report a Bug window, the screen will lose its blueish color, even if you are still underwater

**Comment by D3nnis3n** [comment]
Seems logical that the plant is replaced by flowing Water. This is exactly what i would expect

**Comment by MarjieAVolk** [comment]
Looks like what happens now is that a strange looking absence of water appears briefly, and then is filled in by regular water.

**Comment by craig-jong** [comment]
Yea, this is basically intended. I'm going to close this.
