### ISSUE TITLE
USER ISSUE: Stuck in storckpile

### ISSUE THREAD

**Issue by sanegaming** [StrangeLoopGames/EcoIssues#5166]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. place stock pile
2. stand on edge and fill full of items

**Expected behavior:**
placed items on your feet kinda, causing you to not be able to move

**Actual behavior:**
Made it so i can't move, and disconnect didnt fix it either

**Comment by UnknownViper** [comment]
Known issue - learn not to stand in stockpiles while placing items there. ;) The same can happen if you build in the same spot where you're standing.
Should it happen you can always use /unstuck.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5122

You will have to use /unstuck to get out for now.  We are not sure how we want to address this yet.
