### ISSUE TITLE
USER ISSUE: Wood Pulp Crate not accepting Wood Pulp

### ISSUE THREAD

**Issue by AyeeAyeeRon** [StrangeLoopGames/EcoIssues#5167]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Open Wood Pulp Crate
Try to put in Wood Pulp

**Expected behavior:**
Accepted Wood Pulp

**Actual behavior:**
Doesn't accept Wood Pulp

**Comment by MarjieAVolk** [comment]
This is a mod item, you will need to talk to the mod author.
