### ISSUE TITLE
USER ISSUE: Flying woodcart

### ISSUE THREAD

**Issue by Gaokin** [StrangeLoopGames/EcoIssues#5169]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
When I use my woodcart near my factory, it always fly or teleport across the map 

**Expected behavior:**
My woodcart shouldn't moove

**Actual behavior:**
My woodcart flies/teleports far away

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4991
