### ISSUE TITLE
SUGGESTION: More Infrastructure

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5184]
I'd like to See plenty of new infrastructure in the future.

For example i would like to have a player satisfying electricity needs centralised for the whole world or at least districts on big worlds. Like in real life. Seems not possible now and would need electricity cables.

Water for Machines and treatment of Dirty Water seems nice too.

Maybe even Gas?

Conveyor belts for linking of bigger Destinations, but not as big as with Pipes in minecraft would also be a nice Addition for low-mid Range Transport, carts als vehicles being mid-high Range Transport und eventually Trains and ships for high Range Transport.

**Comment by MarjieAVolk** [comment]
Buying and selling electricity sounds awesome

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#226
