### ISSUE TITLE
USER ISSUE: Waypoints 

### ISSUE THREAD

**Issue by legenmastermen** [StrangeLoopGames/EcoIssues#5185]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
make something with distance calculate. It makes me runing over the planet, but im am stonding within 50 m away

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5056
