### ISSUE TITLE
USER ISSUE: Cant connect to my server

### ISSUE THREAD

**Issue by Boqwe** [StrangeLoopGames/EcoIssues#5188]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I press continue to come to my "server" and it just tabs out and i cant come in. (also i can join other servers.)

**Expected behavior:**
JUst got me in the game

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Since you are tabbed out, is a firewall or antivirus software blocking the game?

**Comment by Boqwe** [comment]
I checked in my windows defender and it was not blocked, i have played a few days as well and the problem came today.

**Comment by MarjieAVolk** [comment]
Okay.  You can also try deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO

**Comment by MarjieAVolk** [comment]
If that doesn't work, send me any log files in '[...]\steamapps\common\Eco Server'.  Possibly your save can't be loaded.

**Comment by Boqwe** [comment]
Do you want me to delete the ECO folder? C:\Users\Acer\AppData\LocalLow\Strange Loop Games\Eco

**Comment by MarjieAVolk** [comment]
Yeah - It will only delete local config and temporary files, such as the last server you connected to, and your preferences for which windows are open.

**Comment by MarjieAVolk** [comment]
Did that help you?

**Comment by MarjieAVolk** [comment]
Closing due to no response.
