### ISSUE TITLE
USER ISSUE: Entering world!!!

### ISSUE THREAD

**Issue by Malenkei** [StrangeLoopGames/EcoIssues#5190]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1.Fell under the texture. 2.Leave the game. 3.When you log in, it says "Entering world" and nothing happens!!!

**Expected behavior:**
Help!!! What to do? 

**Actual behavior:**
Entering world! Nothing changes with a long wait time!!!

**Comment by MarjieAVolk** [comment]
Are you joining your own server, or someone else's?  Are other people able to join this server?

**Comment by Malenkei** [comment]
Server name: "EN-TOPSERVER-Eco"
The server of someone else. At the moment it is restarted.
Anyone can join who want.

**Comment by MarjieAVolk** [comment]
Okay, so it's something specific to you.  Have you restarted the game?  You can also try deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO

**Comment by Malenkei** [comment]
Server name:  "RU-TOPSERVER-Eco"
Here is the link http://188.134.14.156:3001/index.html if it helps.

**Comment by Malenkei** [comment]
And my achievements will be lost?

**Comment by MarjieAVolk** [comment]
No, nothing will be lost from deleting that folder, other than some of your local preferences, such as the Continue button state and which windows you had open.

**Comment by Malenkei** [comment]
I tried to reboot. not help! The coordinates I fell off the planet! coordinates are approximate -2000000000 -2000000000 
I try to contact the administrator of the server.

**Comment by MarjieAVolk** [comment]
So you tried deleting the folder like I suggested?  If you are still having trouble, send me your log file right after you see the problem: 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by MarjieAVolk** [comment]
Closing due to no response.
