### ISSUE TITLE
/setpowercost does not persist through server restart

### ISSUE THREAD

**Issue by Yorkforce** [StrangeLoopGames/EcoIssues#5191]
As per title, when using the /setpowercost command, the changes do not persist through a server restart and any lights/items revert back to thier default requirement values.

**Comment by Huntermeign** [comment]
Neither does setting the skillpoint gain multiplier if thats relevant

**Comment by WeaselDog** [comment]
Hey sorry for the late response. This is a developer command now and as it is intended for testing purposes.
