### ISSUE TITLE
USER ISSUE: keine Verbindung zum Webserver Plugin

### ISSUE THREAD

**Issue by Crazzyred** [StrangeLoopGames/EcoIssues#5192]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
ich kann keine verbingung mehr aufbauen zu meinem spiel, mehrfaches deinstallieren hat nicht geholfen

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Was meinst du mit dem Webserver Plugin?

Für die Verbindung fehlgeschlagen Problem, hier sind ein paar Dinge, die Sie versuchen können:

* Löschen des Ordners C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Deaktivieren Sie vorübergehend Ihre Firewall und / oder Antivirus-Software
* Wenn diese nicht funktionieren, sende mir irgendwelche Log-Dateien in '[...]\steamapps\common\Eco Server'

English:
What do you mean about the Webserver Plugin?

For the connection failed problem, here are a couple of things you can try:

* Deleting the folder C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'

**Comment by Crazzyred** [comment]
Hab alles ausprobiert das ist die einzige Log-Datai die es gibt 

Eco Log Session from 26.02.2018 03:06:45
Eco Server 0.7.1.2 beta
Server Initialization... 
Starting ModKitPlugin... 
Loading mods... 
Initializing items... 
Initializing skills... 
Starting NetworkManager... 
Starting WorldGeneratorPlugin... 
Starting StorageManager... 
Starting GameplayStatsPlugin... 
Starting WorldPlugin... 
Starting StatDatabase... 
Loading World... 
Converting world to new format... 
Initializing world... 
Starting TimePlugin... 
Starting ReputationPlugin... 
Starting PlayerHousingManager... 
Starting UserManager... 
Initializing inventories... 
Starting EcoObjectManager... 
Starting ControllerManager... 
Starting ChatServer... 
Starting EcoSim... 
Starting BackupPlugin... 
Starting PropertyManager... 
Starting DisasterPlugin... 
Starting DifficultySettings... 
Starting WirePlugin... 
Starting MinimapManager... 
Loading Disasters... 
Loading Plants... 
Initializing plants... 
Starting RouteProbingPlugin... 
Loading RouteProbing... 
Starting WorldLayerManager... 
Loading Layers... 
Initializing world layers... 
Starting EconomyTracker... 
Starting WorldObjectManager... 
Starting EconomyPlugin... 
Starting RoomPlugin... 
Starting ObjectivePlugin... 
Starting Legislation... 
Starting WebServerPlugin... 
Failed to start Webserver: Ein Aufrufziel hat einen Ausnahmefehler verursacht.
Starting DiscordPlugin... 
Initializing WorldGeneratorPlugin... 
Initializing WorldObjectManager... 
Initializing RoomPlugin... 
Ticking... 
Compressing... 
Saving world... 
Server Initialization finished in 41.233,4ms

**Comment by Crazzyred** [comment]
Achso wenn beim laden "starting WebServerPlugin..." steht bricht die verbindung ab

**Comment by Hexeran** [comment]
Hab mir das spiel heute gekauft und habe das selbe Problem.
Hab eine neue Welt erstellt wollte joinen und dann schmeißt er mich auf den destop und ist im hauptmenu.
Das selbe problem hab ich wenn ich bei Steam ein server erstellen will, erlädt bis WebServerPlugin in und sagt dann das er eine Ausnahme bräucht und das programm stürzt ab.
wäre lieb wenn jemand helfen könnte

**Comment by MarjieAVolk** [comment]
Können Sie Ihre .eco Sicherungsdatei senden?

English:
Can you send your .eco save file?

**Comment by Hexeran** [comment]
Wo kann ich diese Datei finden und wie kann ich die senden?

**Comment by Crazzyred** [comment]
ich wollte grad die datei schicken aber es funktioniert leider hier nicht hier wird keine .eco unterstützt kann ich sie ihnen irgendwie anders zusenden?

**Comment by Hexeran** [comment]
Sie können mich bei Steam adden dann könnte ich ihnen meine email adresse geben 
Steam Name : Hexeran

**Comment by Crazzyred** [comment]
hab es jetzt als .zip gesendet Hexeran du warst eigendlich nicht gemeint ich meinte MarjieAVolk :)
[Jura.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1764801/Jura.zip)

**Comment by Hexeran** [comment]
oh entschuldigung 
da hab ich was verwechselt

**Comment by MarjieAVolk** [comment]
@Hexeran Speichern von Dateien sind in '[...]\steamapps\common\Eco Server\Storage'

**Comment by MarjieAVolk** [comment]
@Crazzyred Ich konnte Ihre Sicherungsdatei laden. Ich vermute also, dass auf Ihrem Computer etwas nicht stimmt.

English:
I was able to load your save file.  So I would guess there is something wrong on your computer.

**Comment by MarjieAVolk** [comment]
Haben Sie Crash-Dump-Dateien von Ihrem Server?

English:
Do you have any crash dump files from your server?

**Comment by Hexeran** [comment]
Bei mir steht auch das

[01:04] Eco Server 0.7.1.2 beta
[01:04] Server Initialization...
[01:04] Starting ModKitPlugin... Finished in 3.184,5ms
[01:05] Loading mods... Finished in 10,7ms
[01:05] Initializing items... Finished in 2.630,4ms
[01:08] Initializing skills... Finished in 116,7ms
[01:08] Starting NetworkManager... Finished in 35,8ms
[01:08] Starting StorageManager... Finished in 3.232,5ms
[01:08] Starting GameplayStatsPlugin... Finished in 0,3ms
[01:08] Starting WorldGeneratorPlugin... Finished in 79,6ms
[01:11] Starting StatDatabase... Finished in 0,4ms
[01:11] Starting WorldPlugin... Finished in 31,0ms
[01:11] Initializing world... Finished in 3,2ms
[01:11] Starting TimePlugin... Finished in 5,6ms
[01:11] Starting ReputationPlugin... Finished in 2,6ms
[01:11] Starting PlayerHousingManager... Finished in 1,2ms
[01:11] Starting UserManager... Finished in 47,2ms
[01:11] Initializing inventories... Finished in 22,5ms
[01:11] Starting EcoObjectManager... Finished in 1,1ms
[01:11] Starting ControllerManager... Finished in 636,6ms
[01:11] Starting PropertyManager... Finished in 37,1ms
[01:11] Starting ChatServer... Finished in 51,8ms
[01:11] Starting EcoSim... Finished in 541,0ms
[01:11] Starting MinimapManager... Finished in 11,2ms
[01:11] Starting DisasterPlugin... Finished in 10,9ms
[01:11] Starting BackupPlugin... Finished in 3,2ms
[01:11] Starting WirePlugin... Finished in 0,6ms
[01:11] Starting DifficultySettings... Finished in 7,2ms
[01:11] Initializing plants... Finished in 54,6ms
[01:12] Starting RouteProbingPlugin... Finished in 7,9ms
[01:12] Starting WorldLayerManager... Finished in 18,4ms
[01:12] Starting EconomyTracker... Finished in 3,8ms
[01:12] Starting WorldObjectManager... Finished in 40,4ms
[01:12] Starting EconomyPlugin... Finished in 21,5ms
[01:12] Starting RoomPlugin... Finished in 13,3ms
[01:12] Starting ObjectivePlugin... Finished in 12,6ms
[01:12] Starting Legislation... Finished in 223,4ms
[01:12] Starting WebServerPlugin...

Unbehandelte Ausnahme: System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Runtime.InteropServices.SEHException: Eine externe Komponente hat eine Ausnahme ausgelöst.
   bei System.Net.UnsafeNclNativeMethods.SetFileCompletionNotificationModes(CriticalHandle handle, FileCompletionNotificationModes modes)
   bei System.Net.HttpListener.CreateRequestQueueHandle()
   bei System.Net.HttpListener.Start()
   bei Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   bei Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   bei Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   bei Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   bei Eco.Webserver.WebServer.Init(Int32 port)
   bei Eco.WebServer.WebServerPlugin.Init()
   bei Eco.WebServer.WebServerPlugin..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager..ctor()
   bei Eco.Server.Startup.Start(String[] args)
   bei Eco.Server.MainClass.Main(String[] args)

**Comment by Hexeran** [comment]
ja das ist das selbe problem wie bei mir

Yes this is the same Problem by me

**Comment by MarjieAVolk** [comment]
Noch ein paar Fragen: Haben Sie den Port für Ihren Webserver geändert? Sind Sie sicher, dass der Port, den Sie für den Webserver verwenden, nicht verwendet wird? (Sie können die Network.eco Konfigurationsdatei einchecken)

A couple more questions: Have you changed the port for your web server?  And also, are you sure that the port you are using for the web server is not in use?  (You can check in the Network.eco config file)

**Comment by Hexeran** [comment]
Ich hatte noch nie einen server aufgemacht das ich das spiel seit gestern besitze und nicht einmal gespielt habe

**Comment by Mauxschter** [comment]
One Question.
You said that i can find the .log file under the path '[...]\steamapps\common\Eco Server'

But the path i needed to find the .log file was actually this '[...]\steamapps\common\Eco\Eco_Data\Server\Logs'

So what if the Path is for some (unknown) reason another one then in the English Version? (Im from Germany)

**Comment by Hexeran** [comment]
Hier mein .eco datei und mein Dump ordner
[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1771943/Dump.zip)


[welt 1.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1771935/welt.1.zip)

**Comment by MarjieAVolk** [comment]
@Mauxschter Thanks for letting me know, it's possible different machines might do different things, hard to keep track of them all.

@Hexeran Ich konnte Ihre Sicherungsdatei laden. Es scheint also, dass Ihre Sicherungsdatei nicht das Problem ist. 

@Hexeran @Crazzyred Vielleicht kannst du die Option "Integrität von Spieldateien prüfen" von dampf testen? Sie könnten auch versuchen, den Webserver-Port in Network.eco in etwas anderes zu ändern. Vielleicht wird dieser Port auf Ihrem Computer verwendet.

I was able to load your save file.  So it seems your save file is not the issue.

Maybe try steam's 'validate integrity of game files' option?  You could also try changing the webserver port in Network.eco to something else.  Maybe that port is being used on your computer.

**Comment by Mauxschter** [comment]
I tried but it doesnt actually work

**Comment by Mauxschter** [comment]
Propably it seems to work only sometimes so maybe the webserver port isn't the Problem

**Comment by Crazzyred** [comment]
ich hab jetzt endlich den port gefunden 
{
  "PublicServer": false,
  "Password": "",
  "IPAddress": "Any",
  "GameServerPort": 3000,
  "WebServerPort": 3001,
  "DetectNAT": true,
  "Rate": 10,
  "ServerBrowserService": "https://ecoauth.strangeloopgames.com/game"
}

in was soll ich den denn ändern ich hab in meinem router schon eine ausnahme für beide ports gemacht aber es funktioniert immer noch nicht..

**Comment by Mauxschter** [comment]
@Crazzyred habe es schon mit mehreren Ports probiert und es funktioniert auch nicht.

Ich vermute das Problem ist, dass immer wenn das Spiel minimiert normalerweise ein Fenster von Windows erscheinen sollte was nach dem Recht fragt, Eco auf ein Netzwerk zugreifen zu lassen. Da dieses Fenster nicht erscheint kommt bei uns diese Fehlermeldung.  (Reine Vermutung)

**Comment by Crazzyred** [comment]
@Mauxschter jetzt ist nur die frage wie man das behebt ^^

**Comment by MarjieAVolk** [comment]
Nun, wenn das das Problem ist - Haben Sie versucht, das Spiel als Administrator zu betreiben? Oder haben Sie versucht, Ihre Firewall oder Antivirensoftware zu deaktivieren?

---------

Well, if that is the problem - Have you tried running the game as an administrator?  Or have you tried disabling your firewall or antivirus software?

**Comment by Crazzyred** [comment]
ja alles schon probiert, ich hab keine ahnung mehr an was es liegen könnte und wie ich es behebe aber solangsam nervt es echt weil ich geld für ein spiel ausgegeben habe was ich grad mal einen Abend spielen konnte....

**Comment by Mauxschter** [comment]
I also tried to execute the .exe as an Administrator, but then, when the game starts,  you have to Login with a strangeloop account.

**Comment by Luicetarro** [comment]
I'm coming over from my topic to keep this together.

Allright, same issue here. On my widsows 10-computer, the game will execute until webserverplugin and stop, lose it's focus, just to return again and show the screen for the worlds we're trying to build/copied over.

Things I've tried so far:

- Deactivating virus-scanner and making an exeption for the eco-files
- Deactivating windows firewall/defender and add exeptions for the eco-files
- Lowering/raising the security-level in the usersettings
- Testing it with all securuty down. No virus scanner, no firewall, security lowered to minimum
- Installed the files from the developers-website, running those as administrator
- Checked the integrity of the windows-files, no issues found
- Checked the installation for .net 4 and 4.5, running a diagnosis-programm for those as well
- Checked for a dump-file, none were found. All I have a two logfiles from connecting with a premade server
- Checked the integrity of the files via steam
- Reverting the installation to an older version
- Checked for the ports, both are available
- Modified ports for the eco-files in it's config
- Installing the game on my windows 8.1-computer. Everything is running fine there.
- Copying the files for a generated world from my 8.1-computer to the 10-computer, attempting to join on a premade world

My windows 8.1-computer was asking for permission to change some values on my computer twice, while it was running the webserverplugin. On my windows 10-computer he did that once.

Hopefully we can narrow it down what might cause the issue on the windows 10-computer, since I guess Mauxschter and Crazzyred are running windows 10 as well.

**Comment by GophTheGreat** [comment]
+1:

yesterday i wrote with pam via discord to solve a solution for my 
problem. she said, i should write with one of the dev´s

here my problem:

i cant start a server via 
D:\SteamLibrary\steamapps\common\Eco\Eco_Data\Server because windows 
said: ecoserver dosent work anymore (see screenshot 1) i start it as an 
admin.

if i start a new generated world via the game gui, game said: connection 
failed. (see screenshot 2)

always i start a verify my files on steam, steam found two corrupted 
files, always!

pam told me alot, but nothing worked.

please look at my shots and give me a reply
![screenshot2](https://user-images.githubusercontent.com/13459026/37440258-fbddc62c-279f-11e8-9926-01d7ae48060b.jpg)
![screenshot1](https://user-images.githubusercontent.com/13459026/37440259-fc00c85c-279f-11e8-96a7-385c7fd9aa4a.JPG)
[output_log (3).txt](https://github.com/StrangeLoopGames/EcoIssues/files/1813742/output_log.3.txt)

**Comment by Luicetarro** [comment]
So atm we have 4 Germans with the very same issue and at least two of them using Win10. Coincedence? Or is something up with the German version of Win10, related to that issue?

**Comment by MarjieAVolk** [comment]
It is possible that the locale is related, we had other locale issues before.

**Comment by Luicetarro** [comment]
I'm willing to act as guinea pig for field tests, if it would help you in any way. Just gimme a call how we're able to do that and we'll get that sucker out of your code.

I have a suitable solution for me in the meanwhile by setting up a local server on my win8 for my wife to connect with the win10, so it's not a pressing matter for me atm. But others have that issue, so I'm trying to help the best I can.

**Comment by metachronism** [comment]
Can any of you give the latest staging build a try, and see if that resolves any of your issues?  We've updated the various plugins to the latest version in an attempt to fix.

@Luicetarro @Mauxschter @Crazzyred @Hexeran

**Comment by Luicetarro** [comment]
I'm firing up that win10 and update the client. Will report back in a few here.

**Comment by Mauxschter** [comment]
I tried to start a world right after the update and it worked, but im not sure if the Problem is fixed or if ots just live befire so it starts only sometimes

**Comment by Luicetarro** [comment]
I'm currently still crashing, but that may as well be something easy, related to something currently not in my mind. Dump says something about writing into protected memory. Started steam as administrator, still no prevail.

I'kk include the sump, maybe it's a common thing and I'm too tired to find the fix right away. But your update did something, that's for sure. The client does act different now.

> --BEGIN DUMP--
> Dump Time
> 03/16/2018 23:24:08
> 
> Exception
> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.AccessViolationException: Es wurde versucht, im geschÃ¼tzten Speicher zu lesen oder zu schreiben. Dies ist hÃ¤ufig ein Hinweis darauf, dass anderer Speicher beschÃ¤digt ist.
>    bei System.Net.UnsafeNclNativeMethods.SetFileCompletionNotificationModes(CriticalHandle handle, FileCompletionNotificationModes modes)
>    bei System.Net.HttpListener.CreateRequestQueueHandle()
>    bei System.Net.HttpListener.Start()
>    bei Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
>    bei Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
>    --- Ende der internen AusnahmestapelÃ¼berwachung ---
>    bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    bei Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
>    bei Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
>    bei Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
>    bei Eco.Webserver.WebServer.Init(Int32 port)
>    bei Eco.WebServer.WebServerPlugin.Init()
>    bei Eco.WebServer.WebServerPlugin..ctor()
>    --- Ende der internen AusnahmestapelÃ¼berwachung ---
>    bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
>    bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
>    bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
>    bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
>    bei System.Activator.CreateInstance(Type type, Object[] args)
>    bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
>    bei Eco.Server.PluginManager..ctor()
>    bei Eco.Server.Startup.Start(String[] args)
>    bei Eco.Server.MainClass.Main(String[] args)
> 
> Inner Exception
> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.AccessViolationException: Es wurde versucht, im geschÃ¼tzten Speicher zu lesen oder zu schreiben. Dies ist hÃ¤ufig ein Hinweis darauf, dass anderer Speicher beschÃ¤digt ist.
>    bei System.Net.UnsafeNclNativeMethods.SetFileCompletionNotificationModes(CriticalHandle handle, FileCompletionNotificationModes modes)
>    bei System.Net.HttpListener.CreateRequestQueueHandle()
>    bei System.Net.HttpListener.Start()
>    bei Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
>    bei Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
>    --- Ende der internen AusnahmestapelÃ¼berwachung ---
>    bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    bei Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
>    bei Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
>    bei Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
>    bei Eco.Webserver.WebServer.Init(Int32 port)
>    bei Eco.WebServer.WebServerPlugin.Init()
>    bei Eco.WebServer.WebServerPlugin..ctor()
>    --- Ende der internen AusnahmestapelÃ¼berwachung ---
>    bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
>    bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
>    bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
>    bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
>    bei System.Activator.CreateInstance(Type type, Object[] args)
>    bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
>    bei Eco.Server.PluginManager..ctor()
>    bei Eco.Server.Startup.Start(String[] args)
>    bei Eco.Server.MainClass.Main(String[] args)
> 
> --END DUMP--

**Comment by metachronism** [comment]
this is definitely a hardware problem, or a problem with a 3rd party app mangling with memory it shouldnt.  as is, something we can't really fix
