### ISSUE TITLE
USER ISSUE: Can´t join my friends game

### ISSUE THREAD

**Issue by peoplebasti** [StrangeLoopGames/EcoIssues#5193]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Start the Game and try to join my friend.

**Expected behavior:**
That i can join my friends game

**Actual behavior:**
Try to join and then i got the Error.

**Comment by MarjieAVolk** [comment]
What error message did you see?  Just "Connection failed"?  Or did you see anything else?  Can you connect to other games?

There are a couple of things you can try as a workaround:

* Deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Try connecting directly by entering the server's IP address in the 'Join' screen
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server' and 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'
