### ISSUE TITLE
BSON recycling issue causing a crash

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#5196]
So looks like ClientUpdate is creating a bson with updated objects
one of those objects is the WorldChunkGrid
It's sending an array 'chunks'
And one of the elements in the chunks array is not a chunk, but some other ClientUpdate bson.
I wasnt able to track it down further, but perhaps something now releasing the ClientUpdate bson

We should add asserts and mode to detect errors like this.  Very easy for code to hold onto a BSON undetected. For example, when we recycle a bson set a 'destroyed' bool, and then assert that bsons are never destroyed when accessed.

![image](https://user-images.githubusercontent.com/3536496/36755106-04cd7304-1bc0-11e8-89ed-9f7768b6f47f.png)
![image](https://user-images.githubusercontent.com/3536496/36755118-0a78d974-1bc0-11e8-955e-7f87f002a2a6.png)

**Comment by metachronism** [comment]
this was localization
