### ISSUE TITLE
Balancing of Solar Generator and Wind Generator

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5198]
I find it odd the Solar Generator is costing Steel and only produces 500 W while the wind generator is producing 750 watt and only costing iron. It's also smaller. Solar Generators presumably will also only work in sunlight. Why should i choose a solar generator?

**Comment by fillion07** [comment]
Unless there is a Battery Packs attached to the Solar Generator (like Tesla do irl) the power could remain steady day and night (with a power controller).

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#225
