### ISSUE TITLE
After placing, workbenches use fuel without anything in queue. Alpha 4.2

### ISSUE THREAD

**Issue by jhadred** [StrangeLoopGames/EcoIssues#520]
To duplicate:  Build oven. Put a log into fuel.  Timer immediately starts before having anything queued to cook.

**Comment by jhadred** [comment]
Only happens when the oven has never had anything in the queue.     Queue something first, then fuel oven.  After this finishes, the Oven will work normally.

If Oven is moved (picked up and put down, even in the same place) this can occur again.  Do not fuel without putting something in the queue first or the fuel will be used and wasted.

**Comment by jhadred** [comment]
http://ecoforum.strangeloopgames.com/topic/783/powered-benches-always-on-now

**Comment by neutronc** [comment]
We observed that the cement kiln and the blast furnace while in the same room switched power supplies to each other every second. Somne sort of "power connection" between those even while we havent researched electricity yet ?

**Comment by stormoffires** [comment]
this does not always correct itself after the first order, i have burned several stacks of coal feeding a blast furnace, when the order is done after a que for 2+ it seems to keep running.

**Comment by jhadred** [comment]
It does appear that a server restart will cause the workbench to start using fuel as if it had an order, even when nothing is in the queue.   

Workaround:  Do not leave extra fuel in the workbench.  Only use enough to power the current work or remove fuel after order is complete.

**Comment by metachronism** [comment]
power has been fixed considerably for alpha 5
