### ISSUE TITLE
Client side interactions didn't revert blocks

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#5202]
I dug these blocks on Keegan's property, and got notifications that I wasn't allowed to do so.  But they did not reappear.  Logging out and back in reverted it to the expected state.

![image](https://user-images.githubusercontent.com/23460210/36761623-caa75f0e-1bd4-11e8-81ac-ade9428e2288.png)

**Comment by SeanAtr0n** [comment]
Fixed a while back
