### ISSUE TITLE
USER ISSUE: Window-orientation wrong when too close to Stockpile

### ISSUE THREAD

**Issue by gralpli** [StrangeLoopGames/EcoIssues#5204]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Create a Stockpile
2. Create a stone wall to the south (or north) of it with no space in between
3. Add some stone windows to that wall
4. Fill up the Stockpile with e. g. stone

**Expected behavior:**
The contents of the Stockpile should not interfere with its surrounding world.

**Actual behavior:**
The windows are rotated perpendicular to the remaining wall. It looks like the windows were "opened" by step 4. ![Screenshot](https://user-images.githubusercontent.com/25158727/36763558-c6416bea-1c28-11e8-8b7f-488d322efd96.jpg)

**Comment by Conchipedia** [comment]
looks the same problem as this
[Art] Give priority over Building blocks that is next to a stockpile to stop windows turning #3751
