### ISSUE TITLE
USER ISSUE: Cannot skip tutorials

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#5206]
**Version:** 0.7.2.0 beta staging-bc863b4b

i have chosen 3 times to skip all tutorials, they disappear off screen then they just come back again, so i have to complete them to get rid of them. Very annoying if you want to skip them if you have already done them

**Comment by MarjieAVolk** [comment]
I have seen this also.

**Comment by MarjieAVolk** [comment]
@B1sounours says they reappear when you select a tool

**Comment by johnkslg** [comment]
fixed thanks!
