### ISSUE TITLE
USER ISSUE: When Mining Graphics not showing the broken Stone

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#5207]
**Version:** 0.7.2.0 beta staging-bc863b4b

sometimes i can here the stone being broken but it will not update graphically, then i relog and hey presto the stone is broken and on the surface
this all i could see was a solid stone wall and i could here me mining when i logged back in this is what i saw
![snap1859](https://user-images.githubusercontent.com/29383891/36764251-a61dcf70-1c23-11e8-922c-a696888f2dee.png)
and this is where all the stuff appeared (on the surface)
![snap1860](https://user-images.githubusercontent.com/29383891/36764258-b159e0c2-1c23-11e8-84fa-c245babecee5.png)

**Comment by Conchipedia** [comment]
oh and this is Marmot and  with **only** two players online

**Comment by Conchipedia** [comment]
this is the same as this Graphics dont update that they are mined and have to disconnect to let them show again #3469

**Comment by MarjieAVolk** [comment]
Oh yeah... well closing as duplicate then :)
