### ISSUE TITLE
USER ISSUE: World does not load - HANG

### ISSUE THREAD

**Issue by ShotaroKaneda** [StrangeLoopGames/EcoIssues#5214]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Trying to start my last Game.
Hangs at "Starting Gameplay Stats Plugin", then Stops and throws me back to the main screen

**Expected behavior:**
Loaded my Game

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Okay, I don't see any errors here, but it looks like the server didn't load all of the plugins.  Do you have any crash files in '[...]\steamapps\common\Eco Server'?

**Comment by MarjieAVolk** [comment]
Closing due to no response.  It looks like your server is failing to load.  If you can get me the server logs, I can diagnose further.

In the future, we will have better error messages for when the server can't start up, which should make this a lot easier for both of us to debug.
