### ISSUE TITLE
[Suggestion] Paint

### ISSUE THREAD

**Issue by Huntermeign** [StrangeLoopGames/EcoIssues#5216]
Some ideas for paints and how it could be used.

Step one: Making Supplies

- Mortar and Pestle station
- Collect plants or foods to make dyes
- Collect wood pulp and plant fibers to make Resin (or use pitch)
- Distil some resin to make turpentine
- End game stations to mass produce items above

Step two: Making Paints

- Combine dye, resin, and terpentine to make paint.
- Paint can becomes item with durability. Consumed when durability is gone.

Step three: Uses of Products

- Paint walls different colors like in real life.
- Paint furniture
- Paint signs
- Paint powered carts different colors (Since garages will be a thing)
- Change Tailoring Specialization tree to Crafts specialization tree.
- Add Paints specialization under Crafts Tree
- Use dyes in tailoring to change colors of things like Carpets
- Add recipes like cloth canopies, banners, flags, table cloths for tables
- Add recipe for civil engineers to make road paint templates to add painted lines on roads, parking lots, board walks, etc.

Step four: End Result

![home-design](https://user-images.githubusercontent.com/4082137/36790448-e22ff332-1c62-11e8-9e65-864075086ac0.jpg)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#224
