### ISSUE TITLE
USER ISSUE: Get a option to make it fixable

### ISSUE THREAD

**Issue by FearTheMaggi** [StrangeLoopGames/EcoIssues#5217]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
set the world to 1-3 players

**Expected behavior:**
i expected there to be a setting of some sort to be able to chnage how many players can be in a world later

**Actual behavior:**
no option at all.

**Comment by MarjieAVolk** [comment]
Yeah, that setting doesn't actually determine how many players are allowed to enter, only the difficulty balance.  A lot of people are confused about that.  The only thing that determines how many players can enter is the 'Allow friends to join' checkbox.  You may also be seeing this bug: https://github.com/StrangeLoopGames/EcoIssues/issues/3768

You can change how many players are allowed to join by typing /openserverui, going to Users>Config and setting Max Slots.  '-1' is unlimited.
