### ISSUE TITLE
Suggestion for making it easier to deal with trolls

### ISSUE THREAD

**Issue by Spacedestructor** [StrangeLoopGames/EcoIssues#5218]
will i needed to deal a few minutes ago with 4 or 5 trolls on my server i got the idea if its possible to add a delete command like the already existing one just for deled everything that is placed and you currently aim at. So for example if someone on the server place a craft table and start an crafting or do that multiple times with different tables and just want to block the place that an admin that is facing it can enter a command to delete it and if its still active that it's simply just deleted everything from it that is active and remove that thing, no matter if its a crafting place or a door, window or something else. What would make it a lot easier :slightly_smiling_face:

**Comment by Thyriel** [comment]
If you mean that someone is joining a server and trying to block the spawn area: Protect it with property claims

**Comment by Spacedestructor** [comment]
not the spawn area, a random place in the world. the person just go to a random place and place stuff and start craftings just to mace it for me impossible to remove it.

**Comment by MarjieAVolk** [comment]
Oh I didn't realize the dev tool did that, haha.

**Comment by Thyriel** [comment]
That tool should be mentioned in Wiki's command page as an example for /give ;)

**Comment by Spacedestructor** [comment]
i now learned somethig new, thanks for that information :)
