### ISSUE TITLE
/pay command does not work with point values

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5220]
Tried to do this: /pay Name,0.57,Dollar
Said this: You do not have 57 Dollars.

Expected: Transferred 0.57 Dollars.

**Comment by MarjieAVolk** [comment]
I'm guessing this is a localization problem - Is your server on a non-english locale?

**Comment by D3nnis3n** [comment]
The Eco Server is running on a Windows Server 2016 using German Localisation, yes. But i have no set language in Eco. I also tried with "," instead of the "." - but this does not work, as then the command is not recognized, as parameters of commands are seperated with commas. Should fix :)

**Comment by MarjieAVolk** [comment]
Yeah, I am betting this is the problem, it doesn't parse the number correctly because the float parser expects a comma, but our chat system does not allow a comma.

**Comment by D3nnis3n** [comment]
> [StrangeLoopGames/Eco] Pull request opened: #2561 Update Readme.me Requirements
> Public Release Notes:
> 
> Additional Internal Details:
> Got an issue where float.TryParse would fail for "0.1". It was expecting a comma because of the system country settings.
> 
> I thought about fixing every float.TryParse with CultureInfo.InvariantCulture argument, but IMO it is a very fragile fix. Any new code might break if someone forget it.
> I think it's better to put it in the readme so people can make the change themselves.
> At least it will save some headaches for the next p...

I suppose this is the fix for this? What does it mean it will not be fixed everywhere but instead put into the readme? How can the end user fix that? oO

**Comment by Nanders** [comment]
This is fixed in upcoming staging
