### ISSUE TITLE
USER ISSUE: Woodcart Flying into the sky

### ISSUE THREAD

**Issue by GsGxGatekeeper** [StrangeLoopGames/EcoIssues#5224]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I don't really now how to reproduce because it's random im farming stone bring it to the cart go into mine go up and see it flying away sometimes it's trembles a little bit when it wants to fly

**Expected behavior:**
just stand there 	

**Actual behavior:**
Flying to the Moon like Shooting Stars Meme first it was funny but now its annoying 4 woodcarts with iron are lost sometimes i find them near my house

**Comment by GsGxGatekeeper** [comment]
x

**Comment by Huntermeign** [comment]
Repeat of #4149

**Comment by MarjieAVolk** [comment]
Closing as duplicate of #4149
