### ISSUE TITLE
USER ISSUE: 64 bit server in 32 bit game version

### ISSUE THREAD

**Issue by LaneaLucy** [StrangeLoopGames/EcoIssues#5225]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
in the 32 bit game version is a 64 bit server so you cant play the game in singelplayer

**Expected behavior:**

**Actual behavior:**

**Comment by metachronism** [comment]
closing as wont fix;  32 bit client may eventually be deprecated entirely, but a warning message now appears about singleplayer in unsupported versions
