### ISSUE TITLE
USER ISSUE: cant connect to active online server??!!

### ISSUE THREAD

**Issue by zer0ghost** [StrangeLoopGames/EcoIssues#5226]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Duno you should tell me i just tried to connect to active server ...even the server screen its lagy fix the stupid RAM leaks!!! For real now ram leaks and 2-3 FPS in the server screen when got 30+ in fancy settings in game? ROFL

**Expected behavior:**
Rage quit then put bad metascore and awfull comment

**Actual behavior:**
keeping calm thinking the devs are industrius, the game got amazing potential and have recieved allot of love..wont be for long
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
We are working on a number of connection problems.  There are a couple of things you can try as a workaround:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Try connecting directly by entering the server's IP address in the 'Join' screen
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server' and 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'
