### ISSUE TITLE
USER ISSUE: Rock raining

### ISSUE THREAD

**Issue by NytoO** [StrangeLoopGames/EcoIssues#5227]
**Version:** 0.7.1.2 beta
![rock raining](https://user-images.githubusercontent.com/36629711/36800860-d0c377ec-1cb0-11e8-90f5-186d5e71e233.gif)

**Comment by NytoO** [comment]
A network issue is happening, we ve restart the game and ....

**Comment by Huntermeign** [comment]
I see this happen when rocks land on stockpiles sometimes. 
Not sure if thats the cause or not

**Comment by D3nnis3n** [comment]
Happened to us after we used the Excavator to remove stone and let the stone fall down on the ground, some stones were then raining from above until restart.

**Comment by SeanAtr0n** [comment]
fixed 7.2
