### ISSUE TITLE
Petroleum Crafting Time

### ISSUE THREAD

**Issue by ddearing** [StrangeLoopGames/EcoIssues#5228]
The crafting time of petroleum from a pumpjack appears to have an inverse relationship to what is expected.

A block reporting 6.87 oil results in a 8m25s craft time.
A block with 16.43 oil resulted in a nearly 20 minute craft time.

If this is the intended behavior, then the "oil" world layer is confusing, as it's representing the best spots to pump oil as purple, and the worst spots in white/yellow which is the opposite value representation of every other yield graph.

**Comment by Huntermeign** [comment]
Yeah a map key would be helpful as well to determine what color means what on a map

**Comment by D3nnis3n** [comment]
How can you see the value of oil? I only see yellow an red colors and dunno which one is better.

**Comment by D3nnis3n** [comment]
Thank you two!

**Comment by Thineboot** [comment]
Tested in 0.7.2.5 on 27th or 28th:
yellow was 3:20 for 10 barrels, violet was 7:00

Tested in 0.7.3.1: colors reversed

![ecooilhigh](https://user-images.githubusercontent.com/4364842/38334866-dd479a9e-385c-11e8-8a24-31f80e2f1b48.png)
![ecooillow](https://user-images.githubusercontent.com/4364842/38334867-dd644c7a-385c-11e8-9485-f2d9b4e32501.png)

**Comment by elfl0rd** [comment]
Hm... now they looks as intended.
