### ISSUE TITLE
USER ISSUE: No longer my cart

### ISSUE THREAD

**Issue by Spaceferret42** [StrangeLoopGames/EcoIssues#5229]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Crash a cart or run out of fuel on someones property other then yours or unclaimed

**Expected behavior:**
Be able to add and remove items from fuel storage

**Actual behavior:**
Says not authorized to remove items from that location even though it is still my cart

**Comment by MarjieAVolk** [comment]
Hm, this seems to be working for me.  Is this fixed for you now?

**Comment by MarjieAVolk** [comment]
I think this may have been fixed along with the AuthorizationInventory flag fix.  Going to assume fixed unless I hear otherwise
