### ISSUE TITLE
Crops bugged on Eco Official EU Server 4.2

### ISSUE THREAD

**Issue by PhosphorDragon** [StrangeLoopGames/EcoIssues#523]
Some crops are growing and some aren't. My seed growth skill enables all crops to grow in 8 hours or less seen hear;
![crops grow time](https://cloud.githubusercontent.com/assets/20499560/17063261/477f0730-502e-11e6-9070-2ab8b97eee29.jpg)

So today i got up at 7am and noticed not all my crops had grown so i harvested some and replanted. I was at work 9 hours and when i got back same thing had happened. Seen hear;
![crops 1](https://cloud.githubusercontent.com/assets/20499560/17063172/e988d1ec-502d-11e6-9215-c43d2cc3a8f8.jpg)
The half that hasnt grow is the bit that didnt grow in the morning plus more.
![crops 2](https://cloud.githubusercontent.com/assets/20499560/17063186/f7dd0308-502d-11e6-9b2d-0d59a6cc74fb.jpg)

allso entire rows havent grown. left is berry's and right is bulbs.
![crops 4](https://cloud.githubusercontent.com/assets/20499560/17063232/2b09112c-502e-11e6-9421-4d918c868c38.jpg)

Also when i try to dig up the seeds they don't disappear and when i put the soil back they stay there  and cannot be hoed .
![crops 3](https://cloud.githubusercontent.com/assets/20499560/17063391/ed4a0db8-502e-11e6-99e6-2dc44f082fac.jpg)

This maybe how its supposed to work now but in 4.1 everything grew fine within the time stated.

**Comment by mariowenig** [comment]
There currently is a growth bug, if you manage to not crash your server it should grow fine. If the server does crash the grow time gets reset. This is being patched already. We have the same issue on the dev server, none of our crops have grown since beginning (2d) since there are always crashes with higher pop servers.

Link here:
https://github.com/StrangeLoopGames/EcoIssues/issues/518

**Comment by PhosphorDragon** [comment]
Ok glad its known thanks for the quick response.

**Comment by mariowenig** [comment]
Np, as long as you dont crash your server (assuming you are on a private) then you should be fine. Currently easiest way to crash server from what we have discovered is making order in short succession before inventory items are removed from previous order made. Watch out for that.

**Comment by PhosphorDragon** [comment]
I'm on the Eco Official EU Server 4.2 and theirs a few active players all in different time zones so hopefully they wont go mad on orders. I think i will just increase the growth time of my seeds a far a possible hopefully that will increase the odds of them growing before a crash.
Hope you guys can fix this issue asap as we're all desperate for food and most of our plants are extinct in the wild.

**Comment by mariowenig** [comment]
Chat with @noblackthunder, he is the server admin on EU Official. One of the SLG Employees is taking care of our server and fixing it up. noblackthunder can likely get info from SLG on how to fix it.

**Comment by metachronism** [comment]
closing this for now due to significant changes in eco system with alpha 5
