### ISSUE TITLE
USER ISSUE: игра

### ISSUE THREAD

**Issue by Grumbumbes** [StrangeLoopGames/EcoIssues#5237]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Could not create save file: E:/ECO v0.7.1.2/Eco_Data/Server/Storage\Grumbumbes.eco already exists
```

**Comment by MarjieAVolk** [comment]
You need to pick a different name for your save file.
