### ISSUE TITLE
USER ISSUE: Connection to Steam Invite failed

### ISSUE THREAD

**Issue by WhAtEvErYoUmEaN** [StrangeLoopGames/EcoIssues#5238]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Get Invite to Join while in Main Menu
2. Accept Invite via Steam Overlay

**Expected behavior:**
It should've connect me to the inviting player's session.

**Actual behavior:**
The following error message popped up:
```Connection Failed```

**Comment by MarjieAVolk** [comment]
Are you able to connect other ways?  For example by entering the server's ip address in the Join window?

**Comment by WhAtEvErYoUmEaN** [comment]
Well.
That's weird. The game just crashed and now i have the corrsponding world saved as favourite in the server browser. I can connect without an issue.

**Comment by MarjieAVolk** [comment]
I don't know about the crash, but yeah I think there are some problems with the steam join features.  The in game join should work better.

**Comment by WhAtEvErYoUmEaN** [comment]
I'm just sorry i can't contribute further to find the issue. But i'm gonna say i'm **very** impressed about the speed of your replies.

**Comment by MarjieAVolk** [comment]
Haha I'm on top of it today :P

**Comment by WhAtEvErYoUmEaN** [comment]
Heads up: I just recieved a Steam invite while not beeing in the game and was greeted with an interesting warning-message from Steam when accepting it that may show the problem in why Steam invites do not work (at least on LAN)
![Connect to localhost](https://user-images.githubusercontent.com/7109098/36915146-f9fc756e-1e4f-11e8-8add-eee4cb502cd4.png)

**Comment by liloso** [comment]
i got the same steam error as you

**Comment by Nanders** [comment]
This should be much improved with the new networking changes
