### ISSUE TITLE
USER ISSUE: Invisible Washboard

### ISSUE THREAD

**Issue by Lagicrus** [StrangeLoopGames/EcoIssues#5239]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Pickup washboard

**Expected behavior:**
It should have looked normal

**Actual behavior:**
Instead it was transparent

https://imgur.com/a/XlDMN

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4318
