### ISSUE TITLE
CO2 goes through walls

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5241]
It should not be possible that CO2 from a machine can go through e.g. brick blocks, a chimney out of pipes should be enforced for it to be working.

**Comment by D3nnis3n** [comment]
Uh. I did consider this as a bug. At least visual.

**Comment by MarjieAVolk** [comment]
If it's a visual bug, can you attach a screenshot?  Maybe I don't understand.

**Comment by D3nnis3n** [comment]
At least - I - consider this a visual bug.

<img width="852" alt="a" src="https://user-images.githubusercontent.com/25908592/36815720-e5c4abfe-1cdb-11e8-98a0-3d2441bf9912.png">
<img width="625" alt="b" src="https://user-images.githubusercontent.com/25908592/36815721-e5fb2738-1cdb-11e8-9d6c-01d7a452582b.png">

**Comment by MarjieAVolk** [comment]
lol What can't you see all the little holes in the brick?

**Comment by D3nnis3n** [comment]
This is the same with concrete, where are no holes.

**Comment by MarjieAVolk** [comment]
I know, I'm just joking :)

**Comment by Thyriel** [comment]
Beside the visual issue: Gameplay wise i don't think it would be a good idea to prevent CO2 going through walls. This would allow abusing it by pumping all generated CO2 underground to prevent it's effect on the environment

**Comment by D3nnis3n** [comment]
No, you don't understand. What i'm suggesting is, that the machine just doesn't work when the chimney has no line-of-sight to the clouds. This would make it impossible to pump CO2 underground.

**Comment by keegan-o** [comment]
We may add further restrictions in the future, but for now I've improved the look visually by adding collision to the particles that come out, so they clump against ceilings etc.
