### ISSUE TITLE
USER ISSUE: Sound FX right ear fuzz

### ISSUE THREAD

**Issue by Dremand** [StrangeLoopGames/EcoIssues#5243]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Just start game

**Expected behavior:**
It should not be fuzzing

**Actual behavior:**
Instead it should have good sound fx

**Comment by MarjieAVolk** [comment]
I don't know much about the sound, but this kind of sounds like you have a problem with your headphones.

**Comment by GophTheGreat** [comment]
Could not reproduce, gonna assume user error.

**Comment by Dremand** [comment]
What's this? Months ago when I was reporting the sound fx of the rain sounding like fuzz? Horrible sound fx. Anyways thanks for getting back to me even though it's a bit late.
________________________________
