### ISSUE TITLE
USER ISSUE: Cactus - Tree - Desert Bug

### ISSUE THREAD

**Issue by Alendrus** [StrangeLoopGames/EcoIssues#5244]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
open map zoom to a desert. cactus shown me as trees

**Expected behavior:**
he shows me  a cactus	

**Actual behavior:**
He shows me a tree

**Comment by GophTheGreat** [comment]
Cacti look like cacti to me. Closing.
