### ISSUE TITLE
Modern Tools don't show a Uses Values

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5250]
All the other Tools show Uses Values - Modern Tools don't.

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/37232967-29fc2ac4-23a6-11e8-8602-3b2c285a5af4.png)
Do you mean the "Uses" value here or something else?

It seems to be appearing fine in the current build. If this problem is still present, please reopen this/clarify.
