### ISSUE TITLE
[SUGGESTION] Dirt Roads should have a speed bonus

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5251]
In my opinion dirt roads should have a speed bonus over normal terrain. Players tend to only place ramps and don't make the dirt roads, as they give no bonus but take away loads of calories. This makes roads hard to see.

I also think that a road that you made with a tool is better than normal terrain in reallife, so it makes sense.

**Comment by MarjieAVolk** [comment]
You know, I still don't know what road efficiency actually does.

**Comment by D3nnis3n** [comment]
You drive faster on those roads. And that's good.

**Comment by D3nnis3n** [comment]
Also, sand should maybe have a lower value of 80%.

**Comment by Thyriel** [comment]
> You drive faster on those roads. And that's good. (And it does work)

I can't confirm that this does work. We did a test with a pretty long stone and dirt road beneath each other but both players where at the same speed. (with and without carts)
Also if you compare it to the ~25% speed bonus of light backpack/running shoes you definitly notice that it's not faster.

**Comment by D3nnis3n** [comment]
Now it get's funny as we did test that too and have directly opposite results.

We found the running Boots to not work - a comparison has shown both persons are walking at the same speed on dirt roads.

The asphalt roads though are making people with carts much faster, but not when they do do not have carts.

Stone roads haven't been tested, we switched from dirt to asphalt. We did also not test light backpacks yet.

**Comment by Thyriel** [comment]
Maybe only asphalt roads actually give a bonus and that's why we got different results ?
Shoes: I've only tested with shoes and backpack, maybe the same here: Bonus only works with both or only bp gives bonus. But they definitly work.

**Comment by OfficialNoms** [comment]
Personally I think stuff like Dirt should offer a 50% Road efficiency, maybe differing if it's got grass or plants there, then stuff like Dirt Roads should offer 80, going up to 100 for stone, and then above that with asphalt and maybe future roads.

**Comment by D3nnis3n** [comment]
In my opinion 100 % efficiency at the moment equals 50% efficiency. It's just unreasonable slow and boring.

**Comment by Thyriel** [comment]
> it's fully irrelevant if you keep it like now or put the efficency down but raise the general speed to double value. 

It's not irrelevant. The speed with running shoes + light backpack is already too high to smoothly gather / replant a big field so increasing the default speed would not be good for everyone

**Comment by D3nnis3n** [comment]
Also, Street Bonuses do NOT apply to People on foot. We tested that.

Gesendet von Mail für Windows 10

Von: Thyriel
Gesendet: Donnerstag, 1. März 2018 15:11
An: StrangeLoopGames/EcoIssues
Cc: D3nnis3n; Author
Betreff: Re: [StrangeLoopGames/EcoIssues] [SUGGESTION] Dirt Roads should havea speed bonus (#5251)

it's fully irrelevant if you keep it like now or put the efficency down but raise the general speed to double value.
It's not irrelevant. The speed with running shoes + light backpack is already too high to smoothly gather / replant a big field so increasing the default speed would not be good for everyone

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#221
