### ISSUE TITLE
USER ISSUE: Successfully Fishing did not add fish into my inventory

### ISSUE THREAD

**Issue by MrBennG** [StrangeLoopGames/EcoIssues#5252]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Successfully reel in a fish
2. Observe that the fish is not in your quickbar or backpack
3. disconnect and reconnect to the server
4. Observe fish is now in inventory

**Expected behavior:**
After reeling in a fish it should have been added to my inventory	

**Actual behavior:**
Fish did not appear in my inventory until I disconnected and reconnect to the server

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588

This should be fixed on the current staging release.

**Comment by MrBennG** [comment]
Thanks for the prompt response!
