### ISSUE TITLE
USER ISSUE: Breaking Coal "Double Stone" trigger no sound

### ISSUE THREAD

**Issue by Skelun** [StrangeLoopGames/EcoIssues#5258]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Break a block of Coal
2. Try to break the "Double Stone" into two pieces

**Expected behavior:**
It does trigger a sound

**Actual behavior:**
It doesn't trigger the "pickaxe breaking stuff" sound

**Comment by Nanders** [comment]
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4454
