### ISSUE TITLE
USER ISSUE: Can't Start New Game 0.7.2.0 beta staging-0f2c018e

### ISSUE THREAD

**Issue by Gilgatex** [StrangeLoopGames/EcoIssues#5259]
**Version:** 0.7.2.0 beta staging-0f2c018e

**Steps to Reproduce:**
Click New
Select Generate New World
Click Start
Confirm New World

**Expected behavior:**
Started a New Game

**Actual behavior:**
Nothing Happens

**Comment by MarjieAVolk** [comment]
Just noticed this myself O.o

**Comment by fwohlfarth** [comment]
Same for Mac version.

**Comment by MarjieAVolk** [comment]
Fixed in staging
