### ISSUE TITLE
USER ISSUE: Collect Hewn Logs task won't finish or close

### ISSUE THREAD

**Issue by Sigrsig** [StrangeLoopGames/EcoIssues#5262]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Place a stockpile next to a workbench
2. make hewn logs
3. Task requests you to add logs to the workbench
4. Tried skipping the task

**Expected behavior:**
- Task Completes when the required logs to finish the task are added/ Task disappears when yes is clicked after trying to skip the task

**Actual behavior:**
Task doesn't complete and doesn't disappear when I tried to skip it

**Comment by johnkslg** [comment]
Verified skipping and completing the tutorial both work.  Perhaps was fixed with other tutorial fixes. Try restarting tutorial and try again? Thank you for the bug report.
