### ISSUE TITLE
Version: Staging Beta 7.2.0 #0f2c018e - Eco.WorldGenerator.PlateauGenerator - Rounding bug in Generate function

### ISSUE THREAD

**Issue by meonester** [StrangeLoopGames/EcoIssues#5264]
Version: Staging Beta 7.2.0 #0f2c018e
There is bug in 'fancy' rounding in Eco.WorldGenerator.PlateauGenerator in Generate function:

```
namespace Eco.WorldGenerator
{
	public class PlateauGenerator
	{
		//...
		public void Generate(Action<float> updateAction)
		{
			int num = (int)((double)(this.settings.Dimensions.x * this.settings.Dimensions.y) * 0.5);
			for (int i= 0; i < num; i++) //...
```
Should be:
```
			int num = (int)((double)(this.settings.Dimensions.x * this.settings.Dimensions.y) + 0.5);
```

**Comment by MarjieAVolk** [comment]
I am not sure if the intention was to round here or not.

**Comment by meonester** [comment]
Sorry, it was kind of obvious for me.
Old version(#0ef2b7d6) looked like this:
```
			int num = this.settings.Dimensions.x * this.settings.Dimensions.y;
```
And this is only line that changed in this class/file in comparison to older version.

**Comment by MarjieAVolk** [comment]
Yeah, I think this was changed intentionally.  Since we decreased the frequency of plateaus and increased their size.

**Comment by meonester** [comment]
Just went through the code and it sure makes seanse with the latest changes in WorldGen config file.
Lol, and i was just thinking to my self how funny it would be if someone transformed  "Off by one" to "off by half". :)
Anyway , I hope I didn't cause too much confusion.
