### ISSUE TITLE
can place several items with signs

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#527]
http://ecoforum.strangeloopgames.com/topic/799/a-possible-bug-with-signs

**Comment by neutronc** [comment]
Happens also With Dirt and Stone Ramps

**Comment by mariowenig** [comment]
Once you combine 2 items like tables, chairs, chest anything even putting them into an inventory and retrieving them has the same result. Not yet tested having 2 faulty stack mixed with a non faulty.
