### ISSUE TITLE
USER ISSUE: stuck

### ISSUE THREAD

**Issue by Area1233** [StrangeLoopGames/EcoIssues#5270]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
stand on corner of stockpile and put logs on stockpile

**Expected behavior:**
logs on stockpile

**Actual behavior:**
stuck on corner of stockpile. reconnect doesn´t help

**Comment by MarjieAVolk** [comment]
You will have to use /unstuck to get out.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4113

**Comment by Area1233** [comment]
thank you ;D
