### ISSUE TITLE
USER ISSUE: Koop Steam

### ISSUE THREAD

**Issue by Neocron970** [StrangeLoopGames/EcoIssues#5272]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**
wir versuchten über steam zu spielen aber dies hat nicht funktioniert und wissen beide nicht warum (bei anderen spielen hat das aber funktionirt)

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Wir arbeiten an einer Reihe von Verbindungsproblemen. Es gibt ein paar Dinge, die Sie als Workaround versuchen können:

* Löschen des Ordners C: \ Benutzer \\ [Benutzername] \ AppData \ LocalLow \ Strange Loop Games \ ECO
* Deaktivieren Sie vorübergehend Ihre Firewall und / oder Antivirus-Software
* Versuchen Sie, die Verbindung direkt herzustellen, indem Sie die IP-Adresse des Servers im Bildschirm "Beitreten" eingeben

------
We are working on a number of connection problems.  There are a couple of things you can try as a workaround:

* Deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Try connecting directly by entering the server's IP address in the 'Join' screen
