### ISSUE TITLE
USER ISSUE: cant start a world

### ISSUE THREAD

**Issue by Fredrigo** [StrangeLoopGames/EcoIssues#5273]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. start a world
2. watch it fail

**Expected behavior:**
started a world

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
We are working on a number of connection problems.  There are a couple of things you can try as a workaround:

* Deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When starting a new world, select 'Generate new'
* Run the server via the EcoServer tool
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server' and 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'
