### ISSUE TITLE
USER ISSUE: Picking up a Log

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5274]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Picking up a Log while having a Scythe in my hands leads to a crash.

**Expected behavior:**
Picked up the Log

**Actual behavior:**
The following error message popped up and the Log got not picked up.
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei TreeEntity.PickupLog(Player player, Guid logID)
   bei TreeEntity.OnActInteract(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668
