### ISSUE TITLE
USER ISSUE: Exception

### ISSUE THREAD

**Issue by EpixXx** [StrangeLoopGames/EcoIssues#5277]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Loss Connection

**Expected behavior:**
Connect proberly

**Actual behavior:**
Error Message: Caught exception: Der Objektverweis wurde nicht auf eine Objekinstanz festgelegt.

**Comment by MarjieAVolk** [comment]
Hey there - unfortunately this message is very hard to debug on its own.  We have made sure to display better error messages for the next release, which will let us start debugging issues like this.

If you have more details about when and why this happens, I may be able to look at it.
