### ISSUE TITLE
USER ISSUE: game not using gpu

### ISSUE THREAD

**Issue by S-man16** [StrangeLoopGames/EcoIssues#5278]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
gpu amd HD 8970m
cpu i7 4700mq
windows 10
all latest drivers
even when force booted with amd catalyst it refuses to use gpu

**Expected behavior:**
used gpu and ran 40-60 fps with some setting tweaks

**Actual behavior:**
the game refuses to run on my gpu opting to instead only use integrated graphics resulting in an abysmal frame rate even  even

**Comment by Troy8878** [comment]
Did you just install your GPU by chance?  I remember having to do some extra configuration after installing my latest GPU on Windows 10.

**Comment by S-man16** [comment]
No it is a laptop so other than some extra ram I added years ago the system
is stock.
 I had a similar issue with gtaV when it was first released but that got
fixed after a few updates. Unfortanatly this issue seams to be common with
other mobile gpus in many games both nvidia and amd, with amd getting the
short end of the stick.
- Shawn

**Comment by metachronism** [comment]
we unfortunately cant do anything about this, its up to the software provider of the GPU switching to add us as a game, we have no ability to do that

**Comment by S-man16** [comment]
Thank you anyways for your communication I really appreciate your team
trying to help with my obscure issue and I will be sure to look into more
of your guy's products in the future
