### ISSUE TITLE
infinite land claim flags

### ISSUE THREAD

**Issue by combatbanana** [StrangeLoopGames/EcoIssues#528]
Glassworking, Baking and Smithing scrolls give land flags regardless if you have already learnt the skill or not

**Comment by mariowenig** [comment]
Could not confirm for Smithing:

Dev server confirmed 4.2 (post growth patch)
-Butchery
-Baking
-Glassworking
-Paper
-Steelworking
-Cement
-Culinary
-ADV Research

All give claims regardless of having learned them.

**Comment by jhadred** [comment]
Possibly related:  When someone on the server has learned the skill from a scroll and your character has not, hovering over many of the scrolls will indicate that "you have already learnt this skill" even if your character actually has not (and it's semi-visible in your skill screen indicating that someone else has learned the skill).  
Will update this if mario updates the list with adv baking & others  (I know that some of the skills said to give more flags do state that it was learned, even it was not).

**Comment by pan7s** [comment]
Please fix!

**Comment by metachronism** [comment]
fixed in alpha 5
