### ISSUE TITLE
USER ISSUE: See through walls

### ISSUE THREAD

**Issue by honux** [StrangeLoopGames/EcoIssues#5286]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Place a brick (or any other) on a wall surrounded by "fixed" blocks

**Expected behavior:**
See the block behind/besides it

**Actual behavior:**
You see through the world

Image:
https://imgur.com/a/dp7PZ

**Comment by keegan-o** [comment]
#4286 Duplicate
