### ISSUE TITLE
invisible dirt to other players

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#5291]
![screenshot_20180301-231844](https://user-images.githubusercontent.com/3536496/36887704-4114a984-1da7-11e8-8ac0-893948914507.png)

**Comment by johnkslg** [comment]
![screenshot_20180301-232213](https://user-images.githubusercontent.com/3536496/36887746-660d6172-1da7-11e8-971d-eb2ef9de791e.png)

**Comment by SeanAtr0n** [comment]
fixed with ^ PR a long time ago
