### ISSUE TITLE
USER ISSUE: Disabled Tab Key

### ISSUE THREAD

**Issue by sceadara** [StrangeLoopGames/EcoIssues#5293]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Press "Tab" to enter Mouse Mode
2. Click "+" to add a new Talk Channel
3. Hit "Esc"
4. Try to enter mouse mode with tab key -> not working

**Expected behavior:**
Tab to enter mouse mode should work 

**Actual behavior:**
Can't enter mouse mode. Have to leave server and join again.

**Comment by MarjieAVolk** [comment]
Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/4115 - I have fixed this issue in the current staging build.
