### ISSUE TITLE
Trample

### ISSUE THREAD

**Issue by ArkenorOakshadow** [StrangeLoopGames/EcoIssues#5294]
Version: 0.7.1.2 beta

Trample propagates outwards affecting squares not trodden on to quite a significant distance, as seen in the TrampleSpread map layer.
It is only tracked in 2 dimensions, so even building a tunnel will still damage the land above it.
It still occurs even if you're in your house walking on crafted floors. This makes it extremely difficult to keep any plants alive near homes, or anywhere where people frequently pass nearby. Such as farms.

The player harms his environment simply by being there, with no obvious way to mitigate or prevent it. The only way to not cause trample damage is to not play, which makes it an overly punishing mechanic in its current implementation.

I propose, at the least, that trample should not occur if you're not standing on dirt, or if you're indoors or underground.

Also, a skill which lets us cause less trample when we walk around might be a nice addition to the skill tree.

![trample](https://user-images.githubusercontent.com/36987604/36895115-a113dc02-1e05-11e8-8efe-246f2c457d2d.png)

**Comment by CompactDisc** [comment]
This is not really a suggestion, more a bug report. Since trample damage surely isn't supposed to happen above ground if you walk in a mine several meters down?

**Comment by MarjieAVolk** [comment]
Tunnels making the top ground become trampled is reported here, by the way: https://github.com/StrangeLoopGames/EcoIssues/issues/5101

**Comment by MarjieAVolk** [comment]
Am leaving this open as a suggestion to decrease the amount trample 'spreads'

**Comment by CompactDisc** [comment]
Ah thanks 👍 Very good, hope to see the change soon, because this is a bit ridiculous =)
I made a stone path between my farms and apparently  I still kill the plants by walking over it.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#219
