### ISSUE TITLE
USER ISSUE: Negative Weight in Cart

### ISSUE THREAD

**Issue by coetomo** [StrangeLoopGames/EcoIssues#5295]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Have a stockpile, cart, and sands.
2. Put 5 Sands in Stockpile, 2 Sands in cart.
3. Try putting the 2 Sands into the 5 Sands from the storage menu.

**Expected behavior:**
2 Sands rejected from stockpile normally (since stockpile can only hold 5 Sands) and return it to cart.

**Actual behavior:**
2 Sands got returned to cart but their weights removed from cart (resulting negative weights)

**Comment by MarjieAVolk** [comment]
Thank you for the detailed repro steps!

**Comment by MarjieAVolk** [comment]
Fixed in 7.3
