### ISSUE TITLE
[CLIENT CRASH] 

### ISSUE THREAD

**Issue by pmeyerson** [StrangeLoopGames/EcoIssues#5296]
First I noticed that after gathering a beet in front of me that the text displayed I got 3-4 beets and/or seeds but the graphic of the beets remained in place in the ground.  I noticed that my backpack and inventory was full.
Then I went to shovel and while shoveling eco.exe completely froze.
https://imgur.com/a/ARMZH
https://pastebin.com/YSbrscHn - crashdump
client file product version 2017.3.0.11139181 ... not sure how to check alpha version, sorry.

**Comment by MarjieAVolk** [comment]
You can see the game version in the bottom left corner of the escape menu.

The dump you showed looks like the server is crashing immediately on startup.  But the scenario you described sounds like it crashed much later.  That is strange.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
```

**Comment by pmeyerson** [comment]
BTW, I just did a 'verify local files' in steam and it downloaded 2 missing/corrupt files.  When I first installed I noticed that my antivirus software (trend micro) threw a bunch of popups about blocking stuff.  I thought I clicked OK to all of them but maybe something got blocked before I setup an exception.  Will see if that helps.

**Comment by MarjieAVolk** [comment]
Closing as it seems like that fixed the problem.
