### ISSUE TITLE
Can't move camera of character once game starts

### ISSUE THREAD

**Issue by mgold** [StrangeLoopGames/EcoIssues#53]
OS X 10.11.3, ECO Alpha-3. My machine is a 13-inch retina MacBook Pro, early 2013, 2.6 GHz i5, 8GB RAM.

When I connect to a server, I can't move the camera or my character. When I connected to worldofeco.net:3000, I got this screen:

![screen shot 2016-01-13 at 9 31 49 pm 2](https://cloud.githubusercontent.com/assets/1191970/12314458/3f066dc6-ba3f-11e5-95c0-5bb1d102543b.png)

The axe animates, I can mouseover the UI and read some info about the tools, but I can't seem to navigate the 3D world at all. I tried 151.80.117.27:3000 ("darkcubes.net"?) and got this:

![screen shot 2016-01-13 at 9 34 31 pm](https://cloud.githubusercontent.com/assets/1191970/12314472/63356062-ba3f-11e5-9314-b976b428c87f.png)

This seems to be a reasonable world, the river animates, but again I couldn't move or navigate. (Ideally players wouldn't start facing a wall, but it's alpha, I get it.)

I considered that maybe the keys I'm trying (arrows, wasd) aren't being received correctly, but I can hit Enter to send messages and typing seems to work normally.

**Comment by metachronism** [comment]
you might be stuck in the ground -
try 
/unstuck
if thats not working, you have to use Tab to hide/show the cursor and toggle mouselook

**Comment by mgold** [comment]
Tab took care of it, thanks!
