### ISSUE TITLE
Serverwatcher using backup creates dupes in carts

### ISSUE THREAD

**Issue by Zenitaa** [StrangeLoopGames/EcoIssues#530]
Stacks that were removed and placed in a workstation, after reboot they exist in both the workstation and cart.

Only 2 crashes so far (System.ArgumentOutOfRangeException, when using a crafting table), but has occurred both times.

Alpha 4.2 hotfixed server, using Serverwatcher to restart after crash with a backup time of 30 mins.

**Comment by mariowenig** [comment]
Guessing general inventory related?
Server crash: 
28 coal in both cart and chest after28 being moved from cart to chest, server crash (unrelated)
![image](https://cloud.githubusercontent.com/assets/10489431/17091767/72cf181a-520b-11e6-9e8a-b37ebf0aa93e.png)

**Comment by noblackthunder** [comment]
Dont think this is tied to the serverwatcher since it is only starting the application like you would almostly

**Comment by noblackthunder** [comment]
also did that dube error happens only on crashes or in general?

**Comment by metachronism** [comment]
this should be mostly fixed in alpha 5
