### ISSUE TITLE
USER ISSUE: Could not create save file

### ISSUE THREAD

**Issue by Sergant1530** [StrangeLoopGames/EcoIssues#5301]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Could not create save file: E:/ECO v0.7.1.2/Eco_Data/Server/Storage\Serg.eco already exists
```

**Comment by MarjieAVolk** [comment]
You already have a save file with that name.  You will need to name it something else.
