### ISSUE TITLE
Ubuntu 17.10 Issues

### ISSUE THREAD

**Issue by davegrix** [StrangeLoopGames/EcoIssues#5304]
I can't start a new game either from steam or by downloading from the website.

On both everything typed is duplicated.

Using the latest beta from the website, I can't login as everything is duplicated, copy / paste duplicates the paste.

From steam I try to start a new game and get the warning this may take a long time, then nothing.

Ubuntu 17.10.1
AMD 270X GPU
48GB Ram

Player.log from steam attached

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/1775827/Player.log)

**Comment by MarjieAVolk** [comment]
Are you playing on staging?  The issue with the 'start' button not doing anything I believe was on staging only, and will be fixed in the next staging build.

The duplicated typing bug is reported here: https://github.com/StrangeLoopGames/EcoIssues/issues/3580

**Comment by davegrix** [comment]
No, this is the steam version

**Comment by MarjieAVolk** [comment]
You can access staging from steam.  But in any case - I'm assuming this is the issue that is fixed in staging now, but if you send me your log file ( 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt') after trying to create a new world, I can verify whether it is the same.

**Comment by davegrix** [comment]
This file doesn't exist on Linux.
.config/unity3d/Strange Loop Games/Eco only has the player.log file which I have attached
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/1776963/Player.log)

I have tried copying the downloaded non staging game from the website and overwriting the downloaded steam files, again, only gets as far as creating a new world but no files are created.

**Comment by MarjieAVolk** [comment]
Ah yes, sorry I forgot about the different operating system.  Thank you - yes, that looks like the same issue.  It will be fixed in the next release.
