### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by GendoIkari** [StrangeLoopGames/EcoIssues#5308]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Join Game
2. Choose a server
3. Connection Fail

**Expected behavior:**
Asking the server password

**Actual behavior:**
Connection fail popup. I know for sure the server is on, the connection is fine, my firewall is okay, I already played online.

**Comment by MarjieAVolk** [comment]
Can you connect to the server directly via ip address?

**Comment by pamduncan** [comment]
The server could be online but the ports might be incorrectly configures or the firewall is blocking - that is the most often cause... the owner can test here http://www.canyouseeme.org or https://www.yougetsignal.com/tools/open-ports/   If you can get to other servers but not that one server and never been on it before chances are its the ports or firewall unless there are other players on it via the internet (not the owner as they are probably local to it)

**Comment by MarjieAVolk** [comment]
Closing due to no response.
