### ISSUE TITLE
Skillbook not giving skill

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#531]
http://ecoforum.strangeloopgames.com/topic/812/skillbooks-don-t-actually-give-the-skill/5

http://ecoforum.strangeloopgames.com/topic/811/can-not-learn-smithing-skill

**Comment by metachronism** [comment]
fixed

**Comment by Nado307** [comment]
We are also having this exact same issue on my server now, i was wondering how you went about solving this issue, all progress has come to a stand still without this skill.

I have tried restarting and regenerating the world/server, neither fixed the issue
Cheers

**Comment by metachronism** [comment]
are you on 4.2?  This is only fixed in the most recent alpha 5.
