### ISSUE TITLE
USER ISSUE: Renaming Chest

### ISSUE THREAD

**Issue by Stixz** [StrangeLoopGames/EcoIssues#5310]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Stack 3 chest one on top of the other. Stand in front of them and rename one. Close the menu.	

**Expected behavior:**
Have the chest renamed and allow me to continue to play.	

**Actual behavior:**
Chest gets renamed, I become stuck in place and can no longer do anything except turn the camera.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115

This is fixed in the current staging build.
