### ISSUE TITLE
USER ISSUE: Error

### ISSUE THREAD

**Issue by Xnetsrac** [StrangeLoopGames/EcoIssues#5314]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
none

**Expected behavior:**

**Actual behavior:**
Caught exception: der Index war außerhalb des Arraybereichs

**Comment by MarjieAVolk** [comment]
I'm sorry, this error message is not enough to debug the issue.  If you can find more detailed error messages in your log files, then I can look at the issue.  Otherwise, in the next release we are sending better error messages on disconnect, so that we can work on issues like this.
