### ISSUE TITLE
USER ISSUE: water system is bad. realy bad.

### ISSUE THREAD

**Issue by SunriZZe** [StrangeLoopGames/EcoIssues#5315]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Try to dig blocks around the water

**Expected behavior:**
Water will fill the space.

**Actual behavior:**
Water turns into a terrible spray. Unrealistic.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4807
