### ISSUE TITLE
Eco Server 0.7.2.0 beta staging-adf7002a - Critical Fail on Dedicated Server Start

### ISSUE THREAD

**Issue by Nashable** [StrangeLoopGames/EcoIssues#5317]
Taken from the console after patching.

> [55:18] Eco Server 0.7.2.0 beta staging-adf7002a
> [55:18] Server Initialization...
> [55:18] Starting ModKitPlugin...
> [55:18] Compiling mods... Finished in 411.3ms
> [55:19] Mods recompiled with errors.
> [55:19] Error in Torch at 45: Partial declarations of 'Eco.Mods.TechTree.TorchItem' must not specify different base classes (CS0263)
> 
> 
> Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error in Torch at 45: Partial declarations of 'Eco.Mods.TechTree.TorchItem' must not specify different base classes (CS0263)
> 
>    at Eco.ModKit.RuntimeCompiler.HandleCompilerError(CompilerResults results)
>    at Eco.ModKit.RuntimeCompiler.LoadOrCompileMods()
>    at Eco.ModKit.ModKitPlugin..ctor(ManualResetEvent doneEvent)
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
>    at System.Activator.CreateInstance(Type type, Object[] args)
>    at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
>    at Eco.Server.PluginManager..ctor()
>    at Eco.Server.Startup.Start(String[] args)
>    at Eco.Server.MainClass.Main(String[] args)

**Comment by Nashable** [comment]
Looks like rolling these two files back fixed the issue and allowed the server to reboot.

[torch.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1777055/torch.zip)

**Comment by MarjieAVolk** [comment]
Think this has been fixed.

**Comment by MarjieAVolk** [comment]
Oh, I think you may actually be having a problem with the 'mods' folder not being regenerated (this can happen even on a server with no mods).  You can try going into the Eco Server installation folder and deleting the "Mods" folder.

**Comment by Nashable** [comment]
Correct, deleting mods also worked. I wonder if the server.exe could rename the mods folder and restart if there was a bad mods build? At least a command line option to make dedicated server management easier.

**Comment by metachronism** [comment]
closing this, best to start clean when updating server builds for this reason
