### ISSUE TITLE
USER ISSUE: Block placed inside player (stuck)

### ISSUE THREAD

**Issue by AndyClausen** [StrangeLoopGames/EcoIssues#5319]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Build an 45 degree wall
2. Jump to set a block on top of wall
3. Spam left click and place a block inside you

**Expected behavior:**
Collision detectors should've gone off there. Are you missing a collision check on between blocks and the player?

**Actual behavior:**
I placed a block inside me and got stuck.

**Comment by SeanAtr0n** [comment]
fixed in 7.2
