### ISSUE TITLE
USER ISSUE: Won't load world on startup.

### ISSUE THREAD

**Issue by Arctr** [StrangeLoopGames/EcoIssues#5320]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Won't load world on startup.
Computer restarted randomly and now can't enter world.

**Expected behavior:**
Load

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server' and also 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

* Deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Run the server via the Eco Server tool
