### ISSUE TITLE
USER ISSUE: Farming issue

### ISSUE THREAD

**Issue by mwarnec2** [StrangeLoopGames/EcoIssues#5321]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. till the ground
2.plant crop		

**Expected behavior:**
to see tilled ground and plants that were planted	

**Actual behavior:**
was not able to see the tilled ground or the plants they were invisible but game still recognizes they are planted

**Comment by craig-jong** [comment]
I'm guessing this has to do with the server lagging behind significantly. Did the plants eventually appear or did they never actually appear?

**Comment by craig-jong** [comment]
If this still occurs past 7.3, please reopen the bug. Multiple fixes may have improve this, but I'm not sure without a response.
