### ISSUE TITLE
USER ISSUE: Small Wooden Cart can be burried down and disappear

### ISSUE THREAD

**Issue by Skelun** [StrangeLoopGames/EcoIssues#5323]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Dig up a hole, 1 block deep, wide enough (2x1 or 2x2)
2. Drop the Small Wooden Cart there
3. Cover the hole with construction blocks (I used Bricks)

**Expected behavior:**
I can't construct over the cart or, at least, the cart would still be there

**Actual behavior:**
The car is vanished, but I can still access his inventory through other containers that are close by

_The car got in the hole by accident. He was full, so I couldn't put it in my inventory, I tried to bug the game -- In my mind it would force the cart 1 block up, so I could pull it away -- but ended up making the cart vanish_

**Comment by WeaselDog** [comment]
This has been fixed so it is not possible to build on the cart as described in the expected behavior.
![CartSpace](https://user-images.githubusercontent.com/47330823/71495673-ffcf2580-2803-11ea-9962-9cd26c59e268.png)
