### ISSUE TITLE
USER ISSUE: Connect to Friend

### ISSUE THREAD

**Issue by HustlaSmiley** [StrangeLoopGames/EcoIssues#5325]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Friend invite me... error

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server' and also 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

* Deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Try connecting directly by entering the server's IP address in the 'Join' screen
