### ISSUE TITLE
USER ISSUE: made a world, cant enter it

### ISSUE THREAD

**Issue by sigsus** [StrangeLoopGames/EcoIssues#5329]
**Version:** 0.7.2.0 beta staging-adf7002a

**Steps to Reproduce:**
i just created a world then trying to join it, but it wont let me

**Expected behavior:**
that i would get put in the world to play

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server' and also 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

* Deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When starting a new world, select 'Generate new'
* Run the server via the Eco Server tool
