### ISSUE TITLE
USER ISSUE: Cooking bug

### ISSUE THREAD

**Issue by Speke25** [StrangeLoopGames/EcoIssues#5330]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
When i have full firecamp cooking in level max, cooked beet and cooked fish can't be taken frome the fire, it's only hapened since i have max cooking.

**Expected behavior:**
I should be capable to take my cooked food.	

**Actual behavior:**
The cooked beet and cooked fish are stuck in the fire.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3240

Interesting note about the skills, I will see if that is maybe related.

As a workaround, you should be able to queue up a project that has 1 more than you want (eg. if you want to craft 5 beets, queue up 6), and then when the project gets stuck, you can cancel it.
