### ISSUE TITLE
USER ISSUE: bug report

### ISSUE THREAD

**Issue by tradari** [StrangeLoopGames/EcoIssues#5333]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
a PC with 2 network cards both configured on different networks, the game refuses to see the lan server as its looking on the wrong network. I had this issue when i found that i had a Vethernet connection setup, however you can try to connect by adding the server manually and it see's it all correct but wont connect	

**Expected behavior:**
requires an option to select which network in the options	

**Actual behavior:**
unable to select which ethernet card to use for the game

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#218
