### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by icekult** [StrangeLoopGames/EcoIssues#5334]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Cutted a tree with an axe
2. While the tree was falling startet to chop the root

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

Stack:
   bei TreeEntity.PickupLog(Player player, Guid logID)
   bei TreeEntity.OnActInteract(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

Stack:
   bei TreeEntity.PickupLog(Player player, Guid logID)
   bei TreeEntity.OnActInteract(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment]
Fixed in next release

Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668
