### ISSUE TITLE
USER ISSUE: Pick up wood that floats in the air

### ISSUE THREAD

**Issue by icekult** [StrangeLoopGames/EcoIssues#5335]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Chop a tree
2. If a piece floats in the air try to pick it up

**Expected behavior:**
Stack wood to carried wood

**Actual behavior:**
The following error message popped up:
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

Stack:
   bei TreeEntity.PickupLog(Player player, Guid logID)
   bei TreeEntity.OnActInteract(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment]
Fixed in next release

Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668
