### ISSUE TITLE
USER ISSUE: Keyboard keys don't react after renaming an object

### ISSUE THREAD

**Issue by Krayt** [StrangeLoopGames/EcoIssues#5336]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Rename a chest, confirm with Enter key. After tabbing out of the game and tabbing back into it, it was not instantly reproducable. After some time it happened again while renaming a fishery.

**Expected behavior:**
After renaming the object you should be able to move etc. via the keyboard

**Actual behavior:**
No keyboard key except ESC worked, mouse behaviour was fine. Disconnecting and reconnecting seems to restore normal behaviour. Once rightclicking also restores normal behaviour.

**Comment by MarjieAVolk** [comment]
This is fixed in 7.2
