### ISSUE TITLE
USER ISSUE: Skillpoint on crafting turns off on game reload

### ISSUE THREAD

**Issue by Chrjss** [StrangeLoopGames/EcoIssues#5338]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. When creating a new solo game; set "generate skillpoints on crafting"
2. Craft something; confirm you get SP.
3. Disconnect and reload game.
4. Craft something again; no SP gain.	

**Expected behavior:**
It should remain consistent, i.e. not turn off on reload.	

**Actual behavior:**
Turns off SP generation on crafting.

**Comment by tauron83** [comment]
Still happening in 0.7.2.3

**Comment by MarjieAVolk** [comment]
Fixed in 7.3
