### ISSUE TITLE
[workaround] Steam Overlay crashes browsers called from within the game (even if disabled)

### ISSUE THREAD

**Issue by eliotcougar** [StrangeLoopGames/EcoIssues#5339]
Windows 10 v1709 x64. The current staging build (0.7.2-adf7002a)...
If I set my web browser to Chrome, Opera, Firefox or Internet Explorer, every time I click any of the buttons that should lead to the web page (including the Report an Issue button), it minimized the game, but the web browser crashes on launch... There is a crashdump with an Error 0xc0000005 (Access Violation) for either chrome.exe, opera.exe, firefox.exe or iexplore.exe respectively... It all works only in Microsoft Edge for some reason which I don't understand...
The only workaround right now is setting the game to run under Admin privileges which is not good...

**Comment by eliotcougar** [comment]
Further investigation shows that it's the new Advanced Threat Protection in Windows Defender that forbids Win32k.sys calls for untrusted application... Web browsers are untrusted by default because they can run arbitrary code from the Internet...
And I don't really want to set an exception for that since it applies to the browser executable and not to the game...

**Comment by eliotcougar** [comment]
Additional information: If the game is run without Steam, I am able to go to Report a bug, hit send and the Github page opens...
From what I found using the Process Explorer and some Steam logs, Steam tries to inject GameOverlayRenderer.dll into any child process the game creates, including the browser, called via rundll32.exe url.dll,FileProtocolHandler

In the GameOverlayRenderer.log I can see the issue as the phrase "Injecting to a child process..." followed by 5836 NUL characters where the information about the process the overlay is injected in should be...

Surprisingly, disabling the Steam overlay either for the game or for the whole Steam does not help...

**Comment by eliotcougar** [comment]
**Final confirmation:**
Renaming GameOverlayRenderer.dll and GameOverlayRenderer64.dll so that Steam does not try to inject them everywhere totally solves the problem...
Apparently, unticking the "Use Steam Overlay" box doesn't make Steam not to try injecting that DLL in other processes...

**Comment by Nanders** [comment]
Can no longer repro as of 7.5.0, so I'm closing this issue.
