### ISSUE TITLE
Weight mismatches : or items gain weight misteriuosly (blast Furnace)

### ISSUE THREAD

**Issue by neutronc** [StrangeLoopGames/EcoIssues#534]
If you put in 2 iron (@2 KG each) and turn that into Steel, the Steel now has 30KG of weight...

I dont know if its planned to mine/extract more ore/minerals for steel production to explain that weight gain in the future ?

Oh and even more the resulting tailings weigh also 30kg and you get between 1 and 2 per smeltprocess per steel. So from 4kg of original material you magically produce 90kg of goods ? 
This is a bit off the simulational aspect

**Comment by mariowenig** [comment]
Totally agree with weight mismatching, thinking weight is used here to allow for less of it to be carried rather then being an exact conversion. Mathematically just like the Barrel issue, with efficiency  this gets even weirder.

Steelworking lvl 3 = 52% i think, making Iron(2kg) -> Steel(30kg) + Tailing(30kg) a ~ 1 Iron : 1 Steel + 1 Tailing conversion. I think to makes eff work with this there would need to be a different value attached to items, something like carry limit, rather then basing it on weight alone to create the disconnect and smooth out those numbers of weight.

Make tailings lighter so we can store more in chest, jk. :+1:

**Comment by pan7s** [comment]
Yeah I think weights are weird too. Cart can only hold 50 blocks of dirt but 100's of coal. Might be planeed that way for a game perspective but idk
 Feels weird to me
