### ISSUE TITLE
USER ISSUE: Store Inventory Delete/Move

### ISSUE THREAD

**Issue by mreil617** [StrangeLoopGames/EcoIssues#5340]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Add or remove enough items to see the hover display enable / disable itself.

**Expected behavior:**
Able to delete or reorganise inventory list for a store.	

**Actual behavior:**
Only able to delete or move sold items when the list is long enough to scroll.

**Comment by MarjieAVolk** [comment]
@johnkslg I have seen similar behavior off and on.  The most common one I see is that sometimes the list controls don't appear for the first listing in the store.  Seems to be a problem in the auto view system thing.

**Comment by johnkslg** [comment]
Reducing priority but will fix.

**Comment by johnkslg** [comment]
Verified working in staging
