### ISSUE TITLE
USER ISSUE: Randomly left Steam multiplayer Session

### ISSUE THREAD

**Issue by jWalker92** [StrangeLoopGames/EcoIssues#5341]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Played some time via Steam Join Game and after about 1-2 hours i randomly disconnected. Rejoining says Connection failed, both restarted and stil Connection failed

**Expected behavior:**
Should be able to reconnect

**Actual behavior:**
Connection failed

**Comment by MarjieAVolk** [comment]
Did the server you were playing on go down?

**Comment by jWalker92** [comment]
We played PeerToPeer

**Comment by MarjieAVolk** [comment]
Are you still having the same problem?  Or did it only happen for a while?

**Comment by jWalker92** [comment]
It just happened once, we then never tried p2p again and just switched to a server.
Maybe his server instance crashed, but the game still played. And error handling for this specific case was not there. So maybe steam or matchmaking didn't get notified that the server object is not there anymore and it tried to connect to a null server.
We could look into log files on his local machine if that helps.

**Comment by MarjieAVolk** [comment]
Yeah, if you can find crash files for the server, that might be it.  They should be in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'.  Thanks.

**Comment by MarjieAVolk** [comment]
Closing due to no response / not enough information.
