### ISSUE TITLE
USER ISSUE: Client Crash

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#5342]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Placing mortared stone on the ground

**Expected behavior:**
The client shouldn't crash.

**Actual behavior:**
The following error message popped up:
```
Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment]
If you can find a server log that has a more detailed error message, then I can look at that.  But without that, it is hard to know what this is.

In 7.2, we are now outputting better error messages, so the next time you have this problem, we should be able to help.  Sorry about that!
