### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by tiegs2000** [StrangeLoopGames/EcoIssues#5344]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**
To join my friends game

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
The next time you have this problem, if you can send me your log file 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

* Deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Try connecting directly by entering the server's IP address in the 'Join' screen
