### ISSUE TITLE
USER ISSUE: Zero G Resources

### ISSUE THREAD

**Issue by kgress** [StrangeLoopGames/EcoIssues#5348]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Find a way to fall through the world endlessly
2. After doing so, disconnect
3. Log back in to the same server
4. Chaacter will spawn on top of a stockpile. When spawning on top of the stockpile, resources will begin to float away in zero g.	

**Expected behavior:**
Resources that are in the stockpile should stay in the stockpile.

**Actual behavior:**
Resources floated away in zero g. See screenshot below.

https://imgur.com/a/57ahp

**Comment by MarjieAVolk** [comment]
Floating logs are fixed in 7.2.  Some missing chunks are also fixed in 7.2, but there may still be some falling through the world issues.
