### ISSUE TITLE
Pollution by player vs placed by player?

### ISSUE THREAD

**Issue by mariowenig** [StrangeLoopGames/EcoIssues#535]
I haven't been able to fully track this down.
But I am getting the feeling pollution is added not by whom started the job, but rather to whom the object belongs.

This is unconfirmed but I placed a bloomery down (belongs to me).
Community has been using said bloomery, seem like my pollution increases due to usage of my bloom, even though I am not the one running the job/crafting.

Or is this deed dependent? More testing required.

**Comment by metachronism** [comment]
should be addressed by new simulation system in alpha 5
