### ISSUE TITLE
Game crashes when you try to view servers while logged out of Steam

### ISSUE THREAD

**Issue by anyweez** [StrangeLoopGames/EcoIssues#5351]
Clicking the "join" button on the intro screen leads to a near-immediate crash when you're in offline mode in Steam.

https://support.steampowered.com/kb_article.php?ref=3160-agcb-2555

It makes sense that this wouldn't work in offline mode, but it'd be nice to give an error message instead of crashing. Took me a few tries to figure out what was wrong.

**Comment by MarjieAVolk** [comment]
@Nanders This may explain some other bugs assigned to you.

**Comment by anyweez** [comment]
OK I'm not sure this is actually capturing my issue correctly; still trying to poke around and better understand it but I've managed to connect while in offline mode. I'll follow up with another issue once I've got something.
