### ISSUE TITLE
USER ISSUE: Camo Pants not showing

### ISSUE THREAD

**Issue by xTrickShotProx** [StrangeLoopGames/EcoIssues#5353]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Equip Camo Pants

**Expected behavior:**
Show Camo pants on player

**Actual behavior:**
Item doesn't show up

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3208
