### ISSUE TITLE
USER ISSUE: Endless hole

### ISSUE THREAD

**Issue by JonKelley88** [StrangeLoopGames/EcoIssues#5356]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I was fishing and i went back to the town i made and it wasnt there instead it was just a hold where graphics should be and when you walked in it you fell off the map.

**Expected behavior:**
Go back to my town 

**Actual behavior:**
graphics missing and fell off the map.

**Comment by MarjieAVolk** [comment]
We believe this is fixed in 7.2, we will keep an eye on it.
