### ISSUE TITLE
USER ISSUE: broke stone

### ISSUE THREAD

**Issue by ljej1989** [StrangeLoopGames/EcoIssues#5357]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
was mineing under my bace and error appeard	

**Expected behavior:**
broke rock

**Actual behavior:**
The following error message popped up:
```
Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment]
Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/5537, which is fixed in 7.2
