### ISSUE TITLE
Plastic Has No In-game Model or Texture

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#5358]
![20180303235402_1](https://user-images.githubusercontent.com/2582909/36942683-b0b9a54e-1f3e-11e8-9414-2af42a83eda9.jpg)

Also if it is placed in the world, if you try to pick it up with a hammer it simply disappears.

**Comment by MarjieAVolk** [comment]
Working as intended :P - Plastic was not intended to be a block.  For 7.2, we are attempting to get rid of existing plastic blocks from migrated saves.  You should be able to pick it up in your inventory to get the plastic items back, after which you will need to place them in a chest.
