### ISSUE TITLE
Suggestion: More Signs and Ways to Advertise

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#5360]
The small wood sign and wood sign are nice, but after that there isn't anything. It would be nice and logical to have metal signs, billboards (like the kind you see next to highways), neon signs, and all sorts of light strips to embellish modern buildings to make them more alive and attractive. Also, an even larger wooden sign that is wall mounted similar to a chalkboard would be useful.

**Comment by Blanclour** [comment]
Also forgot to mention overhead highway signs, which are useful for navigation.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#217
