### ISSUE TITLE
USER ISSUE: No Hud

### ISSUE THREAD

**Issue by Schaboom** [StrangeLoopGames/EcoIssues#5362]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Playerbug from other User, restart the Server All players have no HUD!!!. Server Deleted, Reinstall over Steam. Connect.... UUUUPS All Players NO HUD

**Expected behavior:**

**Actual behavior:**

**Comment by Schaboom** [comment]
The Problem is Solved... The Serveradmin has Changed the UseWaste Field to true...

**Comment by MarjieAVolk** [comment]
Thanks for letting us know.  That option needs to be hidden.
