### ISSUE TITLE
USER ISSUE: fishing

### ISSUE THREAD

**Issue by knuckles2k12** [StrangeLoopGames/EcoIssues#5363]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
cannot catch and have more than 1 type of fish in inventory.
when catching second fish and reeling it in it just disapears.
also same with fish traps.

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/4588?

**Comment by craig-jong** [comment]
This should have been fixed in the latest release
