### ISSUE TITLE
USER ISSUE: Game unplayable after loading save

### ISSUE THREAD

**Issue by legionvs** [StrangeLoopGames/EcoIssues#5365]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Load a save or click continue	

**Expected behavior:**
Should play as normal

**Actual behavior:**
FPS drops to 0 and game is completey unplayble and stutters.  New world creation runs as normal.

**Comment by metachronism** [comment]
@legionvs do you have this gamesave still?  if so please re-open and attach the save if possible, thanks
