### ISSUE TITLE
Eco crashed the third time now

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#5368]
...and i am unable to find ANY logfiles to make a proper bugreport, please assist me with where to find the logs to make a proper crashlog ... PS you could add some contribution guidelines to the project to make it easier to find answers to frequently asked questions

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5421
