### ISSUE TITLE
USER ISSUE: Permanent dead cedar

### ISSUE THREAD

**Issue by CSmither** [StrangeLoopGames/EcoIssues#5371]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Plant cedar in plowed ground that isn't suitable
Wait for cedar to die
dig ground and replace
use sampler on ground

**Expected behavior:**
No plant detected by sampler

**Actual behavior:**
Sampler still thinks there is a dead cedar planted

**Comment by GophTheGreat** [comment]
Open of it reoccurs, but I think this was recently fixed and I can't reproduce it.
