### ISSUE TITLE
USER ISSUE: I CAN'T LOG IN

### ISSUE THREAD

**Issue by dejan19911** [StrangeLoopGames/EcoIssues#5373]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
how can i uncover or reset or make new account because tehnicaly i bought game instaled but i can't enter to play because either i forgot username or password (wich i doubt) or im typing wrong so where i can see what i wrote or what is actual name of account

**Expected behavior:**
LOGING IN

**Actual behavior:**

**Comment by pmeyerson** [comment]
others reported fix by restarting steam client, if you purchased via steam.  HTH

**Comment by MarjieAVolk** [comment]
If you purchased via steam, and it is asking you to log in, then your steam login has failed.  In which case restarting steam could help.

If you purchased via our website, you should contact support@strangeloopgames.com to get your login info back.

**Comment by dejan19911** [comment]
Have another question we downloaded ECOserver and tried to make one for us,
but we made some mistakes and wanted to make another one but it wont let us
delete the one we are using how to delete or restart the ECOserver client
or how you call it. Huge thanks if you could help us

2018-03-06 3:36 GMT+01:00 MarjieAVolk <notifications@github.com>:

**Comment by dejan19911** [comment]
because i made now new server on my end but on other end it shows that its
offline and can't connect to it what is the problem and how to fix it any
thoughts?



2018-03-06 18:11 GMT+01:00 Thresh baby care <dejanmihajlovic1991@gmail.com>:

**Comment by MarjieAVolk** [comment]
Ah, yeah I guess you can't delete save files from in game right now >>  You will need to open up the folder and delete the save file on your computer manually.  These should be in '...\steamapps\common\Eco Server\Storage'  I will make a note to add a delete button for save files.

For the connection problem, you can try connecting to the server by entering its ip address in the join window.  Let me know if that works.

**Comment by dejan19911** [comment]
We will try to delete the server (save files) manually, because we try to
make one server and mess things with meteor crash. So we tried to fix it
with our working on world/codes but we than make code mistake and world is
not playable, than we try to delete that world it didn't worked, than a
problem appeared with starting an ECO server and it constantly popin' the
picture below. After that i downloaded ECO server myself made brand new
world put password and description name took IP address from the ECO server
and we tried  both 3000,3001, and the number that is by NAT detected/
External Ports/ web number that also doesn't work. I turned off my anti
viruses and firewalls nothing seems to do any changes because the world
that we are making is just for two persons not more not less, and when i
enter the world, world is avaliable for me but for her its offline and
won't let her join the world if you can think on any possible problem on
both of problems that you encounter till this time i would be happy to
listen for your advice on the matter, nothing is complicated and not
fixable so we just need some advice on where to look and what to search
for. And that Delete button would be nice to add :D!!!!
All regards and thank you for your time to listen a problem.
Peace.

2018-03-06 19:18 GMT+01:00 MarjieAVolk <notifications@github.com>:

**Comment by dejan19911** [comment]
Now is saying this on both accounts.

2018-03-06 20:45 GMT+01:00 Thresh baby care <dejanmihajlovic1991@gmail.com>:

**Comment by MarjieAVolk** [comment]
Hey, sorry I'm really struggling to understand what your problem is.  You said there was a screenshot, but I don't see one.  So you started a server on your machine, and your friend can't connect to it?

**Comment by dejan19911** [comment]
Correct and when we make a server it seems that we can't delete it and/or
make brand new server. So we are playing on first server that we made even
though we want to make brand new bigger one with new setup. We try to
delete from steam/ECO/server/storage we delete servers there but when we
make new one in ECO server it constantly starts the first one over and
over. My question is. Is there any way for us to completly remove that
server from our games and make new bigger server? Thanks and sorry for
spamming, it's really nice game and we want to enjoy in making for us
perfect world. Peace.

2018-03-09 20:19 GMT+01:00 MarjieAVolk <notifications@github.com>:

**Comment by MarjieAVolk** [comment]
Is it just that you're starting your new servers with the default world?  You can check 'generate new' while starting a new world to ensure that the world generation is different.

**Comment by dejan19911** [comment]
Checking that every time trust me.
and every time it comes the world with meteor destroyed world and with all
destroyed buildings and stuff. Same world that we build allready.


2018-03-09 23:03 GMT+01:00 MarjieAVolk <notifications@github.com>:

**Comment by MarjieAVolk** [comment]
Oh you know what, I think I gave you the wrong directory maybe.  Are the save files in '[...]\steamapps\common\Eco\Eco_Data\Server\Storage'?

**Comment by dejan19911** [comment]
Yes Both new world and the new generated one and we tried to delete one at
the time and than both of worlds but it didn't helped. And that is weird
for me to be honest if i delete world from there how it can re appear again
when we make new world.

2018-03-09 23:06 GMT+01:00 MarjieAVolk <notifications@github.com>:

**Comment by MarjieAVolk** [comment]
Originally I told you to look in '...\steamapps\common\Eco Server\Storage' - Now I am telling you to look in  '[...]\steamapps\common\Eco\Eco_Data\Server\Storage'.  You deleted all in both?

**Comment by dejan19911** [comment]
You mean to go Steam/steamapps/common/Eco Server/ Storage we have folder
Backup, DefaultWorld, Game, Game.eco
and on Steam/steamapps/common/Eco/Eco_Data/Server/Storage we have some
DotNetZip-.... and Name of the World.
My question is now from where you would delete to really delete world?
:))))))))))

2018-03-09 23:12 GMT+01:00 MarjieAVolk <notifications@github.com>:

**Comment by dejan19911** [comment]
In my mind now logical would be to delete just DefaultWorld> reason that
world is generated from Eco server and what we make in the program. Am i
correct or i'll mess game more xD :D?


2018-03-09 23:23 GMT+01:00 Thresh baby care <dejanmihajlovic1991@gmail.com>:

**Comment by MarjieAVolk** [comment]
No, don't delete Default World.  Delete everything else.

**Comment by MarjieAVolk** [comment]
The file that is the name of your world is what you really want to delete.  But anything else in Storage folder other than DefaultWorld is fine to get rid of, if you just want to clear your save file.
