### ISSUE TITLE
USER ISSUE: No way to loot a Fishtrap

### ISSUE THREAD

**Issue by AnKasper** [StrangeLoopGames/EcoIssues#5376]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Place a Fishtrap underwarter

**Expected behavior:**
my Char has to stay underwarter while looting a fishtrap

**Actual behavior:**
my Char swims back to surface while looting the trap, the inventory is closing, so no way to loot the trap

**Comment by ArmandVestibule** [comment]
I, too, experienced this issue.  

A workaround that works for me is to take a hammer to the trap. The trap and the contents are placed in your inventory.  HTH!

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4275
