### ISSUE TITLE
USER ISSUE: Not logical ground moisture

### ISSUE THREAD

**Issue by fame1991** [StrangeLoopGames/EcoIssues#5380]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Use soil sampler on blocks next to or in the water	

**Expected behavior:**
It should have a high level of moisture

**Actual behavior:**
A block in the water has 30% soil moisture

**Comment by fame1991** [comment]
Just checked the moisture at a river. It was around 90%. I checked it next to the sea and in the sea.

**Comment by craig-jong** [comment]
Soil moisture only counts fresh water which is why water by the sea does not increase soil moisture.
