### ISSUE TITLE
USER ISSUE: Produced products

### ISSUE THREAD

**Issue by bootj93** [StrangeLoopGames/EcoIssues#5384]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Order products at a crafting station (does not matter which type)

**Expected behavior:**
Produces products when enough recources are available when production time is completed you can select collect	

**Actual behavior:**
Says products heave been produced with a green beam and time = 0 but you cannot collect them nor gives the station any other message

**Comment by MarjieAVolk** [comment]
Have you checked the status tab for the station?  Are any requirements missing?
