### ISSUE TITLE
USER ISSUE: Road contract do not expire

### ISSUE THREAD

**Issue by neyna** [StrangeLoopGames/EcoIssues#5385]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. create build road contract with default 24h

**Expected behavior:**
after 24h if the contract is not fullfilled, it should be cancelled or the person who made the contract should be allowed to cancel it .

**Actual behavior:**
The contract never ends and money is not given back

**Comment by johnkslg** [comment]
You can mark a contract failed once it's expired if you're the client, it doesn't happen automatically.  Added this info to the tooltip.
