### ISSUE TITLE
USER ISSUE: You must complete the form

### ISSUE THREAD

**Issue by FuJa0815** [StrangeLoopGames/EcoIssues#5387]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Try to propose a law
2. fill all fields
3. click propose law

**Expected behavior:**
The law should be proposed

**Actual behavior:**
The following error message popped up:
```
You must complete the form

**Comment by MarjieAVolk** [comment]
Do you have districts defined in your law and/or on your server?  Some people were seeing this in combination with districts, and particularly if there were two districts with the same name.

**Comment by MarjieAVolk** [comment]
Closing as probably already fixed.
