### ISSUE TITLE
USER ISSUE: cannot play the game it either crashes or doesn't recognize my account info

### ISSUE THREAD

**Issue by dannyboy9001** [StrangeLoopGames/EcoIssues#5388]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
trying to start the game, if I hit create world and confirm the screen totally disappears and if I hover over the tab then it shows the beta server number thing but if I try to click on it to bring it up the game kicks back to naming a new world, and occasionally it tries to have me log in but it won't recognize my username or password

**Expected behavior:**
the game should have started and let me play it

**Actual behavior:**
would not allow me to play the game

**Comment by MarjieAVolk** [comment]
Well I haven't heard this one before.  What operating system are you on?  Also, would you be able to attach your log file?  'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by MarjieAVolk** [comment]
Closing due to no response.

If you are having trouble with logging in, and you purchased the game on steam - try restarting steam, or if you are offline in steam go back online, etc.  If you are playing via steam and Eco asks you for login info, that means your steam login has failed.
