### ISSUE TITLE
USER ISSUE: Admin cant give me points

### ISSUE THREAD

**Issue by Monsterschnitzl** [StrangeLoopGames/EcoIssues#5389]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Admin tried to give me skillpoints, couldnt because of [] in my name. please fix

**Expected behavior:**
gotten 500 skillpoints	

**Actual behavior:**
i didnt

**Comment by MarjieAVolk** [comment]
This seems to be working for me.  Is this fixed for you now?  Will reopen if not fixed.
