### ISSUE TITLE
USER ISSUE: Logs are flying away

### ISSUE THREAD

**Issue by Awesomepro247** [StrangeLoopGames/EcoIssues#5390]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I am not certain on how this happend.
I was cutting a tree and had to go do something irl, so I logged off.
I come back on and the log pieces I cut were flying away

**Expected behavior:**
Stayed on the ground

**Actual behavior:**
The log pieces flew into the sky

**Comment by MarjieAVolk** [comment]
This should be fixed in 7.2
