### ISSUE TITLE
USER ISSUE: Powered Cart Glitch

### ISSUE THREAD

**Issue by ProFatBoi** [StrangeLoopGames/EcoIssues#5392]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Exit Powered Cart

**Expected behavior:**
Cart stays where it is

**Actual behavior:**
Cart glitches and seems to bounce on the spot. Very annoying if you are on a cliff side and it jumps off the cliff when you exit it/

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4461
