### ISSUE TITLE
Electric/Petrol Lawnmower

### ISSUE THREAD

**Issue by ProFatBoi** [StrangeLoopGames/EcoIssues#5393]
I think having a mechanical lawn mower instead of having to do it manually would be good. Of course if it was a petrol mower it would output exhaust fumes same as the powered cart.

**Comment by johnkslg** [comment]
My favorite scene is still someone mowing their lawn nice and tidy while the meteor is about to hit.

**Comment by ProFatBoi** [comment]
Got to make it look nice and tidy while pretending that all is well and hoping the meteor just passes us by haha

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#215
