### ISSUE TITLE
USER ISSUE: Electric Wall Lamps not clipping to walls

### ISSUE THREAD

**Issue by Boldee** [StrangeLoopGames/EcoIssues#5395]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Make Electric Wall Lamp
2. Attache to narrow wall

**Expected behavior:**
Position flush to wall

**Actual behavior:**
Positions with gap from wall maintaining same distance as foundation block

**Comment by MarjieAVolk** [comment]
![image](https://user-images.githubusercontent.com/23460210/41874923-2d030670-787e-11e8-985a-3f4053d4577e.png)
-- @kshood

**Comment by metachronism** [comment]
@BlazeGuy2 can you move this to suggestions?  not a bug

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#523
