### ISSUE TITLE
USER ISSUE: Placed a plactic block in the world and it can't be picked up.

### ISSUE THREAD

**Issue by ThaProfessor11** [StrangeLoopGames/EcoIssues#5396]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I went to transfer plastic from my stockpile to the electronic assembly machine, I wanted to see what plastic looked like placed in the world so I plopped it down in the middle of my building, and now it won't go away. If I smack it with my hammer it disappears, BUT it comes back if I place or smack another block nearby. I've even tried to make it disappear then place a block over it, but it if I smack a block, the plastic block overrides the newly placed block and the block comes back to my inventory.

**Expected behavior:**
I should be able to pick it up

**Actual behavior:**
Instead it disappears then reappears.

**Comment by MarjieAVolk** [comment]
Plastic was not meant to be a block, so it was messed up in this version.  Will be fixed in 7.2.
