### ISSUE TITLE
USER ISSUE: Game won't start when creating world

### ISSUE THREAD

**Issue by sokiamasan** [StrangeLoopGames/EcoIssues#5397]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. I opened the game
2. I went to new
3. went to put my world name and settings in
4. clicked start but nothing happened

**Expected behavior:**
It should've loaded me into a new world after creating it, but instead it wouldn't load in and kept me at the options menu in the "new worlds" screen

**Actual behavior:**
The following error message popped up:
```
Could not start server: Process has not been started.
```

**Comment by MarjieAVolk** [comment]
What operating system are you on?

**Comment by MarjieAVolk** [comment]
Closing due to no response

**Comment by ShaydenMac** [comment]
http://steamcommunity.com/profiles/76561198038446128/recommended/382310/

"Startet this game for the first time and every time i press start new world the game switches to my dektop and nothing else happens....?"
