### ISSUE TITLE
USER ISSUE: Object not set to an instance

### ISSUE THREAD

**Issue by kamiifx** [StrangeLoopGames/EcoIssues#5399]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Chop wood, and this error randomly comes up

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment]
Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/3668, which will be fixed in 7.2
