### ISSUE TITLE
OS X paste happens twice

### ISSUE THREAD

**Issue by mgold** [StrangeLoopGames/EcoIssues#54]
When using command-P to paste in to the text fields (log in, connect to server), the pasted text is inserted twice. This is particularly annoying when trying to paste a long password from a password manager...

Steps to reproduce:
* Copy some text.
* Open Eco.
* Select the username field.
* Command-P
* Notice that the copied text is inserted twice.

**Comment by metachronism** [comment]
fixed in alpha 5
