### ISSUE TITLE
USER ISSUE: Skill point per action are bugged for mining ores

### ISSUE THREAD

**Issue by neyna** [StrangeLoopGames/EcoIssues#5400]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Add skill point per action in the config.
When you mine ore you will get something like 100 more times the config value as skill points. 
It seems other actions do not give the value set in parameters but all have some kind of multiplier.

**Expected behavior:**
Get the value set in parameters, for example 0.01, for each action. 100 actions will give 1 point. And for any combination of actions.

**Actual behavior:**

**Comment by craig-jong** [comment]
The skillpoints per action is based on the player's current skillpoint gain which, in turn, is affected by the skillrate set by the entire server.

I'm not really sure this is actually a bug, but rather a miscommunication of a poorly described feature. I'll see if I can throw in toggles for that kind of stuff, but I don't think it's high priority.

**Comment by craig-jong** [comment]
The system doesn't actually care WHAT action is performed, just that one has been. So basically picking up a rock gives you the same skillpoints as hitting a tree with an axe. I've check multiple times under various scenarios and all actions run through the same code-path. They all give the same amount of skillpoints.

It's not a perfect system and can definitely be abused. There's a reason it isn't enabled by default on any settings. That said, in the right environment it could still work. As I said, we'll look into improving it in the future.

**Comment by MarjieAVolk** [comment]
Shouldn't it not give you points if you didn't successfully perform an action at all though?

**Comment by neyna** [comment]
It's strange you cant reproduce it. I saw this issue on 2 servers (one on which i was admin. I put skill point per action but removed it after i saw that it was bugged with ores. Everyone, more than 20 people, noticed the bug as well). I reported it when game version was 7.1 maybe it's fixed since.

And when i was testing who skill point per action was working before switching settings on my server, i noticed that all actions were not giving the same amount of skill point. To test that, i had the setting on 1 and after 10 points par action. But you need to wait the server to tick to see how much skill points you won (wait around 3-10s depending on your luck with the next tick)

**Comment by neyna** [comment]
I just tested it again. I cant reproduce it anymore.

It should have been fixed since i encountered this issue.
