### ISSUE TITLE
USER ISSUE: Parando de funcionar

### ISSUE THREAD

**Issue by LimaLaranja** [StrangeLoopGames/EcoIssues#5401]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
parando de funcionar o ecoserver quando eu tento entrar no meu mundo

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Na próxima vez que você tiver esse problema, se você pode me enviar arquivos de log / crash em '[...] \ steamapps \ common \ Eco Server' e também 'C: \ Users \\ [nome de usuário] \ AppData \ LocalLow \ Strange Loop Games \ ECO \ output_log.txt ', posso tentar diagnosticar o problema.

Há também algumas coisas que você pode tentar como uma solução alternativa:

* Apagando a pasta C: \ Users \\ [nome de usuário] \ AppData \ LocalLow \ Strange Loop Games \ ECO
* Desativando temporariamente o seu firewall e / ou software antivírus
* Ao iniciar um novo mundo, selecione 'Gerar novo'
* Execute o servidor através da ferramenta Eco Server

---------------------

The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server' and also 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

* Deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When starting a new world, select 'Generate new'
* Run the server via the Eco Server tool
