### ISSUE TITLE
USER ISSUE: remapping interact partially ineffective

### ISSUE THREAD

**Issue by apowers** [StrangeLoopGames/EcoIssues#5404]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Remap interact to another key and 'E' to something else, like move right. pick up a cart. use new interract key to try and drop the cart. see that it doesn't drop. press 'E' to move right and see that the cart drops.

**Expected behavior:**
remapping interact should also remap the action to drop a cart.

**Actual behavior:**
After remapping interact, 'E' still drops the cart.

**Comment by MarjieAVolk** [comment]
Fixed in 7.2
