### ISSUE TITLE
Server list + favourites being lost after entering wrong password while joining a server

### ISSUE THREAD

**Issue by SmattyCore** [StrangeLoopGames/EcoIssues#5405]
**Version:** Latest Stable Version from Steam

**Problem:**
If I want to join a server and the password I intered is wrong and want to try it again server list is empty, and my favourited server is gone. 

**Workaround:**
Restarting the game, server list + favourites are back again!

**Hardware/Software:**
CPU: Intel i5 Quad Core CPU with 2,50 GHz and up to 3.xx GHz boost
RAM: 8 GB
OS: Latest Windows 10 Version

**Comment by MarjieAVolk** [comment]
7.4 will have the new and improved server list screen. I have tested out entering incorrect passwords, etc, and it seems to work fine. So I'm hoping this will no longer be a problem after 7.4. Let me know if you have any more issues after updating!
