### ISSUE TITLE
USER ISSUE: Falling infinitly becaus the world didn't loaded

### ISSUE THREAD

**Issue by Siedler** [StrangeLoopGames/EcoIssues#5406]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Walk into an area that isn't loaded

**Expected behavior:**
Should load the area	

**Actual behavior:**
Let's me fall down

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861.  Hopefully this will be fixed in 7.2
