### ISSUE TITLE
USER ISSUE: Cannot create a new world

### ISSUE THREAD

**Issue by DrDr3ck** [StrangeLoopGames/EcoIssues#5407]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Launch ECO
Click on NEW
Click on Start

**Expected behavior:**
It should create a new world

**Actual behavior:**
Connection Failed

**Comment by MarjieAVolk** [comment]
The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server' and also 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

* Deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When starting a new world, select 'Generate new'
* Start your new world via the Eco Server tool
