### ISSUE TITLE
USER ISSUE: Crash while mining maybe due to teleported blocks

### ISSUE THREAD

**Issue by cmfrydos** [StrangeLoopGames/EcoIssues#5408]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Mine stone under ground.
2. I noticed that 30-50% of the stone-items where teleported ~ 20 layers to the top, but actually there was enough room for them to spawn where the block was. 

**Expected behavior:**
Blocks being teleported was not new to me, but it should not crash.

**Actual behavior:**
The following error message popped up:
```
Caught exception: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
```

There is an empty file named 'ClientUpdateException NullReferenceException 03055929.ecodmp' in dump folder. The last two lines in the serverlog are:
'Caught update exception from (MyUsername)  Disconnecting...
Disconnecting client [reason: Caught exception: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.]...'

**Comment by MarjieAVolk** [comment]
We have been working on reducing teleporting stone, should be greatly improved in the next release.

I am not sure if the crash is related.  Pretty hard to tell without a full stack trace.  In the next release, we will also be sending full stack traces in the disconnect message, so it will be easier to debug these.

**Comment by MarjieAVolk** [comment]
Going to close as already fixed for now.  If you get a full stack trace, please share :)
