### ISSUE TITLE
Feature: Contracts paid out of Treasury funds

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#5409]
Currently, the Leader can Allocate funds to players as they see fit - possibly as a reward for services rendered, or maybe as advance payment for services yet to be performed.

However, there's no bulletproof way for the Leader to offer a **contract for services on behalf of the public**.

The existing way is for the Leader to allocate funds to themselves, and then offer the Contract in their own name - as in this example:

![image](https://user-images.githubusercontent.com/2173684/36973656-8ca42148-20bf-11e8-9c93-00fbcf1fbd66.png)

![image](https://user-images.githubusercontent.com/2173684/36973663-91c850cc-20bf-11e8-86d7-757f9096344e.png)

However, mixing up the Leader's personal bank balance with the public funds is not ideal - it's possible that the Leader could go bankrupt, which prevents the public contracts (in the Leader's name) from being fulfilled.

**Comment by Amphysbaenas** [comment]
+1 we need that feature !!!!

**Comment by D3nnis3n** [comment]
+1

**Comment by johnkslg** [comment]
Once aliases give you access to other bank accounts, we can add something to let you choose which account it comes from.

**Comment by D3nnis3n** [comment]
Implemented in 8.0
