### ISSUE TITLE
Multiple Blast Furnaces in single room (enabled/disabled flicker)

### ISSUE THREAD

**Issue by mariowenig** [StrangeLoopGames/EcoIssues#541]
Room has original Blast Furnace
Combustion Gen
Electrical Gen
Rolling Mill
Industrial Cutter (i think, whatever allows rebar)

Works fine by itself, when second Blast Furnace is added and a job is run in it, it does what the image shows. Enables/Disabled continuously.
Both Blast Furnaces are considered valid when placed.
No other tables in room.

![image](https://cloud.githubusercontent.com/assets/10489431/17179169/30817962-53e6-11e6-951b-0c7894df16d9.png)

**Comment by jhadred** [comment]
Further attempts at testing indicates that a single room is not the issue.  It may be proximity of two blast furnaces to an industrial cutter.   I was able to slowly shift both blast furnaces and the rolling mill away from a certain point (lets call it away from the front where the gens and industrial cutter are and where the two gens are still close to the blast furnace.  At some point the repeating "work halted/work restarted" messages did not occur during the creation process.

Further testing may require the creation of another room and an industrial cutter as this is not able to be moved (while the roller mill could).

**Comment by metachronism** [comment]
fixed with power fixes
