### ISSUE TITLE
Server taking 2-20 minutes to appear in server browser unless favorited

### ISSUE THREAD

**Issue by nebior** [StrangeLoopGames/EcoIssues#5414]
My server is hosted via PingPerfect. The server is online and running just fine.
When I search for my server in the server browser it takes up to 20 minutes to be found. I had 8 people trying this and reporting times from 2 minutes up to 20 minutes from different parts of the world. The server is in New York and many of us are nearby. After taking this long time to show up the server is also reporting incorrect and massive ping. I would always see 30k+ ping after 5 minutes of waiting for the server to appear in the browser. 

For all 8 of us, if we favorited the server it would appear immediately and have a proper ping representation. 

My worry is that nobody will stumble across our server as a new player because nobody is going to wait 5 minutes and then look for a server with thousands of ping. I know this erroneous ping has been reported and is being worked on, but I have not read anything about a server not showing up in the server browser.

**Comment by MarjieAVolk** [comment]
@rainfarmer Could the delay to show up be web side?

If I understand correctly, the first time we set ping, it is based on how long the server takes to respond with all its listing data (eg. law count, player count, and other things displayed in the server browser), but later the ping might be reset based on a ping-only thing, idk if that would affect the accuracy this much, but might be related.

**Comment by metachronism** [comment]
This is just general issues with the server browser.  it only adds one entry/frame to the list, and our list of servers now is quite large.

Recommend adding as favorite for now, until the server browser rework is completed

**Comment by MarjieAVolk** [comment]
In 7.4, the server browser has been redone, and our method of getting ping has also been changed.  Hopefully you will see better behavior after updating.  If not, let me know.

**Comment by nebior** [comment]
I closed this server/account months ago. Please confirm that I am not
paying for this server. Thank you.

--Ben

**Comment by MarjieAVolk** [comment]
We are not affiliated with PingPerfect, so we can't confirm that ;)
