### ISSUE TITLE
USER ISSUE: Graficbug Stockpile

### ISSUE THREAD

**Issue by hikarusulu** [StrangeLoopGames/EcoIssues#5415]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
build a stockpile in a house and fill it with earth then transport the dirt to an other place and remove the stockpile

**Expected behavior:**
the stockpile should be empty and the stockanimation should not more there.

**Actual behavior:**
the stockpile is not empty a grafik bug is there and when you remove the stockpile the bug is always ther .

**Comment by MarjieAVolk** [comment]
Some screenshots might help to clarify this issue.

**Comment by hikarusulu** [comment]
after I restarted the game the graphic error is gone, if in the future again a bug should emerge I will make a screenshot.Thank you for your prompt reply.

MfGPatrick Boiko
    Am Montag, 5. März 2018, 21:09:43 MEZ hat MarjieAVolk <notifications@github.com> Folgendes geschrieben:  
 
 
Some screenshots might help to clarify this issue.
