### ISSUE TITLE
USER ISSUE: Building Issue [window-stair interaction]

### ISSUE THREAD

**Issue by frogger35** [StrangeLoopGames/EcoIssues#5417]
![capture](https://user-images.githubusercontent.com/5314324/36986839-7bc8b5a0-2060-11e8-87d1-b619385518a1.PNG)
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Place a window down where one would normally place a window
2. put stairs next to window

**Expected behavior:**
the stairs and window should not interact

**Actual behavior:**
the stairs and windows interact and you get what is shown in this picture

**Comment by keegan-o** [comment]
Can't repro after various tweaks to mortared stone, should be fixed.
