### ISSUE TITLE
USER ISSUE: Not go in in game

### ISSUE THREAD

**Issue by Dirius86** [StrangeLoopGames/EcoIssues#5418]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. i prof to load my game it din't work

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server' and also 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

* Deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When starting a new world, select 'Generate new'
* Run the server via the Eco Server tool
