### ISSUE TITLE
Campfire displays (but does not use) power when electricity is available.  May be skill related.

### ISSUE THREAD

**Issue by jhadred** [StrangeLoopGames/EcoIssues#542]
When electrical generators are placed (irrespective of combustion generators), I was seeing some campfires show Producing 1000W (Powered) / Consumed 700W (Powered).  It seems to have been one campfire per generator.  
However another two users (who do not have as many invested cooking points) saw the campfire correctly as 50.0 (Unpowered) and 50.0 (Off)

The campfire likely does not consume energy from the generator and does not cook anything when generators are fueled so it appears to just be a display behavior.

My view of campfire
![fire2](https://cloud.githubusercontent.com/assets/20424793/17196520/56a650ca-5433-11e6-8a46-bed81165cc0a.jpg)

Mario's view
![image](https://cloud.githubusercontent.com/assets/20424793/17196630/04eb8ace-5434-11e6-8b36-0cafe3c24b14.png)

**Comment by mariowenig** [comment]
Which is very odd, checked code found PowerTypeHeat.
