### ISSUE TITLE
USER ISSUE: Stone gone

### ISSUE THREAD

**Issue by MightyMi124** [StrangeLoopGames/EcoIssues#5424]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Is managed to produce a researchtable at the craftingtable. it needs stone. I've got something in my storage, but not enough. 2 stones needed to finish the researchtable.
So i went to get some. Some more as i need and brought it back to the storage.

**Expected behavior:**
the 20 stone should have stacked in the storage and 2 stone should have gone to the workbench.

**Actual behavior:**
it tells me, 2 stone needed to complet the table. and all stone were gone. (sorry for my bad english, i hope u understand me :)   )

s

**Comment by MarjieAVolk** [comment]
I understand :)

Is it possible that a different crafting table took the stone out of the stockpile first?  If someone else has access to the stockpile for example, they might have linked the stockpile to a table.

**Comment by MightyMi124** [comment]
no, i was alone and i only had just one stockpile and one crafting table. 
the game just eat my stones...

**Comment by MarjieAVolk** [comment]
Okay, well if the stone is disappearing from stockpiles, that is very bad.  But I am suspicious, since we haven't seen any other reports of this.

Is there anything else going on in your setup that might be relevant to the issue?  Just to triple check, you're sure that you didn't have a second project on your crafting table that required stone?

**Comment by MightyMi124** [comment]
Sorry about that. 
It was my first game. So i used the original setup from the game. 

I hadn't a sec project on my crafting table. at this moment i didnt knew that i could create more than one crafting-project at the craftingtable.

**Comment by MarjieAVolk** [comment]
Okay, glad you figured it out :)  Do you have any suggestions for how to make it more clear what happened?
