### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by Flappies** [StrangeLoopGames/EcoIssues#5425]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Connection failed  loading local game.
I was able to load the game a few times, but now I get a "Connection Failed" error

**Expected behavior:**
It should have loaded the game fine

**Actual behavior:**
Connection Failure

**Comment by MarjieAVolk** [comment]
The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server' and also 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

* Deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Run the server via the Eco Server tool
