### ISSUE TITLE
USER ISSUE: Automatic Teleport Wood Cart on Mountain

### ISSUE THREAD

**Issue by Dangermouse86** [StrangeLoopGames/EcoIssues#5426]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Hello,
I've dug a mine and whenever I put my cart in the same zone
in the mine, the cart will teleported horizontally up the mountain.
Through the mountain.

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4461

I believe this is being worked on now.
