### ISSUE TITLE
Law action: Mint currency

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#5428]
Create a legally preventable PlayerAction for minting currency.

**Comment by Amphysbaenas** [comment]
the idea is to manage the volume of currency in circulation by a way.
![image](https://user-images.githubusercontent.com/29807119/37002162-14708608-20c9-11e8-82ec-6e43b63b88c5.png)
on this picture i triyed to limit the creation of money but it's not possible.
if we don't have responsible player, volume total grow and value of money decrease.

**Comment by AndyClausen** [comment]
How did you make that @Amphysbaenas ? I'd like to use that myself :P

**Comment by MarjieAVolk** [comment]
Added but won't be released for a while - probably in 8.0
