### ISSUE TITLE
SkillModifiedValues.cs returning -2 as default for SkillLevel

### ISSUE THREAD

**Issue by mariowenig** [StrangeLoopGames/EcoIssues#543]
http://ecoforum.strangeloopgames.com/topic/829/learning-the-cooking-skill/5

Code: Server\Eco.Gameplay\Skills\SkillModifiedValues.cs
int SkillLevel(Player player) => player.Skill(this.SkillType)?.Level ?? -2;

Which following his SS results in
return Text.Error($"Your {skillName} is too low to craft this.)" + Text.Subtext($"\n(Current level: {Text.Skill(this.SkillLevel(player).ToString())}. Required level: {Text.Skill(this.MinLevel.ToString())})\n"));

**Comment by mariowenig** [comment]
Reproduced:
Learned Cooking Skill (initial learn showed Campfire available to craft)
After relog, Skills does not show Cooking Tab, and in Workbench shows -2 for Cooking Skill.

**Comment by mariowenig** [comment]
By user: @Nappelinis I recreated the situation and SOLVED it. Not sure if the fix has been posted somewhere but when you create the cooking book from the Research table make sure you MOVE the book into your inventory and THEN create a scroll- Right Click the scroll to learn Cooking. Then it showed up in my Skill Tree this time.

**Comment by metachronism** [comment]
fixed in latest
