### ISSUE TITLE
USER ISSUE: "Claim Property" Tutorial bug

### ISSUE THREAD

**Issue by fame1991** [StrangeLoopGames/EcoIssues#5430]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Use all your Property Claim Flags and then start Tutorial Claim Property Flag	

**Expected behavior:**
Tutorial completed	

**Actual behavior:**
Tutorial not completed. Due to the lack of claim flags its not possible to finish tutorial

**Comment by johnkslg** [comment]
Changed the tutorial to come up when you select a property claim.
