### ISSUE TITLE
Single Player Difficulty Broken

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#5431]
![image](https://user-images.githubusercontent.com/18184943/36997887-f8bdf94e-206f-11e8-943c-53e5881160e5.png)

It also does not apply the basic settings when a server is started.

**Comment by MarjieAVolk** [comment]
Mer this connection ui, I have fixed it so many times.

**Comment by MarjieAVolk** [comment]
I can do it

**Comment by MarjieAVolk** [comment]
Fixed in staging
