### ISSUE TITLE
USER ISSUE: I'm stuck

### ISSUE THREAD

**Issue by Kaetzchensprung** [StrangeLoopGames/EcoIssues#5433]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I got pushed into a mason table because I was standing next to it and a wall and put a shovel of sand above me. It pushed me aside and into the table. Now I cannot move. I also cannot remove the table because it is working on mortar and I cannot clean it out because already carry too much mortar. 	

**Expected behavior:**
Not get me stuck

**Actual behavior:**
Got me stuck. Can't move anyplace.

**Comment by MarjieAVolk** [comment]
You can use /unstuck to get out.

@SeanAtr0n I believe you recently added depenetration stuff to the character controller - would that help in this case?

**Comment by SeanAtr0n** [comment]
should be fixed now
