### ISSUE TITLE
USER ISSUE: EXP Bar full and dont resets

### ISSUE THREAD

**Issue by lefavilla** [StrangeLoopGames/EcoIssues#5434]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Level up on a dedicated server by day end

**Expected behavior:**
it should reset to 0 on the next level and the blue should become empty

**Actual behavior:**
it stays full and blue

**Comment by MarjieAVolk** [comment]
Does the problem go away if you log out and back in?

**Comment by lefavilla** [comment]
Yep

Am 06.03.2018 00:21 schrieb "MarjieAVolk" <notifications@github.com>:

**Comment by craig-jong** [comment]
should be fixed in the latest staging
