### ISSUE TITLE
USER ISSUE: No multiple currencys possible

### ISSUE THREAD

**Issue by FuJa0815** [StrangeLoopGames/EcoIssues#5436]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Build two mints
2. Place one down and rename the currency
3. Place the second one, the name will be copied

**Expected behavior:**
There should be created another currency

**Actual behavior:**
There's still only one currency

**Comment by Amphysbaenas** [comment]
+1

**Comment by MarjieAVolk** [comment]
When you crafted the two mints, did you put them into the same stack?  I think there were some problems because Mints were allowed to stack; in the next release, they will not be allowed to stack, so it may already be fixed.

**Comment by craig-jong** [comment]
This isn't on staging, is it?

There is a bug where Mint items weren't tagged as unique so they were being pulled from the master item list and picking one up would write the currency ID to EVERY mint item. I fixed that in staging. 

@Amphysbaenas this was also added in the latest staging build. You should soon be able to back currency with any non-perishable resource.

**Comment by FuJa0815** [comment]
@MarjieAVolk yes, I did stack the mints

**Comment by MarjieAVolk** [comment]
Sounds like this is fixed in 7.2 then.
