### ISSUE TITLE
Meteor only seen at an angle, not directly

### ISSUE THREAD

**Issue by jhadred** [StrangeLoopGames/EcoIssues#544]
Dev server, 20 days till meteor
Can see meteor out of the "sides of one's eyes" but nothing appears when directly facing.
Wasn't sure if this was https://github.com/StrangeLoopGames/EcoIssues/issues/328 regarding (temporary) transparent meteor or a different issue.

![ssemeteor](https://cloud.githubusercontent.com/assets/20424793/17273341/4cfb848e-567f-11e6-8d3b-fd9081219fab.jpg)
![semeteor](https://cloud.githubusercontent.com/assets/20424793/17273343/509369a4-567f-11e6-9430-1471c4dbea7d.jpg)
![emeteor](https://cloud.githubusercontent.com/assets/20424793/17273345/532b2134-567f-11e6-8626-54a76796c8f4.jpg)
![nemeteor](https://cloud.githubusercontent.com/assets/20424793/17273350/6ea6af00-567f-11e6-956c-29416b0cfb2f.jpg)
![nnemeteor](https://cloud.githubusercontent.com/assets/20424793/17273351/73fc43c0-567f-11e6-82ee-f25d2696a7c1.jpg)

**Comment by metachronism** [comment]
its clipping through the skydome, is adjusted in alpha 5
