### ISSUE TITLE
You can log in twice 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#5440]
You can be logged in both through steam and standalone at the same time with the same account.

**Comment by MarjieAVolk** [comment]
So the accounts are linked?

**Comment by MarjieAVolk** [comment]
Not sure if this is web side or game side.

**Comment by Nanders** [comment]
The accounts were linked

**Comment by craig-jong** [comment]
I just got kicked out for invalid token after a while of being logged in on both.
