### ISSUE TITLE
Law action : Skill Scroll / Skill book

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#5441]
It would interesting to force people to search for skill book and have a skill scroll and unallow them to sell or give/exchange book or scroll. Knowledge have a cost it's not just clic clic clic i have knowledge and full property claims.
Why , because people always forgot to integrate the price of search and devellopment in the final price of what they sell , so it's important to allow by law the ability to block sharing knoledge.
Other effect, people don't search for paper or townhall item because useless, they have just to ask for other skill scroll.

You can not learn a skill if you don't search it. You can not search a skill if it's not your profession.
We will not see mason searching chief skill just to have property claims for exemple :)

**Comment by Kastuk** [comment]
May just fix that law clause Action Craft where Skill scroll will check action of Using of Skill Book and not be useless clause as it is now.

**Comment by MarjieAVolk** [comment]
So what you want is a law action 'Use Skill Scroll'?

**Comment by Amphysbaenas** [comment]
Exemple if we limit to 2 professions (survivalist + mason for exemple)
People will not have to be able to craft skill book if that is not in their specialisation branch.
(why a manson need to search for a skill from chef ???)
People will not have to be able to use a skill craft if they have not unblock the profession.
(Same but to block free skill scroll gift by other or sell by other)
People wil not have to be albe to use a skill craft if they hove not made the research for it.
(Important in economy to force people understand cost of search and devellopment, and have a circular economy)

It's an important way to protect knowledge / economy and cooperation between players.
Stop omnipotent players we never see a mason chef enginner IRL

**Comment by MarjieAVolk** [comment]
Okay this is a very delayed response, but I think I got it now.  What you want is a way to prevent buy/sell for all skill books or skill scrolls.  So what you want is like categories of items that you can query on in laws.  Okay I agree, sounds good :)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#418
