### ISSUE TITLE
USER ISSUE: Will not show more than 3 Worlds in Load List

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#5442]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
have more than 3 Worlds in Storage Directory
![snap1889](https://user-images.githubusercontent.com/29383891/37004176-7e5df94e-20c7-11e8-88fb-95deece30832.png)

**Expected behavior:**
it should let me scroll up and down the list

**Actual behavior:**
just sits there showing first 3 Worlds in the List

![snap1888](https://user-images.githubusercontent.com/29383891/37004110-4b4fa700-20c7-11e8-98f4-ab4f8defefce.png)

if you move the Mouse wheel it just jumps the list screen up and down a bit
if you use the Cursor up and down keys it looks as if it is going through the list but you cannot see it to verify

**Comment by metachronism** [comment]
fixed, added a scrollwheel and whatnt
