### ISSUE TITLE
USER ISSUE: Storage Issues

### ISSUE THREAD

**Issue by Deathuponu** [StrangeLoopGames/EcoIssues#5443]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Putting items into your storage

**Expected behavior:**
It should be placed with the picture there, the number etc.

**Actual behavior:**
instead it, turns invisible, it says how many are in there but you just cant see the picture

**Comment by MarjieAVolk** [comment]
Is this also like #3841?  Do you have icons floating on the screen?

**Comment by MarjieAVolk** [comment]
Closing as duplicate of #3841 since there was no response.
