### ISSUE TITLE
USER ISSUE: Quest~ Remove Marker From Map.

### ISSUE THREAD

**Issue by Deathuponu** [StrangeLoopGames/EcoIssues#5445]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. You are able to do everything in the quest except the last task, "Click on the marker to pull up more options and remove it"

**Expected behavior:**
Should be able to remove the marker.

**Actual behavior:**
Instead it, does not allow you to remove it, keeping the marker forever on the map until you move it. You can never 'remove' it.

**Comment by johnkslg** [comment]
Verified working in staging
