### ISSUE TITLE
Long strings for worldmarkers push worldmarker off of position on the minimap

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#5446]
We probably need to limit max input length on most of our UIs in general

![image](https://user-images.githubusercontent.com/6262198/37005349-9eb2d438-2088-11e8-8934-4942c4d95be4.png)
*Extreme example* actual point is somewhere in the middle of that string.

**Comment by johnkslg** [comment]
Capped to 35
