### ISSUE TITLE
Contracts let you put in more items than needed to containers

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#5450]
Also note:

The contracts system will currently allow you to put in more items than requested. For example:

You accept a "Harvest Field" contract on a Wheat field.
You already have 10 Wheat in your inventory.
You harvest a further 20 Wheat from the field.
The Contract system will expect you to deposit 20 Wheat into the nominated Chest / Stockpile.
You can deposit 30 Wheat into the chest.
You should only be allowed to deposit 20 Wheat.
When implementing a fix for this issue - the permission should be to INSERT INTO or REARRANGE the Contract inventory. I.e, if there are two stacks of 40 Wheat in a chest, the Contractor should be allowed to combine those into one stack of 80 Wheat.

**Comment by Therandus93** [comment]
just as a side note, i actual abuse this fact for hewn log and lumber conversions systems using contracts. Sometimes i allow more than the set amount. Would be sad if that gets removed becuase then i would need different contracts for different amount and i dont particularly like it when you have a long list of completed contracts next to your name lagging you. Though i guess that is a different issue.

**Comment by johnkslg** [comment]
It now restricts to the max amount.
@Therandus93 long list of contract names shouldnt lag.  But variable rates on contracts is something I'm planning to implement, so that should address this need. Closing this issue as the root bug is fixed!
