### ISSUE TITLE
USER ISSUE: Wtf

### ISSUE THREAD

**Issue by toots89** [StrangeLoopGames/EcoIssues#5452]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

La référence d'objet n'est pas définie à une instance d'un objet.

Stack:
   à TreeEntity.PickupLog(Player player, Guid logID)
   à TreeEntity.OnActInteract(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

La référence d'objet n'est pas définie à une instance d'un objet.


Stack:
   à TreeEntity.PickupLog(Player player, Guid logID)
   à TreeEntity.OnActInteract(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment]
This will be fixed in 7.2
