### ISSUE TITLE
[Suggestion] Making Ecosystem: tooltip easier to find like we have for Inventory

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#5453]
as it stand if we have loads of text in chat this option disappears and is hard or maybe impossible to find
![snap1894](https://user-images.githubusercontent.com/29383891/37009244-042f1420-20de-11e8-9150-16f2058fd944.png)

maybe have it in a fixed place like the Inventory Tooltip as that is always easy to find and get information about.
![snap1895](https://user-images.githubusercontent.com/29383891/37009284-2a0429ce-20de-11e8-80ea-9701891c7d94.png)

possibly add it in the mini map pullout, or bottom right of the screen where the Other information is

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#214
