### ISSUE TITLE
USER ISSUE: Fishing

### ISSUE THREAD

**Issue by Deathuponu** [StrangeLoopGames/EcoIssues#5458]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Reeling in the fish works~ Besides seeing the fix glitch and spaz everywhere... but it will dissapear until you relog.

**Expected behavior:**
Proper behavior~ Should just go straight into my inventory like hunting animals does.

**Actual behavior:**
Instead~ Sometimes it will appear in your inventory or storage (The fish you had 'caught' earlier) and it will glitch everything out. It will freeze that specific slot, and if you try and switch it with anything else (moving it around) it will usually break. I've figured out that logging out is the best way to fix this.

**Comment by MarjieAVolk** [comment]
Fish disappearing until relog will be fixed in 7.2 (https://github.com/StrangeLoopGames/EcoIssues/issues/4588)
