### ISSUE TITLE
Friends cannot see server in server listing

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#5459]
User says:
I can not start an online server. The server file starts running, but the IP stays on 0.0.0.0 and unseeable in the "Join" section in the game.

**Comment by MarjieAVolk** [comment]
What does is meeeean

**Comment by rainfarmer** [comment]
User runs a server.
Friends cannot see server in server listing.
server says its ip 0.0.0.0 but when using their computer ip, it says "invalid"

**Full chat:**
I have several problems with it:
  Firstly, when I try to start a new map (does not matter if I choose "not to generate new") it crashes.
  Secondly, I can not start an online server. The server file starts running, but the IP stays on 0.0.0.0 and unseeable in the "Join" section in the game.
  Finally, there is an option on steam to join to another's game and it is also not working.
  Thanks for your help in advance.

I don't have any error message, simply I cannot make any server.
And I found another problem when I copy my IPv4 (176.63.xx.xxx) to change it in the server menu, it says that it is "invalid".
Thank you for help.

**Comment by rainfarmer** [comment]
+4 had a few complaints on this issue:
Friends cannot see server in server listing.

**Comment by futuretman** [comment]
+1

**Comment by MarjieAVolk** [comment]
What does "the IP stays on 0.0.0.0" mean?

**Comment by MarjieAVolk** [comment]
Wait, are they editing the IpAddress field in the server Network tab?  I would tell them to set that field back to "Any", which is the default.

**Comment by MarjieAVolk** [comment]
If this one person is having trouble with their ip address, it's unlikely that any of the other "+1" are the same issue.

**Comment by MarjieAVolk** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/6071

**Comment by rainfarmer** [comment]
I think @metachronism said that the ip displays as 0.0.0.0 is normal,
If so, I think the user was just confused by it.

Common issue for all complaints is that their server does not show up in the server list.

+1 another for that

**Comment by metachronism** [comment]
resolved as of networking rewrite 7.4+
