### ISSUE TITLE
USER ISSUE: Wood Pulps

### ISSUE THREAD

**Issue by Deathuponu** [StrangeLoopGames/EcoIssues#5461]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Collecting them after the tree has fallen...

**Expected behavior:**
Should remove it completely from the ground... putting it into your inventory.

**Actual behavior:**
Instead~ It SOMETIMES, (about 50/50 tbh) will stay in the same spot after collecting it, and no longer have the green outline, but forever staying... 

**Screenshots**
https://steamuserimages-a.akamaihd.net/ugc/934932623005444390/5D8D9EC84EA25A10D673FCCAFF06B6D161E9B568/
https://steamuserimages-a.akamaihd.net/ugc/934932623005444188/F2005A768EF95B0A73418A4BCD0932E21AC98315/

**Comment by metachronism** [comment]
this is a chunk build issue, should be resolved as of 7.3
