### ISSUE TITLE
Servers are confusing default ports?

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#5462]
We have had a problem recently, seems  to be happening more and more, where the players have to connect via IP:gameport instead of IP:webport.  We will get a server with ports forwarded and firewall configured and this can be tested and the ports are open.... but a steam invite fails and the players friends cannot  join by IP:WebPort.  If they then have them try using IP:gameport the connection will be made and the players can join.

**Comment by metachronism** [comment]
its always ip:webport, gameport is not used when trying to get anyone to join
the port shared via steam join is always the webport
