### ISSUE TITLE
USER ISSUE: Invisible Wall

### ISSUE THREAD

**Issue by Gamingcml** [StrangeLoopGames/EcoIssues#5463]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I choped a tree but it seems like the tree stump is still there. I cant see the stump, i restarted the game but i still cant pass that block.

**Expected behavior:**
I could easily pass

**Actual behavior:**
invisible block

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4908
