### ISSUE TITLE
Wind Turbine Mesh-- Collision Doesn't Match

### ISSUE THREAD

**Issue by Landona24** [StrangeLoopGames/EcoIssues#5464]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Place Wind Turbine
Stand ontop
jump to the sides of the blades

**Expected behavior:**
Blade world objects to be animated similar to the windmill

**Actual behavior:**
Rather the physical object of the blades do not animate

**Comment by keegan-o** [comment]
Collision is not going to be animated on skinned meshes most likely, but we may switch this to sub-mesh anyways so I'll leave it open till then.

**Comment by keegan-o** [comment]
fixed in staging
