### ISSUE TITLE
USER ISSUE: campfire cant empty

### ISSUE THREAD

**Issue by purpleypete** [StrangeLoopGames/EcoIssues#5469]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
4 campfires loaded with 999 fish and chests and wooden cart connected.
left overnight to cook.
make sure there is not enough chests to load into.

**Expected behavior:**
upon emptying chests the fish should auto move into the chest.

**Actual behavior:**
fish amount in campfire shows [-] in picture box,
and you cant move the fish out the campfire.

**Comment by purpleypete** [comment]
[https://imgur.com/a/KQiej](url)

**Comment by purpleypete** [comment]
[https://imgur.com/a/KQiej](url)

**Comment by purpleypete** [comment]
[<blockquote class="imgur-embed-pub" lang="en" data-id="a/KQiej"><a href="//imgur.com/KQiej"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>](url)

**Comment by shulrak** [comment]
The link doesn't work.

**Comment by purpleypete** [comment]
just copy paste wont work on this site
https://imgur.com/a/KQiej

**Comment by MarjieAVolk** [comment]
Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/3240

Did you get any of the fish?  Did it output all but the last one?

**Comment by MarjieAVolk** [comment]
Closing as duplicate of #3240, since there was no response
