### ISSUE TITLE
Singleplayer server fails to start if path contains an apostrophe

### ISSUE THREAD

**Issue by ExoSonic83** [StrangeLoopGames/EcoIssues#5472]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Could not start server: ApplicationName='D:/Dan's Games/steamapps/common/Eco/Eco_Data/Server/EcoServer.exe', CommandLine='-nogui -loadSave="The Beginning" -maxslots="1" -specialtyMultiplier="0" -skillGainMultiplier="24"', CurrentDirectory='D:/Dan's Games/steamapps/common/Eco/Eco_Data/Server/'

**Comment by imthe666st** [comment]
Hello,
the issue seems to be because one of the folders has an apostrophe in it. You could download the game from the website and put it in a directory without an apostrophe in it.

**Comment by MarjieAVolk** [comment]
Was this an error message you saw while running the game?  Or were you trying to start a server from the command line?

**Comment by metachronism** [comment]
this still happens as of 7.5.1
