### ISSUE TITLE
USER ISSUE: Crash when place stone atop of storage

### ISSUE THREAD

**Issue by EkoGuandor229** [StrangeLoopGames/EcoIssues#5478]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I have 6 stockpiles in my world, 4 of them right next to each other and next to my mine	where i store tailings. since i need a lot of space for tailing deposit. I started to put stones on top of the stockpile when suddenly the stones stopped to be placed and instead vanished. a second later the game crashed	

**Expected behavior:**
place the stone bits in front of me	

**Actual behavior:**
decreased the stone count, vanished the stone and then the game crashed.

**Comment by EkoGuandor229** [comment]
it happened again after i was able to lay another plateau of stones on top of the stacks. this time i was able to lay 4 stones which dissapeared before the game crashed. hope this helps

**Comment by MarjieAVolk** [comment]
Is this your own local world?  Can you attach any crash files in '[...]\steamapps\common\Eco Server'?

**Comment by EkoGuandor229** [comment]
I play on a local world. Hope this helps


[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1793552/Dump.zip)

**Comment by metachronism** [comment]
need a save repro case for this, sorry for late reply :/
if you manage to have this happen again and can attach the save file, please reopen
