### ISSUE TITLE
When I propose a new law, I get 'This law does not exist' error

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#5479]
The law is created fine, but I see this:
![image](https://user-images.githubusercontent.com/23460210/37050285-52bf2f22-2128-11e8-8685-048aa2bdbcc7.png)

**Comment by rainfarmer** [comment]
This is a error that comes up in debug, when you are not logged in fully.

**Comment by MarjieAVolk** [comment]
In that case, how and why do I become 'not logged in fully'?  Seems like this state is related to a lot of issues.
