### ISSUE TITLE
USER ISSUE: Can't move after renaming Chest

### ISSUE THREAD

**Issue by grappyX** [StrangeLoopGames/EcoIssues#5482]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Open Chest with 'E'
Click on Rename-Button and Rename it
Enter the new name with 'Enter'
Exit Chest with 'Esc'

**Expected behavior:**
Be able to move or interact with things

**Actual behavior:**
Stuck on point
Cant use keys or mouse as Input
Only Dissconect and Re-connect help

**Comment by FuJa0815** [comment]
Same thing always happens to me..

**Comment by MarjieAVolk** [comment]
Fixed in 7.2
