### ISSUE TITLE
USER ISSUE: Room designation Broken

### ISSUE THREAD

**Issue by Mikerium** [StrangeLoopGames/EcoIssues#5483]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Created a 5x5 room to put research table in.
Placed a bed (which has a placeholder icon of a barrel)

**Expected behavior:**
Not effected the room	

**Actual behavior:**
Make the research table claim that the room is no longer a room and had to pick up and re-put down the research table.

**Comment by johnkslg** [comment]
Fixed
