### ISSUE TITLE
USER ISSUE: Cannot start a single player game

### ISSUE THREAD

**Issue by Basili0** [StrangeLoopGames/EcoIssues#5485]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Create a new game

**Expected behavior:**
It should start, but it doesn't

**Actual behavior:**
```
Connection Failed

**Comment by Basili0** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1786450/output_log.txt)

**Comment by MarjieAVolk** [comment]
From the output log, it looks like your server is crashing.  Can you find any crash files for the server, in '[...]\steamapps\common\Eco Server'?

**Comment by Basili0** [comment]
The folder you mentioned does not exist. However, there are several dumps in \\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Server\Dump
[dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1791837/dump.zip)
As a follow-up, I have cleared the download cache for Steam client, and also removed the folder %AppData%\LocalLow\Strange Loop Games
Not sure which one of these helped, but the game started after that. Probably this issue may be closed as the game started after all.

**Comment by MarjieAVolk** [comment]
Great!  From your dumps, it looks like you were having a locale problem, which I think we fixed in 7.2, so it may be that the update fixed your problem.
