### ISSUE TITLE
USER ISSUE: Reconnection issue after renaming a chest.

### ISSUE THREAD

**Issue by Rainemakerx** [StrangeLoopGames/EcoIssues#5487]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Rename a chest
2. Controls are locked from the chest being renamed
3. Disconnect to clear the error
4. Unable to reconnect

**Expected behavior:**
Allowed me to reconnect, actually it should have just let me rename the chest.

**Actual behavior:**
Unable to reconnect. Server appears to still be functioning.

**Comment by MarjieAVolk** [comment]
Fixed in 7.2
