### ISSUE TITLE
USER ISSUE: Keyboard not responding after renaming

### ISSUE THREAD

**Issue by cray935** [StrangeLoopGames/EcoIssues#5488]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. open a storage box
2. rename it and press enter
3. leave the storage box

**Expected behavior:**
Keys responding (walk, interact, etc.)

**Actual behavior:**
Keys not responding (the "report a bug" does work)

**Comment by imthe666st** [comment]
Possible duplicate to #5482

**Comment by MarjieAVolk** [comment]
Fixed in 7.2
