### ISSUE TITLE
Carts flying away

### ISSUE THREAD

**Issue by 42656e** [StrangeLoopGames/EcoIssues#5492]
The first hours of the game everything worked fine.
But then suddenly a wooden cart just flew away and drifted through space. Since this incident, just every cart eventualy does the same thing. There are no special steps to perform. It just happens when the cart is standing around.

**Comment by SeanAtr0n** [comment]
should be fixed in 7.2

**Comment by 42656e** [comment]
Problem still occurs in 7.2.1

**Comment by 42656e** [comment]
Today the cart started like a rocket while I was driving it. I flew with the cart very high and after that fell to the ground again. So the problem occurs not only if the cart is unoccupied.

**Comment by 42656e** [comment]
I think I found the problem. The problem is not the carts itself but other objects. Today I saw a stone block falling out of the sky straight to the cart. The cart then flew up and the stone block disappeared. It seems like some blocks of my world are a bit buggy. Maybe a command to delete all loose objects (those which have never been picked up) in the world would help.

**Comment by SeanAtr0n** [comment]
should be fixed in 7.3, cart physics now sleeps when unused
