### ISSUE TITLE
USER ISSUE: Connection failed 

### ISSUE THREAD

**Issue by maietrifo** [StrangeLoopGames/EcoIssues#5494]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. the game Eco crash after big drop fps 
2. my computer have bleu screen
3/ i reboot but i dont see "continue"
4: i cant 'join a server" or favorite server (i can read offline, or he's online...)
5: i try to create a new game, but i cant... and i can read cannection failed

**Expected behavior:**
Connection failed 

**Actual behavior:**
Connection failed, but i could play before the crash. i sheck my port but they are open.

**Comment by MarjieAVolk** [comment]
To fix your immediate problem, try deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO.  Let me know if that helps.

**Comment by MarjieAVolk** [comment]
Closing due to no response
