### ISSUE TITLE
Extended mining creates freeze frame in moving dirt/stone (maybe others)

### ISSUE THREAD

**Issue by mariowenig** [StrangeLoopGames/EcoIssues#550]
When doing long term mining of dirt/stone (possibly others) the action of placing them into an inventory becomes progressively longer. Not sure how many actions need to be performed for this to become noticeable. The longer you keep mining without relog the longer each action becomes. Becomes noticeable when the freeze frame hangs for about 2s, from there on it just gets longer and longer until user is required to relog (which fixes the issue entirely) until of course it returns after more mining operations being performed.

Current hack/fix.
Relog creates a reset for the issue.

Reproduction: 
Long term mining and moving of dirt/stone into cart (other users experienced this without carts. regular inventories)

Note:
usaf_techguy (on slack) reported this happening without the involvement of inventories, plain moving of dirt/stone from one place to another.

**Comment by selrahc13** [comment]
I've observed the same issues, and if you don't relog and continue moving objects in the environment, the lag time slowly increases. At one point the lag time became long enough that my server kicked me for inactivity (30s)

**Comment by metachronism** [comment]
should be fixed in alpha 5
