### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Izzy761** [StrangeLoopGames/EcoIssues#5503]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
Scrolled to a beet seeds (2) in the hotbar.
Walked up to a chest that was known to have beet seed's.
right clicked chest to auto drop.

**Expected behavior:**
item remove from hotbar ans placed in chest.

**Actual behavior:**
Caught exception. object reference no set.
stack at eco.gaemplay.items,inventory.moveasmanyitemsas

**Comment by SeanAtr0n** [comment]
fixed in 7.2.1
