### ISSUE TITLE
[Server] World Conversion Error 0.7.1.2 -> 0.7.2.0

### ISSUE THREAD

**Issue by frenchy128** [StrangeLoopGames/EcoIssues#5507]
I'm reporting this as the release notes advised of no issues with migrating the worlds, so I felt compelled to post this bug. I haven't seen any other reports of this, I do apologize if I couldn't find it. I've included a link to the Game.eco (zipped) if it helps. 

Steps to reproduce: 
1) Update Eco installation via Steam from 0.7.1.2 to 0.7.2.0
2) Created a backup of my 0.7.1.2 world into a seperate folder (copy game.eco to a backup folder)
3) Launce Eco Server.exe
4) Error generated.. 

https://www.loosestring-designs.ca/Game.zip

Thanks
JF

[Crash AggregateException 03064554.log](https://github.com/StrangeLoopGames/EcoIssues/files/1787424/Crash.AggregateException.03064554.log)

**Comment by frenchy128** [comment]
[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1787473/DxDiag.txt)

**Comment by MarjieAVolk** [comment]
We are supporting migration from 7.1 to 7.2.  Have you confirmed that Clay's Mod was the issue?
