### ISSUE TITLE
7.2.0 - Pump Jack GUI Bugged

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#5516]
![pumpjackgui](https://user-images.githubusercontent.com/2582909/37071040-3c8786e8-2180-11e8-9ac9-f2b4424a3c66.jpg)

**Comment by MarjieAVolk** [comment]
After you have just open this UI and seen this error, can you send me your output log? C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt

**Comment by MarjieAVolk** [comment]
@craig-jong as it looks like world layer stuff.  And @SeanAtr0n as there's a bunch of avatar stuff in there too?

**Comment by SeanAtr0n** [comment]
Fixed in 7.3.2
