### ISSUE TITLE
7.2 - Server CPU usage spiking to 100%

### ISSUE THREAD

**Issue by DavidWFarley** [StrangeLoopGames/EcoIssues#5518]
Myself and several users in the support chat are experiencing CPU usage spiking to 100% on powerful, dedicated machines that were previously running smoothly.  Cannot determine repro steps.

**Comment by rorti** [comment]
I have the same problem

**Comment by notorioushaze** [comment]
Same happened here, there seems to be an error that happens to cause the CPU to spike. A restart was able to fix the cpu issue. At least temporarily.

**Comment by squished-01** [comment]
Same.  Server is 107.152.100.58 if you want to check it out.  It was a 4 day old, 1 km x 1 km 7.1.2 world.  we have a fairly steady 20 players or so online.  The game is unplayably laggy.  Ping times are 10000-15000.  We set everything to false in stats.eco and restarted, no good.

**Comment by B1sounours** [comment]
Same problem, the server was fine for the first hour and someone got a few MoveAsManyItemAsPossible exception and it started to lag a few minute after

**Comment by SeanAtr0n** [comment]
fixed in 7.2.1 (hopefully... reopen if not)

**Comment by B1sounours** [comment]
Still happening
