### ISSUE TITLE
USER ISSUE: Charred fish efficiency

### ISSUE THREAD

**Issue by Vezio58** [StrangeLoopGames/EcoIssues#5524]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
The Charred Fish recipe moved to Campfire Cooking but the efficiency is still listed as Campfire Creations Efficiency.

**Expected behavior:**
I imagine the efficiency should've been changed to Campfire Cooking Efficiency.

**Actual behavior:**
The efficiency is still using Campfire Creations efficiency as if the recipe hasn't moved.

**Comment by craig-jong** [comment]
Should have been fixed in a hotfix
