### ISSUE TITLE
USER ISSUE: Crash on Candle Removal while fuel source present

### ISSUE THREAD

**Issue by notorioushaze** [StrangeLoopGames/EcoIssues#5525]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
1. Place down Tallow Candle
2. Pull out hammer
3. Add fuel sorce to Tallow Candle
4. Remove Tallow Candle with Hammer.

**Expected behavior:**
Shoulder either not let you remove it, or remove and add the fuel source back to inventory

**Actual behavior:**
Hard crash to Main Menu with Exception Caught.

**Comment by SeanAtr0n** [comment]
fixed in 7.2.1
