### ISSUE TITLE
Road efficiency drop to 0% (0\zero speed on ramp)

### ISSUE THREAD

**Issue by lemarkis** [StrangeLoopGames/EcoIssues#5532]
**Version:** 0.7.2.0 beta staging-f6bf50db

**Steps to Reproduce:**
1. Walk pulling a wood cart (especially on top of ramp or when block change from one type to another)

**Expected behavior:**
Road efficiency should not have drop to 0% and so, not slow down player.

**Actual behavior:**
Road efficiency drop to 0% causing player to slow down and sometimes stop.

**Comment by FuJa0815** [comment]
Sometimes, when the server is laggy the same thing happens

**Comment by elfl0rd** [comment]
Still happens in latest versions...

**Comment by Fireboss4** [comment]
This is still happening in 7.8.8

**Comment by elfl0rd** [comment]
Comment from @redwyre 

https://drive.google.com/open?id=1SqVqZt87KFXbPwr7aBrMPT_9agbWXCaC

If you watch the UI in the bottom left, the speed sometimes changes to 0 which momentarily stops the cart, then changes back to 1 and I can move freely again.
