### ISSUE TITLE
[7.2-beta] "Connection Failed" being caused by Servers that are showing online and connectable when they are still building/loading

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#5535]
Servers are showing in the browser as online and with a "connect; button even if still in the world generation process and/or loading the game.  To people looking at the browser the server appears to be up and ready to accept players.  they then try to connect and a get a subsequent "Connection Failed" error message and assume that there are issues with their client.  If they wait for information that the server is actually ready to receive players , ie the world is built/loaded and server UI is up they are able to login without issue.  There are also associated crashes happening due to this when players keep attempting to access a server with a "connect" button (link) it is in some cases causing the server to crash with a network error.   This was an old problem we had some many versions back where the server would appear online in the browser and it was not yet ready to take players.  this maybe what is generating the high number of support issues for "Connection Failed" errors on servers that had no issues before the patch for players that had no issues before the patch either.

**Comment by metachronism** [comment]
Just verified this is not possible, the server does not listen for connections until the server is completely booted up

**Comment by MarjieAVolk** [comment]
What if it's the Continue server?
