### ISSUE TITLE
Masonry page doesn't give you the skill, but still gives you land tags.

### ISSUE THREAD

**Issue by troxtrot** [StrangeLoopGames/EcoIssues#554]
As the title states, when using the masonry book crafted from the research bench, it gives you the page. But when you use this page, it says it gives you the skill in the text box, gives you the 5 land tags, but then doesn't actually give you the skill.

**Comment by bonzaii** [comment]
I believe it just unlocks the Masonry skill rather than applying a point to it. Correct me if I am wrong, but I have gone past Masonry and definitely was able to craft items with that skill.

**Comment by troxtrot** [comment]
Is it supposed to show up with the other skills like when you use the
carpentry page for example? Because it doesn't show up with the rest.
Unless you can only have 6 total skills learned?

**Comment by bonzaii** [comment]
Make sure you check other tabs, not all skills appear as new tab. For example Steelworking goes under Smithy.

**Comment by troxtrot** [comment]
I just went through and checked all the tabs/trees within the skills, and I
did not find masonry anywhere.

**Comment by metachronism** [comment]
fixed in alpha 5
