### ISSUE TITLE
USER ISSUE: Caindo ao pegar itens

### ISSUE THREAD

**Issue by LimaLaranja** [StrangeLoopGames/EcoIssues#5543]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Referência de objeto não definida para uma instância de um objeto.

Stack:
   em Eco.Gameplay.Items.Inventory.MoveAsManyItemsAsPossible(Inventory destination, Func`2 sourceStackPredicate, User user)
   em Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   em Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   em Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   em Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   em Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   em Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   em Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   em Eco.Shared.Networking.NetPort.ProcessBuffer()
   em Eco.Shared.Networking.NetPort.Update()
   em Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Referência de objeto não definida para uma instância de um objeto.


Stack:
   em Eco.Gameplay.Items.Inventory.MoveAsManyItemsAsPossible(Inventory destination, Func`2 sourceStackPredicate, User user)
   em Eco.Gameplay.Components.StorageComponent.OnActLeft(InteractionContext context)
   em Eco.Gameplay.Intera

**Comment by SeanAtr0n** [comment]
Fixed in 7.2.1
