### ISSUE TITLE
USER ISSUE: plant

### ISSUE THREAD

**Issue by angelocheck** [StrangeLoopGames/EcoIssues#5544]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
1.I plant tomatoes, reboot the server, tomatoes grew by 100%.. This occurs after the last update. If you can fix this tell me where.

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4003
