### ISSUE TITLE
7.2.0 Client Bug Camo Shirt and Pants not showing.

### ISSUE THREAD

**Issue by MittenMarauder** [StrangeLoopGames/EcoIssues#5547]
**Server, Client or Website?** Client

**OS/Web Browser?** Win10

**Detailed Description of Issue:** Camo Shirt and Pants are not showing. Shows as if nothing is equipped. 

**Reproducible? How difficult is it to reproduce?** Yes. Equip Camo Shirt and Pants.

**Steps to reproduce bug/issue:** Equip Camo Shirt and Pants.

**Additional Comments:** N/A

**Client Version?** 7.2.0

**Include recent Crash dump ( get only generated if the server crashes):** N/A

**Comment by MarjieAVolk** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/3208
