### ISSUE TITLE
USER ISSUE: Logs have culling issues.

### ISSUE THREAD

**Issue by Tannyr** [StrangeLoopGames/EcoIssues#5550]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
Sometimes logs will have an invisible inner wood side when rolling off other obstacles.

**Expected behavior:**
A texture to always be visible

**Actual behavior:**
random invisible sides.  usually when the log is near a 45 degree angle i think.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5551
