### ISSUE TITLE
USER ISSUE: Tree slices have culling issues.

### ISSUE THREAD

**Issue by Tannyr** [StrangeLoopGames/EcoIssues#5551]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
Sometimes tree slices will have an invisible inner wood side when rolling off other obstacles.

**Expected behavior:**
A texture to always be visible

**Actual behavior:**
random invisible sides.  usually when the slice is near a 45 degree angle i think.

**Comment by MarjieAVolk** [comment]
Does this happen only with specific tree species?

**Comment by keegan-o** [comment]
Duplicate bug
