### ISSUE TITLE
USER ISSUE: Tree slices that are flat on the ground are difficult to chop

### ISSUE THREAD

**Issue by Tannyr** [StrangeLoopGames/EcoIssues#5552]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
let a tree slice fall flat on the ground.

**Expected behavior:**
slice section in half

**Actual behavior:**
you can only slice on the outside part of the tree (which makes sense) but you can waste all your energy trying to chop down the wrong part.

**Comment by FuJa0815** [comment]
Yes, it’s the same with cactus lying on the floor, sometimes it’s really difficult to slice.

**Comment by beastyn** [comment]
Shoud be fine now
