### ISSUE TITLE
Unable to place objects

### ISSUE THREAD

**Issue by OmegaTou** [StrangeLoopGames/EcoIssues#556]
On the Eco Springs server anytime I try to place an object, the object does not place, and I lose the ability to interact with any other object/tool. After about 15-20 Seconds I get booted from the server with the message, "Inactivity." I ran my own server locally, and on a different public server, and everything appeared to be working normally. The one exception to not being able to place items is that I can place one seed that doesn't grow before the same thing happens.

**Comment by metachronism** [comment]
should be fixed in alpha 5, some placement was pretty wonky
