### ISSUE TITLE
[Server Bug] Can't load serveur setting file

### ISSUE THREAD

**Issue by DevHoratio** [StrangeLoopGames/EcoIssues#5563]
Hi everyone,

I just started a new eco server on my personal computer based on windows.
After setting my parameters, I saved the configuration with "File --> Save as" and I named my file "server_config.eco"
But, when I want to load my config file ("File --> Open"), I don't see my eco file. I am in the good folder and the extension file is on Eco file.

Has anyone encountered the same problem? 

Thanks !

**Comment by MarjieAVolk** [comment]
Hey there, sorry we lost track of this bug.  Unfortunately I don't believe the File>Save options actually do anything right now.
