### ISSUE TITLE
USER ISSUE: Stockpile visual and sound delayed if in the air

### ISSUE THREAD

**Issue by Freddyterp** [StrangeLoopGames/EcoIssues#5566]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
1. be in the air by jumping
2. put a item in the stockpile

**Expected behavior:**
sound and visual should be 
immedi
ately

**Actual behavior:**
sound and visual is delayed by seconds

**Comment by Nanders** [comment]
This is only delayed as long as it takes to complete the interaction with the server
