### ISSUE TITLE
7.2.0 & 7.2.1 Desync Issue

### ISSUE THREAD

**Issue by Mystery16** [StrangeLoopGames/EcoIssues#5567]
Hey,

So not sure how much information I can provide here but the latest update has caused issues with players constantly desyncing and having to relog to the server. 

I had a server a week ago running a world twice the usual size with 5 people, not a single issue. 
That same server this week (with a new group of 5) couldn't run on that server without issues from the very start, nor on the new server we have now. 

I can't seem to find a link of what causes it as it happens from us doing anything from hunting, building, mining, etc.  From what we found though, it happened frequently when adding skill points though.

**Comment by MarjieAVolk** [comment]
This should be fixed in 7.2.2.
