### ISSUE TITLE
[7.2] World generation always missing something

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#5568]
World generation should really try to generate at least something of everything. I'm now trying to generate a new standard sized world in 7.2 since nearly an hour but everytime according to the Server UI "simulation tab" at least 2-3 plants are totally missing and/or some animals are already very underpopulated (had it various times for example that bisons where < 5)

Especially these have issues to get populated at all:
Creosote, Bullrush, Beets, Rice, Bison

Seems very hard up to impossible generating a world where everything is available

**Comment by Thyriel** [comment]
Ok, i've generated now like 30-40 worlds with standard size and now give up on that. Half of the time it seems theres whole biomes missing (especially desert or wetlands). I've not managed to generate a single world where not at least 2-3 plants where missing while others had populations over 15k.
Imho for people playing singleplayer this could be a gamebreaking issue they won't even realize until they progress quite a bit.

I'm now trying 100x100 worldsize and see if that can generate a playable world

**Comment by Thyriel** [comment]
100x100 now took me 15 tries until i had a world where not at least 1-2 important plants where missing. And then i still had a world with zero creosote and 2 bullrush. 

Next time you do something like "Tweaked worldlayer gen to have larger regions of biomes" you should probably not only focus on nice 16km² for theoretical 100 player worlds and test tweaked world generation for standard size too ;)

Also the height map seems to be pretty "shooting over the goal" in smaller worlds. This is how the height map looks almost everyhwere: http://steamcommunity.com/sharedfiles/filedetails/?id=1323063220
How are you supossed to build cities with huge mountains everyhwere ??

**Comment by MarjieAVolk** [comment]
By the way, I learned you can use '/regenlayer CriminiMushroom' to try to bring mushrooms to your world if they are missing.  You can do this with any species.  It will only work if there is an area in the world that is suitable for the species, but it might help.

**Comment by johnkslg** [comment]
Steam report: http://steamcommunity.com/id/inthenameofbubbles/recommended/382310/

**Comment by metachronism** [comment]
craig did this

**Comment by elfl0rd** [comment]
Okay.
0.7.7.2
![unknown](https://user-images.githubusercontent.com/4980243/46524061-51eafa80-c890-11e8-9144-af8ee4c51e93.png)

**Comment by TheLostBreadd** [comment]
![ecoriceandwolf](https://user-images.githubusercontent.com/43879920/46532274-6f27c500-c8a0-11e8-9aab-cfaf751b704a.png)
Hello, GDragon told me to show there my Rice problem :)
So i just begin to pay attention to the Rice on day 2, and they was already down... i travel this world a lot of time, for try to see if there is a bug in the graphic and i dont find any rice to.
We also have a wolf problem, a new player kill the most of them (stay 1), we make a law about it so no one kill any of them anymore, and i dont see any amelioration :/

Thx for your concern :)
