### ISSUE TITLE
USER ISSUE: Connection to Server failed

### ISSUE THREAD

**Issue by NogX** [StrangeLoopGames/EcoIssues#5569]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
1. Start game
2. Try to connect to server

**Expected behavior:**
It should have connected to the private server

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server' and also 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

* Deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Try connecting directly by entering the server's IP address in the 'Join' screen
* If the server is still loading, wait until it has finished loading before trying to join.
