### ISSUE TITLE
[Server Issue] Client and Server version not Synced

### ISSUE THREAD

**Issue by willkillyaquick** [StrangeLoopGames/EcoIssues#5571]
Steam version of the Eco server Steam ID 739590 is at 7.2.0 with Client Steam ID 382310 updated to 7.2.1.  Getting an incompatible version when clients try and connect.  Please update 739590 to 7.2.1.

**Comment by snaiperskaya** [comment]
Seconding this. Standalone server install is behind one version.

**Comment by willkillyaquick** [comment]
[UPDATE] I am using SteamCMD to update the game on my server.  The game will not update unless I remove or rename the ecoserver.exe file.  When I do that, running the command "app_update 739590 validate" pulls the update.

**Comment by snaiperskaya** [comment]
@willkillyaquick So if you delete that exe and try to update you actually get 7.2.1 now? I'll have to try that later.

**Comment by willkillyaquick** [comment]
@snaiperskaya , Yes but now it's 7.2.2 .  It worked for that version

**Comment by metachronism** [comment]
@Nanders fixed this
