### ISSUE TITLE
USER ISSUE: Been Whitelisted on a Stockpile can take items out but not allowed to put in

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#5575]
**Version:** 0.7.2.1 beta

as Can be seen i am whitleisted to use this Stockpile

![snap1920](https://user-images.githubusercontent.com/29383891/37092927-7c0a0b80-2205-11e8-9858-724dd75cbea4.png)

i can take stuff out but not allowed to put in and i see this message
![snap1922](https://user-images.githubusercontent.com/29383891/37093012-c21e098c-2205-11e8-9f33-5315e24bcff3.png)

The stockpile was originally mine but i unclaimed the land and let Holm use it, and had forgotten it was there so he gave me permission to use it again

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/5555 / https://github.com/StrangeLoopGames/EcoIssues/issues/5229

**Comment by MarjieAVolk** [comment]
I am not seeing this happen now.  Has this already been fixed?

**Comment by MarjieAVolk** [comment]
I think this may have been fixed along with the AuthorizationInventory flag fix.  Going to assume fixed unless I hear otherwise

**Comment by Conchipedia** [comment]
not sure as that world was wiped, we yet again destroyed the meteor in about a week+
