### ISSUE TITLE
[SERVER ISSUE] 7.2.1 crashes every few hours without leaving a dump file

### ISSUE THREAD

**Issue by Last2Night** [StrangeLoopGames/EcoIssues#5579]
7.2.1 crashes every few hours without even leaving a dump file. Players report that their progress is lost upon the crash and rolls back to latest backup. No lag or instability before crash was reported.

**Comment by ZeskaN** [comment]
I have had this happen almost 10 times on 7.2.3. This issue is still current.

**Comment by metachronism** [comment]
any updates on this from 7.3 / 7.3.1+ ?  not having any luck with a reliable repro

**Comment by Last2Night** [comment]
7.3.2
Still happens.
