### ISSUE TITLE
USER ISSUE: Tailoring

### ISSUE THREAD

**Issue by OOTBlade** [StrangeLoopGames/EcoIssues#5584]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
My Tailoring Specialities need to Learn 7k pts

**Expected behavior:**
1-10 pts

**Actual behavior:**
7000 pts

**Comment by OOTBlade** [comment]
![20180307153529_1](https://user-images.githubusercontent.com/37148122/37098203-96c17acc-221d-11e8-8fe2-b222c401969b.jpg)

**Comment by OOTBlade** [comment]
![20180307153937_1](https://user-images.githubusercontent.com/37148122/37098335-eeda50a8-221d-11e8-99b4-a13b290018ab.jpg)

**Comment by craig-jong** [comment]
Looks like an issue with the difficulty settings.

Let me know if this occurs in any recent version of the game and reopen this bug.
