### ISSUE TITLE
USER ISSUE: Hitzone doesn´t working

### ISSUE THREAD

**Issue by Kaube92** [StrangeLoopGames/EcoIssues#5585]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
My friend Goody have a big problem. If he try to make wood or break stones, he doesn´t hit them. The green Zone and the new green point is marked, but it doesn´t break wood or anything other. He bought the game yesterday and the error was there too. Steam reparation withour errors..

**Expected behavior:**
His PC has the recommended requirements

**Actual behavior:**

**Comment by Kaube92** [comment]
Thanks for your response! The Server IP is 46.251.235.48:4150 - but in a single game or other server too. 
I know the behavior of lags - you couln´t change tools, collect something, the server is frozen. You have to reconnect to solve the issue or waiting. **But no, it itn´t the problem of my friend.** The error happens the whole time, immediately after login since the first minute. The tree is green and if he try to hit, there are different **sounds**. 1) 10 times no hit (sound "hit in the air"), 1 time with luck a hit (sound "hit the tree"). The same with pickaxe. The button E (collect) is still working.

Following a video of the issue: https://videobin.org/+qfe/v20.html

He have a low ping (100k download) and 50fps

**Comment by MarjieAVolk** [comment]
Since last we spoke, we have gotten lots of server syncing & performance problem reports, so we are hard at work fixing this back up.  0.7.2.2 should be better.  We are also working on more fixes for another hotfix later today.  Thank you!
