### ISSUE TITLE
USER ISSUE: Log crash

### ISSUE THREAD

**Issue by Imothep80** [StrangeLoopGames/EcoIssues#5586]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
May be not possible.
- cut a tree
- log out close game
- open game login
- collect log
I'm realy not sure if this reproduce

**Expected behavior:**
...pickup log

**Actual behavior:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

Stack:
   bei TreeEntity.PickupLog(Player player, Guid logID)
   bei TreeEntity.OnActInteract(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment]
Fixed in 7.2
