### ISSUE TITLE
[CLIENT] Crash when running the application when not administrator

### ISSUE THREAD

**Issue by Neavend** [StrangeLoopGames/EcoIssues#5587]
**Steam version** (Build ID 2582766) (Guessing it's 7.2)

**Detailed Description of Issue:** When running the game from steam or Eco.exe from the installation folder, the process ends immediately for a user that is not in the windows administrator group.

**Workaround:** Running it with an administrator account works (Even though it does not hook properly with the non-admin steam process, preventing login unless restarting steam as admin as well).

**Reproducible / Steps ?** Yes, simply create a non-administrator account and try to run the game from it.

**Additional Comments / logs:** no crash logs in LocalLow as the folder is not even created before crash.
The closest thing I'm able to give is a SimpleProgramDebugger crashlog: https://pastebin.com/7YSPD8NW

**Comment by metachronism** [comment]
this does not repro for us, and Eco does not require admin privs to run (only to execute a few commands once to add firewall rule, and netsh rules, which is asks for manually when they are needed)
