### ISSUE TITLE
[Server] An update 7.2.1 for ECO steam server ?

### ISSUE THREAD

**Issue by rorti** [StrangeLoopGames/EcoIssues#5593]
Hi,

I just want to know, when gonna be the 7.2.1 update for the steam ECO server please ?
Actually I can have only the 7.2.0....
But client side is 7.2.1

Regards.

**Comment by D3nnis3n** [comment]
It's not on steam but on StrangeLoops. Another Derp.

**Comment by rorti** [comment]
I bought ECO on steam and for getting server fils you have to pass by steam.
But I'm think, I found a solution.

**Comment by 42656e** [comment]
You can just use the server files of the client (sounds strange to say this). It's in `steamapps/common/Eco/Eco_Data/server`.

**Comment by rorti** [comment]
Thanks for reply,
I found a solution => In steam, ECO server, select BETA 7.2.1
And that all :)
