### ISSUE TITLE
7.2 desyncing way more often

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#5594]
Client/Server descyncs are pretty common now.
Like unable to place something, unable to switch tool, unable to open chests or anything else stopping to be able to interact with the world. We've also seen trees not syncing correctly to the client (they magically appear after reloging)
In 7.1. these things happened only occasionally but now every 10-30mins of playing for everyone on the server.

Relogging helps but it's not a smooth gameplay having to relogg every couple minutes

**Comment by lefavilla** [comment]
maybe #5640

**Comment by Thyriel** [comment]
Could indeed be 5640. As i wrote in there too, at least most issues where gone once hunters where offline (but could be less people online too). Will test once a hunter is online today and let you know.
I just can't provide serverlogs/dumps as i don't have access to these on gportal hoster (would need to recreate the server to fix that which i can't do atm)

**Comment by metachronism** [comment]
related to the hunting lag
should be fixed in 7.2.3

**Comment by Thyriel** [comment]
> should be fixed in 7.2.3

it is ;) thanks
