### ISSUE TITLE
USER ISSUE: You can not see the regional symbols in the pop-up chat.

### ISSUE THREAD

**Issue by SunriZZe** [StrangeLoopGames/EcoIssues#5598]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
To write to the chat with regional symbols (for example Russian)

**Expected behavior:**
You can not see the regional symbols in the pop-up chat.

**Actual behavior:**
The symbols should be visible.

**Comment by MarjieAVolk** [comment]
We have recently added support for many other language's characters, but I don't believe we have added Russian yet.

**Comment by Nanders** [comment]
When you say regional symbols, what are you referring to specifically?

**Comment by MarjieAVolk** [comment]
I assume they meant Russian in this case.  But reading it again, it may also mean only the 'main' chat and not the 'log' chat, as we saw yesterday.

**Comment by SunriZZe** [comment]
Yep, Russian symbols. And yep, only in the 'main' chat.

**Comment by MarjieAVolk** [comment]
Okay if it is only in the main chat, then that is more of a bug than a feature.  I think @Nanders found a fix for this yesterday.

**Comment by Nanders** [comment]
Ah indeed this is fixed
