### ISSUE TITLE
Objects Icons persistent on the Screen

### ISSUE THREAD

**Issue by Rellikeon** [StrangeLoopGames/EcoIssues#56]
Where: Client
Detailed Description of Issue:
While I was moving some of my objects between my backpack and my house chest storage, the object icon freeze in the middle of the screen and the object in fact disappeared (it is not available on the backpack either on the chest). After restart the game the objects reappeared on my backpack

Reproducible? How difficult is it to reproduce?
I continuous playing and the problem appear again while I was moving an object between the backpack and the tool bar

Steps to reproduce bug/issue: I am not sure I only was moving objects between different sources 

Client Version: Alpha 0.3 release-979581c8

**Comment by klimSLG** [comment]
This happen for some reason unity pricked out, while you moving icon
