### ISSUE TITLE
Dupe property claims / Not learning Agriculture skill book

### ISSUE THREAD

**Issue by shortybsd** [StrangeLoopGames/EcoIssues#560]
Client/Server version alpha 0.4.2, Windows 7 64bit Client, Unix-based server FreeBSD and Linux based server CentOS x64 (either do the same exact thing)

I made the agriculture book, when right clicking and making at least 11 skill scroll, when right click skill scrolls I get 5 property claims, it states I have learned agriculture but yet have not. So repeat the process for unlimited property claims yet no gaining of agriculture skill.

[Click here for a Screenshot](http://www.shortybsd.org/EcoGame/2016-09-02 19_25_39-ECO.png)

**Comment by miralomaadam** [comment]
I had the same thing with the butchery skill, however I learnt the skill and got the claims

**Comment by metachronism** [comment]
fixed in alpha 5
