### ISSUE TITLE
USER ISSUE: Ramp Gaps

### ISSUE THREAD

**Issue by projdarkmoon** [StrangeLoopGames/EcoIssues#5601]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
1. Place ramp against dirt

**Expected behavior:**
Should Mesh well with dirt

**Actual behavior:**
Has a gab between dirt and ramp, and only fixed by paving or placing road

**Comment by projdarkmoon** [comment]
![image](https://user-images.githubusercontent.com/14205729/37107556-9e990b90-2202-11e8-9b68-bb00c8e554e7.png)

**Comment by thibaut-fagart** [comment]
Not a bug
You need to make road next to the ramp

**Comment by projdarkmoon** [comment]
Yes, but the Sides of it have a gap, and i dont feel on the sides it should be there.

**Comment by MarjieAVolk** [comment]
We are working on fixing this for a future version.  It may be available in 7.3, or possibly 7.4
