### ISSUE TITLE
USER ISSUE: Ghost Trees due to update

### ISSUE THREAD

**Issue by Wetzu** [StrangeLoopGames/EcoIssues#5603]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
Update Removed some dead tree saplings from my tree farm, soil tiles don't seem to get updated, like they still have trees on them, so i cannot remove them or plant new saplings

**Expected behavior:**

**Actual behavior:**

**Comment by rorti** [comment]
Have the same problem, all **planted** trees and only planted trees are invisible...

**Comment by MarjieAVolk** [comment]
Same as https://github.com/StrangeLoopGames/EcoIssues/issues/5321?

**Comment by Wetzu** [comment]
Not for me, as I am able to see the tilled soil tiles and it only affects trees which I planted and that died before the current update adding the auto-remove after 24h for Dead plants

**Comment by craig-jong** [comment]
should be fixed in 7.3.2
