### ISSUE TITLE
USER ISSUE: Server Freeze / High Ping after last hotfix

### ISSUE THREAD

**Issue by Ardesy** [StrangeLoopGames/EcoIssues#5613]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
Just Open a 200 x 200 world an play a while

**Expected behavior:**
Smooth Gameplay

**Actual behavior:**
Lag spikes and desync after some time passed with pings around 2 - 3k, then the Server become unresponsive after a while

**Comment by Thyriel** [comment]
Maybe related to https://github.com/StrangeLoopGames/EcoIssues/issues/5578 ?

**Comment by Ardesy** [comment]
Yep, exactly the same. CPU load goes to 100% after 1 or 2 hours

**Comment by lefavilla** [comment]
#5640

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5640
