### ISSUE TITLE
USER ISSUE: Everything is slower

### ISSUE THREAD

**Issue by Todeshuegel** [StrangeLoopGames/EcoIssues#5614]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
since the last update where you say that you improved the performance, every interaction takes waaay longer. for e.g. harvest a single plant takes about 2-4 seconds

**Expected behavior:**

**Actual behavior:**

**Comment by SeanAtr0n** [comment]
Fixed in 7.2.2
