### ISSUE TITLE
USER ISSUE: Cant plant seeds

### ISSUE THREAD

**Issue by Todeshuegel** [StrangeLoopGames/EcoIssues#5615]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
since the last update i can't plant any seeds anymore

**Expected behavior:**
plant the seeds

**Actual behavior:**
Message "Plant already exists here"

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5607
