### ISSUE TITLE
Corrugated Steel cube form texture

### ISSUE THREAD

**Issue by Nes112** [StrangeLoopGames/EcoIssues#5616]
Version: 7.2.1

The cube form texture for corrugated steel is bugged. Not only does the texture look strange, but there is no "ghost" form of the block visible before placing it. Other forms of corrugated steel work as expected.

![corrugate_steel_texture_bug_7 2 1](https://user-images.githubusercontent.com/24631375/37114572-a3351bc6-21fd-11e8-8fab-41a5e0a72d3a.png)

**Comment by keegan-o** [comment]
fixed in master.
