### ISSUE TITLE
Client can not connect to server if default view rang is to low (stuck at loading objects)

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#562]

**Comment by metachronism** [comment]
this is fixed

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/1156/purchased-cant-play

issue is there again

**Comment by tarmael** [comment]
I'm having this issue as well.

Tried on Windows and Linux. Checked view distance on Linux, hasn't helped - will check on Windows soon.

**Comment by metachronism** [comment]
closing, as this is not the same issue brought up
the deadlock during load should be fixed now though
