### ISSUE TITLE
USER ISSUE: Map not displaying correctly.

### ISSUE THREAD

**Issue by Gice020** [StrangeLoopGames/EcoIssues#5621]
![mapbug2](https://user-images.githubusercontent.com/36849199/37116216-e677c49c-224d-11e8-9477-06626b879c82.png)
![mapbug](https://user-images.githubusercontent.com/36849199/37116131-9ec1645a-224d-11e8-8c61-7f870bfa3c86.png)
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
For me it's just opening the map, relogging doesn't fix it. Sometimes the map pops back up after a while.

**Expected behavior:**
Display the map.

**Actual behavior:**
See screenshot. Not sure why the trees popped up, they weren't there earlier aswel. Just the dark/light blue background.

EDIT: Relogged again, trees are gone again.

**Comment by Boldee** [comment]
I reported this also didn't see it was a duplicate, I discovered how to force the map to load properly, I lost one of my carts and created a way point to it and the map slowly generated, I'm not sure if this is permanent or whether it will have to be done each session as yet.

**Comment by Boldee** [comment]
This bug is not rectified by the above actions permanently unfortunately and I cannot get the map to regenerate using the same method a second time, the difference this time is that my cart way point is very close as opposed to a very long distance away which seems to be making a difference.

**Comment by SeanAtr0n** [comment]
Fixed 7.3
