### ISSUE TITLE
USER ISSUE: Unable to connect

### ISSUE THREAD

**Issue by Eydwin** [StrangeLoopGames/EcoIssues#5622]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
Join my friends game via the tab from steam.

**Expected behavior:**
Put me in his game

**Actual behavior:**
The following error message popped up:
```Connections Failed
Connection Failed
```

**Comment by Maroxis** [comment]
After the update my server config was reseted and i had the same issue. When I configured my server again it worked. Whoever is hosting should check their server config.
Also try to join server using JOIN button for the first time after update. If it doesn't fix it you could write also if you see the server online on the list or not at all.

**Comment by MarjieAVolk** [comment]
@Maroxis Thanks for the advice.

@Eydwin Here are a couple more things you can try:

* Deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Connecting directly by entering the server's IP address in the 'Join' screen

If none of that works, send me your log file at 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.
