### ISSUE TITLE
USER ISSUE: Empty connection failed dialogue box

### ISSUE THREAD

**Issue by mastercake10** [StrangeLoopGames/EcoIssues#5624]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
1. Start Eco
2. Connect to a server that is compressing the world

**Expected behavior:**
A message which says that the server is currently starting.

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Thanks!  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5535
