### ISSUE TITLE
USER ISSUE: My UI elements are gone

### ISSUE THREAD

**Issue by dwumpus** [StrangeLoopGames/EcoIssues#5630]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
I hit some button I guess

**Expected behavior:**
not lost my chat screen, my inventory, my ability to switch between what is in my hand, basically no UI elements are on the screen.

**Actual behavior:**
Everything is gone, I am holding my bow and cannot even switch items.  I have a magnifying glass in the upper left corner.

**Comment by MarjieAVolk** [comment]
If that doesn't fix your problem, send me your log file: 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'
