### ISSUE TITLE
USER ISSUE: Game Updated to 0.7.2.1 instead of 0.7.2

### ISSUE THREAD

**Issue by psaidwid** [StrangeLoopGames/EcoIssues#5632]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
Update through steam

**Expected behavior:**
Minimal Bugs

**Actual behavior:**
Can't switch weapons, constantly have to restart the server, constantly have to reconnect and re-join

**Comment by MarjieAVolk** [comment]
Yes, we have released some hotfixes since 0.7.2.  We are working on several of the things you mentioned.  If you have more details, let us know.
