### ISSUE TITLE
[v0.7.2.2] Caught exception invoking RPC PlayerInteract on Player!

### ISSUE THREAD

**Issue by ApoRes1337** [StrangeLoopGames/EcoIssues#5638]
I have an failure in my Server Console. 
The Server is a Windows System (Windows Server 2016 Standard) with the following Specs:

I7-6700K
32 GB DDR4 RAM
2 x 256 NVMe SDDs Storage

[54:29] Caught network exception from Frank[GER]!  Disconnecting...
[54:29] Disconnecting client [reason: Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

Stack:
   bei TreeEntity.PickupLog(Player player, Guid logID)
   bei TreeEntity.OnActInteract(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>]...

Is this a Failure of me, or a generally Problem with the ECO Server Software ? 

Greetz SkyfaR

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5595
