### ISSUE TITLE
Masonry Skill Book bug / Masonry -2

### ISSUE THREAD

**Issue by DeasEx** [StrangeLoopGames/EcoIssues#564]
![image](https://cloud.githubusercontent.com/assets/22255247/18607617/afbcad24-7cda-11e6-8da8-e3835bbf4fa6.png)
Was playing on private server with a friend, learning the game, I crafted Masonry Skill Book, I took out the page and learned it, I tried to find any changes in skill tree, nothing. After that I gave my friend a page, same thing, we tried reading it again, it only gave us plot claims, Masonry in skill tree didn't appear at all, when I checked Quarry it said my Masonry level is still -2.

**Comment by metachronism** [comment]
skill revamp should have this fixed
