### ISSUE TITLE
[Art][Low Priority] Still no Sound on Hitting large piece of Coal Rubble

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#5644]
**Version:** 0.7.2.2 beta

Everything other Large Rubble makes sound, just not coal

**Comment by Conchipedia** [comment]
still not working 0.7.3.2

**Comment by Nanders** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4454
