### ISSUE TITLE
USER ISSUE: Harvesting elk

### ISSUE THREAD

**Issue by SmashedBeard** [StrangeLoopGames/EcoIssues#5645]
**Version:** 0.7.2.1 beta

**Steps to Reproduce:**
After shooting an elk, I try to harvest the meat and it just sits there.  If I disconnect and reconnect the meat is in my inventory.

**Expected behavior:**
Meat should be harvested without disconnecting

**Actual behavior:**
Requires disconnecting before it will enter inventory.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of #5640
