### ISSUE TITLE
USER ISSUE: [Art] Building: Glass and Mortared Stone don't 'snap'

### ISSUE THREAD

**Issue by Splutty** [StrangeLoopGames/EcoIssues#5647]
When building in simple glass panes and mortared stone, the glass and stone will not snap together to make corners or edges. It leaves holes in the wall, but it has not functional impact.

**Comment by keegan-o** [comment]
Fixed this up on master so Glass is usable as glass windows/walls with any building. 

![image](https://user-images.githubusercontent.com/14983165/37225802-ab4c4f24-238c-11e8-929f-66891e8f2762.png)
