### ISSUE TITLE
USER ISSUE: Scrolls

### ISSUE THREAD

**Issue by mwarnec2** [StrangeLoopGames/EcoIssues#5650]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
1. Right click on a book for research to get scroll
2. Right click on scroll to learn and nothing happens	

**Expected behavior:**
scroll should disappear and learn the skill	

**Actual behavior:**
nothing

**Comment by MarjieAVolk** [comment]
The next time you see this problem, can you send us your client log file? (C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt)  If there are crash files or error messages from your server, those might be useful also.

**Comment by mwarnec2** [comment]
I researched another book and once I did that they all started working again.

**Comment by craig-jong** [comment]
I can't get this to reproduce - please reopen with an attached save or client logs if this continues to happen.
