### ISSUE TITLE
USER ISSUE: Wrong Framed Glass Height

### ISSUE THREAD

**Issue by honux** [StrangeLoopGames/EcoIssues#5653]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Add a Framed Glass on the 3º space, leaving empty space of 2 blocks (the same needed for a door).

**Expected behavior:**
You should be able to walk under it

**Actual behavior:**
You can't

![image](https://user-images.githubusercontent.com/2934877/37133815-415b7b76-2274-11e8-865b-71c6cf9fa05a.png)

**Comment by keegan-o** [comment]
Just fixed in master, will be in 7.3
