### ISSUE TITLE
[User Issue] 7.2.2 Production time reduction bonuses not reflected in item build GUI

### ISSUE THREAD

**Issue by kshood** [StrangeLoopGames/EcoIssues#5655]
Production time reduction bonuses are not reflected in in a crafting tables production cost. Instead, the base time is shown.

However, the production time reduction bonus is still applied to the item. Also, the cost reduction bonus is shown.

Attached image shows that the production time implied by the build cost for the kitchen is 2hr. But, I had the Lumber Woodworking Speed at max level and so when production is started we see that it has the correct production time.

![produciton_time](https://user-images.githubusercontent.com/31428664/37133817-7ef32878-2263-11e8-9bd6-b2d3c7228a25.png)

**Comment by kshood** [comment]
It has either been fixed in 7.2.3 or is an intermittent issue.

**Comment by GophTheGreat** [comment]
Seems to be fixed. Reopen if it occurs again.
