### ISSUE TITLE
USER ISSUE: Joining through steam

### ISSUE THREAD

**Issue by jordan9856** [StrangeLoopGames/EcoIssues#5656]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Attempt to join a friend from steam	

**Expected behavior:**
it should allow me to join my friends game through steam

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server' and also 'C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

If the server is still loading, wait until it has finished before trying to join
Deleting the folder C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO
Temporarily disabling your firewall and/or antivirus software
Connecting directly by entering the server's IP address in the 'Join' screen
