### ISSUE TITLE
USER ISSUE: Can't join friends 

### ISSUE THREAD

**Issue by Devin152** [StrangeLoopGames/EcoIssues#5657]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
go to steam friend and click join or invite and it doesn't work

**Expected behavior:**
it should let me join or invite friends

**Actual behavior:**
it will say Connection Failed when i try to make a world and invite or join my friend

**Comment by MarjieAVolk** [comment]
The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server' and also 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

* If the server is still loading, wait until it has finished before trying to join
* Deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Connecting directly by entering the server's IP address in the 'Join' screen
