### ISSUE TITLE
USER ISSUE: Cant play on friends server

### ISSUE THREAD

**Issue by pearlkadel** [StrangeLoopGames/EcoIssues#5662]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
make a new server. clicked 1-3 players and allowed friends

**Expected behavior:**
to play on my friends world with them. i have another friend where we can and do often.

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by Teemine** [comment]
Check firewall and antivirus!

**Comment by Ekkelus** [comment]
Could be a port issue aswell perhaps?

**Comment by Teemine** [comment]
Well no. As far as i know the port should be used from steam. Steam gives a port so friends can connect using that port. If ur hosting a dedicated server then yes it could be port but if ur hosting it through the game then it isnt port because steam opens that automatically.

**Comment by MarjieAVolk** [comment]
The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server' and also 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

* If the server is still loading, wait until it has finished before trying to join
* Deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Try connecting directly by entering the server's IP address in the 'Join' screen
