### ISSUE TITLE
Dedicated Server Product on steam stuck on staging

### ISSUE THREAD

**Issue by Nashable** [StrangeLoopGames/EcoIssues#5663]
If you review beta options for Eco Dedicated server on Steam you can NOT opt out of staging.

This means it’s impossible to use SteamCmd to keep server in sync with stable branch

Repo steps:
In Steam: Library > Tools > *right click* Properties on Eco Server > Beta > No other option than Staging exists.

This version is out of sync from the existing client version at time of writing 0.7.2.2

**Comment by Nanders** [comment]
What happens if you click check code with an empty access code?

Seeing only staging definitely should not be the case.
