### ISSUE TITLE
Multiple Public Server, One IP, Diff. Ports

### ISSUE THREAD

**Issue by PapaHarni** [StrangeLoopGames/EcoIssues#5666]
Hello Guys,

i will be running different ECO servers over one IP but with difference Ports.
I have test it with difference port ranges. 10, 100, 500 and 1000 Port difference. But i can only connect to the Main Port Server.

Is there a way to connect without ingame server list? Like direct connection? Or what i do wrong to lets work multiple servers on same ip with difference ports?

Sincerely,
PapaHarni

**Comment by Thyriel** [comment]
As long as they start up (each using their own installation directory) it should work. Did you add the servers with gameport or webport ? Cause for some strange reason you need to add it ingame with webport and not gameport

**Comment by PapaHarni** [comment]
Ahh Okay thats my mistake. I add all times only the Game Port. Thanks with WebPort it works directly fine.

Good to know it. ;-)
