### ISSUE TITLE
[v0.7.2.2] Converting Map by every Server restart

### ISSUE THREAD

**Issue by ApoRes1337** [StrangeLoopGames/EcoIssues#5674]
Hello everybody, i would to ask about a Bug on my Server.

Good day, I wanted to ask if there is a known bug so far as it comes to the fact that the server map is converted at each restart?

Every time our server reboots the card is converted again, which also means that all plants are always 100% fully grown.

Server Specs:

Windows Server 2016 Standard
I7-6700K
32 GB DDR4 RAM
2 x 256 NVMe SDDs Storage

Greetz SkyfaR

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/4003

**Comment by metachronism** [comment]
no longer happening / been fixed
