### ISSUE TITLE
USER ISSUE: Can't join my own Steam-Server

### ISSUE THREAD

**Issue by Steinkex** [StrangeLoopGames/EcoIssues#5675]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
1. starting the Steam server
2. trying to join the server via the game

**Expected behavior:**
I should've been able to join the world

**Actual behavior:**
The following error message popped up:
```"Connection Failed"
Connection Failed
```

**Comment by AndyClausen** [comment]
Are you using an ip like this: 192.168.x.x? If so, your sever is running of your local network, and others outside your house will not be able to join.
If not, then did you remember to forward your ports?

**Comment by Steinkex** [comment]
Thanks for the quick reply!
Yes I am using an IP like that. But that shouldn't be the problem, because I am the one who can't join...and I am obviously in my house and thus in my own network...

**Comment by AndyClausen** [comment]
Just FYI, I'm not a staff member, just a normal user trying to help.
Can you type here the last number of the ip you're trying to connect to?

And can you try connecting to:
1. The same ip your friends are connecting to (right click and join game on your friend in steam)
2. localhost:port or 127.0.0.1:port where port is obviously the port your server is running on

**Comment by Steinkex** [comment]
I am so confused...the problem is that I am just a gamer and no computer expert ^^

1. I am trying to play on my own - just bought the game yesterday - but I am able to join other public servers though...
2. As far as I know 3001 should be the correct port and it isn't working for me. If I try to connect via my IP or localhost it shows me that the server is online but the "connection failed" message pops up when I try to enter it...
With the "127.0.0.1:3001" nothing even shows up in the server list...

Although after trying this some times I can't see anything on the server list at all....but that might just be a limited time bug :D

**Comment by AndyClausen** [comment]
Ah, so you can see the server. That's very useful info for when the devs reach this issue :)
If you just want to play by yourself you don't need a server though. You should just press New game in main menu.

Still, it's good that you report this. If anything it could help other users in the future.

Have you checked if the firewall is blocking it somehow?

**Comment by Steinkex** [comment]
The problem is that when I just press "new" the server loads and once it finishes "ecoserver.exe stopped working" is flashing and after that I get "connection failed" as well...

I checked that and gave the game and the server all permissions. I also created inbound rules for the used ports so that shouldn't be the problem either...

**Comment by AndyClausen** [comment]
If you don't have anything saved in the game, you could try to delete this folder: `%appdata%\..\LocalLow\Strange Loop Games\eco`
Inside this folder should also be a file called `output_log.txt`. Send this as an attachment here if you can.

Also, try selecting "Generate new" when creating a new world.

**Comment by Steinkex** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1795049/output_log.txt)

Here you go. I didn't delete the folder yet to wait what you say about the file :)

**Comment by AndyClausen** [comment]
I'm gonna go smoke and then take a look :)

**Comment by Steinkex** [comment]
Take your time mate :)

**Comment by Steinkex** [comment]
I'll sleep now though. Will reply tomorrow :)

**Comment by AndyClausen** [comment]
Whoops. Drinking with flatmates, forgot about this :P

**Comment by MarjieAVolk** [comment]
The URI format exception looks like https://github.com/StrangeLoopGames/EcoIssues/issues/4995.  If it's related, then deleting the folder as @AndyClausen said should help with that.

The second one I have never seen before.

However, both of these are problems with looking up the public server list, they are probably not related to starting your own world.  Local server crash files are located in '[...
]\steamapps\common\Eco\Eco_Data\Server\Dump' - Do you have anything there?

**Comment by Steinkex** [comment]
Thanks to both of you!

I hope to have a fix soon :D

**Comment by MarjieAVolk** [comment]
@Steinkex Did you try deleting the folder?  And have you looked for the crash files?

**Comment by Steinkex** [comment]
I did both but I couldn't attach the crash files here due to their type...

Atm I am playing on a friend's server so I am fine - but a fix for this would still be awesome :D

**Comment by MarjieAVolk** [comment]
You can either paste the contents of the files directly in the message, or you can send the whole crash folder to a .zip file

**Comment by Steinkex** [comment]
[Eco.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1820296/Eco.zip)

Thanks mate - here you go :)

**Comment by MarjieAVolk** [comment]
Oh are you on a mac?

**Comment by Steinkex** [comment]
Nope, Win8 - normal computer

**Comment by Steinkex** [comment]
Win 7, my bad....I downgraded some time ago :D

**Comment by MarjieAVolk** [comment]
Oh, yeah I was confused, sorry :P  Okay so you've sent me your client log files/config.  Can you also send me your server crash files, which are located in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'?  (You can also get to this 'Eco' folder via steam's Browse Local Files).

**Comment by Steinkex** [comment]
[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1828976/Dump.zip)

Heeeere you go mate :)

**Comment by MarjieAVolk** [comment]
Great, thank you.  There are two unique crashes in there:

This one seems to be complaining that the port is already in use.  Were you trying to run two servers at once, or anything like that?

```
--BEGIN DUMP--
Dump Time
03/07/2018 16:38:47

Exception
System.Net.Sockets.SocketException (0x80004005): Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden
   bei System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   bei System.Net.Sockets.Socket.Bind(EndPoint localEP)
   bei System.Net.Sockets.TcpListener.Start(Int32 backlog)
   bei Eco.Plugins.Networking.ListenServer.Setup(String ip, Int32 port)
   bei Eco.Plugins.Networking.NetworkManager.Run()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--
```


What's happening with this one is that when the server is starting up, it's trying to delete temporary files which are created during saves.  But some other process is already using the temporary file.  Which suggests there is another server running that is in the process of saving.  So both of these suggest to me that you have multiple servers running, using the same ports and the same installation.

```
Exception
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.IO.IOException: Der Prozess kann nicht auf die Datei "D:\SteamLibrary\steamapps\common\Eco\Eco_Data\Server\Storage\DotNetZip-helje31s.tmp" zugreifen, da sie von einem anderen Prozess verwendet wird.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalDelete(String path, Boolean checkHost)
   bei Eco.Core.Plugins.StorageManager.DeleteTempFiles()
   bei Eco.Core.Plugins.StorageManager..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Eco.Server.PluginManager..ctor()
   bei Eco.Server.Startup.Start(String[] args)
   bei Eco.Server.MainClass.Main(String[] args)
---> (Interne Ausnahme #0) System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.IO.IOException: Der Prozess kann nicht auf die Datei "D:\SteamLibrary\steamapps\common\Eco\Eco_Data\Server\Storage\DotNetZip-helje31s.tmp" zugreifen, da sie von einem anderen Prozess verwendet wird.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalDelete(String path, Boolean checkHost)
   bei Eco.Core.Plugins.StorageManager.DeleteTempFiles()
   bei Eco.Core.Plugins.StorageManager..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   bei System.Threading.Tasks.Task.Execute()<---
```

**Comment by Steinkex** [comment]
That might be possible since at some point I started a server via "ecoserver" and afterwards I clicked "new game" when joining that said server didn't work. So maybe that's what happened there...

But it didn't work before that either, so that's not the solution we need...

**Comment by MarjieAVolk** [comment]
Okay, sorry this thread has gotten confusing, so let me review what is going on.  Right now you are not able to load a save file -  Are you able to load any save files?  Are you able to start a new world?

Sounds like you tried the eco server tool too - did that start up and show the server window?  Or did it error out?

**Comment by Steinkex** [comment]
I am not, no.

I can only join other people's servers, non of mine (ingame or with the tool).
With the eco server tool it sometimes errors out but 2 out of 3 times it works - although I still can't join the server nor stop the server without restarting my computer (not even the task-manager helps)

**Comment by MarjieAVolk** [comment]
Well that is sounding very weird.  If you are running the server tool as well, you might have more dumps in '[...]\steamapps\common\Eco Server\Dump'.

Okay, so one obvious thing I've neglected to suggest is steam's 'verify integrity of game files' button. 
 Also, this was briefly mentioned earlier, but have you tried temporarily disabling your firewall and/or antivirus software?

**Comment by Steinkex** [comment]
[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1837561/Dump.zip)
This is it...although there is not too much in it since I re-installed the tool a couple of times :D 

I tried that but neither worked :/

**Comment by MarjieAVolk** [comment]
Closing due to no response.
