### ISSUE TITLE
USER ISSUE: UI is gone again

### ISSUE THREAD

**Issue by dwumpus** [StrangeLoopGames/EcoIssues#5678]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
1). Login thru Steam
2). Join Game

**Expected behavior:**
I should have the normal UI after logging in.

**Actual behavior:**
No UI or ability to interact with the UI via keyboard, ie number keys do not switch what is in my hand, and M does not bring up the map, C does not bring up chat.  Only thing that shows is the plot ownership window and that changes as I walk around the world.  I can use the tool I have but that is it.  In this case today it is a shovel.  Uninstalling and reinstalling the game does not correct it.  Deleting the AppData folder and uninstalling, and scrubbing all associated folders and reinstalling worked for 1 day.

**Comment by Ekkelus** [comment]
Have you tried pressing ALT + Z in game?

**Comment by MarjieAVolk** [comment]
Can you send me your log file?  "C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt"

**Comment by MarjieAVolk** [comment]
Closing due to no response
