### ISSUE TITLE
Door orientation / placement issue 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#568]
http://ecoforum.strangeloopgames.com/topic/958/door-orientation-broke

**Comment by FzyFurbal** [comment]
The same thing applies to wood stairs when it comes to orientation. They snap to one direction regardless of where you are pointing them or what backdrop you aim them at unless there's 2 side walls or items to lock them into going the direction you want them. They should be able to be placed any direction, independent of what is beside them - at least they are in most other block building games I've played.
