### ISSUE TITLE
USER ISSUE: My IGN

### ISSUE THREAD

**Issue by irk1** [StrangeLoopGames/EcoIssues#5680]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
I would like to change my in game name

**Expected behavior:**
the option to change your ign

**Actual behavior:**
is extremly annoying and changing my steam name did not work

**Comment by AndyClausen** [comment]
It worked for me when I changed steam name I think.
If this is true though, I must agree. There should at least be a check for steam name change upon joining a server. I expect you haven't bound the username to anything important ;)

**Comment by MarjieAVolk** [comment]
You cannot change your name after joining a server right now.  If you change your steam name and then join a new server, it will use your new name.

**Comment by WeaselDog** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6113
