### ISSUE TITLE
USER ISSUE: Inventory freeze

### ISSUE THREAD

**Issue by DJmRek** [StrangeLoopGames/EcoIssues#5682]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Playing on local server over lan with 2 players. After a while the inventory stucks, so you can't change tools for example. Also interaction with structurs like the 5x5 storage isn't seeable. After dis- and reconnect, all (invinsible) taken changes are there and everything is back to normal. Starts again after a  few minutes without specific actions to trigger it.

**Expected behavior:**
Like the inventory normaly does :). So switchable tools, actions (dragdrop, whith structurs) should be visible

**Actual behavior:**

**Comment by TBlueF** [comment]
Having the same issue on a hosted Server, 
seems to happen if you click things too quickly.
Also, if i reconnect after this issue i am standing on a location i was a minute ago.
And sometimes i have a clone of myself standing arond and always holding the same tool i am holding. And most of the time other players see a duplicate player marker on the location i disconnected.
*(My guess would be something with the connection to the server - syncronisation?)*

**Comment by MarjieAVolk** [comment]
This sounds like server lag.  Several important performance issues have been patched in today, this should be fixed in the most recent version.
