### ISSUE TITLE
USER ISSUE: MInt

### ISSUE THREAD

**Issue by Nenormalus** [StrangeLoopGames/EcoIssues#5684]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
i had mint that was backed up whit gold ingots. after update i saw that there is posibility to back it up whit another items. i picked up mint and placed it down. and currency is not backed up whit nothing and chosing window is not opening.

**Expected behavior:**
window to chose item opens and pick item to back up currency.

**Actual behavior:**
window to chose item for backing up currency is not opening.

**Comment by GophTheGreat** [comment]
Can't reproduce, and I even moved the mint. Reopen if it occurs again.
