### ISSUE TITLE
USER ISSUE: Not being able to join/load/create a game

### ISSUE THREAD

**Issue by zomyjordy** [StrangeLoopGames/EcoIssues#5686]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Start the game, select new, load or join a server in the main menu

**Expected behavior:**
Join a game	

**Actual behavior:**
Getting stuck in an infinite loading screen

**Comment by MarjieAVolk** [comment]
The next time this happens, could you send me your log file? "C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt"

One thing you could try is to delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO

**Comment by MarjieAVolk** [comment]
Closing due to no response
