### ISSUE TITLE
USER ISSUE: Failed to join via Steam friends list

### ISSUE THREAD

**Issue by TimWinkelmann** [StrangeLoopGames/EcoIssues#5689]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Requirement:
- Have a friend in your friend list, that has created a multiplayer game.
Step:
- Join Game

(If there are settings that myself or my friend aka. firewall etc. should have set, I would expect a more detailed popup that suggests to check specific system settings.)

**Expected behavior:**
Game connected

**Actual behavior:**
Popup:
Failed to Connect.

**Comment by MarjieAVolk** [comment]
The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server' or 'steamapps\common\Eco\Eco_Data\Server\Dump' and also 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

* If the server is still loading, wait until it has finished before trying to join
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software
* Try connecting directly by entering the server's IP address in the 'Join' screen

We have some already reported bugs that may be the same as your issue (eg. https://github.com/StrangeLoopGames/EcoIssues/issues/4909), and we are also working on improving connection error messages (eg. https://github.com/StrangeLoopGames/EcoIssues/issues/4956)
