### ISSUE TITLE
Client Bug: Caught exception: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by andrew2280** [StrangeLoopGames/EcoIssues#569]
Client crash.
Windows 10 build 14393.222

Detailed Description of Issue: I claimed some land and then went to the deed and clicked Add all in the unauthorised player column. Then I clicked attach current plot. My client then shows the error Caught exception: The given key was not present in the dictionary.

Reproducible? How difficult is it to reproduce? I've reproduced this by logging in and doing the same process again but only on one server. I haven't tried on another server yet.

Steps to reproduce bug/issue:

Client Version? Alpha 0.4.2

**Comment by metachronism** [comment]
should be fixed in alpha 5
