### ISSUE TITLE
USER ISSUE: tomato rendering bug

### ISSUE THREAD

**Issue by xZephlin** [StrangeLoopGames/EcoIssues#5691]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Look at tomatoes from a distance (15-20m)
Slowly walk towards tomatoes
stand right by/on tomato plant(s)

**Expected behavior:**
Show the red flowers/tomatoes when you are standing right by the tomato plant

**Actual behavior:**
as you get closer to the tomato plants, the red flowers/tomatoes will not render and only show the green stems

**Comment by Thyriel** [comment]
If they behave like that they are not fully matured yet. But i agree it looks like a visual bug.

**Comment by xZephlin** [comment]
sounds good, thanks

**Comment by MarjieAVolk** [comment]
Also reported in https://github.com/StrangeLoopGames/EcoIssues/issues/2825
