### ISSUE TITLE
USER ISSUE: Connection to server

### ISSUE THREAD

**Issue by zakann** [StrangeLoopGames/EcoIssues#5694]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Join a game from steam friend list

**Expected behavior:**
join game

**Actual behavior:**
The following error message popped up:
Connection Failed
Connection Failed
```

**Comment by MarjieAVolk** [comment]
The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server' or 'steamapps\common\Eco\Eco_Data\Server\Dump' and also 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

* If the server is still loading, wait until it has finished before trying to join
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software
* Try connecting directly by entering the server's IP address in the 'Join' screen
