### ISSUE TITLE
USER ISSUE: Duck down on first use of workbench

### ISSUE THREAD

**Issue by Todeshuegel** [StrangeLoopGames/EcoIssues#5695]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
1. close the game
2. start the game (seems to happen the first time of the session)
3. press e on workbench or similar

**Expected behavior:**
Just open the window

**Actual behavior:**
During opening the window for the first time of the session there is a strange "duck down" movement

**Comment by D3nnis3n** [comment]
Not happening anymore.
