### ISSUE TITLE
USER ISSUE: Can not create world

### ISSUE THREAD

**Issue by ruabmbua** [StrangeLoopGames/EcoIssues#5698]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
New -> Start

**Expected behavior:**
Works?

**Actual behavior:**

Could not create save file: /home/rruckerbauer/.local/share/Steam/steamapps/common/Eco/Eco_Data/Server/Storage/DefaultWorld does not exist
```

**Comment by MarjieAVolk** [comment]
Sounds like you have deleted your default world file.  To get it back, try clicking steam's 'verify integrity of game files' button.

Alternatively/additionally you can check 'Generate new' while creating a new world in order to avoid using the default world.
