### ISSUE TITLE
USER ISSUE: Map error

### ISSUE THREAD

**Issue by Nimeryon** [StrangeLoopGames/EcoIssues#5700]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
1.Walk untill you find a not charged portion of the map
2.Fall inside
3.Wait

**Expected behavior:**
The sound of falling goes faster and faster, item in hand begin to move in every direction faster and faster.

**Actual behavior:**
The sound of falling goes faster and faster, item in hand begin to move in every direction faster and faster.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5730
