### ISSUE TITLE
USER ISSUE: Connecting to my friend

### ISSUE THREAD

**Issue by IceWolf07** [StrangeLoopGames/EcoIssues#5702]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Sent me to steam invited

**Expected behavior:**
Join friend's server

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server' or '[...]\steamapps\common\Eco\Eco_Data\Server\Dump' and also 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

* If the server is still loading, wait until it has finished before trying to join
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software
* Try connecting directly by entering the server's IP address in the 'Join' screen
