### ISSUE TITLE
USER ISSUE: See through bodies of water when placing something in line of sight

### ISSUE THREAD

**Issue by Ministrator03** [StrangeLoopGames/EcoIssues#5703]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
1. Take a log or stone (or something similar in terms of placement properties)
2. Locate the edge of a river or a cliff with water below
3. Look at the edge of said location as if you wanted to place down the log or stone
4. By looking at the water through the white outlined preview you can see the floor of the body of water

**Expected behavior:**
Water should appear normal while looking through the white outlined preview in the act of placing something

**Actual behavior:**
You are able to look right through the water

**Screenshot**

![ ](https://puu.sh/zDzLl/3c2d7461e1.jpg)

**Comment by metachronism** [comment]
fixed with newer water shader
