### ISSUE TITLE
USER ISSUE: torch

### ISSUE THREAD

**Issue by Eidhaart** [StrangeLoopGames/EcoIssues#5708]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Try holding a torch in 3rd person	

**Expected behavior:**
The torch should show up in hand and iluminate the area

**Actual behavior:**
The torch does not show up in my hand

**Comment by CreeperLord** [comment]
Torches are also not visible to other players. (player cannot hold torch for other player)

**Comment by keegan-o** [comment]
This is something strange in code I think because the torch does appear and work in third person if you switch to it from the Axe, but not if you switch to it from holding nothing...
