### ISSUE TITLE
USER ISSUE: Unable to Connect to multiplayer server

### ISSUE THREAD

**Issue by Harkole** [StrangeLoopGames/EcoIssues#5709]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Set up server as normal on box 1. Set up port forwarding for external network to access server on box 1. Launch game from box 2 (same sub network). Attempt to connect to server from box 2 to box 1.

**Expected behavior:**
Both internal and external clients should be able to connect

**Actual behavior:**
Box 1 unable to connect to server. External connections connect as expected and players can play

**Comment by MarjieAVolk** [comment]
Have you tried connecting to the server directly via ip address?

**Comment by Harkole** [comment]
Hi Marjie,

I've disabled IPv6 on the internal network and tried a direct connection to both the internal and external IP as well as using the qualified network names. I've verified other connections to the server via other applications such as TeamSpeak and Remote Desktop Software. I've successfully ran other game servers on there and had no issues with connections such as DCS-World, Minecraft, Dark and Light and Arma 3.

The server appears in the browser and shows online with the correct number of players connected at that time but as soon as I click join it thinks for a second, then fails with Connection Failed message. I have successfully connected to several other servers in the browser list.

Additionally I can connect to a server I run on the localhost without issues. I've forward port 3000 and 3001 on the server (which is working as external players can connect) it just seems to have an issue with the internal lan connection.

**Comment by MarjieAVolk** [comment]
Gonna up priority on this, as it sounds like you have enough know how to help us figure this out.

**Comment by Harkole** [comment]
Let me know if you've got any traces or anything I can capture to help along. I'm going to dig in tonight and see if can work anything out.

**Comment by Harkole** [comment]
Just to give a full picture of what's happening at the moment:

![image](https://user-images.githubusercontent.com/3703699/37227269-a7cc794e-23d4-11e8-843b-67d51b62e71f.png)

and then...

![image](https://user-images.githubusercontent.com/3703699/37227290-b7518e22-23d4-11e8-8e27-8542cbb36036.png)

Web Page works fine, and is set up as part of the same firewall configuration:

![image](https://user-images.githubusercontent.com/3703699/37227634-e6ab4964-23d5-11e8-9f21-c75ab701065d.png)

Tonight I've tried disabling the software firewalls on both box 1 and box 2 to ensure it's not a set up issue on one of those but the same fault remains. As you will see from above the server does allow external players on as two are currently connected.

I attempted to capture traces on the network but Fiddler didn't capture anything and the Eco application didn't show in the App Containers to try force feed back and WireShark was only showing the server browser list populating and not any server connection attempts.

**Comment by MarjieAVolk** [comment]
Have you tried disabling DetectNAT on the server?  (It might make external people not able to connect, but worth seeing if that does anything)

**Comment by Harkole** [comment]
That nailed it!

Disabling the NatTranslation on the Eco server seems to have solved the issue and as I've manually configured the routers firewall people are still connecting in.

Thank you for the pointer! :)

**Comment by MarjieAVolk** [comment]
Okay great - Gonna leave the bug open, since we would like DetectNAT to work in all cases ideally
