### ISSUE TITLE
Floating Continent

### ISSUE THREAD

**Issue by kardafly** [StrangeLoopGames/EcoIssues#571]
I just bought the game and created my first world.  After exploring for a bit i fell down off the continent in was on, much to my surprise, to find another one under it.  I realized then that the bottom land masses were what the minimap was showing, not the giant floating landmass.  
Im not sure if this has been reported yet.  If not i can provide screenshots and any other information upon request.

**Comment by metachronism** [comment]
I'm 90% sure this is fixed in alpha 5
