### ISSUE TITLE
SERVER ISSUE: 7.2.3 Crash old Save

### ISSUE THREAD

**Issue by B1sounours** [StrangeLoopGames/EcoIssues#5715]
**Version:** 7.2.3

**Step to reproduce :**
Load old save map

**Expected behavior :**
Load the old save map

**Actual behavior:**
Crash

Exception non gérée : System.AggregateException: Une ou plusieurs erreurs se son
t produites. ---> System.AggregateException: Une ou plusieurs erreurs se sont pr
oduites. ---> System.Reflection.TargetInvocationException: Une exception a été l
evée par la cible d'un appel. ---> System.Exception: Error(s) occurred when load
ing World
   à Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 creat
eFunc)
   à Eco.World.PersistentChunkGrid.Load()
   à Eco.World.WorldPlugin..ctor()
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnl
y, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boo
lean& bNeedSecurityCheck)
   à System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheck
This, Boolean fillCache, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance(Type type, Boolean nonPublic)
   à System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder bind
er, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCraw
lMark& stackMark)
   à System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder
 binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   à System.Activator.CreateInstance(Type type, Object[] args)
   à Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   à Eco.Server.PluginManager.<.ctor>b__10_1()
   à System.Threading.Tasks.Task.Execute()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout
, CancellationToken cancellationToken)
   à Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   à System.Threading.Tasks.Task.Execute()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout
, CancellationToken cancellationToken)
   à Eco.Server.PluginManager..ctor()
   à Eco.Server.Startup.Start(String[] args)
   à Eco.Server.MainClass.Main(String[] args)

**Comment by x23a1s** [comment]
i get the same error.
Please help !

greetz alex

**Comment by D3nnis3n** [comment]
Same Issue.

**Comment by D3nnis3n** [comment]
A dump for you.
[Crash AggregateException 03083024.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1794901/Crash.AggregateException.03083024.zip)

**Comment by ItsReddi** [comment]
same here:
![grafik](https://user-images.githubusercontent.com/3147888/37177906-25f88df8-2321-11e8-832d-b875670bc426.png)

**Comment by B1sounours** [comment]
https://ufile.io/0xcn0 Download link for the map

**Comment by D3nnis3n** [comment]
Fixed by:
- Open Game.eco as a zip-archive
- Edit file "version" and replace "2,2" by "2.2"

**Comment by x23a1s** [comment]
thank you it worked ^^

**Comment by MarjieAVolk** [comment]
Aha, I guess the fix we did for locale is not backwards compatible.

**Comment by MarjieAVolk** [comment]
A fix for this migration issue has already been patched in.  Should work now.
