### ISSUE TITLE
USER ISSUE: Connection Failed (I am host)

### ISSUE THREAD

**Issue by Cind12** [StrangeLoopGames/EcoIssues#5716]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Continuing or Loading Game that was created on this client with "New" and had friends connected in the past. 
This happened right after 25MB Patch on 8.3.2017

**Expected behavior:**
My machine is host in this context. Server & Client should have started.

**Actual behavior:**
Game minimizes after "Loading World" when reopening it is on "Connecting" and then:
The following error message popped up:
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Can you send me any crash files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'?

**Comment by Conchipedia** [comment]
i had that happen and realized i had a mod that i hadn't updated for the this version , so i deleted it and now i could load back in (this is for Single-player game not a hosted server)

**Comment by Cind12** [comment]
@MarjieAVolk Dump folder zip file attached. All dumps are at around the time I encountered the error, I guess they will all show the same problem. Thanks for looking into this.

In contrast to @Conchipedia I am not running any mods, so I guess we are not having the same problem.

[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1799262/Dump.zip)

**Comment by Cind12** [comment]
@MarjieAVolk 
The issue seems to be fixed now. The world fully loaded and I can continue to play. I noticed additional steps on starting the world, including "converting world to new format" that were not visible when encountering the error... Maybe I just started the game in between some stable versions?

**Comment by MarjieAVolk** [comment]
Hmmm, that's interesting.  I wonder if the version detector thing was being weird.

Here's the exception from the attached dumps:

```
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Exception: Error(s) occurred when loading World
   bei Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   bei Eco.World.PersistentChunkGrid.Load()
   bei Eco.World.WorldPlugin..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager.<.ctor>b__10_1()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Eco.Server.PluginManager..ctor()
   bei Eco.Server.Startup.Start(String[] args)
   bei Eco.Server.MainClass.Main(String[] args)
```
