### ISSUE TITLE
USER ISSUE: Connection Failed with switch to desktop

### ISSUE THREAD

**Issue by Tomek2711** [StrangeLoopGames/EcoIssues#5717]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Try to continue a game
2. After loading world, tabbing out to desktop (game still running)
Happened only since last tiny update

**Expected behavior:**
Loading further components and connect to game

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Hey there, sorry we lost track of this bug.  Are you still having problems loading your save?  If so, can you send me any crash files in '[...]\steamapps\common\Eco Server\Dump'?

**Comment by MarjieAVolk** [comment]
Closing due to no response
