### ISSUE TITLE
Overloading the Character from Powered cart causes a crash

### ISSUE THREAD

**Issue by PerksPrisoner** [StrangeLoopGames/EcoIssues#5719]
When you are attempting to unload a powered cart and you already (in this case) have Tier 2 Lumber in your carrying slot while using a broken hammer to pull the materials out. It causes a crash.

**Comment by SeanAtr0n** [comment]
sounds like you are on 7.2.0? should be fixed in latest

**Comment by PerksPrisoner** [comment]
Negative this is in version 7.2.3

**Comment by MarjieAVolk** [comment]
Can you attach the message you see when you are kicked, and/or the crash file from the server?

**Comment by PerksPrisoner** [comment]
Unfortunately I haven't duplicated the action as I don't want to crash again. If it is in the logs I can go dig it out I just need to know the path.

**Comment by MarjieAVolk** [comment]
If you are running the server locally, they are probably in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'.  Otherwise, you will need to ask the server owner.

**Comment by PerksPrisoner** [comment]
I am the server owner

**Comment by PerksPrisoner** [comment]
I just haven't ventured to much into the files as I try not to manipulate a EARLY ACCESS game so I can help with actual bugs and not ones I have created

**Comment by PerksPrisoner** [comment]
I take that back I think I found it. But it may actually be in version 7.2.2 
[Eco Files For Bug Report.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1795261/Eco.Files.For.Bug.Report.zip)

**Comment by MarjieAVolk** [comment]
Ah yeah, the bug from that crash has been fixed in 7.2.3.  Thanks!
