### ISSUE TITLE
USER ISSUE: three "offline" Savegames don´t load any more/ Game is unplayabel

### ISSUE THREAD

**Issue by FlamBeon** [StrangeLoopGames/EcoIssues#5720]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. I start game and Pressing "Continue-/Load Button"
2. "GameplayStatsPlugin" loads, then "World" loads
3. Game Minimized
4. After "Tabing/Clicking" Ingame
5. Loadscreen shown a while or/and Errormessage:"Connection failed" shown

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Can you send me any crash files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'?  It seems likely that your server is failing to start up.

**Comment by FlamBeon** [comment]
the .ecodmp data is not supported in chat field. 

Before some hours steam updated the Game (0bytes/0bytes), after this the savegame works. We can close the thread. I can reopen it, when its dosen´t work again, right?

**Comment by MarjieAVolk** [comment]
Glad to hear it.  Yes, you can reopen it later if you need to.
