### ISSUE TITLE
Server (Steam) won't Start (+screenshot)

### ISSUE THREAD

**Issue by DanielxGhax** [StrangeLoopGames/EcoIssues#5722]
I tryed to start the ECO server.exe on my Computer and that happened...
![screenshot_1](https://user-images.githubusercontent.com/37195670/37179820-4f7e0148-2327-11e8-9c6a-4e1c1e44e28b.PNG)

A day before, everything was fine, but now I do not know what to do.

Thanks (Im German, sorry :D)

**Comment by MarjieAVolk** [comment]
It looks like your save file is corrupted somehow.  Could you send over the .eco save file?

**Comment by metachronism** [comment]
fixed in the hotfix
