### ISSUE TITLE
Hollow Stockpile

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#5724]
http://steamcommunity.com/sharedfiles/filedetails/?id=1324601612

As seen on the screenshot, one of my stockpiles displays as being hollow although it's full

**Comment by Ministrator03** [comment]
Same here!

![](https://puu.sh/zDxG3/03eb1243d5.jpg)

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4616
