### ISSUE TITLE
USER ISSUE: Building a wood cart quit on me

### ISSUE THREAD

**Issue by kevnar** [StrangeLoopGames/EcoIssues#5725]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
I started a wood cart at the workbench, but did not have all the required materials yet. Then I wandered away to get new logs. I chopped a tree and hauled the logs to the nearby stockpile. I went back a few times, and then checked the workbench to see how many logs I was still short. The wood cart build had apparently been cancelled. I lost all the logs and boards. wtf?

**Expected behavior:**
It should have continued buiding the cart, and paused until I added more materials.

**Actual behavior:**
It apparently canceled the cart without refunding the materials It did use to the stockpile. Basically, I lost precious wood for nothing.

**Comment by Ministrator03** [comment]
Are you sure it didn't get placed in a nearby container?
