### ISSUE TITLE
USER ISSUE: Starting Singleplayer

### ISSUE THREAD

**Issue by DanielxGhax** [StrangeLoopGames/EcoIssues#5726]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Start Game	
2. Press "New"
3.Tick everything (boxes) 0-3Player 
4.Start New Game
5.Here you are...

**Expected behavior:**
Started a new game

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Could you send me any crash files in 'steamapps\common\Eco\Eco_Data\Server\Dump'?

**Comment by DanielxGhax** [comment]
Sure

--BEGIN DUMP--
Dump Time
03/08/2018 23:37:42

Exception
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.TypeInitializationException: Der Typeninitialisierer fÃ¼r "Eco.Gameplay.Stats.PlayerActions" hat eine Ausnahme verursacht. ---> System.ArgumentException: Illegales Zeichen im Pfad.
   bei System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   bei LiteDB.FileDiskService.Initialize(Logger log, String password)
   bei LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log, Boolean utcDate)
   bei LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   bei LiteDB.LazyLoad`1.get_Value()
   bei LiteDB.LiteCollection`1.EnsureIndex(String field, String expression, Boolean unique)
   bei Eco.Stats.StatDatabase.EnsureIndex[T](IEnumerable`1 fieldNames)
   bei Eco.Gameplay.Stats.ConcretePlayerActions.AcceptContractPlayerStatManager..ctor()
   bei Eco.Gameplay.Stats.PlayerActions..cctor()
   --- Ende der internen AusnahmestapelÃ¼berwachung ---
   bei Eco.Gameplay.Stats.PlayerActions.get_ActionManagers()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.PreventableActionDropDown.DisplayedManagersStatic()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown.get_UnsortedOptions()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.get_AllOptions()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown..ctor(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.ActionList.CreateNewElement()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.ActionList..ctor(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.PreventActionClause..ctor(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.LawClauseDropDown.<>c.<.cctor>b__7_0(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.EnumToNodeDropDown`2.<>c__DisplayClass4_0.<get_UnsortedOptions>b__0(DropDownOption option)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init()
   bei Eco.Gameplay.LegislationSystem.LawLogic.LawLogicRoot..ctor(Government govData, Laws lawData)
   bei Eco.Gameplay.Legislation.InitDefaultLaws(LegislationData data)
   bei Eco.Core.Plugins.StorageManager.CreateOrLoad[StorageType](String folder, Action`1 onCreate)
   bei Eco.Gameplay.Legislation..ctor()
   --- Ende der internen AusnahmestapelÃ¼berwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager.<.ctor>b__10_3()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen AusnahmestapelÃ¼berwachung ---
   bei System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Eco.Server.PluginManager..ctor()
   bei Eco.Server.Startup.Start(String[] args)
   bei Eco.Server.MainClass.Main(String[] args)
---> (Interne Ausnahme #0) System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.TypeInitializationException: Der Typeninitialisierer fÃ¼r "Eco.Gameplay.Stats.PlayerActions" hat eine Ausnahme verursacht. ---> System.ArgumentException: Illegales Zeichen im Pfad.
   bei System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   bei LiteDB.FileDiskService.Initialize(Logger log, String password)
   bei LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log, Boolean utcDate)
   bei LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   bei LiteDB.LazyLoad`1.get_Value()
   bei LiteDB.LiteCollection`1.EnsureIndex(String field, String expression, Boolean unique)
   bei Eco.Stats.StatDatabase.EnsureIndex[T](IEnumerable`1 fieldNames)
   bei Eco.Gameplay.Stats.ConcretePlayerActions.AcceptContractPlayerStatManager..ctor()
   bei Eco.Gameplay.Stats.PlayerActions..cctor()
   --- Ende der internen AusnahmestapelÃ¼berwachung ---
   bei Eco.Gameplay.Stats.PlayerActions.get_ActionManagers()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.PreventableActionDropDown.DisplayedManagersStatic()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown.get_UnsortedOptions()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.get_AllOptions()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown..ctor(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.ActionList.CreateNewElement()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.ActionList..ctor(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.PreventActionClause..ctor(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.LawClauseDropDown.<>c.<.cctor>b__7_0(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.EnumToNodeDropDown`2.<>c__DisplayClass4_0.<get_UnsortedOptions>b__0(DropDownOption option)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init()
   bei Eco.Gameplay.LegislationSystem.LawLogic.LawLogicRoot..ctor(Government govData, Laws lawData)
   bei Eco.Gameplay.Legislation.InitDefaultLaws(LegislationData data)
   bei Eco.Core.Plugins.StorageManager.CreateOrLoad[StorageType](String folder, Action`1 onCreate)
   bei Eco.Gameplay.Legislation..ctor()
   --- Ende der internen AusnahmestapelÃ¼berwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager.<.ctor>b__10_3()
   bei System.Threading.Tasks.Task.Execute()<---


Inner Exception
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.TypeInitializationException: Der Typeninitialisierer fÃ¼r "Eco.Gameplay.Stats.PlayerActions" hat eine Ausnahme verursacht. ---> System.ArgumentException: Illegales Zeichen im Pfad.
   bei System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   bei LiteDB.FileDiskService.Initialize(Logger log, String password)
   bei LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log, Boolean utcDate)
   bei LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   bei LiteDB.LazyLoad`1.get_Value()
   bei LiteDB.LiteCollection`1.EnsureIndex(String field, String expression, Boolean unique)
   bei Eco.Stats.StatDatabase.EnsureIndex[T](IEnumerable`1 fieldNames)
   bei Eco.Gameplay.Stats.ConcretePlayerActions.AcceptContractPlayerStatManager..ctor()
   bei Eco.Gameplay.Stats.PlayerActions..cctor()
   --- Ende der internen AusnahmestapelÃ¼berwachung ---
   bei Eco.Gameplay.Stats.PlayerActions.get_ActionManagers()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.PreventableActionDropDown.DisplayedManagersStatic()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown.get_UnsortedOptions()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.get_AllOptions()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown..ctor(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.ActionList.CreateNewElement()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.ActionList..ctor(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.PreventActionClause..ctor(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.LawClauseDropDown.<>c.<.cctor>b__7_0(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.EnumToNodeDropDown`2.<>c__DisplayClass4_0.<get_UnsortedOptions>b__0(DropDownOption option)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init()
   bei Eco.Gameplay.LegislationSystem.LawLogic.LawLogicRoot..ctor(Government govData, Laws lawData)
   bei Eco.Gameplay.Legislation.InitDefaultLaws(LegislationData data)
   bei Eco.Core.Plugins.StorageManager.CreateOrLoad[StorageType](String folder, Action`1 onCreate)
   bei Eco.Gameplay.Legislation..ctor()
   --- Ende der internen AusnahmestapelÃ¼berwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager.<.ctor>b__10_3()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen AusnahmestapelÃ¼berwachung ---
   bei System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Eco.Server.PluginManager..ctor()
   bei Eco.Server.Startup.Start(String[] args)
   bei Eco.Server.MainClass.Main(String[] args)
---> (Interne Ausnahme #0) System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.TypeInitializationException: Der Typeninitialisierer fÃ¼r "Eco.Gameplay.Stats.PlayerActions" hat eine Ausnahme verursacht. ---> System.ArgumentException: Illegales Zeichen im Pfad.
   bei System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   bei LiteDB.FileDiskService.Initialize(Logger log, String password)
   bei LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log, Boolean utcDate)
   bei LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   bei LiteDB.LazyLoad`1.get_Value()
   bei LiteDB.LiteCollection`1.EnsureIndex(String field, String expression, Boolean unique)
   bei Eco.Stats.StatDatabase.EnsureIndex[T](IEnumerable`1 fieldNames)
   bei Eco.Gameplay.Stats.ConcretePlayerActions.AcceptContractPlayerStatManager..ctor()
   bei Eco.Gameplay.Stats.PlayerActions..cctor()
   --- Ende der internen AusnahmestapelÃ¼berwachung ---
   bei Eco.Gameplay.Stats.PlayerActions.get_ActionManagers()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.PreventableActionDropDown.DisplayedManagersStatic()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown.get_UnsortedOptions()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.get_AllOptions()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.BaseActionDropDown..ctor(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.ActionList.CreateNewElement()
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.ActionList..ctor(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.PreventActionClause..ctor(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Clauses.LawClauseDropDown.<>c.<.cctor>b__7_0(LawLogicNode parent)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.EnumToNodeDropDown`2.<>c__DisplayClass4_0.<get_UnsortedOptions>b__0(DropDownOption option)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   bei Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init()
   bei Eco.Gameplay.LegislationSystem.LawLogic.LawLogicRoot..ctor(Government govData, Laws lawData)
   bei Eco.Gameplay.Legislation.InitDefaultLaws(LegislationData data)
   bei Eco.Core.Plugins.StorageManager.CreateOrLoad[StorageType](String folder, Action`1 onCreate)
   bei Eco.Gameplay.Legislation..ctor()
   --- Ende der internen AusnahmestapelÃ¼berwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager.<.ctor>b__10_3()
   bei System.Threading.Tasks.Task.Execute()<---


--END DUMP--

**Comment by MarjieAVolk** [comment]
Okaaay, so it looks like the game doesn't like the name of your world.  What was your world called?

**Comment by MarjieAVolk** [comment]
Well, we have fixed some problems with world names, so while I have never actually seen this exact error, I'm going to close this as fixed for now.  We have had no other reports of it, so seems likely.
