### ISSUE TITLE
USER ISSUE: Can connet to friends games

### ISSUE THREAD

**Issue by Notapeoples** [StrangeLoopGames/EcoIssues#5727]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
try to connect to friends game via steam (its a private world not a server)

**Expected behavior:**
allow me to join his game

**Actual behavior:**
The following error message popped up:
``` Conection Failed
```

**Comment by Notapeoples** [comment]
other people are able to connect to his game

**Comment by MarjieAVolk** [comment]
You were disconnected with an empty message?

**Comment by MarjieAVolk** [comment]
Here are a couple of things you can try as a workaround:

* If the server is still loading, wait until it has finished before trying to join
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software
* Try connecting directly by entering the server's IP address in the 'Join' screen

**Comment by MarjieAVolk** [comment]
Closing due to no response
