### ISSUE TITLE
USER ISSUE: Crimini Mushrooms

### ISSUE THREAD

**Issue by Hezzi6** [StrangeLoopGames/EcoIssues#5732]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Start game	

**Expected behavior:**
spawning crimini mushrooms on map

**Actual behavior:**
no crimini mushrooms on map

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5568
