### ISSUE TITLE
Crafting queue: Can't enter more then 999

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#5733]
Entering a queue number by keyboard number keys allows a max of 999 while with the arrow buttons higher numbers >1000 are possible.
Would be great if at least 9999 would work with keyboard, i tend to start a lot semiautomatic craftings i don't like to requeue every now and then ;)

**Comment by MarjieAVolk** [comment]
Changed in next major release.  Maximum will be 9999.
