### ISSUE TITLE
Host and Client Are Arguing

### ISSUE THREAD

**Issue by PerksPrisoner** [StrangeLoopGames/EcoIssues#5737]
The server settings don't seem to like the configuration of the "difficulty.eco" So I have managed a screen shot of the exact weirdness and the .eco so you can see what I believe is every aspect. You can see in the details window in the bottom left there is an issue.
![capture](https://user-images.githubusercontent.com/22648457/37184390-0311d320-22f0-11e8-83f9-471cd4abed2b.PNG)
[Eco Files For Bug Report.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1795246/Eco.Files.For.Bug.Report.zip)

**Comment by PerksPrisoner** [comment]
I might add the Machine Shop wasn't an issue in 7.2.2 and the Blast Furnace is in its own building.

**Comment by MarjieAVolk** [comment]
It looks like maybe you are seeing fallback text on the HUD.  Can you send me your log file? 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by PerksPrisoner** [comment]
Will that remain the same path if it is a hosted server?

**Comment by MarjieAVolk** [comment]
Yes, that will be on your own machine.

**Comment by PerksPrisoner** [comment]
It doesn't seem to want to pull the file up saying the path is no existent even after replacing the user with the correct folder name.

**Comment by MarjieAVolk** [comment]
Okay, have you found the AppData folder?  Have you found the ECO folder?

**Comment by MarjieAVolk** [comment]
Is your computer set to a different language?  The folders may have names in your own language in that case.

**Comment by PerksPrisoner** [comment]
The appdata folder is this the same one as say in "Minecraft" as I can find that one through the run command no sweat

**Comment by PerksPrisoner** [comment]
Excuse me I forgot when you use run it opens the actual folder Standby

**Comment by PerksPrisoner** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1795356/output_log.txt)

**Comment by Thyriel** [comment]
I don't think those "NNNNNNNN" in the tooltip have anything to do with your difficulty.eco
Most of us have the same "problem" (seems only to be a displaying issue nothing broken or so). Language setting of the computer is german.

**Comment by MarjieAVolk** [comment]
Yes, the NNNN is a silly display bug, shouldn't be a problem.

Oh man you got a lot of stuff going on in that log file.  Looks like you were seeing a bunch of the problems that got hotfixed yesterday, so that might be related.  There are also a crap ton of these:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: 
  at (wrapper managed-to-native) UnityEngine.Component:get_gameObject ()
  at UnityEngine.Component.GetComponentInParent (System.Type t) [0x00000] in <filename unknown>:0 
  at UnityEngine.Component.GetComponentInParent[BaseItemStackListUI] () [0x00000] in <filename unknown>:0 
  at UI.BaseItemUI.OnChange () [0x00000] in <filename unknown>:0 
  at UI.ItemCollectionUI.OnChange () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00000] in <filename unknown>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x00000] in <filename unknown>:0 
```

Did this problem go away after the hotfix, by any chance?

**Comment by PerksPrisoner** [comment]
No it isn't fixed. As of 7.2.3

**Comment by MarjieAVolk** [comment]
Okay, closing as already fixed (since there was no response)

**Comment by MarjieAVolk** [comment]
Oh man, I guess I had some weird deal since I left this tab open last week, sorry, didn't see your message.

**Comment by MarjieAVolk** [comment]
Okay, so you think this is related to the difficulty settings.  Why is that?  Do other people on the same server see the problem?  Do you see the problem on other servers?

**Comment by MarjieAVolk** [comment]
Assigning @craig-jong for now, since it may be related to skill points gained on action / crafting, since both of those are enabled looks like.

**Comment by PerksPrisoner** [comment]
I haven't checked, but replying to keep the post active.

**Comment by PerksPrisoner** [comment]
Doesn't seem that anyone else has seen the issue so maybe it is just me. But they also stated they didn't open that particular window seen in the picture.

**Comment by MarjieAVolk** [comment]
Since the last log file you sent had a lot of errors in it that have been fixed, it might be helpful for you to send a log file again the next time you see this issue.  I'm pretty sure the tooltip is right, and the HUD is just failing to initialize.

**Comment by PerksPrisoner** [comment]
I have restarted the entire world on a different server so this error is none existent any longer as I am aware of.

**Comment by MarjieAVolk** [comment]
Okay well in that case... tentatively closing as fixed :P
