### ISSUE TITLE
USER ISSUE: "Common Grass" and air pockets generating underwater

### ISSUE THREAD

**Issue by Ministrator03** [StrangeLoopGames/EcoIssues#5739]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Dive in any (larger?) body of water

**Expected behavior:**
Should not generate air blocks with grass underneath in oceans

**Actual behavior:**
"Common Grass" spots are generated, mostly but not always with air pockets ontop

**Screenshot**

![ ](https://puu.sh/zDBGO/3eaa018d03.jpg)

**Comment by SeanAtr0n** [comment]
was fixed in 7.3.2
