### ISSUE TITLE
USER ISSUE: Powered Cart Randomly Moves

### ISSUE THREAD

**Issue by dantheuber** [StrangeLoopGames/EcoIssues#5740]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
unclear what causes this to happen.

**Expected behavior:**
Powered cart will stay where it is parked and NOT MOVE

**Actual behavior:**
Once, upon logging in, the powered cart drives past me and almost down a hill... I had to chase after and get in it to stop it moving.

Another time, a friend I was playing with tells me it is moving, and i turn around to it on its side...

**Comment by fritzr** [comment]
can confirm

**Comment by SeanAtr0n** [comment]
fixed in 7.3
