### ISSUE TITLE
When a player crashes or the server crashes (They get reloaded)

### ISSUE THREAD

**Issue by PerksPrisoner** [StrangeLoopGames/EcoIssues#5741]
I have a player on the server that has been kicked or dropped from client/host issues and he has been reloaded though the game will recognize the land as his it treats him as a new player. This causes his properties to be different and one deed doesn't cover all

**Comment by PerksPrisoner** [comment]
This may have something to do directly with 7.2.0 as I can't seem to reproduce it anymore and it happen almost every time prior to the update.

**Comment by MarjieAVolk** [comment]
Did the server have requireauth turned off at the time?  Do you still have the save where this happened, that has all these different users on it?

**Comment by PerksPrisoner** [comment]
Negative as the server creates a new back up every couple of hours.

**Comment by MarjieAVolk** [comment]
Okay well if you aren't seeing it anymore, gonna close for now.  Let me know if you have trouble again.
