### ISSUE TITLE
USER ISSUE: Stairs vanishing

### ISSUE THREAD

**Issue by kevnar** [StrangeLoopGames/EcoIssues#5743]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
I attempted to place a wooden stair block on top of a hewn wood block. It removed the stair from my inventory, but didn't place it. I lost a whole stack of 15 stairs, not realizing it was glitching out. 	

**Expected behavior:**
Should place stairs on right-click

**Actual behavior:**
The stairs vanished from my inventory, but was not placed.

**Comment by Ministrator03** [comment]
I've experienced this too. I walked away for a bit and the "placed" blocks were there again.
