### ISSUE TITLE
USER ISSUE: crafting bug

### ISSUE THREAD

**Issue by jakejdb1999** [StrangeLoopGames/EcoIssues#5744]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
crazy frame drops when opening workbench	

**Expected behavior:**
should be faster

**Actual behavior:**
super slow

**Comment by metachronism** [comment]
we need to do some more UI profiling one of these days

**Comment by metachronism** [comment]
leaving this to marjie, pretty sure she has fixed this though

**Comment by MarjieAVolk** [comment]
Fixed in next major release
