### ISSUE TITLE
USER ISSUE: offline?

### ISSUE THREAD

**Issue by Murrrrrr** [StrangeLoopGames/EcoIssues#5748]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
When i open the game its telling me either I am offline, or the server i have favorited is offline.  I know for a fact the server is not offline.	Is there a way I have to log in to the game?

**Expected behavior:**
Ishould be able to join a sever   but cannot	
![offline](https://user-images.githubusercontent.com/7930347/37191692-4305f54e-232f-11e8-8805-e4085d13c264.png)

**Actual behavior:**
I cannot join a server or search other servers.

**Comment by Murrrrrr** [comment]
nvm I deleted the appdata files and it worked.

**Comment by MarjieAVolk** [comment]
Okay, glad you have fixed the problem.  If you see this again, then send me your log file 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'.  Would like to figure out why this happens.
