### ISSUE TITLE
USER ISSUE: Gui text disapers

### ISSUE THREAD

**Issue by syonfox** [StrangeLoopGames/EcoIssues#5749]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Download eco on linux
Start it and have it wopend for a minute
The text will diaper

**Expected behavior:**
All of the text for menu items

**Actual behavior:**
shows the buttonds but dosent render the text

**Comment by MarjieAVolk** [comment]
Log file from another person who saw this (also on linux): https://github.com/StrangeLoopGames/EcoIssues/files/1805999/Player.log

**Comment by mastercake10** [comment]
Got this issue too, described in #5860.
Finally, I was able to obtain the Logfile:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/1808999/Player.log)
I've to add that this bug does not appear every time I start Eco, so I was able to play the game for 2 hours or so without seeing this bug appearing.

**Comment by WTFire** [comment]
But if

**Comment by WTFire** [comment]
When I change the window of the game the text disappear. And if it reproduce I disconnected and reconnect. If I don't change the window the text is normal.

**Comment by mastercake10** [comment]
**Version: **0.7.2.4 beta

Changing the resolution of the game does nothing. However, some fonts like the chat messages or the resolution drop-down entries are still rendered:

![image](https://user-images.githubusercontent.com/16278273/37409312-53697b4a-279e-11e8-8d9d-ce017db5ae34.png)

![image](https://user-images.githubusercontent.com/16278273/37409431-a22a8df0-279e-11e8-8b7e-7ab9eb6a9ccc.png)

The Player.log file does not have any entry that is relevant to this issue.

**Comment by SlayksWood** [comment]
Seems fixed
