### ISSUE TITLE
User Issue:Trampled dirt from below

### ISSUE THREAD

**Issue by Goreko** [StrangeLoopGames/EcoIssues#5750]
![trampleddirt](https://user-images.githubusercontent.com/2740560/37192796-5d316984-2335-11e8-8595-f96b4743dabd.png)
Dirt above my mine is being trampled by constant movement from below.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5101
