### ISSUE TITLE
Issue: Aqueduct

### ISSUE THREAD

**Issue by ZeelNightwolf** [StrangeLoopGames/EcoIssues#5751]
Aqueducts still don't appear to be working. I believe this is due to not having 'Watertight' as an attribute on the appropriate class for the brick aqueducts.

**Comment by FishAus** [comment]
Can confirm, Adding "Watertight" as an attribute on the Aquaduct block causes the water to spread through the Aquaduct. Here is the change I made in the Bricks.cs file in Mods/AutoGen/Forms/

![image](https://user-images.githubusercontent.com/35624562/37206873-8a8913fa-23ee-11e8-9d72-2ebff768ca20.png)

**Comment by craig-jong** [comment]
Yea, adding watertight will fix this issue. I'm not really sure where my fixes went, but this'll be in the next build. There are a few other things that will be changed to make aqueducts behave better as well.

**Comment by Conchipedia** [comment]
Aqueducts don't transport water far enough? #4478
they keep closing as done, so hoping this one eventually is Done 😄

**Comment by MarjieAVolk** [comment]
I swear to you, I witnessed this working the other week :P :'(

**Comment by Conchipedia** [comment]
get them to make Aqueduct as seperate block with its own Recipe then we KNOW it works 😄 at the moment its still hidden in the Brick hammer skill

**Comment by FishAus** [comment]
I don’t think it needs its own block and recipe. It’s fine where it is. And it does work when the code is fixed so it will be fine at the next update. :)

**Comment by Conchipedia** [comment]
reason i think it should have its own Block is so farmers can use this themselves to Water their Farms without waiting for it to be unlocked later in game and they have to learn stone construction and then almost top tier in brick construction to lay it down

**Comment by MarjieAVolk** [comment]
I also think that aqueducts should be their own block: https://github.com/StrangeLoopGames/EcoIssues/issues/4891

**Comment by Conchipedia** [comment]
maybe we should have a vote on this, i vote for your idea @MarjieAVolk 😄

**Comment by craig-jong** [comment]
Okay well, this is fixed in the 7.3. We can keep the other one open.
