### ISSUE TITLE
Server Save State

### ISSUE THREAD

**Issue by PerksPrisoner** [StrangeLoopGames/EcoIssues#5752]
Why is it when the server is restarted it rolls back. There is no listed commands to save the world nor does it have an auto save as prior to restart. It is causing a great deal of grief among players as it can rollback an entire hour of game play.

**Comment by MarjieAVolk** [comment]
How are you exiting the server?  Are you running it from in game, or standalone?

**Comment by PerksPrisoner** [comment]
Standalone I Believe. To be sure I am understanding you "I rent the server"

**Comment by PerksPrisoner** [comment]
For anyone looking at this later on. This is stated for 7.1.2 but I am currently running it on 7.2.3 and it still works fine seemingly. https://pradoxzon.squarespace.com/eco-mods/adminutils/

**Comment by MarjieAVolk** [comment]
Okay, so do you have access to the server window?  Right now, the server doesn't have a great save and quit option, you need to manually save before taking the server down.  There is an option to do so in the server window.  Open the "Storage" menu drop down and select "Force Save All and Flush To Disk".  You can also configure how often the server saves a backup.  The default is once every 4 hours.  This is done in the Backup tab.

**Comment by MarjieAVolk** [comment]
To clarify, the backups are saved into a separate directory.  In order to revert to a backup, you need to copy the backup files into the Storage directory, replacing the files that are there.

The game does also save automatically from time to time, but doing a manual save before you take the server down will ensure that the save is up to date.

**Comment by PerksPrisoner** [comment]
The configuration of the STORAGE.ECO file was the fix I needed ultimately.  That file would be beneficial under a new file if possible. I didn't even think to look in that folder but maybe I am just dumb. Either way problem is resolved.

**Comment by MarjieAVolk** [comment]
So you changed the save frequency setting in Storage.eco?  That number is in seconds, so it should be saving once per minute by default.  (For future reference, editing the .eco files in config is the same as setting values in the server window)

But okay, if your problem is resolved, then closing.

**Comment by PerksPrisoner** [comment]
The default was 1500 second? Anyhow yea I did change and thanks for that lil heads up

**Comment by MarjieAVolk** [comment]
The default is 60 seconds as far as I can tell >> hmmmmm

**Comment by PerksPrisoner** [comment]
Yea. Perhaps it is something the hosting provider has done

**Comment by MarjieAVolk** [comment]
Ah yeah maybe
