### ISSUE TITLE
USER ISSUE: Mint backing glitch

### ISSUE THREAD

**Issue by Napier-JP** [StrangeLoopGames/EcoIssues#5755]
**Version:** 0.7.2.1 beta
# **This glitch only happened at the mint crafted and placed in v0.7.1.x**
# **I confirmed that newly crafted mint worked fine**

**Steps to Reproduce in v.0.7.2.1:**
1. Name the currency
2. Default backing item for the currency was gold ingot (as it was crafted and placed in v0.7.1.x.)
3. Changed backing item to biodiesel.
4. Pressed craft button. Got a notification that I cannot change backing item after crafting currency. Crafted 10 currencies in exchange of 1 biodiesel.

**Expected behavior:**
Mint requires biodiesel for more currency crafting

**Actual behavior:**
Now mint requires gold ingot. I confirmed that the mint consumed gold ingot for additional currency. It cannot be changed even after I put away the mint and re-put it.
Also, in economy viewer, it is shown that the currency is backed by gold ingot(icon).

**Comment by MarjieAVolk** [comment]
I assume you had already crafted some currency on the old mint?  Once you have crafted some, you can't change what is backing it anymore.  Is that what is going on?

**Comment by Napier-JP** [comment]
>I assume you had already crafted some currency on the old mint?

I crafted currency on the old mint in 0.7.2.1, and it was my very first attempt (I've never crafted before.)

>Once you have crafted some, you can't change what is backing it anymore.

I understand that I can't change backing material anymore.
The problem is **I successfully crafted first 10 currency using BIODIESEL but after that the mint requires GOLD INGOT.**

**Comment by Napier-JP** [comment]
Cheap solution for this might be "don't use old mint if you want to back with things other than gold ingot"

**Comment by MarjieAVolk** [comment]
Okay I see; I am not sure if I understand exactly what happened.  Does this sound right?
1. Ran the game in v0.7.1.x
2. Placed mint, named and crafted some currency using gold ingot
3. Ran the game in v.0.7.2.1
4. Switched mint backing object to biodiesel
5. Crafted some currency
a. Crafting successful - spent 1 biodiesel to get 10 currency
b. Got error message saying not allowed to change backing object from gold ingot to biodiesel
c. Mint backing object is reverted to gold ingot and can no longer be changed

**Comment by Napier-JP** [comment]
Sorry for my confusing usage of "craft."

Precisely:
- Ran the game in v0.7.1.x
- Manufactured and placed mint, named the currency
- Ran the game in v.0.7.2.1
- Switched mint backing object from gold ingot to biodiesel
- Pressed Craft button at mint
-- Confirm window (not error) saying __"you won't be able to change backing object after crafting currency"__ popped up and I pressed YES
-- Crafting successful - spent 1 biodiesel to get 10 currency
-- Mint backing object is reverted to gold ingot and can no longer be changed

**Comment by Napier-JP** [comment]
Finally I succeeded in reproducing the issue (uploaded on YouTube.)
The issue only happens after putting the mint away and re-putting it.
https://youtu.be/n6F2J0X1aJY

**Comment by johnkslg** [comment]
This is a migration issue from old mints, going to close it now as I think it shouldnt be a concern.
