### ISSUE TITLE
USER ISSUE: Nothing grows up

### ISSUE THREAD

**Issue by Cypata** [StrangeLoopGames/EcoIssues#5758]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Unfortunately, nothing grows as well as the trees or the fruit & vegetable plants. not even the grass? There is also no toturial about it if it should be so intended.

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Most things grow very slowly, over the course of several hours to a day.  Are you sure that they're not growing at all?

**Comment by craig-jong** [comment]
This, possibly, could have been related to the repopulate command.

I'm going to close this, if you encounter this issue in the latest release please reopen this issue.
