### ISSUE TITLE
USER ISSUE: Building lag/freezing

### ISSUE THREAD

**Issue by Beemerron** [StrangeLoopGames/EcoIssues#5759]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
1. Build anything
2.attempt to change tool or do anything
3.Fail
4.Disconnect/reconnect
5.Carry on

**Expected behavior:**
It should continue to work perfectly well as it did in 7.2

**Actual behavior:**
Instead it allows me to cntinue running around but not perform any actions.

**Comment by MarjieAVolk** [comment]
This should be fixed in 7.2.3.
