### ISSUE TITLE
7.2.3 - Items placed in Stockpile Disappears

### ISSUE THREAD

**Issue by DumpsterDave** [StrangeLoopGames/EcoIssues#5765]
**Version:** 
0.7.2.3 beta

**Steps to Reproduce:**
Build Stockpile.  Begin moving full stacks of one type of item into stockpile from another (ex: stacks of 20 stone).  At random, one of the previously placed stacks disappears.  No other stockpiles are linked to the stockpile and no crafting is occurring at the time.  So far, this only seems to occur when moving items from one stockpile to another.  Moving items from character inventory or cart did not seem to trigger the issue (yet).

**Expected behavior:**
Items get placed in stockpile

**Actual behavior:**
Some items (random) disappear.  No crash, just items disappearing.  On one stockpile, it happened each time I tried to place a third stack of the same item.  On another, it was random and allowed me to place 5 of one (mortared stone), but then caused the second of the next type (sand) to disappear.

**Comment by MarjieAVolk** [comment]
Did logging out and back in make the items reappear?

**Comment by DumpsterDave** [comment]
I tried logging out and back in and the items do not seem to have re-appeared.  I was condensing stockpiles so that I could move them for building purposes at the time, so none of the stockpile exist where they did when the issue occurred.  I will try to re-create the bug and then try logging out and back in again without moving stockpiles.

**Comment by DumpsterDave** [comment]
I was able to re-produce the bug.  Logging out and back in again did not make the items re-appear.

Attached is a video showing the bug and relog.
[Eco Stockpile Bug.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1799365/Eco.Stockpile.Bug.zip)

**Comment by TheRealMaxion** [comment]
I have also noticed this issue.
It seems random whether the stack that was moved disappears or one of the other stacks already in the  stockpile being moved to does. Most of the time it works fine, but this happens relatively often if you are moving stuff between stockpiles a lot.

**Comment by metachronism** [comment]
reworked stockpiles should no longer have this issues
