### ISSUE TITLE
USER ISSUE: There is no berries on huckleberry bushes all around the server

### ISSUE THREAD

**Issue by FixResh** [StrangeLoopGames/EcoIssues#5777]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Find a lot of huckleberry bushes
2. Wait
3. Wait
4. In any cases, the huckleberries don't appear on the bushes

**Expected behavior:**
It should have appeared	

**Actual behavior:**
Berries don't appear on the bushes

**Comment by craig-jong** [comment]
How long did you wait? Is there any chance you could get a soil sampler screenshot of one of your huckleberry bushes?

**Comment by craig-jong** [comment]
Is it possible the "repopulate" command was used on your server? That may cause this.

I'm going to close this bug due to no response, but feel free to reopen it if you have any extra information that you can share.
