### ISSUE TITLE
Game crashes after 15-25 mins on playtime

### ISSUE THREAD

**Issue by Imbawolf** [StrangeLoopGames/EcoIssues#5780]
Pam, from support discord channel section, tell me this is a unity error and ask me post this log here 

[Crash_2018-03-09_180718.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1797509/Crash_2018-03-09_180718.zip)

**Comment by MarjieAVolk** [comment]
Thanks!  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5793
