### ISSUE TITLE
Some HTML Text tag bugs.

### ISSUE THREAD

**Issue by Matikari** [StrangeLoopGames/EcoIssues#5785]
I figured out the < br> and < size=#>< /size> work.

However, < br> will offset the cursor from where its inputting for anything following the use of it. And will increase the offset following each use.

And < size=#> does not reflect well what the font size actually is after its altered in comparison to other text within the same window that is not altered.

Test sign below is written as < size=20>Altered Size @ 20< /size>< br>Unaltered Size

![20180309102450_1](https://user-images.githubusercontent.com/9065496/37220710-a6ebb67a-2384-11e8-9443-9bf7e0c2c25c.jpg)

![20180309102454_1](https://user-images.githubusercontent.com/9065496/37220699-99e5c092-2384-11e8-95b4-6da4d8b99b32.jpg)

**Comment by MarjieAVolk** [comment]
The size thing is weird partially because the sign text auto sizes by default.  But I wonder if we can try to sync up manually defined sizes a little better.

For the weird tag problems, I think the solution is for the text editor not to render rich text.

**Comment by MarjieAVolk** [comment]
Sign text sizes have been fiddled with quite a bit recently, and some of the size options disabled, based on issues with the text going outside the bounds of the sign.  I think we're going to call the current state good for now.
