### ISSUE TITLE
Fir seeds ?

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#5786]
According to 7.2 patchnotes Fir trees should now drop seeds but how do you get them as you can't target the leaves ?

**Comment by Harkole** [comment]
Thyriel are you targeting the lowest branch of the Fir tree? I've had no issues removing the branches but have yet to have a single seed drop.

I've been managing to cut the branches/leaves by targeting the lowest branch on each of the 4 cardinal directions (north/south/east/west) leaving me with just the main trunk.

**Comment by Thyriel** [comment]
@Harkole : Targeting the branches isn't the problem, but targeting the leaves (at least that's how you get all other tree seeds) doesn't seem to be possible. I've tried from bottom, standing on a branch, from top, from side and lastly even with /fly. All i could get into target was branches and the main trunk

**Comment by elfl0rd** [comment]
Any plans?

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/49685780-e37a2100-fafa-11e8-8aee-47b38e88513e.png)
https://github.com/StrangeLoopGames/Eco/pull/3727
Hooray! It's so close! :P

**Comment by D3nnis3n** [comment]
Firs now drop seeds.
