### ISSUE TITLE
USER ISSUE: Stove dosent work

### ISSUE THREAD

**Issue by NortonDK** [StrangeLoopGames/EcoIssues#5790]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Install a stove in your house, connect pipes, try to make food and see that the exhaust doesn't work (for some reason the new stove design has 2 pipe ports and none of them work.

**Expected behavior:**
Expected exhaust to go out trough the pipes

**Actual behavior:**
exhaust builds up inside the stove and cant get out

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5805 -- Looks like the stove's 'real' pipe port is floating off to the side right now.
