### ISSUE TITLE
USER ISSUE: Map displays incorrectly

### ISSUE THREAD

**Issue by Boldee** [StrangeLoopGames/EcoIssues#5799]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Open map

**Expected behavior:**
See map

**Actual behavior:**
Only trees, buildings and players visible, terrain is missing

![20180309214800_1](https://user-images.githubusercontent.com/23031034/37231605-a9e4b8e0-23e3-11e8-977a-de8e2368fd76.jpg)

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5621
