### ISSUE TITLE
Torch stack is used when placing a single torch

### ISSUE THREAD

**Issue by Alexxondre** [StrangeLoopGames/EcoIssues#58]
When you have multiple torches in your toolbar and you place one in the world, the whole stack is used.

**Comment by klimSLG** [comment]
It's fine at current branch.
If that problem is keep occurring, can you specify how you get torches and what condition you used it?

**Comment by Alexxondre** [comment]
Forgot to say i had this bug on public alpha 3 release. I got torches from the campfire and placed them on the floor (grass), and i was able to reproduce the bug each time. The server is running on Windows Server 2008 R2.
Will try to record a little video.

**Comment by mariowenig** [comment]
This is back fyi :)
