### ISSUE TITLE
USER ISSUE: Holding tool in hand while sitting in powered cart in third person

### ISSUE THREAD

**Issue by Ministrator03** [StrangeLoopGames/EcoIssues#5800]
**Version:** 0.7.2.3 beta

**Steps to reproduce:**
1. Equip/select tool (for example Iron Shovel)
2. Sit in seat of powered cart
3. Switch to third person

**Expected behaviour:**
Tool should not be held together with handle of powered cart

**Actual behaviour:**
Tool is held in hand while driving, putting it in a weird position

**Screenshot**

![ ](https://puu.sh/zEb2P/7fb461dd6a.png)

**Comment by SeanAtr0n** [comment]
fixed a while back
