### ISSUE TITLE
USER ISSUE: Torch icon and grab animation bugged.

### ISSUE THREAD

**Issue by VAArtemchuk** [StrangeLoopGames/EcoIssues#5802]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Open both torch stand and your backpack
2. Take a pack of torches from your bakcpack and try to switch to torch stand's inventory having torches grabbed.
3. Grub animation freezes for good (only closing the game helps). Torches' icon freezes where it was at the moment of switching. 

**Expected behavior:**
It should have simply switched torch stand's menu

**Actual behavior:**
But it led to a bug. Grub animation freezes for good, icon freezes, menu behaves weirdly (random not responding).

**Comment by MarjieAVolk** [comment]
Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/3841
