### ISSUE TITLE
Shader Issue: Curved Shader not used on the model items inside the icebox.

### ISSUE THREAD

**Issue by FishAus** [StrangeLoopGames/EcoIssues#5803]
The items inside the icebox model clearly don't have the Curved Shader applied. As you move away from the icebox the items raise and begin to float in the air.

Here you can see the items beginning to raise up out of the icebox.

![image](https://user-images.githubusercontent.com/35624562/37233265-a766ca14-2446-11e8-90fb-a8e8a44f0ff8.png)

**Comment by keegan-o** [comment]
Fixed in master

**Comment by keegan-o** [comment]
And in staging.
