### ISSUE TITLE
Stove occupancy wrong

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#5805]
![image](https://user-images.githubusercontent.com/3536496/37234379-3300b4fe-23ac-11e8-88e0-46552651a4d0.png)

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/37234403-521e5c38-23ac-11e8-8a60-6b0c96421bc7.png)
Looks like its this floating pipe output

**Comment by MarjieAVolk** [comment]
This sounds like an easy fix, so high priority ;)

**Comment by keegan-o** [comment]
sean should be assigned unless I guess nick does pipe port stuff too.

**Comment by MarjieAVolk** [comment]
Oh I thought it was an occupancy thing.

**Comment by kshood** [comment]
So even when the real output is in the right place and the pipe connects to it, it won't release any pent-up pollution.

**Comment by kshood** [comment]
So, it looks like under some unknown rules, the output end of the stove disappears (determined by hovering over pollution input/output part of the pipes view).

I haven't figured out the rule though. Certainly, if in a building, when the back is up against a wall the output disappears.

The following does **not** block the output area: Blocks put at the back of the stove (even if blocks are above the stove).

The following **does** block the output though: The stove against the back of a wall while underground does (even though it doesn't and shouldn't count as a room).

**Comment by kshood** [comment]
Looks like the pipe opening shows up in the wrong place even without the graphic.

![20180311014506_1](https://user-images.githubusercontent.com/31428664/37250553-ed206c86-24cd-11e8-89c6-4138a94ff896.jpg)

**Comment by SeanAtr0n** [comment]
fixed in next hotfix or 7.3
