### ISSUE TITLE
Exception Caught on Disconnect (Server)

### ISSUE THREAD

**Issue by Harkole** [StrangeLoopGames/EcoIssues#5806]
Any player disconnecting causes the server to log a Caught Exception - Argument out of range. Doesn't seem to be causing any harm other than filling the server console screen with text...

![image](https://user-images.githubusercontent.com/3703699/37234644-f83c1b98-23f0-11e8-8337-9f9a6879aaf6.png)

Different players get different errors in the stack:

![image](https://user-images.githubusercontent.com/3703699/37234732-705bb6f6-23f1-11e8-9922-a5af3301ba82.png)

**Comment by MarjieAVolk** [comment]
The first exception is https://github.com/StrangeLoopGames/EcoIssues/issues/5496.  The second one is https://github.com/StrangeLoopGames/EcoIssues/issues/5527
