### ISSUE TITLE
USER ISSUE: After 7.2 my house is bugged

### ISSUE THREAD

**Issue by nataklug** [StrangeLoopGames/EcoIssues#5807]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Update	

**Expected behavior:**
House ok

**Actual behavior:**
House is not giving me skill points for strange reasons and even if I fix the reason it still get me another strange reason.

**Comment by MarjieAVolk** [comment]
Can you enumerate what those strange reasons are?

**Comment by nataklug** [comment]
Hello Marjie, I will try to show it by images. Other thing I think is a bug it my location... After this update it`s like I am not moving in the right way. I have a ultra-wide. I will try to list all the bugs I`ve seen:

1) After the update everytime I open the game for the first time (after a computer power on/reboot) it hangs and my computer turns off. I can see the screen to select a game and I just have to wait for 4 or 5 seconds to happen. It`s something related to fan speed on AMD Radeon RX480. I am attaching a dxdiag to help. [DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1799610/DxDiag.txt)

2) Look at the Bloomery. It`s outside and yet it`s making me loose points as a room. This was not like that. Below you can see the "NNNNNN". ![bloomery_outside](https://user-images.githubusercontent.com/34246539/37245004-92bb4494-2470-11e8-8324-a735157c4423.png)

If I move the bloomery you will get another error. ![without_bloomery](https://user-images.githubusercontent.com/34246539/37245026-ee93c76e-2470-11e8-9c43-249a989a802e.png)

And this keep happening all the way. I had a +97 skill points before 7.2 and now I can`t get over 38. I am running 0.7.2.3 beta right now.

**Comment by nataklug** [comment]
Ignore the minimap/point/direction arrow error... I think it`s solved in 7.2.3.
![minimap](https://user-images.githubusercontent.com/34246539/37245067-7de261d2-2471-11e8-97cb-8357711bc5fd.png)

Now my arrow is pointing in the right direction as the street. Just the house bug is still here.

**Comment by johnkslg** [comment]
Fixed

**Comment by nataklug** [comment]
John, can I expect the solution in an upcoming update?
