### ISSUE TITLE
USER ISSUE: Nutrition

### ISSUE THREAD

**Issue by purplerage** [StrangeLoopGames/EcoIssues#5809]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Eat

**Expected behavior:**
Fill the chart according to proper nutritional values

**Actual behavior:**
filled in all stats exactly the same and with no degradation after multiple uses. the text is also showing strange characters

**Comment by MarjieAVolk** [comment]
What operating system are you on?  Can you show a screenshot of these strange characters?

**Comment by MarjieAVolk** [comment]
Also the next time you see this problem, could you attach your output log file? 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by purplerage** [comment]
(sorry ive been away for a few days)

Im running windows 10.
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1805000/output_log.txt)
![untitled](https://user-images.githubusercontent.com/5185338/37316365-d0444778-261b-11e8-8116-56932543df66.png)

**Comment by MarjieAVolk** [comment]
Okay I see - yeah the strange characters are affecting everyone, it is just a visual bug, so not related.

So it looks like your nutrition pie and chart have reasonable looking numbers.  Is this screenshot showing the issue with the pie?  Or what makes you say it is wrong?

**Comment by MarjieAVolk** [comment]
Okay, for the next release we've fixed the strange characters, and also the line wrapping for stomach contents.
