### ISSUE TITLE
USER ISSUE: you can hoe trees?

### ISSUE THREAD

**Issue by squished-01** [StrangeLoopGames/EcoIssues#5811]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. hold a hoe
2. highlight the ground under a tree
3. hoe it and the tree vanishes

**Expected behavior:**
The tree shouldnt vanish.

**Actual behavior:**
It vanishes. Makes it way too easy to grief.  And being able to hoe a tree IRL or in a game makes no sense

**Comment by craig-jong** [comment]
was fixed
