### ISSUE TITLE
Crash when playing with family share users

### ISSUE THREAD

**Issue by alecpura** [StrangeLoopGames/EcoIssues#5813]
Posting this from a ticket in the support queue. Told the user to follow this thread.

Hello,

I write you about a few crashes we’re having since a couple of weeks. The server was running properly for a little longer than a week and then started to crash on regular basis. We have serious suspicions that the crashes are mainly caused by one user, reason being that most of the crashes happen when he is on the server or trying to connect. He’s verified the cache on Steam, reinstalled the game but nothing helped. A detail is that he doesn’t own the game but have it through the Family Library Sharing system of Steam.

Do you know about a solution? In the event you didn't and would like to investigate the issue, please, let me know what file(s) and information you need. 

Regards,
Julien.

**Comment by MarjieAVolk** [comment]
Hey, sorry about your problems.  Can you get me your server crash files?  They will be in '[...]\steamapps\common\Eco Server\Dump' if you are running the steam Eco Server tool.

**Comment by MarjieAVolk** [comment]
Closing due to no response
