### ISSUE TITLE
Basic engineering Skill Book

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#5814]
![image](https://user-images.githubusercontent.com/29807119/37236812-de3bf4d2-240b-11e8-8f0c-7bbb035a4a69.png)

Why Basic engineering skill book need Stone construction????
I ask that because this is the only skill book that need a skill from an other profession (here a speciality of Mason)?!? it seems not logic when you look the other skill book......

We try in our server to limit players to 1 profession (survivalist + 1other profession) to make the game more difficult and force player barter to be collaborative and not be omnipotent but because of that we can not.

![image](https://user-images.githubusercontent.com/29807119/37236860-91968984-240c-11e8-98bf-085935b7bd3c.png)
We try to force people be collaborative by only be able to learn 1 profession (and not omnipotent able to do all by themselve with nobody), and i think it's the general idea of the game ...?!

**Comment by Thyriel** [comment]
You don't need to learn a required specialization to be able to craft a skillbook, using the scroll is enough.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#208
