### ISSUE TITLE
Whaterweel works without water

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#5815]
http://steamcommunity.com/sharedfiles/filedetails/?id=1325844469

It turns around and supplies power even when no water is anywhere near.

**Comment by Conchipedia** [comment]
its been this way for awhile that it doesn't need water, maybe they should call it an Airwheel 😄

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2105
