### ISSUE TITLE
Suggestion: Fuel timer

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#5816]
Not a big thing but would be neat when the fuel page could not only show J per second but also how much minutes / hours of fuel is remaining with the filled fuel.

**Comment by MarjieAVolk** [comment]
I believe it already does so?  It is only enabled while the machine is operating though, if I recall.

**Comment by MarjieAVolk** [comment]
Okay it was not working for me either.  Just found an important bug because of this, thanks!  lol

**Comment by MarjieAVolk** [comment]
Fixed in 7.3
