### ISSUE TITLE
USER ISSUE: Ramps

### ISSUE THREAD

**Issue by purplerage** [StrangeLoopGames/EcoIssues#5817]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Try placing

**Expected behavior:**
Simple to place

**Actual behavior:**
Ramps are incredibly frustrating to place, often requiring several minutes of strafing around and building up dirt platforms to stand on just to get to the right range to place.

**Comment by MarjieAVolk** [comment]
We are working on replacing ramps with blocks.  Hopefully that will be easier to use.

Sounds like maybe you are trying to place the ramps directly in the air, without anything under them?

**Comment by purplerage** [comment]
Sort of?

There are blocks that should be well within reach but I cant place the ramp that close to myself.

I was trying to make ramp down to a mineshaft to drag a cart up and down with me so imagine tight spaces and something that resembles a stair case.

**Comment by TheRealMaxion** [comment]
@RedBlockFilms I think the issue with a lip where cart wheels fall into is fixed by using a road tool on the block.

**Comment by craig-jong** [comment]
I'm going to close this because we're reworking how ramps are placed entirely and reassigning this bug to Eric doesn't seem like it'd be particularly productive.
