### ISSUE TITLE
USER ISSUE: Fish jump into Fish Traps on land

### ISSUE THREAD

**Issue by MeltedPixel** [StrangeLoopGames/EcoIssues#5818]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Build a Fish Trap.
2. Find populated fishing ground.
3. Place Fish Trap on land near water.
(In my testing I have only done 1 tile back. 1 tile up from water source)

**Expected behavior:**
Traps should remain empty when not placed in water.	

**Actual behavior:**
Traps populate with fish while place on docks or beaches near water.

**Comment by SlayksWood** [comment]
It will be fixed in 8.2.0
