### ISSUE TITLE
Weird skillpoint changes in livingroom

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#5819]
I'm sometimes having weird skillpoint changes in my livingroom:
http://steamcommunity.com/sharedfiles/filedetails/?id=1325935250
Without changing anything sometimes the total SP for the house drop down by ~1.5. When i pickup one of the chairs in livingroom and place it at the exact same position in the room again it's going up again.
Another strange thing with that room is, when i pickup that chair and place it down on somewhere else in the same room the total SP varies by ~5 up/down based on where i put that chair down.

**Comment by johnkslg** [comment]
Fixed
