### ISSUE TITLE
Undesired Result when Proposing Multiple Districts

### ISSUE THREAD

**Issue by asniper** [StrangeLoopGames/EcoIssues#5820]
I looked through the bugs and could not find this one, so sorry if i missed it.

When proposing a district, while another proposal for a district is currently in a voting state, the second district proposal, will overwrite the first district proposal. 

### Example

**Player 1** proposes **District A**
**Player 2** proposes **District B** within the 24 hr voting period of **District A**.

If **District A** passes, the District will get created, then when **District B** passes after it, **District A** will be deleted since it was not on the original proposal for **District B**, since it had not passed at the time of the creation of **District B**'s proposal

### Suggested Solutions
- Limit the number of Active District Proposals (not desired)
- When a District passes, automatically amend the active proposals to include that district 
  - *(I understand that this may be troublesome if two district requests happen for the same area of land, not sure what to do about that scenario)*
- show, and restrict District adjustment of an area that is currently being proposed when creating a new proposal.
- Different interface for creating districts as opposed to laws. `¯\_(ツ)_/¯`

**Comment by MarjieAVolk** [comment]
Moving this to our new suggestion project: https://github.com/StrangeLoopGames/EcoSuggestions/issues/9

(P.S. I also think this is a bit troublesome, but I am not sure how to resolve it.  As you noted, merging two proposals might not always work.  And limiting the number of active proposals would prevent, for example, proposing two alternatives at the same time.  So any resolution to the issue looks like it will require a larger revamping of the system.  I will continue to think about it.)
