### ISSUE TITLE
Stone > Sand > Pitch

### ISSUE THREAD

**Issue by Nes112** [StrangeLoopGames/EcoIssues#5822]
Version: 7.3.2

Turning Stone into Sand and Sand into Pitch at the Masonry Table is too easy, especially with max efficiency. It makes stone too important and too easy for a Miner and Mason to do most of the work making mid-tier building materials (mortared stone, brick, glass). It used to be necessary for a Woodcutter/Carpenter to supply pulp/pitch, now they are not as important in the process.

Possible solutions:

- Stone > Sand or Sand > Pitch could be eliminated altogether
- Stone > Sand could be a much higher tier recipe at an industrial grinder kind of machine (factory, rolling mill?). This way beaches won't be depleted making Framed Glass.
- Sand > Pitch could be at a higher tier table, like a blast furnace, and/or require different efficiency than Stone > Sand.

**Comment by Thyriel** [comment]
> It used to be necessary for a Woodcutter/Carpenter to supply pulp/pitch, now they are not as important in the process.

It was never necessary just a good way to get rid of the wood pulps but they always where a bad way to make pitch. Best early game way of making a ton  pitch was Grassland Gathering (Plant Fiber) and midgame Wheat > Pitch.
But i agree at some point, Fiber / Wood Pulp / Wheat Pitch is plenty enough possibilities and removing  Sand > Pitch would be a good idea.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#207
