### ISSUE TITLE
Fish Trap Object code only includes Trout and Salmon as catch options.

### ISSUE THREAD

**Issue by FishAus** [StrangeLoopGames/EcoIssues#5823]
![image](https://user-images.githubusercontent.com/35624562/37239944-b833d138-2497-11e8-8b37-6ee05c4d9324.png)

Might be intended but as you can see only Trout and Salmon are in the list. No Tuna.
If it is intended perhaps a Tooltip to explain Tuna are too smart to be caught by baitless traps?

**Comment by craig-jong** [comment]
Super late, but the original thinking was that tuna were too large/strong for the wooden fish trap. I've changed description.
