### ISSUE TITLE
USER ISSUE: Server is full

### ISSUE THREAD

**Issue by Vancuzya** [StrangeLoopGames/EcoIssues#5824]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Creating new World / Friends can join is on
2. Friend treis to join the world
3. "Server is full" Message appears

**Expected behavior:**
Friend joins the World... ^^;

**Actual behavior:**
Firstofall its happeneing via Lan which previously worked just fine... and it doesnt happen every time, kinda weird

**Comment by MarjieAVolk** [comment]
You may be experiencing this bug: https://github.com/StrangeLoopGames/EcoIssues/issues/3768

You can fix this for your game easily though.  In game, type /openserverui.  In the window that opens, go to the Users tab, then to Config.  Set the "MaxSlots" setting to however many people you want to play with, or to -1 if you want to allow any number.
