### ISSUE TITLE
USER ISSUE: [Dedicated, 7.2.3] Rice won't disappear after picking it

### ISSUE THREAD

**Issue by lefavilla** [StrangeLoopGames/EcoIssues#5829]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Find rice
2. Harvest / pick it up by "E"

**Expected behavior:**
It should disappear instant or fast

**Actual behavior:**
Instead it disappears after 3-10 seconds. Sometimes you need to reconnect.(Not an Hardwareproblem)

**Comment by MarjieAVolk** [comment]
@lefavilla also saw plants taking several seconds to appear after planting them.  Could just be network problems, idk.

**Comment by metachronism** [comment]
dupe of #5036
