### ISSUE TITLE
USER ISSUE: Converting world to new format

### ISSUE THREAD

**Issue by TheWhiteJacket** [StrangeLoopGames/EcoIssues#5831]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. loading old world after update
2. formating wolrd to new format
3. loading world
4. loading objects <- here its crashes!

**Expected behavior:**
converting and loading the old world, so its ready to play

**Actual behavior:**
Connection failed
after loading objects

**Comment by MarjieAVolk** [comment]
Do you have a crash file and/or the save file?

**Comment by MarjieAVolk** [comment]
Closing due to no response
