### ISSUE TITLE
Roundoff error in Small Butchery Efficiency

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#5833]
Expected: Small Butchery Efficiency 1 should give a 20% cost reduction, i.e. 5 items for the price of 4.

This doesn't happen. If you order 5 Butcher Hare recipes, it still costs 5 Hare Carcasses. It should cost 4.

![image](https://user-images.githubusercontent.com/2173684/37241897-619f7e2a-24ac-11e8-827c-368b55962c76.png)

On further inspection, this looks like a floating point division roundoff.

See, for example, if we order 1,000 Butcher Hare recipes, we get nearly the correct result (801 Hare Carcasses required - should be 800.)

![image](https://user-images.githubusercontent.com/2173684/37241905-9725df08-24ac-11e8-9b52-595e81c448b1.png)

I don't think this is related to https://github.com/StrangeLoopGames/EcoIssues/issues/2294 .

**Comment by craig-jong** [comment]
Rounding errors were fixed fairly recently. Let me know if this is still happening.
