### ISSUE TITLE
USER ISSUE: Speed upgrades don't apply to wooden doors

### ISSUE THREAD

**Issue by SeruleBlue** [StrangeLoopGames/EcoIssues#5835]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Level up Woodworking Speed to Lv.5
2. Start crafting Wooden Doors

**Expected behavior:**
The door should take 1 minute each (80% faster than normal), just like the other items unlocked through Woodworking.

**Actual behavior:**
The door takes 5 minutes each.

**Comment by craig-jong** [comment]
I've moved the door to autogen. Finally. Eventually every world object and item will make it to the promised land.
