### ISSUE TITLE
USER ISSUE: Stuck in Blocks when placing stone/ore under yourself.

### ISSUE THREAD

**Issue by Phant0mQ** [StrangeLoopGames/EcoIssues#5836]
**Version:** 0.7.2.0 beta staging-f6bf50db

**Steps to Reproduce:**
1. Stand under a block (can be a ceiling or anything)
2. This block must be 3 blocks high so you can barely fit under it.
3. Pick up some stone or ores
4. Place it under you

**Expected behavior:**
Being pushed to the side to make room for the stone/ore

**Actual behavior:**
Pushed into the ceiling/block above without being able to get out. (if you don't have the right tools)
P.s. if you are pushed inside a block near a stockpile you can't remove the block you are in, when you click you go into the stockpile instead.

**Comment by MarjieAVolk** [comment]
@SeanAtr0n Has this already been fixed?  This was reported on an old version.

**Comment by SlayksWood** [comment]
merged to #6238
