### ISSUE TITLE
USER ISSUE: Failing to remove full storage still has cost

### ISSUE THREAD

**Issue by SeruleBlue** [StrangeLoopGames/EcoIssues#5838]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Have a storage chest with any items.
2. Have not enough space in your inventory to obtain all of the storage chest's items.
3. Attempt to remove the chest with a hammer.

**Expected behavior:**
The attempt should fail without costing tool durability or calories.

**Actual behavior:**
The attempt fails, but it still costs tool durability and calories.

**Comment by MarjieAVolk** [comment]
Fixed in next hotfix
