### ISSUE TITLE
USER ISSUE: Chopping log in water cause it to launch into air

### ISSUE THREAD

**Issue by InzeNL** [StrangeLoopGames/EcoIssues#5840]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
Have a log drop into the water, try to chop it

**Expected behavior:**
The log chops up and keeps floating or goes down to the bottom

**Actual behavior:**
The chopped log flies into the air and comes falling down

**Comment by D3nnis3n** [comment]
No longer occuring.
