### ISSUE TITLE
USER ISSUE: Make currency exchange appear earlier in game

### ISSUE THREAD

**Issue by Scheigy** [StrangeLoopGames/EcoIssues#5848]
**Notes**:
On a side note, I think the Currency Exchange is too expensive to make in the current state of the game. It comes with the Factory, which is, with the default settings, almost the end of the game.

**Attached screenshot**:
![currency_ex2](https://user-images.githubusercontent.com/7931135/37244433-3cd3cf06-2489-11e8-85ee-cc1a15473aff.png)

**Comment by johnkslg** [comment]
Adding Craig for rebalancing note at the end, would be nice to have this soon after mints. 
I'll take a look at the bug part.

**Comment by johnkslg** [comment]
Fixed! Thanks for the detailed report.  
I'll leave this open for @craig-jong as I agree it could be earlier in the game.

**Comment by craig-jong** [comment]
it was moved
