### ISSUE TITLE
7.2.3 Shopkeepers not taxed in buy/sell orders.

### ISSUE THREAD

**Issue by MittenMarauder** [StrangeLoopGames/EcoIssues#5850]
**Server, Client or Website?** Client

**OS/Web Browser?** Win10

**Detailed Description of Issue:** When Buying or Selling, Shopkeeper isn't taxed. Does not seem like intended behavior because shop should be taxed when the shop is buying items. Instead, the person using the store is being taxed when buying items and selling items.

**Reproducible?** How difficult is it to reproduce? Yes. Easy.

**Steps to reproduce bug/issue:** Buy/Sell with Taxes active.

**Additional Comments:** N/A

**Client Version?** 7.2.3

Include recent Crash dump ( get only generated if the server crashes): N/A

**Comment by Spoonfed** [comment]
Can confirm that this is what happens. The person using the store is taxed both ways. This means I will not deliver any resources. I am not getting taxed to bring you stuff.

**Comment by MarjieAVolk** [comment]
Fixed in 7.3.  The person who is paying money is now responsible for paying taxes (calculated on a per item basis when doing a multi-item trade)
