### ISSUE TITLE
USER ISSUE: Bricks in stockpile, hitbox blocks grid outside stockpile

### ISSUE THREAD

**Issue by ataboo** [StrangeLoopGames/EcoIssues#5851]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Put bricks in first slot of a stockpile so they end up appearing in the North West corner (mine were in the first slot but they would move when other things did)
2. Try to walk past the West side of the stockpile's North West corner.

**Expected behavior:**
No collision outside the stockpile/brick model

**Actual behavior:**
Blocks the neighbouring grid enough to prevent passage if it is 1-wide.  Moving the bricks corrects it.

![image](https://user-images.githubusercontent.com/5650738/37244852-33f3ff10-244c-11e8-8b02-d8af7bb4ff7b.png)

![image](https://user-images.githubusercontent.com/5650738/37244859-5d5f15a6-244c-11e8-8749-d48eb9790571.png)

**Comment by metachronism** [comment]
verified fixed 7.5.1
