### ISSUE TITLE
USER ISSUE: [Dedicated. 7.2.3] Tomatoes influence Moisture to much

### ISSUE THREAD

**Issue by lefavilla** [StrangeLoopGames/EcoIssues#5852]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Look where tomatoes grow well
1a. check with your Sampler
2. Hoe 3 GrassBlocks within the same 5x5 plot
3. Plant 3 Tomatoes
4. Take shovel and make every GrassBlock to DirtBlock
5. check healthstatus again. Moisture is ruined

**Expected behavior:**
Tomatoe shlould grow well in the range between 30-90% compaltiblity

**Actual behavior:**
Instead the tomatoe changes the moisture?

**Comment by MarjieAVolk** [comment]
I believe that plants consume some moisture, but a drastic difference with only 3 plants sounds odd.

**Comment by Legends0** [comment]
![image](https://user-images.githubusercontent.com/5702579/38227596-f398a054-36cc-11e8-9a16-41f87f77b9a6.png)
Something is off with tomatoes yield. TomatoesYieldPotential suggests that it would have high yield, but this one plot is 0% match for tomatoes.

Very strange how over 3 days, the area has been 100% tomatoes just fine, and moisture actually rose.

**Comment by beastyn** [comment]
seems to br fixed
