### ISSUE TITLE
USER ISSUE: Continue Button Fails Since update to 7.2

### ISSUE THREAD

**Issue by Ironhelix98** [StrangeLoopGames/EcoIssues#5856]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Since the update from 7.1 to 7.2 the continue button fails with the below message. I can work around the issue by clicking Join and finding the server that way. The server is located on the same network as myself. Please let me know if there is any further information needed.

**Expected behavior:**
Continue button should word

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Often in this case, deleting the folder 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO' seems to fix this problem.  If you could, move that folder elsewhere and if that does fix your problem, zip the folder up and send it to me.  Would be nice to prevent this from happening.

**Comment by Ironhelix98** [comment]
@MarjieAVolk sorry for taking so long on getting back to you. I tried deleting/moving the above folder and it did not fix the issue. Either way, here are the copies of my 2 attempts and the current ECO folders found at the above location. 1 is the original and 3 is the current.
[Eco - Error - 1.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1809038/Eco.-.Error.-.1.zip)
[Eco - Error - 3.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1809039/Eco.-.Error.-.3.zip)
[Eco - Error - 2.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1809040/Eco.-.Error.-.2.zip)

**Comment by MarjieAVolk** [comment]
Deleting the folder didn't help?  So when you tried this, you deleted the folder, then reconnected to the server you wanted to join without using the Continue button (because the button was reset) and that worked, then you tried to use the Continue button again and it still didn't work?  Is this linked to a specific server in that case, perhaps?

**Comment by Ironhelix98** [comment]
Yes, I did the steps as you outlined them above. That being said I also used the same server every time. Tomorrow I'll try connecting to another server and seeing if it is related to the server I am using. If it helps I own the possible trouble-making server and it is located on the same subnet as myself.

**Comment by MarjieAVolk** [comment]
Well I would suggest some network steps, like disabling DetectNAT on your server, but if you can connect to it directly and just not via the continue button, then it seems like it's not a network problem.  I was thinking maybe the name of the server might be weird or something.

**Comment by metachronism** [comment]
closing as dupe/similar issue to #4267
