### ISSUE TITLE
Need 'ok' button on connection dialogs

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#5857]
![image](https://user-images.githubusercontent.com/3536496/37246752-612fdcf2-2464-11e8-8da8-0a77d1e4470b.png)

Pressing escape here opens the settings, escape should also close it. Not clear you need to click.

**Comment by WeaselDog** [comment]
This has an error box now and pressing escape will close it.
![ConnectionFailed](https://user-images.githubusercontent.com/47330823/71489576-1745e880-27db-11ea-90ea-fe8098ac617c.png)
