### ISSUE TITLE
USER ISSUE: bug from a little tree

### ISSUE THREAD

**Issue by xarnarany** [StrangeLoopGames/EcoIssues#5862]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
I wanted to remove a tree seedling and then this error message came in addition, I would like to note that from time to time there are the invisible plants houses you can not plant anything. even if you remove the soil and then set it down again, the invisible plant is still there.

excuse me for my english a large part is translated with google thank you in advance.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei Eco.Simulation.Agents.Plant.Destroy()
   bei Eco.Simulation.Agents.Tree.Destroy()
   bei TreeEntity.Destroy()
   bei TreeEntity.TryApplyDamage(INetObject damager, Single amount, InteractionContext context)
   bei Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   bei Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)



Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>
```

**Comment by MarjieAVolk** [comment]
Thanks for the report.  The stack trace you gave is reported here: https://github.com/StrangeLoopGames/EcoIssues/issues/5619.  The issue with invisible plants is reported here: https://github.com/StrangeLoopGames/EcoIssues/issues/5603 https://github.com/StrangeLoopGames/EcoIssues/issues/5321

Closing as duplicate
