### ISSUE TITLE
Broken World, Desert problem

### ISSUE THREAD

**Issue by alexwrtm** [StrangeLoopGames/EcoIssues#5863]
Yesterday we have talked about our Map where our wetland turned into a desert within a half day ... now it turn´s from desert to wet land and back randomly all the time. For checking our Map for Bugs are here all of our files. Now we are on Day two with a new generated Map after the Update 7.2.2 .

https://www.dropbox.com/sh/5p8lzj8kw8x23pi/AAC4K1dUUiuL4NxF6MxD27l0a?dl=0

**Comment by GophTheGreat** [comment]
Reopen if it occurs again. Locking for now.
