### ISSUE TITLE
USER ISSUE: Invisible Ramp

### ISSUE THREAD

**Issue by hurraybies** [StrangeLoopGames/EcoIssues#5869]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Applies to 7.2.2, 7.2.3. Unknown steps.

**Expected behavior:**
Ramp model is visible.

**Actual behavior:**
Ramp is invisible and has no collision. Cannot place anything on top. Issue arose updating from 7.1.2 to 7.2.2. Not all ramps are affected.

**Comment by MarjieAVolk** [comment]
Do you have a save file where this consistently happens?

**Comment by Alloc86** [comment]
Think this is the same as what we are experiencing.

**Version:** 0.7.2.5 (fresh world)

**Coordinates:** 558, 604

**Actual behaviour:** Stone ramps, a door, a few stock piles, a chest, a door and maybe other stuff that I'm not noticing is neither rendering nor interactable. New blocks can not be placed in these positions though and inventories can still be used through the linking system.

**Savegame/configs:**
[Eco-5869.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1837352/Eco-5869.zip)

**Missing stuff:**
![issues_outside](https://user-images.githubusercontent.com/5400030/37768861-617947b0-2dcf-11e8-95e1-59cb90a8ce91.jpg)
![issues_outside2](https://user-images.githubusercontent.com/5400030/37768862-61971da8-2dcf-11e8-960b-6c4721056d66.jpg)
![issues_basement](https://user-images.githubusercontent.com/5400030/37768860-6153e9ac-2dcf-11e8-87a2-a9a609b1954a.jpg)

**Inventories of the missing storage still here:**
![inventories](https://user-images.githubusercontent.com/5400030/37768859-612edf90-2dcf-11e8-8999-a42787830c3c.jpg)

**Comment by SeanAtr0n** [comment]
probably fixed already but definitely fixed in 7.7
