### ISSUE TITLE
USER ISSUE: Conect

### ISSUE THREAD

**Issue by Seysko** [StrangeLoopGames/EcoIssues#5874]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Connecting to the server
Error
​Login info could not be verified. Your auth servers may be down

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Has this happened more than once?  Does it happen on a specific server?  Does it always happen for you?

**Comment by Seysko** [comment]
it happens constantly, except for its own personal server. But when I try to go to someone else on the server, I get this error.

**Comment by MarjieAVolk** [comment]
Okay.  Are you running the game from steam?  Or from our site download?

**Comment by Seysko** [comment]
From steam. And I linked my steam to my account on the site.

**Comment by MarjieAVolk** [comment]
In that case, your strange loop account may have an error on it.  What is your Strange Loop username?  We may be able to fix your account in the database.

**Comment by Seysko** [comment]
User name Seysko, id-slg94547

**Comment by Seysko** [comment]
Thank you very much, my mistake is corrected. On the server to your friends, there are no more errors. Good rauyot.
