### ISSUE TITLE
USER ISSUE: Hunger Glitch

### ISSUE THREAD

**Issue by Villerger27** [StrangeLoopGames/EcoIssues#5876]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
None, it just happened

**Expected behavior:**
When working, the calories should just go down

**Actual behavior:**
Instead, the calories go up

**Comment by Nenormalus** [comment]
if you are admin and was using command /durability on the tool and made it bigger then it supposed to be then you getting calories not losing them.

**Comment by Villerger27** [comment]
Well thank you for telling me, I can see why it would do that,

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by craig-jong** [comment]
Calorie consumption no longer scales with durability in 7.3, so this shouldn't be an issue in that build. Please reopen it if it is.
