### ISSUE TITLE
Another crash issue with no dumb errors 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#5878]
Random crashes with no error logs can happen like 3 times a day and sometimes in short intervals like several times within hours- Only event viewer is logging the crash.

CPU and Memory usage are low ( 10 % cpu and 1 gb ram in general) 

<img width="960" alt="eco_server_error" src="https://user-images.githubusercontent.com/1668416/37249868-eeee1d02-24ef-11e8-9220-df825b497185.png">
<img width="960" alt="eco_server_error_2" src="https://user-images.githubusercontent.com/1668416/37249869-f0f6d8e6-24ef-11e8-9f08-1ce135115538.png">

**Comment by metachronism** [comment]
unfortunately will need more information to debug this
