### ISSUE TITLE
USER ISSUE: second layer items not visible

### ISSUE THREAD

**Issue by Harmarz** [StrangeLoopGames/EcoIssues#5879]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
drop 1st layer of items or wall down
drop 2nd layer down

2nd layer isnt visable
disconnect
reconnect
2nd layer visable

**Expected behavior:**
2nd layer of items be visable after placement
items taken from carry inventory

**Actual behavior:**
2nd layer of items invisable
items taken from carry inventory

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/5849

**Comment by metachronism** [comment]
keegan's fixed this
