### ISSUE TITLE
Audio continually muting itself

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#588]
I have to keep setting it back to maximum; unless theres a hotkey I'm pressing...

**Comment by pan7s** [comment]
Yes I have this issue aswell. Volume sliders default to off

**Comment by Nanders** [comment]
Any idea how to repro? Or has this been fixed?

**Comment by noblackthunder** [comment]
look at post 20 http://ecoforum.strangeloopgames.com:4567/topic/1021/alpha-5-known-issues/20

**Comment by mauzao9** [comment]
On Alpha 5 only, facing issue like this. I have a GIF https://www.dropbox.com/s/7amq7ls6lgs5ixe/2016-11-04_11-54-40.gif?dl=1 of the thing always going back as soon I do ESC.

The interesting thing is that even muted, I can hear only the sound of the chat messages beeping. This is Alpha 5 only.
