### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by AbyssalOne** [StrangeLoopGames/EcoIssues#5883]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Clicked on Continue.
Sever Strat Progess. 
Connection Failed. 
I am not playing on any server, the World is local 

**Expected behavior:**
It Should have start the game, this is my 3rd World wich is fucked up like that. 

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Could you send me any crash files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'?  It's likely that your server is failing to start up.

You can also try the following workarounds:
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software

**Comment by MarjieAVolk** [comment]
Closing due to no response.
