### ISSUE TITLE
You get to pick it up but not set it down, Stockpiles

### ISSUE THREAD

**Issue by PerksPrisoner** [StrangeLoopGames/EcoIssues#5885]
So the stockpile allows the excavator to pull out of it like it is regular soil but won't allow you to place it.
![20180311031125_1](https://user-images.githubusercontent.com/22648457/37252193-54fd803a-24da-11e8-9746-21d05ea77a1a.jpg)

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2651
