### ISSUE TITLE
USER ISSUE: Can´t connect to the game

### ISSUE THREAD

**Issue by Pinguinpalad** [StrangeLoopGames/EcoIssues#5886]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
I´ve closed the game today in the morning. When I try now to connect to my world there is the loading screen. But when it gets to the point "Loading StorageManager" the game the game minimize itself and shows me my Windows Desktop screen. After maximize the game the eroor message "Connection Failed" stands on the screen.

**Expected behavior:**
It should have load the world.

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by Pinguinpalad** [comment]
Well, I don´t know where the problem was. I found the backup-file and replaced the actuall files. Now I can start the game without problems.

**Comment by MarjieAVolk** [comment]
Probably your server was failing to start up.  If you could send me any crash files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump', I can try to find why it was crashing.
