### ISSUE TITLE
USER ISSUE: "Plant already exists there."

### ISSUE THREAD

**Issue by Hero2442** [StrangeLoopGames/EcoIssues#5887]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Plant any seed(Corn, Tomato, Beans, Camas...)
2. Wait some time, until most of the field is grown
3. Harvest the hole field(including the plant that aren't fully grown)
4. Try to plant seed at the places were you harvested the not fully grown plants beforehand.

**Expected behavior:**
Plant the desired plant :D

**Actual behavior:**
Notification pops up:    "Palnt already exits there" 

Can not plant a plant :(

**Some sort of solution:**
Tried to dig away and back the dirt:  -Still "Palnt already exits there" 
Lay some dirt above it: - Still "Palnt already exits there" 
Restart: -Still "Palnt already exits there" 

Wait until an tree sapling gets planted by itself at the desired field and remove it afterwards - No notification "Palnt already exits there" and the plant gets planted

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/5522 and https://github.com/StrangeLoopGames/EcoIssues/issues/4669

**Comment by craig-jong** [comment]
I've never been able to reproduce this despite trying.

If this occurs past 7.3, please attach a save file so I can check that.

**Comment by zEverdeen** [comment]
I had Yamajama add his save to this issue, should be here shortly.

**Comment by CuAnnan** [comment]
https://www.dropbox.com/s/8ml3019yytq7ycm/eco%20downloads.zip?dl=0

**Comment by CuAnnan** [comment]
Issue not fixed by latest patch.

**Comment by MarjieAVolk** [comment]
Yeah, sorry about that - we are still tracking this issue in https://github.com/StrangeLoopGames/EcoIssues/issues/4669

For now, restarting your server should cause existing phantom plants to go away.  But you may continue to see more appear as you play (which we are now working on fixing).

**Comment by CuAnnan** [comment]
Thanks Marjie.
