### ISSUE TITLE
Upgrading world from 0.7.1.2 to 0.7.2.0/3 botches Skill Multiplier

### ISSUE THREAD

**Issue by tlobig** [StrangeLoopGames/EcoIssues#5890]
Steps to reproduce:
1. copy a 0.7.1.2 world to the storage path of a clean 0.7.2.3 installation.
2. start this world up
3. look at the skill multiplier

expected (in my case, high default mulitplier in a singleplayer world):
![grafik](https://user-images.githubusercontent.com/10432347/37253334-c26f7276-2530-11e8-92e6-2e3c37ef3d55.png)

actual (applied multiplier seems to be 1, display of multiplier corrupted):
![grafik](https://user-images.githubusercontent.com/10432347/37253263-d023f9ec-252f-11e8-91db-8e5134101d74.png)

background:
Windows 10 64bit system with German locale

**Comment by Thyriel** [comment]
Sounds like it could be the general problem we mentioned/discussed here already somewhere a few weeks ago: Config files and Mod files are just gamefiles like all others so when there is a patch providing new default configs/mod files that patch just overwrites your settings.

**Comment by tlobig** [comment]
Just for clarification, is the file in the server storage folder all I need to copy my world from one version to another?

**Comment by Thyriel** [comment]
No, the skillpoint config is not stored in the world savegame, it's in Configs/difficulty.eco

**Comment by MarjieAVolk** [comment]
Yeah, you have just lost your config, since the config is not in the save file.  The N's are unrelated.  I would like to improve this experience.  We have some bugs for it open already (see eg. https://github.com/StrangeLoopGames/EcoIssues/issues/3977)
