### ISSUE TITLE
Fuel consumption is double as fast as it should be

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#5892]
According to "Power" tab Stone Brazier uses 1 J / sec.
Coal has 20.000 Joule so it should use 4.3 coal per 24 hours.

I placed a couple of them as street lights around 13-14 hours ago, filled each with 10 coal but now they already burned through 5.5 coal which should have been the consumption for ~30 hours

**Comment by Thyriel** [comment]
After some more testing on other things it seems this is a global problem and not restricted to the stone brazier. Kiln burns through a coal every ~3minutes but 50 J/sec should be 1 coal every 6 minutes. Same with blast furnace.
Either all fuel rates (J/sec) are displayed wrong, coal provides 10.000 J and not 20k like in the tooltip or all fuel consumptions are double as high as they should be.

**Comment by MarjieAVolk** [comment]
Fixed in 7.3
