### ISSUE TITLE
USER ISSUE: Failed to login

### ISSUE THREAD

**Issue by talpalababa** [StrangeLoopGames/EcoIssues#5893]
Today i tried starting eco 7.2.3 Win 64 (first time ever to start it) and when trying to login i got this error message:

Failed login
Error getting response stream (Write: The authentification or decryption has failed.): SendFailure

**Comment by MarjieAVolk** [comment]
Did you see that message in an error popup?

Were you running the game from steam?

**Comment by talpalababa** [comment]
I did see that message as an error popup, but not in the steam version. I did run the version from the website.MarjieAVolk <notifications@github.com> hat am 13. März 2018 um 01:47 geschrieben:  Did you see that message in an error popup?Were you running the game from steam?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by MarjieAVolk** [comment]
Okay, sounds like your Strange Loop account probably has an error on it.  What is your Strange Loop username?

**Comment by MarjieAVolk** [comment]
@rainfarmer, the second half of the error message ("Error getting response stream (Write: The authentification or decryption has failed.): SendFailure") is from /responsev4

**Comment by talpalababa** [comment]
My username is talpalababa.MarjieAVolk <notifications@github.com> hat am 13. März 2018 um 19:57 geschrieben:  Okay, sounds like your Strange Loop account probably has an error on it. What is your Strange Loop username?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by rainfarmer** [comment]
I don't see any errors in your account. 
Sent you an email with some troubleshooting steps.

Will update here with solution.
