### ISSUE TITLE
USER ISSUE: Devtool Will Remove Bedrock

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#5898]
**Version:** 0.7.2.3 beta

as you can see i removed Bedrock with a devtool and replaced with Mortared Stone
![snap1992](https://user-images.githubusercontent.com/29383891/37254508-cc00ccee-2536-11e8-91fc-ad24b9514748.png)
![snap1993](https://user-images.githubusercontent.com/29383891/37254509-cc1a2c52-2536-11e8-926d-68c4dd4af544.png)

![snap1994](https://user-images.githubusercontent.com/29383891/37254490-6597a4d2-2536-11e8-957f-cfc729dff6b6.png)
but if you place any block on top of the bedrock within a certain radius (i think its the world chunks) it will automatically put it back

**Comment by craig-jong** [comment]
This is intentional, though. The DevTool is for smiting anything and everything.

**Comment by gau-veldt** [comment]
But here's the million tailings question: can the devtool replace bedrock it (say accidentally due to a stray click which frequently happens during a lagspikes) smited?
