### ISSUE TITLE
USER ISSUE: Exception while mining

### ISSUE THREAD

**Issue by pointlessPointer** [StrangeLoopGames/EcoIssues#5902]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
unsure, maybe pick up stone while using pickaxe

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
Caught exception:

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

Stack:
   bei Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   bei Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5496
