### ISSUE TITLE
USER ISSUE: Falling off the world

### ISSUE THREAD

**Issue by wietse292** [StrangeLoopGames/EcoIssues#5904]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Parts were rendering, I dont know why

**Expected behavior:**
Rendering

**Actual behavior:**
I fell through it and started falling, and because you cant die or something i just kept falling

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5917
