### ISSUE TITLE
Creosote Bush layers

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#5907]
As you can see on the picture bellow, there is a problem with Creaosote bush layers: 
![image](https://user-images.githubusercontent.com/29807119/37255704-65793546-2550-11e8-97ef-62527e9d6707.png)
We have the Potential Layer for farmers but  the natural spawn layer is set to ZERO so no natural plants.
Exactly the same problem as for wheat when the Beta start on steam release.

The only thing we are able to do is:
- add manually creosotebush on first layer using Ecopanel
- use ingame commands to manually spawn CreosoteBush
We have to wait for un update of this layer from SLG then we will be able to regen this Layer

**Comment by craig-jong** [comment]
You can run /regenlayer to get specific layers to regenerate, but in order to completely fix this issue, we need a much large change to world gen.

**Comment by craig-jong** [comment]
We've added changes so that plants are forced to spawn after worldgen. It's still possible, but very rare. We'll be looking at worldgen soon.
