### ISSUE TITLE
Trees can grow on filled stockpiles

### ISSUE THREAD

**Issue by myperx** [StrangeLoopGames/EcoIssues#5913]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. fill a storageplace with dirt
2. cut some trees nearby 

**Expected behavior:**
nothing should happen	

**Actual behavior:**
on top of the dirtstorage spawns a sepling and grows a tree??

**Comment by elfl0rd** [comment]
dupe https://github.com/StrangeLoopGames/EcoIssues/issues/6902 :P

**Comment by D3nnis3n** [comment]
Duplicate
