### ISSUE TITLE
USER ISSUE: Game Crash

### ISSUE THREAD

**Issue by MountnDewd** [StrangeLoopGames/EcoIssues#5916]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. I opened the game as usual using steam,
2. I clicked on "Continue" because i already had a good savegame
3. Game crash "Connection Failed"
(Also creating a new world failes)

**Expected behavior:**
It should have started the game as it did before	

**Actual behavior:**
Instead it crashes, then minimizes and then says "Connection Failed"

**Comment by MarjieAVolk** [comment]
Can you send me your server crash files, in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'?

You may be able to load a backup that doesn't crash.  Look inside '[...]\steamapps\common\Eco\Eco_Data\Server\Storage\Backups' for the most recent backup, and copy the files out into the Storage folder, replacing the existing save files with those.

**Comment by MarjieAVolk** [comment]
Closing due to no response
