### ISSUE TITLE
Fell through the world

### ISSUE THREAD

**Issue by FinnLeh** [StrangeLoopGames/EcoIssues#5917]
I wanted to go around the world, to prove that the world of eco is a ball. But when I was like at the half of the way, there was a line of about 10 blocks without any terrain. First I thought, it would only be a screen bug.

But when I wanted to walk on these invisible terrain, I was falling through the world...

Here is a screenshot on [Steam.](http://steamcommunity.com/id/finnleh/screenshot/937184972377068342)

I don't know if it's just a bug in this session or if it stays forever...we'll see  :)

**Comment by MarjieAVolk** [comment]
More chunk load problems :'(

**Comment by metachronism** [comment]
It should resolve itself after a reconnect, so lowering priority

**Comment by J-1** [comment]
My truck fell through the crust of the planet, near my main play area, possibly while all players were offline, possibly during the upgrade from 8.2.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3330102/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3330103/Player-prev.log)
