### ISSUE TITLE
USER ISSUE: To many Skillpoints

### ISSUE THREAD

**Issue by Umoy** [StrangeLoopGames/EcoIssues#5921]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
I got 11.914 Skillpoint in ine day... i didn't change the server options... 	

**Expected behavior:**
I should have about 30 skillpoints....	

**Actual behavior:**

**Comment by MittenMarauder** [comment]
Did you run out of food? You stop gaining points if you are at 0 calories.

**Comment by Umoy** [comment]
No I didn`t run out of food.

The problem is, that i got over 10k skillpoints from one day to anther and I don`t know why...

Could the new update have changed the server configuration?

In the meantime I think I`ve found out that I earn skillpoints for crafting.

But I didn`t set this up in the server config.


________________________________
Von: MittenMarauder <notifications@github.com>
Gesendet: Montag, 12. März 2018 19:05
An: StrangeLoopGames/EcoIssues
Cc: Umoy; Author
Betreff: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: To many Skillpoints (#5921)


Did you run out of food? You stop gaining points if you are at 0 calories.

**Comment by MarjieAVolk** [comment]
Is this on your own local world?  Are you seeing this bug? https://github.com/StrangeLoopGames/EcoIssues/issues/3768

**Comment by craig-jong** [comment]
Guessing this was a difficulty bug. Reopen if you have more information.
