### ISSUE TITLE
USER SUGGESTION: Anvil

### ISSUE THREAD

**Issue by NortonDK** [StrangeLoopGames/EcoIssues#5924]
**Version:** 0.7.2.3 beta

Make anvil craftable in something that isn't a bloomery, so you can stop using the bloomery completly.

**Comment by rpsiv** [comment]
Also could it be reduced to a tier 1 building?  Only 2/3 of the tier 2 building options are available to you since Lumber requires a Saw Mill which is produced by an Anvil.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#206
