### ISSUE TITLE
USER ISSUE: No Mushrooms

### ISSUE THREAD

**Issue by Fuchur414** [StrangeLoopGames/EcoIssues#5928]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Create a normal World

**Expected behavior:**

**Actual behavior:**
There are no Mushrooms on the entire map

**Comment by rpsiv** [comment]
I am also having this issue, which makes it impossible to get the farming skill.

**Comment by PoK-Micky** [comment]
Also having this issue, I also cant find rice in my wetlands, unless rice is bunchgrass.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5568
