### ISSUE TITLE
USER ISSUE: Items get stuck while dragging

### ISSUE THREAD

**Issue by brehmluke** [StrangeLoopGames/EcoIssues#5931]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
Drag some items from your inventory to chest, eventually it keeps happening

**Expected behavior:**
The items move from your inventory to chest

**Actual behavior:**
The items get stuck while being moved and the picture never leaves your screen till restart

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841
