### ISSUE TITLE
USER ISSUE: Pump Jack, Insufficent Power

### ISSUE THREAD

**Issue by Imothep80** [StrangeLoopGames/EcoIssues#5940]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
- Build a Pump Jack
- Build an Waterweel or Windmill
- Place Pump Jack to ground and give him Power
- all fine. Lamp green
- Start an Project	

**Expected behavior:**
After start Project it should use the power produced by generator.

**Actual behavior:**
After start Project he has insufficent Power.

**Comment by MarjieAVolk** [comment]
This is probably because while not running, the pump jack is not attempting to consume any power, so its power consumption will always be green while not running.  Once it starts trying to run, it will start requesting power.
