### ISSUE TITLE
USER ISSUE: Unable to login

### ISSUE THREAD

**Issue by talpalababa** [StrangeLoopGames/EcoIssues#5941]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. Start game
2. Try to login

**Expected behavior:**
Get logged into the game

**Actual behavior:**
An error message pops up: Failed to login
Error getting response stream (Write: The authentification has failed.): SendFailure

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5893
