### ISSUE TITLE
Suggestion: Hide the discord part of the server GUI, until it is fully implemented.

### ISSUE THREAD

**Issue by zEverdeen** [StrangeLoopGames/EcoIssues#5942]
Right now the support channel often gets questions about how to enable discord.

Also, clarify what ports are needed. I personally think 2999 TCP is a myth, as I have only found a server listening on 2999 UDP, which would make sense if it is used for discord. Currently, the support channel says it is TCP, this will lead to issues down the road, as people will forward TCP, not UDP.

**Comment by metachronism** [comment]
removed the internal discord plugin - there is a mod version however
