### ISSUE TITLE
"Put Items in Container" contracts track the wrong quantity

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#5943]
When attempting to complete a "Put Items in Container" contract,

The contract completion criteria is based on the number of items **currently in the container** - not the amount of items that the Contractor has inserted into the container.

Take this contract as an example:

![image](https://user-images.githubusercontent.com/2173684/37287713-2db97eb6-2651-11e8-9841-20af1789aea8.png)

* This contract was to insert 30 Mortared Stone into a stockpile.
* The stockpile was linked to a crafting project.
* The Contractor inserted 30 Mortared Stone, but it was immediately consumed by the crafting project.
* The Contractor was unable to complete the contract, because the target stockpile **currently** contained zero Mortared Stone (despite the Contractor having fulfilled their obligation to deliver 30 Mortared Stone to the nominated place.)
* The Principal manually marked the contract as complete, so the Contractor could be paid.

The expected behaviour is that items are counted *at the moment the Contractor inserts them into the stockpile.*

**Comment by LiaungYip** [comment]
Note: Further testing on 0.7.2.3 showed that the buggy behaviour is limited to Stockpiles. Storage Chests work fine.

**Comment by LiaungYip** [comment]
Note 2: This may actually be a duplicate of #6050. Will test further.

**Comment by GophTheGreat** [comment]
Seems to work now. Reopen if it occurs again.
