### ISSUE TITLE
"Receive Permissions" contract clause cannot grant Property Rights

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#5944]
When attempting to define a "Receive Permissions" contract clause,

There are two options - to grant "Object Rights" and to grant "Property Rights".

I attempted to grant "Property Rights" as follows:

1. Make a new contract.
2. Add a "Receive Permissions" clause.
3. At the "Gain..." drop down, select "Property Rights".
4. Click the "From... Pick" button to try and select the target property.
5. The "Choose Contract Destination" dialog is displayed, but it only shows storage inventories. **I expected it to show a list of properties, i.e. "Lwsburg" or "Kadrinshire".**

![image](https://user-images.githubusercontent.com/2173684/37289081-900cb67a-2654-11e8-996b-3ed0bb2b754a.png)

**Comment by Alteraner** [comment]
It would be great if it would be fixed soon. It would help to make the contract board much more usefull. And by the way, if i choos Object Rights it always give full access to the complete property and not the object.

**Comment by olegshegai** [comment]
https://drive.google.com/open?id=1GuybbVcvOab-Dno4cesWm3tfV8OYS2pj
Will commit and PR it tonight

**Comment by beastyn** [comment]
1. Make contract with property permission. Put a chest on this property.
2. Someone should take a contract
3. Someone now has access to your deed AND objects on it (someone can take things and put thing to your chest)
Can we limit rights so someone can't use objects if you has deed rights? (like with add/remove contracts still limit your interaction with stockpile)
