### ISSUE TITLE
USER ISSUE that can crash server. Digged cube disappear in hands

### ISSUE THREAD

**Issue by Kastuk** [StrangeLoopGames/EcoIssues#5949]
If you dig and in moment of shovel strike will change tool to Scythe of Soil sampler, pile of dirt/tailings/etc just disappear. 
After third-fourth one server may crash.

**Comment by GophTheGreat** [comment]
Cannot reproduce, but maybe it'll be easier to reproduce on a low-performance system? Closing anyway for now.
