### ISSUE TITLE
USER ISSUE: Connection Failed after New game.

### ISSUE THREAD

**Issue by DonnyLee** [StrangeLoopGames/EcoIssues#5955]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
New game,
Name the Game "HelloWorld:)"

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Could not create save file: Destination directory not found: C:/SteamLibrary/steamapps/common/Eco/Eco_Data/Server/Storage\HelloWorld
```

**Comment by MarjieAVolk** [comment]
Hm, sounds like it doesn't like the ':' character perhaps.

**Comment by WeaselDog** [comment]
Unfortunately the ':' character is not supported when hosting through the Steam game client. If you host using the Eco Server tool, you can rename the server "HelloWorld:)" 

There is a new error message on Steam to prevent this from happening to someone else. Thanks for reporting this.

![HelloWorld](https://user-images.githubusercontent.com/47330823/71127875-c6157380-21a0-11ea-9432-95a7c8910eb7.png)
