### ISSUE TITLE
7.2.3 Incorrect Windmill Animation Direction

### ISSUE THREAD

**Issue by MittenMarauder** [StrangeLoopGames/EcoIssues#5956]
**Server, Client or Website?** Client

**OS/Web Browser?** Win10

**Detailed Description of Issue:** Windmill animation spins incorrectly regardless of placement. Should be reversed.

**Reproducible? How difficult is it to reproduce?** Yes. Easy.

**Steps to reproduce bug/issue:** Place Windmill.

**Additional Comments:** N/A

**Client Version?** 7.2.3

Include recent Crash dump ( get only generated if the server crashes): N/A

**Comment by elfl0rd** [comment]
Looks fixed.

**Comment by GophTheGreat** [comment]
Looks fine. Closing.
