### ISSUE TITLE
USER ISSUE: Wood

### ISSUE THREAD

**Issue by Xnetsrac** [StrangeLoopGames/EcoIssues#5957]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
when i will haverest a tree and pickup logs

**Expected behavior:**

**Actual behavior:**
Caught exception:

<size=60,00%>Caught exception invoking RPC PlayerInteract on Player!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

Stack:
   bei TreeEntity.TrySliceTrunk(Player player, Single slicePoint)
   bei Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   bei Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3752
