### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Ksenija94** [StrangeLoopGames/EcoIssues#5958]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Could not create save file: C:/Games/ECO v0.7.2.2/Eco_Data/Server/Storage\Мирок.eco already exists
```

**Comment by MarjieAVolk** [comment]
This means that you already have a world with that name.  Try choosing a different name, or deleting the save file from your computer.
