### ISSUE TITLE
USER ISSUE: Hovering mouse over LOADS of Specialities shows an Error message

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#5967]
**Version:** 0.7.3.0 beta staging-facee1c6

![snap2002](https://user-images.githubusercontent.com/29383891/37310245-384baa86-263b-11e8-8dcb-b96ed57d1e11.png)
![snap2003](https://user-images.githubusercontent.com/29383891/37310403-b6cffe2a-263b-11e8-96e0-ce7f0e23c50d.png)
![snap2004](https://user-images.githubusercontent.com/29383891/37310404-b6f10782-263b-11e8-93b2-fd25e1520018.png)
![snap2005](https://user-images.githubusercontent.com/29383891/37310406-b7102db0-263b-11e8-9a88-e16ace8d1577.png)

**Comment by Conchipedia** [comment]
Mentioned this on Discord, now closing as this version is Ultra Broken

**Comment by MarjieAVolk** [comment]
Yeah @Nanders has been working on fixing this this morning
