### ISSUE TITLE
USER ISSUE: Pipe-Location Stove

### ISSUE THREAD

**Issue by Geisterlein** [StrangeLoopGames/EcoIssues#5969]
**Version:** 0.7.2.3 beta

1. You can not attach the pipe to the correct output of a stove
2. I also attached an other device to the pipes the output of the air pollution is also at the stove

**Comment by Ardesy** [comment]
Same, Stove didnt has an workking Pipe Output Port

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5805
