### ISSUE TITLE
No default world folder on fresh install on Mac

### ISSUE THREAD

**Issue by haniawni** [StrangeLoopGames/EcoIssues#5973]
Hello!

With a fresh install of the regular game (*not dedicated server*) on OSx through either an external download or through Steam, there is no default world file,  so just hitting "New Game > Start" gives a bug report popup:
```
Could not create save file: /Applications/Eco.app/Contents/Server/Storage/DefaultWorld does not exist
```
(this is in non-steam version)

I suspect a workaround could be very simple- could just tell user to generate a new world if the default world is not found and check the box for them, correct? 

My setup is as such, though its all fresh installs and menu only so likely is not relevant:
<img width="253" alt="screen shot 2018-03-12 at 19 04 37" src="https://user-images.githubusercontent.com/5202143/37314552-2e393726-262b-11e8-8533-ceddcd74120c.png">

**Comment by metachronism** [comment]
singleplayer not supported yet on osx/linux
