### ISSUE TITLE
USER ISSUE: Savegame Error

### ISSUE THREAD

**Issue by Pedtony** [StrangeLoopGames/EcoIssues#5974]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
If i want to load my save game, it shows me every time a "connection failed" ich played in this savegame for maaany hours, i hope it is not broken :/

**Expected behavior:**

**Actual behavior:**
The following error message popped up: Loading Screen
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Can you send me any log/crash files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'?  Seems likely that your server can't start up.

**Comment by MarjieAVolk** [comment]
Closing due to no response.
