### ISSUE TITLE
After a reboot, some rooms are not recognized

### ISSUE THREAD

**Issue by TapZap1** [StrangeLoopGames/EcoIssues#5975]
If we reboot our GameServer, sometimes rooms are not detected. If this should be recognized again, you have to take out a brick and put it back in again.

Version 7.2.3

**Comment by MarjieAVolk** [comment]
I thought there was another bug for this, but looks like it has been marked as fixed.  Guess noooooot

**Comment by craig-jong** [comment]
Are there double doors in the affected rooms?

**Comment by SlayksWood** [comment]
Checked on 0.8.2.9. Wasn't able to reproduce. Seems fixed.
