### ISSUE TITLE
Backup behavior needs improvements, and non-dedicated server inconsitency.

### ISSUE THREAD

**Issue by dimensionwizard** [StrangeLoopGames/EcoIssues#5981]
For the first several days I was playing with the client/server joined as a single thingy (pardon my terminology) and I ended up losing several days worth of progress after a crash rendered my world unloadable. My impression on why is because I was playing in 2-3 hour bursts.

Backup.eco values:

{
  "$id": "1",
  "BackupFrequencyInHours": 4,
  "NumBackupsToKeep": 6
}

So because I wasn't actually hitting 4 hours of continuous run-time, there were no backups made. I ended up losing probably 8-12 hours worth of play time. Two easy fixes to this:

1. Track time since last backup in world data instead of using up-time.
2. Backup on startup and/or close.

One other thing, when running in this fashion the world will be simulated between logins as far as skill point accrual and plant growth go (possibly other ecology too?), but the meteor time will remain as it was. Not sure if this is intentional or not.

**Comment by dimensionwizard** [comment]
Also, there probably needs to be some kind of file flipping type of check when saving the world since it looks like from the backtrace on https://github.com/StrangeLoopGames/EcoIssues/issues/4665 that the game wouldn't load because of a checksum failure. Basically, rather than just writing to the existing file maybe write to a second file and flip back and forth when the checksum on the write succeeds and if the checksum fails, try to save again... something like that. Replacing a working world with a bad world in place is generally something you want to avoid.

Specifically referencing: ---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Ionic.Zip.ZipException: Could not read Storage\Game.eco as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException: Bad signature

**Comment by elfl0rd** [comment]
As i see backup now works on singleplayer

**Comment by metachronism** [comment]
John significantly changed this, should be lots of backups for singleplayer
and in an ideal world, you'd never need them :P
