### ISSUE TITLE
Soil Moisture from Aqueducts does not flow unless the area is loaded. 

### ISSUE THREAD

**Issue by FishAus** [StrangeLoopGames/EcoIssues#5984]
Placing aqueducts does cause 'Soil Moisture' to change over time and using this mechanic it is easily possible to get plants which require high soil moisture to grow in an area that would not typically have high soil moisture. 

However, the soil moisture appears to only flow from the aqueducts while the world area is loaded by a player being nearby. If the world area is not loaded because no-one is around the soil moisture returns to the moisture level it had before the aqueducts were installed. This of course causes a lot more of the plants to die as they have lost soil moisture.

This makes it difficult to use the aqueducts as intended (i.e bring moisture to soil on a farm to expand the range of crops an area can grow) it is not feasible to be always in the area to keep the soil moisture flowing.

Essentially, whether a player is in the area or not the Soil moisture should flow , especially if it is generated from an aqueduct.

**Comment by Thyriel** [comment]
Aqueducts are nonfunctional since a long time ;)

**Comment by FishAus** [comment]
Aqueducts work fine if you edit the .cs to include ‘Watertight’ as an attribute in bricks.cs file of forms in the mods folder. As I said I already tested this, and it is working, this is not a bug report about the aqueducts. This is a specific bug report about the soil Moisture layer not working as it should when the world area is not loaded.

**Comment by craig-jong** [comment]
I just tested this and the soil moisture correctly spreads regardless of connected clients.

Plants in the area can (and will) consume soil moisture as they grow - is it possible that the new moisture in the area was consumed by plants? Can you check the longer term effects in the area or give me a save file with a location so I can check it out?

**Comment by craig-jong** [comment]
Please reopen this bug if this behavior continues past 7.3
