### ISSUE TITLE
Money double spending

### ISSUE THREAD

**Issue by k0ka** [StrangeLoopGames/EcoIssues#5987]
Reproduced on GreanLeaf ECO server.

1) Sale tax is "-10%". 
2) Most of shops are using gold-backed global currency, but one uses local credits.
3) Most probably, treasury doesn't have these local credits.
4) I spend a lot of credits to buy a lot of mortared stone
5) I get mortared stone to wood cart
6) Credits are not withdrawn from me.
7) I relogged to server - still have them. I try to spend them 2nd time - it works.
8) Spending them in small portions works as intended

This happens to me two times.

**Comment by MarjieAVolk** [comment]
Sales tax is negative 10%?  So you get money from the treasury when you buy/sell things?

Do you know whether the store owner got the money also, the time it was not taken from you?  Like was there more money in the world afterwards?

**Comment by k0ka** [comment]
yes, sale tax was (and is) negative. I got some money if I buy/sell. 
Owner has unlimited credits - it wasn't backed by gold.

**Comment by johnkslg** [comment]
Clamped tax to 0 for now.  This can be setup with specific laws though.
