### ISSUE TITLE
USER ISSUE: Housing skill point corrections

### ISSUE THREAD

**Issue by Fazamere** [StrangeLoopGames/EcoIssues#5990]
Hi guys, I've reposted this as a separate issue because it was marked as closed and did not resolve as of v7.2.5. Please see #5490 for history. I will re-iterate two specific problems with housing right now:

Problem 1: Tooltip interface

I have a house with 12 rooms, 2 of each type. I hover over the house pie chart, and it shows a breakdown. Obviously there are more furniture items than the box can hold. So a scrollbar appears at the side. If I try to move my mouse to the scrollbar, the tooltip disappears. If I move my mouse over one of the furniture items, a sub-tool tip appears and it is stable. If I move my mouse over the general background and use the mouse-scroll wheel it scrolls for a second or too, but then the entire housing tooltip disappears. So that means, I cannot see the full list of rooms I have in my house, or which room is causing the imbalance.

Problem 2: Incorrect furniture selection for deciding Skillpoint allocation

Also, I have a constant issue of housing items selecting the lowest quality item (e.g. latrine), when there are higher quality items available nearby (large rug, medium rug). This causes imbalance every time I logon, and I have to rearrange furniture every time I logon. I'm not the only user who finds this issue a pain to deal with to use housing skill points. I really love the housing mechanic but the user interface issues make it difficult to use in practice. If you need me to demonstrate live, I can do so on two separate servers or my own hosted server. 

If it is intentional that the defining furniture piece (latrine) is the first item, can you please provide multiple objects (latine = 1, iron toilet = 3, steel shower = 5) which would then allow the room to be balanced compared to the kitchen, bedroom, living room etc.

Can you please:

(a) fix the tooltip delay so if your mouse is in the housing tooltip area it stays, or make housing skill point breakdown an actual pop-up box we can click and stay in to investigate.
(b) fix the housing point allocation so that the highest value item in a room always goes first and gets 100%, while latter items get 75%, etc.

If you have further questions, please email me or contact me on Pam's Big World server on Discord or something and I can talk you through it.

Fazamere

**Comment by MarjieAVolk** [comment]
#2 should be fixed in the next full release, 7.3

I will look at #1

**Comment by SlayksWood** [comment]
Checked on 8.3.0 staging-1073. Wasn't able to reproduce, seems fixed.
