### ISSUE TITLE
USER ISSUE: Open crafting tabe menu

### ISSUE THREAD

**Issue by ljej1989** [StrangeLoopGames/EcoIssues#5993]
**Version:** 0.7.3.0 beta staging-facee1c6

**Steps to Reproduce:**
walk up to table
press [E]
Nothing happens except goes into tab mode	

**Expected behavior:**
open crafting menu

**Actual behavior:**
nothing clear screen wih press e still on screen

**Comment by MarjieAVolk** [comment]
Next time this happens, can you send me your log file? 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by MarjieAVolk** [comment]
Closing due to no response
