### ISSUE TITLE
USER ISSUE: vision water bug

### ISSUE THREAD

**Issue by Foussek** [StrangeLoopGames/EcoIssues#5994]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
when i have wood or stone or etc. in hands and aim to land, where behind it is a water, it show an xray without the water 

**Expected behavior:**
it should render the water behind the ghost

**Actual behavior:**
water is not rendered in the place ghost for stone/wood etc

**Comment by fezhub** [comment]
I think this was fixed in PR2604 today?

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5703.  I am not sure whether that PR fixed it, will check.
