### ISSUE TITLE
Mint default auth should not be public

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#5997]
Mint should not default to public. When you create a currency and don't change that everyone can just print money while you obviously would want to control how much currency is around

**Comment by MarjieAVolk** [comment]
When we play, public is often the setting that we want, since it does cost resources to create money.  But I could see either way really.

**Comment by Thyriel** [comment]
We thought more that the intention behind a mint was to use it like real world currency works, so we restrict the crafting of mint to one person with a law and have the leader exlusively print money so the goverment controls how much money there is in the world ;)
