### ISSUE TITLE
USER ISSUE: Text infomation

### ISSUE THREAD

**Issue by WTFire** [StrangeLoopGames/EcoIssues#5999]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
When I change the window, the text in item is missing.

**Expected behavior:**
Show nomally the text, as usual.
![eco](https://user-images.githubusercontent.com/37344176/37357630-3a477078-26e9-11e8-83b7-0d6765173f7f.png)

**Actual behavior:**
But the text is missing.
![eco without](https://user-images.githubusercontent.com/37344176/37357629-3a1876ce-26e9-11e8-9e5a-b5a09c90cdaf.png)

**Comment by MarjieAVolk** [comment]
Are you playing on linux?  Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/5749

**Comment by WTFire** [comment]
I play on Windows 10 (64bits)

**Comment by MarjieAVolk** [comment]
Oh, well that is a different issue I suppose then.

So this happens when you change the window - I assume you mean changing the resolution?  Or maybe resizing the window?

**Comment by WTFire** [comment]
Resizing the window but when I go to settings and change resolution , text is normal

**Comment by Nanders** [comment]
This should be fixed now
