### ISSUE TITLE
after Minutes player log on Server

### ISSUE THREAD

**Issue by Xnetsrac** [StrangeLoopGames/EcoIssues#6001]
Timeout. Database is locked for more than 00:01:00.

Stack:
   bei LiteDB.LockService.Write()
   bei LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExist
s, Func`2 action)
   bei LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType au
toId)
   bei LiteDB.LiteCollection`1.Insert(T document)
   bei Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   bei Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   bei Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   bei Eco.Gameplay.Components.CraftingComponent.CreateWorkOrder(Player player,
Recipe recipe, Int32 quantity)

Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String meth
odname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object control
ler, String methodname)
   bei Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname
, BSONObject bson)

Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String meth
odname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object control
ler, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSON
Object bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()
</size>]...

**Comment by Xnetsrac** [comment]
--BEGIN DUMP--
Dump Time
03/13/2018 20:18:11

Exception
LiteDB.LiteException: Timeout. Database is locked for more than 00:01:00.
   bei LiteDB.LockService.Read()
   bei LiteDB.LiteEngine.<Find>d__9.MoveNext()
   bei LiteDB.LiteEngine.<Find>d__13.MoveNext()
   bei LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   bei Eco.Gameplay.Players.WelcomeMessage.<>c.<Get>b__2_4(<>f__AnonymousType15`2 <>h__TransparentIdentifier2)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   bei Eco.Gameplay.Systems.Tooltip.TooltipExtensions.FoldoutList(IEnumerable`1 list, String itemNounSingular, Int32 max)
   bei Eco.Gameplay.Players.WelcomeMessage.Get(Player player)
   bei Eco.Gameplay.Systems.Chat.ChatManager.Eco.Shared.Networking.INetObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   bei Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   bei Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5343

In the next version, this will stop crashing the server, but instead may cause some statistics to be incorrect.
