### ISSUE TITLE
USER ISSUE: Stove does not use the pipes for output ("disconnected")

### ISSUE THREAD

**Issue by Dultus** [StrangeLoopGames/EcoIssues#6006]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
Place Stove
Connect the (steel)pipes on the right side of the stove
Use Coal
Use Stove

**Expected behavior:**
Use the pipes for output of gas

**Actual behavior:**
Kept the gas within it and stayed disconnected

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5805
