### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by DaichiYuu** [StrangeLoopGames/EcoIssues#6007]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
Try to join a friend server

**Expected behavior:**
Join the server and play 

**Actual behavior:**
The following error message popped up:
"Connection failed"
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Here are a couple of things you can try:

* If the server is still loading, wait until it has finished before trying to join
* Try connecting directly by entering the server's IP address in the 'Join' screen
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software

Let me know if that works.

**Comment by DaichiYuu** [comment]
Thanks guys for the fourth option, you save my life !
