### ISSUE TITLE
USER ISSUE: Cannot collect logs

### ISSUE THREAD

**Issue by FrederikTheDane** [StrangeLoopGames/EcoIssues#6012]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
1. Create a server
2. Fell a tree
3. Try chopping up the tree

**Expected behavior:**
It should chop the tree up into smaller pieces that can then be collected

**Actual behavior:**
Nothing happens. On a reconnect, the felled tree becomes invisible. On a server restart, the felled tree dissapears completely

**Comment by GophTheGreat** [comment]
Reopen if it reoccurs.
