### ISSUE TITLE
USER ISSUE: All wall/roof mounted objects (Windmill/Wall Lamps, etc) "Must be Placed on Solid Ground" in order to function 

### ISSUE THREAD

**Issue by DorniNerd** [StrangeLoopGames/EcoIssues#6021]
**Version:** 0.7.3.0 beta staging-9e252de8

**Steps to Reproduce:**
1. Using "saved" world that was converted to new staging version.
2. Checking Wall mounted lamps, etc items and windmill/waterwheel type objects all state "must be placed on solid ground" in order to function.

**Expected behavior:**
Objects should function (light up, operate, provide power) without resolving the vertigo, fear of heights, that these objects are displaying. Should function on walls or posts as they are designed to do.

**Actual behavior:**
"Must be placed on solid ground" is the only way to get them to work, making them useless otherwise.

**Comment by metachronism** [comment]
craig, can you update the csv such that only specific objects need to be grounded?

**Comment by johnkslg** [comment]
I had a 'WallMounted' list in the techtree that no longer seems to exist....

**Comment by craig-jong** [comment]
The locks should prevent stuff like this from happening - I certainly haven't broken any locks, so IDK how that could happen.

**Comment by johnkslg** [comment]
Weird, do you want to add it in?  Its now on all kinds of objects not just ones with roomrequirements.

**Comment by craig-jong** [comment]
Yea, I'm doing it now

**Comment by craig-jong** [comment]
should be fixed in staging
