### ISSUE TITLE
USER ISSUE: settings fecher

### ISSUE THREAD

**Issue by Rinsher** [StrangeLoopGames/EcoIssues#6022]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
i am tringf two resetr setings

**Expected behavior:**
wen hover overing the reset botton it intracks abd wen cli8king on it it maks a nose 

**Actual behavior:**
out com the reset button for settings dos not reset the defolt settings

**Comment by Nanders** [comment]
What settings were you not seeing get reset?

**Comment by Rinsher** [comment]
this is for the game eco
