### ISSUE TITLE
USER ISSUE: UI Issue

### ISSUE THREAD

**Issue by Nachtus01** [StrangeLoopGames/EcoIssues#6023]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
Unknown....seems to occur randomly after a certain amount of play time.	

**Expected behavior:**
Quick Access Bar should always be present.

**Actual behavior:**
Quick Access Bar vanishes. Selecting a different number/ using scroll wheel does not fix. Restart solves issue. Think quick access bar is crashing.

**Comment by MarjieAVolk** [comment]
When this happens, is the rest of your interface still visible?  For example, did you turn off the interface with alt+z?

**Comment by Nachtus01** [comment]
Actually, I think you can close this thread. I didn't realize when using a cart that the toolbar would disappear. I might have been using a cart, and thought i set it down, or forgot i was using it. I have discovered that, the last few times that I have "noticed" the toolbar disappearing, that clicking e again, would bring my toolbar back. Huge oversight on my part, I think I was tired or something. Apologies for wasting your time.
Being right isn't always fair, but being fair is always right. 

    On Friday, March 16, 2018, 11:24:34 AM PDT, MarjieAVolk <notifications@github.com> wrote:  
 
 
When this happens, is the rest of your interface still visible? For example, did you turn off the interface with alt+z?

**Comment by MarjieAVolk** [comment]
Ah I see.  Thanks!
