### ISSUE TITLE
Wall Lights hover in front of thin walls (e.g. ones not full block size).

### ISSUE THREAD

**Issue by kshood** [StrangeLoopGames/EcoIssues#6025]
Wall Lights are not flush against thin walls, just full sized blocks.

![wrong_lights](https://user-images.githubusercontent.com/31428664/37382865-9acddb62-271b-11e8-9602-a50c337407b2.png)

**Comment by elfl0rd** [comment]
Dupe https://github.com/StrangeLoopGames/EcoIssues/issues/5395 but contain screenshot

**Comment by MarjieAVolk** [comment]
Thanks, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5395

I will paste the screenshot there.
