### ISSUE TITLE
Beta 7.2.4 - Missing parameter that limit the number of action per day in law system 

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#6027]
Is there a parameter in the law system that limit the number of action per day?
If yes can you provide an example?

I was attempting to create a law to limit the number of trees cut per day by a player in a specific district, but I wasn't able to add the parameter "limit one tree per day for each player" with the current law system. Here what I was able to do, but the parameter "time performed (days)" is not the number of times the action can be done per day but the day itself since the server started. So if it is day 7 on the server, time performed (days) = 7.
http://ecoforum.strangeloopgames.com/uploads/files/1521003836969-eco_law_prevent_havest_oak_more_than_1_time_per_day.jpg

**Comment by fillion07** [comment]
Now I understand Time Performed is a parameter like Performed By is a parameter and Current Time is a variable that represents a value like Number of Players is a variable that represents a value.
So I can do:
Where Time Performed(days)  > Current Time (days) - 1

In SQL it will be:
SELECT * FROM Action_Harvest WHERE TimePerformed > DATEADD(day, -1, GETDATE())

meaning, get me all the (the harvest actions) where the datetime of these actions have been performed is bigger than yesterday (give me all the harvest actions since yesterday).

**Comment by MarjieAVolk** [comment]
Yep that's how you do it, glad you figured it out :)

**Comment by MarjieAVolk** [comment]
If you have suggestions about how to make that more intuitive, let me know.
