### ISSUE TITLE
Login Authentication does not seem to be working for me.

### ISSUE THREAD

**Issue by FishAus** [StrangeLoopGames/EcoIssues#6029]
So logging in through steam I don't get any servers come up in the browser, when friends of mine do.
Attempting to log in in using the SLG credentials but not loading through steam yields the following error.

![image](https://user-images.githubusercontent.com/35624562/37385986-9bb69728-27aa-11e8-9476-3968abc2e06c.png)

Steam version just yields an empty server search...

![image](https://user-images.githubusercontent.com/35624562/37386171-5581d212-27ab-11e8-8b3a-ba15b3772410.png)

**Comment by FishAus** [comment]
Issue has been resolved.

**Comment by MarjieAVolk** [comment]
Glad to hear your problem was resolved.  Could you let me know how you fixed it, so I can help other people?

**Comment by FishAus** [comment]
Hi Marjie, 

In this case I believe it was my ISP or router being difficult. I still had connectivity and could do basic searches etc. but after being frustrated I couldn’t play eco, I found I could also not log into many other services. I left the issue for 12hours hoping the issue would resolve but it did not. A factory reset of my router fixed the issue.
