### ISSUE TITLE
USER ISSUE: won't load one of my saves

### ISSUE THREAD

**Issue by KindaLaggy9988** [StrangeLoopGames/EcoIssues#6034]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**

**Expected behavior:**
should load i guess

**Actual behavior:**
The following error message popped up:
```won't connect thus i can't play on that save lost all progress. other than that nothing.
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Can you send me any files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'?

**Comment by MarjieAVolk** [comment]
Closing due to no response
