### ISSUE TITLE
devtool and Shop+icebox problem

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#6035]
Recently, some players quit our gameserver.
We wanted to clean his old land. So we unclaimed his property claim but we are not able to clean this old shop? How to remove that???

![image](https://user-images.githubusercontent.com/29807119/37399734-e21d2ea2-2782-11e8-95d3-281ff783f6b5.png)

**Comment by Arend90** [comment]
think the dev tool should not be care about autorization, but you can do /unclaim first and then you can delete it all

**Comment by Amphysbaenas** [comment]
/unclaim was done , and i can not remove the shop

**Comment by MarjieAVolk** [comment]
Hm, I guess the auth was set to whitelist or something, so unclaiming didn't clear the auth correctly.

As Arend said, the devtool should allow you to remove objects even if you aren't authorized on them.  But I will look into clearing auth when an object becomes unowned.

**Comment by Thyriel** [comment]
The devtool currently does care about authorization so if it shouldn't do that (which would be good especially to get rid of carts) it's bugged.
Would even be great to enhance the devtool so while holding it an admin can access everything.

**Comment by MarjieAVolk** [comment]
Oh hm, I was fairly sure it worked that way during our last playtest.  Maybe someone has changed it.

**Comment by MarjieAVolk** [comment]
@SeanAtr0n was this changed client side?

**Comment by Amphysbaenas** [comment]
![image](https://user-images.githubusercontent.com/29807119/37427682-6e308712-27ca-11e8-8dab-4bc13595c2b7.png)

![image](https://user-images.githubusercontent.com/29807119/37427702-79436d04-27ca-11e8-9ae1-0d51c566d0f6.png)

**Comment by ecoemmeck** [comment]
You can trick authorized tables into letting you delete them by claiming the land they are on with a claim pots then you can unclaim that post and delete the table with the dev tool

**Comment by Skjolbir** [comment]
A good workaround, thanks ecoemmeck, not ideal though. This needs fixing, but maybe not the highest priority.

**Comment by metachronism** [comment]
fixed as of most recent hotfix 7.3 - devtool now ignores auth
