### ISSUE TITLE
[Client][Linux] Keystrokes recorded twice

### ISSUE THREAD

**Issue by Epimetheus89** [StrangeLoopGames/EcoIssues#6042]
I have the issue that when I try to type in my username and password of my strage loop account, every keystroke is printed twice. I am using Ubuntu 17.10 with Eco 7.2.4.
After searching through the internet, I found an issue in Unity that exactly behaves the same way: https://issuetracker.unity3d.com/issues/linux-keystrokes-recorded-twice

Their issue tracker says, that this issue is fixed in version 2018.1

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3580

Thanks for the info!  Will paste it there
