### ISSUE TITLE
Dynamically choose graphics options 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#6045]
Should only enable high-end features by default if they will run well.
![image](https://user-images.githubusercontent.com/3536496/37420436-02dafa70-2774-11e8-9b7b-a087eb80f85b.png)

**Comment by johnkslg** [comment]
http://steamcommunity.com/profiles/76561198149757218/recommended/382310/

**Comment by metachronism** [comment]
GI will always drop your fps, regardless of your hardware

**Comment by metachronism** [comment]
also GI starts off by default for this reason
