### ISSUE TITLE
7.2.4 Player contracts Dysentery

### ISSUE THREAD

**Issue by MittenMarauder** [StrangeLoopGames/EcoIssues#6046]
**Server, Client or Website?** Client

**OS/Web Browser?** Win10

**Detailed Description of Issue:** Player contracts Dysentery after eating an Elk Taco

**Reproducible?** How difficult is it to reproduce? Yes. Easy.

**Steps to reproduce bug/issue:** Consume Elk Taco

**Additional Comments:** This is a serious issue. Player remains unable to remove the effect and all SP gain stops due to the player being unable to maintain calories.

**Client Version?** 7.2.4

**Include recent Crash dump ( get only generated if the server crashes):** N/A

**Comment by MittenMarauder** [comment]
![dysentery](https://user-images.githubusercontent.com/37132978/37421193-0e8429a8-278f-11e8-8694-6bb72e37658a.png)

**Comment by Amphysbaenas** [comment]
it's not a bug :D

**Comment by MittenMarauder** [comment]
Disconnect from the server, then a reconnect will remove the status.

**Comment by MittenMarauder** [comment]
@Amphysbaenas Also, it is a bug that was acknowledged by the devs,

**Comment by Amphysbaenas** [comment]
http://ecoforum.strangeloopgames.com/topic/2000/help-got-a-dissease/6

https://www.strangeloopgames.com/you-have-died-of-dysentery-how-games-will-revolutionize-education/

Google is your friend :)

**Comment by MittenMarauder** [comment]
Sorry, but no. It's not a joke if you are forcing a player to exit the game to remove a status effect from a food, making that food source totally worthless.

I did Google it before posting this. I'm well aware of those results.

**Comment by Amphysbaenas** [comment]
![image](https://user-images.githubusercontent.com/29807119/37422073-e9ae9fe2-27ba-11e8-8bf5-b46e0fc8d699.png)

it's a kind of easter egg

**Comment by MittenMarauder** [comment]
Look, I understand what you're trying to say, and I'm all for having a disease as part of the game (Easter Egg or not). There's no tooltip, no warning, and to have it trigger on a late game food is even worse, but having to Google a solution is not really funny.

If it was a status message but did nothing would be better then penalizing the player while they looked for a solution.

**Comment by D3nnis3n** [comment]
"Easter Egg" removed a while back.
