### ISSUE TITLE
Contract "Put items in Container" Bug

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#6050]
"When you do a 'Put items in Container' clause. You need to open the stockpile (maybe also chests) inventory, if you just right click with the items in hand. it will not count it as added in the contract."

-From a Discord User

**Comment by MittenMarauder** [comment]
Can confirm we've experienced this behavior on our server as well.

**Comment by CreeperLord** [comment]
I found a work around is to revoke other players access to the stock pile This forces them to interact).  The Contract grants "Delivery" access to the stock pile by interaction key but does not allow removal of items.  
Let your players know that it is possible to "over-supply" a contract, (it is possible to place more than the contracted amount into the stock pile)

**Comment by johnkslg** [comment]
Fixed in staging now!
