### ISSUE TITLE
USER ISSUE: Acorn-Tree-Bug

### ISSUE THREAD

**Issue by BunkerBen** [StrangeLoopGames/EcoIssues#6052]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
1. Plant an Acorn to raise a tree!

**Expected behavior:**
....planted a Tree-Sapling!

**Actual behavior:**
...planted over 16 Saplings which are respawning everytime - even after I cut'em down they respawn. Using own server via steam

**Comment by MarjieAVolk** [comment]
Might be the same thing as https://github.com/StrangeLoopGames/EcoIssues/issues/5930
