### ISSUE TITLE
USER ISSUE: Not loading

### ISSUE THREAD

**Issue by Cheesepixi** [StrangeLoopGames/EcoIssues#6054]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
Open game and try to load or create world.

**Expected behavior:**
It should load a new or previous game file.

**Actual behavior:**
It minimises to the tray and when tabbed back into only shows the title screen background with no options.

**Comment by MarjieAVolk** [comment]
Can you send me any log/crash files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'?

**Comment by Cheesepixi** [comment]
[Crash MissingMethodException 03140159.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1823071/Crash.MissingMethodException.03140159.txt)

Opens as:
--BEGIN DUMP--
Dump Time
03/14/2018 20:01:59

Exception
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)

--END DUMP--

I've also uninstalled and reinstalled the game but it's still doing the same thing and every dmp file is the same.

**Comment by Cheesepixi** [comment]
Also got these

[crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1823119/crash.zip)

**Comment by MarjieAVolk** [comment]
That crash means that you don't have the right version(s) of .NET installed.  Steam is supposed to do that for you automatically, but sounds like our dependencies might be set up wrong.

I believe these are the two that we use, so let me know if installing these works:
https://www.microsoft.com/net/download/thank-you/net46
https://www.microsoft.com/net/download/thank-you/net35-sp1

**Comment by Nanders** [comment]
Marjie was right, this issue was wrong .NET version
