### ISSUE TITLE
[Suggestion] Need a slider in Currency Report

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#6056]
**Version:** 0.7.2.4 beta

when we have loads of players in the game trying to see who has what currency is almost impossible as the list will not scroll
![snap2017](https://user-images.githubusercontent.com/29383891/37430435-03600598-27ca-11e8-9234-0d72c2e80042.png)

**Comment by Ekkelus** [comment]
I'd really like to see a scroll bar aswell.

**Comment by MarjieAVolk** [comment]
Fixed by @misasrael in the PR above
