### ISSUE TITLE
USER ISSUE: Place Windmill/Waterwheel

### ISSUE THREAD

**Issue by JankKeks** [StrangeLoopGames/EcoIssues#6058]
**Version:** 0.7.3.0 beta staging-a5ac01f4

**Steps to Reproduce:**
Placement works, but Object keeps Status "place on solid ground" negative. Place it anywhere where it should work - it wont.

**Expected behavior:**
Placed on solid ground (house/building/rock) should make status green.

**Actual behavior:**
Status keeps red.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6021
