### ISSUE TITLE
USER ISSUE: Server Crashing

### ISSUE THREAD

**Issue by Ardesy** [StrangeLoopGames/EcoIssues#6060]
**Version:** 0.7.2.4 beta

Hiho, Getting Kicked every few minutes with Inactivity. Reason after that the Server just Crashs.

--BEGIN DUMP--
Dump Time
03/14/2018 23:32:08

Exception
LiteDB.LiteException: Timeout. Database is locked for more than 00:01:00.
   bei LiteDB.LockService.Read()
   bei LiteDB.LiteEngine.<Find>d__9.MoveNext()
   bei LiteDB.LiteEngine.<Find>d__13.MoveNext()
   bei LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source)
   bei Eco.Stats.ContinuousPlayerStatManager`1.RecordAction(T action)
   bei Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   bei Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   bei Eco.Gameplay.Players.User.Tick()
   bei Eco.Simulation.Simulation.TickAll()
   bei Eco.Gameplay.Players.UserManager.Run()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

--BEGIN DUMP--
Dump Time
03/14/2018 23:31:58

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC PerformTrade on StoreComponent!

Timeout. Database is locked for more than 00:01:00.

Stack:
   bei LiteDB.LockService.Write()
   bei LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   bei LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   bei LiteDB.LiteCollection`1.Insert(T document)
   bei Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   bei Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   bei Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   bei Eco.Gameplay.Components.StoreComponent.PerformTrade(Player purchaser, BSONObject tradeData)

Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Plugins.Networking.Clients.Client.ViewRPC(Int32 id, String methodname, BSONObject bson)

   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5343
