### ISSUE TITLE
USER ISSUE: Waypoint selection not working

### ISSUE THREAD

**Issue by AuntJemima** [StrangeLoopGames/EcoIssues#6062]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
Drop a waypoint on the map
Click the arrow below it

**Expected behavior:**
Should open waypoint context menu to edit/remove

**Actual behavior:**
Does nothing

World files:
https://www.dropbox.com/s/ni4whemdfrmzo5s/World%20Files.rar?dl=0

**Comment by johnkslg** [comment]
Works in 7.3!
