### ISSUE TITLE
USER ISSUE: Only latest waypoint shown on map

### ISSUE THREAD

**Issue by AuntJemima** [StrangeLoopGames/EcoIssues#6063]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
Drop multiple waypoints

**Expected behavior:**
Each waypoint should be shown on the map

**Actual behavior:**
Only the latest waypoint dropped is shown on map

World files:
https://www.dropbox.com/s/ni4whemdfrmzo5s/World%20Files.rar?dl=0

![2252f02a5a](https://user-images.githubusercontent.com/8947997/37435577-3d2e4dda-27ba-11e8-8191-5278c9706262.jpg)

**Comment by johnkslg** [comment]
Fixed in staging
