### ISSUE TITLE
USER ISSUE: Unable to connect to any server

### ISSUE THREAD

**Issue by skatche** [StrangeLoopGames/EcoIssues#6065]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
1. Load game.
2. Pick a server.
3. Attempt to connect.

**Expected behavior:**
Connected.

**Actual behavior:**
I've tried about five different servers, excluding the ones, and none connected. Btw this text box is also buggy: if there's too much text it starts behaving very strangely.

**Comment by MarjieAVolk** [comment]
Here are a couple of things you can try as a workaround:

* Try connecting directly by entering the server's IP address in the 'Join' screen
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software

Let me know if any of those work.

**Comment by MarjieAVolk** [comment]
Closing due to no response
