### ISSUE TITLE
USER ISSUE: Delivery Contract Over-Supply

### ISSUE THREAD

**Issue by CreeperLord** [StrangeLoopGames/EcoIssues#6072]
Situation: Accept a delivery contract to add a # of items into a stock pile or chest

Expected result; after # of items are delivered to the stock pile or chest, no more transfers allowed.

Actual result: player is allowed to input additional items above contracted limit into stock pile (and unable to retrieve) 

Repeatability:  Constant per-contract.

**Comment by johnkslg** [comment]
Fixed in staging!
