### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#6073]
Posting this from the support queue:

(sent on March 11th 2018)
"i have problem with game. two day this game work perfect but 3 Th day i cant load servers and new game. after generating new world and compress i still have load animation without text. in this part of load i have been 4 hours. thx for answer."

No other info. I requested more information.

**Comment by MarjieAVolk** [comment]
You can suggest to them deleting their eco preferences folder.  On windows it is 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO'.  They can also try steam's verify integrity of game files.
