### ISSUE TITLE
USER ISSUE: Deposit into a container for a contract and remove your marchandise before validating job

### ISSUE THREAD

**Issue by coolfarmer** [StrangeLoopGames/EcoIssues#6078]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
1. Create a contract "Put into a container". 
2. Put the marchandise into the container.
3. Remove the marchandise.
4. Valid the job -> success.

**Expected behavior:**
See above

**Actual behavior:**
See above

**Comment by CreeperLord** [comment]
Version 0.7.2.4 beta
I tried to recreate this and was met with a "you are not authorized to remove items from that" error
![20180315095121_1](https://user-images.githubusercontent.com/37389259/37470925-a1ca8476-2836-11e8-90ad-c3433cfb123a.jpg)

**Comment by MarjieAVolk** [comment]
Thanks, let's see if we can repro this.

**Comment by johnkslg** [comment]
Fixed in 7.3 staging!
