### ISSUE TITLE
Suggestion: Make tools to filter various lists when making contracts.

### ISSUE THREAD

**Issue by zEverdeen** [StrangeLoopGames/EcoIssues#6081]
Make tools to filter various lists when making contracts, e.g. when picking a property to harvest it would be nice to filter out properties or being able to select the plot from the map.

When doing a "put items in container" clause, it would be nice to filter out chests if you are looking for a stockpile, or if you have named the stockpile, search on name, ect.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#202
