### ISSUE TITLE
Electric Smelter

### ISSUE THREAD

**Issue by ProFatBoi** [StrangeLoopGames/EcoIssues#6083]
Would be good to eventually be able to create an electric smelter which didn't cause any pollution.

The tailings are starting to take up alot of space and the Blast Furnace creates alot of air pollution.

**Comment by Huntermeign** [comment]
It would but if you think about it unless you have a lot of wind mills powering it all you're really doing is burning coal from a generator to power the furnace. Actually that is a good idea. It can show people different needs for different power sources.

**Comment by ProFatBoi** [comment]
It would start bringing in the need for things like solar farms and wind farms. Would just need some sort of substation and powerlines to transfer the power to the village.

Finally got a factory up and running yesterday and built a Combustion generator to power it. The rate it was eating through the petrol and coal was ridiculous and was chucking out alot of pollution. So shut it down and built two solar panels to power it.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#201
