### ISSUE TITLE
USER ISSUE: Vibrancy bug

### ISSUE THREAD

**Issue by Gorebat666** [StrangeLoopGames/EcoIssues#6086]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
opend the options menu and clicked the vibrancy option a couple of times and it screwed up my mouse controls	

**Expected behavior:**
just changed the graphics	

**Actual behavior:**
messed up my mouse controls whenever i left click it brings me into tab mode and when i right click it dose  nothing. cant even quit the game properly

**Comment by WeaselDog** [comment]
Since this report, the graphics options have been remade and the vibrancy option has been moved into other settings. It seems to have fixed the issue with changing graphics settings affecting the mouse controls. I can't replicate in the latest version.
