### ISSUE TITLE
[Suggestion] Bees and Flowers

### ISSUE THREAD

**Issue by Huntermeign** [StrangeLoopGames/EcoIssues#6089]
Apart from the future planned animal husbandry, most farmers will really be selling most of their product to cooks. I think flowers should be added to not only add some decorations that they can sell and make seeds for players to plant, but to add more used of contracts. This could also help introduce Bee Keeping. Basically I would like to see farmers make more goods to sell to other players and not just cooks, similar to how other specializations make product that any player could use.

Gardening Skill
- Farmers can create flower seed after picking flowers. 
- Higher yield potential (Or add to gathering skill)
- Can create flower beds which can be fertilized and hold flowers picked
- Shrubs
- Can make dirt beds suitable for shrubery and flowers to grow outside
- Pollution can kill flowers
- Flower Prunes and Hedge Clippers
- Contracts can be created for people to clip hedges and prune flowers. Or player can do it themselve after buying tool (but not as effective)
- Maybe have a Hedge Sculpting Skill so Gardeners can create different shaped hedges

Bee Keeping Skill
- Bee Hives added and chance to spawn on tree branches
- Make Apiery and Frames out of lumber and cloth
- Bee suit which will be needed to collect from Apiery or Bee hives
- Honey yield based on nearby flowers
- Low yield can kill bees
- Beeswax Yield
- Beeswax Candles/Lamps similar to tallow lamps but use beeswax.

Uses for other specializations
- Can create hedge clippings or plant fibers which can be used for compost or pitch
- Shrubs could be added to Square or Round Pots
- Lumber needed for before mentioned Apiery and Garden Bed
- Cloth used for frames which will need to be remade over time. (more use for tailoring)
- Possibly for Paint as I suggested in #5216
- Beeswax could be used for more advanced toilets later on.
- Beeswax could be added to late game tailoring (Beeswax is used for waterproofing)
- Beeswax could be used as a polish for late game carepentry furniture. 
- Beeswax used in cooking when animal husbandry comes out. (i.e Waxing Cheese)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#200
