### ISSUE TITLE
[USER ISSUE] Corrupted Object | Server can't restart

### ISSUE THREAD

**Issue by SeppDE** [StrangeLoopGames/EcoIssues#6093]
**Version:** 0.7.2.4 beta

The World of an friend is crashing after an server restart.
Seems that the world got corrupted. 
Any chance to fix the corrupted object?

If you need more informations - feel free to ask.

**Crash Log:** https://gist.github.com/SeppDE/90c5df5d48285e72923ffb7234ea6e73
**World:** https://1drv.ms/f/s!AhPeBlzYH2vLonbetaw2lIOB6DBm

**Comment by MarjieAVolk** [comment]
I was able to delete the corrupted objects from your save.  It will also be missing any broken stone rubble or ores, etc, that was lying loose in the world (the things in your storage are safe).
[Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1817331/Game.zip)

But I am not sure how this happened.

Was this save migrated from a staging version, or a very old version of Eco?  Or was it doctored in some way?

I ran the save file here, and got this exception, which I was able to continue through, getting many other similar exceptions for different types, including LumberSkillScroll, WashingMachineItem, LumberConstructionSkill, LumberStairs180Block, LumberStacked3Block, LumberSkillBook, WaterweedSeedItem....

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'Eco.Mods.TechTree.CorrugatedSteelStacked4Block' to type 'Eco.Gameplay.Objects.IEcoObject'.
  Source=Eco.Core
  StackTrace:
   at Eco.Core.Serialization.DataStore.<>c__DisplayClass39_5`1.<LoadAsync>b__1() in C:\Projects\Eco\Server\Eco.Core\Serialization\DataStore.cs:line 345
   at System.Threading.Tasks.Task.Execute()
```

**Comment by SeppDE** [comment]
Great. Thanks for fixing this one!

As for the information you asked for.
- The world was generated 2-3 weeks ago. 
- And there never was an stagging-update on them. Only the recent beta-version.
- Small changes (Rubble only drops to 4) - Changed File: https://1drv.ms/u/s!AhPeBlzYH2vLol0mJzijIwTtk2aG
- I got told that before the world got corrupted there was an crafting task for 500 steel. It got transported to an stockpile and than to an big storage house with an cart. After this one the server got stopped to add an admin. Than the server wasn't going up again and the log you got was created.

**Comment by MarjieAVolk** [comment]
Hmmm if you had changed some code related to rubble, it is possible that is related.  Thanks for the details!

**Comment by SeppDE** [comment]
No problem! If there's an problem with the code related to rubble it would be nice to comment here again. The changes worked fine for me and a few other people.
