### ISSUE TITLE
USER ISSUE: Plant fibre gathering rate

### ISSUE THREAD

**Issue by TheOne320** [StrangeLoopGames/EcoIssues#6094]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
Get Grassland Gatherer

**Expected behavior:**
Increases gathering rate of plant fibre, before it gathers 2-3 fibres per swing, after it should be 3-4

**Actual behavior:**
Reduces fiber gathered per swing to 1

*edit*
Even after refunding "Grassland Gatherer" the gather rate of plant fibre is still at 1 per Scythe swing.

**Comment by craig-jong** [comment]
7.3 will have this fixed (or at least changed)
