### ISSUE TITLE
USER ISSUE: I am unable to turn around

### ISSUE THREAD

**Issue by MoltenShadow** [StrangeLoopGames/EcoIssues#6097]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
I cant use my mouse to turn around. I can use my mouse only in backpack or tab mode.

**Expected behavior:**
I should be able to turn around and use my mouse.

**Actual behavior:**
I am unable to use my mouse to turn around.

**Comment by MarjieAVolk** [comment]
Was your mouse sensitivity set to 0?  Try opening the escape menu, click on Advanced, then Controls.  Mouse sensitivity is at the top.

Can you also send me your log file? 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by MoltenShadow** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1817334/output_log.txt)

**Comment by MarjieAVolk** [comment]
Okay, well there's definitely something in there!

Looks like the game is not able to read your input config file.  I bet if you go and remove the file 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\inputManager.cfg', it will work.  Could you actually send me that file?  And let me know if removing it fixes your problem.

```
NullReferenceException: Object reference not set to an instance of an object
  at InputManager.DeserializeConfig () [0x00000] in <filename unknown>:0 
  at InputManager.Awake () [0x00000] in <filename unknown>:0 
```

**Comment by MoltenShadow** [comment]
I am not able to send you that file because it's not supported. Anyway thank you very much. Everything works now.

**Comment by MarjieAVolk** [comment]
Okay good to hear.  If you send the file to a .zip you should be able to upload it.  I would appreciate it, but if you want to just get playing I understand :P
