### ISSUE TITLE
USER ISSUE: Delete Maps

### ISSUE THREAD

**Issue by Gamerline14** [StrangeLoopGames/EcoIssues#6099]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
I cant delete my own Maps. I´ve got 3 Maps and i cant delete her

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Yes, there is no way to do it in game right now :(  What you will have to do is go to Browse Local Files for Eco, and go to Eco_Data\Server\Storage.  There you can delete any files with the same name as the world you want to delete.

**Comment by Gamerline14** [comment]
Thanks for the fast answer ;) Yeah i got

**Comment by D3nnis3n** [comment]
Merged with #10301
