### ISSUE TITLE
Special Characters breaking login

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [StrangeLoopGames/EcoIssues#6110]
Version: 0.7.2.4 beta

Browser Chrome

Dedicated server

Action taken
Opened Game clicked on law was redirected to webpage

Loaded Law page returns me with Three.js WebGl Errors

Failed to load resource: the server responded with a status of 404 (Not Found)

three.min.js:173 THREE.WebGLRenderer 88

**Comment by Edgar-BlipparDev** [comment]
Another error with more stack seems to be related

jquery-latest.min.js:4 GET http://95.154.229.150:3281/isadmin/Legend%20??? 404 (Not Found)
send @ jquery-latest.min.js:4
ajax @ jquery-latest.min.js:4
(anonymous) @ lawspage.js:372
j @ jquery-latest.min.js:2
fireWith @ jquery-latest.min.js:2
x @ jquery-latest.min.js:4
b @ jquery-latest.min.js:4
XMLHttpRequest.send (async)
send @ jquery-latest.min.js:4
ajax @ jquery-latest.min.js:4
m.(anonymous function) @ jquery-latest.min.js:4
lawspage @ lawspage.js:59
Law.loadLawPage @ Law.js:110
bindEvents @ Law.js:661
(anonymous) @ Law.js:732
j @ jquery-latest.min.js:2
fireWith @ jquery-latest.min.js:2
ready @ jquery-latest.min.js:2
J @ jquery-latest.min.js:2

**Comment by Edgar-BlipparDev** [comment]
I suspect it doesnt possibly like special characters in name Legend ☜☆☞

**Comment by MarjieAVolk** [comment]
Ohhhh yeah seems so, thanks for that.

**Comment by MarjieAVolk** [comment]
@rainfarmer This still looks like a web side bug, right?

**Comment by Edgar-BlipparDev** [comment]
No worries glad to help if you guys want me to record html stacks can do.. I will be testing for vulnerabilities once I get chance

**Comment by rainfarmer** [comment]
adding in more special character support
