### ISSUE TITLE
Law Website Error: Type error line 719

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [StrangeLoopGames/EcoIssues#6111]
Version: 0.7.2.4 beta

Browser Chrome

Dedicated server

Action taken
Opened Game clicked on law was redirected to webpage

Uncaught TypeError: causeeffect.updateMapsInfo is not a function
at
OrbitControls.js:719

**Comment by rainfarmer** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/6112
