### ISSUE TITLE
Law website error: Type error line 751

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [StrangeLoopGames/EcoIssues#6112]
Version: 0.7.2.4 beta

Browser Chrome

Dedicated server

Action taken
Selected law District proposal law thats in progress  to vote

Uncaught TypeError: causeeffect.updateMapsInfo is not a function
    at OrbitControls.js:751
(anonymous) @ OrbitControls.js:751
setTimeout (async)
onMouseWheel @ OrbitControls.js:751

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/6111

**Comment by rainfarmer** [comment]
related to https://github.com/StrangeLoopGames/EcoIssues/issues/6185

**Comment by rainfarmer** [comment]
Is this error breaking some features in the game?
