### ISSUE TITLE
[CLIENT] Game crashes ~15 seconds after launch

### ISSUE THREAD

**Issue by Jaanimo** [StrangeLoopGames/EcoIssues#6116]
ECO Version "0.7.2.4"
expect the game to keep running
but the game crashes around 15 seconds after launch.
 all i can do is race to open a solo.
 there are no files in crashes folder.
the game just crashes with win10's "eco.exe has stopped working"

i got :
Microsoft Windows 10 (build 15063), 64-bit
Processor Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
RAM 32 GB
[Chipset NVIDIA GeForce GTX 880M
Dedicated Memory 6.0 GB
Total Memory 6144 MB]

**Comment by MarjieAVolk** [comment]
Have you tried steam's 'verify integrity of game files' button?  You could also try deleting the folder 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO'

**Comment by Jaanimo** [comment]
yup. did the verify 4 times and reinstalled 3 times
and yup tried deleting it but still the same problem

**Comment by MarjieAVolk** [comment]
So if you 'race to open' your save, and you succeed in loading the save, the game won't crash after that?

**Comment by Jaanimo** [comment]
yea i can play as long as i want. but if i try an online server. i still be in the loading screen when it crashes

**Comment by Jaanimo** [comment]
and i allowed all the "ECOs" thru firewall and listed it as an "exculsion" on win10 defender

**Comment by Jaanimo** [comment]
it can load as long as it wants if its a solo... no crashing. but if idle or try to join an online session it crashes. even when loading into the online session.

**Comment by SeanAtr0n** [comment]
are you still having this issue with the latest release?

**Comment by Jaanimo** [comment]
all seems to be working nicely now
