### ISSUE TITLE
USER ISSUE: Removing stacked chest

### ISSUE THREAD

**Issue by Renovamaa** [StrangeLoopGames/EcoIssues#6136]
**Version:** 0.7.3.0 beta staging-3decfca7

**Steps to Reproduce:**
place a chest above another chest by using a wall behind where both chest are placed. After this, remove the top chest.

**Expected behavior:**
The chest is sent back to your inventory

**Actual behavior:**
Caught exception invoking RPC PlayerInteract on Player!
Object reference not set to an instance of an object.
Ob

**Comment by MarjieAVolk** [comment]
Looks like you didn't get the full error message.  If you see it again, could you show the whole thing?  I'm guessing this doesn't happen regularly though.
