### ISSUE TITLE
Glass construction totally pointless

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#6138]
the 2 kind of blocks, roof and pillar are the same block :/
Wall & Windows is the same block, only stairway has it's own texture.

Especially the roof would be nice if it would acually be a roof so it can be used as a sloped window in normal sloped roofs (lumber, etc.) and as a sloped glass roof to construct a glasshouse

**Comment by keegan-o** [comment]
Glass roof, column, and door added in staging and master, will be in the next patch!
