### ISSUE TITLE
Fix artifact on highlights sprite

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#614]
It's in UI_Icons 
![image](https://cloud.githubusercontent.com/assets/3536496/19542493/595bbe4a-9623-11e6-8ead-95dc7f22980a.png)

**Comment by johnkslg** [comment]
Notice the little line there on the edges

**Comment by metachronism** [comment]
just make another sprite that doesn't go out to the edge (or edit the one thats used right now)
