### ISSUE TITLE
USER ISSUE: Missing Requirement

### ISSUE THREAD

**Issue by Deandorean** [StrangeLoopGames/EcoIssues#6142]
**Version:** 0.7.3.0 beta staging-3decfca7

**Steps to Reproduce:**
http://steamcommunity.com/sharedfiles/filedetails/?id=1332430218

there should be a "reached x out of y" display, but there's no number of the missing parts

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Looks like a translation problem, I remember seeing that before.

**Comment by Nanders** [comment]
Bumping to medium as this is ongoing non-game-breaking work

**Comment by Quadbro** [comment]
Seems to be fixed (tested on 2 localized languages)
