### ISSUE TITLE
USER ISSUE: Burring tailings

### ISSUE THREAD

**Issue by Drae77** [StrangeLoopGames/EcoIssues#6143]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
I burried the tailings in a mine, very far under the ground, i put them into wood cart that i threw down in a vertical hole very far from the ground. I sealed them with one ground of mortared stone and one ground of dirt i did this two times, i built 2	stockpile full of stoneson the many grounds.

**Expected behavior:**
I shouldn't have any ground pollution

**Actual behavior:**
Instead of it the whole zone under the hole is infested of pollution. And it's impossible to manage with the tailings.

**Comment by Thyriel** [comment]
I'm not sure if 1 block stone is enough. We bury them >15 blocks deep and seal the room with 3 layers mortared. Also it can take quite a lot time for the pollution to go away once ground is polluted (2 days+)

**Comment by MarjieAVolk** [comment]
I'm guessing having the pollution in a cart doesn't respect buried-ness

**Comment by Thyriel** [comment]
> I'm guessing having the pollution in a cart doesn't respect buried-ness

If that's the reason admins really need a way to access / delete carts ;)
