### ISSUE TITLE
Suggestion: Give Vehicles, etc. Durability/break down mechanic.

### ISSUE THREAD

**Issue by zEverdeen** [StrangeLoopGames/EcoIssues#6146]
Give vehicles, etc. a break down mechanic that will require a repair specialist to make repairs. Maybe he needs a ditch or a lift to service the vehicles. Maybe an oil change, new tires. More of this can come later, but the initial idea requires a basic break down mechanic.

Also, add a vehicle, that could pick up other vehicels and transport them for repair.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#199
