### ISSUE TITLE
USER ISSUE: Cannot pick up cart

### ISSUE THREAD

**Issue by biggbaz** [StrangeLoopGames/EcoIssues#6150]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Go in third person
2. Put wood in small cart
3. Look in inventory
4. Move cart

**Expected behavior:**
Changed interface to pick up cart.

**Actual behavior:**
Does not allow me to pick up cart.

**Comment by zEverdeen** [comment]
Had a guy with the same issue. He relogged, and he was in a new location, but now he was able to pick the part up.

If you have the same issue, try that first.

**Comment by biggbaz** [comment]
Yeah br0, relogging works a treat but it's only a temporary fix!

On 29 Mar 2018 11:22 pm, zEverdeen <notifications@github.com> wrote:

Had a guy with the same issue. He relogged, and he was in a new location, but now he was able to pick the part up.

If you have the same issue, try that first.

**Comment by SeanAtr0n** [comment]
Fixed a while back
