### ISSUE TITLE
USER ISSUE: Server Jump!

### ISSUE THREAD

**Issue by biggbaz** [StrangeLoopGames/EcoIssues#6151]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Wait a while
2. Walk into location (plot)
3. If location (plot) does not come up
3. Relog
4. In complete other position

**Expected behavior:**
Normal spawn pattern.

**Actual behavior:**
Jumps to a previous position!

**Comment by MarjieAVolk** [comment]
Was this on a local save?  Or someone else's server?

**Comment by biggbaz** [comment]
Hey br0, a rented server unfortunately!

On 20 Mar 2018 11:35 pm, MarjieAVolk <notifications@github.com> wrote:

Was this on a local save? Or someone else's server?

**Comment by MarjieAVolk** [comment]
Okay, I just wanted to check if a relog was also a server restart :)

**Comment by biggbaz** [comment]
Dear my beautiful man,
Nope, it happens quite commonly when I interact with the cart, it reverts your character back to a previous place on religion but keeps all the stuff you've done in the time between but abit of a pain! It seems that if interaction with the cart fails and doesn't allow you, once you relog it jumps and solves the issue for the next 15 mins! P.s my love; I've posted some good ideas in the discord ;)))))
Bazzers

On 21 Mar 2018 6:35 pm, MarjieAVolk <notifications@github.com> wrote:

Okay, I just wanted to check if a relog was also a server restart :)

**Comment by SeanAtr0n** [comment]
Fixed a while back
