### ISSUE TITLE
Admin Feature to remove blocks

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [StrangeLoopGames/EcoIssues#6153]
This is feature request

Currently its next to impossible to remove items from world as admin. There should be way to do it. One suggestion would be to have simple delete block that would just remove stuff when hovering over and object.. Or have command that would make my tool a destruction tool with which i can destroy any object.. 

It is very hard to manage servers especially say people leave without notice or your mayor quits and leaves mint access to everyone only solution is to actually build around object to prevent access

**Comment by Edgar-BlipparDev** [comment]
Found command that is not listed and documented anywhere /give devtool that does exactly what i need

**Comment by MarjieAVolk** [comment]
/help should list all of the commands that you have access too.  It's official now, should be more up to date than external chat command documentation.
