### ISSUE TITLE
CLIENT ISSUE: Linux Steam client stuck in loading and floods memory

### ISSUE THREAD

**Issue by fabianskii** [StrangeLoopGames/EcoIssues#6158]
**Steps to reproduce:**
1. Start Eco Steam client on Ubuntu 16.10
2. wait

**Expected behaviour:**
Main Menu should be displayed

**Actual behaviour**
Ram fills up without ending.
I'm starting with a RAM load of 5GB.
I kill the process when it starts swapping at 15gb

**Hardware:**
i7 7500U
16GB Ram
500gb m.2 SSD
Intel HD Graphics

**Comment by Sebi-M** [comment]
I had the same symptoms, although on the standalone version.

After debugging via strace I found out, that the executable tried to access a nonexisting folder:
I unzipped into my "${home}/Downloads" folder, but strace told me, it was accessing files in "${home}/downloads" (mind the capitalization). Indeed, I do have a folder named "${home}/downloads", but in there is other stuff, and not the unzipped eco files.

I suppose, there is some kind of "to_lower" with the path to the executable (perhaps with an "if_exists" or so), which makes sense on Windows (or Mac), but wreaks havoc on Linux. Perhaps this is also in the Unity Framework.

Try to run the standalone version, if you can, and try to keep in mind the folder naming / unzip directly to your home or all lowercase folders.

**Comment by SeanAtr0n** [comment]
Fixed a while back
