### ISSUE TITLE
USER ISSUE: Dupe method 

### ISSUE THREAD

**Issue by kazenokizu** [StrangeLoopGames/EcoIssues#6160]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Q something up for say 2 off 1 log wait for it to finish one out of 2 and cancel or 3 out of 4 and you will still get the processed product and the whole resource back

**Expected behavior:**
not give back full resources 

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Okay, I'm not able to get this to happen on current staging - since you were playing on staging and it was pretty broken earlier, it's likely already fixed.  Going to close for now, let me know if you still see it.
