### ISSUE TITLE
Framed Glass size and texture bugs

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#6165]
From the support queue: 

Game version - 0.7.2.4 
  
I found two bugs with the subject "framed glass". 
The first is the wrong block (object) size in the "window" mode. If you build an input from such blocks as shown in the screenshot, you can not enter it because the player's character rests (hits) the head in the upper block, and you can not sit down in the game. See picture 1 ( bug ) , picture normal enter ( “cube” mode ) . 
The second bug is a texture bug (used to be the same with ore). When you build something through a block that you have not yet shipped, the texture of the wrong object is located behind the block being installed, and the next one is, as it were, through the block. If you do this against the 
background of water, then this bug is especially visible not the surface of the water as it should be, but the sea (river) bottom (the surface under the water), and this should not be visible.
![20180315113856_1](https://user-images.githubusercontent.com/13459026/37547192-3a95b9d6-2914-11e8-928a-c38726e391e0.jpg)
![20180315113621_1](https://user-images.githubusercontent.com/13459026/37547195-3d90a6be-2914-11e8-8e41-a21f4f8af2e5.jpg)
![20180315125642_1](https://user-images.githubusercontent.com/13459026/37547198-400b10b4-2914-11e8-9d94-85add84c5bba.jpg)

**Comment by Rambo99** [comment]
Thank you for posting my bug report. My computer - Intel i7-4960, 16 Gb, NV 980 GTX, Win 7 x64 bit.

**Comment by GophTheGreat** [comment]
Another addendum that may or may not be related: 

Again, the texture bug described by me earlier in the bug reports about the "texture bug with coal" and "texture bug with framed glass" is again displayed (this is when a texture not shown should be visible for a not yet installed object. Now this also appears on the subject "log".

**Comment by keegan-o** [comment]
This is all fixed in latest staging and will be in the next patch.
