### ISSUE TITLE
USER ISSUE: Currency Report Correction

### ISSUE THREAD

**Issue by Fazamere** [StrangeLoopGames/EcoIssues#6166]
PROBLEM: For the longest time, everyone on our server was trying to figure out why our currency was going up and down unpredictably since we weren't printing anymore. Finally, discovered it is hiding the contract escrow money until the contract is either completed or cancelled.

SUGGESTED SOLUTION: Make the currency report have a separate line called "Contracts Escrow" which sums up the total money that is being aside for contracts. Ideally this would also have sub-lines which list who owns those contract escrow accounts. This way the total currency will be including all contracted amounts and its visible who is contracting the most.

**Comment by WeaselDog** [comment]
Has been added:
![ContractEscrow](https://user-images.githubusercontent.com/47330823/70856705-56e50a00-1e96-11ea-9fd5-8052a72138f6.png)

It does not include sub-lines for the source of the contract escrow but that can get complicated as it would have to list each contract. The money in escrow is not owned by anyone and could end up with either the contractor or the client.
