### ISSUE TITLE
DUMP

### ISSUE THREAD

**Issue by SkyDyz** [StrangeLoopGames/EcoIssues#6167]
--BEGIN DUMP--
Dump Time
03/17/2018 00:03:19

Exception
System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.ArgumentOutOfRangeException: La longueur ne peut pas être inférieure à zéro.
Nom du paramètre : length
   à System.String.Substring(Int32 startIndex, Int32 length)
   à Eco.Core.Serialization.SimpleSerializer.GetOrCreateSerializerFromSchemaType(SimpleSerializer newSerializer, SerializerSchema schema)
   à Eco.Core.Serialization.SimpleSerializer..ctor(SimpleSerializer newSerializer, String schema, Dictionary`2 migrations)
   à Eco.Core.Serialization.EcoSerializer.Initialize()
   à Eco.Core.Plugins.StorageManager..ctor()
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   à System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance(Type type, Boolean nonPublic)
   à System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   à System.Activator.CreateInstance(Type type, Object[] args)
   à Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   à Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   à System.Threading.Tasks.Task.Execute()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à Eco.Server.PluginManager..ctor()
   à Eco.Server.Startup.Start(String[] args)
   à Eco.Server.MainClass.Main(String[] args)
---> (Exception interne #0) System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.ArgumentOutOfRangeException: La longueur ne peut pas être inférieure à zéro.
Nom du paramètre : length
   à System.String.Substring(Int32 startIndex, Int32 length)
   à Eco.Core.Serialization.SimpleSerializer.GetOrCreateSerializerFromSchemaType(SimpleSerializer newSerializer, SerializerSchema schema)
   à Eco.Core.Serialization.SimpleSerializer..ctor(SimpleSerializer newSerializer, String schema, Dictionary`2 migrations)
   à Eco.Core.Serialization.EcoSerializer.Initialize()
   à Eco.Core.Plugins.StorageManager..ctor()
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   à System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance(Type type, Boolean nonPublic)
   à System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   à System.Activator.CreateInstance(Type type, Object[] args)
   à Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   à Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   à System.Threading.Tasks.Task.Execute()<---

Inner Exception
System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.ArgumentOutOfRangeException: La longueur ne peut pas être inférieure à zéro.
Nom du paramètre : length
   à System.String.Substring(Int32 startIndex, Int32 length)
   à Eco.Core.Serialization.SimpleSerializer.GetOrCreateSerializerFromSchemaType(SimpleSerializer newSerializer, SerializerSchema schema)
   à Eco.Core.Serialization.SimpleSerializer..ctor(SimpleSerializer newSerializer, String schema, Dictionary`2 migrations)
   à Eco.Core.Serialization.EcoSerializer.Initialize()
   à Eco.Core.Plugins.StorageManager..ctor()
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   à System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance(Type type, Boolean nonPublic)
   à System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   à System.Activator.CreateInstance(Type type, Object[] args)
   à Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   à Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   à System.Threading.Tasks.Task.Execute()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à Eco.Server.PluginManager..ctor()
   à Eco.Server.Startup.Start(String[] args)
   à Eco.Server.MainClass.Main(String[] args)
---> (Exception interne #0) System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.ArgumentOutOfRangeException: La longueur ne peut pas être inférieure à zéro.
Nom du paramètre : length
   à System.String.Substring(Int32 startIndex, Int32 length)
   à Eco.Core.Serialization.SimpleSerializer.GetOrCreateSerializerFromSchemaType(SimpleSerializer newSerializer, SerializerSchema schema)
   à Eco.Core.Serialization.SimpleSerializer..ctor(SimpleSerializer newSerializer, String schema, Dictionary`2 migrations)
   à Eco.Core.Serialization.EcoSerializer.Initialize()
   à Eco.Core.Plugins.StorageManager..ctor()
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   à System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance(Type type, Boolean nonPublic)
   à System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   à System.Activator.CreateInstance(Type type, Object[] args)
   à Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   à Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   à System.Threading.Tasks.Task.Execute()<---

--END DUMP--

**Comment by Venalyo** [comment]
Yes @MarjieAVolk we are on staging 7.3.0.
The server crash when starting it since yesterday's update (3decfca7).
And today's update (c32792cb) is not helping.

**Comment by MarjieAVolk** [comment]
Yeah so the problem was fixed I believe, but saves that already saw the problem will still be corrupted.  If you are able, maybe restore a backup from before this started happening?
