### ISSUE TITLE
USER ISSUE: beta 7.2.5 Eco is maxing out GPU at 100%

### ISSUE THREAD

**Issue by Skjolbir** [StrangeLoopGames/EcoIssues#6168]
Client Side issue
Eco is pushing GPU to max 100% use regardless of graphics settings.
beta 7.2.5
Windows 10 Home 64-bit
i7 6700k @4.00GHz
16GB Ram
2047MB NVIDIA GTX 980ti
Dell S2417DG 165Hz G-Sync Monitor

I suspect the game is trying to push an uncapped/unlimited FPS so is maxing my card. Or, trying to push to 165Hz is maxing my card. Either way, an FPS limit option in-game would be appreciated. 30/60/120 ect

**Comment by Skjolbir** [comment]
I applied an FPS limiter twice, once at 30fps and once at 60. Both times it carried on hitting 100% gpu utilisation.

**Comment by SeppDE** [comment]
Same is happening on my system.

Windows 10 Home 64-bit
i7 6850k @4GHz
32 GB Ram
2x GTX 1080 (FTW! Evga)
FHD + WQHD 144Hz G-Sync (Game is open on the WQHD Screen)

GPU1 will be on 100% all the time. (SLI is not needed for an game like this)

**Comment by Thyriel** [comment]
An FPS limit can't help if it only runs at 46 fps as seen in the screenshots as you're still under that limit.
Imho the game just needs some optimizations somewhen. For example (with vsync) my fps caps easily at 60 in early game at max settings but once there is a lot of playerbuilt stuff to be rendered it's most of the time down to 20-30 even with minimum graphic settings. Especially stockpiles with stuff to render seem to reduce fps a lot.

**Comment by UnknownViper** [comment]
Skjolbir: The GPU details you've given aren't correct. You say it's a 2 GB 980 Ti. That doesn't exist. Either you stated the amount of VRAM incorrectly (it should be 6 GB) or you stated the GPU incorrectly.

**Comment by Skjolbir** [comment]
My bad, I used a program called Speccy to pull my specs up and its reported incorrectly. Upon further inspection, yeah my gpu has 6GB

**Comment by UnknownViper** [comment]
Just wanted to make sure that it was the right GPU and not something less powerful. :)

**Comment by Skjolbir** [comment]
Put the limiter as low as possible, 23 FPS and was hitting 80-85% usage. I don't think its a memory leak or anything of that kind then, just really badly optimised for the time being.
Not sure what else I can add to the bug report.

![1](https://user-images.githubusercontent.com/37461131/37561083-4acff8f0-2a3d-11e8-9d72-57f0cfb76428.png)

**Comment by SeanAtr0n** [comment]
more options to limit this in 7.3
