### ISSUE TITLE
USER ISSUE: Use of Mortared Stone Base and Wall with Stone road causes fall through world issues UPDATE Repo save added

### ISSUE THREAD

**Issue by Ironhelix98** [StrangeLoopGames/EcoIssues#6170]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Create Stone Road 4wx5l (size may not matter, but is size of tested road)
2. Place Mortar Stone base along edge of and on same level with with the stone road.
3. Place Mortar Stone wall along Mortar Stone base
4. (Optional) Clear at least two levels of material out from underneath the created structure.
5. Walk along seam between mortar stone base and stone road.

**Expected behavior:**
Should be able to walk with out falling through

**Actual behavior:**
Will fall through seam of Mortared stone base and Stone road. If structure is contact with world you will fall all the way through. If you followed step 4 you should either be stuck or underneath structure.

Pictures of Results
![20180316204142_1](https://user-images.githubusercontent.com/37199270/37550050-8f570c38-295d-11e8-99d0-0902a06043e4.jpg)
![20180316204115_1](https://user-images.githubusercontent.com/37199270/37550051-926d4770-295d-11e8-8b44-22797f53ba4d.jpg)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/37940683-d2437f2c-311e-11e8-8ef9-b40829e04b18.png)

Haven't been able to repro this yet... putting on Medium Priority until I can.

**Comment by johnkslg** [comment]
Got another report of this from a negative steam review, bumping priority up.

**Comment by johnkslg** [comment]
Got a repro save: https://drive.google.com/open?id=1ARcL0N1o4RyFVV_yPX2aHtm7_0OK0DJl

Location is 509,64,41 
There's a missing triangle on the dirt there:
![image](https://user-images.githubusercontent.com/3536496/38337461-261eb02e-381a-11e8-9cf1-a3a59649d270.png)

Probably deleted by the vertex remover.

**Comment by keegan-o** [comment]
Have not been able to able to repro (teleported to that spot on the server and looked all around but could not find that exact location), but also have not been able to repro other tests since changing all the mortared stone floor colliders to be simpler (cubes for everything pretty much), so hopefully that fixed the problem and is more friendly to the collider simplifier code.

**Comment by keegan-o** [comment]
Should hopefully be fixed in master and thus 7.4.

**Comment by ShaydenMac** [comment]
Followed up with Steam user 4/23/18
