### ISSUE TITLE
USER ISSUE: Cannot join a game

### ISSUE THREAD

**Issue by banderson6979** [StrangeLoopGames/EcoIssues#6171]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
have someone with a game already running that is setup to allow friends to join. have said friend send a game invite via steam.

**Expected behavior:**
Expected to be able to join.

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Here are a couple of things you can try:

* If the server is still loading, wait until it has finished before trying to join
* Try connecting directly by entering the server's IP address in the 'Join' screen
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software

Let me know if that helps.
