### ISSUE TITLE
Database Lock Up is stopping .Net 

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6172]
[![Screenshot from Gyazo](https://gyazo.com/a05db275cb59f36d1515e44274b3a6d2/raw)](https://gyazo.com/a05db275cb59f36d1515e44274b3a6d2)

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5343
