### ISSUE TITLE
USER ISSUE: excavator missing

### ISSUE THREAD

**Issue by mwarnec2** [StrangeLoopGames/EcoIssues#6173]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
digging dirt with excavator

**Expected behavior:**
kept digging	

**Actual behavior:**
threw me accross the map couldnt move until i got back to where my excavator was and then its gone completelyw

**Comment by SlayksWood** [comment]
Checked on 8.1. Wasn't able to reproduce, seems fixed.
