### ISSUE TITLE
USER ISSUE: Washing Machine makes crafting noise ALWAYS

### ISSUE THREAD

**Issue by AyeeAyeeRon** [StrangeLoopGames/EcoIssues#6175]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Placed Washing machine
(make sure it's powered?)

**Expected behavior:**
Have an on/off switch? Actually do something?

**Actual behavior:**
Is always on, making noise.

**Comment by GophTheGreat** [comment]
A possibly related excerpt from a support ticket: 

After manufacturing and installation in the player's house of the object "washing machine", there is an unceasing sound from the working “anvil”, with no one using the washing machine.

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5846 - This will be fixed in 7.3
