### ISSUE TITLE
Can't empty stove tank

### ISSUE THREAD

**Issue by Twelve57** [StrangeLoopGames/EcoIssues#6176]
Version: 0.7.2.5 beta

Steps to Reproduce:
2 Issues here 
1) When I try to connect pipes to the stove (not cast iron stove) it's only connect with the one at the right. I've tried everywhere and multiples times.
2) I can't empty the stove tank. Even if it's connected (see 1)

Expected behavior:
Don't know for 1) but for 2) I should be able to empty the stove with and without pipes

Actual behavior:
1) see steps to reproduce
2) The only way it's to take it and replace it.

**Comment by hcosoft** [comment]
Same issue here

**Comment by MarjieAVolk** [comment]
Fixed in 7.3 (https://github.com/StrangeLoopGames/EcoIssues/issues/5805)
