### ISSUE TITLE
USER ISSUE: excavator keeps disappearing

### ISSUE THREAD

**Issue by mwarnec2** [StrangeLoopGames/EcoIssues#6181]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
get out of excavator and just turn around and its gone

**Expected behavior:**
excavator should just sit there waiting to be used

**Actual behavior:**
after getting out it disappears and cant use it have to shut game down to get back

**Comment by SlayksWood** [comment]
Checked on 8.1. Wasn't able to reproduce, seems fixed.
