### ISSUE TITLE
USER ISSUE: Unable to get my server in the public list even if my friends can join it

### ISSUE THREAD

**Issue by coolfarmer** [StrangeLoopGames/EcoIssues#6183]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
I have successfully configured a server on a dedicated PC and all my friends can join it if they use "Add server" in JOIN menu.

Server host: coolfarmer-pc.no-ip.info:8001
Server name: ECO Friendly (QC/FR)
Web: http://coolfarmer-pc.no-ip.info:8001

My ports 2999, 8000-8001 are all open and my firewall is correctly configured. I have talked ~30 min with Pam (moderator) on your Discord channel and he have recommended to me to create a bug report.

It's pretty weird. It's the first time that I have so much difficulty to create a server, on Space Engineers, ARK or other survival games I have never had a problem.

Thanks for your help.

**Expected behavior:**
See above

**Actual behavior:**
See above

**Comment by MarjieAVolk** [comment]
Just to double check, you have 'Public Server' set to 'true' in your server's network settings?

**Comment by coolfarmer** [comment]
Yeah, I have double check everything with your moderator (pam) on Discord. All is good but can't have it in public list.

**Comment by MarjieAVolk** [comment]
Okay.  Could you give me your ip address?  I want to check if it is getting listed on our server list service.

**Comment by coolfarmer** [comment]
You can ping directly **coolfarmer-pc.no-ip.info** , currently my ip is 70.48.79.245.

**Comment by MarjieAVolk** [comment]
Thanks, okay so I do see your server listed on our server listing service.  So you are set up right.  I guess there must be problems with the server browser, maybe your server is low enough in the list that it takes a long time for it to get loaded.

**Comment by coolfarmer** [comment]
I will have to retry, last time I have used the search function even after 10 minutes the server browser never found it. The browser is supposed to find the list by sort it by ping?

**Comment by MarjieAVolk** [comment]
Yeah, but it also takes quite a bit of time just to query for some standard info from all the servers.  Theoretically if you type in your search and then wait for a while, it should show up eventually.  But it also has not handled the huge increase in the # of servers very well, so I am not sure how much I trust it >>  We are working on a big re-write for this whole screen.

**Comment by coolfarmer** [comment]
Perfect I understand, thanks for sharing this infos!

**Comment by MarjieAVolk** [comment]
Sure thing.  Gonna close this out for now I guess.  Hopefully with the new server browser this will work better.
