### ISSUE TITLE
USER ISSUE: Caught exception

### ISSUE THREAD

**Issue by trudylein** [StrangeLoopGames/EcoIssues#6184]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Starting the game is possible, but after a short time the game crashes.

**Expected behavior:**
The game should run.

**Actual behavior:**
Caught exception: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. 

--BEGIN DUMP--
Dump Time
03/17/2018 09:11:10

Exception
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Eco.Simulation.Agents.Tree.GetBranchesBSON()
   bei Eco.Simulation.Agents.Tree.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   bei TreeEntity.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   bei Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   bei Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5000
