### ISSUE TITLE
Law Web Errors: Bunch of errors unable to use law proposal

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [StrangeLoopGames/EcoIssues#6185]
Too many to write so I am posting screenshot!
Browser: Chrome

Actions taken clicked in game on laws was taken to website tryed to propose see lots of errors

![errors](https://user-images.githubusercontent.com/10381947/37553962-8d9d46c0-29c9-11e8-83aa-a088168e061f.png)

**Comment by rainfarmer** [comment]
@Edgar-BlipparDev what browser are you using? Try Chrome

This is on the propose law page?

**Comment by rainfarmer** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/6112
