### ISSUE TITLE
USER ISSUE: Excavator out of fuel no mouse bug

### ISSUE THREAD

**Issue by Sanquira** [StrangeLoopGames/EcoIssues#6186]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Get an Excavator and fuel it
2. Dig and do stuff with excavator
3. Run out of fuel
4. Leave Excavator

**Expected behavior:**
You should have your mouse control.

**Actual behavior:**
Your character does not respond on mouse (you cannot turn around, etc.)

**Comment by SeanAtr0n** [comment]
fixed in next hotfix
