### ISSUE TITLE
Suggestion: Make a contract clause that demands payment. Mining/oildrilling Clause

### ISSUE THREAD

**Issue by zEverdeen** [StrangeLoopGames/EcoIssues#6187]
If you give people rights to something, then you should be able to make a clause that demands money.

Also add mining rights or oil drilling rights as a clause.

E.g. I want an clause that gives mining rights or oil drilling rights, but this needs a clause that demands payment.

**Comment by johnkslg** [comment]
Great idea. Will do it when I get time.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#198
