### ISSUE TITLE
USER ISSUE: No skill point generation since the last update

### ISSUE THREAD

**Issue by DubsTheFox** [StrangeLoopGames/EcoIssues#6188]
Well like the title already says my friend and I can't gain any skill points since the last update. We only have the problem on my server. The singleplayer works just fine. The only thing I have noticed is, every time I join the server a number pops up above the skill point bar like I would get 1732.72 skill points. I didn't change any settings since the last update, so I think it the problem is caused by the update.

**Comment by craig-jong** [comment]
Can you check your multiplayer server difficulty settings to see if they were affected by the update?

**Comment by DubsTheFox** [comment]
it wasn't changed. but we noticed a few hours later that the whole simulation has stopped working. so we decided to start a new world

**Comment by craig-jong** [comment]
Did you ever try to run the repopulate command or any other admin commands?

**Comment by DubsTheFox** [comment]
Yep. Now I am very sure its caused by the command. We used the repopulate command on the last server because the "spawnplant" command somehow doesn't work. I thought it was caused by the update because it stopped working afterwards. 
We used it on the new server today and the same thing happened. I was about to comment that we used the command and that it could be caused by it. and it was confirmed by your comment.

**Comment by craig-jong** [comment]
Repopulate was s'posed to have been removed from the game in a past update because of issues like this but it seems to have come back - if you're looking to respawn a specific plant, you should try the regenlayer command.

I'm going to leave this open until the command is, once again, removed from the game.

**Comment by craig-jong** [comment]
Actually it looks like repopulate is gone in our latest staging. If this presists past 7.3, please reopen.
