### ISSUE TITLE
USER ISSUE: New World Generation doesn't work

### ISSUE THREAD

**Issue by balloonhead** [StrangeLoopGames/EcoIssues#6189]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Play on a local Server. Quit
2. Click New and generate new world
3. the same world and data as within the local server appears.

**Expected behavior:**
A complete new World should be generated

**Actual behavior:**
the same world like in the local self-hosted server.

**Comment by MarjieAVolk** [comment]
Are you by chance naming the new world the same thing as the old world?  We just added some better naming and file path checks to the new world screen that would fix this, if that is your problem.

**Comment by MarjieAVolk** [comment]
Okay, then one other question - does the new world have the same things that you did in it, like for example your house or a tree that you chopped down?  Or is it just the same starting terrain?

**Comment by balloonhead** [comment]
the newly build world has the exact terrain and the exact buildings also my exact position when i left the server.

**Comment by MarjieAVolk** [comment]
Okay, thanks.  I will see if I can get this to happen here.

**Comment by MarjieAVolk** [comment]
I've been trying to get this to happen, but no dice.  Everything seems to be working right for me.

The next time this happens, could you send over your log file? "C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt"

**Comment by balloonhead** [comment]
yes i will do this
