### ISSUE TITLE
USER ISSUE: Game no response when many servers list out

### ISSUE THREAD

**Issue by narcissu14** [StrangeLoopGames/EcoIssues#6191]
# Issue description
List out too many servers will cause the game no response

**Comment by MarjieAVolk** [comment]
You mean when there are too many servers in the 'join' screen?

**Comment by narcissu14** [comment]
Yes, too many servers in screen makes the game starting lag. And when I want to quit, most of time it will no response

**Comment by narcissu14** [comment]
👍 Thanks for your hard works.

**Comment by MarjieAVolk** [comment]
Performance on the Join screen should now be much better.

**Comment by MarjieAVolk** [comment]
Edit: in the 7.4 release that is, which is coming soon, possibly today.
