### ISSUE TITLE
USER ISSUE: Refresh Server List

### ISSUE THREAD

**Issue by BJmini** [StrangeLoopGames/EcoIssues#6194]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Start the game
2. Click 'Join'
3. Click 'Add Server'
4. Type in IP:Port
5. Click 'Add'
6. Click 'Refresh'

**Expected behavior:**
It should have refreshed the list showing the added server as favorite.

**Actual behavior:**
Instead it showed me no servers at all. After closing the list, logging out and back in, it's stuck saying "Logging in...". After it produced the problem, unrelated to trying to relog, whenever I try to close the game (via 'Quit' or 'Alt+F4') it freezes and has to be terminated manually. Restarting the game and/or the PC didn't help, or rather produced the same problem over and over again.

**Comment by coolfarmer** [comment]
I would add that the list is SOOOOO long to refresh sometime ...

**Comment by MarjieAVolk** [comment]
The Join screen and the server connection code have both been revamped in 7.4.  Hopefully it will work much better for you.  Let me know if you have any more problems after updating!
