### ISSUE TITLE
stack of items used with single click

### ISSUE THREAD

**Issue by DHWise** [StrangeLoopGames/EcoIssues#62]
Version Alpha 0.3 on Windows 10, playing on server worldofeco.net
Single click to place either a refined stone or a wooden roof made on the workbench uses the stack.
Only while building a building.

**Comment by klimSLG** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/58

**Comment by mariowenig** [comment]
Issue of disappearing items/stacks still exist in 4.1 (when placing)

**Needed:**
3 ChestItem (in stack) (any place-able item should work)
1 Hammer

**Reproduction steps:**
Place 3 chests
Collect 3 chest with hammer into single stack.
Place 1 chest, will consume all three chests.
