### ISSUE TITLE
USER ISSUE: Woodcard driving alone

### ISSUE THREAD

**Issue by LostRune** [StrangeLoopGames/EcoIssues#6200]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Walk on asphalt with a woodcard.
Let it go while moving.

**Expected behavior:**
stop or at least don't go crazy

**Actual behavior:**
It drives forever, even uphill.

**Comment by Epimetheus89** [comment]
I think this is a duplicate of #6104

**Comment by SeanAtr0n** [comment]
Fixed 7.3
