### ISSUE TITLE
USER ISSUE: no skill points 

### ISSUE THREAD

**Issue by Gar-W85** [StrangeLoopGames/EcoIssues#6201]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
when u do a achievement you are not getting rewarded for it 

**Expected behavior:**
to get a skill point when u complete a task 

**Actual behavior:**
nothing is happening and all the skills ponts are gone

**Comment by craig-jong** [comment]
I'm not really sure what this means, but I did fix a bug where the skill points bar was incorrectly displaying progress. I'm going to close this. Please reopen it with more specifics if the issue persists.
