### ISSUE TITLE
USER ISSUE: Door open with shovel

### ISSUE THREAD

**Issue by Eideard** [StrangeLoopGames/EcoIssues#6203]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Take a Shovel (wooden) in you hand
2. Get dirt from a stockpile with left klick
3. take dirt back to the stockpile (or card, i have testet with both)
4. Try to open the door (wooden) with right click.

**Expected behavior:**
The door opened.

**Actual behavior:**
The door do nothing.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3868
