### ISSUE TITLE
Bad POST requests in web client/API

### ISSUE THREAD

**Issue by AndyClausen** [StrangeLoopGames/EcoIssues#6206]
You have a flaw in your web client. Your AJAX calls are using url parameters in post requests, you should send them as body instead in a JSON format or so.

Example: `http://4.20.4.20:1337/api/v1/elections/addcandidate?authtoken=LONGHEXSTRINGHERE&speech=Hello%20World!&username=??Anarki??`

In this case, it's my friend's server. He has a username with non-URL-friendly characters. This could possibly be fixed by sending through a request body instead of directly in the URL, which causes the API server to throw a 500.

If you can also tell me where the files for the API are, that would be great. I can only find the AngularJS files. If you can do this, I could even make a fix for it myself and post it here.

**Comment by MarjieAVolk** [comment]
The game web server api is defined in Server/Eco.Webserver.

Ironically, we do not use that username field anymore, so if it is causing problems, we should prioritize removing it.

**Comment by AndyClausen** [comment]
Oh okay. Well, if it's not used, then it shouldn't be causing problems. Can you maybe check if you're using the same charset in Web frontend and backend as in the game? Don't know if that has anything to do with it. Or maybe in the request headers in web? Don't know much about HTTP request header tbh.

**Comment by MarjieAVolk** [comment]
Yeah, the param is getting populated on the web side, but not read on the server side, so it might be causing problems.  We have just added a bunch more support for special characters server side, which may not have been addressed web side yet too.

**Comment by AndyClausen** [comment]
Ah, that might be it. Because it suddenly stopped working.

**Comment by MarjieAVolk** [comment]
The web side should be sending your friend's up-to-date steam name, so they can try changing their name to see if that makes the problem go away.

**Comment by MarjieAVolk** [comment]
Well assuming it was a username in the url problem - fixed in 7.3
