### ISSUE TITLE
Wood Cart drives further after getting out

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#6207]
Since one of the latest updates i notice a wooden cart driving further without me steering it when i leave it while i was still moving. Funnily, it does only stop when it hits something, and even more funny it does not ever run further in the direction i was driving, but sometimes in the opposite direction.

**Comment by D3nnis3n** [comment]
I see this has been fixed for other types of vehicles in 7.2.5 - it persists in 7.2.5 for the normal wood carts, though.

**Comment by SeanAtr0n** [comment]
Fixed in 7.3
