### ISSUE TITLE
Mac client crashes

### ISSUE THREAD

**Issue by FreshClash** [StrangeLoopGames/EcoIssues#6208]
I have the problem that when I want to start eco. It get's stuck before even the menu appears :/.  I also gave it a try with a mac of a friend of mine. -> The same problem appeared. 
Thank you in advance

**Comment by Epimetheus89** [comment]
Does it crash or does it load the menu if you wait along time? I had to wait a long time to load the menu on Mac as described in this issue #4281

**Comment by MarjieAVolk** [comment]
Going to close as duplicate of #4281 for now
