### ISSUE TITLE
Trees wig out when you cut them down

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#621]
This is because their branch physics often intersects with surrounding trees.  Make branches not collide with other trees and this will fix itself.

**Comment by metachronism** [comment]
You can't do this, they are the same rigid bodies

this would result in trees falling through each other and not otherwise colliding on the ground

they need to not be spawned so close together

**Comment by johnkslg** [comment]
Let's find a way to make the branches not collide with trees.  The trunks should still collide.  I'm sure it can be done.  Current behavior is not shippable.
