### ISSUE TITLE
Contracts: Property selection list is empty.

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#6216]
On Eco 0.7.2.5, Linux Server,

When making a Contract that specifies a storage location, i.e. a Stockpile or Chest,
The list of Stockpiles / Chests is empty - none can be selected.

**This breaks the Contracts system for "Harvest Field", "Put Items in Container", "Receive Permissions", and "Transport" contract clauses.**

![image](https://user-images.githubusercontent.com/2173684/37561750-4201388c-2aa2-11e8-8fd1-820a5e76bb2b.png)

![image](https://user-images.githubusercontent.com/2173684/37561754-58428c68-2aa2-11e8-8acd-c530b9705554.png)

![image](https://user-images.githubusercontent.com/2173684/37561757-62d5c172-2aa2-11e8-8a34-1f6a3c8ac818.png)

![image](https://user-images.githubusercontent.com/2173684/37561758-6f699404-2aa2-11e8-8a72-900e6138d830.png)

**Comment by johnkslg** [comment]
Fixed in staging
