### ISSUE TITLE
USER ISSUE: Looking for supplies

### ISSUE THREAD

**Issue by chopperprop** [StrangeLoopGames/EcoIssues#6222]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
When you look at ORE in the world and or get close to it to see what type it is

**Expected behavior:**
the type of ore or stone should be displayed

**Actual behavior:**
nothing happens

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#197
