### ISSUE TITLE
USER ISSUE: Cut tree logs vanish if the player walks to far away (map distance check error?)

### ISSUE THREAD

**Issue by CiberX15** [StrangeLoopGames/EcoIssues#6223]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Cut down a tree
2. Cut up tree (optinal)
3. Mark location
4. Walk far away
5. Walk back
6. Observe tree trunks have disapeared

Note: This appears to be made more obvious becasue the point on the planet I am mining is near the place that the map flips. I noticed that when I get to the mining location the waypoints are pointing in the oposite direction from where my base actually is, presumably wraping around the other side of the planet. This is most likely making the distance check throw a false positive when checking weather an object is far enough away from the player to delete the object.

**Expected behavior:**
Resource items in world should not dissapear, at least not within the limited distance that they were lost from.	

**Actual behavior:**
Resourced logs vanish, wasting resources

**Comment by SlayksWood** [comment]
Checked on 8.1.4. Wasn't able to reproduce, seems fixed.

**Comment by mattkennedynz** [comment]
Hey folks (especially @SlayksWood), I know this is closed but I'm still encountering this issue (and the referenced issues) on 8.1.4. I'm attaching my log files if they're of help: [output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3269152/output_log.txt) and [output_log_copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3269153/output_log_copy.txt)

The way I work around it is by either walking sufficiently far away from area until my computer re-renders the region, or by disconnecting and reconnecting (the latter is also is a work around for the low frame-rate issue which seems to happen after travelling sufficiently far away from your starting location, then returning to the same place after having interacted with lots of stuff along the way. By the way, these log files could also serve to help the low-frame rate bug as I'm currently experiencing that as well).
