### ISSUE TITLE
USER ISSUE: Excavator lost, server laggy

### ISSUE THREAD

**Issue by Mattheus80** [StrangeLoopGames/EcoIssues#6224]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. work wit Excavator
2. boom
3. Excavator flying over Planet
    second Excavator too, can´t find them
4. server lags and fps-drops since boom

**Expected behavior:**
If Excavator get lost there should be a method to despawn or bring it back (Admin command or with Deed)

**Actual behavior:**
Excavator get lost, fly somethere and cause lags and fps-drops.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6159
