### ISSUE TITLE
Contracts: Road Contracts Cannot Be Completed

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#6225]
Eco 0.7.2.5.

I set a contract to build a straight track of asphalt road, approximately 40 metres east-west, all on a level surface (i.e. no change in height.)

The contractor has built the road to the required specification, as shown in screenshots below.

The road contract cannot be completed.

Possibly related to #5082, though apparently that was already fixed.

![image](https://user-images.githubusercontent.com/2173684/37563062-064e87aa-2ac4-11e8-9a8b-cdad3eef2507.png)

![image](https://user-images.githubusercontent.com/2173684/37563070-186b52e2-2ac4-11e8-9298-9efe9c60d882.png)

![image](https://user-images.githubusercontent.com/2173684/37563074-3dc79cee-2ac4-11e8-9c45-bd674fc9b65f.png)

![image](https://user-images.githubusercontent.com/2173684/37563079-55ccbb26-2ac4-11e8-9e34-a0c60d651048.png)

![image](https://user-images.githubusercontent.com/2173684/37563087-8deb8082-2ac4-11e8-8805-f01a29dd90c1.png)

![image](https://user-images.githubusercontent.com/2173684/37563088-961c883c-2ac4-11e8-842a-77cc9770d985.png)

**Comment by johnkslg** [comment]
This is fixed in staging.  Try it out in the staging build to confirm if you like but pretty sure its the same as the other bug, the fix just hasnt made it to release yet.
