### ISSUE TITLE
USER ISSUE: Save Chat Window Settings

### ISSUE THREAD

**Issue by crymates** [StrangeLoopGames/EcoIssues#6227]
**Version:** 0.7.2.4 beta

**Steps to Reproduce:**
When you reconnect or restart the game your chat settings get resetted.

**Expected behavior:**
It should e.g. show only the chat

**Actual behavior:**
It shows General, Crafting, Logins, ... on the left side, the chat on the right side.

**Comment by MarjieAVolk** [comment]
Is this happening when you reload a local world?  Or when you disconnect and reconnect on a dedicated server?

**Comment by SlayksWood** [comment]
Seems fixed. It separately saves chat setting for each server.
