### ISSUE TITLE
USER ISSUE: VERY ABUSABLE - Negative buy prices drain tax

### ISSUE THREAD

**Issue by dlouwers** [StrangeLoopGames/EcoIssues#6229]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
- Set negative buy price, usefull for tailings and bunchgrass seeds and other unwanted items. 
- Make a transaction

**Expected behavior:**
Tax is paid to the treasury

**Actual behavior:**
Tax is drained from the treasury and added to the sellers credits

**Comment by MarjieAVolk** [comment]
Fixed in 7.3.  Taxes will now always be positive.
