### ISSUE TITLE
USER ISSUE: Open Door has Wrong Key

### ISSUE THREAD

**Issue by bombitmanbomb** [StrangeLoopGames/EcoIssues#6232]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Press E on Door
2. Realise E does not actually open the door

**Expected behavior:**
Opened the door

**Actual behavior:**
Opened the permission menu

**Comment by MarjieAVolk** [comment]
You need to right click to open the door.

**Comment by bombitmanbomb** [comment]
Yes I am aware but on your own doors it says "Press E to Open"

**Comment by MarjieAVolk** [comment]
On the controls tooltip?  That's interesting, they look correct to me, although I am on the staging version.  Maybe already fixed?

**Comment by MarjieAVolk** [comment]
Okay, double checked with team, and it seems it was fixed recently.  So, fixed in 7.3

**Comment by bombitmanbomb** [comment]
Possibly? On the public "stable release build" I guess I'll call it it only
does it for Your Own doors. Other people's doors the tooltip is correct

**Comment by bombitmanbomb** [comment]
Ok

**Comment by MarjieAVolk** [comment]
Oh, only for your own?  Okay I will check that

**Comment by MarjieAVolk** [comment]
Hm no I still don't see any problems on latest staging build
