### ISSUE TITLE
USER ISSUE: 100% CPU usage on chrome when browing a page with the map

### ISSUE THREAD

**Issue by neyna** [StrangeLoopGames/EcoIssues#6233]
If you press L in game, new law, go to the website, create a new district to get the map, then chrome uses all CPU available and the website is very laggy (the map is almost unusable).

This bug affects around 5 people on my server (with a total of 20 players asked).

I do not have any plugin in chrome, it's a vanilla installation.

I have no problem with the map using using firefox.

**Comment by rainfarmer** [comment]
@neyna could you send your computer stats?

*The version of the game you were running
*Operating system
*Processor model
*Graphics card model
*Amount of RAM

**Comment by neyna** [comment]
Hello,

*The version of the game you were running : 7.2.5
*Operating system : windows 10 pro
*Processor model : i5 3570K OC to 4.2 Gz (standard OC for this CPU, no issue with OC for 1+ year)
*Graphics card model : GTX 970
*Amount of RAM : 16 Go

I tested closing the game after opening the webpage to lower cpu usage to less than 10% and when i go on "view district" page, the cpu goes to 100%.

**Comment by rainfarmer** [comment]
@SeanAtr0n any ideas?

their computer should be able to handle the map easily.

@neyna could you press f12 in browser and see if there are console errors. and send them please.

**Comment by neyna** [comment]
Hello,

no console error :

jquery-latest.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery-latest.min.js:4
ajax @ jquery-latest.min.js:4
m._evalUrl @ jquery-latest.min.js:4
domManip @ jquery-latest.min.js:3
prepend @ jquery-latest.min.js:3
m.fn.(anonymous function) @ jquery-latest.min.js:3
(anonymous) @ (index):49
j @ jquery-latest.min.js:2
fireWith @ jquery-latest.min.js:2
x @ jquery-latest.min.js:4
b @ jquery-latest.min.js:4
XMLHttpRequest.send (async)
send @ jquery-latest.min.js:4
ajax @ jquery-latest.min.js:4
m.(anonymous function) @ jquery-latest.min.js:4
(anonymous) @ (index):48
three.min.js:173 THREE.WebGLRenderer 88

Chrome eats 97% of my CPU when the page with a map is open. (i go from 4% to 100% cpu usage)

**Comment by neyna** [comment]
Ok i found something to solve this problem.
My chrome configuration had hardware acceleration set to off, I turn it to on and now the page works correctly (20% cpu 10% gpu).
I dont know if this setting is off or on by default but i never touched it. But my chrome installation is very old (several years) and maybe the default value changed (could explains why 15/20 people on my server dont have this issue)

**Comment by rainfarmer** [comment]
Oh great, thanks for the update and solution.
