### ISSUE TITLE
No way to destroy another player's cart as admin

### ISSUE THREAD

**Issue by neyna** [StrangeLoopGames/EcoIssues#6239]
There is no way to destroy another player's cart as admin (no command and devtool does not work on something you dont own).

Only way i know is to unzip game.eco and delete all carts and zip it again. But it's not a good solution at all.

Inactive player's carts are really a problem when you are managing a big server. Please add a way to destroy them.

**Comment by LiaungYip** [comment]
Duplicate of #3607.

**Comment by MarjieAVolk** [comment]
Thanks, closing as duplicate
