### ISSUE TITLE
Graphical glitch when placing an item created with the modkit.

### ISSUE THREAD

**Issue by neyna** [StrangeLoopGames/EcoIssues#6240]
I followed the ceiling fan modkit tutorial and when you are placing it in the world you encounter a graphical glitch showing a cube as outline :
![image](https://user-images.githubusercontent.com/3091083/37567142-ed355f4c-2ac2-11e8-9f01-fdd7a41e3703.png)

No problem when item is placed : 
![image](https://user-images.githubusercontent.com/3091083/37567160-296e7c46-2ac3-11e8-999b-df0e72d9f289.png)

The solution is to remove the cube (mesh part) in the CeilingObject and set it to none.

**Comment by Kodekc** [comment]
Close, this is not a ModKit error. I myself was aware of this, but there was no explanation in the tutorial. It is necessary to remove mesh and cube, leaving them on the object, but not in the root folder
