### ISSUE TITLE
USER ISSUE: Camo shirt is not camo

### ISSUE THREAD

**Issue by Arturaceloray** [StrangeLoopGames/EcoIssues#6241]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Create and equip a camo shirt.

**Expected behavior:**
Camo pattern

**Actual behavior:**
white torso with hot pink arms

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3208
