### ISSUE TITLE
Item created with ModKit is written in white in game while other items are written in blue

### ISSUE THREAD

**Issue by neyna** [StrangeLoopGames/EcoIssues#6244]
See screenshot :
![image](https://user-images.githubusercontent.com/3091083/37567634-f6b6a0a6-2ac9-11e8-8766-fb7a2835d576.png)

**Comment by FishAus** [comment]
On the icon for the CeilingFanItem in unity change the colour of the background overlay. 
In the tutorial Sean sets the overlay to white, but whatever colour you set this to will be the chat colour.

**Comment by MarjieAVolk** [comment]
Thanks @FishAus.  Yes, the color of the text will match the color of the image named "Background" in the icon object, if any.
