### ISSUE TITLE
USER ISSUE: Crimini Mushroom

### ISSUE THREAD

**Issue by seene** [StrangeLoopGames/EcoIssues#6247]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
there is not a single cimini mushroom in the whole World. So i cant research the farming skill

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5568
