### ISSUE TITLE
Possible Bug - Carry more than you can

### ISSUE THREAD

**Issue by Daryl791** [StrangeLoopGames/EcoIssues#6248]
This bug has been tested with split and none split piles.

If you go to a storage box or stock pile and say grab 100 iron ingots which no one can carry.  Pick it up and act like you are dragging it to your hot inventory but don;t.  

Press esc while while holding the item and you can now walk anywhere and deposit it in a chest on the other side of the world. Just as long as you don't release the mouse button.

Want to take a stack of forty coal in hand, drag 20 to your carry slot.  And hold 20 in your hand using the above method.

**Comment by MarjieAVolk** [comment]
Oh gosh this is hilarious.  Okay, fixing this will also help alleviate stuck drags which I cannot figure out how to fix, so let's do it lol

**Comment by Daryl791** [comment]
Looks like you got them fixed in the new notes.  Thanks for all the work you guys do with the updates and fixes.

**Comment by MarjieAVolk** [comment]
Thanks for playing!

Yep, fixed in 7.3 (idk why github's auto close thing isn't working right now)
