### ISSUE TITLE
USER ISSUE: reaching Tier 2 impossible

### ISSUE THREAD

**Issue by the-max** [StrangeLoopGames/EcoIssues#6251]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**

**Expected behavior:**
To craft lumber for T2 I need to use the sawmill. The sawmill is crafted with the anvil, that requires T2 buildings.

**Actual behavior:**
I should be able to create the sawmill in a different way ot at least to use the anvil with T1

**Comment by Huntermeign** [comment]
Didnt they solve this by making the kiln a tier 1 requirement? This would allow you to make bricks so you can make Lumber

**Comment by the-max** [comment]
Well, I just noticed that one of these materials is enough.
