### ISSUE TITLE
USER ISSUE: players can't join

### ISSUE THREAD

**Issue by gabgab01** [StrangeLoopGames/EcoIssues#6253]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. start new world - settings: high collab, friends can join etc.

2. tab out of the game, allow whatever message there is

3. try to invite friends and - oh, it's greyed out.

lemme jsut try to host the server separately then, shoudl work, right?
so navigate into the games files, ah, there is the server! okay, default ports are 3000 and 3001? fine, i'll jsut set that in my router and in my firewall, both TCP and UDP to make sure.
aight, server was started with administrator, NAT enabled, found everything, set it to public, put a name and password in, i can join and my friends - can NOT join.
oh, apparently i jsut have to put my IP in there aswell. well, i do it and... the server crashes. and again.
well, how about "0.0.0.0"? server doesn't crash but friends can't join.

let's see what the forums and other people say...

it should have worked. it's not my first time hosting game server for private purposes.

i'm not the only one with this issue. on the steam discussions, there are multiple people with the same problem. some people claim that it works if you use the server files from your website, but it still didn't work for me. you can contact me easily if you want to discuss this further. on discord, i'm gabgab01#0380

**Comment by MarjieAVolk** [comment]
Sorry you're having trouble.  You shouldn't need to set your ip address in the server, that is only needed if you are doing fancy stuff with multiple ip addresses.

Since it sounds like you set up port forwarding stuff yourself, maybe you should try disabling our built in DetectNAT setting?

**Comment by gabgab01** [comment]
thanks for the answer.
i've first tried hosting it with NAT disabled, it didn't work either.
and i also played around with the NAT setting, but to no avail.
interestingly enough, the server apparently is able to communicate with the master server, as there is no error message when the server starts, but there is an error message when i alter the master server link, meaning that the correct link (the default one) works and the server has no problems connecting with the master server.
of course, i don't know for sure, because the server kinda lacks feedback.

what's also fun is that the server does not produce any errors whatsoever.
since it crashes if i type my ip in there, i just left it on any whenever i started it, as i'm not juggling around with weird IP-stuff anyways.

is there anythign else i could try to do on my end? i've got full administrator privileges over both my PC and router.
would also like to send the server error log, if there is any. so far, i haven't found one.

**Comment by MarjieAVolk** [comment]
Could you tell me your ipaddress?  I can check whether your server is listed on our server list service.

Also, have your friends tried connecting to your server via ipaddress?

**Comment by gabgab01** [comment]
i am hosting it on my private pc, so the ip changes daily and i'd have to manually start the server.
my friends have also tried to manually connect to my ip, sometimes even putting the port behind it, to no avail.
i have also tried to connect to my own server, which runs on the same machine as my game btw, and there it of course works, but i only see it in the lan-tab, not on the official server list.

so far only one guy managed to join my server succesfully, 2 other dudes were unable to. but those others however can join other game servers of mine without problems.

we'd have to set up a time where we'd try to properly troubleshoot the issue with coordination.
you can reach me through either steam or discord if you're interested in helping me out with this.
my steam username is also gabgab01, and on discord i'm gabgab01#0380. i might take a few hours to answer first, since i live in the eu, different timezones and such.

and yes, i know that this issue seems weird. maybe it's just my pc.

**Comment by MarjieAVolk** [comment]
Our networking system and our steam join features have both gotten big improvements in 7.4.  Hopefully you will be able to connect now.  Let me know if you still have problems.
