### ISSUE TITLE
USER ISSUE: Powered Cart

### ISSUE THREAD

**Issue by KebabRemovalSquad** [StrangeLoopGames/EcoIssues#6256]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Engineer builds a powered cart and sells it 2. Customer places the cart 3. Customer receives the Deed 4. Customer can't deconstruct his cart (with the hammer) 5. No clue why but now my cart is basically unusable when it falls into the water.

**Expected behavior:**
The Customer should be able to deconstruct his powered cart with the hammer.

**Actual behavior:**
Well the Customer can't deconstruct his own cart with his hammer.

**Comment by MarjieAVolk** [comment]
So you can open the cart's inventory and stuff, but you can't pick it up?  Does the cart have anything in it, perhaps?  Do you see any error messages in chat when you try to pick it up?

**Comment by KebabRemovalSquad** [comment]
Yeah it's empty. I took the remaining gas out of it and also the Items in the storage. It said that i'm not authorized to pick it up because it isn't mine. Well i went to the Engineer who build it for me but he wasn't able to pick it up either (did it because of the authorization said it aparently was his). Idk if it just bugged but after a Server Restart it fixed itself. I can pick it up now. But still might be a good idea to take a look at the files in case there it has something to do with that.

**Comment by MarjieAVolk** [comment]
Ah okay.  Well if a server restart fixes it, that's gonna be harder to look at :'(  I would have said to look at the deed window to see who the owner was, but too late I guess.

**Comment by D3nnis3n** [comment]
Deed System changed in the meanwhile, picking up the powered cart is possible.
