### ISSUE TITLE
USER ISSUE: Currency Exchange as World Leader

### ISSUE THREAD

**Issue by CobaltEcho** [StrangeLoopGames/EcoIssues#6260]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Become World Leader
2. Make a Mint.
3. Make a Currency Exchange.
4. Set all the exchange rates.
5. Now, as a world leader, try to exchange some currency.

**Expected behavior:**
There should be a way for the world leader to exchange currencies they aquired earlier in the game.

**Actual behavior:**
The world leader should be able to exchange currencies like all the other players.  Although I can see potential abuse with this... Perhaps a way to lock the rates by voting?

**Comment by johnkslg** [comment]
All currency exchange happens between players, if the world leader is the one who made the currency exchange he can't use it.

Stay tuned though, we will be adding government bank accounts, which I think is what you're looking for. Separate accounts which can be controlled by one or more government officials.
