### ISSUE TITLE
3 Dumps in 1 minutes 

### ISSUE THREAD

**Issue by Xnetsrac** [StrangeLoopGames/EcoIssues#6261]
--BEGIN DUMP--
Dump Time
03/18/2018 23:49:28

Exception
System.Exception: Caught exception invoking RPC PlayerInteract on Player!

Timeout. Database is locked for more than 00:01:00.

Stack:
   bei LiteDB.LockService.Write()
   bei LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   bei LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   bei LiteDB.LiteCollection`1.Insert(T document)
   bei Eco.Core.Utils.AtomicAction.SimpleAtomicAction.TryApply()
   bei Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   bei Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   bei Eco.Gameplay.Items.UsableItemUtils.PlayerPlaceBlock(Type blockType, Vector3i blockPosition, Player player, Boolean replaceBlock, IAtomicAction[] additionalActions)
   bei Eco.Gameplay.Items.BlockItem.PlaceBlock(Type blockType, Vector3i targetPos, Player player, Boolean replaceBlock)
   bei Eco.Gameplay.Items.BlockItem.OnActRight(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer()
   bei Eco.Shared.Networking.NetPort.Update()
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_0()

--END DUMP--

--BEGIN DUMP--
Dump Time
03/18/2018 23:50:08

Exception
LiteDB.LiteException: Timeout. Database is locked for more than 00:01:00.
   bei LiteDB.LockService.Read()
   bei LiteDB.LiteEngine.<Find>d__9.MoveNext()
   bei LiteDB.LiteEngine.<Find>d__13.MoveNext()
   bei LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   bei Eco.Gameplay.Players.WelcomeMessage.<>c.<Get>b__2_4(<>f__AnonymousType15`2 <>h__TransparentIdentifier2)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   bei Eco.Gameplay.Systems.Tooltip.TooltipExtensions.FoldoutList(IEnumerable`1 list, String itemNounSingular, Int32 max)
   bei Eco.Gameplay.Players.WelcomeMessage.Get(Player player)
   bei Eco.Gameplay.Systems.Chat.ChatManager.Eco.Shared.Networking.INetObject.SendInitialState(BSONObject bsonObj, INetObjectViewer viewer)
   bei Eco.Shared.Networking.NetObjectManager.GetInitialObjectStates(IEnumerable`1 newObjects, INetObjectViewer viewer, ICollection`1 monitored)
   bei Eco.Plugins.Networking.Clients.Client.Update(Stopwatch timer)
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__56_1()

--END DUMP--

--BEGIN DUMP--
Dump Time
03/18/2018 23:50:17

Exception
LiteDB.LiteException: Timeout. Database is locked for more than 00:01:00.
   bei LiteDB.LockService.Write()
   bei LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   bei LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   bei LiteDB.LiteCollection`1.Insert(T document)
   bei Eco.Simulation.WorldLayers.WorldLayerStats.<>c__DisplayClass0_0.<CollectStats>b__0(Species species)
   bei Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   bei Eco.Simulation.WorldLayers.WorldLayerStats.CollectStats()
   bei Eco.Simulation.EcoSim.CollectStats()
   bei Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   bei Eco.Simulation.EcoSim.DoTick(TickSample tick)
   bei Eco.Simulation.EcoSim.Run()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5343
