### ISSUE TITLE
USER ISSUE: Backpack does nothing?

### ISSUE THREAD

**Issue by BJmini** [StrangeLoopGames/EcoIssues#6262]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Wear a backpack
2. Check carrying capacity
3. Remove the backpack
4. Check again

**Expected behavior:**
It should change the carrying capacity.

**Actual behavior:**
It doesn't. The "Big backpack" effectively brings my capacity down because of the fact that it weighs 0,1kg more than the standard one.

**Comment by LiaungYip** [comment]
Also seeing this on 0.7.2.5 with Big Backpack and the Bearpack.

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/37739410-34521a9a-2d17-11e8-94b9-725ed65d5e0a.png)

I'm seeing the bearpack/big backpack working, however I see that the regular backpack does nothing. Will fix.

**Comment by craig-jong** [comment]
fixed in new staging
