### ISSUE TITLE
USER ISSUE: Fell through the world.

### ISSUE THREAD

**Issue by SomefluffyBunny** [StrangeLoopGames/EcoIssues#6263]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Set your view distance to about 60
2. Walk in one set direction
3. Fall forever

**Expected behavior:**
I should have not been thrown into the abyss.

**Actual behavior:**
Im stuck here forever.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5917
