### ISSUE TITLE
USER ISSUE: tower bug

### ISSUE THREAD

**Issue by Otaku2932** [StrangeLoopGames/EcoIssues#6265]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Build a tower to height limit
Place all sorts of items near the base of tower

**Expected behavior:**
items are visible and interactable

**Actual behavior:**
items are invisible and uninteractable, can be visible to soil analyser for such items as stone ramps but cannot go up a stone ramp and acts like it is not there. Other invisible items include carts, powered carts, trees storage boxes and stockpile. Stockpile still interactable from other still visible storage or stockpile.

**Screenshots:**
![20180319005749_1](https://user-images.githubusercontent.com/37527056/37578820-7b731cce-2b11-11e8-8f47-7c47a6578aa8.jpg)
![20180319005806_1](https://user-images.githubusercontent.com/37527056/37578821-7b8451ce-2b11-11e8-8d17-f1c9b0add2d0.jpg)
![20180319005819_1](https://user-images.githubusercontent.com/37527056/37578822-7b931ac4-2b11-11e8-8359-78ac7cfaa69e.jpg)
![20180319005828_1](https://user-images.githubusercontent.com/37527056/37578824-7ba6c0f6-2b11-11e8-985b-1c6e65f76e88.jpg)
![20180319005846_1](https://user-images.githubusercontent.com/37527056/37578825-7bb5f6f2-2b11-11e8-878a-64f967708b63.jpg)
![20180319005857_1](https://user-images.githubusercontent.com/37527056/37578826-7bd04eda-2b11-11e8-9ae0-8d0f5c40e3f2.jpg)
![20180319005908_1](https://user-images.githubusercontent.com/37527056/37578827-7be1c296-2b11-11e8-9aa3-aa1d4273d52a.jpg)
![20180319005959_1](https://user-images.githubusercontent.com/37527056/37578828-7bf48246-2b11-11e8-83a5-fac737fe33dc.jpg)
![20180319012903_1](https://user-images.githubusercontent.com/37527056/37579512-08af0352-2b15-11e8-88b0-8d1228b0f123.jpg)

**Comment by metachronism** [comment]
sean fixed this.  It was related to the waitforground script failing to spawn the objects in
