### ISSUE TITLE
[Staging Beta 7.3.0 #Fb586bc2]  Very High RAM usage on new default world

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6267]
On a new server with no players online and no citizens yet the server has a very high RAM usage for a default world.  In previous versions with new world RAM rarely exceeded 2GB with many players doing lots of things.  The server RAM below was snapshotted with server empty of all players and nothing had been done on this world since creation

[![Screenshot from Gyazo](https://gyazo.com/9d7b32244487a614c99205577eb99bb6/raw)](https://gyazo.com/9d7b32244487a614c99205577eb99bb6)

**Comment by pamduncan** [comment]
Once players,7, joined the game the RAM has jumped to  over 10 GB.  This is a very high amount of RAM for 7 players

**Comment by metachronism** [comment]
pretty sure this was chat bug
