### ISSUE TITLE
USER ISSUE: Stone falling from the sky.

### ISSUE THREAD

**Issue by dschealler** [StrangeLoopGames/EcoIssues#6271]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Send an excavator underwater.
2. Excavate underground.
3. Let the excavated stone pack in really tightly underground/underwater.
4. Keep pushing the excavator into the tight space being excavated.

**Expected behavior:**
Excavated stone underground and underwater should stay underground/underwater.

**Actual behavior:**
Above ground, stones start to fall from the sky. :)

**Comment by SlayksWood** [comment]
Checked on 8.1. Wasn't able to reproduce, seems fixed.
