### ISSUE TITLE
USER ISSUE: Mortared stone

### ISSUE THREAD

**Issue by Selerastar** [StrangeLoopGames/EcoIssues#6273]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Set to make 15 or more mortared stone in a single player game.

**Expected behavior:**
Should finish after alloted time and give you 15 mortared stone.

**Actual behavior:**
Says it is 100% finished and still shows active in the crafting table when it has only finished 14.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3240 (will be fixed in 7.3)
