### ISSUE TITLE
error after using fishing rod

### ISSUE THREAD

**Issue by DrPeppiX** [StrangeLoopGames/EcoIssues#6274]
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1825326/error.log)

**Comment by MarjieAVolk** [comment]
Unfortunately this seems to be a bug in Unity (see https://github.com/StrangeLoopGames/EcoIssues/issues/4272).  Guess we are waiting for a unity update that fixes this.

Are you running the game on a mac by any chance?

**Comment by DrPeppiX** [comment]
Nope. Windows.  Sry

**Comment by MarjieAVolk** [comment]
Okay, thanks.  Well, Unity marked this as fixed earlier in the year, but it's unclear whether it is actually fixed.  We're going to update our Unity version on our build machine to see if that makes this go away.

**Comment by DrPeppiX** [comment]
Thx for the Info.  Keep up the good work!

**Comment by Dimitri0xff** [comment]
Hello,
Did updating Unity solve the UnityPlayer.dll crash problem (#4272)? If yes, which version, 2017.4?
