### ISSUE TITLE
Blast furnace creating ground pollution

### ISSUE THREAD

**Issue by greatmutato** [StrangeLoopGames/EcoIssues#6276]
My blast furnace is polluting the ground.
I have triple check my tailings and they can't be blamed for ground pollution.
The data are showing three peaks in my ground production 
<a href="http://www.noelshack.com/2018-12-1-1521449239-pollution.png"><img src="http://image.noelshack.com/minis/2018/12/1/1521449239-pollution.png" border="0" alt="1521449239-pollution.png - envoi d'image avec NoelShack" title="1521449239-pollution.png"/></a>
The first little bump is producing and disposing tailing, the two others are blast furnace orders.

Tailings mine show no sign of pollution 
 <a href="http://www.noelshack.com/2018-12-1-1521449782-pollution.png"><img src="http://image.noelshack.com/minis/2018/12/1/1521449782-pollution.png" border="0" alt="1521449782-pollution.png - envoi d'image avec NoelShack" title="1521449782-pollution.png"/></a>

I have made a new order on the furnace to double check the fact the furnace is indeed the problem and we can see another ground pollution peak right after
![image](https://user-images.githubusercontent.com/37193038/37603488-07803648-2b8f-11e8-922c-7406482a1151.png)
And with "show in world" checked, this is what the room with the furnace looks like (we did try to bluid a room to see if it will affect the spreading)

![furnace](https://user-images.githubusercontent.com/37193038/37603516-14949324-2b8f-11e8-802d-0289ac69f368.png)

Is this air pollution falling and polluting the ground ? Is this a normal behaviour for the blast furnace ?

**Comment by craig-jong** [comment]
This is intended behavior - air pollution creates ground pollution over time.
