### ISSUE TITLE
USER ISSUE:  Woodcard under water

### ISSUE THREAD

**Issue by annoxoli** [StrangeLoopGames/EcoIssues#6279]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Put a Woodcard (or anything else) into a sea
2. Deceive to your Woodcard
3. You can use your Card under water (movement etc.)

**Expected behavior:**
Impossible to hold / drive it under water

**Actual behavior:**
You can drive/move it under the sea.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#196
