### ISSUE TITLE
Occupancy all messed up

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#628]
![image](https://cloud.githubusercontent.com/assets/3536496/19573733/36cfbf5e-96bc-11e6-9139-ff286f9d9919.png)
The space selected should be under the table. Check for all tables.

**Comment by keegan-o** [comment]
This is because the table is 4x4, not 2x4-- so I have the front clamp facing out. But I agree that the art should be changed so it's 2x4, probably.

**Comment by metachronism** [comment]
placement of world objects in general needs a lot of love

**Comment by johnkslg** [comment]
@keegan-o are you able to change the occupancy values?  Or is that @craig-jong

**Comment by keegan-o** [comment]
Yeah, I can change them in the tech tree. I'll change the art on the workbench so it's 1x2 instead of 2x2. (If I changed the occupancy w/o doing that it'd clip into walls etc)

**Comment by keegan-o** [comment]
Committed the workbench, will check the others.

**Comment by keegan-o** [comment]
I have gone through and done a pass on occupancy for world objects and fixed a bunch of stuff, will keep an eye on it as it is committed/pushed in.
