### ISSUE TITLE
Request: Shadow in First Person

### ISSUE THREAD

**Issue by Macludde** [StrangeLoopGames/EcoIssues#6280]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Be in first person mode
2. Have shadows on max (to see it clearer)
3. Stand in light and look down

**Expected behavior:**
Shown a player shadow

**Actual behavior:**
Didn't show anything because the player model isn't loaded. Shows in third person.

**Comment by SeanAtr0n** [comment]
maybe someday, it's not as easy of a thing to add as you might think

**Comment by keegan-o** [comment]
Anything I would do to address this would be hacky and probably wrong, though I can certainly guess about how it would be done-- un-assigning self.

**Comment by IcedForge** [comment]
Duplicate/related issue  to as with an avatar addition, this would naturally be fixed. #16871
