### ISSUE TITLE
USER ISSUE: Leaving excavator movement bug

### ISSUE THREAD

**Issue by DodgeEco** [StrangeLoopGames/EcoIssues#6281]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Leaving the excavator ( not always) especially when all fuel was just consumed

**Expected behavior:**
leaving the excavator and behing able to move in any direction

**Actual behavior:**
When leaving the excavator looking left or right doesnt work anymore (but mouse still moves on esc and map etc, need to relog to fix the issue

**Comment by MarjieAVolk** [comment]
A second report of this also said it was related to exiting when out of fuel.  They mentioned they were still holding down the mouse button.

**Comment by SeanAtr0n** [comment]
fixed in next hotfix build
