### ISSUE TITLE
Second task on mining tutorial is blank.

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#6282]
Couldn't capture screenshot in time, but the tutorial listed two tick boxes, only the first task had text, the second was blank.

**Comment by Nanders** [comment]
![image](https://user-images.githubusercontent.com/6262198/37617959-d24528b6-2b71-11e8-8ddb-bbdb71206690.png)

**Comment by johnkslg** [comment]
Fixed
