### ISSUE TITLE
Sometimes tutorial will not register as complete 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#6283]
![image](https://user-images.githubusercontent.com/6262198/37617850-88ea2798-2b71-11e8-8fdc-1f3da0e98f13.png)
I have completed all tasks, but this won't show as complete

**Comment by Nanders** [comment]
Persists after toggling/selecting other tutorials and returning.

**Comment by johnkslg** [comment]
Fixed
