### ISSUE TITLE
USER ISSUE: Multiplayer Connection bug (LAN)

### ISSUE THREAD

**Issue by zpdc10** [StrangeLoopGames/EcoIssues#6285]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Host a windows server on LAN
Port Forward
Try to join from a different PC on the same network
Unable to connect

**Expected behavior:**
i sohuld be able to join the server

**Actual behavior:**
Others, on different networks can join, but i cant connect to the server on LAN

**Comment by MarjieAVolk** [comment]
The first thing I would suggest is, in your server window under the Network>Config tab, to disable 'DetectNAT'.  That's usually responsible for not being able to connect on LAN, although we have tried to reduce these problems as much as possible.

**Comment by MarjieAVolk** [comment]
Closing due to no response.  I can keep giving advice if you need it.
