### ISSUE TITLE
USER ISSUE: no way to connect friend via steam

### ISSUE THREAD

**Issue by danilsolo** [StrangeLoopGames/EcoIssues#6286]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
trying to connect

**Expected behavior:**
connect game

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
If you are trying to connect using steam's Join button or via friend invitation, maybe instead try connecting directly, either by searching for the name of the server on Eco's Join screen, or by adding the server by ip address.

**Comment by MarjieAVolk** [comment]
Does that let you connect?

**Comment by MarjieAVolk** [comment]
Closing due to no response
