### ISSUE TITLE
SaveFrequency default setting in Stoarge.eco issue

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6287]
When savefreguency in Storage.eco was changed from minutes to seconds then default amount of 60 was not adjusted.  This means that games are auto saving every minute but default.  We are seeing more and more server that have gotten to where autosaves are exceeding this time and causing db lockups, and crashes and when they crash while saving they end up missing parts of the save. (seen saved worlds isising 1 to numerous folders and unable to load)

Could the default config file be adjust to perhaps 300 seconds so that players that do not know to adjust this themselves don't have issues with it?

**Comment by MarjieAVolk** [comment]
Saving shouldn't affect the db at all, that is a separate issue.  I am not sure about the crashing.

**Comment by pamduncan** [comment]
This is not the db isue this is about thesave to  .eco issue that is causing game lag :)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#194
