### ISSUE TITLE
Sidepanels on minimap open in different ways

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#6288]
![image](https://user-images.githubusercontent.com/6262198/37621198-79184318-2b7b-11e8-9484-cb17444d46ec.png)

This should be normalized, I didn't even know it opened a second side panel until poking around

**Comment by Nanders** [comment]
I prefer the option on the right

**Comment by MarjieAVolk** [comment]
What, there's another pull out over there?
