### ISSUE TITLE
Single player server generation freeze at loading screen

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#6289]
When generating a new world for single player server. 
Generating stays at loading screen indefinitely. No error message.

Windows 10
i5 2.20ghz
4gb ram
nvidia 920M

**Comment by GophTheGreat** [comment]
+1 from the support queue:

Operating System: Windows 10 64 bit
Prozessor model: AMD FX™-6300 Six-Core Prozessor 3.50 GHz
Graphics Card model: Nivida G-force 1070
RAM: 32 GB
Game Version .  eco (7.2.5)

PS: when i wont start a singleplayer then dont stop with load the world. I try wait 2 houers and load and load. But noting stand wat is loading.
