### ISSUE TITLE
Please add a player interaction event

### ISSUE THREAD

**Issue by lordmampf** [StrangeLoopGames/EcoIssues#6297]
If multiple mods are overriding the OnActRight method of the same WorldObject there will be a problem.
You have to merge the code from both mods, so they are working together. -> Admins can't do that ;)
For example two mods are changing the OnActRight of an WoodSign.

Are there any plans to improve that?
My idea is to add an player interact event where you can hook into.

**Comment by MarjieAVolk** [comment]
You shouldn't override OnActRight for a WorldObject if at all possible.  You should put that behavior in a WorldObjectComponent and put that component on the object.  WorldObject.OnActRight will call OnActRight on all of its components.  Does that help?

**Comment by lordmampf** [comment]
Sorry, I'm a little bit confused ;)
Should I loop through all Objects and then use AddComponent(...) ?
Because components aren't static.

And I have the same problem for items, too :P

**Comment by MarjieAVolk** [comment]
You should use the RequireComponentAttribute.  Add another one to the world object file - or better, create a new file with a new partial definition of the world object class, and add it there.  The component will automatically be added to all new and existing objects.

**Comment by MarjieAVolk** [comment]
RequireComponentAttribute can also be put on WorldObjectComponents if they have a dependency on another component.  Then any component that requires one will also be given the other.

**Comment by lordmampf** [comment]
When I use component, the user of the mod has to merge RequireComponentAttributes, too.
Or is there another possibility?

**Comment by MarjieAVolk** [comment]
That's what the partial class would be for.  So you can have it in a separate file.  In order for the partial class to work though, it has to be in the same assembly and namespace as the original file.

**Comment by lordmampf** [comment]
OK I understand. You don't want to add something like a interaction event. ;) 
For me partial classes are useless, too. Because mods are in different assemblies.

And also my opinion is adding a component to add an onClick event is overkill.
I don't want lots of small object in C# because of GC.

But Thank you very much for your answers. The idea with partial classes sounds very good for the first seconds ;)

**Comment by MarjieAVolk** [comment]
I am not super knowledgeable about our modkit, but I checked with the team, and it sounds like as long as you make the partial class be a standalone .cs file (not in a dll), they will get compiled into the game's assembly, so it should work.
