### ISSUE TITLE
Chopping fail

### ISSUE THREAD

**Issue by aleith** [StrangeLoopGames/EcoIssues#63]
alpha 3.0, Mac OS X 10.10.5

not sure if its because I was using a Wacom and stylus but chopping didn't work for about ten minutes. I went and got a mouse and eventually it started to work. Trees were indicated in green outline mode as targets and chopping animation and even sounds happened but no timber.

I screen-captured for posterity.
https://dl.dropboxusercontent.com/u/1585739/watch-me-chop-a-tree-not-wtf-480.mov

**Comment by klimSLG** [comment]
Based on ax animation from your video it looks like your stylus is giving several click instead of one long click(pressing).
All the tools working with keep pressing left mouse.
