### ISSUE TITLE
Coin Generation Glitch

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#6300]
From a Discord DM:

![](https://cdn.discordapp.com/attachments/424471670854778892/424471716715167744/20180317003425_1.jpg)

So found a little glitch. Apparently if you give access to a box via contract with a  negative depost it just creates the money. Then if you cancel the contract, the money just gets added to the money supply

Yeah, wanted to give you guys the clearest picture
what I missed
Was that previously I had the screen up and then I minted 1 bar for new coins
So it actually said 4980 EcoCoins, and M007368 had his 10564
That probably would have been a good picture to have as well.

**Comment by Nanders** [comment]
Can also just set contract as "Payment upon completion", Set the currency to any currency that you want, and set the payment to any negative value that you want. Free money of any kind.

**Comment by johnkslg** [comment]
Fixed, prevented negative payments/deposits
