### ISSUE TITLE
Pipes and stoves not actually connected

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#6302]
From the support queue: 

As shown in the picture 1 stove is connected to the pipe. However, if you open the tab "pipe" in the settings of the stack, then we see that the system persistently tells us that the device is NOT IN CONNECTED (picture 2) and all the pollution produced by it accumulates in the room where the device is located. Moving or reconnecting stove does not give any results. Accordingly, in statistics, these data are not taken into account. 

![20180318123140_1](https://user-images.githubusercontent.com/13459026/37632977-a3cfc928-2b94-11e8-9b99-f78a882f9c29.jpg)

![20180318123158_1](https://user-images.githubusercontent.com/13459026/37632990-b03741be-2b94-11e8-8a4d-eee55c11e95a.jpg)

**Comment by Twelve57** [comment]
#6176 I've got the same issue.

**Comment by MarjieAVolk** [comment]
Fixed in 7.3 (https://github.com/StrangeLoopGames/EcoIssues/issues/5805)
