### ISSUE TITLE
SERVER ISSUE: Crash

### ISSUE THREAD

**Issue by MrSiB** [StrangeLoopGames/EcoIssues#6307]
Приложение: EcoServer.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: LiteDB.LiteException
   в LiteDB.LockService.Write()
   в LiteDB.LiteEngine.Transaction[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, Boolean, System.Func`2<LiteDB.CollectionPage,Int32>)
   в LiteDB.LiteEngine.Insert(System.String, LiteDB.BsonDocument, LiteDB.BsonType)
   в LiteDB.LiteCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon)
   в Eco.Simulation.WorldLayers.WorldLayerStats+<>c__DisplayClass0_0.<CollectStats>b__0(Eco.Simulation.Types.Species)
   в Eco.Shared.Utils.EnumerableExtensions.ForEach[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Action`1<System.__Canon>)
   в Eco.Simulation.WorldLayers.WorldLayerStats.CollectStats()
   в Eco.Simulation.EcoSim.CollectStats()
   в Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(System.Action)
   в Eco.Simulation.EcoSim.DoTick(TickSample)
   в Eco.Simulation.EcoSim.Run()
   в System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   в System.Threading.ThreadHelper.ThreadStart(System.Object)

**Comment by MarjieAVolk** [comment]
I'm guessing this is a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5343

This should be handled better in 7.3
