### ISSUE TITLE
USER ISSUE: join game

### ISSUE THREAD

**Issue by matmooss** [StrangeLoopGames/EcoIssues#6308]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
try to join game

**Expected behavior:**
game cras some times never conect 

**Actual behavior:**
connection failed

**Comment by MarjieAVolk** [comment]
Here are a couple of things you can try:

* Try connecting directly by entering the server's IP address in the 'Join' screen
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software

**Comment by MarjieAVolk** [comment]
If all three of you are playing on the same network, you could try disabling the server's 'DetectNAT' setting.  This can be done in the server's settings window.  If you don't have the window open, while running the server, enter /openserverui.  In the window, go to the Network tab, select Config, and set DetectNAT to false.

**Comment by matmooss** [comment]
hi ive tried turning detect Nat only worked on standing  1c5d112f thought
we war good  but after 4 hours reece was kicked by sever and now could not
log back in gave up at that point next bay no one could log in to sever
game client crash as its about to start in would with no crash report just
windows saying it  it had to report problem  to Microsoft then in a new
window a problem caused the program to stop working correctly and windows
will close   program  tried reset sever all new tried new and older Vinson
and reinstall base game  to no change still get the same result i now
extremely confused

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_5984996471326904542_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MarjieAVolk** [comment]
If Windows is closing the program, is the issue because of your firewall?  Try disabling your windows firewall and any anti virus software.  If that allows you to connect, you can set up an exception in those programs for Eco.

**Comment by matmooss** [comment]
turned of fire wall on all 3 pc tried and even turned of avast thirst thing
i tried then verified game files and then tried dict down load as well to
now effect  i tried  new up date reece coneted to old game but on one got
skill points started new wold and now change to settings on pc  reece
cannot conet again  then tried sever  this time it told me that a
unauthorized player was connecting then player has been idle 30 second and
is being disconnected so if we can connect it wont do it a second  time and
only 1 out of 50 attempts works doing a complement reinstall  of system  up
grading to ryzen 5  hope this mite help withe clean windows 10

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
