### ISSUE TITLE
[Suggestion] Mid to Late Game Non-Stockpile Storage Items

### ISSUE THREAD

**Issue by Huntermeign** [StrangeLoopGames/EcoIssues#6310]
Putting Items in chests is cool and all, but toward the mid to late game some items may have been over produced or maybe you just want to carry items around in bulk without the tediousness of unpacking and repacking everything into a cart to bring to a new spot just for storage. Boxes are an item that can be easier to transfer. Late game food production is also a thing being planned.

Sollution: The Box for items and Bag/Sac for food would be for this.

Boxes and bags

- Create Boxes/bags with boards/cloth with weight limits. Does NOT stack.
- Acts like a chest, only when picked up with items in it, the items stay in it and are carried in the Carry item slot.
- Can put several boxes/bags in carts to transfer.
- Can put onto Pallets
- Boxes/Bags with items in it cannot be placed in chests.
- Whitelist Items to be stored in boxes if desired.

![download](https://user-images.githubusercontent.com/4082137/37660149-1c5f9df8-2c28-11e8-9df1-bbbee0df2efb.jpg)

Pallets.

- Can store 27 Boxes/sacs. 3x3x3
- Can be placed on other FULL pallets
- Can be easily moved for storage using Pallet Jack
- Can also store other stockpile items (except dirt and sand. That would be silly) 

Pallet Jack

- Can move Pallets similar to Carts.
- Used to move large quantities of items without having to pack and unpack
- Can store pallets in Pallet Rack (making it ideal over Carts for short distances)

![product_image_10-3](https://user-images.githubusercontent.com/4082137/37663706-2ce5dd60-2c30-11e8-9fd5-183e9378e519.jpg)

Pallet Rack

- Large item. 9x3x6
- Stores Pallets that automatically move pallets to lowest rack when pallets are taken out, similar to stockpiles.
- User Interface different than normal storage items. Each of the 6 pallet sections has its own UI which shows the contents of up to 27 boxes, the pallet limit. and option to put box in carry item inventory.

Alternatively, another option would be to just get rid of chests in favor of boxes, or to treat chests similar to above since all we really do now is stash a bunch of chests near a store/work table so we can sell/use the items and being able to carry a chest with its contents would be desired. All I know, is these days people only use chests as a hope chest, or to store clothes in the attic.

**Comment by MarjieAVolk** [comment]
Hey, sounds a lot like our crates idea!

**Comment by Huntermeign** [comment]
Was that in the Roadmap and I didn't see it?

**Comment by MarjieAVolk** [comment]
No, it's something a small faction of slg employees was pushing for :P

**Comment by Huntermeign** [comment]
Well I can vouch for a lot of players on the server I admin on by saying items like this would be appreciated

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#193
