### ISSUE TITLE
USER ISSUE: Delete Favorites

### ISSUE THREAD

**Issue by annoxoli** [StrangeLoopGames/EcoIssues#6311]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Start Game
2. Click on "Join"
3. Add a Server...
4. Insert IP
5. Add.

**Expected behavior:**
A Button / Selection to delete Favorites

**Actual behavior:**
Nothing.

**Comment by MarjieAVolk** [comment]
So the server shows up in favorites, but you can't remove it?

The star icons on the left side of the server listing are how you favorite and unfavorite things.  But the servers may not be added/removed from the favorites list until you hit Refresh (or leave and come back).  Does that help?

We are currently working on a big redesign of the server browser, which should improve this issue as well.

**Comment by annoxoli** [comment]
I'll take a look later,

However, my behavior is, a small button on ervery record, to delete my favorites or a CheckBox to "Delete all selected" - or "Add selected to Favorites" (for Public Server).

**Comment by MarjieAVolk** [comment]
I mean, unchecking the star toggle is going to be easier than selecting a different toggle and then also having to click a button to remove it from favorites, right?

**Comment by MarjieAVolk** [comment]
Okay, well I'm going to close this for now, partially because I'm not sure what you are asking for, and partially because we are already working on a rewrite of the join server screen.  I will keep in mind making favoriting and unfavoriting clear and easy as I work on this.
