### ISSUE TITLE
[Suggestion] "Do Backup Now" through a batchfile

### ISSUE THREAD

**Issue by Ekkelus** [StrangeLoopGames/EcoIssues#6314]
I'd really like to see the option to send a "Do Backup Now" command through a batchfile.
Reason for this is that I would like to auto restart the server at specific times and before it gets restarted I'd like to do a backup. I think that would be a great feature for server owners.

**Comment by metachronism** [comment]
you can send 'exit' to stdin on the process and it will save and close
