### ISSUE TITLE
Nop' Bug

### ISSUE THREAD

**Issue by MrTrofort** [StrangeLoopGames/EcoIssues#6315]
I have buy eco and when I start the game all is normal ,  when I creat new map it's looks OK but the I can't charge any maps and multiplayer dont charging, . So for resume I cant play, it's litlely embarasting (JUST litely).

If you can help me please contact me.

**Comment by MarjieAVolk** [comment]
I'm not sure if I understand what your problems are.  You are able to play one local game, but you can't create another local game?  And you also can't connect to any multiplayer games?  What error messages are you seeing?

**Comment by MrTrofort** [comment]
So the bug is : 
I double click on a map --> It's charging --> it's return to windows (like a alt tab) --> When I return to the game it was return to the charging menu.

**Comment by MarjieAVolk** [comment]
Okay I see.  Sounds like your server is failing to start up.  Could you send me your server dump files?  They should be in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump' .

**Comment by MrTrofort** [comment]
no error message and I nether connect to any local game.
I will try to describe:
So the bug is :
I double click on a map --> It's charging --> it's return to windows (like a alt tab) --> When I return to the game it was return to the charging menu.

**Comment by MarjieAVolk** [comment]
Yes I understand, I'm asking for you to look for crash files on your computer.  They won't necessarily have been displayed on screen.  You should be able to find the Eco folder in steam by going to 'Browse Local Files'

**Comment by MrTrofort** [comment]
ok

**Comment by MrTrofort** [comment]
I have no ''Dump''.

**Comment by MarjieAVolk** [comment]
Hm okay.  In that case, is your firewall or antivirus blocking the server from running?  Maybe the game is minimizing because the computer is trying to show a confirm popup?

**Comment by MarjieAVolk** [comment]
What do you mean, when you launch the game without connection?  Have you tried disabling your firewall and anitvirus?
