### ISSUE TITLE
Teleported up while standing on ramp

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#6317]
sometimes you get teleported about one block upwards if you stand on a ramp and mine something.
teleport on ramps when mining
![image](https://user-images.githubusercontent.com/37247290/37670698-404b466c-2c6a-11e8-9de9-259c08a5ea6c.gif)

**Comment by SlayksWood** [comment]
Seems fixed with avatar, but still have another issues with rubbles #12888.
