### ISSUE TITLE
USER ISSUE: Takes minutes to access chests or anything else with items in it

### ISSUE THREAD

**Issue by LuigiTheHunter** [StrangeLoopGames/EcoIssues#6319]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Just click any chest e.g.

**Expected behavior:**
It should appear directly	

**Actual behavior:**
Im waiting 10 seconds at least

**Comment by MarjieAVolk** [comment]
Does this happen on all servers?  Sounds like the server you are on might have lag or a high ping.

**Comment by LuigiTheHunter** [comment]
Yes, and Its a localhost ping < 10ms

**Comment by metachronism** [comment]
offloading to marjie who is looking at this particular issue (UI perf) right now

**Comment by MarjieAVolk** [comment]
Fixed in next major release
