### ISSUE TITLE
Client bug Unityplayer.dll access violation

### ISSUE THREAD

**Issue by jayates1995** [StrangeLoopGames/EcoIssues#6320]
**Client** 
**O/S** - Windows 10 64bit
**Description of Issue** - The game plays fien for around 5 minutes then crashes with the log and dump file saying that an access violation has been caused by "UnityPlayer.dll".
**Reproducible** - I am able to reproduce this fault everytime, not sure what initially caused it as the game ran fine for afew days prior. 
**Steam Build ID** - 2607698

**Additional comments**- I have attached the error.log file to this post to make it easier to understand the nature of the fault. The .DMP file can be given if needed. 

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1830939/error.log)

**Comment by MarjieAVolk** [comment]
This seems to be a bug in Unity.  We are hoping to update to a new version of Unity, which might resolve the issue.  Others have reported this going a way when they:
* Decreased graphics settings in Eco
* Updated their drivers
* Uninstalled GeForce Experience

Let me know if that helps.

**Comment by jayates1995** [comment]
Uninstalling GeForce Experience and decreasing the settings seemed to
increase the amount of time I could spend in game from 5 to 10 minutes but
the game still crashed with the same reason. I also reinstalled my windows
to see if this would rectify the issue however this didnt work either.
Hopefully this will be fixed with the new version of Unity so I can get
back to playing!

**Comment by MarjieAVolk** [comment]
Sorry the issue wasn't solved.  7.3 is coming out today, let me know if you have better luck on that version.
