### ISSUE TITLE
Store chat in pages to disk, instead of keeping fully in memory

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#6323]
All chat messages are kept in memory all the time, forever.  Over time this grows to a massive amount of messages when 99% of them are never accessed or used.

optionally also change chat to be saved in the db, instead of in storage

**Comment by MarjieAVolk** [comment]
I'd been planning/hoping to move chat to the db, although I'm reluctant to while the db is having so many problems still.

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/14980
