### ISSUE TITLE
Mint Causing Game Crash

### ISSUE THREAD

**Issue by MayoChan** [StrangeLoopGames/EcoIssues#6324]
So in my world we had a law that prevented creation of another mint in the world while one existed. Well, when I went to go to create more of our currency, I crashed but what I noticed is the Currency Name was blank yet by hitting Y it showed the currency was still circulating and working in the world. This may be possible that removing the walls and making it no longer working properly for being out of a room, may have caused this bug. We have attempted to remove all laws associated with it and then it even allowed renaming another currency the same name. 

File for the db and eco are to large even in compression. Here is an open dropbox. Please feel free to contact me to email one at a time perhaps. 
https://www.dropbox.com/sh/9rt0kvbhdl6029x/AAC_m0t3OXkW2UNSbUeRlG1Za?dl=0

**Comment by MarjieAVolk** [comment]
Thanks for all the details and attaching the save files.

**Comment by WeaselDog** [comment]
I haven't been able to reproduce this is in the latest version with the new law system.  Please let us know if you experience this issue again.
