### ISSUE TITLE
USER ISSUE: Cant login

### ISSUE THREAD

**Issue by SamuraiOctopi** [StrangeLoopGames/EcoIssues#6326]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
When server is set to Nat = True, I can't get on my own server. But friends can get on it at other locations. My own comp and my other home comp on the same network cant connect... 

**Expected behavior:**
All should be able to connect	

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by metachronism** [comment]
you'll have to add your server manually, via the internal IP, as some routers don't correctly route back to themselves

**Comment by SamuraiOctopi** [comment]
Oh hello, Im sorry I forgot I put this ticket in. Thank you for your response, I got help on the Eco discord from Pam! They are awesome!! Thank you too. :]
