### ISSUE TITLE
USER ISSUE: Contract active on a player but deleted crash

### ISSUE THREAD

**Issue by bruteman** [StrangeLoopGames/EcoIssues#6327]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Create a Contract
2. have anouther player accept the contract
3. Delete the Contract
4. Other Player tries to finish contract 
= Crash

**Expected behavior:**
Deleting a contract should have cancelled all active contracts. or it should just delete any remaining repetitions and left it active till the others were completed but no more could be issued.

**Actual behavior:**
Exception Error i missed copying to clipboard

**Comment by johnkslg** [comment]
Fixed
