### ISSUE TITLE
Waterwheel Placement [0.7.3.0 staging-eb6e4ece]

### ISSUE THREAD

**Issue by PillowyGiant** [StrangeLoopGames/EcoIssues#6329]
Having some problems with the waterwheel placement in 'staging' 
Unable to place it in the water anymore. Can place on the side of a hill thats not close to the water/river though. 'Can't place there, Blocked'

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/2105

**Comment by Thineboot** [comment]
0.7.3.2
tested in water: works
tested rotate: works
suggestion: auto-rotate to match water flow

tested in inland: works... generates mechanical power out of humidity ;) - bug
tested in(!) stone road: you can place so it in massive blocks, still rotating and generating power - bug
![ecowaterwheel](https://user-images.githubusercontent.com/4364842/38419882-53710fca-39a2-11e8-9c52-9874615d0128.png)
tested a block below: also placeable - bug
tested hub above ground: not placeable - as expected

**Comment by D3nnis3n** [comment]
Closing to merge with #2105
