### ISSUE TITLE
USER ISSUE: Laws/voting breaks the servers

### ISSUE THREAD

**Issue by AndyofBorg** [StrangeLoopGames/EcoIssues#6330]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Submit a law, have people start voting on them, the server will begin to lag severely and usually eventually crashes. It appears to sometimes take just 1 law, or sometimes more than one law. The web browser also seems to have problems with lag and voting errors.

**Expected behavior:**
Web browser should not give generic "An error has occurred" when voting, and it should not lag/crash the server to heck.

**Actual behavior:**
Lags the server or crashes it.

**Comment by bruteman** [comment]
We also have had 2 server crashes related to opening up the laws and trying to vote create laws attached server crash dmp files.
[Eco laws crash files.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1834412/Eco.laws.crash.files.zip)

**Comment by MarjieAVolk** [comment]
Okay I realized this is probably the same as https://github.com/StrangeLoopGames/EcoIssues/issues/5343, which we have fixed for 7.3.  We just did a stress test with some voting and database spamming and it looks good now, so hopefully fixed in 7.3
