### ISSUE TITLE
USER ISSUE: Delete sand/dirt

### ISSUE THREAD

**Issue by DubsTheFox** [StrangeLoopGames/EcoIssues#6336]
**Version:** 0.7.2.5 beta

If you dig into dirt/sand and change the tool right after you received the dirt/sand it just disappears and doesn't end up in the inventory
![zeh bug i found](https://user-images.githubusercontent.com/37247290/37706736-dbd393e6-2d00-11e8-8590-71a8ccac1ff5.gif)

**Comment by elfl0rd** [comment]
Looks fixed (i cannot repro this)

**Comment by GophTheGreat** [comment]
Can't reproduce, closing.
