### ISSUE TITLE
Feedback technology should be included in game - future of farming

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#6339]
Green house that was built that they want UN to invest in more of them, turns salt water into fresh water 
at cost of 50 litter bottles for couple cents 
saltwater greenhouse also produces food, said to be answer to Africa in ability to grow food due to climate

..  if this is learning game might be good to have technology that is in works to solve world issues in it ?

http://www.wired.co.uk/article/charlie-paton-seawater-greenhouse-desalination-abu-dhabi-oman-australia-somaliland

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#192
