### ISSUE TITLE
USER ISSUE: orders stuck in masonry table

### ISSUE THREAD

**Issue by idontwanttogiveyoumydata** [StrangeLoopGames/EcoIssues#6342]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
place order for mortared stone at masonry table

**Expected behavior:**
auto deposit in stockpile

**Actual behavior:**
completed but uncollectable orders stuck in masonry table despite viable stockpile connected

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3240

This will be fixed in 7.3
