### ISSUE TITLE
World Markers freak out when moving

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#6343]
![bug](https://user-images.githubusercontent.com/6262198/37729952-9dba5d1a-2cfb-11e8-8a79-7140d346dfff.gif)

**Comment by johnkslg** [comment]
Cant repro this, need a demo

**Comment by johnkslg** [comment]
I moved the position update to Late Update so lets see if that helps.

**Comment by Nanders** [comment]
Not hard to reproduce, might need to do it in release, happens with every world marker
