### ISSUE TITLE
Cannot accept or post "Mow Lawn" Contract

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#6346]
I have a valid contract for lawn mowing, I cannot post it.

/Testcontracts creates a mow lawn contract that also cannot be accepted.

**Comment by johnkslg** [comment]
Cannot repro either, need to see the failure message.  I think there is something unrelated going on preventing failure messages from appearing.

**Comment by Nanders** [comment]
was related to #6351
