### ISSUE TITLE
Need text limit on messages

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#6349]
![image](https://user-images.githubusercontent.com/6262198/37736337-e601678c-2d0d-11e8-8a7f-5b0968b3039b.png)

**Comment by MarjieAVolk** [comment]
I tried posting a whole wikipedia article into chat just now, and while it took some time to load, it displayed fine.  Fixed I guess?

**Comment by MarjieAVolk** [comment]
![image](https://user-images.githubusercontent.com/23460210/43662414-bc4e27fa-971a-11e8-928d-b6c803dd7f15.png)
