### ISSUE TITLE
Contracts should tell you when your contract is failing / incomplete

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#6351]
And why, if possible.

Even if its just "Could not mark as complete, contract not fulfilled" Rather than doing nothing when you click 'mark as completed'.

**Comment by johnkslg** [comment]
Not sure what you mean, it displays a dialog box with full details:
![image](https://user-images.githubusercontent.com/3536496/37803760-fc63bbc0-2ded-11e8-8bce-4ff5bc0979bc.png)

**Comment by johnkslg** [comment]
Cant repro this, if you can help me repro it in a debuggable environment that would be tres helpful

**Comment by Nanders** [comment]
Might very well be something that only happens in release, not debug
