### ISSUE TITLE
Lategame needs a serious rebalance / overhaul

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#6352]
After we now played through the entire current content / game three times i'd like to give some feedback on the current lategame and (in my opinion) serious balance issues and with the way it's currently implemented as well as some suggestions that could make it better.

The main problem i've seen all three times with my server is, that the whole game currently "forces" you to switch from a game where there is plenty of things to do in early/midgame (building houses, expanding houses, rebuilding to be able to run tier 2 crafting stations, lots of materials needed) but that whole pattern somewhere gets totally lost in lategame. Around the time you get steel / tier 3 it currently feels like all the following tech / skills have just been thrown into the game without any logic behind them.

In the end while i always had like 20 online players in early/midgame during prime playtime, people just login in lategame, invest skillpoints and wait for tech to be available just to make more tech until you have the lasers active. There is no more need to actually play the game, no more massive need of ressources like in midgame.

- There is NO need to build any tier 3 / tier 4 as nothing needs them to be used except 2 furniture. But at the time you unlock them people already have max housing SP with only tier 2. Why do the higher crafting tables not follow the midgame pattern of needing higher tier materials to be operated ? Why doesn't housing SP follow the pattern of food that you need higher tier materials / higher tier furniture to increase max housing SP ?

- The game is about not causing an ecological disaster. Only having renewable energy sources (wind, solar, water) just seems wrong in a game like that. Those should only produce minor amounts of electricity while coal power plants should be the main source. I could even imagine something like a nuclear power plant where you have to solve nuclear waste disposal problems (similar to tailings) or even nuclear accidents as a lategame option, but Wind/Solar/Water just feels missplaced in a game like that.

- Engineer tree is the only tree with a lategame at all. Every other job just does the same over and over again from mid- to lategame with nothing new. They just sit around and wait for engineers to get the skillpoints to build them an excavator maybe, or some nice street lamps or whatever, but they totally lack any lategame content. 

- Wood for example really fits nice into all the crafting until midgame, but it just totally stops to be used then. There's no tier 3 / tier 4 made of wood, no components, it's just a job & resource that is no more needed in lategame.

- I would guess farming could become pretty nice once all the vehicles are implemented, but with the current system i see little benefit for it. There's too little need to increase food/ingredient production and every vehicle that can be used to replace a job previously done by hand (mining, digging, etc.) will just lower the need for food at all as well as better calorie usage skills. What's the point in playing a farmer when it just ends with farming a field once per week and having enough resources to easily feed 30-40 people for a week with the best available food ?

- Efficiency Skills: While i really liked the idea of those skills for maybe my first 200 hours of playtime, in the end all they are is just a timesink. Don't craft stuff until you maxed it, sit around and wait. It's fun when you skill Lumbering or any other low-SP skilltree but it's definitly no fun or any gameplay-benefit in lategame skills when you either have the choice of wasting a ton of resources or better wait another 3 days to have SP for eff.5 after you already waited 3-4 days to buy the specialization itself before you even craft the first thing with it. Gameplay/fun wise i would tend to say it would be better to lower initial resource usage and decrease the benefit from efficiency skills a lot so it makes sense to craft things while you're not having efficiency but still have a benefit when you have them finally.

- Speed Skills: More or less the same as with efficiency. While i guess that they are crucial for singleplayer, they just seem to be too overpowered in multiplayer especially to extremely lower CO2 emissions. Furnaces / etc. should be forced to run at least 12/24 hours a day and not only like 1 hour per day to easily fullfill all resource needs. Emission are already pretty low compared to what all the plants on a standard sized map can recycle but it's just impossible to create any noticeable emission on a server even with dozends of machines & players when they only need to run a fraction of the time per day. 

- Maximum speciality costs: Imho the cap for spec costs not increasing anymore after the 8th is totally counterproductive in multiplayer. Everyone that just waits for the few engineers to skill the final trees has nothing to do with his skillpoints except learning specialities that remove their dependency from other players so with time going by instead people working more and more together, the opposite is happening. Being able to adjust speciality cost multiplier is not a real solution here as you either just implement a senseless early/midgame timesink by setting it higher to avoid that but can't prevent this issue in lategame. There really needs to be a setting to adjust at how many specialisations it does start to cap the SP needed for another as well as being able to set a hardcap for the maximum specs you can learn at all.

**Comment by johnkslg** [comment]
Great comments, thanks. We'll be adding lots more to this section of the game and will discuss these points.

**Comment by lightdrawn** [comment]
The major problem I see here, is the way skill points are gained, you get them for waiting/doing nothing at all. They should be way more related to playing activity, maybe even awarded by other players (given together with reputation).

And the housing bonus is mostly annoying to me the way it is, there are too many bugs, restrictions and confusing game mechanics. 
But I like the idea, that one would need Tier 4 building materials for the full bonus.

**Comment by xtreampb** [comment]
I would like to point out in the server config file, the difficulty config, you can change 2 of the settings so that you get skill points for doing tasks such as mining and crafting (each being their own values in the file).    This way you can gain strive to gain skill points.  In one game play session of just mining I can generate over 1000 skill points and that is with those two config values set at 0.1.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#191
