### ISSUE TITLE
Property Claims per research config

### ISSUE THREAD

**Issue by xtreampb** [StrangeLoopGames/EcoIssues#6353]
As a server admin I would like to configure the amount of Property Claims given to a player after researching technology.  I would like the government of the people to be able to set how many claim flags are awarded for researching.  Would also like to be able to set it via a config file so that the gov't will be able to issue claim flags how it sees fit, something like building permits.  Is it possible for a mod to hook into when a scroll was read, and remove the claim flags from the inventory?  Maybe have an admin "give" the server 500 Property Claims?

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#190
