### ISSUE TITLE
USER ISSUE: Sawmill Catch 22 loop

### ISSUE THREAD

**Issue by CiberX15** [StrangeLoopGames/EcoIssues#6355]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
-Anvil requires tier 2 room materials to work
-Lumber is a tier 2 material
-Lumber can only be made in the sawmill
-Sawmill can only be made at the anvil
While it is possible to use brick as a tier 2 material instead of lumber, it creates an unnecessary bottleneck and removes player choice.

**Expected behavior:**
Saw mill should be craft-able at the workbench or carpentry table, enabling two paths to tier 2 materials.

**Actual behavior:**
Saw mill cannot be crafted until the player has already built a brick structure to enable to anvil, making lumber construction obsolete before it is even unlocked.

**Comment by bruteman** [comment]
glass is also tier 2 were not finding it that difficult on a MP server.

**Comment by Huntermeign** [comment]
Bricks is also tier 2

**Comment by ecoemmeck** [comment]
Hmm the anvil kinda seems like an object that shouldn't have many if any restrictions regarding it's usage

**Comment by craig-jong** [comment]
Please make sure your server isn't modded in any way. I don't BELIEVE this changed from 7.2 -> 7.3, but in the current release version the anvil requires no room at all.

I'm going to close this issue, but if you're still experiencing this reopen it.
