### ISSUE TITLE
Can't Start A Government on my Server

### ISSUE THREAD

**Issue by christianbhill** [StrangeLoopGames/EcoIssues#6356]
So I started a new world with my friend and we are playing but we want to set up a government when our other friends join. So I click on run for office and it sends me to a web page. I click on run for office on the webpage and it does this 
![screenshot_1](https://user-images.githubusercontent.com/30854926/37748755-6cf65df4-2d5b-11e8-9596-be0bc1e3e1dc.png)
Any help?!

**Comment by MarjieAVolk** [comment]
So from that message, it looks like you are not logged in.  Have you tried going to this page via the buttons on the Government window in game?  That should ensure that you are logged in.

Right now, you can't log in directly on the website, so you have to open the page from the in game buttons for it to work.  We hope to add website login soon.

**Comment by christianbhill** [comment]
Marjie, I do open it from in-game, because its client side it has to. I'm not sure what to, I guess I am already logged in, and everything of mine is linked up

**Comment by MarjieAVolk** [comment]
Hm well all I can really suggest is to try closing the page and opening it from in game again.  Sending this over to the web team.

**Comment by rainfarmer** [comment]
hey @christianbhill what browser are you on?
Is this from Steam? You can try our website version of Eco, should work.
What version of the game?
Thanks

**Comment by elfl0rd** [comment]
Looks is not repro
