### ISSUE TITLE
Application exit takes long, app hangs for a while before responding to WIN

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6367]
Every time I quit the game, it takes a long time to return to Win OS. Also, alt tabbing into other windows is not possible. The app totally hangs (doing whatever it is doing).

Suggestion:
Either have proper feedback for the user, so the user knows what is happening, and why, or
speed up application closure. 

Usually a good app closes within seconds after the user hits ALT+F4.

![image](https://user-images.githubusercontent.com/37662083/37773512-17c36bd2-2dde-11e8-9045-081b2fbd68de.png)

Win 10 64Bit

**Comment by Huntermeign** [comment]
Ive noticed this when disconnecting as well

**Comment by metachronism** [comment]
should be fixed by now, but if not I have a few more fixes for some other cases of this in 8.0
