### ISSUE TITLE
Suggestion: Different forms of government

### ISSUE THREAD

**Issue by zEverdeen** [StrangeLoopGames/EcoIssues#6368]
I think it would be interesting to let the players themselves have a vote, in an effort to choose what type of government that they would like to be ruled by.

Obviously, we start in anarchy and end up somewhere.

Maybe a republic, maybe a president, who knows? Maybe there are two parties, maybe there are four?

**Comment by Huntermeign** [comment]
Laws are there to simulate this. The name is just what is used to give a general idea of how the government works. 

The only thing selecting a government would be needed for is if there were leaders in zones as opposed to worlds.

**Comment by ZeskaN** [comment]
Huntermeign, I think you are on to something, when you think about time zones, a big BIG server, and different governments for different timezones.

When I say governments, the way decisions are made are different. Are a certain amount of votes needed? or does the acting president have a lot of power on his own?

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#189
