### ISSUE TITLE
Server-List only functional on first open

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6369]
I cannot use the server list in the same session two times. 

My repro:
1. Enter server list
2. Return to main menu
3. Enter Server list
-> No refresh taking place. No servers shown. Empty list.

On my client it is 100% repro

Only way to fix it: Restart the game completely.

Win 10, 64-Bit
Internet Acces: IPv6 and IPv4 Dual Stack Lite

**Comment by MarjieAVolk** [comment]
The next time you see this, could you send me your log file? 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by Dreepa** [comment]
Initialize engine version: 2017.3.0f3 (a9f86dcd79df)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 970 (ID=0x13c2)
    Vendor:   NVIDIA
    VRAM:     4058 MB
    Driver:   23.21.13.8813
Begin MonoManager ReloadAssembly
- Completed reload, in  0.661 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Setting up 4 worker threads for Enlighten.
  Thread -> id: 27a0 -> priority: 1 
  Thread -> id: e50 -> priority: 1 
  Thread -> id: 2254 -> priority: 1 
  Thread -> id: 1c44 -> priority: 1 
UnloadTime: 2.884614 ms
RPC lookup took: 2891.4264ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout

**Comment by MarjieAVolk** [comment]
And that's after going to Join for the second time?  Hm well I dunno what is up.  This does not happen for me either.

**Comment by Dreepa** [comment]
Yes. I do not even need to join a server. I only need to open the server browser once. Entering the server browser a 2nd time during the same session will result in an empty server browser list. Though if it is only me affected, maybe the problem lies on my end.

**Comment by MarjieAVolk** [comment]
I wouldn't be too sure about that, there have been a lot of complaints about the server browser.  Which is why we are working on rewriting it.  So we will probably not fix this specific bug, but I will keep an eye out for it as I work on rewriting this screen.

**Comment by Dreepa** [comment]
The issue no longer is present consistently in 7.3.1
It now only happens rarely (and usually after some bugged connection like being stuck on "entering world" or having a lot of offline servers in the list).

**Comment by MarjieAVolk** [comment]
Well that's one good thing that's happened today :P

**Comment by MarjieAVolk** [comment]
7.4 will have a revamped Join screen, as well as server connection code.  So hopefully your remaining connection issues will be addressed.  Let me know if you have more problems after updating!
