### ISSUE TITLE
USER ISSUE: server listing

### ISSUE THREAD

**Issue by LuZiferdk** [StrangeLoopGames/EcoIssues#6371]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
i have been playing on a serve for som H yesterday and after a waild it shout down then tred to reconnect and i cutten find it not eving on the fev.list i just tryed to reconnect to a server and it failt then i see all my fev.listings reset to only 1 server the last 1 i tryed to connect to...i hope you can fix this problem....p.s. can yo add som sort off time playt on the server listings so you have a better change to see whits server you play on....

**Expected behavior:**

**Actual behavior:**

**Comment by pamduncan** [comment]
If your server is not showing in favorites list when you do 'add server' then you have a connection issue/ports issue/firewall issue.  We can help you troubleshoot that in discord.  If the server shows up in 'add server' then it will show up in the browser, usually might take a restart or two for the first time but once it shows then after that it will show up right away.  There are some issues with the browser and they are working on a new one but if your server will not show up with 'add server' it is not the browser but how you have it configures that is the issue and you need to step through some troubleshooting to get you online

**Comment by MarjieAVolk** [comment]
Okay, I talked to pam a bit about this issue.  Here are some suggestions:

* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software
* If none of those work, you might try nuking it all - Uninstall Eco, shut down Steam, delete the AppData folder, restart your computer, reinstall the game.

Let me know if those work.  If not, you might want to ask for help on discord, as pam said.
