### ISSUE TITLE
Could you re-generate a new "Default World" for SP games for next release

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6372]
I believe you know this because one of you said you planned to generate a new Default World for a previous release but not sure that happened.  The current Default World is having major issues, it either does not work at all or people are complaining of very bad amounts of resource or total lack of resources in the world.  The big thing is that we get many people that set up a singleplayer world and then cannot connect and get an error, but they can generate a fresh world and get in fine.  I was told this was an issue with the Default World and a new one would be generated but I guess that might now of happened as people are still getting this error.  If we could get a new Default World that people could connect to it would be great - thanks

**Comment by metachronism** [comment]
thinking this is wont fix for now - small worlds are gonna have different biome balances

**Comment by metachronism** [comment]
made a new world, has almost all species
