### ISSUE TITLE
USER ISSUE: connection failed

### ISSUE THREAD

**Issue by shadow239ju** [StrangeLoopGames/EcoIssues#6374]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
i was kicked from the server so i tried to rejoin but it keeps saying connection failed i am told by the admin that he didnt mean to kick me but was trying the commands out to see if they work 

**Expected behavior:**
it should let me rejoin

**Actual behavior:**
The following error message popped up:
```connection failled```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Are you able to join other worlds?  Here are some suggestions:

* Try connecting directly by entering the server's IP address in the 'Join' screen
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software

**Comment by shadow239ju** [comment]
i fixed it all i had to do was reinstall the game thanx for the help though
