### ISSUE TITLE
USER ISSUE: Log Placement

### ISSUE THREAD

**Issue by Ellislee1** [StrangeLoopGames/EcoIssues#6376]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. chop down tree
2. place logs near edge of cliff (mine was adjacent to water)
3. stack 

**Expected behavior:**
Logs should stack or not leave inventory if unable

**Actual behavior:**
logs left inventory and did not stack

**Comment by MarjieAVolk** [comment]
Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/5906

In which case, this will be fixed in 7.3
