### ISSUE TITLE
Bakery Oven doesn't pollute

### ISSUE THREAD

**Issue by PatrickG07** [StrangeLoopGames/EcoIssues#6377]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1.Connect Factory and Cement Kiln to iron pipe
2.Extend iron pipe up
3.Connect Bakery Oven ot it
4.Extend the iron pipe further up

**Expected behavior:**
The smoke shoud come aut of the end of the pipe

**Actual behavior:**
Instet it comes aut of the Bakery oven and the end of the pipe

![eco rauch 1](https://user-images.githubusercontent.com/22293838/37793815-fe408d34-2e0f-11e8-8338-7906610dd5a8.PNG)

![eco rauch 2](https://user-images.githubusercontent.com/22293838/37793828-0c8b9fc8-2e10-11e8-9f41-6fa43665b61a.PNG)

**Comment by ecoemmeck** [comment]
I believe at this current point and time both the pipes on the bakery oven and cast iron stove are just place holders there for won't be a start point for smoke / smog

**Comment by SeanAtr0n** [comment]
pipe ports are all fixed in 7.3 but bakery oven doesn't actually pollute so i'll leave this open for craig to fix
