### ISSUE TITLE
USER ISSUE: Cant play in Singleplayer

### ISSUE THREAD

**Issue by MarviBiene** [StrangeLoopGames/EcoIssues#6378]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Start Game
2. Click on Continue
3. Let the Game Load
4. Read the Error

The Pc Crashed before (Because of a Power failure)

**Expected behavior:**
It should have stardet the Game in Singleplayer. (Local Server should start)

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarviBiene** [comment]
Hello,

I wanted to add that the game minimizes when the error occurs

Have a nice Day

**Comment by MarjieAVolk** [comment]
Usually when the game minimizes like that, it is either that some kind of firewall/anti virus popup is trying to open, or the server has crashed.

Could you send me any crash files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'?

**Comment by MarviBiene** [comment]
Hello,

The Game worked perfectly before. So it is not the Firewall/Antivirus.

The Crash Dump:
`--BEGIN DUMP--
Dump Time
03/22/2018 22:30:47

Exception
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> Ionic.Zip.ZipException: Could not read Storage\World #1.eco as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x00000000) at position  0x00000000
   bei Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   bei Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   bei Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   bei Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   bei Ionic.Zip.ZipFile._InitInstance(String zipFileName, TextWriter statusMessageWriter)
   bei Ionic.Zip.ZipFile..ctor(String fileName)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Ionic.Zip.ZipFile..ctor(String fileName)
   bei Eco.Core.Serialization.DataStore.OpenZipFile()
   bei Eco.Core.Plugins.StorageManager..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Eco.Server.PluginManager..ctor()
   bei Eco.Server.Startup.Start(String[] args)
   bei Eco.Server.MainClass.Main(String[] args)
---> (Interne Ausnahme #0) System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> Ionic.Zip.ZipException: Could not read Storage\World #1.eco as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x00000000) at position  0x00000000
   bei Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   bei Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   bei Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   bei Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   bei Ionic.Zip.ZipFile._InitInstance(String zipFileName, TextWriter statusMessageWriter)
   bei Ionic.Zip.ZipFile..ctor(String fileName)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Ionic.Zip.ZipFile..ctor(String fileName)
   bei Eco.Core.Serialization.DataStore.OpenZipFile()
   bei Eco.Core.Plugins.StorageManager..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   bei System.Threading.Tasks.Task.Execute()<---


Inner Exception
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> Ionic.Zip.ZipException: Could not read Storage\World #1.eco as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x00000000) at position  0x00000000
   bei Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   bei Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   bei Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   bei Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   bei Ionic.Zip.ZipFile._InitInstance(String zipFileName, TextWriter statusMessageWriter)
   bei Ionic.Zip.ZipFile..ctor(String fileName)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Ionic.Zip.ZipFile..ctor(String fileName)
   bei Eco.Core.Serialization.DataStore.OpenZipFile()
   bei Eco.Core.Plugins.StorageManager..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Eco.Server.PluginManager..ctor()
   bei Eco.Server.Startup.Start(String[] args)
   bei Eco.Server.MainClass.Main(String[] args)
---> (Interne Ausnahme #0) System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> Ionic.Zip.ZipException: Could not read Storage\World #1.eco as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x00000000) at position  0x00000000
   bei Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   bei Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   bei Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   bei Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   bei Ionic.Zip.ZipFile._InitInstance(String zipFileName, TextWriter statusMessageWriter)
   bei Ionic.Zip.ZipFile..ctor(String fileName)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Ionic.Zip.ZipFile..ctor(String fileName)
   bei Eco.Core.Serialization.DataStore.OpenZipFile()
   bei Eco.Core.Plugins.StorageManager..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   bei System.Threading.Tasks.Task.Execute()<---


--END DUMP--
`

**Comment by lightdrawn** [comment]
I had a similar problem, turned out the save game for that map was damaged (possibly caused by steam update/restart), you could try to create a new map.

Maybe interesting for investigation, the last thing I did before steam update killed the game was opening the graphs in my browser with g, from in-game, so it was minimised when the task was killed. 
And it did always minimise again when I tried to load that map and gave me that Connection Failed error. 
Not sure what fixed it for me, maybe one of the hotfix or loading some other maps.

**Comment by MarviBiene** [comment]
Hello,

Is there a way to recover the world? Or is everything gone? 

Maybe they can add a Data Protection so the Data won't get destroyed when the game crashes.

**Comment by MarviBiene** [comment]
The problem is that the server don't start because of the error... With this problem I can not enter the server GUI. And when I'm loading the Singleplayer world, the server don't create a new logfile... So the server is not starting...

**Comment by MarjieAVolk** [comment]
Yeah that is a corrupted save file, unfortunately.  We think we have fixed this in 7.3 (https://github.com/StrangeLoopGames/EcoIssues/issues/4665)

As @lightdrawn suggested, the best thing to do will be to restore a backup.  Right now you have to just do this on the file system.  The backups are located in '[...]\steamapps\common\Eco\Eco_Data\Server\Storage\Backup'.  Find the most recent backup folder for your save, and copy all the files inside that folder out into the Storage folder, replacing the existing files.
