### ISSUE TITLE
USER ISSUE: I'm tuck in textures

### ISSUE THREAD

**Issue by Delaert** [StrangeLoopGames/EcoIssues#6385]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
I'm tuck in textures. Please help me. I already have a lot of progress in the game, don't want to start over

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Can you please explain what the issue you're having is?

**Comment by SeanAtr0n** [comment]
stuck? have you tried "/unstuck" in chat?

**Comment by MarjieAVolk** [comment]
Closing due to no response
