### ISSUE TITLE
Room is complete but Tables are unusable in the room

### ISSUE THREAD

**Issue by littlett98** [StrangeLoopGames/EcoIssues#6387]
The room is identical to another room I made, but this one doesn't allow me to build anything in it.

![screenshot 6](https://user-images.githubusercontent.com/37678140/37806203-2fdc8c12-2e15-11e8-9ff5-3e405adf55d7.png)
![screenshot 7](https://user-images.githubusercontent.com/37678140/37806204-2fe9d282-2e15-11e8-97f5-189074bacf3f.png)

The 2 above screenshots are of the room which doesn't work.

![screenshot 8](https://user-images.githubusercontent.com/37678140/37806205-2ff6fb24-2e15-11e8-843d-8aa51e81cf6f.png)

Proof that the table doesn't think it's in a room.

![screenshot 9](https://user-images.githubusercontent.com/37678140/37806206-30090062-2e15-11e8-91f4-e2ae6a980e48.png)
![screenshot 10](https://user-images.githubusercontent.com/37678140/37806207-3016f852-2e15-11e8-951f-7f9498e6e07f.png)

The 2 above screenshots are of the room that allows me to use my tables and such.

**Comment by ecoemmeck** [comment]
Have you tried breaking the room with a hammer picking up the blocks and placing them back to see if it fixes your issue?

**Comment by MarjieAVolk** [comment]
Yeah I would recommend picking up a wall block and putting it back down.  Sometimes the room detection messes up.

Also, it's hard to tell from screenshots - Do you have any doorways bigger than 1x2?  You could also try putting a door in your doorway, if that's the issue.

**Comment by MarjieAVolk** [comment]
I was looking for an existing bug about rooms not getting loaded on server restart (which is definitely a bug that we have been trying to nail down), but I couldn't find it...

**Comment by ecoemmeck** [comment]
I believe someone had posted a bug about the objects not loading In order as in highest to lowest. Or older to newest in a room. I'm not sure if this is this issue here though.

**Comment by littlett98** [comment]
Fixed it! I followed your advice and rebuilt the room from the ground up. It turns out that 2 mortar stone blocks were contained in the same location, this happened twice.

**Comment by MarjieAVolk** [comment]
2 blocks in the same place?  >>

Do you happen to have an old save file where these duplicate blocks are still there?

**Comment by littlett98** [comment]
Yea! Oddly enough there were 2 blocks in the same place

Here is a game file that includes the issue:
[Game-2018-03-22-21.26.38.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1843368/Game-2018-03-22-21.26.38.zip)

I'm uploading a video to youtube right now and will link it so you can see what I mean.

**Comment by MarjieAVolk** [comment]
Thanks!

**Comment by littlett98** [comment]
https://youtu.be/i-xxzi2W3Ao?t=6m30s

**Comment by littlett98** [comment]
In the video you'll see me destroy blocks and have ones that weren't there before appear/reappear.

**Comment by metachronism** [comment]
this sounds like it was highly likely the corrupt max block cache from a while back.  closing as fixed
