### ISSUE TITLE
Suggestion: Mining improvements. Tunnel supports.

### ISSUE THREAD

**Issue by zEverdeen** [StrangeLoopGames/EcoIssues#6389]
Wooden and metal supports in tunnels. Mining should be an experience of underground exploration. To make sure your tunnels don't crash, you should have to support them, the larger they are, e.g. able to hold a vehicle, the stronger the support. This will make mining very interesting, because you need to use resources to do it properly.

Now here's the kicker: Ore is too easy to find. Walking around on the surface you can find anything, gold, iron, you name it! Ore is too abundant. If people want more ore, quicker/more efficiently, then they should have a skill called ore refining, not "use less calories". Make smart planning pay off, with the current setup, anyone can be a "miner", when in fact it could be an entire industry on it's own.

You can also lower the amount of gold ore. The amount of gold ore needed for things is too high, and honestly, with a lower amount of gold needed then you can lower the amount of gold ore.

Make it a treasure hunt!

Make ore something that you should need to have a little bit of luck to find. Give people that feeling of happiness when they strike gold! "What! You found iron/gold/copper? Nice dude!"

This will also enable the grinder as a vehicle with a lot of power. Being able to quickly grind a tunnel and then having a guy setting supports behind, will make collaboration and the joy of finding ore with your friends a positive experience. The competition has nothing on you.

Mo' equipment, mo' fun.

Also, hand drills. Quicker and faster than the pickaxe, because you make the pickaxe slower.

Also, also, chainsaws.

**Comment by ecoemmeck** [comment]
I like this idea for the most part e.g. the tunnel / mine suports.
And gold is mostly useless unless trying to defeat the meteor apart from currency.
In saying all this it would be kinda nice to have something equivlant to diamonds in (minecraft) or even emeralds for that matter 
To hunt for... something that gets you all excited to find

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#188
