### ISSUE TITLE
Suggestion: Survival skills & calorie skills

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#6390]
As a lot skills in survival tree are often and easily missunderstood while their true usability is at best questionable i think the survival tree, as well as most (atm pretty lonely) calorie skills should be redone:

- Research Efficiency: Usefull in singleplayer no doubt, but in multiplayer the costs for eff. 4 / 5 are way too high compared to the resources saved considering you only need to craft each book once per server. Unless the server uses very high skillpoint gain rates those points are better used somewhere else for real progression then to save a couple resources. Especially considering these are only one-time-crafted items (that could in my opinion easily use way more resources btw) i think it would be better to replace that skill entirely with a research skill that NEEDS to be leveled to be able to craft certain skillbooks at all. Maybe also increase the time to craft (mid/lategame) books a lot  and add a research speed skill

- Strong Back: We need more slots and/or being able to carry more in carry-slot but more kg is never usefull. For this skill to work you would need to rebalance the weight of almost all things. Currently it seems that there is a ton of things that have literally no weight at all so you can carry a full backpack easily, while others are so heavy that even with double kg you won't be able to carry a usefull amount and have anyway to use a cart. Either change it to unlock more slots / allow more carry or make it a percent kg increase that is also used for carts.

- Big Stomach: Most useless skill in the game currently. It does not increase maximum possible skillpoints as a lot people think. It does not decrease the amount of food you need per day. All it does is increasing the timespan until you have to eat again. It's totally either if i have to eat every 3 minutes while mining or if i have to eat something every 5 minutes. Best thing i could imagine to make this skill usefull would be that it increases the calories food does give instead making the stomach bigger, so you actually have to eat less per day.

- Calorie Efficiency / Digging / Mining / Logging vs. Hoe / Scythe Efficiency:
First off: "calorie efficiency" is probably the most missunderstood skill. The name suggests that it reduces all calorie consumption on top of all other skills / bonus but actually it's only a "Hammer efficiency" skill and therefor should be renamed. And i've no idea why this is in survival. If any of the calorie skills should be in survival it should be digging because the shovel is the thing everyone is using a lot or it should be changed to be a generic calorie reducer on top of all other skills.
This brings me on the 2nd critic about those skills: Hoe & Scythe efficiency are found within their apropiate specialization while all other calorie skills need an extra specialization. It's a very hard decision if it's worth taking a specialization (that increases costs of all other specs you want to learn) for just a single calorie efficiency skill. As a builder it's even harder as you would need both mining & logging.
I think the best thing that could be done with these is either to implement all of them into survival (but that tree would become pretty full) or better just make a generic specialization under "survivalist" profession that includes hammer, digging, mining and logging efficiency.
Logging for example already goes somewhat the right way by adding another skill tied to it that increases damage. This pattern should be followed for the other skills too. Especially usefull would be a skill for digging to be able to dig more dirt at once before you need to unload it (with max skill you should be able to put up 10 dirt like you can carry 10 dirt now). Mining +skill to reduce chance for big chunk to appear (at max skill they don't appear anymore). This new spec would probably also be a good place to add a skill to reduce repair costs (or replace the current calorie/hammer efficiency skill in survival with a repair efficiency skill)

**Comment by ecoemmeck** [comment]
#1 research efficiency is a very important skill for the research monkey as it makes the cost of skill books drop..
#2 is essentially just more inventory carry weight which in some situations is useful (other situations not so much)
#3 big stomach will allows you to eat a bigger meal possibly allowing you to earn extra skill points while your offline.
#4 calorie efficiency I will be honest not manxh people know what it does unless the they have played the game for awhile. ( as far as I can tell drops all callorie usage including running and such

**Comment by Thyriel** [comment]
@ecoemmeck you just proved how missunderstood most of these skills are ;)
ad 1) Just do some math and you will see that research efficiency 4 & 5 are a bad idea in multiplayer. You need to use skillpoints from roughly a full day to learn them. So something new you research will be effectively learned a day later then that char could have learned it when he would have just researched it with eff.3. It's a choice between loosing a full day of skillpoints vs. loosing a couple more resources for a one time craft. But you have plenty of resources in multiplayer. It's either for your cook if he cooks 8 or 20 of a meal for a research book. It's either for your smith if he makes 50 or 100 steel for that book. Especially industry skillbook is a perfect example. If you spend the skillpoints you would need for research efficiency 4&5 into the skill to craft steel with efficiency 5 instead 4 (which is roughly the same SP costs) you saved more iron then with the research efficiency, you can craft steel effectively a day earlier and it will affect every steel you ever craft and not only for the book.

ad 2) Please tell me one single situation where it's usefull ;)

ad 3) Wong ! Go out and test it in singleplayer with 2 saves, or ask people on servers that have skilled it and those haven't skilled it how much SP / day they get with the same food. Big Stomach has NO influence on SP gain. The only situation where you ever benefit from it is when you just login once per day to eat and go offline again, so you are able to balance nutritions easier without the need to use up calories so you can eat a second time.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#187
