### ISSUE TITLE
USER ISSUE: Dropping Logs with the Excavator drops indestructible blocks.

### ISSUE THREAD

**Issue by Lo0seChange** [StrangeLoopGames/EcoIssues#6392]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
**1.** Chop down a tree and harvest the logs.
**2.** Walk up to the Excavator and press the right mouse button.
**3.** Enter the Excavator.
**4.** Press the 1 key to switch to excavation mode.
**5.** Press the right mouse button to drop the logs.

**Expected behavior:**
Excavator is unable to drop logs from its inventory.

**Actual behavior:**
When dropping logs with the Excavator, the Excavator instead drops indestructible blocks.

![Indestructible Blocks.](https://lh3.googleusercontent.com/-NoSnx14Fecs/WrR9MX38dXI/AAAAAAAAAA4/v8h2_RChMtIJH125ro--9PWrpBpd7eXvgCJoC/w530-h298-n-rw/20180323002335_1.jpg)

**Comment by ecoemmeck** [comment]
Well this kinda sounds normal as the excavator is for stone and ores and coal. Not trees and logs

**Comment by SeanAtr0n** [comment]
Fixed in next hotfix
