### ISSUE TITLE
Connection Failed: "Invalid login info. Invalid parameter".

### ISSUE THREAD

**Issue by bruisefest** [StrangeLoopGames/EcoIssues#6394]
I successfully created a game on LAN to co-op with my buddy, but my name has always been "user" in the game.  I cannot figure out how to change it, nor am I able to log in or change my password to the eco servers in game, and I cannot join any multiplayer games on other servers, or else I get the error shown in title.  I created an account on the Eco website, bruisefest.  Game is run through Steam.

**Comment by MarjieAVolk** [comment]
Okay, sounds like you might have an error on your account.  You say you created an account on our site.  Did you link it with your steam account?  You also say you can't 'log in or change my password to the eco servers in game'.  Where are you unable to log in?  Does the game ask you to log in when you open it?  If so, restarting steam might fix your problem.

In any case, I'll ask the web team to check if there is an error on your account.

@rainfarmer "Invalid parameter" is an error message coming from https://ecoauth.strangeloopgames.com/game/verifytokenv3?token=''

**Comment by bruisefest** [comment]
Three days ago I installed the game, opened it up and made a LAN server open to my friend.  It never asked for me to input my name or anything, it just assigned me the name "user".  The game has never asked for my login information, and I don't see any option to provide it.  After I was having this trouble I went to the Eco website and created an account, and linked it to my steam, no effect.  Still cannot join public server games online because of this error.

**Comment by bruisefest** [comment]
My friend had his steam username as his name in game, but not me.  He is able to join public servers no problem.

**Comment by MarjieAVolk** [comment]
Okay, since you saw the problem before making an account with us, it's probably not a problem on your account with us :P  So there is something wrong with your steam login info.  Have you tried restarting steam?  Make sure you shut it all the way down.  Also, do you have any special privacy settings on your steam account, anything like that?

**Comment by bruisefest** [comment]
Steam has been restarted multiple times.  Nothing special changed in steam.

**Comment by bruisefest** [comment]
Am I going to be unable to join online Eco games permanently?

**Comment by MarjieAVolk** [comment]
Sorry we lost track of this issue - I'm trying to find someone to help you out.

**Comment by rainfarmer** [comment]
I sent @bruisefest an email with some troubleshooting for your account.

I wasn't able to recreate the error.

Will update here, when we find a solution.

**Comment by bruisefest** [comment]
Sorry, I don't know what @bruisefest is, how did you send me an email?  I haven't received anything.  The issue is persisting.  The error message has changed slightly, "Invalid Parameter" is now on a separate line and smaller font than Invalid Login Info.

**Comment by rainfarmer** [comment]
Fixed issue by unlinking their steam account.
Not sure the exact cause. Seems like the linked accounts were getting mixed up somehow.

Or it could have just been fixed from a patch in recent releases...
