### ISSUE TITLE
USER ISSUE: connection failed

### ISSUE THREAD

**Issue by kdr264** [StrangeLoopGames/EcoIssues#6395]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
not exactly sure, buy my main world wont connect, i reverified game files and opted out of the staging branch and went back to stable but still wont connect	

**Expected behavior:**
should connect

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
It's likely that your server is crashing during startup.  Could you send me any files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'?

**Comment by kdr264** [comment]
how do i send you those files?

**Comment by MarjieAVolk** [comment]
Sorry for the late response.  Just zip them all up into a single zip file and drop it in here.

**Comment by kdr264** [comment]
https://drive.google.com/open?id=1YsMLe0JzjkmA41oN9P615LgJtYco0f4z

**Comment by MarjieAVolk** [comment]
Okay, it looks like your local files might be corrupted.  Here's a list of things to try:

* steam's Validate Integrity of Game Files
* Uninstalling and reinstalling the game
* Browse local files for Eco, go to Eco_Data\Server and delete the file Eco.Mods.dll
* Delete the folder  %APPDATA%\..\LocalLow\Strange Loop Games\ECO

**Comment by kdr264** [comment]
I did the first 2, Ill try the last 2 and report back. Thanks for the quick response.

**Comment by MarjieAVolk** [comment]
Oh also, since you said you switched to staging and then back -- You could also try restoring a backup of your save.  We don't always support going from a later version back to an earlier version.  Backups are located in Eco's local files, in Eco_Data\Server\Storage\Backups.  Copy the save files up into the Storage directory, replacing the files there.

**Comment by kdr264** [comment]
deleting mods.dll didnt work, nor did deleting the app data folder, i saved an old version before I updated to the unstable version so Ill try loading that. I am able to load other worlds but thats not what I want haha

**Comment by kdr264** [comment]
Marjie youre amazing, there was a recent backup in the backup files. Thanks again buddy, I owe ya one :)
