### ISSUE TITLE
GUI: Icon language for heavy(carry) vs small objects

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6397]
Currently:
Player needs to memorize what type of item is a carry item and what is an inventory item.

Problem:
Bad usability, problem with flow, problematic readability

Suggestion:
Use different shape / color for each of the 2 categories.

**Comment by ecoemmeck** [comment]
I'm not sure exactly where the OP was going with the bug report however I have noticed when picking up rubble the chat will say no room in inventory.
Where the message should be less generic
E.g.  perhaps in such a case saying no room in carrying slot or something of the corresponding storage mechanic

**Comment by MarjieAVolk** [comment]
I think having a different background color for carried items sounds great.

Re the inventory messaging, yeah we have kind of an over-automated messaging system for inventories which often doesn't give good messages.  We might need to revisit that whole thing.

**Comment by Dreepa** [comment]
@ecoemmeck 
What clarification do you need?

Currently we have 2 items types for 2 different sockets, but they are not distinguishable to the user. So my point was that using for example a linked storage GUI does not really give you an idea that you are handling 2 types of objects, one for inventory, one for "carry".

**Comment by keegan-o** [comment]
Made them different colors in master, and thus probably 7.4
