### ISSUE TITLE
Fast transfer between player inventory and world inventory

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6398]
Currently:
Drag & Drop icons to transfer items

Problem:
Users are totally used to a best practice here: SHIFT+Click.
Since Minecraft, nearly all of these kind of games allow instant transfer with SHIFT click

Suggestion:
Add functionality to quick transfer items between player inventory and active world container (follow up: Set active world container in storage GUI, by clicking it once)

**Comment by annoxoli** [comment]
Good idea - or maybe a "Invide to trade" - Function / Window ( like World of Warcraft )

**Comment by ecoemmeck** [comment]
This sounds like a duplicate of #4280

**Comment by MarjieAVolk** [comment]
Thanks, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4280

I like the idea of setting the active inventory also.
