### ISSUE TITLE
Heatmap of ocean animals misleading

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6404]
Currently:
Heatmaps of ocean animals are brightest on the beach, but not really readable on the water layer.

Problem:
It is irritating to the user why the heatmap shows the beach. It is not possible to fish on land. 

Suggestion:
Remove water layer from heatmap or improve visualization.

![image](https://user-images.githubusercontent.com/37662083/37824515-2e7ca820-2e8d-11e8-9a0d-6337d17efd0e.png)

**Comment by Solly-W** [comment]
This is fixed, isn't it? Aquatic animal heatmaps work fine now

**Comment by SlayksWood** [comment]
Seems fixed.
