### ISSUE TITLE
Contrats do not expire and can't mark them as failed

### ISSUE THREAD

**Issue by neyna** [StrangeLoopGames/EcoIssues#6407]
Version: 0.7.2.5 beta

Like in the bug #5385 I created a contract, the times runs out (0s left) and i can't mark it as failed :

![image](https://user-images.githubusercontent.com/3091083/37828835-0f44425a-2e9d-11e8-87a7-df3c986a9a7b.png)

The person who took my contract can only do "job finished" but it does not work since he has not complete what he should do.

The previous bug was closed but it still does not work, no option to mark job as failed.

**Comment by Sekor2600** [comment]
In 7.5.1 the same Problem. You cant Abort Contracts

**Comment by D3nnis3n** [comment]
This is at least fixed partially, https://github.com/StrangeLoopGames/EcoIssues/issues/9588.

**Comment by beastyn** [comment]
Both client and contractor has Mark Failed now.
