### ISSUE TITLE
USER ISSUE: Sound of the washing machine

### ISSUE THREAD

**Issue by neuromantiker** [StrangeLoopGames/EcoIssues#6411]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Just start the washing machine, you will hear the sound  of the anvil.

**Expected behavior:**
A washing machine sound would be fine!:-)

**Actual behavior:**
Sound of the smithering

**Comment by MarjieAVolk** [comment]
Same as https://github.com/StrangeLoopGames/EcoIssues/issues/5846

Will be fixed in 7.3
