### ISSUE TITLE
USER ISSUE: connection problem

### ISSUE THREAD

**Issue by markflohr** [StrangeLoopGames/EcoIssues#6413]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
try to join a friend

**Expected behavior:**
join the server

**Actual behavior:**
Connection Failed

**Comment by MarjieAVolk** [comment]
Hare are a couple of things you can try:

* If the server is still loading, wait until it has finished before trying to join
* Try connecting directly by entering the server's IP address in the 'Join' screen
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software
* If your friend's server is on the same network as you, have your friend disable 'DetectNAT' on the sever.  They can change this setting by entering /openservui in game, going to the Network tab, and then selecting Config.
* If none of those work, you might try nuking it all - Uninstall Eco, shut down Steam, delete the AppData folder, restart your computer, reinstall the game.

Let me know if that helps.
