### ISSUE TITLE
Missing usage of biodiesel

### ISSUE THREAD

**Issue by Simonmicro** [StrangeLoopGames/EcoIssues#6414]
Hello again,
today I noticed, that the "Biodiesel" Item has not any usage and cant used for crafting gasoline or burn it directly inside a car. The wiki is also empty.
Thanks,
Simonmicro

**Comment by Gringar** [comment]
It's used in the excavator. It is a kind of diesel fuel so naturally only diesel engines would be able to use it. Powered carts are more like our everyday cars.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#186
