### ISSUE TITLE
USER ISSUE: Water Flow

### ISSUE THREAD

**Issue by draexan** [StrangeLoopGames/EcoIssues#6415]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Go to a Water source
2. Shovel the Dirt Away
3. try to set up a way for the water to flow
4. Take your stream about 6-7 blocks

**Expected behavior:**
Keeps flowing all the Way	

**Actual behavior:**
Hits an Invisible Wall after exactly 6 Blocks

**Comment by metachronism** [comment]
intended; need to use aqueduct or other constructions to move it farther
