### ISSUE TITLE
Can't open any saved worlds or create a new one after Steam update. Find crash reports

### ISSUE THREAD

**Issue by joanqcflow** [StrangeLoopGames/EcoIssues#6416]
[Crash files Eco.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1843426/Crash.files.Eco.zip)

Find enclosed the crash report files. Since last Steam update we can't connect on any saved worlds or create new.

**Comment by MarjieAVolk** [comment]
Thanks for linking the crash files.  Okay, you got a couple things in there.  A few of them look like you were trying to run two servers at the same time, with the same ports and stuff, so fyi that won't work without a little more setup.

For the others though, I'm guessing that doing steam's 'verify integrity of game files' button will help you (Eg. https://github.com/StrangeLoopGames/EcoIssues/issues/5296).  If that doesn't work, try going in to '[...]\steamapps\common\Eco\Eco_Data\Server' and delete the file Eco.Mods.dll (This triggers some item classes etc to recompile)

**Comment by joanqcflow** [comment]
Thank you, I'll try that 😊 and keep you informed.


Joan




Joan DEFRÊNE, M.Sc. in Biotechnology
PhD student in microbiology-immunology
Laboratoire du Dr. Philippe Tessier
Centre Hospitalier de l'Université Laval (CHUL)
Axe Maladies infectieuses et immunitaires
2705, boulevard Laurier
RC-709
Québec (Québec)
CANADA G1V 4G2
Mail: joan.defrene@hotmail.fr
Cell: +1 418-906-5695


________________________________
De : MarjieAVolk <notifications@github.com>
Envoyé : vendredi 23 mars 2018 22:09
À : StrangeLoopGames/EcoIssues
Cc : joanqcflow; Author
Objet : Re: [StrangeLoopGames/EcoIssues] Can't open any saved worlds or create a new one after Steam update. Find crash reports (#6416)


Thanks for linking the crash files. Okay, you got a couple things in there. A few of them look like you were trying to run two servers at the same time, with the same ports and stuff, so fyi that won't work without a little more setup.

For the others though, I'm guessing that doing steam's 'verify integrity of game files' button will help you (Eg. #5296<https://github.com/StrangeLoopGames/EcoIssues/issues/5296>). If that doesn't work, try going in to '[...]\steamapps\common\Eco\Eco_Data\Server' and delete the file Eco.Mods.dll (This triggers some item classes etc to recompile)

**Comment by joanqcflow** [comment]
Hello,


We tried everything but it's still not working. I send the new crash report files in a new issue number:

#6461


Thanks,


Joan



________________________________
De : MarjieAVolk <notifications@github.com>
Envoyé : vendredi 23 mars 2018 22:09
À : StrangeLoopGames/EcoIssues
Cc : joanqcflow; Author
Objet : Re: [StrangeLoopGames/EcoIssues] Can't open any saved worlds or create a new one after Steam update. Find crash reports (#6416)


Thanks for linking the crash files. Okay, you got a couple things in there. A few of them look like you were trying to run two servers at the same time, with the same ports and stuff, so fyi that won't work without a little more setup.

For the others though, I'm guessing that doing steam's 'verify integrity of game files' button will help you (Eg. #5296<https://github.com/StrangeLoopGames/EcoIssues/issues/5296>). If that doesn't work, try going in to '[...]\steamapps\common\Eco\Eco_Data\Server' and delete the file Eco.Mods.dll (This triggers some item classes etc to recompile)

**Comment by MarjieAVolk** [comment]
Okay, closing in favor of https://github.com/StrangeLoopGames/EcoIssues/issues/6461 I guess lol
