### ISSUE TITLE
USER ISSUE: Blast Furnace stops production if you quit/restart

### ISSUE THREAD

**Issue by Andraxxxx** [StrangeLoopGames/EcoIssues#6419]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
-Start production of iron bars
-Quit Game
-Restart Eco
-Blast Furnace has stopped and can't be restarted
-I have to remove and replace the blast furnace and start again to fix

**Expected behavior:**
Continue producing the ordered products

**Actual behavior:**
-Blast Furnace has stopped and can't be restarted

**Comment by MarjieAVolk** [comment]
Does the blast furnace have any requirements missing on its status tab when this happens?  I'm guessing what's happening is that the room data fails to load when the game starts up.

**Comment by Andraxxxx** [comment]
I didn’t think so – but did notice the output was full – turned out I had it blocked and that was what was stopping the blast furnace – I opened up a hole and it works fine. That did change the room status for the anvil in the same room. The single block missing from the roof killed the status as a room.

Building a single layer up and then capping the hole – allowed the blast furnace output to clear and the room status to be fixed and the anvil work./

**Comment by MarjieAVolk** [comment]
Ooookay, yeah you actually do not need a chimney in your room, but you do need to make sure the pipe port on the object is not blocked, as you found.  You can also build pipe attached to this to control where the pollution is output.
