### ISSUE TITLE
Can not load/create a local game

### ISSUE THREAD

**Issue by nas2803** [StrangeLoopGames/EcoIssues#6420]
Hello,

Tonight i get a big problem. I cannot load or create a new world. When i want to load a game after few time i have just a wheel which is turning again and again. same about create.

If i want to join a server, i have no one server on list even after a refresh.

I tried to load a game on my second computer, and it's working i can play. I transfer all files to my main computer, same problem.

I deactivate my antivirus, reinstall my graphic card driver nothing.

When i try to launch with an old version 7.1.X, the loading is stopped, comes back to windows and displayed an error message Connection Failed.

Can you help me, please?

**Comment by MarjieAVolk** [comment]
Could you send me any files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump' ?

The first things I would suggest you try:
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* You might try nuking it all - Uninstall Eco, shut down Steam, delete the AppData folder, restart your computer, reinstall the game.

**Comment by nas2803** [comment]
[
[Crash AggregateException 03240217.ecodmp.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1844127/Crash.AggregateException.03240217.ecodmp.zip)
](url)

I delete the folder C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO, and it's working but each time i connect i need to reattribute my keyboard touch and my house value is very low (160.6 point to 7 now)

**Comment by MarjieAVolk** [comment]
Okay, so your original problem is fixed, so closing this bug.  Let's talk about the other issues, maybe we can file new bugs for those.

So what do you mean by reattribute your keyboard?  Are your controls mappings getting reset?

For your house, did a room fail to load when you started back up your server?  Can you check whether some of your objects are disabled, for example?
