### ISSUE TITLE
USER ISSUE: Can't join freind

### ISSUE THREAD

**Issue by Astronomic2003** [StrangeLoopGames/EcoIssues#6422]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
i open steam overlay go to my freinds name click join and it says connection failed

**Expected behavior:**
It should have connect me to my freind

**Actual behavior:**
The following error message popped up:
```Connection Failed```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Here are some things to try:

* If the server is still loading, wait until it has finished before trying to join
* Try connecting directly by entering the server's IP address in the 'Join' screen
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software
* If your friend is on the same network as you, have your friend try disabling the DetectNAT setting on their server.  They can do this by typing /openserverui and in the window that opens, going to the Network tab, and the Config sub-tab.
* If none of those work, you might try nuking it all - Uninstall Eco, shut down Steam, delete the AppData folder, restart your computer, reinstall the game.

**Comment by MarjieAVolk** [comment]
Closing due to no response
