### ISSUE TITLE
Authorization Code could use better naming and structuring

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#6424]
There's 5 types of classes/enums in the Auth system, and classes each have derived types:

AuthMode
AuthType
AuthModeType
AuthorizationController
AuthComponent

It's very hard to understand how they're all related, what the hierarchy is there, and the differences between each.

I think AuthModeType designates which of all the authmodes is currently selected, but it defines an Enum that is separate from the availble AuthModes.  It could just use the names of the AuthMode classes directly

AuthComponent contains an AuthController, which contains an AuthMode. However, AuthMode also links to an AuthController, creating a circular dependency that adds a lot of confusion about how the system works.  Removing circular dependencies to have a clear hierarchy, renaming them to illustrate that, and removing classes or embedding them when theyre strictly dependent on the other would go a long way.  Ran into a bug in contract permission setting because I didnt have an understanding of this and still having a hard time grasping it.

**Comment by johnkslg** [comment]
Another issue that has really complicated it and caused bugs:

AuthroizationComponent.AuthorizationController.AuthMode
gives a *different* AuthMode than
AuthoirzationComponent.AuthMode

It appears that the former is hardcoded to the property's AuthMode, regardless of what the component is set to.

**Comment by metachronism** [comment]
per prior comment, they give different authmodes cause they are different types - they could be named better maybe

**Comment by MarjieAVolk** [comment]
They are two separate objects that are basically unrelated to each other.  One is the property auth, and one is the world object auth.

I don't think this code needs to be reorganized or re-written.  It could use some better naming.

**Comment by MarjieAVolk** [comment]
I've cleaned this up a bit on master now
