### ISSUE TITLE
Beta - Staging - picking clams = nothing

### ISSUE THREAD

**Issue by bruteman** [StrangeLoopGames/EcoIssues#6425]
Current Staging build 3-23-18 : pick clams get nothing in your hotbar or inventory.

**Comment by bruteman** [comment]
actually this is for all under water collectables

**Comment by bruteman** [comment]
Version: 0.7.3.0 beta staging-1c5d112f Also Confirmed in 9969b2e9

**Comment by Limelill** [comment]
Still present in latest staging.

**Comment by craig-jong** [comment]
We've merged something in to fix this. It will be working in the next staging.
