### ISSUE TITLE
Eco Linux 0.7.2.5 unplayable in single player and multiplayer

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#6426]
From the support queue: 

Hello,

I am user ID slg124798, and I tried playing the game for the first time in both single player ("New") and multiplayer ("Join") modes but have been unsuccessful.

After the graphics thread is blocked for about 3 minutes during the initial startup to the main menu, I tried clicking "New", typing in a "World Name", selecting "Allow Friends to Join", and "Skillpoints on Crafting".  When I press "Start", a modal dialog appears saying "Could not create save file: …/EcoLinux_v0.7.2.5-beta/Eco_Data/Server/Storage/DefaultWorld does not exist".

If I also select "Generate new", nothing happens upon clicking "Start" except for the fact that [Escape] can no longer be used to return to the main menu.

On the "Join" menu, I tried connecting to a friend's server.  I know that the server is recognized by the game client because the name of the server, the number of citizens, the online count, the world objective, the skill specialization, the active laws count, and the economy count are all populated in the client.  See the screenshot "Screenshot_20180323_170312.png".

I also know that the server is reachable over the specified TCP port because I am able to telnet to it:

$ telnet 193.80.170.69 19552
Trying 193.80.170.69...
Connected to 193.80.170.69.
Escape character is '^]'.
�id
�3^]
telnet> Connection closed.

When I actually try to join the server, an undismissable modal appears showing "Connecting..." and a spinning wheel icon.  After a few minutes, I am sent back to the main menu with a modal displaying "Connection Failed".

If I push "Connect" on any other server (under "Public Eco Servers [ecoauth.strangeloopgames.com]"), the button does nothing.

My firewall is completely open for outbound connections.

Here are some system specs that may be useful:

* xorg-server version: 1.19.6
* NVIDIA driver version: 390.42-0ubuntu1
* Graphics processor: NVIDIA Quadro M1000M
* CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
* Operating system: Ubuntu 18.04 Bionic Beaver (development branch)
* Desktop environment: KDE

What can I do to troubleshoot these gameplay starting problems further?

Thanks,

**Comment by Deltik** [comment]
## Attachments

### Screenshot_20180323_170312.png
![Screenshot_20180323_170312.png](https://user-images.githubusercontent.com/1364268/37861023-3bfce498-2eff-11e8-817f-df5627fe718e.png)

**Comment by metachronism** [comment]
singleplayer is not yet supported on linux/osx

**Comment by Deltik** [comment]
@metachronism: What about multiplayer?
