### ISSUE TITLE
Beta Staging - 3-23-18 - Possible Bug? - Rooms imbalance no more living room items in the game

### ISSUE THREAD

**Issue by bruteman** [StrangeLoopGames/EcoIssues#6434]
Small Table which used to be the living room item is now a general item if elimination of the living room then the housing calculator is off as its still looking for the 5th room. 

Not 100% positive if this is a error or just the elimination of the living room as the new system only has 4 rooms instead of 5?

**Comment by bruteman** [comment]
This was in the Steam Staging I also Confirmed still exist in 9969b2e9

**Comment by MarjieAVolk** [comment]
Yes, removing the living room was intentional.  In what way is it still looking for the 5th room?

**Comment by MarjieAVolk** [comment]
Closing for now, if there is still an issue I will reexamine
