### ISSUE TITLE
Dedicated server only launching with medium skill collaboration

### ISSUE THREAD

**Issue by Biggles12** [StrangeLoopGames/EcoIssues#6435]
Setup being used: Dedicated server hosted through PingPerfect, no mods installed.

Dedicated server only launches with the medium skill collaboration regardless of what the configuration parameter has been changed to. Attempted to start the server with the high collaboration setting and server showed up in server browser as being a medium collaboration server. Server was restarted with no change. Server world was regenerated with no change. PingPerfect support personnel verified that high collaboration setting was present in GUI and recommended this issue be brought to the attention of developers.

**Comment by bruteman** [comment]
if your only allowed to edit the configs you have to change all the settings just saying low will not change the other settings when editing the file. 

Example of default Low settings in the config : 
"CollaborationPreset": "LowCollaboration",
  "UnlearnRefundRate": 0.5,
  "SpecialtyCostMultiplier": 0.5,
  "SkillGainMultiplier": 2.0,
  "SkillPointsPerAction": 0.0,
  "SkillPointPerCrafttime": 0.0

**Comment by Biggles12** [comment]
Thank you for your help Bruteman. I will relay this to PingPerfect because I don't believe they are aware of this.
