### ISSUE TITLE
USER ISSUE: Language selection breakes the UI

### ISSUE THREAD

**Issue by zEverdeen** [StrangeLoopGames/EcoIssues#6436]
Version [7.3.0]

Press ESC, move the language dropdown list. UI is now broken.

You can now not select things when you have tabbed or pressed ESC.

**Comment by ZeskaN** [comment]
This is still an issue in v0.7.3.0-beta-staging-9969b2e9

**Comment by MarjieAVolk** [comment]
I believe this is fixed in the final 7.3 release.  Let me know if that's not the case.
