### ISSUE TITLE
USER ISSUE: Pipe connection at stove

### ISSUE THREAD

**Issue by neuromantiker** [StrangeLoopGames/EcoIssues#6444]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Rezz a stove
2. Try to connect a pipe with the stove at the connection part, it will not work.
3. Now put a pipe one field left, one field back and three fields high. The pollution will be collected there.

**Expected behavior:**
The pollution of cooking should come out at the connection part of the stove and the pipes should collect it there. 

**Actual behavior:**
You can't put the stove at a wall, it has to have an opened field in the upper left.

**Comment by MarjieAVolk** [comment]
Fixed in 7.3
