### ISSUE TITLE
USER ISSUE: search bug

### ISSUE THREAD

**Issue by keyboardwario** [StrangeLoopGames/EcoIssues#6446]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Search for game
hit escape
try searching for another game, nothing

**Expected behavior:**
new fresh server list pops up	

**Actual behavior:**
none

**Comment by MarjieAVolk** [comment]
I believe you have to hit refresh after changing your search now.

We are working on a big rewrite for this screen, so hopefully this will work better in the new version.
