### ISSUE TITLE
Opinion: Is it really fun to unreliably -sometimes- having to hack a 2nd time?

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6448]
Hi,

so I have no idea to frame this in any objective way. But for some reason I am annoyed by just _sometimes_ having to hack a stone for a second time.

To me, the "minecraft flow" is not emerging. Minecraft gives you that reliable "POP" of a block, that you hack towards in cognitive anticipation. It even "builds up" tension by making the block be more and more covered with a "progress texture" while your hammer tool is hacking away at an insane frequency (rather cartoony comical style if you actually would envision someone using it that way).

Now, sure, ECO is it's own thing, but being a block based game, I think comparing "game flow feeling" with the "best" out there is okay to do.

And to get back to the point: In  ECO I do not feel so satisfied using the pick axe. I actually am a bit in rejection mode when I know I need to go mine another 50 stones or so.
I _think_ but I don't really know, that it is due to the unreliability of the to be expected result of hacking.

What you do is you hack, you inspect if there is an element not broken down to the smallest piece, and then you hack again. It is kind of breaking that "brain OFF, flow-mode ON" feeling I get in minecraft.

Anyone else feels similar about that? I mean, it is really a minor thing overall, but I just always get back to this thought that I don't like hacking stones in ECO.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#185
