### ISSUE TITLE
USER ISSUE: Water wheel bug out water

### ISSUE THREAD

**Issue by Vagorr** [StrangeLoopGames/EcoIssues#6449]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Lay a water wheel out of the water.
2. Have a machine that uses mechanical energy near the wheel
3. Make an object

**Expected behavior:**
The object is not created because the water wheel is not in the water

**Actual behavior:**
The object is created

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2105
