### ISSUE TITLE
USER ISSUE: Text disappearing when joining multiplayer server

### ISSUE THREAD

**Issue by bschlz** [StrangeLoopGames/EcoIssues#6450]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Using Arch-Linux when joining a server the game works, but all text in the ui disappears

**Expected behavior:**
It should have text in the ui

**Actual behavior:**
There is no text in the ui, but empty buttons

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5749
