### ISSUE TITLE
USER ISSUE: stone contract

### ISSUE THREAD

**Issue by Trefferquote0** [StrangeLoopGames/EcoIssues#6453]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Have taken a contract for 500 stones in Stockpile.

**Expected behavior:**
it should have count the stones i put in.

**Actual behavior:**
doesnt count any stone
cant finish the contract

**Comment by MarjieAVolk** [comment]
This might be the same as https://github.com/StrangeLoopGames/EcoIssues/issues/6050 which was fixed in 7.3 - Can you let us know if you still have this issue in 7.3?

**Comment by Ser-Geeves** [comment]
Encountered this bug in 8.1. Linked with issue 11902, where I had multiple issues with 1 contract. One of which ended up causing a game crash.

**Comment by SlayksWood** [comment]
Seems fixed:
![bandicam_2019-12-23_16-13-11-760](https://user-images.githubusercontent.com/45708377/71355186-57b12680-258f-11ea-8db0-9162afde211a.jpg)
![bandicam_2019-12-23_16-16-48-684](https://user-images.githubusercontent.com/45708377/71355223-70214100-258f-11ea-989a-0816c8390fc1.jpg)
