### ISSUE TITLE
USER ISSUE: Blue box in middle of screen

### ISSUE THREAD

**Issue by BCFirestar** [StrangeLoopGames/EcoIssues#6456]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Unkown

It is a blue text looking box in the middle of he screen about the length of the inventory bar. It appeared when attempting to unstick the cart

**Expected behavior:**
Not been there

**Actual behavior:**
Not be there?

**Comment by MarjieAVolk** [comment]
Sorry for the delayed response.

Has this only happened once?  Do you have a screenshot or anything?  The next time it happens, could you send me your output log file,  %APPDATA%\..\LocalLow\Strange Loop Games\ECO\output_log.txt

**Comment by ecoemmeck** [comment]
I think I've had this happen before.

Usually it's when your draging a storage in the storage UI and you accidentally let go of the mouse left click the blue rectangle / box gets stuck on screen untill you exit the game client

**Comment by MarjieAVolk** [comment]
Oh, I see.  In that case, I think this should behave a lot better now.  I previously thought it was completely fixed, but I have since had just 1 report, so I guess it is not completely gone: https://github.com/StrangeLoopGames/EcoIssues/issues/6642
