### ISSUE TITLE
System.IO.IOException: 

### ISSUE THREAD

**Issue by Xnetsrac** [StrangeLoopGames/EcoIssues#6459]
--BEGIN DUMP--
Dump Time
03/24/2018 19:44:14

Exception
System.IO.IOException: Der Vorgang ist bei einer Datei mit einem geöffneten Bereich, der einem Benutzer zugeordnet ist, nicht anwendbar.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.SetLengthCore(Int64 value)
   bei Ionic.Zip.ZipEntry.Write(Stream s)
   bei Ionic.Zip.ZipFile.Save()
   bei Eco.Core.Serialization.DataStore.ProcessQueue()
   bei Eco.Core.Serialization.DataStore.<Run>b__29_0()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()

--END DUMP--

**Comment by metachronism** [comment]
closing per fixes of zipfile system that happened a while ago
