### ISSUE TITLE
USER ISSUE: Buggin trough wall/wood

### ISSUE THREAD

**Issue by cylbo** [StrangeLoopGames/EcoIssues#6460]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
I was digging dirt out of my house trough an open window. Then i accidently put it on the window (sill) and i stand in the dirt. After that I bugged out of my house and I stood on top of it.

**Expected behavior:**
I should be blocked so where I am I shouldn't be able to playce anything.

**Actual behavior:**

**Comment by SlayksWood** [comment]
merged to #10345
