### ISSUE TITLE
Can't open any saved worlds or create a new one after Steam update. Find crash reports AGAIN

### ISSUE THREAD

**Issue by joanqcflow** [StrangeLoopGames/EcoIssues#6461]
[Crash files 2 Eco.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1844751/Crash.files.2.Eco.zip)

We tried all your advices but it's still not working.

**Comment by MarjieAVolk** [comment]
Oh, are you on a mac?

It still looks like you just have a bad installation of some sort.  The only thing I have left to suggest is just the nuke it all approach: Uninstall Eco, shut down Steam, delete the AppData folder (C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO), restart your computer, reinstall the game.

**Comment by joanqcflow** [comment]
No Windows.

OK let's try it !


Thanks,


Joan


________________________________
De : MarjieAVolk <notifications@github.com>
Envoyé : lundi 26 mars 2018 19:33
À : StrangeLoopGames/EcoIssues
Cc : joanqcflow; Author
Objet : Re: [StrangeLoopGames/EcoIssues] Can't open any saved worlds or create a new one after Steam update. Find crash reports AGAIN (#6461)


Oh, are you on a mac?

It still looks like you just have a bad installation of some sort. The only thing I have left to suggest is just the nuke it all approach: Uninstall Eco, shut down Steam, delete the AppData folder (C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO), restart your computer, reinstall the game.

**Comment by MarjieAVolk** [comment]
Any luck?

**Comment by joanqcflow** [comment]
Didn't try yet, my PhD is life-consuming lol



________________________________
De : MarjieAVolk <notifications@github.com>
Envoyé : mardi 27 mars 2018 21:33
À : StrangeLoopGames/EcoIssues
Cc : joanqcflow; Author
Objet : Re: [StrangeLoopGames/EcoIssues] Can't open any saved worlds or create a new one after Steam update. Find crash reports AGAIN (#6461)


Any luck?

**Comment by MarjieAVolk** [comment]
Okay, well I'm going to close this for now.  I will still see if you reply here. If you are still having trouble, I can keep helping you out.

**Comment by joanqcflow** [comment]
Hello,


It worked, but because we removed every remaining folders we lost saved worlds. A bit frustrating if every updates will do the same.

Thank you very much for your help.

Joan

________________________________
De : MarjieAVolk <notifications@github.com>
Envoyé : lundi 2 avril 2018 23:03
À : StrangeLoopGames/EcoIssues
Cc : joanqcflow; Author
Objet : Re: [StrangeLoopGames/EcoIssues] Can't open any saved worlds or create a new one after Steam update. Find crash reports AGAIN (#6461)


Okay, well I'm going to close this for now. I will still see if you reply here. If you are still having trouble, I can keep helping you out.

**Comment by MarjieAVolk** [comment]
Oh no! :(  Sorry, I didn't even think about uninstalling the game making you lose your save.  Next time I'll advise people to copy their save file out.

Hopefully this doesn't happen to you again!  I should certainly hope it won't happen with every update.
