### ISSUE TITLE
USER ISSUE: Public markers are invisible to others

### ISSUE THREAD

**Issue by dlouwers** [StrangeLoopGames/EcoIssues#6462]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Be world leader
2. Create a marker and make tick the box to make it publicly visible

**Expected behavior:**
It should be visible to all	

**Actual behavior:**
Only visible to the creator

**Comment by MarjieAVolk** [comment]
I believe this is fixed in 7.3
