### ISSUE TITLE
USER ISSUE: Can't Connect w Friend

### ISSUE THREAD

**Issue by rbuda** [StrangeLoopGames/EcoIssues#6463]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Start game
2. Send invite to friend (in another country) via Steam
3. Friend joins game
4. Friends have fun

**Expected behavior:**
Allowed other player to join once invited/trying to join game.

**Actual behavior:**
"Connection Failure"

**Comment by MarjieAVolk** [comment]
Hey there, sorry for the delayed response.  Here's some suggestions, let me know if anything helps:

* If the server is still loading, wait until it has finished before trying to join
* Try connecting directly by entering the server's IP address in the 'Join' screen
* Temporarily disable your firewall and/or antivirus software (both you and your friend)

**Comment by MarjieAVolk** [comment]
Closing due to no response
