### ISSUE TITLE
USER ISSUE: Beta Staging - Tools have a flat rate of consumption

### ISSUE THREAD

**Issue by bruteman** [StrangeLoopGames/EcoIssues#6467]
Version: 0.7.3.0 beta staging-1c5d112f

A tool always consumes 20 calories regardless if its broken or not.

**Comment by bruteman** [comment]
Also Confirmed in Staging 9969b2e9

**Comment by Legends0** [comment]
Looks to have been fixed in 7.3.1 as broken tools now cost 5x the calorie.

**Comment by MarjieAVolk** [comment]
Oh okay, great thanks
