### ISSUE TITLE
USER ISSUE: Trees dissapearing

### ISSUE THREAD

**Issue by Giggles64** [StrangeLoopGames/EcoIssues#6469]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Cut down tree

Cut log off tree

immediately press E upon log breaking	

**Expected behavior:**
grab logs and leave rest of tree on ground

**Actual behavior:**
whole tree dissapears except what was picked up

**Comment by Giggles64** [comment]
Unsure of how likely recreation will be, it happened 3 times while i was clearing a few trees, after sending the report i cant seem to recreate it and one of the logs re appeared where it dissapeared.

**Comment by WeaselDog** [comment]
seems to no longer be an issue in patch 8.3
