### ISSUE TITLE
USER ISSUE: failed to connect

### ISSUE THREAD

**Issue by kdr264** [StrangeLoopGames/EcoIssues#6470]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
reinstalled game and still cant load my world :(

**Expected behavior:**
loaded

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
It's likely that your save is crashing as it tries to load.  Could you send me any crash files in '[...]\steamapps\common\Eco Server\Dump'?

**Comment by MarjieAVolk** [comment]
Closing due to no response
