### ISSUE TITLE
ISSUE: Two different staging versions

### ISSUE THREAD

**Issue by zEverdeen** [StrangeLoopGames/EcoIssues#6471]
If you download the staging version from steam, you get a much older, unstable version of the client and server.

This has led to issues being reported as issues with the current build from the SLG website, when in fact the issues might have been dealt with already.

Also, people will download the steam version thinking it is stable, when it is not.

**Comment by bruteman** [comment]
Steam version was updated friday afternoon I can't see what the update time and day for the version is on the website and the alphanumeric number difference isn't very clear as to what version is newer than the other.... but there is diff 2 different versions floating around out there.

**Comment by Nanders** [comment]
This has been resolved
