### ISSUE TITLE
Comment on New Housing System.

### ISSUE THREAD

**Issue by bruteman** [StrangeLoopGames/EcoIssues#6474]
The new housing system is more intuitive but feedback on the server is that by adding soft caps to the housing material the room is made of is going to fill servers up with alot of all brick or lumber upper Tier materials eliminating variety in house design and looks. 

There's something just sexy about a Hewn log floor with brick walls and mortared brick windows and roof. but the mixing of all those tiers gets you around 1.33 in the soft cap calculation right now. and looking across a planet of all red brick or lumber homes is going to become pretty plain pretty fast and if someone does change it up they are artificially hurt by having a lower SP house income because they want to look different....

**Comment by Dreepa** [comment]
Yes, we should be allowed to build pretty without being punished. The same applies for aesthetic skills that allow to utilize the advanced block shapes. If you are serious about playing the game, those skills are just a waste of points, as they do not help with fighting the meteor or progressing. 
I think the game should clearly separate those two fields.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#184
