### ISSUE TITLE
USER ISSUE: Dropped items and tree branch seedling 

### ISSUE THREAD

**Issue by TheMightyMcGrew** [StrangeLoopGames/EcoIssues#6476]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Cannot drop items that are no longer useful. Cannot obtain seedlings to replant trees.

**Expected behavior:**
A feature to destroy or pollute with dropped items. An effective means of obtaining tree seedlings.

**Actual behavior:**
No error message, just a lack of development

**Comment by MarjieAVolk** [comment]
Dropping items should be available in the next major release.  We are working on that now.

As for getting tree seeds - I assume you know that you can get them by breaking the tree leaves?  However, we are still talking about a better way to implement this.  We are thinking of having trees drop seeds on the ground, for example.
