### ISSUE TITLE
[Server issue] Freshwater nearly dissapears after 6 hours

### ISSUE THREAD

**Issue by ClarkyMacLeod** [StrangeLoopGames/EcoIssues#6477]
Windows 7 Server
Description of Issue:
After exact 6 hours, all rivers loose their freshwater quality, with only a few spots left. 

Browser: Firefox 59.0.1 (64-Bit), Opera 51.0.2830.55 (64-Bit)

I couldn't reproduce the Issue, since it requires a fresh server to run for > 6 hours straight.

Additional Comments:
Since I don't know how that affects the flora around rivers, i cannot say how severe the issue is.
    
Server Version: 0.7.2.5

Screenshots:
![freshwater_until_6h](https://user-images.githubusercontent.com/34461635/37873600-30a39a52-3020-11e8-84de-9a8ac5179708.PNG)

![freshwater_after_6h](https://user-images.githubusercontent.com/34461635/37873602-35e9214e-3020-11e8-838e-e0c89f3c5eb5.PNG)

**Comment by SlayksWood** [comment]
> New world:
> ![bandicam_2020-01-23_17-31-38-203](https://user-images.githubusercontent.com/45708377/72984883-c20af000-3df5-11ea-8bef-b106998b5843.jpg)
> Fastforward 7-8 hours:
> ![image](https://user-images.githubusercontent.com/45708377/72984972-f9799c80-3df5-11ea-9a2a-3c0e001ba04a.png)

**Comment by SlayksWood** [comment]
Fixed with https://github.com/StrangeLoopGames/Eco/pull/6681
![image](https://user-images.githubusercontent.com/45708377/91814075-464f0c80-ec3c-11ea-9548-4db379442e1b.png)
