### ISSUE TITLE
USER ISSUE: Build a Jack on Sea

### ISSUE THREAD

**Issue by annoxoli** [StrangeLoopGames/EcoIssues#6478]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Build a Jack on Sea
2. Connect to Power-Grid 
3. Craft some Petroleum

**Expected behavior:**
see description, etc.

**Actual behavior:**
See parameter <style="Skill">[Skill] 

<a href="https://ibb.co/fndoVS"><img src="https://thumb.ibb.co/fndoVS/Screen.png" alt="Screen" border="0"></a>

**Comment by MarjieAVolk** [comment]
The next time this happens, can you send me your log file, %APPDATA%\..\LocalLow\Strange Loop Games\ECO\output_log.txt

**Comment by MarjieAVolk** [comment]
Closing due to no response
