### ISSUE TITLE
Server Send Errror Message but hurry on

### ISSUE THREAD

**Issue by lethyro** [StrangeLoopGames/EcoIssues#6480]
( Server !!)

even when we Playing, all 1-2 hours this error come:

über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.InvalidOperationException: Die Sammlung wurde geändert. Der Enumerationsvorgang kann möglicherweise nicht ausgeführt werden.
   bei System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   bei System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   bei Eco.Core.Serialization.Serializers.DictionarySerializer`3.Encode(BinaryWriter writer, Object instance)
   bei Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeMembers(BinaryWriter writer, Object instance)
   bei Eco.Core.Serialization.SimpleSerializer.Serialize(Object obj)
   bei Eco.Core.Serialization.ZipBlob.Persist(Object obj)
   bei Eco.Core.Plugins.SimplePlugin`1.SaveAll()
   bei System.Collections.Generic.List`1.ForEach(Action`1 action)
   bei Eco.Server.PluginManager.ForEach(Action`1 action)
   bei Eco.Core.Serialization.DataStore.SaveAndFlush()
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2633.0 built by: NET471REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
EcoServer
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2633.0 built by: NET471REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
Eco.Shared
    Assembly-Version: 0.7.2.5.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
Eco.Core
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Collections.Immutable
    Assembly-Version: 1.2.2.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
System.Runtime
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll.
----------------------------------------
System.Collections
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll.
----------------------------------------
System.ServiceModel
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2612.0 built by: NET471REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll.
----------------------------------------
Eco.Gameplay
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
System.Design
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll.
----------------------------------------
Eco.Simulation
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
Eco.WorldGenerator
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
Eco.World
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
Eco.ModKit
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
Eco.Plugins
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
Eco.WebServer
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
C5
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
Newtonsoft.Json
    Assembly-Version: 8.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
System.Numerics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll.
----------------------------------------
System.Runtime.Serialization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2612.0 built by: NET471REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
----------------------------------------
System.Xml.Linq
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2612.0 built by: NET471REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Data
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2633.0 built by: NET471REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
----------------------------------------
Eco.Mods
    Assembly-Version: 0.0.0.0.
    Win32-Version: 0.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/Eco.Mods.DLL.
----------------------------------------
System.Globalization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Globalization/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Globalization.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Runtime.Extensions
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Extensions.dll.
----------------------------------------
System.Security
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll.
----------------------------------------
Open.Nat
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
DotNetZip
    Assembly-Version: 1.10.1.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll.
----------------------------------------
System.Diagnostics.Debug
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Diagnostics.Debug/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Diagnostics.Debug.dll.
----------------------------------------
System.ServiceModel.Internals
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2612.0 built by: NET471REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll.
----------------------------------------
System.IdentityModel
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2612.0 built by: NET471REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll.
----------------------------------------
System.Transactions
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll.
----------------------------------------
System.EnterpriseServices
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll.
----------------------------------------
System.Xaml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2633.0 built by: NET471REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll.
----------------------------------------
System.Net.Http
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll.
----------------------------------------
System.Runtime.DurableInstancing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.DurableInstancing/v4.0_4.0.0.0__31bf3856ad364e35/System.Runtime.DurableInstancing.dll.
----------------------------------------
System.Web.Services
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll.
----------------------------------------
SMDiagnostics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2612.0 built by: NET471REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
Eco.Stats
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
System.Web
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2633.0 built by: NET471REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll.
----------------------------------------
System.Drawing.Design
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.Design.dll.
----------------------------------------
Priority Queue
    Assembly-Version: 4.1.1.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
SharpNoise
    Assembly-Version: 0.11.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
NodeGraphControl
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
System.Web.Http
    Assembly-Version: 5.2.3.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
System.Data.SqlXml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2612.0 built by: NET471REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll.
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll.
----------------------------------------
System.Web.ApplicationServices
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2633.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.ApplicationServices/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.ApplicationServices.dll.
----------------------------------------
Microsoft.Build.Framework
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Build.Framework/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.Build.Framework.dll.
----------------------------------------
System.Runtime.Caching
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll.
----------------------------------------
System.Net.Http.Formatting
    Assembly-Version: 5.2.3.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
SharpNoise.Utilities
    Assembly-Version: 0.11.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
System.Threading
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll.
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly-Version: 0.0.0.0.
    Win32-Version: 4.7.2633.0 built by: NET471REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll.
----------------------------------------
System.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
----------------------------------------
Humanizer
    Assembly-Version: 2.1.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
System.Reflection
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Reflection/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.dll.
----------------------------------------
System.Text.RegularExpressions
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Text.RegularExpressions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Text.RegularExpressions.dll.
----------------------------------------
LZ4
    Assembly-Version: 1.0.15.93.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
LiteDB
    Assembly-Version: 4.1.1.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
System.Linq
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll.
----------------------------------------
Microsoft.Owin.Hosting
    Assembly-Version: 3.0.1.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
AutoMapper
    Assembly-Version: 4.2.1.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
Microsoft.Owin
    Assembly-Version: 3.0.1.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
Owin
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
Microsoft.Owin.Host.HttpListener
    Assembly-Version: 3.0.1.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
System.Web.Http.Cors
    Assembly-Version: 5.2.3.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
Swashbuckle.Core
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
System.Web.Http.Owin
    Assembly-Version: 5.2.3.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
System.Web.Cors
    Assembly-Version: 5.2.3.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
Microsoft.Owin.FileSystems
    Assembly-Version: 3.0.1.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
Microsoft.Owin.StaticFiles
    Assembly-Version: 3.0.1.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
Discord.Net
    Assembly-Version: 0.9.6.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
RestSharp
    Assembly-Version: 105.2.3.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/WindowsSpieleServer/Desktop/Eco%20Server/EcoServer.exe.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
System.Windows.Forms.DataVisualization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization/v4.0_4.0.0.0__31bf3856ad364e35/System.Windows.Forms.DataVisualization.dll.
----------------------------------------
System.Windows.Forms.DataVisualization.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization.resources/v4.0_4.0.0.0_de_31bf3856ad364e35/System.Windows.Forms.DataVisualization.resources.dll.
----------------------------------------
Microsoft.CSharp
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll.
----------------------------------------
System.Dynamic
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll.
----------------------------------------

**Comment by MarjieAVolk** [comment]
Threading problem in saving!

**Comment by metachronism** [comment]
partial fix checked in, remaining 2 bugs assigned out #6757 and #6758
