### ISSUE TITLE
USER ISSUE: Dirt Ramp not removable [7.3]

### ISSUE THREAD

**Issue by TeamReality** [StrangeLoopGames/EcoIssues#6481]
**Version:** 0.7.3.0 beta staging-1c5d112f

**Steps to Reproduce:**
1. Place Dirt Ramp

**Expected behavior:**
Using the shovel tool it should dig up the dirt ramp, also attempted to use the dev tool

**Actual behavior:**
But instead, it's like impossible to remove even using the dev tool it deletes blocks under it and around it but it won't delete the ramp.

**Comment by keyboardwario** [comment]
(hammer tool removes it)

**Comment by MarjieAVolk** [comment]
Hammer + ramp was not working on staging for a little while.  That is fixed now.  But yes, you need to use a hammer.

**Comment by MarjieAVolk** [comment]
In a future version, we will have ramps be blocks rather than objects, so this will probably be less confusing then.
