### ISSUE TITLE
USER ISSUE: Resizing Chat panel move it back to last position.

### ISSUE THREAD

**Issue by geeknessfr** [StrangeLoopGames/EcoIssues#6485]
**Version:** 0.7.3.0 beta staging-1c5d112f

**Steps to Reproduce:**
1. On a fresh game update : Moving Chat panel to the bottom of screen.
2. Resize panel.
3. The panel will go back to its last position while resizing.

**Expected behavior:**
It shouldn't move back ;)

**Actual behavior:**
It go back to its last position.

**Comment by MarjieAVolk** [comment]
Yeah we started noticing things like this on staging the other day.  It should be fixed in the current staging build.
