### ISSUE TITLE
Dealing with airpolution

### ISSUE THREAD

**Issue by Heldenstueck** [StrangeLoopGames/EcoIssues#6487]
Hello everyone,

i think there should be a good way to deal with airpolution because at the moment, the only way i know is to build a high chimney in an area you don't care, and watch as the air pollution rises and brings ground pollution with it. I think it would be a good idea to have some high tech technology that allows you to clean up the polluted air, so one can really play environmentally friendly. Maybe it if that technology was available so early that one can, from the beginning, clean up the polluted air and spread none at all.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#183
