### ISSUE TITLE
Server crashes with Stackoverflow on Loading GameplayStatsPlugin

### ISSUE THREAD

**Issue by JankKeks** [StrangeLoopGames/EcoIssues#6489]
Occurs on loading: [SaveGame.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1845453/SaveGame.zip)

The last working server version was Eco Server 0.7.3.0 beta staging-a5ac01f4. Dump file see comment. First not working build is the next staging version staging-3decfca7

- [09:30] Eco Server 0.7.3.0 beta staging-1c5d112f
- [09:30] Server Initialization...
- [09:30] Starting LocalizationPlugin... Finished in 187,7ms
- [09:31] Starting ModKitPlugin... Finished in 110,1ms
- [09:31] Loading mods... Finished in 5,9ms
- [09:31] Starting NetworkManager... Finished in 58,4ms
- [09:31] Initializing items...
- [09:31] Starting StorageManager... Finished in 2.370,5ms
- [09:31] Starting WorldGeneratorPlugin... Finished in 51,4ms
- [09:31] Starting GameplayStatsPlugin... Finished in 0,1ms

```
Unbehandelte Ausnahme: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.ArgumentOutOfRangeException: Die Länge darf nicht kleiner als 0 (null) sein.
Parametername: length
   bei System.String.Substring(Int32 startIndex, Int32 length)
   bei Eco.Core.Serialization.SimpleSerializer.GetOrCreateSerializerFromSchemaType(SimpleSerializer newSerializer, SerializerSchema schema)
   bei Eco.Core.Serialization.SimpleSerializer..ctor(SimpleSerializer newSerializer, String schema, Dictionary`2 migrations)
   bei Eco.Core.Serialization.EcoSerializer.Initialize()
   bei Eco.Core.Plugins.StorageManager..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
```

**Comment by JankKeks** [comment]
[Crash AggregateException 03255452.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1845459/Crash.AggregateException.03255452.zip)

**Comment by JankKeks** [comment]
Seems something like #6048, but with existing world...

**Comment by MarjieAVolk** [comment]
Actually #6048 was with an existing world also, I believe.  They created the world in single player, then copied the save files to the standalone server and ran it there.

It does look like #6048.  And that one was closed since we don't currently support migrating saves from one staging version to the next.  Sorry about that!  Are you still able to play on the previous staging version?

**Comment by JankKeks** [comment]
It's a pity :( actually the save game works in a5ac01f4 but that staging version was nearly unplayable (u can't place objects that are not grounded).
So that means everything is lost?

**Comment by MarjieAVolk** [comment]
Sorry I missed your response.  Now we have the next release out, maybe you will be able to upgrade the save file to that release?

**Comment by JankKeks** [comment]
Unfortunately it was not working with 7.3.1. I restarted with an older Backup.

**Comment by MarjieAVolk** [comment]
Okay, glad you were able to play.
