### ISSUE TITLE
USER ISSUE: CriminiMushroom Spores Non Existant

### ISSUE THREAD

**Issue by albertkun** [StrangeLoopGames/EcoIssues#6492]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
When starting a new world there are no mushroom spores.

**Expected behavior:**
There should be crimini mushroom spores in world because farming research requires it.

**Actual behavior:**
They do not exist.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5092
