### ISSUE TITLE
Client Crash Report

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#6493]
Client crashed while walking... 
[crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1845581/crash.zip)

**Comment by MarjieAVolk** [comment]
You've got `KERNELBASE.dll caused an Access Violation` -- Based on what I found via google, this seems to be a platform level error and not a problem in our code.  Some suggestions I saw were (a) you ran out of RAM (sooo make sure nothing else is running I guess?), (b) restart your computer.
