### ISSUE TITLE
USER ISSUE: Road Tool when Broken will crashlock server.

### ISSUE THREAD

**Issue by Hawk-v3** [StrangeLoopGames/EcoIssues#6494]
**Version:** 0.7.3.0 beta staging-1c5d112f

**Steps to Reproduce:**
Use Road Tool until Broken.

Observe tooltip of Road Tool.

Attempt to repair Road Tool.

**Expected behavior:**
Tooltip displays correct data.

The tool can be repaired.

**Actual behavior:**
The tooltip is full of exception text.
![tooltip](https://user-images.githubusercontent.com/1232355/37878169-76ccf3fc-305c-11e8-87a1-bc1a123df5f2.png)

Attempting a repair causes a server exception only fixed by deleting the Repair Bench from the world.
![serverlog](https://user-images.githubusercontent.com/1232355/37878168-76a9ab04-305c-11e8-9f77-d15d06ff3a6f.png)

**Comment by MarjieAVolk** [comment]
@craig-jong looks like RoadTool doesn't override SkilledRepairCost, so that it will always be null?  Since everything overrides that and nothing sets it, can we have that be abstract?

**Comment by craig-jong** [comment]
should be fixed in staging
