### ISSUE TITLE
USER ISSUE: Cant start the Game

### ISSUE THREAD

**Issue by Mynasteria** [StrangeLoopGames/EcoIssues#6495]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Cant start the Game

**Expected behavior:**

**Actual behavior:**
Could not start server: ApplicationName='E:/Spiele/Steam/steamapps/common/Eco/Eco_Data/Server/EcoServer.exe', CommandLine='-nogui -loadSave="Myna" -maxslots="1" -specialtyMultiplier="0" -skillGainMultiplier="24" -spOnAction', CurrentDirectory='E:/Spiele/Steam/steamapps/common/Eco/Eco_Data/Server/'

**Comment by MarjieAVolk** [comment]
I tried this out, pointing to my steam installation's Eco_Data folder, and with the same args -- working okay for me.

So what is the error that you see?  I assume it is unable to load your save file.  Do you have crash dumps at 'E:/Spiele/Steam/steamapps/common/Eco/Eco_Data/Server/Dump'?

**Comment by MarjieAVolk** [comment]
Closing due to no response
