### ISSUE TITLE
Server Browser not populating by add servers without restart and goes empty of refresh

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6498]
When I add a new server via 'add server' the server does not pop up in favorites.  If I do a refresh the server list empties and never populates.  I have to shut down the client (both on steam or slg client happens on both) and restart for the browser list to populate again.  When I do this the servers I have added via 'add server' now show there just fine.  It's like the browser list is not refreshing as refresh consistently empties the server list and does not repopulated it.  This is happening on both 7.2.5 and 7.3

**Comment by MarjieAVolk** [comment]
Fixed in 7.4
