### ISSUE TITLE
USER ISSUE: Floating beets

### ISSUE THREAD

**Issue by Loomisam** [StrangeLoopGames/EcoIssues#6499]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Hoe a secion of dirt that is protruding from the surroundings.
2. Plant beets on that plot.
3. Notice the beets appear to be floating in the air.

**Expected behavior:**
The beets should be anchored into the ground

**Actual behavior:**
The stems are floating in the air

**Comment by MarjieAVolk** [comment]
I've seen this as well.  Not sure how we want to fix it though.

**Comment by craig-jong** [comment]
This is a much larger art issue that we plan to look at in the future. For the sake of keeping bug reports to important gameplay issues, this should be posted in the suggestions area.
