### ISSUE TITLE
Client stuck after "Caught exception"

### ISSUE THREAD

**Issue by bl0ons** [StrangeLoopGames/EcoIssues#65]
Alpha 3 Windows 7

When I use a command with wrong arguments, for example "/move a,b,c" I get kicked from the server and an error is displayed. The client is stuck now in this screen and I have to reopen the client.

**Comment by klimSLG** [comment]
https://github.com/StrangeLoopGames/Eco/commit/41fe4a8fbfb3fae6750070f66c9d35576eafa094
fixed

**Comment by klimSLG** [comment]
fixed
