### ISSUE TITLE
USER ISSUE: Cant type in chat

### ISSUE THREAD

**Issue by AsianHam** [StrangeLoopGames/EcoIssues#6502]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
press enter to access chat
scroll using the mouse wheel
chat no longer responds but character cannot move anymore
may have pressed enter and esc numerous times
eventually character can move
chat text box is forever open as if im trying to type

**Expected behavior:**
half expected scrolling while in the chat to show previous chat messages

**Actual behavior:**
Scrolling while in the chat scrolled through my chat bar

**Comment by MarjieAVolk** [comment]
Nope, don't see it on 0.7.2.5 either.

**Comment by AsianHam** [comment]
This has only happened once. Although I haven't done any similar to
recreate it either.
I will try to recreate it on my end and if it occurs again I will send you
the log

**Comment by MarjieAVolk** [comment]
I will increase the priority if we get another repro of it :)

**Comment by MarjieAVolk** [comment]
I don't think anyone else ever reproduced it.  Guess I will close as no repro.
