### ISSUE TITLE
USER ISSUE: It says inventory is full if user places research table in house

### ISSUE THREAD

**Issue by LexCaputo** [StrangeLoopGames/EcoIssues#6506]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Build a house that is 4 blocks in height
1. Try to put in research table
1. Note it doesn't let you
1. Open up the ceiling above where table should be then place table
1. try to makeceilnig tall enough
1. It is now deleting blocks as you put them down and making you unable to pick anything else up

**Expected behavior:**
User should be able to continue building after placing a research table down

**Actual behavior:**
Currently, it is deleting things as you put them down and will not allow the user to pick anything else up

**Comment by MarjieAVolk** [comment]
When it deletes the blocks you put down, do you get them back in your inventory?  Do you maybe get them back after logging out and back in?  Or do they disappear forever?

**Comment by LexCaputo** [comment]
They disappear until you log out then back in. From what I found last night, If you are trying to make a roof But having the roof part sort of floating above instead of being connected by the side walls, that's when you run into the issue

**Comment by MarjieAVolk** [comment]
Okay, thanks.

Tried it out, both with roof connected to walls and roof floating, and this is what I see (this is on staging, by the way, so it's possible it is already fixed, although I'm not aware of such a thing being changed).  This is the lowest I can place a block above the research table:
![image](https://user-images.githubusercontent.com/23460210/37925435-651cb63c-30e9-11e8-80af-5bf4b278f5d9.png)

Placing a block just below that one will make the block be temporarily placed, but it will get put back into my inventory immediately.

So, the next time this happens, could you send me your error log?  'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by LexCaputo** [comment]
I don't know if it changes anything, but those walls look different than mine. What I was using was when I used those blocks along with the hammer so they were square. And yeah when I get home I'll try to reproduce it.

**Comment by MarjieAVolk** [comment]
This is using the hammer too - you can choose between hammer constructs with shift + scroll wheel ;)  But I will try with the squares as well.

**Comment by LexCaputo** [comment]
Another way I reproduced it, was when using those blocks I made a hallway that was 3 blocks wide and 4 in height. Then at the beginning of the hallway I placed a block and tried to make the roof go just down the middle, and it did not like it

**Comment by LexCaputo** [comment]
Hm, I'll give it a shot when I get home from work. See if I can lice cap it

**Comment by LexCaputo** [comment]
It looks like the issue with it was connecting to the server. It had happened again when I was building some walls and I got kicked for inactivity. One of the people I was playing with said I was just standing there.

**Comment by MarjieAVolk** [comment]
Oookay, that makes sense.  Do you get this problem pretty frequently?  And does it happen to you on all servers?

Closing this I guess, since after looking this over, that sounds like pretty reasonable behavior when your game can't communicate with the server.  I would guess either you or your server has a bad internet connection if you are seeing this that often, but if you think that's not the case let me know.

**Comment by LexCaputo** [comment]
Yeah a server that was on by myself and a friends server. false alarm then I suppose~
