### ISSUE TITLE
Long-term progression interferes with short-term

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6507]
Currently:
The game offers short term and long term crafting jobs. Some take minutes, others take hours.

Problem:
The user might have nothing to do as long term progression tasks block short term activity.
E.g. crafting a kitchen or excavator totally blocks the user from doing minor labor tasks as well.

To put it in abstract terms: If a game has an "inner" and "outer" (meta) game-play, the inner (short term) loop should always be accessible and playable in order to have something to do. Long term progression should not block minute-to-minute game-play.

Suggestion:
Hard to suggest something here without too much re-work. Easiest option would probably be to  allow to put a job "on hold" without canceling, so that other smaller jobs can be injected and executed, after which it would be possible to unpause the long-term job.

**Comment by disfated** [comment]
You can actually change the order of tasks by dragging them, thus putting short tasks first. As far as they are done the long-term ones will resume.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#181
