### ISSUE TITLE
USER ISSUE: Sales tax bugged

### ISSUE THREAD

**Issue by AndyofBorg** [StrangeLoopGames/EcoIssues#6509]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
If you sell to a store, you get taxed. If you buy from a store, you pay the tax. In either case, the person initiating the transaction pays the tax. This means if I go to a store and sell something and buy something, I get taxed twice and they don't pay any tax.

**Expected behavior:**
It should tax the appropriate party. Either the buyer should always pay the tax (so if I buy, I pay, if THEY buy from me, THEY pay)

**Actual behavior:**
Taxes ME both when I sell and when I buy. It rewards people who run stores and don't actively play the game, which is bad for the economy.

**Comment by disfated** [comment]
It should be named "sales initiator tax" :)

**Comment by MarjieAVolk** [comment]
Haha.  This will actually be fixed in 7.3 :) (https://github.com/StrangeLoopGames/EcoIssues/issues/5850)
