### ISSUE TITLE
USER ISSUE: wwe3

### ISSUE THREAD

**Issue by noris7** [StrangeLoopGames/EcoIssues#6512]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
refdfd

**Expected behavior:**
fdsdf

**Actual behavior:**
The following error message popped up:
```
Could not create save file: D:/Games/Eco/Eco_Data/Server/Storage\dfffd.eco already exists
```

**Comment by MattesSteffen** [comment]
https://imgflip.com/i/275mvv

**Comment by MarjieAVolk** [comment]
You need to name your save something different from previous saves.
