### ISSUE TITLE
USER ISSUE: Using the Tab key while in a vehicle changes the players camera angle suddenly.

### ISSUE THREAD

**Issue by Lo0seChange** [StrangeLoopGames/EcoIssues#6515]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
**1.** Enter a vehicle.
**2.** Point the vehicle in any direction other then North.
**3.** Hit the Tab key to see your mouse pointer.
**3.** Hit the Tab key to return to the controls.

**Expected behavior:**
Players can use mouse pointer without having the camera angle change abruptly in vehicles.

**Actual behavior:**
Camera angle change suddenly when moving from the mouse pointer in vehicles.

**Notes**
It appears that the direction the vehicle is facing matters how severe it is.
North. Very little change.
South. Camera angle changes. 
East. Same as South.
West. Same as South

**Video**
https://youtu.be/PTyP9Ol6DFY

**Comment by SlayksWood** [comment]
Can't reproduce. Seems fixed.
