### ISSUE TITLE
USER ISSUE: Cant Walk with Wood cart

### ISSUE THREAD

**Issue by kalvo11** [StrangeLoopGames/EcoIssues#6516]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Just take the wood cart - in 5-10 % you cant move

**Expected behavior:**
you should move

**Actual behavior:**
you cant move

**Comment by MarjieAVolk** [comment]
Were you out of calories, by chance?

**Comment by kalvo11** [comment]
Yes, sure
Got this Problem several times - not being out of calories or something

**Comment by MarjieAVolk** [comment]
Okay, if you are out of calories, then you are unable to pull the cart.  You need to eat first and then you will be able to.
