### ISSUE TITLE
USER ISSUE: Fell through the world and into oblivion

### ISSUE THREAD

**Issue by jonms90** [StrangeLoopGames/EcoIssues#6517]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Carried a stack of hewd logs outside my stockpile.
Fell through the ground, falling endlessly through oblivion.

**Expected behavior:**
I should have stayed above ground.

**Actual behavior:**
I fell through the ground.

**Comment by MarjieAVolk** [comment]
Did you see any missing chunks?

**Comment by SeanAtr0n** [comment]
sounds like the physics mesh failed to build

**Comment by SeanAtr0n** [comment]
if it happens again or you haven't restarted the game since it happened please send us your log file from `%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

**Comment by SeanAtr0n** [comment]
Duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/7293

**Comment by SeanAtr0n** [comment]
actually this reports more useful
