### ISSUE TITLE
USER ISSUE: Opening a door resulting in getting stuck in ceiling.

### ISSUE THREAD

**Issue by jonms90** [StrangeLoopGames/EcoIssues#6519]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Walk through a door with a ceiling above it.

**Expected behavior:**
I should have opened the door and been able to walk through.

**Actual behavior:**
Opening the door bumped by character up into the ceiling where i got stuck.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4140
