### ISSUE TITLE
Server currupt. 

### ISSUE THREAD

**Issue by pan7s** [StrangeLoopGames/EcoIssues#652]
Not sure what causes it exactly.  It might be fixed in alpha 5 already. I think one way to currupt the server is to change the name.  It had happened on more then one occasion.  Had a server going 6 days and I changed name and boom broke.  That was mine.  The public server I play on has currupted twice.  The second time I can verify they changed names

**Comment by metachronism** [comment]
this is largely fixed in alpha 5, but will leave this open to keep a watch on it

**Comment by pan7s** [comment]
Great thanks :) had our public server currupt twice after 3 days. And my personal one after changing names.  Was a huge bummer for our community of active players on FnF

**Comment by metachronism** [comment]
closing for now, have not seen any corruption issues yet on alpha 5
