### ISSUE TITLE
USER ISSUE: Rice

### ISSUE THREAD

**Issue by Hanumavilasumica** [StrangeLoopGames/EcoIssues#6521]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Get some rice
2. Plant it
3. Pick it up with E

**Expected behavior:**
The rice should disappear on the field and get into my inventory or backpack.	

**Actual behavior:**
Instead it disappears completely

**Comment by MarjieAVolk** [comment]
So it was a newly planted plant.  I guess baby plants don't give you anything.  Maybe they should just give 1 seed back?

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#180
