### ISSUE TITLE
USER ISSUE: work station errors?

### ISSUE THREAD

**Issue by coolman59833** [StrangeLoopGames/EcoIssues#6528]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
step one: Have a workbench
step two: make masonry or carpenter table
step three: craft something

**Expected behavior:**
It should make the item

**Actual behavior:**
instead, it starts making it, but does not... as in, the timer apears, but does not go down.

**Comment by MarjieAVolk** [comment]
So the resources bar fills up, but the time bar doesn't?  Does your workbench have any requirements missing on the status tab?

**Comment by MarjieAVolk** [comment]
Okay, well I'm guessing the workbench was not active because it was missing some requirement.

Closing due to no response.
