### ISSUE TITLE
Rather hard to judge excavator shovel interaction

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6533]
The excavator shovel is hard to judge: What block is exactly below it, when dropping stuff, but also how close it is to another block when mining (like when you try to only pick up stuff but not damage blocks).

Maybe a highlight of the blocks could help here? Or give the excavator a strong light source, so that the shadow of the shovel can be related to.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#179
