### ISSUE TITLE
Excavator controls: Front arm movement & accidental destruction

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6534]
Since pressing left-mouse-button(LMB) is used to move the front part of the arm, as well as used for "dig/collect/pick up", I often end up involuntarily destroying blocks I didn't meant to destroy. 
Maybe it could be an idea to split "dig" and "front arm movement" into to separate controls?

Since you cannot jump inside an excavator, maybe dig could go to the space key, while LMB stays the way it is for front arm controls.

**Comment by SeanAtr0n** [comment]
Fixed in staging, 1 now toggles arm movement
