### ISSUE TITLE
Excavator: Switching vehicle modes resets selected hotbar entry

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6535]
1. Pick up stuff with excavator till all slots are filled
2. Select slot 4
3. Switch vehicle mode to drive
4. Switch back
-> Notice hotbar entry slot 2 is selected

This is especially annoying if you have to move a bit, drop stuff, have to move a bit, drop stuff, repeat...  as you have to re-select the proper slot manually each time.

**Comment by SlayksWood** [comment]
Checked on 8.1. Wasn't able to reproduce, seems fixed.
