### ISSUE TITLE
Excavator: Shortcut keys not matching hotbar slots

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6536]
1. Enter Excavator
2. Select hotbar entry 2, by pressing '2' on the keyboard
->Notice that slot 3 is selected.

(Side issue: Since pressing 1 selects slot 2, selecting slot 2 will always result in vehicle mode switch also.)

**Comment by SeanAtr0n** [comment]
fixed 7.3.1
