### ISSUE TITLE
USER ISSUE: glitched into ceiling

### ISSUE THREAD

**Issue by Reael** [StrangeLoopGames/EcoIssues#6540]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Mine a tunnel only two high
2. collect the stones on your way deeper in
3. get blocket on your way out due to a single coal fragment because you accidentally mined a block on the side instead of in front of you and it drops onto the floor behind you
4. not able to pick coal up since hands are full with stone, so no way to move out of the small tunnel nor going further
5. try to place down stone so you can pick up coal
6. get pushed though ceiling due to too little space placing the stone
7. get trapped with no possibility to move what so ever

**Expected behavior:**
Single items should be movable when walking against it or hitting it with a tool. That one piece of coal trapped me in and with my hands full and no way out there was nothing I could do.

**Actual behavior:**
That coal blocked my way... and now I'm stuck between world layers. Need to start a new world.

**Comment by SlayksWood** [comment]
merged to #6238
