### ISSUE TITLE
USER ISSUE: invisible placement

### ISSUE THREAD

**Issue by Ooraka** [StrangeLoopGames/EcoIssues#6541]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
Place items down, not like a hammer, but with a pick/axe. 
Watch as items are taken away, but not visually placed down.
Disconnect and reload, and they show up.

**Expected behavior:**

**Actual behavior:**

**Comment by metachronism** [comment]
fixed a while back, related to chunk building not picking up new chunks on client
