### ISSUE TITLE
Working in the mines: Excavator limited by ceiling collision

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6542]
Working underground is fun, but unfortunately the excavator does not work well down there. 
As seen here in the screeny, the arm cannot mine forward as the ceiling collides with the arm.
![image](https://user-images.githubusercontent.com/37662083/37986750-934e4c00-31fc-11e8-9f9a-9d117c9fa06c.png)

Maybe we can get a variant of the excavator, where the arm is without shovel, and the entire arm breaks blocks? 

![image](https://user-images.githubusercontent.com/37662083/37986925-283e60a2-31fd-11e8-98a8-4386b48d2a2e.png)

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/6389

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#178
