### ISSUE TITLE
Please highlight "Individual Goals" in game better!

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#6549]
Per a subreddit user: 

Today I learned you can set your own goal and look at everyone else's goals by accidentally clicking on the correct interface. HOLY CRAP, why doesn't that come up automatically every time you open the game?!

Slight hyperbole aside, it's REALLY important to communicate as a channel, and the Individual Goals (Which should have a slightly diff name) is a great way to communicate as a server. It helps with economy, lets people know at a glance what is needed, and really helps a community come together.

I'd suggest having that screen pop up automatically every time a server opens, so that a player can frame their work around their community, or something to better emphasize that interface.

**Comment by MarjieAVolk** [comment]
I don't think I'm into the idea of having the window pop up on login.  But maybe we can make an effort to integrate it better.  For example, we could easily show objectives in player tooltips, which I don't think we are currently doing.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#177
