### ISSUE TITLE
Having ~100 storages chests linked throws me out with message "inactivity"

### ISSUE THREAD

**Issue by Limelill** [StrangeLoopGames/EcoIssues#6551]
![bild](https://user-images.githubusercontent.com/27635053/37992532-489a44a6-320c-11e8-8616-b4d6e6208e5b.png)
![bild](https://user-images.githubusercontent.com/27635053/37992554-63c64770-320c-11e8-9be6-4f15fc2ace03.png)

**Comment by Limelill** [comment]
![bild](https://user-images.githubusercontent.com/27635053/37992825-1b15381e-320d-11e8-9d79-4aa0198137a6.png)

**Comment by metachronism** [comment]
related to other UI optimization tasks, offloading to marjie

**Comment by MarjieAVolk** [comment]
Fixed in next major release
