### ISSUE TITLE
Fish Trap invisible under water (0.7.3.0)

### ISSUE THREAD

**Issue by Thineboot** [StrangeLoopGames/EcoIssues#6556]
In shallow water
![ecotrap1](https://user-images.githubusercontent.com/4364842/37994895-2f6b5ef0-3213-11e8-9a74-727941defecb.png)

Under water
![ecotrap0](https://user-images.githubusercontent.com/4364842/37994894-2f4ab86c-3213-11e8-9fa1-7e3e46cd0336.png)

**Comment by D3nnis3n** [comment]
Fixed.
