### ISSUE TITLE
Add Peer-to-Peer 

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#6557]
Via Steam User:

Add Peer to Peer system to make playing with friends easier. Ylands, a similar survival game has this feature and it works and runs flawlessly. If they can do it, I am sure Eco can as well.

**Comment by MarjieAVolk** [comment]
We already do have peer to peer?  We have steam invite and join (although admittedly they are a bit buggy), we have a list of lan games and now a list of games that steam friends are in, prioritized in the server list.

**Comment by ShaydenMac** [comment]
Thanks Marjie!
