### ISSUE TITLE
Game conflict with Discord

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#6559]
Per a Steam User:

"The game seemed to break discord for all of us, we couldnt hear one of my friends then after they restarted discord we could hear them and they couldnt hear us, then the same issue happened the only way to fix this was for all of us to leave the game... I do beleive that this game will be amazing with a better tutorial and no discord breaking bugs."

**Comment by MarjieAVolk** [comment]
Is that even possible?

**Comment by metachronism** [comment]
we dont do anything with discord
