### ISSUE TITLE
Player housing messages are confusing

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#6560]
![image](https://user-images.githubusercontent.com/6262198/37997073-b494316e-31ce-11e8-8729-518afb3a630c.png)

What is the +0.5 supposed to mean
My housing went down from 48 to 0, (change of -48, which is correct)
then up +0.5 to 12?

Its hard to tell what is happening in these systems

**Comment by elfl0rd** [comment]
@D3nnis3n dupe of fixed issue https://github.com/StrangeLoopGames/EcoIssues/issues/5432

**Comment by D3nnis3n** [comment]
Fixed.
