### ISSUE TITLE
USER ISSUE: /allskills Server Crash | Soloplayer World on my PC

### ISSUE THREAD

**Issue by Ponzooo** [StrangeLoopGames/EcoIssues#6562]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
1. Created a new World
2. Filled some Stockpiles with Lumber, to build in the Future something
3. Added some Skillpoints with Admin Command
4. Used /allskills
Server Crashed - back to Main Menu
5. Restarted the World by clicking on Continue
6. /allskills - crashed again - 3 times in a Row

**Expected behavior:**
Unlocking all Researches

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60,00%>Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei Eco.Gameplay.Items.SkillScroll.OnUsed(ItemStack itemStack, Player player)
   bei Eco.Gameplay.Systems.Chat.AdminCommands.AllSkills(User user)
</size>
```

**Comment by MarjieAVolk** [comment]
Fixed in next hotfix
