### ISSUE TITLE
USER ISSUE: No power / Turbines in 7.3.0 not being on ground

### ISSUE THREAD

**Issue by ZeskaN** [StrangeLoopGames/EcoIssues#6563]
"Sure some of the wind turbines that were placed in the world are inactive now due to not being on solid ground. Even after trying pick them up and replace them down they will not give me full green check marks they are active.
Some of them are placed on grass and even if I place ones down on grass they still show they are not on solid ground."

This was on 7.3.0 right after the premature launch, from support.

zEverdeen#1261 on discord

**Comment by Vekoboy** [comment]
Having same issue on a server I am on... also, states that Fish Traps are not on solid ground either.  Picking up and re-placing does not solve either issue.

**Comment by metachronism** [comment]
7.3 is not out yet!  bugs bugs 👍 

(this is fixed very soon, will be fixed for the official announcement)
