### ISSUE TITLE
USER ISSUE: Glitched Chopped trees

### ISSUE THREAD

**Issue by Hagen-Bryz** [StrangeLoopGames/EcoIssues#6565]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Find an awkward angle for the tree to fall on a rock, or any other entity
2. Chop it down
3. Sometimes the tree will disappear after barely touching it
4. Next time you log back in - you spawn next to the earlier invisible tree.

**Expected behavior:**
Fall down as expected

**Actual behavior:**
Despawns and you respawn next to it after logging out.

**Comment by johnkslg** [comment]
Just got this too

**Comment by johnkslg** [comment]
Holding E may be affecting it.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11622
