### ISSUE TITLE
Strange letters in Nutrition menue

### ISSUE THREAD

**Issue by fridgeghost** [StrangeLoopGames/EcoIssues#6566]
![20180328122116_1](https://user-images.githubusercontent.com/37867883/38023937-d9bcf2c2-3283-11e8-9b57-563d77b82d2c.jpg)

**Comment by Thineboot** [comment]
Reported in [forum](http://ecoforum.strangeloopgames.com/topic/3981/nutrition-housing-%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1) 21 days before (0.7.2.1)

![](http://ecoforum.strangeloopgames.com/uploads/files/1520432001418-ecohousevalue.png)

![](http://ecoforum.strangeloopgames.com/uploads/files/1520432001414-econutrition.png)

**Comment by darkshad9999** [comment]
This is the same issue that I already reported at in Bug #6564 

https://github.com/StrangeLoopGames/EcoIssues/issues/6564

**Comment by MarjieAVolk** [comment]
Fixed in 7.3
