### ISSUE TITLE
Skill Points overflow (GUI only) (0.7.3.0)

### ISSUE THREAD

**Issue by Thineboot** [StrangeLoopGames/EcoIssues#6569]
While bottom left and "Skills" show 
![ecoskillpoints](https://user-images.githubusercontent.com/4364842/38026543-bc20d32e-328c-11e8-82ca-2a564573b12c.png)

you can still spend skill points.

Not a realistic scenario but still not a correct output. Maybe add a skill point cap at maxint. On the other hand it won't affect normal game play but would cost another instruction just useful under testing conditions. Mark it as "it exists and now we know it" ;)

**Comment by MarjieAVolk** [comment]
Sounds like you were trying real hard to break it :P

Yeah, I think I'm going to close this as won't fix actually.  As you say, it's not really a realistic situation, I bet we've got a zillion cases like this.
