### ISSUE TITLE
Ideas to give food diversity more meaning

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6571]
Currently food is available in a multitude of variations, but most of the time you do not really need all of that.

Problem is wasted content that feels too optional.

Suggestion:
Adding craft related bonuses. If you do a lot of brain work, enhanced fish would be good. Could reduce materials needed when doing a research while fed with a lot of fish.

When you do logging and mason work, high end meat could give benefits. Could reduce craft ingredients needed and time to craft for all the construction work related materials.

Each craft could have their specific late game food recipe bonus. 

Maybe some food even changes properties of the avatar, like jump height, run speed, carry capacity, night vision e.g. eating some carrot high-end food could make the night less dark. 

Or some food could allow you to carry more in the carry slot (which is scaling rather badly at the moment, as it's always the same value, early vs. late game).
Food could help with success chances. For example could increase chane to catch a fish.

If there was food specific for each activity and purpose with some varianes inside each category, I think that would give the big content around food much more meaning (given the vast diversity the game is offering in that regard).

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#176
