### ISSUE TITLE
USER ISSUE: Crimini Mushrooms

### ISSUE THREAD

**Issue by pio58111** [StrangeLoopGames/EcoIssues#6577]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
you cant you just have to trust me 

**Expected behavior:**
The map should have criminis

**Actual behavior:**
On the map you cant find anything and also on the graphs you cant see that there are criminis

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5092
