### ISSUE TITLE
USER ISSUE: Stones not stackable on ground

### ISSUE THREAD

**Issue by das-mensch** [StrangeLoopGames/EcoIssues#6578]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Mine some Stone (more than 4)
2. Try to stack it on the ground above each other

**Expected behavior:**
It should have stacked on top of the 4 Stones

**Actual behavior:**
Instead it simply disappeared, but it seems that it still uses space in inventory.

**Edit**
After tabbing back into the game the stones appeared. Maybe some kind of render lag?

**Edit2**
Seems to work now. It was the first start of the game.

**Comment by metachronism** [comment]
this was fixed in 7.3
