### ISSUE TITLE
Suggestion: Sushi + fishing trawlers / cooking impromevents/hunting

### ISSUE THREAD

**Issue by zEverdeen** [StrangeLoopGames/EcoIssues#6579]
Add Sushi as a recipe and more fish recipies in general.

At the moment, there are no end game diets that require "fish" as a resource, making fishing obsolete in the late game. This should be countered by making fish harder to get, and making it a better food source to avoid everyone eating Vegetable Stock and Charred Meat in the mid game.

In general, you should avoid that people being able to figure out a simple, 2:3 ratio of only 2 food sources, this is bad for the game over all, as it makes the food industry very selective about what to grow, and in turn makes scarcity a non factor.

To counter this, the game needs a mechanic that deals with having a stale diet. Vitamins come to mind.

If you were to add fishing boats and fishing trawlers at some point, then you would be able to make the fishing part of the game more interesting, and also make the boats needed by the well-balanced food system. These will in turn require either calories, wood, or fuel(oil) to be used.

**Comment by Thineboot** [comment]
To counter 2-food-source-diets make use of an adapted housing-system. When you fill your stomach only with the high-point-diet-food just drop and/or randomize the effect of one or more nutrients. That way you have not only to balance your nutrients but to vary your food, too.

Think of a diet on steak with ketchup day in and day out and two cups of ice-cream when everybody else eats only one... who want's to eat like that ;)

**Comment by zEverdeen** [comment]
More recipies from Madix-3
"We definitely need more Rice and Fish recipes. Not being able to cook Fish beyond scarring it is... sad.
Fishsticks, Baked Fish, Fish Soup, Heck, Combine it with Rice and Make Sushi! and Peas + Fish + Rice = Paella"

**Comment by craig-jong** [comment]
I'm going to move this to the suggestions area.

https://github.com/StrangeLoopGames/EcoSuggestions/issues/486
