### ISSUE TITLE
USER ISSUE: Dont get "Build a Log House" Quest

### ISSUE THREAD

**Issue by cylbo** [StrangeLoopGames/EcoIssues#6580]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
I fully enclosed a room. When I place a Carpenters Table the status is "Contained in a room" OK. But I dont get the last check on the list.

**Expected behavior:**
Check on the Questlist.

**Actual behavior:**
Dont get the check.

**Comment by elfl0rd** [comment]
@D3nnis3n old issue.

**Comment by D3nnis3n** [comment]
Indeed.
