### ISSUE TITLE
Long names destroy the user online list | Reputation is only (N/A)

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#6584]
See the screenshot, that is pretty enerving:
<img width="412" alt="longname" src="https://user-images.githubusercontent.com/25908592/38053013-3c9aba9c-32d3-11e8-98c1-beafb574495d.png">

**Comment by D3nnis3n** [comment]
Also note the N/A - seems reputation is bugged.

**Comment by MarjieAVolk** [comment]
I'm gonna take a look at the layout of this window, see if I can devise a better fallback for when it's too narrow like this.

But the reputation does seem to be messed up.

**Comment by SlayksWood** [comment]
Objective window isn't broken now.
![image](https://user-images.githubusercontent.com/45708377/82987418-25a16600-a000-11ea-8a48-3f8422a1321a.png)
