### ISSUE TITLE
Server crash on startup after 7.3 update

### ISSUE THREAD

**Issue by werkrat** [StrangeLoopGames/EcoIssues#6585]
Getting this after downloading the zip file from the website and overwriting all the files to update to 7.3.
Windws server, 64bit, unmanaged host

[Crash TargetInvocationException 03281953.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1857682/Crash.TargetInvocationException.03281

[19:52] Eco Server 0.7.3.0 beta
[19:52] Server Initialization...
[19:52] Starting LocalizationPlugin... Finished in 208.1ms
[19:52] Starting ModKitPlugin...
[19:52] Compiling mods... Finished in 1,004.3ms
[19:53] Mods recompiled with errors.
[19:53] Error in BerryExtractFertilizer at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in BerryExtractFertilizer at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in BerryExtractFertilizer at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in BerryExtractFertilizer at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in BerryExtractFertilizer at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in BerryExtractFertilizer at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in BerryExtractFertilizer at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in BloodMealFertilizer at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in BloodMealFertilizer at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in BloodMealFertilizer at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in BloodMealFertilizer at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in BloodMealFertilizer at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in BloodMealFertilizer at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in BloodMealFertilizer at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in CamasAshFertilizer at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in CamasAshFertilizer at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in CamasAshFertilizer at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in CamasAshFertilizer at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in CamasAshFertilizer at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in CamasAshFertilizer at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in CamasAshFertilizer at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in CompositeFiller at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in CompositeFiller at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in CompositeFiller at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in CompositeFiller at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in CompositeFiller at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in CompositeFiller at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in CompositeFiller at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in FiberFiller at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in FiberFiller at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in FiberFiller at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in FiberFiller at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in FiberFiller at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in FiberFiller at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in FiberFiller at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in HideAshFertilizer at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in HideAshFertilizer at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in HideAshFertilizer at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in HideAshFertilizer at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in HideAshFertilizer at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in HideAshFertilizer at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in HideAshFertilizer at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PeltFertilizer at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in PeltFertilizer at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PeltFertilizer at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PeltFertilizer at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PeltFertilizer at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PeltFertilizer at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PeltFertilizer at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PhosphateFertilizer at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in PhosphateFertilizer at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PhosphateFertilizer at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PhosphateFertilizer at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PhosphateFertilizer at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PhosphateFertilizer at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PhosphateFertilizer at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PulpFiller at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in PulpFiller at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PulpFiller at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PulpFiller at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PulpFiller at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PulpFiller at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PulpFiller at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error in BerryExtractFertilizer at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in BerryExtractFertilizer at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in BerryExtractFertilizer at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in BerryExtractFertilizer at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in BerryExtractFertilizer at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in BerryExtractFertilizer at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in BerryExtractFertilizer at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in BloodMealFertilizer at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in BloodMealFertilizer at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in BloodMealFertilizer at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in BloodMealFertilizer at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in BloodMealFertilizer at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in BloodMealFertilizer at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in BloodMealFertilizer at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in CamasAshFertilizer at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in CamasAshFertilizer at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in CamasAshFertilizer at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in CamasAshFertilizer at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in CamasAshFertilizer at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in CamasAshFertilizer at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in CamasAshFertilizer at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in CompositeFiller at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in CompositeFiller at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in CompositeFiller at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in CompositeFiller at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in CompositeFiller at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in CompositeFiller at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in CompositeFiller at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in FiberFiller at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in FiberFiller at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in FiberFiller at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in FiberFiller at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in FiberFiller at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in FiberFiller at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in FiberFiller at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in HideAshFertilizer at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in HideAshFertilizer at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in HideAshFertilizer at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in HideAshFertilizer at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in HideAshFertilizer at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in HideAshFertilizer at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in HideAshFertilizer at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PeltFertilizer at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in PeltFertilizer at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PeltFertilizer at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PeltFertilizer at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PeltFertilizer at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PeltFertilizer at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PeltFertilizer at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PhosphateFertilizer at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in PhosphateFertilizer at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PhosphateFertilizer at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PhosphateFertilizer at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PhosphateFertilizer at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PhosphateFertilizer at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PhosphateFertilizer at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PulpFiller at 49: Cannot implicitly convert type 'System.Collections.Generic.List<Eco.Mods.TechTree.NutrientElement>' to 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>' (CS0029)
Error in PulpFiller at 50: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PulpFiller at 50: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PulpFiller at 51: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PulpFiller at 51: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)
Error in PulpFiller at 52: The best overloaded method match for 'System.Collections.Generic.List<Eco.Gameplay.Items.NutrientElement>.Add(Eco.Gameplay.Items.NutrientElement)' has some invalid arguments (CS1502)
Error in PulpFiller at 52: Argument 1: cannot convert from 'Eco.Mods.TechTree.NutrientElement' to 'Eco.Gameplay.Items.NutrientElement' (CS1503)

   at Eco.ModKit.RuntimeCompiler.HandleCompilerError(CompilerResults results)
   at Eco.ModKit.RuntimeCompiler.LoadOrCompileMods()
   at Eco.ModKit.ModKitPlugin..ctor(ManualResetEvent doneEvent)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)

**Comment by MarjieAVolk** [comment]
What version were you updating from?  Was it from staging?

**Comment by werkrat** [comment]
From the last version they had, I think 7.2.5

**Comment by werkrat** [comment]
Ok yeah, after I deleted everything and reinstalled, it works. The old files really should just be ignored if they're no longer used. Anyway, I guess this isn't really a bug for the devs to worry about :+1:
