### ISSUE TITLE
USER ISSUE: Living rooms are gone!

### ISSUE THREAD

**Issue by Kharomoth** [StrangeLoopGames/EcoIssues#6591]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
All the living rooms have  been turned in to general rooms, all living room items are now general room items. Is this intentional?

**Expected behavior:**
Small table will turn room into living room

**Actual behavior:**
Small table will keep it as a general room

**Comment by MarjieAVolk** [comment]
Yes, this was an intentional change.  Some changes were made to how housing works, and we have removed the living room.  "General room" is now a living room.
