### ISSUE TITLE
USER ISSUE: Invisible plants

### ISSUE THREAD

**Issue by Kharomoth** [StrangeLoopGames/EcoIssues#6592]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Try to plant something

**Expected behavior:**
It should plant the plant

**Actual behavior:**
It says plant already exists there, even though there isn't anything

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5887
