### ISSUE TITLE
Currency subscriptions multiply

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#6593]
Will create an excessive number of subscriptions as currencies are created.

 Player.obj.UserView.Currency.SubscribeAndCall(this, "Currencies", () =>
            {
                UpdateCurrency();
                Player.obj.UserView.Currency.Currencies.ForEach(currency => currency.Subscribe("CurrencyName", UpdateCurrency));  //Todo: remove old subscriptions, as this will double up!
            });

**Comment by mirasrael** [comment]
User.Currency was replaced with BankAccount.CurrencyHoldings. I checked all places where CurrencyHoldings used and now it correctly unsubscribes old subscriptions everywhere. So it is fixed.
