### ISSUE TITLE
combustion generators don't pollute

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#6600]
??

**Comment by 10KEco** [comment]
The Combustion Generator is missing 
this.GetComponent<AirPollutionComponent>().Initialize(0.1f);
this one is from the poweredcarts

**Comment by 10KEco** [comment]
this.GetComponent/AirPollutionComponent/().Initialize(0.1f);
cant use < so i used /

**Comment by SeanAtr0n** [comment]
should also probably have a chimney

**Comment by elfl0rd** [comment]
Fixed.
![default](https://user-images.githubusercontent.com/4980243/41872237-e52d3464-78c9-11e8-9445-6236ff9a4a0d.png)
