### ISSUE TITLE
Icebox, ShelfCabinet, and BookShelf issue

### ISSUE THREAD

**Issue by 10KEco** [StrangeLoopGames/EcoIssues#6601]
The Icebox, ShelfCabinet, and BookShelf has an authority issue. When you place them, they start as authority mode public. 

They are all missing "this.GetComponent<PropertyAuthComponent>().Initialize(AuthModeType.Inherited);"

If placed in protected override void Initialize() in all the public partial class Object: it will fix them

example:
public partial class ShelfCabinetObject : 
        WorldObject    
    {
        public override string FriendlyName { get { return "Shelf Cabinet"; } } 

        protected override void Initialize()
        {
            this.GetComponent<MinimapComponent>().Initialize("Housing");                                 
            this.GetComponent<HousingComponent>().Set(ShelfCabinetItem.HousingVal);                                

            var storage = this.GetComponent<PublicStorageComponent>();
            storage.Initialize(8);
            storage.Storage.AddRestriction(new NotCarriedRestriction()); // can't store block or large items
            // added code for Inherited mode
	        this.GetComponent<PropertyAuthComponent>().Initialize(AuthModeType.Inherited);

        }

        public override void Destroy()
        {
            base.Destroy();
        }
       
    }

**Comment by MarjieAVolk** [comment]
I believe I fixed the Icebox in 7.3, but I didn't realize there were others.

**Comment by 10KEco** [comment]
just did a fresh download and the IceBox.cs is missing the code.

**Comment by 10KEco** [comment]
i also would like to note that the refrigerator needs it as well

**Comment by styles784** [comment]
The icebox and shelves are still defaulting to public on 7.3.1 - a lot of other things seem to be linked to the wrong data, so it seems like some part of the updated code was left out of the release

**Comment by craig-jong** [comment]
we moved the default of every world object to inherited.
