### ISSUE TITLE
FPS drop when looking at glass in stockpile

### ISSUE THREAD

**Issue by Daniel93a** [StrangeLoopGames/EcoIssues#6607]
When looking at a stockpile full of glass my FPS are dropping from ~50 in town and ~75 in the wilderness to ~15.

![Graphics Options 1](https://user-images.githubusercontent.com/34270661/38061960-e61fa21c-32f1-11e8-97ca-426e2ec32be7.jpg)
![Graphics Options 2](https://user-images.githubusercontent.com/34270661/38061981-fd463aaa-32f1-11e8-929a-67532f4571a3.jpg)

Note the 14.9 fps in the bottom right, sadly my steam fps counter didnt get screenshotted.

![Control Picture 1](https://user-images.githubusercontent.com/34270661/38062158-ba575f0c-32f2-11e8-8819-77cec7e9f764.jpg)
![Control Picture 2](https://user-images.githubusercontent.com/34270661/38062057-45dea914-32f2-11e8-8727-8e123582b787.jpg)
![Glass Direction 1](https://user-images.githubusercontent.com/34270661/38062077-5d6acb76-32f2-11e8-9142-c7f5def169f8.jpg)
![Glass Direction 2](https://user-images.githubusercontent.com/34270661/38062079-5f7743a4-32f2-11e8-8f71-b19f295f6fb1.jpg)
![Glass Direction 3](https://user-images.githubusercontent.com/34270661/38062080-614033bc-32f2-11e8-8852-78a4fa87a686.jpg)
![Glass Direction 4](https://user-images.githubusercontent.com/34270661/38062082-637b9ffe-32f2-11e8-9f6b-8df26e72875e.jpg)

Hardware: i7-4790k/GTX980*2/16gb 
I didn't notice an increase in CPU load when looking at the glass stockpile.

**Comment by Daniel93a** [comment]
![20180329015141_1](https://user-images.githubusercontent.com/34270661/38062386-e61abd4a-32f3-11e8-995e-33fe0a703988.jpg)
Removed glass, same position as before, now 46 FPS

**Comment by keegan-o** [comment]
I added a new builder for stockpiled glass, but unfortunately the items didn't get set to use it before 7.3.0-- will hopefully be in a hotfix though.
