### ISSUE TITLE
USER ISSUE: Server is full

### ISSUE THREAD

**Issue by portalseeker** [StrangeLoopGames/EcoIssues#6608]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Can play on people's online server, but would rather play alone. It is not an option however, since the update just caused single player servers to say "server full" when no one is playing on them. Even new games act this way.

**Expected behavior:**
I was playing just before the update and had no issues. I was able to hop right in and play.

**Actual behavior:**
"server is full" comes up every time it finishes loading the world file.

**Comment by MarjieAVolk** [comment]
:O

Okay, so you should be able to fix this for yourself by going to steam and selecting browse local files for Eco, then go down into Eco_Data\Server\Configs, opening Users.eco, and looking for the line '"MaxSlots": 0,'.  I assume it will be set to 0, meaning no one can play.  Set it to '1' if you only want to allow yourself, or '-1' if you want to allow any number of people.

**Comment by portalseeker** [comment]
It wasn't set to 0 when I checked. It was always 1 from the way it looks. I will try the -1 thing and see if it makes any difference

**Comment by portalseeker** [comment]
-1 let the single player world boot up, but 1 didn't. Thanks for the quick help

**Comment by MarjieAVolk** [comment]
Sounds like we are rolling out a hotfix for everybody asap

**Comment by portalseeker** [comment]
Great :) Glad I could help find the problem. Great game though, I bought it today and it's already one of my faves
