### ISSUE TITLE
Eating still consumes item when full

### ISSUE THREAD

**Issue by Tetramorium** [StrangeLoopGames/EcoIssues#6614]
Version: 0.7.3.0 beta

Steps to Reproduce:

Eat a BEAR supreme when stomach is full. It will still consume the item.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6590

I'm working on this now, will likely be fixed in the next hotfix
