### ISSUE TITLE
wrong PowerConsumption of SteelTableLamp (250(?)) and SteelFloorLamp (1000)

### ISSUE THREAD

**Issue by Dscha** [StrangeLoopGames/EcoIssues#6616]
As the title says:
SteelTableLamp PU: 250W (not sure if intended or not)
SteelFloorLamp PU: 1.000W (erm, i **HOPE** it's not intended)

Greetz

**Comment by craig-jong** [comment]
This was fixed a while ago. Still might lower the requirements, but for now they're all at 250.
