### ISSUE TITLE
USER ISSUE: Transparent glitch

### ISSUE THREAD

**Issue by GSnakeUS** [StrangeLoopGames/EcoIssues#6623]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
I was walking and found a transparent emptiness in the map

**Expected behavior:**
It shouldn't have been there in the first place. I shouldn't be able to stop seeing parts of the map or fall through it.

**Actual behavior:**
Instead of being able to walk through i fell through the transparency and kept falling over and over again until i decided to close the game.

**Comment by GSnakeUS** [comment]
![bug](https://user-images.githubusercontent.com/37510908/38067953-94580718-32dc-11e8-9b8d-8214bfbfad20.jpg)

**Comment by metachronism** [comment]
chunk issues, which have been fixed in 7.3
