### ISSUE TITLE
Small table not a livingroom Furniture anymore

### ISSUE THREAD

**Issue by Hiroyugane** [StrangeLoopGames/EcoIssues#6629]
It looks like the "small table" isn't a living room furniture anymore. It wouldn't be that big of a problem if it wouldn't be the only living room furniture. Uncertain if this happens in all worlds.

Greetings
Hiro

**Comment by BadHarry00** [comment]
Version 7.3.1 it's the same. The small Table start a 2. General Room now. So, i can't build the living room.

![2018-03-31 11_17_07-eco](https://user-images.githubusercontent.com/30983485/38162004-6e2e6bc8-34d9-11e8-9782-0a8e3d7f2e41.png)

**Comment by MarjieAVolk** [comment]
Yes, Living Room was removed from the game.  The reason for this was to increase the flexibility of where you can place generic items like the small table.
