### ISSUE TITLE
cant craft campfire without the learned cooking skill

### ISSUE THREAD

**Issue by panisch420** [StrangeLoopGames/EcoIssues#663]
cant craft a campfire on a workbench without having cooking researched.
i do have 1 point in "campfire cooking" which is now under survival.

**solution:**
either put the "campfire cooking" skill back under "cooking" or remove the skill requirement for crafting a  campfire on the workbench.

**Comment by craig-jong** [comment]
Yea, this was a quick change that needs to be fixed. Thanks for posting this.
