### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by bender49330** [StrangeLoopGames/EcoIssues#6632]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**

 tous les serveur offline
**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5211

We are working on a rewrite of the join server page, so we will likely not address this until that is released.  Should be soon, fingers crossed.
