### ISSUE TITLE
SERVER ISSUE: Always online -> Full Servers

### ISSUE THREAD

**Issue by Taratsamura** [StrangeLoopGames/EcoIssues#6633]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
1.) Log into a Server
2.) Log out
3.) Another player types in /Players and see that that player is still online (but he's not), using up a Slot.

**Expected behavior:**
People who log out, are considered offline

**Actual behavior:**
After logging out, you are still considered online using up a Server Slot, and the Server is getting Full with offline Users.

**Comment by Quandt** [comment]
Same on our server after 0.7.3.0 beta.

**Comment by edocow** [comment]
I am experiencing the same issue on our server after updating to 7.3.0

**Comment by MarjieAVolk** [comment]
Fixed in 7.3.1 (https://github.com/StrangeLoopGames/EcoIssues/issues/6672)
