### ISSUE TITLE
LMB convenience pick-up

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6634]
Currently:
-LMB chops/hacks, 'e' picks up
-Chopping/Hacking a small piece does not do anything

Easy quality of life improvement:
->Left clicking on an object that has no function on it, defaults to "pick-up"
->Better flow: Just left click, without that annoying 'e' spamming.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#175
