### ISSUE TITLE
USER ISSUE: Can't rejoin server after game crash

### ISSUE THREAD

**Issue by Laylens** [StrangeLoopGames/EcoIssues#6636]
Version: 0.7.3.0 beta

Hi, I could need some help.
I play with some friends on a private online server. After the newest game update my game stopped working while I was changing some graphic options ingame. I restarted eco and tried to reconnect to the server. Game keeps crashing at "loading world 97%".
I already reinstalled the game, cleared the appdate and restarted the server. Game keeps crashing at 97%. Now I'm stuck and don't know how to continue. 
Crash report is attached. 

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1859530/error.log)

Need to add: I keep running into the same problem, when trying to start a solo local game.

**Comment by MarjieAVolk** [comment]
Hm, we thought this would be fixed by updating our version of Unity.  But seems not.  :'(  (https://github.com/StrangeLoopGames/EcoIssues/issues/5793)

I'm going to re-open that one.

**Comment by MarjieAVolk** [comment]
Okay, I guess they want a fresh bug instead lol

**Comment by Laylens** [comment]
should be this one
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1873518/output_log.txt)

In the meantime I created a new user on my computer. On that profile I can create new games and join current games, but the game crashes everytime I hit "Quit". It is really strange. I don't know if it's connected to the original problem.

**Comment by metachronism** [comment]
I believe I have fixed this now
