### ISSUE TITLE
USER ISSUE: Excavator/Arm/Fuel bug

### ISSUE THREAD

**Issue by cucu24** [StrangeLoopGames/EcoIssues#6638]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
You must use the Arm of the Excavator until your Fuel is empty, then you go out of the Excavator and trying to look around (If you put somehow fuel in it, then it works normally and you can look around)

**Expected behavior:**
You can look around how you want

**Actual behavior:**
you cant look to the left and right, like in the empty Excavator

**Comment by MarjieAVolk** [comment]
This should be fixed now :) (https://github.com/StrangeLoopGames/EcoIssues/issues/6281)
