### ISSUE TITLE
connection failed 

### ISSUE THREAD

**Issue by ppurg** [StrangeLoopGames/EcoIssues#6639]
1. Eco opens with steam 
2 .I cant join, load or create a world 
3. After loading it says Connection failed 
4. reinstalled the game 
5. doesnt work 
6. It worked yesterday :)

**Comment by MarjieAVolk** [comment]
It doesn't give you the error message until after the world starts loading?

Could you give me any files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'?

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6882
