### ISSUE TITLE
USER ISSUE: No Templates

### ISSUE THREAD

**Issue by cucu24** [StrangeLoopGames/EcoIssues#6640]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Looking in the Factory co.

**Expected behavior:**
Right Templates and Pictures

**Actual behavior:**
Wrong Pictures on other Crafting goods and missing Templates

**Comment by MarjieAVolk** [comment]
Going to merge this with https://github.com/StrangeLoopGames/EcoIssues/issues/6751

I will note there that items on the Factory are broken as well.
