### ISSUE TITLE
USER ISSUE: Stucking/Lag

### ISSUE THREAD

**Issue by cucu24** [StrangeLoopGames/EcoIssues#6641]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Joining a World 

**Expected behavior:**
Playing normal as other People

**Actual behavior:**
Getting stucked or a big lag until i got kicked for inactivity every hour

**Comment by MarjieAVolk** [comment]
Does this happen for all servers?  Or just a particular one?  Does it happen when you are playing a single player game?  Or when connecting to a server on the same LAN as you?

Sounds like this might just be a bad internet connection, or a far away server.

**Comment by krafty83** [comment]
I'm having this issue aswell. should run fine but after a few minutes it freezes then i either wait a couple minutes and see if it goes back to normal or not. usually ends with End Task.. and it happens way more than once an hour.. and its not my internet.

**Comment by MarjieAVolk** [comment]
Okay, if it's non-internet related bad performance, guess I'll lump you guys in with this performance issue for 7.3.1: https://github.com/StrangeLoopGames/EcoIssues/issues/6957
