### ISSUE TITLE
USER ISSUE: Still Stuck Icons

### ISSUE THREAD

**Issue by cucu24** [StrangeLoopGames/EcoIssues#6642]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Fast transfering stone or something else from a stock pile in another (Bug remains until you restart your game)

**Expected behavior:**
Transporting fastly goods with the Stockpile system	

**Actual behavior:**
Sometimes the Icons freezes somewhere on the display and is still there if you leave the Stockpile

**Comment by MarjieAVolk** [comment]
Noooo I thought I fixed this

**Comment by MarjieAVolk** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/3841

**Comment by MarjieAVolk** [comment]
Okay, it really should be cancelling the drag when you release the mouse button 🤔 

Next time you see this, could you send me your log file? '%APPDATA%\..\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by SlayksWood** [comment]
Checked on 0.9.0 staging-1311. Wasn't able to reproduce. Seems fixed.
