### ISSUE TITLE
Logging Specialty rather useless?

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6643]
Logging specialty benefits are only minor, only interesting at the very start of the game for a few minutes (while you looking for food) and it does not scale with iron axes or more modern equipment...
 (at least the tool-tip does only mention stone-axes as affected).

Yet, the thing costs a whole specialty to unlock (so it makes the exponential cost of opening more specialties go up), which is a major factor when it comes to deciding what skill trees to pick.
I would say this mechanic makes "less vital" skill trees basically underdogs (e.g. mining efficiency, just one skill.... or paper milling).
 

Suggestion:
Put hewing and logging together into one category and make logging work with all axes, not just stone.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#174
