### ISSUE TITLE
USER ISSUE: Alphabetic list & transaction

### ISSUE THREAD

**Issue by Gaokin** [StrangeLoopGames/EcoIssues#6645]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
When i check item listed by alphabetic order, it's on order of english names, not in french

**Expected behavior:**
It should be listed by alphabetic order in french names

**Actual behavior:**
Instead it's listed by english names

**Comment by geeknessfr** [comment]
Duplicate of #6599

**Comment by MarjieAVolk** [comment]
Thanks, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6599
