### ISSUE TITLE
SUGGESTION/REQUEST: could we have basic UPnP features?

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#6647]
It would be a great help to have UPnP Support for the server and this game, many people don't knopw hoiw to setup port forwarding or are not able to do because of parents :P 

but UPnP is very often enable by default so this would help a lot of people that want to play toegether on a private world

**Comment by metachronism** [comment]
we added this, and then removed it in favor of NAT punchthrough
