### ISSUE TITLE
USER ISSUE: Roots in soil where there is no tree

### ISSUE THREAD

**Issue by Swahgner** [StrangeLoopGames/EcoIssues#6648]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
I do not know where it will happen but some places on the soil, when I try to dig up soil it says that I can not dig up because the roots are to strong.

**Expected behavior:**
Dig up soil

**Actual behavior:**
Can not dig up soil and gets message about roots are to strong

**Comment by Laylens** [comment]
We had the same issue. A tree was originally located nearby. Restarting the server or planting something on the affected block and digging the plant out again, solved the problem on our server.

**Comment by Swahgner** [comment]
Laylens thanks for the answer.
I tried planting something and remove it again, but it didn't resolve the issue.
I have just updated the server and I will see if that helps when I get the chance :)

**Comment by SeanAtr0n** [comment]
should be fixed in 7.3.2
