### ISSUE TITLE
ISSUE: starting quests overlap the UI

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#6653]
i having an issue when i have too many stzarter quests open, they stack up and block the UI so i can not select my skills

https://puu.sh/zRTLq/ea07eea4b9.jpg

maybe make em stack somehow or some dropdown option

**Comment by johnkslg** [comment]
The image is missing, can you paste it directly into the comment and reopen?

**Comment by elfl0rd** [comment]
yep, possible.
But you can click on ui to change layer.

userUI scale - 100%
![default](https://user-images.githubusercontent.com/4980243/51369709-a6e01300-1b05-11e9-9b88-7e905ca7f6a9.png)

**Comment by SlayksWood** [comment]
merged to #11098
