### ISSUE TITLE
Add checks around config loading, and display a nice error on failures

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#6654]
i forgot to add an important "," at the world size

i can determin this because i understand the crash dump to a certain point ... but could malformed JSON crashes maybe get a bit sanitized and a proper feedback instead of a hard crash of the console?

other users may not have a single clue on what failed

**Comment by ClayC90** [comment]
Well this is not an issue from the devs, but an error on your end, if you have a syntax error, it won't load, simple.

I know this is hard to swallow but it's even like this in c# compilers etc, incorrect syntax, even missing a ; at the end of line will break a build therefore, all the code.

I'd say that it's good that the game hard crashes with .eco files that are incorrect, as if it soft crashes, who knows what will be expected ;)

**Comment by mindforger** [comment]
>I know this is hard to swallow but it's even like this in c# compilers etc, incorrect syntax, even missing a ; at the end of line will break a build therefore, all the code.

how about 
ry{}
catch{
printnice("incomplete config: "+exception.parse(regexTools.serachFileandLine())
}

**Comment by MarjieAVolk** [comment]
So the problem is, when you use ',' in numbers in the config, the game crashes?

**Comment by metachronism** [comment]
reprioritized and cleaned up the initial name of the bug
