### ISSUE TITLE
Regeneration of world on restart, using 89% CPU

### ISSUE THREAD

**Issue by emttim** [StrangeLoopGames/EcoIssues#6656]
We experienced an issue last night where we found our Eco Server (on Windows Server 2016) was running 89% CPU.  http://headword.me/i/mstsc_2018-03-28_22-21-02.png
Upon inspect of logs, we found that it was kept failing, crashing and restarting.
http://emttim.com/i/3W8H6.png
We were able to tweak configs and we believe we fixed that problem, but we thought we would share to make sure that you were aware of this issue within your configs. 
If you need more information or need more logs or details, let me know!

**Comment by Quandt** [comment]
@emttim can you share de configs you tweaked? We are having the same issue on our server after migrate to 7.3.0.

**Comment by HeadWord** [comment]
We fixed the crashing issue. It was a networking config change on the box that causes it to loop.

The bigger problem is that each time on load the eco server uses all available processor power on all cores to regenerate everything it seems. for upwards of 1-3 minutes during bootup. Then as soon as it loads and checks for the network it panicked and crashed just causing it to loop again.

**Comment by MarjieAVolk** [comment]
What were the before and after versions of the config that fixed this?

**Comment by HeadWord** [comment]
The ip in the config was no longer on that box. Changing the IP to the new one fixed the issue. I also changed the ports but in the end it was the ip that was the issue.

**Comment by metachronism** [comment]
using all CPUs is working as intended
