### ISSUE TITLE
Request/Question: expose a way to gracefully shutdown a server and maybe read it's status

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#6661]
i want to run a docker container as i see no way to limit the resource consumption via config or command line arguments

therefore i need a way to ask for server status and to send a signal for a gracefull shutdown to the server somehow via console, socket , script or whatever when docker starts and shuts down the container

**Comment by SeanAtr0n** [comment]
you can pass 'exit' on the command line to save/shut down

**Comment by mindforger** [comment]
so there is no logging module like in minecraft? Because in MC i can not send anything via console, but via rcon

**Comment by metachronism** [comment]
we have nlog now
