### ISSUE TITLE
Lack of error feedback

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#6663]
The game has a general problem with silent failures.

Error messages don't respond with any information beyond "an error occured". If you get stuck in a log in loop, you just get stuck in a login loop. Meaning we can't possibly give you any meaningful information in error reports.

**Comment by MarjieAVolk** [comment]
I think our worst messaging now is with logins.  I believe a straight up 'an error occurred' only comes from our login servers?  'Connection failed' is the fallback message I mean.  We are still working on providing concrete messages for the various connection failure cases.  But once you connect, most in-game errors will provide you with a nice stack trace and an easy way to report it.

**Comment by MarjieAVolk** [comment]
I'm going to close this for now - we will continue to add more concrete error messages for cases we know about (eg. https://github.com/StrangeLoopGames/EcoIssues/issues/4956)
