### ISSUE TITLE
Vehicle ownership changed by renting it to other people

### ISSUE THREAD

**Issue by TouchMeSamaa** [StrangeLoopGames/EcoIssues#6665]
so i rent my excavator to someone for 3 hour and when i come back it says that its his escavator, but i still have the deed with me, i revoke him from the deed but the ownership still havent changed, what should i do ?
![20180329212657_1](https://user-images.githubusercontent.com/37905885/38094528-33ac92dc-3398-11e8-9286-e331ee8a3faa.jpg)

**Comment by MarjieAVolk** [comment]
Did you rent the excavator to him just by giving him permission on the excavator?  Now, is he able to use the excavator after you have revoked him?

I'm wondering if he just changed the name of the excavator to his own name manually, in which case you are fine (you can change the name back if you like).

**Comment by TouchMeSamaa** [comment]
I give him permission. anyway it already fixed now, idk how but i dont seems to have this bug anymore

**Comment by TouchMeSamaa** [comment]
should i close the case ?
