### ISSUE TITLE
USER ISSUE: gathering skill bug

### ISSUE THREAD

**Issue by Neveric** [StrangeLoopGames/EcoIssues#6666]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
1. Any gatheting skill 2-3
2. Gathering
3. The bonus does not always work

**Expected behavior:**
4 fibers/grass

**Actual behavior:**
2 fiber/grass in 70% cases

**Comment by MarjieAVolk** [comment]
Oh wait, I think this is just the change that we made to gathering efficiency.  It used to be that you would get n+2 fibers, where only n varied with how healthy and happy the plant was.  But now you will get n*2 (not exact numbers, but you get the idea).  So you will find for an unhappy plant, it will now give you significantly less resources when you have high gathering efficiency.  But if the plant is very happy, you should get more than before, I believe.
