### ISSUE TITLE
USER ISSUE: Ceiling glass(skylight) broken after 7.3.0 update

### ISSUE THREAD

**Issue by jss0831** [StrangeLoopGames/EcoIssues#6670]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
All ceiling glass that used to be placed correctly is now broken. braking it and replacing it still does not fix issue. they will only place in up and down manner now they will no longer place horizontal to make a sun roof-skylight.

**Expected behavior:**

**Actual behavior:**

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#173
