### ISSUE TITLE
ISSUE: Mortared stone wall hitbox

### ISSUE THREAD

**Issue by DubsTheFox** [StrangeLoopGames/EcoIssues#6671]
you can walk into the corner of mortared stone walls.
![ezgif com-video-to-gif 8](https://user-images.githubusercontent.com/37247290/38097288-4524b27e-3375-11e8-9c21-782da9be4e4c.gif)

**Comment by keegan-o** [comment]
Haven't been able to repro, this may be something related to camera options...

**Comment by SlayksWood** [comment]
Thank you for report.
I was playing with camera settings and try to reproduce it, but I can't. Seems fixed.
If you still have this problem, please reopen and provide your Graphic settings.
