### ISSUE TITLE
USER ISSUE: Users show online who are offline

### ISSUE THREAD

**Issue by werkrat** [StrangeLoopGames/EcoIssues#6672]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Pressed 'o' in-game to see who is online. The list shows me and 2 friends, but I am the only one online.

Using latest 'hotfix' 7.3

**Expected behavior:**
List should have only shown me online

**Actual behavior:**
Showed offline players as online

**Comment by werkrat** [comment]
Also noticed when I connected, it said I last connected 21 seconds ago, when I was offline for quite a few hours.

**Comment by zEverdeen** [comment]
Having a guy post the same issue here.

**Comment by MarjieAVolk** [comment]
Had a tip off as to what the problem was, so this will be in the next hotfix.

**Comment by MarjieAVolk** [comment]
Yeah you are right.  It was not actually fixed in 7.3.1, sorry about that, I thought that it was.  It should REALLY ACTUALLY be fixed in the next hotfix.
