### ISSUE TITLE
Suggestion: Make it possible for tools to break completely beyond repair.

### ISSUE THREAD

**Issue by ZeskaN** [StrangeLoopGames/EcoIssues#6679]
Tools should be able to break if you use them too much. Then you could make the tools require more energy faster when at low durability. This would prompt people to upgrade, currently there isn’t really any benefit to doing so, as repairing wooden tools is too easy, and there is no downside.

**Comment by MKVangen** [comment]
Changlelog for 7.3.0:
"Tool calorie consumption no longer scales with durability"

https://ecoauth.strangeloopgames.com/changelog

**Comment by craig-jong** [comment]
The improved tool use less calories and last significantly longer before needing repairs. In some cases they also perform better (axe). We're looking into adding different tools to better encourage players to improve their tools, but we likely won't ever completely break people tools so they can't deadlock themselves.

**Comment by zEverdeen** [comment]
Alright, I'll avoid deadlocks.
