### ISSUE TITLE
ISSUE: candles are not counted into room value (solid ground issue)

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#6680]
i figured that tallow candles are ignored when placed on tables but count when placed on ground
(not always, maybe room depending)

seems related to the ground issue

**Comment by craig-jong** [comment]
Is it possible your candle is out of fuel? Lights are only counted if they're powered.

**Comment by mindforger** [comment]
Oh well... I never recognized this, have to check again later

**Comment by craig-jong** [comment]
I'm going to close this as resolved, let me know if your candles still do not work.
