### ISSUE TITLE
Waterfalls keep splashing

### ISSUE THREAD

**Issue by werkrat** [StrangeLoopGames/EcoIssues#6681]
I was digging and caused water to "spill" into my work area, so I tried to wall it off. The water is gone but the splash persists:
http://puu.sh/zS4BR.png

**Comment by Thineboot** [comment]
We had a short chat and he told me the splashing has stopped. Unfortunately he has continued building ;)

**Comment by werkrat** [comment]
Did some more testing, it seems to be a client issue. I flew out of render and came back and the splashing appeared to be fixed for me, but Thineboot stood there the entire time and it still wasn't showing right for him.
![ss 2018-03-29 at 06 47 34](https://user-images.githubusercontent.com/17667159/38117240-eb8ab81e-3381-11e8-8d71-ecb7e893576c.png)

**Comment by Thineboot** [comment]
I've joined @werkrat and it seems to be a client side glitch.
When he closed the wall splashing went down without vanishing.
Than it started to raise and raise higher til about 5 blocks above ground - while it was gone on his side.


![ecoglitch](https://user-images.githubusercontent.com/4364842/38117263-5430e118-33b4-11e8-8746-9e843915429e.png)
