### ISSUE TITLE
ISSUE: mouse cursor not fetched from the window when joing my first world after launch

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#6683]
i am playing in windowed mode and the game has just been launched, the moment i join our server (password protected) the mouse curssor is not locked by the game windo but the game is interacting, so i can click in the game and it works but also i click on my desktop

they keyboard does not work then, and that is an even bigger isue, because i can not hit "tab" i have to move my mouse around  bit and hit tab or escape until the game fetches my keyboard input eventually

i can not 100% recreate this but it seems relöated when the game looses focus while entering the world

**Comment by mindforger** [comment]
i just noticed this goes far beyond this, there are several occasions where the window looses focus and the cursor is still being tracked ingame and outside

maybe as a quick n dirty fix, let the window switch to escape menu when loosing focus?

**Comment by Nanders** [comment]
I cannot reproduce this on latest build. The focus issue described is not (or no longer) present, and windows key + d also works properly.
