### ISSUE TITLE
Servers not appearing in server browser

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#6686]
![image](https://user-images.githubusercontent.com/3536496/38108082-9fd881c8-3348-11e8-931a-3e0599ab9a94.png)
http://steamcommunity.com/profiles/76561198196876622/recommended/382310/
and
http://steamcommunity.com/profiles/76561197991454930/recommended/382310/

**Comment by MarjieAVolk** [comment]
Fixed and/or obsolete in 7.4! 👍 ⚡️ 🦅 🔑
