### ISSUE TITLE
BIG ISSUE: Basic Salad recipe missing

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#6687]
i can not complete my advanced cooking as there is no recipe to make basic salad required for the book, it shows up in the requirements and tells me in the tooltip to craft in the cast iron stove but the cast iron stove AND the home cooking skillbook don't have the salad and no other skill has it

**Comment by craig-jong** [comment]
This might be slightly confusing, but there is no recipe called "basic salad recipe", but there are multiple recipes that produce basic salads. That's what PaulGPratt was saying.

If you check the tooltip for Basic Salad you can see all the recipes that will result in creating a basic salad.
![image](https://user-images.githubusercontent.com/18184943/38109369-c70af8a8-334c-11e8-9d58-2ca7db11569b.png)

**Comment by craig-jong** [comment]
They're just multiple recipes for the same result, so any of the recipes there will create the same item from different materials.
