### ISSUE TITLE
House did not detect enclosure

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#6688]
![image](https://user-images.githubusercontent.com/3536496/38108581-24cd0fce-334a-11e8-93bf-d398eadf8360.png)
http://steamcommunity.com/id/lizkist/recommended/382310/

**Comment by johnkslg** [comment]
The user states that they had the exact same layout and it wasn't working, so it would have to be some other issue.

**Comment by craig-jong** [comment]
We don't even know if the player's first layout was valid. It's never stated. Without screenshots, a save, or anything, there nothing to go off of here.

I'd be more inclined to believe a vague report like this if we had a bunch of other bugs reporting room detection being completely broken but we don't. The whole rooms system is too big to just go in and find/fix this issue when we don't really know what it even is.

**Comment by johnkslg** [comment]
I followed up with the reviewer, here is more details:

rob boss: hey devs, just following up on my review here (since i'm guessing thats what the request was pertaining)
rob boss: the issue with getting stuck in the ceiling was a bug I reported right when it happened. I may have deleted the save but if its there i could resend the report
rob boss: i read the github thread - so my stone "house" should have counted as a room?
rob boss: I figured it came from me not processing the stone (i used raw stone since i had no access to a masonry table) but if that should have worked thats definitely weird
rob boss: its just that nothing on the wiki told me raw stone wouldnt work, at least not at the time
Fri Mar 30 2018

**Comment by MarjieAVolk** [comment]
Is building a house out of rubble supported?

**Comment by johnkslg** [comment]
Yes if you stack all 4, and its hard to tell if some have 3 stacked.  And it takes forever, and would only really be done by people when they dont understand how to work with stone properly.

I think we need some feedback or way to explain that stacked stone/logs do not make a house.

**Comment by johnkslg** [comment]
For a fix, I would just make resource piles of 3 count as a wall, and add a note to the tutorial that raw materials shouldn't be used as walls.

**Comment by SlayksWood** [comment]
Now you can make a room from resources (Tier 0) and we have a Material Processing Tutorial Functions. Seems fixed
![image](https://user-images.githubusercontent.com/45708377/61856155-3fe35280-aeca-11e9-92d1-a5e6691ca71a.png)
