### ISSUE TITLE
Connecting peer-to-peer fails for Eco when it works for other games

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#6690]
Our support for allowing people to connect via servers is lacking compared to other games.  We need to do more on this front. 
![image](https://user-images.githubusercontent.com/3536496/38109080-c9913a7a-334b-11e8-804a-de22a1073f32.png)

Negative reviews as a result of this problem:
http://steamcommunity.com/id/therealgeexmo/recommended/382310/
http://steamcommunity.com/id/SpawnDonkey/recommended/382310/
http://steamcommunity.com/profiles/76561198014737314/recommended/382310/
http://steamcommunity.com/profiles/76561198391464603/recommended/382310/
http://steamcommunity.com/profiles/76561198019937522/recommended/382310/
http://steamcommunity.com/id/MemeZut/recommended/382310/
http://steamcommunity.com/id/charred1/recommended/382310/
http://steamcommunity.com/profiles/76561198391464603/recommended/382310/
http://steamcommunity.com/id/MemeZut/recommended/382310/
http://steamcommunity.com/id/Isogrid/recommended/382310/
http://steamcommunity.com/id/francis9001/recommended/382310/
http://steamcommunity.com/profiles/76561198064449652/recommended/382310/
http://steamcommunity.com/id/karunaluna/recommended/382310/
http://steamcommunity.com/id/CingLong/recommended/382310/
http://steamcommunity.com/id/SpawnDonkey/recommended/382310/

**Comment by metachronism** [comment]
this isn't really true...

**Comment by MarjieAVolk** [comment]
This is a really old review, pretty sure we've improved this quite a bit since then.

**Comment by johnkslg** [comment]
Lets reach out to him and see if his problem has been addressed.

**Comment by johnkslg** [comment]
re @metachronism why would he lie.... I believe him.

**Comment by metachronism** [comment]
really not much can fix here without more info

**Comment by johnkslg** [comment]
Lets get more info and work with the bug reporter than. I will follow up for this one.

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/38156963-28c7899a-3437-11e8-8c27-0dbf9ba42303.png)

**Comment by ShaydenMac** [comment]
Further negative reviews regarding this issue:
http://steamcommunity.com/id/CingLong/recommended/382310/

**Comment by sonst-was** [comment]
Last weekend a friend and I had also problems with running Eco on our own PCs.

We both tried to run the server with the same save file but everytime the other one was unable to connect to the server. I tried to run the EcoServer and everything looked fine from my side (port forwarded, can connect to server and play), but my friend was unable to join. But e.g. changing the server's name in the server config changed the server's name in my friends server list too.

What we (both) tried:
- run EcoServer as admin
- connect via dyndns service
- connect via ip
- let the server do the port forwarding itself
- managing the port forwarding myself (both standard and custom external ports)
- run save game without Ecoserver.exe and invite friends via Steam
- "Join Game" via Steam

I run a different service at home on my Raspberry Pi so I know that the dyndns service and my port forwarding are working just fine in other cases.

I'm currently at work and can't specify my PC specification in detail but I know I have some Intel i5, 8GB RAM, some AMD R9 (270?), the game was installed on HDD.

If you need any additional information please let me know how I can help.

**Comment by metachronism** [comment]
should be fixed in 7.4

**Comment by ShaydenMac** [comment]
Followed up via Steam 4/23/18
