### ISSUE TITLE
USER ISSUE: font issues

### ISSUE THREAD

**Issue by neyna** [StrangeLoopGames/EcoIssues#6692]
**Version:** 0.7.3.0 beta

![image](https://user-images.githubusercontent.com/3091083/38109394-47ffea86-3398-11e8-9e07-09168e1c8f9a.png)

![image](https://user-images.githubusercontent.com/3091083/38109416-5987530c-3398-11e8-8e76-3d60e218eb44.png)

**Comment by neyna** [comment]
I dont have any update for eco client. Bug still happening.

![image](https://user-images.githubusercontent.com/3091083/38128640-b4492ff0-33fb-11e8-9c28-1ea24894d0c8.png)

**Comment by Nanders** [comment]
This issue has since been fixed
