### ISSUE TITLE
USER ISSUE: Crafting stations, storages, carts and furniture disappears

### ISSUE THREAD

**Issue by TesterAufLebenszeit** [StrangeLoopGames/EcoIssues#6693]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
My crafting stations, storages, stockpiles, wood carts and furniture disappears after login. It was during mid game and only in a certain area like a special section.
All new added objects like crafting stations, storages, stockpiles, wood carts and furnitures will disappear. Also quarried raw materials like coal, iron, copper, gold and stone will disappear after using a pick axe.
dirt, sand, tailings, wood or building materials will NOT disappear in this area.
Anyhow, the vanished objects will be shown on the map allready. But they are not focusable or able to interact with.
The crafting processes doestn't stop. Also the storages and the items saved in the storages will be available over an indirect way through a not vanished storage outside this area.
The game is pretty much not playable since this problem occurs.

**Expected behavior:**
Crafting stations, storages, carts and furniture are visible and interactable.

**Actual behavior:**
Object are invisible, vanished or not really reachable.

**Attachments:**
![groomv1](https://user-images.githubusercontent.com/37911706/38109703-584e9738-3399-11e8-8663-9fabf44cbf8c.jpg)
![indroomv2](https://user-images.githubusercontent.com/37911706/38109704-586ab2ba-3399-11e8-8269-450f18bd274c.jpg)

**Comment by metachronism** [comment]
dropping priority due to no repro, need more repro steps, or the game save

**Comment by MarjieAVolk** [comment]
Got a second report.  Asked them for a game save also.

**Comment by PuerNoctis** [comment]
Save file is pending, our admin is currently unavailable. Will provide it ASAP. Also, after destructing the higher platform (#6922), the items start appearing one after another after a few hours without server restart... but it takes some time.

**Comment by MarjieAVolk** [comment]
That's very interesting, thank you

**Comment by PuerNoctis** [comment]
Yeah, but it didn't last long. Now some items did disappear again, some others didn't. Another player reported that his crops are disappearing now, too. But that's a whole other part of the map. It is very very strange. Got in contact with our admin, he tries to pull a save tomorrow as he is currently on a business trip.

**Comment by MarjieAVolk** [comment]
> For reproduction:
> If you relog, some objects load back into the world, but only if you relog near them.
> If you walk away long enough and go back the objects won't load either.
> In the mine below the house you can dig for stone but no chunks are spawning, only after a relog there are some parts of it on the ground.
> Hope that helps to solve that bug or get a workaround
-- @Khalanix

**Comment by metachronism** [comment]
Was not able to repro this in 7.4, I suspect another bug that has been fixed may have been causing this.
