### ISSUE TITLE
Patch removes settings

### ISSUE THREAD

**Issue by willkillyaquick** [StrangeLoopGames/EcoIssues#6694]
PROBLEM: Everytime I use SteamCMD to patch the server version of the game, all my settings are removed.  I have tried saving the settings, patching, and then opening the saved setting but the settings do not apply. 
 Settings dont seem to load no matter what.  This problem seems to have been going on since early release on steam.

INFO: ECO Version 0.7.3.0 beta, WINDOW 2012, CPU Phenom II x4, 4GB Ram

**Comment by MarjieAVolk** [comment]
I know that updates will overwrite settings.  But I am curious to know, which settings in particular do you most want to keep?

Also, I am not sure why you are unable to save and reload your settings.  What method are you using to do that?  If you copy your Configs folder elsewhere for example, then do the update, then paste the folder back, I would imagine that would work.

**Comment by willkillyaquick** [comment]
I am using the built-in feature to save the settings.  I am trying to keep at least the server name and the password which is removed every time I patch the server.  I can try to do the copy the configs but that means I will have to remember to do right before I patch the game using the SteamCMD app.  I would hope that maybe there is a way that the patching could conserve the settings.  Attached is the method I was using to save the configs. (I do a Save As)

![image](https://user-images.githubusercontent.com/7242440/38118687-2c244c0a-3382-11e8-935f-af7302915791.png)

**Comment by MarjieAVolk** [comment]
Okay, yeah I am not sure that those do anything >>  Just wanted to make sure there wasn't something weird going on with loading the config.

But yes, I agree that an update should not override your config.

**Comment by willkillyaquick** [comment]
Nothing weird, jost losing all customs configs.  The whitelist is a pain to rebuild when you didnt save the list somewhere else ;)

**Comment by WeaselDog** [comment]
fixed
