### ISSUE TITLE
Suggestion: Wood cutting machine

### ISSUE THREAD

**Issue by zEverdeen** [StrangeLoopGames/EcoIssues#6697]
I was wondering about how to present this... Only a video does it **justice**.

https://www.youtube.com/watch?v=cwwkO7m4bpY
(also notice the dramatic sound)

This could take the wood industry to a whole new level. Making sub-industries that might require a lot of wood possible.
Also, who doesn't want a cool machine.

I will think about how to balance it, but for now this is the main idea: Cool things to play with, that might impact the environment a great deal.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#172
