### ISSUE TITLE
OS X: Key Binding Changes Cause Crash 

### ISSUE THREAD

**Issue by metrotyranno** [StrangeLoopGames/EcoIssues#67]
http://ecoforum.strangeloopgames.com/topic/514/client-bug-os-x-key-binding-changes-cause-crash

When changing the key bindings in the sign-in screen, the game crashes, especially if you attempt to change the keys used. You can just click on one of the bindings (not double-click) and it will crash.
Repro's without fail. Tried it on a Windows 7 machine with no problems.
Client Version Alpha 0.3
Happens on 10.10.5 and 10.11.2
Log here: OSX Binding Crash Log.rtf

**Comment by SeanAtr0n** [comment]
@Nanders just changed how keybindings work, think that might have resolved this issue.
