### ISSUE TITLE
Server Dump files (V7.3) - ClientNetworkException NullReferenceException

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#6700]
Files in Dump folder on server, while playing with 12 players online:
[ClientNetworkException NullReferenceException 03300424.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1862121/ClientNetworkException.NullReferenceException.03300424.zip)

**Comment by SeanAtr0n** [comment]
Sadly none of these exceptions provide the stack trace we need... the next build should provide more useful traces
