### ISSUE TITLE
USER ISSUE: Food goes away, as if eaten, when stomach is full

### ISSUE THREAD

**Issue by silkysmoothnuts** [StrangeLoopGames/EcoIssues#6701]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Attempt to eat food with full stomach.

**Expected behavior:**
Given me an error message, and nothing happens to the food

**Actual behavior:**
Food dissapears as if eaten with no nutrition gain. Error message does still appear, however

**Comment by werkrat** [comment]
This was patched with the hotfix

**Comment by MarjieAVolk** [comment]
Already fixed :)
