### ISSUE TITLE
Error message wooden cart

### ISSUE THREAD

**Issue by DubsTheFox** [StrangeLoopGames/EcoIssues#6707]
I was kicked out of the game after clicking on a wooden cart.
The error log from the crash.
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1862313/error.log)

**Comment by MarjieAVolk** [comment]
Ah it's this again.  This seems to be a bug in Unity.  We have tried updating our Unity version, hoping it would be fixed, but that seems not to be the case.

Others have reported the problem going away when they updated their drivers, or uninstalled GeForce.
