### ISSUE TITLE
Found DotNetZip-2vbicujv.tmp file in Storage folder (V7.3)

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#6708]
Today I found a file named 'DotNetZip-2vbicujv.tmp' in the Storage folder of our server. What is this, what can I do with it and in which case will this be created.
Can I delete it?

(may be relevant: some of the ECO-backups generates the timetamp-folder and the Game.eco file but not the Game.db file. )

**Comment by MarjieAVolk** [comment]
Yes, I believe that is related.  This file is an artifact of the backup process - it is supposed to delete it when it is done.  I think it will only leave the file there if the backup process fails in the middle.  If you are missing .db files, then it probably errored out while trying to copy them over.  That is too bad, I thought this was all fixed up.

In the mean time, you can delete the .tmp files as much as you like :)  Normally they would only appear there for a second.

**Comment by metachronism** [comment]
these are deleted already when the server boots up -

**Comment by MarjieAVolk** [comment]
I just thought it might indicate that there is an issue, if one doesn't get deleted.
