### ISSUE TITLE
Fertilizers are all showing the same stats and placeholder icon

### ISSUE THREAD

**Issue by styles784** [StrangeLoopGames/EcoIssues#6709]
Fertilizers are now all showing 0.3 for all three nutrients, and the cog placeholder icon. This can be seen at the farmer's table and on the items themselves. I have already deleted/reinstalled my client and server (via steam) in order to rule out a migration issue from 7.2.5 to 7.3.0 and the problem persists. The correct values are present in the c# source files included with the game, but the game doesn't seem to access those files directly

**Comment by zEverdeen** [comment]
I can confirm this. 👍

**Comment by styles784** [comment]
Some of the fertilizers, when held in inventory, do have icons other than the placeholder cog - the berry extract fertilizer looks like actual huckleberries, for example. But I'm assuming this is still a glitch, since it used to have a fertilizer icon with the berry to indicate which type of fertilizer

It seems like the link between the items and their data has been messed up, like a partially completed refactor leaving some items in a broken state

**Comment by Legends0** [comment]
This is not just a visual error either. The fertilizers are all putting the same amount of nutrients into the soil.

**Comment by GophTheGreat** [comment]
+1 from the support queue:

"Why is the fertilizer not working, since the update?

All of the fertilizer, even the fillers, now have the nitrogen, phosphorus and potassium levels. Therefore we are unable to grow crops, because we can't fertilize the fields. I don't know if this has be brought to your attention, but a fix would be appreciated. 

Thank you"

**Comment by craig-jong** [comment]
ITS THE ATTACK OF THE STATIC Feat. missing templates
