### ISSUE TITLE
Water does not fill areas you want it to flow into

### ISSUE THREAD

**Issue by RodgerianGames** [StrangeLoopGames/EcoIssues#6713]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
I dug out a channel that i wanted to be filled by the river above it, i dug the blocks infront of the water out and watched it pour over the cliff and stop at the bottom

**Expected behavior:**
I was expecting it to fill the entire channel that i had dug out so that it could meet the river beneath.

**Actual behavior:**
The water had no movement once it hit the bottom of the cliff.

**Comment by RodgerianGames** [comment]
Or at least some form of water physics, I’m trying to make a nice bridge and river going through my
Village, and also give me farm some moisture,but the water won’t move!!

**Comment by MarjieAVolk** [comment]
If you place those bricks on the floor there as 'aqueduct' constructs instead, it should make the water flow over it.  But yes, a lot of people want better water flow features.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#171
