### ISSUE TITLE
Blank Names causing issues 

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6715]
People are somehow able to create names on Steam, apparently using some ascii chars that Eco does not recognize and can log in to the game with no name.  With no way to determine what that name is there is no way to get an ID using /whois

They cannot do anything with the player or remove them from the game

**Comment by MarjieAVolk** [comment]
I imagine these are '<' and '>' ?  If that is the case, then this will be fixed in the next major release I believe.
