### ISSUE TITLE
Minimap is not rendering world layers correctly

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#672]
![image](https://cloud.githubusercontent.com/assets/3536496/19700595/c3cee684-9aac-11e6-8ce9-b9cdcfa4fdb2.png)
Seems to show half of the regular terrain texture, half world layer

**Comment by stett** [comment]
Something is going wrong with assigning new textures to already loaded chunks. I bet this has to do with minimap chunk mesh caching
