### ISSUE TITLE
USER ISSUE: All Skills dev commands

### ISSUE THREAD

**Issue by SkyFoxEve** [StrangeLoopGames/EcoIssues#6725]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Type /allskills

**Expected behavior:**
game crashes

**Actual behavior:**
vCaught exception

<size=60.00%>Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.SkillScroll.OnUsed(ItemStack itemStack, Player player)
   at Eco.Gameplay.Systems.Chat.AdminCommands.AllSkills(User user)
</size>

**Comment by styles784** [comment]
I can confirm, tested multiple times with reliable crash

**Comment by zEverdeen** [comment]
+1 support

**Comment by MarjieAVolk** [comment]
Fixed in 7.3.1
