### ISSUE TITLE
EcoServer Stopped working-cannot start a new singleplayer.

### ISSUE THREAD

**Issue by Shyscraper** [StrangeLoopGames/EcoIssues#6729]
I saw that a dev noticed this problem being said on the steam forums, but it still bugs many people.

installed ECO, antivirus and firewall were turned off. veryfied if all files were there, steam said it is ok.

ran the game, no problem. tried connecting to a server, no problem. tried creating a new world: named it TEST, checked only allow friends to join, no collab. clicked start.
It threw me onto my desktop, with a message of "Program EcoServer stopped working"
the game did not crash, it was still opnened at load (trying to load did the same thing). tried every version, all the same. I have Win 8, but the bug seems to occur for every OS. found a Crash dump it created, but I seem to not be able to open it.

**Comment by MarjieAVolk** [comment]
🤔 Have you tried deleting the folder  '%APPDATA%\..\LocalLow\Strange Loop Games\ECO'?

**Comment by Shyscraper** [comment]
cannot find it.

**Comment by MarjieAVolk** [comment]
On windows it should be 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO'

**Comment by MarjieAVolk** [comment]
(The path I gave you above will only work if you copy paste it into the explorer search bar)

**Comment by Shyscraper** [comment]
it does not seem to find it.

**Comment by Shyscraper** [comment]
Plus the file names i have are a different language than english

**Comment by Shyscraper** [comment]
seems that i got it. deleted it n it still does the same

**Comment by MarjieAVolk** [comment]
Ah.  Well good, and also :'(

**Comment by MarjieAVolk** [comment]
Okay, you said you had found a crash file it produced.  Could you attach that?

**Comment by Shyscraper** [comment]
everything seems to have problem with that crash files file type

**Comment by MarjieAVolk** [comment]
What is the file type?  If you send it to a zip file, github will let you attach it.

**Comment by Shyscraper** [comment]
nope.

**Comment by MarjieAVolk** [comment]
What is the file type?

Is github not letting you attach it because it's too big?  If so, you could upload it to a file sharing site like Dropbox or Google Drive.

**Comment by Shyscraper** [comment]
nope. its not the size. its the file type

**Comment by MarjieAVolk** [comment]
For the third time, what is the file type?

As I said before, if you zip the file into a zip file, github will let you attach it.

**Comment by Shyscraper** [comment]
[Crash MissingMethodException 04103803.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1907530/Crash.MissingMethodException.04103803.zip)

**Comment by MarjieAVolk** [comment]
Okay thank you.

That crash means that you don't have the right version(s) of .NET installed. Steam is supposed to do that for you automatically, but our dependencies were set up wrong for a while.  It's possible if you update the game, it will start working again.

If not, try installing these:
https://www.microsoft.com/net/download/thank-you/net46
https://www.microsoft.com/net/download/thank-you/net35-sp1
