### ISSUE TITLE
USER ISSUE: no more reputation title

### ISSUE THREAD

**Issue by neyna** [StrangeLoopGames/EcoIssues#6730]
**Version:** 0.7.3.0 beta

All reputation title are N/A now ...

![image](https://user-images.githubusercontent.com/3091083/38134882-6698c530-3415-11e8-875f-15cd19e5570b.png)

**Comment by styles784** [comment]
I'm still seeing this on 7.3.1

**Comment by elfl0rd** [comment]
7.3.2 too, N/A

**Comment by bingliCheng** [comment]
how to fix this N/A?

**Comment by Deantwo** [comment]
It is supposed to say something other than "N/A"? Just figured it wasn't implemented, or that the leader had to set the titles.

Still only says "N/A" for me on version 7.4.6.

**Comment by elfl0rd** [comment]
yes, still bugged.

**Comment by D3nnis3n** [comment]
Color is there now, but that bug stayed :/
