### ISSUE TITLE
Delete Deed & Minimap (0.7.3.1)

### ISSUE THREAD

**Issue by Thineboot** [StrangeLoopGames/EcoIssues#6731]
I've claimed a plot in the wild using a Property Claim Flag.
Opened Deed >> *Split Plot to New Deed*.
Opened new Deed (1 plot) >> *Delete Deed* >> Chat: *Deed deleted. Any property on it still belongs to you and can be re-deeded in Minimap side panel.*

While Minimap tells me that I'm the owner of the plot there is no link or whatsoever in Minimap side panel - there are two *side panels*, right *World Layers*, left (newly added) *Markers*. The *link* in Minimap (bottom *[text] (owner: [...]) [coords]*) doesn't work, too.
I can't claim it by using another Property Claim Flag as expected.
I can re-deed the plot by using *Attach Current Plot* to an existing deed. But that's not what chat-message says - unless I am missing something.

![ecodeed](https://user-images.githubusercontent.com/4364842/38136287-bfc28dd2-341d-11e8-9cb5-5f5cea0b59f2.png)

**Comment by Thineboot** [comment]
A follow-up:
You have to move before text and color of the new deed are updated in Minimap.

**Comment by zEverdeen** [comment]
This was a function previously, now it is gone. Also true for 7.3.2.

**Comment by elfl0rd** [comment]
Interested too, need rework text string or return functional.

**Comment by WeaselDog** [comment]
We have made some significant updates to the property tool which handles splitting property now. Thanks for your contribution.
