### ISSUE TITLE
How to spawn AsphaltRampObject ?

### ISSUE THREAD

**Issue by lordmampf** [StrangeLoopGames/EcoIssues#6736]
How can I spawn AsphaltRampObject for example?

WorldObject obj= new AsphaltRampObject(); //Constructor is private
obj = WorldObjectManager.Add(obj, user, position, rotation);

**Comment by MarjieAVolk** [comment]
Well, you can use WorldObjectUtil.Spawn.  This takes a string, which is the type name.

**Comment by MarjieAVolk** [comment]
Okay I see, the constructor is explicitly private.  I don't thiiink that we need to do this.  Will check

**Comment by metachronism** [comment]
its explicity private to prohibit the creation of world objects manually.  should use the built in systems to spawn objects

**Comment by MarjieAVolk** [comment]
Or have I given bad advice?
