### ISSUE TITLE
USER ISSUE: All Servers Offline

### ISSUE THREAD

**Issue by SushySan** [StrangeLoopGames/EcoIssues#6738]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Install / Start / Join

**Expected behavior:**
Seeing my Servers or new ones, starting one, play the game

**Actual behavior:**
All Server Favs are OFFLINE, no new / other Servers are loading

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5211

We are working on a rewrite of the join server page, so we will likely not address this until that is released.  Should be soon, fingers crossed.
