### ISSUE TITLE
kick for inactivity while placing blocks (7.3.1)

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#6739]
building a floor for my basement with asphalt road blocks i keep getting kicked for inactivity when i log back in half of the floor i just placed isnt there

**Comment by ecoemmeck** [comment]
more info on this it may have something to do with the room volume as when i use asphalt road else where there is no lag and i don't get kicked for inactivity

**Comment by ecoemmeck** [comment]
https://www.dropbox.com/s/7tnb91cmgkdiu05/Game.zip?dl=0

i have included the save to see if it helps with fixing the issue
i was having the problem on the 1st level of my basement at coordinates 317,1039

**Comment by MarjieAVolk** [comment]
Does disabling stats help this at all, by chance?

**Comment by ecoemmeck** [comment]
i will test this out tomorrow when i get a chance.

however I'm beginning to think it might have something to do with the 139 stockpiles i have in my 3 levels of basement

each level of the basement has around 23000+ room volume

**Comment by MarjieAVolk** [comment]
Wow that is a lot of stockpiles

**Comment by metachronism** [comment]
assigning to john, room detection perf (shouldnt happen on any client thread)

**Comment by johnkslg** [comment]
Moved room scanning to separate thread, should be fixed! Thanks for the report
