### ISSUE TITLE
USER ISSUE: Foliage Flash with freeze

### ISSUE THREAD

**Issue by ParadoxedHope** [StrangeLoopGames/EcoIssues#6740]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Transition from a value of 1 to 1999 on the Y axis (Second map value), or vica versa

**Expected behavior:**
Foliage doesn't unload and reload, no lag spike

**Actual behavior:**
As you move across the threshold of '0' on the Y axis (Possibly same for the X axis), all of the foliage unloads there, there is a quick freeze and then the foliage reloads.

**Comment by ParadoxedHope** [comment]
If I cross this '0' boundary whilst pulling a large cart, the screen goes black until I exit pulling the cart.

**Comment by metachronism** [comment]
fixed with vehicles update
