### ISSUE TITLE
USER ISSUE: Can't connect

### ISSUE THREAD

**Issue by MigzGit** [StrangeLoopGames/EcoIssues#6741]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Open the game
Click on Continue

**Expected behavior:**
The server open and I can play

**Actual behavior:**
The server never open.

**Comment by MarjieAVolk** [comment]
What server are you trying to connect to with the continue button?  Is it your own game?  A LAN server?  Or a remote server?

In any case, as a workaround I would recommend that you try to connect to the server directly, without using the continue button.

**Comment by MarjieAVolk** [comment]
Closing due to no response
