### ISSUE TITLE
ECO & CPU temps

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6742]
On my system, that runs Battlefield1, Ghost Recon Wildlands and all the new games very well, I have noticed that ECO seems to be particular demanding on the CPU side.

While most games put the CPU at about 80 degree celsius, playing ECO on a dedicated server with like 20 people will make my CPU go as high as 98 degree celsius. Of course this can be reduced with a new paste for the CPU etc. but the gap between other games and ECO is still quite remarkable.

Is this as designed, due to some heavy workload, or is there maybe a missing optimization somewhere that creates extra CPU load? Is ECO doing hefty mathematical calculation? 

The only other app that drives my CPU close to ECO temperatures is "Prime95" in stress mode. 

![image](https://user-images.githubusercontent.com/37662083/38144368-bb1b76e6-3444-11e8-8317-511d6f867f3c.png)

**Comment by metachronism** [comment]
lots of optimizations since this report - should be considerably better now
