### ISSUE TITLE
USER ISSUE: Cannot run for Office for unkown reason just comes up with Organge bar across the top

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#6743]
**Version:** 0.7.3.1 beta

![snap2106](https://user-images.githubusercontent.com/29383891/38144580-37c72224-343d-11e8-8302-94c31e84d7f7.png)

before this update on this server i could run for office without any problems, if i try now all i get is an orange bar at the top of the screen (i think this is an error bar, but not seeing anything in it)

as can be seen from this Running for Office hasn't been any problem before
![snap2107](https://user-images.githubusercontent.com/29383891/38144650-96ba8dd4-343d-11e8-8059-7adf02d32856.png)

if i try clicking on the run for office i see at the bottom of the screen this
![snap2108](https://user-images.githubusercontent.com/29383891/38145468-61f3d61a-3441-11e8-9f4f-6d9d05067455.png)
thats all the information i can seem to find (oh and i'm doing this from inside the game)

**Comment by MarjieAVolk** [comment]
Wow, you are a real winner :P

This is the same issue as https://github.com/StrangeLoopGames/EcoIssues/issues/4094.  Still not much progress on figuring it out :'(

In terms of your specific situation, the most likely causes for the error are (a) there's a law preventing you from running, or (b) you are not logged in on the website.  FYI, the Citizenship law prevents 'proposing a vote', which includes proposing a law and starting a new election.  Also, if you close the tab and then re-open it with the button in-game, that refreshes your login information, which sometimes makes the error messages show up.

**Comment by MarjieAVolk** [comment]
Well, I suppose it's possible that there is also another issue with running for elections, if you think my reasons for it preventing you are not right.

**Comment by MarjieAVolk** [comment]
I will take another look at that too, actually.

**Comment by Conchipedia** [comment]
you were right as normal @MarjieAVolk 😄 retrying through the game again allowed me to Run for election, but still getting the issue of having to refresh the page for me to click on the button (maybe this last bit is just a Firefox thing)

**Comment by MarjieAVolk** [comment]
Oh sad, which button is this?  The Run for Office button?

**Comment by Conchipedia** [comment]
when i click Run for Office in game i get this page show up
![snap2121](https://user-images.githubusercontent.com/29383891/38285869-208da3dc-37ba-11e8-864c-0f3869d7627e.png)
when i click on the Run for office button i get this flash up then Disappear
![snap2123](https://user-images.githubusercontent.com/29383891/38285884-38d314b8-37ba-11e8-9a13-ccc912257fe0.png)
then it stays like this all dark
![snap2122](https://user-images.githubusercontent.com/29383891/38285896-51c8869c-37ba-11e8-8b37-54cfae774056.png)
but then i click refresh button in Firefox and then it all works normally

**Comment by MarjieAVolk** [comment]
Okay, this sounds like what this other person was reporting (https://github.com/StrangeLoopGames/EcoIssues/issues/6959), but with more details.

I will paste your post over there, thank you
