### ISSUE TITLE
Building horizontally in the sky (e.g. bridges) is too hard / dexterity based

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6745]
Currently:
In order to build a block next to the one you stand on, you need to go very close to the edge (actually you are already over the edge).

Problem:
It is not fun to build that way. Especially building long bridges is a dexterity based game-play where you constantly just "tip" the keys to not fall down. Doing that for a lengthy bridge is exhausting. 

Suggestion:
1) Minecraft has solved this issue by adding a specific functionality. When you hold SHIFT (sneaking) while moving against the edge of a block that has no block beside it, then you will move as far out as safely possible, without falling down. Once you would fall off the current block, your are blocked to enter the next field. 

2) But in a game like ECO, where we get cool machines, maybe a tool that actually places blocks in a row right in front of you would be a cool way to approach bridge building.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#168
