### ISSUE TITLE
USER ISSUE: Can use Farmers Hoe to remove a tree instantly

### ISSUE THREAD

**Issue by oopomopoo** [StrangeLoopGames/EcoIssues#6750]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. equip farmers hoe
2. click on the ground the tree is on 
3. tree disappears instantly, no loot drops		

**Expected behavior:**
not been able to dig the ground, giant tree in the way

**Actual behavior:**
tree disappears

**Comment by Legends0** [comment]
I believe this is also possible to do with a Road Tool.

If it is a tile that grows trees, in my experience, the tree that grows back is also invisible.

**Comment by craig-jong** [comment]
This is no longer possible.
