### ISSUE TITLE
Server: Player stays online

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#6752]
Some Player stays online in the world. When they are clearly offline. They cannot login anymore then!
Version 7.3.1

**Comment by MarjieAVolk** [comment]
Oh no, you're sure this is still happening in 7.3.1?  Thought it was fixed.

**Comment by D3nnis3n** [comment]
No longer happens here since 7.3.1.

**Comment by Sekor2600** [comment]
No it is still a Problem:

**Comment by D3nnis3n** [comment]
I just said it works for me.

**Comment by Sekor2600** [comment]
[https://lh3.googleusercontent.com/ygKHWrZzpm4haQ5rEWph25AyaIYvG4g3KBhHeeEV9x-l0HJz_wCPOAcgVLlUSZsPTLvpePQpXxOQp2MXl91IPLu45h7hyeZaG1U1yB4ohD9AilB2jrMUnbch6HHMeYWpABjDOn51RFyq9YyJPPIpcKO0Ul5SOaTPu3Yi4ubGStycl7uqOeJaPcyHeallYctgh-bvnBFUbazrOLUAi0zWNhwejUMmiipyjFhHmW9bmWnPUMm8VkGq9fZdQgNStbsv2ux0Dox2vYtbiup_rUTwYgORxBR7_W08QYXJy48c-cp6wXp1AfFy6E1all_5Uq_LLuRQ3fVqgTCda_YB_GIxj1vqSXvTWTER6AqZHU-7UQonM0_chTk95XJ0OW_f_IrlULI96e83voZ-GKjzB4WXHeG9pvVFwqNNomT719CrO5nVvbFJe2AJ1UsSG3sG_gfAX0Svnb_J8Z6tE9-QgTyjlq1NOY9WwHoDnxpYiwYknVUNxxty5Vezl_hR_RqCi3VIyzdJ1v-jwgT125TPUTWt-2v7V_Kl7onCpE20nT8uNnE0RINJmWnxodSz2T8DMZeMjdPKY99uZyT2eLXh-0lv5_qui4xLIOdSkj9L0b4=w282-h220-no](url) the 3 Person are not online ingame
