### ISSUE TITLE
USER ISSUE: Glass completely broken

### ISSUE THREAD

**Issue by PrincessCady** [StrangeLoopGames/EcoIssues#6755]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Launch the game.

**Expected behavior:**
Glass should be there, especially the ones already used in buildings.

**Actual behavior:**
Glass blocks used in buildings completely disappeared. Houses aren't recognized as such anymore. New glass blocks are big white blocks without graphics. Tho this doesn't affect windows out of different material and framed glass. Tried restarting game + server, checking config settings and also creating new glass blocks. None of the options was successful.

**Comment by MarjieAVolk** [comment]
In this version, we updated glass to be placed with the hammer, like other construction materials.  It was supposed to be migrated to the new block type, but sounds like there is an issue with that.

**Comment by PrincessCady** [comment]
Thanks, I hope this can be fixed :) It's not important to get the glass back that was placed even tho it was more than 200-300 blocks. As long as it's something that won't cause too much trouble. Thanks for the quick reply!

**Comment by craig-jong** [comment]
Sounds like there was a problem with your server update. Make sure your the glass.cs in both Mods/AutoGen/Items and Mods/AutoGen/Forms are up to date.

If you have a backup of your server before migration, you might want to reload that and remigrate it after ensuring the new glass.cs files are in place.

Are you hosting the server yourself or are you running through a server provider?

**Comment by PrincessCady** [comment]
We are running a server through a server provider (nitrado). I will give the information to another server admin tho, so maybe we can still fix this issue. Thanks for the answer, this is really helpful!

**Comment by craig-jong** [comment]
Yea, I saw the same issue on another Nitrado server.

I would just try reinserting a fresh copy of the mods folder into your server and replacing the files.

**Comment by geeknessfr** [comment]
We had the same issue on our Dedicated Server based on a real Windows Server 2012, and the problem came from the Steam Update... We had to reinstall a fresh install of the server with a world saved backup to correct the issue.
Now glass works fine. I think the Steam update was partially done...

**Comment by PrincessCady** [comment]
Thank you all for your help! 
We managed to fix the issue thanks to you all and glass is working again!
