### ISSUE TITLE
Hard to not miss private chat message

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6759]
Maybe it can make a little "beep" or something?
Communcation is vital in ECO, yet you have only that one chat window, that probably most people not watch.

**Comment by MarjieAVolk** [comment]
Yeah you are totally right >> Most people don't use the PM or channel features much I don't think, so I was wondering when we would get a complaint lol

**Comment by Dreepa** [comment]
PS: 

1)Also, the PM channel is taking the global settings for "crafting/login/auth/ etc" messages. So when you actually see that you have a PM, by that little number in brackets behind the name, you have to manually dig through the spam to find the message. 

I would remove those messages from the PM channel for the time being. To make them configurable per channel would mean a lot of work on the GUI end I guess.

Also
2) Best practice: PM messages are purple color and start with <Name> is whispering you:"<Text>"

**Comment by MarjieAVolk** [comment]
Nah it shouldn't be too hard to split the notifications out elsewhere.  I would love to do this in fact.

**Comment by beastyn** [comment]
Will solve it with redesign #20853
