### ISSUE TITLE
Plastic, Steel Ceiling Light and Steel Table Lamp have no icon, but instead a template icon

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#6760]
At least plastic had an icon the version before.

**Comment by Kevster92** [comment]
![2018-03-30](https://user-images.githubusercontent.com/37886410/38154985-6a531a4e-3475-11e8-98d2-62edb9bcfcbe.png)
![2018-03-30 2](https://user-images.githubusercontent.com/37886410/38154986-6bc2fc3c-3475-11e8-9234-0e9da313100f.png)
![2018-03-30 1](https://user-images.githubusercontent.com/37886410/38154987-6dd410d8-3475-11e8-9d4e-92e62cda0df2.png)

Glas has no texture

**Comment by keegan-o** [comment]
fixed in master hopefully for 7.4
