### ISSUE TITLE
No Room in Destination Inventory - but there is room

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#6761]
See the screenshot, i want to buy one of these vegetables but it says no room in destination inventory - depsite i clearly have three free slots and can carry enough as of weight.

<img width="1716" alt="noroom" src="https://user-images.githubusercontent.com/25908592/38152087-371d9410-3466-11e8-8342-248ffa6a8a44.png">

**Comment by D3nnis3n** [comment]
Okay, my weight bar is not on the screenshot, unfortunatley, but it's at 1/20 and perfectly green.

**Comment by Skipachu** [comment]
It says a beet is 0.15, but the total sale is 50.15. You have other things selected to buy. You should scroll up and set the quantity for other items to 0.

**Comment by D3nnis3n** [comment]
There is nothing else selected.

**Comment by MarjieAVolk** [comment]
Ah good catch, the cost summary definitely indicates that something else is selected to buy.  (Or perhaps you are selling something with negative cost?)

If you really have nothing else selected... I guess there is something wrong with the store?

**Comment by Dreepa** [comment]
The important question would be: Is it reproducible and if yes, what are the steps to make it re-occur?

**Comment by D3nnis3n** [comment]
I had some salmon selected before, but unselected that by typing 0 and pressing enter. Then i put 1 into beets and wanted to buy them. Not possible, maybe because it thinks salmon would still be selected.

**Comment by MarjieAVolk** [comment]
Okay, I will investigate that.  Thanks.

**Comment by D3nnis3n** [comment]
Could not reproduce this issue anymore on any occasions.
