### ISSUE TITLE
Spieler Online, obwohl diese Offline sind

### ISSUE THREAD

**Issue by RobkaGer** [StrangeLoopGames/EcoIssues#6765]
Spieler werden als Online angezeigt, obwohl diese Offline sind.

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/6627

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6672

We thought this was fixed in 7.3.1 - but it was not.  It should be fixed in the next hotfix.
