### ISSUE TITLE
0.7.3.1 Server issue: Conversion to new format happening on every load

### ISSUE THREAD

**Issue by Caledorn** [StrangeLoopGames/EcoIssues#6766]
Version: 0.7.3.1 beta

Steps to Reproduce:
Load the savegame attached in this link: https://drive.google.com/open?id=1ggQU22yYGV4ZKpt8V5-i92dDwzeISZTM

Expected behavior:
Should not try to convert on every restart when the server version consistently has been 0.7.3.1 after I upgraded.

Actual behavior:
ECOServer.exe tells me that it is doing a conversion of the world to new save game format every time I restart it.

**Comment by metachronism** [comment]
craig need to use IsOlderVersion not compare with <

**Comment by metachronism** [comment]
fixed!
