### ISSUE TITLE
Law Item and Object List Incomplete

### ISSUE THREAD

**Issue by gForston** [StrangeLoopGames/EcoIssues#6767]
On my server rental from PingPerfect and my local game I have incomplete lists of options for selecting items or objects when creating a law.  I have tested with both Chrome and Edge browsers.  I have attached screenshots of the result from the above server and then from the server "Eco Friendly Server - 4KM World - All Welcome!" @ 76.23.204.133:3001
From my servers via Chrome
![image](https://user-images.githubusercontent.com/37942484/38154128-46d237ee-3425-11e8-8066-2cbcc7342505.png)
From the Eco Friendly Server via Chrome
![image](https://user-images.githubusercontent.com/37942484/38154285-173010b4-3426-11e8-8ea5-084fbf89980b.png)

Please help!

**Comment by MarjieAVolk** [comment]
These lists will only show items that have been discovered by the server - that is, items which either can be found in the world, or which someone has researched how to craft.

**Comment by gForston** [comment]
Wow!  Didn't know that.  Thanks!
