### ISSUE TITLE
How to check server status

### ISSUE THREAD

**Issue by norfair00** [StrangeLoopGames/EcoIssues#6769]
Hello,

I am looking to get server statu with the number of connected players.

**Comment by MarjieAVolk** [comment]
You can type /players to see who is online.  In the server window, you can also see this information at the bottom of the Network tab.  (If your server window is not open, you can open it by typing /openserverui)

**Comment by norfair00** [comment]
From query or other.
For my status page.

**Comment by MarjieAVolk** [comment]
Ah, you want a web api to look it up?

**Comment by MarjieAVolk** [comment]
In that case, you can query /info - one of the fields returned it "OnlinePlayers" (just the number, not the usernames)

**Comment by norfair00** [comment]
Thanks man
