### ISSUE TITLE
USER ISSUE: Food is consumed when stomach is full

### ISSUE THREAD

**Issue by ClarkyMacLeod** [StrangeLoopGames/EcoIssues#6771]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
1. Eat until your stomach is full.
2. Eat food wich exceeds your maximum calorie intake.

**Expected behavior:**
It should say: "Your Stomach is full" and don't consume the food.

**Actual behavior:**
Instead it says: "Your Stomach is full" and consumes the food.

**Comment by MarjieAVolk** [comment]
Fixed in 7.3.1
