### ISSUE TITLE
"View" function broken, marker placed instead

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6773]
I cannot do this a 2nd time, as I do not own the server, but here is what happened:

1. -DELETED- (Being World leader is not required for getting this bug)
2. Open a menu where you can "view" a location (e.g. contracts -> transport -> pick -> View)
3. Click on view

-> Notice that the map is not jumping to the location, but instead a world marker is created, named after the object.

Select "view": 

![image](https://user-images.githubusercontent.com/37662083/38156982-b3bd7ed8-3482-11e8-9557-d3f0783036b2.png)

Notice the new marker, but no map jump:

![image](https://user-images.githubusercontent.com/37662083/38155733-947d97d2-3479-11e8-9955-85308c443b15.png)

**Comment by Dreepa** [comment]
No longer an issue.
I do not know why it vanished. Very strange. Sorry, no repro.

**Comment by Dreepa** [comment]
And the issue is back again. I cannot see a pattern. Seems random.

**Comment by WeaselDog** [comment]
Fixed in latest version
