### ISSUE TITLE
Server crashes after 20 minutes. Lose materials.

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#6774]
http://steamcommunity.com/profiles/76561198036748973/recommended/382310/

- Server crashes -> Past 15 to 20 minutes of gameplay is gone. But your expended materials are not refunded. Event source this♥♥♥♥♥♥please.

**Comment by metachronism** [comment]
server saves every 60s.  Unless they changed default settings, this can't happen

**Comment by MarjieAVolk** [comment]
Sounds like some things got saved and others didn't.  Is there some section that's not getting saved on this save loop still?
