### ISSUE TITLE
Game frame rate is too slow.

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#6775]
http://steamcommunity.com/profiles/76561198151463341/recommended/382310/

It isn't able to start up if you dont use version 7.1.2 , but it also says you need at least 2GB RAM i have 4 and the game still lags like crazy, do not recommend
________________________________________________

http://steamcommunity.com/profiles/76561198151463341/recommended/382310/

I have all the recomended settings and no matter what I do, it still give me 14-15 frames a second. This is a brand new computer too. And this game just isnt as fun as I thought it would be. **IF YOU HAVE A WINDOWS COMPUTER THAT IS AT THE RECOMENDED SETTINGS, HIGH CHANCE IT WILL BE LAGGY* I do not recomend this game.

__________________________________________________

http://steamcommunity.com/profiles/76561198000692879/recommended/382310/

This game runs at lower framerates on the lowest possible settings than Ark runs on near maximum settings. That's so bad it's almost impressive.
__________________________________________________

http://steamcommunity.com/profiles/76561198315771603/recommended/382310/

its too laggy and theres no way to express your house in a creative way or form.
__________________________________________________

**Comment by raykai** [comment]
+1 for 
"http://steamcommunity.com/profiles/76561198036748973/recommended/382310/

When I open up a chest or anything really, it takes around 10 seconds for the UI to appear. Just one long 10 second wait while everything is frozen. Jesus I'm not streaming a movie I'm just viewing my inventory. This makes me want to keep interaction with anything that opens a UI to a minimum."

im having the same prob...

**Comment by metachronism** [comment]
this issue is way to broad, need more specifics to actually fix something.  game is always going to be continue being optimized

**Comment by metachronism** [comment]
closing, this is not useful as a bug - this is an infinite task
