### ISSUE TITLE
7.3.1 Ownership Bug

### ISSUE THREAD

**Issue by GillyGills** [StrangeLoopGames/EcoIssues#6776]
Every time I try to play Eco, it tells me that "User Does Not Own Eco". This is probably a glitch due to an anti-piracy change over 7.3.1. I am playing Eco through the steam family sharing system, so that may be where proposed the lack of ownership stems from.

Edit: It seems this bug only occurs when logging into servers, but not when playing alone

**Comment by Ellilka** [comment]
Hi! I have the same problem, and am in the same situation. It's verry embarassing because my community are waiting for my food, i already played, maked a house, a job and co. Please help. :/

**Comment by MarjieAVolk** [comment]
Sorry about that.  I will get someone to help you.

**Comment by Nanders** [comment]
This sounds like a web-side issue @rainfarmer

**Comment by rainfarmer** [comment]
Does turning off family sharing fix it?
For a quick fix, if should work from our website version of Eco.

@GillyGills whats your eco username? I'll check your account.

**Comment by Nanders** [comment]
We do not support family sharing
