### ISSUE TITLE
Exception when disconnecting

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#6777]
![image](https://user-images.githubusercontent.com/23460210/38156718-f1ff45d0-3434-11e8-85be-2c824444f29b.png)

**Comment by MarjieAVolk** [comment]
You know, this may or may not be related, but after I saw this I tried to reconnect as another user (require auth turned off on server and client), and started seeing connection failed repeatedly.

**Comment by metachronism** [comment]
this exception is caught though, and expected

**Comment by MarjieAVolk** [comment]
Okay.  Just started seeing it when I didn't before.  Though I think I have reported this and had it closed at least once before lol
