### ISSUE TITLE
Recipes are changing too often

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#6779]
http://steamcommunity.com/id/arpehem/recommended/382310/

Quit changing the ♥♥♥♥ing recipies! I queue all I need for a 24h craft before going to bed and when I come back I realyze that plastic does not produce barrels anymore (out of the ♥♥♥♥ing blue) and that I'm not ♥♥♥♥ing done yet! I can take bugs but tell your game designer to stop ♥♥♥♥ing with the ♥♥♥♥ing tables, make his mind up and stick to it!

**Comment by MarjieAVolk** [comment]
I thought changing recipes wouldn't affect existing work orders?
