### ISSUE TITLE
prioritize new objects based on distance to player ( Object / doors load slow on login)

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#678]

**Comment by noblackthunder** [comment]
This gets duped because title is not user friendly to search. I edit so it will be easier

**Comment by noblackthunder** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/678

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/2239/objects-loading-after-entering-game-takes-a-long-time
