### ISSUE TITLE
Unable to look around using the mouse

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#6781]
From the support queue:

After upgrading to 7.3.0 I have been unable to look around in game using the mouse. Hitting tab I
can move the cursor interact with menus, etc. If I hit tab again I can perform all actions except look around using the mouse including left click to perform an action.

I have tried reinstalling, rebooting, clearing App data, /unstuck, windowed mode, restoring defaults. All with no luck.

The only way I have found to correct this is by forcing the game back to 7.2.5 via Steam. After which the issue goes away and I can look around using the mouse like usual.

Specs (incase they are needed):
Windows 10 64x
Intel i7-4790k
16gb ram
Nvida gtx970
Logitech G900 mouse - firmware 1.3.21

Let me know if there is any further information you may need.

**Comment by Dreepa** [comment]
I had the same effect once, when leaving an excavator which shovel was stuck in terrain.

**Comment by GophTheGreat** [comment]
An update from the first guy:

"Just wanted to send an update. Either 7.3.1 or disabling my av/firewall seems to have corrected the issue. All appears to be working as normal now."

**Comment by MarjieAVolk** [comment]
How could a firewall affect this?

**Comment by vgmohag** [comment]
I have the same problem. 7.3+ I can't look around.  Just loaded the newest and same issue.  Im still playing on 7.2.5 which I can actually play

**Comment by vgmohag** [comment]
OK I have to report back.. I use Comodo AV.  Disabling the antivirus did not help... However when I disabled the 'auto containment' feature I am able to look around... so problem solved.  There are so many files in the containment folder... nothing obvious.. most of them dll's in the windows folder.  Nothing from the game folder.
