### ISSUE TITLE
USER ISSUE: Not authorized to add items when buying in a store.

### ISSUE THREAD

**Issue by fremenusul** [StrangeLoopGames/EcoIssues#6782]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Click on store
Try to purchase an item
Get message "Not authorized to add items"

**Expected behavior:**
Should be able to buy something, i'm not adding anything

**Actual behavior:**
Get the error.

**Comment by MarjieAVolk** [comment]
Is the store attempting to place the items directly into an object that belongs to you?  Maybe a cart?

**Comment by fremenusul** [comment]
I have no idea. I don't believe so. I have no cart nearby

**Comment by PieShade** [comment]
I've had this happen to some stores. All of the stores that this happened at, had storages that I owned linked to it. 

**When I unlinked the storages, I could buy items again.** Relinking the storages didn't reproduce the problem, though.

**Comment by MarjieAVolk** [comment]
Yeah okay.  I think I know the issue, it's because now the store is acting as if it is the store owner player, and that player doesn't have auth on your linked storage.  I will look into it.

**Comment by MarjieAVolk** [comment]
Fixed in next hotfix
