### ISSUE TITLE
Programmatic "muting" of Recipes (and or items) (Suggestion)

### ISSUE THREAD

**Issue by valheran** [StrangeLoopGames/EcoIssues#6788]
This is a suggestion mainly aimed at the making of mods. Currently, it appears the only way to remove or modify existing recipes or items is to edit the respective entries in the Mod directory. This could be a bit clumsy from a deployment perspective, especially if you want to be using multiple mods that may or may not want to interact with the same recipe/item.
Is it perhaps possible to have a method in the base class (ie for the recipe) that makes it work the same as the [Hidden] attribute, such that a mod could "reach out" and turn off the selected recipes, or perhaps some sort of config file that contains all the class objects to ignore.

An example usage would be to "mute" the "Smelt Copper" recipe in order to force the use of a mods processing chain that may be more difficult than the blast furnace method. Another may be to "mute" similar recipes in 2 cooking mods

**Comment by metachronism** [comment]
moving this to EcoSuggestions
