### ISSUE TITLE
Clicking A Player That is Online On The Minimap

### ISSUE THREAD

**Issue by PerksPrisoner** [StrangeLoopGames/EcoIssues#6790]
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1865180/error.log)

[crashdmp.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1865181/crashdmp.zip)

**Comment by MarjieAVolk** [comment]
You've got' KERNELBASE.dll caused an Access Violation' -- Based on what I found via google, this seems to be a platform level error and not a problem in our code. Some suggestions I saw were (a) you ran out of RAM (sooo make sure nothing else is running I guess?), (b) restart your computer.
