### ISSUE TITLE
Bunchgrass not affected by Grassland Gatherer in 0.7.3.1

### ISSUE THREAD

**Issue by Legends0** [StrangeLoopGames/EcoIssues#6792]
**Version:** 0.7.3.1 beta

As of 0.7.3.1, Bunchgrass on my server has stopped giving 4 plant fibers for level 5 grassland gatherer and now gives 2 plant fibers, despite being yield 2. Grass does not seem to be affected by the patch update.

**Steps to Reproduce:**
Check with Soil Sampler the yeild of the Bunchgrass and see that it has yeild of 2 and 100% maturity. Harvest with Stone Scythe.

**Expected behavior:**
Receive 4 Plant Fibers plus random chance of Bunchgrass seeds.

**Actual behavior:**
Receive 2 Plant Fibers plus random chance of Bunchgrass seeds.

**Comment by craig-jong** [comment]
Did it ever give 4 plant fibers? Sounds like bunchgrass is just busted. I'll look into it.
