### ISSUE TITLE
Logged in players 0.7.3.1 Beta

### ISSUE THREAD

**Issue by darkshad9999** [StrangeLoopGames/EcoIssues#6794]
Version: 0.7.3.1 beta

Steps to Reproduce:

1. Log into the the 0.7.3.1 Beta server
2. Type /players

Ok so I know that the developers have said that this was fixed in 0.7.3.1 Beta 
but it doesn't appear that it is. 

https://github.com/StrangeLoopGames/EcoIssues/issues/6672

https://github.com/StrangeLoopGames/EcoIssues/issues/6627

https://github.com/StrangeLoopGames/EcoIssues/issues/6722

"Fixed in 7.3.1 (#6672)"
"MarjieAVolk closed this 14 hours ago"

Expected behavior:

It should show players that are only actually online.  Not people who had logged in
in the past and had already logged off it is 1:51 AM MST (GMT-0700) here and 
no one else was online on this server it is a small server.  It is still showing people 
logged in even though they are not. 

I am on a 0.7.3.1 Beta server right now and the problem still exists and running
the 0.7.3.1 Beta client as well which is the latest. 

To me it looks like this issue isn't resolved and will have to be revisited again
because it is still occurring in 0.7.3.1 Beta

People have logged in and then it never updates when people are logging out. 

Now when I first go to log in it says 0 players connected on the screen
before you click continue.  But when you get into the game it is showing there
are more players connected that really are not. 

In fact I can 100% tell you that this still is not working right because I log into an alt
account and then I log out of the alt account and log into my main account and
10 minutes later if I do a /players it still says my alt is logged in.

This is something that still needs to be looked at it is still not working
properly and hasn't been fixed in 0.7.3.1 Beta.

![eco players logged in march 31 2018](https://user-images.githubusercontent.com/4023976/38161040-f60bd42c-3484-11e8-8161-7421f8b42de3.jpg)

**Comment by MarjieAVolk** [comment]
Should be fixed in the next hotfix (For real this time)

**Comment by darkshad9999** [comment]
any idea when 7.3.2 will be released? I will keep an eye out for this bug when it comes out and I will see if it fixed or not.. if not another ticket will be opened I guess LOL Thanks for looking into the problem.

**Comment by MarjieAVolk** [comment]
It's likely that it will be tomorrow, but I am not sure.  I will check in with the build person.
