### ISSUE TITLE
USER ISSUE: Geringe FPS

### ISSUE THREAD

**Issue by JannLP** [StrangeLoopGames/EcoIssues#6795]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Ich habe Seit dem letzten Update maximal 28FPS

**Expected behavior:**
Ich habe Seit dem letzten Update maximal 28FPS

**Actual behavior:**
Ich habe Seit dem letzten Update maximal 28FPS

**Comment by PermanentEdding** [comment]
Support Anfragen müssen auf englisch geschrieben werden.

**Comment by MarjieAVolk** [comment]
Es ist in Ordnung, wir können Google Translate verwenden. XD

Schließen als Duplikat von https://github.com/StrangeLoopGames/EcoIssues/issues/6957
