### ISSUE TITLE
USER ISSUE: Removed trunks still there

### ISSUE THREAD

**Issue by Praxxley** [StrangeLoopGames/EcoIssues#6796]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1.Chop down an acorn tree.
2.Remove the trunk
3.Try to plant e new acorn tree

**Expected behavior:**
Trunk should be gone, tree should be planted	

**Actual behavior:**
The trunk somehow is still there but invisible - the "chop" command still appears and I can do this all day long. I can dig the dirt underneath away and place it again. Hitbox is still there. Reloging didn't fix it.
If I try to plant at the edge of the dirtblock it works to plant a new tree

**Comment by MarjieAVolk** [comment]
When you say you removed the trunk - you just chopped it up and picked it up, as normal?

**Comment by SeanAtr0n** [comment]
duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/4908
