### ISSUE TITLE
USER ISSUE: DestroyBranch Exception

### ISSUE THREAD

**Issue by Redblueflame** [StrangeLoopGames/EcoIssues#6798]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Play the server

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60,00%>Object reference not set to an instance of an object.

   at TreeEntity.DestroyBranch(Int32 branchID)
</size>
```

**Comment by MarjieAVolk** [comment]
This has been fixed on the most recent release :)
