### ISSUE TITLE
USER ISSUE: Food wasting

### ISSUE THREAD

**Issue by ReverseZoom** [StrangeLoopGames/EcoIssues#6802]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Eat enough to have your calories high enouth, to not being able to eat anymore
2. Try to eat more

**Expected behavior:**
The character should have not been able to eat it, because the calories were too high. (I had 4700/5000 calories and tried to eat some thing with 450 calories)

**Actual behavior:**
Instead it ate it, I got 0 calories added and the food disappeared

**Comment by MarjieAVolk** [comment]
This should be fixed in the next hotfix.
