### ISSUE TITLE
USER ISSUE: No sound on halving coal

### ISSUE THREAD

**Issue by SirPL** [StrangeLoopGames/EcoIssues#6803]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Find coal ore
2. Break it with (stone) pickaxe
3. Find a piece which can be halved.
4. Break the piece with pickaxe

**Expected behavior:**
Halving makes sound

**Actual behavior:**
Only whistle of pickaxe swipe is audible

**Comment by Nanders** [comment]
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4454
