### ISSUE TITLE
USER ISSUE: My world is cut in half

### ISSUE THREAD

**Issue by db72432** [StrangeLoopGames/EcoIssues#6804]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
When I load my saved file (solo server), at some point the world is cut in half (see screenshots). There is no floor anymore and when I try to walk on the floor that should be there (it was there for sure when I saved, my house was at this location), I start falling and never stop falling. I have to disconnect, but it does not fix the issue.

![screen](https://user-images.githubusercontent.com/2060457/38164093-47236d6e-34ff-11e8-9f53-1929ceadc8eb.png)
![screen](https://user-images.githubusercontent.com/2060457/38164108-a7bdf3a6-34ff-11e8-85fb-467afd6f904d.png)

**Expected behavior:**
Have continuity in floor.

**Actual behavior:**
The floor doesn't display and when I walk on it, I fall through the world

**Comment by ShaydenMac** [comment]
https://steamcommunity.com/id/cuntycuntfresh/recommended/382310/

"Played the game for less than an hour game has lots of bugs and not worth the thirthy dollar USD I would like a refund. I was walking back to my crafting bench when the screen turned blue and my player was falling my cords went to -13000."

**Comment by metachronism** [comment]
put in a fix for these collider issues

**Comment by ShaydenMac** [comment]
Followed up with Steam reviewer: https://steamcommunity.com/id/cuntycuntfresh/recommended/382310/
4/23/18
