### ISSUE TITLE
worktable room-requirements dont exist

### ISSUE THREAD

**Issue by panisch420** [StrangeLoopGames/EcoIssues#681]
Kiln, Quarry and Farmers Table in the same room.
Room has no logs or mortared stone.
All 3 worktables are functioning.
![screenshot_529](https://cloud.githubusercontent.com/assets/22756750/19724790/824d1ae2-9b82-11e6-8254-49052296cbf1.png)

**Comment by johnkslg** [comment]
Thanks for the bug report!

**Comment by panisch420** [comment]
the only requirement working right now seems to be on the "workbench" all the others i have (research table, quarry, carpentry table, kiln) dont have requirements. this is version 2.

**Comment by panisch420** [comment]
requirements for bakery oven are also working, including the chimney. (tho the information for the chimney requirement is only provided once you fulfilled the volume and material requirements, no way to learn about this sooner?)

**Comment by johnkslg** [comment]
Ah good point on the chimney, thanks!

**Comment by craig-jong** [comment]
duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/760

and fixed
