### ISSUE TITLE
USER ISSUE: List of connected people

### ISSUE THREAD

**Issue by erucquoy** [StrangeLoopGames/EcoIssues#6810]
**Version:** 0.7.3.1 beta

**Informations**
List of /players is cumulative and never delete the disconnected players

**Steps to Reproduce:**
1. Connect one player to a server
2. Connect another player to this server
3. Type /players (you get a list of 2 players)
4. Disconnect first (or second or both) player
5. Type /players (you get a list of this 2 players, connected or not)

**Expected behavior:**

**Actual behavior:**

**Comment by darkshad9999** [comment]
Ya this was already reported by me https://github.com/StrangeLoopGames/EcoIssues/issues/6794
And there is another ticket open about this as well https://github.com/StrangeLoopGames/EcoIssues/issues/6789

**Comment by MarjieAVolk** [comment]
Should be fixed in the next hotfix (For real this time)
