### ISSUE TITLE
USER Nico : Lan Server doesen´t work if the language is in German

### ISSUE THREAD

**Issue by SchrellaLP** [StrangeLoopGames/EcoIssues#6811]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
If the language is in German you can´t play together in Lan

**Expected behavior:**
It should be possible to play in Lan if the language is in German

**Actual behavior:**

It is not possible to play in the LAN if the language is in German

**Comment by Nanders** [comment]
Did you happen to get an error message when your LAN connection was failing?
Language should have no bearing on this.

**Comment by metachronism** [comment]
I believe the serverbrowser silently hides servers not set to the same lanuage
new server browser has filters for this, so closing this issue
