### ISSUE TITLE
ldd Eco.x86: not a dynamic executable

### ISSUE THREAD

**Issue by braiam** [StrangeLoopGames/EcoIssues#6816]
Steps to reproduce:

- Download eco client for linux from SLG websites version 0.7.3.1
- Unzip the file
- Set executable bit on binaries
- Execute using ./Eco.x86

What happens:

Shell reports `no such file or directory: ./Eco.x86`.

What should happen instead:

- Should execute the client as Eco.x86_64

**Comment by SeanAtr0n** [comment]
I was able to execute both versions... although what happened afterwards is less than ideal

I think you need to run the linux build through steam right now, there are some bugs with input if you try to run without steam

**Comment by braiam** [comment]
@SeanAtr0n version you used?

**Comment by braiam** [comment]
Running ldd produces the following output:

```
➜  eco chmod +x Eco.*                  
➜  eco ldd Eco.x86 
	not a dynamic executable
➜  eco ldd Eco.x86_64 
	linux-vdso.so.1 (0x00007fff3f1c6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5f94f57000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5f94d39000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5f94b31000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5f947ac000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5f94419000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5f94201000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5f93e47000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5f9515b000)
➜  eco 
```

This is version EcoLinux_v0.7.3.2-beta.zip.

**Comment by SeanAtr0n** [comment]
I was on 7.3.2-beta, ubuntu 16.04

maybe it didn't extract correctly for you?

**Comment by braiam** [comment]
```
➜  eco shasum EcoLinux_v0.7.3.2-beta.zip Eco.x86
799b93a3e15c37bae20d53cd9a8cc2b268e57c83  EcoLinux_v0.7.3.2-beta.zip
b9beca6976ad30e3e280e2b1b8bc1ec4f8cbc389  Eco.x86
```

What are your checksums @SeanAtr0n?

**Comment by braiam** [comment]
Ok, figured out what it was, I didn't have libc6:i386 installed on my system (there were only amd64 packages installed), which @SeanAtr0n had since he installed Steam. There should be a README on the file informing that libc6 needs to be installed on the system to execute another architecture binaries. Here's ldd output after installing libc6:

```➜  eco ldd Eco.x86 
	linux-gate.so.1 (0xf7f67000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf7f3f000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf7f20000)
	librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xf7f16000)
	libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xf7d98000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7c96000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf7c78000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7a9f000)
	/lib/ld-linux.so.2 (0xf7f69000)
```

Eco depends on the following binaries in the same architecture of the binary:

- glibc
- gcc-8 (provides libstdc++6 and libgcc1)

**Comment by SeanAtr0n** [comment]
sounds like this is resolved
