### ISSUE TITLE
The HTML interfaces are awful

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#6817]
They only work about half the time.

And I mean that links only work half the time, let alone the exposed behaviour they're supposed to provide interaction with.

Using javascript instead of HTML is wrong for basically all of the reasons. Links are links. You're supposed to know where the link goes when you click on it. This isn't just part of accessibility, it's not just that links are a part of the underlying structure of the internet.

Replacing them with javascript is bad practice. And it complicates the entire process. I can't tell you why the web portal isn't working because I can't get even the basic functionality, the functionality that there is literally no reason to program, to work.

**Comment by rainfarmer** [comment]
OK ya its a good idea.

What are you clicking on that is not working? Can you send errors from console?

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#166
