### ISSUE TITLE
constantly getting kicked out of friends server

### ISSUE THREAD

**Issue by NoctisFeles** [StrangeLoopGames/EcoIssues#6818]
hello
i have some issues with my friends server, i can connect to it but i get constantly kicked out of it randomly every 10 minutes and i dont know why. we tried everything to solve it but nothing helps.
i can connect, everything works fine but then i just get kicked out back to the menu out of nowhere. there's no particular action that could make it happen.
its weird because yesterday it was fine and then the update came, it was still working fine but then today it happened.

**Comment by MarjieAVolk** [comment]
Sorry about that!  Do you get any error messages when this happens?

**Comment by NoctisFeles** [comment]
No it just randomly happens :/

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by MarjieAVolk** [comment]
Okay.  So are you the only one who has this problem, on this server?  Also, is this over LAN?

**Comment by metachronism** [comment]
@NoctisFeles as a temporary fix, you can try turning off auth on your server (Users.eco, RequireAuthentication to false)

do you have any other logs the server is reporting perchance?

**Comment by BlazeGuy2** [comment]
@NoctisFeles are you still having this issue?

**Comment by BlazeGuy2** [comment]
Didn't hear back.  Closing issue for now, reopen if it comes up again.
