### ISSUE TITLE
No way to tell if market prices are in line

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6822]
Currently you have no clue as to get an idea where the market prices are on average, except for checking each store individually, if I am not mistaken.

Problem:
Players have no way to judge their pricing. Especially with such a brilliant money simulation, this would be so interesting for player to play around with. 

Suggestion:
Either add average prices ingame, or add it to the web server browser interface, so that player can select a certain good, and see how many were transferred, what price on average, peak and low end, so the market economy you already simulate very well can actually be judged.

**Comment by darkshad9999** [comment]
Well there is no average price though it varies from server to server and there is no way 
really to tell what the price should be this is something that has to be decided on the server
and that you setup yourself. 

I don't see any issue with the current system he way it is now for the markets.

**Comment by ecoemmeck** [comment]
you can also open the economy viewer to see what others are selling or buying and check your prices against them though this is limited to the current prices.

however in all markets its all about supply and demand so the average price is only relevant in close proximity

**Comment by Dreepa** [comment]
@darkshad9999 
You misunderstood the ticket. It is not about cross server average pricing. It is about price development.
Check EvE Online if you want a good example. 

@ecoemmeck 
Thanks for the heads up, but keep in mind I didn't come here for help. This is not a discussion forum, but  an issue and improvement suggestion tracker.

**Comment by Huntermeign** [comment]
Considering the game is about any and all things Ecosystems from ecology to ecosystem, creating a base set defeats the purpose of the function of the game as a learning tool.

**Comment by darkshad9999** [comment]
Dreepa the prices are going to vary from server to server and there is NO set price you can charge whatever
you can get for it.  This isn't  Eve online I played Eve online for a long time you can't even compare the two games.  I see absolutely no issue here with the current market system.  There is no bug or issue here with the current market system.

**Comment by Dreepa** [comment]
darkshad, wasn't it you that tried to lecture me that it is for the devs to decide and not for us?
And besides violating your own teachings, you still do not understand the ticket. You talk about a strawman argument. 
This is about seeing the market statistics of one single server. Has nothing to do with "server to server" prices nor anything with "set prices". 

And Eve Online is SPOT ON, because it uses regions, in which a fully player run economy defines any supply, demand and pricing, while those regions are not communicating with each other. 

Admittedly EVE Onlines features are totally over the top for ECO. This is way out of scope.

However, in ECO you just have one huge list with all market entries without being able to look at any particular item and see it's supply/demand/price development. Yet there are hundrets of statistics already in the web-interface. So the idea was to add item statistics to the web-interface as well.

**Comment by darkshad9999** [comment]
Dreepa it is about it being server to server because there is NO set prices in this game you sell or barter for stuff that you need.  There isn't any kind of set price what so ever.  Eve is not spot on for this game this is not Eve if you want to go play Eve then go play that game. This game has no set prices.  There is no issue what so ever with the current market system.

**Comment by Dreepa** [comment]
I never said ECO should have "set prices". Really don't know what you are talking about.

**Comment by MarjieAVolk** [comment]
A buy/sell history would be a good addition to the economy viewer.  Better search functionality on the economy viewer might help the issue also.

**Comment by johnkslg** [comment]
I will be adding some features for this soon!

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#165
