### ISSUE TITLE
Laws cannot just have "voting polls"

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6823]
Currently you cannot ask the populace of a server through a poll in the voting system, if I am not mistaken.

It would be very nice if the players could set up polls with the law system, that have no binding character, but act as opinion tool to what the majority wants.

**Comment by Huntermeign** [comment]
I feel like if we are going to do this then the option to vote neither should be required. Otherwise anyone could make a poll law that says option A. player cannot place land claim. Option B. P{layer cannot place land claim

**Comment by Huntermeign** [comment]
Then its pointless. Use chat or make a straw poll

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#164
