### ISSUE TITLE
USER ISSUE: Tree Stump bug

### ISSUE THREAD

**Issue by PermanentEdding** [StrangeLoopGames/EcoIssues#6829]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Chop down a tree, chop the tree stump, collision stays, texture goes away

**Expected behavior:**
Collision should go away with texture

**Actual behavior:**
collision stays

**Comment by MarjieAVolk** [comment]
We have fixed several bugs with invisible trees, phantom plants, etc, in 7.3.2, so this should be fixed
