### ISSUE TITLE
I'm being framed I tell ya! (Framed glass, not glass)

### ISSUE THREAD

**Issue by Huntermeign** [StrangeLoopGames/EcoIssues#6834]
When selecting framed glass to sell at a shop the Trades chat announces it as glass.

![image](https://user-images.githubusercontent.com/4082137/38172341-a1ca1ee2-3578-11e8-91da-f8eff391c4be.png)

![image](https://user-images.githubusercontent.com/4082137/38172357-f88ef25c-3578-11e8-9321-780d82c6f2de.png)

**Comment by MarjieAVolk** [comment]
Looks like a bad string in the csv

**Comment by MarjieAVolk** [comment]
Increasing priority because this should be super easy to fix.
