### ISSUE TITLE
[SERVER ISSUE] Duplicate connections

### ISSUE THREAD

**Issue by Last2Night** [StrangeLoopGames/EcoIssues#6836]
7.3.1
Players have their character dupes in the world. At some point people are simply unable to join the server anymore as they get stuck on Entering World. The only way to kill all the dupe connections is to restart the server.
![121212](https://user-images.githubusercontent.com/36459795/38172863-11ddcd08-3571-11e8-8ad3-5bd9738fad18.jpg)

**Comment by Dreepa** [comment]
Some observation that may be of interest:
I actually was able to connect after waiting for an eternity in the "Entering World" screen. I then actually saw my former character in the world right next to me. I also saw another player being in the world 3 times.

**Comment by Last2Night** [comment]
Dreepa is a player on our server, his observation represents an actual player's experience during this issue. My report should be combined with his when looked into.

**Comment by Last2Night** [comment]
It now plagues our server. I had to set up an auto restart every 2 hours script to fight this issue. Needs fixing ASAP.

**Comment by MarjieAVolk** [comment]
I think we already have a fix for this, but just gonna send it past @metachronism to double check.

**Comment by metachronism** [comment]
pending possible fix.

**Comment by Last2Night** [comment]
7.3.2 still happens. A player got disconnected 3 times in a row due to 'inactivity' and the server left a dupe avatar and a connection. Definitely not fixed.

**Comment by Last2Night** [comment]
@metachronism @MarjieAVolk 
7.3.2 still happens. A player got disconnected 3 times in a row due to 'inactivity' and the server left a dupe avatar and a connection. Definitely not fixed.

**Comment by Last2Night** [comment]
@metachronism @MarjieAVolk 
Here are my thoughts on the issue.
Ive been suspecting that the issue was being caused by certain player or players since a few players left to play on another server due to this issue and we stopped encountering it.
When I noticed a dupe connection, I immediately asked the player what did he do however no response followed, I immediately kicked that player from the server. The behavior of this issue looks very similar to DDOS attack only through the game. I have no idea whether he did it in purpose knowing that abusing this bug will lock the server up or simply have problems with his internet connection.
What I think might be a fix to this issue is adding a cooldown timer for reconnection attempts like 10 seconds or so. Even better, an option for server owners to set the cooldown in seconds.

**Comment by Dreepa** [comment]
From my side I can only say that it does not happen to me anymore, and it was happening 100% in 2h to me in 7.3.1

If that is worth anything.

**Comment by Sekor2600** [comment]
Yes still happens in 7.3.2 but less often from my point of view

**Comment by metachronism** [comment]
should be fixed in 7.3.3, also have a fix for the stuck entering world issue for 7.4
