### ISSUE TITLE
Lagging server

### ISSUE THREAD

**Issue by loaykr** [StrangeLoopGames/EcoIssues#6837]
I bought a VPS to start my server on so me and my friends could play without being abused be admins 
but the problem is we all get lag, ping from 900 to 3000, I tried to edit some stuff in config in order to fix the problem but the lag still exist

VPS specs
Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50 GHz 
2.00 GB RAM
64-bit windows server 2008 R2 Enterprise 
internet speed above 200MB

I edited these settings in eco config: wirtetimeout: 3000 readtimeout: 3000
storage saving: 3600
compression level: best speed

**Comment by Last2Night** [comment]
Just my 2 cents. 2GB RAM is way to low to host a game like ECO. Have you checked your server's hardware load?

**Comment by metachronism** [comment]
many optimizations since this report, going to close
