### ISSUE TITLE
USER ISSUE: Small trees that will never die!

### ISSUE THREAD

**Issue by barthy** [StrangeLoopGames/EcoIssues#6838]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
just try to cut them and they kick you out..
very good admins lol

**Expected behavior:**
it should DIE i mean disapears since they arent grown trees yet

**Actual behavior:**
Caught exception

<size=60,00%>La référence d'objet n'est pas définie à une instance d'un objet.

   à Eco.Simulation.Agents.Plant.Destroy()
   à Eco.Simulation.Agents.Tree.Destroy()
   à TreeEntity.Destroy()
   à TreeEntity.TryApplyDamage(INetObject damager, Single amount, InteractionContext context)
   à Eco.Gameplay.Items.WeaponItem.OnActLeft(InteractionContext context)
   à Eco.Mods.TechTree.AxeItem.OnActLeft(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>

**Comment by MarjieAVolk** [comment]
We believe this is fixed in the next hotfix (https://github.com/StrangeLoopGames/EcoIssues/issues/5619)
