### ISSUE TITLE
USER ISSUE: Small Trees that will never die! part 2#

### ISSUE THREAD

**Issue by barthy** [StrangeLoopGames/EcoIssues#6839]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
just tried to delete them with the devtool..

**Expected behavior:**
it should have vanished but i m the one that gets Vanished :P

**Actual behavior:**
Caught exception

<size=60,00%>La référence d'objet n'est pas définie à une instance d'un objet.

   à Eco.Simulation.Agents.Plant.Destroy()
   à Eco.Simulation.Agents.Tree.Destroy()
   à TreeEntity.Destroy()
   à DevtoolItem.OnActLeft(InteractionContext context)
   à Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   à Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
</size>

**Comment by MarjieAVolk** [comment]
We believe this is fixed in the next hotfix (https://github.com/StrangeLoopGames/EcoIssues/issues/5619)
