### ISSUE TITLE
USER ISSUE: Fishing

### ISSUE THREAD

**Issue by drblaui** [StrangeLoopGames/EcoIssues#6841]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Throw out fishing rod
2. Wait for fish to take the bait

**Expected behavior:**
the swimmer should dip down to show a fish hat taken the bait

**Actual behavior:**
the fish starts spinning like a living fidget spinner

**Comment by Dreepa** [comment]
The swimmer is hard to see, so just dipping it might actually be not easy to spot, especially if thrown a bit further out. So I would say, while the living fidget spinner is looking weird, it should still be something very prominent to see.

**Comment by SlayksWood** [comment]
merged to #11931
