### ISSUE TITLE
Colliders on Tree Leaf Clumps leads to not ideal targeting

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6843]
The hitbox for aiming at tree leaves is really weird. Trying to find the right spot that selects the leaves for interaction seems to be a luck's game.

As an example, see here how looking directly at the leaves does not hilight them.

![image](https://user-images.githubusercontent.com/37662083/38173823-56eb410c-35c4-11e8-84bf-b0e51f32e169.png)

**Comment by keegan-o** [comment]
I'm putting this on medium priority because for the leaves it's a matter of it's probably never going to be perfect, but I did make the sphere collider larger for cedar and birch to start. This should help.
