### ISSUE TITLE
Create github discussion section

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6844]
With the new players rolling in, I think you will more and more see tickets here that are more of a discussion nature.

Maybe it is a good idea to start a separate section, so tickets stay clean. The ticket could then be linked to the discussion, if necessary, and the ticket itself could be about the issue, while people could discuss their opinions in a linked thread.

**Comment by braiam** [comment]
Github has already methods to prevent these, mainly the "Lock" and "Temporary interaction limits". A mix of both would slow down the off topic conversation considerably.

**Comment by Dreepa** [comment]
Wouldn't you want to have people discuss it, as to have more perspective and angles on any one topic? I think it just should be in the right place. And since the old ECO forum, over at strangeloopgames is basically dead, where are those discussions supposed to happen?

**Comment by braiam** [comment]
I presume this is _not a forum_ but an issue tracker. Issue trackers is for tracking issues. The less the devs have to wade through off topic commentary, the more time available to fixing bugs.

**Comment by Huntermeign** [comment]
Eco Discord is the primary discussion area for all things Eco

**Comment by Dreepa** [comment]
braiam, that was the purpose of suggesting a place for discussion. To get it off the bug tracker. So we are on the same page. And in terms of project management, it is an entire valid issue to raise with regards to community management.

**Comment by MarjieAVolk** [comment]
Yeah I think Discord is our main discussion place these days.
