### ISSUE TITLE
0.7.3.1 Converting to new format on every server restart

### ISSUE THREAD

**Issue by Yorkforce** [StrangeLoopGames/EcoIssues#6845]
Just updated from 0.7.2.5 to 0.7.3.1 and every time our server restarts it is going through this process

Currently it's taking our server 40mins+ to restart

**Comment by Yorkforce** [comment]
Tried updating from 7.2.5 to 7.3.0 and got this:
https://pastebin.com/nw9MjDTX

So it's a catch 22, can't update to 7.3 to update to 7.3.1 to fix the conversion issue

**Comment by LiveTeXon** [comment]
same :/

**Comment by Last2Night** [comment]
Same issue. Although it only adds a couple of extra minutes to loading process, still shouldnt be like that at all.

**Comment by MarjieAVolk** [comment]
This will be fixed in the next hotfix (https://github.com/StrangeLoopGames/EcoIssues/issues/6766)
