### ISSUE TITLE
USER ISSUE: User is always displayed online

### ISSUE THREAD

**Issue by 42656e** [StrangeLoopGames/EcoIssues#6847]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Start server
2. Log in to server
3. Log out

**Expected behavior:**
The user gets displayed as offline in the "O-Menu"

**Actual behavior:**
Other users still see all users who logged in since server start as online

**Comment by styles784** [comment]
I am also seeing this issue - started with 7.3.0, continues on 7.3.1

**Comment by darkshad9999** [comment]
Been reported a couple of times now  in the following tickets 

https://github.com/StrangeLoopGames/EcoIssues/issues/6794
https://github.com/StrangeLoopGames/EcoIssues/issues/6789

**Comment by MarjieAVolk** [comment]
Should be fixed in the next hotfix (For real this time)
