### ISSUE TITLE
USER ISSUE: loading a world with linux client

### ISSUE THREAD

**Issue by SHOVELL** [StrangeLoopGames/EcoIssues#6849]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
load game(wait 1/2 hour for loading)
create new game
create new world

**Expected behavior:**
created a new world

**Actual behavior:**
The following error message popped up:
```
Could not start server: Object reference not set to an instance of an object
```

**Comment by MarjieAVolk** [comment]
Currently you need to run the server separately on linux: http://ecoforum.strangeloopgames.com:4567/topic/2984/setting-up-a-eco-server-on-ubuntu-other-linux-is-probably-very-similar
