### ISSUE TITLE
USER ISSUE: Water Downflow Physics Aqueduct

### ISSUE THREAD

**Issue by VitalSubdivision** [StrangeLoopGames/EcoIssues#6851]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Place an Aqueduct which goes down 1x1. And that a few blocks more 

**Expected behavior:**
Normally the water should just flow down the bricks/aqueduct

**Actual behavior:**
It stops after going 3 blocks down just if there was something blocking it

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/38333950-e45cf476-380e-11e8-80e1-eb9cdeac11c9.png)

I'm having trouble reproducing this.

Can you either send me a save where this is occurring or provide a larger screenshot/blueprint of how to set this up?

**Comment by craig-jong** [comment]
Or are you refering to this by chance?
![image](https://user-images.githubusercontent.com/18184943/38334026-178a2512-380f-11e8-8550-5f60abe44dc9.png)

**Comment by VitalSubdivision** [comment]
![20180404225238_1](https://user-images.githubusercontent.com/37982920/38334297-34d776b4-385b-11e8-97b1-2c3d92379ad4.jpg)

Its just more like whether I try to let the water stream flow like you did (so just a few blocks down in y-direction), or like i did in the screenshot the water stops flowing.

**Comment by craig-jong** [comment]
I think this might have to do with water "losing" water when moving down blocks. I'll test a few more things.

**Comment by craig-jong** [comment]
Okay, I think I was able to recreate it. Thanks for the screenshot.

![image](https://user-images.githubusercontent.com/18184943/38338168-3a4821b8-381d-11e8-8272-f0657720bd0c.png)

I'm not sure if there's an easy fix to this, but I'll look into it.
