### ISSUE TITLE
Placed on solid ground detection sometimes failing

### ISSUE THREAD

**Issue by tlobig** [StrangeLoopGames/EcoIssues#6854]
Ways to reproduce:
Place several combustion generators on solid ground

Expected behaviour:
All generators are recognised as beeing "placed on solid ground"

Actual behaviour:
Most of generators don't work as they are not recognized as beeing placed on solid ground.

edit: version 0.7.3.1
I couldn't see any significant difference between working generators not working ones. All seemd to be on solid ground. A possible workaround seems to dig up all the earth and place it back. When placing down generators that don't work afterwards there were decorative plants in the way. Just picking the generators up and placing them down again (plants now gone) didn't do the trick.

![grafik](https://user-images.githubusercontent.com/10432347/38176125-a9625c7a-35e9-11e8-829a-ffb0c0f4ef5f.png)
![grafik](https://user-images.githubusercontent.com/10432347/38176127-b3d95f82-35e9-11e8-9919-60b1a2a44c62.png)

**Comment by tlobig** [comment]
It seems by only digging up one tile from under the generator (and placing it back again) the failed solid ground detection is fixed. Works repeatedly to resolve the issue.

**Comment by styles784** [comment]
I had the same issue with a large rug placed on mortared stone - I had to change from the default basic (rounded) mortared block to the flooring-specific (perfect cube) block to get the rug to detect it as solid ground, so maybe that detail is significant?

**Comment by MarjieAVolk** [comment]
I believe that we have a fix for this, but assigning to @craig-jong to double check.

The issue that I know of was related to rotation - the check for solid ground would do the check as if the object was in its default rotation, instead of the current rotation.

**Comment by craig-jong** [comment]
Rotation is fixed.

Please reopen this if the problem continues past the latest release.
