### ISSUE TITLE
USER ISSUE: Solid Ground Street Lamps

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#6855]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Street Lamps on Asphalt roads have no Solid ground and are inaktiv

**Expected behavior:**
Lamp is shines and stay on Solid ground

**Actual behavior:**
have no Solid ground and do not light up

**Comment by elfl0rd** [comment]
Fixed.
![default](https://user-images.githubusercontent.com/4980243/41872074-87e874bc-78c9-11e8-9f12-df86ae6580ad.png)
