### ISSUE TITLE
USER ISSUE: Excavators

### ISSUE THREAD

**Issue by OrangeeAble** [StrangeLoopGames/EcoIssues#6856]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Get excavator
2. Have someone remove excavator
3. Jump at the excavator

**Expected behavior:**
Excavator should just meme out of exsitence instead of crashing the game for me.

**Actual behavior:**
The following error message popped up:
```
Caught exception

<size=60.00%>Nullable object must have a value.

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Eco.Gameplay.Players.Player.ShouldOverrideAuth(InteractionQueryInfo query)
</size>
```

**Comment by SlayksWood** [comment]
Checked on 8.1. Wasn't able to reproduce, seems fixed.
