### ISSUE TITLE
USER ISSUE: black screen

### ISSUE THREAD

**Issue by freschmeet** [StrangeLoopGames/EcoIssues#6861]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
no clue

**Expected behavior:**
not a black screen...

**Actual behavior:**
a black screen...

**Comment by SeanAtr0n** [comment]
black screen as in you can't do anything or were you in thirdperson and the camera got blocked?

**Comment by freschmeet** [comment]
Hi Sean,

I couldn't see anything at all. I could move around and the friends I was
playing with said I was moving, but I couldn't see a thing.

Thanks,
Mario

**Comment by elfl0rd** [comment]
Duplicate of #11226

**Comment by D3nnis3n** [comment]
Would you be able to contact me on discord so we could get a way to reproduce this issue? Add me on Discord via D3nnis3n#2053

**Comment by freschmeet** [comment]
This was months ago, Dennis. I don't play Eco any longer. Best of luck!
