### ISSUE TITLE
Suggestion: Blue print for Construction Skills

### ISSUE THREAD

**Issue by skeykc** [StrangeLoopGames/EcoIssues#6865]
This is an idea to effectively use construction contracts.
Or it is an idea not to make construction skills a simple game constraint.

It consists of two elements, Architecture (design) mode and blue print.
Each player freely designs the house in the architectural (design) mode.
It is the owner of the construction skills to complete the house.
Or, owners of construction skills can create and sell blueprints.

**Architecture (design) mode**
- In the architectural (design) mode, you can operate like Admin's Fly command
- All building blocks (shapes such as stairs) can be freely installed
- The created building can be saved as building data

**Blue Print**

- Copy archive data created in architectural (design) mode can be saved
- By using blue print, you can specify the location of the building shape (like when installing a work bench)
- At the stage of installation, only the virtual image of the transparent display is created
- When putting necessary building blocks for blueprints, they are materialized (as when putting materials into workbenches)
- When a block that requires construction skills is used, A player who owns that skill puts the materials in the blueprint

**Comment by MarjieAVolk** [comment]
This sounds pretty cool, so you could 'build' your own house but you would still need a specialist to come make it for you.  Best of both.  It sounds like a big feature though.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#163
