### ISSUE TITLE
USER ISSUE: Unable to Pickup Wooden Cart

### ISSUE THREAD

**Issue by jrgriffi** [StrangeLoopGames/EcoIssues#6867]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Create Wooden Cart
2. Place
3. Attempt to pickup

**Expected behavior:**
Pickup cart to begin pulling

**Actual behavior:**
Immediatly drop cart as if a physics bug. Small wooden cart works usually. 

Edit: Almost immediately after placing report, pickup the small wooden cart and it goes ballistic. I am now stuck flying through oblivion...

**Comment by MarjieAVolk** [comment]
Obviously, the cart should not fly around when you pick it up :P  But as to the original issue, were you out of calories when you tried to pull the cart?

**Comment by jrgriffi** [comment]
I was not. The original issue that prompted the bug was the instant dripping of the cart. That Issue cleared up since a disconnect but do still have the occasional freak out when I pull the cart in that same general area. Not near as bad as the time mentioned in the edit (where I flew into Oblivion) but I do go flying a few meters into the air or get thrown around a bit. The issue only seems to occur in one location on the map, though. Nothing stands out as "out of ordinary" in the location and it is flat ground. Wish I could be more help there.

-------- Original Message --------

**Comment by MarjieAVolk** [comment]
Okay, thank you.  Is the area where this happens near a 0 coordinate perhaps?

If this happens a lot in a specific place, could you send us your save file and the coordinates?

**Comment by jrgriffi** [comment]
For some reason my reply did not post. But what do you need for the save file? Also, This issue does not appear to have occurred again since then. On 7.3.2 now.

**Comment by oocx** [comment]
I have the same problem in 7.3.2. I can't use my Wooden Cart any more. It used to work in 7.3.1.

**Comment by MarjieAVolk** [comment]
The main thing we would want is the 'Game.eco' file, in the Storage folder.  (If you are playing a local world, it will be named the name of your world, .eco, in [...]\steamapps\common\Eco\Eco_Data\Server\Storage)

**Comment by MarjieAVolk** [comment]
If you zip it up, you can attach it to the thread here with drag and drop.

**Comment by WeaselDog** [comment]
There have been some physics updates and this seems to be fixed in the latest version.

**Comment by WeaselDog** [comment]
The flying cart is fixed. I merged the difficulty pulling in 7.3.2 with https://github.com/StrangeLoopGames/EcoIssues/issues/7087
