### ISSUE TITLE
Grass not disappearing when dirt is picked up

### ISSUE THREAD

**Issue by goobie** [StrangeLoopGames/EcoIssues#6869]
Sorry if this is a dup, I can't find any similar open tickets

Version: 0.7.3.1 beta

Steps to Reproduce:
Dig dirt with a shovel. Not exactly sure how this occurred, its the first time i've seen it. 

Expected behavior:
Grass on top of dirt should disappear.

Actual behavior:
Grass stays there. Replacing the dirt underneath and digging it again does not remove the grass. 

Reconnecting fixes it.

https://steamuserimages-a.akamaihd.net/ugc/921424381004245007/B6F16B0A417755CC60491DB15099CF9CC1753B67/

**Comment by metachronism** [comment]
closing as dupe/related to #5036
