### ISSUE TITLE
Unable to Harvest Sagebrush

### ISSUE THREAD

**Issue by Legends0** [StrangeLoopGames/EcoIssues#6870]
Version: 0.7.3.1 beta

Steps to Reproduce:
Find sagebrush. Attempt to harvest with Scythe.

Expected behavior:
Scythe is usable on Sagebrush since it gives Plant fibers and Sagebrush seeds.

Actual behavior:
Unable to select Sagebrush.

**Comment by craig-jong** [comment]
Sorry about how long this was a thing - should be fixed in the next release.
