### ISSUE TITLE
Wooden Fabric Bed overridden by Icebox to become Kitchen Room

### ISSUE THREAD

**Issue by Legends0** [StrangeLoopGames/EcoIssues#6873]
Version: 0.7.3.1 beta

Steps to Reproduce:
Place Wooden Fabric Bed and Icebox in the same room.

Expected behavior:
Room becomes bedroom. Wooden Fabric Bed is a 4 skill point bedroom item and should be ordered before the 2 skill point kitchen item, Icebox.

Actual behavior:
Room becomes Kitchen.

**Edit:** Cast Iron stove in place of Kitchen has the same effect. Current state of the game has the Wooden Straw Bed taking priority of the room if placed before Icebox.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#162
