### ISSUE TITLE
USER ISSUE: User experience and Dropping items.

### ISSUE THREAD

**Issue by ghost** [StrangeLoopGames/EcoIssues#6874]
This is a snippit from General Chat.

![edc0b7be2692e2c8c8d307c1c603db3e](https://user-images.githubusercontent.com/31023534/38184107-c0f1b280-3645-11e8-93af-15bcda9ae3d1.png)

If users do not have an easy way to drop or dump an item, but have to resort to potentially game breaking chat commands, then people might get caught dropping all their items, aka a deadlock.

Only users with enough experience will be able to dig themselves out of the hole a /dump could get them in.

If anything, the tutorial should mention that you cannot drop items, and maybe a few more tips that aren't intuitive.

On that note, here are some areas where I believe the tutorial could use some polish, as it is the first thing most users experience, it matters a lot that it does not create confusion.

A lot of users have issues with the wording of the last task. Actually, looking at the world marker with the camera and clicking on it with the cursor enabled is noneintuitive. It could be mentioning using TAB again to get the cursor.

![3299f305ead7d9c935596c3cfea61bdf](https://user-images.githubusercontent.com/31023534/38184447-14606658-3648-11e8-8a49-5d3fd9762209.png)

The dropmarker button is not showing by default, and having two different buttons to open a similar panel is not ideal. See picture:

![udklip](https://user-images.githubusercontent.com/31023534/38184587-00b97cd8-3649-11e8-896e-3469fe1663f4.PNG)

The buttons should be similar as they do the same function.

**Comment by MarjieAVolk** [comment]
Regarding dropping items, we are currently working on adding this.  I am not sure which release it will be in, possibly the next major release or possibly not.

For the other issues, assigning to @johnkslg

**Comment by D3nnis3n** [comment]
Implemented a long time ago.
