### ISSUE TITLE
USER ISSUE: Paper milling costs 2500pts

### ISSUE THREAD

**Issue by byPARSE** [StrangeLoopGames/EcoIssues#6875]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Loading an old game from "load". This games was created with 7.3.1 a few hours before.

**Expected behavior:**
Costs for "paper milling" in the exploration overview i think has to be 1-10pts like all other things to explore	

**Actual behavior:**
Cost is 2,500pts for "paper milling". That's not possible to get.

**Comment by MarjieAVolk** [comment]
Sounds like your specialty cost multiplier got turned up.  To fix it, you should type /openserverui, and in the window that opens go to the Difficulty Settings tab.  There, you can fiddle with your settings, or just revert them all to defaults by selecting an option from the presets drop down.  Assuming you are playing by yourself or with just a couple friends, you should probably select 'No Collaboration'.

**Comment by MarjieAVolk** [comment]
Closing due to no response
