### ISSUE TITLE
USER ISSUE: Asphalt road block randomly disapear

### ISSUE THREAD

**Issue by ThT12** [StrangeLoopGames/EcoIssues#6877]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. build Aspalt road in a forest on a solo server
2. disconnect from the server
3. reconnect

**Expected behavior:**
All constructed blocks should be here

**Actual behavior:**
Some blocks randomly disapeared

![road](https://user-images.githubusercontent.com/13810438/38190897-a4763b3c-3666-11e8-832c-8c6dc6f00d16.png)

**Comment by metachronism** [comment]
spreading the love - this is probably plant related, with the plants not correctly being deleted
(@SeanAtr0n 's recent sim save might have fixed this)

**Comment by SeanAtr0n** [comment]
should be fixed already in 7.3.3
