### ISSUE TITLE
USER ISSUE: Farming Visual Bug

### ISSUE THREAD

**Issue by cwells1298** [StrangeLoopGames/EcoIssues#6880]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Plant an item
Harvest It
Plant again

**Expected behavior:**
On planting, plant should always appear visually
On harvesting plant should always disappear visually

**Actual behavior:**
Some plants dont appear on planting and some dont disappear on harvesting, appears to be random

**Comment by metachronism** [comment]
related to #5036
