### ISSUE TITLE
[Client][Bug][0.7.3] USER ISSUE : only consume one fish

### ISSUE THREAD

**Issue by klhoest** [StrangeLoopGames/EcoIssues#6883]
**Version** 0.7.3.1 beta

**Steps to Reproduce:**
have more than 1 tuna in your inventory
go to your fishery
be at maximum level of fish cleaning efficency (don't know if it is important)
make an order of 3x clean tuna
link to video [https://drive.google.com/file/d/1c2QBMkOOMW1wVAb0rEtbjpY8wEUovP1a/view?usp=sharing](https://drive.google.com/file/d/1c2QBMkOOMW1wVAb0rEtbjpY8wEUovP1a/view?usp=sharing)

**Expected behavior:**
3 tuna should be consummed

**Actual behavior:**
only 1 tuna is consumed but the game thinks you have consumed 3

**Other scenario**
could also reproduce bug when ordering 4 salmon

**Operating system**
windows 10 64 bit
game bought on steam

**Comment by ecoemmeck** [comment]
it looks like you have efficiency's for the fish cleaning.
have you tired to do larger orders of say 10 or more?

**Comment by klhoest** [comment]
Ah you are right, it consume more than 1 fish when I order more than 10. It might not be a bug after all
