### ISSUE TITLE
USER ISSUE: Powerd Cart Screen

### ISSUE THREAD

**Issue by PermanentEdding** [StrangeLoopGames/EcoIssues#6884]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
While sitting on the powerd cart the screen is slightly tilted, its verry annoying for me.

**Expected behavior:**
Screen should be even

**Actual behavior:**
its tilted

**Comment by MarjieAVolk** [comment]
I think this won't be relevant, because of the aforementioned replacement of the powered cart.
