### ISSUE TITLE
USER ISSUE: Invisible Wall?

### ISSUE THREAD

**Issue by cwells1298** [StrangeLoopGames/EcoIssues#6885]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Loaded into game after a crash

**Expected behavior:**
Allowed me to walk around freely and grab my cart

**Actual behavior:**
there was a roughly 10 by 10 area which looked like flat ground with my cart on it, but instead the "ground" was about 5 blocks higher making me float above it

**Comment by metachronism** [comment]
@cwells1298 does this happen repeatedly for you?  and if so, do you have a copy of the gamesave you can possibly provide, thanks!

**Comment by elfl0rd** [comment]
Loks one time and not repro :)
