### ISSUE TITLE
Suggestion: powered cart

### ISSUE THREAD

**Issue by PermanentEdding** [StrangeLoopGames/EcoIssues#6887]
you should be able to make WAYYYY tighter turns with the powerd cart!!!

**Comment by MarjieAVolk** [comment]
Well we are actually about to remove the powered cart, in favor of a truck, but I will offer your opinion to the truck person.

**Comment by Dreepa** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/6531

**Comment by SeanAtr0n** [comment]
It sounds like the powered cart is going away fairly soon, the new truck has a much tighter turning radius
