### ISSUE TITLE
USER ISSUE: campfire not emptying even though storage is attached

### ISSUE THREAD

**Issue by purpleypete** [StrangeLoopGames/EcoIssues#6889]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
same as bug #3240
it was expected to be fixed in latest patch but i encounted it with campfire beans recently.

**Expected behavior:**
campfire should place it into storage or be collectable from campfire

**Actual behavior:**
you cant collect it and it wont go into storage, only fix is to smite it with a dev tool, but you lose it all.

**Comment by MarjieAVolk** [comment]
Nooooo

Okay, thanks.  I'm going to reopen that issue instead, so all the people watching it will know what's up.

Do you have a save file where a project is stuck?  If so, could you send it over?

**Comment by purpleypete** [comment]
I'm afraid not support told me to use dev tool on it to destroy it so I did.

**Comment by purpleypete** [comment]
If it helps another member started it on unowned property.
I added chests connected them.
But they didn't move and once completed they were uncollectable.

**Comment by MarjieAVolk** [comment]
Okay, thanks.  FYI if this happens again, you should be able to just cancel the project.  Don't think you need to dev tool the whole object.
