### ISSUE TITLE
USER ISSUE: Tree become adult after a server restart

### ISSUE THREAD

**Issue by FrancoisECO** [StrangeLoopGames/EcoIssues#6890]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Plant new fresh young trees, and reboot the server. The trees are now fully mature

**Expected behavior:**
young trees

**Actual behavior:**
matures trees

**Comment by SeanAtr0n** [comment]
What type of tree? Any other special circumstances?
Just tried this with cedar and it looked unchanged after reboot

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4003
