### ISSUE TITLE
USER ISSUE: Black screen

### ISSUE THREAD

**Issue by TickTaeck** [StrangeLoopGames/EcoIssues#6891]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Pulling the Wood Cart

**Expected behavior:**
Normal View

**Actual behavior:**
getting a black screen from time to time

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4370
