### ISSUE TITLE
USER ISSUE: Disappearing Block

### ISSUE THREAD

**Issue by ParadoxedHope** [StrangeLoopGames/EcoIssues#6892]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**

1) Upon loading my world, this block is repeatedly missing;

![blockerrora](https://user-images.githubusercontent.com/37836439/38204834-4911c19a-369c-11e8-9daf-6770f459e360.jpg)

2) I replaced the block again;

![blockerrorb](https://user-images.githubusercontent.com/37836439/38204843-501200d6-369c-11e8-969e-aa65d5b1dda9.jpg)

3) At this point, I created a backup of the world, this world save can be downloaded here;

http://www.filehosting.org/file/details/733030/AlamasataBlock.eco

4) Reloaded the world to continue testing and repeated steps 1 and 2 with the same result. Upon each reload, the block is missing. 

4b) Whilst testing step 4 I watched longer than I would have, one time after placing the block, it placed, then a few seconds later broke apart, though other times it places and stays until world reload.

**Expected behavior:**

Block would be permenant

**Actual behavior:**

Specific coordinate block disappears upon reloading.

**Comment by Zoneman81** [comment]
I have the same problem on the server i play on, same 4 blocks missing every time the server is restarted

**Comment by dandrewrichardson** [comment]
I can also confirm this. It happens on player structures all over the world, but it's always in the same spots. Notice it on server restart.

**Comment by metachronism** [comment]
more phantom world objects (or plants) deleting blocks on server startup

**Comment by ParadoxedHope** [comment]
Marjie,

I noticed you had a theory it was related to plants. This world is the same world that Bruce, the crash log, was on. If it would help, I can get the link to that save.

That save I believe was at a point prior to me starting to build in this location, so perhaps you could use the two different saves to identify what was at that specific spot prior to me building there?

**Comment by SeanAtr0n** [comment]
looks like there was a phantom plant in that spot, Fixed in 7.3.2
