### ISSUE TITLE
Artifacts flickering all over screen

### ISSUE THREAD

**Issue by Alto2Forever** [StrangeLoopGames/EcoIssues#6893]
Whenever I boot up the game, both in the starting menu and in the game, artifacts/textures seem to randomly flicker around across my screen. In order to fix this I've tried verifying steam files and reinstalling the game, as well as updating my graphics card driver.
PC specs included as a PNG.
![specs](https://user-images.githubusercontent.com/38013636/38207747-d961fb9a-367c-11e8-9b14-5fff1757da23.PNG)

**Comment by SeanAtr0n** [comment]
Could you send us your log file?
paste this into explorer to find it `%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

**Comment by Alto2Forever** [comment]
This one?
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1869644/output_log.txt)

**Comment by SeanAtr0n** [comment]
hmm, not seeing much useful info in there except for the dx11 msg

Is windows fully updated? Sounds like this update might potentially fix it
https://www.microsoft.com/en-us/download/details.aspx?id=36805

**Comment by Alto2Forever** [comment]
It says there are two different updates that I can download here, which one should I get if I've got 64 bit Windows?

**Comment by SeanAtr0n** [comment]
the one ending in x64

**Comment by Alto2Forever** [comment]
Installed the update, still having the same problem.

**Comment by SeanAtr0n** [comment]
doh, could you send your log file again? you are fully up to date now?

**Comment by Alto2Forever** [comment]
Fully up to date. 
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1869937/output_log.txt)

**Comment by SeanAtr0n** [comment]
Doh, don't see any clues there... can you see well enough to get to advanced options in the escape menu?

Disabling one of those options might eliminate the glitches. Most likely Global Illumination if you have that checked.

**Comment by SeanAtr0n** [comment]
I'm guessing the global illumination was the issue? Please reopen if you still have problems
