### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by Marathorn** [StrangeLoopGames/EcoIssues#6896]
Since 2 weeks no way to connect to any servers.
Any tries on any servers connection is imossible. always same message : connection failed

**Comment by MarjieAVolk** [comment]
Okay, the first things I would suggest you try are steam's 'verify integrity of game files' button, and deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO

**Comment by Marathorn** [comment]
integrity verified and and delete the game already...

**Comment by Marathorn** [comment]
i reinstalled it but sill same error

**Comment by MarjieAVolk** [comment]
Hrm okay.  How are you connecting to these servers?  Are you finding them in the 'Join' screen list?  Or some other way, like steam invitations?

**Comment by Marathorn** [comment]
i finding them on join screen list
but last game was with a whitelist about 1 month ago

**Comment by Marathorn** [comment]
Perhaps computer is too old....
Computer OS is windows  7 , 64 bits

Processor : Intel Celeron CPU B840 @ 1,90 GHz

Graphic card model : AMD Radeon HD 6470M

Memory : 2,00 Go

**Comment by Marathorn** [comment]
last connection log :+1: Initialize engine version: 2017.4.0f1 (b5bd171ee9ba)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: AMD Radeon HD 6470M (ID=0x6760)
    Vendor:   ATI
    VRAM:     882 MB
    Driver:   14.301.1003.1003
Begin MonoManager ReloadAssembly
- Completed reload, in  0.126 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Setting up 1 worker threads for Enlighten.
  Thread -> id: 1334 -> priority: 1 
UnloadTime: 28.972332 ms
RPC lookup took: 10921.2907ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Could not get server info
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Releasing render texture that is set as Camera.targetTexture!
 
(Filename:  Line: 3926)

**Comment by MarjieAVolk** [comment]
Thanks for that stuff.  I am not really sure what else to suggest right now, so waiting to see if somebody else has any ideas.

**Comment by Marathorn** [comment]
ok thanks for help :)
i hope someone will help :)

**Comment by Marathorn** [comment]
still no solution ....

**Comment by noblackthunder** [comment]
@Marathorn just read trough the convo again. Did you delete the appdata folder as Marije asked ? Looks like you might have missed it and just uninstalled the game . But this is not uninstalling all files

**Comment by Marathorn** [comment]
no i did not.
should idelete this folder and resinstall the game again ? i try

**Comment by noblackthunder** [comment]
No need to uninstall just delete the eco folder in appdata as marjie showed above

**Comment by MarjieAVolk** [comment]
Oh thank you @noblackthunder, I didn't realize there was a misunderstanding.

**Comment by Marathorn** [comment]
still same error

**Comment by Marathorn** [comment]
Initialize engine version: 2017.4.0f1 (b5bd171ee9ba)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: AMD Radeon HD 6470M (ID=0x6760)
    Vendor:   ATI
    VRAM:     882 MB
    Driver:   14.301.1003.1003
Begin MonoManager ReloadAssembly
- Completed reload, in  0.152 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Setting up 1 worker threads for Enlighten.
  Thread -> id: b4c -> priority: 1 
UnloadTime: 46.436936 ms
RPC lookup took: 10877.8866ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Can not play a disabled audio source
 
(Filename:  Line: 707)

Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Can not play a disabled audio source
 
(Filename:  Line: 707)

Releasing render texture that is set as Camera.targetTexture!
 
(Filename:  Line: 3926)

**Comment by metachronism** [comment]
@Marathorn can you perchance ping me on discord and we can try to figure out the problem for you?  thanks

**Comment by Marathorn** [comment]
you have same sanme in discord and here ?

**Comment by metachronism** [comment]
verified this is working in 7.4 w/ Marathorn
