### ISSUE TITLE
USER ISSUE: Collider not despawning

### ISSUE THREAD

**Issue by cwells1298** [StrangeLoopGames/EcoIssues#6897]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Cut down a tree
Get rid of the stump
Walk over the stumps last position

**Expected behavior:**
Stump visuals and collider are removed

**Actual behavior:**
Stumps visuals removed but colliders remain in place

**Comment by SeanAtr0n** [comment]
duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/4908
