### ISSUE TITLE
Plant migration crash

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#6898]
From @GophTheGreat :

Got one from the support queue. I don't actually think it's the same error that John's user reported but this already has a fitting title, so:

"What an amazing game, I love it!

BUT while loading my world with Eco server 0.7.3 the following error message appears after „loading plants 100%“:

Unbehandelte Ausnahme: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Exception: Error(s) occurred when loading Plants
bei Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
bei Eco.Simulation.PlantSim..ctor()
bei Eco.Simulation.EcoSim.Initialize()
bei Eco.Simulation.EcoSim..ctor()
--- Ende der internen Ausnahmestapelüberwachung ---

bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)

bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
bei System.Activator.CreateInstance(Type type, Object[] args)
bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
bei Eco.Server.PluginManager.<.ctor>b__10_3()
bei System.Threading.Tasks.Task.Execute()
--- Ende der internen Ausnahmestapelüberwachung ---

bei System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
bei Eco.Server.PluginManager..ctor()
bei Eco.Server.Startup.Start(String[] args)
bei Eco.Server.MainClass.Main(String[] args)

The interesting thing: this file was an backup file that was created automatic by the server itself. This file is broken and 7-Zip also says that there are CRC-Errors in the ECO-File.

After all by backups after the 7.3.0 world-convert are broken.

Is there any chance to get the file working or to repair that backup file, because there are a few “working” hours in it?

(continued from a second email):

it seems to be a problem at a species type definition in Eco.

I debuged the server application for more information in Visual Studio, please see attached file no. 1.

I also attached the eco dump file (see no. 2) and here you can download the world-files in zip-archive:
https://www.amazon.de/clouddrive/share/D8FOEg3voC766j9B05VswNIiWZAy2i4V59eIi7p8AGz

eco_debug

https://pastebin.com/Z5ugKDnx

**Comment by metachronism** [comment]
craig, this seems to be an issue with the config file, bad species info?

**Comment by craig-jong** [comment]
There isn't anything wrong with the current version of the EcoSim file.

We should reopen this issue if it continues past 7.5, but I have seen any recent reports.
