### ISSUE TITLE
Stats causing terrible/terminal lag 

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6899]
Several servers with complains of terrible lag to the point of server crashing when crafting queue are larger that 10.  SOme of this was helped a bit with changing savefrequency in Storage.eco from 60 (seconds which is the default) to 300 seconds  but for the most part the lag continued for large queues, to the point of being terminal and crashing the server.  Disabling stats.eco has been the only workaround that has allowed servers to be up and playable

**Comment by MarjieAVolk** [comment]
So you mean when starting a crafting project larger than 10?  Or while such a crafting project is running?

**Comment by pamduncan** [comment]
If they start a crafting project and while the project runs both, lag is terrible.  And causes crashing.  You can get it to where, with adjusting savefrequency to where you can manage maybe a queue of 100 but larger queue, which are prevalent - say making bricks for a house and setting up crafting 500, lag gets so terrible either the server has to be restarted to clear it or it eventually crashes.  And if you have a couple of poeple crafting it just gets worse.  Disabling stats made it a great deal better.  The server is not crashing, there is still lag but not crippling, you can play through it

**Comment by metachronism** [comment]
this sounds like world object save related, which sean is looking into

**Comment by SeanAtr0n** [comment]
Storage should be less of a problem in 7.4... I'm not certain if that resolves this issue... please reopen with more info if it doesnt.
