### ISSUE TITLE
Chat window highlights last text instead of cursor-ending it

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#690]

**Comment by metachronism** [comment]
this may no longer be valid, close if so

**Comment by MarjieAVolk** [comment]
Is this referring to when you hit enter and it auto adds the last chat tag you used into the chat bar, but then it's highlighted so you end up deleting it if you type?  I've seen that happening still

**Comment by MarjieAVolk** [comment]
So in the current version of the chat ui that I've been working on, it doesn't put the tag name into the text box like that anymore, so might not be relevant - but I also think I happened to find what is doing this; it's inside TMP_InputField:

        protected void OnFocus()
        {
            SelectAll();
        }

Seems like it would be easy to change that to set the cursor to the end instead.  Although that would change the input field behavior throughout the game, if that is okay.  Alternatively I could add a setting for it.

This class is kind of big and weird though - does it have a custom unity editor implementation somewhere?  I don't see any public fields or anything in the class, and that editor looks fancy

**Comment by MarjieAVolk** [comment]
Or should I not edit that class?  I realized it's in Content

**Comment by MarjieAVolk** [comment]
Fixed and/or made irrelevant
