### ISSUE TITLE
Fish Stock Graph Behavior

### ISSUE THREAD

**Issue by MagnusFaustus** [StrangeLoopGames/EcoIssues#6906]
I'm not sure if this is going to become a gameplay issue quite soon in my current server, but the depletion of fish stocks in-game seems to be almost geometric. Ie, a finite amount of resource, that depletes to zero with no restoration of the population over time. Which is a bit strange. Maybe the recovery of tuna should be slower than salmon or trout, but it definitely should not be near-zero recovery over the span of 10 real life days and many more in-game days. Bison and Elk seem to recover faster than it, despite their limited number.

I just saw the stock of fish worldwide in the game server decrease tuna stocks from 700 units to 200 in 5 days, and salmon/trout are taking a big hit because of individuals putting fish traps out while they're offline. (Dozens of them, in fact.) The server I'm in is mostly a water world, with only a few unusually small islands, so that fish stock issue seems to be a ticking time bomb for us. I just wanted to be sure this wasn't a 'bug', given that fishing was a recent addition to the game.

Likewise, I'm looking forward to new advanced cooking recipes for fish items to parallel with the meat alternatives, and the possibility of boats/fishing boats that are on the horizon. Albeit it looks like they will lose out to trains in the near future. Hopefully in the future, then, as I'd like to see how an Eco might handle a global moratorium on fishing because of a stock collapse from fishing trawlers and indiscriminate trapping.

**Comment by johnkslg** [comment]
Will fix before boats
