### ISSUE TITLE
USER ISSUE: stuck into solid material

### ISSUE THREAD

**Issue by mcmalonzo** [StrangeLoopGames/EcoIssues#6908]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
was at the corner of an house made of wood and with "carpet" the dirt on wich grows mushrooms

**Expected behavior:**
not fall in solid ground

**Actual behavior:**
fall in solid ground

**Comment by MarjieAVolk** [comment]
Could you perhaps send a screenshot of the place where you fell through?

Did you do anything that was related to you falling?  Or did it seem to happen just from walking in this particular spot?

**Comment by MarjieAVolk** [comment]
Closing due to no response - if you respond I will reopen :)
