### ISSUE TITLE
Mini Map Lag

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#6909]
opening the Mini Map on a 56 day old server causes the game client to freeze up then kick me from the game for inactivity.

ive checked my pc resources and the server resources while trying to load the mini map and neither of them are going above 20% on cpu and ram

if you need the game.eco file let me know and i can try and upload it. its about 350mb last i checked

ive also tried to zoom the map all the way in and out to see if that would help the mini map load but no success

**Comment by SeanAtr0n** [comment]
sure, please send us the save file

**Comment by ecoemmeck** [comment]
https://www.dropbox.com/s/7tnb91cmgkdiu05/Game.zip?dl=0

here's the save

**Comment by ecoemmeck** [comment]
this seems to be not happening as often anymore if at all

**Comment by SeanAtr0n** [comment]
fixed a while back
