### ISSUE TITLE
Skills didnt load properly

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#691]
![image](https://cloud.githubusercontent.com/assets/3536496/19746956/a76cd17c-9b8d-11e6-80df-38e992be90b2.png)
In latest.  It also shouldnt show that point bar at the bottom, can just remove it (or make it work)

**Comment by metachronism** [comment]
this is a unity masking bug.  If you dont resize the window after the game loads, it looks fine

**Comment by metachronism** [comment]
fixed
