### ISSUE TITLE
Suggestion: Lumber fences line up with different heights

### ISSUE THREAD

**Issue by ZeelNightwolf** [StrangeLoopGames/EcoIssues#6910]
With the Lumber fence if you decided to go from one high to 2 high (and so on) the boards going across do not line up with the rest of the fence (only the top does). It makes it look out of place.

![image](https://user-images.githubusercontent.com/29911902/38234643-d00fa8ae-3761-11e8-89aa-52c0f9a79631.png)

![image](https://user-images.githubusercontent.com/29911902/38234741-1657c99a-3762-11e8-9c2c-83e57b286918.png)

**Comment by keegan-o** [comment]
Haha, fair enough! Fixed in master and thus hopefully 7.4
![image](https://user-images.githubusercontent.com/14983165/38650561-6d98c4ac-3db1-11e8-801a-578b61a8da73.png)

**Comment by ZeelNightwolf** [comment]
:D
