### ISSUE TITLE
(Suggestion) (New Vehicles) For Goods Storage And Movement

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#6911]
#1 can we add a paint accent on the powered carts like maybe there wagon canvas can be made different colours so users can designate them to roles kind of thing.

#2 with the last feature in mind would it be possible to add trucks, forklift's, pallets, pallet racking, a crane.
- Trucks can move up to 6 pallets
- Forklifts can move pallets between trucks and pallet racking
- Forklifts are rear steering and look something like this 

![image](https://user-images.githubusercontent.com/29722757/38234890-99d2cb08-3762-11e8-940e-3fc69b494438.png)

- Pallet racking can hold 6 pallets
- Pallets are 2x2x2 
- Pallets have 10-20 slots for carried items and 20-40 slots for inventory items

At a later point when boats are added maybe add a crane for emptying big boats on to pallet racking

**Comment by Baithoven** [comment]
lovin it!

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#161
