### ISSUE TITLE
USER ISSUE: Corrogated Steel Wall connection issues

### ISSUE THREAD

**Issue by MIKUiqnw0** [StrangeLoopGames/EcoIssues#6914]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Place a corrogated steel slim wall block that will act as the connector for surrounding walls.
2. Place three surrounding slim walls around the connector block.

**Expected behavior:**
The connecting wall block would fill the connections to all three walls.

**Actual behavior:**
The connecting wall block instead fills 2 out of 3 walls. The 3rd filler goes out towards the empty space that has no wall.

**Comment by keegan-o** [comment]
Fixed in master, will be in 7.4
