### ISSUE TITLE
Disconnects me from server when hovering mouse over skilltech and not showing info about the skill

### ISSUE THREAD

**Issue by Zoneman81** [StrangeLoopGames/EcoIssues#6920]
Hello,

![20180403140310_1](https://user-images.githubusercontent.com/38038590/38248360-626ff10a-3748-11e8-9572-0e3ac0eb0d94.jpg)

New issue, my mouse is over the skill but no window is showing about the skilltree (info, costs and so on) and then i'm disconnected from the server.

**Comment by MarjieAVolk** [comment]
Do you get an error message when you are disconnected?

**Comment by Zoneman81** [comment]
No, now that you mention it

 

I get back to default start screen no msg, and I can just press countinue and relogin to the server.

 

Fra: MarjieAVolk [mailto:notifications@github.com] 
Sendt: 3. april 2018 20:12
Til: StrangeLoopGames/EcoIssues
Cc: Zoneman81; Author
Emne: Re: [StrangeLoopGames/EcoIssues] Disconnects me from server when hovering mouse over skilltech and not showing info about the skill (#6920)

 

Do you get an error message when you are disconnected?

**Comment by MarjieAVolk** [comment]
Well that is pretty strange.  I tested out skill tooltips, including the one for Alloy Smelting, which you have highlighted.  All of them are working fine for me.  So sounds like something odd with your machine.

What operating system are you on?  Maybe you can try the following:
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software

**Comment by MarjieAVolk** [comment]
Hey, are you still having trouble?  Have you tried the steps I suggested earlier?

**Comment by MarjieAVolk** [comment]
Oh also, what operating system are you on?

**Comment by MarjieAVolk** [comment]
Closing due to no response / no repro
