### ISSUE TITLE
Cosmetic build options seem to not be used by that many

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6921]
Observation:
Most houses on our server look ugly (as in, no windows, no roofs, etc), as people seem to favor to play efficiently, so the do not put SP into the aesthetic skills.
It seems that pure cosmetic options are less worth to people than the new game-play options and effects they get from other areas to spend the SP.

The approach of just using one single SP pool for both, game-mechanic progression and visual options might be leaving room for improvement. People could be spending time beautifying their houses with different blocks, while waiting for craft jobs to complete.

I have the feeling it is an activity that should always be available, without having the feeling of "wasting" your skillpoints.

**Comment by styles784** [comment]
On the one hand, the current system makes house-building a viable job

But on the other hand, I never played games like Minecraft to ask others to build for me - doing it myself is a large part of the fun. It's tedious to experiment with the additional block types when you have to get another player to place your blocks for you, especially if both players aren't in the same voice channel. And paying SP to unlock an additional specialization so you can do it yourself causes subsequent specializations to ramp up in cost, or costs the player 50% of the SP if they back out of the specialization to lower the cost of a more important one

**Comment by MarjieAVolk** [comment]
> Building a staircase, roof, window, column... doesn't really matter what the construction material is.
> Raise the price a little and roll all of the tier buildings in together into a single, unified construction tree. Tier 1 construction, tier 2 construction, tier 3 construction. Separate skills, but all significantly more useful and more valuable than they currently are.
> 
> Noone on my server is taking them. Because we have actual needs and they're way too expensive.
-- @CuAnnan

**Comment by CuAnnan** [comment]
On that note. The skill should allow the creation of placeable items. Having to get permissions on someone's house to put in the decorations disinclines people to do it as well.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#160
