### ISSUE TITLE
USER ISSUE: Black screen 

### ISSUE THREAD

**Issue by LeyzZONE** [StrangeLoopGames/EcoIssues#6923]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
After creating a world interface on a black screen

**Expected behavior:**
my video card is geforce gt 635 m

**Actual behavior:**
I installed new drivers ,did not help

**Comment by SeanAtr0n** [comment]
So the main menu is fine? Do other servers work?

Please send us the log file from  `%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

**Comment by LeyzZONE** [comment]
The main menu is fine.On other servers the same
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1875963/output_log.txt)

**Comment by LeyzZONE** [comment]
I deleted the Strange Loop games folder, deleted the game from steam and reinstalled it.The problem remained

**Comment by BlazeGuy2** [comment]
@LeyzZONE are you still having the issue?

**Comment by BlazeGuy2** [comment]
Reopen if issue comes up again.
