### ISSUE TITLE
USER ISSUE: Chest on upper floor on lumber not on solid ground

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6924]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Build upper floor in multi-level building
2. Place chest

**Expected behavior:**
Should be a green light.

**Actual behavior:**
Status light is red, not on solid ground.

![grafik](https://user-images.githubusercontent.com/37662083/38259032-54b1d49a-3764-11e8-808b-798888bce5e4.png)

**Comment by MarjieAVolk** [comment]
This might be related to the rotation of the chest - there is a bug with solid ground and rotation.  Can you place the chest in the middle of the room?

Adding @keegan-o in case this is an issue with the lumber floor.

**Comment by Dreepa** [comment]
Server had to restart because of non-terminated connections and after the restart the same chest works fine without doing anything to it.

**Comment by MarjieAVolk** [comment]
Okay thanks.  So not related to the floor type, probably.

**Comment by Dreepa** [comment]
Here is something else: After server restart, my sawmills failed the room check. So I destroyed parts of the room and re-established the room. Still failed room check. I picked the sawmill up and placed it again. Still failed room check. I went away and came back, room check passed.

Have this feeling this is something broader with updating/syncing something not properly.

**Comment by craig-jong** [comment]
This sounds like a room detection issue... I'll look into adding some way to visualize the room detection since we already have a debug thing for that.

**Comment by elfl0rd** [comment]
Place wind turbine, they work fine 2 real day (and 5 server restart) no ground changes on it's region... And... No solid ground untill server restart :(

**Comment by SeanAtr0n** [comment]
Pretty sure I have a fix for this in 7.4 if the broken objects are touching multiple chunks (x/z position ends in 0 or 9)

**Comment by SeanAtr0n** [comment]
fixed 7.4
