### ISSUE TITLE
USER ISSUE: Can not start a new world (Linux)

### ISSUE THREAD

**Issue by CSmither** [StrangeLoopGames/EcoIssues#6928]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Run Debian
2. Try to start a new world

**Expected behavior:**
It should generate and start a new world

**Actual behavior:**
The following error message popped up:
```
Could not start server: Object reference not set to an instance of an object
```

**Comment by SeanAtr0n** [comment]
http://ecoforum.strangeloopgames.com:4567/topic/2984/setting-up-a-eco-server-on-ubuntu-other-linux-is-probably-very-similar
