### ISSUE TITLE
USER ISSUE: Could not create new world (Linux)

### ISSUE THREAD

**Issue by CSmither** [StrangeLoopGames/EcoIssues#6929]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Fail to start game once (with generate new world checked), giving [this error](https://github.com/StrangeLoopGames/EcoIssues/issues/6928)
2. Try again in a stupid hope that it'll work second time.

**Expected behavior:**
Hopefully load the game

**Actual behavior:**
The following error message popped up:
```
Could not start server: Process has not been started.
```

**Comment by SeanAtr0n** [comment]
Currently linux requires running the server separately, here is a guide:
http://ecoforum.strangeloopgames.com:4567/topic/2984/setting-up-a-eco-server-on-ubuntu-other-linux-is-probably-very-similar
