### ISSUE TITLE
Stockpile bugging you under the map

### ISSUE THREAD

**Issue by KosmoLp** [StrangeLoopGames/EcoIssues#6934]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. stay on stockpile
2. put resources in it 
3. if u stay right where the resources are added u bug under the map

**Expected behavior:**
/

**Actual behavior:**
see gif

![bug gif](https://user-images.githubusercontent.com/38045887/38267444-d46840ea-377b-11e8-9fb4-fe4576664136.gif)

**Comment by elfl0rd** [comment]
Addition to fall under map, if you fall under map and leave - you CANT join back, you stuck on loading screen. (10%, on 90% you teleported on surface).

**Comment by SeanAtr0n** [comment]
fixed a while back
