### ISSUE TITLE
(Suggestion) Recycling Plant

### ISSUE THREAD

**Issue by sigmundr** [StrangeLoopGames/EcoIssues#6937]
Now that garbage is implemented, I thought it would be fitting to implement a recycling center:

T2 room
Would have one menu similar to the repair bench to break down unused items to base materials
Second recipe page that could turn garbage blocks into either recycled plastic, cloth, metals
Further recipes at tailoring tables, smelters, etc to turn "recycled x" into usuable resources
Would require power

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#159
