### ISSUE TITLE
Server showing as "offline"

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#6939]
From the support queue:

Normally when i connect to my server my friend could join but for two days my server is permanently shown as offline. 
I opened the ports on my firewall and router and its also adjusted as a public server
i dont know why it doesn't work anymore.  
but i get this errow when its about my ip adress but i'm sure its the right one. 
Failed to discover NAT: Eine Ausnahme vom Typ Open.Nat.NatDeviceNotFoundException wurde ausgelöst. 
  
plz help my i want to enjoy the game without this struggles again

I installed the latest update 
74,1gb free ram Intel(R) Core(TM) i7-4700HQ CPU @ 2.40 GHz 
i have no idea what to do i have this problem for one week it's really depressing 
[log_180402110317 (1).log](https://github.com/StrangeLoopGames/EcoIssues/files/1873161/log_180402110317.1.log)
[log_180402103807.log](https://github.com/StrangeLoopGames/EcoIssues/files/1873162/log_180402103807.log)

**Comment by portalseeker** [comment]
I'm having a very similar problem where the server I set up appears as offline to both me and my friend. He refunded the game until he can get back online because he didn't want to play alone. I would love to solve it.

**Comment by GophTheGreat** [comment]
+1, nothing much to add. I asked them to try forcibly connecting via IP and seeing what happens.

**Comment by noblackthunder** [comment]
Looks like something is blocking the server from the log you provided .. or the user does not have any network adapter. most likely the first one. An example could be antivirus that blocks the application. Missing permissions ( try running the server as admin ) or its a vm with no network interface

**Comment by metachronism** [comment]
@portalseeker if you could ping me on discord, I can try helping to diagnose your problem some more

**Comment by GophTheGreat** [comment]
+1 from the support queue, just keeping a tally.

**Comment by portalseeker** [comment]
@metachronism  I totally missed the email for this. Would you still be able to help me figure things out on discord sometime?

**Comment by BlazeGuy2** [comment]
@portalseeker not sure if anything has moved forward here.  If you're still getting this issue, join our Eco discord channel, and send me a msg (I'm listed under the SLG developers) and I can try to help you out.
