### ISSUE TITLE
Adjust skill specialization preset

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#6941]
Based on player feedback, having 'low' collaboration as 3-10 is too aggressive.  We should reduce this range, 4-10 or 5-10.

Player feedback:
https://steamcommunity.com/id/inthenameofbubbles/recommended/382310/
"We did set the world on "low" before we got started for the second time. We are now playing with an eight times multiplier for skill points, but it isn't that much fun. Just to explain what I mean (This is obviously just my opinion, but I think its quite comprehensible):
 
You've created a game with a goal to it. We want to achieve that goal without adjusting 10 different things in a config file, because it feels like cheating (and it actually is imo). From my experience so far it seems impossible to destroy the meteor on "low" specialization settings with only 3 people. The game just needs better presets for certain amount of players, so that Eco provides a good challenge without being impossible. "

**Comment by beastyn** [comment]
Need make hint for No and Low Collaboration
No Collaboration (1-5 players) 
Low Collaboration (5-10 players)
![bandicam 2020-02-04 15-44-46-075](https://user-images.githubusercontent.com/27898520/73737916-4ac64c00-4765-11ea-8703-d1b031d26cb3.jpg)

**Comment by WeaselDog** [comment]
The host new world UI has changed. It no longer lists recommend player numbers. There will be another update to difficulty setup soon.
