### ISSUE TITLE
Icon with stray pixels

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#6942]
This is the Big Stomach skill.  One of the icons used in it has a stray line along the top, looks like the meat one probably.

![image](https://user-images.githubusercontent.com/23460210/38274398-891f9936-3743-11e8-99dc-f3b1f0f1ef3a.png)

**Comment by rachaelfosner** [comment]
Updated the sprite sheet. ( A shadow from another sprite was bleeding into the meat icon. )
