### ISSUE TITLE
USER ISSUE: Felling Tree Crashes Game

### ISSUE THREAD

**Issue by srech94** [StrangeLoopGames/EcoIssues#6946]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1) Cut down a Tree
2) Leave chunck
3) Return to Chunk -> The tree is not Loaded

4)Quiting and Reloading Loads the Tree
5)Trying to cut the Tree into peaces crashes the Game

**Expected behavior:**
Trying to cut a Tree

**Actual behavior:**
Game Crashes with exception

**Comment by MarjieAVolk** [comment]
Just today we have fixed several issues related to this.  So hopefully this will be fixed in a hotfix tomorrow.
