### ISSUE TITLE
Glass in stockpile shows odd graphic

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#6947]
Glass, anywhere else in the world has the nice glass graphic and no issues with it, however when placed in a stockpile it looks like a block of tan sand:

https://steamuserimages-a.akamaihd.net/ugc/912417471401784484/ED8CD1C37385200A7995C40D1B19CA014A2928DE/

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/38325030-b5ac419e-37f6-11e8-8087-e2600f09f5a8.png)

It sounds likely that your glass.cs files in Mods/AutoGen/Forms and Mods/AutoGen/Items are out of date. Can you double check the server was update properly?
