### ISSUE TITLE
Glitch Steal items through Store/carts/stockepile

### ISSUE THREAD

**Issue by Baithoven** [StrangeLoopGames/EcoIssues#6948]
I can steal items through my cart or store or other storage's
Version 0.7.3.1
Server is 4 days Old

small Example video:
[https://youtu.be/X1vGYC0SIQE](url)

**Comment by erucquoy** [comment]
In the video, you show the Chest locked,and in the Shop you take items from Icebox... ? mmh

**Comment by Baithoven** [comment]
There was also no permission on it

**Comment by johnkslg** [comment]
I believe this is fixed, havent seen that crash in awhile. Reopen if its still happening/still possible, need specific repro steps as it was hard to tell what they were from the video.
