### ISSUE TITLE
Stockpiles overlap claims

### ISSUE THREAD

**Issue by Ekkelus** [StrangeLoopGames/EcoIssues#6954]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Place a stockpile mostly on your own property or unclaimed land but about 10-20% on claimed land by another player.

**Expected behavior:**
"Cannot do that on [Players] property: not authorized"

**Actual behavior:**
You can place it. Not sure here but I've heard reports that some are stealing from other players from stockpiles even though they're claimed, now I can't verify that but if that's true this might be related somehow, maybe after a restart things gets messy.

**Comment by craig-jong** [comment]
world objects now check every property they overlap with - no longer can you put a lathe partially into someone's property.
