### ISSUE TITLE
USER ISSUE: Plants do not Place

### ISSUE THREAD

**Issue by Vekoboy** [StrangeLoopGames/EcoIssues#6956]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
1. Hoe ground.
2. Plant seed.

**Expected behavior:**
Seed to be planted and plant to behave dependent on conditions.

**Actual behavior:**
Get error message stating that a Plant is already there.  Visually, the plant is not planted and even after digging up plot, replacing dirt and re-hoeing, the error message persists.  Does not effect every block.

**Comment by dandrewrichardson** [comment]
I've had this issue as well, I'm betting it's related to the phantom objects (plants) addressed in #6982.

**Comment by MarjieAVolk** [comment]
Yes, thank you - this should be fixed in 7.3.2, coming out soon
