### ISSUE TITLE
USER ISSUE: Framedrops after Update 7.3.1

### ISSUE THREAD

**Issue by Waldi09** [StrangeLoopGames/EcoIssues#6957]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**

**Expected behavior:**
The Game runs like 7.2.5

**Actual behavior:**
After the Update 7.3.1 the Game have many Framedrops and shut down after 10-20 Minutes.
The FPS ist going down to 15-20.
It dont make Fun to play it with this Framedrops
Before i install the Update the Game runs without Problems.
My Computer is very new so i dont think that the Problem comes from my Computer

**Comment by ParadoxedHope** [comment]
Definitely suffered a significant drop in performance following that patch too, had previously been steadily around 40-50 FPS with a smooth experience, following the patch it goes from 35-40 FPS with drops down to 15-20 FPS.
