### ISSUE TITLE
USER ISSUE: Hewn Log and Hew Logs

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#6958]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
![20180404164838_1](https://user-images.githubusercontent.com/4980243/38311963-22b6360a-3829-11e8-9efe-4a2df467d6eb.jpg)
See two reciepe, Hewn Log and Hew Logs,
"Hew Logs" have "Hewn Log" description.

**Expected behavior:**
"Hewn Logs" reciepe on carpentry table
"Hewn Log" reciepe on workbench

**Actual behavior:**
Seen strange, and yes, of course - i cnow "Hew Logs" makes faster then "Hewn Log"

**Comment by elfl0rd** [comment]
"Hewn" is an adjective, "Hew" is a verb.
In one instance the recipe describes the product, a "Hewn Log" in the other the recipe describes the process, to "Hew Logs."
It's wonky and inconsistent but not incorrect.

**Comment by MarjieAVolk** [comment]
Haha, yes I think this is the intention - that the recipe name is the verb.
