### ISSUE TITLE
The entire web interface is broken

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#6959]
Unable to pass laws.
Unable to run for office.
Unable to create new districts.
Every time a UI is selected, the widget pops up and then instantly dissappears.

No further feedback is given

**Comment by MarjieAVolk** [comment]
"Every time a UI is selected, the widget pops up and then instantly dissappears." -- What UI are you 'selecting'?  Is this a UI in the game?  Or in the web interface?

**Comment by MarjieAVolk** [comment]
> when i click Run for Office in game i get this page show up
> ![image](https://user-images.githubusercontent.com/23460210/38326432-a584303e-37fa-11e8-8c86-2a1e22864ebb.png)
> when i click on the Run for office button i get this flash up then Disappear
> ![image](https://user-images.githubusercontent.com/23460210/38326437-ac0a1464-37fa-11e8-83f5-80f31fa31f19.png)
> then it stays like this all dark
> ![image](https://user-images.githubusercontent.com/23460210/38326447-b3a87832-37fa-11e8-9022-775e6e17902b.png)
> but then i click refresh button in Firefox and then it all works normally
> (actually its the reload page button i know how you like it to be Correct 😄 )

-- @Conchipedia

**Comment by rainfarmer** [comment]
Can't repeat, 
I think this has been patched with our cross-browser patch.
Let me know if you're still getting it on 7.3.2

**Comment by CuAnnan** [comment]
This has not been fixed.

**Comment by MarjieAVolk** [comment]
Have you updated to 7.3.2?  It was just released yesterday

**Comment by Conchipedia** [comment]
i am on 7.3.2 and still having to get firefox to reload current  page for trying to run for office, either direct load from game to the run for office window, or to propose a law and using the pulldown part under elections
![snap2136](https://user-images.githubusercontent.com/29383891/38449553-5d564fb2-3a08-11e8-9d7c-5e40a4ea6573.png)
 this still wont let me click unless i have reloaded the page using this button
![snap2137](https://user-images.githubusercontent.com/29383891/38449573-874ba4b6-3a08-11e8-8ebb-1078af8d9308.png)

but the propose law works fine without me having to press reloading at all .

this is Firefox window being launched from within Eco, not me trying to do anything directly outside Eco

**Comment by Conchipedia** [comment]
![snap2138](https://user-images.githubusercontent.com/29383891/38449624-18ba506e-3a09-11e8-9bf1-7928719ef045.png)
none of these will stay open until i have Reloaded the window ONCE, i can even multiple tabs open called from Eco and each tab has to be reloaded Once, i can swap between them once they are reloaded and click and change anything i want

**Comment by CuAnnan** [comment]
To clarify, I was on 7.3.2 when I said "this isn't fixed".

Can I ask that you start logging things in the javascript console while the game is in development. That way I can track down bugs to a given line and say "this thing here is the problem".

**Comment by rainfarmer** [comment]
Sounds like it could be a cache issue. The browser might be loading a cached version of the code.
Try clearing your internet cache, and see if that fixes it.
Thanks for your help!

**Comment by shadow7412** [comment]
Kinda related - although laws and running for office works for me, defining districts does not.

I get to the screen with the map where you are supposed to right-click and drag to define a district, but it doesn't mark the map. There is an icon that looks like an eraser which, when clicked, overlays with a pencil icon. Clicking this does nothing...

Would screenshots help?

**Comment by rainfarmer** [comment]
@SeanAtr0n any idea how to troubleshoot the map not drawing? ^

**Comment by rainfarmer** [comment]
broken popups and menus will be fixed in upcoming build. thanks for the help
