### ISSUE TITLE
USER ISSUE: Crash on tree sapling hit.

### ISSUE THREAD

**Issue by Kjelleren** [StrangeLoopGames/EcoIssues#6961]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
Hitting a tree birch sapling with an iron axe ecuiped in the 1st action bar slot. This happened only to one specific sapling.

**Expected behavior:**
Removes the sapling.

**Actual behavior:**
Crash sends me to main menu with error. Sapling is still present on the server whan I relog.

**Comment by MarjieAVolk** [comment]
We have fixed several tree related crashes in the upcoming hotfix :)
