### ISSUE TITLE
Suggestion: Storage management/Quick transfer 

### ISSUE THREAD

**Issue by ParadoxedHope** [StrangeLoopGames/EcoIssues#6962]
_Regarding the streamlining of storage management/quick transfer by the player._

The standard use of pressing 'T' to transfer a stack, naturally doesn't work with the more complex options available from multiple storage options so I would like to suggest the following mechanics;

**A) Double Click grab -** One of the difficulties can be holding down Left Mouse Button, then at the same time needing to scroll your mouse wheel down to a lower storage. Most of us naturally use our Index finger to perform both these tasks.

Suggested behaviour: 

1) Double clicking an item would perform the same function as holding LMB on an item. The hand would close to a grab and that item would be held by the hand.

2) Closing the inventory or clicking anywhere not considered a destination inventory slot will reset/ungrab the item.

3) A single click on a valid destination inventory slot will transfer the held/grabbed item.

This would remove the difficulty of the index finger being expected to perform several different functions at the same time.

**B) 'Ctrl' Double Click grab -** (Any modifier besides Left Ctrl could be used.) The same function as described in 'A', though the result of step 3 would be;

3b) All items of the same type i.e. Coal, from the source inventory will be transferred to the destination inventory so long as valid storage slots are available.

4) In the event of too many slots in the source inventory compared to the destination inventory, the maximum amount of available slots will be filled i.e. 20 stack of coal from Storage A, Storage B has 14 available slots, results in 14 stacks of coal being transferred from Storage A to Storage B.

**C) Alphabetical storage filtering option -** The connected storage system is fantastic, really, we love it. One thing often discussed in the workload involved to organise this storage when a new table/storage is created. By offering the user an 'Arrange alphabetically' button, the user could easily pre-define storage orders.

For example, players often have one Stockpile and one chest that they prefer as destination outputs. Players could rename that from 'Workshop Stockpile' to 'A - Workshop Stockpile', could rename 'Brazier' to 'Z - Brazier.' 

The result would be that any storage that has 'Arrange Alphabetically' option selected, will automatically display the 'A - Workshop Stockpile' at the top of the list and the rarely needed 'Z - Brazier' at the bottom of the list.

**Comment by ecoemmeck** [comment]
related to #4280

**Comment by MarjieAVolk** [comment]
Oh, several people have suggested alphabetical sorting, but I always thought that they didn't realize the sorting order mattered for the output prioritization.  I didn't think about naming the storage to sort it everywhere. 🤔 

I am still afraid of an alphabetical sort button, because it would make it really easy to lose your sorting, if you have it all set up the way you want.  It sounds like what you want is a default prioritization for your storage, so maybe we should have a separate feature for that.  A default priority field on each storage object, and a sort by default priority button.  >>  I'm not sure if that would be better or worse.

**Comment by MarjieAVolk** [comment]
If you don't mind, I am going to copy your comments over to #4280 though, to keep the discussion organized.  Thanks!
