### ISSUE TITLE
Bug on currency with negative taxe 0.7.3.1

### ISSUE THREAD

**Issue by Grirat** [StrangeLoopGames/EcoIssues#6967]
Hello,

After posted a message on ecoforum they ask me to report bugs at EcoIsses on GitHub.

I whanted report a bug on currency for actual ECO version 0.7.3.1 beta.

It's when the leader of the world set negative taxe that cause bug.

When someone buy in your store with a currency who havn't Tresory, the negative taxe agree him to pay less money.
So when no Tresory in the currency , if people buy for more that they have money, everything become free for them.

Ex: Player A have the store. And player B have 50 $. A glass is selling 1 $ in the shop. Taxe set to -10%.
If player B bought to player A for 60 glass (so for 60$, more money than player B have) so player B take the 60 glass free and give no money to player A.

So negative taxe in a currency who havn't tresory make that bug when player try to buy more than they have money.

**Comment by johnkslg** [comment]
Clamped to 0 for now.  You can still set payments from the treasury though the law system.
