### ISSUE TITLE
Noticed Time De-Sync between clients and server

### ISSUE THREAD

**Issue by geeknessfr** [StrangeLoopGames/EcoIssues#6968]
Game/Server version : 7.3.1

Since the update i noticed sometimes a time de-sync, I can't say if that happened before, on older versions, but for exemple a friend told me that the sun rises for him but for me it was night and when I did a disconnect/reconnect to the server I could see Daylight.
I think it's due to some lags when loading chunks or else, because we have a small city with a lot of buildings on our server and this cause a lot of lag when entering city.

**Comment by TwixterZ** [comment]
ECO have changed so much since then, hence will proceed to close this issue, If you encounter this on a more recent build, please reach out to me (TwixterZ @ discord)
