### ISSUE TITLE
Teleported to -2147483648,-2147483648,-2147483648

### ISSUE THREAD

**Issue by geeknessfr** [StrangeLoopGames/EcoIssues#6970]
Game Version : 7.3.1
I get some reports from our server users and also a friend in a **solo** game.

Few days ago a user told me he suddenly get a black screen while walking with his Wooden cart, yesterday another user while walking, both on our dedicated server and 2 more users today, and now a friend on a solo game on his local server while placing a WindTurbine.

What happened is that the player is teleported to -2147483648,-2147483648,-2147483648 : 
![image](https://user-images.githubusercontent.com/28137335/38328955-8c2a1a84-384c-11e8-80f5-f3dd9e9e76dc.png)
Then, they see a black screen and they have to close the game, and they can't reconnect to the server anymore. They are stuck in an "Entering World" loop until an admin teleport back these players on the world while they are trying to enter world with the /teleporttarget command.
Once they are teleported back to the world, they must close the game and reconnect to the server, and it works.

I think this issue has nothing to do with #6882 since here they are teleported out-of-map and can join the server once teleported back but in the other issue we had to reboot the server.

**Comment by ecoemmeck** [comment]
this just happened to me when i was placing down an ashphalt ramp however it was a slightly off yellow screen i could see

**Comment by SeanAtr0n** [comment]
fixed 7.4
