### ISSUE TITLE
Suggestion Delete User

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#6972]
Maybe a Feature for deleting User that isnt active per ServerUI or Ingame. Every new Player,Visitor is in the Userlist. It gets too confusing when the server gets older.

**Comment by ecoemmeck** [comment]
This would be a good feature to have as long as the server admins could set a day count for inactivity and then the server would delete the player either automatically or apon restart

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#158
