### ISSUE TITLE
Memory Leak Windows 7

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#6973]
http://steamcommunity.com/id/zero_ghost/recommended/382310/

"so i love this game already over 300h in it BUT the review will be negatve as the game has CRITICAL MEMORY LEAK FOR WIN 7 that the DEVs DOSENT CARE TO FIX . basicly IF YOU OWN WIN 7 YOU WILL NEED 16-32gb RAM IF YOU WANT TO PLAY STABLE FOR 2-3 hours if you got 8gb like me YOU MAY PLAY ASSASIN CREED BUT NOT ECO!!"

**Comment by ecoemmeck** [comment]
Can confirm this I also play on windows 7 and after about 4 - 5 hours of play my 16 gb of ram is usually sitting at about 100% usage

**Comment by zer0ghost** [comment]
the game its draining the system out of RAM in 2 cases 1 is ingame the other is in the "Join Server" Window. As for what is making it happen for the 2nd i would say the servers that are being loaded proobably are to much or not handled properly by the game as just after 2-3 mins the game becomes real "heavy" if you stay in there. that all i can help as its all i observed.

**Comment by metachronism** [comment]
punting for unity 2018 roadmap update
