### ISSUE TITLE
Smithing and Tailings

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#6974]
http://ecoforum.strangeloopgames.com/topic/4247/smithing

"The-Ghost posted 12 days ago    0 
This is absolute BS that the only job in this game smithing has a negative effect
on the server. None of the other jobs that you can do seem to have this effect
on the server with their tailings.

The devs need to come up with an approved container that smiths can put their tailings
in and so that they do NOT pollute the environment.

It is extremely unfair the way it is right now and punishes anyone that wants to
be a smith in this game.

I would say you should have two different containers you can make for tailings one
made out of stone mortar pieces which are already being made by a stonesmith to
make an approved container to put tailings in so that they do not pollute or
another idea would be to do a 2nd one out of cement.

This is BS punishing the smiths making them dig caves and crap to bury
their tailings you need to come up with a better solution than this to balance
things out for smiths.

NO other professions seem to have that issues with their excess materials
and this is absolutely wrong to punish a person in this game for wanting to
be a smith.

Also tailings should NOT last forever and should have a "half life" and eventually
just disappear!

The way things are right now are horrible for smiths. Smiting needs a LOT
of work!
'
Devs fix this immediately please!"

**Comment by elfl0rd** [comment]
you can use blast furnace

**Comment by Dreepa** [comment]
In a game like ECO, I would honestly expect more punishing elements to other professions, instead of removing the one we have.

That being said, I find the tailings are a bit over the top in terms of amount. No one I see uses the bloomery. It is more or less a waste of game-content from what I see. People build it, then build the anvil with it, and then go on to the blast furnace. No-one really bothers to much with it on our server.

**Comment by darkshad9999** [comment]
The Bloomery is used at the start before you can get a blast furnace and if you have several people smithing can be an issue and can cause a lot of ground pollution.  There should be a casing 
which you can put the tailings in to prevent ground pollution made out of stone and maybe
a 2nd one which is bigger made out of cement to put these tailings into. 

The game is so unbalanced right now that the Smiting is the only one that seems to
have byproduct which pollutes the environment the game is extremely unbalanced!  This needs to be fixed.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#157
