### ISSUE TITLE
Add a chat command for "ignoreplayer"

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#6975]
http://ecoforum.strangeloopgames.com/topic/4199/ignore-command

"Yes I know we are supposed to work together but on some servers you get on there are some people
that are just way too annoying and I don't want to see their garbage.

There really should still be a /ignore,. /unignore and /ignorelist command in this game so that you don't see
anything from the individual if they are on ignore.

The /unignore takes the person off of ignore

the /ignorelist shows you currently who you have on ignore

I think the developers really need to put something like this in place so that people
who are harassing other players can be ignored and not see it any longer

When I do a /? to see a list of all the commands I do not see anything like
this implemented in this game like this.

Can you please add something like this?

Thank you,"

**Comment by MarjieAVolk** [comment]
Moving this to our suggestion project: https://github.com/StrangeLoopGames/EcoSuggestions/issues/15
