### ISSUE TITLE
Bridges

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#6976]
http://ecoforum.strangeloopgames.com/topic/4280/bridges

"Ok so I think it would be really fun to have more actual bridge construction
in the game done by Engineers instead of having the piece bridges together out
of Hewen Logs or Mortared Stone.

It would be nice to have some actual bridge pieces which can be made by engineers.

Could one of the devs possibly take a look into this it would be a great addition
to the game to have some actual bridge pieces and bridge spans and other pieces
like that to construct an actual bridge in game.

Thanks,"

**Comment by nexitem** [comment]
Oh yeah, make it work similar to the ramp pieces.

**Comment by Dreepa** [comment]
I have so much been thinking the same. The terrain is often times just perfect for bridges and tunnels. But terraforming and bridge building is not so convenient (sometimes really annoying) with the carry system limit and with the fact that you easily fall down while extending the blocks.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#156
