### ISSUE TITLE
Admin command to take over a cart

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#6984]
Sometimes carts were left in strange and unusable positions by a player. Or an animal kicks a powered cart over a railing (like on the screenshot below).
In good moments that only looks ugly, but (according to murphy's law) those carts are blocking important lanes. And usually the deed owner will not come online for long time...

For those cases it whould be helpful to have a admin command to take over one cart or to swipe the deed, or to transfer the deed into the carts storage so one can take it (like the /unclaim command for plots)

![unusablecart](https://user-images.githubusercontent.com/22961978/38338925-ed0cdc82-386b-11e8-9007-eecf8ab06b6c.jpg)

**Comment by craig-jong** [comment]
I think they don't really want to delete them, just get them out of the way since the owner wanted to leave them in a correct spot but won't be on to move it back to a normal spot for a while.

**Comment by lightdrawn** [comment]
Players with admin rights, should be able to drive/move all vehicles.
DevTool works, but completely deletes the vehicle and all its content (fuel and storage).

**Comment by craig-jong** [comment]
I had admins ignoring all auth at one point, although now it seems like we might make that a toggle mode.

**Comment by craig-jong** [comment]
Okay so I just tested this and holding the dev tool out should allow you to drive other people's vehicles.

**Comment by craig-jong** [comment]
I'm going to close this issue - I guess the main problem now is that you're still not allowed to fuel carts that have no fuel.
