### ISSUE TITLE
Regression: V0.7.3.2 Game now crashes when it loses focus. -Linux

### ISSUE THREAD

**Issue by dimension128** [StrangeLoopGames/EcoIssues#6985]
After joining a game, not at the main menu, if you press tab for mouse mode, or escape, then move the mouse outside the game window, the game crashes when focus is lost.

V0.7.3.1 Does not have this problem. With 731 the game renders at a lower framerate when it is not the focused window, but continues running.

From the terminal:
```
Native stacktrace:

        /home/lordjason/Downloads/Eco/EcoClient/Eco_Data/Mono/x86_64/libmono.so(+0x984ba) [0x7f79be6b14ba]
        /usr/lib/libpthread.so.0(+0x11dcf) [0x7f79c6ffcdcf]
        /usr/lib/libc.so.6(gsignal+0x110) [0x7f79c6176860]
        /usr/lib/libc.so.6(abort+0x1c8) [0x7f79c6177ec8]
        ./Eco.x86_64() [0x9e1b7b]
        /home/lordjason/Downloads/Eco/EcoClient/Eco_Data/Mono/x86_64/libmono.so(+0xd8cf0) [0x7f79be6f1cf0]
        /home/lordjason/Downloads/Eco/EcoClient/Eco_Data/Mono/x86_64/libmono.so(+0x3717f) [0x7f79be65017f]
        /usr/lib/libpthread.so.0(+0x11dcf) [0x7f79c6ffcdcf]
        ./Eco.x86_64() [0x12f8194]
        ./Eco.x86_64() [0x12b10de]
        ./Eco.x86_64() [0x12a7201]
        ./Eco.x86_64() [0x12a736a]
        ./Eco.x86_64() [0x8da488]
        /usr/lib/libpthread.so.0(+0x708b) [0x7f79c6ff208b]
        /usr/lib/libc.so.6(clone+0x3e) [0x7f79c6237e7e]

Debug info from gdb:

I refuse to debug myself!
No threads.

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
```
I don't know what sections of the log file are important, so I've attached the whole file.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/1878539/Player.log)

EDIT: The same crash happens sometimes when trying to change any graphics settings in game.
EDIT2: I was able to get the game to stop using fullscreen mode when I found the config file. In true windowed mode, I am no longer experiencing crashes when the game window loses focus. But this is still worse behavior than V0.7.3.1

**Comment by dimension128** [comment]
I can not reproduce this on a Linux Mint machine. Tabbing out of the game, etc. all work as expected.

**Comment by SeanAtr0n** [comment]
Hmm yeah I haven't been able to reproduce this so far

**Comment by SeanAtr0n** [comment]
please reopen if this is still an issue for you
