### ISSUE TITLE
Suggestion: Change General rooms into Living Room

### ISSUE THREAD

**Issue by MasterWhoMW** [StrangeLoopGames/EcoIssues#6986]
Seeing that we got rid of the Living room, why not instead rename General rooms into Living Room? I know, not really any point, but General room just does not sounds like a place one would have in a house... Now, the old Living rooms.. there is a room you would have in a house :)

**Comment by MasterWhoMW** [comment]
Looking at the code, it does look easy to quickly fix, but now that I thought a few about it I have a slight problem. Most players are used to items giving the room a label and may freak out if they see a ton of items for a Living Room. Maybe turn one Item into a Living Room, and make the other so-called General items Just "House Items" if they are in a room that does not have a "Label" then the points are 0 out, like Industry. Quick Fix would be to copy Industry 0 point function in General and make an item that players can make at Tier 0 (Maybe the Campfire? Later on in Tier 3 make Fireplaces??) Just throwing ideas out there

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#155
