### ISSUE TITLE
Currency Exchange allowing infinite exchange

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#6988]
So my friends and I just started playing Eco recently and for our first game, we're trying to experiment with the various parts of the game.  Tonight, we were playing with the currency exchange and trying to figure out how to make it work.  I made a gold mint earlier and we've been loosely playing with that and how we might be able to implement it into our world.

Anyway, we were running an experiment where my friend would allow the exchange of 10 of their player credits for 1 gold coin.  I had 64 of their credits in my wallet and I tried to buy 10 gold, just to see what would happen.  Turns out that the game exchanged 100 player credits for 10 gold, even though I didn't have that much on me to start with.  Also, my total of player credits did not reduce.  Upon discovering this, we tried another experiment, this time with me having 0 player credit and 1 to 1 exchange rate.  Same issue was occurring.  I could buy a virtually limitless amount of minted currency with none of the required player currency in my possession.

**Comment by johnkslg** [comment]
Fixed!
