### ISSUE TITLE
Alpha Rewards not working

### ISSUE THREAD

**Issue by KevinVerstegen** [StrangeLoopGames/EcoIssues#6990]
Hey Eco,
I love the game! I supported it last year and love to see the game growing. Now I do have a question about the Alpha Rewards. I have these in one server I made in single player mode (1-3 players) but this was just a test. I am playing on public servers now, but in none of them I seem to have the Alpha Rewards. I tried making a new game again and still had no luck. Maybe it is because I linked the game to steam? Or is it because I bought a few new upgrades. However, is there a way to fix this.
Thanks for this amazing game!

**Comment by SeanAtr0n** [comment]
will be fixed in 7.3.3
