### ISSUE TITLE
Stacked Torches - Still an issue in 0.7.3.2

### ISSUE THREAD

**Issue by RallyPanther** [StrangeLoopGames/EcoIssues#6994]
It seems that the old torch stacks (from prior 0.7.3.x) are still bugged in 0.7.3.2 as I am still unable to move them out of the inventory slot they are using. This is affecting both a slot in a chest and backpack.

Previous Issue #6598

Is there any way to just delete them from the slots?

**Comment by MarjieAVolk** [comment]
Ah darn :'(

**Comment by RallyPanther** [comment]
I have found that you can split the stacks now, this did not work when I first joined my server.

**Comment by MarjieAVolk** [comment]
Ahhh okay that is reassuring.  I guess I just only handled some of the cases.

**Comment by MarjieAVolk** [comment]
Thanks for the update.
