### ISSUE TITLE
Laws are deleted on every Restart

### ISSUE THREAD

**Issue by Rick86** [StrangeLoopGames/EcoIssues#6995]
PLEASE! Delete the "check laws on startup" feature... this destroyed 10 hours of hard work (the law creation is a pain by the way, you should just add a server side feature with if/else in text format)...
We have some laws with Buying Arrows for example (Sell-Event), about 75% of our Laws are deleted on every server start since, 7.3.1 (the last upload of this version)...
I can show you the laws, or send you the Laws\Data in Storage, the laws are working, but they are deleted all the time :/ And also in 7.3.2!

**Comment by IGSApex** [comment]
Im having the same problem on 7.3.1 and 7.3.2. Like stated above its very annoying to have to remake laws every time the server restarts.

**Comment by Rick86** [comment]
It seems like there are many items which are invalid after Restart (this time I saw a message on startup).
So If you have the Sell-Event and the following items for example:
Acorn, Beans, Beet > everthing is fine (also after restart)
Example: When attempting to Sell where (item is Acorn) > prevent

If you have the following items for example:
Arrow, Bread, Substrate, Board, ... > they will be deleted after restartet (message "dropdown item Arrow is no longer valid")
When attempting to Sell where (item is Arrow) > prevent
But these Laws are working till the next restart, so there is nothing invalid... I lost over 20 complexe laws, please just delete this """feature""".

**Comment by PieShade** [comment]
Noticed the same thing. Active laws are gone with every restart, and law proposals are mostly gone too / invalid.

**Comment by MarjieAVolk** [comment]
@Rick86 Thank you for the details, this helped me track down the issue much more quickly.
