### ISSUE TITLE
Seems to not be possible to donate directly to the treasury

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6998]
Currently:
Treasury is filled through tax setting.

Problem:
In order to fill the treasury, we had to announce to players to stop doing direct transaction for a moment. We then cranked up the taxes to 100%, direct-transfered money between 2 player back and forth (filling the treasury) and then set tax low again.

Suggestion:
Unless I have just missed the function somewhere...   Add the ability for player to donate to the treasury directly. Maybe just through /pay 'Treasury',[Amount],[Currency]

**Comment by elfl0rd** [comment]
you can donate to treasury using their own settings.
Use - sumbol in numeric field.

**Comment by MarjieAVolk** [comment]
Yeah, you can do a negative allocation.  That is kind of confusing though, would be nice to make this interface more clear.

**Comment by Dreepa** [comment]
Okay, nice to know.
However: What about people in the player community that want to do it on their own accord? It seems like for the current functionality the world leader needs to "soak" the money from the person. 
A much more likely use case would be, that a player wants to donate on his own. (e.g. putting signs ab that say stuff like "Donations to the treasury are welcome and will be used for road construction and helping new players".

**Comment by MarjieAVolk** [comment]
That's a good point too

**Comment by Deantwo** [comment]
Related suggestion: https://github.com/StrangeLoopGames/EcoSuggestions/issues/447

**Comment by MarjieAVolk** [comment]
Yeah I think you're right.  I'm going to close this and copy some of these comments over there (https://github.com/StrangeLoopGames/EcoSuggestions/issues/447).  Thanks
