### ISSUE TITLE
USER ISSUE: Plant Already exist

### ISSUE THREAD

**Issue by spykees** [StrangeLoopGames/EcoIssues#6999]
![images-ext-1 discordapp](https://user-images.githubusercontent.com/16926519/38376632-530e75d0-38f9-11e8-8e84-bbdaabee2179.jpg)
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
It's append some time after harvest

**Expected behavior:**
Normaly can put a seed in

**Actual behavior:**
It's same tha they already ave a plant but bot

**Comment by spykees** [comment]
Sorry for the poor quality of the image, here better one 
https://steamuserimages-a.akamaihd.net/ugc/936061369448980932/AE4A6DA7861F7AD66CD43923D0726E5FAF0EF411/

**Comment by MarjieAVolk** [comment]
Ah sad day, thought this was fixed.

**Comment by craig-jong** [comment]
Any chance we can get a save file where this is happening?

**Comment by spykees** [comment]
Of course, juste tell me where i can find the save file in the server folder ? :)

**Comment by craig-jong** [comment]
It's under Server/Storage and is called Game.eco

**Comment by spykees** [comment]
[Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1881831/Game.zip)
Here it is :)
Good Luck !

**Comment by craig-jong** [comment]
Thanks! Hopefully we can get this sorted out ASAP.

**Comment by spykees** [comment]
Hope to :) Keep going you're great work on this game :)

**Comment by craig-jong** [comment]
I went to the coordinates where your screenshot was taken and I didn't find a farm. Is this save the most up to date one you have?

**Comment by spykees** [comment]
Nope it's not ... i missed up, you ave the first save ... So here is the last, and the next save will be in 6h i think ... Sorry. 

[Game(1).zip](https://github.com/StrangeLoopGames/EcoIssues/files/1882067/Game.1.zip)

**Comment by spykees** [comment]
The exact position of the Garden is 363,695 let me know if you see it or i will send you the next save in a couple of hours.

**Comment by craig-jong** [comment]
You should be able to force a save with this: 
![image](https://user-images.githubusercontent.com/18184943/38395710-1d4f760c-38e9-11e8-8c12-5f3fc8243052.png)

**Comment by craig-jong** [comment]
Actually don't worry about it, I just got it to reproduce. Thanks!

**Comment by spykees** [comment]
Ok, sorry, but don't ave option to flush on nitrado server. Hope you will find the bug :) Ave a nice day (or night)

**Comment by craig-jong** [comment]
Just as an update, we've fixed the bug (at least in this particular circumstance) so it should be in the next hotfix or normal build.

As a temp measure, you *should* be able to restart your server to get rid of the phantom plants assuming it doesn't try to re-migrate.

**Comment by spykees** [comment]
Thx restarting the server fix de hold phantom plants but still comming new one. But cool you find the bugs and fixe in the next patch. Good work :)
