### ISSUE TITLE
Phantom plants (?) cause blocks to disappear over time

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#7003]
> I am still seeing this. Occurs along the ground only and not after reboots. I have issues after all clients log off the server (I was on last night, came back this morning and they were missing. No one on server overnight). This is on 7.3.2.
> 
> Additional notes: always the same blocks. The issue occurred right after I logged out last night (I had some flour queued and it stopped right after I left due to the blocks disappearing and causing the room to not function.)
-- @jrgriffi

**Comment by SeanAtr0n** [comment]
umm... save file?

**Comment by jrgriffi** [comment]
What exactly is needed for this? Just the configs and storage folder?

**Comment by jrgriffi** [comment]
After a couple days and a few server restarts the portions of the wall have stopped disappearing.

**Comment by MarjieAVolk** [comment]
Just the Storage folder would be fine.  If the current game version doesn't do it anymore, we could look at the backup saves.

**Comment by SeanAtr0n** [comment]
Sounds like its resolved... the next hotfix will also make it so the reboots aren't required to fix it
