### ISSUE TITLE
Feature: Being able to delete a world, from the "Load UI", made by the client server.

### ISSUE THREAD

**Issue by zEverdeen** [StrangeLoopGames/EcoIssues#7006]
![](https://i.gyazo.com/0b835c96fea24ee747fca1fae215c22a.jpg)

Maybe also list the last backup, and make a "make new backup" button, so people that don't get a lot of backups can choose to make one.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6964

**Comment by zEverdeen** [comment]
Man, I was a day late.

**Comment by MarjieAVolk** [comment]
:P It's okay, good to see if people are wanting the feature
