### ISSUE TITLE
Claiming property did not update minimap

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#701]

**Comment by stett** [comment]
Cannot reproduce - works fine for me on master. More details?

**Comment by panisch420** [comment]
just had this aswell. claimed some property but minimap doesnt update.
i relogged and still not updated. it also doesnt show my player right now. ive had a couple issues with the minimap not updating (i.e. i switch to the camas overlay and then i cant go back to normal / map doesnt change)

**Comment by stett** [comment]
hmmm will definitely be looking at this issue more closely today

**Comment by metachronism** [comment]
sean fixed this
