### ISSUE TITLE
Unable to link to Steam 

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7011]
From the support queue:

"I'm a Kickstarter backer. When I login and link to steam, everything on the steam end appears to work, and then the site sends me back to Strange Loop, the game isn't added to my library, and the Link To Steam button stays there.

I'll need some assistance with this, please."

---

(my reply)
"Hey Cody,
Your account shows indeed that the Steam linking process did not complete properly. We have no record of a link happening. This indicates that the process failed before the request even hit our servers.
Have you tried linking the game to Steam through a different browser? Or through Incognito mode (or the equivalent)? Maybe try doing so on a different device or network?"

---

Just tried Chrome, Chrome in Incognito, and Opera.  No change.  When it says "Confirm" or "Deny" allowing Eco to activate codes on my behalf, and I hit "Confirm", it takes me back to the Eco page, and nothing changes in Steam.

**Comment by rainfarmer** [comment]
responded in kayako

**Comment by rainfarmer** [comment]
fixed. user did not own eco yet.
