### ISSUE TITLE
USER ISSUE: Unowned Cart

### ISSUE THREAD

**Issue by Kirbiez** [StrangeLoopGames/EcoIssues#7012]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
After the most recent patch my server rolled back roughly 20 minutes. When logging back online my cart was listed as "unowned" and the deed says the same. I can still move and use the cart but I cannot pick it up with my hammer.	

**Expected behavior:**
When hitting my cart with a hammer while having the deed in my inventory I expect to be able to pick up my cart

**Actual behavior:**
After hitting my cart with my hammer it tells me I must have the deed in order to pick it up

**Comment by Kirbiez** [comment]
![cart](https://user-images.githubusercontent.com/37318830/38392378-27a2a302-38dc-11e8-8664-d9b5cf6f5ada.png)

**Comment by Dreepa** [comment]
Same issue here.
After server restart also. 

However, there was another thing: I also had a deed in my inventory from another player's cart.

**Comment by elfl0rd** [comment]
Looks fixed.

**Comment by MarjieAVolk** [comment]
Fixed in 7.6 (not the release today, but the next major release after that) -- hopefully :P  Deeds have been deeply revised.  Also, if this does somehow happen again, after 7.6 you will be able to re-claim your vehicle with a button.
