### ISSUE TITLE
Error while creating a new World

### ISSUE THREAD

**Issue by xTIMSoRx** [StrangeLoopGames/EcoIssues#7013]
When i try to create a new world, i always get this error: 
ApplicationName='S:/Steam Spiele/steamapps/common/Eco/Eco_Data\Server\EcoServer.exe', CommandLine='-nogui -loadSave="Welt" -specialtyMultiplier="0" -skillGainMultiplier="24" -spOnAction', CurrentDirectory='S:/Steam Spiele/steamapps/common/Eco/Eco_Data\Server'

http://prntscr.com/j1ggpj

I also can't join my own server running on my PC (even without AV-Software). It is just listed as offline.

**Comment by KinKyyGaming** [comment]
Having same issue and was told it was resolved. Curious if you could post the fix so I may attempt on mine?

**Comment by metachronism** [comment]
@xTIMSoRx can you verify that the folder exists in that location?
