### ISSUE TITLE
USER ISSUE: Cannot receive iron ingots

### ISSUE THREAD

**Issue by Vlad-Hatter** [StrangeLoopGames/EcoIssues#7017]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
1. Place Bloomery
2. Cook iron

**Expected behavior:**
Worked fine like it was

**Actual behavior:**
as soon as I upgrade my iron production, when I try to collect my iron ingots it says "Not enough inventory space". I'm assuming for the tailings, but I don't have anything in my carry slot.

**Comment by elfl0rd** [comment]
Ingots stored in inventory, not carry.

**Comment by MarjieAVolk** [comment]
Iron ingots are also very heavy.  Are you near your weight limit?  You can see this in the small vertical bar on the right panel of the HUD.

**Comment by Vlad-Hatter** [comment]
It was the weight issue.. I always forget about the weight limit

**Comment by MarjieAVolk** [comment]
Awesome :)
