### ISSUE TITLE
No refund when cancelling project with resources from stockpile

### ISSUE THREAD

**Issue by erocoar** [StrangeLoopGames/EcoIssues#7018]
I leveled up brick-production efficiency to level 4, and thought I would just restart my production of 100 bricks. But, I did not get any stone (or pitch) refund. Sorry if this is normal with higher tier items - but it seemed weird to me since I always got refunds up to this point

**Comment by MarjieAVolk** [comment]
No, this is not normal, you should always get a refund.

Was the project you cancelled already partially completed, or anything like that?  Also is it possible the refund went into a stockpile/cart you didn't expect?  Just double checking.

**Comment by erocoar** [comment]
Definitely not to another stockpile, it was 700 stones so I would have noticed it. The project was just started, so not completed at all!

**Comment by MarjieAVolk** [comment]
Okay, I will look into it at some point.  If you can figure out a way to reproduce this issue consistently, that would help me a lot.  If not, I will just mess around looking for it.

**Comment by D3nnis3n** [comment]
Not occuring anymore.
