### ISSUE TITLE
Could not start server error : Unable to currently play.

### ISSUE THREAD

**Issue by KinKyyGaming** [StrangeLoopGames/EcoIssues#7019]
(Running on Windows 10)
Purchased the game two days ago for myself and a few friends and started out a server. Everything worked fine for my wife and I, as it showed on LAN, but no friends were able to join. After following the wiki guide, I was then met with an error message, "Could not start server: ApplicationName='D:/SteamLibrary/steamapps/common/Eco/Eco_Data\Server\EcoServer.exe', CommandLine='-nogui -loadSave="Fail" -maxslots="1" -specialtyMultiplier="0" -skillGainMultiplier="24"', CurrentDirectory='D:/SteamLibrary/steamapps/common/Eco/Eco_Data\Server'" and nothing else.

(This message is also off a clean install, which has been done multiple times now)

When attempting to submit the bug report through the game popup it would bring the browser up after filling it out for me to log in and submit, and at that point it only tells me incorrect information. Logging in with same information without going through that message works fine. Attempting to load up the websites support button directing does nothing though.

After getting the link from a discord moderator I was able to load to here. 

Currently as it stands I am unable to even start a single player map without it giving me the exact same message and then the only way for me to exit that screen is by force quitting the game.

![unknown](https://user-images.githubusercontent.com/38134012/38423629-73b3bb32-397c-11e8-811f-69190f920a6d.png)

Thank you for any assistance, I greatly appreciate any help you can lend.

**Comment by metachronism** [comment]
@KinKyyGaming can you browse to your installed eco folder and see if the server resides there?  We've had reports before of some 3rd party apps "quarantining" the server when it runs, and this may have happened in your case

**Comment by KinKyyGaming** [comment]
The folder did in fact exist. Though at this point we are trying to refund
the game and that is all. Sadly I had hours that added up due to trying to
get this fixed and the game "running" at the error message while talking to
Pam for assistance, and now Steam is saying I have too many hours to get a
refund. Because I was trying to work with customer support I have too many
hours of not playing a game.

So if there would be any way you could assist in that? I spent 90 dollars
on the game, for my wife and myself and friend for his birthday. I would
greatly appreciate assistance in getting a refund due to the issue and
getting maybe 20 minutes of game time before the error.

Thank you for the assistance.

**Comment by KinKyyGaming** [comment]
You guys are beyond fantastic at your ability to reply not only on Discord
but it would seem here in email as well! Thank you so much, and I look
forward to leaving a review that definitely let's people know what the
customer service and just over all feeling they will get from your company
by going with it. Very disappointed.

**Comment by metachronism** [comment]
@KinKyyGaming sorry for late reply.  If you are still interested in trying some fixes, the 7.4 staging branch on steam may fix your issues.

Failing that, please contact support (support@strangeloopgames.com) and we can work on trying to get that refund approved.  Sorry for all the trouble you are encountering :/

**Comment by KinKyyGaming** [comment]
I definitely appreciate it, sadly my group I do not believe is willing to
give it a try at this time. It is a game that I am still greatly interested
in though, and should we decide to try a new game of this type again I will
revisit it. I will go ahead and contact support at that email.

Thank you again for your assistance Eric.

Greg
