### ISSUE TITLE
USER ISSUE: stuk in nowhere

### ISSUE THREAD

**Issue by mcmalonzo** [StrangeLoopGames/EcoIssues#7020]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
I was just walking

**Expected behavior:**
walk, illuminate with a torch, back on surface when shutting down and restarting

**Actual behavior:**
stay stuk. all is black, even the visual is compromised (face allways on same spot). torch doesn't illuminate what is around me. oif I close the game and reopen it, the bug is still operating (so I can't make anything at all...)

**Comment by SeanAtr0n** [comment]
did you try using "/unstuck" in chat?

what happens if you switch to 3rd person using the toggle in your backpack?

Could you send us a screenshot or something? I can't really understand the problem with this info
