### ISSUE TITLE
Accidentally placed item in not-owned claim are unrecoverable

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#7022]
Situation:
Claim next to claim

Problem: 
When building at the border of the claim, one singe miss-click (placing something in the other players claim) cannot be corrected.
But this generally applies to any accidental placement on other peoples claim.

Suggestion:
Add grace time to pick-up restriction for the case where not-property-owner places object on property. After grace time, placed object will belong to property-owner. Before that, it still can be picked up again.

**Comment by MarjieAVolk** [comment]
What kind of objects are you placing?  Typically you shouldn't be allowed to place objects on other people's property.  Are you talking about eg. a tree falling into their property?

**Comment by Dreepa** [comment]
I placed an iron pipe. But I was not able to pick it back up.

**Comment by MarjieAVolk** [comment]
Okay, you should not be able to do that, so turning this into a bug rather than a suggestion.

**Comment by SlayksWood** [comment]
Seems fixed for now. Sometimes you have some troubles with high pings, but it's another issue.
