### ISSUE TITLE
Corrugated steel: Shape1 and shape2 do not connect properly

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#7023]
Unlike all other construction blocks, shape1 and shape2 are not filling the gaps properly when adjacent.

![image](https://user-images.githubusercontent.com/37662083/38425971-a0b52baa-39b5-11e8-9ac8-75edeb54a5cd.png)

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/4286

**Comment by SlayksWood** [comment]
Still an issue 8.1.4

**Comment by keegan-o** [comment]
Cube form is now usable for this, and more forms with more options will be added. Floor blocks are not intended to always work as walls.
