### ISSUE TITLE
Authorization for Generators

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#7024]
i think the authorization for generators needs to be set to inherited by default as we have had trolls coming along and turning all our solar generators and wind turbines off

Edit : id almost go as far as saying anything put on claimed land should be default inherited 

2nd Edit i seem to be sharing my power with my neighbour is it at all possible to be able to limit the power to the claimed area and not have to share it

**Comment by craig-jong** [comment]
Auth was set to inherited by default.
