### ISSUE TITLE
When using pipes, hard to recognize empty fuel on blast furnace

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#7025]
When using pipes to transport the pollution to another area, you no longer see the smoke of the furnace.
Therefore it is hard to spot if a furnace is no longer working.

![image](https://user-images.githubusercontent.com/37662083/38433663-fe60dc52-39cb-11e8-8ead-a8c4fcb2c110.png)

I would suggest to add a little indicator to the crafting stations that show if they are running or not.
Like many mods in minecraft do, where just a texture turns a bit different, or a light is switched on, or a little sparkle effect is emmited, showing activity.

**Comment by MarjieAVolk** [comment]
Eventually we hope to have all objects be animated when they are running.

**Comment by WeaselDog** [comment]
This was a great idea. There is a nice animation now when it is running, with sparkles.
