### ISSUE TITLE
The paper skill is a skill tax

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7026]
Skill taxes, skills you need to take in order to progress but provide no purpose themselves, are bad for games. They provide purposeless blockages to the progress of the game. Deeds should not need to be made, and given how buggy the game is regarding them, you certainly shouldn't need to spend SP on a skill to fix a bug, which is currently the case.

All of the recipes that use paper should not. And the paper skill should be nixed.

**Comment by CuAnnan** [comment]
And please don't say "We have plans for other uses for paper". Because y'all are relatively committed to a six week release and the servers are less stable than Trump's ego.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#153
