### ISSUE TITLE
Not possible to see district on ingame map?

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#7027]
Seems it is not possible to show districts in-game on the map.

When planning actions, and there are laws concerning districts, it would be very helpful to actually see the districts

**Comment by TemporalWolf** [comment]
This is consistently a source of headaches... having to "fish" for district edges by walking back and forth in game is very annoying... having it as a map overlay (with show in world option) would be very nice.

**Comment by SlayksWood** [comment]
added in 0.9.0
![image](https://user-images.githubusercontent.com/45708377/71539716-8c3b2e80-2951-11ea-9498-6e3a63306097.png)
