### ISSUE TITLE
[Suggestion] Showing Server name for a Friend in Steam and also no friends on favourite Server

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#7029]
**Version:** 0.7.3.2 beta
![snap2129](https://user-images.githubusercontent.com/29383891/38434093-0c41eee4-39c5-11e8-97b7-5a3001a6f721.png)
as you can see from the Above snapshot i can Join a Server that My friend is on, and it works Great
![snap2128](https://user-images.githubusercontent.com/29383891/38434139-3cb5d356-39c5-11e8-80ea-e66e18a0333a.png)
but if i choose info about which server he is on it wont say, which is weird because it knows to connect me to it Directly.

also a weird thing, if i Don;t have a server as a favourite i see my friends name appear
![snap2126](https://user-images.githubusercontent.com/29383891/38434256-a53d38ce-39c5-11e8-9198-5162c01c27e5.png)
but if i do have it as favourite it doesnt show friend as online (which he is) and it also removes it from Friends listing
![snap2130](https://user-images.githubusercontent.com/29383891/38434310-cb19f1a4-39c5-11e8-90c6-68fd8b920203.png)

Other than those small Bugs ❤️

**Comment by MarjieAVolk** [comment]
For the friends list on favorites, I can address that in the server browser 2.0.  The steam server display thing sounds like an easy fix though @Nanders ?

**Comment by Conchipedia** [comment]
oh, one more thing, if i use it when my friend is online In Eco it loads up Eco perfectly and straight into the server, but sometimes when i quit, Steam Says it is still Running (nothing is showing up in Task Manager as running) so the only way to load Eco again is to Shutdown Steam Via the Task Manager
![snap2134](https://user-images.githubusercontent.com/29383891/38448724-7ee4a52a-39fe-11e8-8de4-77312f4898d3.png)
(as it doesn't always want to shut the nonexistent Eco down)
but this sometimes can happen just quitting eco from steam after a long session anyway

**Comment by MarjieAVolk** [comment]
I believe the friends thing is all fixed up in 7.4 now too.
