### ISSUE TITLE
Dumping the shovel should release dirt even with no block targeted

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#703]
Use the facing direction

**Comment by NafenX** [comment]
Yes, this. All the this.

Also, holding left and right mouse button together (or some other keybinding) with a shovel should dig the dirt and flick it behind you like in real life!

**Comment by johnkslg** [comment]
Removed feature label, I would call this a bug

**Comment by johnkslg** [comment]
It worked previously, many moons ago
