### ISSUE TITLE
Lan Connection failed

### ISSUE THREAD

**Issue by Markander** [StrangeLoopGames/EcoIssues#7030]
We are connected via Tunngle and a friend can see my game but when trying to connect a error comes: connection failed. I have startet a single player game and allowed players to join. Another friend can join with no problems.
We have tried with no firewalls

**Comment by MarjieAVolk** [comment]
Is this friend able to join other servers?

Here's a couple of suggestions for your friend to try:

* Try connecting directly by entering your IP address in the 'Join' screen
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO

**Comment by MarjieAVolk** [comment]
Oh, what messages did everyone see when the friend was kicked after joining for 20 seconds?

**Comment by zEverdeen** [comment]
@Markander Hey are you attempting to use Tunngle for a specific reason?

Have you tried to use port forwarding or similar?

**Comment by MarjieAVolk** [comment]
Closing due to no response.

We are also currently working on rewriting our server connection code, which we hope will solve a lot of connection problems like this.
