### ISSUE TITLE
USER ISSUE: FPS issues gone after reinstall

### ISSUE THREAD

**Issue by zEverdeen** [StrangeLoopGames/EcoIssues#7031]
Discord user Dunes.#8136 Ran into fps issues. (agrees to get contacted via discord or here)

"Hi, I just ran into a problem I did not have yesterday. Yesterday I was running the game fine 60~ FPS no problem. Now it is locked at 25 for some reason. I have tried V-Sync, playing around with the numbers, turning it off and on, nothing. Any help would be appreciated." - Dunes

![1dns](https://user-images.githubusercontent.com/31023534/38431948-37f4bea8-39c6-11e8-9501-41875b73262d.PNG)

![firstday](https://user-images.githubusercontent.com/31023534/38431966-4a2bf9b0-39c6-11e8-957e-96b88fd01325.PNG)

Screens of the fps:

![](https://cdn.discordapp.com/attachments/431845473494761485/431845492754874389/fgdfhadfhfgha.PNG)

![](https://cdn.discordapp.com/attachments/431845473494761485/431845496714297355/hgfahgfjafgj.PNG)

Settings on the second day:
"I have not changed anything from yesterday except shadows. I changed shadows to fastest today."
(This is the fps in the menu)

![unknown](https://user-images.githubusercontent.com/31023534/38432259-2fb53122-39c7-11e8-81ee-eb7a6d2b50db.png)

Had Dunes do a backup of favorite servers and worlds.
Then deleted everything in Steam->Eco and appdata->eco

New fps - settings are disabled or changed in the order the photos show

![](https://cdn.discordapp.com/attachments/431845473494761485/431861373316628510/unknown.png)

![](https://cdn.discordapp.com/attachments/431845473494761485/431861929070297088/unknown.png)

![](https://cdn.discordapp.com/attachments/431845473494761485/431862676461846538/unknown.png)

![](https://cdn.discordapp.com/attachments/431845473494761485/431862900462845954/unknown.png)

**Comment by SeanAtr0n** [comment]
render distance makes the biggest difference, it makes sense that dropping it from 150 to 100 would increase your fps significantly

**Comment by zEverdeen** [comment]
![](https://cdn.discordapp.com/attachments/431845473494761485/431924028672966687/unknown.png)

Asked the person to raise that. Sure enough.

If we are naive, why did the person then end up with lower fps from one day to the other?

"I have not changed anything from yesterday except shadows. I changed shadows to fastest today."

**Comment by SeanAtr0n** [comment]
you can't really compare a screenshot from the title scene to in-game, looks like the 3rd screenshot was in the title scene

**Comment by zEverdeen** [comment]
Alright. If it happens again the person will give a notice.

**Comment by zEverdeen** [comment]
I've been playing video games all my life. syncs/frames confuse me. Is it supposed to be refresh rate?

**Comment by SeanAtr0n** [comment]
vsync issues should be fixed in 7.4
