### ISSUE TITLE
USER ISSUE: Couldn't generate World (Linux)

### ISSUE THREAD

**Issue by BB20101997** [StrangeLoopGames/EcoIssues#7032]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
Start Game
Select New
Select Generat New
Select Start

**Expected behavior:**
Generate World and Start Game

**Actual behavior:**
Could not start server: Object reference not set to an instance of an object

**Comment by BB20101997** [comment]
![bildschirmfoto_2017-06-23_13-40-10](https://user-images.githubusercontent.com/3877590/38441975-d7ed8794-39e6-11e8-9fc5-5a523e7914f3.png)

**Comment by BB20101997** [comment]
![bildschirmfoto_2018-04-06_22-08-17](https://user-images.githubusercontent.com/3877590/38442035-239597fe-39e7-11e8-96b8-ad0388ad0eec.png)

**Comment by MarjieAVolk** [comment]
🤔 

Do you have any crash files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'?  If so, could you send them to me?

**Comment by MarjieAVolk** [comment]
Oh well actually, I don't think those will be the issue now that I think of it. 🤔 Possibly your client installation is messed up - you could try these things:

* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO

**Comment by MarjieAVolk** [comment]
Oh you are on linux.  Okay yeah, hope following that guide will work for you!
