### ISSUE TITLE
USER ISSUE: Friends keep getting disconnected

### ISSUE THREAD

**Issue by SoulTurtle** [StrangeLoopGames/EcoIssues#7035]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
1. create a game
2. have friends join you
3. after 5 or 10 minutes your friends will randomly disconnect

**Expected behavior:**
Everyone should stay connected to the hosts game

**Actual behavior:**
instead, after 5-10 minutes all friends will disconnect

**Comment by THEGOBBLER** [comment]
I had this exact same behaviour when I initially hosted a client server, though I'd imagine the issue is the same for a dedicated server hosted on your machine.

It was fixed for me when I went into my router settings and disabled universal plug and play.

**Comment by MarjieAVolk** [comment]
Thanks @THEGOBBLER.  As an update to you guys, we are currently working on overhauling our server connection code.  We are hoping this will resolve many of these problems, but it is hard to say.

**Comment by metachronism** [comment]
@SoulTurtle @THEGOBBLER if you can, try out the staging branch on steam as this issues should be resolved.  Let me know if that is not the case, thanks!
