### ISSUE TITLE
Better UI management required

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7038]
Needing to click and drag 25 times to move from one stockpile to another is a bad workflow.

There should be two buttons. Transfer all and transfer selected. Which do what they say on the tin. With the current click/drag functionality remaining so as to allow single transfers where needed.

**Comment by Baithoven** [comment]
Or maybe hold ctrl + leftclick to automaticly move the stack over?

**Comment by ecoemmeck** [comment]
Duplicate of #4280

**Comment by MarjieAVolk** [comment]
Thanks all, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4280
