### ISSUE TITLE
Fish do not grow

### ISSUE THREAD

**Issue by Baithoven** [StrangeLoopGames/EcoIssues#7039]
Hello,

Fish do not grow since 7.3.1  also in 7.3.2

When i start an new server with nothing on it all the fish are dying  without coming back!

![fishsss](https://user-images.githubusercontent.com/17210563/38450513-22f8e19c-3a1f-11e8-82f0-0f9a70849562.PNG)

**Comment by craig-jong** [comment]
The population of animals GENERALLY trend downward over time as the simulation settles a bit. It should be fine, though. I wouldn't really call this a bug unless your animals are zeroing out for no real reason.
