### ISSUE TITLE
[Suggestion] Storage Drawers

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#7040]
Since Chests now require solid ground beneath, the addition of Storage Drawers that can be stacked would be nice.

Also, stacked chests can still be fully used, but when opening them you automatically land on the screen where it says "No Solid Ground" first and need to change the tab to the storage, instead of being there on opening. Machines can also still put in and take items out without any problem. I'm quite wondering what the purpose of this is, enerving players?

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#152
