### ISSUE TITLE
Steam familyshare not working

### ISSUE THREAD

**Issue by sirvancobra** [StrangeLoopGames/EcoIssues#7041]
Hello,
my steam account is shared with one person but this can't play the game anymore.
Since 0.7.3.1 the feature is not working anymore. I can still play with my main steam account.
Great game and great developers, keep it up.

**Comment by sirvancobra** [comment]
I'm sorry but you misunderstood. Shared game can't be played either when main account actual playing or not. Of cause it would be unfair if you play together with one account at same time.

**Comment by styles784** [comment]
No, I understood - it would be unfair if anyone could play without paying for their own copy. Family share is great for single-player games, and that's it

It would also be unfair if one person could create a second (free) steam account, share their copy with that second account, and have a second presence on the server for double the skill points and such. Allowing family share has literally no benefit to anyone who wishes to play fair

**Comment by Nanders** [comment]
Family Sharing for Eco is not a feature we support.
