### ISSUE TITLE
Black screen in Eco

### ISSUE THREAD

**Issue by LeyzZONE** [StrangeLoopGames/EcoIssues#7043]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**

After creating the world interface on a black screen.On other servers, too.
**Expected behavioк**

Tried to reinstall, download the driver,but to no avail

**Actual behavior:**
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1886195/output_log.txt)

**Comment by SeanAtr0n** [comment]
Did your brightness slider somehow get set to 0?

Could you send a screenshot of your escape menu? Thanks

**Comment by LeyzZONE** [comment]
Well, thanks .Deal was in brightness.Strange for me was that the interface did not disappear.Good luck)
