### ISSUE TITLE
USER ISSUE: Lan Server

### ISSUE THREAD

**Issue by majamii** [StrangeLoopGames/EcoIssues#7045]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
Lan Server is shown as favourite, but Lan is missing. Connection ist not possible.

**Expected behavior:**
Connect to the Server

**Actual behavior:**
Connection failed

**Comment by zEverdeen** [comment]
@majamii This is the official discord: https://discord.gg/wmTJ4f

In the support channel we are ready to help you with trying to figure out what the network problem might be.

My initial thought is a firewall rule blocking on either the server or the client.

**Comment by MarjieAVolk** [comment]
Thanks @zEverdeen 

I'm not sure if you already got help, but here are some basic debug steps you can try.  If this doesn't work, going to discord for some real time advice might be easier for you.

* If the server is still loading, wait until it has finished before trying to join
* Try connecting directly by entering the server's IP address in the 'Join' screen
* Temporarily disable your firewall and/or antivirus software
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO

**Comment by MarjieAVolk** [comment]
Closing for now, assuming you got help elsewhere.
