### ISSUE TITLE
Corrugated steel material unlit: Too dark, few details visible, just black

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#7047]
Art wise, the corrugated steel block is not showing many details of its texture. Nor does it have any contrasting elements, especially in the shadow. It is just a dark blob.

![image](https://user-images.githubusercontent.com/37662083/38454847-41199db0-3a6f-11e8-89e7-2ac78b5aa2dc.png)

**Comment by keegan-o** [comment]
In this screenshot it looks like you have the brightness cranked up which can affect things strangely at the moment... other than that I think one solution to this is going to be re-considering how we use metalness maps in the game a bit, because I agree that this doesn't look good.

**Comment by Dreepa** [comment]
Well, you can do it on your machine and check it out I guess. I have not played with full detail (as even my Nvidia 1070 goes down to low FPS then). So maybe you will have different results.

For me, going into a steel building is like going into a cave. You kind of enter the void :)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#150
