### ISSUE TITLE
Reinforced Concrete Texture

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#7048]
I'm not sure if this in intended or not but it looks odd as you will see in the pics below the texture between the wall and floor are slightly different

it would be nice if the wall was smooth like the floor

Wall
![image](https://user-images.githubusercontent.com/29722757/38456093-c74b6c3e-3ac3-11e8-8f69-64be70b22f3d.png)

Floor
![image](https://user-images.githubusercontent.com/29722757/38456121-05d55af0-3ac4-11e8-85d2-58b71af6e675.png)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#149
