### ISSUE TITLE
Game is crashing graphic card driver

### ISSUE THREAD

**Issue by surcoufx83** [StrangeLoopGames/EcoIssues#7049]
Hi there,

I'm playing Eco since two weeks on a dedicated linux server. Since yesterday, my gaming computer seems crashing and I have to restart the entire computer.

At some point (can't determine exactly) while playing or while starting the game (both happend multiple times) that happens:
- Always: Both screens turn off and don't get signal from graphics card
- Always: Windows logs in the event viewer has hardware error
- Always: Eco continues plaing game sounds
- Always: Windows plays sound as hardware has been removed and added
- Sometimes (2 of 10 cases): graphics card turns on fans to maximum rpm
- Sometimes: Windows disables the Nvidia graphic card driver and boot up with Microsoft default display driver

Eco version: Beta 7.2.5 from Steam
Steps to reproduce: Keep playing for 0 ~ 60 minutes
[Crashes.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1886443/Crashes.zip)

System specs and OS:
Microsoft Windows 10 Pro (1709; Build 16299.309)
CPU: Intel i7-4770K
GPU: Nvidia GeForce 780 Ti with driver Version 391.35

I tested the following things:
- Activate the Windows 7 compatibility mode
- Reinstall Nvidia driver
- Install an older version of the Nvidia driver (from 05/2017 and 09/2017)
- Reinstall the game

**Comment by surcoufx83** [comment]
I forgot to mention: Eco is the only game where this happens. I'm playing other games without issues.

Right now, it also happend with Beta 7.3.2 from Steam, while switchen UI Language from English to Germin. No dump/log file has been written

**Comment by MarjieAVolk** [comment]
Hey, did you close this issue on purpose?

**Comment by MarjieAVolk** [comment]
Ah okay, thank you!
