### ISSUE TITLE
Recipes that require a skill should say the root level skill required if I dont have it

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#705]
![image](https://cloud.githubusercontent.com/assets/3536496/19747864/1b0449d0-9b93-11e6-96e4-e9e388c7dbb3.png)

I have to get carpentry before I can get woodworking, so it should say 'requires carpentry' until I have carpentry, then 'requires woodworking' 

Or perhaps 'requires Carpentry/Woodworking' to make it easier to find the damn things. Yes, lets do that.

**Comment by metachronism** [comment]
Theres multiple skills leading up to some even, way more than two

requires X/Y/Z/Q/A/B ?  also some require different skill levels in between those steps

**Comment by johnkslg** [comment]
I think displaying that many would be too much.  Thinking it should show:
[TopLevelSkill]/[Skill I Need]

or if there are multiple levels of skill acquisition needed which I dont have:
[TopLevelSkill]/[First skill down the hierarchy that I don't have]

This way, you always know which top level section to look, and you always know what skill you need to get next if you dont have the one needed.

**Comment by metachronism** [comment]
largely irrelevant now with clickable links
