### ISSUE TITLE
Aqueduct disables on a server restart

### ISSUE THREAD

**Issue by Seknor** [StrangeLoopGames/EcoIssues#7053]
**Version:** 0.7.3.2 beta
**Steps to reproduce:**
Have an aqueduct. Write initial moisture level for some blocks nearby. Wait for the new moisture level to kick in. Restart the server.
**Expected behavior:**
Moisture level remains about the same as it was before the server restart.
**Actual behavior:**
Moisture level drops to its initial level and the aqueduct ceases working altogether without any visible indication of doing so. Have to replace a couple of its blocks to kick it working again. Happened third time in a row after a scheduled server restart.

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/7263
