### ISSUE TITLE
Suggestion: Hunting seasons + elaborate hunting techniques.

### ISSUE THREAD

**Issue by zEverdeen** [StrangeLoopGames/EcoIssues#7054]
I would like to see hunting get a remake, as in you introduce hunting seasons, either by law or by real seasons, e.g. [season suggestion](https://github.com/StrangeLoopGames/EcoIssues/issues/3692).

Further more making hunting different animals meaning more difficulty and via different methods.
Introducing a limited resource might promt the player to over hunt more easily.

Discord user vvbudh, suggested that predators should be linked to a prey, so not killing too many predators, could snowball the (prey) population out of control, or killing too many (predators), would make little room for other species that the (prey) would be competing for food with.

> If kill too many predators
> prey population increase rapidly + die of starvation
> 
> If !kill too many predators
> predators increase in population + die of starvation

A modder named Vendetta#4338 made this: https://i.gyazo.com/1f858d8257a62c4e1a095eee8dc1f9b0.gif

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#148
