### ISSUE TITLE
USER ISSUE: Laws: unable to restrict mining with laws

### ISSUE THREAD

**Issue by FrancoisECO** [StrangeLoopGames/EcoIssues#7055]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
I have created a law to prevent the mining outside his own property, but it doesnt work, 

**Expected behavior:**
Unable to pickup stone with no mining skill

**Actual behavior:**
ca pickup a stone with no mining skill

**Comment by FrancoisECO** [comment]
![image](https://user-images.githubusercontent.com/37746405/38460111-bcdb27c2-3a81-11e8-988b-c2e2951a68a6.png)

**Comment by MarjieAVolk** [comment]
Ah, yeah looks like mining these doesn't count as picking them up right now.  It only counts if you pick up already mined rubble.  We should probably fix that.

**Comment by MarjieAVolk** [comment]
(That is, only if you pick up rubble that has been mined, and then picked up and placed in the world)

**Comment by Lex1co** [comment]
Would love to see this fixed as well. I feel a lot of economic problems occurring in mid to late game communities are based on abundance of ores. Tried to work on a functional law for this several times before.

**Comment by TrueBale** [comment]
+1

**Comment by MarjieAVolk** [comment]
Fixed in 8.0 - both mining and picking up loose rubble will count as "Pick Up" actions for stone and other minable blocks.
