### ISSUE TITLE
USER ISSUE: eEvveerryytthhiinngg  iiss  ddoouubblleedd  tteexxtt..

### ISSUE THREAD

**Issue by kicker22004** [StrangeLoopGames/EcoIssues#7058]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
lLaauunncchh  tthhee  llaatteesstt  eeccoo  oonn  lliinnuuxx..	

**Expected behavior:**
wweellccoommee  ssccrreeeenn  wwiitthh  uusseerrnnaammee//ppaasssswwoorrdd

**Actual behavior:**
aAss  yyoouu  ccaann  sseeee  eevveerryytthhiinngg  iinn  ggaammee  iiss  ddoouubbllee  tteexxtt..

**Comment by kicker22004** [comment]
It's not my keyboard as you can see here....

**Comment by zEverdeen** [comment]
Yes, you are having a kick out of the fact that the distro is giving you the input twice.

**Comment by kicker22004** [comment]
not the distro

**Comment by kicker22004** [comment]
This distro has been used for ALL of my linux testing on ECO and up until 7.1.3 it was fine, I haven't bothered with it since then so not sure about between that.

**Comment by SeanAtr0n** [comment]
does it matter if you run through steam vs the standalone download? (just tried on a fresh ubuntu install and the standalone one didn't have double type... although during our launch the steam one worked and standalone had double type)

**Comment by kicker22004** [comment]
Standalone, haven't tried steam

**Comment by morngrar** [comment]
I also have this problem. Both on ubuntu 16.04 and Fedora 26

**Comment by spannerman79** [comment]
This is ongoing.
On both stand alone client (obtained via https://s3-us-west-2.amazonaws.com/eco-releases/EcoLinux_v0.7.3.3-beta.zip ) and on steam.

Using Arch and Ubuntu 16.04 LTS

NB: Talking about **client** here - not server.  Client =! Server - I know the difference.

**Comment by morngrar** [comment]
In the meantime I got kinda tired of this. Made a thing to work around it: [ecopad](https://github.com/morngrar/ecopad)

It pads odd-length strings and puts them in your clipboard for pasting in the game.

**Comment by kicker22004** [comment]
This form of copy and paste wouldn't work when I tried it, as ECO Westworld simply paste it doubled.

**Comment by morngrar** [comment]
It works. I made it so that it pads a space character at the end if the length is odd numbered. Then when you press backspace it aligns no matter what. Numbers are another story, tho.

**Comment by morngrar** [comment]
I can finally write on signposts and make contracts, lol

**Comment by SeanAtr0n** [comment]
duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/3580
