### ISSUE TITLE
USER ISSUE: Brick Glitch

### ISSUE THREAD

**Issue by boomy46** [StrangeLoopGames/EcoIssues#7060]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
placed a brick next to coal and could see through the world

**Expected behavior:**
it shouldnt be able to see through the world

**Actual behavior:**
shouldnt see through the world
![20180408142842_1](https://user-images.githubusercontent.com/5836002/38464029-38f61a94-3b39-11e8-9d99-14885561e6f2.jpg)

**Comment by elfl0rd** [comment]
duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/4286

**Comment by MarjieAVolk** [comment]
Thanks, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4286
