### ISSUE TITLE
USER ISSUE: Stuck In ceiling

### ISSUE THREAD

**Issue by mcleangg** [StrangeLoopGames/EcoIssues#7061]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
I stacked logs in my house and I got stuck in the stack then I picked up the logs and I was still stuck in the ceiling.

**Expected behavior:**
Pushed me away from stack.

**Actual behavior:**
Consumed my character into the blocks

**Comment by GophTheGreat** [comment]
Try the /unstuck command in the meantime.

**Comment by SlayksWood** [comment]
dup #6238
