### ISSUE TITLE
[ECO Icon] After buying it on steam

### ISSUE THREAD

**Issue by Citroxe** [StrangeLoopGames/EcoIssues#7063]
Hi,

Could you possibly make the Eco icon not so pixelated after you bought the game on Steam and have it on the desktop? Maybe in high-resolution? Or is it not possible. Or is that because of my attitude.

Citrox

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/41872321-29470382-78ca-11e8-91af-3bebc8a0925d.png)
Just replace steam icon :P

**Comment by elfl0rd** [comment]
@D3nnis3n can you look? :D

**Comment by elfl0rd** [comment]
From Spudmeist3r

So on Medium icon size, the desktop icon is super blurry
![capture](https://user-images.githubusercontent.com/41703282/52868969-3c24f600-310a-11e9-9043-aa9a38752f9b.PNG)

**Comment by SlayksWood** [comment]
Still an issue
![image](https://user-images.githubusercontent.com/45708377/71539637-58133e00-2950-11ea-8268-5e78329a2c37.png)

**Comment by redwyre** [comment]
@keegan-o 
I had a quick look into this, it's the client icon specified at https://partner.steamgames.com/apps/clientimages/382310

A new one can be created from Client\Assets\Art\UI\Splash\Icon.png, and just chucking it into https://icoconvert.com/. I can do it, unless you want to keep the .ico file somewhere in your working folders.

**Comment by redwyre** [comment]
Actually I realised the server should have an icon, and it does at Server\Eco.Server\UI\EcoIcon.ico and it even includes a 256px version. I've uploaded that to steamworks but I'm not sure when that will updated clients (it's outside of the game itself so it will fix it for all versions).
