### ISSUE TITLE
USER ISSUE: Candle stand is not work, if stay on tables\chests\etc

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7065]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
1. Create candle stand
2. Create table
3. Place candle stand to table	
![20180408163632_1](https://user-images.githubusercontent.com/4980243/38468196-6ab05dee-3b4b-11e8-968b-bc6fc4c76993.jpg)

**Expected behavior:**
Working candle stand

**Actual behavior:**
"place on solid ground"

**Comment by craig-jong** [comment]
Changing to high priority since it should just take a CSV change.
