### ISSUE TITLE
USER ISSUE: Tallow Candle have same icon as Wall Candle

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7066]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
see on it.
![20180408164225_1](https://user-images.githubusercontent.com/4980243/38468281-4022473a-3b4c-11e8-9701-d711c70e3b4e.jpg)

**Expected behavior:**
Different icon

**Actual behavior:**
Same icon (remove "wall mount" part from tallow candle icon)

**Comment by keegan-o** [comment]
Doesn't have art yet but I put it on our list to do.

**Comment by elfl0rd** [comment]
:(

**Comment by elfl0rd** [comment]
Looks confusing in Carved Pumpkin receipe
![default](https://user-images.githubusercontent.com/4980243/50697945-bf0b5900-1054-11e9-912f-7c0b6a4ae838.png)

**Comment by SlayksWood** [comment]
move to #11977
