### ISSUE TITLE
ISSUE: Framed glass hitbox

### ISSUE THREAD

**Issue by DubsTheFox** [StrangeLoopGames/EcoIssues#7068]
The hitbox of framed glass Windows is to big
![hitbox thing](https://user-images.githubusercontent.com/37247290/38468845-e7d8426e-3b4b-11e8-8302-a3e986f0fe07.gif)

.

**Comment by keegan-o** [comment]
This is a good example of something going wrong with the collision simplifier.... the collider looks like this:
![image](https://user-images.githubusercontent.com/14983165/38702910-ae13bcb2-3e56-11e8-9568-302b09ceb0bd.png)

But becomes an entire voxel for some reason:
![image](https://user-images.githubusercontent.com/14983165/38703006-f53f5434-3e56-11e8-9505-a254fd52f3dc.png)

**Comment by keegan-o** [comment]
Fixed in master and thus hopefully for 7.4
