### ISSUE TITLE
USER ISSUES: Store Bug: "Not Authorized To Add Items There"

### ISSUE THREAD

**Issue by LisaKnittyCSI** [StrangeLoopGames/EcoIssues#7069]
I had an issue approximately four days ago where I was unable to buy things from my friend's store. At first it was two items. Then within a few hours it was all of his items listed. 

I went out of town for a few days and was able to buy items from his store about two days later. (For the record, I was on my laptop while traveling. When at home I am on my desktop.) When I returned home, I had no issues purchasing from his store. 

Yesterday, he was unable to buy some items from my store and from his wife's store. But he could buy from my husband's store with no issues. Today he cannot buy anything from my store nor his wife's store. 

No one else is having any issues buying to selling. We did update our server after the most recent patch. This issue started AFTER that patch.

**Comment by LisaKnittyCSI** [comment]
Just an update from last night about things we've tried.

I lost the ability to buy a few items from a friend's store this past Monday.
On Tuesday I was unable to buy anything from his store.
On Wednesday (from a different computer) I was able to make purchases from his store.
On Friday (from my original computer) I was able to make purchases from his store.
Yesterday, a friend cannot buy from my store.
Today the same friend cannot buy from my store and one other person's store but can make purchases from other stores.
Today, I am unable to purchase from a store I have been purchasing from all day.
We tried verifying Steam files. We tried a server reset. We made sure our bags were empty.

Has anyone else experienced this issue? Did you find a way to fix it?

**Comment by LisaKnittyCSI** [comment]
I forgot to mention, when someone buys from a store we get the notification that we've "received" however many of what item is bought. I hope that helps.

**Comment by johnkslg** [comment]
Going to look at this now. Are you on Discord? Would be great to have the save file this is happening.  Message me on Discord if you can I'm JohnK

**Comment by johnkslg** [comment]
discord.gg/eco

**Comment by LisaKnittyCSI** [comment]
We figured it out! My friend that could not buy from me and his wife realized that he had storage chests close to our stores. Those storage chests were "checked" as containers to deliver to. He unchecked them and can now buy again.

**Comment by johnkslg** [comment]
Ahhh great, it must not be paying attention to which inventory should receive the item properly. Passing back to you Marjie :)  Thanks for the report!

**Comment by MarjieAVolk** [comment]
What game version are you on?  Looks like I fixed this in 7.3.2, or at least thought I did https://github.com/StrangeLoopGames/EcoIssues/issues/6782

**Comment by MarjieAVolk** [comment]
Or wait, that might not have made it in to 7.3.2, might be in 7.3.3 which is coming out today.  Will double check.  I need to comment the version number when I do stuff like that O.o

**Comment by MarjieAVolk** [comment]
Okay, no that would have gone out with 7.3.2.  So let me know if you still have this issue on that version or later.

**Comment by LisaKnittyCSI** [comment]
We are currently on 7.3.2.

**Comment by MarjieAVolk** [comment]
Hm okay, thanks.  Any chance you could send over the save file?  I'd also need to know the coordinates of the store where this happens, and the coordinates of the chest(s) that need to be checked to make it happen.

**Comment by LisaKnittyCSI** [comment]
Which save file do you need? The one for the server? Or mine? Or my
friend's? Or all three?

**Comment by MarjieAVolk** [comment]
Any one save file where the error happens consistently.

**Comment by MarjieAVolk** [comment]
Hey @LisaKnittyCSI - I have been trying to repro this, but haven't seen it happening.  If you have a save file where it happens, that would be really helpful.

**Comment by MarjieAVolk** [comment]
I'm going to close this as 'probably fixed' in 8.0 (the next major release, not due out for a while)
