### ISSUE TITLE
Client Issue: Map Marker Performance issue

### ISSUE THREAD

**Issue by Jakob3xD** [StrangeLoopGames/EcoIssues#7071]
Version: 0.7.3.2 beta

Steps to Reproduce:
Create around 14 markes on the Map on different locations. This will reduce the GPU usage only a little bit. But if you uncheck "Display Offscreen", "Display Distance" and look away from them the GPU usage drops extrem. At my Computer to less then 30%. This occure in Multi- and Singelplayer. It also does not matter if the markes are only Text or a ItemIcon* is used.
When disableing all Markes the GPU usage will rice again. 

*With ItemIcon I mean the `<ecoitem item='GoldOre'>`

PC Specs:
I7-6700K @4.6 GHz
MSI GTX 1080 Armor
ASUS Z170 Gaming Aura
2x 8 GB Crussial DDR4 Ram

Expected behavior:
Map Markers are shown on Map without reducing the GPU Usage.

Actual behavior:
The more Map Markes are placed the more the GPU Usage get reduced.

**Comment by johnkslg** [comment]
Dropping critical as it doesnt break the game or feature

**Comment by elfl0rd** [comment]
@D3nnis3n Fixed in 0.7.8

> Map icons are now GPU accelerated! (drastically improves map performance in worlds with a lot of objects).

**Comment by D3nnis3n** [comment]
Indeed.
