### ISSUE TITLE
Top Layer of Map Determines Biome

### ISSUE THREAD

**Issue by Legends0** [StrangeLoopGames/EcoIssues#7073]
**Version:** 0.7.3.2 beta

I am not certain if this is a bug or just currently an undocumented feature, but the top layer of the map is what the server uses to determine the biome of an area and this does not seem to be the correct way to do so.

I was in a small forest biome that had a river going through it. It was high bean yield potential. I created a dirt bridge over the river without replacing the water. Area changed from forest biome to grasslands biome. This method of calculating the biome has been around since at least 7.0.

![image](https://user-images.githubusercontent.com/5702579/38472761-e742e6f4-3b52-11e8-8927-f23fe2839133.png)
This is an image of today's beanyieldpotential, before the tilled land you see was all yellow for beanyeild.

I expect to be able to create a flat forest with underground rivers. The bridge of dirt should not have changed the biome.

Another issue is that water seems to be ignored when calculating a biome, we get oceans that are considered forest biomes but no trees or dirt.

**Comment by craig-jong** [comment]
Yea, unfortunately world layers are 2D. This isn't really a fixable bug afaik - it's something that may be addressed during the biomes push.
