### ISSUE TITLE
unable to play online with friends

### ISSUE THREAD

**Issue by LRidley18** [StrangeLoopGames/EcoIssues#7074]
When I try to set a server up it always comes up with 'failed to start webserver: exception has been thrown by the target of an invocation' does anyone know how to fix this?

**Comment by metachronism** [comment]
Hey @LRidley18 this could happen for a number of reasons - one easy fix can be to run the server with administrator priviledges (right click->run as admin on the server exe)

if you are still having issues, can you ping me on discord?  we can try a few more things
