### ISSUE TITLE
Single player and local Server use the same default port

### ISSUE THREAD

**Issue by lightdrawn** [StrangeLoopGames/EcoIssues#7077]
When I have a local server running on default port (3000/3001, from Steam tools) and I try to start a new single player game it logs me on the running server instead of a new created world.

To change the default ports of single player server, seems to be the simplest/fasted solution to remove this behavior.

**Comment by GophTheGreat** [comment]
Working as intended, I think. There's this note on our Setting Up a Server page:

"*IMPORTANT* If you are installing a dedicated server on the same computer you have or will be running the client from, Network.eco will need to use 2 different ports other then 3000 and 3001. [Example = 4000 and 4001] Port Forward these two new ports and be sure set detectNAt = false once server is online."

**Comment by lightdrawn** [comment]
I understand what happened und I know how to change the ports, but this may be confusing for most common players and could rather easily be avoided.
