### ISSUE TITLE
USER ISSUE: No Workbench

### ISSUE THREAD

**Issue by tenpigs** [StrangeLoopGames/EcoIssues#7083]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
Followed all quests, logged out and back in

**Expected behavior:**
Should have been in back pack

**Actual behavior:**
no workbench in backpack

**Comment by MarjieAVolk** [comment]
So, you had a workbench in your backpack to start with, but logging out and back in made it disappear?  Or you never had one?

Were you playing on a locale server?

**Comment by tenpigs** [comment]
I have never had a workbench. I have relogged and nothing is there. 

I think I may be paying on a local server (ie my own computer, as I have not opted to join one).

I started the game months ago, didn’t get it to work after a few tries, and came back to it yesterday.

 

Thank you
