### ISSUE TITLE
Placing block in open door tile

### ISSUE THREAD

**Issue by ThrostGunnulf** [StrangeLoopGames/EcoIssues#7085]
Try to place a dirt block on an open door. It will allow you to do it, but then you can't change tools unless you pick it back up. Should it just not allow you to place the block there?

**Comment by SlayksWood** [comment]
Need add notification.
There is no notification about the inability to place block here:
![image](https://user-images.githubusercontent.com/45708377/61857557-17108c80-aecd-11e9-8bb6-01e5a69ae725.png)
or here:
![image](https://user-images.githubusercontent.com/45708377/61857467-e892b180-aecc-11e9-9ef0-73eb3d6f4673.png)
But when you try to place block here (Large Lumber Door), you have notification:
![image](https://user-images.githubusercontent.com/45708377/61857452-dfa1e000-aecc-11e9-8f5f-bd0227262da0.png)
