### ISSUE TITLE
Carts will frequently stop being dragged.

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7087]
They just get stuck in the ground.
Or start moving backwards. Or will only move in circles because one wheel has clipped (I suspect)

Version 7.3.2

**Comment by SeanAtr0n** [comment]
you aren't running out of calories and dropping it? (should be a temporary chat msg if that is happening)

**Comment by CuAnnan** [comment]
I am not

**Comment by CuAnnan** [comment]
If it helps, pushing the cart when it does this, instead of pulling, often resolves the issue. But they're super unmanageable when you do that.

**Comment by MarjieAVolk** [comment]
Oh, is this happening along the tops of ramps, where there is a little crevice in the terrain?

**Comment by CuAnnan** [comment]
At the top of one ramp and the bottom of the next is where it often happens.
I don't leave crevices.

**Comment by CuAnnan** [comment]
I use a road tool, to be clear.

**Comment by WeaselDog** [comment]
From https://github.com/StrangeLoopGames/EcoIssues/issues/6867
>I have the same problem in 7.3.2. I can't use my Wooden Cart any more. It used to work in 7.3.1.

**Comment by SlayksWood** [comment]
Seems fixed.
