### ISSUE TITLE
Please track trees cut down and trees planted

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7090]
It would allow a sensible law like "If number of trees planted > number of trees felled, you may cut down a tree, otherwise you may not"

**Comment by MarjieAVolk** [comment]
You can already check # of trees cut down (you do have to list every tree species manually - better support for checking all trees at once is in https://github.com/StrangeLoopGames/EcoIssues/issues/4088).  Adding a check for # of trees planted is in https://github.com/StrangeLoopGames/EcoIssues/issues/4077.

So yes, I would like to make this better :)  As soon as we prioritize working on laws again, I will do that.

**Comment by CuAnnan** [comment]
Thank you.
