### ISSUE TITLE
USER ISSUE: Pflanzen

### ISSUE THREAD

**Issue by Ponkilus1** [StrangeLoopGames/EcoIssues#7092]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
das wieder geht

**Expected behavior:**
das Pflanzen wieder wachsen 

**Actual behavior:**
Pflanzen wachsen nicht mehr

**Comment by craig-jong** [comment]
I'm not really sure what this bug is about - perhaps google translate is not doing it justice. Feel free to reopen this if more information is provided.
