### ISSUE TITLE
Laws need to be editable during the debate phase.

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7094]
Mistakes in laws require deleting the proposal and then adding a new one.

**Comment by MarjieAVolk** [comment]
Yes, I agree - your suggestion is similar to https://github.com/StrangeLoopGames/EcoIssues/issues/4079

As for the law being wrong when you propose it - that sounds like a bad error O.o

**Comment by MarjieAVolk** [comment]
I haven't heard about or seen the law not having the correct values when you hit propose.  If you have any more detailed steps about how to get this error to happen, that could be useful.  Thanks!

**Comment by CuAnnan** [comment]
It happened once. It think it was because I changed a later value later, which caused a post to be sent. Which cancelled the previous post. But I wasn't watching and haven't delved into your JS

**Comment by rainfarmer** [comment]
reset button is being added
