### ISSUE TITLE
Black screen since upgrading to Windows 10

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7096]
"When i start Eco then i see only a black screen an hear the sounds, the problem i have since i upgraded to windows 10"

**Comment by SeanAtr0n** [comment]
need more info... 
log from `%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

or screenshots... going to close this if we can't get any

**Comment by SeanAtr0n** [comment]
i would need some sort of info to debug this... closing
