### ISSUE TITLE
Official site, classroom pack is out of screen and no horizontal scrolling.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7099]
On official site, https://ecoauth.strangeloopgames.com/home pack "Classroom" out of screen, and page can not contain horizontal scrolling.
Firefox 59.0.2 64bit, display resolution - 1280*1024 (it's my additional monitor).
On chrome - horizontal scrolling available.
(ff window in fullscreen mode)
![2018-04-09 23 08 57](https://user-images.githubusercontent.com/4980243/38520325-2601b250-3c4b-11e8-8b1d-61a257448e0d.png)

**Comment by rainfarmer** [comment]
aware of this display error. thanks.
will fix asap
