### ISSUE TITLE
Steam players news section, where to go

### ISSUE THREAD

**Issue by lightdrawn** [StrangeLoopGames/EcoIssues#7104]
Steam users often don’t find their way to official news, bug reports, discord and whatever else their is, please show us where we are supposed to go.
Please make sticky posts, with the most important links to your other sites.
here https://steamcommunity.com/app/382310/discussions/
and here (German) https://steamcommunity.com/app/382310/discussions/10/

Thank you very much. :)

**Comment by MarjieAVolk** [comment]
Steam players do have the Report a Bug buttons, available in a couple of places in game.  But that is a good idea, thanks :)

**Comment by ShaydenMac** [comment]
Done! Thanks for the suggestion lightdrawn. :)
