### ISSUE TITLE
In-game ui enhancement, split the world layers into different drop down menus.

### ISSUE THREAD

**Issue by lightdrawn** [StrangeLoopGames/EcoIssues#7106]
Still only one Layer should be visible at any time. I found it easier to create a picture than trying to explain. Just a quick example.
![example](https://i.imgur.com/OCJie6i.png)

**Comment by MarjieAVolk** [comment]
@craig-jong assigning you because I think to do this we will want to have some kind of official grouping / hierarchy of world layers, which I don't think we have right now.

**Comment by MarjieAVolk** [comment]
Fixed in next major release
