### ISSUE TITLE
Suggestion: Visible object/block information in the UI without interacting or opening object

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#7107]
Hi!

A great improvement to the UI would be the addition of a UI/HUD element similar to the highly popular WAILA / The One Probe mods from Minecraft, which, through a tooltip, informs the player about "What am I looking at" [WAILA]

Examples:
![image](https://user-images.githubusercontent.com/26847645/38547553-b36de764-3c85-11e8-918d-f01561ea220b.png)
![image](https://user-images.githubusercontent.com/26847645/38547562-b71828ca-3c85-11e8-8624-f87ab64574ba.png)

This would help immensely when dealing with multiple chests/storage, for instance, especially due to the [lag/freezes experienced by players when opening the screen of an object](https://github.com/StrangeLoopGames/EcoIssues/issues/6903).

Thank you!

[This suggestion comes from a series of suggestions discussed between me and Steam/Discord player mattevi#7762]

**Comment by lightdrawn** [comment]
You can read the by players given names of the objects and some more info when you mouse-over their icons on the map (m).
And for info on plants and blocks there is the Soil Sampler Tool (craftable).

**Comment by gabeux** [comment]
Not sure what you mean. There's also the Wiki. Doesn't mean the in-game encyclopedia HUD / information about crafting recipes, items and other entities when hovering over their names aren't valid or incredibly useful and saves time.

Soil sampler info should be kept to soil sampler usage. Although having the UI/HUD element be context-sensitive, displaying different information based on held tools, would be amazing and pretty unique.

**Comment by lightdrawn** [comment]
I’m sorry, english is not my first language, what is confusing you about what I wrote?
If more information about your in-game surrounding is not what you (or mattevi#7762) are looking for, then I misunderstood, I never used that Waila mod.

![Imgur](https://i.imgur.com/9AHuoUM.png)

![Imgur](https://i.imgur.com/swQYIyZ.png)

**Comment by PacifyerGrey** [comment]
This is something I feel is missing from the game. Due to lighting you can confuse block types (sand vs dirt, ores) and you can miss plants if you are not holding proper tool in tool hand (like shovel vs kamas).

I generally expect the game help me identify what am I pointing at and give certain hints as what to do with it. We do have later in many cases but some exxessive tooltips (like chest name on the previous poster screen) would help a lot.

**Comment by lightdrawn** [comment]
Maybe it's because I started gaming in the late 80s, there was no hand holding like this at all, I got used to it. ^^
But please, if this makes it into official client, make it optional. I really enjoyed to figure out the camas/shovel thing on my own (3rd day of playing). :)

**Comment by MarjieAVolk** [comment]
I guess there are people on both sides, as usual :P
