### ISSUE TITLE
Suggestion: Ability to Replace blocks with Carried Item on hand

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#7108]
Hi!

A really neat feature to have would be the ability to replace blocks. There are many ways this could be designed and implemented, but here's our take on the general idea:

A skill in the Survivalist tree could be in place to enable the ability of carrying two Carry items, _"one item for each hand"_. Stack/weight could be limited and shared by the amount of both hands, rather than having 20 items on each.

This would enable further functionality, such as enabling a player to keep Brick in one hand, and the other hand free. When hitting the hammer on a Hewn Wood Block, using Right Mouse Button or Modifier + Left Click, it would replace the Hewn Wood Block by the Brick Block, and place the Hewn Wood on the players' then empty hand.

Or, bringing two types of construction materials, the player could build faster, with more detail.

An example of the idea can be given through the game Stationeers, although in it there's no weight limit to what can be carried on the players' hand - only stack sizes. 
_However, in Stationeers, a Tool [like the Hammer] would occupy one of the 'carry' slots, defeating the purpose intended for this Eco suggestion._
![image](https://user-images.githubusercontent.com/26847645/38548355-ef82c3c6-3c87-11e8-86af-46952f5fa0ec.png)

Thanks!

[This suggestion comes from a series of suggestions discussed between me and Steam/Discord player mattevi#7762]

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#146
