### ISSUE TITLE
Minor visual bug: My flying washing machine

### ISSUE THREAD

**Issue by lightdrawn** [StrangeLoopGames/EcoIssues#7109]
I found this only as a closed issue: USER ISSUE: Floating Washing Machine #5141
But I still have that bug, it’s like the washing machine position is not properly adapting to the visual rounding of the worlds surface.
The height of the block it’s standing on is 81 (4th floor).

![Imgur](https://i.imgur.com/eIiaq5V.jpg)

**Comment by keegan-o** [comment]
Fixed in master and should get in to 7.4
