### ISSUE TITLE
Vehicles dont open

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#711]
UI Missing?

KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[System.String,Eco.Shared.Serialization.BSONValue].get_Item (System.String key) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:150)
Eco.Shared.Serialization.BSONObject.get_Item (System.String key)
UI.WorldObjectUI.Init (Eco.Shared.Serialization.BSONObject bsonObj) (at Assets/UI/Scripts/WorldObject/WorldObjectUI.cs:52)
GenericClient`1[T].OpenUI (System.String uiName, Eco.Shared.Serialization.BSONObject bsonObj, Boolean toggle) (at Assets/Scripts/Networking/GenericClient.cs:59)
GenericClient`1[T].ToggleUI (System.String uiName, Eco.Shared.Serialization.BSONObject bsonObj) (at Assets/Scripts/Networking/GenericClient.cs:40)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)

**Comment by metachronism** [comment]
verified as working in master
