### ISSUE TITLE
Candle stand not placeble on table & if on it candle is not on solid groud

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#7114]

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/38573269-cf622e10-3cf5-11e8-9aa2-2b55398997dd.png)
![image](https://user-images.githubusercontent.com/31536813/38573285-dc37953a-3cf5-11e8-8773-770ca1466188.png)

**Comment by elfl0rd** [comment]
Duplicate, https://github.com/StrangeLoopGames/EcoIssues/issues/7065

**Comment by MarjieAVolk** [comment]
Thanks, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/7065
