### ISSUE TITLE
English and russian fonts have huge difference in the space occupied

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7115]
It's make translation... Terrible?
![unknown](https://user-images.githubusercontent.com/4980243/38574068-87b59466-3d00-11e8-8682-c7951b8f650a.png)
![20180410205007_1](https://user-images.githubusercontent.com/4980243/38574309-35619f60-3d01-11e8-8bd5-a06d5ca6df80.jpg)
![20180410204859_1](https://user-images.githubusercontent.com/4980243/38574314-3780a2f0-3d01-11e8-9bda-9ed73a4b7cb9.jpg)
![20180410204903_1](https://user-images.githubusercontent.com/4980243/38574315-37a20896-3d01-11e8-898e-ae7a4ccfe795.jpg)

**Comment by elfl0rd** [comment]
Please use font with same (or less) space!

**Comment by MarjieAVolk** [comment]
It's going to be a big task to touch up all of our UIs in order to better support various languages and various lengths of different words, etc.  As far as I know, we haven't done too much work on that yet.

But in this case, it's possible a font change would make a big difference.  Not sure if that's possible @Nanders ?

**Comment by elfl0rd** [comment]
Yes, i speak with it on discord.

> [21:00] Nanders: If anyone here has suggestions for a better Cyrillic font its pretty easy to change
> [21:05] Nanders: Right now Eco uses three fonts, the primary english one, plus two additional 'fallback' fonts (one for Cyrillic and one for CJK) to cover characters not in the primary.
> So really would just need a font where the Cyrillic characters match the main font better
> [21:06] GDragon: Please say main font name?
> [21:06] Nanders: Perspective sans
> [21:06] GDragon: thx

I'll try to find compatible font with smaller letters.

**Comment by elfl0rd** [comment]
[22:06] GDragon: can you check, you use same size on both fonts? regular\bold?
[22:09] GDragon: currently, it's looks like as you use light\regular to Perspective sans and regular\bold to Arimo
[22:10] GDragon: if it's not correct, maybe try light Roboto Condensed
[22:12] GDragon: cyrillic symbols looks like as latin in perspective sans
[22:13] GDragon: and light version provide more space to long russian words.
[22:20] Nanders: Actually looks like something crazy is going on with boldness settings, yeah
[22:21] Nanders: I will touch that up

**Comment by elfl0rd** [comment]
And if available, pleace replace cyrillic font to https://fonts.google.com/specimen/Roboto+Condensed
(in Light style).
it's more compact, provide more space to longer russian words.
And have letters missing in current font. (ёЁ and more).

**Comment by Nanders** [comment]
I've replaced the font to what was suggested. 
The rest of the UI refactor is in progress, and is beyond the scope of one singular bug, so closing this.
