### ISSUE TITLE
Storage UI Stockpile Duplication bug

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#7117]
I have 2 stockpiles that are bugged a glass and a brick stockpile which show up as doubles in the storage ui.

when I try to consolidate the items into the stockpiles it duplicates the materials.

I'm currently trying to find a fix to remove the stockpiles that duplicate items any ideas would be appreciated

**Comment by ecoemmeck** [comment]
after having some sleep i was able to figure out a fix for this problem.

i moved the items to new stockpiles and removed the original stockpiles the issue was that for some reason there was 2 stockpiles on top of each other I'm assuming this happened during a restart where it sometimes duplicates objects

this can probably be closed now

**Comment by metachronism** [comment]
closing as dupe of the stockpile/object duplication bug #5895
