### ISSUE TITLE
MacOS Steam version 0.7.3.2 some impressions

### ISSUE THREAD

**Issue by lightdrawn** [StrangeLoopGames/EcoIssues#7118]
Server and single player seem not to be working at all.
The performance on my MacBook Pro felt like <1fps, I usually can’t max recent games on this (because the graphics chip is a bit crappy), but almost everything is well playable on medium graphics settings. 
 
MacOS Sierra 10.12.6
MacBook Pro (Late 2013)
i7, 16gb ram, ssd and Intel Iris 1536 MB

With a lot of patience I made it to Advanced Settings, Resolution was set to 3360x2100 (native retina display), no more wonder this is not working. xD
Changed to 1280x800 and got 8 fps at the title screen with almost everything maxed. :D
And now with 8 fps it can also discover servers :O
After I restarted the client the resolution was back to 3360x2100. I set the Render Scale to 10% instead, 16 fps then. 
(I wish there were a Reset button in the main options window as well.)
Set almost all settings to min, looks ugly, but 26 fps. 
I needed several tries to join one of the local servers, still looks ugly but works, but when I wanted to try the other again, the server window was empty again.
The initial loading up to the windmill screen still takes about 3 minutes (for the first minute the screen stays black). :(
Trying to disable Full Screen does strange things and resets itself after restart of the client (like resolution).
When I switch to another application (cmd + tab), it's not possible to get the Eco window back, I only can kill Eco process then.
The Join a Server window, seems to be working just once after each client restart, if I open it a second time it's empty.

I give up for today, enough for you to read and inspire you to hunt down all those nasty bug. :)
I was very exited when I read there is a mac version, I'm still, in some time I can play Eco also on my laptop. :)

Some screens/error messages: https://imgur.com/a/gVhhV

**Comment by Cheveyome** [comment]
I have almost the same problem with my Retina iMac.
When I start the game it takes a long time (several minutes). Finally in the main menu, I always have to go to advanced settings to change the resolution from 5120x2880 back to 2560x1440.

**Comment by SeanAtr0n** [comment]
Have you tried 7.3.3? It should load more quickly in osx

Yeah there is no way the game would run on a macbook at retina resolutions, we should probably automatically limit the resolution

**Comment by lightdrawn** [comment]
When I start Eco there still is the black screen first, about a minute, after that things speed up with 7.3.3, yes. :)

Most annoying to me, especially on Mac I'm so used to cmd+tab, I forget that it crashes Eco. xD

And second most annoying, is the empty server list window, on second time opening it or refresh button (only comes back after Eco restart).

**Comment by BlazeGuy2** [comment]
@lightdrawn @Cheveyome are you still having issues with this?

**Comment by lightdrawn** [comment]
Sry, forgot to update.

v0.7.4.6:
Black screen is gone and startup loading a lot faster now. :)

But still, when I switch out of full screen with Cmd+Tab I can’t switch back, have to kill the task and restart Eco. 
Changed graphics setting now seem to save properly on client exit (except resolution), and Cmd+Tab works well as long it’s windowed mode.

The new server connect window is really nice, a lot better than before, but sometimes bit buggy (non-reproducible, on windows too). And local lan server are invisible, connecting by ip works always, but they are also not in recent list, so I can’t favorite them, every time I want to connect I have enter the ip directly.

Overall performance, is mostly well on very low graphics settings.

**Comment by SlayksWood** [comment]
In 8.1.4, besides low FPS, there are no special problems with download speed.
I will close this issue and move it to #5119
