### ISSUE TITLE
"Delete all markers": No confirmation check

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#7119]
On the map: The button "Delete all markers" is right next to a button of the opposite function "Place marker".

Missclick can thus happen easily. And all markers are gone.

-> Add confirmation dialogue to "Delete all markers"

**Comment by wraithan** [comment]
Just wasted over an hourof work marking out roads and other locations because of this UX failure, please fix this.

**Comment by johnkslg** [comment]
Fixed! Thanks for the report.
