### ISSUE TITLE
Failed to start Webserver

### ISSUE THREAD

**Issue by LostWood4** [StrangeLoopGames/EcoIssues#7120]
Hello,

I am using the Steam version of Eco, and have been trying to use the Eco Server tool. However, every time I start an Eco server I get the error: 

**Failed to start Webserver: Exception has been thrown by the target of an invocation.**

![webserver failed to start](https://user-images.githubusercontent.com/38262351/38578965-62ef8a5e-3cfd-11e8-9d9d-39c6042cefce.PNG)

I run it as Admin and still get the same error.

I have used this command in an elevated console:
**netsh http add urlacl url=http://+:4001/ user=Everyone (I replaced "everyone" with my user)**

and received:
**Url reservation add failed, Error: 183
Cannot create a file when that file already exists.**

I have port forwarded on both the firewall and router, however when I check the ports the GameServer is open but the Webserver is not.

What ever port Webserver is on appears to be closed even if i know that the port has been port forwarded correctly.

Any idea what my problem could be? 

Thanks.

**Comment by metachronism** [comment]
Sorry for late reply, but you need to use netsh to delete that urlacl, before then re-adding it.

still not quite sure why SOME PCs have this reserved by default
