### ISSUE TITLE
USER ISSUE: MOUSE IS CRAZY

### ISSUE THREAD

**Issue by TheBeardGuru** [StrangeLoopGames/EcoIssues#7121]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
Just by lauching the game(steam )	

**Expected behavior:**
A normal pointer ?!

**Actual behavior:**
The pointer of the mouse is crazy: stuttering and slow and even jumping across the screen

**Comment by SeanAtr0n** [comment]
I'm guessing your frame rate was low? Did you try adjusting the graphics settings? Usually render scale makes the biggest difference on high resolution monitors

**Comment by TheBeardGuru** [comment]
I didn't work but thank you for your response.

**Comment by BlazeGuy2** [comment]
@TheBeardGuru are you still having this issue?
