### ISSUE TITLE
Pingperfect server issue.  Players unable to connect.

### ISSUE THREAD

**Issue by Henolicro** [StrangeLoopGames/EcoIssues#7122]
Don't have many clues on this one as it happens when I'm at work and don't know what actions the players take to cause this.  But this is the server log I've come home to the last 2 days and players say they couldn't connect to the server.

![screenshot 2](https://user-images.githubusercontent.com/38217801/38583552-fb4ee080-3cd8-11e8-92dd-fea8e2ff24ed.png)

**Comment by MarjieAVolk** [comment]
Looks like https://github.com/StrangeLoopGames/EcoIssues/issues/6996 - closing as duplicate
