### ISSUE TITLE
Interact does not work the first time after tabbing out of UI

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7124]
Makes things feel really sloggy and unresponsive.

Tab out of a UI
Target an object, press interact key (nothing happens)
press interact key again (works)

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/4918?

**Comment by SeanAtr0n** [comment]
fixed 7.4
