### ISSUE TITLE
Singelplayer and Multiplayer connect Error

### ISSUE THREAD

**Issue by PlayLikeSven** [StrangeLoopGames/EcoIssues#7125]
Dear developers,

is my PC crashes, after I no longer reinstalled the game eco and did nothing, generated in a single player and all that then gives connection in connection, he invites tot.und in multiplayer shows me all servers as offline is one even though they are online; (Why can that be, otherwise has problems?

Then gets the following error compared to:

![](http://ecoforum.strangeloopgames.com/uploads/files/1523397471053-image.png)

**Comment by MarjieAVolk** [comment]
Hey there, sorry you are having trouble connecting.  I'm not sure I understand your situation exactly.  You can no longer load your single player world?  And also all servers in the join screen show as offline?

If you are unable to load your single player world, could you send me any files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump'?

Here are a couple of general troubleshooting steps you can try:

* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software
* If none of those work, you might try nuking it all - Uninstall Eco, shut down Steam, delete the AppData folder, restart your computer, reinstall the game.

**Comment by PlayLikeSven** [comment]
Hello,

here is the link for the desired file, unfortunately, it is still not, despite reinisntalation, etc. what could that be? Yesterday at noon everything went, from the evening not more; (Need very urgently because of Lets play

https://www.dropbox.com/s/jopsmbvghbkwdgq/Crash%20SocketException%2004101541.ecodmp?dl=0

**Comment by MarjieAVolk** [comment]
Okay, it looks like your crash file is saying your ports are already in use.  Are you trying to run two servers on the same computer?  Playing with your network config might help you - setting the ports and/or the ip address to something else, for example.

Looks like we have gotten a small handful of similar stack traces before, but never identified a bug that might be causing them (either the reporters found a configuration solution, or stopped responding).

**Comment by PlayLikeSven** [comment]
Hallo Liebes Entwickler-Team,

habs nun hinbekommen,vielen Dank für ihre Hilfe! LG Sven

http://www.youtube.de/user/PlayLikeSven

2018-04-11 22:33 GMT+02:00 MarjieAVolk <notifications@github.com>:

**Comment by MarjieAVolk** [comment]
Froh das zu hören. Vielen Dank!
