### ISSUE TITLE
Collecting a workorder gives you items one at a time

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7126]
Spamming the chat log

![image](https://user-images.githubusercontent.com/6262198/38585855-4420327c-3cd0-11e8-90ab-b3205ad1c4bc.png)

**Comment by WeaselDog** [comment]
No longer an issue. Here is the new notification:
![WorkorderCollection](https://user-images.githubusercontent.com/47330823/70856927-d6280d00-1e99-11ea-8356-8de4df244504.png)
