### ISSUE TITLE
Player location changes to NaN,NaN,NaN

### ISSUE THREAD

**Issue by 10KEco** [StrangeLoopGames/EcoIssues#7128]
I have a player on the server that randomly teleports to a location of NaN,NaN,NaN. Once in location NaN,NaN,NaN the player can not move at all and if logged off will not be able to log back on until the server restarts. This happened twice in the past 12 hours.

![xxunicorncookiesxx location](https://user-images.githubusercontent.com/37884814/38590129-327dfe6e-3ce4-11e8-9b5b-af86136b6333.jpg)

**Comment by bingliCheng** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/6730

**Comment by SeanAtr0n** [comment]
Should be fixed in 7.4, also modified /unstuck so it can fix these situations
