### ISSUE TITLE
Chat lines overlap sometimes when at min chat window width

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#7130]
Normal:
![image](https://user-images.githubusercontent.com/37662083/38597247-c85fee8e-3d56-11e8-8d8c-a3951bb0dc07.png)

Resizing horizontally (making it smaller) leads to this:

![image](https://user-images.githubusercontent.com/37662083/38597268-e1f94214-3d56-11e8-9a05-29a33ee26b57.png)

**Comment by SlayksWood** [comment]
Seems fixed.
