### ISSUE TITLE
Power grid improvements

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#7133]
Without plans for future improvements that I know of, I would like to start some suggestions for this,

A power grid in the real world does use wires, without wires, you cannot have a connection.

So, for the start, I would like wired connections to be possible, even if you don't physically put down wires, but instead connect 1 device to another without any visuals.

Then, there is grid and authorizations, if a home has a grid, and doesn't want to share it's power with someone else, then let it have local power, with the above system, you'll just disconnect the generator from another generator, having the ability to have local / city power grids.

More suggestions will be added in the coming days

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#145
