### ISSUE TITLE
Power grid improvements - Blackouts and Loads

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#7135]
Moving into more advanced power grid management, I would like to see a more realistic effect on supply / demand, 

Whether having a small allowance where if supply is lower then demand, having things slow down and lights dim,
or
Devices which are further away from source of power, be completely off if the demand cannot hold up power to them.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#143
