### ISSUE TITLE
USER ISSUE: Random block losses

### ISSUE THREAD

**Issue by Heldenstueck** [StrangeLoopGames/EcoIssues#7137]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
At certain places it can happen that you place a block then disconnect and when you reconnect the block is gone. I'm happy to share an example in a message.

**Expected behavior:**
The block should be there after loading the game again	

**Actual behavior:**
The block is gone an nowhere found again

**Comment by Heldenstueck** [comment]
An example would be server  DESKTOP-BF549P5 in the brick floor at 77,45,537

**Comment by metachronism** [comment]
we've fixed this in 7.3.3, was a plant loading issue
