### ISSUE TITLE
No SkillPointPerCrafttime not in function under Server with Ubuntu 17.10

### ISSUE THREAD

**Issue by Schaboom** [StrangeLoopGames/EcoIssues#7138]
Hello,
I have a Problem. I have setup a Linux Server Ubuntu 17.10 with actual ecoserver. 
My Config in Difficulty.eco is:
{
  "$id": "1",
  "CollaborationPreset": "MediumCollaboration",
  "UnlearnRefundRate": 0.5,
  "SpecialtyCostMultiplier": 1.0,
  "SkillGainMultiplier": 1.0248,
  "SkillPointsPerAction": 0.0,
  "SkillPointPerCrafttime": 0.03
}

When i connect to the Server an i craft a Item (any Item) the i become no Skillponts..

Can you pleas help me? 
P.s. sorry for my bad English ;)

**Comment by SeanAtr0n** [comment]
@craig-jong does that setting for SkillPointPerCrafttime look right? not sure if this is a linux specific issue yet

**Comment by craig-jong** [comment]
If you crafted something small enough, it might not show you any sp gain. So I'm not sure if it is either.

**Comment by craig-jong** [comment]
Closing because I'm not sure this is actually a bug. Please reopen if you have more information, but for now I'm going to assume the sp/gain was too small to notice. Try setting the number higher and let me know if it still doesn't work.
