### ISSUE TITLE
Missing localization string.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7139]
![20180411204215_1](https://user-images.githubusercontent.com/4980243/38634163-6970e51c-3dca-11e8-875d-eb7f77e94b02.jpg)
![20180411204227_1](https://user-images.githubusercontent.com/4980243/38634234-8f480e64-3dca-11e8-8e62-05ecd79e61d4.jpg)
![20180411204730_1](https://user-images.githubusercontent.com/4980243/38634493-4fe3c758-3dcb-11e8-8d2b-4afc0146f34d.jpg)
![20180411204839_1](https://user-images.githubusercontent.com/4980243/38634494-50025e7a-3dcb-11e8-9ab0-ec87d1a2c9fe.jpg)
@Nanders 
(and lot of more)

**Comment by elfl0rd** [comment]
Have? localisation, but not used.
![20180411211507_1](https://user-images.githubusercontent.com/4980243/38635312-a1d20762-3dcd-11e8-866a-a3e484d87975.jpg)
https://crowdin.com/translate/eco-by-strange-loop-games/3/en-ru#26105

**Comment by elfl0rd** [comment]
![20180411213341_1](https://user-images.githubusercontent.com/4980243/38636222-4497dbaa-3dd0-11e8-9031-fd357f7ac3c4.jpg)
And "hew logs" suggestion - https://github.com/StrangeLoopGames/EcoIssues/issues/6958

**Comment by elfl0rd** [comment]
![20180412201336_1](https://user-images.githubusercontent.com/4980243/38693562-f39f7382-3e8f-11e8-8e98-ea6e10a9a716.jpg)
![20180412193714_1](https://user-images.githubusercontent.com/4980243/38693563-f3c5af8e-3e8f-11e8-9661-8acb7870aabc.jpg)
![20180412195110_1](https://user-images.githubusercontent.com/4980243/38693564-f3e946f6-3e8f-11e8-8cc4-4f661418bcda.jpg)
![20180412200601_1](https://user-images.githubusercontent.com/4980243/38693565-f40b9792-3e8f-11e8-9264-4a27974ca888.jpg)
![20180412201305_1](https://user-images.githubusercontent.com/4980243/38693566-f42d196c-3e8f-11e8-92b9-b3ff4953f9f4.jpg)

**Comment by elfl0rd** [comment]
![20180412203832_1](https://user-images.githubusercontent.com/4980243/38694169-9a14adc6-3e91-11e8-9d95-b74b41c681f3.jpg)

**Comment by elfl0rd** [comment]
![20180413101453_1](https://user-images.githubusercontent.com/4980243/38723944-5f6ed604-3f0b-11e8-96e1-2dba22cd2a92.jpg)
![20180413104059_1](https://user-images.githubusercontent.com/4980243/38723946-61dd666c-3f0b-11e8-9e2a-4b76bb0a7c84.jpg)
https://crowdin.com/translate/eco-by-strange-loop-games/3/en-ru#26409

**Comment by Nanders** [comment]
Bumping to medium as this is ongoing non-game-breaking work

**Comment by elfl0rd** [comment]
And mooore :p 
![20180826183850_1](https://user-images.githubusercontent.com/4980243/44630505-7eddf080-a967-11e8-8fea-ce32720697cb.jpg)
![20180826183118_1](https://user-images.githubusercontent.com/4980243/44630506-7eddf080-a967-11e8-93d0-631a70688337.jpg)
![20180826183124_1](https://user-images.githubusercontent.com/4980243/44630507-7eddf080-a967-11e8-93f6-a71615b45e9b.jpg)
![20180826183129_1](https://user-images.githubusercontent.com/4980243/44630508-7eddf080-a967-11e8-8875-3cd7ec60110b.jpg)
![20180826183207_1](https://user-images.githubusercontent.com/4980243/44630509-7eddf080-a967-11e8-97dd-969144c97ce7.jpg)
![20180826183215_1](https://user-images.githubusercontent.com/4980243/44630510-7f768700-a967-11e8-9e42-5a5b954ed8f9.jpg)
![20180826183234_1](https://user-images.githubusercontent.com/4980243/44630511-7f768700-a967-11e8-92b5-459976bcc363.jpg)

**Comment by elfl0rd** [comment]
More, meteor tutor.
![default](https://user-images.githubusercontent.com/4980243/45339689-575c6a00-b59c-11e8-91a3-3545c65e048d.png)
map tutor
![default](https://user-images.githubusercontent.com/4980243/45339743-85da4500-b59c-11e8-8a9d-0693002fa773.png)
camp tutor
![default](https://user-images.githubusercontent.com/4980243/45339755-9094da00-b59c-11e8-8073-94826bd5409e.png)

**Comment by elfl0rd** [comment]
exit confirmation dialog
![default](https://user-images.githubusercontent.com/4980243/45465010-e479fd00-b71b-11e8-903a-780d716713ab.png)

**Comment by Nanders** [comment]
These have been added to crowdin, If any are still broken add them as separate bugs
