### ISSUE TITLE
Localized text lose colour and icon.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7140]
See screenshots.
![20180411212143_1](https://user-images.githubusercontent.com/4980243/38635573-7cb1ca34-3dce-11e8-939e-481ab0682dc2.jpg)
![20180411211927_1](https://user-images.githubusercontent.com/4980243/38635574-7cd24714-3dce-11e8-81c7-6fc62f62d532.jpg)
@Nanders

**Comment by Nanders** [comment]
Bumping to medium as this is ongoing non-game-breaking work

**Comment by elfl0rd** [comment]
Reciepes - same.
look at "modern hammer reciepe"
Original
![default](https://user-images.githubusercontent.com/4980243/47199666-5842a180-d37b-11e8-83c8-016b0e83123b.png)

Translated
![default](https://user-images.githubusercontent.com/4980243/47199641-39dca600-d37b-11e8-8c65-df12fd73ff7f.png)
