### ISSUE TITLE
Invisible bridge built too high - Now glitched out / Disappeared

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7146]
From Steam:

"Someone on our server built a bridge strait up until they clipped the ceiling of the world. They started from ground level and just layed bridges until they hit the “ceiling”. Once they hit said ceiling the entire bridge has disappeared yet still shows on the map. Is there a way that we can delete this thing as I believe it is the reason we are experiencing major lag.

Any input would be greatly appreciated. Restoring to a previous save point would be sub-prime as this apparently was done several RL days ago.

Thanks in advance."

**Comment by trojal** [comment]
Hello, I'm the user who built the bridge to the sky. When the client is loading in chunks of the world around me, it doesn't seem to load the ramps; even if I log out on the ramp and log back in, eventually it stops loading in the next pieces.
Here is a screenshot for more information of how it looks.
![image](https://user-images.githubusercontent.com/1402635/38650281-d3860812-3daf-11e8-936a-7bbf62b9f488.png)

**Comment by trojal** [comment]
This seems related to #7147 where their furniture/stockpiles aren't loaded after they started building a house in the sky.

**Comment by metachronism** [comment]
related to the bug sean fixed earlier with world objects.  was an issue with the waiting for ground component
