### ISSUE TITLE
Crashing on load

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7149]
From the support queue:

Hi, i recently purchased Eco two days ago from steam, downloaded fine and i'm not the one for multiplayer as i don't have the time so i went to start up a single player game, clicked on new and after about 30 seconds was in the game, played for a few hours then jumped off, the next day when i go to load up the world i get the error message  failed to start webserver: exception has been thrown by the target of an invocation 

I have posted in the discord chat to see if anyone could help, a couple of helpful suggestions were offered such as running the server.exe as admin ( even though when i first started playing i didn't do that )  another one was to change the ports from 3000 - 3001 to 4000 - 4001 which has still not fixed the issue. I have done clean installs and have tried uninstalling and installing multiple times and am out of ideas.

Version of game is 7.3.2
Operating system is windows 10 
Processor - i7 8700k
Graphics card - gtx 1060 6 gb
Ram - 32gb ddr4 

Have left the server on for about 25 minutes and tried joining and either got the error message and an infinite load screen or a " connection lost "

Have Verified the integrity, has come back ' all files successfully validated "

I don't have any firewalls enabled or have anti-virus  

When i go to generate new, is where the error comes up, it starts off loading different pieces of it then i get a pop up saying " do you want to allow this app to make changes to your device? " " Network command shell "
When i click yes i get the error message and also get the same message when i click no followed by a infinite load screen

Same thing happens when i run the steam eco server

In the server search it wont load or show any servers, but it did when i first started playing before i started getting the error message 

[output_log (6).txt](https://github.com/StrangeLoopGames/EcoIssues/files/1901005/output_log.6.txt)

**Comment by metachronism** [comment]
try 7.4
