### ISSUE TITLE
can craft lumber without sawmill (woodworking level 2)

### ISSUE THREAD

**Issue by panisch420** [StrangeLoopGames/EcoIssues#715]
woodworking level 2 as seen on the screen. sawmill unlocks on level 3 (and should unlock lumber).
and for 0 cost because of that other bug
![screenshot_541](https://cloud.githubusercontent.com/assets/22756750/19776352/f669be48-9c73-11e6-9777-c6afe06d7b6f.png)

**Comment by johnkslg** [comment]
Fixed!
