### ISSUE TITLE
Suggestion: RCON / Telnet

### ISSUE THREAD

**Issue by ClanHost** [StrangeLoopGames/EcoIssues#7150]
Hi, I have developed a cloud based administration tool called WebMod. For this tool to work I would require a remote connection to the server(s) to request information.

The ideal connection would be RCON and the required information listed below preferably in JSON format.

Minimum: 
/listplayers
Username,Steam64id.
/getchat
Display global chat since last /getchat command issued. Most requested by server administrators.

Preferred:
/listplayers
PlayerID,Username,Steam64id,IPAddress,GameLocationXYZ,Kills,Ping
/getchat
Display global chat since last /getchat command issued. Most requested by server administrators.

Making the in-game commands available via remote console available would be good.

The more data to retrieve the better the tool :)

Thanks

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#140
