### ISSUE TITLE
FPS drop (to 10-12fps) after open a chest/stockpile (with many items) and it does not recover after closing till restarting the game.

### ISSUE THREAD

**Issue by Snakekill** [StrangeLoopGames/EcoIssues#7151]
The problem occurs only when opening the boxes / stockpiles and it does not recover after closing till restarting the game.
Before that I have a fps of 80-90. But this makes the endgame unplayeable for me. Even if I have all settings on very low.

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/6319

**Comment by MarjieAVolk** [comment]
In fact, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6319
