### ISSUE TITLE
[Staging Beta 7.4.0 #B995d86c] Trash removed on server restart

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7152]
Perhaps I misunderstood but I was under teh impression that trash would be helpful for people needing to drop items for other to pick up and to help with quick way to make needed space in inventory but not to solve the issue of ecology dealing with trash, broken and unwanted items etc - just to drop and have them do the minecraft 'poof'

If you drop something on the ground it turns to trash, all you have to do to clear that trash is restart the server and the trash is gone, no need to think about recycling, treating, storing it or cleaning it up.  If this is by design now and trash is meant to just disappear I feel like the game has lost a bit of uniqueness in that trash and garbage etc is something that an Ecosystem should deal with - and not solve it by just have it disappear into thin air.

**Comment by craig-jong** [comment]
Should be fixed in the current staging - although rapid server restarts may not play perfect with it. Still testing that out a bit.
