### ISSUE TITLE
connection failed dedicated server

### ISSUE THREAD

**Issue by LaTrouTe** [StrangeLoopGames/EcoIssues#7155]
i have rented a dedicated server
 for 3 days the error message when i clcik on icon connect a message shows connected failed

I tried many  things that I changed but without success always the same message

"RequireAuthentication": false,

"DetectNAT": false,

 **## change ip address
and reinstall the server too**

few had the same problem on a server to dedicate

### **_I can connect but only add manual ip address_**

# server 0.7.3.2
ip server    ## **IP : 149.56.192.152: 40315**

video problem

youtube

https://www.youtube.com/watch?v=JUYKxX76vqU&feature=youtu.be

picture  problem

https://prnt.sc/j4apmu

Thank you for your help

LaTrouTe #6817

**Comment by MarjieAVolk** [comment]
Version 7.4 will have a brand new server connection backend, which maaaay magically solve your problem.

I got a 404 when clicking the links, but when I copy-pasted them they worked /shrug

**Comment by LaTrouTe** [comment]
ok update    picture is ready
