### ISSUE TITLE
USER ISSUE: Connection failed popup not removable

### ISSUE THREAD

**Issue by bummie** [StrangeLoopGames/EcoIssues#7156]
**Version:** 0.7.3.2 beta

**Steps to Reproduce:**
Connect to server
Connection fails
Popus says that connection failed, cant remove popup

**Expected behavior:**
Been able to close popup

**Actual behavior:**
Locked up mouse click
No way to close popup

**Comment by MarjieAVolk** [comment]
Well that's pretty odd.  What operating system are you on?

The next time this happens, could you send me your client error log?  On an English Windows computer it's at 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by MarjieAVolk** [comment]
Okay, well I'm guessing there would be something good in the client log for this one, but without that it's hard to know what might have gone wrong.  I'm going to decrease the priority until we get another repro.

**Comment by beastyn** [comment]
8.2 Can't reproduce. Close for now
