### ISSUE TITLE
Wrong map keeps showing up

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7158]
When I hit the g key to get the graphs, the world map is wrong about four out of five times. It doesn't represent the game world we're playing on.

**Comment by CuAnnan** [comment]
It also takes literal minutes for the graphs page to load. Which may or may not be a factor in the inactivity thing.

**Comment by CuAnnan** [comment]
[02:04] Error writing to stat database: ThreadAbortException Thread was being aborted.

That is the only thing of note in the console. Which may or may not be relevant.

**Comment by MarjieAVolk** [comment]
Console message related to https://github.com/StrangeLoopGames/EcoIssues/issues/6996

**Comment by rainfarmer** [comment]
@CuAnnan is the map totally different? or just missing the water?
Are buildings missing?

**Comment by CuAnnan** [comment]
I am not sure, I'll log on tomorrow and have a loook.

**Comment by rainfarmer** [comment]
should be working now
