### ISSUE TITLE
farming suggestions

### ISSUE THREAD

**Issue by ZehTed** [StrangeLoopGames/EcoIssues#7159]
How about
dairyfarms,hay & straw,silos for corn/wheat, plows,cotton,  slurry  etc. ?
Is there anything planed ?

**Comment by MarjieAVolk** [comment]
Plows are coming in the vehicles update :)

**Comment by boggl3r** [comment]
Dairy farming with cows and dairies would further enhance agriculture and provide the cooks with additional ingredients.
One could also think about pigs and cattle breeding. Both, of course, with their dark sides, be it methane emissions from animals or groundwater pollution from manure.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#139
