### ISSUE TITLE
USER ISSUE: While tree cutting down

### ISSUE THREAD

**Issue by Gjafar** [StrangeLoopGames/EcoIssues#7161]
**Version:** 0.7.4.0 beta staging-b8e0bc58

**Steps to Reproduce:**
Cutting a tree

**Expected behavior:**

**Actual behavior:**
Server encountered an exception:

<size=60,00%>Der Index war außerhalb des Arraybereichs.
   bei System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   bei TreeEntity.CollideWithTerrain(Player player, Vector3i position)</size>

**Comment by metachronism** [comment]
fixed a while back
