### ISSUE TITLE
[Staging Beta 7.4.0 #B8e0bc58] Server UI is erroneously populating password field

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7162]
The password field is empty in the config file  : https://gyazo.com/c02d38982ea2e8301823c4f3418a5c4c   but when the server loads its populating it with this password (see image of server UI).  No idea where it is coming from and even if I remove it from the server UI password field it is immediately repopulated with another string:   https://gyazo.com/20e4e6b36fea353de07c5260316cbdf0

No one, unless whitelisted is able to get on the server

**Comment by mcunha** [comment]
Sorry about that @pamduncan . The pull request above fixes that behavior.

**Comment by pamduncan** [comment]
Since I could not reopen this bug as I believe its essential still this bug re hashed passwords *but only if password field is used) I opened a new issue here:  [.7.4.-beta-staging-518a927f] hashing passwords again/still if password is used #7592  Maybe somoene woul want to re-open this bug and just link the new one I posted to it
