### ISSUE TITLE
One string uses on 2 different position.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7163]
Please fix it, they have different context, and require different translation.
https://crowdin.com/translate/eco-by-strange-loop-games/3/en-ru#26533
![20180413000506_1](https://user-images.githubusercontent.com/4980243/38704339-ae2a57f8-3eae-11e8-996e-a2f49d35f71e.jpg)
![20180413000503_1](https://user-images.githubusercontent.com/4980243/38704340-ae4ab7dc-3eae-11e8-8ea4-b805f5a07b01.jpg)
@Nanders

**Comment by Nanders** [comment]
This will be fixed with the implementation of String IDs, will leave this open until this goes in.

**Comment by elfl0rd** [comment]
https://crowdin.com/translate/eco-by-strange-loop-games/3/en-ru#2823
As skill name and item name. Need split too.

**Comment by Nanders** [comment]
Bumping to medium as this is ongoing non-game-breaking work

**Comment by elfl0rd** [comment]
Back fixed, Lumber need recheck.
I create new issue if problem with lumber still here.
