### ISSUE TITLE
[Staging Beta 7.4.0 #B8e0bc58] Launching Single player game Crashes instantly 

### ISSUE THREAD

**Issue by S0zi0p4th** [StrangeLoopGames/EcoIssues#7164]
Trying to launch A single player game from within the client will push true and generate a map but will crash or shutdown before you enter the world 

Current Workaround is manually launch Ecoserver.exe from steam library as administrator  and join true LAN 

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1905111/output_log.txt)

**Comment by metachronism** [comment]
fixed
