### ISSUE TITLE
Chat takes too long to save

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#7165]
Save all time for a decently populated save is over 10s
![image](https://user-images.githubusercontent.com/774628/38706587-8cfba1b4-3e62-11e8-8392-10614cfeb08c.png)

**Comment by MarjieAVolk** [comment]
Is the database stable enough that we are ready to move that over now?

**Comment by tomsseisums** [comment]
@mirasrael could it be this was solved with your introduction of `CompsiteChatData`?

**Comment by mirasrael** [comment]
yes, it should fix the issue
