### ISSUE TITLE
Can't go to the main menu once hitting "new", there should be a back button

### ISSUE THREAD

**Issue by braiam** [StrangeLoopGames/EcoIssues#7174]
On a Linux 7.3.3 client, hit "new" to start a new game, [fail to do so](https://github.com/StrangeLoopGames/EcoIssues/issues/6930), try to get to the previous screen. There's no back button and <kbd>Esc</kbd> is ignored. There should be a back button to return to the previous screen as right now there's no visible way to return to the main screen.

**Comment by MarjieAVolk** [comment]
Escape should take you back to the main menu - guess that doesn't work on Linux?

But yeah, we should also add a back button to those sub screens.

**Comment by braiam** [comment]
@MarjieAVolk as said in the OP, the esc key is ignored.

**Comment by SeanAtr0n** [comment]
probably due to an exception while attempting to make a new world on linux... in 7.4 you can't get there in linux anymore so i guess this is resolved
