### ISSUE TITLE
cO2 Instantaneously removed everywhere

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7177]
"Bugs: Server Running on Sleep Mode (self.EcoGlobalSurvival)

submitted an hour ago by omgguyriots

I am running a local server on a Windows 10 PC and accidentally switched to sleep mode while still running the server. Interestingly, the simulated game time in this period (about 10s to go to sleep and restart again) were around 40(!) days. Since we changed the meteor impact to 180 days, our world is fine and all animal species are alive. But: Air pollution is now competely bugged. We got some CO2 production of -120000048567ppm leading to a world where all CO2 is instantaneously removed. Any suggestions to fix this? (and nope, i cannot use the last backup)"

**Comment by craig-jong** [comment]
I could use a game save for this if you could still contact the person.

**Comment by ShaydenMac** [comment]
I've asked for it.

**Comment by omgguyriots** [comment]
I'll guess I will wait until you give me further instructions

**Comment by craig-jong** [comment]
Throw it into a google drive or something. Basically any filehost you feel comfortable using.

Thanks for the extra information, though. Might be able to diagnose this without the save, but I could still use it if you have it.

**Comment by WeaselDog** [comment]
Hi. In our latest update we have made some significant changes to how CO2 absorption is calculated so this should no longer be an issue. Thank you for your contribution.
