### ISSUE TITLE
[Feature Request] Make speed skills retroactive

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7178]
Cancelling projects and restarting them, from a software perspective, is easier. But from a human experience perspective, makes no sense.

**Comment by ecoemmeck** [comment]
I like this idea but how would the game deal with the efficiency side of it, would it just deposit the now extra materials back into a stockpile / chest or would it order more to the extent of materials given to the project.

**Comment by CuAnnan** [comment]
I don't know. I was actually just thinking about speed because it wouldn't have to deal with "Is there room for the items you would get back".

**Comment by mcunha** [comment]
Maybe we could adjust the output and the speed ? I'm thinking of places where people leave a very long standing orders with their skills so others can leverage them. Forcing everyone to go around and redo the long standing orders is tedious. If we simply adjusted speed and output, people could skill up and everyone would benefit right away. This may be more of a game balance / emergent play incentives conversation.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#137
