### ISSUE TITLE
Random Glitch out of world?

### ISSUE THREAD

**Issue by JleanderS** [StrangeLoopGames/EcoIssues#7180]
The 2. Time in 2 Versions i glitched out of the world and cant do /unstuck after some Hours i spawn on the Spawn cords. Today i stucked there after a Crash in a Tunnel 
![screenshot_35](https://user-images.githubusercontent.com/1758322/38752639-3948d47e-3f5c-11e8-8e3e-1551f6b70e61.png)

**Comment by JleanderS** [comment]
//added Picture of Map

![screenshot_36](https://user-images.githubusercontent.com/1758322/38752713-86b51380-3f5c-11e8-8eff-f4b011c107cc.png)

**Comment by JleanderS** [comment]
I found out you can glitch out there if you build on Ramps Stone and Concrete both tested

**Comment by SeanAtr0n** [comment]
fixed a while back
