### ISSUE TITLE
/teleporttarget and /teleporttargetplayer commands do not work

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7182]
Per Discord member:

"When I try to teleport a player with /teleporttarget and /teleporttargetplayer it says "with great power comes great responsibility" it's an Easter egg I see but nothing else happens... Need to teleport someone... wahts is the fail?"

Confirmed that player is an admin.

**Comment by metachronism** [comment]
Kirthos fixed this for us
