### ISSUE TITLE
Suggestion: Ability to lock right-click-enabled items, e.g., consumables

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7183]
From a subreddit member:

"Can I make a suggestion? How difficult would it be to impliment a "food lock" for planting edible seeds? Like you can type '/diet or something' to disable right click consuming items (planting, tossing food/property flags/ect into a chest) until you finish a task then when you are ready you type '/diet or something' again to unlock.

I don't have much experience with coding so I'm not sure how easy it would be to do. This isn't a major problem, but it is worrying when you are carrying an endangered plant and you are trying to plant it without consuming it."

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#136
