### ISSUE TITLE
USER ISSUE: some text hard to read

### ISSUE THREAD

**Issue by MacGabhann** [StrangeLoopGames/EcoIssues#7184]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
using a wide screen monetor

**Expected behavior:**
the numbers for the amount of items should be large enough to be readable.

**Actual behavior:**
the numbers indicating the amount in a stack or the amount needed is so small that some numbers are imposible to read

**Comment by GophTheGreat** [comment]
We have a UI scale option for this. Closing.
