### ISSUE TITLE
Multiple monitor use in full screen mode

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7186]
I loaded up the latest version of the game in full screen mode and noticed right away that while I can move my mouse to my other monitors and even click them, I couldn't interact with them. It just caused the game window to blink. 

I have a fairly high end computer that I use primarily as a dev machine, so it would be easier for my to play a game like this if I could use my other monitors to work and/or read emails and such.

An obvious work around is to change it to windowed mode and set it to the resolution of the monitor, but even if I auto hide the task bar there's this bar that detracts from the experience. Still, it does allow me to do what I need to do so I'll use that for the time being. If at all possible it would be nice if a full screen environment behaved with multiple monitors though.

Thanks.

**Comment by Chi-Yu** [comment]
Isn't this what is commonly known as "windowed borderless"?

**Comment by Elliander** [comment]
Yes, although it does have the top border still, which is a problem because often when I go to close the map (which I put to the top right corner) I inadvertently X out of the game entirely and have to load it back up. Again, a slight inconvenience , but would be nice if there was an alternative.

**Comment by SeanAtr0n** [comment]
in 7.4
