### ISSUE TITLE
stone roofs have no model (also: "rooves")

### ISSUE THREAD

**Issue by panisch420** [StrangeLoopGames/EcoIssues#719]
![screenshot_544](https://cloud.githubusercontent.com/assets/22756750/19781166/623eed00-9c88-11e6-8933-71fc8cf75683.png)
![screenshot_545](https://cloud.githubusercontent.com/assets/22756750/19781173/6e71ace8-9c88-11e6-8360-6c589c139ce3.png)

**Comment by keegan-o** [comment]
building materials will get an in-depth pass at some point, for now making stone into a grey tinted brick.
