### ISSUE TITLE
Suggestion: Bicycle

### ISSUE THREAD

**Issue by Xeanoa** [StrangeLoopGames/EcoIssues#7196]
A small vehicle 1x2x2, without storage, that increases movement speed, has moderate restrictions on travel, good turn rate, and higher movement speed, and calorie consumption similar to running maybe?

Walking around is one of the more wasteful tasks in the game, and cutting that time down while generating a fun way to travel seems like a good idea to me.

**Comment by Dreepa** [comment]
I had the same thought. In terms of world balancing, I find the game is far from the sweet spot. 
Creating bigger worlds makes game-play slow and distances travelled can get annoying. 

There are many minecraft mods dealing with this problems, introducing a progression for character attributes like jump height, running speed, etc.
It feels really good. In the start you are more limited, but then you get running boots and eventually jet-packs and teleports. Not saying ECO should do that, just a reference for good scaling of player-tools.
It makes you feel like you advance, and it has real impact on how much time is spend doing what in the game.

**Comment by talamatur** [comment]
see this related suggestion of motorcycles https://github.com/StrangeLoopGames/EcoIssues/issues/7264

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#134
