### ISSUE TITLE
ECO 7.3.3 Computer crashes

### ISSUE THREAD

**Issue by Serynthara** [StrangeLoopGames/EcoIssues#7197]
Version: 0.7.3.3

Steps to Reproduce:
Play around 5-60 Minutes.

Expected behavior:
Game aswell as computer keep on working.

Actual behavior:
The screen suddenly turns black, the computer stays on though. It is neither overheated, nor does it give any error. Other games work just fine.

[Sysinfo.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1911104/Sysinfo.txt)

**Comment by GophTheGreat** [comment]
I've seen a report of a similar crash that may originate from a problem with AMD cards. See if the following thread helps: https://steamcommunity.com/app/382310/discussions/4/1694918539669093263/

**Comment by metachronism** [comment]
please attach crash dump file if this occurs again
