### ISSUE TITLE
Oil crafting times are inverted

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7199]
The heatmap for pollution: White is more, purple is less
The heatmap for oil: Purple is more, white is less

I shouldn't need to read a wiki to know this. The scales should be present, consistent and clear.
Right now, they are none of the above.

**Comment by SeanAtr0n** [comment]
The multi-colored heat map gradient is the same for all layers... does the wiki say otherwise?

**Comment by CuAnnan** [comment]
There is more oil at purple areas than white. The numbers on the wiki for oil reflect in game values.
Which means the heatmap for oil is "white low, purple high".
Which is the opposite of air and ground pollution.

**Comment by SeanAtr0n** [comment]
Are you sure about that? The pumpjack tooltip seems to indicate the opposite
![image](https://user-images.githubusercontent.com/774628/38838364-9a7e5162-418a-11e8-9914-2e4b6fbf6180.png)

![image](https://user-images.githubusercontent.com/774628/38838395-b93fb794-418a-11e8-9f98-dea01c946687.png)

**Comment by CuAnnan** [comment]
Yes I am sure about that. The pump jack confirms that you get more oil out of purple areas than white.
Oil projects at white take 5 minutes to produce oil.
Oil projects at purple take 2 minutes to produce oil.

![20180419155115_1](https://user-images.githubusercontent.com/2996036/38999641-36429c32-43ea-11e8-8718-62bdc6347f75.jpg)
![20180419155438_1](https://user-images.githubusercontent.com/2996036/38999642-365a3a86-43ea-11e8-896d-8994a8c945c4.jpg)
![20180419155508_1](https://user-images.githubusercontent.com/2996036/38999643-367ca88c-43ea-11e8-8249-b00a38b4c5dc.jpg)
![20180419155515_1](https://user-images.githubusercontent.com/2996036/38999644-36978d3c-43ea-11e8-8690-69e702a70c13.jpg)
![20180419155520_1](https://user-images.githubusercontent.com/2996036/38999645-36ae5d32-43ea-11e8-87c0-550d09dfe7c8.jpg)

**Comment by CuAnnan** [comment]
If you would like a save file to confirm these numbers, let me know

**Comment by SeanAtr0n** [comment]
Think craig mentioned this before so i thought it was fixed... yeah looks like oil crafting is inverted

**Comment by craig-jong** [comment]
I swear I fixed this....

**Comment by CuAnnan** [comment]
I am a tied piece of string with ratty ends.
Or I'm a frayed knot
