### ISSUE TITLE
cart gets stuck on ramp and floats above the ground

### ISSUE THREAD

**Issue by panisch420** [StrangeLoopGames/EcoIssues#720]
![screenshot_546](https://cloud.githubusercontent.com/assets/22756750/19782015/4028c20a-9c8c-11e6-87f4-26826f05ab50.png)

cant be moved back or forth. road efficiency says 100%. it floats slightly above the ground, the wheels are turning when i try to move it.

i removed the ramp, and the cart dropped to the grass and i was able to move my cart again. then i put the ramp back down and tried gain -> got stuck at the very same spot.

**Comment by metachronism** [comment]
fixed
