### ISSUE TITLE
Wood Cart Deed Description Changes on Server Restart

### ISSUE THREAD

**Issue by Legends0** [StrangeLoopGames/EcoIssues#7200]
**Version:** 0.7.3.3 beta

I left a cart at a user's store since they were logged off on the other side of the world and at the time had their store not in a valid room. Server restart in the morning changed the description text field of the deed.

**Steps to Reproduce:**
Place Wood Cart on ground, leave it on Malk's property.
Restart the server.

**Expected behavior:**
Description field remains the same name as what it was before server restart.

**Actual behavior:**
Description changes to say Malk's Wood Cart.
![image](https://user-images.githubusercontent.com/5702579/38774237-e94cc45e-4031-11e8-9c34-719720482486.png)

**Comment by WeaselDog** [comment]
Can't reproduce this in 0.9.0 staging

**Comment by D3nnis3n** [comment]
Those deeds do no longer exist.
