### ISSUE TITLE
Tables don't update crafttime after spending skillpoints

### ISSUE THREAD

**Issue by Xeanoa** [StrangeLoopGames/EcoIssues#7204]
Crafting tables don't update the time needed for a project until I change something, such as the amount requested, after spending skill points.

Expected: When I look at the crafting table again after spending skill points, I expect to see the new, correct resource cost and time needed.

**Comment by mirasrael** [comment]
Fixed in 9.0. Time and resources updates with module (starting from next craft iteration)
