### ISSUE TITLE
USER ISSUE: Single player Connection Failed

### ISSUE THREAD

**Issue by Siern** [StrangeLoopGames/EcoIssues#7206]
**Version:** 0.7.4.0 beta staging-b8e0bc58

**Steps to Reproduce:**
Using Steam:
1. Install bleeding edge version 
2. Create new game
3. Fail to connect to local game

**Expected behavior:**
To work like 7.3.  I checked and this problem does not exist there	

**Actual behavior:**
Receive Connection Failed and have not way to access single player via Steam.  When testing with downloaded version I got it to work.  I think the steam problem is related to the elevated power script execution.  Might want a better solution!

> <size=150%>Connection Failed</size>
> 
> Locally requested connect
> 

Additional Details since the reporting dialog is small:
Tested on Windows 10 via Steam.
Tested with both allow other checked and unchecked.
Tested loading game.. same result.

**Comment by metachronism** [comment]
FIXED!
