### ISSUE TITLE
Icons of user modded items missing or broken in preview texts

### ISSUE THREAD

**Issue by Channly** [StrangeLoopGames/EcoIssues#7207]
Version: 0.7.3.3

**Steps to Reproduce:**
Look at the textual description of a community modded item

**Expected behavior:**
looks like vanilla items, has an icon on the left side of the item name

**Actual behavior:**
doesn't show an icon or displays text instead of an icon

__
As far as I can tell, items that are from community made mods are missing their icons in the textual bits of the game. They show up as items in the inventory, craft windows etc. just fine.

I've observed 2 different behaviours.
- If the icon is from a single sprite, it simply doesn't show up.
- If it belongs to a sprite sheet, the link to the right sprite is shown where the icon should be, making it hard to read any item information or receipe.

I included pictures of the two behaviours.
Tested this with my own as well as other mods.

example of a missing icon
![missing icons2](https://user-images.githubusercontent.com/7736723/38777252-16f3d9a6-40a5-11e8-85ad-56cf2709d545.png)
example of text replacing the missing icon if from a sprite sheet
![icon missing 1](https://user-images.githubusercontent.com/7736723/38777251-16d8af00-40a5-11e8-8dc2-c25fdd6ddef7.png)

**Comment by Last2Night** [comment]
I've encountered the same issue. A fix will be much appreciated.
Thank you.

**Comment by metachronism** [comment]
will require changes to the modkit.  closing as per this bug #2784 will address this issue
