### ISSUE TITLE
USER ISSUE: If try to open laws site - opens game folder.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7208]
**Version:** 0.7.4.0 beta staging-b8e0bc58

**Steps to Reproduce:**
Click to any button moving you to server site (laws, election, etc...)

**Expected behavior:**
Site opens and available.

**Actual behavior:**
Game folder opens

**Comment by elfl0rd** [comment]
Still fixed, maube close?
@metachronism

**Comment by MarjieAVolk** [comment]
If it's fixed, closing XD Thanks
