### ISSUE TITLE
USER ISSUE: Stuck in the ceiling

### ISSUE THREAD

**Issue by kleinline** [StrangeLoopGames/EcoIssues#7211]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Build reinforced concrete structure and had item I jumped up on to build the ceiling.  While building out the ceiling I placed a block too close - right at my level.	Cannot get out of being stuck even after a reboot of the game.

**Expected behavior:**
Expected to be pushed off the item I was standing on (the metal press thing) and placed back on the floor.

**Actual behavior:**
I got stuck in the block somehow.  Everything at my level nearby became invisible, and I cannot get out of my position.

**Comment by GophTheGreat** [comment]
Have you tried the "/unstuck" or "/teleport" commands to remove yourself from the position?

**Comment by kleinline** [comment]
Yep, /unstuck worked to solve the problem.  Good to know teleport is also
an option!

**Comment by SlayksWood** [comment]
dup #6238
