### ISSUE TITLE
Singleplayer Connection Failed

### ISSUE THREAD

**Issue by Serynthara** [StrangeLoopGames/EcoIssues#7213]
Aaand it's me once more.

Version: 0.7.3.3

Steps to Reproduce:
Create a new world, restart the computer, trying to continue the game.

Expected behavior:
It should load the world again.

Actual behavior:
It says the connection failed, although it is a singleplayer game?

**Comment by metachronism** [comment]
@Serynthara another thing to try would be latest staging (7.4) version, reopen if you are still seeing issues there
