### ISSUE TITLE
USER ISSUE: Wooden pulp won't be cut

### ISSUE THREAD

**Issue by hlmvy** [StrangeLoopGames/EcoIssues#7217]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
I think i dug dirt under the pulp, or did something else related to digging around a piece of wooden pulp.

**Expected behavior:**
When using stone ax to cut it, it should be marked green and go to inventory. Note that my inventory is not full.

**Actual behavior:**
It is not indicating green, nor will it be cut when using stone ax. Nothing happens. I can even put dirt in the same spot, when I obviously shouldn't be able to do that.

**Comment by SeanAtr0n** [comment]
was the problem fixed after reconnecting?
