### ISSUE TITLE
[0.7.3.3]  "Report a Bug" windows doesn't have scroll bars

### ISSUE THREAD

**Issue by hlmvy** [StrangeLoopGames/EcoIssues#7218]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
I just submitted a bug before this one, and noticed that if I put enough words in "report a bug" window in game it doesnt show me all text I've written. The cursor moves to the middle when the black box is filled with text. 

**Expected behavior:**

**Actual behavior:**

**Comment by WeaselDog** [comment]
No scroll bars for bug report fields. Still an issue in [0.9.0 staging-1568]

![image](https://user-images.githubusercontent.com/45708377/82995546-656e4a80-a00c-11ea-93c0-6b2b983fbe1c.png)

**Comment by beastyn** [comment]
1. Can we have scroll bars after text is big enough? We don't need it with empty or not fully filled.
![bandicam 2020-09-18 17-50-21-534](https://user-images.githubusercontent.com/27898520/93599857-2f4c4080-f9d8-11ea-9cb4-56e5f616e0d9.jpg)

2. I still won't see a cursor when typing a big message. Its fine sometimes. Maybe connected to the scroll, its not working with mouse wheel until you select all the message. It has really strange behavior. Type a big message and then try to place  a cursor and type further at the end of the message - nothing happens
![bandicam 2020-09-18 17-50-35-454](https://user-images.githubusercontent.com/27898520/93599863-32dfc780-f9d8-11ea-882c-d857a7533cc1.jpg)
![bandicam 2020-09-18 17-50-47-234](https://user-images.githubusercontent.com/27898520/93599868-3410f480-f9d8-11ea-8efe-f95c326571f1.jpg)

**Comment by SlayksWood** [comment]
- [ ] 1. Scroll bars are inverted:
![image](https://user-images.githubusercontent.com/45708377/94233802-28aa5580-ff11-11ea-9544-73bf2a1b8527.png)
![image](https://user-images.githubusercontent.com/45708377/94233853-42e43380-ff11-11ea-81a8-818770b4f852.png)

- [ ] 2. Scrolling with mouse wheel works very bad. Seems something with text field, I can't place cursor in some positions.

**Comment by SlayksWood** [comment]
All works fine except thi one:
> 1. Can we have scroll bars after text is big enough? We don't need it with empty or not fully filled.
>    ![bandicam 2020-09-18 17-50-21-534](https://user-images.githubusercontent.com/27898520/93599857-2f4c4080-f9d8-11ea-9cb4-56e5f616e0d9.jpg)

![image](https://user-images.githubusercontent.com/45708377/95333871-066fea80-08b6-11eb-8301-0f92989f5ae2.png)
