### ISSUE TITLE
USER ISSUE: Failing to drag from inventory

### ISSUE THREAD

**Issue by hlmvy** [StrangeLoopGames/EcoIssues#7219]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
This is a new bug for me. Sometimes I have to try up to 5 times dragging objects from different inventories into the inventory I carry. 

**Expected behavior:**
Click and drag an icon to my personal inventory from various other inventories (small wooden cart, storage chest etc.)

**Actual behavior:**
After some dragging the icon despawns and I have to redo until successful.

**Comment by MarjieAVolk** [comment]
Hm sounds like this is probably related to changes I made to prevent icons getting stuck on the screen.  Now instead icons get incorrectly unstuck from the screen, sigh :P

**Comment by MarjieAVolk** [comment]
Okay well, as expected I am not seeing this much on my own computer.  I'm wondering if this is again related to your mouse.  Does your mouse register multiple clicks frequently or anything like that?  Would you be able to test the game out with a different mouse and see if it's still happening?

**Comment by MarjieAVolk** [comment]
Guess I'll move it back down to medium priority unless we get more reports of this.

**Comment by WeaselDog** [comment]
We haven't had any reports of this recently so it seems to be fixed. Thanks for your report and please let us know if you experience this issue again.
