### ISSUE TITLE
Items vanishing and vanishes when placed.

### ISSUE THREAD

**Issue by IIBuxy** [StrangeLoopGames/EcoIssues#7220]
Ramps, Stockpile and a Combustion Generator went invisible.

 The stockpile and combustion generator had been placed 12 hours (roughly) prior them going invisible, but a chest and 2 pumpjacks right next to the items didn't.

Items were not randomly placed, but happend on two different locations.

 8 ramps turned invisible while building a ramp road down from a mountain. Items placed by other players also turned invisible.

A relog, deleting files in Eco folder and a server restart did not fix the issue.

**Comment by metachronism** [comment]
@IIBuxy do you have a copy of this save?
and also, can you try the save with 7.4 staging version perchance?  Plz reopen if still seeing the issue

**Comment by Last2Night** [comment]
@metachronism @GophTheGreat 
We do not use Staging versions, sorry.
Here are the world files:
https://drive.google.com/open?id=1sCuRgntR6fnUBRNWwtgy2UUa7OuNxPRt
