### ISSUE TITLE
USER ISSUE: Cannot cancel certain projects

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7224]
**Version:** 0.7.4.0 beta staging-b8e0bc58

**Steps to Reproduce:**
1. Start a project that requires more than one different "carrying" items.
2. Not having a stockpile close for the items to return to
3. Try to cancel the project

**Expected behavior:**
There should be a way to cancel even if the parcel lacks a place to put the resources. This is especially of concern since shops are supposed to allow other players use of tables for a fee, who should get their items back if it is cancelled rather than depending on a stockpile, which the players also shouldn't have access to. There needs to be a way to cancel projects that require more than one carrying item (or, similarly, more total weight than the player can otherwise carry) without requiring that the player have access to a stockpile on the parcel. Alternatively, if it is intended to require a stockpile, it should prevent the table from being used to start a project if there is no way to return the items to the player which in turn would require giving property owners the ability to own stockpiles and set authorizations for them.

**Actual behavior:**
I get a "Not enough room in inventory" message because you can only hold a single "carrying" item. In my case, even though I wanted to create a single skill book, it keeps putting two on the stack from a single click and then I cannot stop the second one from being made because this is a shop that does not yet have a stockpile because, due to no permission settings for stockpiles (all show as unowned, even on owned property ) and having to divide the parcel from my existing stockpiles and not yet having room for a stockpile here. 

![cannot_cancel](https://user-images.githubusercontent.com/15022396/38807264-a8b3dc3c-4141-11e8-94cb-3e6bdc907db2.jpg)

**Side note:**

I'd really like to be able to set authorizations for stockpiles, and to set more than just access permissions to my property. That way I could let others walk onto my property freely without them walking away with stuff or littering the site. It seems weird that I have to hide them behind special doors or not build them at all.

**Comment by metachronism** [comment]
more of a marjie/craig problem, but I believe we've addressed a lot of these already now

**Comment by MarjieAVolk** [comment]
What is intended in these cases is that you should bring a vehicle with you in order to carry back all your resources.  This would be made easier if we were to add a shoulder basket to the game, as we've been throwing around ;)

It would require some revision to how work orders work to refund items partially, I think I'm going to close this one as won't fix.
