### ISSUE TITLE
Question: Should certain menu clicks be opening the game folder?

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7225]
I've asked questions in the Eco forum, but there doesn't seem to be anyone active over there, so going to ask it here: 

Is it normal that when I click on Government > (anything), or click on Graphs, the Eco game folder opens and nothing else? Is there some out of game way that these features are supposed to be used, or are they currently disabled in the latest build?

It always opens the folder in one of my other monitors. If the game is windowed it opens the folder without changing screen focus, but when the game is full screen it minimizes the game when opening the folder.

**Comment by GophTheGreat** [comment]
Which version of Eco are you running?

**Comment by Elliander** [comment]
**Version:** 0.7.4.0 beta staging-b8e0bc58

I downloaded that a few days ago, and am running it on  the following server:

[EU]-Jupiter Beta 0.7.40 (currently on day 5)

Although, now that I think about it, I have never been able to use that functionality. When I first tried the Alpha version 2 years ago I observed the same behavior (I can dig up the old files if you need the version info for that) and hosted my own server. Since I was playing solo I just figured the behavior was because of that and this is the first time I played with other players.

So what is supposed to happen? Is there supposed to be an in game menu?

**Comment by Elliander** [comment]
Also happening on version 0.7.4.0 beta staging-6da91821 , with server updated to same. 

What's supposed to happen? There's no Graphs menu (it opens game folder), and while there is a Government menu clicking anything (Propose Law, Run for Office, View Data) opens game folder. There's only one law in effect (Citizenship) which I can see, but view is greyed out. Keyboard shortcuts to these menus works the same.

**Comment by Elliander** [comment]
Also happening on version 0.7.4.0-beta-staging-248fc2c1

Is there someplace that I can read about how this is supposed to be working? and trouble shooting I can do on my end?

**Comment by Elliander** [comment]
Also in v0.7.4.0-beta-staging-b79d89de

I spoke with others in the server and it sounds like everyone is having the same exact problem on this world, so seems to be a server side issue. Like, maybe it's misconfigured? But if it can be misconfigured in that way, there would need to be some way to detect such an issue to prevent it from harming user experience.

I was given the URL for the server here: http://samurai19.com:3009/index.html

and I can view graphs when I go there (even though from in game this page doesn't load), but I cannot participate in government or propose laws because it says "You must access from the game server"

I'm not sure if it's supposed to always open a web page, but I think I'd like the interface better if the website was just an option - if all the data was available in game.

**Comment by SeanAtr0n** [comment]
Yeah its definitely a server issue... some code was commented out during the conversion to use UDP

**Comment by Elliander** [comment]
Maybe then, going forward, the user client could have a way to detect if a server is misconfigured? and instead of opening a game folder, to tell the user about the issue so they are not surprised?

**Comment by Elliander** [comment]
When I created my own server, I am able to load these web pages, but when I do so I see a local IP address. How would I go about testing to make sure the server is properly configured? and how might I go about using my own domains to host such pages?

**Comment by metachronism** [comment]
fixed 7.4.0 release
