### ISSUE TITLE
Research should be a separate skill to survivalist

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7228]
Once the skill tree is complete, the research skill becomes useless.

Worse yet, it is unrefundable. So, if you're like me, you've sunk a considerable amount of SP for the good of everyone. But you can't get it back (at whatever the server penalty is)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#130
