### ISSUE TITLE
Banning should unclaim all owned property

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7229]
EOM

**Comment by MarjieAVolk** [comment]
Yeah it's true.  We also just need a way to delete players safely.

**Comment by WeaselDog** [comment]
I disagree. What about temporary bans?

**Comment by elfl0rd** [comment]
I'm agreeing with WeaselDog, Eco already have command for unclaim property, no real needs to merge ban and unclaim commands.

Also i agree MarjieAVolk comment, eco really need a way to safely delete players from database.

**Comment by D3nnis3n** [comment]
No, unclaiming is not wished by all administrators:
- Temporary Bans
- Rich properties that would be easily looted
- Cool looking buildings that should be preserved.

Eco has a unclaim ability via law and a seizing one in 9.0, additionally the admin commands, that should suffice.
