### ISSUE TITLE
can not craft aqueduct 

### ISSUE THREAD

**Issue by panisch420** [StrangeLoopGames/EcoIssues#723]
"you do not have the items needed to create this order"
but i do!
![screenshot_547](https://cloud.githubusercontent.com/assets/22756750/19790565/7aa8036e-9cb9-11e6-8270-98401cce3669.png)

**Comment by panisch420** [comment]
possibly related to this is the fact that there are 3 different types of pitch "masonry pitch, wheat pitch and charred pitch. the needed material in the workbench is simply called "pitch".
i just tested all 3 different kinds of pitch seperately and none is working.

**Comment by craig-jong** [comment]
The multiple "pitch" items should all work (or at least they used to) for any recipe that requires pitch. I'll look into this.
