### ISSUE TITLE
[SUGGESTION] Don't eat when full

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7231]
When you eat, depending on the nutritional content your skill rating will either go up or down while the calories you consume increase your fullness factor - except when you are full. For whatever reason, trying to eat while full still results in the player stuffing his or her face beyond the point of fullness.

If the player goes to eat something, and they are full, the food should remain uneaten.

**Comment by craig-jong** [comment]
this is a bug - it used to block you from eating. Will fix.
