### ISSUE TITLE
Inventory sort workflow needs to be redone

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7232]
You need to put in "Swap with inventory above/below" and "Move to bottom/top" buttons.

At present, in order to move a stockpile in the list, you hold down the stockpile drag area. While holding down the mouse button with one finger, scroll the mouse wheel with the other. **PRAY REALLY HARD** that you hit the drop area. Hope that the carpel tunnel you're developping by scrolling while holding isn't debilitating. Rage quit because you missed the drop zone again.

The entire process is painful. It is literally painful (as in in actuality, not figuratively painful). My fingers hurt.

**Comment by MarjieAVolk** [comment]
:'(

**Comment by MarjieAVolk** [comment]
```
From Steam https://steamcommunity.com/app/382310/discussions/4/1694920442952409991/:

the inventory UI needs work (and optimization, since opening it lags badly when there are many nearby inventories). I would use buttons for "expand all", "collapse all", "expand linked only" (perhaps one button with those three states), and "send this inventory to the top of the list". it would also be nice to be able to click on a stack in a remote inventory to send it to the item you have open or your backpack (perhaps Shift-click to the item you have open, and CTRL-click to your backpack/hands)
```

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#129
