### ISSUE TITLE
USER ISSUE: in fenster festgebugt komme nicht raus

### ISSUE THREAD

**Issue by jennysweet** [StrangeLoopGames/EcoIssues#7233]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**

**Comment by GophTheGreat** [comment]
Versuchen Sie, die Befehle '/ unstuck' oder '/ move' zu verwenden, um sich in der Zwischenzeit zu befreien.

**Comment by jennysweet** [comment]
Schönen guten abend das Problem hat sich selber gelöst nur wenn sowas nochmal passiert wo kann ich die Befehle eingeben ich habe das spiel nur bei steam gekauft keinen eigenen server oder ähnliches LG krohn jennifer

Von meinem Huawei-Mobiltelefon gesendet

-------- Originalnachricht --------
Betreff: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: in fenster festgebugt komme nicht raus (#7233)
Von: Goph
An: StrangeLoopGames/EcoIssues
Cc: jennysweet ,Author


Versuchen Sie, die Befehle '/ unstuck' oder '/ move' zu verwenden, um sich in der Zwischenzeit zu befreien.

**Comment by GophTheGreat** [comment]
Closing the ticket then.
