### ISSUE TITLE
Fertilizers and seed production part of the same specialization

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7236]
Per Reddit user:

"I think I do wish that fertilizers and seed production were both in the same specialization. I’d like to be able to take up another side skill a bit earlier - for instance, lumber or brick production to help when the primary folks in those skills have sold out their store and haven’t logged back in.

Edit: I think cooking is good but will continue to progress. For instance, there are many recipes for ingredients that aren’t really used yet, like bean paste, that I suspect will become more useful as more recipes are added.

Edit 2: Also, a low-capacity, high yield farming method that maybe requires special soils would be nice. Like greenhouses as basically the farmer tier 2 and hydroponics as the farmer tier 3/4."

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#127
