### ISSUE TITLE
Admins can't set Global Map Markers

### ISSUE THREAD

**Issue by Jayshua83** [StrangeLoopGames/EcoIssues#7237]
Being an Admin on a Server DOESN'T allow setting of Global Map Markers.

Only World Leader.

Shouldn't Admins be able to?

**Comment by sirPattrick** [comment]
I agree, Admins should be able to set Global Markers as well.  Even if its through a Admin/Dev Command and not on the Map.

**Comment by Jayshua83** [comment]
Any news on this issue? Seems easy to fix? :) lol

**Comment by Quadbro** [comment]
nope,  you need to be a leader to do it, it's quite logical, it's not an admin feature)

**Comment by elfl0rd** [comment]
However, it is strange that the administrator does not have rights to anything.

**Comment by WeaselDog** [comment]
This will be added in 9.1
