### ISSUE TITLE
USER ISSUE: mine coal

### ISSUE THREAD

**Issue by chopperprop** [StrangeLoopGames/EcoIssues#7238]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Tryed to mine coal

**Expected behavior:**
picked up coal 

**Actual behavior:**
Caught exception

<size=60.00%>Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.ClothingInventory.SetUpSuitCallback(User user)
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.TryAddItem(Type itemType, User user)
   at Eco.Gameplay.Objects.RubbleObject`1.TryPickup(Inventory inv)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>

**Comment by metachronism** [comment]
@chopperprop do you have a save this repros on?  this is a very strange error...

**Comment by chopperprop** [comment]
I will check but now the error has changed from throwing me out of the server and generating a code to report with - to the coal breaking apart and disappearing into the ground and not allowing me to pick it up. 
I am playing on Hanley's Playground - server

**Comment by chopperprop** [comment]
I am hosting this server with my other account which is a a Developer purchase. Server is a Dual Processor XEON 2.4 ghz -64 gb ram running on its own IP - 47.50.185.236

**Comment by metachronism** [comment]
@craig-jong related to your creative mode cheat command

**Comment by chopperprop** [comment]
Server is now running at 162.210.240.179 earth builders this is a VM and running smoothly however can only hold 20 in carrying cap in creative mode

**Comment by craig-jong** [comment]
Oh, because it lets you put ore in your suit slot. That's funny, I guess.

**Comment by craig-jong** [comment]
fixed
