### ISSUE TITLE
Wrong action. Hint - "Put "fuel"", action - turn on\off

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7240]
All lighting items with fuel storage, have this.
Grab fuel (coal on screenshot) move to it, hover mouse to it.
See "put coal", but RMB do not put fuel, RMB swith on|off.
![20180417002859_1](https://user-images.githubusercontent.com/4980243/38837058-33aef500-41d9-11e8-83e9-4bd1180993be.jpg)

Ideal - if you carry fuel, and target have space, they put.
else - turn on\off

**Comment by elfl0rd** [comment]
Looks fixed on stagind, but you lost "torch stand" ;)

**Comment by elfl0rd** [comment]
same on combustion generator.

**Comment by elfl0rd** [comment]
@BlazeGuy2 hm, can you close lot of duplicates? :D

**Comment by Deantwo** [comment]
Easiest fix would just be to fix the "(Right-click) Put Coal" to say "(Right-click) Toggel on/off" instead.
Or is the two functions so much in conflict that they also want do the opposite?

**Comment by elfl0rd** [comment]
As i know - yes, hint and actions based on loaded components, loading order is not hardcoded and "random" in this case.

**Comment by elfl0rd** [comment]
Found discussin.

> MarjieAVolk
> This is because both the fuel component and the on/off component add right click behaviors, and in this case the on/off component is winning.
> Not sure how we want to resolve these issues in general.
> Yes it will be a bit random I would guess, it's going to be based on what order the components were added to the object. So it might be specific to certain objects. It might also change when you reload the server. But I would guess during a single play session it will be specific to each object.
> To do it the 'right' way, we might need to add some kind of priority system to the components.

**Comment by elfl0rd** [comment]
@D3nnis3n can you close lot of duplicates? :D

**Comment by SlayksWood** [comment]
move to #11979
