### ISSUE TITLE
Massive reduction in perfomance as a result of underground excavator use (poor performance testcase)

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7241]
Someone on my server has used an excavator underground.
This has lead to the game becoming unresponsive for almost anyone who gets close to his house, which leads to inactivity boots.
I will attach a save file when it has uploaded to drop box.

**Comment by CuAnnan** [comment]
https://www.dropbox.com/s/122s9s03cmy0t7s/problematic%20house%20save.zip?dl=0

**Comment by CuAnnan** [comment]
So I should add.
These massive reductions in performance effect only the client. I realise that was ambiguous.

Also, they can cause the game to completely stop responding (sometimes requiring a task manager kill) and at worst they can lead to silent crashes that produce no crash log.

I get that it's already High Priority, I'm not trying to pressure, just trying to be as complete with my description of the problem as I can.

**Comment by SeanAtr0n** [comment]
where is their house?

**Comment by SeanAtr0n** [comment]
found one in alex.richter's mine but it seems fine to me?

**Comment by CuAnnan** [comment]
Game consistently freezes when I approach it. And when I say consistenly, I do mean every time.

**Comment by SeanAtr0n** [comment]
approach it from what coordinates w/ what view distance?

**Comment by SeanAtr0n** [comment]
i'm not seeing much loose rubble in the save here... does he normally have tons?

does it only lag when he is actively digging with the excavator?

**Comment by CuAnnan** [comment]
The game becomes unperformant/unrepsonsive whether he is online or not.
When I approach from my house or from north of his house.
And not just for me. For four or five of the other players.
my view distance is 65, it was 77 and worse for it

**Comment by SeanAtr0n** [comment]
Yeah it's pretty sluggish there, but a lot is going on in that area... seems like this isn't really related to the excavator so reassigning as a general performance issue

**Comment by SeanAtr0n** [comment]
btw @metachronism the area in question is ~2390, 716

**Comment by metachronism** [comment]
closing per other optimization "bugs" - I have the save downloaded though and will take a look to see how it performs with new pending stuff in 8.0
