### ISSUE TITLE
Clean up Economy Viewer

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7245]
Per Forum Users:

"azizmandar posted 2 days ago   

I play with a community that is over 100 players. The biggest headache for us is the Economy Viewer. after about 3 days it takes a while to open up. after 10 days you almost can't use it because it lags too bad. It also looks like the Viewer may be attempting to keep values updated in real time which would explain some of the lag.

Suggestion: Add a filter to the Shop screens (at the least Sale and Wanted) so you only see what you are looking for (maybe open it blank and only show once the filter has been set even if the filter is All) Only update when refreshed which should be easier and faster with a filter.

This seems to be the single most disruptive component to our community enjoying the game and we would love it to work better.

Pacifyer posted about 16 hours ago   

I support this.
The economy window should fetch the data once and then manually update it.
In the fetched results you should be able to do a text search (dynamic filter).
These are minimum requirements right now."

**Comment by Huntermeign** [comment]
I support text searches

**Comment by johnkslg** [comment]
Good points. I put in some basic optimizations for 7.5 that I hope will help, and will look at adding these suggestions.

**Comment by johnkslg** [comment]
Anyone have a link to a save file where the economy viewer is way-too-slow?

**Comment by ShaydenMac** [comment]
What file would that be? I can probably get one.

**Comment by johnkslg** [comment]
The save file, game.eco

**Comment by ShaydenMac** [comment]
Okay, I should be able to get that today.

**Comment by ShaydenMac** [comment]
Via KoS Betazed server. 1st file is mods.zip and the second is the game.eco file.

https://drive.google.com/file/d/119m_iD1ce8i143SU7WubmPWudIDv5JG-/view?usp=sharing
https://drive.google.com/file/d/1VO3JPpsTAp0TvA-msfW5_FBLzoGCcGaO/view?usp=sharing

**Comment by johnkslg** [comment]
Calling this fixed, the economy viewer is way faster now and has more options.  Will add more soon too.
