### ISSUE TITLE
Game kicks user out to main menu after 'LocalServer -  Initializing WebServerPlugin...' step

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7246]
From Discord, user included output_log.txt at the end. Already tried deleting the appdata folder:

Generalpluto3 - Today at 2:22 PM
hello do you know how to fix the game where I can play,i either get tabbed out or it just shows the menu screen but blank

GophTheGreat - Today at 2:22 PM
Hello!
There a bunch of reasons why that might happen
What version of the game and operating system are you running?

Generalpluto3 - Today at 2:23 PM
windows 10 16299.371
And I'm opted out of all betas
so 0.7.3.3
Ive tried file verifying and the server tool along with reinstalling

GophTheGreat - Today at 2:25 PM
So you can get to the main menu, but there are no buttons?

Generalpluto3 - Today at 2:26 PM
I can be on the menu and start new game or join a server however it never loads either way and either tabs me out and when I tab back in its in the load game area or it shows the background with no buttons

https://pastebin.com/ybyaRXuN

**Comment by johnkslg** [comment]
Seems likely, since it halted on webserver

**Comment by johnkslg** [comment]
Resolving as fixed.
