### ISSUE TITLE
[V7.3.3] Logging Efficiency seems bugged

### ISSUE THREAD

**Issue by Mahsaap** [StrangeLoopGames/EcoIssues#7247]
Player reported issues with logging efficiency.
I investigated and it seems that not only does the GUI act strange, but the value doesn't change after level 1.

Level - Consumption
0 - 20
1 - 17.14
2 - 17.14
3 - 17.14
4 - 17.14
5 - 17.14

![image](https://user-images.githubusercontent.com/13688718/38842713-df7be8a6-41c1-11e8-9289-d779c6f51720.png)

![image](https://user-images.githubusercontent.com/13688718/38842727-f63cb278-41c1-11e8-8dcc-1218e3e5013c.png)

**Comment by Mahsaap** [comment]
Yes that is how it is supposed to work. Not sure the point your trying to say there.

**Comment by craig-jong** [comment]
The "Axe" item is a base-item and is not obtainable through any normal means.

It should be hiidden, though, so I'll fix that. The rest of the axe items seem to be functioning correctly.

**Comment by Mahsaap** [comment]
Hmm didn't think that would matter. Someone else had mentioned issues with the numbers so I checked. I'll verify myself with iron axe later too. Thanks.

**Comment by Mahsaap** [comment]
I summoned it , so I didn't get it through normal means. Just for testing.

**Comment by Mahsaap** [comment]
I summoned it , so I didn't get it through normal means. Just for testing.
