### ISSUE TITLE
[7.4] Unable to get 7.4 servers to show online.

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7248]
I am unable to see any 7.4 servers with the 7.4 client,  I thought maybe it was just may server as there is no longer a  server browser service setting in network.eco and in the Network tab but 7.4 client loads all favorites as offline and shows no other servers online at all, whether 7.4 servers or incompatible

I think now perhaps its the client?  I deleted the appdata and that made no difference but when I went back to the 7.3.3 client i could again see most servers online but no 7.4 servers even with show incompatible checked..  The server is online and I can reach the webpage and /info but cannot get it to show in the browser, either the 7.3.3 browser or the new 7.4 browser.  The 7.4 browser shows nothing online at all.

**Comment by elfl0rd** [comment]
I create this screenshots to my community, maybe this help to you.
![20180417150930_1](https://user-images.githubusercontent.com/4980243/38869141-5915ba62-4252-11e8-9f7c-e5100172b1aa.jpg)
![20180417150021_1](https://user-images.githubusercontent.com/4980243/38869147-5d7a2caa-4252-11e8-81c3-4881ee64c543.jpg)

And QoL request.
https://github.com/StrangeLoopGames/EcoIssues/issues/7251

**Comment by metachronism** [comment]
yes, most servers will be filtered out wiht the default settings (primarily, only show servers with more than 1 current player on them)
