### ISSUE TITLE
USER ISSUE: Can't claim land that has a stockpile on it.

### ISSUE THREAD

**Issue by ECO34RT** [StrangeLoopGames/EcoIssues#7249]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Unclaim land with a stockpile on it. Then attempt to reclaim the same land. (Doesn't matter if the stockpile is empty or not)

**Expected behavior:**
I expected to be able to reclaim land that has a stockpile on it.

**Actual behavior:**
Game did not let you reclaim land with a stockpile on it.

**Comment by MarjieAVolk** [comment]
Same as https://github.com/StrangeLoopGames/EcoIssues/issues/1493 which got closed as won't fix earlier, but I think we should fix it still.

**Comment by metachronism** [comment]
verified this works in 7.5.1
