### ISSUE TITLE
In-game ecosystem counters in #Welcome chat window all read zero

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#725]
![image](https://cloud.githubusercontent.com/assets/6193670/19803049/18e4d59e-9d63-11e6-913c-b5da69d24b98.png)

As per the title, all these ecosystem values are zero

alpha 0.5.0 master-2db86ae4, on StrangLoop debug server

**Comment by johnkslg** [comment]
Fixed! Thank you.
