### ISSUE TITLE
QoL default server browser filter parameters.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7251]
**Version:** 0.7.4.0 beta staging-283f0ecb
In the current settings, the user may not see any servers.
They looks as bug.
![20180417150008_1](https://user-images.githubusercontent.com/4980243/38868556-1a2e1fa8-4250-11e8-94c2-c152ee55ba15.jpg)
My suggestion is disable filter by default.
![20180417150021_1](https://user-images.githubusercontent.com/4980243/38868603-43466490-4250-11e8-9a9a-d9c8bd4fb457.jpg)
or
add all filtered servers to list, and colour it as gray
![20180417150332_1](https://user-images.githubusercontent.com/4980243/38868772-f4b7b26a-4250-11e8-929e-f2467a6004be.jpg)

**Comment by MarjieAVolk** [comment]
This has been changed as you suggested.
