### ISSUE TITLE
Ability to pass a law based on player reputation

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7253]
Does not seem possible at present. Or if it is it is not immediately obvious where it is found and nobody in the discord could answer where to find it.

**Comment by MarjieAVolk** [comment]
Nope it is not possible right now.  Good idea.

**Comment by beastyn** [comment]
Need to add reputation into Citizens measurements

**Comment by johnkslg** [comment]
It finally exists!
