### ISSUE TITLE
Clickling any button that opens external window starts steamVR

### ISSUE THREAD

**Issue by CammyRK** [StrangeLoopGames/EcoIssues#7256]
Hello! its a little annoyance when playing the game. when i click one of the buttons at the bottom right that opens an external window my steamVR fires up, in task manager it says SteamVR (3) so it fired up 3 times and i also cant close it as long as ECO runs. If i use task manager to close it it just starts back up with the (3) still.

**Comment by rainfarmer** [comment]
@CammyRK Is this on your on a single player server or online?
Are you hosting it or someone else?

**Comment by metachronism** [comment]
we've added confirmation buttons to open the web browser, should resolve this
