### ISSUE TITLE
Suggestion: "loog hook" tool

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7257]
Hi there!
I really want a tool, allow player grab and move unprocessed tree trunk.
In real world - this tool is "loog hook"
![a3110_1_full](https://user-images.githubusercontent.com/4980243/38889655-0935dcee-4288-11e8-93d7-1bdf2d18acc1.jpg)

**Comment by Elliander** [comment]
I want to see this as well. I had an issue in the past of either not being able to find a log I cut, or it disappearing when I came back to the spot I marked unless I cut all the logs first, then set them down and then came back.

Maybe it could require dragging slowly, with a higher energy cost, depending on weight?

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoSuggestions/issues/26
