### ISSUE TITLE
User Issue: Need more than exact change when purchasing from shop

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7265]
**Version:** 0.7.4.0 beta staging-b8e0bc58

When I went to make a purchase in game, having exactly 1 credit and trying to buy an item costing 1 credit, I was unable to do so because the game things "You can't afford that. You have 1 [credit] but need 1." As you can see here:

![need_more_than-exact_change](https://user-images.githubusercontent.com/15022396/38906057-f6ab09ea-4279-11e8-89d8-ef3a6c6c223f.jpg)

Selling an item for 0.2 credit allowed me to purchase.

**Steps to Reproduce:**

1. Have exact change to make a purchase.
2. Attempt to make a purchase that would result in credit remaining.
(I only observed this with 1 even credit, so it might work with other numbers. Don't know)

**Expected behavior:**

If I have exact change to make a purchase it should allow me to end up with zero money.

**Actual behavior:**

Once credit is acquired it's impossible to have zero since some seems to be required to be left over no matter what. This could also skew people into thinking a currency has more acceptance than it does. My guess is that it's probably a very slight logic error where a zero is incorrectly handled.

As a side note, it's also impossible to make a purchase while simultaneously making a sale - at least from what I experienced. It should be possible to do so.

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/8466
