### ISSUE TITLE
User Issue: Glitching through world with cart

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7266]
I found an issue which I would consider to be very low priority because of the specific series of events required to trigger it, but does have some possible in game consequences so should be addressed.

If you make an underground tunnel wide enough and tall enough for a cart to go through, but not turn around in, the attempt will partially glitch you into the wall and allow you to see the over world objects and look around like so:

![see_through2](https://user-images.githubusercontent.com/15022396/38906896-be72fa24-427e-11e8-8307-f9bc2dac0892.png)

And here's what the cart and hall looks like:

![see_through3](https://user-images.githubusercontent.com/15022396/38906950-08b5bd24-427f-11e8-84be-2593ddbf55cf.png)

If you keep trying to turn around, you will fall through - going down under the map which would then result in being teleported to above ground. The cart, similarly, can also get pushed up, in which case if a tree is overhead it can fuse with the tree:

![see_through6](https://user-images.githubusercontent.com/15022396/38907030-67f807ba-427f-11e8-9d50-bff1bcfe86fe.png)

In which case there are two options: You can either pick up the cart (that works, but only if empty of course) or you can try dragging it. However, dragging doesn't work by itself. I had to repeatedly pick it up and drop it until it moved enough to wiggle out of the tree.

A simple solution to this issue would be to allow pushing as well as pulling carts. Well, it wouldn't stop people from trying anyway, but it would reduce the likelihood of someone trying to turn around and getting the cart stuck in a tree above ground.

As far as in game consequences go, something that I have been trying to do to get around some of the limitations with running shops and also keeping people out of areas is the combination of doors and hidden rooms. I can imagine a few scenarios where a player could try glitching to get into an area of someone's property they shouldn't otherwise be able to physically access. Again, a very small issue, but thought you guys would want to know about it.

**Comment by Xeanoa** [comment]
Similar issue:
I tried to use a 2-wide underground ramp with a Powered Cart. About two out three tries, the cart glitched into the wall, jumping around eratically, and the only way to get it out was deconstruction, or attempting to glitch it through the wall completely, so it would get teleported to the surface.

Suggestion: Would be nice if /unstuck also worked with carts, taking them with you.

P.S.: @Elliander, you can already push carts around, and drive backwards with the powered vehicles, and I do it frequently getting out of underground paths again.

**Comment by ShaydenMac** [comment]
Via Discord: 

"Hey :smiley: My friend and I have an major bug at some point of our street. When we cross that point with an truck or powered cart we fly threw the map. Is there any known solution to that problem? Thank you in advance"
