### ISSUE TITLE
CO2 Emissions rate from plants Capped at -100PPM per day

### ISSUE THREAD

**Issue by Legends0** [StrangeLoopGames/EcoIssues#7267]
**Version:** 0.7.3.3 beta

Is this some sort of server configration / default cap that I am not aware of? We were having pollution issues, and one means we thought to combat it was just to plant more trees, until we reached a point where more trees did not decrease PPM per day anymore. We are planting about 100+ trees at a time.

**Steps to Reproduce:**
Plant many trees until -100 PPM per day from plants is met.
Continue to plant more trees.

**Expected behavior:**
Plants intake of C02 PPM increases as more plants are planted.

**Actual behavior:**
Once PPM from plants reaches -100, additional plants do not decrease more PPM per day.
![image](https://user-images.githubusercontent.com/5702579/38910462-68ba8516-4297-11e8-86d0-9b83a147ae4c.png)

**Comment by craig-jong** [comment]
Yea, plants are capped. This is a server setting and can be changed, though pollution is getting changed so you may not need to make edits.
