### ISSUE TITLE
[Suggestion] Deed Covenants and Mineral Rights

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7269]
In real life, deeds can have restrictions placed on them prior to a transfer of ownership - often called covenants. I was looking at my property and realized that the only real reason why I took possession of the areas I did were because I didn't want someone clear cutting and strip mining my pristine area.

If I could put a covenant in place that say that the owner of such and so parcel(s) have a series of restrictions I place on them - which can exceed the restrictions of a law - I could see players actually being willing to sell property in the game.

For example, "No more than X trees per day cut, and no trees can be cut until previous stumps etc removed." or "No hunting allowed." or even "No hunting, no fishing, no killing." (So the law could say you can cut as many trees as you want, but I say that as a condition of sale you must be willing to leave the trees and animals be and work around them)

Of course, for that to work the option to unclaim property would have to be able to be disabled while a covenant is in place with only the original owned having the authority to anull the covenant.

A related suggestion is the ability to sell mineral rights only for a location, meaning I could offer to buy the land under an adjacent property meaning that I am free to dig under, provided that I stay below a certain number of blocks from the surface - and the original owned is not allowed to dig below that point, but is still free to add more dirt on top. This would, in effect, make it much easier for me to build underground roads connecting regions.

**Comment by Elliander** [comment]
To add to the above:

Maybe we could have an option for using properly claim flags, where they are worth a larger area if the player choose to either claim just the surface or just the minerals. In that case, when building a rail system or underground highway I could claim just what I need and purchase surface rights only where I will need to go above ground. I could then purchase from land owners rights to dig under their land, and likewise someone only interested in building on the surface could claim a larger area while ignoring the underground such as in a low skill point world where only miners would really be the ones digging like mole men.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#124
