### ISSUE TITLE
Store & Fuel

### ISSUE THREAD

**Issue by Thineboot** [StrangeLoopGames/EcoIssues#7271]
Version: 0.7.3.2

Setup: Link *Fuel Supply* to *Store*; don't link *Storage*

Expected: Buying *Fuel* in a *Store* direct into *Fuel Supply* tank.

Behavior: *Fuel* lands in *Storage* which isn't linked.

![ecostorefuel](https://user-images.githubusercontent.com/4364842/38926470-173c1df0-4303-11e8-8412-607c1cf22161.png)

**Comment by Thineboot** [comment]
Store owner: *Seeker86* (see *Seeker's Store*).
Buyer *Thineboot*.
And no, Seeker86 had neither linked my *Storage* nor my *Fuel Supply*, I tried to buy *Fuel* in his Store.

Setup: 2 player
A: *Store* sells Fuel, no further link
B: *Powered Cart* links *Fuel Supply*, not *Storage*

**Comment by MarjieAVolk** [comment]
Okay I went and looked at this, and in fact it only stores settings per object, not per inventory on the object.  So no wonder it is doing that.  Going to go in and extend the settings so it stores them per inventory.  It won't be released in the upcoming release though.
