### ISSUE TITLE
USER ISSUE: De-syncing from tree chopping

### ISSUE THREAD

**Issue by minerguy341** [StrangeLoopGames/EcoIssues#7272]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Chop down a tree
stand on it while you chop and immediately pick up what you can	

**Expected behavior:**
tree should have remained visible until ALL wood was collected from it

**Actual behavior:**
tree vanishes after about 3 or 4 sections, and client and server de-sync about where said player is, requiring them to relog

**Comment by metachronism** [comment]
fixed 7.4.0 release
