### ISSUE TITLE
[7.4] Excavator sound is playing when not using

### ISSUE THREAD

**Issue by FWerewolf** [StrangeLoopGames/EcoIssues#7274]
I stand in front of my excavator, not using it (neither does someelse else) and I can hear the sound of the motor. It doesn't use any power, so it is definitly off, but the sound is on.

**Comment by omgguyriots** [comment]
Sometimes I have it the other way round. I'm using the excavator but there is no sound.

**Comment by geeknessfr** [comment]
Same issue, also in 7.4, I can hear engine sound while walking around the excavator.

**Comment by Nanders** [comment]
Fixed

**Comment by elfl0rd** [comment]
Thx :D can you pull update to steam?

**Comment by Nanders** [comment]
Will be appearing in the next build
