### ISSUE TITLE
Add AirPollutionComponents to PoweredCarts

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#728]
Can you add these components to PoweredCarts in the tech tree?  Thanks!

**Comment by johnkslg** [comment]
this.AddComponent(new AirPollutionComponent(4));
            this.AddComponent(new LockComponent(false,false));
            this.AddComponent(new StatusComponent());

Can you add these other two components in addition?

**Comment by metachronism** [comment]
it does now
