### ISSUE TITLE
/unstuck no longer works

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7284]
Even with the timer, waiting it out fails.

**Comment by SeanAtr0n** [comment]
are you truly stuck in the first place?

**Comment by Nanders** [comment]
Fell into a cave/hole

**Comment by SeanAtr0n** [comment]
was it a really big cave or did it have an exit you could walk out of?

unstuck now uses pathfinding so it won't unstick you if you can walk out of an area

**Comment by Nanders** [comment]
Was a 2x3 hole in the ground, maybe 8 blocks deep.

**Comment by SeanAtr0n** [comment]
fixed
