### ISSUE TITLE
Storage Link only set manual and willingly

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#7285]
Hello SLG-Team!
I would suggest, links between devices and storages should be done only manual and willingly, not automatic. Otherwise the material flow may not be overseen.
I hope You understand what i meen - excuse my bad english.
Have a nice day

Edit: Wanna extend the first idea, if possible put two marker/check-boxes in the menu for each device, one acts as source link, one as destination link. Both can be set independently.

**Comment by ecoemmeck** [comment]
I put this idea forward on the forums awhile ago.

http://ecoforum.strangeloopgames.com/topic/2762/game-improvements

**Comment by ZehTed** [comment]
also a button to link/unlink all storage from the selekted storage would be nice.

**Comment by Elliander** [comment]
I like this idea. I actually had a problem wanting to move a temporary stockpile, but was unable to do so because it was linked. I also had trouble getting more distant stockpiles to work at all because the closer one had priority.

**Comment by Nicolausi113** [comment]
As I played this game now a while, I steady had to think about this cumbersome storage links. If a device is opened, it takes long time till a reaction is visible. Then  a hole bunch of uninteresting links appear and I have to sort and control them the hole time.
So another idea emerged and seams to me the best solution, the former suggestions are then needless.

Each device should have a marker/checkbox in the headline somewhere beside the name and switches the link on/off. With placing a device, the link is per default off and the device is not visible to others. The player selects interesting devices and switches the link on (crafting tables without fuel have no link). This could bring back some performance and clearness in the storage menu.

I just wanna mention one step more, namely two markers for source and destination. Bud this is going to be complex and should be considered thoroughly.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#123
