### ISSUE TITLE
[Suggestion] Ability to download backup of server hosted by someone else

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7287]
While I understand that in a server based game, the people logging on expect to be building in a world that someone else is hosting, but it was very discouraging to have spent so much time building something beautiful only to to open the game and see... nothing... under "Continue", and then to not see the server listed at all when I clicked "Join", but a similarly named server was now on day 1.

The last thing I did was build a tunnel through a mountain, that came out over a waterfall stream and the way the light struck the trees as you came through was just so beautiful I wanted to share it with a friend. I was in the process of logging in to show her, to get her interested in the game, when I discovered it was all gone.

Apparently, I was playing on a test server that without warning was reset on day 5. It was enough to make me want to quit playing all together. I certainly no longer feel comfortable playing in a world hosted by someone else, because it means the host can arbitrarily decide to destroy the entire world regardless of the actions taken in game, and that's just wrong. I didn't even get a screenshot yet because I had no way of knowing the world was about to be destroyed!

While ordinarily we shouldn't expect to be able to download an online game, in this case - where the game can be played offline or in a small server - I think it would be appropriate to have that option. 

I can think of two ways to go about it: The simplest would be for a world setting where all the server files are incrementally backed up to a zip folder with a URL generated that anyone can download, but the 2nd makes more sense to me personally: While playing the game, the game client can generate it's own backup of the world. Then, if the server goes down, a player could have the option to host new world from backup and then when doing so be presented with 2 options: restore entire world as is (meaning that properties owned by other players are still owned by them and all settings remain) or restore only your own property (meaning that a new world generated from the old seed is created, where only your own property gets ported into the new world and anything you built outside of your parcel has to be started over.

If nothing else, I'd like to have an offline only backup of said world.

Additionally, any host that has a history of destroying a world early should generate some kind of error so the other players can be aware of what they are getting themselves into. Similarly, if a world is about to be reset, the host should have to actually give people a warning about it.

On a related note, if anyone knows who was hosting:
[EU]-Jupiter Beta 0.7.40 

I'd like to find out if they still have backups of the world they were testing. I'd like to get those files and host that world myself if nothing else.

**EDIT:** After  I posted this, the server seems to have come back, but now I can't continue because it says "Incompatible version".  I didn't know what that meant at first, but apparently the server was taken offline to be updated and then I had to download a different build of the same version to continue. It would be nice then if there was a cache of the server listed that can show online status, as well as a note if an update is required and a link to where to go to download said update.

**Comment by pamduncan** [comment]
I see a problem here with this.  Most server owner feel like that data is theirs and not for the taking from their server without tehir permission especially as there maybe chat in the chat logs that the owner does not want propagated throughout the internet.  the second is that to download a backup from their impacts their data transfer, not just the person  grabbing a copy and for many servers - especially hosted servers you would need access to download a file from their directory and that would pose a security breech if just by having permission to play the game you would have access to their file store.  And third you could not download the live file as that would cause the server to be unable to read/write while it was in the process of being copied which means you would have to have access to the full backup store and again many probably down want just everyone having access to that.

**Comment by Elliander** [comment]
The first issue - chat logs - would be impacted if a total copy of the server was made, but then that approach would be a server setting to begin with. However, with the approach of the client only saving a copy of the objects and owner associations (or, even more limited, what the player themselves own) that wouldn't be a problem.

The 2nd issue, yeah, I can see the problem there. Then again, how much of the world is downloaded by the client while they are playing anyway? What if the program could copy whatever is in the data stream as it's incremental backup, so maybe not an exact copy of the world, but a copy as they see it? 

Ultimately, what people find themselves attached to are the things they spent time creating. There has to be a way to preserve that without hampering the host.

**Comment by Deantwo** [comment]
As @pamduncan already mentioned, this poses very more issues than it would ever solve.

Minecraft even had to allow hiding of a server's world seed, because cheaters made a cheat-enabled singleplayer world with the seed and then noted down locations of all rare minerals in order to get an advantage on the server.

It is much easier for you to ask the server admin for a copy of the backup. If you really want to be able to download a backup at any time, ask the server admin to setup scheduled automatic backups saved to a public accessible file server.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#122
