### ISSUE TITLE
On singleplayer "Run for office" opens game directory instead of webpage

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7290]
I know its nonsensical anyway, but this option should be handled somehow for single-player play.

**Comment by Elliander** [comment]
This is actually related to an issue I have in multiplayer, as I reported here:

https://github.com/StrangeLoopGames/EcoIssues/issues/7225

Are you able to view graphs? or propose laws? I had no idea that a web page was supposed to be involved in this. Seems like it should be an in game menu.

**Comment by rainfarmer** [comment]
Follow other issue for solution: https://github.com/StrangeLoopGames/EcoIssues/issues/7225
