### ISSUE TITLE
USER ISSUE: Fall Through the world

### ISSUE THREAD

**Issue by carsonbarlow** [StrangeLoopGames/EcoIssues#7293]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
I jumped into the ocean.	

**Expected behavior:**
I swim in the ocean.

**Actual behavior:**
I fell through the world.

**Comment by SeanAtr0n** [comment]
duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/6517
