### ISSUE TITLE
Suggestion: allow renting of deeds in contracts.

### ISSUE THREAD

**Issue by zimmah** [StrangeLoopGames/EcoIssues#7295]
I have made a big mall, where I am selling (and planned to rent) the shops. Like the mall itself has 14 shops and is expandable, and I've subdivided the plot and selling individual sections.     
  
I'd love to rent some of them.     
   
It would be nice to add clauses for payment to contractor in reward for something (like temporary or permanent access to land or an item)    
   
You could rent shops, houses/hotel rooms (which would give the skillpoints), farms, mines, orchards (if fruit trees become a thing), animal farms (if that becomes a thing) hunting grounds, lumberyards, work stations, etc.       

(I know you can allow the use of an item for a fee, which is similar, but doesn't capture most of the above situations, which are bigger in scope. Speaking of which, it would be nice if said items, like a repair bench, would allow to set usage fees based on items used, in case the owner of the repair bench supplies the items (set price per stone used, price per iron ingot used, price per log used, allow the user to provide their own materials for a discount or even free repairs).      
  
While on the topic of contracts, loans would be nice to have too. But i think a system like that is coming soon.

**Comment by johnkslg** [comment]
I will definitely do this!  Might be a bit though.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#121
