### ISSUE TITLE
USER ISSUE: Not Allowed To Create A New World

### ISSUE THREAD

**Issue by GamingScott** [StrangeLoopGames/EcoIssues#7297]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
1. Launch game.
2. Create a New World.
3. Have your fun deprived as you struggle getting this game to work.

**Expected behavior:**
Created a new world

**Actual behavior:**
The following error message popped up:
```
Could not start server: Process has not been started.
```

**Comment by metachronism** [comment]
fixed 7.4.0 release
