### ISSUE TITLE
SUGGESTION: Admins need a /save for restarts

### ISSUE THREAD

**Issue by XsExcess** [StrangeLoopGames/EcoIssues#7298]
**Version:** 0.7.3.3 beta

**Suggestion**
Restarting the server right now can cause large rollbacks, which have the potential to mess with balance or really screw people over, due to how the world/player db are saved separately.

**Comment by SeanAtr0n** [comment]
you can currently do Storage -> Save All and flush to disk
or type "exit" in the console

**Comment by elfl0rd** [comment]
need ingame chat command.
save, and shutdown (save, then quit).

**Comment by XsExcess** [comment]
You can save in the GUI, but most server hosts don't give access to that. Its just the same as /whitelist /admin etc. being in the game when they're doable on the gui or in the files.

**Comment by CompactDisc** [comment]
Our people just lost hours of progress because of this. The world is saved, but their inventories and skills got reset for multiple hours.

**Comment by pamduncan** [comment]
There is a mod https://pradoxzon.squarespace.com/eco-mods/adminutils/ that gives you many of the server UI command, including /save and /backup through the in-game command  line.  This is recommended if you do not have access to the server UI to save a game before shutting down

**Comment by CompactDisc** [comment]
I do use pradoxzon's mod now, but it's still something that should be addressed in the main game.

**Comment by shadow7412** [comment]
As I host our server on a headless ubuntu server, anything that is customisable in the UI but not via commands is something I can't change.

I might check out that mod - but it would be nice if full admin functions were available.

**Comment by CompactDisc** [comment]
Update: Even using Pradoxzon's mod, using the /save function doesn't work properly. No matter what, if our server crashes or restarts, we lose more progress in either the world save or the character save compared to the other. We often lose materials that way and sometimes get massive rollbacks of multiple hours.

**Comment by XsExcess** [comment]
Yep, the only way to reduce the effect of the rollbacks is to massively increase the frequency of both Backup.eco and Storage.eco . Even then for planned restarts, /save is nice to prevent any world rollback, even if you can't stop player rollback (but you can set it low enough that it doesn't matter as much).

Unfortunately this fix can also cause a lot of CPU/Storage usage, up to 20x the default settings in my case.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#120
