### ISSUE TITLE
USER ISSUE: Farming scroll

### ISSUE THREAD

**Issue by ColWindsor** [StrangeLoopGames/EcoIssues#7301]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Created the farming skill book which gave me the scroll.  I right clicked on the scroll and it disappeared and the chat room said i learned farming.  Though when i go into my skills tree it's not highlighted and i don't have any recipes.  When i create a new scroll and try to do it again it says i already learned it.

**Expected behavior:**
I expected the skill in the tree window to be highlighted and recipes to be learned.

**Actual behavior:**
Game says i learned it but i have no recipes and it's not highlighted on the skill tree.

**Comment by craig-jong** [comment]
Is it possible the specialization was unlocked and you just didn't pick it?

**Comment by craig-jong** [comment]
If that was not the case, can you please upload a copy of the save?

**Comment by ColWindsor** [comment]
Yes, actually, I wasn't aware that the research station doesn't teach you the skill, it just makes it available to be CHOSEN as an option.  I was under the impression that by researching something that you learned the skill, i was mistaken.  Thank you though.

**Comment by craig-jong** [comment]
This should be more clear (UX thing) but for now I'm going to close this issue.
