### ISSUE TITLE
[User Issue] Vehicles reorient sideways after walking away and returning

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7302]
**version** 0.7.4.0-beta-staging-248fc2c1

I had a truck parked in a tunnel I was building, because the roof was too low and needed to walk a short distance to unload. When I came back though I saw this:

![truck position resets](https://user-images.githubusercontent.com/15022396/39026004-0d84a440-4410-11e8-93dc-57f96a592ccd.jpg)

Basically, the truck has a preferred default orientation in the world and the tunnel happened to be built different from that orientation, so when I walked away and came back the object was reloaded without regard for how I left it.

Thankfully the tunnel was wide enough for it to fit, or else who knows how I'd find it. Still, I have no way of driving it out of there so I have to remember to never park in any tunnel... or rather, if I do, plan the garage orientation carefully.

What really bites about this though is that it barely had any fuel in it and picking up a vehicle seems to destroy any unburned fuel.

**Comment by shadow7412** [comment]
I feel like this issue also occurs with wooden carts - I'll leave the cart alone for a while and come back to it being upside-down.

**Comment by Elliander** [comment]
Yeah, and with the cart duplication bug I once had a cart end up stuck in a walkway in such a way that prevented me from ever dragging it out or pick it up, so rotating vehicles can be a real problem.

If we could keep it loaded in RAM that would probably fix the issue, but it would obviously be a bad idea if we kept track of it no matter where we were because that would strain the servers. It also wouldn't really stop it from rotating when we close the game and re-open, but I just posted a suggestion along those lines here: https://github.com/StrangeLoopGames/EcoIssues/issues/7409

**Comment by shadow7412** [comment]
> kept track of it no matter where we were because that would strain the servers

Stuff like this needs to be written to disk. I'm not sure how it works in this game, but if I were developing it I would keep a save file of the entire world state but only have the 'active' portions of it in ram. That way if you left a vehicle in this way it would unload from RAM (thus not straining the server) but when a player got near it again it would load it back into RAM in the correct state.

Your issue does seem a little different from mine though - my cart did not duplicate, merely reorientate.

**Comment by Elliander** [comment]
> Stuff like this needs to be written to disk. I'm not sure how it works in this game, but if I were > developing it I would keep a save file of the entire world state but only have the 'active' portions of it in ram.

You are basically talking about disk cache, which is slower, but a possibility for systems with more hard drive space than RAM.

>  That way if you left a vehicle in this way it would unload from RAM (thus not straining the server) but when a player got near it again it would load it back into RAM in the correct state.

Well, from what I heard from others, the number of objects around a player is what determines how much processing power the server ends up using. So multiple objects loaded in RAM, no problem, but if you actively keep track of what the objects are doing - be it in RAM or in the hard drive - that would strain things. 

So while I think that we should have our computers keep loaded the objects halfway around the world in RAM, we shouldn't be keeping active watch of them. The blocks should refresh when we enter regardless, but maybe only update the position of objects that moved.

**Comment by SeanAtr0n** [comment]
Fixed in next staging build
