### ISSUE TITLE
USER ISSUE: Butchery Skill Book

### ISSUE THREAD

**Issue by ColWindsor** [StrangeLoopGames/EcoIssues#7304]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Created Butchery Skill Book in order to get the skill Butchery. Brought out the scroll, right clicked on it, game said i learned butchery.  I go into my skill tree and it does not register that i've learned butchery.

**Expected behavior:**
I expected it to give me the skill of Butchery in my skill tree.	

**Actual behavior:**
Game chat stated i learned the butchery skill though it doesn't register in the skill tree.

**Comment by craig-jong** [comment]
dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/7301
