### ISSUE TITLE
Sort workspace items and skills by profession

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7305]
From Facebook:

"Hey everyone, I am finding that sticking to one profession to be confusing. I would like to see each workspace and each item within the workspace be clearly labeled to identify the profession it belongs to. The skills table should also be more clearly marked to match. This mite go some way to incentivising players to stick to one trade. I really want to enjoy this game. I am finding that more often than not people doing their own thing and not cooperating... I really want to like this game but so far it is failing to encourage players to work together at least in my experience. The graphics look great and you guys have created a really beautiful world. Thanks

I just had another idea. You could set up the tables so that only the items in YOUR profession are visible. This will make it simpler and less confusing. I think it will also further encourage players to stick to one profession."

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#118
