### ISSUE TITLE
Excavator disappears 

### ISSUE THREAD

**Issue by Twelve57** [StrangeLoopGames/EcoIssues#7306]
Version: 0.7.3.3 beta

Steps to Reproduce:
Drive an excavator and dig some dirt

Expected behavior:
A default digging session with the excavator, dig a hole to put a stockpile (so digging a 5x5x5 block)

Actual behavior:
The excavator disappears under the map, cannot find it in water or under even with the fly command in admin mode. So the excavator is still exists but we can't find it. The only way is to remove it from the Game.eco file with 7zip.

**Comment by SeanAtr0n** [comment]
Do you still have a save where you can't find it?

Were you driving it when it disappeared or did it disappear when you weren't looking at it?

**Comment by SeanAtr0n** [comment]
haven't been able to reproduce this yet... any clues as to what triggered the disappearance?

**Comment by Twelve57** [comment]
Hi, sorry don't have any clues to provide you, and also no save because the server is now offline.
We noticed it happens when we are on top of a mountain with a cave underneath.

**Comment by Petyrpox** [comment]
Just had this happen digging tailings storage at bedrock, game crashed, i logged back in i was 1500m away and the excavator reads at a real estate desk as 600 million blocks high in the air

**Comment by SlayksWood** [comment]
Checked on 8.1. Wasn't able to reproduce, seems fixed.
