### ISSUE TITLE
Campfire Crash to main Menu

### ISSUE THREAD

**Issue by JorgenK74** [StrangeLoopGames/EcoIssues#7309]
Hello, I play this game ECO a couple of days till today no problems. Now i have this problem with my campfire, i can add logs/coal and i can get in the menu of recipes. but when i want to order anything, I can't do anything and after a minute i get booted to the main menu with as reason INACTIVITY. The fire place is on my ground in my house balcony. And moved on Teusday to get better acces to my chest, on the same day i did do 3 recipes without a problem, before i logged off.  I can do everything else..

**Comment by craig-jong** [comment]
I need a save where this is occurring. Please upload one (if possible) or provide some steps I can follow to get this to reproduce.

**Comment by SlayksWood** [comment]
Checked on 0.8.3.0 staging-1066. Wasn't able to reproduce. If it happens again, please reopen and provide log and save files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
