### ISSUE TITLE
House SP report tooltip needs to be toggleable

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7310]
The current "dissappears after <x> seconds or <some other reason>" makes it impossible for me to scroll through my room list. By the time I get to the general rooms, it inevitably dissappears.

**Comment by CuAnnan** [comment]
And the room panel down the bottom left needs to tell you what room type you're in.

**Comment by SlayksWood** [comment]
Checked on 8.3.0 staging-1066. Wasn't able to reproduce, seems fixed.
Second message moved to suggestion https://github.com/StrangeLoopGames/EcoSuggestions/issues/869
Closed for now.
