### ISSUE TITLE
Suggestion: Skills table should indicate who has claimed which professions

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7312]
In the skills table the game should indicate what speciality has already been claimed and who has claimed it. Then people can start playing without relying on other players to be online to discuss who is doing what.

**Comment by Elliander** [comment]
I like this idea. Additionally, I'd like to see an option someone can select where they are indicating to other players what skill set they plan to focus on even before specializing. It would help to avoid too much competition and too little diversity.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#117
