### ISSUE TITLE
Suggestion: Creative mode

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7313]
From Facebook:

"I was also wondering if you would consider adding a creative game mode where you can do everything yourself if you chose to?
Players would still have to work together to look after the eco system leaving the unique gameplay concept intact."

**Comment by Elliander** [comment]
I do like that idea, maybe including the ability to fly (like in Minecraft) and to have an unlimited inventory so you don't have to store things dug up in stockpiles, which can detract from the creative process in creative mode.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#116
