### ISSUE TITLE
Add/Remove Blocks Contract Clause missing Seeds and blocks

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#7315]
Hello there!

This could be a pending feature, but the Contract Clause "Add/Remove Blocks" mentions in its tooltip that it can be used for "Planting fields", but there's no way to select seeds on the Item Selection/Search window.

This clause could be used to make contracts for planting tree seeds, for instance.

![ecocontractclausemissingseeds](https://user-images.githubusercontent.com/26847645/39073736-2bb629ec-44c5-11e8-8a23-a8ae1ecc2833.jpg)

Related issues: #7143 [Plant tree Contract Clause] and #5059 [Farming-related laws]

[ Discord player Dr. Rump PhD#5062 attempted to do a tree replant contract during a playthrough and couldn't - he was the one who let me know about the issue. ]

**Comment by beastyn** [comment]
Also some blocks are missing.
Pushing to 0.9
![bandicam 2019-05-31 14-09-06-792](https://user-images.githubusercontent.com/27898520/58695201-33e98180-83ae-11e9-9e16-b967901c3b59.jpg)

**Comment by WeaselDog** [comment]
Plant seeds has its own condition now:
![PlantSeeds](https://user-images.githubusercontent.com/47330823/70365363-e1e65480-1845-11ea-9772-6253968dae40.png)

The blocks look like they are all there now, though some blocks are missing icons.
![droporpickup](https://user-images.githubusercontent.com/47330823/70365388-004c5000-1846-11ea-9efc-6f89597a9220.png)

**Comment by johnkslg** [comment]
Going to push this and do it in work parties instead, closing for now.
