### ISSUE TITLE
[Suggestion] Z-coordinates

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7318]
I'd like to see the Z-coordinate on a map, as it would help me when digging tunnels since the level ground on one side of a mountain can be different from the other side. I also think that Z-coordinates would be helpful if my other suggestion about mineral rights was ever applied.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#115
