### ISSUE TITLE
USER ISSUE: Too many stones

### ISSUE THREAD

**Issue by ironsquishy** [StrangeLoopGames/EcoIssues#7320]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
1. Great a huge hole
2. make alot of mined stone
3. gather it.

**Expected behavior:**
Not Crash

**Actual behavior:**
Crashed

**Comment by SeanAtr0n** [comment]
does this regularly happen for you while gathering stone? did the game crash or your computer crashed?

**Comment by ironsquishy** [comment]
Sorry, for the late response. The game itself crashed.
