### ISSUE TITLE
Allow Eco server to download from steam anonymously.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7322]
Currently, to update server you need lot of manual operations, or use account without 2 factor, or buy additional eco copy to use on dedicated.
basically, you buy eco copy on steam, you have 2 factor.
launch steam on dedicated, download and launch eco server. Try launch eco on main pc - ooops, error! Eco server launched on another machine!
Try to use steamcmd. Oops - they requie 2 factor on each use.
Downloading from site? - no autoupdate...

And i really doest not understand why you make server private, not available to all.

**Comment by Nanders** [comment]
This just got added by Steam today, should be able to access as an anonymous user now
