### ISSUE TITLE
High building makes nearby objects invisible.

### ISSUE THREAD

**Issue by Kumagor0** [StrangeLoopGames/EcoIssues#7323]
## Version
7.3.3

## Problem description

Some objects disappear if placed close to a very high building. List of objects confirmed to disappear:

* Stockpile
* Storage chest
* Blast furnace
* Kiln
* Wooden cart
* Masonry table

After disappearing objects continue to exist: can't place anything on the same spot, keep taking up room volume, can even access inventory from other nearby storages (it's especially fun with stockpiles because you can place items inside invisible stockpile and they get placed on the ground just like if you placed them there by hand).

## Known reproduction steps

1. Place an object (preferably from confirmed list).
2. Build vertical column of blocks above an object (in my case there were 100-150 blocks).
3. Wait (I had 2 cases of this bug, both happened overnight, so it might require rejoin, some time and/or server restart).

## Known solution

1. Remove a column of blocks.
2. (might be not required for success) Wait ~30 mins.
3. Rejoin a server.

**Comment by metachronism** [comment]
fixed 7.4.0 release
