### ISSUE TITLE
USER ISSUE: Players can block each other in character creation

### ISSUE THREAD

**Issue by shadow7412** [StrangeLoopGames/EcoIssues#7324]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
1. Player 1 joins server
2. Player 2 joins server.

**Expected behavior:**
Neither player should see each other during character creation

**Actual behavior:**
Player 1 and Player 2 are both visible on Player 1s screen. Player 2s screen behaves as expected.

**Comment by metachronism** [comment]
seans fixed this long ago
