### ISSUE TITLE
USER ISSUE: can't acces local saves when steamserver tool is open

### ISSUE THREAD

**Issue by NathanMisset** [StrangeLoopGames/EcoIssues#7328]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
1. press load in main menu
2. press a save

**Expected behavior:**
should have loaded saved world

**Actual behavior:**
joins local server

**Comment by elfl0rd** [comment]
singleplayer - launch server too.
You need change ports of localserver.
