### ISSUE TITLE
[Server Issue] Continue button doesn't work for password protected world

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7331]
**Version:** 7.3.3
**System:** Windows 10 64-bit

Last night I ran a few tests to see how large of a world I can make, and it all went great. It's not open for joining yet (I want to run tests to see how many simultaneous connections I can handle first reliably) so I closed the server program and process after running the backup.

When I turned it on today and clicked continue I got an error that the "connection failed" so I went into server list and the details made it look like the world was totally new, but when I clicked to join and entered the password I still had the food I picked up and got the server message that I logged back in.

I thought that maybe it was due to the way I stopped the server, but when I logged out then tried to log back in I got the same message so I am thinking it's an issue with having passwords set, meaning the client needs to prompt the user for a password on continue as well, or better yet store the password that was used.

**Comment by elfl0rd** [comment]
you can add your ID to whitelist.
It's action allow bypass password.

**Comment by Elliander** [comment]
ahh. Good idea! It will help with testing at least, and that way I could give someone test access with me without making it fully open. Still a bug though ;)

**Comment by Elliander** [comment]
This is working in: v0.7.4.0-beta-staging-b79d89de
However, the white list is not working for either, so the password has to be entered regardless every time.

**Comment by MarjieAVolk** [comment]
I just tested this out, and it looks like the whitelist is working for skipping the password.  You do have to enter your slg id / steam id in the whitelist these days (not your username).  Admins can do this in game easily with the command /whitelist, rather than entering the ids in the server window manually.

Closing as fixed.
