### ISSUE TITLE
[Suggestion] Server stop button w/ user notification

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7334]
I'd like to see a "Server Stop Button" that we can click on when running a server that will send a message to all users active in the world that the server will be shut down in X time (which the host can define in a configuration tab) and likewise tell users of remaining time if they log in afterwards. It could also have a message saying when it will be back online, or any other details such as "Server being upgraded. Will be back within the hour." or "Server will return at X time." so they know what to expect.

Then at the designated time users will be logged off, then it will do an immediate backup, then close the server process.

Additionally, it would be nice if the server could then send some kind of notice to a central server which would list text that would appear in the "Continue" button (only for people who only joined the world - not the join list) which we could set to list the status, such as "Offline until X time" so they know the server wasn't just taken off completely.

While people tend to expect servers to be up all the time, it would be more professional to have communication with users if downtime is needed, and to be able to close it with a batch of events so the risk of a corrupted server due to improper closing can be reduced.

**Comment by elfl0rd** [comment]
Love it.

**Comment by Elliander** [comment]
To add to the above, how about including a simple upgrade button and server restart button?

Upgrading is nothing more complicating than replacing all the files except for the storage folder, but a separate process could be used to detect when an update is available and download it all there (although no one likes forced automatic updates - so maybe just a way to download from within the IDE)  which would then grab the files and put them in a temporary folder. It would then initiate the stop server process, with a batch instruction to replace files and then start the server back up.

If the above was implemented the right one, someone could set the server to automatically download an update if available and then notify users that the server will reboot in X time briefly and then do so, all without user interaction.

A user reboot button would be similar, but would be used to apply important changes that require a reboot - and the server operator could be notified if something requires a reboot when setting it.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#114
