### ISSUE TITLE
[Suggestion] Climate change disaster events

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7335]
One thing I noticed so far is that people tend to think that the game is over when the objective - to destroy the killer Earth asteroid - is complete, regardless of the condition of the planet afterwards. 

While I am sure that other disaster events are planned, one idea I had was for a global temperature trend that begins when the world starts and progresses towards a specific end unless the players do something about it. The server could set the start time, and the time when it is complete, to essentially define how quickly the changes occur.

If it's an ice age event, the planet will gradually cool causing ice terrain to expand downward from the mountains, forests to die, crops to fail, and ocean levels to fall. The players will need to get forests established in new areas and increase greenhouse emissions in order to offset the problem, but too many emissions could cause the opposite problem.

In a warming event, we get the opposite: increase desertification, increased ocean levels, dying trees and wildlife, etc. This would be a far more difficult disaster to deal with because the players need to destroy the asteroid while increase carbon absorption. 

We can say that for the purposes of the disaster these are natural events that have a concluded time, but player actions in dealing with the disasters could result in the opposite problem after the disaster is averted. 

As a side note: It would be nice if, in a tall world, the asteroid is likewise shifted upwards. It's weird to see the asteroid fly through a mountain beneath me.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#113
