### ISSUE TITLE
[Suggestion] Allow Gamepad Controls

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7336]
While I love the built in keymapping, it can only really do so much. Specifically, I cannot get it to recognize either thumb sticks for any movement controls - nor even the arrow buttons directly. For that I have to use Joy2Key, and with that I can mostly get things to work right, but it's still not quite right.

For example, the control bar uses a mouse scroll wheel to cycle, but there is no keymapping for that, so I can't tell it to use a shoulder button to cycle (even though it will otherwise accept the shoulder button as mapped input) and so far I haven't managed to get Joy2Key to accept that meaning I had to keymap tab, use a thumb stick as a mouse, then click on what I want to use if I want to use a mouse and that's just tedious.

Another issue is that the items in any storage is meant to be dragged out with a mouse, but I'd like to be able to select an item in a chest with the arrow keys, press a button, and expect it to withdraw to an available space in my inventory. Maybe a right click could be mapped to do that, in which case we'd just need a highlight that can be moved with a key mapped button press. Even when using a keyboard I'd want to use the num pad keys for that.

In any case, for a game like this, you are definitely going to have a large group of people who would want to sit back with a gamepad and play comfortably.  It doesn't seem like it would take much work to go that extra step either.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#112
