### ISSUE TITLE
USER ISSUE: Stuck inside a players building

### ISSUE THREAD

**Issue by ECO34RT** [StrangeLoopGames/EcoIssues#7337]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Log off close to a players building
Log back on.

**Expected behavior:**
I expected to log back into the game outside a players building where I was standing at the time

**Actual behavior:**
I spawned inside a players building instead

**Comment by metachronism** [comment]
working as intended, afaik.  seans tweaked this a bit with /unstuck command
