### ISSUE TITLE
Prickly Pears are not pickable like huckleberries.

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#734]
You just can't pick them, man.

**Comment by metachronism** [comment]
Ferns should also work this way

**Comment by keegan-o** [comment]
Alright I set prickly pear growth curves to be the exact same as huckleberry in terms of when they appear and disappear...

**Comment by keegan-o** [comment]
I think this is a simple thing that should be fixed for alpha 6. I imagine it's a pretty simple code fix? Now that the curves are exactly the same as huckleberries, whatever code exists to set them to a specific age for huckleberries should work for these, as opposed to deleting the block.

**Comment by MarjieAVolk** [comment]
Ooh I figured out how to do this!  I'm gonna do it!

**Comment by MarjieAVolk** [comment]
So I set the values for prickly pears to match huckleberries - now they look like this after I pick them:
![image](https://user-images.githubusercontent.com/23460210/30186464-87a0cf9c-93da-11e7-9757-4b6f97aa9edb.png)

(The tufts on the ends of the fruit are floating in mid air)

**Comment by keegan-o** [comment]
I'll fix that in the mesh and texture

**Comment by keegan-o** [comment]
committed it, with your code and my art, we can now hope that: Prickly Pears are Properly Pickable!
