### ISSUE TITLE
Server error with no log written locking game then machine hardware

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7340]
Server error with no log written locking game and forcing CPU to 100%.  In turn this totally locks up the hardware and a hard reboot is required to allow server to function.  Have tried recovering from backup, removing all mods, disabling stats and writing or laws,   

https://www.dropbox.com/s/t3cpvr9btq57w6x/PamBigWorld_db_in_use_crashs.zip?dl=0

**Comment by metachronism** [comment]
could not repro this with 7.4.1
