### ISSUE TITLE
Forum Register/Login Issues and Excavator Issues

### ISSUE THREAD

**Issue by vbcji** [StrangeLoopGames/EcoIssues#7341]
![unbenannt](https://user-images.githubusercontent.com/38613613/39094567-b707fe40-4631-11e8-8a7b-28f0d953bb8c.png)
hello, 

I have discovered the following two mistakes. 

1. I cannot register myself (all the same with which browser). 
If I I register anew there originates a mistake, I should want to log in me then it does not go. 

2. The excavator has problems 
2. 1 I become I the shovel if turns, away tele-ported. 
2. 2 The shovel of the excavator disappears and flies by the area 
2. 3 Of the excavators Flippt often found very fast and very simply from inexplicable ones. 
2. 4 The excavator disappears in nothing why also always 

Unfortunately, I can make off no video 
If they excuse because of my bad English I have written with a translator. I become the original into German also here post. 

____________________________________German_________________________________________________________________
Hallo, 

Ich habe folgende zwei Fehler entdeckt..

1. Ich kann mich (egal mit welchem Browser) nicht registrieren.
Wenn ich mich neu registriere entsteht ein Fehler, sollte ich mich einloggen wollen geht es dann nicht.

2.  Der Bagger hat Probleme 
 2.1 Ich werde wenn ich die Schaufel schwenke, weg teleportiert.
2.2 Die Schaufel des Baggers verschwindet und fliegt durch die Gegend
2.3 Der Bagger Flippt oft sehr schnell und sehr einfach aus unerklärlichen gründen.
2.4 Der Bagger verschwindet in das nichts warum auch immer 

Ich kann leider kein video davon machen
Entschuldigen sie wegen mein schlechten Englisch ich habe das mit einem Übersetzer geschrieben. Ich werde das Original in Deutsch auch hier posten.

**Comment by GophTheGreat** [comment]
For the forum issue, send an email to support@strangeloopgames and I can address that for you.

**Comment by SeanAtr0n** [comment]
guess the remaining excavator issues we are aware of however it is possible to use without triggering those problems so reducing priority

**Comment by SlayksWood** [comment]
Checked on 8.1. Wasn't able to reproduce, seems fixed.
