### ISSUE TITLE
Dissappearing room

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7342]
According to my room report, I have fewer rooms than I have built.

I have a four story apartment complex, with each of the four rooms on each of the four floors. If I go through each of the rooms and pick something up and put it down again, the SP value of my house will fluctuate as the ideal rooms get removed.

Can provide save for further demonstration but do not know if it is a known bug.

**Comment by SlayksWood** [comment]
merged with #12780
