### ISSUE TITLE
SUGGESTION: Price(s) of item in tooltip

### ISSUE THREAD

**Issue by XsExcess** [StrangeLoopGames/EcoIssues#7343]
**Version:** 0.7.3.3 beta

**Detail:**
Pretty much the only thing missing right now from the tooltips is the ability to check prices of indavidual items, that would be an excellent addition. For sanity sake it could be limited to cheapest/most expensive 3 for example, with the ability to click for a marker or even a detailed shop list just for that specific item (which may help reduce lag on Y).

**Comment by ecoemmeck** [comment]
This actually used to be included in the tooltips in the alpha version of the game I believe it was rather helpful to easily find stuff for sale

**Comment by MarjieAVolk** [comment]
Yeah it got lost when we redid the inventory system if I recall, got left tagged as needing re-implementation and it never got it.

**Comment by D3nnis3n** [comment]
This has been fixed for a long time.
