### ISSUE TITLE
[Server Issue] Cannot set admin permissions

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7345]
I created a test server within 7.3.3 and set myself as admin in the users.eco file like so:

> "Admins": {
>     "$id": "4",
>     "System.String": {
>       "$type": "System.Collections.Generic.List`1[[System.String, mscorlib]], mscorlib",
>       "$values": ["Elliander"]
>     }
> 

and in the game I was able to use admin commands. The only thing that didn't work is the white list. Even white listed, I still have to type the password. (although on the plus side, now the password window comes up when clicking continue)

Then I upgraded it to v0.7.4.0-beta-staging-b79d89de and these settings were ignored. I don't have any admin rights and can't give myself any. 

I double check the EcoServer GUI under Users > Config > Admins and I see my name there, but it doesn't seem to do anything.

**Comment by elfl0rd** [comment]
not name.
Steamid64 or SLGid.

**Comment by metachronism** [comment]
as soon as you get one admin in game, you can use the in-game commands (/admin etc) to grant additional admins
