### ISSUE TITLE
USER ISSUE: Stump is invisible I think.

### ISSUE THREAD

**Issue by BizKwikTwist** [StrangeLoopGames/EcoIssues#7346]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
I chopped at a stump and it is gone but it seems like it still has collison.

**Expected behavior:**
It should have completely disappeared.

**Actual behavior:**
It still has collision and shows that I can chop at it, yet it is gone.

**Comment by Hagigamer** [comment]
I had the same issue with several stockpiles yesterday. emptied and then removed stockpile, but collision hitbox was still there. restarting the client fixed it for me, but it kept re-appearing with new stockpiles.

**Comment by Nanders** [comment]
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4908
