### ISSUE TITLE
[Suggestion] Have atmosphere and meteor scale outward with world height

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7354]
I've been playing around with trying to generate a super tall world, because I like mountain ranges, and loved how the land stretches upward from the same seed with a taller map.

With a world size of 372x372, a height of 140 (or 372x372x140, ignoring depth) seems to be the max right now, and everything looks OK at such scales, but by reducing the world size I can increase the height.

I started to see some pretty weird things the higher I went. At a world height of 200 the meteor ends up flying through mountains. I actually had it fly through my character once. I wonder how the laser animation would function in such a case.

When I tested higher still, things got REALLY weird. This is what it all looks like - during day - on a 200x200x400 map we see this:

![200x200x400_server_map](https://user-images.githubusercontent.com/15022396/39151595-4880909c-470b-11e8-9601-31bc8dbddf28.jpg)

Halfway up a mountain:

![200x200x400_partway_up](https://user-images.githubusercontent.com/15022396/39151599-4ca30196-470b-11e8-8e39-e60503c3a4a4.jpg)

Top of a mountain:

![200x200x400_might_be_too_tall1](https://user-images.githubusercontent.com/15022396/39151633-6ac50fb6-470b-11e8-8d63-47dbb0951e8e.jpg)

![200x200x400_might_be_too_tall3](https://user-images.githubusercontent.com/15022396/39151958-56bd7368-470c-11e8-9d5e-3f4bca82af3a.jpg)

It's strange, to say the least. 

The other issue of course is the view distance. The higher you are the harder it is to load certain things. Would be nice if there was a way to make more distant objects load a lower quality image so that more can load, and for the game to have maybe some kind of haze beyond a certain point so you don't get things half loading.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#386
