### ISSUE TITLE
Opening UI is too slow

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7357]
_________________________________________________
Reports:
http://steamcommunity.com/profiles/76561198036748973/recommended/382310/
https://steamcommunity.com/profiles/76561198013144150/recommended/382310/

- When I open up a chest or anything really, it takes around 10 seconds for the UI to appear. Just one long 10 second wait while everything is frozen. Jesus I'm not streaming a movie I'm just viewing my inventory. This makes me want to keep interaction with anything that opens a UI to a minimum.

**Comment by sonst-was** [comment]
I can confirm this issue, imo it seems to be connected to the amount of other storage chests being around because their content has to be pulled as well.

Maybe it would be possible to pull the content of the opened chest first, then the content of linked chests and only afterwards the contents of other chests.

**Comment by Ericinator** [comment]
I'm also experiencing this issue. Or I was (I wrote the initial comment. Sorry about the snotty childish tone).

This seems to be related to the disk the game is running from. I was running it from an old external drive at the time. All UIs took around 20 - 30 seconds to load. I then tried the game from an SSD and the UIs now load in 2 seconds max.

The number of linked storage containers seems to be irrelevant (I tried up to 12).

Maybe something is being cached to disk before displaying the UI.

**Comment by sonst-was** [comment]
> The number of linked storage containers seems to be irrelevant (I tried up to 12).

I didn't meant the amount of linked storages but the amount of storages nearby (the ones you can link). In my experience the content of those chests is displayed too. My game is installed on an internal HDD, but I can try to install it on my SDD too.

**Comment by johnkslg** [comment]
Lowering priority as it doesnt break the game, but will definitely be taking a look at improving this in the near future.  Thanks for the report.

**Comment by SlayksWood** [comment]
The problem is still when you have an excessive amount of storage. But we have a lot of improvements. Ui open fast and load storage after opening. It drops FPS(another issue) but it doesn’t take 10 seconds.
Seems fixed. We also have planned improvements in UI in 0.9.0
