### ISSUE TITLE
 SUGGESTION: Show Coverage of Storage

### ISSUE THREAD

**Issue by Salorano** [StrangeLoopGames/EcoIssues#7359]
Hello,
I allways try to build in spaces beetween my buildings, Storages, Items and so on. It would be nice to have a indicator(on and off by a switch) in which you can see how is the range of a building. As example I have a reffinery and this should put the items in a box and from this box to the electric fabric. The buildings are to far away and I need to debuild and rebuild. And move the storage unitl I find "the golden middle". With and indicator I can put the storage at the Middle between the 2 maximun ranges and everything would be fine.
Thanks and cu
Star

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#110
