### ISSUE TITLE
Trees make no sound as they fall

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#736]
Lets make this auditorially exciting.  Big whoosh, crash, birds and wildlife freaking out around you.

**Comment by metachronism** [comment]
They do make a sound, but I do think it needs to be louder and/or considerably more dramatic

**Comment by Nanders** [comment]
This is in the works, have plans to go out to the forest and record actually felling some trees.

**Comment by metachronism** [comment]
nicks added this by now
