### ISSUE TITLE
SUGGESTION: 2-D Minimap

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7362]
From a Steam comment (https://steamcommunity.com/app/382310/discussions/4/3288067088119203125/):

"The minimap world makes you lag on big worlds and even small ones please optimize! 
It would be nice if their was a 2d minimap that was less intensive for bigger maps maybe?"

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#109
