### ISSUE TITLE
Brick blocks not displaying correctly

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7363]
From a Steam comment (https://steamcommunity.com/app/382310/discussions/4/3288067088117724782/):

https://steamcommunity.com/sharedfiles/filedetails/?id=1366419888

Reload of the game not fix it, but i ask for a server restart.
This problem is only with brick-blocks. When i set the normal block or the pillar block (1 height) next to a full block.

https://steamcommunity.com/sharedfiles/filedetails/?id=1367757050

**Comment by metachronism** [comment]
closing as dupe of #4286
