### ISSUE TITLE
Carried objects unsmitable

### ISSUE THREAD

**Issue by gustafsonsean** [StrangeLoopGames/EcoIssues#7364]
Some objects can't be smited with the admin tool, these seem to be the carried objects such as rocks.

**Comment by lightdrawn** [comment]
Pick them up and place them on the ground, then you can delete them, I think it's not possible to delete them as long as they physics objects. But there is a Mod to remove loose stones.

**Comment by elfl0rd** [comment]
@D3nnis3n fixed.

**Comment by D3nnis3n** [comment]
Indeed.
