### ISSUE TITLE
Rocks teleporting to surface

### ISSUE THREAD

**Issue by gustafsonsean** [StrangeLoopGames/EcoIssues#7365]
When using the excavator, the mined rocks will occasionally teleport to the top of the surface--similar to a player typing /unstuck. This also happens when hand mining (Not to the extent of the excavator)--the rocks near the stone block being mined will appear to "jump" as the stone block breaks. Sometimes they appear on the surface.
![wildrocks](https://user-images.githubusercontent.com/17696697/39165519-677bd86e-474a-11e8-8e24-da5060d05ebc.png)

**Comment by ZehTed** [comment]
they are also floating in the air, mostly above water

**Comment by SlayksWood** [comment]
still an issue
![image](https://user-images.githubusercontent.com/45708377/55719758-b0439200-5a07-11e9-8298-7bc2f3d54b1d.png)

**Comment by redwyre** [comment]
This happens when the rubble falls through the terrain, it happens to me about 50% of the time when breaking large rubble into two pieces.

**Comment by D3nnis3n** [comment]
I'm giving this my tag, cause this is insane.

**Comment by SlayksWood** [comment]
Still an issue 8.2.0 Staging-3
![image](https://user-images.githubusercontent.com/45708377/57285618-424cc200-70bc-11e9-8854-c8fdbeafc8cf.png)

**Comment by Praefator** [comment]
Issue seems to be most common when yellow debris is created and/or broken to green debris. Having lucky break (mining 6) reduces it a great deal in most cases
