### ISSUE TITLE
SUGGESTION: Water usage and computers

### ISSUE THREAD

**Issue by AnteThePie** [StrangeLoopGames/EcoIssues#7369]
If i got everything correct, the game is supose to be as close to real life as possible ( With logics and so on). Will we not have water usage and water wells etc. At least I need to drink to not die but i might be wrong. 

Computers would be a great implement if you would add trains, if computers were added make a display to an tv/screens. This could be used in both multiplayer and single player. 

Singelplayer: Could be used for a remote controlled train for your supplies, could also be used as a way to make hightech/ Future technoligy in the storage department of things. 

Multiplayer: The screen could be used for digital maps to see where your supplies are ( If you ordered something from a shop/friend or some sort) to see of anything would happen in the way. This could also be used to see when your train would come to the station etc. 

Computers could also be used to make a "Smart shop" like Ebay or amazon for players. This would make a persons day alot easier for buying and selling cargo/products. 

Thank you for your time Devs!

**Comment by AnteThePie** [comment]
Ohh god sorry i jusr realised that we auctally so just ignore that but the rest would be great

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#108
