### ISSUE TITLE
USER ISSUE: after shown UI, skill window opens too.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7370]
**Version:** 0.7.4.0 beta staging-68e3874b

**Steps to Reproduce:**
1) press Alt+Z to hide UI.
2) Press Alt+Z to show it back.

**Expected behavior:**
Only Show UI.

**Actual behavior:**
Show UI AND open skills window.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/4485

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/10182
https://github.com/StrangeLoopGames/EcoIssues/issues/10317

**Comment by D3nnis3n** [comment]
Funnily, i cannot reproduce this, but i'll merge the issues.

**Comment by elfl0rd** [comment]
It still happens( I can record video if needed
