### ISSUE TITLE
SUGGESTION: Framed glass window type without the frame

### ISSUE THREAD

**Issue by UnknownViper** [StrangeLoopGames/EcoIssues#7371]
Currently normal glass, which is nice and without frames for those big panorama windows, are tier 2. Framed glass is tier 4, where the wall and window type are identical (as far as I can see). Framed glass also means you can't do those nice panorama windows that you can with glass, as you get the framing there which ruins the whole thing aesthetically.

My suggestion is simple: Make the window type for framed glass be similar to glass, but a tier 4 equivelant. Perhaps a slightly changed texture to better tell them apart.

I think this makes a lot of sense to do, as there's no reason to have a window and wall type be the same, and because we don't have a nice panorama window option above tier 2.

**Comment by keegan-o** [comment]
I totally agree about the aesthetic vs. tier being a big problem for creativity in the game-- at the very very least you can at least count on there eventually being higher tier stone and wood sets. I'll read your forum post too and we'll definitely be considering ways to make it better!

**Comment by UnknownViper** [comment]
Thanks for the replies, @keegan-o! Very happy to read that higher tier stone and wood sets will come at some point. :)

Keep up the good work!

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#107
