### ISSUE TITLE
Game throws eco.exe error then crashes.

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7372]
From a Steam user. https://steamcommunity.com/profiles/76561198359450098/recommended/382310/

"Game doesn't even work. Just crashes. I'm running it on the latest version of Windows 10 with a GTX 1080, just gives the "eco.exe" error and then proceeds to crash. Do not waste your money, hoping I can get a refund but probably not."

Asked them to send crash file.

**Comment by SeanAtr0n** [comment]
crash files are usually pretty useless, we usually want the player log from:
`%APPDATA%\..\LocalLow\Strange Loop Games\ECO\output_log.txt`

single player games all start with -nogui so thats normal, don't see any useful error message in that second comment

**Comment by ShaydenMac** [comment]
Ah, okay. Thanks Sean.

**Comment by ShaydenMac** [comment]
More crashes. This one is from a FB user. 

![2018-04-27_1349](https://user-images.githubusercontent.com/36867473/39384580-2bb32780-4a22-11e8-92af-5bf1473fb3b3.png)





[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1956628/error.log)
[error2.log](https://github.com/StrangeLoopGames/EcoIssues/files/1956629/error2.log)
[error3.log](https://github.com/StrangeLoopGames/EcoIssues/files/1956630/error3.log)
[error5.log](https://github.com/StrangeLoopGames/EcoIssues/files/1956631/error5.log)
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1956632/output_log.txt)

**Comment by metachronism** [comment]
cant really do much here
