### ISSUE TITLE
Remote server stops working properly when someone accesses law page 

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7373]
Via subreddit: https://www.reddit.com/r/EcoGlobalSurvival/comments/8eiqhw/my_remote_server_always_stops_working_properly/

"Hi folks, my problem is as described in the title. I run a server hosted by pingperfect.com and my group has so far done playthroughs on two different worlds -- one vanilla, one with a few mods. We've come to realize that it has a significant problem: if anyone accesses the law page (the website) from the game, the server will become very laggy and kick some people and refuse to let them back on until the server is restarted. This does not occur if the website is accessed externally, although then you can't propose any laws or vote anyway. This also isn't a problem when I test it on a local server.

At first I thought this was a result of the game being buggy, but I have had the notion recently that this might not be anyone else's experience. I'm going to be getting a new server soon for unrelated reasons. Should I expect this to still be a problem, or should I consult tech support if it happens with the new one?"

**Comment by mindforger** [comment]
there have been collected many intel/reports (sorry i am missing the right word atm) that hint's into the direction to disable statistics or increase the timeout value for statistics above 2000 to improve the performance

**Comment by dandrewrichardson** [comment]
We've had this problem on our server as well. We've had to set up the server to reboot once every 6 hours, and probably need to up that to once every 4. 

Generally, we know it's incoming when users start getting disconnected for "Inactivity." If we then try to log back in, it will be stuck on "Entering world..." and never let us in, though anyone still in the game can see our avatars and get the message that we've logged in (and logged out when we eventually kill the process on our local computer).

Not everyone gets kicked at the same time, it usually happens over about 15-30 minutes. But eventually, we're all kicked and nobody can log in until server reset. We have implemented both suggested fixes (I think, I'm not the server admin but this is what we were told), but this continues to happen. Perhaps less frequently, not sure.

Server is also PingPerfect, for what it's worth.

**Comment by ShaydenMac** [comment]
Via Subreddit user:

"Turn off statistics, things seem to be a lot more stable with them off. The web server part of the game is just not stable and accessing it with statistics on will either freeze the server or, in my experience, prevent new players from logging in. **Once stats were disabled all issues vanished**."

**Comment by SeanAtr0n** [comment]
The problem is definitely related to stats. I found one request in particular that was spamming stats from the front page and removed it for the next hotfix build. That should reduce the impact of accessing the webpage significantly but I doubt it has solved the stats issue completely. 

We also added some fail-safe checks to prevent the stats tab from freezing so it should be safe to enable stats and if the issue comes back you can disable stats w/o restarting.

**Comment by SeanAtr0n** [comment]
Haven't heard much about this issue since the last fix so i guess we can close this
