### ISSUE TITLE
Linux Play : Don't Start solo game 

### ISSUE THREAD

**Issue by liberodark** [StrangeLoopGames/EcoIssues#7375]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Could not start server: Object reference not set to an instance of an object
```

**Comment by SeanAtr0n** [comment]
Linux currently requires manually setting up a server for solo play:
http://ecoforum.strangeloopgames.com:4567/topic/2984/setting-up-a-eco-server-on-ubuntu-other-linux-is-probably-very-similar

The single player buttons will disappear in linux/osx in 7.4
