### ISSUE TITLE
Opening Steam overlay while loading a single-player world bricks game

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7378]
You get stuck on the gear icon.

Force-quitting the game makes steam think the game is still running, and requires a steam restart to resolve.

**Comment by Nanders** [comment]
Only happens sometimes

**Comment by BlazeGuy2** [comment]
The Steam restart isn't necessary, an EcoServer.exe is left running, which needs to be closed.

**Comment by metachronism** [comment]
seans fixed the server still running issue - other I could not repro
