### ISSUE TITLE
Server not updating with new Difficulty.eco file

### ISSUE THREAD

**Issue by ThePickleTickle** [StrangeLoopGames/EcoIssues#7379]
Only partial elements of the difficulty file are being implemented to the world when i try and update it. i have restarted the server multiple times to try and update the difficulty with no change

for example:
SpecialtyCostMultiplier- changed from 1 to 0.5 **(worked)**
SkillPointPerCrafttime: - changed from 0 to 1 **(didn't work)**

For craft time i tried an extreme to see a visible change in crafting as when i tried #0.0003 or other recommended settings, there was no clear change and nothing in the chat log when completing crafts.

**Comment by voguhl** [comment]
isnt it SkillPoint**s**PerCraftTime
