### ISSUE TITLE
SUGGESTION: Soil-sampler – not farmers best friend

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#7380]
The soil-sampler (v7.3.3) shows a very scientific window with lots of text and numbers. It’s hardly useful for drawing a decision from it.
Instead I could imagine a more graphical presentation, where the 4 essential parameters are displayed as bar-graphs with an under- and over-matching portion for that plant. The bars can be intuitive coloured or just a simple scale. In short words – a speaking information for a fast decision.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#106
