### ISSUE TITLE
Webbrowser not starting unless 'run as admin', does not display error

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7381]
It should say what error occurred.
![image](https://user-images.githubusercontent.com/3536496/39209505-cb1a0f1a-47ba-11e8-9ce4-01bd5293a29c.png)

**Comment by johnkslg** [comment]
User fixed by running as admin, this shouldnt be required.

**Comment by SeanAtr0n** [comment]
there is a popup if you aren't an admin that you have to say yes to
