### ISSUE TITLE
USER ISSUE: No Mushrooms

### ISSUE THREAD

**Issue by ColWindsor** [StrangeLoopGames/EcoIssues#7382]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
In order to research the farming specialization you need spores from the Crimini Mushrooms.  I have looked all over this world for the past 3 days and have not found any.  The heat map doesn't show any and when I went to where the highest yield would be i find nothing.  Since i can't dive down under the water i can't check the yield areas in the ocean.

**Expected behavior:**
Some area where Crimini Mushrooms exist so i could get spores to learn the farming specialization

**Actual behavior:**
Heat map doesn't show any spots and the yield spots for them don't have any mushrooms either.  

I don't know if this is really a bug to be honest or maybe just a flaw in the world creation process.  Though if it is a bug, now you know that it exist at least 😄 .

**Comment by Elliander** [comment]
I encountered something similar in one world. The mushrooms never did appear on the map, so I looked at the marsh habitat and found that the game happened to overlap the marsh biome with the ocean, so found a remote tiny island with a single parcel next to a desert which has the marsh biome and was able to pick enough to start farming.

Unfortunately, to get enough spores to unlock farming I also inadvertently pushed the crimini mushroom to extinction and there was no way to get it back.

I have noticed that, when generating a new world from the same configuration files as an old world, that the biomes are randomly situated - so one location that was a desert in one build ended up being a forest in another build. A possible solution would be for the game to make sure that a minimum number of skill required items spawn in any world by ensuring a minimum geographic coverage of certain biomes. Species shouldn't be missing from a world on creation, or be too few to learn a skill without causing extinctions.

**Comment by ShaydenMac** [comment]
Via Forum: http://ecoforum.strangeloopgames.com/topic/4597/fehlende-pflanzen

"Hello,

We have the problem that there are no mushrooms in our world. 
This we need to skillen cooking further :(

Have read that even plants that do not exist at some point grow, is that really? 
If so, can you possibly adjust that they grow faster? 
Would be nice if there who could help.

We thank you in advance in advance :)

lg"

**Comment by metachronism** [comment]
craig has fixed this
