### ISSUE TITLE
32 bit support is not complete

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7384]
You cannot play single player in 32 bit because the server doesnt run in 32 bit.
We need to let players know this in the system requirements.

**Comment by Nanders** [comment]
Do we just need this listed in min requirements, or is there additional action needed

**Comment by metachronism** [comment]
IMHO we should drop 32bit support, would be a bit of a challenge to get the server memory down to run in 32bit, unless running only very tiny worlds

**Comment by johnkslg** [comment]
Closing as dupe
