### ISSUE TITLE
Currency Duplicated

### ISSUE THREAD

**Issue by Darklord6229** [StrangeLoopGames/EcoIssues#7388]
I do not know how this happened but the server duplicated our currency. We are working on a brand new server running 7.3.3. Here is a picture of what I am talking about https://i.imgur.com/aIucCq0.png. As you can see they are the exact same names but one has currency in circulation and one does not. I have restarted the server and it has persisted. I wish I knew how this happened so we could reproduce it for bug testing but I honestly have no clue. When I placed the mint and typed out the currency it just created it twice. With that being said is there a way to delete the duplicate currency or are we just stuck with the two currencies using the same name. Anyways thank you in advance and let me know how I can help with figuring out this bug.

**Comment by D3nnis3n** [comment]
No further reports of this since this.
