### ISSUE TITLE
Landscape appearing and disappearing when I walk near

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7389]
![animx](https://user-images.githubusercontent.com/3536496/39221745-b239c822-47ed-11e8-9baf-71d2783a8c89.gif)

**Comment by johnkslg** [comment]
Its a 20x20 world btw...

**Comment by metachronism** [comment]
yup, working as intended on small worlds

**Comment by metachronism** [comment]
fwiw 20x20 is only 2x2 "chunks" for rendering, so you'll see this all the time as it wraps on a a world that small
