### ISSUE TITLE
Remove specular when rendering worldlayers on minimap

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#739]
![image](https://cloud.githubusercontent.com/assets/3536496/19826691/61cda71c-9d46-11e6-9c9f-62a3d9171a48.png)

The material is shiny, making it very hard to get the coloring info when its rendered.

**Comment by johnkslg** [comment]
The center for example is meant to be very red but appears white.

**Comment by metachronism** [comment]
Its not really specular, its blowout due to using the emissive channel.

We should swap diffuse textures or look into customizing it a bit more, since I dont think emissive will ever look exactly how we want - doing a simple alpha blend will probably work better.
