### ISSUE TITLE
Ability to lock Ctrl key when diving or the ability to craft weights to hold us down when in water

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7393]
From Forum User: http://ecoforum.strangeloopgames.com/topic/4481/going-under-water/2

"How if clicking Ctrl would lock diving and clicking Ctrl second time or Space would release it?

Or more role-play wise, let us craft stone belts that hold us under water while we wear them. :)"

**Comment by Nicolausi113** [comment]
Yes!
Not the best solution as it is, hanging on keyboard like spastic.
Or just a possibility to remap the diving-key to another one.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#105
