### ISSUE TITLE
Allow for cosmetics on buildings/materials

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7394]
From Forum Member: http://ecoforum.strangeloopgames.com/topic/4518/the-new-housing-skill-system-vs-freedom-of-creativity

"The new housing skill system vs freedom of creativity  

The problem

The new housing skill system is definitely an improvement over the old one. It's easier to understand (the old one was not very transparent) and it forces you to produce higher tier building materials, which in turn puts a bigger dent in the world's eco system through resources needed and pollution created. This is definitely a welcome change in my opinion.

It does, however, ruin a different and important aspect of the game: The ability to choose what your house looks like - what it’s built from - as you're now forced to upgrade to higher tier building materials to increase your housing skill bonus. Basically these two systems are mutually exclusive.

The question is: How do we maintain the gameplay impact of the housing skill system change in 7.0.0, but bring back the freedom to choose how your house looks - what it’s built from?

The possible solution

I believe I've found a good solution for doing this, but I am putting this here to hear what people think, as well as making SLG aware. It might even spark an even better solution from someone else.

I went through a good few ideas (none of which were really any good) until I landed on this one.

A (4 actually) new building block type is introduced. You use this to build your house like you would with any of the current building block types. The difference is that this is a tier building block type, which allows you to build any block material type (ie. bricks or glass) that you have currently unlocked.
This new block type is created from already made building block types. So for instance to get a tier 2 type block you would craft it from bricks (or another tier 2 material block).

A tier 2 block type allows you to build tier 1 and 2 building block types (that you have unlocked).
You would select the type of material you want to build, by selecting it in a manner much like the current building block types (window, wall, stairs, column etc.), allowing you to create a tier 2 hewn log room, if you want.

This gives people back the freedom to have their house look like they want, while maintaining the new housing skill system and its progression.

I imagine that crafting these new blocks won’t take a lot of time, but probably require an extra ingredient or not be a 1:1 ratio conversion. This is a balancing issue that I’ll leave up to SLG, if they choose to implement this solution.

Put in another way:

Craft framed glass like you would now.
Convert the framed glass to the new tier 4 (since framed glass is a tier 4 building block material) building block using the kiln.
Use the new tier building block to make any building block material type that you have unlocked (hewn, mortarted stone, glass, bricks, corrugated steel and so on), which will all be tier 4.

A potential issue

One thing that is of concern with this is that you can basically create bricks from lumber, for instance. Since both are tier 2 materials, it'd mean that you could get bricks by creating this new building block type out of lumber.

One solution to this could be that if you want to create this type of building block from lumber, it would also require a brick to do. Of course for this example tier 2 has other tier 2 material types, so this would again be a balancing issue across the tiers.

This has the interesting side effect that to do this you're more reliant on each other, assuming the person making the lumber doesn't already have the ability to also make bricks. This opens up for another trade venue and transportation requirements.

In closing

I hope this makes sense, if not let me know and I will try to clarify! :)"

**Comment by Elliander** [comment]
I like this idea. I, for one, actually prefer the look of stone roads over asphalt so being able to use an alternate skin based on some other materials could help with more than just inside walls. 

Maybe just treat it like wallpaper and/or siding? So you'd build the normal wall, and then you can make a "skin" from the alternate material? Which of course could be bought or sold. So using your example, you'd build your wooden house normally and then cover it with brick veneer like so:

![brick-veneer](https://user-images.githubusercontent.com/15022396/39279587-a9dd1fda-48bf-11e8-82a9-140257d277ff.jpeg)

and then, when the game checks for the minimum number of blocks of a certain tier, it would see the veneer as counting as brick for those purposes and ALSO see the stone block that is part of the wall behind it.

To make it easier, veneer and/or wallpaper could be something other than a carried item so you can hold it at the same time as a construction material.

This approach could allow for other options as well, such as dyed wood. Maybe you could make dyes from plant fibers and stain the siding before it goes up to get some interesting colors.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#104
