### ISSUE TITLE
Better fishing/hunting tools

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7395]
From Forum Members: http://ecoforum.strangeloopgames.com/topic/4500/better-hunting-fishing-tools/2

"
 lisaknittycsi posted 4 days ago  0 
I wasn't sure if there was any plan to make better hunting and fishing tools? All other tools you increase from wood, to stone, to iron to steel. But not the bow or the fishing rod.

Just a thought.

  Prongs posted 2 days ago  1 
I'd like to see:
-Spear for hunting and/or fishing.
-Cross bow for hunting (more damage but slow reload)
-Rifle

  tuvermage posted a day ago   0 
I'd like to see snare traps, I can hunt Elk and buffalo easy, but I suck with it come to the smaller animals."

**Comment by ShaydenMac** [comment]
Via Forum member: http://ecoforum.strangeloopgames.com/topic/4541/hey-guys-you-should-revamp-the-entire-fishing-skill-tree-and-usefulness

"coco2046 

Right now its ok but doesnt have many options and fishing with a hook/stick doesnt work well most of the time. It would be nice if we had baits, worms, lures, traps, crab traps! etc and also boats to use on the water, with engines, differrent fish and sharks deeper waters, enticing reasons to go deep sea fishing, scuba gear/pole fishing/spear gun? oxygen tanks? haha. ok maybe too much. but its cool, lots of potential. def make it so you have more high level recipes so we can continue to be fishermen later in game, right now everyone abandons it mid game for higher level recipes using traditional hunting, etc. Anyways cool, this game is amazing! Excited to see whats next. Thanks!"

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#103
