### ISSUE TITLE
Mapping the world as you explore it

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7396]
From Forum Member: http://ecoforum.strangeloopgames.com/topic/4509/map-the-world-as-you-explore-it

"Map the world as you explore it?  

Red Gonzalo posted a day ago  0 
Maybe having a world map only of the areas you had explored, would add more mystery to it and push the need to explore it could be a good idea. Possibly only having tabs like pollution being available through technology (i.e. planet scanning)"

**Comment by Elliander** [comment]
Could make for a nice server option: Fog of War

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#102
