### ISSUE TITLE
Write & Read stat database error

### ISSUE THREAD

**Issue by PapaHarni** [StrangeLoopGames/EcoIssues#7399]
![eco error](https://user-images.githubusercontent.com/6943360/39269043-db683082-48d1-11e8-842b-a9564f643bf4.png)

Hey guys,
i think but i don't know that to 100%, the error starting if a user cancel the loading of the website stats.
What can i do to stop it? It breaks the server all the time..

Sincerely,
PapaHarni

**Comment by metachronism** [comment]
fixed 7.4.0 release
