### ISSUE TITLE
Contracts are padding funny due to TableLayout problem

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7400]
Somehow the Items and Still To Add sections are way larger than then they need to be, didn't see anything strange with padding settings.  This is a problem on a few different contract clauses.
![image](https://user-images.githubusercontent.com/3536496/39270724-c1128de0-488b-11e8-9d33-23cfa970a0a7.png)

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/39501000-3ab534f0-4d6d-11e8-9922-cce12b3ccb50.png)
Also this problem

**Comment by gabeux** [comment]
Still occurs on Add/Remove Blocks and Harvest Field clauses

**Comment by MarjieAVolk** [comment]
Fixed.  There was an issue where once you set any eg. LayoutElement values on an object with a TableRowLayoutGroup, you could never decrease them ever again, only increase them.  It was a very interesting loophole.  Copying and pasting the object in the editor seemed to reset the values.  I am sure now that I have seen this before while working in the editor, and it was making me insane.
