### ISSUE TITLE
User fell through world, got stuck, had to restart

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7401]
https://drive.google.com/open?id=12E9SBedtzVZnG4co2X8z8Qgg6mNn61nf
Also played an earsplitting sound

**Comment by johnkslg** [comment]
Reported by Jewseph

**Comment by SeanAtr0n** [comment]
Duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/7293
