### ISSUE TITLE
User chunks failing to load frequently

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7402]
![image](https://user-images.githubusercontent.com/3536496/39273895-153e16c4-4895-11e8-8fb0-ff107f2e8aa5.png)
![image](https://user-images.githubusercontent.com/3536496/39273904-19e82246-4895-11e8-9e52-d0e6729a37f3.png)
![image](https://user-images.githubusercontent.com/3536496/39273911-1ef70d92-4895-11e8-8d15-55fdc43071fa.png)

**Comment by SeanAtr0n** [comment]
description? error log? not a very useful report...

**Comment by johnkslg** [comment]
There was nothing useful in the error log unfortunately. He saw it just walking around.

**Comment by johnkslg** [comment]
Closing as we have no repro case atm.
