### ISSUE TITLE
Saves can be corrupted

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7405]
https://drive.google.com/open?id=12zvG4T97cpzGVjjt_KriWCdvdr6E4pQV
Here's an example of a corrupted save, which has a subset of the folders it should in the zip and an 'incomplete archive'

**Comment by johnkslg** [comment]
Filed by user Jewseph

**Comment by johnkslg** [comment]
Added handling for this, backups will be restored. Still need to figure out how they're getting corrupted though, but lowering priority.

**Comment by metachronism** [comment]
NO MORE!!!  we fixed this a while back after a long epic discord fight (which I won, btw.  go me.)
