### ISSUE TITLE
Bring back save game renames and deletes

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7407]
From user request:
![image](https://user-images.githubusercontent.com/3536496/39276221-15209f9c-489d-11e8-8609-593687828fc0.png)
He who deleteth the feature must recreateth it.

**Comment by metachronism** [comment]
dupe of #6984
we actually never supported renames

**Comment by MarjieAVolk** [comment]
Think you linked the wrong bug here
