### ISSUE TITLE
[Suggestion] Allow the entire world to remain loaded in RAM as an option

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#7409]
As a possible solution to objects rotating sideways when you return to them, or some objects not loading in a distant view, maybe there could be an option to allow all the blocks to remain loaded? 

I don't mean to keep track of everything at once - that would really kill server performance - I mean that once an object has been loaded into RAM it remains loaded into RAM until the user goes back and observes it different. 

This would be a major RAM hog idea, but if you have the RAM to spare it would keep from having to reload objects every time you walk away and return.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#100
