### ISSUE TITLE
USER ISSUE: house value

### ISSUE THREAD

**Issue by FatBaconGuy** [StrangeLoopGames/EcoIssues#7410]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
When i extend my house (size/width) the house value goes down to 0. it looks like the house value only stays at my main room, when i make another room the house value dissapears. but if i wall it off the value comes back. but now i have lost all the value, it wont come back whatever i do...

**Expected behavior:**
it should have given me more house value

**Actual behavior:**
instead it takes away all my value.

**Comment by craig-jong** [comment]
I'm going to need some screenshots or a save or something for this.

I'm going to close this since housing sp seems to be working fine, but please feel free to reopen it if you have additional info.

**Comment by FatBaconGuy** [comment]
Its a while ago since ive played eco, probably Works better now, i will try it again later some day. Ill report back if it still is not working 😊

Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Fra: craig-jong <notifications@github.com>
Sendt: Monday, July 30, 2018 8:13:34 PM
Til: StrangeLoopGames/EcoIssues
Kopi: FatBaconGuy; Author
Emne: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: house value (#7410)


I'm going to need some screenshots or a save or something for this.

I'm going to close this since housing sp seems to be working fine, but please feel free to reopen it if you have additional info.
