### ISSUE TITLE
Crash when tree collides with terrain

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7413]
4-23 dump log
Object reference not set to an instance of an object.
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at TreeEntity.CollideWithTerrain(Player player, Vector3i position)

**Comment by johnkslg** [comment]
Also:
Das Zielarray ist nicht lang genug. Überprüfen Sie destIndex, die Länge und die Untergrenze des Arrays.

(The target array is not long enough. Check destIndex, the length and the lower bound of the array.)

   bei System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   bei System.Collections.Generic.HashSet`1.SetCapacity(Int32 newSize, Boolean forceNewHashCodes)
   bei System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   bei TreeEntity.CollideWithTerrain(Player player, Vector3i position)

**Comment by metachronism** [comment]
fixed 7.4.0 release
