### ISSUE TITLE
Chat manager crash

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7414]
Could not parse string "4"
   bei Eco.Gameplay.Systems.Chat.ChatManager.InvokeCommand(String commandName, MethodInfo method, String args, User user)
   bei Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   bei Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)

**Comment by Nanders** [comment]
Do we know what version of the game this came from?

**Comment by Nanders** [comment]
Also if this user was using a mod, because they can use their own handlers now.

With our current handler this is impossible to get unless the command parameter was asking for something other than User, Int, Float, String, or Bool
