### ISSUE TITLE
Crash in WorldLayer tick

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7416]
Indeksen var utenfor matrisegrensen. (The index was beyond the matrix limit.)
   ved System.Array.Clear(Array array, Int32 index, Int32 length)
   ved System.Collections.Generic.HashSet`1.Clear()
   ved Eco.Simulation.WorldLayers.WorldLayerSync.<>c.<Tick>b__11_3()
   ved Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   ved Eco.Simulation.WorldLayers.WorldLayerSync.Tick()
   ved Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   ved Eco.Simulation.WorldLayers.WorldLayerManager.Tick()
   ved Eco.Simulation.WorldLayers.WorldLayerManager.TryTick()
   ved Eco.Simulation.WorldLayers.WorldLayerManager.Run()
   ved System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ved System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ved System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   ved System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by metachronism** [comment]
fixed 7.4.0 release
