### ISSUE TITLE
Double file access when saving

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7418]
Der Prozess kann nicht auf die Datei zugreifen, da sie bereits von einem anderen Prozess verwendet wird.
(The process can not access the file because it is already being used by another process.)
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   bei Ionic.Zip.ZipFile.Save()
   bei Eco.Core.Serialization.DataStore.ProcessQueue()
   bei Eco.Core.Serialization.DataStore.<Run>b__26_0()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()

**Comment by johnkslg** [comment]
Possibly a clue for our save corruptions?

**Comment by metachronism** [comment]
fixed 7.4.0 release
