### ISSUE TITLE
Top level skills need descriptions

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#742]

**Comment by MarjieAVolk** [comment]
None of the skills have descriptions these days /shrug

**Comment by elfl0rd** [comment]
@D3nnis3n hm, looks fixed, but need some info about "what is descriptions" in John case :P

**Comment by D3nnis3n** [comment]
@johnkslg Is that fixed? I've no idea what you mean, as you didn't add a more detailed description *g*

**Comment by GophTheGreat** [comment]
Looks like all of them have descriptions, even the nested ones. Closing.
