### ISSUE TITLE
Crash writing to server console

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7420]
Der er ingen proces i den anden ende af denne pipe.
(There is no process at the other end of this pipe.)

   ved System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   ved System.IO.__ConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   ved System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   ved System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   ved System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   ved System.Console.WriteLine(String value)
   ved Eco.Server.Startup.Start(String[] args)
   ved Eco.Server.MainClass.Main(String[] args)

**Comment by metachronism** [comment]
fixed 7.4.0 release
