### ISSUE TITLE
Crash when eating food

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7427]
Ссылка на объект не указывает на экземпляр объекта.
(The object reference does not point to an instance of the object.)
   в Eco.Gameplay.Items.InventoryChangeSet.ModifyStack(ItemStack stack, Int32 delta, Item newItem, Boolean updateComponents)
   в Eco.Gameplay.Items.ItemStackExtensions.TryModifyStack(ItemStack itemStack, User user, Int32 increment, Func`1 test, Action onSuccess)
   в Eco.Gameplay.Items.FoodItem.OnUsed(ItemStack itemStack, Player player)
   в Eco.Gameplay.Items.Inventory.UseStack(ItemStack stack, Player player)

**Comment by craig-jong** [comment]
Need more context to this or reproduction steps - this obviously doesn't happen every time someone tries to eat food.

**Comment by elfl0rd** [comment]
Looks as old and maybe fixed issue.

**Comment by D3nnis3n** [comment]
Reopen if it reoccurs, i could never ever occur a crash when eating and people on my server were eating a lot.
