### ISSUE TITLE
Mining crash

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7428]
Impossibile caricare il tipo
(The type could not be loaded)
 'System.Numerics.Quaternion' dall'assembly 'System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   in Eco.Gameplay.Objects.RubbleObject.TrySpawnFromBlock(Type blockType, Vector3 position)
   in Eco.Mods.TechTree.PickaxeItem.OnActLeft(InteractionContext context)
   in Eco.Gameplay.Interactions.InteractionExtensions.<>c__DisplayClass0_1`1.<ExecuteUntilSuccess>b__1()
   in Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   in Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by SeanAtr0n** [comment]
usually this means the player's .net version is out of date

**Comment by craig-jong** [comment]
Isn't that something steam handles?

**Comment by SeanAtr0n** [comment]
not sure... we have seen that quaternion complaint before though

**Comment by Nanders** [comment]
Steam only handles installing the redistributables on first launch, I don't think it maintains the install though.
