### ISSUE TITLE
Issue adding server to favorites [7.4.0 #68e3874b]

### ISSUE THREAD

**Issue by lordrasmus** [StrangeLoopGames/EcoIssues#7431]
when adding a server to the favorites list like this

![image](https://user-images.githubusercontent.com/5795036/39316603-d45b2c4c-4979-11e8-9576-fcfd30c8619e.png)

the favorites.eco lookes like this :
 [{"UniqueIdentifier":0,"Description":"gameserver.tangotanzen.de:28501"}]
and the server is always offline and i cant connect

when i add it with the server browser  favorites.eco lookes like this:
[{"UniqueIdentifier":-1264244138805155062,"Description":"Vegane Bio Hippies v0.7.4.0"}]

and it works

but when the server is private it cant be joined because it does not appear in the server browser and it cant be added to the favorites list

**Comment by MarjieAVolk** [comment]
In the final 7.4 release, adding servers by ip address just connects you to them directly, rather than adding them to your favorites (they will show up in the Recents section the next time you go to the join screen).  Doing so should no longer result in a strangely formatted favorite.
