### ISSUE TITLE
Misleading Animal population in the mouse-over Tooltip

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#7434]
Hello!

When hovering over the name of an animal, the Population shown is the population in the respawn pool / pop pool / animals that can't be spawned due to world capacity already filled [not sure how SLG refers to it, internally].

Here's an example with the Bison: this starting world is filled with Bisons worldwide [minimap Bison layer shows Bisons everywhere], but tooltip misleads and makes players think only 20 are available - making them think the animal is close to extinction:

![bisonexample](https://user-images.githubusercontent.com/26847645/39324271-7966c576-4965-11e8-9bbc-922912a27170.jpg)

Note that for plants, it's likely that the number is accurate - since a 10 population plant (like Crimini Mushroom) will really give you a hard time finding them in the minimap layer:

![criminiexample](https://user-images.githubusercontent.com/26847645/39324597-42ef247e-4966-11e8-9c9f-32fbc8683802.jpg)

Thanks!

**Comment by SeanAtr0n** [comment]
not sure if this is still an issue, sounds related to stats

**Comment by MarjieAVolk** [comment]
This population line is coming from SpeciesTooltip.PopulationTooltip, which is reading the value straight from Species.currentPopulation.  So it's an environment sim issue.

**Comment by SlayksWood** [comment]
Seems fixed.
