### ISSUE TITLE
USER ISSUE: Character duplication

### ISSUE THREAD

**Issue by LazyTfft** [StrangeLoopGames/EcoIssues#7435]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Hello. So. I disconnected then I have back connected me and then was there my character I have reconnect again and it duplicated my charcter and I can't chat or go on m< tables please fix it.

**Expected behavior:**

**Actual behavior:**

**Comment by metachronism** [comment]
fixed 7.4.0 release
