### ISSUE TITLE
7.4 Server browser not showing consistent information 

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7438]
My server shows in the server browser as online and I can connect to it in 'recent'  and shows in the 'browse' panel as online however it shows as offline and not able to join in "My Servers".  there are also times it shows in My Servers but does not poopulate "recent at all" and will shows as online in "Browse"

[![Screenshot from Gyazo](https://gyazo.com/c8347d3b17e27697d0845364b18443b4/raw)](https://gyazo.com/c8347d3b17e27697d0845364b18443b4)

**Comment by johnkslg** [comment]
Some difference in the way those two lists are populated?

**Comment by pamduncan** [comment]
I tried again today - In the brows they show online, as long as filter is set correctly - it very annoying that the filters you set does hold even when just in a game and you always have to remember to reset it but as you can see these servers all show online:

[![Screenshot from Gyazo](https://gyazo.com/aaf60542c644b46800620ac5943341fb/raw)](https://gyazo.com/aaf60542c644b46800620ac5943341fb)

The ones on that list that are in "My Favorites show offline in "My Servers"  although they are really online

[![Screenshot from Gyazo](https://gyazo.com/b511539f5553f9b66ce3bd57d70c1b26/raw)](https://gyazo.com/b511539f5553f9b66ce3bd57d70c1b26)

**Comment by metachronism** [comment]
fixed in 7.4
