### ISSUE TITLE
User's laptop did not choose correct GPU

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7439]
Not sure how to make nvidia get Eco to make the right choice but we should look into it.

**Comment by GophTheGreat** [comment]
https://www.techadvisor.co.uk/how-to/pc-components/how-set-default-graphics-card-3612668/

I'm not sure that's a thing we can even touch though. The default value depends on the user's laptop power settings, and they have to go into the NVidia Control panel to override or change it.

**Comment by metachronism** [comment]
we cant do this, dont have access to the software
