### ISSUE TITLE
Text on excavator not curving

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7442]
![image](https://user-images.githubusercontent.com/3536496/39333443-c03f06b2-495f-11e8-83e0-1eaffe5d9d50.png)

Also:
![image](https://user-images.githubusercontent.com/3536496/39333458-cb510118-495f-11e8-9377-7241f2b993bf.png)

**Comment by keegan-o** [comment]
@SeanAtr0n Do we not have a TMP curved shader?

**Comment by SeanAtr0n** [comment]
fixed in 7.4
