### ISSUE TITLE
Ability to offload mats directly into a stockpile

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7443]
From Youtube: https://youtu.be/cY5Y5piZm38

"please add the ablity to offload the dirt/stone directly into a stockpile, having to take it out stack by stack takes awhile and it hinders the progress you can go before having to break.﻿"

**Comment by FWerewolf** [comment]
Please also skid steer unloads dirt/stone directly into the truck.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#98
