### ISSUE TITLE
Auth levels for Admins have changed to User for everyone on latest staging patch

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7446]
From Forum: http://ecoforum.strangeloopgames.com/topic/4523/auth-levels-changed-latest-staging

"Wondering if this is intentional or not due to a bug. But during the latest staging patch Auth levels for Admins have changed to User for everyone. Is there a way to correct this?"

**Comment by metachronism** [comment]
fixed
