### ISSUE TITLE
Addition of selective farming

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7447]
From Forum: http://ecoforum.strangeloopgames.com/topic/4529/selective-farming

"So, recently I had an idea that I thought would suit the game fantastically. Selective farming. Originally, for instance, corn looked more like wheat. Maybe, when you find a plant it will be in its worst form. You grow a bunch, and there could be a small chance of it "leveling up" into something better. This cycle would repeat until it got to its maximum form. Just a little extra thing."

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#96
