### ISSUE TITLE
[Suggestion] Possible Ideas for Steam Achievments

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#7448]
These are in no particular order (just as i thought of them)
1. Remove 1000 (or more) Stumps from the world (encourages people to clean up) and more trees to regrow
2. Remove 1000 (or more) Debris from the world (encourages people to clean up)
3. Destroy the Meteor in a server they play on with More than 5 people that have logged in (saves cheating on a singleplayer world or just creating a world as an admin then destroy meteor by admin commands ) (maybe also give an in game reward like a small meteor shard?)
4. Be in a world the Meteor has hit
5. Plant all types of crops (maybe one achievement for each plant)
6. Harvest all type of Crops  (maybe one achievement for each plant)
7. cook all types of food (maybe one achievement for each specialty this would encourage more people to try other stuff)
8. get Max everything in a set Speciality (this can be an achievement for each one)
9. Craft certain items (this would encourage people to try playing with different skills)
10. not sure about digging dirt or mining ore/stone as this would just encourage people to dig up same dirt, or just make a mess with rubble)
11. live on a world that has tailings but they are safely stored for a certain number of days without any ground pollution (encourages players to actually try and store these tailings safely)
12. not sure Hunting could be done as this would just encourage people to kill everything
13. Walking or driving powered Cart or Pulling a cart a certain amount of Distance?

Just a thought to try and encourage people to play via steam and put a little bit more thought to how they play.
Hoping other players or devs have more ideas on this ❤️

**Comment by elfl0rd** [comment]
Hidden acheivement - Ecko found! first discover an Ecko statue.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#95
