### ISSUE TITLE
Browser shows server offline in 'favorites' and online in 'recent' and not existing in 'LAN'

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7449]
![image](https://user-images.githubusercontent.com/3536496/39339673-e7bdf940-497e-11e8-8bc4-1f32ff20ec80.png)

**Comment by johnkslg** [comment]
I was able to connect to the server with 'auto connect to local' but not through the server browser

**Comment by elfl0rd** [comment]
Um, looks like hairpin-nat issue.
You cannot see local server directly, but can see through third service.

**Comment by metachronism** [comment]
fixed 7.4.0 release
