### ISSUE TITLE
[SUGGESTION] Option to override URL used for in-game links

### ISSUE THREAD

**Issue by shadow7412** [StrangeLoopGames/EcoIssues#7450]
I'm hosting an eco server, and have DNS set up for it. However when people click on in-game links, instead of being taken to my neat https://eco.example.com they are taken instead to http://1.2.3.4:19337

I would like, if possible, a server setting that overrides the base url for all such interactions.
Ideally, this setting should reside inside a file so that it can be easily edited (as I'm running the server on a headless ubuntu, I don't have access to the UI).

Lastly, if left blank, it should probably default to its current behaviour.

**Comment by Elliander** [comment]
Yeah, I noticed this as well. When I host, I see a local IP address and would prefer it if I could designate an alternative location - such as a domain I own.

**Comment by Chi-Yu** [comment]
Seeing that browser developers are working on warning users more and more about insecure connections and using non-default ports also sometimes triggers security warnings, I'd really like to see this feature implemented.

Also, there are servers behind NAT which reportedly build those links with incorrect IP addresses from the local address space such as `192.168.*.*` which of course won't work outside the local network.

Implementing this feature request should also help those people with broken NAT configurations.

**Comment by aawilson** [comment]
There was a mention in the 7.4.5 update around this, but no mention of any config, has anyone experimented with it and found out what mechanism they used to, quote, "[fix] webserver link from using the wrong address"?

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#94
