### ISSUE TITLE
Server Crash Loop: PowerGrid?  System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SessionExpired** [StrangeLoopGames/EcoIssues#7458]
Third time it's happened on my server,
It runs well for several days and one day after it's scheduled restart it goes into a crashloop forcing a Rollback from 8 hours or a 24 hours period.

4KM world
7.3.3 Version.
Any known issues that causes this and how to avoid it? Population of my server has dropped considerably due to this happening multiple times now which pushes a lot of our progress back, sadly.

> --BEGIN DUMP--
> Dump Time
> 04/27/2018 16:02:21
> 
> Exception
> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Object.GetType()
>    at Eco.Gameplay.Components.PowerGrid.<.ctor>b__25_0(PowerGridComponent comp)
>    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Eco.Gameplay.Components.PowerGrid..ctor(IPowerEnergyType energyType, PowerGridComponent[] components)
>    at Eco.Gameplay.Components.PowerGridComponent.LinkToGrid()
>    at System.Collections.Generic.List`1.ForEach(Action`1 action)
>    at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass13_0.<Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize>b__1(KeyValuePair`2 pair)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
>    at Eco.Gameplay.Objects.WorldObjectManager.Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize(TimedTask timer)
>    at Eco.Server.PluginManager.InitializePlugins()
>    at Eco.Server.PluginManager..ctor()
>    at Eco.Server.Startup.Start(String[] args)
>    at Eco.Server.MainClass.Main(String[] args)
> ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Object.GetType()
>    at Eco.Gameplay.Components.PowerGrid.<.ctor>b__25_0(PowerGridComponent comp)
>    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Eco.Gameplay.Components.PowerGrid..ctor(IPowerEnergyType energyType, PowerGridComponent[] components)
>    at Eco.Gameplay.Components.PowerGridComponent.LinkToGrid()
>    at System.Collections.Generic.List`1.ForEach(Action`1 action)
>    at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass13_0.<Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize>b__1(KeyValuePair`2 pair)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
> 
> 
> Inner Exception
> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Object.GetType()
>    at Eco.Gameplay.Components.PowerGrid.<.ctor>b__25_0(PowerGridComponent comp)
>    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Eco.Gameplay.Components.PowerGrid..ctor(IPowerEnergyType energyType, PowerGridComponent[] components)
>    at Eco.Gameplay.Components.PowerGridComponent.LinkToGrid()
>    at System.Collections.Generic.List`1.ForEach(Action`1 action)
>    at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass13_0.<Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize>b__1(KeyValuePair`2 pair)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
>    at Eco.Gameplay.Objects.WorldObjectManager.Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize(TimedTask timer)
>    at Eco.Server.PluginManager.InitializePlugins()
>    at Eco.Server.PluginManager..ctor()
>    at Eco.Server.Startup.Start(String[] args)
>    at Eco.Server.MainClass.Main(String[] args)
> ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Object.GetType()
>    at Eco.Gameplay.Components.PowerGrid.<.ctor>b__25_0(PowerGridComponent comp)
>    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Eco.Gameplay.Components.PowerGrid..ctor(IPowerEnergyType energyType, PowerGridComponent[] components)
>    at Eco.Gameplay.Components.PowerGridComponent.LinkToGrid()
>    at System.Collections.Generic.List`1.ForEach(Action`1 action)
>    at Eco.Gameplay.Objects.WorldObjectManager.<>c__DisplayClass13_0.<Eco.Core.Plugins.Interfaces.IInitializablePlugin.Initialize>b__1(KeyValuePair`2 pair)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
> 
> 
> --END DUMP--
> 

Worldfiles:
https://drive.google.com/open?id=1STkX1WGGqRYpYX0whBuggd6Mc8ZNHt3g
(Couldn't upload due to 10mb limit)

**Comment by metachronism** [comment]
this save is working in 7.4.1, will keep an eye on the issue though
