### ISSUE TITLE
USER ISSUE: Machinist Table not buildable

### ISSUE THREAD

**Issue by michaelberthold** [StrangeLoopGames/EcoIssues#7459]
**Version:** 0.7.4.0 beta staging-68e3874b

**Steps to Reproduce:**
1. Update from 7.3.3 to 7.4 staging
2. Start existing server
3. Start game
4. Craft Machinist Table at the Sawmill
5. Try to build the table
6. Try to use the table

**Expected behavior:**
Should have built the table so I can use it

**Actual behavior:**
Has build a one block default object which is not usable. When trying to use or trying to unbuild with hammer, server becomes unstable.

**Comment by craig-jong** [comment]
The machinist table is not intended to be in 7.4 - it will be removed in the next staging build.

It will make an appearance in 8.0.
