### ISSUE TITLE
[ISSUE] Wooden elevator doesn't stop at intermediate floors

### ISSUE THREAD

**Issue by matias-b** [StrangeLoopGames/EcoIssues#7460]
**Version:** 0.7.4.0 beta staging-68e3874b

**Steps to Reproduce:**
Place an elevator on a hole with multiple floors

**Expected behavior:**
The elevator should stop at every floor

**Actual behavior:**
The elevator skips floors and goes all the way to the bottom

![ecoelevator](https://user-images.githubusercontent.com/17019409/39374728-317e9fa0-4a22-11e8-98e6-0e3c9d0d6412.png)

**Comment by elfl0rd** [comment]
I would like the elevator to have two modes.
First. Single click on direction button - move elevator to direction end.
Second. HOLD direction button - move elevator onto direction before button is released. (and stop on closest block level if button released).

**Comment by elfl0rd** [comment]
Or add third, "stop" button.

**Comment by SeanAtr0n** [comment]
7.5 has a stop button, will probably add an interface to select floors to a more advanced version of the elevator in the future
