### ISSUE TITLE
[ISSUE] Can't get non-carriable items clicking a storage

### ISSUE THREAD

**Issue by matias-b** [StrangeLoopGames/EcoIssues#7461]
**Version:** 0.7.4.0 beta staging-68e3874b (happens in 0.7.3.3 too)

**Steps to Reproduce:**
Click any storage with items

**Expected behavior:**
Get some non carriable item, like clicking a stockpile

**Actual behavior:**
Only get carriable items and not other non-carriable items

**Comment by metachronism** [comment]
pretty sure this is working as intended

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#92
