### ISSUE TITLE
USER ISSUE: black screen in world

### ISSUE THREAD

**Issue by JorgenK74** [StrangeLoopGames/EcoIssues#7463]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
the world doesnt load in start screen, then hear a tone like a mistake happened and when i press escape, im inside the world but the screen black.. except the tasksbar i can still see.. nothing out of the ordinary happened, except i was kicked from the game 30 min before

**Expected behavior:**
it should have loaded normally (takes a very long time in normal conditions) 

**Actual behavior:**
not loading at all

**Comment by SeanAtr0n** [comment]
please send us your log file from
`%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

or are you on osx/linux?

**Comment by JorgenK74** [comment]
it was temporary issue it seemed. I am won 10 64bit.. i got other issue
that are of bigger concern to me now. work items that become corrupt after
a full day being offline, and with this.. not gaining a single skill points
or using calories while being offline.. this is situation is since friday

**Comment by SeanAtr0n** [comment]
how were work items becoming corrupt?

you can gain skillpoints while offline if you play on a public server or leave your private server running by launching the "Eco Server" under tools on steam

**Comment by D3nnis3n** [comment]
Duplicate.

**Comment by elfl0rd** [comment]
Duplicate of #11226

**Comment by D3nnis3n** [comment]
Would you be able to contact me on discord so we could get a way to reproduce this issue? Add me on Discord via D3nnis3n#2053

**Comment by JorgenK74** [comment]
Sorry, i havent played eco for ages..so im sure most bugs are gone now...

Kind regards Jorgen
