### ISSUE TITLE
Machinist table in 7.4 not working

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7464]
Via Reddit: https://www.reddit.com/r/EcoGlobalSurvival/comments/8ev786/moving_right_along_with_74_staging/

![2018-04-27_1400](https://user-images.githubusercontent.com/36867473/39384975-6b23970a-4a23-11e8-918f-cb1a320ba9cc.png)

"Anyone else try 7.4 Staging and have trouble advancing? Some of the parts have been moved to the Machinists Table, like pistons, but the table isn't working at all for me (it spawns a DefaultGameObject I can't interact with). Given that you can only build certain parts at that table, it's halted my technological advancement in my single player game.

[–]Voguhl 
having exatly the same issue, do you know how to at least remove that default block?"

**Comment by ShaydenMac** [comment]
Michael that would be helpful. Thanks! C:\Users\yourname\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt

**Comment by michaelberthold** [comment]
Here are my current [output_log.txt (zipped)](https://github.com/StrangeLoopGames/EcoIssues/files/1956734/output_log.zip) and the 
[broken game files (zipped)](https://github.com/StrangeLoopGames/EcoIssues/files/1956739/BrokenGame_20180427.zip). Hope this helps.

**Comment by craig-jong** [comment]
The machinist table was not meant to appear in 7.4, it will return (with its actual purpose, steam vehicles) in 8.0.

**Comment by craig-jong** [comment]
It will be removed in the next version of the 7.4 staging.
