### ISSUE TITLE
USER ISSUE: Animal

### ISSUE THREAD

**Issue by ColWindsor** [StrangeLoopGames/EcoIssues#7467]
[**Version:**](url) 0.7.3.3 beta

**Steps to Reproduce:**
I don't know if it's happened with anybody else but the heat map shows two spots in my world where the color is almost yellow, It's a decently sized area, I only found 1 elk each in those spots.  i killed them and haven't found any more. Did i just make them go extinct?

**Expected behavior:**
A much larger population of elk for an area showing almost yellow on the heat map

**Actual behavior:**
Appears to have been only one elk in the area.

**Comment by Elliander** [comment]
You can check the population of each species by going to the graphs for your world, which should even work if playing solo.

As I commented in your mushroom post, the biomes are generated randomly such that even if you used the same configuration files to generate a new world the biomes won't have the same layout. As such, it's possible to end up without a habitat, but you can work around the issue by building land yourself and trees will eventually grow there spontaneously. Animals of course won't, but if you are careful enough to not make them go extinct and create a way for the animals to get there the numbers can increase.

If you are creating single player servers my suggestion would be to check the biomes after the world is generated before settling in. If you don't like the layout, just generate a new world with the same configuration files.

As a side note, if anyone knows where I can manually set the biome seed in the configuration files for consistent world recreation I'd appreciate it.

**Comment by craig-jong** [comment]
Animals are pretty decent at running away.

Feel free to reopen this if you have any extra information to provide. It's possible to generate a low-population world, but its unlikely that there'd only be 2 elk.
