### ISSUE TITLE
USER ISSUE: Providing resources via wooden cart should trigger notification

### ISSUE THREAD

**Issue by shadow7412** [StrangeLoopGames/EcoIssues#7468]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
1. Link a wooden cart (or presumably any mobile inventory) to a thing that actions recipies (such as a kiln)
2. Take the cart away, and fill it with the required resource
3. Take the cart back to within linked inventory range

**Expected behavior:**
Your resources disappear without notification

**Actual behavior:**
Similar to when one adds resources to a builder, or a linked inventory of that builder, a notification should be made for contributing to the project. I suspect the credit should go to the one who is pulling the cart.

**Comment by WeaselDog** [comment]
No longer an issue with new crafting system.
