### ISSUE TITLE
[ISSUE] SP per craft abuse

### ISSUE THREAD

**Issue by Last2Night** [StrangeLoopGames/EcoIssues#7469]
1. It was brought to my attention that it is possible to heavily abuse the option of SP/craft time. Players are simply using 10-20 crafting stations to craft 24/7, usually stations that require cheap resources such as Campfires to cook fish or Fishing Table to skin fish. Fishing currently yields an insane amount of resources as well as some other professions. It creates unbalanced and frustrating environment especially for players that pick tough professions that require a lot of resources gathering and low crafting times.
- Please add some sort of SP/Craft mitigation for every additional crafting station of the same type owned by the same player.

2. Also people tend to not unlock Speed skills to keep their crafting stations occupied longer for SP/CraftTime purposes.
- Dont have a suggestion how to overcome this problems thou :D

Thanks.

**Comment by Last2Night** [comment]
@GophTheGreat @craig-jong 
Ill correct myself here, USED by the same player, not owned. As players can group up and use stations of each other to bypass the OWNED mitigation requirement.

- mitigation for every additional crafting station of the same type USED by the same player.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#91
