### ISSUE TITLE
USER ISSUE: Singleplayer Eco Gov: Localhost refuse to connect.

### ISSUE THREAD

**Issue by ECO34RT** [StrangeLoopGames/EcoIssues#7471]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Open a new game from start menu computer (No Server) and select 1 - 3 players.

**Expected behavior:**
I expected to have access to Graphs considering there is a menu option for 1 - 3 players.

**Actual behavior:**
An internet page tried to load but failed. Localhost refused to connect.

**Comment by metachronism** [comment]
due to security issues it will be difficult to fix this in every case
