### ISSUE TITLE
Server Restart causes Vehicles to mutiply

### ISSUE THREAD

**Issue by voguhl** [StrangeLoopGames/EcoIssues#7472]
Version: 7.4 Staging

After restarting the server some of the carts and vehicles multiplied.
It seems to me as if they reappeared at locations where they got stuck and the user did pick them up to place them again.

My guess is they we're only visually removed but not actually in the save and the server restart made them appear again.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/7317

**Comment by voguhl** [comment]
ok that seems to be the same issue, i'll close this
