### ISSUE TITLE
USER ISSUE: I can fill two contracts at same time with same material

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#7474]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
make a contract asking for 500 stone and place in a stockpile, put more than 1 repitition

**Expected behavior:**
should ONLY fill One Contact at a time

**Actual behavior:**
i can fill BOTH contracts with same stone and get paid for doing two contracts but ONLY really deleivering one contract

**Comment by Conchipedia** [comment]
![snap2177](https://user-images.githubusercontent.com/29383891/39398386-d420d2cc-4b04-11e8-8762-5ce3b5a08fc2.png)

when i add stone to the Stockpile for the Contract BOTH of them are filled with same Stone, what we need is an order of contracts, so one is Always Filled before the other.

**Comment by johnkslg** [comment]
Reducing priority but will fix this

**Comment by Artainx** [comment]
Yep this is still an issue.  I accepted 5 identical contracts for 120 steel.  Put 120 steel in the box and I was able to complete all 5 contracts with only that first 120 steel.

**Comment by Conchipedia** [comment]
quickly finds which servers are doing multiple contracts and filling them, making a fortune 💰
