### ISSUE TITLE
USER ISSUE:Skill separation doesn't make sense

### ISSUE THREAD

**Issue by PaleGhost** [StrangeLoopGames/EcoIssues#7475]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Skill tree

**Expected behavior:**
Since gathering comes with the scythe skill and farming comes with the hoe skill. Logging, Mining and digging should be combined with their corresponding class. Why would you have to specialize separately? I think these should either be combined with other skill groups like the above mentioned. Or better yet, put all the tool skills in survivalist since that's where the building one is.
Logging, Mining and digging should be combined with their corresponding class. Why would you have to specialize separately? I think these should either be combined with other skill groups like the above mentioned. Or better yet, put all the tool skills in survivalist since that's where the building one is.

**Actual behavior:**
Basic skills are sold separately and require more specialization just to do your job without wasting a bunch of food. It's completely wasteful how it is now.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#90
