### ISSUE TITLE
Names unhandled in Game and also show up differently in-game and in the server UI

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7476]
Need to be able to deal l with user names like Goku rustmoney.com and Vegeta rustmoney.com  
In game they show up as Goku.rustmoney.com and Vegeta.rustmoney.com  but in the Server UI they gave a space in them 
[![Screenshot from Gyazo](https://gyazo.com/cee3e764c79a770c9a45c3f5f59163a2   https://gyazo.com/f25d48693b90e4bbc112e1b18200e443/raw)](https://gyazo.com/cee3e764c79a770c9a45c3f5f59163a2   https://gyazo.com/f25d48693b90e4bbc112e1b18200e443)

/whois or a /ban or /kick or an admin command that needs to use a player name is not able to handle names like this.

JohnK said to assign to him

**Comment by johnkslg** [comment]
Would like to be able to reference players by some ID, which you could see with a /players command perhaps.

**Comment by wolfgangmeyers** [comment]
Working on it!

**Comment by wolfgangmeyers** [comment]
Fix in progress: https://github.com/StrangeLoopGames/Eco/pull/3288

**Comment by SlayksWood** [comment]
Now all users have ID, so you can ban or kick it by ID. Seems fixed.
