### ISSUE TITLE
GRAPHIC ISSUE: Wall elements displayed in wrong direction

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#7478]
(v0.7.3.3 also 0.7.2.5) Possibly all wall-elements (bricks, stone, logs) are displayed in a wrong direction if they are inserted in a north-south-wall with gaps between. If windows or doors (or even blocks) are inserted, the texture turns in the right direction. Fancy things happen when a door is opened, the wall opens also :)

![eco wrong elemnts](https://user-images.githubusercontent.com/38510829/39401664-df732418-4b4a-11e8-98be-ce3dc5c54b36.jpg)

Attachment and Suggestion: wouldn't it be best to use the direction keys for such elements, it would clear the code?

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#89
