### ISSUE TITLE
USER ISSUE: Skillpoint gain on crafting

### ISSUE THREAD

**Issue by Fez57** [StrangeLoopGames/EcoIssues#7479]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
I am playing on a hosted server and I can create servers, but there is no way to set the skillpoint on crafing to enabled, I do not get the front screen giving me the option to enable this feature. I would hope that simply changing the value of the Skill gain from crafting from 0.0 in the configs and a server restart would let the players gain SP from crafting.

**Expected behavior:**
Changing the value of Skillpoint gain for crafting when the config value is changed.

**Actual behavior:**
Changing the value does nothing even after server restarts unless the checkbox is checked when creating the server which does not appear on my hosted server.

**Comment by Last2Night** [comment]
@Fez57 
Its working fine and located under Difficulty Settings tab, SkillPointsPerCraftTime

**Comment by Fez57** [comment]
It only works when the checkbox is marked on the initial world creation
page. Unfortunately how clanforge set their servers up i do not see this
initial page when a new world is created.

**Comment by Fez57** [comment]
I have been looking at many game hosting sites and can not find any that lets you gain skill points on crafting or actions, The servers are created, but because the Skill gain on crafting can not be clicked on a hosted site the configs are not loaded and what ever value you change in the config it does not work.

This to me is a crucial setting so it means that hard workers can get rewarded for skill points rather than just having eaten good food and built a decent house. I would hope this setting can be automatically enabled and changing the value of the Skill gain from crafting and actions from 0.0 would give the effect.

**Comment by Last2Night** [comment]
@Fez57
What you describe is definitely game server provider issue. You have to contact their support.

**Comment by MarjieAVolk** [comment]
The checkbox that you see when creating a server locally will just set the SkillPointsPerCraftTime setting to 0.0001, so yes that is the only setting you should need to change.

**Comment by MarjieAVolk** [comment]
I believe this is an issue with the hosting service then, as @Last2Night suggests.

**Comment by D3nnis3n** [comment]
Settings no longer exists.
