### ISSUE TITLE
USER ISSUE: Carts and dirt ramps disappearing

### ISSUE THREAD

**Issue by PaleGhost** [StrangeLoopGames/EcoIssues#7480]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Path in sky
have ramps and cart on path
Leave render distance	

**Expected behavior:**
carts and ramps should stay there

**Actual behavior:**
Ramps and carts disappear and become glitched. unable to be replaced or built over

**Comment by metachronism** [comment]
should be fixed in 7.4+
