### ISSUE TITLE
GRAPHIC ISSUE: Text doesn't draw on Ubuntu (with integrated gfx + mods)

### ISSUE THREAD

**Issue by matias-b** [StrangeLoopGames/EcoIssues#7481]
When joining a game, text displays for a while then suddenly dissapears, restarting the game has no effect.

OS: Ubuntu 
Game version: 0.7.3.3

![screenshot from 2018-04-29 01-44-46](https://user-images.githubusercontent.com/17019409/39403321-9f77ef1a-4b4f-11e8-9372-96ae7fda0f32.png)

**Comment by SeanAtr0n** [comment]
Could you make this happen again and then send us your log file? Should be somewhere like
`~/.config/unity3d/Strange Loop Games/ECO/Player.log`

**Comment by SeanAtr0n** [comment]
Doh, are you certain your desktop is running w/ the nvidia gpu? Sounds like its an all or nothing thing depending on your setup
https://askubuntu.com/questions/596855/choose-which-gpu-to-use-for-each-application

I meant to look into this as it could help some users but if your setup is one of the all or nothing configs it might not help you

**Comment by matias-b** [comment]
Will try that,
Also noticed that joining a server without mods doesn't make the text dissapear, may be something to do with CTK's mod?

**Comment by SeanAtr0n** [comment]
Interesting, does the text still look broken on that server with CTK when your nvidia card is running?

**Comment by matias-b** [comment]
No problems so far running on the nvidia with CTK! may be something fixable or it has to do with drivers/low level unity stuff?

**Comment by Sebi-M** [comment]
I have the same issue on Debian, I think. I have a Thinkpad T450 with Debian/testing with Intel integrated graphics only, running Beta 7.4.4
When I start the game, and click on the "Quit Game" button, text is displayed in the dialog box. When connecting to a server (Win64, Beta 7.4.4) on LAN, the last message displayed is "Entering World", then the text is not rendered anymore, but the space is reserved (gear spinning not in the middle, but "on the second line", leaving space for text "on the first line".)
When I then disconnect, and the select "Quit Game" in the main menu again, the text in the dialog box is not rendered.
The only things that puzzle me are:
* When first connecting to the server, I could see the text, some minutes into the game. The character creation wizzard(?) displayed text, which it now doesn't anymore, when starting with a fresh server (and a fresh client / deleted configuration, see below)
* I deleted .config/unity3d/Strange Loop Games/Eco and started anew, no changes
* I deleted the unpacked files and re-extracted them, no changes
* I restarted the sysem, no changes
* I unpacked the Win64 server into a new directory and started anew, no changes
* Therefore no mods present

So the title can be changed to "GRAPHIC ISSUE: Text doesn't draw on Linux (with integrated gfx)"

**Comment by Sebi-M** [comment]
#5991 seems to be a duplicate?

**Comment by Sebi-M** [comment]
Error still exists on Server Win64 / Client Lin64, Intel-GFX (LAN) with version 7.4.5. During my 10 minutes testing on the official Test-Server noone joined, so I had text.
Perhaps I'll try to reproduce on Win64, Intel-GFX.

**Comment by Sebi-M** [comment]
So, I tested on the Test-Server, there the bug did not happen... for a long time, but then it eventually showed. But once I reconnected, everything was fine again and I could continue playing. If this happens once in an hour, I can cope with it, I thought.
So I asked my wife to join, and then... the bug happened over and over again, just like on the server she started. I could, if I was lucky, perhaps play one or two minutes with text, but most of the time the text disappeared while still loading the map.
So, perhaps something is sent over the wire that makes the client drop out. Do you need some tcpdump files or something like that?

**Comment by hillna** [comment]
I am having this same issue after switching over from an Intel/Nvidia platform to all AMD. Text was fine before swapping my hard drive over to the new hardware, so initially figured an `amdgpu` driver issue.

[Player.log](https://gist.github.com/hillna/665c1f9d2d8da2501a48f59082e689c8)

**Comment by SlayksWood** [comment]
Seems fixed
