### ISSUE TITLE
Singleplayer Connection Failed

### ISSUE THREAD

**Issue by Serynthara** [StrangeLoopGames/EcoIssues#7482]
Original Post with 7.3.3. : 
https://github.com/StrangeLoopGames/EcoIssues/issues/7213

As GophTheGreat suggested, I deleted the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO, which had no effect, the problem remained.

I updated to 7.4.0 , but still, the problem remains, that's why I'm opening the thread again.
The requested error logs are attached.

[ServerCrash AggregateException 04294400.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1958481/ServerCrash.AggregateException.04294400.txt)

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1958483/output_log.txt)

[sysinfo.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1958484/sysinfo.txt)

**Comment by GophTheGreat** [comment]
If I'm reading those logs correctly it looks like your save was corrupted.

**Comment by metachronism** [comment]
we've fixed this in 7.4+
