### ISSUE TITLE
Version 7.4 stagged

### ISSUE THREAD

**Issue by Marathorn** [StrangeLoopGames/EcoIssues#7485]
Machinist table is not designed so we can't craft things like gearbox. that mean we can't destroy meteor....

**Comment by elfl0rd** [comment]
what? use machine shop or factory.

**Comment by Marathorn** [comment]
In Version 7.4 , gearbox are craft in machinistshop

**Comment by Squash-it** [comment]
See screenshot, it should be craftable at the "Machinist Table" but as far as I can tell it's not in the game for the staged version.

![gearbox](https://user-images.githubusercontent.com/38844448/39411837-d897a278-4c11-11e8-9d8d-91302f1eba5a.jpg)

**Comment by turnburgler** [comment]
I thought it was just not added yet *_* got to this point of progression a day ago and moved back to 7.3 in wait for an update :p

**Comment by dawidbanka** [comment]
I have this problem too

**Comment by elfl0rd** [comment]
fixed in latest bleeding_edge_staging

**Comment by johnkslg** [comment]
Fixed in latest apparently!
