### ISSUE TITLE
USER ISSUE: Can not tab out of game using Windows 7

### ISSUE THREAD

**Issue by chopperprop** [StrangeLoopGames/EcoIssues#7489]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Tab out to desktop

**Expected behavior:**
Go to desktop so I can view ECO Wilkki

**Actual behavior:**
Tries to go to desktop but just for a split second

**Comment by Nicolausi113** [comment]
Deselect fullscreen in Main Menu/Advanced Settings and click apply, then you can use other apps beside.

**Comment by metachronism** [comment]
probably not relevant anymore, but you have a win7 install maybe you can check this real quick @SeanAtr0n

**Comment by SeanAtr0n** [comment]
Fixed a while back
