### ISSUE TITLE
USER ISSUE: Holes in walls (for windows or doors) lower average room tier

### ISSUE THREAD

**Issue by TheRealMaxion** [StrangeLoopGames/EcoIssues#7490]
I have a room made entirely of hewn logs.
There is a hole in one wall that is 2 blocks high and 1 wide, to be able to enter the room.
This hole counts as tier 0 materials, even if there is a door in the hole, and pulls the average tier of the room down to 0.99 (the room is 168 square meters in volume).
If I fill the hole (door) with hewn log wall, the room reaches an average of 100% tier 1 materials.

I have not tested this for actually placing windows in window-holes, but I suspect they might work correctly since they are placed in the same way that walls are, but doors currently do not.
Making holes for windows without placing windows in them does reduce the skill point gain though.

Doors and windows should not reduce the tier and skill point gain of a room, especially if there are actually doors and windows in the holes (I have tested placing the most basic of wooden doors, but not tested placing windows).

**Comment by TheRealMaxion** [comment]
After further testing, I have found that for smaller rooms, such as a room with 3x3x3 squares of space, even fully enclosing the room in hewn logs does not get rid of all the % of tier 0.

**Comment by craig-jong** [comment]
I've updated tiers to fix this - let me know if you encounter this again in the next build of the game.
