### ISSUE TITLE
Trample spread going through the roof

### ISSUE THREAD

**Issue by ThePickleTickle** [StrangeLoopGames/EcoIssues#7493]
Noticed a lot of grass disappearing all over the map. spent ages trying to work it out. finally discovered the 'trample spread' under 'Cause & Effect' at day4 skyrocketed and covered the map.

http://78.129.212.51:10615/index.html?

**Comment by ThePickleTickle** [comment]
it appears to be a bug with player activity and the trample is a byproduct of that

**Comment by SlayksWood** [comment]
> I did nothing on the surface. I made an entrance underground and began to mine ore inside. Surface biome trampled
> ![image](https://user-images.githubusercontent.com/45708377/60574046-76252a80-9d81-11e9-987e-1dc9cfa351b6.png)

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/91278126-7b66e500-e78c-11ea-86fc-329441827add.png)
