### ISSUE TITLE
USER ISSUE: skill points

### ISSUE THREAD

**Issue by JorgenK74** [StrangeLoopGames/EcoIssues#7494]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
None, I do not get more skill than the 90 i have now, but i have 90 since 1,5 days. out of food i should get 41,3 and my house least 25,3.. 

**Expected behavior:**
I should have least between 150 and 200 skill points, but im stuck on 90 for 1,5 days now

**Actual behavior:**
Stuck on 90 skill points without further increasing of it

**Comment by JorgenK74** [comment]
Addition: today april 30th 2018 I logged off at 5:10pm and logged on again around 8:20pm thats more than 3 hrs, in this time i should have least gained 6 skill points and used some or if not all my calories. but both are ZERO. nothing changed in my absence. While I also noticed yesterday I was 2 hrs online after being a full day gone. in this time i also did not receive any skill points, as i did before, bugged by absence ?!?! Also my kiln which i could use before.. became corrupt (inactivity issue) same happened with my campfire before.. is getting inactive for more than 24hrs a problem?!?!?!? It should not, but it is.  the only thing that is reactivated while being online now is my calorie consumption. ... I want compensation in skill points 250 or so should do it...

**Comment by JorgenK74** [comment]
New Development... I was again offline for 2 days 17hrs, got online again today, and i had earned 170 skill points. While I should have, by the food I ate and the house skill points, around 350-400 so i miss still a lot. 
I also noticed that when you are offline for more than a day, its NOT ONLY the skill points regeneration that gets "damaged" but also a piece of working furniture that get corrupt, last time before it was my campfire, now it is my kiln, I want to use, it place and amount and press order, nothing happens, the following everything becomes unusable and after 2-3 min you get kicked from the server for being inactive, replacing the item doesn't help, still get the same message and kick. I also noticed that being offline for another day is enough to "restore the issue" however the player still misses lots of skill points.. and during some of this time offline , the player doesn't consume any calories either.
Another thing that I found weird, is that i did not start on the spot where i ended my last session, but on my largest plot on a different spot on the map.

**Comment by JorgenK74** [comment]
New Development Addition... Im unable to use certain work items, Is player become (partly corrupt when inactive for longer time?!?!?!? (items affected, Kiln, workbench, mortar table... ) game is highly unstable and not fun to play...

**Comment by JorgenK74** [comment]
theorethic thesis: When a player has become inactive for more then 24 hrs, it.s most likely the case that skills of the player become corrupt or "inactive" that is why (most likely) that when you want to use a specific part of the skill that had become inacitve, you as player get booted from the server with as message "inactive" I fear that the skill tree is not as stable as it should be and with it the skill generation.

**Comment by craig-jong** [comment]
Were any admin/server commands run on the servers where you saw this effect?

This could possibly be related to the server time becoming incorrect.

**Comment by JorgenK74** [comment]
as it turns oput the server has no admin, but with the new update none can
play on it anymore... wasted time there..

**Comment by craig-jong** [comment]
To be honest, it sounds like the lack of skillpoint gain is due to the food in your stomach being rotated out every 24 hours. Basically food only grants you skill benefits for the 24 hours after consumption, so time after that you'll revert to the base skill gain set by the server. By default, this number is 12.

Being kicked for inactivity could, possibly, be attributed to server instability with is a separate issue that is being looked into. When I mentioned the admin, I was talking about whoever was running the server. There has to be someone - the servers don't just magically appear.
