### ISSUE TITLE
Bugged wooden cart

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7498]
From Steam https://steamcommunity.com/app/382310/discussions/4/1694919808751923619/:

"So for w/e reason i pickedup my cart and i fell through the world and i ended up on a beach. I went to drag teh cart again this time it flug itself into teh ocean where after several attempts i could not get the deed out and therefore can not pick it up. I have to make a whole new one now. It might be nice if we could actually go towards teh bottom of the sea and stay for a sec or you know maybe grab the cart with out the deed in our inv."

**Comment by SeanAtr0n** [comment]
I'm not sure how they managed to make the cart go flying while placing it... would need more info to debug that if it still happens.

The ability to pickup a cart while not holding the deed sounds reasonable... maybe @MarjieAVolk can look into that when she gets back.

**Comment by MarjieAVolk** [comment]
I think the reason we are requiring that is because the cart doesn't actually have a reference to the deed, so it can't find it unless it's in your inventory.  Which is kind of silly anyway.

**Comment by SeanAtr0n** [comment]
Looks like @MarjieAVolk fixed this one by getting rid of deed items
