### ISSUE TITLE
Tool Tip arrows don't point at what they are tool tipping

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7499]
![image](https://user-images.githubusercontent.com/6262198/39452763-52daa5e6-4c88-11e8-896f-047f84750fa1.png)

Only for the "side" tooltips

**Comment by MarjieAVolk** [comment]
Nooooo whyyyyyyy

We need a tag for 'A Matter of Pride' priority

**Comment by MarjieAVolk** [comment]
Okay I checked on this in the current bleeding edge build, and it looks fixed.  I believe this might have been related to the resizing bugs that were present on some versions of Unity 2017, and fixed in 2018
