### ISSUE TITLE
Contact ItemsInContainer Failure improvemnet

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7502]
![image](https://user-images.githubusercontent.com/6262198/39455116-b12a66bc-4c93-11e8-85cb-ba721a3a2aad.png)

Should accept the 5 dirt it wants, and leave me with 5 dirt left over

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#88
