### ISSUE TITLE
Invalid contract wording always addresses the contract creator

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7504]
![image](https://user-images.githubusercontent.com/6262198/39455545-dd7063be-4c95-11e8-98a2-fe1498045a61.png)

This is worded like I was the one who wrote the contract, which is confusing because I wasn't.

**Comment by johnkslg** [comment]
The contract wont even be allowed to be posted if its invalid. Thus, you will only ever see this legitimately if youre the contract creator. I'll update the 'random generation' settings to not generate this case.
