### ISSUE TITLE
Contracts should be labeled as invalid before trying to accept them.

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7505]
Or some other solution
Contracts are confusing because they're all presented as valid, when often times you'll run into invalid ones mixed in.

Could just grey out the "accept" button
or not show contracts on the board until they're valid

**Comment by johnkslg** [comment]
Problem is they can become invalid at anytime, and its not trivial to track when that happens (requires counting ground to see if theres anything harvestable, for example).
Could make it update when you open it or something though.  Reducing priority.

**Comment by SlayksWood** [comment]
I don't quite understand what this is about. Is this still relevant for contracts?
