### ISSUE TITLE
Contract UI inserts extra whitespace

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7507]
![image](https://user-images.githubusercontent.com/6262198/39455817-6af95b04-4c97-11e8-9ef0-ebf1efeb56eb.png)

(Different from other bugs, this window allows the content to fit, but still breaks)

**Comment by johnkslg** [comment]
Dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/7400
