### ISSUE TITLE
Contract build room fails

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7508]
![image](https://user-images.githubusercontent.com/6262198/39456160-63933900-4c99-11e8-818b-67519bbe3995.png)

**Comment by Nanders** [comment]
![image](https://user-images.githubusercontent.com/6262198/39456250-06c43606-4c9a-11e8-8eb3-70c94f7cd884.png)

**Comment by johnkslg** [comment]
Whyd it fail? no sand? Can you send the save?

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/39500960-ff13b3c2-4d6c-11e8-81c3-da84537f907a.png)
Could not repro, send through save?

**Comment by Nanders** [comment]
I just uploaded the save on thread #7535 

Its also reproduce-able in build, heres another example

![image](https://user-images.githubusercontent.com/6262198/39539630-03fe2bf0-4df5-11e8-9ae4-86100608ebe4.png)

**Comment by SlayksWood** [comment]
Now you can only set room tier, without materials. I think this issue isn't actual. Closed for now.
![image](https://user-images.githubusercontent.com/45708377/62540745-f3e8c400-b860-11e9-9902-b2e54b2379db.png)
