### ISSUE TITLE
Search and select caret is offset from text

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7510]
![image](https://user-images.githubusercontent.com/6262198/39456397-01da93fa-4c9b-11e8-9587-14f616c0aa05.png)

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3308

I've tried and failed to fix this multiple times :'( Some TMP setting is wrong I guess, but I cannot understand
