### ISSUE TITLE
Crash in KillPlant

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7514]
La référence d'objet n'est pas définie à une instance d'un objet.
Object reference not set to an instance of an object.

   à Eco.Simulation.PlantSim.KillPlant(Plant plant, DeathType deathType, Boolean applyToWorldLayer)
   à Eco.Simulation.PlantSim.DestroyPlant(Plant plant, DeathType deathType, Boolean applyToWorldLayer)
   à Eco.Gameplay.Plants.PlantBlock.Tick(Vector3i worldPosition)
   à Eco.World.PersistentChunk.Tick()
   à Eco.World.WorldPlugin.Run()
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by SeanAtr0n** [comment]
Seems to be fixed now, no recent reports
