### ISSUE TITLE
Crash while harvesting

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7517]
Der Wert darf nicht NULL sein.
The value can not be NULL.
Parametername: key
   bei System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   bei System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   bei System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   bei Eco.Gameplay.Items.ItemAttribute.Get[T](Type itemType)
   bei Eco.Gameplay.Plants.PlantEntity.TryHarvest(Player player, Boolean picked)
   bei Eco.Mods.TechTree.ScytheItem.OnActLeft(InteractionContext context)
   bei Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by SeanAtr0n** [comment]
fixed 7.4.1 (or maybe 7.4)
