### ISSUE TITLE
[7.4.0 #518a927f]  Worlds still being created with 0 recources

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7524]
https://steamcommunity.com/sharedfiles/filedetails/?id=1375054402

0 turtles....

Expected at least one as update said that worlds would no longer create with 0 in a layer

**Comment by craig-jong** [comment]
It force spawns plants, not animals. The only animals that block progress are Elk, Bison, and Hare so the priority on this one is significantly lower imo.

**Comment by craig-jong** [comment]
This has always been a stopgap for until we can get a full world generation rework in. There are always going to be possible gaps in our coverage as long as world generation is completely random.

The chances of having a world where any given plant is not capable of existing at all is extremely low, though. I'm going to close this, but we ARE planning on reworking worldgen to allow us more control over what spawns.
