### ISSUE TITLE
[7.4.0 #518a927f]  Browse does not populate until filter is applied

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7525]
When you click 'join' and then pick browse the browser does not populated, even if you want the default filter settings until you 'apply them

After clicking Join:
[![Screenshot from Gyazo](https://gyazo.com/2d3564cffead77535a5e9fe957ca2d14/raw)](https://gyazo.com/2d3564cffead77535a5e9fe957ca2d14)

After clicking 'Apply' in the filter even without changing the default filter settinsg:
[![Screenshot from Gyazo](https://gyazo.com/3e4d681a45b20c7e2130e1cdb33177b6/raw)](https://gyazo.com/3e4d681a45b20c7e2130e1cdb33177b6)

**Comment by MarjieAVolk** [comment]
This definitely did not happen the last time I looked at this.  But who knows what has gone on while I was gone.

**Comment by MarjieAVolk** [comment]
Well, I have to take it back, turns out it had been like that the whole time.  Seems I didn't catch it because I always had to go in and turn off the version match filter while I was testing, since I was on a debug version.
