### ISSUE TITLE
Writing message to oneself. Crash and prevent login

### ISSUE THREAD

**Issue by voguhl** [StrangeLoopGames/EcoIssues#7527]
Version: 7.4 Staging

Write message with "@me" where "me" is the own username.

Instant crash and crash when logging in.

**Comment by turnburgler** [comment]
Having the same issue, messaged myself by mistake when copy-pasting something and now I am unable to join my own dedicated server. Keeps getting stuck on "entering world...", restarting the server didn't help. 7.4 bleeding edge.

**Comment by turnburgler** [comment]
Restarted steam a while later and was able to log in again!

**Comment by elfl0rd** [comment]
Confirm.
Same as latest 7.5 staging.
Need wipe chat data from save, to allow bugged user to join.

**Comment by MarjieAVolk** [comment]
Hey guys, I tried to repro this and messaging myself works fine for me.  Does anyone have a stack trace for the crash?  Maybe it's related to specific usernames?  What are some of your usernames in Eco?

**Comment by elfl0rd** [comment]
i cant reprodyce it now.

**Comment by MarjieAVolk** [comment]
Okay, I'm going to close this as no repro.  Haven't had a report of it in months, and I never saw it happen.
