### ISSUE TITLE
World Marker for contract is placed when trying to accept invalid contract

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7530]
Tried to accept "Mow Lawn" contract, which is invalid because it has no grass.

Still get a world marker showing up for the contract, even though I never successfully accepted.

**Comment by Nanders** [comment]
Correction: when accepting a valid contract after attempting to accept an invalid one, the world marker placed will be the text provided for the invalid one, not the one you've just accepted.

**Comment by johnkslg** [comment]
Did you accept 'plow'?  Plow contract was tagging the field 'mow'. Fixed.
