### ISSUE TITLE
World markers should occlude other world markers

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7531]
![image](https://user-images.githubusercontent.com/6262198/39487604-9fc43d8e-4d34-11e8-882f-f144e1d0625d.png)
After accepting only two contracts. I imagine this would be problematic with even a small number of markers.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#85
