### ISSUE TITLE
Transport Clause doesn't actually require you to transport goods

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7532]
Only requires you to insert the number of requested items into the ending stockpile. This makes it no different from the Items in Container clause.

Suggestion: add a "Remove Items from Container" clause, then "Transport Items" would be the same as "Remove Items from Container" + "Items in Container"

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#84
