### ISSUE TITLE
Contract Clause Build Road: Valid road was not detected 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7535]
![image](https://user-images.githubusercontent.com/6262198/39488914-a86ee4f8-4d38-11e8-8a4a-2f55341d307f.png)

**Comment by johnkslg** [comment]
Got the save for this?  I cant tell from the screen shot how youre using ramps.

**Comment by johnkslg** [comment]
My tests with roads succeeded

**Comment by Nanders** [comment]
[Gamesave.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1968298/Gamesave.zip)

**Comment by Nanders** [comment]
![image](https://user-images.githubusercontent.com/6262198/39539154-c655ac84-4df3-11e8-9a9b-bb59a76712d7.png)
![image](https://user-images.githubusercontent.com/6262198/39539282-0dec7b90-4df4-11e8-806c-959c760d8ee9.png)

**Comment by D3nnis3n** [comment]
Caused by a ramp being in it, merged with https://github.com/StrangeLoopGames/EcoIssues/issues/12205
