### ISSUE TITLE
Large delay when clicking on contract picker dropdown for the first time

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7536]
![image](https://user-images.githubusercontent.com/6262198/39489008-f91d1730-4d38-11e8-8c06-a0d77489210d.png)

takes several seconds to open this

**Comment by johnkslg** [comment]
Cant repro this, can you demo?  Could it be the server was stalled doing something else?

**Comment by SlayksWood** [comment]
Can't reproduce in staging-1568. Seems fixed.
