### ISSUE TITLE
"Could not start server: object reference is not set to an instance of an object"

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7539]
Via Forum member: http://ecoforum.strangeloopgames.com/topic/4349/could-not-start-server

"TheFlyingOppman 

Hall oils with an oil! ;)

Had this problem before recently, but it seemed to be fixed with the last update. If I try (since Sunday evening) to enter my world, then the following error message appears:

"Could not start server: object reference is not set to an instance of an object"

I played normally on Sunday, but when I wanted to take a look at the evening around 8pm, I was not in the game anymore, but in the main menu. When trying to enter my world or to load an old save now always the above error message.

Even as an info: 
I currently play single player without an online server, therefore leave most of the time the computer running, so that also does something and the server is not always off and quasi stands still. Therefore the info above that I was "out of game".

Hope somebody can help me, because I am finished with my Latin ...

Thanks in advance

**Comment by johnkslg** [comment]
Can you ask him to run it in bleeding edge?  Or collect the save game and attach to the bug?

**Comment by johnkslg** [comment]
Should be fixed in 7.4!
