### ISSUE TITLE
7.4 Can't r-click deposit coal to stone brazier

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7541]
From Steam https://steamcommunity.com/app/382310/discussions/4/1694919808755637900/: 

On 7.4 staging, I'm unable to deposit coal that I'm carrying with an r-click. After putting some in the brazier with E button, I tried to add one more that I was carrying and this turns the brazier on and off now.

**Comment by MarjieAVolk** [comment]
This is because both the fuel component and the on/off component add right click behaviors, and in this case the on/off component is winning.

**Comment by elfl0rd** [comment]
@MarjieAVolk periodically all works nice, but i cant see logic in they work.
Rare times if i try to add fuel - it's added.

**Comment by elfl0rd** [comment]
> Ideal - if you carry fuel, and target have space, they put.
else - turn on\off

**Comment by MarjieAVolk** [comment]
Yes it will be a bit random I would guess, it's going to be based on what order the components were added to the object.  So it might be specific to certain objects.  It might also change when you reload the server.  But I would guess during a single play session it will be specific to each object.

**Comment by D3nnis3n** [comment]
Duplicate
