### ISSUE TITLE
7.4 bleeding edge new signs/wheelbarrow not working.

### ISSUE THREAD

**Issue by turnburgler** [StrangeLoopGames/EcoIssues#7542]
The large/small standing and hanging wood signs crafted at the carpentry table are just white blocks when placed and are missing icons. Same goes for the hanging/standing lumber signs and the wheelbarrow.

**Comment by turnburgler** [comment]
The hand plough works to place and use but is missing icon art as well.

**Comment by turnburgler** [comment]
Skid steer is also missing an icon, but works to place an drive.

**Comment by craig-jong** [comment]
should be fixed in the current build
