### ISSUE TITLE
USER ISSUE: Wrong username/password combination for no reason

### ISSUE THREAD

**Issue by cuzitsjonny** [StrangeLoopGames/EcoIssues#7543]
**Version:** 0.7.4.0 beta staging-518a927f

**Steps to Reproduce:**
1. Select username field
2. Type username
3. Select password field
4. Type password

**Expected behavior:**
A valid login response

**Actual behavior:**
A window telling me the following:
"Invalid username or password."

<details>
<summary>Log File</summary>Initialize engine version: 2017.4.0f1 (b5bd171ee9ba)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 970 (ID=0x13c2)
    Vendor:   NVIDIA
    VRAM:     4043 MB
    Driver:   24.21.13.9731
Begin MonoManager ReloadAssembly
- Completed reload, in  0.038 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Setting up 2 worker threads for Enlighten.
  Thread -> id: fc0 -> priority: 1 
  Thread -> id: 24fc -> priority: 1 
UnloadTime: 3.495258 ms
Client version: 0.7.4.0 beta staging-518a927f
Monday, April 30, 2018 9:42 PM
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fallback handler could not load library C:/Users/JonnyDesktop/Desktop/Eco 7.4/Eco_Data/Mono/libc
Fallback handler could not load library C:/Users/JonnyDesktop/Desktop/Eco 7.4/Eco_Data/Mono/.\libc
Fallback handler could not load library C:/Users/JonnyDesktop/Desktop/Eco 7.4/Eco_Data/Mono/libc
RPC lookup took: 4210.5637ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> PreLogin
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggingIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggingIn -> PreLogin
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggingIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggingIn -> PreLogin
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

</details>

**Comment by johnkslg** [comment]
Could be related to https://github.com/StrangeLoopGames/EcoIssues/issues/7546

What is your username @cuzitsjonny?

**Comment by cuzitsjonny** [comment]
I bought the game on the Eco website and then linked my Steam account with the SLG account. I can technically play the game on Steam, but I should be able to play using the non-Steam client too, right?

**Comment by cuzitsjonny** [comment]
Just to have that here:

My SLG ID is **slg132646**.

**Comment by rainfarmer** [comment]
I tried your login and it works for me, I emailed you a new password to try.
