### ISSUE TITLE
Crash while playing

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7545]
Initialize engine version: 2017.4.0f1 (b5bd171ee9ba)
Forcing GfxDevice: Direct3D 11
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1060 6GB (ID=0x1c03)
    Vendor:   NVIDIA
    VRAM:     6061 MB
    Driver:   23.21.13.8813
Begin MonoManager ReloadAssembly
- Completed reload, in  0.045 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Setting up 4 worker threads for Enlighten.
  Thread -> id: 23d88 -> priority: 1 
  Thread -> id: 43ce4 -> priority: 1 
  Thread -> id: 4383c -> priority: 1 
  Thread -> id: 20250 -> priority: 1 
UnloadTime: 3.197496 ms
Client version: 0.7.4.0 beta
Tuesday, May 01, 2018 1:59 PM
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/.\libc
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
RPC lookup took: 4116.073ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, StuffedElkObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at PostProcessingManager.UpdateHypoxia () [0x00000] in <filename unknown>:0 
  at Eco.Shared.View.ISubscriberExtensions.SubscribeAndCall (ISubscriber s, System.String propname, System.Action changedCallback) [0x00000] in <filename unknown>:0 
  at PostProcessingManager.Start () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by johnkslg** [comment]
Any details on the crash they got?  Can we contact the user?  The exception in the log is an expected one and wouldnt lead to the crash.

**Comment by Nanders** [comment]
Crash was from me, wasn't doing anything crazy, was just walking around.

**Comment by johnkslg** [comment]
It seems to be missing the exception that actually caused the crash

**Comment by Nanders** [comment]
That was the entire contents of the logfile immediately following the crash, I didn't get a crashdump.

**Comment by Nanders** [comment]
Closing as cant repro
