### ISSUE TITLE
0.7.3.3 Beta Windows client Unexpected charter encountered

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#7547]
Version: 0.7.3.3 beta 

Steps to Reproduce:

1. Select User name and enter your user name 
2. go to the password field and enter your password 
3. press the login button 

Expected behavior:
A valid login response and being able to log into the game

Actual behavior:

I get a window that pops up with the error message 

"Failed to login Unexpected character encountered while parsing 
value: <. Line 2, position 1." 

I have tried this with two separate accounts and get the same error message
on both.  This is occurring around 5:43 PM MST (GMT-0700) on May 1 2018 
I was on the the  server I play on earlier today around 2:30 PM today and I was 
able to log in fine so I am suspecting that this is something on the server side. 

I am using the same password as I always have and have not changed it or anything
recently.  Running Windows 10 (64 bit) 

This is the server I am playing on 

http://104.192.227.90:6005/index.html
https://ecoservers.io/server/3765/

![eco unexpected character encountered may 1 2018](https://user-images.githubusercontent.com/38896397/39498815-99dfe9c6-4d67-11e8-88fb-71ab5214cbae.jpg)

**Comment by SeanAtr0n** [comment]
fixed
