### ISSUE TITLE
USER ISSUE: Shuck Clams recipe

### ISSUE THREAD

**Issue by Gnorm42** [StrangeLoopGames/EcoIssues#7549]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Have multiples of 5 clams in inventory and full skills for cost reduction, then attempt to use shuck clams recipe.

**Expected behavior:**
Recipe should only require 4 clams per output of 5 units.

**Actual behavior:**
Recipe is not utilizing the cost reduction for skill where it remains a 1-to-1 ratio of clams for input vs. the output.

**Comment by craig-jong** [comment]
The base cost of the recipe is 5 clams -> 1 fish flesh.

80% of 5 clams is a cost reduction of 4 clams. At least based on this math, the recipe is correct to offer a 1:1 ratio at maximum level.
