### ISSUE TITLE
Contract UI scroll rect clips contract icon

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7551]
![image](https://user-images.githubusercontent.com/6262198/39539112-ac2aa0f8-4df3-11e8-8e53-78eb6e21453a.png)

**Comment by WeaselDog** [comment]
No longer an issue with new work tab.
![WorkTab](https://user-images.githubusercontent.com/47330823/70870139-83eff600-1f44-11ea-87bb-2e782df666f9.png)
