### ISSUE TITLE
Weird piece appears in meteor destruct sequence

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7554]
![image](https://user-images.githubusercontent.com/3536496/39550225-6fdde9ee-4e15-11e8-8b20-ab92a767186b.png)

That big shrinking chunk in the center, thats new but shouldnt be there.

**Comment by keegan-o** [comment]
very hard to repro in new meteor destruct sequence, I don't think it's really an issue anymore.
