### ISSUE TITLE
USER ISSUE: Stuck in Entering World but if i press tab i can see ingame stuff

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#7555]
**Version:** 0.7.3.3 beta

The server this is happening on is The Lounge, 54.39.28.27:3004
i think the server is needing a restart but no admin available as yet, But if you press TAB you can see
![snap2193](https://user-images.githubusercontent.com/29383891/39550243-890092f8-4e58-11e8-9877-b4cab49ad076.png)
i can eat food open Minimap 
![snap2194](https://user-images.githubusercontent.com/29383891/39550315-b2688c40-4e58-11e8-8a5d-5fbc1fce86ae.png)
open and close backpack, move stuff from Toolbar to backpack, i can even chat, but nothing is showing in the world

**Comment by Conchipedia** [comment]
![snap2196](https://user-images.githubusercontent.com/29383891/39550827-9317f0f4-4e5a-11e8-94a7-d88c3205ce7f.png)

**Comment by MaxInertia** [comment]
Same thing for me here, however if you leave it sit for a couple minutes the world loads. Still, not everything is working as expected.

### Issue updating vehicle (and player?) positions?

The position of carts is not being updated. I drove my cart quite far to a shop, however I can still access the contents of stockpiles from home and the shop is not aware of the close proximity of my cart. It's been there for at least 10 minutes now.

On attempting to purchase something I can hold on my person from the shop, there is a ~10 second pause then I get pushed to the main screen with the message "Inactivity." appearing. This may imply issues with player positions as well? (Image below)

![eco 2018-05-02 4_40_23 pm](https://user-images.githubusercontent.com/12981415/39552716-f9bc460a-4e2f-11e8-8624-544a4a69765e.png)

I'm not sure about specifics of the implementation (regrettably I could not be a developer-level supporter), but if there's a game loop with a sequence of updates it may be getting cut off prior to the updating of vehicle (and possibly player) positions.

**Comment by metachronism** [comment]
should be fixed 7.4.0 release
