### ISSUE TITLE
Crash trying to connect 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7556]
Exception
Exception: KeyNotFoundException
Message:La clave proporcionada no se encontró en el diccionario.
HelpLink:
Source:System.Collections.Immutable
System.Collections.Generic.KeyNotFoundException: La clave proporcionada no se encontró en el diccionario.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Eco.Plugins.Networking.NetworkServer.<>cDisplayClass20_0.<ProcessIncomingDataMessage>b0(Object o)

--END DUMP--

**Comment by johnkslg** [comment]
Could this be related to your recent networking fixes?

**Comment by metachronism** [comment]
fixed 7.4.0 release
