### ISSUE TITLE
Law prevents killing of animals

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#7561]
Version: 0.7.3.3 beta

Steps to Reproduce:
N/A

Expected behavior: 
Law ability to be able to prevent the killing of an animal 

Actual behavior:

There is no way to stop people from actually killing an animal right now. And this
is clearly a bug. 

On the server I am playing on we have setup a Nature Reserve where I want animals to 
be protected. But you can't protect them.

What you need is a law that goes something like this 

"When Attempting to Kill  where (in district Nature Reserve) 
Prevent"

The name "Nature Reserve" is the name I gave my district but what ever you call
your district it you should be able to prevent the hunting of animals in it. 

Right now the only thing we could prevent is the harvesting of animals but it is 
too late once the animal is already dead laying on the ground. I want to prevent
the killing of animals in my nature reserve area. 
 

I would also say you need something as well for each animal  and if they are bellow 
a certain number to disallow them from being shot. 

"Prevent Action when attempting to Kill where species is Bison and is less than 100
Prevent" 

Your laws right now are quite lacking and this is clearly a bug right  by not allowing
the players to be able to setup a district and be able to protect the wild life in it
or to protect wild life if it drops bellow a certain number. 

I would also suggest the same for plants as well if they drop bellow a certain number
to prevent harvesting. 

Please add laws like this please ASAP!

**Comment by JamesTalon** [comment]
I use laws to do similar on my server, and Harvest prevents doing damage to the animal entirely, did not allow killing them. Had to repeal and replace the law to be more specific to crops so we COULD hunt animals in the district.

**Comment by MarjieAVolk** [comment]
Yes, it may be a confusing name, but Harvest will prevent damaging/killing an animal or plant.
