### ISSUE TITLE
USER ISSUE: Steel Floor Lamp texture is not glow

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7565]
**Version:** 0.7.4.0 beta staging-518a927f

**Steps to Reproduce:**
Place Steel Floor Lamp and power it.

**Expected behavior:**
Texture glow, like as Steel Table Lamp
![20180503125457_1](https://user-images.githubusercontent.com/4980243/39570524-39fc7d06-4ed1-11e8-9348-d98444fc395b.jpg)
![20180503125458_1](https://user-images.githubusercontent.com/4980243/39570527-3a27e5ae-4ed1-11e8-963d-bc0485b07526.jpg)

**Actual behavior:**
Texture dark, everytime.
![20180503125133_1](https://user-images.githubusercontent.com/4980243/39570542-4dbb9cf0-4ed1-11e8-847d-3e5f91162c52.jpg)
![20180503125137_1](https://user-images.githubusercontent.com/4980243/39570544-4ddd6ab0-4ed1-11e8-9f7c-7f6ae095e92d.jpg)
![20180503125053_1](https://user-images.githubusercontent.com/4980243/39570545-4e2d4422-4ed1-11e8-98d0-027805eaa7ca.jpg)
![20180503125105_1](https://user-images.githubusercontent.com/4980243/39570546-4e4d42a4-4ed1-11e8-8d3f-543f58cb9900.jpg)

**Comment by keegan-o** [comment]
Fixed in master and thus it will be fixed in 7.5

**Comment by SeanAtr0n** [comment]
also fixed in 7.4
