### ISSUE TITLE
[SUGGESTION] Possibility to switch tutorial off.

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#7568]
At least after the fifth new start, struggling against tutorial becomes boring.

**Comment by turnburgler** [comment]
Mouse-overing the tutorial window will show you a red X in the top right corner, click this and check "disable all tutorials", and they disappear!

**Comment by Nicolausi113** [comment]
Thanks, it works - so I close this entry.
