### ISSUE TITLE
Hoes are not working properly

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7569]
Via Forum member: http://ecoforum.strangeloopgames.com/topic/4550/hoes-funktionieren-nicht

"Hello,

For me, the Hoes do not work: both the Wooden Hoe and the Iron Hoe appears (even if the block is marked in green) neither a symbol (as in the ax: right click to perform the action) still happens when clicking something. Every 10-20 clicks, the sound comes as if something had happened, but even after many more clicks, the Earth does not change."

"I have already tried to modify the wooden hoe C# file, so that it doesn't check if theres a block above the current block, but that didn't help."

Running 7.3.3

**Comment by ShaydenMac** [comment]
"The problem is that the OnActLeft () method in HoeItem is not called (If you insert the code from OnActLeft () into the OnActLeft () method of the ShovelItem it works)."

**Comment by craig-jong** [comment]
All tools are hold to use - clicking doesn't really make sense in this case. Some tools may function if you click fast enough, but that's not the intended use-case.

The hoe does currently work in master and the current steam release. Please let me know if this issue comes up again.
