### ISSUE TITLE
Suggestion: Non-exclusive Fullscreen Mode

### ISSUE THREAD

**Issue by ChubbyQuokka** [StrangeLoopGames/EcoIssues#7572]
I realize that there is a slight performance-gain when using the exclusive fullscreen mode, but this makes it near impossible to use any secondary displays.

I would love to see an option to use a non-exclusive fullscreen mode, say maybe a "Borderless Window" checkbox when Fullscreen is enabled.

**Comment by SeanAtr0n** [comment]
added in 7.4
