### ISSUE TITLE
USER ISSUE: server crash on garbage

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7577]
**Version:** 0.7.5.0 beta staging-44bd0a06

**Steps to Reproduce:**
Try to launch server with save from prev bleeding_staging version.

**Expected behavior:**
Succeed

**Actual behavior:**
Server crash

removing "garbage" file from save - fix it.

[ServerCrash AggregateException 05042622.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1973426/ServerCrash.AggregateException.05042622.zip)
https://www.dropbox.com/s/8usq1oz655feoea/Save.zip?dl=1

**Comment by elfl0rd** [comment]
Still crashing on staging-a4fbe934
But different error.
New files.


[ServerCrash AggregateException 05054750.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1975988/ServerCrash.AggregateException.05054750.zip)
https://www.dropbox.com/s/qmh5fu8mueacxh2/Game2.zip?dl=1

**Comment by craig-jong** [comment]
This should be fixed in 7.4/whenever a new build of 7.5 happens. If it still happens, please let me know.
