### ISSUE TITLE
USER ISSUE: Elevator cabin collizion size

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7579]
**Version:** 0.7.5.0 beta staging-44bd0a06

**Steps to Reproduce:**
Place wooden elevator
(Look how cool it looks!)
Try to come down to 2x3 hole (cabin visual size)
![20180504100337_1](https://user-images.githubusercontent.com/4980243/39616111-84c0e30c-4f82-11e8-9e1c-38ec4c0178b1.jpg)

**Expected behavior:**
Working elevator! Woohoo!

**Actual behavior:**
Nothing.
Cabin require 2x5 hole to move, but it useless :(
![20180504100355_1](https://user-images.githubusercontent.com/4980243/39616113-88f69caa-4f82-11e8-94ed-00964e40bac9.jpg)

**Comment by elfl0rd** [comment]
@SeanAtr0n update bleeding staging please :3

**Comment by elfl0rd** [comment]
0.7.5.0 beta staging-7755333d - not fixed

**Comment by elfl0rd** [comment]
work
![20180525040000_1](https://user-images.githubusercontent.com/4980243/40520712-531a0b72-5fd0-11e8-86f6-d610c9291c16.jpg)
not work
![20180525040024_1](https://user-images.githubusercontent.com/4980243/40520725-591e04a6-5fd0-11e8-85ce-ca76ea64a858.jpg)

**Comment by SeanAtr0n** [comment]
doing a clean build fixed it 
![image](https://user-images.githubusercontent.com/774628/40562426-c25e5ee4-6015-11e8-9470-90fea3ad92bb.png)

**Comment by elfl0rd** [comment]
Wooohooo! After update it's working :) thx!
