### ISSUE TITLE
Waterfalls and doors are broke

### ISSUE THREAD

**Issue by SkarDungeon** [StrangeLoopGames/EcoIssues#7583]
Waterfalls rolling water isn't there and doors are reverted back to the blocks with directionals on them

**Comment by SkarDungeon** [comment]
![image](https://user-images.githubusercontent.com/38991481/39650974-c938b5fa-4faf-11e8-8a53-4e0c79a77b3e.png)

**Comment by SkarDungeon** [comment]
![image](https://user-images.githubusercontent.com/38991481/39651038-09cfb302-4fb0-11e8-84a9-9fa3457515cd.png)
Just saw this as well

**Comment by keegan-o** [comment]
Was a shader problem due to unity versions that was fixed.
