### ISSUE TITLE
USER ISSUE: Waterfalls broke

### ISSUE THREAD

**Issue by SkarDungeon** [StrangeLoopGames/EcoIssues#7586]
**Version:** 0.7.5.0 beta staging-44bd0a06

**Steps to Reproduce:**
Logging in

**Expected behavior:**
Roling water

**Actual behavior:**
is a bunch of squares

<details>
<summary>Log File</summary>(...previous log truncated...)

onnecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[04:09] Connecting via Lidgren to localhost:3000
Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoadingWorld -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'MovingPlatform') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'MovingPlatform') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'MovingPlatform') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'MovingPlatform') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'MovingPlatform') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, StuffedElkObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at PostProcessingManager.UpdateHypoxia () [0x00000] in <filename unknown>:0 
  at Eco.Shared.View.ISubscriberExtensions.SubscribeAndCall (ISubscriber s, System.String propname, System.Action changedCallback) [0x00000] in <filename unknown>:0 
  at PostProcessingManager.Start () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

Couldn't find mapping for object 'DoorObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'DoorObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'DoorObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

</details>

**Comment by SeanAtr0n** [comment]
fixed in next build
