### ISSUE TITLE
Connection Failed between versions 7.4 to 7.5

### ISSUE THREAD

**Issue by dwujcik** [StrangeLoopGames/EcoIssues#7589]
Version 7.4
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host

Log File:
Initialize engine version: 2017.4.0f1 (b5bd171ee9ba)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 670 (ID=0x1189)
    Vendor:   NVIDIA
    VRAM:     2017 MB
    Driver:   23.21.13.8859
Begin MonoManager ReloadAssembly
- Completed reload, in  0.927 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Setting up 4 worker threads for Enlighten.
  Thread -> id: b20 -> priority: 1 
  Thread -> id: 1b70 -> priority: 1 
  Thread -> id: 28c0 -> priority: 1 
  Thread -> id: d94 -> priority: 1 
UnloadTime: 4.908484 ms
Client version: 0.7.4.0 beta staging-518a927f
Monday, April 30, 2018 9:42 PM
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/.\libc
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
RPC lookup took: 8334.5427ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

[52:15] Stopping existing server.Changing state: LoggedIn -> LoadingWorld
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.4.0 beta staging-518a927f

LocalServer -  Server Initialization... 

LocalServer -  Starting LocalizationPlugin... 

LocalServer -  Starting ModKitPlugin... 

LocalServer -  Loading mods... 

LocalServer -  Starting NetworkManager... 

LocalServer -  Initializing items... 

LocalServer -  Starting WorldGeneratorPlugin... 

LocalServer -  Starting GameplayStatsPlugin... 

LocalServer -  Starting BackupPlugin... 

LocalServer -  Starting StorageManager... 

LocalServer -  Initializing skills... 

LocalServer -  Starting StatDatabase... 

LocalServer -  Starting WorldPlugin... 

LocalServer -  Loading World... 

LocalServer -  Initializing world... 

LocalServer -  Starting TimePlugin... 

LocalServer -  Loading Time... 

LocalServer -  Starting ReputationPlugin... 

LocalServer -  Loading Reputation... 

LocalServer -  Starting PlayerHousingManager... 

LocalServer -  Starting UserManager... 

LocalServer -  Loading Users... 

LocalServer -  Initializing inventories... 

LocalServer -  Starting EcoObjectManager... 

LocalServer -  Loading Objects... 

LocalServer -  Starting ControllerManager... 

LocalServer -  Starting PropertyManager... 

LocalServer -  Starting ChatServer... 

LocalServer -  Starting WirePlugin... 

LocalServer -  Starting DisasterPlugin... 

LocalServer -  Starting DifficultySettings... 

LocalServer -  Starting GarbagePlugin... 

LocalServer -  Starting EcoSim... 

LocalServer -  Loading Property... 

LocalServer -  Loading Garbage... 

LocalServer -  Loading Disasters... 

LocalServer -  Loading Chat... 

LocalServer -  Starting MinimapManager... 

LocalServer -  Loading Plants... 

LocalServer -  Initializing plants... 

LocalServer -  Starting RouteProbingPlugin... 

LocalServer -  Loading RouteProbing... 

LocalServer -  Starting WorldLayerManager... 

LocalServer -  Loading Layers... 

LocalServer -  Initializing world layers... 

LocalServer -  Loading ClimateSim... 

LocalServer -  Starting EconomyTracker... 

LocalServer -  Starting WorldObjectManager... 

LocalServer -  Loading WorldObjects... 

LocalServer -  Starting EconomyPlugin... 

LocalServer -  Loading Economy... 

LocalServer -  Starting RoomPlugin... 

LocalServer -  Loading Rooms... 

LocalServer -  Starting ObjectivePlugin... 

LocalServer -  Loading Objectives... 

LocalServer -  Starting Legislation... 

LocalServer -  Loading Laws... 

LocalServer -  Starting WebServerPlugin... 

LocalServer -  Starting HousingTierDefinition... 

LocalServer -  Initializing LocalizationPlugin... 

LocalServer -  Initializing WorldGeneratorPlugin... 

LocalServer -  Initializing UserManager... 

LocalServer -  Initializing MinimapManager... 

LocalServer -  Initializing WorldObjectManager... 

LocalServer -  Initializing RoomPlugin... 

LocalServer -  Initializing HousingTierDefinition... 

LocalServer -  Initializing WorldPlugin... 

LocalServer -  Ticking... 

LocalServer -  Compressing... 

LocalServer -  Initializing WorldLayerManager... 

LocalServer -  Initializing WebServerPlugin... 

LocalServer -  Server Initialization finished in 13�206,4ms

Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[52:29] Connecting via Lidgren to localhost:3000
Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoadingWorld -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[52:44] Disconnected from server.Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

[52:50] Stopping existing server.Changing state: LoggedIn -> LoadingWorld
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.4.0 beta staging-518a927f

LocalServer -  Server Initialization... 

LocalServer -  Starting LocalizationPlugin... 

LocalServer -  Starting ModKitPlugin... 

LocalServer -  Loading mods... 

LocalServer -  Starting NetworkManager... 

LocalServer -  Initializing items... 

LocalServer -  Starting WorldGeneratorPlugin... 

LocalServer -  Starting GameplayStatsPlugin... 

LocalServer -  Starting BackupPlugin... 

LocalServer -  Starting StorageManager... 

LocalServer -  Initializing skills... 

LocalServer -  Starting StatDatabase... 

LocalServer -  Starting WorldPlugin... 

LocalServer -  Loading World... 

LocalServer -  Initializing world... 

LocalServer -  Starting TimePlugin... 

LocalServer -  Loading Time... 

LocalServer -  Starting ReputationPlugin... 

LocalServer -  Loading Reputation... 

LocalServer -  Starting PlayerHousingManager... 

LocalServer -  Starting UserManager... 

LocalServer -  Loading Users... 

LocalServer -  Initializing inventories... 

LocalServer -  Starting EcoObjectManager... 

LocalServer -  Loading Objects... 

LocalServer -  Starting GarbagePlugin... 

LocalServer -  Starting ControllerManager... 

LocalServer -  Starting PropertyManager... 

LocalServer -  Starting WirePlugin... 

LocalServer -  Loading Garbage... 

LocalServer -  Starting EcoSim... 

LocalServer -  Starting DifficultySettings... 

LocalServer -  Starting ChatServer... 

LocalServer -  Starting DisasterPlugin... 

LocalServer -  Loading Property... 

LocalServer -  Loading Disasters... 

LocalServer -  Loading Chat... 

LocalServer -  Starting MinimapManager... 

LocalServer -  Loading Plants... 

LocalServer -  Initializing plants... 

LocalServer -  Starting RouteProbingPlugin... 

LocalServer -  Loading RouteProbing... 

LocalServer -  Starting WorldLayerManager... 

LocalServer -  Loading Layers... 

LocalServer -  Initializing world layers... 

LocalServer -  Loading ClimateSim... 

LocalServer -  Starting EconomyTracker... 

LocalServer -  Starting WorldObjectManager... 

LocalServer -  Loading WorldObjects... 

LocalServer -  Starting EconomyPlugin... 

LocalServer -  Loading Economy... 

LocalServer -  Starting RoomPlugin... 

LocalServer -  Loading Rooms... 

LocalServer -  Starting ObjectivePlugin... 

LocalServer -  Loading Objectives... 

LocalServer -  Starting Legislation... 

LocalServer -  Loading Laws... 

LocalServer -  Starting WebServerPlugin... 

LocalServer -  Starting HousingTierDefinition... 

LocalServer -  Initializing LocalizationPlugin... 

LocalServer -  Initializing WorldGeneratorPlugin... 

LocalServer -  Initializing UserManager... 

LocalServer -  Initializing MinimapManager... 

LocalServer -  Initializing WorldObjectManager... 

LocalServer -  Initializing RoomPlugin... 

LocalServer -  Initializing HousingTierDefinition... 

LocalServer -  Initializing WorldPlugin... 

LocalServer -  Ticking... 

LocalServer -  Compressing... 

LocalServer -  Initializing WorldLayerManager... 

LocalServer -  Initializing WebServerPlugin... 

LocalServer -  Server Initialization finished in 13�146,2ms

Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[53:03] Connecting via Lidgren to localhost:3000
Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoadingWorld -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[53:18] Disconnected from server.Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Version 7.5
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 670 (ID=0x1189)
    Vendor:   NVIDIA
    VRAM:     2017 MB
    Driver:   23.21.13.8859
Begin MonoManager ReloadAssembly
- Completed reload, in  0.893 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
UnloadTime: 2.142950 ms
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/.\libc
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
[02:22] Stopping existing server.LocalServer -  Eco Server 0.7.5.0 beta staging-7be2f02c

LocalServer -  Server Initialization... 

LocalServer -  Starting LocalizationPlugin... 

LocalServer -  Starting ModKitPlugin... 

LocalServer -  Compiling mods... 

LocalServer -  Starting NetworkManager... 

LocalServer -  Initializing items... 

LocalServer -  Starting WorldGeneratorPlugin... 

LocalServer -  Starting GameplayStatsPlugin... 

LocalServer -  Starting BackupPlugin... 

LocalServer -  Starting StorageManager... 

LocalServer -  Initializing skills... 

LocalServer -  Starting StatDatabase... 

LocalServer -  Starting WorldPlugin... 

LocalServer -  Loading World... 

LocalServer -  Converting world to new format... 

LocalServer -  Initializing world... 

LocalServer -  Starting TimePlugin... 

LocalServer -  Loading Time... 

LocalServer -  Starting ReputationPlugin... 

LocalServer -  Loading Reputation... 

LocalServer -  Starting PlayerHousingManager... 

LocalServer -  Starting UserManager... 

LocalServer -  Loading Users... 

LocalServer -  Initializing inventories... 

LocalServer -  Starting EcoObjectManager... 

LocalServer -  Loading Objects... 

LocalServer -  Starting ControllerManager... 

LocalServer -  Starting DifficultySettings... 

LocalServer -  Starting ChatServer... 

LocalServer -  Starting PropertyManager... 

LocalServer -  Starting DisasterPlugin... 

LocalServer -  Starting EcoSim... 

LocalServer -  Starting GarbagePlugin... 

LocalServer -  Starting WirePlugin... 

LocalServer -  Loading Property... 

LocalServer -  Loading Garbage... 

LocalServer -  Loading Disasters... 

LocalServer -  Loading Chat... 

LocalServer -  Starting MinimapManager... 

LocalServer -  Loading Plants... 

LocalServer -  Initializing plants... 

LocalServer -  Starting RouteProbingPlugin... 

LocalServer -  Loading RouteProbing... 

LocalServer -  Starting WorldLayerManager... 

LocalServer -  Loading Layers... 

LocalServer -  Initializing world layers... 

LocalServer -  Loading ClimateSim... 

LocalServer -  Starting EconomyTracker... 

LocalServer -  Starting WorldObjectManager... 

LocalServer -  Loading WorldObjects... 

LocalServer -  Starting EconomyPlugin... 

LocalServer -  Loading Economy... 

LocalServer -  Starting RoomPlugin... 

LocalServer -  Loading Rooms... 

LocalServer -  Starting ObjectivePlugin... 

LocalServer -  Loading Objectives... 

LocalServer -  Starting Legislation... 

LocalServer -  Loading Laws... 

LocalServer -  Starting WebServerPlugin... 

LocalServer -  Starting HousingTierDefinition... 

LocalServer -  Initializing LocalizationPlugin... 

LocalServer -  Initializing WorldGeneratorPlugin... 

LocalServer -  Initializing UserManager... 

LocalServer -  Initializing MinimapManager... 

LocalServer -  Initializing WorldObjectManager... 

LocalServer -  Initializing RoomPlugin... 

LocalServer -  Initializing HousingTierDefinition... 

LocalServer -  Initializing WorldPlugin... 

LocalServer -  Ticking... 

LocalServer -  Compressing... 

LocalServer -  Saving world... 

LocalServer -  Initializing WorldLayerManager... 

LocalServer -  Initializing WebServerPlugin... 

LocalServer -  Server Initialization finished in 25�244,2ms

Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[02:48] Connecting via Lidgren to localhost:3000
Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[03:03] Disconnected from server.Shutting down server
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by armyofskankz** [comment]
Same error, here is my log

<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GT 640M LE  (ID=0xfd3)
    Vendor:   NVIDIA
    VRAM:     2017 MB
    Driver:   21.21.13.7254
Begin MonoManager ReloadAssembly
- Completed reload, in  0.099 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
UnloadTime: 5.165824 ms
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/.\libc
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
[41:23] Stopping existing server.LocalServer -  Eco Server 0.7.5.0 beta staging-7be2f02c

LocalServer -  Server Initialization... 

LocalServer -  Starting LocalizationPlugin... 

LocalServer -  Starting ModKitPlugin... 

LocalServer -  Loading mods... 

LocalServer -  Starting NetworkManager... 

LocalServer -  Initializing items... 

LocalServer -  Starting WorldGeneratorPlugin... 

LocalServer -  Starting GameplayStatsPlugin... 

LocalServer -  Starting BackupPlugin... 

LocalServer -  Starting StorageManager... 

LocalServer -  Initializing skills... 

LocalServer -  Starting StatDatabase... 

LocalServer -  Starting WorldPlugin... 

LocalServer -  Loading World... 

LocalServer -  Converting world to new format... 

LocalServer -  Initializing world... 

LocalServer -  Starting TimePlugin... 

LocalServer -  Loading Time... 

LocalServer -  Starting ReputationPlugin... 

LocalServer -  Loading Reputation... 

LocalServer -  Starting PlayerHousingManager... 

LocalServer -  Starting UserManager... 

LocalServer -  Loading Users... 

LocalServer -  Initializing inventories... 

LocalServer -  Starting EcoObjectManager... 

LocalServer -  Loading Objects... 

LocalServer -  Starting ControllerManager... 

LocalServer -  Starting ChatServer... 

LocalServer -  Starting PropertyManager... 

LocalServer -  Starting WirePlugin... 

LocalServer -  Starting DisasterPlugin... 

LocalServer -  Starting DifficultySettings... 

LocalServer -  Starting GarbagePlugin... 

LocalServer -  Loading Property... 

LocalServer -  Starting EcoSim... 

LocalServer -  Loading Disasters... 

LocalServer -  Loading Garbage... 

LocalServer -  Starting MinimapManager... 

LocalServer -  Loading Chat... 

LocalServer -  Loading Plants... 

LocalServer -  Initializing plants... 

LocalServer -  Starting RouteProbingPlugin... 

LocalServer -  Loading RouteProbing... 

LocalServer -  Starting WorldLayerManager... 

LocalServer -  Loading Layers... 

LocalServer -  Initializing world layers... 

LocalServer -  Loading ClimateSim... 

LocalServer -  Starting EconomyTracker... 

LocalServer -  Starting WorldObjectManager... 

LocalServer -  Loading WorldObjects... 

LocalServer -  Starting EconomyPlugin... 

LocalServer -  Loading Economy... 

LocalServer -  Starting RoomPlugin... 

LocalServer -  Loading Rooms... 

LocalServer -  Starting ObjectivePlugin... 

LocalServer -  Loading Objectives... 

LocalServer -  Starting Legislation... 

LocalServer -  Loading Laws... 

LocalServer -  Server Initialization finished in 31,268.7ms

Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[41:54] Connecting via Lidgren to localhost:3000
Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[42:09] Disconnected from server.

**Comment by metachronism** [comment]
no response - seems like the local server crashed
