### ISSUE TITLE
USER ISSUE: Stuck in a pipe

### ISSUE THREAD

**Issue by memeToasty** [StrangeLoopGames/EcoIssues#7591]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
1. go underwater
2. place a pipe in front and behind of you
3. go with your head to the height of the pipes
4. place a pipe in the place, where the 2 pipes would connect to each other (the block, where your head is)
5. your stuck

**Expected behavior:**
It should have glitched me out or would prevent me from placing the pipe in some way

**Actual behavior:**
Instead it let me place the pipe inside of my head

**Comment by pamduncan** [comment]
did you try the /unstuck command?  Often when stuck you won't glitch out but /unstuck is there to get you out

**Comment by SlayksWood** [comment]
Seems fixed.
