### ISSUE TITLE
[.7.4.-beta-staging-518a927f] hashing passwords again/still if password is used

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7592]
I was not using passwords on my 7.4 server so did not see this happening again until I updated my modding server to the last 7.4 and this server is password protected.  This had happened earlier in 7.4 but was fixed I thought but during this time I also had stopped using a password on my server.  If you do not use a password you do not get the hash, and I believe last time you were getting the has with or without a password set.  If I delete the password the field does stay empty but as soon as password is added it shows up as a hash

[![Screenshot from Gyazo](https://gyazo.com/3c6d47724724f59421641a33a2e88faf/raw)](https://gyazo.com/3c6d47724724f59421641a33a2e88faf)

**Comment by pamduncan** [comment]
The old bug report from when this was fixed before is here:.  https://github.com/StrangeLoopGames/EcoIssues/issues/7592  I remember it was being populated with a hash with or without a password in use at that time so not sure if both were fixed or no one noticed that passwords when in use still generated a hash..   If I remove the password from the setting in the config the had does not populated but when a password is there it does.   Here are screenshots from my server before and after I start it up after adding a password.  I have been able to reproduce this about a dozen times.  I have checked with other server owners running 7.4 and they all are not using passwords, or if using passwords they are also using a whitelist so no one would be trying to put in a password and hit this issue, so I think its maybe been unnoticed that use of passwords are creating a hash but if no password in in use the field is clear.    Running with password:  When I first started an newly updated server on latest 7.4  with old world.  https://gyazo.com/3c6d47724724f59421641a33a2e88faf  
then the password removed but same world  :  https://gyazo.com/c42526e451cf5b5f651d7d334038edc3  then when password is added back and a newly generated world (not that i imagine a save game would have any effect):  https://gyazo.com/1e52a89c64543d81d1e33a70a54b420d     https://gyazo.com/2f8a8aeef2b6ce1bc46f6ef533283f86

**Comment by MarjieAVolk** [comment]
This sounds like correct behavior to me.  When a password is present, it shows a hash of the password.  When a password is not present, it shows as empty.  Right?  And entering the password in game works as expected?

The password is shown as a hash there for security reasons, so you don't have to worry about leaving the window open with the password just showing there.  Although I could see there being better solutions for this, such as asterisks and maybe a 'show' button.

**Comment by pamduncan** [comment]
How do other admins retrieve passwords without going to the config files?  And as soon as a Fille >Save is done in the Server UI that hash is saved to the config file and the set password is lost.  [![Screenshot from Gyazo](https://gyazo.com/ac4891a5d40a3aec51bed76d0cd7f32e/raw)](https://gyazo.com/ac4891a5d40a3aec51bed76d0cd7f32e) 

This means that any password change that takes place immediately overwrites the config file with the hash and so admins have no way to determine the password and can do nothing but change it as there is no way to retrieve it. 

This also means that any commercial host whose game panel reads from the configs ends up with the hash overwriting the password setting mad by the user and no way to retrieve the password.  I guess and ingame command could be made that would give an admin the password but that is more liable to be a security issue then the chance that some one might get in your house and see your computer screen.

 Yes, the server UI remains active on the desktop or within interactive desktop so if its your computer at home anyone walking by the screen could see the password.  If its a remotely hosted server no one would would just walk by and see it they would have to RDP into the desktop and if it is a game hosted server no one but the the support people who can rdp in to that server and have access would ever see it if they even run it with the server ui open (many use -nogiu switch or interactive desktop so its not in view).  

Also with a server on a hosting service some game control panels read the data that is in the config files  - the hash is not what is expected in that variable and therefore an error state is created for the game control panel or only part of the has is read as the password and when a save is made it sets up a new password and  a new hash and and any non whitelisted/admin player can no longer get in, admins cannot retrieve the new password a new hash is written, is partially picked up by the game control panel, seems as a new password and a loop through the system keeps going on.  The game control panels can be re-coded to accept the hash on read back but there is nothing in the system where one admin can verify a password once its been changed meaning many server owners may end up have to have admins post password in text in less secure places then the game itself.  And so the whole idea of password security actually ends up making it a good deal less secure then if it is in plain text in the Server UI.  I have my server UI's open on my desk top very often but since my front door is locked the chance of anyone player or stranger walking buy and stealing the password to get into the game is very slight - maybe the cleaning woman if I don't shut down at night but I dont think she wants to play on the server!  Having to now post the current password in discord or a form for the other admins is much less secure..  Also all that password will do is give someone access to the server.  If the find the server UI screen open on a desktop and wished to cause trouble they will add themselves as admin and not even worry about the password.  For a very low risk I think the hash behavior has really complicated things

**Comment by MarjieAVolk** [comment]
Server passwords are fixed up in the next hotfix
