### ISSUE TITLE
USER ISSUE: Tallow Lamp (Kiln)

### ISSUE THREAD

**Issue by XsExcess** [StrangeLoopGames/EcoIssues#7593]
**Version:** 0.7.3.3 beta
Currently gives:
0 Housing points
100% less Lighting points

Should really be:
2 Housing points
20% less Lighting points
Like all other Tallow items/Stone Brazier

Edit: The file for it (WorldObjects\TallowLamp.cs) is correct,

**Comment by craig-jong** [comment]
fixed in above pr
