### ISSUE TITLE
USER ISSUE: "car stockpile" moving textures.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7596]
Version: 0.7.5.0 beta staging-7be2f02c
See video
https://youtu.be/_cNoKc2lsrM

**Comment by elfl0rd** [comment]
Same on crane cargo.

**Comment by johnkslg** [comment]
This is borderline high priority because its such an obvious bug.

**Comment by SeanAtr0n** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/2971

**Comment by elfl0rd** [comment]
not fully fixed https://youtu.be/DQfJHJA-v9w

**Comment by SeanAtr0n** [comment]
oh man, this is like super duper critical >.> better hotfix it
