### ISSUE TITLE
USER ISSUE: Cant reorder linked inventory

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7597]
Version: 0.7.5.0 beta staging-7be2f02c
You can't move linked inventory, if they inventory have secondary, pinned inventory.
Excavator, SkidSteer, Trucks, etc.
They can be moved, bur after release, its jump back.
See video.
https://youtu.be/LNCpaYhVsKY

**Comment by elfl0rd** [comment]
Looks like as https://github.com/StrangeLoopGames/EcoIssues/issues/5087

**Comment by elfl0rd** [comment]
And https://github.com/StrangeLoopGames/EcoIssues/issues/4501

**Comment by MarjieAVolk** [comment]
I believe this was fixed by the updates to linked inventories, which allows the normal inventory and the fuel supply to be treated completely independently.

**Comment by MarjieAVolk** [comment]
Oops, this fix is not released yet, it will be in 7.6

**Comment by elfl0rd** [comment]
Still here in latest BE and release.
@MarjieAVolk

**Comment by elfl0rd** [comment]
And you cannot reorder vehicle inventory... (Fuel lower than bed)

**Comment by MarjieAVolk** [comment]
I just tested this out on bleeding edge, and it's working for me.

**Comment by MarjieAVolk** [comment]
I wonder if this has to do with a slow connection?

**Comment by elfl0rd** [comment]
Local server...

**Comment by elfl0rd** [comment]
So... i update BE now, looks fixed in staging-2b46eb65
Closing.
