### ISSUE TITLE
Steel recipe is wrong

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#7599]
Version: 0.7.3.3 beta

Steps to Reproduce:

1.  Go a blast furnace and look at the recipe  for steel

Expected behavior:

For there to be a correct recipe for steel

Actual behavior:

The recipe to make steel is totally wrong.   Right now at the Blast Furnace 
it says to make steel you need 4 Iron Ingots.  By putting 4 Iron Ingots 
alone in the blast Furnace  you are not making steel you are making Iron. 

The recipe for Steel is incorrect. 

IF you want to base how steel is made in a real life situation in game then 
the recipe should be something like 3 Iron Ingots and 1 coal. 

It is the coal that gives you the added carbon to actually turn it into steel. 

http://www.keenovens.com/articles/steel-furnance.htm

"To make steel, iron ore is first mined from the ground. It is then smelted in blast furnaces where the impurities are removed and carbon is added. In fact, a very simple definition of steel is "iron alloyed with carbon, usually less than 1%.""

Can you please correct the recipe for steel on the blast furnace in game please. 

![eco steel recipe](https://user-images.githubusercontent.com/38896397/39676416-b3ead7cc-5127-11e8-8be0-1b8ff18ed9a8.jpg)

**Comment by elfl0rd** [comment]
Yes, more coal use!
Want it :)

**Comment by craig-jong** [comment]
Steel recipe was changed to include this.
