### ISSUE TITLE
5Pre3 Workbench dont need a building to work

### ISSUE THREAD

**Issue by Gemji1990** [StrangeLoopGames/EcoIssues#760]
have seen this problem with 5Pre2 but then the workbench and the bakingoven needed one building.
about anyting else didint need one to function right

**Comment by panisch420** [comment]
yup. these are functioning
![screenshot_574](https://cloud.githubusercontent.com/assets/22756750/19870771/4f0b7118-9fb2-11e6-9359-33f83c6d0dc9.png)

**Comment by johnkslg** [comment]
Thanks guys will get this fixed
