### ISSUE TITLE
USER ISSUE: Stuffed Elk - no model

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7600]
**Version:** 0.7.5.0 beta staging-7be2f02c
![20180507004231_1](https://user-images.githubusercontent.com/4980243/39678130-a666f1a4-518f-11e8-839d-814798166fc3.jpg)

**Comment by craig-jong** [comment]
Should be fixed in the next build of staging.

**Comment by elfl0rd** [comment]
@craig-jong fixed, but icon now have a X mark...
