### ISSUE TITLE
7.4.0 Crash when mining coal

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7602]
From Steam https://steamcommunity.com/app/382310/discussions/4/1694920442948465870/: 

Client version: 0.7.4.0 beta staging-518a927f

error log

server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
HelpLink:
Source:Eco.Core
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
at Eco.Core.Serialization.ZipBlob.Delete()
at Eco.Gameplay.Objects.EcoObjectManager.Remove(IEcoObject ecoObject)
at Eco.Gameplay.Objects.RubbleObject`1.TryPickup(Inventory inv)
at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>

Log File:
Initialize engine version: 2017.4.0f1 (b5bd171ee9ba)
GfxDevice: creating device client; threaded=1
Direct3D:
Version: Direct3D 11.0 [level 11.1]
Renderer: NVIDIA GeForce GTX 960 (ID=0x1401)
Vendor: NVIDIA
VRAM: 4062 MB
Driver: 23.21.13.8813
Begin MonoManager ReloadAssembly
- Completed reload, in 1.478 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Camera') is missing!

(Filename: Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Setting up 4 worker threads for Enlighten.
Thread -> id: c14 -> priority: 1 
Thread -> id: 2084 -> priority: 1 
Thread -> id: 29c0 -> priority: 1 
Thread -> id: 24f0 -> priority: 1 
UnloadTime: 3.589107 ms
Client version: 0.7.4.0 beta staging-518a927f
Monday, April 30, 2018 9:42 PM

(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fallback handler could not load library E:/Games/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
Fallback handler could not load library E:/Games/Steam/steamapps/common/Eco/Eco_Data/Mono/.\libc
Fallback handler could not load library E:/Games/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
RPC lookup took: 5423.1919ms

(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn

(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[52:28] Stopping existing server.Changing state: LoggedIn -> LoadingWorld

(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer - Eco Server 0.7.4.0 beta staging-518a927f

LocalServer - Server Initialization... 

LocalServer - Starting LocalizationPlugin... 

LocalServer - Starting ModKitPlugin... 

LocalServer - Compiling mods... 

LocalServer - Starting NetworkManager... 

LocalServer - Initializing items... 

LocalServer - Starting WorldGeneratorPlugin... 

LocalServer - Starting GameplayStatsPlugin... 

LocalServer - Starting BackupPlugin... 

LocalServer - Starting StorageManager... 

LocalServer - Initializing skills... 

LocalServer - Starting StatDatabase... 

LocalServer - Starting WorldPlugin... 

LocalServer - Loading World... 

LocalServer - Converting world to new format... 

LocalServer - Initializing world... 

LocalServer - Starting TimePlugin... 

LocalServer - Loading Time... 

LocalServer - Starting ReputationPlugin... 

LocalServer - Loading Reputation... 

LocalServer - Starting PlayerHousingManager... 

LocalServer - Starting UserManager... 

LocalServer - Loading Users... 

LocalServer - Initializing inventories... 

LocalServer - Starting EcoObjectManager... 

LocalServer - Loading Objects... 

LocalServer - Starting GarbagePlugin... 

LocalServer - Starting ControllerManager... 

LocalServer - Starting ChatServer... 

LocalServer - Starting DisasterPlugin... 

LocalServer - Starting WirePlugin... 

LocalServer - Starting DifficultySettings... 

LocalServer - Starting PropertyManager... 

LocalServer - Loading Garbage... 

LocalServer - Starting EcoSim... 

LocalServer - Loading Property... 

LocalServer - Loading Disasters... 

LocalServer - Loading Chat... 

LocalServer - Starting MinimapManager... 

LocalServer - Loading Plants... 

LocalServer - Initializing plants... 

LocalServer - Starting RouteProbingPlugin... 

LocalServer - Loading RouteProbing... 

LocalServer - Starting WorldLayerManager... 

LocalServer - Loading Layers... 

LocalServer - Initializing world layers... 

LocalServer - Loading ClimateSim... 

LocalServer - Starting EconomyTracker... 

LocalServer - Starting WorldObjectManager... 

LocalServer - Loading WorldObjects... 

LocalServer - Starting EconomyPlugin... 

LocalServer - Loading Economy... 

LocalServer - Starting RoomPlugin... 

LocalServer - Loading Rooms... 

LocalServer - Starting ObjectivePlugin... 

LocalServer - Loading Objectives... 

LocalServer - Starting Legislation... 

LocalServer - Loading Laws... 

LocalServer - Starting WebServerPlugin... 

LocalServer - Starting HousingTierDefinition... 

LocalServer - Initializing LocalizationPlugin... 

LocalServer - Initializing WorldGeneratorPlugin... 

LocalServer - Initializing UserManager... 

LocalServer - Initializing MinimapManager... 

LocalServer - Initializing WorldObjectManager... 

LocalServer - Initializing RoomPlugin... 

LocalServer - Initializing HousingTierDefinition... 

LocalServer - Initializing WorldPlugin... 

LocalServer - Ticking... 

LocalServer - Compressing... 

LocalServer - Saving world... 

LocalServer - Initializing WorldLayerManager... 

LocalServer - Initializing WebServerPlugin... 

LocalServer - Server Initialization finished in 427.231,4ms

Connecting to local host.

(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[59:38] Connecting via Lidgren to localhost:3000
Connection complete.

(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoadingWorld -> Connecting

(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!

(Filename: Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!

(Filename: Line: 1758)

Missing following icons: HandPloughItem, LargeHangingHewnLogSignItem, LargeHangingLumberSignItem, LargeHangingStoneSignItem, LargeStandingHewnLogSignItem, LargeStandingLumberSignItem, LargeStandingStoneSignItem, SkidSteerItem, SmallHangingHewnLogSignItem, SmallHangingLumberSignItem, SmallHangingStoneSignItem, SmallStandingHewnLogSignItem, SmallStandingLumberSignItem, SmallStandingStoneSignItem, WheelbarrowItem

(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LargeHangingHewnLogSignObject, LargeHangingLumberSignObject, LargeHangingStoneSignObject, LargeStandingHewnLogSignObject, LargeStandingLumberSignObject, LargeStandingStoneSignObject, LogicGateObject, SmallHangingHewnLogSignObject, SmallHangingLumberSignObject, SmallHangingStoneSignObject, SmallStandingHewnLogSignObject, SmallStandingLumberSignObject, SmallStandingStoneSignObject, StuffedElkObject, SwitchObject

(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose

(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source

(Filename: Line: 707)

[22:32] Disconnected from server.Shutting down server

(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer - Saving...

LocalServer - Saving world... 

Changing state: PreLogin -> LoggedIn

(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer - Finished in 1.030,2msDone

---------------
This error happend while picking up mined coal pieces.

btw: It happens with all items that can be mined with a pickaxe.

**Comment by metachronism** [comment]
could not repro with 7.4.1, will monitor bug reports service for reoccurances
