### ISSUE TITLE
Masonry table timer bug?

### ISSUE THREAD

**Issue by ZeelNightwolf** [StrangeLoopGames/EcoIssues#7603]
I have a Masonry Table that has around 300 Grind to Sand going. I had another recipe after it and Im not sure when or how but the Grind to Sand duplicated on the Table. I thought it was a graphical bug and thought nothing of it. 

I decided i wanted to move the table but due to the amount of stone it wouldnt empty to a stockpile. I made stockpiles to fill them and cancelled the project. the stone emptied and the first grind to stone disappeared the second did not.

I then cleared the stockpiles and tried to cancel it. It filled the stockpile and the grind to sand crafting remained. 

I have just over 20hrs remaining on this crafting job. It will not remove.

There is no server error report. 

Server: Saphira-Moon.....
Location of table is around 625,711

(we know we can devtool it but thought you might want to look at it)

**Comment by craig-jong** [comment]
Ideally I would have wanted a save along with this, but I was slow so I understand if that's not possible.

Let me know if you can get a save (possibly a backup) of when the messed up work order existed.

**Comment by craig-jong** [comment]
closing for no response. Let me know if you have more information or this occurs again and I'd be happy to take a look.
