### ISSUE TITLE
USER ISSUE: Cannot access crash files

### ISSUE THREAD

**Issue by heimskringla** [StrangeLoopGames/EcoIssues#7604]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
wait for a crash

**Expected behavior:**
Crashed eco should relinquish the input focus so that crash file can be opened

**Actual behavior:**
Input focus stays with crashed program. Eventually eco will shut down completely, but by then the dialogue which leads to the crash file is gone. Neither can I then find a file "crash_2018..." etc on the computer.

**Comment by heimskringla** [comment]
Question: Are the crash files stored on the client or on the server? What is the path? 
As I am experiencing daily crahes since ca May 1 I would love to send you the Data, but cant find them so no clue what's the matter. Crashes random, just when walking.

**Comment by heimskringla** [comment]
sorry, closed by mistake

**Comment by metachronism** [comment]
closing as wont fix;  crash dumps are controlled by unity, we cant pick where they are placed
8.0 should have this a bit better, however.

Server dumps are stored in server/dump, and logged to our central server
