### ISSUE TITLE
Autogen templates should be excluded from localization table scraping

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#7605]
Looks like macro strings in autogen are making their way into the translation tables, eg. BuildingModuleTemplate line 55: `Category = Localizer.Do("_HousingCategory_"),`  All of these template files should probably be manually excluded from whatever string scraping you're doing.

**Comment by Nanders** [comment]
This is intended, and is OK

**Comment by MarjieAVolk** [comment]
I am not sure now whether what I originally said is true or how I knew that, but it looks like what I was saying is that the actual string "_HousingCategory_" was getting translated.  That's not actually a real display string, so that doesn't need to get translated.
