### ISSUE TITLE
[Suggestion] World Gen Settings

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7606]
From the support queue:

Dear Strange Loop Games,

 

I have another suggestion for an update. I was playing Eco a while back and I’m thinking that it would be nice to have settings and presets for individual worlds; like world size, the rarity of natural resources like gold, iron, and coal, and how much water is in a world; the size of the ocean and rivers.

I Would like this in another update. Also this would help build a different type of world ecosystem.

 

Example

                                                                Settings

Iron Rarity: select one; SUPER RARE         RARE       NORMAL          MORE       **LOTS**       ALMOST,EVERYWHERE 

Gold Rarity: select one; **SUPER RARE**        RARE       NORMAL          MORE       LOSTS       ALMOST,EVERYWHERE

Copper Rarity: select one; SUPER RARE   RARE       NORMAL          MORE       LOSTS       **ALMOST,EVERYWHERE**

Ocean Size: select one; NONE  -x20    -x15    **-x10**      -x5     NORMAL     x5       x10       x15          x20          HUGE

River Rarity: select one; SUPER RARE       **RARE**       NORMAL          MORE       LOSTS       ALMOST,EVERYWHERE

Land: select one; SUPER RARE     RARE       NORMAL          MORE       LOSTS       **ALMOST,EVERYWHERE**

World Size: select one; NORMAL     x5          x10       **x15**          x20          HUGE

 

NOTE: The bolded words are the selected ones for my example.

 -Sincerely Linvar13579

                                                                                                                                                                                A huge fan

**Comment by elfl0rd** [comment]
Addition, to vein generation.
Need 2 different option.
Size and Rarity.

**Comment by Nicolausi113** [comment]
Also a slider for landscape appearance, for example: flatland, alluvial, hilly, mountainous, bizarre.
The default settings of World Gen look rather bizarre (I have screwed them down a bit).

**Comment by elfl0rd** [comment]
yes!
Worldgen is very configurable, but it's not easy.
