### ISSUE TITLE
Stuck loading forever

### ISSUE THREAD

**Issue by ChristianMingle1** [StrangeLoopGames/EcoIssues#7610]
After launching game and clicking "Continue", it just randomly stops loading and shows the gear spinning, this goes on forever & the only way to fix it is closing the game and restarting. I would be more detailed, but it happens at different points in the loading, and seems random, although fairly frequent(about 4 times in past 15 loads)(maybe my files are just bugged tho, because I also have to wait through the "first time setup" every time i launch game). Version 7.4 staging

**Comment by metachronism** [comment]
should be fixed in the official 7.4.1+ release
