### ISSUE TITLE
USER ISSUE: Vehicles periodically jump from ramp.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7612]
Version: 0.7.5.0 beta staging-7be2f02c
Look video
https://youtu.be/1n_yTp8rWiU

**Comment by combatbanana** [comment]
still happening - not intermittent in some cases (ive been able to make my truck fly the same way every time by hitting this ramp on the edge (see video) and have been using it as a short cut since i land the same place each time) https://youtu.be/C1eikUjPoic

**Comment by elfl0rd** [comment]
Not happens after ramps are block.
