### ISSUE TITLE
New server browser: Private server shown as offline

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#7614]
Via Reddit:

"[–]Voguhl
Sadly the new connect Gui has its issues. Had to put my server to public for my friend to find the server and see it as online. Direct connect via favourites always showed it as offline."

**Comment by MarjieAVolk** [comment]
Okay I see the issue; even on the favorites tab, we're only looking up servers by lan and by public listings.  We still need a way to save ip address or something for favorites and look up server details with that, as an alternative/fallback.

**Comment by MarjieAVolk** [comment]
Didn't notice this since I only tested with LAN servers and public servers

**Comment by MarjieAVolk** [comment]
Well I am not sure if that comment is true now, we are actually querying favorite servers directly, and metachronism tells me that should work for non-public servers theoretically.  So I'm gonna need to get my hands on some test servers.

**Comment by MarjieAVolk** [comment]
Yeah, the request still goes through the master server, but it's a request for a specific server, which should work for both public and private servers, unlike the browse tab which will only show public servers.

So maybe this issue was related to the master server going down for a bit?

**Comment by elfl0rd** [comment]
(i really want real direct connection)

**Comment by MarjieAVolk** [comment]
Yeah the advantage of doing it this way is that it will handle NAT and such things for you, so there should be a lot less networking issues than before.  It's possible we could implement some kind of ip address fallback, but this would either be a lot less likely to succeed, or a big task, or both, not sure.

You can still connect directly by ip address manually, by the way.

**Comment by elfl0rd** [comment]
> You can still connect directly by ip address manually, by the way.

How? Create link with parameters?

**Comment by MarjieAVolk** [comment]
on the My Servers tab, click the '+' button, enter the ip address and port, and it will attempt to connect directly to that.

**Comment by elfl0rd** [comment]
> on the My Servers tab, click the '+' button, enter the ip address and port, and it will attempt to connect directly to that.

Thx, i will keep in mind that.

**Comment by MarjieAVolk** [comment]
Okay, well if that solves your concern, then... I think this issue is some combination of no repro/working as intended. :P
