### ISSUE TITLE
USER ISSUE: asphalt road\ramp looks like concrete

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7616]
Version: 0.7.5.0 beta staging-7be2f02c
See screenshot.
They asphalt road and reinforced concrete.
![20180508012439_1](https://user-images.githubusercontent.com/4980243/39728283-e878a46e-525e-11e8-9e0a-dc07d5f706ca.jpg)
Looks as concrete road
![69_tn](https://user-images.githubusercontent.com/4980243/39728306-073e9e94-525f-11e8-95f4-966f42f61fbb.jpg)
asphalt road more dark
![24548_original](https://user-images.githubusercontent.com/4980243/39728354-37b2e94a-525f-11e8-99b8-57f47b5cbaa0.jpg)

and suggestion.
more road tiers are good.
untouched ground - 60%, dirtroad(0 - 80%), stoneroad (1 - 100%), asphalt (first use 1876) (2 - 120%), concrete (1892) (3 - 140%), asphaltic concrete (4 - 160%).

**Comment by keegan-o** [comment]
For sure, Asphalt (and reinforced concrete building materials) needs an art update! We will be on it.

**Comment by elfl0rd** [comment]
> and suggestion.
> more road tiers are good.
> untouched ground - 60%, dirtroad(0 - 80%), stoneroad (1 - 100%), asphalt (first use 1876) (2 - 120%), concrete (1892) (3 - 140%), asphaltic concrete (4 - 160%).

No? Cry :(
