### ISSUE TITLE
0.7.3.3 Law system / stat bug?

### ISSUE THREAD

**Issue by DeathTech154** [StrangeLoopGames/EcoIssues#7632]
Hi there,

Had a small hiccup with laws.
We made a law to force people to co-operate more as it prevents people to do everything by restricting them to 300 learned skills overall.

However, one of my members complained and sent me this picture. 

![untitled](https://user-images.githubusercontent.com/22085378/39775686-8f049760-52f6-11e8-8e27-b126e58759a7.jpg)

I suspect there is an imbalance between the count of "Learn skill" actions and "Unlearn skill" actions.
Possibly because there is only one event for unlearning.
And like 8 - 10 for learning.

**Comment by MarjieAVolk** [comment]
Ah, yeah the Learn Skill action gets triggered whenever you learn a specialty or put points into a skill, whereas the Unlearn Skill only happens when you abandon a specialty.  We should probably have separate actions for Learn Specialty and Learn Skill to enable this.

**Comment by MarjieAVolk** [comment]
Or wait, that wouldn't handle this case either, since you're trying to restrict the number of skills they have, not the number of specialties, right?

**Comment by DeathTech154** [comment]
Well, the intent of the law was to stop a single player from doing everything.
If you'd like to review the law. I am keeping it up so you can review it. 
http://209.93.94.76:37278/laws.html?lawid=93dabdbd-60e9-4b1f-b107-4ecfd4b37ca0

The problem is that people would logically draw the conclusion unlearn skill balances out learn the learn skill.
Which at the moment it does not.

The easy fix would probably be to check how many times they levelled up the various skills and trigger 'unlearn' count for every entry. But of course, that is all relative depending on how the system was built.

I will just leave it in your capable hands. ;)
