### ISSUE TITLE
[0.7.4.0 staging] right click on Hand Plough

### ISSUE THREAD

**Issue by Thineboot** [StrangeLoopGames/EcoIssues#7635]
/give HandPlough
place HandPlough (right click) >> you receive a deed for the *Hand Plough*

- left click / Take: works (using Hammer)
- right click / Put Deeds: works
- E / Pull Cart: works ... left click to plough

When it comes to pick it up again ... _**Cannot pick up, must have the correct deed in inventory.**_

As you can't access the internal storage space of the plough you end up with a plough standing around forever.

Workaround:
12 storage spaces capable of storing 1500 kg of deeds (and seeds, and logs, and...) are nice but it's a bit irritating that you can only gain access placing it near a chest (or any other storage you can access) to gain access.

-----

Steering backward is awkward. You may test it once again.

-----

Files:
\Mods\AutoGen\Vehicle\HandPlough.cs
\Mods\Objects\CartHoeObject.cs

Using different named files for one Item/Object isn't helping, too.

-----

Still missing an icon as stated a week ago by @turnburgler in #7542

**Comment by MarjieAVolk** [comment]
Sounds like we should allow accessing the internal inventory.  And also maybe limit what kinds of items can go in it.

**Comment by elfl0rd** [comment]
Or remove this inventory.
Storage space IN plough? srsly?

**Comment by Thineboot** [comment]
Well, it's a farmers tool and storing seeds would make sense. Technically (implementation) it's the same item as the Wheelbarrow (#7637) plus the ability to plow. While you wouldn't store seed in a plow in reality Eco, especially at it's actual stage of development, is simplifying things.

---

Ok, now things become a little bit scary.

Wheelbarrow.cs is a copy of SmallWoodCart.cs with only _Wheelbarrow_ replacing _SmallWoodCart_ and a new _Description_. Well, there is a difference: you can move twice as much weight... using a Wheelbarrow which weigh 15 kg while a Small Wood Cart weigh 10 kg...

HandPlough.cs is a sophisticated copy of Wheelbarrow.cs (RequiresSkill, Ingredients, CraftingComponent).
The Description "_**Small wheelbarrow for hauling minimal loads.**_" has to be wrong.
And don't forget the sophisticated speed limits for a plow: you double your speed in relation to Small Wood Cart and Wheelbarrow and it's max speed is 25% higher, too. Plus you can store twice as much items (space, not weight) in a Plow.

Now checking HandPlough.cs with WoodCart.cs and it's again a copy only exchanging a single ingredient. And yes, the Wood Cart is also described as a _small wheelbarrow_...

I've noticed this things and I'm just a user (with background). I know it's beta but someone was lazy when pushing this code. Balancing may not be a high priority but when you copy paste code you should spend at least a few minutes to check related, existing stuff.

---

Checking out [bleeding edge staging] it seems you will get rid of the storage component completely and added a few new ingredients. Still, there is more bleeding to stop ;)

**Comment by elfl0rd** [comment]
Fixed, inventory removed from plough! :P 
@MarjieAVolk

**Comment by MarjieAVolk** [comment]
Ah yes, there are also no deed items in 7.6 either, so this should be extra fixed.
