### ISSUE TITLE
USER ISSUE: Shoving dirt with a wooden shovel delay

### ISSUE THREAD

**Issue by chrischi16** [StrangeLoopGames/EcoIssues#7636]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
1. Equip a WOODEN Shovel
2. Aim at the dirt
3. Right Click (Shove)
4. Drag the Camera quickly to the spot you wanna place the dirt example: Cart

**Expected behavior:**
The Dirt should be on the shovel instantly after the animation played.

**Actual behavior:**
Sometimes it starts removing a different dirt block.

**Comment by WeaselDog** [comment]
It is designed this way. You dig the block the shovel is aimed at when the animation completes. It allows us to dig faster without making sure we are precisely aimed before starting the animation. Changing this could make digging slower.

Left click is shovel now for trying to reproduce this; right click places dirt.

**Comment by D3nnis3n** [comment]
Not too happy with this one, as i hear complaints about thisnquite regularily, especially the animation taking too long and mistakes therefore easily happening. It's not a big issue, though, but there might be something to tweak.
