### ISSUE TITLE
[0.7.4.0 staging] Wheelbarrow not proper implemented

### ISSUE THREAD

**Issue by Thineboot** [StrangeLoopGames/EcoIssues#7637]
_Small wheelbarrow for hauling minimal loads._

Well, at the moment it's just an ancient washboard (no 3D or 2D available) which can store 1500 kg in 6 spaces. And as it's predecessor it's not movable at all ;)

The only real difference to the Hand Plough I can see is that the Hand Plough has an additional dedicated VehicleHoeComponent (for ploughing using left click). Both should work the same way moving around.
While the Hand Plough uses "E" for moving Wheelbarrow uses "E" to access it's storage.

**Comment by craig-jong** [comment]
Doesn't exist in 7.4 anymore - will come back in 7.5 or 7.6
