### ISSUE TITLE
Powered Cart Movement

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#7638]
Version: 0.7.3.3 beta

Steps to Reproduce:

1. Make a powered cart and put fuel in it.
2. get on the powered cart by targeting it and hitting E
3. drive around in the powered cart and watch it fall off cliffs.

Expected behavior:
Better steering and turning with the Powered Cart

Actual behavior:

Wow the steering with the powered cart is absolutely horrible! 
The turning radius on the powered cart is way too wide.

Both the steering and the turning radius of the powered cart can
use a lot of work.  Right now the way things are I absolutely hate
taking my powered cart anywhere. 

Come on guys can you please improve the steering and turning of
the powered cart so that way players like me are not driving 
over cliffs all the time.  The steering and turning is horrible right now
for the powered carts!

**Comment by SeanAtr0n** [comment]
The powered cart is going to be replaced by a truck in 7.4... not sure if powered carts will disappear though, @craig-jong ?

**Comment by thereporter42** [comment]
Ya it would be a good one to keep. . I would like to see the powered cart stay as well but the
steering just needs a lot of work on it.

**Comment by D3nnis3n** [comment]
Closing out, as powered carts are deprecated, there is a suggestion to rebalance them:
https://github.com/StrangeLoopGames/EcoSuggestions/issues/924
