### ISSUE TITLE
Crash upon jumping (?) in mine - bleeding edge

### ISSUE THREAD

**Issue by armyofskankz** [StrangeLoopGames/EcoIssues#7639]
Crash when I jumped in a mine.

[Crash_2018-05-08_172238.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1985913/Crash_2018-05-08_172238.zip)

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1985912/error.log)

**Comment by metachronism** [comment]
>	0000037300000301()	Unknown
 	UnityPlayer.dll!CastFilter::preFilter(struct physx::PxFilterData const &,class physx::PxShape const *,class physx::PxRigidActor const *,class physx::PxFlags<enum physx::PxHitFlag::Enum,unsigned short> &)	Unknown
 	UnityPlayer.dll!MultiQueryCallback<struct physx::PxOverlapHit>::invoke(float &,struct physx::Sq::PrunerPayload const *,unsigned int)	Unknown
 	UnityPlayer.dll!BucketPrunerOverlapTraversal<struct OBBAABBTest_SIMD,0>::operator()(class physx::Sq::BucketPrunerCore const &,struct OBBAABBTest_SIMD const &,struct physx::Sq::PrunerCallback &,class physx::PxBounds3 const &)	Unknown
 	UnityPlayer.dll!physx::Sq::BucketPrunerCore::overlap(class physx::Sq::ShapeData const &,struct physx::Sq::PrunerCallback &)	Unknown
 	UnityPlayer.dll!physx::Sq::AABBPruner::overlap(class physx::Sq::ShapeData const &,struct physx::Sq::PrunerCallback &)	Unknown
 	UnityPlayer.dll!physx::NpSceneQueries::overlap(class physx::PxGeometry const &,class physx::PxTransform const &,struct physx::PxHitCallback<struct physx::PxOverlapHit> &,struct physx::PxQueryFilterData const &,class physx::PxQueryFilterCallback *)	Unknown
 	UnityPlayer.dll!Unity::PhysicsQuery::OverlapCapsuleInternal(class Vector3f const &,class Vector3f const &,float,int,enum QueryTriggerInteraction,struct physx::PxHitCallback<struct physx::PxOverlapHit> &)	Unknown
 	UnityPlayer.dll!Unity::PhysicsQuery::OverlapCapsuleNonAlloc(class Vector3f const &,class Vector3f const &,float,class Collider * *,int,int,enum QueryTriggerInteraction)	Unknown
 	UnityPlayer.dll!Physics_CUSTOM_INTERNAL_CALL_OverlapCapsuleNonAlloc(class Vector3f const &,class Vector3f const &,float,struct MonoArray *,int,enum QueryTriggerInteraction)	Unknown
 	0000021d490a2a9a()	Unknown

**Comment by metachronism** [comment]
sean has fixed this, fwiw
