### ISSUE TITLE
Crash when mining overhead with rocks falling - bleeding edge

### ISSUE THREAD

**Issue by armyofskankz** [StrangeLoopGames/EcoIssues#7640]
Was surface mining, and mined a rock over my head. Crashed when I expected the rocks to fall on me.
Crash file attached
[Crash_2018-05-08_182036.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1985979/Crash_2018-05-08_182036.zip)

**Comment by SeanAtr0n** [comment]
fixed in 7.5.1 hotfix
