### ISSUE TITLE
Suggestion: Inventory UI changes

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7645]
From Steam https://steamcommunity.com/app/382310/discussions/4/1694920442952409991/: 

the inventory UI needs work (and optimization, since opening it lags badly when there are many nearby inventories). I would use buttons for "expand all", "collapse all", "expand linked only" (perhaps one button with those three states), and "send this inventory to the top of the list". it would also be nice to be able to click on a stack in a remote inventory to send it to the item you have open or your backpack (perhaps Shift-click to the item you have open, and CTRL-click to your backpack/hands)

**Comment by MarjieAVolk** [comment]
Merging this with https://github.com/StrangeLoopGames/EcoIssues/issues/7232
