### ISSUE TITLE
Law Interface breaks on different set of rules

### ISSUE THREAD

**Issue by TrueBale** [StrangeLoopGames/EcoIssues#7648]
This is better explained with screenshots:

1 shows normal behaviour, this is where we are going from.
![1](https://user-images.githubusercontent.com/38583280/39808584-9bf40b84-537f-11e8-9e0f-088d6c849355.png)

Once we change the last rule to something that would also change the "item is" variable, it changes for all the other options as well. This is an unwanted behaviour.
![2](https://user-images.githubusercontent.com/38583280/39808583-9bdaea64-537f-11e8-9140-ed4b52539766.png)

Which happens with whatever option you select (here, I can still choose items, but a very different set of items - I can not choose the tools again for the first two rules).
![3](https://user-images.githubusercontent.com/38583280/39808582-9bc3643e-537f-11e8-8e35-3f1f4e38eb27.png)

**Comment by rainfarmer** [comment]
@TrueBale I'm not able to recreate, can you confirm this is happening in newest version of Eco?

**Comment by rainfarmer** [comment]
We have a fix for this coming. Needs qa
