### ISSUE TITLE
Missing player icon on minimap

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7656]
![image](https://user-images.githubusercontent.com/6262198/39832179-5ebe59d0-537b-11e8-9d0f-8448454ee4fc.png)

**Comment by SeanAtr0n** [comment]
can't reliably reproduce

**Comment by Deantwo** [comment]
Playing in window-mode and changing the size of the window (dragging the edges or maximizing) while the map is open might move the player's indicator on the map around weirdly.

I will try to reproduce it again on my end if that doesn't help you.

**Comment by SlayksWood** [comment]
seems fixed with resizing. Also have another issue #9990
