### ISSUE TITLE
Still getting messages from channels I'm unsubscribed from

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7657]
![image](https://user-images.githubusercontent.com/6262198/39832349-c882b820-537b-11e8-9d50-e835f42ce979.png)

**Comment by MarjieAVolk** [comment]
Yeah, 'hiding' them just minimizes them in the tag list, it doesn't actually turn them off.  You have to toggle them off to turn them off.  But now that I think of it, hiding them should also turn them off probably lol.
