### ISSUE TITLE
[Suggestion] Chat: Focus when activating & up/down keys

### ISSUE THREAD

**Issue by Thineboot** [StrangeLoopGames/EcoIssues#7660]
When you open chat most likely you wanna type something in. Instead of moving your mouse on a 4K screen it would be much appreciated to be able to start typing.

---

Chat is stored in Eco constantly. Just activate up/down (arrow) keys to scroll through (at least your own) chat commands/lines. Not only useful for every player but would save much time during testing, too.

**Comment by MarjieAVolk** [comment]
Second suggestion sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/2585

But focusing the chat input when you open the window sounds like a good idea and would be pretty easy.  (You can also hit enter to start typing into chat wherever you are, by the way)

**Comment by beastyn** [comment]
focusing is woking with Enter
