### ISSUE TITLE
USER ISSUE: wrong web link on nated server.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7662]
**Version:** 0.7.5.0 beta staging-7be2f02c
Hello!
I have a problem.
Players on my dedicated server, receive wrong web link.
My server nated, and have local ip is 1.18
Players receive it, not external.
They can open web page using external ip, but i cant see way to autorize they. No elections\laws...
I try to use ip bind, but they crash server if arg not "any"
domain name|externalip - not working.

**Comment by elfl0rd** [comment]
Server ip 95.30.231.233
server domain server.flydragon.ru
local ip 192.168.1.18
(correct - http://server.flydragon.ru:3001/ or http://95.30.231.233:3001/ but they receive http://192.168.1.18:3001/ )

**Comment by metachronism** [comment]
fixed as of 7.4.5+

though NAT'd servers will still have to forward the web port, there isnt a way around this due to the nature of HTTP connections
