### ISSUE TITLE
Exceptions while server start after update 7.4.0

### ISSUE THREAD

**Issue by Foomy** [StrangeLoopGames/EcoIssues#7664]
Hi,

after the recent update to 7.4 the server will not start a fresh world. (I emptied the storage folder.) In the server windows the first things seem to happen correctly until to that Tick-thing. Then it throws the exception I posted below. I'm sorry, but it seems in a german Windows 7 also the exception messages  a translated to german. I hope it's no problem. 

Regards,
Sascha

Anwendung: EcoServer.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.ArgumentException
   bei Eco.Shared.Math.WorldPosition3i.Initialize(Eco.Shared.Math.Vector3i)
   bei Eco.Shared.Voxel.ChunkGrid`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddChunk(System.__Canon)
   bei Eco.Shared.Voxel.ChunkGrid`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetOrAddChunk(Eco.Shared.Math.Vector3i)
   bei Eco.World.WorldChunkGrid.SetBlock[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Eco.Shared.Math.Vector3i, System.Object[])
   bei Eco.World.World.SetBlock[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Eco.Shared.Math.Vector3i, System.Object[])
   bei Eco.World.Blocks.WaterBlock.TryMoveWater(Eco.Shared.Math.Vector3i, Eco.World.Block, Single, Boolean)
   bei Eco.World.Blocks.WaterBlock.Tick(Eco.Shared.Math.Vector3i)
   bei Eco.World.PersistentChunk.Tick()
   bei Eco.WorldGenerator.WorldGeneratorPlugin+<>c__DisplayClass27_8.<CreateWorld>b__6(Eco.World.PersistentChunk)
   bei System.Threading.Tasks.Parallel+<>c__DisplayClass42_0`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<PartitionerForEachWorker>b__1()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(System.Threading.Tasks.Task)
   bei System.Threading.Tasks.Task+<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(System.Object)

Ausnahmeinformationen: System.AggregateException
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
   bei System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken)
   bei System.Threading.Tasks.Parallel.PartitionerForEachWorker[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Concurrent.Partitioner`1<System.__Canon>, System.Threading.Tasks.ParallelOptions, System.Action`1<System.__Canon>, System.Action`2<System.__Canon,System.Threading.Tasks.ParallelLoopState>, System.Action`3<System.__Canon,System.Threading.Tasks.ParallelLoopState,Int64>, System.Func`4<System.__Canon,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func`5<System.__Canon,System.Threading.Tasks.ParallelLoopState,Int64,System.__Canon,System.__Canon>, System.Func`1<System.__Canon>, System.Action`1<System.__Canon>)
   bei System.Threading.Tasks.Parallel.ForEachWorker[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Threading.Tasks.ParallelOptions, System.Action`1<System.__Canon>, System.Action`2<System.__Canon,System.Threading.Tasks.ParallelLoopState>, System.Action`3<System.__Canon,System.Threading.Tasks.ParallelLoopState,Int64>, System.Func`4<System.__Canon,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func`5<System.__Canon,System.Threading.Tasks.ParallelLoopState,Int64,System.__Canon,System.__Canon>, System.Func`1<System.__Canon>, System.Action`1<System.__Canon>)
   bei System.Threading.Tasks.Parallel.ForEach[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Action`1<System.__Canon>)
   bei Eco.WorldGenerator.WorldGeneratorPlugin.CreateWorld()
   bei Eco.WorldGenerator.WorldGeneratorPlugin.Initialize(Eco.Core.Utils.TimedTask)
   bei Eco.Server.PluginManager.InitializePlugins()
   bei Eco.Server.PluginManager..ctor()
   bei Eco.Server.Startup.Start(System.String[])
   bei Eco.Server.MainClass.Main(System.String[])

**Comment by elfl0rd** [comment]
attach .ecodmp and savefile (if they created) pls ;)

**Comment by Foomy** [comment]
Good Morning,

guess with savefile you mean the game.db? It is in Storage.zip. In the archive Dump.zip are 3 dump files, because I tried three times to start the new server map.

Didn't expect this will going to high priority. My brother and me playing this game for some weeks now and we both looking forward to, when we can start a new map. So many many thx for the fast reaction and reply.

Regards,
Sascha

[Storage.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1990634/Storage.zip)
[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1990640/Dump.zip)

**Comment by elfl0rd** [comment]
This looks as modified and corrypted config, can you clean reinstall with deleting configs?

**Comment by Foomy** [comment]
Just deleting config files an start the server, or do I have to reinstall the completely new?

**Comment by elfl0rd** [comment]
Deleting config files, then reinstall, then try launch.

**Comment by Foomy** [comment]
Wohoo... it's up an connectable. Again many thank for your fast help. Thank you.

**Comment by elfl0rd** [comment]
Good luck and have a nice day!
