### ISSUE TITLE
Property overlay outlines are a little off

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#7669]
The white outline is shown offset 1 block outside of the actual claimed property.
![image](https://user-images.githubusercontent.com/23460210/39841786-d589e526-5398-11e8-8714-78131c5087cb.png)

There is no outline between 2 different properties.
![image](https://user-images.githubusercontent.com/23460210/39841758-bf0ed04a-5398-11e8-96aa-9d17d171e9b1.png)

**Comment by metachronism** [comment]
this is intended, was changed this way so the border is shown correctly
