### ISSUE TITLE
USER ISSUE: can't go under overhangs while diving

### ISSUE THREAD

**Issue by OtherMike** [StrangeLoopGames/EcoIssues#7670]
When Diving (holding CTRL underwater to stay on the bottom), any overhang, at any height above you, will produce an invisible wall that stops you from going under the overhang. (tested up to height about 10, not certain about overhangs above the water's surface, or overhangs made by constructed blocks) Releasing CTRL while pushing into the invisible wall will let you enter the space as long as it would be walkable above ground (so an opening at least 2 tiles high). Once you are under the overhang, you can then hold down CTRL again to stay on the bottom, or just leave it off and let the ceiling keep you where you want to be. I noticed this while mining underwater iron ore in 0.7.3.3, and later tested with stone & soil in 0.7.4.0.

Expected behavior: Diving should not affect what areas can be entered except insofar as it changes what vertical level you are at underwater

Steps to reproduce: 
- jump in a river
- hold CTRL to go to the bottom, and keep holding it to stay there
- find a sheer vertical surface at least 3 tiles high
- mine out a 2x1 opening at the bottom of the face
- try to enter the mined-out area, and fail

**Comment by indie-kaname** [comment]
[0.7.4.6] I find this to be true when the 2h X 1w area has a top block that is **not** a full/complete water block, but a voxel containing flowing water. Concur with @OtherMike that it is un-intuitive and has gotten my pawn stuck before.

**Comment by beastyn** [comment]
Won;t be fixed for now. Didn;t have any problems with mining under water.
