### ISSUE TITLE
USER ISSUE: Dump admin command functionality removed

### ISSUE THREAD

**Issue by XsExcess** [StrangeLoopGames/EcoIssues#7671]
**Version:** 0.7.4.0 beta

Previously the command had parameters to dump specific items, very useful to get rid of the devtool for instance.

Specifically selected and carried parameters.

**Comment by elfl0rd** [comment]
command splited.
Use /dumpcarried /dumpselected

I notice wiki editiors about it, but they lose it.

**Comment by elfl0rd** [comment]
@D3nnis3n can be closed, intended.

**Comment by D3nnis3n** [comment]
Indeed,
