### ISSUE TITLE
Mining coal crash - bleeding edge

### ISSUE THREAD

**Issue by armyofskankz** [StrangeLoopGames/EcoIssues#7672]
Unsure exact trigger, crash file attached.
[Crash_2018-05-09_153506.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1989671/Crash_2018-05-09_153506.zip)

**Comment by armyofskankz** [comment]
In addition, cannot reload the world, crash upo
[Crash_2018-05-09_171726.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1989682/Crash_2018-05-09_171726.zip)
n loading.

**Comment by metachronism** [comment]
need more repro steps, cant do much with just dumps
