### ISSUE TITLE
Sign Text Overflow

### ISSUE THREAD

**Issue by nappelinis** [StrangeLoopGames/EcoIssues#7676]
Version: 0.7.4.1
Reproducible: Easy
Severity: SUPER LOW

Signs seem to have no text limit.
Easy to overflow.

![signs_overflow](https://user-images.githubusercontent.com/10768633/39845244-bb97820c-53c2-11e8-984e-03d015bf1b25.png)

**Comment by Conchipedia** [comment]
looks the same issue as this old one
No limit on how much text can be placed in a sign and too much gives sky writing 6.0.3 #2773

**Comment by craig-jong** [comment]
was fixed with some sign changes - let me know if this happens in a more recent build.
