### ISSUE TITLE
USER ISSUE: Can't access my server

### ISSUE THREAD

**Issue by mdere** [StrangeLoopGames/EcoIssues#7677]
**Version:** 0.7.4.1 beta

**Steps to Reproduce:**
I updated my server to 7.4.x just now and I can't access my server, but I can access the web client

**Expected behavior:**
Able to access my server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host
```

<details>
<summary>Log File</summary>Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Radeon RX 580 Series (ID=0x67df)
    Vendor:   ATI
    VRAM:     8137 MB
    Driver:   23.20.15017.3010
Begin MonoManager ReloadAssembly
- Completed reload, in  0.077 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.674595 ms
Setting up 3 worker threads for Enlighten.
  Thread -> id: 2e28 -> priority: 1 
  Thread -> id: 1958 -> priority: 1 
  Thread -> id: 1fa4 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.1 beta
Wednesday, May 09, 2018 2:53 PM
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fallback handler could not load library E:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
Fallback handler could not load library E:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/.\libc
Fallback handler could not load library E:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> ServerBrowser
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[02:36] Connecting via Lidgren to 70.106.242.34:3001
Changing state: ServerBrowser -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[02:51] Disconnected from server.Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

</details>

**Comment by elfl0rd** [comment]
Double check firewall

> Networking Upgrade
> 
>     A large part of the networking code has been overhauled for this release. The server now uses UDP on port 3000 for game traffic by default, and TCP on port 3001 for web traffic by default. If you were forwarding ports to your dedicated servers in the past, you will need to update your rules accordingly, including any rules in firewall programs.

**Comment by Lothior** [comment]
Having this same issue with my server. Web works fine, cannot join server. Of note.. if I manually try to join the server with a direct connect in game the console will print: "Invalid user trying to connect: Lothior=VX9="
[eco-server-error.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1993001/eco-server-error.txt)

**Comment by pamduncan** [comment]
Are you trying to connect by IP:port? Are you using the gameport now instead of the webport?

**Comment by metachronism** [comment]
@Lothior that should be an unrelated error, sometimes related to your steam ticket expiring

closing this one out for now, seems to all be working with the join game button - I cleaned up the text that was showing the wrong port, which may have been confusing people
