### ISSUE TITLE
sand and dirt are transparent/purple.

### ISSUE THREAD

**Issue by EnigmaticTailor** [StrangeLoopGames/EcoIssues#768]
![screenshot from 2016-11-02 13 09 56](https://cloud.githubusercontent.com/assets/23137516/19928772/547e1a0c-a100-11e6-8d2c-98a0b12cf9ad.png)
I have tried all graphics settings and multiple servers in all of the a5 releases. The problem still persists.

Playing on a ubuntu 14.04 system with a AMD A8-5500 APU with Rsdeon HD Graphics x 4.

**Comment by metachronism** [comment]
should work on 5.5 now
