### ISSUE TITLE
USER ISSUE: Local hosted server authentication stucked

### ISSUE THREAD

**Issue by NicoHof** [StrangeLoopGames/EcoIssues#7681]
**Version:** 0.7.4.1 beta

**Steps to Reproduce:**
(NOTE: This did work before the update - tested with firewall off --> did not help)
1. start hamachi
2. start local server with "eco server" (ip address of hamachi correct set)
3. start eco and join via IP:Port

**Expected behavior:**
This should work for me and my friend in the hamachi room. Before the patch 7.4.0 it did work.

**Actual behavior:**
My friend ist stuck authentication process. In server display I see him trying to connect "Authenticating user [username]...:"

<details>
<summary>Log File</summary>Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: AMD Radeon R9 200 Series (ID=0x6810)
    Vendor:   ATI
    VRAM:     2028 MB
    Driver:   22.19.677.257
Begin MonoManager ReloadAssembly
- Completed reload, in  0.045 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.459021 ms
Setting up 4 worker threads for Enlighten.
  Thread -> id: 3e90 -> priority: 1 
  Thread -> id: 3ff8 -> priority: 1 
  Thread -> id: 50c -> priority: 1 
  Thread -> id: 3f3c -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.1 beta
Wednesday, May 09, 2018 8:53 PM
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fallback handler could not load library E:/Program Files (x86)/Games/steamapps/common/Eco/Eco_Data/Mono/libc
Fallback handler could not load library E:/Program Files (x86)/Games/steamapps/common/Eco/Eco_Data/Mono/.\libc
Fallback handler could not load library E:/Program Files (x86)/Games/steamapps/common/Eco/Eco_Data/Mono/libc
Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> ServerBrowser
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[09:51] Connecting via Lidgren to 25.33.111.183:3000
Changing state: ServerBrowser -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

</details>

**Comment by SlayksWood** [comment]
Relay server was added in 8.3.0. Which solves many connecting issues. If it happens again, please reopen.
