### ISSUE TITLE
Typo in Difficulty.eco

### ISSUE THREAD

**Issue by voguhl** [StrangeLoopGames/EcoIssues#7684]
Version 7.4.1

Unmodified Difficulty.eco is missing an s for Craft Skill Points.
This leads to this setting being not applied if only the file is edited.

In the Screenshot you can see the unmodified file vs. the one after editing it in the server gui.

![grafik](https://user-images.githubusercontent.com/38797484/39870369-6aaf85e8-5461-11e8-8525-4a7278a1f686.png)

**Comment by craig-jong** [comment]
This was fixed fairly recently
