### ISSUE TITLE
People unable to use passwords they set on servers

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7686]
People are reporting that they are setting passwords and once its converted to a hash they get an 'incorrect password' when they try to use the password they set.  They are able to work around that with whitelist and admin listing so they do not have to use a password but want the password to work for people they do not want to white-list

**Comment by razerx7** [comment]
I had the same problem and was struggling with it for the last few hours.
My fix is to just enter the pw in plain text in the config file its not grate but does it for the moment.

**Comment by BaconFist** [comment]
same problem here. I managed to use my password by puting int kleartext in the Cingigs/Ntework.eco
Now i can connect to the  server with this password.

Looks like the server makes a hash but the client does not.
