### ISSUE TITLE
Server Crash: Garbage.BagBlock.Update [7.4.1]

### ISSUE THREAD

**Issue by SessionExpired** [StrangeLoopGames/EcoIssues#7687]
Been having a repeating crash since a scheduled restart which dumps the same log repeatedly.
Server is running on 7.4.1.

`--BEGIN DUMP--
Dump Time
05/10/2018 15:53:46

Exception
Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Gameplay

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.Items.GarbageBagBlock.UpdateVisuals()
   at Eco.Gameplay.Garbage.GarbageManager.Initialize()

--END DUMP--
`

**Comment by Arti-llery** [comment]
Just got this same error today. We had to shut down the server, as it kept trying to reboot.

--BEGIN DUMP--
Dump Time
05/11/2018 11:39:27

Exception
Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Gameplay

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.Items.GarbageBagBlock.UpdateVisuals()
   at Eco.Gameplay.Garbage.GarbageManager.Initialize()

--END DUMP--

**Comment by craig-jong** [comment]
This should be fixed in the latest hotfix. Please let me know if it continues to happen.
