### ISSUE TITLE
"Inactivity"

### ISSUE THREAD

**Issue by Xenophon1** [StrangeLoopGames/EcoIssues#7689]
Hello,

I've a problem with ECO on my Server. I can connect correctly to the server, but on doing some action like: scrolling through the tool-bar, opening any inventory like a chest, or  getting out of an vehicle - the server kicks me out and tells me the problem: "Inactivity".

Other Players on my servers don't have this problem - they can play normally.

This problem first appears after the update on 10.05.2018.

Please help me - i really want to play your beautiful game :)

Best regards
Xenophon

Following the bug-report:

Inactivity.

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: AMD Radeon HD 7800 Series (ID=0x6819)
    Vendor:   ATI
    VRAM:     2028 MB
    Driver:   22.19.677.257
Begin MonoManager ReloadAssembly
- Completed reload, in  0.068 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.180647 ms
Setting up 4 worker threads for Enlighten.
  Thread -> id: 1e28 -> priority: 1 
  Thread -> id: 830 -> priority: 1 
  Thread -> id: cf0 -> priority: 1 
  Thread -> id: 51c -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.1 beta
Wednesday, May 09, 2018 8:53 PM
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fallback handler could not load library X:/Programme/Games/Steam/Steam-Installation/steamapps/common/Eco/Eco_Data/Mono/libc
Fallback handler could not load library X:/Programme/Games/Steam/Steam-Installation/steamapps/common/Eco/Eco_Data/Mono/.\libc
Fallback handler could not load library X:/Programme/Games/Steam/Steam-Installation/steamapps/common/Eco/Eco_Data/Mono/libc
Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Core/PlayerClient/PoweredCartObject/PoweredCartObject(Clone)/Chassis/PoweredCart/Driving/MainCartMesh"
 
(Filename:  Line: 0)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[52:42] Disconnected from server.KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.String,UnityEngine.GameObject].get_Item (System.String key) [0x00000] in <filename unknown>:0 
  at Vehicle.Dismount (Int32 playerID) [0x00000] in <filename unknown>:0 
  at Vehicle.OnDestroy () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Core/PlayerClient/PoweredCartObject/PoweredCartObject(Clone)/Chassis/PoweredCart/Driving/MainCartMesh"
 
(Filename:  Line: 0)

[54:19] Disconnected from server.Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Core/PlayerClient/PoweredCartObject/PoweredCartObject(Clone)/Chassis/PoweredCart/Driving/MainCartMesh"
 
(Filename:  Line: 0)

[58:27] Disconnected from server.Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by metachronism** [comment]
no longer relevant as of 7.4.0
