### ISSUE TITLE
Connection Failed 0.7.4.1 beta

### ISSUE THREAD

**Issue by dwujcik** [StrangeLoopGames/EcoIssues#7690]
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 670 (ID=0x1189)
    Vendor:   NVIDIA
    VRAM:     2017 MB
    Driver:   23.21.13.8859
Begin MonoManager ReloadAssembly
- Completed reload, in  1.661 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 14.301004 ms
Setting up 4 worker threads for Enlighten.
  Thread -> id: 29b8 -> priority: 1 
  Thread -> id: 130c -> priority: 1 
  Thread -> id: 9e8 -> priority: 1 
  Thread -> id: 22b0 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.1 beta
Wednesday, May 09, 2018 8:53 PM
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/.\libc
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

[44:17] Stopping existing server.Changing state: LoggedIn -> LoadingWorld
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.4.1 beta

LocalServer -  Server Initialization... 

LocalServer -  Starting LocalizationPlugin... 

LocalServer -  Starting ModKitPlugin... 

LocalServer -  Compiling mods... 

LocalServer -  Starting NetworkManager... 

LocalServer -  Initializing items... 

LocalServer -  Starting WorldGeneratorPlugin... 

LocalServer -  Starting GameplayStatsPlugin... 

LocalServer -  Starting BackupPlugin... 

LocalServer -  Starting StorageManager... 

LocalServer -  Initializing skills... 

LocalServer -  Starting StatDatabase... 

LocalServer -  Starting WorldPlugin... 

LocalServer -  Loading World... 

LocalServer -  Converting world to new format... 

LocalServer -  Initializing world... 

LocalServer -  Starting TimePlugin... 

LocalServer -  Loading Time... 

LocalServer -  Starting ReputationPlugin... 

LocalServer -  Loading Reputation... 

LocalServer -  Starting PlayerHousingManager... 

LocalServer -  Starting UserManager... 

LocalServer -  Loading Users... 

LocalServer -  Initializing inventories... 

LocalServer -  Starting EcoObjectManager... 

LocalServer -  Loading Objects... 

LocalServer -  Server Initialization finished in 31�447,7ms

Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[44:52] Connecting via Lidgren to localhost:3000
Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoadingWorld -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[45:07] Disconnected from server.Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

[45:24] Stopping existing server.Changing state: LoggedIn -> LoadingWorld
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.4.1 beta

LocalServer -  Server Initialization... 

LocalServer -  Starting LocalizationPlugin... 

LocalServer -  Starting ModKitPlugin... 

LocalServer -  Loading mods... 

LocalServer -  Starting NetworkManager... 

LocalServer -  Initializing items... 

LocalServer -  Starting WorldGeneratorPlugin... 

LocalServer -  Starting GameplayStatsPlugin... 

LocalServer -  Starting BackupPlugin... 

LocalServer -  Starting StorageManager... 

LocalServer -  Initializing skills... 

LocalServer -  Starting StatDatabase... 

LocalServer -  Starting WorldPlugin... 

LocalServer -  Loading World... 

LocalServer -  Converting world to new format... 

LocalServer -  Initializing world... 

LocalServer -  Starting TimePlugin... 

LocalServer -  Loading Time... 

LocalServer -  Starting ReputationPlugin... 

LocalServer -  Loading Reputation... 

LocalServer -  Starting PlayerHousingManager... 

LocalServer -  Starting UserManager... 

LocalServer -  Loading Users... 

LocalServer -  Initializing inventories... 

LocalServer -  Starting EcoObjectManager... 

LocalServer -  Loading Objects... 

LocalServer -  Server Initialization finished in 14�109,2ms

Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[45:39] Connecting via Lidgren to localhost:3000
Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoadingWorld -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[45:54] Disconnected from server.Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> LoadWorld
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[46:15] Stopping existing server.Changing state: LoadWorld -> LoadingWorld
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.4.1 beta

LocalServer -  Server Initialization... 

LocalServer -  Starting LocalizationPlugin... 

LocalServer -  Starting ModKitPlugin... 

LocalServer -  Loading mods... 

LocalServer -  Starting NetworkManager... 

LocalServer -  Initializing items... 

LocalServer -  Starting WorldGeneratorPlugin... 

LocalServer -  Starting GameplayStatsPlugin... 

LocalServer -  Starting BackupPlugin... 

LocalServer -  Starting StorageManager... 

LocalServer -  Initializing skills... 

LocalServer -  Starting StatDatabase... 

LocalServer -  Starting WorldPlugin... 

LocalServer -  Loading World... 

LocalServer -  Converting world to new format... 

LocalServer -  Initializing world... 

LocalServer -  Starting TimePlugin... 

LocalServer -  Loading Time... 

LocalServer -  Starting ReputationPlugin... 

LocalServer -  Loading Reputation... 

LocalServer -  Starting PlayerHousingManager... 

LocalServer -  Starting UserManager... 

LocalServer -  Loading Users... 

LocalServer -  Initializing inventories... 

LocalServer -  Starting EcoObjectManager... 

LocalServer -  Loading Objects... 

LocalServer -  Server Initialization finished in 14�477,4ms

Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[46:30] Connecting via Lidgren to localhost:3000
Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoadingWorld -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[46:45] Disconnected from server.Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[47:02] Stopping existing server.Changing state: LoggedIn -> LoadingWorld
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.4.1 beta

LocalServer -  Server Initialization... 

LocalServer -  Starting LocalizationPlugin... 

LocalServer -  Starting ModKitPlugin... 

LocalServer -  Loading mods... 

LocalServer -  Starting NetworkManager... 

LocalServer -  Initializing items... 

LocalServer -  Starting WorldGeneratorPlugin... 

LocalServer -  Starting GameplayStatsPlugin... 

LocalServer -  Starting BackupPlugin... 

LocalServer -  Starting StorageManager... 

LocalServer -  Initializing skills... 

LocalServer -  Starting StatDatabase... 

LocalServer -  Starting WorldPlugin... 

LocalServer -  Loading World... 

LocalServer -  Converting world to new format... 

LocalServer -  Initializing world... 

LocalServer -  Starting TimePlugin... 

LocalServer -  Loading Time... 

LocalServer -  Starting ReputationPlugin... 

LocalServer -  Loading Reputation... 

LocalServer -  Starting PlayerHousingManager... 

LocalServer -  Starting UserManager... 

LocalServer -  Loading Users... 

LocalServer -  Initializing inventories... 

LocalServer -  Starting EcoObjectManager... 

LocalServer -  Loading Objects... 

LocalServer -  Server Initialization finished in 14�767,4ms

Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[47:17] Connecting via Lidgren to localhost:3000
Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoadingWorld -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[47:32] Disconnected from server.Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by elfl0rd** [comment]
Hi @dwujcik ! As i see, you want to start singleplayer ga,me, right?
Can you attach latest .ecodmp from \Eco_Data\Server\Dump and two file named as world you try to start from \Eco_Data\Server\Storage ?

**Comment by metachronism** [comment]
should be fixed 7.4.2
