### ISSUE TITLE
World objects getting nuked in situations involving vertical placement of some kind...

### ISSUE THREAD

**Issue by TheNitrogen** [StrangeLoopGames/EcoIssues#7694]
I found that when I put something on the ground that is not seen as a building block and over it build building blocks at an altitude of about 200 meters, so down, everything will disappear
and can not be replaced or removed
The ramps disappeared
![20180430103814_1](https://user-images.githubusercontent.com/39168445/39886514-f699a2fe-548f-11e8-82e3-27cdeec27c4a.jpg)
![20180430103411_1](https://user-images.githubusercontent.com/39168445/39886589-350ad184-5490-11e8-97c8-b36632e54f35.jpg)
![20180430103430_1](https://user-images.githubusercontent.com/39168445/39886599-3ce0c328-5490-11e8-8f71-b3f293a05b9e.jpg)
![20180430103454_1](https://user-images.githubusercontent.com/39168445/39886624-4e129734-5490-11e8-875d-518bde0ef568.jpg)
![20180429215812_1](https://user-images.githubusercontent.com/39168445/39886648-5e9627c4-5490-11e8-9e9c-9c486448ba5c.jpg)

You can see the neighbor on the map of the equipment so it is not seen as a building block

![20180430104348_1](https://user-images.githubusercontent.com/39168445/39886811-e102794c-5490-11e8-9692-aa9fb5a07bae.jpg)

it's also invisible and can not be used
![20180430104334_1](https://user-images.githubusercontent.com/39168445/39887242-0173329c-5492-11e8-8740-835cd6a98b29.jpg)

at the right of the picture you can see the disappeared stock pile while building blocks remain

**Comment by SeanAtr0n** [comment]
think this was fixed in 7.5
