### ISSUE TITLE
Center-Point of world not loading causing vehicles to fly off. [7.4 / 7.4.1 / 7.4.2]

### ISSUE THREAD

**Issue by SessionExpired** [StrangeLoopGames/EcoIssues#7695]
Theres an odd glitch in my world which has persisted from 7.3 into 7.4.1.
If you cross this point anywhere in the world (0,???) it will always freak out, the world won't load and if you are in a vehicle it will cause audio and visual stuttering and eventually send your vehicle off into the sky.

I have a video of this happening located here: [YouTube Link](https://www.youtube.com/watch?v=aSeIKLZeG5k)

**World Size** 140x140
**Server Version:** 7.4.1
(Previously happened on 7.4 and 7.3.3 also.)
The world file is over 100mb so if required I can upload the files if requested.

Once you step over that area the world loads properly but if you take a vehicle over that point it freaks out, but once you go a bit of a distance away from that point it will deload the other side of the world and produce the same bug over and over again.

Server restarts do not fix it.

**Comment by elfl0rd** [comment]
looks as this double issue at one time :d
https://github.com/StrangeLoopGames/EcoIssues/issues/7613 + https://github.com/StrangeLoopGames/EcoIssues/issues/7612

**Comment by SessionExpired** [comment]
@elfl0rd Ah I see, and with your video I noticed you were near the 0 coordinate also, but oddly enough this issue happens on foot but it loads the world the moment you step past that point, Freaks out with Carts, and all other vehicles.

And its been happening on 7.4, 7.4.1.
I had a similar issue on 7.3.3 but instead of deloading the world would turn black and you'd see the stars of the skybox until you exited the vehicle.

**Comment by SessionExpired** [comment]
From what I've experienced it's basically a straight line across the entire axis of the map on the 0 co-ordinate, so building your road to the left or right will make no difference if your destination is on the other side of this section, you will constantly run into this issue no matter what until it's fixed.

(Haven't checked 7.4.2 yet)

**Comment by SessionExpired** [comment]
Still happens on 7.4.2

**Comment by Sekor2600** [comment]
Same Problem here. We havent Update 7.4 on our Server because of this bug. Not Playable with Vehicles

**Comment by Sekor2600** [comment]
Same Problem with 7.4.3. Driving is not funny with this Bug. Our City has two 0 Cordinates inside Center

**Comment by SeanAtr0n** [comment]
will be fixed in 7.4.5
