### ISSUE TITLE
Steam Engines and Toxic Waste

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7697]
Via Forum: http://ecoforum.strangeloopgames.com/topic/4587/steam-engines-and-on-another-note-toxic-waste

"Steam engines in later releases, I hope there are plans to use the steam traction engine shown here for mobile stationary power. https://www.kickstarter.com/projects/1037798999/eco-global-survival-game/posts

Steam traction engines were more commonly used as plowing machines, in fact some traction engines are often mistaken for plowing engines or threshing engines when they were used as a mobile power unit , I'm hoping the devs look into these often overlooked machines when it comes to video games.

And for something completely different ... How about the idea of ​​burying barrels of toxic waste?"

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#59
