### ISSUE TITLE
Players can pick up any store, including its contents regardless of ownership/access rights

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7699]
Via Forum: http://ecoforum.strangeloopgames.com/topic/4582/server-issue-store-pickup-no-rights-needed-to-pickup-store-in-any-properties

"Version: 0.7.4.1 beta

Steps to Reproduce:
Just take a hammer and hit any store in the world.

Expected behavior:
Users can't pickup any stores in other parcel

Actual behavior:
Since the update, anyone can pickup all the stores in the world without any right on propriety, also pieces disepeared (volumetric config)"

**Comment by MarjieAVolk** [comment]
Fixed (for reals) in next hotfix
