### ISSUE TITLE
a5p3 property got randomly(?) unclaimed (not by me)

### ISSUE THREAD

**Issue by panisch420** [StrangeLoopGames/EcoIssues#770]
so i logged into the debug server today and the property i claimed yesterday was no longer claimed. none of it. i did not do this.
so unless you guys did this, this is a bug :)

**Comment by panisch420** [comment]
they just dissapeared again after i set em up again earlier.
also another player s reporting this happeneing.
maybe a server crash/restart does this?

**Comment by SeanAtr0n** [comment]
Yeah property wasn't getting saved previously, I just fixed this yesterday and it should be in next release
