### ISSUE TITLE
Viewing insinde of vehicles [digging mode]

### ISSUE THREAD

**Issue by razerx7** [StrangeLoopGames/EcoIssues#7700]
I dont know if it is a bug or a feature but i cant shift my view when iam inside the digging-mode of the excavator or the new one. 

This is realy hindering when digging and i would like to have back this ability to look where i want.

**Comment by SeanAtr0n** [comment]
press 1 to toggle between controlling the vehicle vs controlling your view

**Comment by razerx7** [comment]
thats what iam doing but i thought that you where able to change the viewig angle in both modes. but maybe my  memory messed up something.
