### ISSUE TITLE
Ingredients on ordered recipes do not have tooltips

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7704]
![image](https://user-images.githubusercontent.com/6262198/39898938-f9715d54-546d-11e8-848d-d81110d8965f.png)
Green: has tooltips
Red: No Tooltips

**Comment by elfl0rd** [comment]
@D3nnis3n fixed.
![20181205213139_1](https://user-images.githubusercontent.com/4980243/49535406-32467180-f8d5-11e8-95c5-daf90e8aa1ed.jpg)

**Comment by D3nnis3n** [comment]
Indeed.
