### ISSUE TITLE
Stuck in Map 

### ISSUE THREAD

**Issue by KratosTheHunter** [StrangeLoopGames/EcoIssues#7706]
Hey i am Stuck in the planet or something, i can´t do anything anymore. 
Is it possible to respawn on you map?

Please please help me

![eco 2018-05-11 02-02-56-08](https://user-images.githubusercontent.com/39164584/39900176-46bcaaee-54c0-11e8-9c41-b6cd41958e37.jpg)

**Comment by SessionExpired** [comment]
Have you tried using /unstuck  in the chat?

**Comment by SeanAtr0n** [comment]
/unstuck should fix this if you are playing the latest version, would be good to know how you managed to get there

**Comment by KratosTheHunter** [comment]
Thank you guys i solved the Problem with your idea, it worked perfect.

I was sitting in the cart on the screenshot, thats how i came there.

![eco 2018-05-11 17-00-21-79](https://user-images.githubusercontent.com/39164584/39931726-8d956c52-553e-11e8-821e-5b4d39a27c2d.jpg)

**Comment by SeanAtr0n** [comment]
fixed in 7.6
