### ISSUE TITLE
Need to add seeds to all plant growth animations

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#771]
New way of doing seeds: plants at age zero should have their seeds visible as part of their animation, and overtime they sink into the ground and fade out.  This way, when you drop a seed it spawns the plant immediately and seamlessly transitions. Can you add this for all existing plants?

**Comment by keegan-o** [comment]
Seeds should be a separate thing for a lot of reasons. Alpha cutoff can fade in or out, not both. Adding them to the speedtree assets would require editing every single speedtree file and custom editing every single plant texture to fit in seeds. No current way to make them sink other than scaling down. Most plants start as invisible for a bit, can just make sure they all do just by editing curves, then we can have seeds as their own thing that do whatever they want (and could use one prefab for everything except where inappropriate)

**Comment by metachronism** [comment]
The idea is to add more control to the plant growth -

* have all plants start as seeds - this would involve adding the seeds to the existing plant models
* modify the initial plant growth animation to sink the seeds into the ground (move the y-pos down) - this can occur very early in the animation, resulting in the seeds becoming completely invisible very early in its growth
* animate the alpha as normal - the seeds will be underground and no longer visible

**Comment by metachronism** [comment]
also some plants don't/shouldn't even have need seeds - camas for example as they are bulbs

**Comment by keegan-o** [comment]
How would we separate out the seeds to move them down but not the rest of the plant? Seems like either way, they'll be an object we add to the plant prefab, not in the same speed-tree model. And then you may as well have a little script specifically for their behavior.
