### ISSUE TITLE
[Suggestion] Skid Steer is too fast

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7710]
From the Steam forums https://steamcommunity.com/app/382310/discussions/0/2561864094339306800/: 

Skid steer is way to fast
First off, Dev's thank you! The Truck is amazing, handles so nice and has a good amount of speed and power, and I am loving the skid steer. 

However the speed while in "bucket mode"? makes it very hard to control for small quick moves. 
To move into the perfect spot you either have to push the gas a second then stop, push, stop, till you nudge you way around a area.

I think if you want to go a fair distance with a load you should be forced into the drive mode then back to bucket mode when you reach the area. Because right now this little guy is far to sensitive in tight areas.

Thanks a bunch! Just some user feedback.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#57
