### ISSUE TITLE
[Suggestion] Steam Server Link ?

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7711]
From Steam https://steamcommunity.com/app/382310/discussions/0/2561864094340711197/: 

Hello

I would like to add a direct Steam-link to a posting that points to my server. On click.. Steam would start Eco ( if not running ) and connect Eco to the server ip/port from link.

Should be the same as to "join friends game+server" in your Steam friends list.

Is this possible?

**Comment by elfl0rd** [comment]
like as  steam://connect/ip:port

**Comment by Nanders** [comment]
This is possible right now.

steam://rungameid/382310// -connectTo=<your servers' unique ID>

ex.
steam://rungameid/382310// -connectTo=7002578218773351703

This will connect to Stuffed Elk testing server

**Comment by Nanders** [comment]
Really, the only thing this needs is an easy way to see your servers' unique ID

**Comment by elfl0rd** [comment]
or way to direct connect, using ip:port :D

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#56
