### ISSUE TITLE
Teleported way off world on exiting truck

### ISSUE THREAD

**Issue by TAUTIC** [StrangeLoopGames/EcoIssues#7715]
I was exiting a truck which was parked next to a dirt ramp - upon exit, my character was teleported a bit off world as seen here: https://i.imgur.com/wPRXbyA.png

Truck position: https://i.imgur.com/usP8eII.png

This is reproducible, I've exited tree times now, and gotten teleported each time. I've also moved the truck, exited properly, put the truck back and the teleport returns.

This also seems to have broken the minimap, I can't seem to get it back to center on my player.

**Comment by Raa225** [comment]
How did you get back on the map? Did you use /unstuck? I have the same problem but I cant get back in my world.

**Comment by SeanAtr0n** [comment]
what coordinates was the truck at?

**Comment by TAUTIC** [comment]
Truck was at 498,57,203 facing South.

I got back to the planet using /teleport, thankfully i'm the server admin for our group, else i'd be lost in space.

**Comment by TAUTIC** [comment]
@Raa225 hopefully you saw my reply above, not sure how else to reply here.  same for @SeanAtr0n ..

**Comment by SeanAtr0n** [comment]
reducing priority a bit as it seems pretty difficult to make it teleport you off world and weird behavior can be avoided by leaving a bit of room to exit the vehicle

**Comment by SlayksWood** [comment]
Now I appear on the surface of the ramp:
![image](https://user-images.githubusercontent.com/45708377/62539941-12e65680-b85f-11e9-9273-3ec2eb69fecc.png)
Seems fixed. If it happens again please reopen and provide log files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
