### ISSUE TITLE
USER ISSUE: Chat not responding

### ISSUE THREAD

**Issue by XsExcess** [StrangeLoopGames/EcoIssues#7716]
**Version:** 0.7.4.2 beta

**Steps to Reproduce:**
When ever anyone attempts to type in chat, the server never receives it and it never shows in the chat log, even for the typer. Confirmation that we have the correct channel shown in the chat log, and we're typing in the correct channel.

Server UI confirms nothing is going through. I have attached the chatlog
[ExportedChat-2018-05-11T1757.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1996081/ExportedChat-2018-05-11T1757.zip)
the "." was at ~10:50 UK time after I restarted to fix the issue initially, and then any subsequent messages didn't go through. Even after a restart (Xs left Xs joined) nothing went through.

**Comment by WeaselDog** [comment]
We are not able to reproduce this is in the latest version and it appears to be fixed.

Thanks for the report!
