### ISSUE TITLE
Sitting in vehicle with lights  causes lights on other same vehicle type to activate

### ISSUE THREAD

**Issue by TAUTIC** [StrangeLoopGames/EcoIssues#7717]
Second truck: https://i.imgur.com/DGmdjDi.png
Second truck when I sit in mine: https://i.imgur.com/EnY8oBD.png
Does not seem to affect vehicles of different type. Sitting in skid steer, truck lights not activated: https://i.imgur.com/JwTYgmh.jpg
Sitting in skid steer, lights on second skid steer are improperly activated: https://i.imgur.com/7Nf7Nvm.png
Lights on

**Comment by SeanAtr0n** [comment]
@keegan-o (i'm doing a compile right now so i can't check) sounds like we need to do a material swap for the lights instead of changing a material parameter?

**Comment by keegan-o** [comment]
Aww, we had it that way then I made it this way since I figured the mat property would be less expensive. multiple materials it shall be then...
