### ISSUE TITLE
Dead zones in placement

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7718]
https://imgur.com/a/uJibdQt

**Comment by SeanAtr0n** [comment]
what was/is in that spot before?

did logging out/in fix it?

**Comment by johnkslg** [comment]
Nothing was in the space, it happened throughout the world.
Didnt try logging in/out but will do so if I can detect it again.

**Comment by SeanAtr0n** [comment]
could also be something you changed? sounds like you are editing interaction manager

**Comment by SeanAtr0n** [comment]
haven't been able to repro
