### ISSUE TITLE
USER ISSUE: Pipe branch terminating at cast iron stove or bakery oven counts as open end

### ISSUE THREAD

**Issue by TheRealMaxion** [StrangeLoopGames/EcoIssues#7719]
I have a number of copper pipes connected to a blast furnace, where one end of the pipe system connects to the blast furnace exhaust exit port, and a longer end of the pipes ends openly in the air as a chimney.
There is also another branch of the pipe system that connects on one end to one of the pipes between the aforementioned two ends, which creates a 3 way intersection, and the other end of this pipe terminates at the exhaust port of a cast iron stove and/or bakery oven.

When checking the pipes tab of the blast furnace, it lists there being 2 open ends, one at the chimney, and one at the stove or oven on the other branch.
This only happens if the pipe terminates at the stove or oven, and not if those connections are part of another 3 way intersection in the same block.
A dumb but simple workaround at the moment is therefore to have the pipe loop back into itself after connecting to the structure in the kitchen.

Hopefully this explanation is clear enough, but please ask me for clarification or screenshots if any of this is unclear.

**Comment by SeanAtr0n** [comment]
Could you post a screenshot of the hookup or the game save?

**Comment by TheRealMaxion** [comment]
Sure! :)

Pipe terminating in kitchen device letting out fumes:
![image of problem](https://user-images.githubusercontent.com/13872642/39943009-a37ffdd4-5561-11e8-8aa2-e84e087263a6.png)

Current workaround to avoid bug letting out fumes:
![image of workaround](https://user-images.githubusercontent.com/13872642/39943049-c3c5b638-5561-11e8-953f-8327188e141c.png)

**Comment by SeanAtr0n** [comment]
whoops, this one is not fixed in 7.4.5 >.>

**Comment by SeanAtr0n** [comment]
@craig-jong think bakery oven needs a pollution component?

**Comment by TheRealMaxion** [comment]
I would like to re-emphasize that this happened both to the bakery oven, and also to the cast iron stove when the pipe terminated there. Whenever the pipe ended at either of them without having a 3-way intersection at the device.

**Comment by WeaselDog** [comment]
Thanks for the detailed report. This will be fixed in update 0.9.0 with changes to how the Cast Iron Stove and Bakery Oven handle pipes. They now emit pollution instead.
