### ISSUE TITLE
a5p3 bakery oven occupying space behind it but not infront of itself

### ISSUE THREAD

**Issue by panisch420** [StrangeLoopGames/EcoIssues#772]
front is faced against the wall with no gap
![screenshot_579](https://cloud.githubusercontent.com/assets/22756750/19943020/050d0c04-a136-11e6-90fe-c9aeaca7df8d.jpg)

if i turn it around i cant put it in the same spot, because it says it's blocked. i need that gap to place it. if anything it should be the other way around, no?
![screenshot_580](https://cloud.githubusercontent.com/assets/22756750/19943080/3e877762-a136-11e6-8929-faf49a26872a.jpg)

sidenote: roomrequirements for bakery oven are still intact

**Comment by metachronism** [comment]
keegan fixed this
