### ISSUE TITLE
USER ISSUE: Treasury allocation windows closes when clicking away.

### ISSUE THREAD

**Issue by DeathTech154** [StrangeLoopGames/EcoIssues#7722]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Open the allocation window.
Click on a credit
Set a value
Click anywhere else that is not selectable field.

**Expected behavior:**
Deselect the value field

**Actual behavior:**
Closes the whole window as if you clicked outside of the window.

**Comment by MarjieAVolk** [comment]
Fixed in 8.0
