### ISSUE TITLE
Swimming and Fish trap driving me nutes creating problems

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#7723]
so there issue with trying to get open up fish traps to collect fish with the way swimming is done.

1. I swim under water holding ctrl key to get to bottom to get my fish trap
2. press e to open trap
3. float to surface before i can collect my fish

had to repeat this process 10 times before i could get my fish out of my trap, i ended up deleting fish trap because its just to annoying to deal with.

it also drove my wife crazy to point where she just stopped playing game for now.

be nice to be able to turn off the auto floating thing to make it option.

**Comment by TheRealMaxion** [comment]
Agreed, it is annoying that we float out of range of the fish trap faster than we can drag something out of it. Would be nice if opening the fish trap menu kept us from floating up while it is open, or at least delayed it a bit.

Current workarounds include:
- Placing a chest in storage linking range of the fish trap, to move stuff out of the fish trap in the storage menu of the chest.
- Picking up the whole trap with everything inside by using the hammer, though this does not work if the trap contains more fish than you can carry.
- Shift-clicking a stack of fish in the trap before the menu closes, which allowed getting the fish out after the menu closed, though I'm not sure if this was fixed (made impossible) in a patch already.

**Comment by SeanAtr0n** [comment]
will be fixed in 7.4.5

**Comment by midn8t** [comment]
I think floating thing was added to keep people from living underwater, id rathere have floating thing out put air breathing into game - when you run out of Air just make it so you lose experience  - to simulate going brain dead from lack of air.
