### ISSUE TITLE
Shop errors in prices with decimal places

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7726]
Via Forum: http://ecoforum.strangeloopgames.com/topic/4595/shop-fehler-bei-preisen-mit-kommastellen

"Hello,

we have since the update today 0.7.4.2 errors in the prices in shops if they have decimal places.

Does it affect the server, the client, or the website? - Server 
Which version of the server or client is involved? - 0.7.4.2 
Which operating system do you use? - Not relevant 
Which internet browser do you use? (in case of problems with the website) - Not relevant 
Could you understand the problem? Do you know what makes it happen? =

As soon as a price with decimal places is set in the shop (eg 1.50), the comma (until the update was the delimiter a dot) is displayed for the shop operator, but ignored for buyers. The buyer sees then 150 and gets these also calculated.

Error is traceable and there is no workaround."

**Comment by XsExcess** [comment]
Exactly the same issue as sisimonis, only effects localized comma using clients and is visible on the client side temporarily as working, but on the server side its setting the price to 0.

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/4971

**Comment by duxter** [comment]
I'm running a server on ubuntu with mono, all users on the server are using windows version of ECO and we also have the problem on the wole server.
I try to launch the server with:
#!/bin/bash export LANG=en_US.utf8 mono EcoServer.exe -nogui

But seem not work...

**Comment by johnkslg** [comment]
Fixed!
