### ISSUE TITLE
USER ISSUE: NullException when picking up a chest

### ISSUE THREAD

**Issue by PedroFonseca** [StrangeLoopGames/EcoIssues#7731]
**Version:** 0.7.4.4 beta

**Steps to Reproduce:**
1. Placed a chest on public property (1 tile on plowed dirt another on coal block)
2. Tryed to pick it up with a hammer
3. NullException was thrown

(This is consistent, i still can't pick up the chest)

**Expected behavior:**
I should have picked up the chest

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Source:Eco.Mods

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   at HammerItem.TryPickUp(WorldObject obj, InteractionContext context)
   at HammerItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>
```

<details>
<summary>Log File</summary>(...previous log truncated...)

tObjComponent.Eco.Shared.Networking.INetObject.ReceiveInitialState (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
BSON: Eco.Shared.Serialization.BSONObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[15:27] Disconnected from server.Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Caught exception on PipeEmitterObject(Clone) while in NetObject ReceiveInitialState.
Exception: Object reference not set to an instance of an object
Callstack:   at PipeEmitterObject.SmogRateChanged (System.Single rate) [0x0003d] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
  at UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) [0x00011] in <0ab26637e49a49deb2c166b5c94319b0>:0 
  at UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) [0x00023] in <0ab26637e49a49deb2c166b5c94319b0>:0 
  at WorldObject.UpdateAnimatedState (System.String name, System.Single val) [0x0003b] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
  at WorldObject.UpdateAnimatedStates () [0x00073] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
  at Eco.Shared.View.ISubscriberExtensions.SubscribeAndCall (Eco.Shared.View.ISubscriber s, System.String propname, System.Action changedCallback) [0x00008] in <8b0c07b6205f4a8caba97065e1537ee0>:0 
  at WorldObject.ReceiveInitialState (Eco.Shared.Serialization.BSONObject bson) [0x00190] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
  at NetObjComponent.OnReceiveInitialState (Eco.Shared.Serialization.BSONObject bsonObj) [0x00022] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
  at NetObjComponent.Eco.Shared.Networking.INetObject.ReceiveInitialState (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
BSON: Eco.Shared.Serialization.BSONObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[15:42] Disconnected from server.Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

</details>

**Comment by Kumagor0** [comment]
Full error message of crash when picking up dirt ramp:

Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Source:Eco.Mods

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   at HammerItem.TryPickUp(WorldObject obj, InteractionContext context)
   at HammerItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)</size>

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
d3d11: D3D_FEATURE_LEVEL_11_1 not-recognized (only 11.0 runtime installed?)
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GT 540M    (ID=0xdf4)
    Vendor:   NVIDIA
    VRAM:     993 MB
    Driver:   8.17.12.6754
Begin MonoManager ReloadAssembly
- Completed reload, in  0.284 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.365402 ms
Setting up 2 worker threads for Enlighten.
  Thread -> id: 2eac -> priority: 1 
  Thread -> id: 180c -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.4 beta
Saturday, May 12, 2018 12:33 AM
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> ServerBrowser
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[37:19] Connecting via Lidgren to 89.163.192.231:10400
Changing state: ServerBrowser -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[37:44] Disconnected from server.Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> ServerBrowser
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[37:53] Connecting via Lidgren to 89.163.192.231:10400
Changing state: ServerBrowser -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[39:24] Disconnected from server.Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/40017530-7f20ae70-576e-11e8-959f-a7721433cf20.png)
MEME Priority enabled.

**Comment by Kumagor0** [comment]
Server I am playing on doesn't have any mods as far as I know. I asked admin to provide Game.eco, waiting for his response.

**Comment by Sonic1305** [comment]
Here is my Game.eco https://drive.google.com/open?id=1YXFq5qQNxj5PEp3wcebQguVPKyGhZig5
As Kumagor0 already said, this is a vanilla server with a small map and no special options.

**Comment by MarjieAVolk** [comment]
Thanks, I will take a look!

**Comment by MarjieAVolk** [comment]
Thank you, going to look for this chest now.  If anybody could give me the coordinates of it real quick, that would be helpful.

**Comment by Kumagor0** [comment]
After Sonic reinstalled server issue seems to be fixed on his server so dirt ramp case is closed for now, sorry for wasting your time.

**Comment by MarjieAVolk** [comment]
Oh you guys were the ones with the dirt ramp, not the chest.  Oops.  No problem, thanks for letting us know!
