### ISSUE TITLE
[0.7.4.4] Game locks up when opening the chat window with the hotkey C

### ISSUE THREAD

**Issue by DeathTech154** [StrangeLoopGames/EcoIssues#7736]
On 0.7.4 when joining a new server the whole game locked up when pressing C to open the chat log.
After waiting for 5 minutes I forcibly terminated the game and rejoin worked fine after that.
Minus of course the absurd lag spike every time I open the chat window.

Steps to reproduce:
Join a server you've never been on before with several days of chatlog.
Press C and watch it lock up.

Observed behaviour:
The game locked up after pressing the hotkey for the chat window (C).
The game did not recover.

Expected Behaviour:
The game opens the window and loads the data in without locking up.

**Comment by elfl0rd** [comment]
ummm... https://github.com/StrangeLoopGames/EcoIssues/issues/7527 maube one bug.

**Comment by matias-b** [comment]
Happens to me on linux, looks like windows too

**Comment by MarjieAVolk** [comment]
@matias-b You noted that typing #General fixed the problem.  What tag were you on before you typed #General?  Did the other tag you were on have a larger or smaller history than #General?

I'm thinking this is probably related to just really bad chat performance, rather than a specific error.

**Comment by MarjieAVolk** [comment]
Also, do you guys think this behavior is new in 7.4?

**Comment by MarjieAVolk** [comment]
Okay, well I found a bug where the chat was refreshing once per channel when you log in to a new server for the first time.  I think that's the reason for the big freeze up.  Chat refresh also needs to be optimized quite a bit, but after fixing this it should be like a couple seconds to load at most instead of minutes or however long.

**Comment by MarjieAVolk** [comment]
Fixed in 7.4.6
