### ISSUE TITLE
USER ISSUE: Deleting all text in a text component don't update sign

### ISSUE THREAD

**Issue by Kirthos** [StrangeLoopGames/EcoIssues#7737]
**Version:** 0.7.4.4 beta

**Steps to Reproduce:**
1. Place something that have a text Component (i.e sign, woodcart, poweredCart...)
2. Write a text what you want (i.e "test")
3. Save, you see the text write normally
4. Delete all characters to make the text become nothing (just space work too)
5. Click save and the text don't change even after closing and reopen the object the text not show in the textComponent

**Expected behavior:**
The client should send the command to the server about text that was updating when no text (or just space) was send.

**Actual behavior:**
Instead the client don't send the new text to the server when it was empty (or just space).

<details>
<summary>Log File</summary>Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1070 (ID=0x1b81)
    Vendor:   NVIDIA
    VRAM:     8096 MB
    Driver:   23.21.13.8813
Begin MonoManager ReloadAssembly
- Completed reload, in  0.177 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.173103 ms
Setting up 4 worker threads for Enlighten.
  Thread -> id: 3f6c -> priority: 1 
  Thread -> id: 2930 -> priority: 1 
  Thread -> id: fb4 -> priority: 1 
  Thread -> id: 2688 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.4 beta
vendredi 11 mai 2018 23:33
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> ServerBrowser
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: ServerBrowser -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at PostProcessingManager.UpdateHypoxia () [0x0002f] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
  at Eco.Shared.View.ISubscriberExtensions.SubscribeAndCall (Eco.Shared.View.ISubscriber s, System.String propname, System.Action changedCallback) [0x00008] in <8b0c07b6205f4a8caba97065e1537ee0>:0 
  at PostProcessingManager.Start () [0x00081] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
 
(Filename: <f40bff3faa6041269b1e5f6e1739e5a0> Line: 0)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

</details>

**Comment by craig-jong** [comment]
This one is sort of self explanatory. I think you just need to update the client code to send empty strings, but I haven't looked into it.

**Comment by Kirthos** [comment]
The text is trim then if the text length is not > 0 the rpc is not call by the client.
