### ISSUE TITLE
USER ISSUE: Ingame links to server website use local IP

### ISSUE THREAD

**Issue by TheRealMaxion** [StrangeLoopGames/EcoIssues#7738]
Since updating our private server from version 0.6.3.3 or so to 0.7.4.2 and 0.7.4.4, the ingame links to the server's website (market, stats etc, such as by pressing G) try to open it using the server's local IP instead of its external IP address.

**Comment by elfl0rd** [comment]
Duplicate - https://github.com/StrangeLoopGames/EcoIssues/issues/7662

**Comment by TheRealMaxion** [comment]
Fair enough.
