### ISSUE TITLE
Cant join any Server

### ISSUE THREAD

**Issue by cucu24** [StrangeLoopGames/EcoIssues#7739]
Version: 0.7.4.4 beta

Steps to Reproduce:
try to join in any 7.4.4 Server

Expected behavior:
connecting to the server

Actual behavior:
Loading the World until 100% and see the surroundings for 1 second, then it wents automatically to the main menue

Additional:
I tested it on the Server of my friend, he said it shows that i'm going online, he saw me for like 15 seconds on the world until it wents automatically to the main menue.

**Comment by metachronism** [comment]
try this is 7.4.5
