### ISSUE TITLE
a5p3 server crash: as soon as you would have a funtioning bakery oven

### ISSUE THREAD

**Issue by panisch420** [StrangeLoopGames/EcoIssues#774]
1. bakery oven was put down in an unfinished room. -> no crash
2. as soon as this room was finished (mortared stone, walls, volume) -> server crashes
3. i removed the oven and finished the room -> no crash
4. i put the oven down into the finished room -> server crashes

actually took me a while and multiple crashes to pin this down on the oven.

**Comment by johnkslg** [comment]
Fixed, thank you!
