### ISSUE TITLE
[0.7.4.4] USER ISSUE: Doors show up in tables section of economy viewer

### ISSUE THREAD

**Issue by TheRealMaxion** [StrangeLoopGames/EcoIssues#7740]
In the economy viewer (from pressing Y), the tables tab has doors listed among the crafting tables.
I guess this is because doors have a crafting menu and a credits menu instead of where I think there was a lock menu.

**Comment by craig-jong** [comment]
Should not be the case anymore (7.5, or maybe 7.6)
