### ISSUE TITLE
USER ISSUE: Local server manager destroyed

### ISSUE THREAD

**Issue by Radoken** [StrangeLoopGames/EcoIssues#7741]
**Version:** 0.7.4.4 beta

**Steps to Reproduce:**
Try to join any server

**Expected behavior:**
Join the server

**Actual behavior:**
"Loading eco" window appears and counts to 9% then jumps to 90% after this the "Entering world..." window appears and i wait 2 minutes just get back to the main menu (happens in every server i try to join). My friends on the server say that i join the server but get kicked after 1 second. After every attempt to join a server i get a log which says "Eco Log Session from [date of attempt] [time of attempt] Disconnected from server. Local server manager destroyed, stopping server."

<details>
<summary>Log File</summary>(...previous log truncated...)

viour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.UI.Scripts.ChatUI.Update () [0x00025] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
 
(Filename: <f40bff3faa6041269b1e5f6e1739e5a0> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.UI.Scripts.ChatUI.Update () [0x00025] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
 
(Filename: <f40bff3faa6041269b1e5f6e1739e5a0> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.UI.Scripts.ChatUI.Update () [0x00025] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
 
(Filename: <f40bff3faa6041269b1e5f6e1739e5a0> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.UI.Scripts.ChatUI.Update () [0x00025] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
 
(Filename: <f40bff3faa6041269b1e5f6e1739e5a0> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.UI.Scripts.ChatUI.Update () [0x00025] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
 
(Filename: <f40bff3faa6041269b1e5f6e1739e5a0> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.UI.Scripts.ChatUI.Update () [0x00025] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
 
(Filename: <f40bff3faa6041269b1e5f6e1739e5a0> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.UI.Scripts.ChatUI.Update () [0x00025] in <f40bff3faa6041269b1e5f6e1739e5a0>:0 
 
(Filename: <f40bff3faa6041269b1e5f6e1739e5a0> Line: 0)

[05:19] Disconnected from server.Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

</details>

**Comment by metachronism** [comment]
chatUI exception

**Comment by gabeux** [comment]
+1 this seems to be happening to a few rare players and there seems to be no known fix or workaround at the moment.

**Comment by johnkslg** [comment]
@Radoken Im having trouble reproducing this. Can you message me on discord.gg/eco @johnk?  Or email john@strangeloopgames.com

**Comment by johnkslg** [comment]
Dropping priority as it seems uncommon, but following up with Radoken

**Comment by johnkslg** [comment]
User reports this fixed.
