### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by harevlesa** [StrangeLoopGames/EcoIssues#7742]
**Version:** 0.7.4.1 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Invalid username or password.
```

<details>
<summary>Log File</summary>Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GT 525M (ID=0xdf5)
    Vendor:   NVIDIA
    VRAM:     2000 MB
    Driver:   22.21.13.8476
Begin MonoManager ReloadAssembly
- Completed reload, in  1.950 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 41.193204 ms
Setting up 2 worker threads for Enlighten.
  Thread -> id: 1a68 -> priority: 1 
  Thread -> id: 159c -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.1 beta
Wednesday, May 09, 2018 9:53 PM
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fallback handler could not load library D:/ECO v0.7.4/Eco_Data/Mono/libc
Fallback handler could not load library D:/ECO v0.7.4/Eco_Data/Mono/.\libc
Fallback handler could not load library D:/ECO v0.7.4/Eco_Data/Mono/libc
Changing state: PreLogin -> PreLogin
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/D

**Comment by rainfarmer** [comment]
@harevlesa are you using Steam or our website version of Eco?
If from the website, what is your username? 'harevlesa' doesn't own the game on our website.

Closing until response. thanks
