### ISSUE TITLE
Graphical Issue - Visible Objects - Low Render Distance

### ISSUE THREAD

**Issue by EvilKenevil** [StrangeLoopGames/EcoIssues#7743]
**Steps To Reproduce**
Set low view distance and graphics across board, apart from Vibrance and 50% Render Scale. You can see animals, trees and peoples structures just floating around, and not unloaded, thus lowering fps.

**Expected Behaviour**
These items should be in visible, and i should be just looking into an empty abliss 

![capture](https://user-images.githubusercontent.com/38164448/39961471-7b240af6-562e-11e8-85a9-5a34bea27424.JPG)

**Comment by SeanAtr0n** [comment]
kinda hard to tell, i think those are chunks

**Comment by EvilKenevil** [comment]
137, 187

**Comment by metachronism** [comment]
this is working as intended.  Chunks unload "lazily" so as to reduce churn when walking around a given area.

If you go from high->low view distance without moving, you'll see this more dramatically
