### ISSUE TITLE
Difficulty.eco hasn't been updated for 0.7.4.0

### ISSUE THREAD

**Issue by UnknownViper** [StrangeLoopGames/EcoIssues#7744]
In the server software the setting for gaining skill points from crafting is now SkillPointsPerCrafttime, with the plural s added to point, which in pre-0.7.4.0 wasn't there, making it different from SkillPointsPerAction (and causing confusion).
In the Difficulty.eco supplied with the server download it hasn't been updated to the new name.

This is a minor issue, but does cause problems for people using my Network Control Tool on https://eco.viper.wtf, as I can't make it backwards compatible to pre-0.7.4.0 versions, unless I have this setting listed twice in the list, which is obviously silly and confusing to the user.
Likewise it's also an issue for those editing the file themselves, as they'll be editing a setting that isn't being read (assuming you're not reading both versions of the setting name).

For good measure this should just be updated regardless. :)

**Comment by UnknownViper** [comment]
I see that this has been fixed in 7.4.5 - thanks! :)

**Comment by craig-jong** [comment]
The version without the 's' is incorrect and likely wont work as intended.

I've switched the difficulty in master to use the S - thats how it should be in the current/next release. Let me know if thats not the case.
