### ISSUE TITLE
Gates and big doors and more

### ISSUE THREAD

**Issue by Melondres** [StrangeLoopGames/EcoIssues#7747]
it would be nice if we could have gates (like for Hangars) and bigger doors so we can build garages.
It also would be nice to  be able to switch the ramps  vertically so we can  make more decorative elements to buildings,  whats about 1x1x1 ramps? Curved Dices so we can build  arches. 
It  would be nice if we can select the broadside of the ramps  from  1x4to 2x4to 3x4to 4x4,
Another Idea would be to have some Kind of curves for the roads ready to use (maybe  8x8  fields?) . Also could be roadblocks in 4x4  and 2x4  verry helpful while building up roads.
A "water in" and "water out" block would be also great to  build  lakes and Ponds where we want to have them.
Ah and before i Forget: the bigger backpacks should give also bigger inventory :D

I hope i was able to give you some ideas.

**Comment by EvilKenevil** [comment]
This is for bugs and issues, not requesting damn items. Delete you post

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#53
