### ISSUE TITLE
Water does not refill and fishes spin

### ISSUE THREAD

**Issue by Serynthara** [StrangeLoopGames/EcoIssues#7749]
Dear Strange Loop Team, 

I have brought a few bugs, most of them are graphical ones.

**Water does not "refill"**
_I've built a bridge and destroyed it later the day, to replace it by a bigger one. I came across the following bug, seen in the pictures._

![20180513191643_1](https://user-images.githubusercontent.com/34604183/39970123-8cea8680-56e6-11e8-9cfe-2198d28c0503.jpg)
![20180513191711_1](https://user-images.githubusercontent.com/34604183/39970124-8ffe6dd2-56e6-11e8-9945-d64524638032.jpg)

**Fish spinning like all hell has broken lose, when caught with a fishing rod.**
_I've been fishing and the fish spun around the hooking point like.. Well._

![20180512235444_1](https://user-images.githubusercontent.com/34604183/39970143-01c25d7a-56e7-11e8-923c-7b4681fb7e77.jpg)
![20180512235444_2](https://user-images.githubusercontent.com/34604183/39970144-01d9fc96-56e7-11e8-8c41-694dab484e96.jpg)
![20180512235444_3](https://user-images.githubusercontent.com/34604183/39970146-01f28c7a-56e7-11e8-9c7c-e9f2eb1ce3fa.jpg)
![20180512235445_1](https://user-images.githubusercontent.com/34604183/39970147-020b412a-56e7-11e8-9bee-161f5d534259.jpg)

~~**Not enough room in inventory.**
_My girlfriend tried to pick up her cart, which was empty. She also had the correct deed in her backpack, but the following bug occured._~~

The scratched problem was solved by the comment below.

**Comment by Serynthara** [comment]
Ah thanks for the info about the cart, I'll leave up the water bug though, since... I guess it should be solved at some point. :)

**Comment by SlayksWood** [comment]
first part merged with #9971
second part merged with #11931
