### ISSUE TITLE
River Water issues - with Dams

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#7753]
Well I have river in my back yard so i put a dam earth works dam..

I was expecting water level to raise behind the wall and then run over at very least for the water in front of the dam to lower over time.

nether happened.

it be really nice to have little better water maybe add in water sources like underground springs like in real life where water flows from.

that way latter on we can create dams for power.

on subject of power it be nice to add power lines also so we can create power planets that can power whole towns or multiple buildings.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#51
