### ISSUE TITLE
[Suggestion] Illness

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7754]
From the support queue:

Hey, im a brazilian fan in love with your game and thinking about the possibility of introducing some kind of illness to the game, not something really complex just a few health problems capable to prejudice you somehow, like low stamina for example until you find a recipe or some cure. A good ideia delivering all this is bringing to the game some animals like rats, that players would try to eradicate for health. Thank you guys, this game is awesome !!!

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#50
