### ISSUE TITLE
Perma-Destroying Items without Consequences using Trashpiles

### ISSUE THREAD

**Issue by TwistedGate** [StrangeLoopGames/EcoIssues#7755]
**First of: i appologize for not following the format of how to reproduce stuff, what was expected and what actualy happend.**

As im not very good with words (and _please_ excuse me for that) i've recorded a little bug (or two) with the garbage, a bug that let's you pretty much destroy items without leaving these tailings like blocks that end up apearing after a while.

I hope it helps, here's the video: https://www.youtube.com/watch?v=gqraXPM7nRc

If that video doesnt help i'll try my best to explain or whatever needs to be done.

**Comment by Thineboot** [comment]
Sometimes a video is worth a thousand words 👍

**Comment by Kastuk** [comment]
I got the same? but without exceptions.
Also you can add into disappeared garbage pile anything more.

**Comment by TwistedGate** [comment]
Everything that can be thrown away and as much as fit's into the container.
