### ISSUE TITLE
Server wouldnt start due to parsing error

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7756]
![image](https://user-images.githubusercontent.com/3536496/39973047-13eb50d2-56cf-11e8-86f6-08f7994c9fb3.png)
Reported by 

руслан зубок <ruslan18052@gmail.com>
--

**Comment by johnkslg** [comment]
Could it be Russian blockade related?

**Comment by johnkslg** [comment]
The guy was in Ukraine so probably not.

**Comment by metachronism** [comment]
this is an auth server error

**Comment by johnkslg** [comment]
Why is it not high priority?

**Comment by rainfarmer** [comment]
User owns eco on steam, but not their slg account. Yet they are linked. so probably related to that.
I updated their slg account. should fix it
