### ISSUE TITLE
Water doesn't flow correctly

### ISSUE THREAD

**Issue by matias-b** [StrangeLoopGames/EcoIssues#7757]
I was removing sand and noticed water didn't fill the space left.
(grass grew on top of the dirt that was below sand after a while)
Running 7.4.4

![playaeco](https://user-images.githubusercontent.com/17019409/39978030-799a6180-5714-11e8-9d0e-8520373e3c5c.png)

**Comment by pamduncan** [comment]
This is known, water is not fully complete yet and does not 'run' like real water.  If you want to move water you can use the aqueducts to get it from place to place

**Comment by GophTheGreat** [comment]
Closing this. Another pass on water is planned at a later date.
