### ISSUE TITLE
Magic teleportation allows you to steal from others

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#7760]
steps

1. put chest near other players border in range of some storage chest or something of theirs.
2. open chest that you put down
3. move there item from there chest to yours

screen shoot included.

 I have no permissions for anything of this guys.

![20180514043432_1](https://user-images.githubusercontent.com/15990789/39989889-d2bb4542-5730-11e8-92a3-2fbc785d58ea.jpg)
![20180514043446_1](https://user-images.githubusercontent.com/15990789/39989891-d548e238-5730-11e8-86b8-73b74b79df51.jpg)

**Comment by mindforger** [comment]
as far as i remmeber, the icebox starts in public mode instead of derived when placed, did you double check the icebox is not in public mode?

**Comment by SeanAtr0n** [comment]
@craig-jong  maybe we could have the template set auth to inherited if an object has storage + property auth?

**Comment by midn8t** [comment]
I cant check ice box its locked in persons house i have no access to it, but not sure if this is bug or not but, if someone gives access to a table.  i can then go and link there inventory and take or use there stuff even if i do not have permission at chest or storage..  at least thats been my experience so far.

seems like if you have access to one thing that link to other storage gives access to other things sometimes.

**Comment by matias-b** [comment]
this happens with braziers too, you can steal coal from them

**Comment by mindforger** [comment]
Sounds like they acknowleged the issue with the default settingd. Being able to override access rules over claim is important for business and contract stuff, but inherited rules should be default imho when placing inside a claim. If you find other objects with wrong default add them here please

**Comment by JamesTalon** [comment]
Icebox, braziers, bookshelf, fish trap, these are all set to public by default

**Comment by Deantwo** [comment]
I often see players leave their deeds in bookshelves or iceboxes.

This is simply a default Auth probably. I would assume it is already fixed for next update? Plenty of "Auth fixes" have been committed through #codestream.

As for the report itself. You can just use someone's crafting stations, they also default to public so through that you can access all public containers around the claim. Nothing weird or magical about it, just a bug with default Auth.

**Comment by craig-jong** [comment]
All auth was changed to default to inherited recently. I'm going to close this, please reopen it if you notice any stray objects.
