### ISSUE TITLE
Networking Issue - Non Default Ports

### ISSUE THREAD

**Issue by JamesTalon** [StrangeLoopGames/EcoIssues#7764]
When setting up my server, I used ports 4000 and 4001. Before 7.4, this worked as expected, people could see the server, see the status of it, connect, etc. Since 7.4, the server perpetually shows as offline in the server browser and does not appear in the public server tab.

Expected Behavior:
Server shows as online and joinable without IP address

Actual Behavior:
Only shows online and joinable when using default ports

**Comment by metachronism** [comment]
I tracked this down.  It looks like it might have been caused by the master server not respecting the change from private->public server listing, if the listing persisted on the server.  I've updated the master server to account for this.

**Comment by JamesTalon** [comment]
Not sure if this would be noticeable on my end right away, but I did a quick check, and it still shows as offline, even for LAN, and its on the same computer as I play
