### ISSUE TITLE
Proposing law shows error message

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#7766]
Sometimes when I click propose on the propose law form, instead of showing me the law proposal page, it will show me this error message:

![image](https://user-images.githubusercontent.com/23460210/40018451-2ec88242-5771-11e8-98a1-af3b11c9a1fc.png)

The law is still created correctly, and I can go look at the law proposal page with the link in the left nav bar.  Presumably this is some kind of race condition, i.e. the web page tries to load the law summary before the law has finished being created.  I don't see this pop up on the server when this happens, so it's not related to a server side exception, but we may have to fix the race condition server side, not sure.

**Comment by rainfarmer** [comment]
fixed
