### ISSUE TITLE
7.4.4 > Holes in the world (invisible blocks) at X-coordinate 0

### ISSUE THREAD

**Issue by Rick86** [StrangeLoopGames/EcoIssues#7768]
Hey there, since 7,4.0 (and also in 7.4.4) the are missing blocks at X-coordinate 0 (the point where the world "connects" to eachother, the whole is around the world with a width of 10 blocks or something. Seems there is no difference if I use my current world with my configs and mods, or if I use the default / empty settings (no mods, no storage, default configs). So in a new created world, the error happens also.

If you walk over the hole (even with a wood cart), the blocks will be displayed again and everything seems fine. After reconnect the blocks are invsible again.

If you try to drive over the hole (with powered cart oder truck for example), you get a visual "blizzard" with stuttering sound, or sometimes you will jump over the world.

**Comment by SeanAtr0n** [comment]
will be fixed in 7.4.5

**Comment by Rick86** [comment]
Ah okay, now I saw all the reports in the closed part here. Maybe you should disable the default "isOpen" filter, so everyone can see if there were already the same reports, because I wondered, there aren't yet :D
