### ISSUE TITLE
Law creation page will accept line returns, but law display in game does not show them. 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7775]
![image](https://user-images.githubusercontent.com/6262198/40028997-f475c8a4-5796-11e8-8e68-9716fe921782.png)

![image](https://user-images.githubusercontent.com/6262198/40029029-16c4fb6e-5797-11e8-961b-bb996a28133b.png)

**Comment by Nanders** [comment]
Related

Comment entry accepts new line, but doesn't display it correctly

![image](https://user-images.githubusercontent.com/6262198/40083058-e73cccd0-5847-11e8-8ae3-1085b1fee49a.png)

**Comment by rainfarmer** [comment]
@mirasrael can you check into adding line break for the in-game display.
Although it might be necessary to remove line breaks in-game for design space. i.e. not too big
