### ISSUE TITLE
Can’t switch torch stand or brazier with empty shovel  selected

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#7777]
This are conflicting functions, the load function from shovel and the switch function of the brazier, bud can leave you wondering why it don’t work. May be there are other devices like wall lamps, street lamps… bud I have not reached so far. Would be nice if there could be a solution.

**Comment by Nicolausi113** [comment]
For completion I should show the way to reproduce:
- select a shovel and dig a dirt, place the dirt somewhere
- go to a brazier and try to switch it
- it won't work

**Comment by SlayksWood** [comment]
Same behavior with Door #3868

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-192

Appears to be fixed.
I am able to switch both Torch Stand and Brazier ON and OFF while holding a shovel.
