### ISSUE TITLE
Can't play game except on other peoples servers

### ISSUE THREAD

**Issue by dwoodsky** [StrangeLoopGames/EcoIssues#7778]
![ecobugscreen](https://user-images.githubusercontent.com/39308192/40066290-b6428584-585b-11e8-8f42-a22cd19f9849.JPG)
New, then any settings and start, or continue, or load, when clicked, remove the IU showing this screen indefinitely, escape key brings the main menu back immediately, have not been able to play since updating to bleeding edge version and issue persists at 7.4.4 even with complete fresh installs
can join other servers but want solo/commands for tinkering

Windows 10 up to date
intel i5
radeon r9
8gb ram
Steam purchase/install

**Comment by dwoodsky** [comment]
Windows 10 up to date
intel i5
radeon r9
8gb ram
Steam purchase/install

**Comment by turnburgler** [comment]
Try disabling antivirus, that worked for me!

**Comment by MarjieAVolk** [comment]
If disabling antivirus doesn't work, can you send me your log file?  C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt

**Comment by dwoodsky** [comment]
Tried, disabling antivirus doesn't seem to affect
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2016489/output_log.txt)

**Comment by dwoodsky** [comment]
Verified game files no problems found, still doing it, have also tried setting the .exe to run as admin no change

**Comment by MarjieAVolk** [comment]
Okay, well the quick and dirty thing you can do is to navigate to that file path ('A:\Games\steamapps\common\Eco\Eco_Data\Server\Storage') and just create any folders that are missing.  I assume just Storage is missing.  If that is the case, creating the empty folder will allow you to create new worlds, but you will have to select 'Generate New'.

If Verify Game Files didn't work though, I would suggest re-installing the game, to try to get back the extra files that are missing from inside the Storage folder.

**Comment by dwoodsky** [comment]
Storage folder present and filled with saves of new games I have attempted to launch, cleared and gonna try now, have reinstalled as well as uninstalled, manually deleted all files and reinstalled several times to no effect so thinking maybe an issue with my system/OS but unsure

![eco files](https://user-images.githubusercontent.com/39308192/40325157-a8108ebc-5d32-11e8-8123-2e2d7f49f48b.JPG)

**Comment by dwoodsky** [comment]
No change noted, irritating that I purchase Minecraft 6 for awesome vehicular escapades, then upon the big vehicle updates its swapped out for a £23 screen saver with bird noises.

**Comment by MarjieAVolk** [comment]
Oh, the folder is there?  That's very odd.  In that case, have you tried running the game as an administrator?  You will have to find Eco.exe in the installation directory, right click it and go to the Compatibility tab; select the 'Run this program as an administrator' checkbox, and click Ok.  Then launch from steam again.

**Comment by dwoodsky** [comment]
Have tried running as admin, no luck :/

**Comment by MarjieAVolk** [comment]
Hm well this is very odd, I'm not sure how to solve it.  I haven't heard any other similar reports, so I suspect it is something odd on your computer, but I can't be 100% sure.

But in an attempt to let you get playing now -- You could try running a local server using the 'Eco Server' tool.  To install it, in Steam select Library>Tools, and it will be in the list.  Then you can run Eco Server to startup your server, and join it from the Join screen in game.

**Comment by dwoodsky** [comment]
![ecoserver](https://user-images.githubusercontent.com/39308192/40431288-0c64a7b4-5e9f-11e8-877c-2d13b7b18c0d.JPG)
Eco server Doesn't work either :D 
Seems to be an issue with windows 10 or steam dicking with my files as there are copies and copies of folders all over the place so am uninstalling all and reinstalling, shall update with results

**Comment by dwoodsky** [comment]
Seems to be working following a total wipe of steam and reinstall on different drive

**Comment by MarjieAVolk** [comment]
Great, thanks for following up.  So a strange windows/steam problem 🤔
