### ISSUE TITLE
Linux Client duplicates key input

### ISSUE THREAD

**Issue by BaconFist** [StrangeLoopGames/EcoIssues#7780]
No matter where, all my keyboard input is dupliated.
- Server browser: type an ip adress you waynt to connect to eg. 127.0.0.1 it will write 112277..00..00..11
- ingame: try to pen the chat with ENTER: the chat will open and instantly close because ENTER gets doubled.
- not to say it is kind of hard to connect to a server with password
- switching mouse-ui/mode with tab works well.

I indeed asked google and found something. It's likely somethin with ibus. Mostly linux realted double key stuff i found were ibus realated.

Environment:
Ubuntu Budgie 18.04
Eco 0.7.4.4 beta (Steam)
Keyboard: Logitech G810 / (also tested with onboard virtual keyboard)

**Comment by ReedME** [comment]
I have the same issue, some research showed people having this issue in other games running on Unity.
In my case all input is doubled - pressing tab to switch to mouse UI mode can often result in it switching in and out of mouse mode and movement input is the same. Pressing space results in a double jump. 
Ubuntu 18.04 Bionic Beaver,
Eco 0.7.4.6
Keyboard Razer Deathstalker

**Comment by SeanAtr0n** [comment]
duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/3580
