### ISSUE TITLE
Connecting by ip should have a timeout

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#7784]
Connecting via the master server apparently has a timeout, and eventually pops up an error message.  Connecting directly by ip address does not seem to.

**Comment by metachronism** [comment]
just verified this works fine in master

**Comment by MarjieAVolk** [comment]
Yeah I saw this too.  There's some other problem this person is seeing I guess.  Thanks.

**Comment by gabeux** [comment]
Exact same thing happens to me when trying to connect to the only available bleeding edge server. 
Might need another server to check .

**Comment by MarjieAVolk** [comment]
Were you connecting by ip?  I would imagine you were connecting via the server browser.

**Comment by gabeux** [comment]
Yep, connecting via ip works. Server browser has timeout. But there's only 1 server in the browser for bleeding edge at the moment showing to me :/

**Comment by elfl0rd** [comment]
it's my server and this is in Russia...
Maybe they have problem with connecting to masterserver.
