### ISSUE TITLE
Stockpile array overflow

### ISSUE THREAD

**Issue by Hactarus** [StrangeLoopGames/EcoIssues#7785]
Stack 
Version: 0.7.4.4 beta (maybe before)

Steps to Reproduce:
Place a stockpile and put some stuff in it until is full.
On the last action (put a stack in the last slot), one of the stockpile slot (a random one) will loose it content.

Expected behavior:
"Use every slot of the stockpile witouth lossing stuff."

Actual behavior:
Don't use all slot of a stockpile, don't use shop to buy  stuff with stockpile's storage

**Comment by surcoufx83** [comment]
I had the same behavior with 0.7.3.3 and 0.7.4.2 too. And most times it occurs at random insert, not at the last one (on my server)

**Comment by metachronism** [comment]
closing as dupe of #3182 - its a tricky one :/
