### ISSUE TITLE
Skill Point Bar stopped increasing

### ISSUE THREAD

**Issue by HMMurdoch** [StrangeLoopGames/EcoIssues#7786]
My friend and I have been playing on a server and increased the skill point gain to suit our needs. Doing this caused the skill points to up rather fast so I could see the change in the bar and tell we were getting points. After I relaunched the server today we were no longer gaining skill points and the skill points bar had frozen, not moving at all even though we had plenty of Nutrition and house points giving us experience.

**Comment by elfl0rd** [comment]
no more happens
