### ISSUE TITLE
Server Connection

### ISSUE THREAD

**Issue by ml0130** [StrangeLoopGames/EcoIssues#7787]
Don't know what causing this. Start a day or 2 after rolling the game back to 7.3.3
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1060 3GB (ID=0x1c02)
    Vendor:   NVIDIA
    VRAM:     2999 MB
    Driver:   23.21.13.8813
Begin MonoManager ReloadAssembly
- Completed reload, in  0.102 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.999423 ms
Setting up 2 worker threads for Enlighten.
  Thread -> id: 1d00 -> priority: 1 
  Thread -> id: 2ab4 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.4 beta
Friday, May 11, 2018 2:33 PM
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> ServerBrowser
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[34:58] Connecting via Lidgren to caledorn.ddns.net:3000
Changing state: ServerBrowser -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[35:13] Disconnected from server.Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
![unknown](https://user-images.githubusercontent.com/27445711/40155224-514375d4-5947-11e8-9111-42eef91d0536.png)

**Comment by elfl0rd** [comment]
Russia?)

**Comment by pamduncan** [comment]
Did you use a backup from the older version?  If teh world updated your cannot take it back to an older version of the game
