### ISSUE TITLE
Error Dump when trying to Join a server.

### ISSUE THREAD

**Issue by bryangrossman** [StrangeLoopGames/EcoIssues#7788]
The game itself loads fine, I can start a local game and enter it just fine. It just when I try and Join a server the game dumps an error. 

Dump Starts Here:

<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: AMD Radeon HD 5670 (ID=0x68d8)
    Vendor:   ATI
    VRAM:     1010 MB
    Driver:   15.200.1062.1004
Begin MonoManager ReloadAssembly
- Completed reload, in  0.158 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 2.286667 ms
Setting up 2 worker threads for Enlighten.
  Thread -> id: 1f8c -> priority: 1 
  Thread -> id: 1a14 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.4 beta
Friday, May 11, 2018 3:33 PM
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> ServerBrowser
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[42:38] Connecting via Lidgren to caledorn.ddns.net:3001
Changing state: ServerBrowser -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[42:53] Disconnected from server.Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by elfl0rd** [comment]
Russia?

**Comment by metachronism** [comment]
ports changed, no longer use 3001, should use 3000 by default
