### ISSUE TITLE
 Disappearing objects

### ISSUE THREAD

**Issue by sallazarPL** [StrangeLoopGames/EcoIssues#7790]
All objects placed on road becomes invisible. After restart game my truck becomes invisible and 
untouchable. Ramps placed on this road are invisibles.
![desktop screenshot 2018 05 16 - 13 27 16 83](https://user-images.githubusercontent.com/20505612/40114373-fa5bd034-590c-11e8-964a-d14617ac5768.png)

**Comment by SeanAtr0n** [comment]
fixed 7.5
