### ISSUE TITLE
USER ISSUE: Not able to join Server with Family Shared Game

### ISSUE THREAD

**Issue by IceManX93X** [StrangeLoopGames/EcoIssues#7791]
**Version:** 0.7.4.4 beta

**Steps to Reproduce:**
1. Start shared Game
2. Join Server	

**Expected behavior:**
I can join the Server..	

**Actual behavior:**
A error "Invalid login info. User does not own Eco" appears

<details>
<summary>Log File</summary>Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1050 Ti (ID=0x1c82)
    Vendor:   NVIDIA
    VRAM:     4018 MB
    Driver:   24.21.13.9764
Begin MonoManager ReloadAssembly
- Completed reload, in 10.858 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 7.897273 ms
Setting up 6 worker threads for Enlighten.
  Thread -> id: 1fd0 -> priority: 1 
  Thread -> id: 4d40 -> priority: 1 
  Thread -> id: 24e0 -> priority: 1 
  Thread -> id: 3c44 -> priority: 1 
  Thread -> id: 5340 -> priority: 1 
  Thread -> id: 2d64 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.4 beta
Freitag, 11. Mai 2018 23:33
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[02:15] Disconnected from server.</details>

**Comment by elfl0rd** [comment]
Family sharing is not supported at this moment.

**Comment by GophTheGreat** [comment]
Not only do we not have plans for it, we actively disabled it because it was causing problems. Closing this ticket.
