### ISSUE TITLE
Suggestion - Further benefits of food / health / MD profession

### ISSUE THREAD

**Issue by armyofskankz** [StrangeLoopGames/EcoIssues#7792]
For food, I find myself doing perfectly well with boiled shoots, campfire beans, charred tomatoes/corn/camas for a balanced diet during the entire game. There is really no need for me to make anything more complicated except for research purposes.

I propose some way of incentivizing higher tiers of food. Possibly related, a health metric would add a new dimension. This could be impacted by pollution, falling high distances, having rocks fall on your head, animals charging at you, spending too much time under water etc. 

Health would open a new specialty path - medicine, which could have its own set of recipes, furniture, and research.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#46
