### ISSUE TITLE
USER ISSUE: World creation fails

### ISSUE THREAD

**Issue by mastercake10** [StrangeLoopGames/EcoIssues#7793]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
1. Start the game on Linux using Steam
2. Create a new World and tick "Generate New"
3. Click "Start"

Sad that the game still does not work, I bought the game half a year ago, and it still does not work and has many bugs. 

**Expected behavior:**
Generate a world I guess?

**Actual behavior:**
Error: Could not start server: Object reference not set to an instance of an object

**Comment by mastercake10** [comment]
Using an old version

**Comment by Schuermi7** [comment]
This Bug still exists. Reporting from 7.4.4

**Comment by metachronism** [comment]
@mastercake10 @Schuermi7 
can you provide some more info perhaps?  what your OS is, what game version you are using, etc, and reopen this
