### ISSUE TITLE
Frezzes and Lags :(

### ISSUE THREAD

**Issue by HitoryLP** [StrangeLoopGames/EcoIssues#7794]
I got some kind of performance problems. First of all my specs: i7 processor, GeForce 1080 (2GB VRAM) and 16GB RAM. I was watching my RAM via the Windows Taskmanager and after one of many complete frezzes is began rising vrom 200MB to 3GB  and all the time my RAM was rising my game lagged af. I'm sorry to say but the performance really needs a boost. You can see my specs are way higher than the recommanded and I got such big lags. How could this be? I played this game now over 60 houres and the frezzes and the lags comes more often as our world growes. (btw im playing on a Nitrado server with only one other person, we playing for 5 days now). So please can you give me some advice to boost my performance or can you make some sort of fix? ty for your responce. (P.S. I'm not an english native so pls don't judge my mistakes :P)

**Comment by PacifyerGrey** [comment]
We do experience the same on our public server (KatherineOfSky).
I did not monitor RAM usage during lag out but I surely will.
It just starts lagging out with 0.3 FPS (yes less than 1 FPS) and does so for a few seconds (10-15) and then goes back to normal.

And have to admin that since 7.4 patch overall performance did drop significally.

**Comment by HitoryLP** [comment]
im with you. I really hope they fix this massive performance problem. Hopefully they will listen on there community...

**Comment by mindforger** [comment]
isn't eco based on java? maybe the garbage collector is acting up, i had such issues with minecraft servers in the past until i tweaked the garbage collector via JVM options during launch

does eco deal with garbage collector optimization already? maybe we can discuss this in discord at some point, java is optimized for 2GB RAM, if you increas above, some tweaks are required, especially when dealing with many short living class-objects like vectors and such ... will plan to be online in about 10h from this post on (18:30 GMT+1 Summertime) ... and if somebody can find out until then how to add JVM arguments to the server launch script would be wonderfull :)

**Comment by HitoryLP** [comment]
To be honest I don't know what is Eco running on. I really hope it is not Java.

**Comment by GophTheGreat** [comment]
Eco is developed on Unity.

**Comment by mindforger** [comment]
yeah i figured out in discord already, my bad, must have been a rouge minecraft server isntance been running which i forgot on my root

**Comment by metachronism** [comment]
sean fixed some of this with 7.4.6, we are looking more into performance soon with other stuff as well though.
