### ISSUE TITLE
View Distance and The Border: Rendering issue

### ISSUE THREAD

**Issue by MaxInertia** [StrangeLoopGames/EcoIssues#7796]
Blocks do not render properly near borders. This occurs every time I approach the border from a location further from it than my view distance.

Once I cross the border the blocks will load in. 

Prior to crossing, I can only see specific world objects (chests, trees, doors, signs, stockpiles, road ramps, broken stone, etc). These blocks seem to be within my view distance setting, and therefore would be visible if there were not a wall of blocks between me and them.

![image](https://user-images.githubusercontent.com/12981415/40143454-1668f432-5921-11e8-96d0-1f3751b9b677.png)

My view settings in case that's relevant.

![image](https://user-images.githubusercontent.com/12981415/40143479-26305054-5921-11e8-8dac-b84297d32355.png)

As you can see from the screenshots below, I can interact with the blocks on that side normally, it's only the rendering of them which is an issue.

### Able to break a block over the border
![image](https://user-images.githubusercontent.com/12981415/40143845-2bc20aac-5922-11e8-88ce-9267bc100ad6.png)

### Able to place a block over the border
They remain invisible after being placed.

![image](https://user-images.githubusercontent.com/12981415/40143866-3dd2012a-5922-11e8-9546-3931ec76a9d7.png)

## After having crossed the border.
The image below is taken from a similar position and orientation as the first, but after crossing the border. Once the border is crossed (Z value was set to 0), the game realizes that these blocks ARE within my view distance, and therefore render. 

![image](https://user-images.githubusercontent.com/12981415/40143978-983755a2-5922-11e8-8918-eb69921c6ca3.png)

The game doesn't appear to be taking the wrapping world coordinates into account determining if blocks are within a users view distance (and therefore whether they should be rendered).

The same occurs when approaching the border from the opposite side.

**Comment by SeanAtr0n** [comment]
fixed in 7.4.5

**Comment by MaxInertia** [comment]
Awesome! Great job guys 😄
