### ISSUE TITLE
[7.4.4] Shop prices decimal separator comma issue

### ISSUE THREAD

**Issue by PacifyerGrey** [StrangeLoopGames/EcoIssues#7797]
It seams the issue started in 7.4 (was definitely not an issue in 7.3.3)

The game has always used dot as a decimal separator for both display and shop interface.

For my region decimal separator is comma. And starting with 7.4.4 (which our server has migrated to) prices in the market window show a decimal separator of comma for me. However the shop interface does not let me type comma and typing a dot results in an effective price of 0 (displayed for other players and market) while shop window still shows me a correct value with a dot in it.

I did try to change decimal separator in Windows 10 regional settings / Advanced (while not changing the region itself) and restarting the game with no success. It seams the game inherits the setting from somewhere else or keeps it cached in some way.

That is how some people from Europe end up with a 0 price wares in their shops on the server.

Edit:
Changing number formatting to English (USA) solves the issue. But the bug should be fixed still as this is only a temporary bandaid solution

**Comment by madxmat** [comment]
I stumbled upon this issue and while I can keep windows region as it is (Poland) I have to change region formatting of date, numbers etc. to English (USA). Changing only the decimal separator while having local formatting doesn't work. It looks like game is checking if the formatting is set up to USA version and not if decimal separator is comma or period.

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/4971

**Comment by johnkslg** [comment]
Fixed!
