### ISSUE TITLE
audio warning with doors

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#780]
Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (DoorOpenSfx).
UnityEngine.GameObject:SetActive(Boolean)
ClientObjectMap:InstantiateFromType(String) (at Assets/Scripts/ModKit/ClientObjectMap.cs:64)
GenericClient`1:SpawnObject(Int32, BSONObject, String) (at Assets/Scripts/Networking/GenericClient.cs:124)
PlayerClient:SpawnObject(Int32, BSONObject, String) (at Assets/Scripts/Networking/PlayerClient.cs:24)
GenericClient`1:NewNetworkObject(Int32, BSONObject) (at Assets/Scripts/Networking/GenericClient.cs:160)
Eco.Shared.Networking.NetObjectManager:GetObject(Int32, BSONObject, Boolean) (at E:/Projects/Eco/Server/Eco.Shared/Networking/NetObjectManager.cs:267)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject) (at E:/Projects/Eco/Server/Eco.Shared/Networking/NetObjectManager.cs:117)
NetworkManager:ReceiveEvent(INetClient, NetworkEvent, BSONObject) (at Assets/Scripts/Networking/NetworkManager.cs:315)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject) (at E:/Projects/Eco/Server/Eco.Shared/Networking/NetObject.cs:61)
Eco.Shared.Networking.NetPort:ProcessBuffer(Int64) (at E:/Projects/Eco/Server/Eco.Shared/Networking/NetPort.cs:196)
Eco.Shared.Networking.NetPort:Update(Int64) (at E:/Projects/Eco/Server/Eco.Shared/Networking/NetPort.cs:215)
NetworkManager:Update() (at Assets/Scripts/Networking/NetworkManager.cs:275)

**Comment by Nanders** [comment]
Fixed now in SVN
