### ISSUE TITLE
Suggestion: More Powergeneration and new Powerconnection System

### ISSUE THREAD

**Issue by maginator** [StrangeLoopGames/EcoIssues#7804]
Hi,
My Idear was something like a Steamturbine with Water Pump and Pipes to get Water in. And a new Powerconnection System that you might be need Cable and not only "over the air Energy" and for mechanical maybe Gears and Shafts. Also a idear that you need Transformstations and High Voltage and something like this.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#45
