### ISSUE TITLE
Water population decreases after 24h

### ISSUE THREAD

**Issue by surcoufx83** [StrangeLoopGames/EcoIssues#7805]
Hi there,

I'm playing on a linux server in my private network. On my first server (world created with 0.7.2.5) I wondered, why the population starts decreasing after 24 hours (can be seen in web statistics). With my second world (created with 0.7.3.3) I experienced the same.
So I started two worlds (0.7.3.3 and 0.7.4.2) where no player will connect. The ecosystem is on it's own and again you can see that the population decreases after 24 hours.

What is causing this and shall players (or admins) do something against it?

![2018-05-17 22_23_24-eco](https://user-images.githubusercontent.com/1303974/40202002-002c16c6-5a21-11e8-999a-1faecc68160e.png)
![2018-05-17 22_20_25-eco](https://user-images.githubusercontent.com/1303974/40202003-004eaf06-5a21-11e8-917d-2faca9ec6dc6.png)
![2018-05-17 22_22_48-eco](https://user-images.githubusercontent.com/1303974/40202004-00690202-5a21-11e8-967a-1e4f3c63ba01.png)

**Comment by headswe** [comment]
I have the exact same drop in my linux world.

**Comment by lightdrawn** [comment]
I have pretty much the same problem, the only reason I didn’t bug report earlier is, my world is heavily modded.
Server v0.7.4.5 on Windows, world is generated with v0.7.4.4 or 0.7.4.5, world size 140x140

Additionally to the screenshots below, FreshWater seems to switch on and off over time. 


![screenshot 1402](https://user-images.githubusercontent.com/16464028/40473698-32a1800c-5f3d-11e8-95ad-3336d2a39d2f.png)
![screenshot 1404](https://user-images.githubusercontent.com/16464028/40473699-32d4a482-5f3d-11e8-8291-50cccaea26d9.png)
![screenshot 1406](https://user-images.githubusercontent.com/16464028/40473701-32f56938-5f3d-11e8-9f3f-5944ddfd3399.png)

**Comment by surcoufx83** [comment]
I only have one drop of population (one server running since 50 days) and the temperature drops only when server is down

**Comment by lightdrawn** [comment]
I’m sorry I didn’t want to mess up your bug report.

I deleted my previous post, because as I expected first, there was a mod, at least involved, causing unexpected things.

**Comment by craig-jong** [comment]
The populations are expected to settle over time, so I'm not sure this qualifies as a bug. At least until we change world gen, these sorts of shifts are expected because worldgen can't properly place animals 100% of the time.
