### ISSUE TITLE
Removing the last furniture/room does not refresh the HV count/meter display in the UI

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#7806]
Hello!

Removing the last furniture in the last room you have does not update the HV counter and graph in the UI back to zero:

![Issue](https://thumbs.gfycat.com/MiserableSaltyApe-size_restricted.gif)
[Higher quality](https://gfycat.com/MiserableSaltyApe)

Thanks!

**Comment by BlazeGuy2** [comment]
Closing due to Craig's fix.
