### ISSUE TITLE
USER ISSUE: Spamming esc makes screen freeze on option page

### ISSUE THREAD

**Issue by mrpeeps** [StrangeLoopGames/EcoIssues#7807]
**Version:** 0.7.4.5 beta

**Steps to Reproduce:**
hit the escape button a few times quickly

**Expected behavior:**
closed when I hit esc again	

**Actual behavior:**
Just stayed on options page, regardless if I click escape again.

<details>
<summary>Log File</summary>(...previous log truncated...)

  Loading RouteProbing... 
LocalServer -  Starting WorldLayerManager... 
LocalServer -  Loading Layers... 
LocalServer -  Initializing world layers... 
LocalServer -  Starting EconomyTracker... 
LocalServer -  Starting WorldObjectManager... 
LocalServer -  Starting EconomyPlugin... 
LocalServer -  Loading Economy... 
LocalServer -  Starting RoomPlugin... 
LocalServer -  Loading Rooms... 
LocalServer -  Starting ObjectivePlugin... 
LocalServer -  Loading Objectives... 
LocalServer -  Starting Legislation... 
LocalServer -  Loading Laws... 
LocalServer -  Starting WebServerPlugin... 
LocalServer -  Starting HousingTierDefinition... 
LocalServer -  Initializing LocalizationPlugin... 
LocalServer -  Initializing WorldGeneratorPlugin... 
LocalServer -  Initializing UserManager... 
LocalServer -  Initializing MinimapManager... 
LocalServer -  Initializing WorldObjectManager... 
LocalServer -  Initializing RoomPlugin... 
LocalServer -  Initializing HousingTierDefinition... 
LocalServer -  Initializing WorldPlugin... 
LocalServer -  Ticking... 
LocalServer -  Compressing... 
LocalServer -  Saving world... 
LocalServer -  Initializing WorldLayerManager... 
LocalServer -  Initializing WebServerPlugin... 
LocalServer -  Failed to start Webserver: Exception has been thrown by the target of an invocation.
LocalServer -  Server Initialization finished in 28,234.1ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[13:42] Connecting via Lidgren to localhost:3000
Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoadingWorld -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

</details>

**Comment by HeyBanditoz** [comment]
Can reproduce.

**Comment by MarjieAVolk** [comment]
Fixed, but the fix won't be released until 8.0
