### ISSUE TITLE
USER ISSUE: https://github.com/georgis1999/georgis.git

### ISSUE THREAD

**Issue by georgis1999** [StrangeLoopGames/EcoIssues#7810]
**Version:** 0.7.1.0 beta staging-b9d4fcf5

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Could not start server: Process has not been started.
```

**Comment by thereporter42** [comment]
Ok why the heck are there 5 tickets all made by the same guy about the same issue. 
Please make only ONE ticket for the same issue.  I looked at each of these tickets
and they are all the same. making multiple tickets for the same issue is not going to 
get the issue fixed faster. Please cease this immediately 

https://github.com/StrangeLoopGames/EcoIssues/issues/7810
https://github.com/StrangeLoopGames/EcoIssues/issues/7811
https://github.com/StrangeLoopGames/EcoIssues/issues/7812
https://github.com/StrangeLoopGames/EcoIssues/issues/7813
https://github.com/StrangeLoopGames/EcoIssues/issues/7814

**Comment by GophTheGreat** [comment]
Not only that, but it's of really old version of Eco if that version number is correct. Closing this ticket.
