### ISSUE TITLE
You can't swap a full stack with a partially full one

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7816]
You can only swap a partially full one with a full one

![image](https://user-images.githubusercontent.com/6262198/40249615-670cd404-5a88-11e8-90ba-4d74319fef50.png)

**Comment by MarjieAVolk** [comment]
That's because this isn't actually swap stacking, it's moving all items possible from the dragged stack to the target stack.  Not that we can't make this work if we want to.
