### ISSUE TITLE
Network usage jumping to 100% since 7.4.5 (smog rate related?)

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7817]
A friend of mine has problems since update 7.4.5 ->

He connects, play for a while and suddenly the network usage is jumping to 100%.
He alt+f4 the game. starting again, connects. Problem still persist. He allready reinstalled the game. The last error in hist log is: https://pastebin.com/zTik5VnJ

Log: https://pastebin.com/zTik5VnJ

**Comment by johnkslg** [comment]
Game files: http://cranktube.tv/gamestats.zip

**Comment by metachronism** [comment]
sean fixed this in 7.4.6
