### ISSUE TITLE
Simultaneous logins should not be possible

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#7818]
You can currently login twice to the same server and it doesn't kick one off.

This also makes it so you can meet your clone in debug mode when you crash

**Comment by johnkslg** [comment]
Its debug only?

**Comment by SeanAtr0n** [comment]
you can do this in release as well

**Comment by metachronism** [comment]
fixed a while back
(can leave it enable for you though sean if you want some friends?)
