### ISSUE TITLE
USER ISSUE: Crashed when world was loading

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7821]
**Version:** 0.7.5.0 beta staging-77a8710c

**Steps to Reproduce:**
Continue to former world (via bleeding edge)	

**Expected behavior:**
Login to world

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Connection timed out
```

<details>
<summary>Log File</summary>(...previous log truncated...)

 
LocalServer -  Starting GarbagePlugin... 
LocalServer -  Starting DisasterPlugin... 
LocalServer -  Starting ControllerManager... 
LocalServer -  Starting PropertyManager... 
LocalServer -  Starting EcoSim... 
LocalServer -  Starting WirePlugin... 
LocalServer -  Starting ChatServer... 
LocalServer -  Starting DifficultySettings... 
LocalServer -  Loading Garbage... 
LocalServer -  Loading Disasters... 
LocalServer -  Loading Property... 
LocalServer -  Loading Chat... 
LocalServer -  Starting MinimapManager... 
LocalServer -  Loading Plants... 
LocalServer -  Initializing plants... 
LocalServer -  Starting RouteProbingPlugin... 
LocalServer -  Loading RouteProbing... 
LocalServer -  Starting WorldLayerManager... 
LocalServer -  Loading Layers... 
LocalServer -  Initializing world layers... 
LocalServer -  Loading ClimateSim... 
LocalServer -  Starting EconomyTracker... 
LocalServer -  Starting WorldObjectManager... 
LocalServer -  Loading WorldObjects... 
LocalServer -  Starting EconomyPlugin... 
LocalServer -  Loading Economy... 
LocalServer -  Starting RoomPlugin... 
LocalServer -  Loading Rooms... 
LocalServer -  Starting ObjectivePlugin... 
LocalServer -  Loading Objectives... 
LocalServer -  Starting Legislation... 
LocalServer -  Loading Laws... 
LocalServer -  Starting WebServerPlugin... 
LocalServer -  Starting HousingTierDefinition... 
LocalServer -  Initializing LocalizationPlugin... 
LocalServer -  Initializing WorldGeneratorPlugin... 
LocalServer -  Initializing UserManager... 
LocalServer -  Initializing MinimapManager... 
LocalServer -  Initializing WorldObjectManager... 
LocalServer -  Initializing EconomyPlugin... 
LocalServer -  Initializing RoomPlugin... 
LocalServer -  Initializing HousingTierDefinition... 
LocalServer -  Initializing WorldPlugin... 
LocalServer -  Ticking... 
LocalServer -  Compressing... 
LocalServer -  Saving world... 
LocalServer -  Initializing NetworkManager... 
LocalServer -  Initializing WorldLayerManager... 
LocalServer -  Initializing WebServerPlugin... 
LocalServer -  Server Initialization finished in 17,211.0ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[46:35] Connecting via Lidgren to localhost:3000
Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[47:13] Disconnected from server.</details>

**Comment by craig-jong** [comment]
If you could attach the save this is occurring on that would be helpful. I guess it's been 21 days so the chance of you having it is low, but if it comes up again, just throw the save at me and reopen this.
