### ISSUE TITLE
Contracts ui is really buggy

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#7823]
Testing on staging, but I think some of this has been this way for a long time.  I am not sure how it behaves on release.

The clause drop down does all kinds of weird things.  Sometimes selecting a different clause from the drop down will work fine.  Sometimes doing so will add or remove other clauses in the list, and/or set the value of other clauses' drop downs such that they no longer match the clause that is displayed.

All of the property 'Pick' buttons do nothing.

When I clicked on 'Post Job' with this contract, I got an exception in RPCManager saying 'Wrong number of args passed to method: set_Description.'
![image](https://user-images.githubusercontent.com/23460210/40258115-5a32fc3c-5aa5-11e8-9624-0d764ef63787.png)

**Comment by johnkslg** [comment]
Probably loan related.  Adding Eric if he can illuminate any issues from his changes.

**Comment by MarjieAVolk** [comment]
I don't think this is related to loans.  You can see the same issue with the clause drop downs in Nick's comment from Jan 9 here: https://github.com/StrangeLoopGames/EcoIssues/issues/3295

I had assumed there was another bug for that issue, but apparently not.

**Comment by SlayksWood** [comment]
Seems fixed with new UI
