### ISSUE TITLE
Add a README linking to the Issues page of this project

### ISSUE THREAD

**Issue by aawilson** [StrangeLoopGames/EcoIssues#7824]
It's pretty easy to visit the base page for the EcoIssues Github project and not realize that all of the actual content is tucked away under the "Issues" tab, since it prominently says that the repository is empty. A README with just a link to https://github.com/StrangeLoopGames/EcoIssues/issues would be trivial to add and would solve the issue completely.

**Comment by rainfarmer** [comment]
Great idea @aawilson

**Comment by elfl0rd** [comment]
Can you add more information to it? E.g. link to suggestion section :P
