### ISSUE TITLE
Suggestion: colored room label or box in front of it

### ISSUE THREAD

**Issue by BadHarry00** [StrangeLoopGames/EcoIssues#7825]
Colored marker for a better allocation in the pie chart

![2018-05-19 08_20_10-eco](https://user-images.githubusercontent.com/30983485/40265700-843f35e8-5b3d-11e8-844d-1a4a5a6c4dd9.png)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#44
