### ISSUE TITLE
Suggestion: Info about which Skillbook I already learned on the Researchtable

### ISSUE THREAD

**Issue by BadHarry00** [StrangeLoopGames/EcoIssues#7826]
Research Table: 
An information in the list of skill books, which I already learned. Maybe under the name of the skill book or in the tooltip.

**Comment by Deantwo** [comment]
FYI: Tooltip of the skill book says it is learned.

**Comment by BadHarry00** [comment]
This skill was learned:
![2018-05-27 19_41_55-eco746](https://user-images.githubusercontent.com/30983485/40588985-3208d176-61e6-11e8-81fb-29bd3927907b.png)

this wasn't learned:
![2018-05-27 19_35_47-eco746](https://user-images.githubusercontent.com/30983485/40588986-42bb6d4e-61e6-11e8-82e7-f1d92815e4e1.png)

I dont see the difference.

**Comment by Deantwo** [comment]
Oh, I guess I am thinking of the **Skill Scroll**'s tooltip.
So easiest solution would be to just copy that to the **Skill Book** too.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#43
