### ISSUE TITLE
Unable to load single player (offline) world

### ISSUE THREAD

**Issue by jaeger426** [StrangeLoopGames/EcoIssues#7827]
Good morgning everybody,
Last week i updated the game from version 7.3.X to 7.4.X and from this toime on i´m not able to load any singleplayer savegamge. I´m playing offline without any LAN or internet connection. So no router is involved....
So i tried to create a new offline singleplayer world but there ist no sucess....
I only get following error message:
Connection failed
Failed to establish connection - no response from remote host

When i start the game with an active internet connection then everything is working. I´m able to create new worlds and i´m able to load my created worlds. After the world is fully loaded then i can disconnect the internet and i´´m able to continue playing without any connection....
But i can only load new created world from Version 7.4.X. I´m not able to load old world´s before version 7.4.X.

So i do no know what to do?
Why is it not possible to create and load games without an active internet connection?
Why is it not possible to my old world?

I´m using Windows 10 and i reinstalled the game after i recognized the problem....
Below i have attached the game generated failure mesage during loading my worlds...
Have a godd day and a nice weekend :)

[Failure message.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2019302/Failure.message.txt)

**Comment by elfl0rd** [comment]
\Eco\Eco_Data\Server\Dump attach .ecodmp file please.

**Comment by jaeger426** [comment]
Good afternoon,
you will find the requestet files in the attachment.
Zhank you for your help

2018-05-19 15:13 GMT+02:00 elfl0rd <notifications@github.com>:

**Comment by elfl0rd** [comment]
You attached log.
not dump.

**Comment by jaeger426** [comment]
Sorry for that but there are no more Files in this Folder. What did i
wrong?


2018-05-19 17:06 GMT+02:00 elfl0rd <notifications@github.com>:

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/40270306-3257f052-5b93-11e8-9151-05bc279f3bf7.png)
Dump folder can not contain log files, and if your server crashed, they create dump.

**Comment by jaeger426** [comment]
Sorry but i'm a little Bit dumped....
What should i exactly send to you. The Files in my Folder See named like
your ones.
Bit o Ne question is Single Player (offline) the Dame like an Server?

elfl0rd <notifications@github.com> schrieb am Sa., 19. Mai 2018, 17:34:

**Comment by elfl0rd** [comment]
Singleplayer launch server for 1 user.

**Comment by Nicolausi113** [comment]
Maybe a hint and my assumption:
the game is licensed and copy protected via an active (online) SLG account.
If I start the client offline, the only I get is the login screen (v0.7.3.3).

**Comment by MarjieAVolk** [comment]
I believe right now the game connects to a local server the same way it would connect to a LAN server.  So I'm guessing you do need to have your internet on, even to play locally.

But if you do have any crashes in that folder ('[...]\steamapps\common\Eco\Eco_Data\Server\Dump'), like @elfl0rd said, it would be helpful to attach those.

**Comment by metachronism** [comment]
@jaeger426 do you have the game save file of this still and can attach or link to it?  It will be in your Server/Storage folder - please attach and reopen if so
