### ISSUE TITLE
Can't connect to server 7.4.5 steam updating issue

### ISSUE THREAD

**Issue by Leadenigma** [StrangeLoopGames/EcoIssues#7828]
After hosting a server (7.4.5) from steamcmd some users were reporting they couldn't connect or would be on the connecting screen indefinitely. They have switched to the 7.4.5 - staging build under betas in steam and can connect without problem. Myself and a few others have "None - Opt-out" selected and have no issues connecting.

I think that steam is not updating some clients properly. This has been going on since the 7.4.5 release on steam until they switched to the 7.4.5 beta staging branch.

**Comment by GophTheGreat** [comment]
You can force Steam to push queued game updates by fully closing Steam and relaunching it.
