### ISSUE TITLE
Random FPS drop/Disconnection for "inactivity" after game freezing

### ISSUE THREAD

**Issue by Retoma** [StrangeLoopGames/EcoIssues#7830]
Not sure if this is happening to anyone else, but on occasion I'd get a severe FPS drop, from like 40-50, down to 1 and this would last anywhere between 15 seconds up to a minute. Also there are other times where my game will freeze for anywhere between 5-15 seconds, and then I get a message either saying "Kicked for inactivity" or "inactivity". There have also been occasions where it freezes for a couple of seconds after I have either started a project, or started looking through my facility's inventory and I was randomly "kicked for inactivity" or "inactivity". This last bit has happened at least...oh 6 times now today (5/19/2018)? Attached is the latest "crash log" that I received from being disconnected for inactivity.
[Eco Bug 2.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2019957/Eco.Bug.2.txt)

Quick system specs:

Win 10 x64
Nvidia GeForce GTX 1050Ti - 4096MB Vram
24GB ram
AMD A10-5800k 4.09 GHz CPU

**Comment by metachronism** [comment]
Inactivity shouldnt be a kick reason anymore since 7.4.6+, closing this out in favor of the other duplicate bug about getting the 'disconnected' icon appearing
