### ISSUE TITLE
Game.eco uses incorrect Path separator on Windows

### ISSUE THREAD

**Issue by mettke** [StrangeLoopGames/EcoIssues#7831]
Hey Eco-Team,

I found a small bug with the Game.eco file which only appears when using Linux and Windows for Server. The Short Version is, that a zip file must contain Unix Slash for path separation and not the Windows Backslash. More info below:

I created my world under Linux, which results in a valid zip containing files like `History/Birch.gif`. Afterward, I switched to a Windows Server. That Server found all of the files ('cause Linux slash is supported under windows archive as it is the standard) and every non-existing file (like new players) was from now on created with a Backslash like `Users\76561198041461243_`.

As long as I stayed on the Windows Server everything worked fine. However, after switching back to the Linux Server, suddenly a lot of stuff and player were missing. It turns out that Linux does not accept files with a backslash to be in the same directory thus the game is not detecting them. 

I was able to correct the mistake by removing the History folder inside the zip (every file had a duplicated using the backslash) and then renaming files from backslash to slash. If there is someone experiencing the same issue, the following commands corrected the file for me. However, remember to backup you file as it may not suit your current server data.

```
7z l Game.eco | grep '\\' | cut -c 54-  > test
while read -r p; do 7z rn Game.eco "$p" "${p/\\//}" ; done < test
```

I suggest switching the Path Separator inside zips to slash to make the zip cross-platform compatible. I'm happy to send you my files if necessary.

**Comment by SeanAtr0n** [comment]
Fixed in 7.5
