### ISSUE TITLE
Suggestion: More optical contrast in the skill menu

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#7832]
The focused profession and the specialization is bad remarkable.
The white text on yellow background is hard readable ( at least for me).

![skillmenu](https://user-images.githubusercontent.com/38510829/40278424-202ee5a4-5c31-11e8-825f-ca13775c8003.PNG)

**Comment by Nicolausi113** [comment]
Yes, a green background would be fine for better readability!

And if You have an idea how could the focused profession and specialty made more obvious, eye-catching. I thought of more transparency for the not focused?

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/3379

**Comment by MarjieAVolk** [comment]
Fixed in 7.7 (not the next major release, but the one after)
