### ISSUE TITLE
[0.7.3.3 - 0.7.4.5] Small cart operable while typing.

### ISSUE THREAD

**Issue by DeathTech154** [StrangeLoopGames/EcoIssues#7833]
The small cart, not sure if others do it too but definitely the small cart lets you drive it backwards while typing. I've been observing this behaviour for a while now and thought I better report it.

Only really dangerous when using carts but still nothing more annoying than falling off a bridge with the cart because you decided to respond to people's questions.

Expected Behaviour:
Full motion stop when typing in chat.

Observed behaviour:
Pressing any movement keys let you move while in the process of typing.

**Comment by SeanAtr0n** [comment]
Fixed a while back
