### ISSUE TITLE
Fody code triggering updates during migration, prevents loading game

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7835]
When loading this usersave:
https://drive.google.com/drive/folders/1gFTlcg4r2UbREXw5Gb2x0MJbY3s_0CE_?usp=sharing

The game triggers a changed call off a 'set' call, which I assume is happening due to Fody.  Breaks migration.

Callstsack:
 	Eco.Core!Eco.Core.Serialization.ISerializationUtil.Save(Eco.Core.Serialization.IStorage storage) Line 15	C#
>	Eco.Gameplay!Eco.Gameplay.Economy.Contracts.ContractClause.Changed(object clauseObject, System.ComponentModel.PropertyChangedEventArgs args) Line 39	C#
 	[External Code]	
 	Eco.Gameplay!Eco.Gameplay.Economy.Contracts.ContractClauseBuildRoad.SelectedItem.set(Eco.Gameplay.Items.SearchAndSelect.SearchAndSelectItem value) Line 186	C#
 	Eco.Gameplay!Eco.Gameplay.Economy.Contracts.ContractClauseBuildRoad.ContractClauseBuildRoad() Line 194	C#
 	[External Code]	
 	Eco.Core!Eco.Core.Serialization.Serializers.ClassSerializer<Eco.Gameplay.Economy.Contracts.ContractClauseBuildRoad>..ctor.AnonymousMethod__1() Line 174	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ClassSerializer<Eco.Gameplay.Economy.Contracts.ContractClauseBuildRoad>.NewInstance.get() Line 162	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(System.IO.BinaryReader reader) Line 95	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.EnumerableSerializer<Eco.Core.Controller.RPCList<Eco.Gameplay.Economy.Contracts.ContractClause>, Eco.Gameplay.Economy.Contracts.ContractClause>.Decode(System.IO.BinaryReader reader, object instance) Line 76	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ClassSerializer<Eco.Gameplay.Economy.Contracts.Contract>.DecodeMember(Eco.Core.Serialization.Serializers.MemberInfo member, ref object instance, System.IO.BinaryReader reader) Line 255	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ClassMigrationSerializer<Eco.Gameplay.Economy.Contracts.Contract>.DecodeToInstance(ref object instance, System.IO.BinaryReader reader) Line 513	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(System.IO.BinaryReader reader) Line 96	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.DictionarySerializer<Eco.Core.Utils.ThreadSafeDictionary<System.Guid, Eco.Gameplay.Economy.Contracts.Contract>, System.Guid, Eco.Gameplay.Economy.Contracts.Contract>.Decode(System.IO.BinaryReader reader) Line 68	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ClassSerializer<Eco.Gameplay.Economy.Contracts.ContractManager>.DecodeMember(Eco.Core.Serialization.Serializers.MemberInfo member, ref object instance, System.IO.BinaryReader reader) Line 258	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ClassMigrationSerializer<Eco.Gameplay.Economy.Contracts.ContractManager>.DecodeToInstance(ref object instance, System.IO.BinaryReader reader) Line 513	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(System.IO.BinaryReader reader) Line 96	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ClassSerializer<Eco.Gameplay.Economy.EconomyManager>.DecodeMember(Eco.Core.Serialization.Serializers.MemberInfo member, ref object instance, System.IO.BinaryReader reader) Line 258	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ClassMigrationSerializer<Eco.Gameplay.Economy.EconomyManager>.DecodeToInstance(ref object instance, System.IO.BinaryReader reader) Line 513	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(System.IO.BinaryReader reader) Line 96	C#
 	Eco.Core!Eco.Core.Serialization.SimpleSerializer.Deserialize(System.IO.Stream stream) Line 444	C#
 	Eco.Core!Eco.Core.Serialization.CurrentSerializer.Deserialize(System.IO.Stream stream) Line 45	C#
 	Eco.Core!Eco.Core.Serialization.EcoSerializer.Deserialize(System.IO.Stream stream) Line 65	C#
 	Eco.Core!Eco.Core.Serialization.DataStore.Load<Eco.Gameplay.Economy.EconomyManager>(string folder, System.Action<Eco.Gameplay.Economy.EconomyManager, Eco.Core.Serialization.IPersistent> createFunc) Line 347	C#
 	Eco.Core!Eco.Core.Plugins.StorageManager.CreateOrLoad<Eco.Gameplay.Economy.EconomyManager>(string folder, System.Action<Eco.Gameplay.Economy.EconomyManager> onCreate) Line 110	C#
 	Eco.Core!Eco.Core.Plugins.SimplePlugin<Eco.Gameplay.Economy.EconomyManager>.DoLoad(string name) Line 39	C#
 	Eco.Core!Eco.Core.Plugins.SimplePlugin<Eco.Gameplay.Economy.EconomyManager>.SimplePlugin(string name) Line 32	C#
 	Eco.Gameplay!Eco.Gameplay.Economy.EconomyPlugin.EconomyPlugin() Line 24	C#
 	[External Code]	
 	EcoServer.exe!Eco.Server.PluginManager.AddPlugin(System.Type pluginType, object[] p) Line 199	C#
 	EcoServer.exe!Eco.Server.PluginManager.AddPlugin<Eco.Gameplay.Economy.EconomyPlugin>(object[] p) Line 195	C#
 	EcoServer.exe!Eco.Server.PluginManager..ctor.AnonymousMethod__10_2() Line 131	C#
 	[External Code]

**Comment by metachronism** [comment]
Fixed this with smarter changed callback
