### ISSUE TITLE
server takes 5+ min to load in Browse Tab

### ISSUE THREAD

**Issue by EnjoiTanner** [StrangeLoopGames/EcoIssues#7836]
even while having 7+ players online we do not show up or load really late so its hard for players to find us. even while searching by name most players can not find server.       Server name: Enjoimyeco2  Server IP: 12.34.56.789:3000

**Comment by MarjieAVolk** [comment]
Should be greatly improved in the next release.  We were loading 1 server per frame, now we will load 5 per frame, so your server should appear 5x faster.  There's kind of a trade off between loading more servers quickly and trying not to overload people's machine and/or router.  I'm hoping this will strike a better balance, but we might tweak it again in the future.
