### ISSUE TITLE
Brick texture bug 7.4.5.

### ISSUE THREAD

**Issue by Serynthara** [StrangeLoopGames/EcoIssues#7837]
Well, I tried to place the bricks, but all brick constructions that aren't exactly filling the 1x1x1 are causing the texture bug seen below.

![20180521044643_1](https://user-images.githubusercontent.com/34604183/40290591-27c3c29c-5cbf-11e8-9635-a60759baf45f.jpg)

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/4286
