### ISSUE TITLE
World layers not showing in minimap

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#784]

**Comment by johnkslg** [comment]
Pollution doesnt show and many others. Some do show.

**Comment by metachronism** [comment]
there is an error reported regarding this, something about needing voxels per entry

**Comment by stett** [comment]
I believe this has to do with last update sent time... worldlayer updates are heavy and sent at lower frequency intervals than other stuff, so using the standard player.LastSentUpdateTime to decide whether or not to send a layer's data doesn't work on anything except layer types like Diffuse, which are updating every step anyway
