### ISSUE TITLE
Problems while diggin

### ISSUE THREAD

**Issue by Ivonator** [StrangeLoopGames/EcoIssues#7840]
When I dig, the game crashes pretty fast.
I can do anything else: walk, run, jump, ride, climb, swim, dive, mine resources, anything that I think needs more computing power, but when I dig (sometimes just only 2 or 3 shovels), the game freezes and gets out completely.

I startet with version 7.2.5, this problem occured rarely
Now I use 7.4.5., my world is well equipped, and now when I dig, the game crashes really quick.
1. Screen freezes
2. Black screen
3. White screen, after pushing Windows butto following screen and I have to quit Eco:
![crash](https://user-images.githubusercontent.com/39534015/40385934-8d1be206-5e08-11e8-8332-11b411245477.png)

It doesnt care, if I startet the Computer the first time this day or if I did a lot of things before starting Eco.

**Comment by metachronism** [comment]
Do you happen to have any logs from the server/dump folder?

**Comment by Ivonator** [comment]
Sent to E-Mail

**Comment by Ivonator** [comment]
After two weeks of vacation I started the game via Steam (version 7.4.7) and it works fine.

I will report, when the problem appears again.
