### ISSUE TITLE
Combustion Generator Continuously Produces Pollution

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7841]
Once the combustion generator has been fueled and started for the first time, even when it's out of fuel, if 'left on' it continuously generates pollution.  Once out of fuel it produces no power but produces pollution even days after running out of fuel and not being re-fueled.  The only way to stop the pollution is to make sure the generator is switched to 'off'.  This causes issues when a generator is left running and the player assumes it will stop when the fuel runs out and will not be polluting at that time.  However, since they leave it set to on it continues polluting at the same level although its technically not running as it is out of fuel and not producing any power.

**Comment by SeanAtr0n** [comment]
fixed in 7.4.6
