### ISSUE TITLE
Serializer crash on OccupancyInitItem

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7843]
The serializer was trying to serialize OccupancyInitItem, as an instance, event though that class is not [Serialized].

This happened after adding a few thousand store entries with /spawneconomy

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Eco.Core
  StackTrace:
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.EncodeMembers(BinaryWriter writer, Object instance) in C:\Eco\Server\Eco.Core\Serialization\Serializers\ClassSerializer.cs:line 277

>	Eco.Core!Eco.Core.Serialization.Serializers.ClassSerializer<Eco.Mods.OccupancyInitItem>.EncodeMembers(System.IO.BinaryWriter writer, object instance) Line 277	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(System.IO.BinaryWriter writer, object instance) Line 72	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ClassSerializer<Eco.Gameplay.Items.ItemStack>.EncodeMembers(System.IO.BinaryWriter writer, object instance) Line 278	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(System.IO.BinaryWriter writer, object instance) Line 72	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ClassSerializer<Eco.Gameplay.Items.SearchAndSelect.SearchAndSelectItem>.EncodeMembers(System.IO.BinaryWriter writer, object instance) Line 278	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(System.IO.BinaryWriter writer, object instance) Line 72	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ClassSerializer<Eco.Gameplay.Components.TradeOffer>.EncodeMembers(System.IO.BinaryWriter writer, object instance) Line 278	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(System.IO.BinaryWriter writer, object instance) Line 72	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.EnumerableSerializer<Eco.Core.Controller.RPCList<Eco.Gameplay.Components.TradeOffer>, Eco.Gameplay.Components.TradeOffer>.Encode(System.IO.BinaryWriter writer, object instance) Line 48	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ClassSerializer<Eco.Gameplay.Components.StoreComponent>.EncodeMembers(System.IO.BinaryWriter writer, object instance) Line 278	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(System.IO.BinaryWriter writer, object instance) Line 72	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.EnumerableSerializer<Eco.Core.Utils.ThreadSafeList<Eco.Gameplay.Objects.WorldObjectComponent>, Eco.Gameplay.Objects.WorldObjectComponent>.Encode(System.IO.BinaryWriter writer, object instance) Line 48	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ClassSerializer<Eco.Mods.TechTree.StoreObject>.EncodeMembers(System.IO.BinaryWriter writer, object instance) Line 278	C#
 	Eco.Core!Eco.Core.Serialization.Serializers.ObjectSerializer.Encode(System.IO.BinaryWriter writer, object instance) Line 72	C#
 	Eco.Core!Eco.Core.Serialization.SimpleSerializer.Serialize(object obj) Line 435	C#
 	Eco.Core!Eco.Core.Serialization.CurrentSerializer.Serialize(object obj) Line 43	C#
 	Eco.Core!Eco.Core.Serialization.EcoSerializer.Serialize(object obj) Line 62	C#
 	Eco.Core!Eco.Core.Serialization.ZipBlob.Persist(object obj) Line 58	C#
 	Eco.Core!Eco.Core.Serialization.ISerializationUtil.Save(Eco.Core.Serialization.IStorage storage) Line 15	C#
 	Eco.Gameplay!Eco.Gameplay.Objects.WorldObject.SaveIfDirty() Line 83	C#
 	Eco.Gameplay!Eco.Gameplay.Objects.WorldObjectManager.SaveSome() Line 331	C#
 	Eco.Core!Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(System.Action func) Line 28	C#
 	Eco.Gameplay!Eco.Gameplay.Objects.WorldObjectManager.Run() Line 300	C#
 	EcoServer.exe!Eco.Server.PluginManager.StartPlugins.AnonymousMethod__0(object x) Line 229	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 891	C#
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart(object obj) Line 93	C#

**Comment by metachronism** [comment]
things should not be instancing this item type - real issue was a chat command adding these items to an inventory somewhere
