### ISSUE TITLE
[NETWORK] hostname - SRV Record

### ISSUE THREAD

**Issue by Hagigamer** [StrangeLoopGames/EcoIssues#7844]
Hi guys, 

I have a server behind two firewalls, which is usually referred to via domain name. 
So before the change to udp, everyone was able to connect to "sub.domain.de:3000" - with the change to udp this does not work anymore. the webinterface on 3001 is still fine. 
Connecting to the game server is still possible when directly connecting to the IPv4 of my external facing firewall, which then redirects to the internal firewall which redirects to the server - so basically a classic DMZ. 

Would the implementation of SRV Record support like teamspeak resolve this issue? I believe I am not the only server hosting guy who has this problem. 

This is an explanation how one sets up the SRV Record for teamspeak - might want to add something similar for eco. 
https://www.namecheap.com/support/knowledgebase/article.aspx/9766/2208/how-can-i-link-a-domain-name-to-teamspeak-3

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#42
