### ISSUE TITLE
empty red bar

### ISSUE THREAD

**Issue by Kryt3r** [StrangeLoopGames/EcoIssues#7846]
Serverversion: **0.7.4.5 beta**

i have some troubles with the webinterface by the host **gamed.de**:

first:
i can't login on the webinterface directly, only if i click ingame on the "Run for Office" or "Propose Law" Button in the quick menue "L", i will be logged in. if i want to log in directly, it shows me the login form and after i clicked "Enter", nothing happens and it shows me only this one:

![grafik](https://user-images.githubusercontent.com/18367691/40433302-fe1de0a0-5eab-11e8-8fcd-f60f2edfb5fd.png)

secondly:
i can't do anything, after i'm logged in.
every time i want to change something or want to start the vote for a leader, it shows me a red bar without any error message like this:

![grafik](http://ecoforum.strangeloopgames.com/uploads/files/1526939061737-grafik.png)

thirdly:
if i'm logged in and want to click on the webinterface on "Propose a New Law", i see the red bar, too:

![grafik](https://user-images.githubusercontent.com/18367691/40434061-d1eceb78-5ead-11e8-8160-147da4d775db.png)

i don't know, what is wrong and the support from the host tells me, i need to contact you. 
Unfortunately, I can't find any logs on the FTP server that could help. :/

**Comment by rainfarmer** [comment]
@Kryt3r is this still happening for you? 
I'm not able to recreate on newest version of Eco
