### ISSUE TITLE
Freeze of the game

### ISSUE THREAD

**Issue by Dampfhamma** [StrangeLoopGames/EcoIssues#7847]
in 30 minutes the game freezes 3-4 times for several seconds.
We are playing on a better Nitrado server.

my system:

WIN 10
INTEL I5 (6600K) on ASUS  Z 170-P
16 GB
NVIDIA 1060 / 6 GB
Kingston SUV 400S37480G    2x

all updated and running always very fast

Volker

**Comment by Dampfhamma** [comment]
after last update, yesterday, there are no freezes but now there are only lags in same time.

**Comment by metachronism** [comment]
closing this out - need more reproduceable steps for this, otherwise its just a generic performance issue which we are always looking at
