### ISSUE TITLE
Windows Storage (.db/.eco) not compatible with Linux Server

### ISSUE THREAD

**Issue by willcormier** [StrangeLoopGames/EcoIssues#7850]
When transferring the .db and .eco files from a Client Server to a Standalone server and renaming it to Game.eco and Game.db appears to work fine.

But transferring the Game.eco and Game.db from a Windows machine to a linux server, it does not seem to pick up the world file that's already there and will regenerate the terrain from scratch.

There are no errors in the logs from what I can see.

**Comment by SeanAtr0n** [comment]
will be fixed in 7.5 with https://github.com/StrangeLoopGames/Eco/pull/2958
