### ISSUE TITLE
USER ISSUE: Invalid username or password.

### ISSUE THREAD

**Issue by DopeEx** [StrangeLoopGames/EcoIssues#7851]
**Version:** 0.7.4.5 beta

**Steps to Reproduce:**
Download the Game from SLG homepage and try to Login (I buy the game on Steam and link the Account)

**Expected behavior:**
Invalid username or password.

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 (ID=0x1b80)
    Vendor:   NVIDIA
    VRAM:     8079 MB
    Driver:   24.21.13.9764
Begin MonoManager ReloadAssembly
- Completed reload, in  0.061 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.128517 ms
Setting up 8 worker threads for Enlighten.
  Thread -> id: 3974 -> priority: 1 
  Thread -> id: 2994 -> priority: 1 
  Thread -> id: 2ec8 -> priority: 1 
  Thread -> id: 1b08 -> priority: 1 
  Thread -> id: 38b8 -> priority: 1 
  Thread -> id: 106c -> priority: 1 
  Thread -> id: 3678 -> priority: 1 
  Thread -> id: 3220 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.5 beta
Mittwoch, 16. Mai 2018 02:29
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> PreLogin
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggingIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fallback handler could not load library C:/Users/schro/Desktop/EcoPC_v0.7.4.5-beta/Eco_Data/Mono/libc
Fallback handler could not load library C:/Users/schro/Desktop/EcoPC_v0.7.4.5-beta/Eco_Data/Mono/libc.dll
Fallback handler could not load library C:/Users/schro/Desktop/EcoPC_v0.7.4.5-beta/Eco_Data/Mono/libc
Changing state: LoggingIn -> PreLogin
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Actual behavior:**
The following error message popped up:
```
Invalid username or password.
```

<details>
<summary>Log File</summary>Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 (ID=0x1b80)
    Vendor:   NVIDIA
    VRAM:     8079 MB
    Driver:   24.21.13.9764
Begin MonoManager ReloadAssembly
- Completed reload, in  0.061 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.128517 ms
Setting up 8 worker threads for Enlighten.
  Thread -> id: 3974 -> priority: 1 
  Thread -> id: 2994 -> priority: 1 
  Thread -> id: 2ec8 -> priority: 1 
  Thread -> id: 1b08 -> priority: 1 
  Thread -> id: 38b8 -> priority: 1 
  Thread -> id: 106c -> priority: 1 
  Thread -> id: 3678 -> priority: 1 
  Thread -> id: 3220 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.5 beta
Mittwoch, 16. Mai 2018 02:29
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> PreLogin
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggingIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fallback handler could not load library C:/Users/schro/Desktop/EcoPC_v0.7.4.5-beta/Eco_Data/Mono/libc
Fallback handler could not load library C:/Users/schro/Desktop/EcoPC_v0.7.4.5-beta/Eco_Data/Mono/libc.dll
Fallback handler could not load library C:/Users/schro/Desktop/EcoPC_v0.7.4.5-beta/Eco_Data/Mono/libc
Changing state: LoggingIn -> PreLogin
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

</details>

**Comment by rainfarmer** [comment]
@DopeEx do you have special characters in your password or username?
Try changing your password with the Edit link on the account page, to something simple for testing.
