### ISSUE TITLE
Joining server screen [spinning cogwheel] requires a "Downloading Modded Models" message 

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#7852]
Hello again!

**Issue:**
When joining a server with many mods and a clean appdata /Mods folder, it can take a very long time to join a server depending on host upload and player download speed. Game does not let the player know whether it's download mods/models, connecting or 'hanged up'.

**Scenario:**
My Modpack is sized about 120mb, with probably 110mb of those being Unity files that are downloaded to clients, so some folks reported 45 seconds, up to 5 minutes looking at the spinning cogwheel. A player gave up connecting as he thought it was Eco issues, spinning cogwheel for 15+ minutes. 
I sent him the appdata /Mods for my server via Google Drive and he connected instantly.

Infinite Cogwhel:
![cogwheel](https://user-images.githubusercontent.com/26847645/40448727-bf57da14-5eac-11e8-8f14-93221e3b8fda.png)

AppData Mod folder. Took me ~5 minutes of cogwheel to log in the server:
![mods](https://user-images.githubusercontent.com/26847645/40448721-bcfd5cb2-5eac-11e8-8d41-96a6142d813c.png)

**Steps to reproduce:**
With a clean appdata /Mods folder, connect to a server running multiple mods. 
Here's my main public server ip if required: 4.31.168.78:28205 - running the 120mb modpack.

Thanks!

**Comment by elfl0rd** [comment]
huh, i found this for linking ) https://github.com/StrangeLoopGames/EcoSuggestions/issues/341

**Comment by redwyre** [comment]
Long since fixed
