### ISSUE TITLE
map doesn't follow player while driving/flying

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#7853]

**Comment by elfl0rd** [comment]
and flying (/fly)

**Comment by elfl0rd** [comment]
heh, my issue is dupe :) closing it - https://github.com/StrangeLoopGames/EcoIssues/issues/8620

**Comment by SlayksWood** [comment]
> To add onto this, if you click another player's coordinates it will start to follow that player instead.
