### ISSUE TITLE
Solid wooden door

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#7860]
Version: 0.7.4.5 beta

Steps to Reproduce:
Just look at the current list of doors

Expected behavior:

That there would be a door with no window 

Actual behavior:

It is kind of creepy to have a bathroom door with a Window in it so anyone
can look into it.  :) 

Can you please make just a solid door with no window in it please? 

I am sure that other players are looking for this too. so far all the doors
which I have seen all have some kind of window in it. 

Can you just make a solid door with no window or anything in it please?

**Comment by elfl0rd** [comment]
Hmmm...
Already on bleeding staging.
Multiple times announced, screenshoted, etc.
Only TWO doors have window.
Other THREE doors - solid.
![20180524172603_1](https://user-images.githubusercontent.com/4980243/40491792-a9fc3dd8-5f77-11e8-853e-750a819c4f96.jpg)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#403

**Comment by thereporter42** [comment]
Not everyone is running bleeding edge nor did I see any announcements about it. Stop being such a jerk  elfl0rd  you are just trolling.
