### ISSUE TITLE
Suggestions       |     Excavator eazy digging     |

### ISSUE THREAD

**Issue by JACKKRACK** [StrangeLoopGames/EcoIssues#7863]
I feel like the excavator is painful to use at this state of game. 
I have a suggestion for an eazy digging mode;       When you are sitting the excavator you get this laser pointer on what block you about to dig/mine. A laser that looks alot like the arrow projectile path. This way you can just look around and eazy mine what block you want. I don't want to remove the original way but just to have an option. ;)

**Comment by elfl0rd** [comment]
Already suggested :) 
https://github.com/StrangeLoopGames/EcoSuggestions/issues/29

**Comment by JACKKRACK** [comment]
Nice!    just what i had in mind! ;)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#401
