### ISSUE TITLE
7.4.6 OutOfMemoryException with big save games (~ 2 GB)

### ISSUE THREAD

**Issue by Rick86** [StrangeLoopGames/EcoIssues#7866]
Hey ECO-Guys,
it seems the C# Zip Library can not handle big save games (12 km² world), which is in our case nearly 2 GB. We get this exception on every save and the server crashes:

--BEGIN DUMP--
Dump Time
05/24/2018 15:57:07

Exception
Exception: OutOfMemoryException
Message:Exception of type 'System.OutOfMemoryException' was thrown.
Source:mscorlib

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader()
   at System.IO.Compression.ZipArchive.WriteFile()
   at System.IO.Compression.ZipArchive.Dispose(Boolean disposing)
   at Eco.Core.Serialization.DataStore.SaveAs(String filename)
   at Eco.Core.Serialization.DataStore.ProcessQueue()
   at Eco.Core.Serialization.DataStore.<Run>b__31_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

--END DUMP--

In 7.4.6 its "the data stream is to long":

[17:38] Server Initialization finished in 126.236,2ms
[19:30] Failed to save: Der Datenstrom war zu lang.

Unbehandelte Ausnahme: System.ObjectDisposedException: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "System.IO.Compression.ZipArchive".
   bei System.IO.Compression.ZipArchive.ThrowIfDisposed()
   bei System.IO.Compression.ZipArchiveEntry.Open()
   bei Eco.Core.Serialization.DataStore.ProcessQueue()
   bei Eco.Core.Serialization.DataStore.<Run>b__31_0()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()

.NET Frame says "End of Central Directory record could not be found"

HDD has 100+ GB free space and ram is 18 GB, the server takes 17 gb sometime on startup now, which is much more than before. Before 7.4.x the server took 7 gb the most time, but at this time. the save game was around 1,8 GB

The .eco file is 2 gb, the stats are disabled for some weeks.

**Comment by Rick86** [comment]
ah sorry forget this:
HDD has 100+ GB free space and ram is 18 GB, the server takes 17 gb sometime on startup now, which is much more than before. Before 7.4.x the server took 7 gb the most time, but at this time. the save game was around 1,8 GB

**Comment by Rick86** [comment]
The .eco file is 2 gb, the stats are disabled for some weeks.

**Comment by Rick86** [comment]
updated comment. If you can give me an mail adress of you / ECO, I can grant you access to the 2 GB Storage File (via GoogleDrive)

**Comment by Rick86** [comment]
This is strange: When the server is starting, it uses up to 12 GB RAM.
After starting is finished, it uses 9 GB of RAM, over time (like 20 seconds) it grows smoothly to 14 GB of RAM (sometimes just 12 GB), then it suddenly drops to 9 GB again... and the same starts again... This is in idle (no saves at this time and no users on server).
At this time the server has 20 GB RAM (so I raised it now from 18 to 20), 2 GB is used by system & co, so the eco server can use 18 GB RAM of all...
If I save, the RAM is still growing, then drops to 7-8 GB and then it crashes

I tested this with an older savegame (its 4 days older and has 1,6 GB // wonder how it grows so much in a few days, we are only 5-6 active players):
After starting it uses 8 GB of RAM without growing and dropping, also the save is working (it takes just 8 seconds instead of 30+ seconds with crash).

What can I do?

**Comment by Rick86** [comment]
Okay seems like my first thought was right... I now tested this:
I copied 7.4.6 Game.eco (1.99 GB) to 7.3.3 and let the server convert the save game (I know this is no "clean" way, but this is just for testing).
7.3.3 can save all the time (everything is fine). The Game.eco is now 2.03 GB).

If I restart the server, it says:
```
[32:03] Starting EcoObjectManager... Finished in 847,1ms
[32:03] Loading Objects... Finished in 824,2ms

Unbehandelte Ausnahme: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Exception: Error(s) occurred when loading Objects
   bei Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   bei Eco.Gameplay.Objects.EcoObjectManager..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager.<.ctor>b__10_1()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Eco.Server.PluginManager..ctor()
   bei Eco.Server.Startup.Start(String[] args)
   bei Eco.Server.MainClass.Main(String[] args)
```

If I copy the (converted) save game now from 7.3.3 to 7.4.6 it says:
```
[27:12] Starting StorageManager... Finished in 5.898,6ms
[27:18] Couldn't open save 'Game'.
Exception: IOException
Message:Der Datenstrom war zu lang.
Source:mscorlib

System.IO.IOException: Der Datenstrom war zu lang.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at Eco.Core.Serialization.DataStore.OpenZipFile()
   at Eco.Core.Plugins.StorageManager..ctor()

Unbehandelte Ausnahme: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.ArgumentException: Der Delegat einer Instanzenmethode kann kein "this" von NULL haben.
   bei System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   bei Eco.Core.Plugins.StorageManager..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Eco.Server.PluginManager..ctor()
   bei Eco.Server.Startup.Start(String[] args)
   bei Eco.Server.MainClass.Main(String[] args)
```

So it seems there IS a 2 GB ZIP Library problem...

**Comment by metachronism** [comment]
This is likely still valid, but 12km worlds take so long to generate :/
