### ISSUE TITLE
Windows Defender Detects EcoServer.exe as Trojan

### ISSUE THREAD

**Issue by asniper** [StrangeLoopGames/EcoIssues#7868]
Trojan: Win32/Cloxer.D!cl 
Level: Severe
Date: 5/24/2018 
Category: Trojan
Description: This program is dangerous and executes commands from an attacker.
Recommended action: Remove this software immediately.
File: C:\Users\Administrator\Desktop\EcoServer_v0.7.4.6-beta\EcoServer.exe

this is a freshly extracted zip downloaded from https://s3-us-west-2.amazonaws.com/eco-releases/EcoServer_v0.7.4.6-beta.zip

Note: this is Windows Defender on Windows Server 2016 Standard 64 bit
Antimalware Client Version: 4.14.17639.18041
Engine Version: 1.1.14800.3
Antivirus definition: 1.267.1906.0
Antispyware definition: 1.267.1906.0
Network Inspection System Engine Version: 1.1.14800.3
Network Inspection System Definition Version: 1.267.1906.0

**Comment by Last2Night** [comment]
Can confirm that. If you extract by ignoring and try to start the server, it wont start saying something related to Server directory not found.

**Comment by asniper** [comment]
**Update:**
updating definitions seems to make it so that it doesn't detect it anymore but I am not sure if this was also because I tried to whitelist the file, which still will not execute.

Antimalware Client Version: 4.14.17639.18041
Engine Version: 1.1.14901.4
Antivirus definition: 1.269.58.0
Antispyware definition: 1.269.58.0
Network Inspection System Engine Version: 1.1.14901.4
Network Inspection System Definition Version: 1.269.58.0

**Comment by BlazeGuy2** [comment]
It looks to me like Windows Defender is detecting a false positive.  I just spun up an ec2 instance of Windows Server 2016 and found no issue, currently using a newer version of Windows defender.  I'm assuming that updating your version should fix the issue.

![windows_version](https://user-images.githubusercontent.com/35509188/41247619-5a5c92d8-6d63-11e8-9c8c-dd40f9a49d3e.PNG)

**Comment by effolkronium** [comment]
Have no issues with 
![image](https://user-images.githubusercontent.com/15274763/50220588-6886f500-039b-11e9-9da5-7f28defaa33e.png)
