### ISSUE TITLE
USER ISSUE: Crash while trying to continue the game

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#7869]
**Version:** 0.7.4.6 beta

**Steps to Reproduce:**
1. Make the textures not being able to load somehow (it should not load new ones)
2. Click Esc and exit to the main menu
3. Click continue
4. Profit! (aka bluescreen, aka error msg)

**Expected behavior:**
It should.. uh.. load itself?

**Actual behavior:**
The following error message popped up:
```Connection error
failed to establish connection - no responce from the remote host
<size=150%>Ошибка подключения</size>

Failed to establish connection - no response from remote host
```

<details>
<summary>Log File</summary>(...previous log truncated...)

rUI.Update () [0x00000] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at UI.WorkOrderUI.Update () [0x00000] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at UI.WorkOrderUI.Update () [0x00000] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at UI.WorkOrderUI.Update () [0x00000] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at UI.WorkOrderUI.Update () [0x00000] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d

**Comment by HetNeSS** [comment]
It may somehow affect the attemp to load the wooden logs into a small wooden cart without a permissiong thingy being held in the inventory. They do stack there, yes. But you can't grab the handles since then.
https://youtu.be/eydipaA2hZQ

**Comment by MarjieAVolk** [comment]
So I notice you have some Russian in your error message there; and I know Russian players have been experiencing difficulties because of our master server being blocked by the Russian government.  I'm not sure if this is related to your issue.

I also see in the tail end of your log there, you have a whole bunch of errors, but it looks like they are spinning off from some earlier error, like you suggested, and the earlier part of the log isn't there.  Would you be able to attach the full log?  On a Windows machine in English, it is located at 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'  ('Users' might be translated into your language)

**Comment by HetNeSS** [comment]
Uh.. Sure.
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2060382/output_log.txt)

**Comment by MarjieAVolk** [comment]
Thanks.  Yeah since I didn't catch you right away, this won't be the same log unfortunately :(  This does look like it has some interesting errors in it though.

**Comment by HetNeSS** [comment]
Will save it raw next time something happens. Sorry

**Comment by MarjieAVolk** [comment]
Okay so there's 2 main errors that I see in there:

```
InvalidOperationException: Sequence contains no matching element
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00011] in <389a581424f249b6bfedc5bb6d85fb6d>:0 
  at UI.WorldObjectUI.UpdateHideablePanels () [0x0005a] in <a14c2a2baa3940d0969f235d02df648a>:0 
  at UI.WorldObjectUI.OnEnable () [0x00006] in <a14c2a2baa3940d0969f235d02df648a>:0 
UnityEngine.GameObject:SetActive(GameObject, Boolean)
UI.UIManager:TryShow(String)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Toggle(String, BSONObject, UILayer)
GenericClient`1:ToggleUI(String, BSONObject)
[...]
```

```
InvalidOperationException: Queue empty.
  at System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) [0x0000b] in <a3bc56cd038446b2ba8027b187001bf8>:0 
  at System.Collections.Generic.Queue`1[T].Dequeue () [0x00008] in <a3bc56cd038446b2ba8027b187001bf8>:0 
  at Assets.UI.Scripts.ChatUI.Update () [0x00064] in <a14c2a2baa3940d0969f235d02df648a>:0 
```

**Comment by MarjieAVolk** [comment]
The first one is happening when you are trying to open a window for an object.  Do you know which object it might be?  Did you see any weird behavior for a certain object's window?

The second obviously has to do with chat, but not sure how it might happen.

**Comment by HetNeSS** [comment]
Hm. I've noticed the workbench window loading up a bit longer than all others do, but I don't touch it too often. Also, last time played it had been on a server which did had some custom mods in it. Can't remember much of an extraordinary behaviour though.

**Comment by MarjieAVolk** [comment]
Ah, it might be a mod object.  Okay well I can probably prevent those errors anyways, maybe no one will notice, but I will know :P

**Comment by MarjieAVolk** [comment]
Okay, I'm going to address the other little issues I saw there.  And I'm going to close this as no repro for now.  But if you have trouble again, I will open this back up.
