### ISSUE TITLE
USER ISSUE: It's impossible to grab the fish trap placed underwater

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#7871]
**Version:** 0.7.4.6 beta

**Steps to Reproduce:**
1. make the fish trap
2. place it underwater
3. Profit! (no)

**Expected behavior:**
It should be grabbable every time, all the time yea

**Actual behavior:**
Instead it.. being stuck underwater

<details>
<summary>Log File</summary>(...previous log truncated...)

rUI.Update () [0x00000] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at UI.WorkOrderUI.Update () [0x00000] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at UI.WorkOrderUI.Update () [0x00000] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at UI.WorkOrderUI.Update () [0x00000] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at UI.WorkOrderUI.Update () [0x00000] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at UI.WorkOrderUI.Update () [0x00000] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at UI.WorkOrderUI.U

**Comment by Dampfhamma** [comment]
in my trap there are over 30 fishes! place the trap deeper or something more away from the beach.

**Comment by elfl0rd** [comment]
Yes, try to place in open sea.

**Comment by HetNeSS** [comment]
It might be just because i've waited not long enough. No guarantees though

**Comment by beastyn** [comment]
Could't recreate in 0.8.1.3 Close for now.
