### ISSUE TITLE
Skillpoints gaining speed may set up it's nominal to zero by resuming the SP game

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#7873]
It's possible for the nominal skillpoint gain cap being reset to 0. I've had like 750 skill points a day one play session, and the other time i've joined by (the same savestate in both cases, singleplayer), my new skillpoint gaining rate was like 36, and did never raised above 40. If did stayed on 30+ mark all the time, even if you're hungry to the point you can't work anymore, it keeps up on 30+, then when you'll eat something it will send up a message like "you've eaten and 've gained like 30 points", and when you look back on that counter, it still will be a bit over 30. An easy way to stop your SP progression just based on that.

**Comment by craig-jong** [comment]
It sounds like you're saying your skillpoints are getting softcapped?

Can you post a screenshot of your nutrition wheel/housing wheel? Or perhaps post a gamesave and the username of the offending character?

**Comment by HetNeSS** [comment]
Not..really softcapped. They're just became to earn up very, very slowly. For the times when at the start of the singleplayer game they did arrive like 300 a real-time hour, where i've had capability to research basically everything that did came out of my research table to the expert level in time where the other research book will come out, eventually it dropped down to 15-20, to the point where i've had to use cheats just to push forward the research.
![20180608101823_1](https://user-images.githubusercontent.com/18286472/41140596-d462cc5e-6b07-11e8-81c8-64c5dfd99999.jpg)
![20180608101828_1](https://user-images.githubusercontent.com/18286472/41140597-d4915ad8-6b07-11e8-8fcf-67319a91113e.jpg)

**Comment by craig-jong** [comment]
No, you're quite right. It looks like the difficulty settings on your server got reset.

I would open the server console by typing "/openserverui" into the chat window then navigate to the difficulty settings and set it back to "no collaboration". Let me know if that fixes it.

**Comment by HetNeSS** [comment]
Yeah, it was on "medium collaboration" for some reason. Thank you

**Comment by vincentmrose** [comment]
Just to confirm: @craig-jong your fix worked for me as well.

I needed to reinstall Eco through Steam because of a crash.
After loading my backup of the world, the collaboration was set to "MediumCollaboration", while before te crash it loaded the world multiple times correctly with "NoCollaboration".

I'm unsure if it happens at random, as @HetNeSS s' report suggests or if specific occurences cause the game to not save the set collaboration setting.

**Comment by SlayksWood** [comment]
merged to #12039
