### ISSUE TITLE
7.5.0: Unable to generate new world on game startup

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#7883]
**Version:**
7.5.0 on Bleeding_Edge_Staging

**Description:**
If you open the game and generate new world, Eco makes world's .db file, then shuts down.  No crash log is created to post.  Reproduced 8 times with all of the collaberation lvl's tested.

**Steps to Reproduce:**
1. Open Eco (used Steam).
2. Click New tab.
3. Name world, select Generate new and allow friends to join buttons.
4. Game will eventually shutdown once world generation is complete.

**Comment by BlazeGuy2** [comment]
With new 7.5.0 build, can't make new worlds at all , nor can I port existing worlds to the new version.

**Comment by metachronism** [comment]
seems to be working fine
