### ISSUE TITLE
Waterlevel on web viewer is incorrect

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7885]
![image](https://user-images.githubusercontent.com/6262198/40560270-56686916-600e-11e8-9e6f-5e47941331af.png)

**Comment by SeanAtr0n** [comment]
sea level is probably incorrect, is this a world you just generated?

**Comment by SeanAtr0n** [comment]
i've seen this on a bunch of other servers... sea level & initial sea level getting set to very wrong values, not sure how people are doing it though

**Comment by SlayksWood** [comment]
Never saw this in latest versions. Seems fixed.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/72610001-59280180-3937-11ea-9097-334ac62f0e3b.png)

**Comment by j3fffff** [comment]
fixed
