### ISSUE TITLE
Chat tag exception

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#7887]
Moving multi-bug https://github.com/StrangeLoopGames/EcoIssues/issues/7829

In this save I logged in as the user and it looks like the fix from 7.4.6 gets past the exception but categories look messed up for this user
![image](https://user-images.githubusercontent.com/774628/40566584-3ff9f7ea-6026-11e8-976a-5556ba181e91.png)
```

NullReferenceException: Object reference not set to an instance of an object
Assets.UI.Scripts.ChatTagPanel.AddChatTags (System.Collections.Generic.IEnumerable`1[T] messages) (at Assets/UI/Scripts/Chat/ChatTagPanel.cs:53)
Assets.UI.Scripts.ChatTagPanel.AddChatTagsForLog () (at Assets/UI/Scripts/Chat/ChatTagPanel.cs:46)
Assets.UI.Scripts.ChatTagPanel.<Start>m__0 () (at Assets/UI/Scripts/Chat/ChatTagPanel.cs:34)
UI.ChatManager.DoOnChatManagerInitialized (System.Action action) (at Assets/UI/Scripts/Chat/ChatManager.cs:37)
Assets.UI.Scripts.ChatTagPanel.Start () (at Assets/UI/Scripts/Chat/ChatTagPanel.cs:34)
```

From Pam:
Okay another server: https://www.dropbox.com/s/5yiroy9jidt4vhx/broken-save.zip?dl=0 this one has a .txt in with the name of the user with the problem connecting. He is the owner of the server and crashed out and unable to log back on no matter what he tried - even stopping the server and waiting an hour (I said 30-60 secs and he read it as mins) and still could not get on/ Everyone else can get on and he can get on any other server he tries, whether or not he has been on before.

**Comment by WeaselDog** [comment]
Haven't seen any reports of this and I can't replicate it. Appears to be fixed in 9.0 staging.
