### ISSUE TITLE
USER ISSUE: crane availability zone is too narrow

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7888]
**Version:** 0.7.5.0 beta staging-1367ba0d
![20180526004559_1](https://user-images.githubusercontent.com/4980243/40567539-6e3d37fe-607e-11e8-9de6-14eb2c70133b.jpg)
ring width 3 blocks ...
![20180526004604_1](https://user-images.githubusercontent.com/4980243/40567544-77db9e36-607e-11e8-9696-626623cbedab.jpg)
They looks as ~7 block in range, but crane rope is too short.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#41

**Comment by elfl0rd** [comment]
Fixed, thx.
