### ISSUE TITLE
USER ISSUE: Connecion Failure

### ISSUE THREAD

**Issue by sdtoler0122** [StrangeLoopGames/EcoIssues#7890]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
I went to continue and the game failed to load

**Expected behavior:**
loaded the game

**Actual behavior:**
The following error message popped up:
```Connedtion failure
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Looks like you're running a fairly old version of Eco.  Update to the latest version - we have fixed many connection issues since then :)
