### ISSUE TITLE
USER ISSUE: regular game crashes on active moving.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7891]
Version: 0.7.5.0 beta staging-1367ba0d
[Crashes.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2041135/Crashes.zip)

**Comment by metachronism** [comment]
unfortunately can't really do much just with crash dumps (would need unity source license, which we don't have)

**Comment by elfl0rd** [comment]
crashes every ~2-10 min on this release, it's make game unplayable :(

**Comment by elfl0rd** [comment]
Game still crashes after 0.7.5.0 beta staging-87e67f1f
[Crash_2018-05-31_233028.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2060111/Crash_2018-05-31_233028.zip)

**Comment by elfl0rd** [comment]
0.7.5.0 beta staging-589c887f still crashes
