### ISSUE TITLE
7.5.0 Can't use crane to place objects in truckbed

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#7892]
Cranes are unable to place materials in a truckbed.  In sample clip, I attempted to place a an object in a stockpile and a truckbed.  Stockpile worked as intended, but the i couldn't place the object in the truck.

![crane_truck](https://user-images.githubusercontent.com/35509188/40570662-eb577dea-6041-11e8-8b70-2005435cb9bb.gif)

**Comment by johnkslg** [comment]
Fixed
