### ISSUE TITLE
7.5.0 Spawning the economy or placing a store crashes Eco

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#7893]
Gabeux and I both replicated this by calling /spawneconomy and placing store objects, probably an issue with some deprecated currency features.
[store_crashIssue.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2041162/store_crashIssue.txt)

**Comment by johnkslg** [comment]
Should be fixed
