### ISSUE TITLE
game open

### ISSUE THREAD

**Issue by herano3** [StrangeLoopGames/EcoIssues#7895]
**Version:** 0.7.4.5 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60,00%>Token is invalid.</size>
```

<details>
<summary>Log File</summary>Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
d3d11: D3D_FEATURE_LEVEL_11_1 not-recognized (only 11.0 runtime installed?)
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: Intel(R) HD Graphics 4000 (ID=0x166)
    Vendor:   Intel
    VRAM:     880 MB
    Driver:   8.15.10.2626
Begin MonoManager ReloadAssembly
- Completed reload, in  0.079 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.979375 ms
Setting up 4 worker threads for Enlighten.
  Thread -> id: 1cb4 -> priority: 1 
  Thread -> id: 1d00 -> priority: 1 
  Thread -> id: 1824 -> priority: 1 
  Thread -> id: 1044 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.5 beta
Wednesday, May 16, 2018 3:29 AM
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/

**Comment by rainfarmer** [comment]
What is your eco username?

Are you playing from Steam or our website version of the game?
Did you link Steam to our website?

**Comment by Voosle** [comment]
@rainfarmer @herano3 
It's the Steam version linked to the web site. Both names are "Voosle"

**Comment by BlazeGuy2** [comment]
Closing due to no response.
