### ISSUE TITLE
USER ISSUE: Invisible Stone Ramps

### ISSUE THREAD

**Issue by Baret** [StrangeLoopGames/EcoIssues#7898]
**Version:** 0.7.4.6 beta

**Steps to Reproduce:**
Dig Dirt to make space for a Ramp. In a specific area (maybe only a single chunk?) stone ramps can be placed, but are not visible for some players. Another ramp can not be placed, although it seems it would be possible ("Can't place there, blocked").
This seems to be the same problem described here: https://steamcommunity.com/app/382310/discussions/4/1692669912388531683/

**Expected behavior:**
All players can see and use the placed ramps.

**Actual behavior:**
Some players (in this case only me afaik) can not see the ramps. This means you can not use it with a cart. When trying to place another ramp in the same (seemingly free) space, you get the message "Can't place there, blocked".

<details>
<summary>Log File</summary>(...previous log truncated...)

 1 
  Thread -> id: 1910 -> priority: 1 
  Thread -> id: 1914 -> priority: 1 
  Thread -> id: 1954 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.6 beta
Freitag, 25. Mai 2018 03:12
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> ServerBrowser
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[48:00] Connecting via Lidgren to dertoaster.ddns.net:3000
Changing sta

**Comment by Baret** [comment]
This issue seems to be related to #7849, #7790 (already assigned) and #7815 (already assigned)

**Comment by GophTheGreat** [comment]
Gonna make this one High priority just because it's been reported a bunch of times now.

**Comment by SeanAtr0n** [comment]
fixed in 7.5
