### ISSUE TITLE
USER ISSUE: Falling through the floor

### ISSUE THREAD

**Issue by Kimonid** [StrangeLoopGames/EcoIssues#7899]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Well, i have built my basement, everything worked fine.
Now after about 1 Day i went back down just to look at it and suddenly fell through the floor. Its made out of mortared Stone and about 6 blocks under the surface.

**Expected behavior:**
Falling through the floor.

**Actual behavior:**
Well, exactly that, works everytime i go down there, even after server restart.

**Comment by SeanAtr0n** [comment]
Is it still an issue in the latest version? We are on 7.4.6 now

**Comment by SeanAtr0n** [comment]
if it's still an issue in 7.4.6 could you please send us your game save?
