### ISSUE TITLE
Workbench occupancy bugged

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#790]
![image](https://cloud.githubusercontent.com/assets/3536496/20025160/1875c15e-a2a9-11e6-822c-5ce1624c0d2f.png)

**Comment by johnkslg** [comment]
![image](https://cloud.githubusercontent.com/assets/3536496/20025172/2fddec9a-a2a9-11e6-8e65-38de5548c33a.png)

**Comment by keegan-o** [comment]
should be 2,1,2 rather than 2,2,2
