### ISSUE TITLE
USER ISSUE: Game crashed while loading a save

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#7902]
**Version:** 0.7.4.6 beta

**Steps to Reproduce:**
1. Play a SP game
2. Exit to the main menu
3. Load the game savestate

**Expected behavior:**
It should not crash

**Actual behavior:**
The following error message popped up:
```
<size=150%>Ошибка подключения</size>

Failed to establish connection - no response from remote host
```

<details>
<summary>Log File</summary>(...previous log truncated...)

ventories... 
LocalServer -  Starting EcoObjectManager... 
LocalServer -  Loading Objects... 
LocalServer -  Starting GarbagePlugin... 
LocalServer -  Starting ChatServer... 
LocalServer -  Starting ControllerManager... 
LocalServer -  Loading Garbage... 
LocalServer -  Starting PropertyManager... 
LocalServer -  Starting EcoSim... 
LocalServer -  Loading Property... 
LocalServer -  Starting DisasterPlugin... 
LocalServer -  Loading Chat... 
LocalServer -  Starting MinimapManager... 
LocalServer -  Starting WirePlugin... 
LocalServer -  Starting DifficultySettings... 
LocalServer -  Loading Disasters... 
LocalServer -  Loading Plants... 
LocalServer -  Initializing plants... 
LocalServer -  Starting RouteProbingPlugin... 
LocalServer -  Loading RouteProbing... 
LocalServer -  Starting WorldLayerManager... 
LocalServer -  Loading Layers... 
LocalServer -  Initializing world layers... 
LocalServer -  Loading ClimateSim... 
LocalServer -  Starting EconomyTracker... 
LocalServer -  Starting WorldObjectManager... 
LocalServer -  Loading WorldObjects... 
LocalServer -  Starting EconomyPlugin... 
LocalServer -  Loading Economy... 
LocalServer -  Starting RoomPlugin... 
LocalServer -  Loading Rooms... 
LocalServer -

**Comment by metachronism** [comment]
Need the server logs.  Can you check Eco_Data\Server\Dumps and attach any of them?  (and reopen this bug with them if so?  thanks)

**Comment by HetNeSS** [comment]
Github doesn't support that file type, so I've uploaded it to dropbox
https://www.dropbox.com/s/9ugwdkj1c7suykl/ServerCrash%20SocketException%2005251755.ecodmp?dl=0
https://www.dropbox.com/s/w860nr7954nbi3t/ServerCrash%20SocketException%2005262924.ecodmp?dl=0
