### ISSUE TITLE
7.5.0. Massive GPU usage / Lag

### ISSUE THREAD

**Issue by Serynthara** [StrangeLoopGames/EcoIssues#7903]
![unbenannt](https://user-images.githubusercontent.com/34604183/40578724-61304178-6119-11e8-92a7-352b87958b3d.PNG)

[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2041821/DxDiag.txt)

**Comment by metachronism** [comment]
this is a bit too generic of an issue to do anything about - Do you want eco to not use your GPU fully?  if so you can cap the framerate in the options menu.

otherwise closing this out as need more specifics
