### ISSUE TITLE
7.5.0 - wheels clipping to surface

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7905]
Version: 0.7.5.0 beta staging-1367ba0d
![20180526202433_1](https://user-images.githubusercontent.com/4980243/40578900-3c27a1a8-6125-11e8-838d-455474a2991a.jpg)
![20180526202441_1](https://user-images.githubusercontent.com/4980243/40578901-3c828096-6125-11e8-82fd-2d4d7278ed25.jpg)
![20180526202558_1](https://user-images.githubusercontent.com/4980243/40578902-3cde0ff6-6125-11e8-8579-e37d60ba05e6.jpg)
![20180526204225_1](https://user-images.githubusercontent.com/4980243/40578910-5c0533d2-6125-11e8-9c3e-ce7411869530.jpg)

**Comment by Nicolausi113** [comment]
kind of realistic impression due to load… :)
However, I could life with it.

**Comment by elfl0rd** [comment]
>kind of realistic impression due to load… :)

Realistic on hard wheel? (Steel|wood ring) Pressurised wheel (excavator, truck) not have this issue.

>However, I could life with it.

Yes, i too.

**Comment by SlayksWood** [comment]
8.1 still an issue

**Comment by SlayksWood** [comment]
move to #12047
