### ISSUE TITLE
Game crashes after a couple of minutes of gameplay

### ISSUE THREAD

**Issue by TheRobertsE** [StrangeLoopGames/EcoIssues#7907]
i had this problem when i first got the game and after fixing another major bug this one was still happening

when i load/create game it lets me play for a couple of minutes until i get taken back to the main menu with the error "connection timed out"
this error happens every time i load any save even after a clean re-install and disabling my antivirus and firewall just in case they got in the way of the server

ive talked a moderator on discord trying every way to get this to work but even after a 
clean re-install 
checking that my av or firewall got in the way
disabling my av to allow all eco files to be downloaded(the av doesnt like the eco server file)
checking .Net Frameworks was at the right version

[log_180526075948.log](https://github.com/StrangeLoopGames/EcoIssues/files/2041891/log_180526075948.log)

**Comment by Caledorn** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/7839 (Now closed issue, but may contain some relevant files/info)

**Comment by TheRobertsE** [comment]
ive just tried turning down all the graphics settings just in case its caused by a hardware issue(i dont have a godly pc) but the crashes still happen

**Comment by TheRobertsE** [comment]
ive been able to mostly fix it my increasing the priority of the game and decreasing graphics settings which makes me think its a cpu issue
