### ISSUE TITLE
USER ISSUE: Wheelbarrow too slow

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7913]
**Version:** 0.7.5.0 beta staging-1367ba0d
Wheelbarrow move 50% slower versus cart.
That's terribe :(

**Comment by elfl0rd** [comment]
and they have action on LMB, code copied from hand plough?

**Comment by elfl0rd** [comment]
this is not suggestion...

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#399
