### ISSUE TITLE
Client crashed while cut tree lying on ground

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#7915]
Connection timed out

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: AMD Radeon (TM) R9 200 Series (ID=0x6811)
    Vendor:   ATI
    VRAM:     2028 MB
    Driver:   24.20.11001.5003
Begin MonoManager ReloadAssembly
- Completed reload, in  0.963 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.906400 ms
Setting up 4 worker threads for Enlighten.
  Thread -> id: 6a50 -> priority: 1 
  Thread -> id: 5f78 -> priority: 1 
  Thread -> id: 5f74 -> priority: 1 
  Thread -> id: 6be0 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.6 beta
Freitag, 25. Mai 2018 03:12
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> PasswordRequest
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PasswordRequest -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException
  at (wrapper managed-to-native) UnityEngine.GameObject:GetComponentInParent (UnityEngine.GameObject,System.Type)
  at UnityEngine.GameObject.GetComponentInParent[T] () [0x00001] in <0ab26637e49a49deb2c166b5c94319b0>:0 
  at InteractionManager.SendInteraction (Eco.Shared.Items.InteractionMethod method) [0x000ae] in <a14c2a2baa3940d0969f235d02df648a>:0 
  at PlayerHeldObject.PerformInteraction (Eco.Shared.Items.InteractionMethod method) [0x00005] in <a14c2a2baa3940d0969f235d02df648a>:0 
  at PerformInteraction.SendInteraction (UnityEngine.AnimationEvent animationEvent) [0x00006] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <0ab26637e49a49deb2c166b5c94319b0> Line: 0)

[47:46] Disconnected from server.Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by metachronism** [comment]
Need the logs from the server.  can you check Eco_Data\Server\Dump and attach any of those if this occurs again?  thanks.

**Comment by metachronism** [comment]
(and reopen)
