### ISSUE TITLE
Vehicle + Border Issue (Truck disappears)

### ISSUE THREAD

**Issue by MaxInertia** [StrangeLoopGames/EcoIssues#7917]
**ECO Version: 0.7.4.6 beta**

When crossing the border in my truck the game seems to freeze momentarily and then when it unfreezes I am no longer in my truck. The truck just vanishes. After crossing the border (sometimes more than once) it reappears, often falling from the sky.

While it's invisible It's X and Z coordinates are constant, but the Y coordinate is oscillating. The lowest value I saw was -4, highest was roughly 70.

NOTE: This doesn't always happen on the border, I relogged and it stopped happening, so I'm not sure exactly how to replicate it yet.

Here is the recording of it happening: https://youtu.be/WVsL8XhmB7E

**Comment by MaxInertia** [comment]
It happened again, however this time when I crossed the border all my ramps disappeared as well as the truck.

There's still something really weird going on in the games underlying treatment of the border. Maybe an overhaul of the src handling the border is required to prevent similar bugs from arising? I've played since version 5 and there were border-related bugs at that time as well. If I can ever afford Dev Tier (poor student, RIP) I'll definitely spend some time trying to figure out what's going on here.

Video: https://youtu.be/9CXiLHbndUE

**Comment by SeanAtr0n** [comment]
are you sure you are on 0.7.4.6? This behavior should be fixed already

**Comment by MaxInertia** [comment]
Unless Steam has been lying to me. The Server I play on has been this version since May 24th, and I haven't changed my client version since.

![image](https://user-images.githubusercontent.com/12981415/41020896-28336634-692a-11e8-9098-985bce88d0c8.png)

While being very similar to my previously posted issues (since it's related to the border) **this is a slightly different problem than I had reported in the past**: Blocks would not render on the other side of the world border until I crossed (at which point both would be visible). 

Here some world objects vanish on the other side of the world border when I cross (so things mess up when I go over there). In the case of the dirt ramps - they don't only fail to render, my character is not held up by invisible ramps, as far as I can tell they don't even exist.

**Comment by MaxInertia** [comment]
Also forgot to mention that in the first video even though the ramps were still visible to me (and the other player present) my characters position was inside the ramp according to the other player. You can see him say something like "You're swimming in the ramp" around the 15 second mark.

Luckily he took a screenshot of it at the time!

![image](https://user-images.githubusercontent.com/12981415/41021939-c1bb5426-692d-11e8-81f5-065a662c9827.png)

**Comment by ecostasiaUser** [comment]
I have exactly the same problem at the current Version 0.7.6.3. Ramps and other placed objects disappear by crossing a certain point. My truck disappears. When I cross the line backwards, objects are rendered again and the truck is falling from the sky.
