### ISSUE TITLE
USER ISSUE: Invalid login info - invalid ticket

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#7918]
**Version:** 0.7.4.6 beta

**Steps to Reproduce:**
1. Select a server with some language prefix which is different from the language being shown  in server configuration
2. Receive the message.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Ошибка подключения</size>

Invalid login info.

<size=60.00%>Invalid ticket</size>
```

<details>
<summary>Log File</summary>Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 950 (ID=0x1402)
    Vendor:   NVIDIA
    VRAM:     1960 MB
    Driver:   23.21.13.9065
Begin MonoManager ReloadAssembly
- Completed reload, in  0.126 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.894445 ms
Setting up 2 worker threads for Enlighten.
  Thread -> id: 199c -> priority: 1 
  Thread -> id: d88 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.6 beta
25 мая 2018 г. 6:12
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> Log

**Comment by HetNeSS** [comment]
<size=150%>Connection error</size>

Invalid login info.

<size=60.00%>Invalid ticket</size>


.. I think it was a one-time issue where the game auth servers were down.

**Comment by Nanders** [comment]
That would make sense, I'll close this issue then
