### ISSUE TITLE
Game Keeps Freezing / Crashing

### ISSUE THREAD

**Issue by Darklord6229** [StrangeLoopGames/EcoIssues#7919]
Ever since 7.4.6 my game will randomly freeze / then crash. I have been watching my resource usage of my computer and nothing has been maxing out that would cause this crash. I also have gone to my logs / dump files and can find nothing so trying to diagnose this issue myself has been problematic. It happens on different servers and local play so I cannot determine if it is specific to connection type and it happens no matter what I am doing ingame. Any help that can be given in this matter would be greatly appreciated.

**Comment by Darklord6229** [comment]
This is still happening and is very game breaking, any help would be appreciated.

**Comment by metachronism** [comment]
this is any server?  Client has a bad memory issue now, could be related to that

**Comment by metachronism** [comment]
memory issues are considerably improved in 8.0
