### ISSUE TITLE
Client side animation

### ISSUE THREAD

**Issue by FishAus** [StrangeLoopGames/EcoIssues#7920]
**Issue:**
When connecting to a server a client will see the entry state animations and wont move to the correct animations

**To replicate:**
Make Kiln, Start job. Doors close as they should be while job is going
Disconnect client
Reconnect client
Kiln doors are open and should not be while job is still in progress.

This also means that anyone trying to implement animations on mods will run into a similar issue for animations that should be in a  particular "state" when clients connects.

**Comment by Nicolausi113** [comment]
Yes, I have that experienced as single player on the builtin server also for other devices like research table (no motion) and masonry table ( no sound).

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#400
