### ISSUE TITLE
USER ISSUE: Connection fails when continuing network game

### ISSUE THREAD

**Issue by surcoufx83** [StrangeLoopGames/EcoIssues#7922]
**Version:** 0.7.4.6 beta

**Steps to Reproduce:**
1. Join a network server (my own server is in the same network as my desktop computer for gaming)
2. Leave game (disconnect or quit game)
3. Use the Continue function from main menu

**Expected behavior:**
It should ask again for the server password and connect to the server.

**Actual behavior:**
Client tries to connect and after a few seconds shows the error "Connection failed. No response from master server."
The following error message popped up:
```
<size=150%>Connection Failed</size>

No response from master server.
```

<details>
<summary>Log File</summary>Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 (ID=0x1b80)
    Vendor:   NVIDIA
    VRAM:     8079 MB
    Driver:   24.21.13.9764
Begin MonoManager ReloadAssembly
- Completed reload, in  0.793 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.696902 ms
Setting up 4 worker threads for Enlighten.
  Thread -> id: 2f3c -> priority: 1 
  Thread -> id: 2c1c -> priority: 1 
  Thread -> id: 11ac -> priority: 1 
  Thread -> id: 36f8 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.6 beta
Freitag, 25. Mai 2018 03:12
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> ServerBrowser
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: ServerBrowser -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[11:45] Disconnected from server.</details>

**Comment by metachronism** [comment]
should be fixed as of 7.4.7+
