### ISSUE TITLE
0.7.4.6 SkidSteer can't owned by user.

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#7924]
Game version 0.7.4.6

1. build a SkidSteer
2. put her on the ground
3. open it (press the "E" key)
4. We see in the top the mark "Owned by ."
5. Any player can use this SkidSteer because he has no owner.

![20180528210710_1](https://user-images.githubusercontent.com/1098421/40626840-d8b4e748-62c3-11e8-8a35-ed1d1b59dc0e.jpg)

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/7931
