### ISSUE TITLE
Game does not start

### ISSUE THREAD

**Issue by Ivonator** [StrangeLoopGames/EcoIssues#7925]
When I start the game, I can choose which world I want to play, then it begins to load.

After a few moment the procedure interrupts with a black screen, followed by a white screen, followed by an error message on screen, that Eco doe not react.

The same happens, when I create a new world.

I play Singleplayer, Version 7.4.5, SGL-Version

When I start the Steam version, the start will be interrupted with following message:  Connection failed - Incompatible Version.

My System:

Windows 7 Home

Intel Core I7 - 2700  3,50 Ghz,  16GB Ram

AMD Radeon HD 5700 Series

If you need a report, please tell me how to create...

**Comment by metachronism** [comment]
this sounds like you are potentially maybe running another, older server locally?

**Comment by Ivonator** [comment]
Hi,
Now after 2 weeks of vacation I startet the game via Steam.
It worked fine (version 7.4.7.)
I will report when the problems still appear...
