### ISSUE TITLE
USER ISSUE: meteorite destroy with insufficient power

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7927]
Version: 0.7.5.0 beta staging-1367ba0d
Currently, meteorite can be destroyed if you have power to power one or more laser.
4 not requied.
https://youtu.be/NCU9tysGlRw

**Comment by Deantwo** [comment]
https://github.com/StrangeLoopGames/Eco/pull/3337

If it is a bool, does that mean that if I supply enough power to 4 laser, but my 5th laser is un-powered, will I be unable to destroy the meteor?
