### ISSUE TITLE
Suggestion: Add different Input/Output Storage Links

### ISSUE THREAD

**Issue by MikeW27** [StrangeLoopGames/EcoIssues#7928]
It would be cool to have two checkmarks for linking storages.
One for input, one for output.
For example to set the input box for ironingots in one box, but output steel to another box so a production-chain could be set up.

**Comment by Nicolausi113** [comment]
There are already suggestions in this direction #7285

**Comment by elfl0rd** [comment]
And right place for suggestions here - https://github.com/StrangeLoopGames/EcoSuggestions/issues

**Comment by MikeW27** [comment]
Thanks for the note, my apologies! Thought I was in the right place before.
I will change it.
