### ISSUE TITLE
0.7.4.6 TRUCK can't owned by user.

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#7931]
Game version 0.7.4.6
1. build a truck
2. put his on the ground
3. open it (press the "E" key)
4. we see in the top the mark "Owned by ."
5. any player can use this Truck because he has no owner.
![truck_error](https://user-images.githubusercontent.com/1098421/40673847-af35bb82-637b-11e8-82b3-fc5ecf647979.jpg)
**Re-entry to the server or restarting the client** does not solve the problem. Sometimes it helps to completely restart the server.

**Comment by MikeW27** [comment]
Is it possible that it this behavior is directly affected, where you place your truck?
Is it owned when you place it on a field where you own the property / unowned when you place it somewhere else?
