### ISSUE TITLE
0.7.4+ - recent not contain directly connected servers.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7934]
If player connect to server using direct connect [+] server is not saved in recent servers.

**Comment by MarjieAVolk** [comment]
Fixed in next release

**Comment by MarjieAVolk** [comment]
Alright, I checked in on this, and looks like the continue button should work with direct ip connections.  However, it won't work without a connection to the master server.  So I assume that's what you're seeing.

**Comment by MarjieAVolk** [comment]
Filed a new issue for this here: https://github.com/StrangeLoopGames/EcoIssues/issues/8003

**Comment by elfl0rd** [comment]
hmm... how continue work without ip addres info?

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/41187638-94dbca90-6bb6-11e8-89c7-7a9d45f30375.png)
Recent servers contain IP:port

Continue - not
![default](https://user-images.githubusercontent.com/4980243/41187641-ab678c36-6bb6-11e8-9fd0-32fc5464f525.png)

**Comment by MarjieAVolk** [comment]
Yeah, it only uses the unique identifier, which is why it needs the master server.  It looks up the connection info from the master server using the identifier.

**Comment by elfl0rd** [comment]
Ok :)
