### ISSUE TITLE
GRAPHIC ISSUE: Wall elements displayed in wrong direction

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#7939]
_From @BlazeGuy2 on May 30, 2018 7:27_

_From @Nicolausi113 on April 28, 2018 23:19_

(v0.7.3.3 also 0.7.2.5) Possibly all wall-elements (bricks, stone, logs) are displayed in a wrong direction if they are inserted in a north-south-wall with gaps between. If windows or doors (or even blocks) are inserted, the texture turns in the right direction. Fancy things happen when a door is opened, the wall opens also :)

![eco wrong elemnts](https://user-images.githubusercontent.com/38510829/39401664-df732418-4b4a-11e8-98be-ce3dc5c54b36.jpg)

Attachment and Suggestion: wouldn't it be best to use the direction keys for such elements, it would clear the code?

_Copied from original issue: StrangeLoopGames/EcoIssues#7478_

_Copied from original issue: StrangeLoopGames/EcoSuggestions#89_

**Comment by BlazeGuy2** [comment]
_From @elfl0rd on May 30, 2018 12:47_

this looks as issue, not suggestion =|
Wrong direction elements terrify me.

**Comment by BlazeGuy2** [comment]
_From @Nicolausi113 on May 30, 2018 13:21_

Initially I opened this as an issue as the title says and somehow muted it to a suggestion, maybe because there is a suggestion included. What shell happen now? Shell I copy it back?

**Comment by BlazeGuy2** [comment]
I was using a tool to bump over the issues tagged as suggestions, I'll move this one back to the bug area.

**Comment by BlazeGuy2** [comment]
This was logged as a suggestion but looks more like a bug to me.

**Comment by elfl0rd** [comment]
yep) thx

**Comment by Nicolausi113** [comment]
similar entry #4500

**Comment by keegan-o** [comment]
It's not quite so simple as this because if we did this, we would have to have a new form as well that would be quite confusing and a hassle: we'd have walls, and then we'd have intersection wall pieces. However, I should be able to improve the logic to at least take care of the situation in the screen shot.

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/42789792-0e52a150-891c-11e8-8416-e605607cbce2.png)
Fixed this exact case for now, anyways! In master on 7/16 (should go in 7.7 or 7.8)
