### ISSUE TITLE
World doesn't load

### ISSUE THREAD

**Issue by Sn4k31337** [StrangeLoopGames/EcoIssues#7940]
(Vers. 0.7.4.6) Problem when Joining game, World just stops Downloading world, i got a ping like 70ms to the Server and Up- / Download is at 0, i just got this Logs: 

Output_log
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1060 6GB (ID=0x1c03)
    Vendor:   NVIDIA
    VRAM:     6052 MB
    Driver:   23.21.13.9101
Begin MonoManager ReloadAssembly
- Completed reload, in  0.099 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.860302 ms
Setting up 4 worker threads for Enlighten.
  Thread -> id: 2e18 -> priority: 1 
  Thread -> id: 3534 -> priority: 1 
  Thread -> id: 434 -> priority: 1 
  Thread -> id: 3508 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.6 beta
Freitag, 25. Mai 2018 03:12
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> PasswordRequest
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PasswordRequest -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[02:59] Local server manager destroyed, stopping server.Releasing render texture that is set as Camera.targetTexture!
 
(Filename:  Line: 3926)

-------------------------------------------------------------------------

Eco Log Session from 30.05.2018 20:24:45
Packet parsing error: Value cannot be null.
Parameter name: key from IP:PORT
Packet parsing error: Value cannot be null.
Parameter name: key from IP:PORT
Packet parsing error: Value cannot be null.
Parameter name: key from IP:PORT
Disconnected from server.
Packet parsing error: Value cannot be null.
Parameter name: key from IP:PORT
Packet parsing error: Value cannot be null.
Parameter name: key from IP:PORT
Packet parsing error: Value cannot be null.
Parameter name: key from IP:PORT
Packet parsing error: Value cannot be null.
Parameter name: key from IP:PORT
Packet parsing error: Value cannot be null.
Parameter name: key from IP:PORT
Packet parsing error: Value cannot be null.
Parameter name: key from IP:PORT
Packet parsing error: Value cannot be null.
Parameter name: key from IP:PORT
Packet parsing error: Value cannot be null.
Parameter name: key from IP:PORT
Packet parsing error: Value cannot be null.
Parameter name: key from IP:PORT
Packet parsing error: Value cannot be null.
Parameter name: key from IP:PORT
Local server manager destroyed, stopping server.

**Comment by metachronism** [comment]
Need a copy of the gamesave.  Please attach and re-open if possible
