### ISSUE TITLE
Cant pass District Law

### ISSUE THREAD

**Issue by Jakaya0897** [StrangeLoopGames/EcoIssues#7945]
![image](https://user-images.githubusercontent.com/20933341/40785814-6d852940-64e1-11e8-8e3b-9893e12f2dad.png)

![](https://cdn.discordapp.com/attachments/451731007398215680/451731020199362571/unknown.png)

Unless I draw super quickly otherwise I get an out of index error

**Comment by Jakaya0897** [comment]
![image](https://user-images.githubusercontent.com/20933341/40810070-93235fe4-6524-11e8-9742-e57f9ab8a888.png)
Just to show it doesn't only happen on district creation but all laws if i take too long cant submit the law

**Comment by MarjieAVolk** [comment]
Does this happen on all servers?  Or is it specific to one?  Is it a local save?  Also, what version of the game are you running?  You can check in the escape menu.

**Comment by rainfarmer** [comment]
laws moved to in-game
