### ISSUE TITLE
USER ISSUE: official testing server visible in LAN

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7947]
Version: 0.7.5.0 beta staging-87e67f1f
![20180531234657_1](https://user-images.githubusercontent.com/4980243/40808007-856d68e0-652e-11e8-9ca4-8a6dbde32b2e.jpg)
![20180531234601_1](https://user-images.githubusercontent.com/4980243/40808008-85929fc0-652e-11e8-8011-906752111e24.jpg)

**Comment by gabeux** [comment]
+1, in 7.5.0 87e67f1f all my favorite and recent servers are shown in the LAN

**Comment by MarjieAVolk** [comment]
Both the LAN section issue and some problems with favorites will be fixed in the next build.

**Comment by gabeux** [comment]
Heya! Latest bleeding edge [589c887f] has issues with Favorites:

[Video example](EagerPertinentEnglishpointer)

**Comment by MarjieAVolk** [comment]
Continued fixing this here: https://github.com/StrangeLoopGames/Eco/pull/2921
