### ISSUE TITLE
USER ISSUE: Command Results in Server Exception

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7950]
**Version:** 0.7.5.0 beta staging-87e67f1f

**Steps to Reproduce:**
Used /spawneconomy when first entering world

**Expected behavior:**
Command should have worked as intended.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.StoreComponent.get_Enabled()
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Objects.WorldObject.UpdateEnabledAndOperating()
   at Eco.Gameplay.Components.SolidGroundComponent.UpdateEnabled()
   at Eco.Gameplay.Objects.WorldObject.AddComponent(Type componentType, Object[] args)
   at Eco.Gameplay.Objects.WorldObject.ValidateComponents()
   at Eco.Gameplay.Objects.WorldObject.BeginInitialize()
   at Eco.Gameplay.Objects.WorldObject.OnAdd(User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.Add(WorldObject worldObject, User creator, Vector3 position, Quaternion rotation)
   at Eco.Gameplay.Objects.WorldObjectManager.TryToAdd(Type worldObjectType, User creator, Vector3 position, Quaternion rotation, Boolean validatePlacement, WorldObjectItem item)
   at Eco.Gameplay.Economy.EconomyUtil.SpawnBuildingWithObject(DeedItem deed, String name, Player player)
   at Eco.Gameplay.Economy.EconomyUtil.SpawnEconomy(Player player, Int32 ordersPerStore, Int32 stores)</size>
```

<details>
<summary>Log File</summary>(...previous log truncated...)

er... 
LocalServer -  Starting EconomyPlugin... 
LocalServer -  Starting RoomPlugin... 
LocalServer -  Starting ObjectivePlugin... 
LocalServer -  Starting Legislation... 
LocalServer -  Starting WebServerPlugin... 
LocalServer -  Starting HousingTierDefinition... 
LocalServer -  Initializing LocalizationPlugin... 
LocalServer -  Initializing ModKitPlugin... 
LocalServer -  Initializing WorldGeneratorPlugin... 
LocalServer -  Generating world 0.52km�... 
LocalServer -  Generating terrain... 
LocalServer -  Caching world data... 
LocalServer -  Generating plateaus... 
LocalServer -  Carving rivers... 
LocalServer -  Generating special features... 
LocalServer -  Ticking (Pass 1)... 
LocalServer -  Initializing world layers... 
LocalServer -  Ticking world layers... 
LocalServer -  Ticking (Pass 2)... 
LocalServer -  Determining visibility... 
LocalServer -  Compressing... 
LocalServer -  Saving world... 
LocalServer -  Generating world 0.52km� finished in 159,006.6ms
LocalServer -  Initializing UserManager... 
LocalServer -  Initializing MinimapManager... 
LocalServer -  Initializing WorldObjectManager... 
LocalServer -  Initializing EconomyPlugin... 
LocalServer -  Initializing RoomPlugin... 
LocalServer -  Initializing HousingTierDefinition... 
LocalServer -  Initializing WorldPlugin... 
LocalServer -  Ticking... 
LocalServer -  Compressing... 
LocalServer -  Initializing NetworkManager... 
LocalServer -  Initializing WorldLayerManager... 
LocalServer -  Initializing WebServerPlugin... 
LocalServer -  Server Initialization finished in 180,785.9ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following icons: CraneItem, SteamTractorHarvesterItem, SteamTractorItem, SteamTractorPloughItem, SteamTractorSowerItem, VehicleToolItem
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Shutting down server
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer - Saving...
LocalServer -  Saving world... 
LocalServer - Finished in 256.9msDone
</details>

**Comment by BlazeGuy2** [comment]
Clip of spawn Economy:
https://youtu.be/fKxPXdKAAg8

**Comment by BlazeGuy2** [comment]
Can't tell if stores are the only issue, but at the moment, when placing the store (I r-clicked to place it in the clip), I get disconnected in a couple seconds.
https://youtu.be/P5ZS9ANa6cQ

**Comment by johnkslg** [comment]
Cant repro this anymore, I believe its been fixed with recent currency changes.
