### ISSUE TITLE
Unnatural Land Generation

### ISSUE THREAD

**Issue by ArtisticTuxedo** [StrangeLoopGames/EcoIssues#7951]
In Eco, there have been areas in the world where land generation is exaggerated or it looks unnatural. Mainly they are weird overhangs that are flat, or weird indentations in hills/mountains (these aren't caves, I checked). I checked an older world and it doesn't have the same problem. If this is intended please let me know.
![20180531165104_1](https://user-images.githubusercontent.com/39813007/40813778-d73ac274-64f9-11e8-8fbe-8ba2676e4b88.jpg)
![20180531170028_1](https://user-images.githubusercontent.com/39813007/40813780-d948cad4-64f9-11e8-8fb4-45df8d1f0484.jpg)
![20180531170525_1](https://user-images.githubusercontent.com/39813007/40813787-db11c6e0-64f9-11e8-80c3-28af11687c0f.jpg)
![20180531170555_1](https://user-images.githubusercontent.com/39813007/40813789-dcfb043a-64f9-11e8-8ffa-cb1382e348fb.jpg)

**Comment by AlaskanBootyMeat** [comment]
This is NOT unnatural! I love it! Please don't remove this from the game, because it really simulates alaskas climate well in some areas. Look up "cut banks" or Bluffs. It is a pretty common occurance where the top extends farther out then the middle.

**Comment by johnkslg** [comment]
These are intended yah, but we will be visiting terrain gen soon so these will get a pass!  Closing for now.
