### ISSUE TITLE
Blast Furnace 7.4.6

### ISSUE THREAD

**Issue by AlaskanBootyMeat** [StrangeLoopGames/EcoIssues#7952]
Asked on steam, asked on reddit, Reddit said to post a bug report.

Blast Furnace lags/stutters game client for about 2 seconds, returns to normal for a second, then does it again for 2 seconds. I checked, it IS the blast furnace causing this. It only does it when i think it is dropping its load to a stoarge bin.

Yes, Computer is completely updated. I've checked. And no, its not running on potatoes.

**Comment by PacifyerGrey** [comment]
I can confirm it with Blast Furnace.

However it might be not the Blast Furnace itself but its smoke. I heard people make a long pipe away from the base to remove the stuttering.

**Comment by WeaselDog** [comment]
I haven't been able to reproduce this in the latest version. It seems to be fixed, but please reply back if you experience this issue again.
