### ISSUE TITLE
USER ISSUE: No Response from Master Server

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#7954]
**Version:** 0.7.4.6 beta

**Steps to Reproduce:**
1. Log into your account
2. Try and connect to the server

**Expected behavior:**
Expect it to be able to connect to the server

**Actual behavior:**
Instead you get a message 
"Connection Failed No response from master server."

What is going on with the master server? and why is it not 
responding? It is June 1 2018 at about 9:00 AM MST (GMT-0700)

This is the server I am trying to connect to 
https://ecoservers.io/server/3765/

So why is it saying that there is no response from the master server 
right now?  There is no connection issues on my end I can connect to
everything else fine. 

Here is my output_log.txt as well from AppData\LocalLow\Strange Loop Games\Eco
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2063174/output_log.txt)

![eco no response from master server june 1 2018](https://user-images.githubusercontent.com/38896397/40848003-27086852-657b-11e8-92b7-ce2e184c2432.jpg)

<details>
<summary>Log File</summary>(...previous log truncated...)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at AdjustTransformToCurve.LateUpdate () [0x00074] in <a14c2a2baa3940d0969f235d02df648a>:0 
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[01:53] Disconnected from server.Can not play a disabled audio source
 
(Filename:  Line: 707)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[02:14] Disconnected from server.Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[02:47] Disconnected from server.</details>

**Comment by metachronism** [comment]
this is not a bug per-sey, if you are in russia ATM they are blocking all AWS traffic, so its part of that

otherwise it would just be an intermittent connectivity issue
