### ISSUE TITLE
Corn Seed Gather

### ISSUE THREAD

**Issue by DeadlyDeadric** [StrangeLoopGames/EcoIssues#7959]
It seems no matter how high your grassland gathering skill is, the amount you get for Corn seeds is really low a fellow player who has grassland gathering up to max only seem to get 8 corn seeds from 10 planted corn and this happen twice.

**Comment by BlazeGuy2** [comment]
This is a suggestion for modifying seed gathering rate.  Moving to our Suggestions depot.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#385
