### ISSUE TITLE
Workbench Completion Text w/ Storage Chests - Text Error

### ISSUE THREAD

**Issue by lordtaron** [StrangeLoopGames/EcoIssues#7963]
There is a text error when items are completed at the workbench, which could lead to confusion of lost items when crafting is completed in your territory. Once a storage chest is crafted and placed, workbench projects move to the storage chests when possible. The text that appears, however, still indicates the project should be picked up at the workbench. There is no indication that items will automatically move to chests.

Text should update to "Completed Item has been moved to <Storage Chest Name>" or something similar. Text field on Storage Chest should also be updated to include a reference to crafting and auto-storage.

**Comment by Nicolausi113** [comment]
An annoying problem mentioned already here #7285
Storage links should be managed before crafting and after placing new devices.
Hopefully this will change some day.

**Comment by BlazeGuy2** [comment]
#7285 got moved to https://github.com/StrangeLoopGames/EcoSuggestions/issues/123 ; Closing the issue, but I'll take a look when my tasklog clears up.
