### ISSUE TITLE
Rohrer Bug:  First workbench a player puts down no longer tags itself

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7966]
This used to happen.

"I need to make a workbench, but cannot, because it can only be crafted at a workbench.  This is weird.  No way to bootstrap.  Realized that I placed my "free" workbench last time but wandered away from it.  Had to find my way back."

**Comment by BlazeGuy2** [comment]
Find my workbench was requested in #2981.  Bumping up priority.

**Comment by craig-jong** [comment]
This is fixed in my branch - it'll be merged when the introduction stuff is all complete

**Comment by johnkslg** [comment]
Fixed by Craig
