### ISSUE TITLE
Rohrer Bug: Don't allow using shovel if logs are carried

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7967]
This used to be the case, you were prevented from selecting a tool that didnt work with what you're carrying.

"On my way back to the workbench, I had to climb a hill.  Some dirt is in the way, and I have a shovel in my hand, and I can make a digging noise, but I can't actually dig.  Why?  No space in inventory.  What?  My backpack and toolbar have lots of space.  Oh, I'm holding logs.  I can't dig dirt if I'm holding logs, because the dirt on the tip of the shovel counts as being in my arms?  Set down the logs, and then I can dig.  Why let me have the shovel out if it's impossible to use at this moment?"

**Comment by GophTheGreat** [comment]
Fixed for shovel.
