### ISSUE TITLE
Rohrer Bugs: Crafting Overwhelm

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7968]
"At the workbench, I open up this menu of completely overwhelm.  A list with all these tiny lines on it.  What should I make?  Oh, I can't make most of this stuff.  Why is it shown to me?  It should be grayed out, or displayed under a partition on the list.  Show me the stuff that I can possibly make now."

Fixes to apply:
- [ ] Grey out stuff that you can't build
- [x] Move most of this stuff off workbenches to other tables or modules
- [ ] Simplify the recipe display so there is a single 'Craft' button instead of lots of 'Order' buttons.  Have a shopping cart.

**Comment by AlaskanBootyMeat** [comment]
I second something Simplifying this. Maybe an option to only show whats craftabled at your current skill level?

**Comment by elfl0rd** [comment]
and "craftabled at existing materials"

**Comment by IcedForge** [comment]
Will close this as it is part of a UI upgrade epic that can be followed and tracked here #20426
