### ISSUE TITLE
Rohrer Bug: Too much data

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7969]
"The screen in general is full of lots of tiny bits of information.  Text all over the place.  Data.  Even going to look at a piece of food to eat... data data data.  I'm reading a Nutrition Facts label about a tomato here..."

We may want to put some of this stuff into expandable areas, or some other approach. Let's discuss.

**Comment by metachronism** [comment]
JohnK added 5 bugs to EcoIssues list [1,227 remaining] [20 added today] [10 fixed last week] [8 liked by his mother]

**Comment by metachronism** [comment]
Eric left snarky comment on bug [100 comments remaining] [annoyance level slightly increased] [reputation loss] [minimalism skill increased by 1]

**Comment by WeaselDog** [comment]
Closing as the issue is old and there has been many changes to the UI since then
