### ISSUE TITLE
Rohrer Bug: Improve carrying + crafting interfaces and introduction

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7970]
"Why can I not put logs in my backpack or toolbar?  I've got this hand full of stuff, but only one thing at a time?  How do I craft things that require two ingredients then?  There's a Put On Bench function, but it doesn't work.  How do I load up the bench with multiple ingredients?"

- Need more clarity on what you can carry and what goes into your backpack 
- Need more clarity in crafting things before you have all the ingredients for it.
- Not sure what 'Put On Bench' feature he's referring to.
- Perhaps introduce and improve stockpile usage

**Comment by BlazeGuy2** [comment]
Sounds to me like adding/updating tutorials to better explain the process.  We could aim for tutorials to explain this flow: Place Workbench=>Place Stockpile=>Link Inventories to Workbench=>Craft Using Materials from Stockpile

**Comment by SlayksWood** [comment]
We have tutorials which help players. I assume this issue can be closed. We have enough another issues to improve tutorials and interface.
