### ISSUE TITLE
Rohrer Bug: Couldnt open bench without chopping it (?)

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7972]
"How do I open the bench without also chopping it with my current tool?"

Was the control display not showing?

**Comment by metachronism** [comment]
you press "e" - also this is clearly shown on the UI so not sure what the confusion is

**Comment by GophTheGreat** [comment]
Closing. The tooltip pops up no matter what tool I'm holding so I assume it's not a problem anymore.
