### ISSUE TITLE
7.4.6: Server won't appear on the server list

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#7975]
Currently when I make a server from the steam tool using the tutorial on https://eco.gamepedia.com/Setting_Up_a_Server, the server registers loads as a LAN server by default.  After modifying the Network.eco file and setting PublicServer to true, the game still loads as a LAN game and can't be found on https://www.yougetsignal.com/tools/open-ports/, so I'm assuming that the issue is related to the config file not being read.

**Comment by elfl0rd** [comment]
hmm... maybe in 7.5 too?

**Comment by metachronism** [comment]
if you dont forward ports, you cant have a public server thats reachable via the master server

if you are on the same LAN as the server, its only going to show up in LAN
