### ISSUE TITLE
Lost my cart when falling into the sea

### ISSUE THREAD

**Issue by MMBovo** [StrangeLoopGames/EcoIssues#7977]
**Version:** 0.7.4.6 beta

I've lost my cart when falling into the sea (height 40) from a bridge (height 64).

**Steps to Reproduce:**
I was trying to extend a sea-crossing bridge at y=64. I set my cart close to a storage. I load the cart with road blocks. I drag the cart to the building site. When I building a block I fall off from the bridge. After I return to the building site I cannot find my cart. I checked the coordination on the cart deed - no cart there.

[edited - added video record]
Video clip : https://www.twitch.tv/videos/270025730

**Expected behavior:**
The cart shall be accessable at the position it was.

**Actual behavior:**
The cart disappears. The coordination information on the cart deed remains the same.

Extra info:
I run my 2-men server with the steam version eco-server on the LAN. I play the game from another PC with a steam version.

**Comment by SlayksWood** [comment]
I can’t check it. I think this is due to Zero Point or the periodic item missing (this issue now rarely arises too) We have separate issues for this, so I'll close this one.
