### ISSUE TITLE
Placement can fall through ground

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7982]
![image](https://user-images.githubusercontent.com/3536496/41060222-33844474-698c-11e8-9b7f-ea9509d6ee9f.png)

**Comment by SeanAtr0n** [comment]
steps to reproduce?

**Comment by SeanAtr0n** [comment]
not sure how to repro

**Comment by johnkslg** [comment]
Havent seen it in awhile, maybe its gone.
