### ISSUE TITLE
7.5.0 Screen turns black after initial loading screen finishes

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#7984]
Open Eco from Steam => Loading Screen finishes => screen is black, should be loading up the title screen.  Eco Cursor is still present though.

![ezgif-1-6cf02f93d3](https://user-images.githubusercontent.com/35509188/41065232-d446c1b0-6992-11e8-84b5-d03844d11868.gif)

**Comment by BlazeGuy2** [comment]
Occurs everytime I try to open the game.

**Comment by BlazeGuy2** [comment]
Related to not having the Translations folder present causes an exception that prevents the rest of the UI prefabs from loading.

**Comment by elfl0rd** [comment]
same

**Comment by BlazeGuy2** [comment]
@elfl0rd uploaded the folder to steam, i'm keeping this issue open until we make a PR to fix this in our codebase.

**Comment by BlazeGuy2** [comment]
https://github.com/StrangeLoopGames/Eco/pull/2908

**Comment by elfl0rd** [comment]
Check server too...

**Comment by Nanders** [comment]
This has been fixed
