### ISSUE TITLE
USER ISSUE: Couldn't connect to own world

### ISSUE THREAD

**Issue by Spurux** [StrangeLoopGames/EcoIssues#7985]
**Version:** 0.7.4.6 beta

**Steps to Reproduce:**
Tried to connect to own world

**Expected behavior:**
My world should load up, and put me right in to it

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host
```

<details>
<summary>Log File</summary>(...previous log truncated...)

r -  Starting BackupPlugin... 
LocalServer -  Starting StorageManager... 
LocalServer -  Initializing skills... 
LocalServer -  Starting StatDatabase... 
LocalServer -  Starting WorldPlugin... 
LocalServer -  Loading World... 
LocalServer -  Initializing world... 
LocalServer -  Starting TimePlugin... 
LocalServer -  Loading Time... 
LocalServer -  Starting ReputationPlugin... 
LocalServer -  Loading Reputation... 
LocalServer -  Starting PlayerHousingManager... 
LocalServer -  Starting UserManager... 
LocalServer -  Loading Users... 
LocalServer -  Initializing inventories... 
LocalServer -  Starting EcoObjectManager... 
LocalServer -  Loading Objects... 
LocalServer -  Starting GarbagePlugin... 
LocalServer -  Starting ControllerManager... 
LocalServer -  Starting WirePlugin... 
LocalServer -  Starting PropertyManager... 
LocalServer -  Starting ChatServer... 
LocalServer -  Starting DisasterPlugin... 
LocalServer -  Starting DifficultySettings... 
LocalServer -  Starting EcoSim... 
LocalServer -  Loading Garbage... 
LocalServer -  Loading Property... 
LocalServer -  Loading Disasters... 
LocalServer -  Starting MinimapManager... 
LocalServer -  Loading Chat... 
LocalServer -  Loading Plants... 
LocalServer -  Initializing plants... 
LocalServer -  Starting RouteProbingPlugin... 
LocalServer -  Loading RouteProbing... 
LocalServer -  Starting WorldLayerManager... 
LocalServer -  Loading Layers... 
LocalServer -  Initializing world layers... 
LocalServer -  Loading ClimateSim... 
LocalServer -  Starting EconomyTracker... 
LocalServer -  Starting WorldObjectManager... 
LocalServer -  Loading WorldObjects... 
LocalServer -  Starting EconomyPlugin... 
LocalServer -  Loading Economy... 
LocalServer -  Starting RoomPlugin... 
LocalServer -  Loading Rooms... 
LocalServer -  Starting ObjectivePlugin... 
LocalServer -  Loading Objectives... 
LocalServer -  Starting Legislation... 
LocalServer -  Loading Laws... 
LocalServer -  Starting WebServerPlugin... 
LocalServer -  Starting HousingTierDefinition... 
LocalServer -  Initializing LocalizationPlugin... 
LocalServer -  Initializing WorldGeneratorPlugin... 
LocalServer -  Initializing UserManager... 
LocalServer -  Initializing MinimapManager... 
LocalServer -  Server Initialization finished in 11.295,8ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[11:55] Connecting via Lidgren to localhost:3000
Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoadingWorld -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[12:10] Disconnected from server.Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

</details>

**Comment by Spurux** [comment]
Didn't give me error second time I tried to load world.

**Comment by BlazeGuy2** [comment]
So the error just happened the one time?

**Comment by Spurux** [comment]
Yup. Haven't occurred since, even though I've loaded back into the world 3 or 4 times.

**Comment by BlazeGuy2** [comment]
Alright, closing for now.  If the issue comes up again send me a msg or open up another issue and reference this issue in it.
