### ISSUE TITLE
USER ISSUE: Incorrect text position on some cases.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7991]
**Version:** 0.7.5.0 beta staging-589c887f
If table is not centered - text position wrong.
(Applies to all not centered signs)
![20180608035604_1](https://user-images.githubusercontent.com/4980243/41133597-87ef221e-6ad0-11e8-98de-0032a45a6c3d.jpg)
![20180608035619_1](https://user-images.githubusercontent.com/4980243/41133599-88174244-6ad0-11e8-8854-5170a0550ad4.jpg)

**Comment by elfl0rd** [comment]
Looks fixed in 0.7.5.0 beta staging-945f48a0

**Comment by keegan-o** [comment]
Sign issues should be fixed now for 7.6
