### ISSUE TITLE
[7.5.0] Currency Exchange UI issue with dropdown menu

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#7992]
Version: 0.7.5.0-beta-staging-589c887f (bleeding edge)
Currency Exchange has UI issues - place down a Currency Exchange and try to use it's dropdowns.
![Video Example](https://thumbs.gfycat.com/AdventurousCheeryBufflehead-size_restricted.gif)
[Higher Quality](https://gfycat.com/AdventurousCheeryBufflehead)

Just in case, I currently have multiple currencies on the testmap:
![Exchange issue](https://user-images.githubusercontent.com/26847645/41135126-8356bd90-6aa6-11e8-9e49-94ef9cb9adec.png)

**Comment by johnkslg** [comment]
Good find thank you, will fix

**Comment by johnkslg** [comment]
Fixed!
