### ISSUE TITLE
Can't grant cart permissions in a contract

### ISSUE THREAD

**Issue by Argent47** [StrangeLoopGames/EcoIssues#7993]
I tried to make a contract that grants the accepter permission to use my cart for the duration, but I can't post the job unless the cart's authentication type is set to "Whitelist". There is no way to set a cart's authentication type on the deed or the cart object itself.

![authfail](https://user-images.githubusercontent.com/40051115/41139669-fa0c80a4-6a9d-11e8-81b9-0f825ed3ee85.jpg)

**Comment by johnkslg** [comment]
Marjie when you update authentication can you take a look at this (or pass back to me)

**Comment by MarjieAVolk** [comment]
Yeah I think this will just naturally go away with my auth change, since all deeds will be the same.  They will all have a whitelist drop down option.

**Comment by MarjieAVolk** [comment]
Fixed in 7.6 (not the release today, but the next major release after that).  All deeds will have a whitelist option.
