### ISSUE TITLE
[Missing Feature] "Put" command tool tip inoperable for tools (0.7.4.6)

### ISSUE THREAD

**Issue by indie-kaname** [StrangeLoopGames/EcoIssues#7994]
**Issue:** "Put ___ " command at tool tip doesn't function for tools. Confusing/frustrating to player in light of seemingly non-function UX with UI prompt.

**Use Case:** Pictured below, if I'd like to equip a torch to a torch stand quickly, I cannot. I'f I'd like to dump an infrequently used tool into a storage chest quickly (e.g. I don't usually run around with the hoe, only used when farming) without going into a storage container's interface, I cannot.

**Rationale:** UX consistency between "Put ___" command for Items AND tools; immersion--helps get players out of menu interfaces a little bit more.

**Discussion:** I understand [right click] toggles the light on/off, but either there should be a different key, or the UI tool tip message for "Put" should not display. *Suggestion*: Personally, I think it would be advantageous to have a torch stand not interpret a torch as "fuel" (binding it to the torch stand), but start counting against the "durability" counter the Tool already has. This would enable players to hot-swap a torch in and out of the torch stand to inventory tool.
https://github.com/StrangeLoopGames/EcoSuggestions/issues/397

**Minor Aside:** As the Torch tool cannot stack "Put Torch-*es*" is errata 
![put command](https://user-images.githubusercontent.com/26205872/41164169-bfc70e64-6af7-11e8-884b-e9a90e767fa2.jpg)

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/7240

**Comment by SlayksWood** [comment]
move to #11979
