### ISSUE TITLE
[0.7.4.6]Fractional numbers and stores

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#7995]
I can only put dots instead of commas while setting up the price in the in-game store, which reverts itself to an integer-like number after i'll leave the plot, making me unable to put up any kinds of a fractional numbers in it (0.2, 0.02 etc). Tried to Ctrl+C, Ctrl+V alredy, it just ignores the comma and brings 02 in the list. Basically it just keeps resetting me back to full numbers. I've seen some of the players to be able to do such thing, but like 10-20% of players i've met do have such of an issue. Some people do get reset from 0.15 to 15. Any suggestions?

**Comment by HetNeSS** [comment]
![20180608210520_1](https://user-images.githubusercontent.com/18286472/41168736-4f98bb74-6b60-11e8-9226-eec90fe66831.jpg)
Had set up the prices and left the house. Killed a turkey, bought a charred fish, returned back, prices are gone
![20180608210843_1](https://user-images.githubusercontent.com/18286472/41168763-5de65c22-6b60-11e8-848d-282771d88618.jpg)
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2085134/output_log.txt)

**Comment by johnkslg** [comment]
Fixed!

**Comment by HetNeSS** [comment]
omg i love you
