### ISSUE TITLE
Chunk thread exception when disconnecting and reconnecting (7.6 staging)

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7998]
Made it freeze on 'Entering World' when I tried to reconnect.  221 of these exceptions in Unity>:

MissingReferenceException: The object of type 'GameObject' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.GameObject.GetComponent[T] () (at C:/buildslave/unity/build/artifacts/generated/common/runtime/GameObjectBindings.gen.cs:38)
ChunkRenderer+CombinedChunkGroup.Combine (UnityEngine.Rendering.ShadowCastingMode shadowCastMode) (at Assets/VoxelEngine/Core/ChunkRenderer.cs:604)
ChunkRenderer.UpdateChunkCombos (ChunkRender chunk, System.Collections.Generic.Dictionary`2[TKey,TValue] batchedInfos) (at Assets/VoxelEngine/Core/ChunkRenderer.cs:751)
ChunkRenderer.ApplyBuiltMesh () (at Assets/VoxelEngine/Core/ChunkRenderer.cs:939)
ChunkRenderer+ChunkJobQueue.ProcessFinishedJob (ChunkRenderer job) (at Assets/VoxelEngine/Core/ChunkRenderer.cs:399)
StaticChunkUpdate.Update () (at Assets/VoxelEngine/Core/StaticChunkUpdate.cs:73)

Other exceptions I had:

NullReferenceException
PooledObjectExtensions.ReturnToPool (UnityEngine.GameObject gameObject) (at Assets/VoxelEngine/Utils/PooledObjectExtensions.cs:20)
PooledObjectExtensions.ReturnToPool (UnityEngine.GameObject gameObject) (at Assets/VoxelEngine/Utils/PooledObjectExtensions.cs:20)
MapConfig.OnDisable () (at Assets/VoxelEngine/Core/MapConfig.cs:187)
UnityEngine.Object:Destroy(Object)
GenericClient`1:OnDisconnect() (at Assets/Scripts/Networking/GenericClient.cs:84)
NetworkManager:OnDisconnected() (at Assets/Scripts/Networking/NetworkManager.cs:357)
NetworkManager:Update() (at Assets/Scripts/Networking/NetworkManager.cs:401)

And:
NullReferenceException: Object reference not set to an instance of an object
Player.get_NetObject () (at Assets/Scripts/Player/Player.cs:40)
MinimapUI.OnDisable () (at Assets/UI/Scripts/MinimapUI/MinimapUI.cs:324)
UnityEngine.Object:Destroy(Object)
UI.UIManager:Destroy(GameObject) (at Assets/UI/Scripts/Manager/UIManager.cs:202)
UI.UIManager:CloseAll() (at Assets/UI/Scripts/Manager/UIManager.cs:237)
Player:OnDestroy() (at Assets/Scripts/Player/Player.cs:108)

**Comment by metachronism** [comment]
cant repro this in 7.6 or current master
