### ISSUE TITLE
[7.5.0] Sign text offset is wrong

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8000]
Sign text is way off.
![unknown](https://user-images.githubusercontent.com/35509188/41179736-9547dcbc-6b20-11e8-8f42-ba1ce74758fa.png)

![](https://cdn.discordapp.com/attachments/326481806138408970/454744760381603850/unknown.png)

![](https://cdn.discordapp.com/attachments/326481806138408970/454743861038940170/unknown.png)

**Comment by rachaelfosner** [comment]
Updated with correct placing for the text.
