### ISSUE TITLE
ContinueUI won't work without a connection to the master server

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#8003]

**Comment by indie-kaname** [comment]
I believe I am having this issue too for Single Player. "Continue" sequence hangs somewhere at or in "Connecting" (displays briefly then "Connecting" text hangs, gear spins, but program becomes unresponsive requiring forced exit). Can load into SP game perfectly, consistently if I hit "Load" though. 

Let me know if I can provide a file for debug purposes at all.

**Comment by metachronism** [comment]
marjie already updated/fixed this
