### ISSUE TITLE
[Bug-GFX] Flowing Water adjacent to beveled dirt block displays artifact (0.7.4.6)

### ISSUE THREAD

**Issue by indie-kaname** [StrangeLoopGames/EcoIssues#8004]
**Issue:** flowing water displays improperly (without angle) in beveled dirt blocks next to a flowing water block

**Reproducability:** still present when left, disconnected, and quit game.

**Expected Behavior:** flowing water mesh in beveled dirt block shares same angle and height with adjacent flowing water block.

**Current Behavior:**
![water artifact](https://user-images.githubusercontent.com/26205872/41184302-a2077eb4-6b3c-11e8-930b-9fb1d56595fb.png)

**Comment by metachronism** [comment]
dupe
