### ISSUE TITLE
[Bug] "Continue" sequence hangs on/during "Connect" to Single Player Map (0.7.4.6)

### ISSUE THREAD

**Issue by indie-kaname** [StrangeLoopGames/EcoIssues#8005]
**Issue:** Upon "Continue" for Single Player, sequence hangs at "Connect" failing to continue the sequence and becoming unresponsive. Requires [alt]+[f4].

**Work around:** Utilizing "Load" from main menu successfully launches game without error.

**Current Behavior**: during sequence "Connecting" text displays on screen very briefly, but vanishes, leaving hung spinning gear, but otherwise unresponsive program. When using "Load" however, save time and welcome messages seem to indicate the local server instance spun up. Seemingly a client issue.

**Expected Behavior:** "Continue" loads into last game without a hiccup.

Forked from #8003

**Comment by metachronism** [comment]
closing to consolidate into #7152
