### ISSUE TITLE
Feature: Eco VR

### ISSUE THREAD

**Issue by MaxInertia** [StrangeLoopGames/EcoIssues#8006]
This is a question along with a feature request.

What is the estimated difficulty of allowing users with VR headsets (such as the Oculus Rift and Vive) to utilize the headsets in Eco? and has this been considered?

I just recently acquired an Oculus which is why I ask. I'd love to be able to play Eco with it!

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#417
