### ISSUE TITLE
Shop price issue with decimals

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8007]
When a price is configure with decimals (e.g. 1.5 credits), at the customers view there is no decimal separator so the price looks like 15 credits. (see attachted screenshots)

The Eco-client ist configured with german language und it runs on a Windows 10 System configured with english regional settings.

![pricewithdecimals2](https://user-images.githubusercontent.com/22961978/41185447-b44b5108-6b88-11e8-9817-4d2c849a8008.png)

![pricewithdecimals1](https://user-images.githubusercontent.com/22961978/41185448-b690364a-6b88-11e8-9699-73568a31a0a0.png)

**Comment by johnkslg** [comment]
Fixed!
