### ISSUE TITLE
USER ISSUE: Ramp disappearing in own territory: Invisible, not functioning as ramp 

### ISSUE THREAD

**Issue by fox19** [StrangeLoopGames/EcoIssues#8009]
**Version:** 0.7.4.6 beta

**Steps to Reproduce:**
1. Dirt ramp placed (long time ago, own territory)
2. Dirt ramp disappeared: Not functioning as ramp and invisible, no actions by players with rights to property

**Expected behavior:**
1.) ramp existing
2.) building of new ramp possible

**Actual behavior:**
1.) ramp invisible
2.) No use via carts and other vehicles possible
3.) Building in area of the ramp blocked: no more building/replacing 

details>
<summary>Log File</summary>(...previous log truncated...)

a14c2a2baa3940d0969f235d02df648a>:0 
  at MinimapUI.OnDisable () [0x00025] in <a14c2a2baa3940d0969f235d02df648a>:0 
UnityEngine.Object:Destroy(Object, Single)
UnityEngine.Object:Destroy(Object)
UI.UIManager:Destroy(GameObject)
UI.UIManager:CloseAll()
Player:OnDestroy()
 
(Filename: <a14c2a2baa3940d0969f235d02df648a> Line: 0)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filen

**Comment by SeanAtr0n** [comment]
could you send us your game save file and location of the ramp?

**Comment by fox19** [comment]
Hello Sean,

enclosed you'll find the save file. Items already affected are:

Dirt Ramps:
- 107, 583
- 103, 578
- 103, 583
- 103, 587

Mortar Stone: 106, 584 (area blocked while building)
Stockpile: 103, 586
Pump Jack: 101, 587

**Important additional information**

The "Bermuda Effect" has spread. See also issue #8022 posted concerning it. First problems with dirt ramps came up while I was building the room where the Pump Jacks and the Combustion Generator are in. Except one mortar stone and the ramps causing problems I could still build the room.

Later on, I put a stockpile on the roof of the oil production room which immediately got invisible. Going further in time I picked up one Pump Jack in order to turn it around and put it at the same location. This was the moment the Pump Jack got invisible same as all items listed before.

**Questions:**

To what extend can you fix the bug?
--> Can you stop the "Bermuda Effect" from spreading and replace the items?
--> How should I proceed playing further on? Should I stop moving or picking up any items in my housing/production area so I can keep using them?


Thanks for your efforts

Attached: save file
[DefaultWorld.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2098990/DefaultWorld.zip)

**Comment by fox19** [comment]
Any conclusions so far? Is the information given by me sufficient? :)

**Comment by babam93** [comment]
Got the same issue on our server. Nothing helps neather a restart a delete the part via worldedit, the bermuda effect is already there....

**Comment by SlayksWood** [comment]
I assume this issue is no longer occurring"

**Comment by SlayksWood** [comment]
I assume this issue is no longer occurring"
