### ISSUE TITLE
Crash Client 7.4.6 - after picking up cart

### ISSUE THREAD

**Issue by pmeyerson** [StrangeLoopGames/EcoIssues#8011]
new 7.4.6 world, after picking up cart and moving a few steps game crashed.
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2087238/error.log)

I also have a .dmp file, not sure how to attach.  Thanks.

**Comment by GophTheGreat** [comment]
You should be able to put it in a .zip and attach it directly to the post by simply dragging and dropping, if I recall correctly.

**Comment by SlayksWood** [comment]
Thank you for report. 
Closing as not reproducable at latest builds.
