### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by KytaSaeso** [StrangeLoopGames/EcoIssues#8015]
**Version:** 0.7.4.6 beta

**Steps to Reproduce:**
Try to Login

**Expected behavior:**
Logged in

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out</size>
```

<details>
<summary>Log File</summary>Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1060 6GB (ID=0x1c06)
    Vendor:   NVIDIA
    VRAM:     6052 MB
    Driver:   24.21.13.9731
Begin MonoManager ReloadAssembly
- Completed reload, in  0.138 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.133163 ms
Setting up 3 worker threads for Enlighten.
  Thread -> id: 32b4 -> priority: 1 
  Thread -> id: 32d4 -> priority: 1 
  Thread -> id: ef0 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.6 beta
25 May 2018 02:12
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[22:07] Disconnected from server.Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

</details>

**Comment by GophTheGreat** [comment]
Was confirmed to be a Steam issue. Closing.
