### ISSUE TITLE
USER ISSUE: Login info could info could not be verified.

### ISSUE THREAD

**Issue by fox19** [StrangeLoopGames/EcoIssues#8016]
**Version:** 0.7.4.6 beta

**Steps to Reproduce:**
1.) Start Eco via Steam
2.) Continue

**Expected behavior:**
connect to server

**Actual behavior:**
Login info could info could not be verified. Our auth servers may be down. The operation has timed out

<details>
<summary>Log File</summary>Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 750 Ti (ID=0x1380)
    Vendor:   NVIDIA
    VRAM:     1967 MB
    Driver:   24.21.13.9764
Begin MonoManager ReloadAssembly
- Completed reload, in  0.136 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.260844 ms
Setting up 3 worker threads for Enlighten.
  Thread -> id: 1320 -> priority: 1 
  Thread -> id: 1a80 -> priority: 1 
  Thread -> id: 13e0 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.6 beta
Freitag, 25. Mai 2018 03:12
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> Connecting
 
(Filename: C:

**Comment by Serynthara** [comment]
Same problem here.

**Comment by GophTheGreat** [comment]
Was confirmed to be a Steam issue. Closing.
