### ISSUE TITLE
Skill Tree for Masonry unobtainable.

### ISSUE THREAD

**Issue by antman00** [StrangeLoopGames/EcoIssues#802]
Server, Client: Both 0.4.2

OS/Web Browser: Windows 8.1 x64

Detailed Description of Issue:
Research for Masonry is successful. Scroll generation successful. Unlock of the skill tree never happens

Reproducible: Yes
How difficult is it to reproduce: Very easy

Steps to reproduce bug/issue: Right click masonry scroll and confirmed New skill was learned. Check skills  and tree for masonry never appears

Additional Comments:
is 0.5 the answer. please let me know so I can stop playing this version.

Client Version: 0.4.2

**Comment by metachronism** [comment]
This is fixed in alpha 5

**Comment by antman00** [comment]
Currently standing up an alpha 5 server and will re-validate
