### ISSUE TITLE
SUGGESTION Pick-only mode for excavator

### ISSUE THREAD

**Issue by matias-b** [StrangeLoopGames/EcoIssues#8020]
Would be nice to have a mode where the excavator only picks up already destroyed stone/ores. It's a bit hard to handle and when trying to pickup items it destroys even more.
I suggest keeping the current behaviour but adding another option to only pick items and not destroy.

**Comment by elfl0rd** [comment]
Love this as 3rd mode.
Drive\Pick\Dig

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#416
