### ISSUE TITLE
Can we get a simplified Hub for mods?

### ISSUE THREAD

**Issue by AlaskanBootyMeat** [StrangeLoopGames/EcoIssues#8021]
As titled suggests, trying to install a mod?  Take a left turn here to get this, oh wheres the download link? You have to back track to the other page and find where the download link is first, then go back and take that left turn to find out its A RIGHT TURN! omfg

**Comment by GophTheGreat** [comment]
Have you tried this? https://eco.mod.io/

**Comment by AlaskanBootyMeat** [comment]
Yet another website to sign up for an account on. Im talking about Steam, or ingame where you click something and it downloads and you restart your client.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#415
