### ISSUE TITLE
USER ISSUE: Steam Tractor Sower - floating

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8023]
**Version:** 0.7.5.0 beta staging-589c887f
See, sower is not correctly attached, they floating :P
![20180611163344_1](https://user-images.githubusercontent.com/4980243/41240929-54e5e48a-6da4-11e8-8ab9-1ded0dadc4b1.jpg)

**Comment by SeanAtr0n** [comment]
think keegan fixed this

**Comment by elfl0rd** [comment]
No. 7.6.1 @SeanAtr0n @keegan-o 
![20180719035539_1](https://user-images.githubusercontent.com/4980243/42915304-c5fa3948-8b07-11e8-93e9-15a7d2fd21fe.jpg)

**Comment by keegan-o** [comment]
Fixed in master. (Will be in whatever patch is after 7.7)
