### ISSUE TITLE
"Access Violation" on CLIENTS played on this world.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8024]
Server works fine. Clients receive "Access Violation" after ~5-10m of active play.
[Crash_2018-06-11_181846.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2090633/Crash_2018-06-11_181846.zip)
https://www.dropbox.com/s/d76jqxtaozr37fn/Access%20Violation.zip?dl=1

p.s.
And additional bug, if you play on singleplayer and client crashed - server still working.

**Comment by elfl0rd** [comment]
Maybe it's because of the convertation, because the world is old, but the behavior is still strange.

**Comment by metachronism** [comment]
was this on 7.5 staging?  there was a crash with that, should be fixed now

**Comment by elfl0rd** [comment]
Yes, latest staging.
For me - fixed by installing latest .net (4.7.2)
