### ISSUE TITLE
Single player game freezing with Red Disconnection icon 

### ISSUE THREAD

**Issue by markuk98** [StrangeLoopGames/EcoIssues#8028]
My single player game freezes regularly with a disconnected icon down the bottom right, I understand you are aware of this problem but I wanted to report my observations. 

I have been playing for around 2 hours with out a single disconnection however as soon as I fire up the Blast Furnace I get 2 in 10 mins.

I have also noticed that the server time continues to run. The game doesn't actually freeze, just the players ability to interact with the world. 

Hope this information helps. Also if your having the same issues try turning off all your blast furnaces and see if it fixes the problem. 

All the best. PS Great game, keep up development.

**Comment by SeanAtr0n** [comment]
Could you play until you get the disconnects again and then send us your log file from here?

`%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

There might be some exceptions that could help explain the issue

**Comment by markuk98** [comment]
Hi Sean,

It appears to be related to air pollution. I have just built a Concrete mixer and it is doing it with that too. I disconnected during a pause so the details should be no more than a few seconds back. After starting the mix, I had two maybe three pauses.

The file is 33mb so won’t let me email. OneDrive link ok?

https://1drv.ms/f/s!ArCvF-W75MxapPp1zA7il-xe6VFAwA

Mark.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by BlazeGuy2** [comment]
@markuk98 Can you send the file again, preferably in google drive?  Reopen it when it's sent or open a new issue with this one referenced and I can help you push this along.

**Comment by elfl0rd** [comment]
@BlazeGuy2 only team can reopen issues :)
