### ISSUE TITLE
Server Startup error StackOver

### ISSUE THREAD

**Issue by antman00** [StrangeLoopGames/EcoIssues#803]
initializing StorageManager.....

causes a StackOverflowException

Windows 8 x64 running Server 0.5

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	EcoServer.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	5813e7da
  Problem Signature 04:	System.Core
  Problem Signature 05:	4.0.30319.34209
  Problem Signature 06:	53489a70
  Problem Signature 07:	11a0
  Problem Signature 08:	0
  Problem Signature 09:	System.StackOverflowException
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	c236
  Additional Information 2:	c236a666a0092e02c12d1c2311d5b408
  Additional Information 3:	58c5
  Additional Information 4:	58c5ac85ce86fee482a93848aedee4ef

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\WINDOWS\system32\en-US\erofflps.txt

**Comment by metachronism** [comment]
This is fixed with the latest version of .net

**Comment by antman00** [comment]
Ok let me make sure I am at the latest version and re-validate.

**Comment by antman00** [comment]
I have updated both .net 3.5 and 4.5 to the latest level windows update as to offer but still same error. Is there a specific hotfix\patch I should be looking for? Anyone provide KB article that has the update I should install?

**Comment by metachronism** [comment]
4.6.2 is the latest version of .net, have you tried that version?
