### ISSUE TITLE
Need to configure more items to display on avatars

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8030]
![image](https://user-images.githubusercontent.com/3536496/41258252-6a2a1e76-6d84-11e8-9e3e-2e02ec639e87.png)
Bonus points if you can get a chainsaw in there somehow.

**Comment by metachronism** [comment]
this shouldnt be a programmer task, fwiw
system is mostly setup for artists to use this

**Comment by johnkslg** [comment]
Giving to keegan then
