### ISSUE TITLE
deep hole

### ISSUE THREAD

**Issue by Robonaria** [StrangeLoopGames/EcoIssues#8031]
on my server are some holes or some places of the landscape disappeared 
https://steamuserimages-a.akamaihd.net/ugc/916927123557780843/9FB42EFA2B4B7892984134E7ABCD620C43C5D260/

**Comment by metachronism** [comment]
closing as dupe of other chunk build issues (not yet fixed)

**Comment by enexusde** [comment]
@metachronism  Please link dupe issue. 

Have same issue here:

![image](https://user-images.githubusercontent.com/6880636/107034415-fa8a2b80-67b6-11eb-8bb6-d52a78165df5.png)
