### ISSUE TITLE
[7.6.0] Blocks don't load after longer running / hunting tour

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8032]
Often when  I'm on longer "hunting tour", parts of the world will not load. Assume that occurs when a player is running long distances through the world…
![20180612004040_1](https://user-images.githubusercontent.com/22961978/41261014-24b3c4cc-6dda-11e8-8e22-a9d7afe29f10.jpg)

**Comment by Voosle** [comment]
I found that ECO.exe takes 8GB of private memory and 15 GB of virtual memory. My maschine 'only' have 8GB pysical RAM. That may cause going down FPS and world load errors...
So maybe a limitation is a good idea. Or to force GC (but, if I stand still and wait some minutes, no memory will been released)?

**Comment by metachronism** [comment]
we wont be able to tackle this until upgrading to unity 2018, dropping priority for now

**Comment by Voosle** [comment]
This issue still exists in 7.6.0. I found it again today.

**Comment by elfl0rd** [comment]
okay, looks fixed in master.
