### ISSUE TITLE
[7.5.0] Currency Exchange UI issue: Holdings dropdown menu order

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#8034]
Version 7.5.0 e3d24b4a [ 06/11 bleeding edge ]

#7992 was fixed, but there's another UI issue on the Currency Exchange interface:
The headers for the Holdings and its dropbox members are in the wrong spots (should be Min-Currency-Max dropbox order, but it's at Min-Max-Currency)

![image](https://user-images.githubusercontent.com/26847645/41265471-d23ff3c0-6dc8-11e8-9305-ab6f59e6d72a.png)

Thanks!

**Comment by johnkslg** [comment]
Fixed
