### ISSUE TITLE
[7.5.0] Store Prices and Decimals not inputting correctly in stores

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#8035]
Version 7.5.0 e3d24b4a [ 06/11 bleeding edge ]

Although decimal pricing now works in general, my keyboard and regional settings are set to PT-BR (Brazilian Portuguese).
My regional-settings separator is a comma, and I cannot input a comma in the Store price textfield.

Using a dot separator will also not work in any way - clicking the UI, pressing enter, or closing the UI with a price using a Dot will simply remove the dot and make a 23.5 price into 235, for example.

The common workaround of holding CTRL and clicking the Plus and Minus to set prices will still work, and prices can then be entered normally.

To illustrate a bit:
![Currency Exchange issue](https://thumbs.gfycat.com/ImprobableEachAfricanelephant-size_restricted.gif)
[Higher Quality](https://gfycat.com/gifs/detail/ImprobableEachAfricanelephant)

Thanks!

**Comment by johnkslg** [comment]
Fixed!
