### ISSUE TITLE
[Bug] Zeroed Out species (incl. rice) upon Single Player default world gen (0.7.4.5/.6)

### ISSUE THREAD

**Issue by indie-kaname** [StrangeLoopGames/EcoIssues#8036]
**Issue;** I discussed this with @Pam on #support but apparently the issue with worlds generating without species present should have been fixed. She indicated it was strange that it happened to me with multiple species, but **ESPECIALLY** with rice. (I guess the team spent a not-insignificant amount of time specifically on rice generating into world, sorry!). She said it may or may not be related to gaping holes generated in hills, terrain, and cliff faces.

**Actual behavior:** several plant species were missing on my new world generated on or sometime after May 17th (when I purchased the game). Missing are: Creosote, Bullrush, Pitcher Plant, Saguaro, and Rice. (Of note, the screenshot indicates 3x Rice; I generated rice "seed" via console command and planted them).

**Expected Behavior:** world gens without missing Rice (and maybe without missing some of the others?) Don't know what species, if any, have creosote, bullrush, pitcher plants, or saguaro in their food web.
![species](https://user-images.githubusercontent.com/26205872/41268598-34ed822c-6dbe-11e8-87f0-22ad17978a4d.png)

**Comment by craig-jong** [comment]
Any chance you can pass me a world save where nothing generated? There are a few things I'd like to check out.

**Comment by craig-jong** [comment]
It looks like you're missing the wetlands biome entirely which, since worldgen is entirely random, is possible.

We can make that setting progressively more aggressive, but at some point plants we'll be force spawning in plants that die anyway. I'll add that as an option, but otherwise completely fixing this issue is going to have to wait for a world generation update.

**Comment by indie-kaname** [comment]
Hey, I missed the other notification, sorry. What's the best way to pass the world saves? Google Drive link? I understand if it isn't feasible to fix at present, just wanted to be sure to pass the info along.

**Comment by craig-jong** [comment]
Yea, however you can send the game.eco is fine. I think github will let you upload some files directly, but I could be wrong. If nothing else, you can email it to me at Craig@strangeloopgames.com.

**Comment by indie-kaname** [comment]
emailed. the eco file type and the db file aren't supported uploads by github (at least not in issue comments)

**Comment by craig-jong** [comment]
Thanks. Got the email and I'll take a look as soon as I got time. I'm going to drop the priority of this bug for now.

**Comment by indie-kaname** [comment]
Thanks for the update. No qualms with the priority change, makes sense. Hopefully you find something useful!

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/9955
