### ISSUE TITLE
[7.5.0] Economy Viewer issues - sorting and updating

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#8037]
Version 7.5.0 e3d24b4a [ 06/11 bleeding edge ]

As I do not know the intented behavior for the Economy Viewer and it's features, I'll bring up a few points:

1) Economy Viewer updates in realtime but does not sort in realtime: the player has to roll all the way down the list to see new entries. This is what I'd expect with the new changes, but I don't know if that's the intended behavior?
_That does not apply to the /spawneconomy command - executing the command with an open Economy Viewer will not update it._

2) When changing a Store Currency to Use, existing offers on the Viewer won't update. So you can see things such as:
![image](https://user-images.githubusercontent.com/26847645/41274983-c961dcd2-6df5-11e8-8959-029b8d862c66.png)
StoreX3 uses GabeuxCash, but the Currencies shown in the Economy Viewer didn't update (I changed the Store's Currency each time I added one of the entries). 
Reconnecting to the server doesn't fix it - only restarting the server reacquires the list with updated, correct, currencies.

3) Sorting by Stores doesn't seem to work. Usually the sorting in the Viewer is by ascending/descending numerical or alphabetical order. I'd expect Alphabetical sort on the Stores column, but I cannot determine which criteria the Store sort is using.

Thanks!

**Comment by johnkslg** [comment]
1. Fixed!
2. Fixed!
3. Fixed!

**Comment by johnkslg** [comment]
Adding new entries still puts them at the bottom, that's expected.
