### ISSUE TITLE
USER ISSUE: elevator enter problem

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8039]
**Version:** 0.7.5.0 beta staging-e3d24b4a
You cannot enter to elevator without jump if you have sand or dirt under it.
https://youtu.be/7Iy0OMBrUBQ

**Comment by elfl0rd** [comment]
as i see - these is minor issue, player still can place hard block to enter to elevator.

**Comment by SeanAtr0n** [comment]
was fixed in 7.5.1
