### ISSUE TITLE
Birdsong error message

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#804]
Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (BirdsongSfx(Clone)).

**Comment by metachronism** [comment]
also on

Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (CricketSfx(Clone)).

and 

Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (OwlSfx(Clone)).

**Comment by Nanders** [comment]
Fixed in SVN
