### ISSUE TITLE
Broken "connect" (player action related)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8041]
If player _clean_ recentServers.eco (not remove file, only empty it)
Connect becomes this
![default](https://user-images.githubusercontent.com/4980243/41307433-cf5e9dfa-6e81-11e8-86e9-58ab71a36fcf.png)

reproducible on 7.4 and 7.5

@MarjieAVolk

**Comment by MarjieAVolk** [comment]
Ahhh, you tampered with the file, not just deleted it 🤔 Okay, that's not quite as urgent as I thought.  But I should be able to add in some safety for a badly formatted file.

**Comment by elfl0rd** [comment]
yeah, in configs these needed too :)
