### ISSUE TITLE
Saved recents with a port different from the default don't get loaded

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#8044]
1. Change game port for local server
2. Direct connect to local server using new port - connection succeeds
3. Exit world and go back to join screen
4. The 'recents' listing for the local server gets an empty line (expected while waiting for a response), but never gets the response it needs to fill out the line

![image](https://user-images.githubusercontent.com/23460210/41318674-f8420ccc-6e4d-11e8-93d1-0f60a8fe5c0e.png)

I debugged this a bit, and it looks like the client is calling NetworkManager.obj.client.GetServerInfo(favorite.Address, favorite.GamePort); with what looks like the correct address and game port.  Haven't dug into it more than that.

**Comment by elfl0rd** [comment]
LAN servers too :)

**Comment by MarjieAVolk** [comment]
The LAN section only scans for servers on the default port.  Unfortunately I think that's just how it's got to be, since that's how the LAN scanning works.

**Comment by elfl0rd** [comment]
Sounds as "no changes planned" :(

**Comment by elfl0rd** [comment]
"LAN too" - you can make (localhosted) server with specific port, and can make LAN server with specific port.
But they available, visiple trough MS, but info is not loaded.

**Comment by elfl0rd** [comment]
And yes, i understand about _LAN_ section is not find server vith port not 3000.
But LAN server with changed port is not loaded in recent too :(

**Comment by MarjieAVolk** [comment]
Oh, yes that I will try to fix.
