### ISSUE TITLE
Local Crash-Files

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8045]
Just found this crash files. Don't know what I did 2 weeks ago…
But may be it can help.
[Crash_2018-05-31_202050.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2096179/Crash_2018-05-31_202050.zip)

**Comment by Voosle** [comment]
@elfl0rd Why thumbs down? Should I do not send this file?

**Comment by elfl0rd** [comment]
No information about it.

**Comment by MarjieAVolk** [comment]
Okay, it's one of these "UnityPlayer.dll caused an Access Violation (0xc0000005)".  We've had reports of these off and on, we've been assuming they were bugs in Unity.  Just recently we started seeing a whole bunch of them in our bleeding edge builds, so now we are finally going to look at them more it seems.

**Comment by elfl0rd** [comment]
@MarjieAVolk perfect... These errors make bleeding edge unplayable to me.
And check these toxic save too, please :) https://github.com/StrangeLoopGames/EcoIssues/issues/8024

**Comment by elfl0rd** [comment]
And my old and closed issue about Access Violation
https://github.com/StrangeLoopGames/EcoIssues/issues/7891

**Comment by BlazeGuy2** [comment]
Issue seems to be crane ropes that interact with the terrain.  Fixed issue and crash rate has dropped.
