### ISSUE TITLE
Minor graphical: Selecting Claim Flags on Third person

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#8049]
Version: Bleeding Edge 945f48a0 [06 / 13]

When on third person, selecting Claim Flags won't bring up the property overlay.
Going into first person, selecting Claim Flags, then going into third person shows it properly.

![Issue](https://thumbs.gfycat.com/FelineDeliriousKakarikis-size_restricted.gif)
[Higher Quality](https://gfycat.com/FelineDeliriousKakarikis)

**Comment by SeanAtr0n** [comment]
was fixed in 7.7
