### ISSUE TITLE
[7.5.0] Using configured and unclaimed Currency Exchange causes throw

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#8050]
Version: Bleeding Edge 945f48a0 [06 / 13]

**Steps to reproduce:**
1. Claim a Currency Exchange and set offers
2. Unclaim it
3. Holdings will be removed but offers will stay in place; 'force' a purchase

![Issue](https://thumbs.gfycat.com/ElderlyEvilEskimodog-size_restricted.gif)
[Higher Quality](https://gfycat.com/ElderlyEvilEskimodog)

**Comment by BlazeGuy2** [comment]
Fixed this bug, closing now.
