### ISSUE TITLE
Repair Table has Credit tab but does not allow setting of fees

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#8051]
Version: Bleeding Edge 945f48a0 [06 / 13]
No UI components on Repair Table Credit tab:

![image](https://user-images.githubusercontent.com/26847645/41386739-62b74c5a-6f59-11e8-9807-2207fbbd0449.png)

PS: Only happens with Repair Table

**Comment by D3nnis3n** [comment]
Fixed a while ago.
