### ISSUE TITLE
Some Memory Exceptions at Server (V7.4.6)

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8052]
[ServerCrash AggregateException 06121838.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2100473/ServerCrash.AggregateException.06121838.zip)

**Comment by metachronism** [comment]
world layers

**Comment by Voosle** [comment]
That did not came up the last weeks. We are on 7.6.0 today. So I think, this one can be closed.
