### ISSUE TITLE
[7.5.0] Economy Viewer shows Offers of disabled Stores

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#8053]
Version: Bleeding Edge 945f48a0 [06 / 13]

With the new changes to the Economy Viewer, if a Store has no stock in a given offer, its Selling Order is omitted. If a Buying Order has reached its set Maximum stock, the buy order will be omitted.
However, when a Store is unclaimed or disabled due to broken rooms, its offers still show up in the viewer:

![image](https://user-images.githubusercontent.com/26847645/41386896-60b1770e-6f5a-11e8-97cf-c5808e817b2f.png)

PS : I do not know if still showing offers by disabled Stores is intended. If it is, take this as a suggestion! :) Letting players know a store is broken/disabled/unclaimed via Econ Viewer would be neat!

**Comment by SlayksWood** [comment]
Still an issue.
![image](https://user-images.githubusercontent.com/45708377/71413077-9a433380-2661-11ea-9ad5-c9dcce09f7cc.png)

**Comment by SlayksWood** [comment]
Something else needs to be done with stores to which you do not have authorization access.

**Comment by IcedForge** [comment]
Disabled stores hide their offers on the Economy Viewer, and unauthorized are marked as red as well.
Would it be possible to add some form of auto hide feature for this? And maybe have a filter option somewhere to show unauthorized stores?

So you cannot see them by default but you can turn it visible to check prices f.ex and compare?
