### ISSUE TITLE
USER ISSUE: wrong position of `offset signs`.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8055]
**Version:** 0.7.5.0 beta staging-945f48a0
![20180614131259_1](https://user-images.githubusercontent.com/4980243/41406445-18d6fb4a-6fd5-11e8-916e-d661e367ec37.jpg)
![20180614131310_1](https://user-images.githubusercontent.com/4980243/41406446-1904d542-6fd5-11e8-93b3-686c93d91791.jpg)
![20180614132407_1](https://user-images.githubusercontent.com/4980243/41406860-4d770b00-6fd6-11e8-9d0c-2ddad343fbdc.jpg)

Looks as result of fixing https://github.com/StrangeLoopGames/EcoIssues/issues/7991

**Comment by elfl0rd** [comment]
In stable 0.7.5.0 now, good work!

**Comment by elfl0rd** [comment]
Still in 7.5.1

**Comment by elfl0rd** [comment]
fixed in 7.6

**Comment by MarjieAVolk** [comment]
Alright, fixed

**Comment by Voosle** [comment]
hmmm… in 7.6.1: 
![image](https://user-images.githubusercontent.com/22961978/42848988-c82bac1a-8a21-11e8-9a13-d09a56659fda.png)
