### ISSUE TITLE
Skillpoint Bug after Update

### ISSUE THREAD

**Issue by Maexel12** [StrangeLoopGames/EcoIssues#8056]
Dear Developers,

after i updated my Server [14.06.18] i wanted to try something with the Skillpoints. 
In the Picture you can see that i got 250 Points for an Skill where i never put something (you can also see i am at the beginning at the game)

The server i play on is on standart colaboration and the growth rate of plant is increased.

I really like your game so far and wanted to help make the game "bugfriendlier"
If you have any questions, i will answer you.
(sry for my writing, German is my main language)

![20180614130646_1](https://user-images.githubusercontent.com/40266363/41408923-b3dc2792-6fd4-11e8-93f6-b2edc98e0fce.jpg)
![20180614130715_1](https://user-images.githubusercontent.com/40266363/41408924-b4000a22-6fd4-11e8-9eb5-a6aafb3aa917.jpg)
![20180614130729_1](https://user-images.githubusercontent.com/40266363/41408925-b41c27fc-6fd4-11e8-9457-666d8e3f6b94.jpg)

**Comment by craig-jong** [comment]
It appears that you started with a bunch of specialties already learned.

The 250 skillpoints you got back were from the cost it takes to specialize which, once you have over a certain number, is 500 skillpoints.

I'm not sure how you started with every specialty, but I'm going to guess its a mod or the player defaults have been changed on the server you're playing on.
