### ISSUE TITLE
Ramp + solid block placement

### ISSUE THREAD

**Issue by megatronp** [StrangeLoopGames/EcoIssues#8066]
Unable to place any type of solid block against any type of ramp (either side, underneath or on top) on 7.4.7 on either singleplayer or multiplayer.

**Comment by metachronism** [comment]
interaction targeting issue, still relevant as of 7.5.1

**Comment by SeanAtr0n** [comment]
eric fixed w/ ramp blocks

**Comment by SeanAtr0n** [comment]
7.7
