### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Zelebob** [StrangeLoopGames/EcoIssues#8067]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Please enter a name for your world
```

**Comment by BlazeGuy2** [comment]
Need more info for how you reached the bug to help find the bug better.  What it sounds like happened is that when you created a new world, you clicked generate without giving it a name in the name box, causing the issue.
