### ISSUE TITLE
Front Page graphs query dislaying dead data, on fresh server.

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#807]
The Front Page Info query tells which graphs to display on the World Status page.

On a fresh server, it says to display "Humans/Polluting" on the Pollution Status graph.
But when querying for that data, there is an error.

Can you remove that from the Front Page Info query.
So on a fresh server, it does not ask to display anything for Pollution (since there is none yet)

That way, on web side, we can check if the Pollution Status graph is empty, and then hide the graph it is empty.
Currently we check if its empty, but its not because of "Humans/Polluting"

**Comment by johnkslg** [comment]
Disabled those for now.
