### ISSUE TITLE
Need a pass on items that can attach to walls

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8071]
Logs shouldnt attach for example
![image](https://user-images.githubusercontent.com/3536496/41493913-5c91311a-70c1-11e8-930b-f14d9e3cfbe9.png)

**Comment by craig-jong** [comment]
Log physics objects when?

**Comment by SeanAtr0n** [comment]
Could make logs physics i suppose, but then ppl will complain about
![image](https://user-images.githubusercontent.com/774628/41629591-23bcf736-73df-11e8-9304-5968ee5023e0.png)
