### ISSUE TITLE
Can get stuck carrying an item

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8072]
When putting down then picking up lots of logs rapidly, I'm able to get one attached that, when I try to place down, disappears and comes back to my hand.  
![animx](https://user-images.githubusercontent.com/3536496/41494044-0696e6a4-70c3-11e8-9b2b-6141a1c0b19c.gif)

**Comment by SeanAtr0n** [comment]
Fixed in 7.5 with https://github.com/StrangeLoopGames/Eco/pull/2960
