### ISSUE TITLE
Fast digging often catches another block then pointed

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#8073]
If digging with shovel and move the cursor too early away, a totally other block then original pointed is catched. It shouldn't be difficult to mark the pointed block as target when ticked with mouse. The current behavior can be annoying.

**Comment by Nicolausi113** [comment]
I forgot - this happens also with road tool, scythe, maybe others.

**Comment by SeanAtr0n** [comment]
This is intentional, the target is picked during the animation impact

**Comment by Nicolausi113** [comment]
Hmm – if intention is to break fluency…? :(

**Comment by GophTheGreat** [comment]
Not a bug? Closing for now.
