### ISSUE TITLE
Freeze for more than 10 seconds on client version 7.4.7

### ISSUE THREAD

**Issue by aristotel2020** [StrangeLoopGames/EcoIssues#8074]
Hello, I have been playing Eco for a few days now, single player and on multiplayer servers, this problem happens on both, I am running the 7.4.7 version of the client but this problem happened on previous versions as well.
Description: The client freezes for 10-30 seconds randomly, during which the red "disconnected from server" icon appears in the  bottom left of the screen, then resumes normally.
It may be related to atmosphere polluting machines (blast furnace)Here is the output log for less than a minute of game play during which the freeze happened.
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2108027/output_log.txt)
I did not reach flooding levels of pollution on the server, I heard that may cause lag as well.
I'm sorry if this issue has been posted about before.

**Comment by X-ITT** [comment]
Yes, I get massive fps drops while furnace is running.
