### ISSUE TITLE
USER ISSUE: Hitbox shift

### ISSUE THREAD

**Issue by LarsHagemann** [StrangeLoopGames/EcoIssues#8075]
**Version:** 0.7.4.7 beta

**Steps to Reproduce:**
Place two bricks as items next to each other on one square.

**Expected behavior:**
Hitboxes around both bricks.

**Actual behavior:**
Hitbox shifted to neighbouring square.

[Image](https://imgur.com/a/Z1usNMm)

<details>
<summary>Log File</summary>Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 650 (ID=0xfc6)
    Vendor:   NVIDIA
    VRAM:     2007 MB
    Driver:   23.21.13.9135
Begin MonoManager ReloadAssembly
- Completed reload, in  1.595 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.346830 ms
Setting up 2 worker threads for Enlighten.
  Thread -> id: 1b14 -> priority: 1 
  Thread -> id: 3168 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.7 beta
Mittwoch, 13. Juni 2018 21:31
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

</details>

**Comment by SlayksWood** [comment]
Seems fixed
