### ISSUE TITLE
Use Profanity filter to screen names used in game

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8076]
This has come up several times as to why words filtered by the profanity filter are not blocked for use as names.   Many admins adjust the profanity filter for their needs but then have the issue of names being used that are offensive and are words that they have in the profanity filter list.  They would like the profanity filter also filter and block when used as a name.  Steam pretty much allows usage of all words as names and leaves it up to game to block inappropriate and/or offensive names but at this time nothing really blocks names for Eco.  If a word is in the profanity filter it shuld not be allowed as a player name.  This also gives the Admin control over names on their server as they can add to the list as they feel appropriate (or remove as the case maybe).  As I was told by a very nice server owner "If you can't say it in chat you should not have it floating over your head all day to force others to read".

**Comment by gabeux** [comment]
+1! Applying the profanity filters to signs, and adding a separate list so admins can block/filter player names could also be interesting - e.g. people that has names such as "At" or "from", naming themselves with pronouns or articles, can be rather troll-y.
