### ISSUE TITLE
Show error if singleplayer server is not started correctly.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8077]
Current - if singleplayer server not started (crashed, etc) game return player to main menu.
This is confusing behavior, and needed to change.

**Comment by MarjieAVolk** [comment]
Showing a startup error for local worlds should be implemented.  Can you give some more details about the cases where you didn't see an error message?

**Comment by elfl0rd** [comment]
user PC not have correctly installed .net
And ingame - no errors, only see it if directly launch server file.

**Comment by elfl0rd** [comment]
screenshot here - https://github.com/StrangeLoopGames/EcoIssues/issues/8078
