### ISSUE TITLE
USER ISSUE: excavator and skidsteer lost functionality.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8079]
**Version:** 0.7.5.0 beta staging-04eb44af
Partially game breaking.
They both can not pick up stone\ores debris. Only fraction it, not pickup.
![20180617164350_1](https://user-images.githubusercontent.com/4980243/41508481-1bca9570-724e-11e8-84d1-e9f22ec0597a.jpg)
https://youtu.be/8_U4iDYu8hA

**Comment by SeanAtr0n** [comment]
fixed next staging build
