### ISSUE TITLE
Decimals in shop

### ISSUE THREAD

**Issue by Myrhaug** [StrangeLoopGames/EcoIssues#8081]
I see on some reports about decimals is fixed for shops. I tried to write 1.5 as price, and it turns out as 0 credits in economy viewer.
I can only put dot in price column, comma does not want to work. But it still show 0 as price when using decimals.

We are using version 7.4.7
I got europeen keyboard setup (Nordic/Norwegian).

**Comment by BlazeGuy2** [comment]
This was fixed for 7.5.0 on bleeding_edge right now, it will come out in later with the official release.  Reopen if it's still an issue on 7.5.0.

**Comment by madxmat** [comment]
But it is an issue now. Will it be fixed in 7.4.8? Or we need to wait for 7.5?

**Comment by elfl0rd** [comment]
wait 7.5

**Comment by madxmat** [comment]
When?

niedz., 24 cze 2018 o 18:21 użytkownik GDragon <notifications@github.com>
napisał:
