### ISSUE TITLE
Terrain not showing in minimap

### ISSUE THREAD

**Issue by Trylk248** [StrangeLoopGames/EcoIssues#8082]
Nvidia GTX 970, i7 4790, 16 GB DDR3, drivers up-to-date.
![error](https://user-images.githubusercontent.com/12155534/41511770-611a2760-724b-11e8-884b-0238bacceda0.png)

**Comment by SeanAtr0n** [comment]
Does your computer have integrated graphics? Are you sure the game is running on the 970?

**Comment by SeanAtr0n** [comment]
Please send us your log file from
`%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

**Comment by SeanAtr0n** [comment]
Gona close until we get some more info to help debug... please reopen if its still an issue and send us
`%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

**Comment by Trylk248** [comment]
The game runs on my GTX 970. I disabled integrated graphics. The way I got
it to work again is by reinstalling the game again.

Le mar. 19 juin 2018, à 19 h 12, Sean Ater <notifications@github.com> a
écrit :
