### ISSUE TITLE
USER ISSUE: crane flying.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8084]
**Version:** 0.7.5.0 beta staging-04eb44af
Crane flying in air
![20180618101408_1](https://user-images.githubusercontent.com/4980243/41522839-6bbf30e4-72e0-11e8-8275-6b62367a22de.jpg)
@johnkslg

**Comment by keegan-o** [comment]
I fixed this in master, so it will go into 7.6. Should we hotfix this in 7.5? @johnkslg

**Comment by elfl0rd** [comment]
Fixed and included to 0.7.5, i`ll close it.
