### ISSUE TITLE
 Server Crash  "instance method cannot have null 'this'"

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8086]
--BEGIN DUMP--
Dump Time
06/18/2018 02:03:28

Exception
Exception: ArgumentException
Message:Delegate to an instance method cannot have null 'this'.
Source:mscorlib

System.ArgumentException: Delegate to an instance method cannot have null 'this'.
   at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   at Eco.Core.Plugins.StorageManager..ctor()

--END DUMP--

**Comment by metachronism** [comment]
need the game save that caused this, please attach and reopen

**Comment by pamduncan** [comment]
We went to the backup from before the crash started and it ran without issue for 24 hours and the started again.  The world save is attached.

--BEGIN DUMP--
Dump Time
06/19/2018 02:04:11

Exception
Exception: ArgumentException
Message:Delegate to an instance method cannot have null 'this'.
Source:mscorlib

System.ArgumentException: Delegate to an instance method cannot have null 'this'.
   at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   at Eco.Core.Plugins.StorageManager..ctor()

--END DUMP--


https://www.dropbox.com/s/ahooo1wp2cuuwps/Game.eco?dl=0
https://www.dropbox.com/s/lnop6eoj8fj7ve0/Game.db?dl=0

**Comment by metachronism** [comment]
this save is loading fine - do you have repro steps?

**Comment by pamduncan** [comment]
Server is just found in that state having crashed over and over on the error posted.  Once it crashes in that state it will load but will just start crashing on that error again

**Comment by pamduncan** [comment]
We were up and running just fine for almost 5 days and then 'this' crash is back again.  I am attacking all the crash files and the Game.db and Game.eco from latest crashing.  This definitely seems like some type of ejection being used to crash the server,  I can go to an immediate backup from before the crash and it loads fine and runs fine.  when I loaded the game up after it crashed it ran foe about 20 minutes and then started crashing again but after going to backup the crash stopped.
https://www.dropbox.com/s/6372ej4ydib005r/PamsBigWorldDump.zip?dl=0

https://www.dropbox.com/s/33gekhnkfxzwnkm/Game.eco?dl=0

https://www.dropbox.com/s/24jbqu8qztpjht6/Game.db?dl=0
