### ISSUE TITLE
USER ISSUE: steam tractor named "steam truck"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8089]
**Version:** 0.7.5.0 beta staging-04eb44af
![2018-06-18 23 46 19](https://user-images.githubusercontent.com/4980243/41561226-f5bb090a-7351-11e8-9921-1fe28424a732.png)
And still 100% identical reciepe as steam truck :)

**Comment by BlazeGuy2** [comment]
Fix made for the name, will send out a PR when I address a few more bugs.  Recipe will probably be looked at when we do a rebalancing pass on it.
