### ISSUE TITLE
Server bug: Meteor hit even though I increased MeteorImpactDays

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#8092]
Running 7.4.7 on win10.
Joined the server today and the meteor had hit. It probably had reached day 30, problem is I had increased MeteorImpactDays to 50.

**Comment by newzealdan** [comment]
Changing the MeteroImpactDays has no effect on meteor ETA.

**Comment by D3nnis3n** [comment]
There is now a command that can change the meteor hit days after the world was created.
