### ISSUE TITLE
Server bug: Backup only keeping 1 backup

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#8093]
Have backup settings as below snip shows, however only 1 backup is in the Storage File. When I "Do Backup Now" it saves 1, but deletes 1.

![image](https://user-images.githubusercontent.com/6193670/41592082-9ac390e4-740f-11e8-9d94-1ec4103840c4.png)

:( this compounds big time with the bug I posted just moments ago "Meteor hit even though I increased MeteorImpactDays"

**Comment by newzealdan** [comment]
btw this is Server v7.4.7.
Checked on my server today and there are just 3 backups for the last hour and a half

**Comment by newzealdan** [comment]
This still seems to be present in 7.5.1, although it is only keeping 5 backups.

**Comment by elfl0rd** [comment]
Same for my testing server.

**Comment by D3nnis3n** [comment]
Backups were reworked and seem to work fine now.
