### ISSUE TITLE
Property claim flag / colour problem

### ISSUE THREAD

**Issue by Cdrix** [StrangeLoopGames/EcoIssues#8094]
Hello, I have a problem because I do not see the colors (with property claim flag), I am forced to disconnect and reconnect. Do I have to activate a specific option in the game to see the colors all the time? I play only on third person.

My graphic drivers are up to date and .Net too.

**Comment by Cdrix** [comment]
![image](https://user-images.githubusercontent.com/40391221/41595644-ee3a9c56-73c7-11e8-886d-69a156436038.png)
![image](https://user-images.githubusercontent.com/40391221/41595664-006b415a-73c8-11e8-84f8-448fdc046f95.png)

**Comment by Cdrix** [comment]
On third person, problem with colour, but on first person, no problem

**Comment by BlazeGuy2** [comment]
Copy of #8049, closing.
