### ISSUE TITLE
USER ISSUE: excavator clip to ground

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8095]
**Version:** 0.7.5.0 beta staging-9dcf3091
Periodically excavator clip to ground.
then - jump out, and fly :(

Please check, every time it's start from left back wheel.
![20180619155051_1](https://user-images.githubusercontent.com/4980243/41598609-550330fe-73d9-11e8-900b-92d8769ec0cb.jpg)
![20180619155103_1](https://user-images.githubusercontent.com/4980243/41598610-55237e18-73d9-11e8-9c31-1928d9c7e60e.jpg)
![20180619155430_1](https://user-images.githubusercontent.com/4980243/41598611-554a33aa-73d9-11e8-87f1-4185968994e2.jpg)
![20180619155447_1](https://user-images.githubusercontent.com/4980243/41598612-556ccce4-73d9-11e8-841c-d3bb4f3ade99.jpg)

Reproduced on fresh world.

**Comment by SeanAtr0n** [comment]
fixed in svn
