### ISSUE TITLE
USER ISSUE: stack limit is not work on some cases

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8097]
**Version:** 0.7.5.0 beta staging-9dcf3091
Bad stacks (28 sand in one slot, 12 road) by RMB unload to storage.
![20180619202054_1](https://user-images.githubusercontent.com/4980243/41614713-d80c04b2-7401-11e8-9103-66032c441a58.jpg)
![20180619203121_1](https://user-images.githubusercontent.com/4980243/41615026-d8d5b8ce-7402-11e8-800b-67cb1042afd8.jpg)

Same as steam tractor harvesting
![20180619204855_1](https://user-images.githubusercontent.com/4980243/41615032-dec7e996-7402-11e8-8dfe-f3d3464681da.jpg)

same as crane unload
![20180619205032_1](https://user-images.githubusercontent.com/4980243/41615049-e5d5e56c-7402-11e8-9dc3-27a3b17d510e.jpg)

And maybe more!

**Comment by MarjieAVolk** [comment]
Sounds like it's all related to vehicles then?

**Comment by SeanAtr0n** [comment]
actually, guess i already fixed this

**Comment by SeanAtr0n** [comment]
nevermind, fixed a similar issue but this only happens when you right click to place in vehicle

**Comment by SeanAtr0n** [comment]
i'm guessing this is related to crane changes

**Comment by johnkslg** [comment]
Fixed!
