### ISSUE TITLE
USER ISSUE: Robotic Assembly Line - bad collision

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8099]
**Version:** 0.7.5.0 beta staging-bad4361f
Robotic Assembly Line have really bad collision :(

![20180619232617_1](https://user-images.githubusercontent.com/4980243/41622504-73c71f0c-7418-11e8-8a48-b680775e6bf5.jpg)
![20180619232522_1](https://user-images.githubusercontent.com/4980243/41622505-73e7cfea-7418-11e8-8d9e-083190ce57c6.jpg)
![20180619232547_1](https://user-images.githubusercontent.com/4980243/41622506-740c185a-7418-11e8-8445-5a6df1a07e1c.jpg)
![20180619232552_1](https://user-images.githubusercontent.com/4980243/41622507-742d7d10-7418-11e8-8c53-ef55e63fc82b.jpg)
![20180619233033_1](https://user-images.githubusercontent.com/4980243/41622624-d95fe4a2-7418-11e8-8552-7ae34cbfb058.jpg)
![20180619233042_1](https://user-images.githubusercontent.com/4980243/41622625-d98d5e14-7418-11e8-8203-fed525469986.jpg)
![20180619233054_1](https://user-images.githubusercontent.com/4980243/41622627-da503a38-7418-11e8-9bd5-fe9cc838500d.jpg)

**Comment by keegan-o** [comment]
fixed in staging, now robots can push you around.
