### ISSUE TITLE
USER ISSUE: 1,1,1,1,1 toolbar on same vechicles.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8100]
**Version:** 0.7.5.0 beta staging-bad4361f
Basic (not excavator\skidsteer) vechicle have strange toolbar.
![20180619232641_1](https://user-images.githubusercontent.com/4980243/41622664-f9030514-7418-11e8-9889-1b019c5e5d84.jpg)
![20180619232711_1](https://user-images.githubusercontent.com/4980243/41622665-f9293036-7418-11e8-8f05-215f6f75a886.jpg)
![20180619232719_1](https://user-images.githubusercontent.com/4980243/41622666-f950964e-7418-11e8-9901-19a88d40fe28.jpg)

**Comment by SeanAtr0n** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/2959
