### ISSUE TITLE
USER ISSUE: steam tractor - no module shortcut on toolbar

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8101]
**Version:** 0.7.5.0 beta staging-bad4361f

**Steps to Reproduce:**
Steam tractor with modules not have right toolbar, but have working buttons on it
(for plough - 1 enable\disable it)
![20180619232641_1](https://user-images.githubusercontent.com/4980243/41622740-33461dec-7419-11e8-9898-3b47624deb75.jpg)

**Comment by elfl0rd** [comment]
More from discord.
![default](https://user-images.githubusercontent.com/4980243/42165091-2d240bbc-7e10-11e8-8654-d57528a3eab3.png)
GokouZWAR: Is there a tutorial on how to use the steam plough? Its not plowing....

**Comment by elfl0rd** [comment]
After adding possibility to enable\disable modules, this is really needed!

**Comment by SlayksWood** [comment]
move to #11976
