### ISSUE TITLE
USER ISSUE: steam tractor - no ability to turn on\off for sower and harvester

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8103]
**Version:** 0.7.5.0 beta staging-bad4361f
Only plough can be enabled\disabled by pressing 1.
Both other modules work everytime.

**Comment by elfl0rd** [comment]
current behavior really bad, you need to constantly add\remove these modules...

**Comment by k0ka** [comment]
It's really annoying, that you can't quickly turn off harverster and it harvests tons of Plant Fibers

**Comment by Kirthos** [comment]
I have a fix for this, that can be used until all module will get an anim event for on/off.

**Comment by elfl0rd** [comment]
@Kirthos its sounds merged but not fixed, attachments not disables after pressing 1

**Comment by SlayksWood** [comment]
merged to #12398
