### ISSUE TITLE
V7.5 Stage : Cant jump out of water

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8108]
Pressing space key frequently but cant climb the strand. Some block along the coast it works as in earlier Versions. But next try on an other position again. The 'jump' Animation isn't running, or only for 2 or 3 Pixel ;-)

![20180620010516_1](https://user-images.githubusercontent.com/22961978/41628753-4fffc8ea-7426-11e8-8f26-1d5d07ad58a3.jpg)

**Comment by SeanAtr0n** [comment]
You can do it, its just very slow depending on slope

**Comment by SeanAtr0n** [comment]
Fixed in https://github.com/StrangeLoopGames/Eco/pull/2963
