### ISSUE TITLE
Save file crashing Ecoserver.exe on load

### ISSUE THREAD

**Issue by megatronp** [StrangeLoopGames/EcoIssues#8112]
The linked save seems to crash EcoServer.exe any time I try to load it. It was created as a singleplayer world.
Running version 0.7.5.0 staging on steam.
https://www.dropbox.com/s/lyarcxd885zu67z/SP%20Save%20file.zip?dl=0

**Comment by elfl0rd** [comment]
Like this? https://github.com/StrangeLoopGames/EcoIssues/issues/8098
