### ISSUE TITLE
USER ISSUE: elevator have small missing collision.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8113]
**Version:** 0.7.5.0 beta staging-bad4361f
![20180620162906_1](https://user-images.githubusercontent.com/4980243/41661475-828e9b52-74a7-11e8-9683-91c4ddebb99f.jpg)
![20180620163019_1](https://user-images.githubusercontent.com/4980243/41661521-a2fd3de4-74a7-11e8-8f0d-96a564b635e0.jpg)

or this planned? To allow jump-down players?

**Comment by SeanAtr0n** [comment]
Yeah it's intentional so you can still get in it from above

**Comment by elfl0rd** [comment]
@SeanAtr0n maybe you remove this texture?
