### ISSUE TITLE
Missing law functions - Species population

### ISSUE THREAD

**Issue by Myrhaug** [StrangeLoopGames/EcoIssues#8114]
I tried to create a law to allocate 50€ when harvesting turtles, when population is over 800 turtles.
We got a huge population of turtles, and we want players to get motivated to harvest, so we get the population down to a accepable level.

But it seems we cant control population with laws.
I added a screenshot of my law, so you understand what I mean.

![turtles](https://user-images.githubusercontent.com/40342749/41674079-2f3492e6-74bf-11e8-9dac-e3c0c5a3b242.PNG)

**Comment by MarjieAVolk** [comment]
I see, so you want to get the population count.  Yeah that sounds useful.

**Comment by Myrhaug** [comment]
Yes, we need to get the population down. So it would be great to have a function that allow us to allocate currency when harvesting animals when there is more then X in population (as I tried to do on the screenshot)

**Comment by WeaselDog** [comment]
This has been added with the new law system.
![AnimalPopulationLaw](https://user-images.githubusercontent.com/47330823/71304061-f104f080-2375-11ea-9e28-35349ef23e6f.png)
