### ISSUE TITLE
Treasury + Store

### ISSUE THREAD

**Issue by Myrhaug** [StrangeLoopGames/EcoIssues#8116]
I have a request for you guys.
We got a public library, instead of giving away property claim for free, we want to take payment for skill scrolls. BUT we want the **_world leader and/or admins_** to have the possibility to add Treasury as payment reciever.

When player buys skill scroll for ex. 100€, the payment goes straight into treasury.

**Comment by GophTheGreat** [comment]
Moved to https://github.com/StrangeLoopGames/EcoSuggestions/issues/425
