### ISSUE TITLE
7.5.0 Textures move when vehicles move

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8120]
Placed sand blocks in the trunk of the truck or steam truck.  When the car moves, the texture also moves when the sand texture should stay static.  Similar issue came up with the crane moving dirt in the show 'n tell last week.

**Comment by metachronism** [comment]
dupe of other issue, not really high priority

**Comment by SeanAtr0n** [comment]
kinda makes sense to tag em as high priority if we want it for 7.5

**Comment by elfl0rd** [comment]
Duplicate - https://github.com/StrangeLoopGames/EcoIssues/issues/7596
