### ISSUE TITLE
USER ISSUE: Wheelbarrow too slow and have "lower" action on LMB

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8125]
**Version:** 0.7.5.0 beta staging-1cd3520e
Wheelbarrow works looks like hand plough, slow movement and lowing by pressing LMB.
https://youtu.be/Z6ZCBcGVP3I

**Comment by elfl0rd** [comment]
So... i makes interview on largest russian eco server.
75% players think that "wheelbarrow is useless, too slow, and not good to use."
25% players rarely use wheelbarrow, in tight places.
100% players uses wood cart really more time then wood cart.

And one of the bad things - wheels requiment.
If you have wainwright table - you can create wooden cart.

**Comment by craig-jong** [comment]
Fixed in staging
