### ISSUE TITLE
[QoL] item tooltip periodically prevent items dragging.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8126]
**Version:** 0.7.5.0 beta staging-1cd3520e
![20180621124941_1](https://user-images.githubusercontent.com/4980243/41712887-570597f8-7554-11e8-96f3-e8bc263df6db.jpg)

As i see - solution is hide tooltip if item dragged!

**Comment by MarjieAVolk** [comment]
Hm, I thought the tooltip was disabled while dragging.  Guess that must have some bugs.

**Comment by elfl0rd** [comment]
If you already drag - no new tooltips, but old - is not hide.

**Comment by LiaungYip** [comment]
Still occurring on 7.7.0.

![nodrag](https://user-images.githubusercontent.com/2173684/44938916-e7dcc280-adc4-11e8-9cd9-847b7a81d2e6.gif)

**Comment by metachronism** [comment]
moved to other bug, sorry @elfl0rd didnt see this one first :P 
#9132

**Comment by elfl0rd** [comment]
@metachronism :(
