### ISSUE TITLE
0.7.4.7 Several Animal species have no food sources

### ISSUE THREAD

**Issue by Caledorn** [StrangeLoopGames/EcoIssues#8129]
On a freshly installed 0.7.4.7 installation, the Server GUI reports that Bison, Turkeys and Foxes have no food sources when going to:

Simulation tab -> Species (Collection) [...] button -> (Animal) -> FoodSources (Collection) [...] button

The window that pops up show these animals to have no food sources. 

On the KoS CM Server 6 we had to manually add the food sources for the bison population to start growing again.

![bison](https://user-images.githubusercontent.com/1360631/41739486-7d50fe7a-7595-11e8-910f-36dbda1c9557.jpg)

**Comment by pamduncan** [comment]
It appears that that has been the setting for animal species food resources for a long time.  I can go back before 7.3.3 (shown here) and find the same setting exists.  
[![Screenshot from Gyazo](https://gyazo.com/00564616ab77cf09dfd864a4d3885afd/raw)](https://gyazo.com/00564616ab77cf09dfd864a4d3885afd)

**Comment by craig-jong** [comment]
That's because the GUI list of generated species does NOT display correctly. I do not recommend editing those settings (or checking the boxes at all) due to some odd behavior it can produce. If animals had no food sources they wouldn't even spawn.

**Comment by SeanAtr0n** [comment]
fixed w/ move to mods
