### ISSUE TITLE
staging 7.5 Null Reference Exception on ContractClauseLoan

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#8131]
Crashes stuffed elk
![image](https://user-images.githubusercontent.com/6262198/41743418-8f3c18f8-7555-11e8-9414-2ffb567c9520.png)

	Eco.Gameplay!Eco.Gameplay.Economy.Contracts.ContractClauseLoan.Valid(Eco.Gameplay.Players.User contractor, Eco.Gameplay.Players.User client) Line 97	C#
 	Eco.Gameplay!Eco.Gameplay.Economy.Contracts.Contract.get_Valid.AnonymousMethod__73_0(Eco.Gameplay.Economy.Contracts.ContractClause x) Line 103	C#
 	[External Code]	
 	Eco.Core!Eco.Core.Utils.ResultExtensions.Merge(System.Collections.Generic.IEnumerable<Eco.Core.Utils.Result> list) Line 49	C#
 	Eco.Gameplay!Eco.Gameplay.Economy.Contracts.Contract.Valid.get() Line 103	C#
 	Eco.Gameplay!Eco.Gameplay.Economy.Contracts.Contract.PostJob(Eco.Gameplay.Players.Player player) Line 115	C#
 	[External Code]	
 	Eco.Shared!Eco.Shared.Networking.RPCManager.TryInvoke(object controller, string methodname, Eco.Shared.Serialization.BSONObject bsonArgs, out object result) Line 223	C#
 	Eco.Shared!Eco.Shared.Networking.RPCManager.InvokeOn(Eco.Shared.Serialization.BSONObject bson, object controller, string methodname) Line 197	C#
 	Eco.Core!Eco.Core.Controller.ControllerManager.HandleViewRPC(int controllerID, string methodname, Eco.Shared.Serialization.BSONObject bson) Line 468	C#
 	Eco.Plugins!Eco.Plugins.Networking.Client.ViewRPC(int id, string methodname, Eco.Shared.Serialization.BSONObject bson) Line 393	C#
 	[External Code]	
 	Eco.Shared!Eco.Shared.Networking.RPCManager.TryInvoke(object controller, string methodname, Eco.Shared.Serialization.BSONObject bsonArgs, out object result) Line 223	C#
 	Eco.Shared!Eco.Shared.Networking.RPCManager.InvokeOn(Eco.Shared.Serialization.BSONObject bson, object controller, string methodname) Line 197	C#
 	Eco.Shared!Eco.Shared.Networking.RPCManager.HandleReceiveRPC(Eco.Shared.Networking.INetClient client, Eco.Shared.Serialization.BSONObject bson) Line 320	C#
 	Eco.Plugins!Eco.Plugins.Networking.NetworkServer.ReceiveEvent(Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) Line 154	C#
 	Eco.Shared!Eco.Shared.Networking.NetObject.ReceiveEvent(Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) Line 69	C#
 	Eco.Plugins!Eco.Plugins.Networking.Client..ctor.AnonymousMethod__52_1() Line 113	C#
 	[External Code]

**Comment by johnkslg** [comment]
Fixed by disabling for now.
