### ISSUE TITLE
Scrollbar disappears in Economy Tab

### ISSUE THREAD

**Issue by babare** [StrangeLoopGames/EcoIssues#8133]
On 0.7.4.7, sometimes the scrollbar disappears on the "For Sale" tab of the Economy panel.

It sometimes reappears by playing with the panel's size, and I suspect it is caused by having a big number of items.

**Comment by X-ITT** [comment]
This happens when someone names their store a ridiculously long name.

**Comment by SlayksWood** [comment]
Seems fixed with new UI
![image](https://user-images.githubusercontent.com/45708377/71412981-315bbb80-2661-11ea-9d28-97a793346d47.png)
