### ISSUE TITLE
gasoline

### ISSUE THREAD

**Issue by LuZiferdk** [StrangeLoopGames/EcoIssues#8136]
wen i have collected the petroleum and make it in to gaoiline that is fine bot wen i trye to add it to the store i can only finde Petroleum and nuclear Fule ther is no icon for gasoline can you take a look at that plz

**Comment by LuZiferdk** [comment]
7.4.7 and a mod dont no whot the mod is call bot her is the server name
[EU] SlappedBy - Friendly Community - custom mod

**Comment by elfl0rd** [comment]
you can ask about it directly on server owner.

**Comment by MarjieAVolk** [comment]
Did your server have Gasoline discovered?  Looks like the server needs to have discovered Petrol Refining in order for it to show up.

**Comment by LuZiferdk** [comment]
i just made the first gasoline and now i can add it to the shop...... thx for all the help....
