### ISSUE TITLE
Decimals separator

### ISSUE THREAD

**Issue by madxmat** [StrangeLoopGames/EcoIssues#8138]
This bug was fixed before but it has returned again. Default setup for my region is comma as a decimal separator. So in game when setting up a price I cannot use period. I can put it but for some reason system doesn't see it. The only way to fix it is to setup windows region to English US.

**Comment by BlazeGuy2** [comment]
The fix should be in staging right now, not in the release version 7.4.7.  Is this bug showing up in 7.5.0 right now?

**Comment by BlazeGuy2** [comment]
Didn't hear back, closing for now.  If this issue appears in 7.5.0, open a new issue and we'll tackle it.
