### ISSUE TITLE
Plant Batching

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#814]
Would be nice if plants batched, making a bug to track progress and avoid duplicated efforts.

**Comment by SeanAtr0n** [comment]
To get plant batching working, I had to:
   * set LODFadeMode = None
   * delete the 'Tree' components on individual plant lods

Removing the tree component disables wind (and possibly other stuff?) so the choice seems to be between wind and batching.

**Comment by metachronism** [comment]
not sure why wind would affect this, as its (supposed to) be controlled via the shader

we could maybe only have wind for the highest/higher LODs, and off for the lower lods

**Comment by SeanAtr0n** [comment]
One problem is that I can't look inside 'Tree' to see what its doing. It's doing something that breaks batching, that might have to do with wind or something else. 

With lod fading & trees disabled I was able to make material property blocks work, however material property blocks break batching on my machine. They provide a slight perf boost over our previous method, but that perf boost probably isn't worthwhile on its own.

Here are some profiling numbers, just loading the game while standing still using the same view point.

no batching (current setup)
Camera.Render: ~7.8ms
Materials: 2233

just deleting tree component, no property blocks resulted in ~120 batched draw calls
Camera.Render: ~6.2ms
Materials: 4014 (not sure why)

ideal batching (tree component deleted, no age set) ~ 500 batched draw calls
Camera.Render: ~4.1ms
Materials: 354

tree component deleted, using material property blocks - no batches
Camera.Render: ~5.6ms
Materials: 421

MaterialPropertyBlocks don't seem to be working as advertised

**Comment by metachronism** [comment]
I added support for this, using GPU instancing shaders

the highest LOD still uses the tree component for wind
