### ISSUE TITLE
Server GUI: File > Open always points to "Eco\Eco_Data\Server\Storage", even if running the standalone server.

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#8142]
A user was running the standalone server version and was trying to swap out his save file, but the GUI pointed him toward the base game directory instead of the standalone server directory.

**Comment by metachronism** [comment]
file->open isnt even used for game saves

**Comment by MarjieAVolk** [comment]
Oh yeeeah :P
