### ISSUE TITLE
USER ISSUE: Steam invite friend => Connection Failed: No response from master server

### ISSUE THREAD

**Issue by 01Xray21** [StrangeLoopGames/EcoIssues#8146]
**Version:** 0.7.4.7 beta

**Steps to Reproduce:**

**Expected behavior:**
I sent my friend a steam invite to my world and it failed every single time.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

No response from master server.
```

<size=150%>Connection Failed</size>

No response from master server.

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1060 3GB (ID=0x1c02)
    Vendor:   NVIDIA
    VRAM:     2988 MB
    Driver:   24.21.13.9811
Begin MonoManager ReloadAssembly
- Completed reload, in  0.179 seconds
<RI> Initializing input.

XInput1_3.dll not found. Trying XInput9_1_0.dll instead...
<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.863808 ms
Setting up 2 worker threads for Enlighten.
  Thread -> id: 186c -> priority: 1 
  Thread -> id: d6c -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.7 beta
21 June 2018 14:26
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggedIn -> NewWorld
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[58:06] Stopping existing server.Changing state: NewWorld -> LoadingWorld
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.4.7 beta
LocalServer -  Server Initialization... 
LocalServer -  Starting LocalizationPlugin... 
LocalServer -  Starting ModKitPlugin... 
LocalServer -  Loading mods... 
LocalServer -  Starting NetworkManager... 
LocalServer -  Initializing items... 
LocalServer -  Starting BackupPlugin... 
LocalServer -  Starting StorageManager... 
LocalServer -  Starting WorldGeneratorPlugin... 
LocalServer -  Starting GameplayStatsPlugin... 
LocalServer -  Initializing skills... 
LocalServer -  Starting StatDatabase... 
LocalServer -  Starting WorldPlugin... 
LocalServer -  Initializing world... 
LocalServer -  Starting TimePlugin... 
LocalServer -  Starting ReputationPlugin... 
LocalServer -  Starting PlayerHousingManager... 
LocalServer -  Starting UserManager... 
LocalServer -  Initializing inventories... 
LocalServer -  Starting EcoObjectManager... 
LocalServer -  Starting GarbagePlugin... 
LocalServer -  Starting PropertyManager... 
LocalServer -  Starting ChatServer... 
LocalServer -  Starting ControllerManager... 
LocalServer -  Starting MinimapManager... 
LocalServer -  Starting EcoSim... 
LocalServer -  Starting DisasterPlugin... 
LocalServer -  Starting WirePlugin... 
LocalServer -  Starting DifficultySettings... 
LocalServer -  Initializing plants... 
LocalServer -  Starting RouteProbingPlugin... 
LocalServer -  Starting WorldLayerManager... 
LocalServer -  Starting EconomyTracker... 
LocalServer -  Starting WorldObjectManager... 
LocalServer -  Starting EconomyPlugin... 
LocalServer -  Starting RoomPlugin... 
LocalServer -  Starting ObjectivePlugin... 
LocalServer -  Starting Legislation... 
LocalServer -  Starting WebServerPlugin... 
LocalServer -  Starting HousingTierDefinition... 
LocalServer -  Initializing LocalizationPlugin... 
LocalServer -  Initializing WorldGeneratorPlugin... 
LocalServer -  Generating world 0.52km�... 
LocalServer -  Generating terrain... 
LocalServer -  Caching world data... 
LocalServer -  Generating plateaus... 
LocalServer -  Carving rivers... 
LocalServer -  Generating special features... 
LocalServer -  Ticking (Pass 1)... 
LocalServer -  Initializing world layers... 
LocalServer -  Ticking world layers... 
LocalServer -  Ticking (Pass 2)... 
LocalServer -  Determining visibility... 
LocalServer -  Compressing... 
LocalServer -  Saving world... 
LocalServer -  Generating world 0.52km� finished in 143,359.7ms
LocalServer -  Initializing UserManager... 
LocalServer -  Initializing MinimapManager... 
LocalServer -  Initializing WorldObjectManager... 
LocalServer -  Initializing RoomPlugin... 
LocalServer -  Initializing HousingTierDefinition... 
LocalServer -  Initializing WorldPlugin... 
LocalServer -  Ticking... 
LocalServer -  Compressing... 
LocalServer -  Initializing WorldLayerManager... 
LocalServer -  Initializing WebServerPlugin... 
LocalServer -  Server Initialization finished in 154,446.2ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[00:40] Connecting via Lidgren to localhost:3000
Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoadingWorld -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at PostProcessingManager.UpdateHypoxia () [0x0002f] in <9db9327c48f4489f8598dcbe8af462a3>:0 
  at Eco.Shared.View.ISubscriberExtensions.SubscribeAndCall (Eco.Shared.View.ISubscriber s, System.String propname, System.Action changedCallback) [0x00008] in <953043a415744ee890d49685304f4fc5>:0 
  at PostProcessingManager.Start () [0x00081] in <9db9327c48f4489f8598dcbe8af462a3>:0 
 
(Filename: <9db9327c48f4489f8598dcbe8af462a3> Line: 0)

Caught exception on ChatManager(Clone) while in NetObject ReceiveInitialState.
Exception: Object reference not set to an instance of an object
Callstack:   at Assets.UI.Scripts.ChatUI.ClearMessages () [0x00000] in <9db9327c48f4489f8598dcbe8af462a3>:0 
  at Assets.UI.Scripts.ChatMainUI.LogOpen () [0x00000] in <9db9327c48f4489f8598dcbe8af462a3>:0 
  at Assets.UI.Scripts.ChatLogUI.<OnEnable>m__0 () [0x0000a] in <9db9327c48f4489f8598dcbe8af462a3>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void ()
  at UI.ChatManager.ReceiveInitialState (Eco.Shared.Serialization.BSONObject obj) [0x000da] in <9db9327c48f4489f8598dcbe8af462a3>:0 
  at NetObjComponent.OnReceiveInitialState (Eco.Shared.Serialization.BSONObject bsonObj) [0x00022] in <9db9327c48f4489f8598dcbe8af462a3>:0 
  at NetObjComponent.Eco.Shared.Networking.INetObject.ReceiveInitialState (Eco.Shared.Serialization.BSONObject bsonObj) [0x00000] in <9db9327c48f4489f8598dcbe8af462a3>:0 
BSON: Eco.Shared.Serialization.BSONObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> FadeAndClose
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.UI.Scripts.ChatUI.ClearMessages () [0x00000] in <9db9327c48f4489f8598dcbe8af462a3>:0 
  at Assets.UI.Scripts.ChatMainUI.LogOpen () [0x00000] in <9db9327c48f4489f8598dcbe8af462a3>:0 
  at Assets.UI.Scripts.ChatLogUI.<OnEnable>m__0 () [0x0000a] in <9db9327c48f4489f8598dcbe8af462a3>:0 
  at UI.ChatManager.DoOnChatManagerInitialized (System.Action action) [0x0001b] in <9db9327c48f4489f8598dcbe8af462a3>:0 
  at Assets.UI.Scripts.ChatLogUI.OnEnable () [0x00011] in <9db9327c48f4489f8598dcbe8af462a3>:0 
UnityEngine.GameObject:SetActive(GameObject, Boolean)
AvatarCreationUI:OnDisable()
UnityEngine.Object:Destroy(Object, Single)
UnityEngine.Object:Destroy(Object)
UI.UIManager:Destroy(GameObject)
UI.UIManager:Hide(GameObject)
UI.UIManager:Close(GameObject)
UI.UIManager:Close(String, BSONObject)
UI.UIManager:Close(String)
UI.BaseUI:Close()
AvatarCreationUI:OnSave()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent()
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: <9db9327c48f4489f8598dcbe8af462a3> Line: 0)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

[03:03] Disconnected from server.Shutting down server
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer - Saving...
LocalServer -  Saving world... 
Changing state: PreLogin -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer - Finished in 124.2msDone
Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[04:15] Disconnected from server.Changing state: LoggedIn -> Connecting
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: Connecting -> LoggedIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[11:55] Disconnected from server.

**Comment by metachronism** [comment]
consolidating into #8443
