### ISSUE TITLE
Game halts on loading

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8148]
https://steamcommunity.com/id/remembertolikeandfave/recommended/382310/
I've seen this reported many times. We need to track down and fix this before 8.0 launch.

**Comment by elfl0rd** [comment]
looks as firewall blocked access to network.
I try to repro it )

**Comment by SeanAtr0n** [comment]
We have no debug info for this....

**Comment by elfl0rd** [comment]
yes, looks like game not have access to internet, to verify license.
![2018-06-27 01 41 25](https://user-images.githubusercontent.com/4980243/41943309-971f0bde-79ab-11e8-92ed-a8c8adb4e2cf.png)
![2018-06-27 01 35 40](https://user-images.githubusercontent.com/4980243/41943310-974372e4-79ab-11e8-8a2d-da3775531c33.png)

**Comment by pamduncan** [comment]
On the servers I have been dealing with the Eco.Mods.dll is not compiling.  Its all been on steam and complete clean reinstall where they go in an delete the files steam is leaving behind and therefor not getting some of the updated files in has solve the issue in most cases.

**Comment by metachronism** [comment]
critical priority is for hotfixes, and this isnt a widespread issue

**Comment by metachronism** [comment]
cant repro

**Comment by metachronism** [comment]
closing per consolidation of 7.5.X issues
