### ISSUE TITLE
Beta 7.5.0 - Hanging signs in middle of wall.

### ISSUE THREAD

**Issue by X-ITT** [StrangeLoopGames/EcoIssues#8149]
Seems signs are now place in the middle of the wall.
![unknown](https://user-images.githubusercontent.com/11493473/41940271-27412224-7966-11e8-8b60-632d824ff0aa.png)

**Comment by elfl0rd** [comment]
Welcome! https://github.com/StrangeLoopGames/EcoIssues/issues/8055
