### ISSUE TITLE
New Jumping is Useless 7.5

### ISSUE THREAD

**Issue by miketek1** [StrangeLoopGames/EcoIssues#8150]
With the introduction of "more realistic physics" the jump has become almost useless when trying to build as you jump and veer off to the right or left and fall off or miss your intended target. It doesn't seem to be predictable either, it seems as if its just useless.

**Comment by SeanAtr0n** [comment]
could you post a video or something where it feels bad for you?

**Comment by SeanAtr0n** [comment]
Closing, please feel free to reopen if you have some constructive feedback.

**Comment by miketek1** [comment]
@SeanAtr0n  I think it is too sensitive, others players that I talk to don't have issues until they start building something. As shown in the video jumping up walls and blocks is too sensitive, if you don't hit it exactly right you are in an endless loop of falling off and having to jump up all over again. (https://youtu.be/9gIjNofAb1A)
