### ISSUE TITLE
Crash on attempt to Join server, Load World, or Create world on 7.5.0 Beta Steam

### ISSUE THREAD

**Issue by whinis** [StrangeLoopGames/EcoIssues#8151]
I have attempt to validate files
uninstall Eco and reinstall via steam
uninstall Eco, Delete all Eco Folders, and reinstall via steam

All results in a crash as soon as it attempts to load the world

**Comment by GophTheGreat** [comment]
You can attach them to your post here -- just drag and drop the files into the comment box. You may have to zip them up before attaching them.

**Comment by whinis** [comment]
[EcoCrash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2140926/EcoCrash.zip)

**Comment by metachronism** [comment]
this is a bad install of the game server - looks like some mods werent overwritten/cleaned up

I would reinstall the game from steam
