### ISSUE TITLE
USER ISSUE: Screw press - iron ingots woodworking skill bonus

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#8156]
**Version:** 0.7.5.0 beta

**Steps to Reproduce:**
1. Place the machinist table
2. Open it's crafting recipies list and hover your mouse over the iron ingots which will be required to craft a screw press
3. Spot the description skill relatement.

**Expected behavior:**
It shows as being related to woodworking skill while trying to craft a screw press on a machinist table

**Actual behavior:**
It may use something smith-related instead.

**Comment by HetNeSS** [comment]
![20180627060423_1](https://user-images.githubusercontent.com/18286472/41947368-a2d85f82-79d0-11e8-8d9e-3c05598d0fd9.jpg)

**Comment by craig-jong** [comment]
Fixed in staging
