### ISSUE TITLE
USER ISSUE: Trucks don't work

### ISSUE THREAD

**Issue by carsonbarlow** [StrangeLoopGames/EcoIssues#8158]
**Version:** 0.7.5.0 beta

**Steps to Reproduce:**
Create a truck.
Place fuel inside truck.
Get in truck.
Attept to move.

**Expected behavior:**
The truck should sound like a truck.
The truck should move.

**Actual behavior:**
The truck sounds like a wood cart.
The truck does not move or get fueled.

**Comment by WolfChieftain** [comment]
Sounds a bit similar to #8189

**Comment by SeanAtr0n** [comment]
whoops, this one was fixed in last hotfix.

Fuel works, but it requires a different type of fuel
