### ISSUE TITLE
[7.5.0] Client crashes every time a player joins a world for the first time

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#8159]
If the player does not have a player profile in a savefile [i.e. first time connecting to a server or existing player profile deleted], first time connecting will result in a crash, and connecting a second time will work (although it won't show the character creator).

**To reproduce:**
1. Create a whole new world/save
2. Try to join
3. Crash

**Note:** this _fully_ prevents singleplayer to be played [in a new world], as the game will always crash when generating the world, resulting in #7875.

**Comment by Kirthos** [comment]
I've got the issue on my server too.
LAN server and server hosted on another machine have the problem too.
Tested on single player and got the issue.

**Comment by pamduncan** [comment]
You can actually start the EcoServer outside of the client and then use teh client to join and play singleplayer in that manner for now

**Comment by elfl0rd** [comment]
0.7.6 happens too, and on server, you can play before you leave - next join attemps crash game.
