### ISSUE TITLE
0.7.6.0 - all land claims removed

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8164]
**Version:** 0.7.6.0 beta staging-4767aa88
After convertation from 0.7.5, all land claim are removed.

**Comment by MarjieAVolk** [comment]
From your inventory?

**Comment by MarjieAVolk** [comment]
Or you're saying all the property was unclaimed.

**Comment by elfl0rd** [comment]
> Or you're saying all the property was unclaimed.
yes.
All plots in world unclaimed after convertation.

**Comment by MarjieAVolk** [comment]
Uh ohhhhhh

This worked when I tested it, I must have broke it during the PR

**Comment by elfl0rd** [comment]
yea, it's really bad :( anarchy world.... Stealers everywhere...

**Comment by MarjieAVolk** [comment]
Okay, I just double checked with our test save, and the property is migrating over correctly.  Do you have a copy of your save file before the migration?

**Comment by elfl0rd** [comment]
![20180628213312_1](https://user-images.githubusercontent.com/4980243/42053758-1b10dcb8-7b1b-11e8-952f-9d235fb03171.jpg)
![20180628211433_1](https://user-images.githubusercontent.com/4980243/42053759-1b3499d2-7b1b-11e8-8d3b-320a4f18a756.jpg)
https://www.dropbox.com/s/1tc9cgzlj984nvc/ECOSave.zip?dl=1

**Comment by MarjieAVolk** [comment]
Fixed in next bleeding edge build
