### ISSUE TITLE
0.7.6.0 - no way to create divided land claim

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8165]
**Version:** 0.7.6.0 beta staging-4767aa88
So... Before - you need DEED in inventory, and you can claim multiple plot on far away from other to one deed.
Now, you cant.
(Yes, you can POSTmanage by estate desk, but this is not easy to know, and is not good to use on the fly)

**Comment by elfl0rd** [comment]
(And yes, you can POSTmanage by estate desk, but this is not easy to know, and is not good to use.

**Comment by MarjieAVolk** [comment]
Working as intended, but it will be good to get some player feedback on these choices.  Why do you want to create a single deed with property very far apart?  Do you just want all of your property on the same deed?

**Comment by elfl0rd** [comment]
for bridges and POI, on public server

**Comment by elfl0rd** [comment]
Another - multiple plots for farming one plant
Another - multiple plots with road lighting.

**Comment by elfl0rd** [comment]
Man, it's really need :(

**Comment by MarjieAVolk** [comment]
> Another - multiple plots for farming one plant
> Another - multiple plots with road lighting.

Not sure if I understand all these.  Why wouldn't the road property all be connected?

**Comment by elfl0rd** [comment]
road not in property, they protected by law.
Byt stone braziers requie claim, to prevent stealing :(

**Comment by MarjieAVolk** [comment]
I see, so the law can protect the road but it can't protect the objects huh?  Sounds like adding law support to protect objects based on districts might be a better solution.

**Comment by elfl0rd** [comment]
property control is really faster then law)))
In active expanding process, claim are better solution

**Comment by elfl0rd** [comment]
But law expanding is nice too.

**Comment by elfl0rd** [comment]
not have requied claim flags? Road is too long.
Fnd bridges, PoI and little farms still here too)

**Comment by MarjieAVolk** [comment]
So do you think one person's property should all go onto a single deed by default?

**Comment by elfl0rd** [comment]
No, splitting is good!
But need way to claiming land to existing deed.
Checkbox on deed interface like "expand this" maybe?
If checked - all new claim attached to it.

**Comment by elfl0rd** [comment]
In addition, it will add some freedom to the players :)

**Comment by MarjieAVolk** [comment]
Yeah I see what you're saying.  I would like to avoid requiring the deed window to be pinned open in order to do basic things, as was the case before.  I think it would be cool if the deed tool had a deed selection interface, similar to how the hammer + constructs selection works - like you hold shift to open the pull out, scroll to select the deed you want, something like that.  (And the default option would be 'auto')  It isn't exactly the same as the hammer though, since it doesn't involve carrying anything.

**Comment by elfl0rd** [comment]
Hmm... Good idea.
The main thing is that the interface is not overloaded (for example, when there are many different sites)

**Comment by elfl0rd** [comment]
From discord.

> [05:21] Amphysbaenas - Ecotopia: i need to find a griefer that rob items
[05:21] Amphysbaenas - Ecotopia: street lamps windturbine etc
[05:21] Amphysbaenas - Ecotopia: thats items are not logged in .db file
[05:23] Pigafetta: thought there was a recent update so tables, etc weren't default to public, best to check and make sure, even if on own property, as griefers can come along and take things that aren't whitelisted or inherited
[05:23] Amphysbaenas - Ecotopia: you can not put claims on all road over a 4 k world ..;
![default](https://user-images.githubusercontent.com/4980243/42085516-52627798-7b99-11e8-914f-2c0737074138.png)

**Comment by elfl0rd** [comment]
Can you reopen issue? Or maybe i move it to suggestion :P

**Comment by MarjieAVolk** [comment]
I think this chat also highlights the need for stats/law actions for picking up objects (and not just blocks).  Filed this for it: https://github.com/StrangeLoopGames/EcoIssues/issues/8243

Um, yeah would you mind re-filing any remaining concerns as a suggestion?  I get what you're saying, but it's kind of fuzzy what the solution should be exactly.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoSuggestions/issues/439

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/42193052-2199af3a-7e75-11e8-82ec-e7361a096dc8.png)
Purple - wheat farms. I not want to split it :(

**Comment by elfl0rd** [comment]
okay, how to i claim these plots for deed trading? :)
![20180718043032_1](https://user-images.githubusercontent.com/4980243/42854444-973b12bc-8a44-11e8-89ee-86b52e981492.jpg)

**Comment by MarjieAVolk** [comment]
I don't understand what your issue is.  You want to claim the plots in the center, but have them go onto a different deed?

**Comment by elfl0rd** [comment]
deed control interface is not usefull, more like as "sea ​​battle game"...
these plot? oh, no... Try next... Oh, another direction...

Creating multiple _different_ plots inside controlled area (like little market on spawn) is terribe to me, despite i admin.
Players more coarser "this is nonsense, I will not do it"
and result, server have two placed real estate desk, one on spawn and one used as decoration.
