### ISSUE TITLE
0.7.6.0 - new deed interface owerloaded by plot information.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8167]
**Version:** 0.7.6.0 beta staging-4767aa88
And have potential issue on really large claim.
![20180627113416_1](https://user-images.githubusercontent.com/4980243/41962733-72d4e642-79fe-11e8-91a8-666812905fa6.jpg)

**Comment by MarjieAVolk** [comment]
Yeah that stuff should probably be in a scroll box

**Comment by elfl0rd** [comment]
Or hidden and show by pressing button (in additional window maybe).

**Comment by MarjieAVolk** [comment]
Interesting idea

**Comment by elfl0rd** [comment]
thx :)

**Comment by MarjieAVolk** [comment]
Fixed in next build

**Comment by elfl0rd** [comment]
:( what about my concept? :P
