### ISSUE TITLE
0.7.6.0 - no Land Claim Stake crafting reciepe 

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8168]
**Version:** 0.7.6.0 beta staging-4767aa88
you can drop\remove it, then you cannot claim.

**Comment by MarjieAVolk** [comment]
Ah, yeah there's no recipe for the tool, that's true.  Should probably have that wherever the other basic tools are.

**Comment by craig-jong** [comment]
Fixed in pr

**Comment by elfl0rd** [comment]
Any chance to add land paper reciepe?
For example, for a server leader. And remove 25 claim flags from election reward.
