### ISSUE TITLE
Server sending stale plant growth data?

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#817]
The server doesn't seem to calculate ages for plants until you modify one?
It's not noticeable until the server has been running for a while but it gets worse the longer it runs.
In this example I logged in and immediately did the screenshots so it wasn't just stale data in the client.

![growthpop](https://cloud.githubusercontent.com/assets/774628/20232906/786654b2-a820-11e6-9bb5-0fc1fcd1cfc9.gif)

**Comment by MarjieAVolk** [comment]
I'm going to assume this is fixed now, correct me if I'm wrong
