### ISSUE TITLE
0.7.6.0 - land claimer has access but it not autorized by default.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8170]
**Version:** 0.7.6.0 beta staging-4767aa88
![20180627114941_1](https://user-images.githubusercontent.com/4980243/41963460-555b7958-7a00-11e8-861b-1f9553dd1f8d.jpg)

**Comment by MarjieAVolk** [comment]
Yeah this behavior has changed a bit.  As the owner, you are always authorized, regardless of what the whitelist says.  I considered removing the owner from the whitelist section, but I kind of thought maybe it might be relevant if the deed was sold or something.  What do you think?

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/41992007-0076ffac-7a50-11e8-8ef3-dfa7a6e51f7e.png)
Maybe like this? As i see - 90% of players immediately moving self to authorized... Removing owner, is bad idea, you receive ton of questions like "where my name? how to authorize?" etc...

**Comment by MarjieAVolk** [comment]
Fixed in next build

**Comment by elfl0rd** [comment]
fixed by removing owner? :(
