### ISSUE TITLE
0.7.5.0 Signs missplaced at stores

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8173]
After update to 7.5 signs placed in front of a store appearing misarranged:
![image](https://user-images.githubusercontent.com/22961978/41964139-92033578-79f9-11e8-9607-3fcee6af53b9.png)

**Comment by elfl0rd** [comment]
Already reported :)
Dupe - https://github.com/StrangeLoopGames/EcoIssues/issues/8055

**Comment by MarjieAVolk** [comment]
Should be fixed in 7.6
