### ISSUE TITLE
[7.6.2] Currency of contracts switched on server restart

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8174]
Existing contracts with configured currency where switched to my own currency.

**Comment by Voosle** [comment]
Today I found this again in 7.6.0. See also #8383

**Comment by Voosle** [comment]
Today again. Not while world migration, but on restart, I think. I will take care on it, while our nightly restart in 3.5h

**Comment by LiaungYip** [comment]
Appears to be on server restart. 7.6.1.

![image](https://user-images.githubusercontent.com/2173684/42944504-20eaf864-8ba9-11e8-9e2f-17419986c59c.png)

**Comment by Voosle** [comment]
Today I cross checked this on 7.6.2:
The currency I selected on contract creation switches to my own infinit currency when server restarts.

Contracts are useless, if we can't select another currency. Please raise this to a higher priority. (@GophTheGreat )

Server stoped and started. Open oconomyviewer, open an existing contract and set currency to "Test Coin".
Restart server, open oconomyviewer. Find the currency set to "Voosle Credit" (my infinte).

This occures on not published, on pubished and on accepted and on finished contracts!

Befor restart:
![image](https://user-images.githubusercontent.com/22961978/43000674-bf5fed3c-8c22-11e8-9965-6459f546fe1b.png)

After restart:
![image](https://user-images.githubusercontent.com/22961978/43000802-2f323da4-8c23-11e8-8c7b-7b37196c3377.png)

**Comment by guilemouse** [comment]
I'm also having this problem on version (7.6.3).

**Comment by johnkslg** [comment]
Hey Voosle, are you on Discord? Ping me at discord.gg/eco @johnk!

**Comment by Aatch** [comment]
This appears to be a problem still in 7.8.6
