### ISSUE TITLE
Wall lamp

### ISSUE THREAD

**Issue by Myrhaug** [StrangeLoopGames/EcoIssues#8176]
Electric Wall lamp says it need to be placed on solid ground after 7.5.0 update. It will only work if I place it on the ground

**Comment by elfl0rd** [comment]
Dupe, already reported :(
https://github.com/StrangeLoopGames/EcoIssues/issues/7879

**Comment by Myrhaug** [comment]
Oh, didnt know. First time I got this issue now. Worked normally until 7.5.0

**Comment by elfl0rd** [comment]
Yea, no problem :) thx for reporting!
