### ISSUE TITLE
Game keeps crashing while mining, unable to get back in

### ISSUE THREAD

**Issue by Nuggie-Eco** [StrangeLoopGames/EcoIssues#8181]
When mining the game crashes, if there are rocks on the ground it crashes again once i log back in.

![2018-06-27 2](https://user-images.githubusercontent.com/40638356/41985062-321c5e92-7a2a-11e8-9db8-2b3fe6d8a405.png)

**Comment by KytaSaeso** [comment]
Having the exact same issue myself.

**Comment by VAlex0** [comment]
Did happen to me too. Rejoining the game does not help.

What i did right before the crash:
* being about 10 blocks below surface
* have a minecart behind me
* mine blockes of stone on my level and 3 blockes higher then me (not directly above me)
* dont pick up the resulting stones on the ground
* on ~8th stone block mined -> crash

[crash.dmp.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2152714/crash.dmp.zip)

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2152713/error.log)


Once my server admin is back online we will try a server restart (gonna recomment then)

**Comment by VAlex0** [comment]
Server admin was here and could join the game without any problems. He found following situation:
* stone parts laying on the ground (nothing special here)
* my cart was turn upside down :/

So he picked up all of the stone, and i could join again.

yay!

**Comment by VAlex0** [comment]
Today it happend again, im now pretty sure the problem occurs when a stone falls on a character:

Stone falling down from 3blocks, now in my field of sight exactly when the game crashes.

![image](https://user-images.githubusercontent.com/23259122/42164149-5b3856d0-7e05-11e8-9082-bf7efa260b0a.png)

**Comment by VAlex0** [comment]
Can only be fixed if another person grabs all the rocks from the ground

**Comment by VAlex0** [comment]
Seams like the hotfix 7.5.1 did fix it. I tried it several times right now.

Thx devs!

**Comment by SeanAtr0n** [comment]
fixed in 7.5.1 hotfix
