### ISSUE TITLE
[7.5.0] Wrong Position for WoodSigns

### ISSUE THREAD

**Issue by Rick86** [StrangeLoopGames/EcoIssues#8182]
Before 7.5 you could put Signs IN FRONT of Walls or "hang" it on the Wall. Now (because of world convertation) the Signs are IN the Wall :/
This happens on:
SmallStandingHewnLogSign
SmallHangingHewnLogSign
LargeStandingHewnLogSign
LargeHangingHewnLogSign
SmallStandingStoneSign
LargeStandingStoneSign
[...]

I had 100+ Signs on the wall, now they are all IN the wall... Why you changed the position?!

**Comment by funnybunnyofdoom** [comment]
I don't know if it's a bug or a feature, but you can no longer place hanging signs against the wall. I also lost many of my signs to this.

**Comment by BlazeGuy2** [comment]
@Rick86 Can you post screenshots of the signs?

**Comment by elfl0rd** [comment]
Sounds like this - https://github.com/StrangeLoopGames/EcoIssues/issues/8055

**Comment by Rick86** [comment]
@elfl0rd Could be the same, yes
@BlazeGuy2 See the screenshots
![sign_position](https://user-images.githubusercontent.com/38107858/41997970-d7604272-7a59-11e8-9754-da678c674463.jpg)

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8055
