### ISSUE TITLE
7.5.0 Staging AIState Flee break

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#8185]
![image](https://user-images.githubusercontent.com/6262198/41989203-52b006ea-79f3-11e8-895e-776c6cbd4036.png)

>	Eco.Simulation!Eco.Simulation.Agents.AI.States.AIStateFlee.Start(Eco.Simulation.Agents.Animal agent, Eco.Simulation.Agents.AI.AIState<Eco.Simulation.Agents.Animal> prevState, out double nextTickTime) Line 58	C#
 	Eco.Simulation!Eco.Simulation.Agents.AI.AIStateMachine<Eco.Simulation.Agents.Animal>.State.set(Eco.Simulation.Agents.AI.AIState<Eco.Simulation.Agents.Animal> value) Line 42	C#
 	Eco.Simulation!Eco.Simulation.Agents.Animal.SetState<Eco.Simulation.Agents.AI.States.AIStateFlee>() Line 55	C#
 	Eco.Simulation!Eco.Simulation.Agents.Animal.SetStateIfDifferent<Eco.Simulation.Agents.AI.States.AIStateFlee>() Line 64	C#
 	Eco.Simulation!Eco.Simulation.Agents.Animal.FleeFrom(Eco.Shared.Math.Vector3 position) Line 160	C#
 	Eco.Gameplay!Eco.Gameplay.Animals.AnimalEntity.TryApplyDamage(Eco.Shared.Networking.INetObject damager, float damage, Eco.Gameplay.Interactions.InteractionContext context) Line 77	C#
 	Eco.Mods.dll!ArrowEntity.Hit(Eco.Shared.Networking.NetObjAttachInfo hitAttachInfo, Eco.Shared.Math.Vector3 position) Line 105	C#
 	[External Code]	
 	Eco.Shared!Eco.Shared.Networking.RPCManager.TryInvoke(object controller, string methodname, Eco.Shared.Serialization.BSONObject bsonArgs, out object result) Line 223	C#
 	Eco.Shared!Eco.Shared.Networking.RPCManager.InvokeOn(Eco.Shared.Serialization.BSONObject bson, object controller, string methodname) Line 197	C#
 	Eco.Shared!Eco.Shared.Networking.RPCManager.HandleReceiveRPC(Eco.Shared.Networking.INetClient client, Eco.Shared.Serialization.BSONObject bson) Line 320	C#
 	Eco.Plugins!Eco.Plugins.Networking.NetworkServer.ReceiveEvent(Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) Line 154	C#
 	Eco.Shared!Eco.Shared.Networking.NetObject.ReceiveEvent(Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) Line 69	C#
 	Eco.Plugins!Eco.Plugins.Networking.Client..ctor.AnonymousMethod__52_1() Line 113	C#
 	[External Code]

**Comment by SeanAtr0n** [comment]
fixed
