### ISSUE TITLE
Can´t Join 7.5 Single Player or Multiplayer Games

### ISSUE THREAD

**Issue by Randaris** [StrangeLoopGames/EcoIssues#8186]
Hello,
i have a Problem to Join Single Player oder Multiplayer Games.
I have Reinstall the Game 3 times, and delete all files from PC.
Install the Game, Ecoserver.exe runs without Errors, but i cant join.
Game Loads 100% and freeze for 1-2 Seconds and bring me Back to Desktop.
All Drivers Up to Date, 7.4.7 Games Running 100%
Steam Founds no error Files

**Comment by Randaris** [comment]
Ok Finish, Exit Steam Delete Files, start Steam New install and it Works

**Comment by BlazeGuy2** [comment]
Sounds like you solved the issue.  Closing.
