### ISSUE TITLE
USER ISSUE: Excavator - Stockpile

### ISSUE THREAD

**Issue by ShoxTech** [StrangeLoopGames/EcoIssues#8187]
**Version:** 0.7.5.0 beta

**Steps to Reproduce:**
1. Place an excavator and enter it. 
2. Fill your inventory/shovel with any world materials for 		  example earth and stone.
3. Put the content of your shovel/inventory ínto a stockpile.
4. Press the LMB like you're trying to fill up the shovel again.	

**Expected behavior:**
It should pick up the materials which you're digging for.

**Actual behavior:**
Your shovel contains the items you transfered to the stockpile before.

http://shox-tech.goip.de/stuff/2018-06-27_19-27-14.mp4

**Comment by SlayksWood** [comment]
Checked on 8.1. Wasn't able to reproduce, seems fixed.
