### ISSUE TITLE
Truck sound issue

### ISSUE THREAD

**Issue by WolfChieftain** [StrangeLoopGames/EcoIssues#8189]
Steps to Reproduce:
Craft, get a truck.

Expected behavior:
You drive a truck, you heard a engine. everything good.

Actual behavior:
If you don't put gasoline in it, it sounds like a wooden cart being pulled. if you put gasoline in it, it sounds like a powered cart, not like a truck.

**Comment by Nanders** [comment]
This will be fixed in upcoming  hotfix
