### ISSUE TITLE
Truck flies up

### ISSUE THREAD

**Issue by WolfChieftain** [StrangeLoopGames/EcoIssues#8190]
Steps to Reproduce:
Get a truck, drive it.

Expected behavior:
Truck drives around corners and straight roads without problems.

Actual behavior:
Every time you make a turn on a stone road, it glitches and flies up in the air.

**Comment by Amphysbaenas** [comment]
suprised that it's just medium priority, we can not use anymore trucks so on 4km² world with road cities etc people stop to play because they can not transport things as before and wait for a patch .....

**Comment by WolfChieftain** [comment]
We need to have patience until the devs fix it. the steam truck doesnt seem to have this problem @Amphysbaenas

**Comment by SeanAtr0n** [comment]
If you can reliably reproduce the behavior somewhere in your world could you send us your Game.eco file and the coordinates?

**Comment by Myrhaug** [comment]
We got the same problem at our server.
When we drive upwards on a ramp, the trucks flipping evrywhere (you can land several hundred yards from where you tried to drive).
As for now I only have tested Truck and it seems to be problem on almost all ramps.

**Comment by elfl0rd** [comment]
Looks like this - https://github.com/StrangeLoopGames/EcoIssues/issues/7612 ?

**Comment by Myrhaug** [comment]
Yes! And sometimes even worse then your clip about it

**Comment by SeanAtr0n** [comment]
fixed in svn for 7.5.1
