### ISSUE TITLE
Placing logs doesn't play nice with other interactions

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#8191]
@keegan-o noted if you are holding logs and also the property tool, you can right click to both claim and place the log.  Interacting is never supposed to do 2 things like that, so I'm guessing something is returning InteractResult.NoOp when it should be returning InteractResult.Success, or else maybe the log placing is not part of the normal interact system?  I couldn't actually find where placing logs was.

**Comment by GophTheGreat** [comment]
Since you can't equip the land claim stake while holding logs, I think this is no longer a problem. Closing.
