### ISSUE TITLE
USER ISSUE: Small Hanging Stone Sign offset bug

### ISSUE THREAD

**Issue by Aintence** [StrangeLoopGames/EcoIssues#8195]
**Version:** 0.7.5.0 beta

**Steps to Reproduce:**
1. Craft sign in title
2. Try place it on wall
3. See the bug

**Expected behavior:**
It should rotate around the block, look like its hanging off the wall when in correct position

**Actual behavior:**
It seems to be offset by 1/2 block. Placing it in correct rotation will put sign inside block you are hanging it on.

**Comment by elfl0rd** [comment]
refers to https://github.com/StrangeLoopGames/EcoIssues/issues/8055

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8055
