### ISSUE TITLE
[7.5.0] Running into people causes client crash (Access Violation)

### ISSUE THREAD

**Issue by miketek1** [StrangeLoopGames/EcoIssues#8196]
When someone runs into you with a vehicle or no vehicle, it causes the game to crash. This has happened to me 4 times. One of which I did to someone else. The error says Access Violation.
[error1.log](https://github.com/StrangeLoopGames/EcoIssues/files/2142799/error1.log)
[error2.log](https://github.com/StrangeLoopGames/EcoIssues/files/2142801/error2.log)
[error3.log](https://github.com/StrangeLoopGames/EcoIssues/files/2142806/error3.log)

**Comment by miketek1** [comment]
I find that this may also be related to ramps. It seems to happen more when people are standing on ramps. It's as if they get pushed into the ramp. Causing the crash, as in prior version 7.4.6 and others when you would place a ramp on top of someone it would cause a black screen, but wouldn't crash your game. You than have to remove the ramp and the person will be okay.

**Comment by SeanAtr0n** [comment]
fixed in next hotfix
