### ISSUE TITLE
Truck sound like Powered Cart

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#8204]
**Version:** 0.7.5.0 beta
Is this intended?
Old sound in 7.4.x > new sound 7.5.0

Reproduce:
Drive the Truck after you figured out how to refuel it.

what happens:
Truck sounds like Powered Cart

whats expected to happen:
Truck sounds like a Truck to differentiate it from the powered cart

**Comment by WolfChieftain** [comment]
Yea I reported this bug before you did, seems like more people have this problem @gamerpaddy

**Comment by SeanAtr0n** [comment]
@Nanders fixed the audio in the next hotfix
