### ISSUE TITLE
Skid-steer picks up from nearby stockpile instead of digging

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#8207]
**Version:** 0.7.5.0 beta
As title says. heres a video about it.  
unloading into a stockpile works only if youre almost standing in it causing it to glitch
but loading from a stockpile works from many meters away making digging impossible 
https://youtu.be/eDFLi-oOVQo

reproduce: see video
dig with a skidsteer or excavator near stockpile filled with dirt

expected:
it digs away material infront 

actual:
it takes the stockpile materials as much as it can

**Comment by mirasrael** [comment]
Wasn't able to reproduce on 8.2. Seems fixed.
