### ISSUE TITLE
Skid-steer cannot unload into trucks

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#8208]
**Version:** 0.7.5.0 beta
https://i.imgur.com/0SLClAI.jpg
nothing happens when i right click

reproduce:
get skid-steer full of materials
try to unload into anything else than a stockpile

expected:
unloads into the truck

actual:
holds its stuff and doesnt do anything

**Comment by SeanAtr0n** [comment]
Fixed in 7.6
