### ISSUE TITLE
Skid-steer randomly digs blocks below it without pressing left mouse.

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#8209]
**Version:** 0.7.5.0 beta
causing it to get stuck. happens randomly, not only in digging / work mode, doesnt need left mouse to be pressed.  commonly happens when driving and hitting something 

reproduce:
use skid-steer
drive, dig, use it. it happens randomly not 100% sure how to reproduce it everytime

expected:
no blocks picked up without being in work mode and without having Left mouse pressed.
especially no blocks that are lower than the ground the vehicle is driving on

actual:
blocks being picked up randomly causing skidsteer to get stuck in the hole.

**Comment by SeanAtr0n** [comment]
fixed in next hotfix
