### ISSUE TITLE
USER ISSUE: eco joining game 

### ISSUE THREAD

**Issue by sl4ught3rxlg** [StrangeLoopGames/EcoIssues#8216]
**Version:** 0.7.5.0 beta

**Steps to Reproduce:**
i load game up gets to 100% then just freezes and says report log 

**Expected behavior:**

**Actual behavior:**
hi i go to load into our dedi server it gets to 100% then crashes  this only started happening after me trying to place the new lift i placed it after that game glitched out and now wont let me back into server

**Comment by Moor718** [comment]
Hi,
there is already another Issue with that Problem. #8213

**Comment by Moor718** [comment]
I found a temporary fix. Download the 32-bit version of the game from the website and use it. This works, but I have no clue why xD

**Comment by Moor718** [comment]
nope. just register on the website and link your steam account to the account!

Register, then login and go on Account... scroll down and find "link steam", there you can insert your steam name. after that you have the ability to download the game and server files from the account page.

**Comment by sl4ught3rxlg** [comment]
ok thanks just downloading now hope it works

**Comment by Demosthenexx** [comment]
I can confirm similar problem. 32 bit works, 64 bit crashes. 

I'm now using some mods, but the same crash happened in straight vanilla.

My output.log is attached, it mentions Mono missing libc libraries. That's confusing given I'm on Windows 7.

TL:DR; Windows 7, Eco 7.5.0 and 7.5.1, vanilla and modded, crashes on entering world. 100% then dies, no crash dump, only output.log available. 64 bit fails consistently, 32 bit works.

**Comment by BlazeGuy2** [comment]
Put out a hotfix.  Open another issue if this problem persists.
