### ISSUE TITLE
[7.5.0] Crash while loading world

### ISSUE THREAD

**Issue by disfated** [StrangeLoopGames/EcoIssues#8217]
While connecting to server I get app crash.
Last indicated step is "Loading world 100%"

![image](https://user-images.githubusercontent.com/430542/42030563-aee67170-7aec-11e8-91bb-60a7ac7688d2.png)

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2144992/error.log)
[crash.dmp](https://yadi.sk/d/Y5IhTHDZ3YXdre)

**Comment by BlazeGuy2** [comment]
Closing as dup of #8218
