### ISSUE TITLE
7.5.0 Crash if I starting the world

### ISSUE THREAD

**Issue by Crushhead** [StrangeLoopGames/EcoIssues#8218]
[log_180626052920.log](https://github.com/StrangeLoopGames/EcoIssues/files/2145172/log_180626052920.log)

**Comment by Crushhead** [comment]
While connecting to server I get app crash.
Last indicated step is "Loading world 100%"

**Comment by Crushhead** [comment]
The game not create new log files

**Comment by johnkslg** [comment]
@Crushhead Please message me on Discord.gg/eco @johnk
Working on this now

**Comment by metachronism** [comment]
consolidating into #8443
