### ISSUE TITLE
Tractor module will be lost if attached and tractor picked up

### ISSUE THREAD

**Issue by WizyTheNinja** [StrangeLoopGames/EcoIssues#8219]
Version: 0.7.5.0 beta

Steps to Reproduce:
Place Steam Tractor
Attach any module to it
Pick up tractor with hammer

Expected behavior:
Either message stating module attached and needs to be removed first
Attachment gets picked up

Actual behavior:
Tractor gets picked up and attached module is lost.

**Comment by craig-jong** [comment]
When hammered, the vehicles need to check all their inventories (or at least the modules inventory) and return stuff. It should already do this for their storage component, so that can be some sort of guide.
