### ISSUE TITLE
Wheel glitch

### ISSUE THREAD

**Issue by WolfChieftain** [StrangeLoopGames/EcoIssues#8221]
Version: 0.7.5.0 beta

Steps to Reproduce:
Get a cart, vehicle park it on road or dirt.

Expected behavior:
Cart, vehicle sits on the ground.

Actual behavior:
Wheels partially go through the ground, I'm not sure if this is a issue. It just looks weird. 
![graphical bug](https://user-images.githubusercontent.com/36776317/42048678-3db73c24-7b04-11e8-8986-3cf571bd5172.png)

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/7905

**Comment by SeanAtr0n** [comment]
ideally all of our vehicles should support some sort of suspension as the physics model requires a bit of movement

**Comment by elfl0rd** [comment]
@SeanAtr0n it's duplicate :P

**Comment by mirasrael** [comment]
Duplicate of #7905
