### ISSUE TITLE
[7.5.0] Cannot place blocks where a stockpile was

### ISSUE THREAD

**Issue by Connor-Kerwin** [StrangeLoopGames/EcoIssues#8222]
Issue:
After placing a stockpile, then destroying it there is no way to place blocks within its old 5x5x5 area. The game simply says "Can't place a block there"

The issue happens anywhere (inside or outside claimed land).

**Comment by craig-jong** [comment]
I can't reproduce this. If you can provide a save file where this occurring that would be helpful.

Please reopen the bug if this happens again/you have a save file I can check out.
