### ISSUE TITLE
[7.6.0] Some world objects causing crash in game

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8227]
Might be related to /testelevator, which is another bug.  /allworldobjects crashes the client without fail every time

**Comment by BlazeGuy2** [comment]
the command creates this exception:
![unity_allobjects](https://user-images.githubusercontent.com/35509188/42064260-70ab463a-7aea-11e8-8b5d-92e891591293.PNG)

**Comment by BlazeGuy2** [comment]
Server has this exception
![server_crash](https://user-images.githubusercontent.com/35509188/42064949-3032b572-7aed-11e8-8bd2-554337b93d7b.PNG)

**Comment by SeanAtr0n** [comment]
I fixed the elevator, the AirPump is a separate issue... maybe craig knows whats changed w/ it... looks like it'd probably work if the object itself had a pipe component

**Comment by craig-jong** [comment]
The air pump is not a valid item. It should probably be removed, although I guess this still needs fixing if we want to use the air pump component at some point.

**Comment by elfl0rd** [comment]
check large windowed lumber door, it's crashed for me.

**Comment by craig-jong** [comment]
HOW DID THE ROBOTIC SPIDERS GET EVERYWHERE

**Comment by craig-jong** [comment]
Fixed in staging
