### ISSUE TITLE
[0.7.6.0] /testelevators Breaks the Game

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8228]
Invoking /testelevator causes 7.6.0 to crash

**Comment by SeanAtr0n** [comment]
any error msg from the server?

**Comment by SeanAtr0n** [comment]
works for me in staging...

**Comment by BlazeGuy2** [comment]
Just replicated on the steam built version; client just closes w/o a pop-up.  Did you test this while running the client and server in release mode?

**Comment by BlazeGuy2** [comment]
![elevator](https://user-images.githubusercontent.com/35509188/42063530-fd25a366-7ae6-11e8-9a6c-57cf8e03fcb9.PNG)

**Comment by BlazeGuy2** [comment]
Elevator is throwing an UnassignedReferenceException with the up button.  It doesn't crash Unity, but the .exe client just closes.

**Comment by SeanAtr0n** [comment]
fixed in svn
