### ISSUE TITLE
Adjust 3rd Person Camera perspective for truck

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8229]
_From @BlazeGuy2 on May 31, 2018 20:51_

Kind of hard to see what's in front of me when I drive a truck at the moment, maybe try something like what Watch Dogs 2 does.

**Eco**
![3rdpersoncamera_truck](https://user-images.githubusercontent.com/35509188/40807604-a2e372de-64d9-11e8-8341-3092cf7568de.png)
**Watch_Dogs 2**
![cameraexample](https://user-images.githubusercontent.com/35509188/40807627-b35ccdcc-64d9-11e8-8e9b-e1e6bf048fe8.jpg)

_Copied from original issue: StrangeLoopGames/EcoSuggestions#380_

**Comment by WolfChieftain** [comment]
I've suggested this in Ideafactory on discord, didn't know it could be posted here

**Comment by BlazeGuy2** [comment]
Ideas typically go to Eco Suggestions.

**Comment by SeanAtr0n** [comment]
fixed whenever https://github.com/StrangeLoopGames/Eco/pull/3015 is merged
