### ISSUE TITLE
Weird water physics (bug?)

### ISSUE THREAD

**Issue by WizyTheNinja** [StrangeLoopGames/EcoIssues#8231]
Sometimes whenever I go into the water, I am unable to dive unless I exit the water and go back in. Other times I cannot leave the water for some time, it refuses to climb up even 1 block shores unless I completely stop moving for a few seconds. Typically happens if I jump ontop of something in the water, or dive into the water from some distance. Has also happened jumping ontop of a truck that flung into the water.

**Comment by BlazeGuy2** [comment]
What version of the game is this occurring in?

**Comment by WizyTheNinja** [comment]
0.7.6.0

**Comment by D3nnis3n** [comment]
Seems indeed fixed, reopen if it reoccurs.
