### ISSUE TITLE
USER ISSUE: World refuses to load

### ISSUE THREAD

**Issue by NeverGoatWest** [StrangeLoopGames/EcoIssues#8233]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
Literally just load a world, eventually streaming stops and you cant do anything

**Expected behavior:**
Streamed terrain near and far to me with different LoD's giving me the impression of living on a dwarf planet with its own eco

**Actual behavior:**
none, ingame world loader/streamer is broken to a game breaking point

**Comment by metachronism** [comment]
consolidating into #8443
