### ISSUE TITLE
cant draw on districts map

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#8234]
@shadow7412 said:
"Although laws and running for office works for me, defining districts does not.I get to the screen with the map where you are supposed to right-click and drag to define a district, but it doesn't mark the map. There is an icon that looks like an eraser which, when clicked, overlays with a pencil icon. Clicking this does nothing...Would screenshots help?"

**Comment by rainfarmer** [comment]
@SeanAtr0n how would we troubleshoot the map not drawing?

@shadow7412 what browser are you using? Can you press f12 and see if there are any errors.

**Comment by shadow7412** [comment]
There wasn't at the time, or at least I don't think so. I was using Chrome.
I'll try to remember to have another go tonight.

**Comment by SeanAtr0n** [comment]
you have to click add district before drawing

**Comment by shadow7412** [comment]
Same deal.

Propose New Law -> on law passed -> redefine districts

![image](https://user-images.githubusercontent.com/286341/42124378-ec37f030-7ca4-11e8-933c-982b57806eaa.png)
Can't draw districts by holding right click, which is what the instructions are telling me to do. There is nothing in the console.

So there are two problems here in my opinion.
1. This is pretty well hidden - was surprised there wasn't a "propose new..." type button on the view districts page.
2. If this isn't the correct way to create a new district, then I can't find that option at all. The instructions at the top of the map view are incorrect in that scenario though.

**Comment by shadow7412** [comment]
As a side, when testing this functionality I noted that if I attempted to navigate to the Propose New Law area from another area in the webpage, i was getting a blank error message at the top.

![image](https://user-images.githubusercontent.com/286341/42124419-929e12a6-7ca5-11e8-9352-6436aa54f277.png)

Navigating to to it directly via the "(+) Propose Law" button in-game worked, but not being able to do so via the webpage seems like a bug.

**Comment by shadow7412** [comment]
Ok, I just had another look at that screenshot and realised what you meant by the "Add New District" button.

Although I'm now feeling slightly gooseish - I feel that the UI could be improved by swapping the list and the map around (so the list of districts, as well as the "add new" button is on the left, and the map on the right) as that will probably help with flow.

However, now that I have cracked through that barrier, I'm now getting a "you must complete the form" error message.

* The name is populated
* The clauses section contains the same as the screenshot above
* A district has been painted and named
* The reasoning has been populated.

**Comment by rainfarmer** [comment]
Thanks for the ui feedback, we will be updating all the ui eventually.

We're working on that empty red bar error.

Do you get both an empty red bar and "you must complete the form" error?

Perhaps when you were testing and changing things around back and forth, which messed it up. 
Can you confirm that starting a fresh district law still gets "you must complete the form" ?

**Comment by shadow7412** [comment]
I tried it again - Clicked on propose law (in game) which took me to the website where I filled out the form to create a new district. I still got the error.

I tried to repeal citizenship so that you could jump onto my server - but it turns out I can't even do that (getting the blank error message).

Either way, if it helps, I'll leave the server running at eco.skhuf.net. It's a fresh install from when I started testing this ticket early this week.

**Comment by Tigran07** [comment]
The issue is fixed

**Comment by rainfarmer** [comment]
empty red bar issue is being tracked here: https://github.com/StrangeLoopGames/EcoIssues/issues/7990
