### ISSUE TITLE
Command Issue: /spawnplant 

### ISSUE THREAD

**Issue by ZeelNightwolf** [StrangeLoopGames/EcoIssues#8237]
/spawnplant spawns the plant at 1 level lower than the player therefor the plant digs itself a hole.

![image](https://user-images.githubusercontent.com/29911902/42076761-d2e75ecc-7bb9-11e8-950f-88f946364f2a.png)

**Comment by FishAus** [comment]
It appears the position of the user is being returned as the block the player is standing on and not the block their feet are in now. which means any command requiring position check is 1 y block lower for the check.

**Comment by craig-jong** [comment]
Fixed in staging
