### ISSUE TITLE
USER ISSUE: wrong languade in Localization string.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8238]
**Version:** 0.7.6.0 beta staging-4767aa88
https://crowdin.com/translate/eco-by-strange-loop-games/3/en-ru#26636
![20180629120449_1](https://user-images.githubusercontent.com/4980243/42084225-c1448ae2-7b95-11e8-951a-e76e1582a8cd.jpg)
@Nanders 
*Localization

**Comment by Nanders** [comment]
Fixed
