### ISSUE TITLE
[7.5.1] Client crash on login / UnityPlayer.dll caused an Access Violation

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8239]
Client crashes when trying to logon to Server:

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2149038/error.log)
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2149039/output_log.txt)
[crash.dmp.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2149044/crash.dmp.zip)

**Comment by Voosle** [comment]
also with 7.5.0: #8177

**Comment by Darklord6229** [comment]
Also having this issue when glitched in a wall etc. 
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2150706/error.log)

**Comment by miketek1** [comment]
We have found on our server that is happens when people get stuck in ramps. If the person logs on you can get their coordinates quickly enough to see where they are at and pick up the ramps in the area and they will be able to get back into the world.

**Comment by Voosle** [comment]
Got a crash like this, too:
[Crash_2018-06-29_120634.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2151072/Crash_2018-06-29_120634.zip)

**Comment by Voosle** [comment]
@miketek1 We will try this...

**Comment by Voosle** [comment]
@miketek1 It worked! We removed a Ramp and the player joined again without an error.

**Comment by miketek1** [comment]
@Voosle glad to hear it worked.

**Comment by X-ITT** [comment]
@Voosle oh geez I'm shocked considering I was told the majority of though's who are getting that access violation is do to a windows 7 bug issue and that you have to have "the owner clear connections." But i'm glad you didn't have to do unnecessary mumbo jumbo to fix your issue.

**Comment by SeanAtr0n** [comment]
fixed in next hotfix
