### ISSUE TITLE
Game Crashed, and will not allow me to re-enter world.

### ISSUE THREAD

**Issue by KytaSaeso** [StrangeLoopGames/EcoIssues#8240]
Hi there, as the title really, I was mining and the game crashed, i reconnected, but the blocks mined had all vanished, so I disconnected to restart the game fully, and now can not re enter the world.

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2149262/error.log)

**Comment by KytaSaeso** [comment]
I have just discovered this bug is repeatable, it seems to happen when mining if you break too many blocks, it is like there are too many entities and so it causes an error. new logs attached.
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2150060/error.log)

**Comment by KytaSaeso** [comment]
If you can get back into the game and turn away from the falling entities it is possible to correct the error and stay connected it would seem. I am therefore more certain than ever that this is caused by the falling entities when mining

**Comment by X-ITT** [comment]
Or have another person remove the the entities in the way of the location your player is at, this will most likely be a ramp. You can find that location by logging in, a different person should see your location on their map then go to it, remove entities in the way, and try logging back in again.

**Comment by SeanAtr0n** [comment]
fixed in next hotfix

**Comment by VAlex0** [comment]
@SeanAtr0n this might be clones:

https://github.com/StrangeLoopGames/EcoIssues/issues/8181
https://github.com/StrangeLoopGames/EcoIssues/issues/7640

Please close them too if thats true, thx!
