### ISSUE TITLE
Bow Efficiency and Mining Efficiency skills do nothing

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#8241]
**Version:** 0.7.5.1 beta

The **Bow Efficiency** skill does nothing, except unlock **Bow Damage** at level 1, even though the skill has 5 levels.

It looks like the **Hunting** specialty actually decreases calorie consumption from using a bow per level, but specialties only have one level.

I am guessing that the calorie consumption reduction is suppose to be for the **Bow Efficiency** skill instead of the **Hunting** specialty, since that would make it similar to the **Logging** specialty's **Logging Efficiency** skill.

This is at least what the tooltips say.

**Comment by Deantwo** [comment]
Just found the same issue with **Mining** and **Mining Efficiency**.

The **Mining** specialty decreases calorie consumption of pickaxe, but the **Mining Efficiency** skill does nothing.

**Comment by Deantwo** [comment]
The tooltip of the **Mining Efficiency** seem to be fixed.

But **Bow Efficiency** still says nothing.

**Comment by D3nnis3n** [comment]
#10714 Addition:
"Clothes Making Speed:
It looks like no Recipes use Clothes Making Speed to improve their craft time."

**Comment by Deantwo** [comment]
This will hopefully not be an issue after v8.0, so just gonna close this.
