### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Chrodegang** [StrangeLoopGames/EcoIssues#8242]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**

**Expected behavior:**
It should have parked a cart backwards by the end of a dirt ramp

**Actual behavior:**
The following error message popped up:
Eco [version: Unity 2017.4.2f2 (52d9cb89b362)]

UnityPlayer.dll caused an Access Violation (0xc0000005)
  in module UnityPlayer.dll at 0033:7a8afb05.

Error occurred at 2018-06-29_185526.
D:\Steam\steamapps\common\Eco\Eco.exe, run by Hajo.
41% memory in use.
16357 MB physical memory [9569 MB free].
18789 MB paging file [8015 MB free].
134217728 MB user address space [134206026 MB free].
Read from location ffffffff caused an access violation.

Context:
RDI:    0xae01c480  RSI: 0xade48f50  RAX:   0xb84e1e00
RBX:    0xe814e038  RCX: 0xae01c480  RDX:   0xe814d8e0
RIP:    0x7a8afb05  RBP: 0xe814e000  SegCs: 0x00000033
EFlags: 0x00010206  RSP: 0xe814d8a0  SegSs: 0x0000002b
R8:    0xae01c480  R9: 0xade48f50  R10:   0x00000004
R11:    0x7ec2e544  R12: 0x00000001  R13:   0xe814e000
R14:    0xe814e038  R15: 0x00000000

Bytes at CS:EIP:
ff 90 08 01 00 00 f6 00 04 74 06 80 7b 1c 00 74 

```

**Comment by SeanAtr0n** [comment]
fixed a while back
