### ISSUE TITLE
2 crash logs

### ISSUE THREAD

**Issue by duschott** [StrangeLoopGames/EcoIssues#8246]
going to attach.  Both times it crashed at random so i cant replicate. 

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2151076/error.log)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2151078/error.log)

idk if that worked on copy drag.

**Comment by Mr-Blue-RL** [comment]
Im also having these two crash logs. Happens at random and causes you to not play in a certain server you crashed in. Very frustrating.

**Comment by miketek1** [comment]
@duschott @Mr-Blue-RL We have had this happen on our server with players, it happens either well mining or when placing ramps. Have a buddy be there when you sign in, get your location when you sign in, before it crashes and remove the ramps from the area you were in. Also if there is any loose stone near by this can also cause the same problem so pick up the loose stone and than re log. Hope this helps for you guys.

**Comment by Mr-Blue-RL** [comment]
Mine happened when I was using a cart. I grabbed the cart and then I crashed. Could it be becuz I was a ramps when doing so?

**Comment by SeanAtr0n** [comment]
Fixed in next hotfix
