### ISSUE TITLE
USER ISSUE: Electric Wall Lamp must be on ground

### ISSUE THREAD

**Issue by carsonbarlow** [StrangeLoopGames/EcoIssues#8247]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
Place an Electric Wall Lamp on a wall.
Connect Electric Wall Lamp to power network with sufficent power.

**Expected behavior:**
Light turns on.
No requirement for it to be on ground.

**Actual behavior:**
Light remains off.
Requirements indicate it must be on ground.

**Comment by elfl0rd** [comment]
Dupe :( https://github.com/StrangeLoopGames/EcoIssues/issues/7879

**Comment by MarjieAVolk** [comment]
@elfl0rd, sorry no one saw your comments on the closed issue.

**Comment by elfl0rd** [comment]
@MarjieAVolk these fixed in 7.6 but not merged to 7.5 :(

**Comment by MarjieAVolk** [comment]
Oh really.  Okay, fixed in 7.6 then.
