### ISSUE TITLE
USER ISSUE: Chat scrolls up automatically 

### ISSUE THREAD

**Issue by babam93** [StrangeLoopGames/EcoIssues#8248]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
Scroll down 

empty the truck with my shovel 
or dig 
Chat scroll up automatically

**Expected behavior:**
should be at the last post 

**Actual behavior:**
it scrolls to the middle or at the beginning

**Comment by Demosthenexx** [comment]
Same issue (7.5.1 on Win7). Try to scroll to the bottom, it keeps jumping midway up the buffer. Tried turning off some notifications, same issue. I have seen weird flashes of text outside the bounding box of the chat window while scrolling. Closing and reopening the chat window (C key) can put it back at the bottom temporarily, and shows a brief flash of text outside the bounding box (scroll history?).

**Comment by Amphysbaenas** [comment]
Same problem for me

**Comment by MarjieAVolk** [comment]
Hm that sounds very strange.  I don't believe I have seen this behavior yet.  If anyone does get an idea of what causes it to happen, let me know.

**Comment by babam93** [comment]
anyone from our server got this 
phenomenon as well. sometimes the chat scrolls up without any command or action

**Comment by MarjieAVolk** [comment]
Think it's related to the server?  Maybe you have to have a large chat log in order for it to happen, or have chat activity going on.

**Comment by babam93** [comment]
dont think so 
we changed the host of the server, the game was 2 times reinstalled and we play the vanilla without mods... :/ 
The both others arent on our server

**Comment by MarjieAVolk** [comment]
@johnkslg I'm assuming this is related to the fancy scroll box stuff

**Comment by Demosthenexx** [comment]
I'm specifically referring to the chat window with scrolling, not the temporary popup chatbox. I've reduced the number of notification types I receive, and it still scrolls back. It seems to prefer the middle of the scrollback buffer.

**Comment by gregoryl09** [comment]
This issue is present on a fresh server on 7.6 as well. There are very few people on this server. I've attempted to reduce chat notifications and/or resize the window. No matter what, it keeps scrolling up whenever I perform actions.

**Comment by D3nnis3n** [comment]
I'd like to bring this issue up again:
It starts when you work much that has to do with chatmessages. E.g. picking up or hammering things. You can stop it by deselecting general chat and activating it again. Hopefully this helps.

**Comment by Splutty** [comment]
This is still happening to all of us in our server (0.8.0.3), It has to do with the cleaning up of the information text lines for picking something up, dropping something, and warnings that your inventory is full.

If you have a lot of those , then you can actually see them disappearing and the chat going bonkers right after that with characters in a one or two wide column appearing vertically above your chatbox, and the chatbox resetting itself to somewhere in the past.

Disabling/enabling the chat window in question on the left, or enabling/disabling one that's disabled will redraw the chat window and fix it, for a little while at least.

Reproduce: Take a cart to a wall, mine the whole wall into your cart as quickly as you can, wait until chat goes bonkers.

**Comment by HetNeSS** [comment]
Very annoying
