### ISSUE TITLE
[7.5.1] Wrong popup receipt for Hand Plough

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8251]
The popup says "4 Iron Bars" but "Iron Ingots" are needed.

![image](https://user-images.githubusercontent.com/22961978/42119540-653567bc-7c0d-11e8-9e39-81c7295f4b12.png)

**Comment by SlayksWood** [comment]
Checked on 8.1.3. Wasn't able to reproduce, seems fixed.
