### ISSUE TITLE
USER ISSUE: Ceo error and must close

### ISSUE THREAD

**Issue by hairmiya** [StrangeLoopGames/EcoIssues#8252]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
At slg testing server 7.5.0. In 3(H)*2(W)*4(L) cave, Build one dirt ramp at myself underfooting.

**Expected behavior:**
The dirt ramp was successful and me stood on the ramp.

**Actual behavior:**
Eco error and must close, Enter the test server again for a moment to error and must close. Enter the other server is allright. please help me.
 
The error log:
Eco [version: Unity 2017.4.2f2 (52d9cb89b362)]

Eco.exe caused an Access Violation (0xc0000005)
  in module Eco.exe at 0033:00000001.

Error occurred at 2018-06-30_104236.
E:\Program Files\Steam\steamapps\common\Eco\Eco.exe, run by SHH.
29% memory in use.
16269 MB physical memory [11545 MB free].
16267 MB paging file [10181 MB free].
8388608 MB user address space [8385710 MB free].
Write to location 00000001 caused an access violation.

Context:
RDI:    0x9522c9c0  RSI: 0x5ba68190  RAX:   0x94f520d0
RBX:    0x0019e2b8  RCX: 0x9522c9c0  RDX:   0x0019db60
RIP:    0x00000001  RBP: 0x0019e280  SegCs: 0x00000033
EFlags: 0x00010206  RSP: 0x0019db18  SegSs: 0x0000002b
R8:    0x9522c9c0  R9: 0x5ba68190  R10:   0x00000004
R11:    0x0c6d9ea4  R12: 0x00000001  R13:   0x0019e280
R14:    0x0019e2b8  R15: 0x00000000

**Comment by SeanAtr0n** [comment]
fixed in next hotfix
