### ISSUE TITLE
USER ISSUE: Tailings

### ISSUE THREAD

**Issue by EiKiDa** [StrangeLoopGames/EcoIssues#8255]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
Tailings isn't neutralized in buildings and stone mines!

**Expected behavior:**
There should be no groundpolution.

**Actual behavior:**
There is groundpolution.

**Comment by Deantwo** [comment]
That is not how tailings' ground pollution work.
See: https://eco.gamepedia.com/Tailings

**Comment by pamduncan** [comment]
You have to bury tailing to prevent them pollution the environment.  See the wiki section about tailings.  They are never neutralized but always pollute but the pollution can be contained by buring them at least 10 blocks deep

**Comment by GophTheGreat** [comment]
Closing as this isn't a bug.
