### ISSUE TITLE
fishing

### ISSUE THREAD

**Issue by Jerz1011** [StrangeLoopGames/EcoIssues#8256]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**

**Expected behavior:**
fish to be caught

**Actual behavior:**
no fish

**Comment by Deantwo** [comment]
No information.

I suggest reading the wiki page on how fishing works.
See: https://eco.gamepedia.com/Fishing_Pole

PS: Also check on the map where there are fish.

**Comment by elfl0rd** [comment]
Select right place to it.
![20180629185626_1](https://user-images.githubusercontent.com/4980243/42136642-243320ea-7d68-11e8-831c-f756f0ef01ca.jpg)
![20180630121103_1](https://user-images.githubusercontent.com/4980243/42136643-245287e6-7d68-11e8-9837-0186aaed9f37.jpg)

**Comment by craig-jong** [comment]
Closing this bug as not-a-bug. We did, in fact, fix a bug with the fishing pole recently, so that's nice.
