### ISSUE TITLE
Mac client version experiencing graphic issues

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8258]
Mac users report that on every server they go on they see missing parts of the world and what appears to be 'world tears'.  These same servers are used by others that are not experiencing these problems and not seeing this gaps or missing parts of the world.  This appears to only be happening with the Mac Client.  A few also have windows clients and when the switch to them the issues are not there.  this has been happening with every Mac user I have spoken with since 7.5 released

**Comment by SeanAtr0n** [comment]
Looks like something weird is going on with lower lods for grass

**Comment by SeanAtr0n** [comment]
low foliage quality:
![image](https://user-images.githubusercontent.com/774628/42198070-d4b792e8-7e3a-11e8-837f-6c7987574e07.png)
high:
![image](https://user-images.githubusercontent.com/774628/42198085-e66fc4d8-7e3a-11e8-9c75-e7fe09b7ebb7.png)

**Comment by SeanAtr0n** [comment]
note you can also see this by setting graphics emulation to shader model 3
