### ISSUE TITLE
USER ISSUE: No response from the master server

### ISSUE THREAD

**Issue by xForcer** [StrangeLoopGames/EcoIssues#8259]
Version: 0.7.5.1 beta

Steps to Reproduce / problem clarification:
Person A hosts the server, he plays fine. Person B joins normally and plays. Person C gets "No response from the master server" everytime. Person C played it just fine yesterday. Nothing changed. Server wasn't turned on in the meantime. Person C uninstalled the game, cleaned appdata, installed again, rebooted router, restarted PC. Person A (host) rebooted router, restarted PC, reinstalled the game, cleaned appdata, restarted server multiple times, started even a new world and still Person C can't join. It's not a profile issue. Person C can join other servers just fine. It's not on his end. Tried flushing DNS. 

Edit: The host sent me server and config files so I tried hosting the server. Now I can join normally because it's on my PC but the Person A, who was the host before, can't join and getting "no response from master server". Person B isn't online to test. We are both on the same internet providers

Expected behavior:
Person C enters the server and plays

Actual behavior:
Person C gets an error message "no response from the master server"

**Comment by pamduncan** [comment]
First you should try to delete the Eco appdata folder.  Also check your Firewall rules and make sure Eco.exe is allowed through.  In some cases your antivirus program can cause the connections to be blocked

**Comment by xForcer** [comment]
Few days passed. Now I (Person C) enters the server Person A hosted just fine, but the Person B can't join now, while he could few days ago.
The host has firewall disabled, He hasn't got an antivirus. He deleted appdata, uninstalled and installed the game. We all did that.

We really want to play so we'll try looking for a paid host

**Comment by metachronism** [comment]
@xForcer can you and each player reach eco.masterserver.strangeloopgames.com with a ping?

**Comment by Nightstaber** [comment]
Me and my girlfriend are experiencing this exact issue as well. We cannot join her brothers game, but his other friends can join the game. We get the "No response from master server" error. Both of us can join other games from the public server list with no problems.

@metachronism - We cannot ping that. "Ping request could not find host eco.masterserver.strangeloopgames.com. Please check the name and try again." I'd be kinda surprised if a ping was possible, as i'd expect that to be disabled, to avoid DDOS attacks, but i wouldn't know for certain.

**Comment by xForcer** [comment]
I can't ping it too. 

- We bought a game server and we are playing fine without any issues. This problem has to be only when a client is hosting from his PC

**Comment by metachronism** [comment]
pretty sure this is related to #8443
consolidating into #8443

**Comment by crystaldolphin** [comment]
Still having this issue #8537
