### ISSUE TITLE
If I set Dirt Ramp ..... game crashed

### ISSUE THREAD

**Issue by Crushhead** [StrangeLoopGames/EcoIssues#8260]
If I set Dirt Ramp ..... game crashed

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2152626/error.log)

**Comment by Deantwo** [comment]
I just crashed when placing a dirt ramp, I was inside where it was being placed. Screen turned black for a moment and then boom to desktop with a crash dump.

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2153074/error.log)
[crash.dmp.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2153075/crash.dmp.txt) (remove `.txt` from the filename)

**Comment by Deantwo** [comment]
Now I crash every time I try to rejoin the server, creating a new crash dump every time.


[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2153175/error.log)
[crash.dmp,txt](https://github.com/StrangeLoopGames/EcoIssues/files/2153176/crash.dmp.txt) (remove `.txt` from the filename)

**Comment by SeanAtr0n** [comment]
fixed in next hotfix
