### ISSUE TITLE
Report a Bug Dialog crash

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#8262]
When attempting to report a bug (#8261) with the in-game _Report a Bug_ dialog, I pasted in a special character name, `𝕲𝖑𝖔𝖗𝖎𝖔𝖚𝖘𝕭𝖎𝖗𝖇`, into the reproductive steps text field and had the client crash to desktop with a crash dump (that I not can't locate again after closing the folder).

When attempting to reproduce the issue the client seem to simply have froze, but sound is still playing and the window (playing in window mode) is not unresponsive.

**Comment by SlayksWood** [comment]
I can't paste this in report a bug window. Seems fixed.
