### ISSUE TITLE
Disconnected after seeing red plus disconnected icon

### ISSUE THREAD

**Issue by Serane155** [StrangeLoopGames/EcoIssues#8264]
Hey guys!
Since this is not the first issue i'm having with the game i'll post it back. Basically i try and login, i eventually enter the world and the world is a bit slow. Then i see the red icon with the plugs (i'm not sure what it indicates really...) 
when it fails it tells me "Connection failed" or I can't recall what. Also i can copy the issues on clipboard when i want to. So this is very frustrating... Can anyone help?
Oh and it also fails when i try and connect it usually fails after "connecting"

**Comment by Serane155** [comment]
Also i get the message "failed to establish a connection - no response from remote host"

**Comment by MarjieAVolk** [comment]
The icon with the plugs means you haven't gotten any responses from the server recently.  This can mean you got disconnected from the server, or more likely in this case it can mean that your connection is extremely slow or overloaded.

Does this happen with all servers?  Or only a specific server?

**Comment by MarjieAVolk** [comment]
Closing due to no response

**Comment by Serane155** [comment]
Hi sorry for not responding earlier. Yes, it does it with all servers whever it'd be multiplayer or solo gaming, it really does suck because the problem keeps repeating itself depsite the fact that i'd still try again whenever a new version of the game is out. I truly don't know what do.

**Comment by MarjieAVolk** [comment]
Hey no problem.  So you've been unable to play the game at all?  And you say you have the same problem even when running your own server?

The first things I would recommend that you check are your antivirus and firewall.  I would also ask about the quality of your internet connection; though I would hope that that wouldn't be an issue when connecting to your own server.

**Comment by MarjieAVolk** [comment]
Okay, closing due to no response again.
