### ISSUE TITLE
[7.5.1] Crash when ran into Elk

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8266]
The Client crashes, when an elk is running throw me:
[crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2152804/crash.zip)

![image](https://user-images.githubusercontent.com/22961978/42134593-460facc0-7d3f-11e8-9da4-b4dc90c054af.png)

**Comment by SeanAtr0n** [comment]
Fixed in next hotfix
