### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by a839474630** [StrangeLoopGames/EcoIssues#8267]
**Version:** 0.7.4.1 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:d
```
Invalid username or password.
```

<details>
<summary>Log File</summary>Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1070 (ID=0x1b81)
    Vendor:   NVIDIA
    VRAM:     8088 MB
    Driver:   24.21.13.9811
Begin MonoManager ReloadAssembly
- Completed reload, in  0.037 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.613378 ms
Setting up 3 worker threads for Enlighten.
  Thread -> id: 7244 -> priority: 1 
  Thread -> id: 2a3c -> priority: 1 
  Thread -> id: 1958 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Client version: 0.7.4.1 beta
Thursday, May 10, 2018 2:53 AM
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fallback handler could not load library D:/aliBoxGames/games/33675/Eco_Data/Mono/libc
Fallback handler could not load library D:/aliBoxGames/games/33675/Eco_Data/Mono/.\libc
Fallback handler could not load library D:/aliBoxGames/games/33675/Eco_Data/Mono/libc
Changing state: PreLogin -> PreLogin
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggingIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggingIn -> PreLogin
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggingIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggingIn -> PreLogin
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggingIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggingIn -> PreLogin
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggingIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggingIn -> PreLogin
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

</details>

**Comment by Deantwo** [comment]
0.7.4.1 beta? Are you intentionally using an outdated client version?

**Comment by BlazeGuy2** [comment]
Closed due to being on an outdated version.
