### ISSUE TITLE
USER ISSUE: Difficult to get out of water

### ISSUE THREAD

**Issue by mrgrr26** [StrangeLoopGames/EcoIssues#8272]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
1. Go in water.
2. try to get out of water with nothing under your feet.

**Expected behavior:**
I should be able to just go up to edge of water and jump out.

**Actual behavior:**
If you don't have a block to stand on next to the shore, it is extremely difficult to get out of the water.

**Comment by SeanAtr0n** [comment]
fixed in 7.6
