### ISSUE TITLE
Stuck in Dirt Ramp causing continuous crash to desktop

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#8273]
**Version:** 0.7.5.1 beta
**Server:** Centration Eco Server ([95.154.229.150:3110](http://95.154.229.150:3111/))
**Mods:** None

I just crashed when placing a dirt ramp, I was inside where it was being placed. Screen turned black for a moment and then boom to desktop with a crash dump.

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2153074/error.log)
[crash.dmp.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2153075/crash.dmp.txt) (remove `.txt` from the filename)

Now I crash every time I try to rejoin the server, creating a new crash dump every time.

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2153175/error.log)
[crash.dmp,txt](https://github.com/StrangeLoopGames/EcoIssues/files/2153176/crash.dmp.txt) (remove `.txt` from the filename)

Reinstall did nothing, might be server/world specific.

Possible duplicate: #8260

**Comment by SeanAtr0n** [comment]
could you send us the save file for this world and the name of your player?

**Comment by Deantwo** [comment]
My character is `Deantwo`, stuck on a Dirt Ramp at <460, 150>.

I asked the server owner/admin. _Noms_ you there buddy?

**Comment by X-ITT** [comment]
This _might_ help but requires a buddy on the server to fix it and if the following is applicable, if your name is displayed in the welcome chat when logging in. (your buddy needs watch the chat). Your buddy then has to see where on the map your location is. (it should display, if it doesn't then you can't do this.) If your name is displayed on the map your buddy should go to that location and delete the ramp or other entities near by. If that doesn't work then this fix won't help. (Do Not go around thinking you need to delete all ramps in the game...that would be foolish.) This fix should be tried before deciding to remove a player profile. I'll probably get crap by some support staff for helping you but w.e i'm tired of seeing people have this issue and seeing people go right to the complicated way of trying to fix it. I have not seen one support staff suggest trying this fix, it's quite ridiculous to watch.

**Comment by Deantwo** [comment]
A friend on the server removed the ramp for me and i am not free. I might have been standing on another ramp next to the ramp i was placing, or something.
If i have time and a helping hand later I can try to reproduce it, but shouldn't be too hard to do.

**Comment by Amphysbaenas** [comment]
exactly ythe same problem on Ecotopia:
1 player is stuck on a dirt ramp and no more able to login
1 player stuck in stoneroad and no more able to login too

**Comment by SeanAtr0n** [comment]
I was able to login as both players in that save w/o any errors or warnings so I'm starting to suspect it could be related to physics acceleration hardware.

Do you know what graphics card the stuck players are using?

**Comment by Amphysbaenas** [comment]
i use 960 gtx nvidia card

**Comment by Amphysbaenas** [comment]
rene use nvidia gtx 780

**Comment by gironimo84** [comment]
Hello, i have exact the same issue on a private server. only my brother and i play on this server. I placed 
accidently a dirt ramp, when i was inside the ramp. Every time i tried to connect to the server, the game crashes to the desktop and i get a crashlog. My brother cant help me for the next to weeks. Is there a possibility to reset my spawn point in the serveroptions to an other location?
I use a gtx 1080 ti.
thanks. :-)

**Comment by SeanAtr0n** [comment]
I was able to repo the issue and got some more useful info back... looks like its due to a bug in Unity itself so it may take a while to find a workaround. Putting this here for future ref
[output_log_rampdebug.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2156969/output_log_rampdebug.txt)

**Comment by X-ITT** [comment]
@SeanAtr0n woah, that's hardly related to a win7 issue, but I'm not suprised that it's out of the ballpark from what support staff suspected. But for now we will continue to remove entities to whoever get's the issue in my server. So far it has been working 99% of the time when coming across this issue. But I'm  glad you found the issue though.

**Comment by SeanAtr0n** [comment]
Found a workaround, fixed in next hotfix build
