### ISSUE TITLE
USER ISSUE: Game crash when I try to launch it

### ISSUE THREAD

**Issue by BonaventureSissokovitch** [StrangeLoopGames/EcoIssues#8274]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
I try to oin a server/ load a solo game, everything loads well but when the message "Entering world" appears, the screen freezes and then the game crashes.

**Expected behavior:**
I should have had my game started.

**Actual behavior:**
Game crashes

**Comment by MarjieAVolk** [comment]
I just saw a similar issue the other day. We found that deleting a certain file fixed it. Open up local files via steam, and then find and delete Eco_Data\Server\Eco.Mods.dll

Let me know if that works.

**Comment by BonaventureSissokovitch** [comment]
Hi,


I deleted the file you told me and it works now. Thanks for your quick answer!




________________________________
De : MarjieAVolk <notifications@github.com>
Envoyé : mardi 3 juillet 2018 00:20
À : StrangeLoopGames/EcoIssues
Cc : BonaventureSissokovitch; Author
Objet : Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Game crash when I try to launch it (#8274)


I just saw a similar issue the other day. We found that deleting a certain file fixed it. Open up local files via steam, and then find and delete Eco_Data\Server\Eco.Mods.dll

Let me know if that works.

**Comment by pischke** [comment]
I have the same issue. Loading an existing world is possible. But starting a new world results in Quit after "Entering World". The EcoServer is still running. Deleting Eco_Data\Server\Eco.Mods.dll changes nothing.

**Comment by pischke** [comment]
@elfl0rd I have verified files. He found 2 damaged files an restored them, but the problem is the same. It is not possible to start with a new world.

**Comment by elfl0rd** [comment]
Okay :) try to launch server directly.
(Open steam, eco properties, "browse local files", go to \Eco_Data\Server run ecoserver.exe

Crashed? Attach \Eco_Data\Server\Dump .ecodmp file with same time (you need pack ecodmp to archive and attach to eg comment)

**Comment by pischke** [comment]
I have started the server. But no crash. :o)
I then started the client and connect to running server. Then it crashes at "Entering World". All the same.

**Comment by elfl0rd** [comment]
attach dump from %appdata%\..\LocalLow\Strange Loop Games\Eco\Crashes
(Win+r or Run in start menu, then paste and ok)

**Comment by elfl0rd** [comment]
okay, wait developers :(

**Comment by pischke** [comment]
Maybe this helps. I have attached VS2017 to Eco.exe and it catches an exception right after "entering world".

Exception thrown at 0x000002788741AA76 in Eco.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

**Comment by MarjieAVolk** [comment]
@pischke one other thing you can try is to delete the whole folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO

**Comment by johnkslg** [comment]
@pischke Please message me on Discord.gg/eco @johnk
Working on this now
