### ISSUE TITLE
/dummy causes client crash

### ISSUE THREAD

**Issue by FishAus** [StrangeLoopGames/EcoIssues#8275]
/Dummy causes client crash when trying to login dummy.

Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.User.Login(Player player, INetClient client)
   at Eco.Gameplay.Players.Player..ctor(User user, Single viewDistance, INetClient client)
   at Eco.Mods.AvatarCommands.MakeDummy(Player player, User sourceUser)
   at Eco.Mods.AvatarCommands.Dummy(User user, Int32 count)</size>

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 960 (ID=0x1401)
    Vendor:   NVIDIA
    VRAM:     2007 MB
    Driver:   23.21.13.9124
Begin MonoManager ReloadAssembly
- Completed reload, in  0.063 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.781215 ms
Setting up 2 worker threads for Enlighten.
  Thread -> id: 3a70 -> priority: 1 
  Thread -> id: 1840 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'ClauseDropdown') is missing!
 
(Filename:  Line: 1758)

Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
Loaded objects should start as DISABLED, but object "Objects" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Decorations.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Items" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Decorations.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Objects" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Games.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Items" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Games.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following icons: AussieFlagFZMItem, LumberjackShirtFZMItem, StoneArchFZMItem, VehicleToolItem
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, AussieFlagFZMObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'AirPumpObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The Text Container component is now Obsolete and can safely be removed from [Name].
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'APGenObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'APGenObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'APGenObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'APGenObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'APGenObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'APGenObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Can not play a disabled audio source
 
(Filename:  Line: 707)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at Player.get_NetObject () [0x00005] in <8bb6161354ba4ce39d2f818572e83d1e>:0 
  at MinimapUI.OnDisable () [0x00025] in <8bb6161354ba4ce39d2f818572e83d1e>:0 
UnityEngine.Object:Destroy(Object, Single)
UnityEngine.Object:Destroy(Object)
UI.UIManager:Destroy(GameObject)
UI.UIManager:CloseAll()
Player:OnDestroy()
 
(Filename: <8bb6161354ba4ce39d2f818572e83d1e> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at MinimapUIObjectManager.OnDestroy () [0x00005] in <8bb6161354ba4ce39d2f818572e83d1e>:0 
  at MinimapUI.OnDestroy () [0x00067] in <8bb6161354ba4ce39d2f818572e83d1e>:0 
 
(Filename: <8bb6161354ba4ce39d2f818572e83d1e> Line: 0)

Loaded objects should start as DISABLED, but object "Objects" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Decorations.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Items" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Decorations.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Objects" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Games.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Items" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Games.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following icons: AussieFlagFZMItem, LumberjackShirtFZMItem, StoneArchFZMItem, VehicleToolItem
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, AussieFlagFZMObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'APGenObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'AussieFlagFZMObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Exception in view notify: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at UI.ViewUIContainer.ListChanged () [0x00000] in <8bb6161354ba4ce39d2f818572e83d1e>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <cfc149f8218b496788d8493c87de777a>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <0fb23579d229465fa20e5996498db2fe>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <0fb23579d229465fa20e5996498db2fe>:0 
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at Player.get_NetObject () [0x00005] in <8bb6161354ba4ce39d2f818572e83d1e>:0 
  at MinimapUI.OnDisable () [0x00025] in <8bb6161354ba4ce39d2f818572e83d1e>:0 
UnityEngine.Object:Destroy(Object, Single)
UnityEngine.Object:Destroy(Object)
UI.UIManager:Destroy(GameObject)
UI.UIManager:CloseAll()
Player:OnDestroy()
 
(Filename: <8bb6161354ba4ce39d2f818572e83d1e> Line: 0)

Loaded objects should start as DISABLED, but object "Objects" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Decorations.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Items" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Decorations.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Objects" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Games.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Items" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Games.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following icons: AussieFlagFZMItem, LumberjackShirtFZMItem, StoneArchFZMItem, VehicleToolItem
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, AussieFlagFZMObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'AussieFlagFZMObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'APGenObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at Player.get_NetObject () [0x00005] in <8bb6161354ba4ce39d2f818572e83d1e>:0 
  at MinimapUI.OnDisable () [0x00025] in <8bb6161354ba4ce39d2f818572e83d1e>:0 
UnityEngine.Object:Destroy(Object, Single)
UnityEngine.Object:Destroy(Object)
UI.UIManager:Destroy(GameObject)
UI.UIManager:CloseAll()
Player:OnDestroy()
 
(Filename: <8bb6161354ba4ce39d2f818572e83d1e> Line: 0)

Loaded objects should start as DISABLED, but object "Objects" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Decorations.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Items" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Decorations.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Objects" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Games.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Items" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Games.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following icons: AussieFlagFZMItem, LumberjackShirtFZMItem, StoneArchFZMItem, VehicleToolItem
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, AussieFlagFZMObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'AussieFlagFZMObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'APGenObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at Player.get_NetObject () [0x00005] in <8bb6161354ba4ce39d2f818572e83d1e>:0 
  at MinimapUI.OnDisable () [0x00025] in <8bb6161354ba4ce39d2f818572e83d1e>:0 
UnityEngine.Object:Destroy(Object, Single)
UnityEngine.Object:Destroy(Object)
UI.UIManager:Destroy(GameObject)
UI.UIManager:CloseAll()
Player:OnDestroy()
 
(Filename: <8bb6161354ba4ce39d2f818572e83d1e> Line: 0)

Loaded objects should start as DISABLED, but object "Objects" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Decorations.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Items" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Decorations.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Objects" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Games.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Items" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Games.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following icons: AussieFlagFZMItem, LumberjackShirtFZMItem, StoneArchFZMItem, VehicleToolItem
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, AussieFlagFZMObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'AussieFlagFZMObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'APGenObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at Player.get_NetObject () [0x00005] in <8bb6161354ba4ce39d2f818572e83d1e>:0 
  at MinimapUI.OnDisable () [0x00025] in <8bb6161354ba4ce39d2f818572e83d1e>:0 
UnityEngine.Object:Destroy(Object, Single)
UnityEngine.Object:Destroy(Object)
UI.UIManager:Destroy(GameObject)
UI.UIManager:CloseAll()
Player:OnDestroy()
 
(Filename: <8bb6161354ba4ce39d2f818572e83d1e> Line: 0)

Loaded objects should start as DISABLED, but object "Objects" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Decorations.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Items" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Decorations.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Objects" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Games.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loaded objects should start as DISABLED, but object "Items" in bundle "C:/Users/User/AppData/LocalLow/Strange Loop Games/Eco\Mods\FZM.Games.unity3d" is not.  This can cause many problems, you should disable the object by default.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following icons: AussieFlagFZMItem, LumberjackShirtFZMItem, StoneArchFZMItem, VehicleToolItem
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, AussieFlagFZMObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'AussieFlagFZMObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'APGenObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at Player.get_NetObject () [0x00005] in <8bb6161354ba4ce39d2f818572e83d1e>:0 
  at MinimapUI.OnDisable () [0x00025] in <8bb6161354ba4ce39d2f818572e83d1e>:0 
UnityEngine.Object:Destroy(Object, Single)
UnityEngine.Object:Destroy(Object)
UI.UIManager:Destroy(GameObject)
UI.UIManager:CloseAll()
Player:OnDestroy()
 
(Filename: <8bb6161354ba4ce39d2f818572e83d1e> Line: 0)

**Comment by BlazeGuy2** [comment]
/dummy is currently fixed on 7.6.0 (on bleeding edge branch).  Fix will be on default game branch when 7.6.0 is ready to ship.  Closing.
