### ISSUE TITLE
You can break TAX to direct pay.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8278]
By sending 0.01!
![default](https://user-images.githubusercontent.com/4980243/42180841-63ae2c2c-7e41-11e8-80f6-320720b70b60.png)

**Comment by elfl0rd** [comment]
Yes, you right :)))

**Comment by Deantwo** [comment]
Maybe it should just be fixed to say `<0.01` instead of `0`.

**Comment by elfl0rd** [comment]
Maybe, but need another issue.

**Comment by Deantwo** [comment]
Don't know if this fix is in the current release.
But I just got this:
![image](https://user-images.githubusercontent.com/2676134/43216399-3771f1c4-903f-11e8-9d09-e6f4d32945f4.png)
