### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by Ph1l95** [StrangeLoopGames/EcoIssues#8279]
Hello,

all started with the version 7.3.3 and mods.
I cleared everything and started the save file with a clean 7.3.3 server but I got "OutOfMemoryException".
So I installed the 7.5.1 server and did it again. Same Exception.
The server has 64 GB RAM and Eco used 2500 MB of it.

I added the english translation to the .ecodmp file.

Game.db: https://drive.google.com/open?id=1f7PaXsMOrIjMz8BDcnAUuu8SpzoA8GIf
Game.eco: https://drive.google.com/open?id=1rCESPxDJn3PxJ8thNjupJJ8XuU1Y1m-w
ServerCrash.ecodmp: https://drive.google.com/open?id=1_HREF2nCuGazR9YM9-AT3qqVUYq_K5vS
All 3 files: https://drive.google.com/open?id=105f4bLR8la9UwU8CS_X6eX1Y1JOqbdLf

**Comment by metachronism** [comment]
verified this is crashing still.  requires a world layer tick.  Mem usage was nearing 8GB when it crashed

**Comment by metachronism** [comment]
![image](https://user-images.githubusercontent.com/3150561/42614908-b8b31c74-855c-11e8-9bff-185d2b0bcb12.png)

**Comment by johnkslg** [comment]
Elevating to critical because it has crashed servers > 5000 times
