### ISSUE TITLE
Changing graphics quality with minimap open causes severe issues 0.4.2

### ISSUE THREAD

**Issue by ThePlaneswalker** [StrangeLoopGames/EcoIssues#828]
Whilst playing with the minimap open, I attempted to reduce and increase the graphics quality slider found in the options. This causes the minimap to replace the main game screen and is not animated. Game sounds can still be heard. Is reproducible by pressing Escape twice, and altering graphics quality multiple times with minimap open. Does not crash the client. Only way to fix is to disconnect from this state, which has crashed the client 1 of 3 times attempted.

**Comment by metachronism** [comment]
looks like something causing unity to use the wrong camera by default after the options change
