### ISSUE TITLE
Server still experience crash loop with "this"

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8280]
This is still happening pretty much on a daily or twice daily basis.  When it occurs the server stays in a crash loop over and over on this same error until stopped and a backup is employed.  I know this was supposed to be resolved in 7.5 but it does not seem to have helped.

--BEGIN DUMP--
Dump Time
07/02/2018 02:01:42

Exception
Exception: ArgumentException
Message:Delegate to an instance method cannot have null 'this'.
Source:mscorlib

System.ArgumentException: Delegate to an instance method cannot have null 'this'.
   at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   at Eco.Core.Plugins.StorageManager..ctor()

--END DUMP--
https://www.dropbox.com/s/0qo0ido04ts1syz/BigWorld_July1_Dump.zip?dl=0
https://www.dropbox.com/s/s3y8riiw643p6jf/BigWorld_Monday_Dump.zip?dl=0
https://www.dropbox.com/s/4d62tlcpt34gmy2/Game.db?dl=0
https://www.dropbox.com/s/48vhbzdf4mf5zvi/Game.eco?dl=0

**Comment by pamduncan** [comment]
https://www.dropbox.com/s/1yf93xlclyv6rpb/BigWorld_Tuesday_Dump.zip?dl=0

**Comment by pamduncan** [comment]
https://www.dropbox.com/s/dtesp8wiqccsr74/BigWorld_July4Dump.zip?dl=0

https://www.dropbox.com/s/a9sw0bs8tm9gfx7/BigWorld_July5Dump.zip?dl=0

**Comment by pamduncan** [comment]
7/11

https://www.dropbox.com/s/8gm6lt26cdepddr/BigWorld_July_11_Dump.zip?dl=0

**Comment by pamduncan** [comment]
No Mods on that server, it had mods several versions back but they stopped using them as they were not being updated and so they were not reinstalled or used after 7.4 released

https://www.dropbox.com/s/kjgbine79nw5fue/BigWorld_July_12_Dump.zip?dl=0

**Comment by metachronism** [comment]
has not occured since 7.6, closing

**Comment by pamduncan** [comment]
That error we had in 7.4 in now reoccurring in 7.6.3 the null 'this'.  This is a new world, not the one that had it before but on the same server..  Is there anyway we can track this down?
 --BEGIN DUMP--
Dump Time
07/31/2018 00:05:48

Exception
Exception: ArgumentException
Message:Delegate to an instance method cannot have null 'this'.
Source:mscorlib

System.ArgumentException: Delegate to an instance method cannot have null 'this'.
   at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   at Eco.Core.Plugins.StorageManager..ctor()

--END DUMP--
https://www.dropbox.com/s/ijapcjlzhv501f9/Pams%20Big%20World.db?dl=0
https://www.dropbox.com/s/b5oxo0u1zim0ze6/Pams%20Big%20World.eco?dl=0
https://www.dropbox.com/s/vtshanr9u0vnrq7/PamsBigWorldDump.zip?dl=0

**Comment by pamduncan** [comment]
1.  The world to test for the null 'this error would be the latest world added:  
https://www.dropbox.com/s/ijapcjlzhv501f9/Pams%20Big%20World.db?dl=0
https://www.dropbox.com/s/b5oxo0u1zim0ze6/Pams%20Big%20World.eco?dl=0
https://www.dropbox.com/s/vtshanr9u0vnrq7/PamsBigWorldDump.zip?dl=0

2.  No idea what is being done in game to make this happen.  Have asked players and no one seems to know what to do except that it happens about the same time of day every 24 hours

3.  Will add players in game name when I find out from other players what it is.  The admin that knows is not currently online

**Comment by johnkslg** [comment]
Verified this works properly in 8.0.  Until then ask the user to change their name to not have the weird characters in order to login.  Thanks!
