### ISSUE TITLE
Can't drag and drop a Steam Truck's storage/fuel supply from other storages.

### ISSUE THREAD

**Issue by nmdanny** [StrangeLoopGames/EcoIssues#8286]
**Version:** 0.7.5.1 (after the Hotfix)

 **Steps to Reproduce:**
Put a Steam Truck and some other storages nearby(crafting table, stockpile, chest etc..) nearby, access one of said storages, drag and drop the steam truck's storage/fuel supply to some different position. 

**Expected behavior:**
The truck's storage/fuel supply position/priority should change accordingly.

**Actual behavior:**
The truck's storage snaps back, either before or after its fuel supply depending in which direction you dragged it. The same applies when dragging the fuel supply(snaps before or after the storage).

Note, there is no problem when dragging other storages/fuel supplies from the truck itself, nor is there any problem with linking to/from the truck storage/fuel supply.

**Comment by MarjieAVolk** [comment]
This should have been fixed with the recent changes to linked inventories.  Let me check what version that is in.

**Comment by MarjieAVolk** [comment]
Okay yeah, this is fixed in 7.6
