### ISSUE TITLE
USER ISSUE: place large windowed lumber door cause crash.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8287]
**Version:** 0.7.6.0 beta staging-1550413c
![default](https://user-images.githubusercontent.com/4980243/42214620-a63f09a2-7ec4-11e8-915a-5bcedbd0f933.png)
![default](https://user-images.githubusercontent.com/4980243/42214671-ccdb56ec-7ec4-11e8-924f-c7eac907b0ba.png)
And corrypt world.
![default](https://user-images.githubusercontent.com/4980243/42215114-2c57dbe4-7ec6-11e8-9fef-8b0754b3c0f6.png)

you can not more enter to it.
No .dump created.
Savefile - https://www.dropbox.com/s/ftngm78tw3ed2bo/largewindlumberdoor.zip?dl=1

**Comment by craig-jong** [comment]
fixed in SVN
