### ISSUE TITLE
[7.6.0] Elevator Buttons don't have the green cursor appear

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8291]
When using the elevator, I can only get the green cursor to appear when I hover over the elevator's up button; not its stop or down button.

**Comment by BlazeGuy2** [comment]
On bleeding_edge:
![elevator_button](https://user-images.githubusercontent.com/35509188/42240578-9255a8fe-7ebc-11e8-9573-01b8cf1f131f.gif)

**Comment by IcedForge** [comment]
https://i.gyazo.com/a564f126c6d6a689f7e06f24cabb6465.mp4
Issue persists with "Wooden Elevator Call Button"
Wooden elevator button works but not the call buttons.
