### ISSUE TITLE
[7.5.1] Excavator/Skid steer Cannot Place Into Trucks

### ISSUE THREAD

**Issue by miketek1** [StrangeLoopGames/EcoIssues#8292]
Both the excavator and skid steer will not place anything into the inventory of the truck and the steam truck. The interaction cursor shows the option but it doesn't actually work. Also you can remove and place fuel into the steam truck but nothing else can be placed in it's storage from the excavator or skid steer.  7.5.1

**Comment by BlazeGuy2** [comment]
probably related.  closing for now, there is a link in #8059 that will reference this issue
