### ISSUE TITLE
[7.5.1] Closing Excavator Boom Causes Wild Tumble

### ISSUE THREAD

**Issue by miketek1** [StrangeLoopGames/EcoIssues#8293]
Closing the excavator boom fully causes the excavator to become glitched and wildly tumble and launch, this will continue until boom is extended or user stops operating. This has happened in previous versions, not sure if there is a report but some limiter would be good so you cannot glitch the bucket inside the boom.

**Comment by mirasrael** [comment]
Seems fixed in 8.2

![image](https://user-images.githubusercontent.com/475445/55628486-8301a480-57b9-11e9-88c4-0b73f9b15b85.png)
