### ISSUE TITLE
[0.7.6.0] Camera Issue with new meteor tutorial

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8295]
https://youtube.com/watch?v=HZ1bPNX59_g&feature=youtu.be

Issue occurred when looking at the meteor after it passes over the horizon, then finishing the tutorial.  Camera was stuck zoomed in (although hitting escape fixed the perspective) but the WASD controls were messed up.

**Comment by johnkslg** [comment]
Fixed!
