### ISSUE TITLE
Let's add a way to delete items except tailings

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#830]
Later we can replace this with a garbage system if we want.

**Comment by wiloxe** [comment]
A form of incineration system where you could burn most objects but depend on the type of the object it will cause a specific amount of pollution out in the air and so can even allow tailings to be burned if you are willing to take the cost.

**Comment by craig-jong** [comment]
ITS BEEN A LONG ROAD BUT WE FINALLY MADE IT
