### ISSUE TITLE
String duplication

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8300]
https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#50553 and https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#50557

https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#50554 and https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#50558

https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#50555 and https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#50559

**Comment by elfl0rd** [comment]
https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#50553 and https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#50557

https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#50554 and https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#50558

https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#50555 and https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#50559

**Comment by Nanders** [comment]
These are all used in different places

**Comment by elfl0rd** [comment]
Can you add context to crowdin?
