### ISSUE TITLE
@pam

### ISSUE THREAD

**Issue by LuketheHero** [StrangeLoopGames/EcoIssues#8303]
![grafik](https://user-images.githubusercontent.com/40810229/42249192-44d95ada-7f2a-11e8-8bfe-6eacbb318757.png)

**Comment by elfl0rd** [comment]
avira... try to disable?

**Comment by metachronism** [comment]
cant run multiple servers on the same box with the same game port - make sure all other server processes are closed, or configure them to use other ports
