### ISSUE TITLE
USER ISSUE: cant start any save data

### ISSUE THREAD

**Issue by flakpredator** [StrangeLoopGames/EcoIssues#8305]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
i try to load any game and nothing happens

**Expected behavior:**
play

**Actual behavior:**
nothing

**Comment by GophTheGreat** [comment]
Pic attached of error as per Discord conversation

![untitled](https://user-images.githubusercontent.com/13459026/42251014-83c4e016-7ed0-11e8-8be3-c7effc4b3517.png)
