### ISSUE TITLE
USER ISSUE: Can't Launch

### ISSUE THREAD

**Issue by rictor86** [StrangeLoopGames/EcoIssues#8306]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
Try to open any world, existing or new.

**Expected behavior:**
CANNOT CONNECT!

**Actual behavior:**
The following error message popped up:
Connection Failed  Failed to establish connection - no response from remote host
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host
```

**Comment by SeanAtr0n** [comment]
should be fixed in the 7.5.1 hotfix today
