### ISSUE TITLE
[0.7.6.0] too tight place to translate

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8307]
https://crowdin.com/translate/eco-by-strange-loop-games/3/en-ru#36158
![20180704045454_1](https://user-images.githubusercontent.com/4980243/42253169-1aea92d8-7f49-11e8-8130-fc7320001875.jpg)
@Nanders

**Comment by mirasrael** [comment]
May be "Вещь" as shorter alternative?

**Comment by elfl0rd** [comment]
Maybe, but little incorrect.
"Инструмент" as far as repair requied only for tools.
And repair window contain LOT of free space, limiting field is strange for me.

**Comment by elfl0rd** [comment]
Economy viever
Trades - need espand too.
![default](https://user-images.githubusercontent.com/4980243/42277984-e48efc70-7fa1-11e8-9f2f-bae8fd06c804.png)
Contracts/Public Crafting Stations/Currencies In Use - not support Russian as i see.
![default](https://user-images.githubusercontent.com/4980243/42278052-25bbbf1c-7fa2-11e8-9080-254a0b65bbd9.png)
