### ISSUE TITLE
USER ISSUE: Can't connect to Single Player.

### ISSUE THREAD

**Issue by Fayelegance** [StrangeLoopGames/EcoIssues#8309]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
Connect to Single Player.

**Expected behavior:**
Connected to server.	

**Actual behavior:**
Failed to establish a connection.

**Comment by pamduncan** [comment]
Has the user been in the world before?

**Comment by Fayelegance** [comment]
Yes.

**Comment by RedCrayonnn** [comment]
I am having the same issue, the only version i can get my old world to load on since 751 re release is bleeding stadging, however that world crashes as soon as i see my world.

**Comment by BlazeGuy2** [comment]
Deployed a hotfix today to address this.  Reopen if this is still occurring.
