### ISSUE TITLE
Constant disconnect after chopping tree down

### ISSUE THREAD

**Issue by mauzao9** [StrangeLoopGames/EcoIssues#831]
So after chopping a tree down into little pieces, trying to grab the block returned a disconnect with this error:
```
[54:39] Disconnecting client [reason: Caught exception: Index was outside the bounds of the array.]...
```

Every time around the area would trigger a disconnect with the same error; was fixed upon restart though, but still reporting it.

**Comment by metachronism** [comment]
should be fixed
