### ISSUE TITLE
USER ISSUE: "Continuing" game unpossible

### ISSUE THREAD

**Issue by springphul** [StrangeLoopGames/EcoIssues#8310]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
1. played for several hrs. Also ended game w/o big probems. I had to shut down steam every time, bc the eco server didn't shut down properly. It worked sveral times.
2. this time the there were no issues with that, but after starting the game..
3. clicking the button "continue (game)" causes the game to halt
4. the end game restarting worked before

<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1070 (ID=0x1be1)
    Vendor:   NVIDIA
    VRAM:     8081 MB
    Driver:   24.21.13.9764
Begin MonoManager ReloadAssembly
- Completed reload, in  0.093 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.323031 ms
Setting up 4 worker threads for Enlighten.
  Thread -> id: 1088 -> priority: 1 
  Thread -> id: 3654 -> priority: 1 
  Thread -> id: c88 -> priority: 1 
  Thread -> id: 2f04 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'ClauseDropdown') is missing!
 
(Filename:  Line: 1758)

Stopping existing server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.5.1 beta
LocalServer -  Server Initialization... 
LocalServer -  Starting LocalizationPlugin... 
LocalServer -  Starting ModKitPlugin... 
LocalServer -  Loading mods... 
LocalServer -  Loading mods finished in 105,2ms
LocalServer -  Starting NetworkManager... 
LocalServer -  Initializing items... 
LocalServer -  Starting WorldGeneratorPlugin... 
LocalServer -  Starting GameplayStatsPlugin... 
LocalServer -  Starting BackupPlugin... 
LocalServer -  Starting StorageManager... 
LocalServer -  Server Initialization finished in 2.633,8ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host
```

**Expected behavior:**
The game should run, ike the other times

**Comment by SeanAtr0n** [comment]
should be fixed in the 7.5.1 hotfix today
