### ISSUE TITLE
USER ISSUE: Game Start connection error

### ISSUE THREAD

**Issue by springphul** [StrangeLoopGames/EcoIssues#8311]
I posted a bug earlier, that the resuming game is not working.

Starting a new world also doesn't work anymore. I didn't do anything different than before. I end the game, clos the laptop and restart it another day.
Usually, I needed to shut down the ecoserver manually before being able to start eco again. Usually the game server wasn't properly shut down before. So I shutted down steam everytime and restarted it. Then eco restarts properly. 
This time eco started without any problems or watnings, but it doesn't connect to the local host server.

There was someting unsual, I have seen in the menue of the game. The game time doesn't fit to the computer clock. see attached screenshot.
![bugreport_eco_servertime](https://user-images.githubusercontent.com/40817901/42259938-c6d328e4-7f62-11e8-8119-e99169aa8f82.png)

<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1070 (ID=0x1be1)
    Vendor:   NVIDIA
    VRAM:     8081 MB
    Driver:   24.21.13.9764
Begin MonoManager ReloadAssembly
- Completed reload, in  0.087 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.304432 ms
Setting up 4 worker threads for Enlighten.
  Thread -> id: a84 -> priority: 1 
  Thread -> id: 7b8 -> priority: 1 
  Thread -> id: 6ac -> priority: 1 
  Thread -> id: 69c -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'ClauseDropdown') is missing!
 
(Filename:  Line: 1758)

Stopping existing server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.5.1 beta
LocalServer -  Server Initialization... 
LocalServer -  Starting LocalizationPlugin... 
LocalServer -  Starting ModKitPlugin... 
LocalServer -  Loading mods... 
LocalServer -  Loading mods finished in 115,4ms
LocalServer -  Starting NetworkManager... 
LocalServer -  Initializing items... 
LocalServer -  Starting WorldGeneratorPlugin... 
LocalServer -  Starting GameplayStatsPlugin... 
LocalServer -  Starting BackupPlugin... 
LocalServer -  Starting StorageManager... 
LocalServer -  Server Initialization finished in 2.597,2ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Version:** 0.7.5.1 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host
```

**Comment by SeanAtr0n** [comment]
should be fixed in the 7.5.1 hotfix today
