### ISSUE TITLE
Reputation Title since 0.7.3 

### ISSUE THREAD

**Issue by Bl4ckSkull666** [StrangeLoopGames/EcoIssues#8313]
Hello everybody,

on my servers are all reputation titles visible only as N/A e.g. in German in k.A. 
All Reputation tiers.

How can i fix it or is that a general problem currently?

Sincerely,
Bl4ckSkull666

**Comment by elfl0rd** [comment]
Yes, general.
And already reported - https://github.com/StrangeLoopGames/EcoIssues/issues/6730

**Comment by Bl4ckSkull666** [comment]
Great reported on 30 March and no fix until now. but import truck and other before fixing existing bugs *thumbup*

**Comment by elfl0rd** [comment]
Bugreport period later :P and this problem is not critical.

**Comment by Bl4ckSkull666** [comment]
It's not critical to add new Items too but it's added. And now?

**Comment by elfl0rd** [comment]
Why artists need wait until programmers fix all bugs?
Man, use brain.
