### ISSUE TITLE
USER ISSUE: fail to load a solo party

### ISSUE THREAD

**Issue by badmonster-nc** [StrangeLoopGames/EcoIssues#8314]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
start the game.
clic on continue
select my world
clic on load

error message:
Connection Failed.
Failed to establish connection - no response from remote host

**Expected behavior:**
it should load my world

**Actual behavior:**
The following error message popped up:
```
failed to estab
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host
```

**Comment by SeanAtr0n** [comment]
should be fixed in the 7.5.1 hotfix today
