### ISSUE TITLE
USER ISSUE: connection failed

### ISSUE THREAD

**Issue by zockerino** [StrangeLoopGames/EcoIssues#8316]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
eine welt vor dem 7.5.1 bug fix haben und nach dem der 7.5.1 bug fix installiert ist in diese welt einsteigen 

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```failed to establish connection - no response from remote host
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host
```

**Comment by SeanAtr0n** [comment]
should be fixed in the 7.5.1 hotfix today
