### ISSUE TITLE
USER ISSUE: Unable to load world

### ISSUE THREAD

**Issue by Hammerkeg** [StrangeLoopGames/EcoIssues#8317]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
1. Create world (1-3 players, friends can join, crafting awards xp)
2. Attempt to join.

**Expected behavior:**
Join the world.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host
```

**Comment by SeanAtr0n** [comment]
should be fixed in the 7.5.1 hotfix today
