### ISSUE TITLE
USER ISSUE: cant load server

### ISSUE THREAD

**Issue by voldaron** [StrangeLoopGames/EcoIssues#8318]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
conection failed. cant make new map or play on loaded

**Expected behavior:**

**Actual behavior:**
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 970 (ID=0x13c2)
    Vendor:   NVIDIA
    VRAM:     4043 MB
    Driver:   23.21.13.9135
Begin MonoManager ReloadAssembly
- Completed reload, in  0.072 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.656606 ms
Setting up 4 worker threads for Enlighten.
  Thread -> id: 1160 -> priority: 1 
  Thread -> id: 3fc -> priority: 1 
  Thread -> id: 1af8 -> priority: 1 
  Thread -> id: 200c -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'ClauseDropdown') is missing!
 
(Filename:  Line: 1758)

Stopping existing server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.5.1 beta
LocalServer -  Server Initialization... 
LocalServer -  Starting LocalizationPlugin... 
LocalServer -  Starting ModKitPlugin... 
LocalServer -  Loading mods... 
LocalServer -  Loading mods finished in 103,8ms
LocalServer -  Starting NetworkManager... 
LocalServer -  Initializing items... 
LocalServer -  Starting WorldGeneratorPlugin... 
LocalServer -  Starting GameplayStatsPlugin... 
LocalServer -  Starting BackupPlugin... 
LocalServer -  Starting StorageManager... 
LocalServer -  Server Initialization finished in 2�451,7ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Stopping existing server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.5.1 beta
LocalServer -  Server Initialization... 
LocalServer -  Starting LocalizationPlugin... 
LocalServer -  Starting ModKitPlugin... 
LocalServer -  Loading mods... 
LocalServer -  Loading mods finished in 105,3ms
LocalServer -  Starting NetworkManager... 
LocalServer -  Initializing items... 
LocalServer -  Starting WorldGeneratorPlugin... 
LocalServer -  Starting GameplayStatsPlugin... 
LocalServer -  Starting BackupPlugin... 
LocalServer -  Starting StorageManager... 
LocalServer -  Server Initialization finished in 2�390,9ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by SeanAtr0n** [comment]
should be fixed in the 7.5.1 hotfix today
