### ISSUE TITLE
USER ISSUE: Opening Map

### ISSUE THREAD

**Issue by EiKiDa** [StrangeLoopGames/EcoIssues#8319]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
Can't open the map.

**Expected behavior:**
It should be opened.

**Actual behavior:**
The map can't be connected with the PC

**Comment by SeanAtr0n** [comment]
whoops, just noticed this bug... need a few more details if this is still an issue for you like the log file from:

`%APPDATA%\..\LocalLow\Strange Loop Games\ECO`
