### ISSUE TITLE
USER ISSUE: Skid steer not emptying

### ISSUE THREAD

**Issue by FlamingDemon** [StrangeLoopGames/EcoIssues#8321]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
1. dig with the skid steer
2. try to empty in container (stockpile or truck)

**Expected behavior:**
it should have dumped the items from it's inventory into the stockpile or truck

**Actual behavior:**
only fuel can be given to vehicles, not other items to trucks or stockpiles

**Comment by GophTheGreat** [comment]
Cannot reproduce -- skidsteer was able to deliver both stone and fuel to a truck. Closing.
