### ISSUE TITLE
"Output_log" Spiel stürzt permanent beim start einer neuen Welt ab

### ISSUE THREAD

**Issue by Slasher0ne** [StrangeLoopGames/EcoIssues#8328]
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 1060 6GB (ID=0x1c03)
    Vendor:   NVIDIA
    VRAM:     6036 MB
    Driver:   23.21.13.9124
Begin MonoManager ReloadAssembly
- Completed reload, in  1.007 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.711068 ms
Setting up 2 worker threads for Enlighten.
  Thread -> id: 1548 -> priority: 1 
  Thread -> id: 1730 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'ClauseDropdown') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following icons: VehicleToolItem
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by BlazeGuy2** [comment]
Released a hotfix to address the new world crashing issue.  Open a new issue if this occurs again.
