### ISSUE TITLE
Server crashes after re-released update 7.5.1 from 2018-07-04

### ISSUE THREAD

**Issue by Amarok41** [StrangeLoopGames/EcoIssues#8329]
By the looks of it, this has been reported numerous times already. A quick fix for this would be appreciated. :-)

The game crashes after the server started (or while it tries to start). This happens with 100% certainty:
- tried rebooting Windows and Steam
- tried to create a new world
- tried to login into an existing world (which has worked without problems before (played in single player only with only one player connected)

The game worked without problems before today's fix (I bought it by the end of last week).

---------------------------------------

<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 775M (ID=0x119d)
    Vendor:   NVIDIA
    VRAM:     1957 MB
    Driver:   23.21.13.8871
Begin MonoManager ReloadAssembly
- Completed reload, in  0.064 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 2.565325 ms
Setting up 4 worker threads for Enlighten.
  Thread -> id: 1ed8 -> priority: 1 
  Thread -> id: ad4 -> priority: 1 
  Thread -> id: 1d84 -> priority: 1 
  Thread -> id: 2b8 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'ClauseDropdown') is missing!
 
(Filename:  Line: 1758)

Stopping existing server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.5.1 beta
LocalServer -  Server Initialization... 
LocalServer -  Starting LocalizationPlugin... 
LocalServer -  Starting ModKitPlugin... 
LocalServer -  Loading mods... 
LocalServer -  Loading mods finished in 124,7ms
LocalServer -  Starting NetworkManager... 
LocalServer -  Initializing items... 
LocalServer -  Starting WorldGeneratorPlugin... 
LocalServer -  Starting GameplayStatsPlugin... 
LocalServer -  Starting BackupPlugin... 
LocalServer -  Starting StorageManager... 
LocalServer -  Server Initialization finished in 4.250,1ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Stopping existing server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.5.1 beta
LocalServer -  Server Initialization... 
LocalServer -  Starting LocalizationPlugin... 
LocalServer -  Starting ModKitPlugin... 
LocalServer -  Loading mods... 
LocalServer -  Loading mods finished in 98,8ms
LocalServer -  Starting NetworkManager... 
LocalServer -  Initializing items... 
LocalServer -  Starting WorldGeneratorPlugin... 
LocalServer -  Starting GameplayStatsPlugin... 
LocalServer -  Starting BackupPlugin... 
LocalServer -  Starting StorageManager... 
LocalServer -  Server Initialization finished in 4.107,6ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Stopping existing server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.5.1 beta
LocalServer -  Server Initialization... 
LocalServer -  Starting LocalizationPlugin... 
LocalServer -  Starting ModKitPlugin... 
LocalServer -  Loading mods... 
LocalServer -  Loading mods finished in 101,2ms
LocalServer -  Starting NetworkManager... 
LocalServer -  Initializing items... 
LocalServer -  Starting WorldGeneratorPlugin... 
LocalServer -  Starting GameplayStatsPlugin... 
LocalServer -  Starting BackupPlugin... 
LocalServer -  Starting StorageManager... 
LocalServer -  Server Initialization finished in 2.747,6ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by BlazeGuy2** [comment]
Deployed a hotfix today, open a new issue if isn't resolved.
