### ISSUE TITLE
USER ISSUE: Eco Connection Failed

### ISSUE THREAD

**Issue by GrimRiposter** [StrangeLoopGames/EcoIssues#8330]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
Launch the code
Click on "Continue"

**Expected behavior:**
Brought up the game

**Actual behavior:**
Failed to establish connection - no response from remote host

<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1070 (ID=0x1be1)
    Vendor:   NVIDIA
    VRAM:     8113 MB
    Driver:   22.21.13.8253
Begin MonoManager ReloadAssembly
- Completed reload, in  0.116 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.156009 ms
Setting up 4 worker threads for Enlighten.
  Thread -> id: 3a00 -> priority: 1 
  Thread -> id: 3524 -> priority: 1 
  Thread -> id: 580 -> priority: 1 
  Thread -> id: 3f1c -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'ClauseDropdown') is missing!
 
(Filename:  Line: 1758)

Stopping existing server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

LocalServer -  Eco Server 0.7.5.1 beta
LocalServer -  Server Initialization... 
LocalServer -  Starting LocalizationPlugin... 
LocalServer -  Starting ModKitPlugin... 
LocalServer -  Loading mods... 
LocalServer -  Loading mods finished in 546.4ms
LocalServer -  Starting NetworkManager... 
LocalServer -  Initializing items... 
LocalServer -  Starting WorldGeneratorPlugin... 
LocalServer -  Starting BackupPlugin... 
LocalServer -  Starting GameplayStatsPlugin... 
LocalServer -  Starting StorageManager... 
LocalServer -  Server Initialization finished in 6,731.2ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Connection complete.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by Aldroca** [comment]
a little workaround
https://steamcommunity.com/app/382310/discussions/0/1728701877501159166/
it works fine on me
