### ISSUE TITLE
[7.5.1] Client crashes on loading world, doesn't generate log file

### ISSUE THREAD

**Issue by kaitoyuuki** [StrangeLoopGames/EcoIssues#8332]
Eco client crashes when attempting to connect to a server, shortly after attempting to load the world.
No log files are generated for this crash, either. Is there a way to enable some kind of console or verbose logging mode?

**Comment by BlazeGuy2** [comment]
Believe the cause was with Eco.Mods.dll, deployed a hotfix today to address this.  Reopen if this is still happening.

**Comment by kaitoyuuki** [comment]
it was fixed while the client was updated and the server was a version behind. after the server restarted this morning and (maybe) regenerated the missing eco.mods.dll file, I can no longer connect to the server
