### ISSUE TITLE
USER ISSUE: Small wood cart(s) dissapeared

### ISSUE THREAD

**Issue by broddan290** [StrangeLoopGames/EcoIssues#8341]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
1. Upgraded both server and game to 0.7.5.1
2. Started the game and continued on a "old" game.
3. The do I discover that all my small wood carts are gone and all the content in them.
4. Try to create new one(s). Can't do because there is no small wood cart in "order list".

**Expected behavior:**
That small wood carts still be left where I put them, or at least make it possible to create new ones

**Actual behavior:**
Instead they have dissapeared in cyberspace :)

To solve this I need to "downgrade" to 0.7.4.7 and everything is back where I placed it and I can create new ones

Otherwise thanks for a grate game!

**Comment by elfl0rd** [comment]
small carts removed from game.

**Comment by BlazeGuy2** [comment]
Not a bug, small carts were removed from the game.  Idea was to replace them with wheelbarrows.

**Comment by broddan290** [comment]
OK then I know, must have missed that information.
