### ISSUE TITLE
[0.7.6.0] None of the tutorial caused the skillpoints tab to spawn

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8349]
Finished playing through all of the tutorials, skillpoints ui button never appeared

![skillpoints](https://user-images.githubusercontent.com/35509188/42348113-10dbccf2-805d-11e8-9900-587b1c69b181.PNG)

**Comment by BlazeGuy2** [comment]
Closing, dup of #8346

**Comment by johnkslg** [comment]
Fixed!
