### ISSUE TITLE
Solid ground broke after a server restart

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#8353]
My server crashed and I restarted it.  Now an object which previously was determined to be on solid ground is saying it isn't on solid ground.  It still looks like it's on solid ground, nothing has changed about it.

**Comment by MarjieAVolk** [comment]
I'm guessing what happened is the object never got saved.  Then when the server is restarted, since it got missed it just sits there forever.

**Comment by MarjieAVolk** [comment]
Seems like it should just always recalculate on startup instead of serializing the bool.

**Comment by johnkslg** [comment]
Fixed
