### ISSUE TITLE
USER ISSUE: large doors is not connect to blocks.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8355]
**Version:** 0.7.6.0 beta staging-f5159538

![20180706020400_1](https://user-images.githubusercontent.com/4980243/42352080-095065ba-80c1-11e8-9a84-a748da041ff7.jpg)
![20180706020424_1](https://user-images.githubusercontent.com/4980243/42352081-09786272-80c1-11e8-9ffe-51bd126cc6b3.jpg)

**Comment by keegan-o** [comment]
Committed the occupancy blocks each of these doors needs to fix this to the prefabs, but this needs to be updated in code as well now.

**Comment by craig-jong** [comment]
fixed in https://github.com/StrangeLoopGames/Eco/pull/3047
