### ISSUE TITLE
[0.7.6.0] Tutorial names don't change languages when server changes language

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8358]
**Steps to Reproduce:**
1. Launch a spanish server from steam
2. Connect to the server in the client
3. Client disconnects from server
4. Change server language to english and reboot
5. Join server from client

**Expected Behavior:**
Tutorial titles change languages

**Actual Behavior:**
Tutorial titles stay as spanish

![espanol](https://user-images.githubusercontent.com/35509188/42352423-44e4e382-806f-11e8-9e0d-d41d9e860c2a.PNG)

**Comment by metachronism** [comment]
eventually, servers wont have a language setting.  dont think this bug will prevent release

**Comment by Nanders** [comment]
Aye, there's a lot that would have to change in order for this to work

**Comment by Nanders** [comment]
(stuff that's planned, but won't be ready for this)
Restarting the game should fix

**Comment by BlazeGuy2** [comment]
Bumping off milestone

**Comment by Nanders** [comment]
This performs a lot better now, restarting the tutorial fixes
