### ISSUE TITLE
[0.7.6.0] Need a texture on the campsite along with an icon

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8361]
Need textures and an icon on this baby

![startingcamp](https://user-images.githubusercontent.com/35509188/42353413-ffa3f9e2-8074-11e8-8e31-fb903c32fbf9.PNG)

**Comment by BlazeGuy2** [comment]
I'm an idiot, I already logged this. #8351

**Comment by keegan-o** [comment]
Added in staging!
