### ISSUE TITLE
Server listing masks servers with sub-40ms ping.

### ISSUE THREAD

**Issue by gnedge** [StrangeLoopGames/EcoIssues#8364]
My server is hosted in MS Azure US East and my users in the USA consistently have sub-30ms ping times when logged in.  [](See:  https://imgur.com/ARp1nxz)

Unfortunately, I end up getting many international users and not many people from US East because the server join screen masks servers with a sub-40ms ping.  This is not a bad thing, but my server is very well populated and I'd like more users - and because it has a sub-40ms ping, it's not being shown.  [](See:  https://imgur.com/OXcwtnC) - server not showing at top of list of server; but it is in my favorites with a sub-40ms ping time.  [](See:  https://imgur.com/BTAwiIm)

I don't understand why the server listing page does this, but I feel like it's adversely affecting my server population during core gaming times.

**Comment by pamduncan** [comment]
Are you sorting by ping or just using the order the ping goes in by default?
Most people do end up using one of the sorts so depending on that your server may or may not be one of the top servers even with a very low ping.

**Comment by gnedge** [comment]
By ping.  Servers with less than 40ms ping are not shown.  Sometimes a 39 ping will sneak in there it not usually

**Comment by Deantwo** [comment]
What do you mean by `masks servers with a sub-40ms ping`? You mean that servers with less than 40ms ping aren't shown on the list? I am not sure the word "mask" makes sense in that case, and "less than" is easier to understand than "sub-".

Which version of the **Eco** client are you using? Looking on my server browser with version 0.7.5.1 client, I get plenty of servers with less than 40ms ping.
![image](https://user-images.githubusercontent.com/2676134/42421525-3c9fe554-82d7-11e8-97fe-fc7886f0ed4a.png)

**Comment by gnedge** [comment]
Semantics aside regarding the use of mask, <<conceal (something) from view.>>, What you show above is something I've never seen in my server list.  If I spam the refresh button several times I might get five-ten servers with sub 40ms ping, but it usually looks like this:

![whereisit](https://user-images.githubusercontent.com/39601448/42423098-6fe7e746-82c2-11e8-9c6f-416f7dbc6f98.png)

As you can see, my server shows in the My Servers view, but even sorted by ping on the Browse view, it does not show up.  Baffling.

![myserver](https://user-images.githubusercontent.com/39601448/42423105-88e0edc4-82c2-11e8-8b1c-f6c61dc7023c.png)

**Comment by Deantwo** [comment]
Didn't say what version of the **Eco** client you are using.

**Comment by gnedge** [comment]
7.5.1

**Comment by metachronism** [comment]
we don't do any masking of servers based on ping.  LAN servers are regularly shown with 0-2ms ping, as you would expect
