### ISSUE TITLE
Dead plants disappear, but occupancy stay until server restart. (roots are too strong)

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#8367]
There are invisible tree stumps present in the Stuffed Elk staging server.

One example is shown below.

These invisible stumps prevent you from digging up the ground using a shovel. ("The roots are too strong!")

Using a soil sampler reveals that the empty patch of dirt supposedly contains a Cedar plant.

![image](https://user-images.githubusercontent.com/2173684/42373699-140efb0e-8159-11e8-97bc-66ffdd07e826.png)

**Comment by D3nnis3n** [comment]
This issue seems to still exist as of a report on discord, despite being fixed in https://github.com/StrangeLoopGames/EcoIssues/issues/9005.
![discord](https://user-images.githubusercontent.com/25908592/48294984-4d65c300-e488-11e8-9200-2eb8ed7fcf15.png)

**Comment by elfl0rd** [comment]
@D3nnis3n i think this issue needed to be renamed to exclude "stuffed elk" from name.

**Comment by elfl0rd** [comment]
Reproducible!
If tree die and disappears - he location saved roots status.

you can reproduce it by
place tailing close to tree and wait some time. You can modify ecosim to die fast :P

**Comment by elfl0rd** [comment]
Changing priority, painfull issue (require server restart to fix) and too many users notice it.

**Comment by metachronism** [comment]
should be fixed on all trees (previously was only for some trees, occasionally)
