### ISSUE TITLE
USER ISSUE: you can have "infinity" player based credits in treasury.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8368]
**Version:** 0.7.5.1 beta
Make law like this
![default](https://user-images.githubusercontent.com/4980243/42392740-7c03c1ec-815c-11e8-9e17-267a987c1586.png)
So...
You have infinity!
![20180706203653_1](https://user-images.githubusercontent.com/4980243/42392756-8c530a4e-815c-11e8-8e18-c6dd8f415ec4.jpg)
![20180706203619_1](https://user-images.githubusercontent.com/4980243/42392758-8c77b114-815c-11e8-8999-0b94def34807.jpg)

(Note, server lag if this law in action!)

@MarjieAVolk

**Comment by MarjieAVolk** [comment]
Oh, because you have infinity of your own credit, so you can use that to put infinity everywhere.  Hm.  I'm not sure what the intended behavior should be here.

**Comment by MarjieAVolk** [comment]
I actually think this is fine probably
