### ISSUE TITLE
IL2CPP

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#8369]
- [x] JSON serialization seems to not be fully working.  Cached login doesnt save
- [x] Can't use HTTPWebRequest, must use unity WWW or UnityWebRequest for auth
- [x] Steamworks.NET issue, "IL2CPP does not support marshaling delegates that point to generic methods."
- [ ] AOT issues with generics.  Class types using generics must all be specifically defined for static code analysis to pick up
- [x] Game does not shutdown gracefully, hangs when closing
- [x] Eco.Shared.dll version is not obtainable, need another solution for version numbers

**Comment by metachronism** [comment]
These are all fixed!  yay.  go me.  No one will ever read this....

**Comment by BlazeGuy2** [comment]
I read this
