### ISSUE TITLE
Avatar in avatar UI needs more lively idle animation

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#837]
Or have an animation setting of some sort - Because for the avatar creation UI you need to choose your walking animation.

**Comment by keegan-o** [comment]
Milenko and I probably aren't the best ones to assign atm for an 'add functionality to a UI' task-- the animations are all there. I'd like to do UI stuff some time in the future, but haven't some people on the team already been working on that?

**Comment by SeanAtr0n** [comment]
Looks like there aren't many options for avatar idle animations... we would likely need some variations from the art team to improve on this

**Comment by MarjieAVolk** [comment]
Well actually, I think just having the avatar be always walking on the avatar edit screen would work well, at least for now.  To demonstrate the posture thing.
