### ISSUE TITLE
[7.5.1] No Response from Master Server

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8372]
Currently Servers are very busy… i was kicked two times after red disconnect sign and now i cant rejoin because of this Error:

<size=150%>Verbindung fehlgeschlagen</size>

No response from master server.

Log File:
Initialize engine version: 2017.4.2f2 (52d9cb89b362)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1060 6GB (ID=0x1c03)
    Vendor:   NVIDIA
    VRAM:     6052 MB
    Driver:   24.21.13.9836
Begin MonoManager ReloadAssembly
- Completed reload, in  0.148 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.015900 ms
Setting up 4 worker threads for Enlighten.
  Thread -> id: 2e8 -> priority: 1 
  Thread -> id: 494 -> priority: 1 
  Thread -> id: 2fd0 -> priority: 1 
  Thread -> id: 4fb4 -> priority: 1 
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'ClauseDropdown') is missing!
 
(Filename:  Line: 1758)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1515)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1758)

Missing following icons: VehicleToolItem
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, APGenObject, AtmosphereRegulatorObject, AtmosphereTesterObject, BigStorageChestObject, ButtonObject, GasGeneratorObject, LogicGateObject, SwitchObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by Voosle** [comment]
The last hours there were no significant limitations anymore. Only for about hour the Servers seems to be abnormal busy.

**Comment by rainfarmer** [comment]
fixed in 7.7
