### ISSUE TITLE
[7.6.0] Stuck on the Starting Storage Manager page

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8373]
Craig, Keegan and I can't load a world at all.  Neither new world, or old world.

![](https://cdn.discordapp.com/attachments/324610765392969739/464929704311390211/unknown.png)

**Comment by Bzly** [comment]
This mappens to me when starting up a dedicated server too. Storage manager actually finishes loading according to the console output, but the next step never starts.

Are there logs I can post?

**Comment by BlazeGuy2** [comment]
Update: Only occurs in exported server build

**Comment by BlazeGuy2** [comment]
@Bzly the logs should be in AppData\LocalLow\Strange Loop Games\Eco

**Comment by Bzly** [comment]
I'm running a fresh copy of your standalone Win x64 server client, and no logs have been created yet in LocalLow, nor of course in dump. 

No issues in f5159538, so I presume bug introduced between those builds.

**Comment by BlazeGuy2** [comment]
Bug was introduced in 964a177e after I built it for the first QA pass.

**Comment by BlazeGuy2** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2172243/output_log.txt)

**Comment by SeanAtr0n** [comment]
fixed
