### ISSUE TITLE
USER ISSUE: 0 coordinate

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8374]
**Version:** 0.7.5.1 beta
![20180707004158_1](https://user-images.githubusercontent.com/4980243/42404918-a8ab485c-8196-11e8-9271-6adefc24ab89.jpg)
![20180707004157_1](https://user-images.githubusercontent.com/4980243/42404919-a8cd7d78-8196-11e8-9ea3-3ba55bce3834.jpg)
And if you on vechicle, you fly.
![unknown](https://user-images.githubusercontent.com/4980243/42404928-ca4f698e-8196-11e8-8a6d-c4f0288d898c.png)
~20% repro by multiple users.

**Comment by SeanAtr0n** [comment]
Most likely fixed in https://github.com/StrangeLoopGames/Eco/pull/3502
