### ISSUE TITLE
USER ISSUE: signs - invisible

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8376]
**Version:** 0.7.6.0 beta staging-4c7f4650
![20180707062954_1](https://user-images.githubusercontent.com/4980243/42406392-4d68071e-81af-11e8-86c4-eb8fa7a41ca6.jpg)
![20180707063715_1](https://user-images.githubusercontent.com/4980243/42406490-6f6c6c36-81b1-11e8-8605-9d6702dd7db2.jpg)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/42479500-02884480-838e-11e8-85b1-71197b2dc78d.png)
Can't repro.

**Comment by elfl0rd** [comment]
Hm... Maube convertation bug?
@MarjieAVolk 
![20180710015209_1](https://user-images.githubusercontent.com/4980243/42480092-62f4dc1a-83e4-11e8-9c4b-155e8909b3e6.jpg)
![20180710015216_1](https://user-images.githubusercontent.com/4980243/42480093-63154400-83e4-11e8-8d5c-f467e710d4f2.jpg)

**Comment by elfl0rd** [comment]
Okay, fresh world.
![20180710015819_1](https://user-images.githubusercontent.com/4980243/42480193-dccf688e-83e4-11e8-9916-b2eddbd3df80.jpg)

**Comment by keegan-o** [comment]
We learned this was an issue with the cache server and it was fixed on Staging.
