### ISSUE TITLE
USER ISSUE: Cant log in

### ISSUE THREAD

**Issue by AppleDipper** [StrangeLoopGames/EcoIssues#8378]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
Try to launch game

**Expected behavior:**
Launched the game

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host
```

**Comment by BlazeGuy2** [comment]
Might be related to Eco.Mods.dll causing issues.  Go to Eco\Eco_Data\Server and delete Eco.Mods.dll.  That is a known issue with 7.5.1 and forcing it to recompile has been fixing it.  Let me know if that works.
