### ISSUE TITLE
Absent room edges do not count as Tier 0 blocks

### ISSUE THREAD

**Issue by babare** [StrangeLoopGames/EcoIssues#8379]
From our observation in 0.7.5.1, while an opening in a wall of a room creates Tier 0 blocks, edges don't act in the same way, edges blocks are taken into account in the Tier average only if there is an actual block here.

This creates a situation where optimizing a room can be done by removing edge blocks instead of using lower tier materials to fill them, leading to buggy looking houses being more efficient.

![2018-07-07 10_04_01-greenshot](https://user-images.githubusercontent.com/12103153/42408442-1bd9b90e-81cd-11e8-871f-fdff6ac247cf.png)

**Comment by SlayksWood** [comment]
Fixed in 8.2.x version
