### ISSUE TITLE
Missing laws feature - Missing Dirt Road Law Options

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8380]
Need 2 additional parameter.
Create dirt road, and pick-up dirt road!

**Comment by Deantwo** [comment]
Suggest you rename this issue.
Maybe: `Missing Dirt Road Law Options`

**Comment by elfl0rd** [comment]
bump

**Comment by D3nnis3n** [comment]
Upvote!
