### ISSUE TITLE
[7.6.1] Election does not work / Send vote is broken

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8381]
The server side evaluation of a sent vote is broken in the current Version.

Players click on 'Send Vote' or 'Update Vote' button, the selected candidates order is send to the Server but the results shows as the player has only gave '1' to the first candidate. So an election is not possible if more then one candidate is there.

A) As user "Voosle." (pay Attention to the dot!) I select the rank and submit the vote:

![image](https://user-images.githubusercontent.com/22961978/42410209-17cbb024-81e6-11e8-8e94-e5ad9743bafe.png)

B) As I can see with Fiddler the correct rank order is send to the api:

![image](https://user-images.githubusercontent.com/22961978/42410055-10ac23e8-81e4-11e8-8b4a-a7d36ee69fb0.png)

C) With the server's response the new result shows a failed calculation. (I anonymized other user names)
In the "All Votes" box is says that I gave candidate1 the rank 1 and selected no rank for candidate 2 "Voosle". That's wrong.
In the background you can see the "Votes Per Round" box that says Voosle got one rank 1. Thats what I voted but not what the "All Votes" box says.
![image](https://user-images.githubusercontent.com/22961978/42410191-dbcb0ebc-81e5-11e8-9ce6-6ea076a4f705.png)

D) After I refreshed the browser with F5 the "Votes Per Round" box shows the same failed calculation result as the "All Votes" box before. No Rank 1 for Voosle. That's wrong.
![image](https://user-images.githubusercontent.com/22961978/42410248-f3a125d4-81e6-11e8-953b-73b66c9a5e33.png)

**Comment by pamduncan** [comment]
I am able to look in our Game.db and see all the actual votes recorded for the people running and yes the votes for the first one running show up but the ones for the others running - who all happened to have higher vote counts we all displaying on the webpage as having no votes case for them.  I thought at first this was just a display issue but if that is the case would not the winner be elected even if the votes did not show n the webpage?

**Comment by johnkslg** [comment]
Elevating to critical as it breaks government

**Comment by johnkslg** [comment]
After closer inspection, lowering to 'high' since you can still vote, just can't do runoff votes.

Depends on https://github.com/StrangeLoopGames/EcoIssues/issues/8648

**Comment by LiaungYip** [comment]
John,

I tried to vote for myself as #1 preference, with no other preferences
allocated. As per previously attached screenshot, my vote for myself was
not recorded.

Runoff voting is certainly broken, but I believe that even normal majority
voting is broken as well.

Lewis.

**Comment by johnkslg** [comment]
Fixed it!
