### ISSUE TITLE
[7.5.1] Contract 'Build Road' : Width, currency and payment will not be saved on close

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8383]
I created a contract with a Bild Road clause. Set the road width to 2 and at the payment clause set some currency and a payment value of 3.000.
Close the Dialog by clicking X.

![image](https://user-images.githubusercontent.com/22961978/42414580-075af2c0-8238-11e8-9255-aae38e24d7dc.png)

When I reopen the contract dialog the width configuration, the currency and the payment are gone (and being reset to the default)

![image](https://user-images.githubusercontent.com/22961978/42414585-0e6bf514-8238-11e8-8838-cc1cdac62da7.png)

**Comment by Deantwo** [comment]
If you check the tooltip of the contract, I think it is actually saved, the editing dialog just doesn't show it?

**Comment by Voosle** [comment]
@Deantwo 
You are right, the tooltip shows the correct values.

And now the payment value seems to work correct again. 
I'm not sure, why this happens. Yesterday I tested it many times. We restartet the Server this night, Maybe this fixed it?

But there is another new problem: I'm not be able to toggle the 'Auto-Accept' check box. The tool tip says that I have to turn it off because of the custom clause. But when I click the green check nothing happens (control seems to be disabled). So, to verify your point above with the tooltip I have to remove the custom clause in this sample contract.

**Comment by MarjieAVolk** [comment]
I would guess the time when you saw incorrect values on the contract, there was an exception during initialization of the UI.  I imagine you no longer have the output log from that session, but if you do see the issue again, the output log would be helpful.

**Comment by Voosle** [comment]
see also #8411

**Comment by Voosle** [comment]
Today (the world is running 7.6.0) I found the currency again switched to my own credits. Mybe because some one else opened the contract just for a short view (the Display currency bug switches the property) and on closing the contract by the other Player, the changed configuration was saved. There was a bug some days before that allows contract changes by other Players...

**Comment by SlayksWood** [comment]
Checked on 0.8.3.0 staging-1066. Wasn't able to reproduce. Seems fixed.
