### ISSUE TITLE
Cannot pick up Logs

### ISSUE THREAD

**Issue by LolindirFox** [StrangeLoopGames/EcoIssues#839]
Using Alpha 5 I'm at logging level one I've seen on the forums where others have had this issue.  After cutting down a tree I cannot pick up logs it says inventory full although it's not and not carrying anything... it's intermittent and happens with different kinds of trees not just limited to a certain kind. so it's almost a lottery of will I be able to take logs from this tree or not, just needs a tweak or something it is certainly game breaking.  I have tried cutting it into the smallest possible size as well to right before it gets too small and unspawns, with no avail. 
![20161117161100_1](https://cloud.githubusercontent.com/assets/23532543/20407793/dd062220-ace0-11e6-956a-ef5834dc8391.jpg)

![20161117161159_1](https://cloud.githubusercontent.com/assets/23532543/20407808/e517c8ba-ace0-11e6-8bb1-30f36f745199.jpg)

**Comment by metachronism** [comment]
Fixed.
