### ISSUE TITLE
Client Crash pushing wheelbarrow

### ISSUE THREAD

**Issue by valheran** [StrangeLoopGames/EcoIssues#8390]
On official staging server (Stuffed Elk)
Second time client hard crash while pushing wheelbarrow carrying stone road (just loaded).
avatar becomes duplicated and remains attached to wheelbarrow until it is emptied and picked up

attached image result of using windows debug from crash dialogue
![image](https://user-images.githubusercontent.com/11647778/42417154-af09b456-82c5-11e8-9f59-d092d5902fd9.png)

**Comment by SeanAtr0n** [comment]
fixed along w/ other crashes in july
