### ISSUE TITLE
USER ISSUE: Squre stone roof

### ISSUE THREAD

**Issue by pjuskr** [StrangeLoopGames/EcoIssues#8394]
**Version:** 0.7.5.1 beta

![roof](https://user-images.githubusercontent.com/5391505/42422178-e4b743cc-82e1-11e8-9e27-dd75413ed967.png)

**Steps to Reproduce:**
Place a single stone roof block on top of roof

**Expected behavior:**
It forms a cone like with Hewn roof	

**Actual behavior:**
The block is cubic and does not fit the rest of the roof at all

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/42789447-363b306c-891a-11e8-8abb-adc847b7f922.png)
Fixed in master as of 7/16.
