### ISSUE TITLE
[7.6.0 staging-4c7f4650] Crash when try to allocate in the Allocate Funds dialog

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8398]
Crash when click "Allocate" in the Allocate Funds Dialog.

In 7.5.1 it crashes when clicking one of the Allocate button in the Treasury Dialog. So I try it with the latest BE version. Now this bug is fixed (see #8354 ) but another one occures.
![image](https://user-images.githubusercontent.com/22961978/42424702-fc81b58a-8310-11e8-9262-d6a77795bdd8.png)

![image](https://user-images.githubusercontent.com/22961978/42424704-02d70cc8-8311-11e8-9817-addf0425c82d.png)

[CrashLog.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2174195/CrashLog.txt)

**Comment by BlazeGuy2** [comment]
Also present on the staging build, reproduced from the treasury command.

**Comment by johnkslg** [comment]
Fixed in 7.6

**Comment by Voosle** [comment]
Still there in todays 7.6.0 Stage Version. see #8460

**Comment by BlazeGuy2** [comment]
fixed on bleeding, forgot to bump it over to staging.

**Comment by Voosle** [comment]
O.k., I will check it there

**Comment by Voosle** [comment]
works in bleeding. :-)
