### ISSUE TITLE
USER ISSUE: Items not crafting, craft time NaN

### ISSUE THREAD

**Issue by GodfatherC** [StrangeLoopGames/EcoIssues#8401]
**Version:** 0.7.6.0 beta staging-4c7f4650

**Steps to Reproduce:**
1. Go to Carpentry Table
2. Try to make Hewn Logs
OR
1. Get full efficiency in Mortar Production Speed
2. Go to Bakery Oven
3. Try to make Baked Pitch

**Expected behavior:**
It should create the items in question.

**Actual behavior:**
Instead the production order simply doesn't progress and the craft time says NaN.

**Comment by elfl0rd** [comment]
0s
![20180709194622_1](https://user-images.githubusercontent.com/4980243/42464161-ed7ec3d4-83b0-11e8-8bc5-d0e3c76ae7ab.jpg)
Max eff and craft
![20180709184039_1](https://user-images.githubusercontent.com/4980243/42464175-f404e242-83b0-11e8-911f-5c7b99088f75.jpg)
![20180709184053_1](https://user-images.githubusercontent.com/4980243/42464178-f423d35a-83b0-11e8-8eed-c211bc49bb1d.jpg)

**Comment by Rooney1007** [comment]
same thing is happening with masonry pitch.  
![bbe9e427be40909faf2ec448c5dcca68](https://user-images.githubusercontent.com/41221723/42720292-950c83a4-86f2-11e8-8b15-db70988fc575.png)

**Comment by BlazeGuy2** [comment]
Being dealt with in #8483
