### ISSUE TITLE
USER ISSUE: Contract Bug

### ISSUE THREAD

**Issue by Disglin** [StrangeLoopGames/EcoIssues#8402]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
Oben Contract Board	,
Make a Custom Contract,
Crash

**Expected behavior:**
Create the Contract

**Actual behavior:**
Wrong number of args passed to method: set_Description.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8244.  Should be fixed in next release.
