### ISSUE TITLE
USER ISSUE: Framed Glass below stockpiles disappear

### ISSUE THREAD

**Issue by mirasrael** [StrangeLoopGames/EcoIssues#8403]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
1. Build ceil from Hewn Log
2. Replace some blocks with Framed Glass
3. Replace other blocks with Brick
4. Framed Glass blocks become invisible, but you can't place anything at their location (they partially appears when you removing closest block)

**Expected behavior:**
Framed Glass blocks stays visible

**Actual behavior:**
Framed Glass blocks become invisible

**Comment by BlazeGuy2** [comment]
Can you post some screenshots?

**Comment by craig-jong** [comment]
I can't get this to reproduce. Is it possible you can add a game save or some screenshots of your issue/exact setup?

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/42494184-26b06578-8428-11e8-93cf-a6207c83c0ae.png)
These empty spaces actually Framed Glass (and you can see it in Room Info)

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/42494220-45bba798-8428-11e8-9a8a-8f7511fb521e.png)
And now I removed single Brick block and nearest blocks appeared

**Comment by craig-jong** [comment]
As long as they don't include the database file, it shouldn't be too large. Just get the game.eco file if you can.

That appears to be tilled dirt above your house - is that correct?

**Comment by mirasrael** [comment]
Yes, it is underground. And also it has Stock Pile over this room. Probably this matters.

**Comment by craig-jong** [comment]
Yup, that was it.

Thanks. I don't need the save now. I'm going to reassign this to Keegan as my initial reaction is that this is a builder issue.

![image](https://user-images.githubusercontent.com/18184943/42591482-a8796e96-84fb-11e8-9f91-80aac5f5f696.png)

I was able to replicate this with the above setup. The empty spaces are framed glass.

Similarly, I have this issue which also might be builder related.

https://i.imgur.com/6kdA3eA.mp4

**Comment by SlayksWood** [comment]
Checked on 0.8.3.0 staging-1066. Wasn't able to reproduce. Seems fixed.
