### ISSUE TITLE
Bug Report #01

### ISSUE THREAD

**Issue by Stahlhelm-TV** [StrangeLoopGames/EcoIssues#8405]
Strange Truck mesh bug.. cant say more but its only on one side.

![desktop screenshot 2018 07 09 - 13 21 15 57](https://user-images.githubusercontent.com/27901510/42447949-d74fc82c-837b-11e8-9a59-5c0136c6cc02.png)

**Comment by keegan-o** [comment]
Fixed in master, along with some other weirdness with the lights on trucks.
