### ISSUE TITLE
SP ISSUE: [7.5.1] Game silently crashes / Force close serve.exe

### ISSUE THREAD

**Issue by Mahsaap** [StrangeLoopGames/EcoIssues#8406]
I recently formatted my computer and now when I try to load a SP world the game will silently crash upon entering world. After this I have to force close ecoserver.exe to completely close the game.

**Comment by BlazeGuy2** [comment]
Wait, just saw it in the title.  It might be an issue with Eco.Mods.dll if you are running on Windows.  Can you try going to Eco\Eco_Data\Server and try deleting that file?  It should force a recompile of mods to help you log on.

**Comment by Mahsaap** [comment]
Ill try that later. Thanks

**Comment by BlazeGuy2** [comment]
Cool, let me know if it works.

**Comment by Mahsaap** [comment]
That didn't help, Just closes the game window with no error. Server requiring force close, same as before.
Reinstalled the game, nothing.

**Comment by johnkslg** [comment]
@Mahsaap  Please message me on Discord.gg/eco @johnk
Working on this now

**Comment by Mahsaap** [comment]
Issue was fixed in 7.6.0 . thanks for the help guys.
