### ISSUE TITLE
3rd view, bug with property highlight

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8408]
**Version**: 0.7.6.0 beta staging-4c7f4650
In 3rd view, property highlight looks like 2d...
![20180709181222_1](https://user-images.githubusercontent.com/4980243/42464274-40863030-83b1-11e8-9535-86662daad07c.jpg)
![20180709181217_1](https://user-images.githubusercontent.com/4980243/42464282-44947376-83b1-11e8-8d01-f7b1a1cb5d1c.jpg)
![20180709181206_1](https://user-images.githubusercontent.com/4980243/42464283-44b76cb4-83b1-11e8-93e9-cf660d41f9d0.jpg)

**Comment by SeanAtr0n** [comment]
fixed a while back

**Comment by SeanAtr0n** [comment]
correction... fixed in 7.7
