### ISSUE TITLE
"Minimal" room 1x1x1

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8409]
**Version**: 0.7.6.0 beta staging-4c7f4650
you can complete tutorial by build 1x1x1 "room"
Looks as bug...
![20180709180748_1](https://user-images.githubusercontent.com/4980243/42464351-6feaf70c-83b1-11e8-99ba-977f1dfcb1f4.jpg)
![20180709180819_1](https://user-images.githubusercontent.com/4980243/42464350-6fc246a4-83b1-11e8-82d3-b134fa1aa591.jpg)

**Comment by craig-jong** [comment]
This isn't really a bug. A 1x1x1 room IS a valid room (technically, though you can't get inside it) and I'm not sure we want to add something specifically excluding this possibility.
