### ISSUE TITLE
[7.6.0] Items listed as soldout are present in the linked storage chest

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8410]
Stores spawned via the /spawneconomy command has their inventory listed as sold out, but they shouldn't be sold out.

Used Testalpha to spawn economy, and had my own user access the store.

**Store**
![storeitems](https://user-images.githubusercontent.com/35509188/42475050-4f4d6562-837e-11e8-8536-3bdf645cfc48.PNG)

**Linked Chest**
![inventory](https://user-images.githubusercontent.com/35509188/42475066-5d71ef32-837e-11e8-84c4-a04ddf9da15c.PNG)

**Comment by BlazeGuy2** [comment]
Seems to fix itself after I sell something to the store.

**Comment by johnkslg** [comment]
Fixed
