### ISSUE TITLE
User's game crashes after loading without message

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8423]
https://www.twitch.tv/videos/283059236
User is EcoBuilder13 on Discord and is available for troubleshooting.
User has a video card ATI Radon HD 4200 which is below spec.

It's possible the silent crash is due to the video card, in any case it should display an error to the player explaining this as the reason though if that is determined to be the problem with no fix available.

**Comment by SeanAtr0n** [comment]
Seems like a windows, unity or hardware issue we have no control over... even if they got in game it would probably be unplayable so devoting significant resources to investigating further than the multiple man-hours we have already spent seems unwise

**Comment by johnkslg** [comment]
Is already fixed in 7.6
