### ISSUE TITLE
Continue button not working for local server

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#8424]
Master only.

I can join via the join screen to my dev server, but if I try to use the continue button it will say 'incompatible version' or 'no response from remote host'

**Comment by MarjieAVolk** [comment]
Well idk it will be high priority some day

**Comment by metachronism** [comment]
this is working fine for me on master, are there more repro steps?

**Comment by MarjieAVolk** [comment]
It's broken for me every time, still is.

**Comment by MarjieAVolk** [comment]
Okay I've been poking at this some more, and it seems the reason the Join screen is working and not the Continue button is probably because on the join screen it's connecting by ip address, while on the continue button it's connecting by unique id.

I have gotten it to successfully connect via unique id both via the continue button and via the join screen on a couple of occasions now.  It seems like it will be connecting fine, and then one time it will say 'no response from remote host' or whatever, and then each time after that it will say 'incompatible version'.  I haven't actually stepped down into the network client / server code yet.

**Comment by MarjieAVolk** [comment]
Welp.  Now it's working fine.  :/

**Comment by metachronism** [comment]
The only time I've seen this fail is when I forgot that I had another server running in the background that was a different version
