### ISSUE TITLE
[7.6.0] Contract UI Text Overlap

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8426]
Slight overlap of text (most noticeable with plants on property/none) when the UI window width is minimized.

![contract ui overlap](https://user-images.githubusercontent.com/35509188/42544444-c396c83a-8466-11e8-9106-d786d21ddde2.PNG)

**Comment by GophTheGreat** [comment]
It wraps to the next line properly now. Closing.
