### ISSUE TITLE
[7.6.0] Campsite Crafting needs sound

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8428]
No sound effects play when I craft a workbench at the campsite.
![need_sounds](https://user-images.githubusercontent.com/35509188/42544922-743d7c72-8469-11e8-9291-d05a275fd79b.PNG)

**Comment by Quadbro** [comment]
Sound may appear a bit later (day-or few) cause it's svn related

**Comment by beastyn** [comment]
I can hear tent opening sound, but there is no any craft sound.

**Comment by Quadbro** [comment]
the sound is in, just rechecked
