### ISSUE TITLE
[7.6.0] Using the Claim Tool while holding hewnlogs places them upon claiming land

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8429]
When holding a hewnlog and using the claim tool to claim land, places a log on the ground after claiming the land.

![propertyclaim](https://user-images.githubusercontent.com/35509188/42545101-92bb4700-846a-11e8-943e-f8e3388c64af.PNG)

**Comment by seccombew** [comment]
Potential Duplicate
