### ISSUE TITLE
Elevator - missing occupancy

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8430]
Currently, elevator is not count as door.
But... They need hole on the roof for use, it disable housing.
Please, add occupancy to the ground part, it's resolve the problem!

**Partially suggestion** but little issue.

**Comment by keegan-o** [comment]
Assigning Craig because all Occupancy changes require a code PR to fix, which is usually more efficient to have programmers do.

**Comment by keegan-o** [comment]
Updated the prefab in master, programmer will update occupancy with a PR and then this can be closed.

**Comment by SeanAtr0n** [comment]
Keegan should get credit for this one... closed with https://github.com/StrangeLoopGames/Eco/pull/3097 (probably in the hotfix, or 7.7)
