### ISSUE TITLE
Missing law feature - limit world objects

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8431]
Need a way to limit world objects per player and per world.
Like "when place blast furnace if >10 blast furnace per player or > 40 blast furnace per world then prevent, othervise allow"

**Comment by Deantwo** [comment]
Won't they just place the blast furnaces off their claim?

Even if you add a "prevent placing blast furnace on not own property" they will just place the max limit of blast furnaces on their claim, unclaim the plots the blast furnaces are on and place a new row of blast furnaces. Then once they are satisfied they claim all the blast furnaces again.

**Comment by Deantwo** [comment]
More interesting would be a way to tax players depending on the number of an object they have.

Tax the player 100 currency per blast furnace they have on their property.

**Comment by elfl0rd** [comment]
> and per world.

**Comment by Deantwo** [comment]
If you limit number of blast furnaces a player can place, they just need someone else to place the extra blast furnaces for them. Harder to cheat on your own I will give you that, but how does that count work if you need to move your 10 blast furnaces to another location?

But I think that is already possible, limit number of times a player can place something.

**Comment by Deantwo** [comment]
Not saying that this law addition shouldn't be added, it is a good idea.

But the example given would not be solved by it. A way to limit the amount of CO2 a player can emit per second would be more useful.

**Comment by elfl0rd** [comment]
Why you see only pollution?
e.g.
per day,
if player have > 10 steel light then tax 100 coins

**Comment by MarjieAVolk** [comment]
Fixed in 8.0 (you can limit picking up/placing world objects)
