### ISSUE TITLE
Can't buy from stores if you are authorised on the store

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#8435]
Trying to buy goods from a player's store,
Where I am authorised on the land deed for the location of the store,

The "Trade" button does not appear, so you can't actually buy or sell anything.

In below screenshots, I am trying to buy from a store owned by the player Kadrin.

This is on the Stuffed Elk staging server.

![image](https://user-images.githubusercontent.com/2173684/42603625-ea8ac922-85b1-11e8-81dc-2743a6578677.png)

![image](https://user-images.githubusercontent.com/2173684/42603650-01b3c590-85b2-11e8-970a-309d3210c51d.png)

**Comment by LiaungYip** [comment]
On other stores (where I don't have authorisation) the store shows a "Trade" button like usual.

![image](https://user-images.githubusercontent.com/2173684/42603757-71770c52-85b2-11e8-9879-3ab74b50308c.png)

**Comment by SlayksWood** [comment]
I assume it's intented behavior now. Closing for now.
