### ISSUE TITLE
USER ISSUE: currency report need scrolling and resizing enabled!

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8437]
**Version:** 0.7.5.1 beta

If you have lot of players with currency you see this.
![20180712013435_1](https://user-images.githubusercontent.com/4980243/42604964-15044b30-857e-11e8-9fc8-1f59b0cebcae.jpg)

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6056
