### ISSUE TITLE
Eric's Backyard

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#8438]
Need a picture for research

**Comment by BlazeGuy2** [comment]
Is this a legit bug?  Or do you need a pic of the backyard of Eric's house?

**Comment by craig-jong** [comment]
It's a "legit bug" in that I want it. This was discussed at Happy Hour and, since it hasn't happened yet, I made a bug.

**Comment by craig-jong** [comment]
I'll close this for now, but know it isn't over...

**Comment by BlazeGuy2** [comment]
I'm confused.
