### ISSUE TITLE
Can no longer propose laws

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8439]
Probably caused by the fix that shuts down the server when the client has shut down.
Web interface just thinks I'm logged out when I opened it from the game seconds ago.

![cantproposelaws](https://user-images.githubusercontent.com/35509188/42606477-b7da8550-8532-11e8-861c-3b7432fec9ae.PNG)

**Comment by SeanAtr0n** [comment]
doesn't appear to be related to the OpenURL change i made, tokens still get passed

**Comment by MarjieAVolk** [comment]
Okay, so I determined this was only happening when running through steam (also happened when emulating steam in the editor).  I just tried commenting out sean's alternative web page opening thing while emulating steam, and then it worked.  So it seems it is related to that after all.

**Comment by MarjieAVolk** [comment]
Okay, after further examination, looks like when using the new browser opening method, the authtoken gets truncated.

**Comment by SeanAtr0n** [comment]
fixed in release, although that broke the steam hack
