### ISSUE TITLE
Bad lightmap?

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8440]
**Version:** 0.7.5.1 beta
![20180710233748_1](https://user-images.githubusercontent.com/4980243/42609608-08ee75a6-8596-11e8-9b6d-c0f2b10ad77d.jpg)

**Comment by SeanAtr0n** [comment]
whats in the inventory?

**Comment by elfl0rd** [comment]
Asphalt ramp too
![20180712163803_1](https://user-images.githubusercontent.com/4980243/42641364-0f85d1b8-85fd-11e8-947b-6e1588fe9952.jpg)
![20180712163813_1](https://user-images.githubusercontent.com/4980243/42641365-0fac1472-85fd-11e8-8684-6221fd96abb4.jpg)

**Comment by seccombew** [comment]
Keegan, can you investigate?

**Comment by elfl0rd** [comment]
Applies to tailings too
