### ISSUE TITLE
USER ISSUE: flat steel form 1 is not connect to dirt

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8441]
**Version:** 0.7.6.0 beta staging-262ce70b
(like another materials)
![20180712054626_1](https://user-images.githubusercontent.com/4980243/42609800-0efe08c0-8597-11e8-841f-1f92e2d92c30.jpg)

**Comment by elfl0rd** [comment]
(and maybe sand)

**Comment by keegan-o** [comment]
Fixed in master.
