### ISSUE TITLE
Hanging signs are floating

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8442]
**Version:** 0.7.6.0 beta staging-262ce70b

![20180712055017_1](https://user-images.githubusercontent.com/4980243/42609941-c1e42280-8597-11e8-80b6-a38f3cd0938c.jpg)
![20180712055129_1](https://user-images.githubusercontent.com/4980243/42609942-c20e5348-8597-11e8-849c-b4867ffe34c6.jpg)

**Comment by seccombew** [comment]
You have to attach sign to ceiling.

**Comment by craig-jong** [comment]
They should be attachable to walls as well. Should find a good solution to this so we can have wallmounted things.

**Comment by elfl0rd** [comment]
As temporary solution - return old position please :(
It's terribe, signs basically used on walls, not on ceilings...

**Comment by keegan-o** [comment]
I will put hanging ones back against the back of the meter of the space! Been going through the sign wringer lately, but we will eventually make it through to the day when signs are good and useful.

**Comment by keegan-o** [comment]
Alrighty, checked in lots of changes to signs in master. Not going to be easy to migrate these back to staging again so they will be in the build after 7.6.
