### ISSUE TITLE
7.5.1 - Electric Wall Lamp requires being placed on solid ground.

### ISSUE THREAD

**Issue by MaxInertia** [StrangeLoopGames/EcoIssues#8445]
![image](https://user-images.githubusercontent.com/12981415/42628628-4cf04b12-8596-11e8-8086-e917021f6c15.png)

This probably shouldn't be a condition for it to function? :P

**Comment by elfl0rd** [comment]
Fixed in 7.6 :P

**Comment by BlazeGuy2** [comment]
Fixed in 7.6.0, closing
