### ISSUE TITLE
/frontpage query sending wrong time for graphs.

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#845]
/frontpage query sending wrong time for graphs.

For all front page graphs, it is sending time like:
        "TimeMin": 0.0028038053600941749,
        "TimeMax": 0.0028038053650438679

Even if the server time is older than 0.002
And I think timeMin should usually be 0

https://gyazo.com/b5d39ed79054b3fa02e3676acf65a94f

**Comment by MarjieAVolk** [comment]
So I can switch all the timeMins to being 0 by changing a default value - but there seems to be a special system in place to toggle between timeMin being 0 and being the same as timeMax... so not really sure why that would be put there deliberately.

As for the time being wrong, I don't immediately see any issues.  The graphs (and thus time stamps) will only be refreshed every 10 minutes no matter how many times you call front page - could that be what you're seeing?  Or is timeMax still staying at such a low value even after minutes or hours?

**Comment by MarjieAVolk** [comment]
Wait no I've found it now... the 10 minute delay thing isn't done properly.  Okay, will send fix shortly

**Comment by rainfarmer** [comment]
The graphs from the /frontpage query are still giving off timing, when the time is before 1 day

You can see /timerange query shows 0.05 days 
https://gyazo.com/7a03a48240ff47f04d2b9e854a32633c

And /frontpage query graph is showing time of 0.01 https://gyazo.com/b3f890b41c0c61f026e98483c82bccba

Should be displaying 0.05 days for the /frontpage query graphs.
Note: we display graphs below 1 day, at 2 decimal places, rounded down.

**Comment by MarjieAVolk** [comment]
Hmm, so I don't see this problem on my local server just now; but it has been running for more than one day.  You're seeing that when the time is lower than one day, it's a problem, and after one day it is fixed?  Or all the servers you're testing just happen to be younger than one day?

**Comment by rainfarmer** [comment]
In my test approx. before 1 day, the error happens, but approx. after one day it does not happen.

I'm not sure the exact time it works and doesnt.

You can reset the server and generate data with this query to test:
http://localhost:3001/datasets/generatetestdata?users=5&days=0.05&generateClimateData=true

**Comment by MarjieAVolk** [comment]
So yeah, I haven't found any wrong behavior yet... I'm not 100% sure that it's wrong, because there are a few different things that get updated at different delays, so within a time range of < 1 hour there will be some inexact time stamps.

**Comment by MarjieAVolk** [comment]
Wait a second... I did just find something impossible.  Okay continuing to investigate lol

**Comment by noblackthunder** [comment]
=) typical .. when you think nope its all ok you suddenly see it ;)

**Comment by MarjieAVolk** [comment]
Alright no, I got unconfused again I think.

So yeah, I haven't seen this behavior that you're seeing during my fiddling with the web API.  From what I understand, the time stamps coming from /timerange get updated once every 30 minutes, while the time stamps coming from /frontpage get updated once every 10 minutes.

So the /frontpage time should never be more than 10 minutes smaller than the /timerange time.  Which is not true in the example you gave me.  So yeah I have no idea what is going on.  Are you on a different branch that didn't get the fix or anything like that?

**Comment by rainfarmer** [comment]
I was using marjie-teachertools, ill retry

**Comment by MarjieAVolk** [comment]
I've primarily been just playing myself to get data

**Comment by MarjieAVolk** [comment]
Did you ever conclude whether this was fixed on master?

**Comment by rainfarmer** [comment]
Its ok,

I think I was just noticing that the /frontpage query and the /timerange query display different times, as you said, based on their update cycle.
