### ISSUE TITLE
Math issue (Bleeding edge)

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#8451]
Tinkering around in Bleeding Edge, I came across this UI/math bug:
![image](https://user-images.githubusercontent.com/38095046/42669066-52fb4f42-8619-11e8-8c5f-5685a3b65195.png)
Hoping the image posted.  Basically, it say that there was enough resources to create -2,147,484,000 pitch

**Comment by MarjieAVolk** [comment]
Do you have a game save where this is happening?  Would you be able to share that?

If not, could you tell me how you got this to happen?

**Comment by D3nnis3n** [comment]
Never seen this again, likely fixed. Please open a new issue if this ever reoccurs.
