### ISSUE TITLE
USER ISSUE: At 0.7.6.0 beta staging, a error in the manufacturing cycle

### ISSUE THREAD

**Issue by hairmiya** [StrangeLoopGames/EcoIssues#8452]
**Version:** 0.7.6.0 beta staging-2b46eb65

Oil refinery, Pump jack, Combustion Generator on the Robotic assembly line maked is wrong!
We need Combustion Generator supply electric power,first of all.
No electric power supply, the electric machinist table, Pump jack etc. couldn`t work. 
No Oil refinery, Pump jack, we couldn`t make epoxy and plastic, No epoxy and plastic, we couldn`t make the Robotic assembly line.
This is too stupid!
Oil refinery, Pump jack, Combustion Generator moving to assembly line is good.

**Comment by craig-jong** [comment]
Looks like a bunch of stuff that wasn't s'posed to be moved to the robotics were moved there.

**Comment by Deantwo** [comment]
Yup, it is impossible to proceed to electronics.
**Pump Jacks** are in a catch-22 with Robotic Assembly Line.
See: #8478

**Comment by GokouZWAR** [comment]
Our solution was to change the steam engine to electrical power vs mechanical power.

Then to fix pumpjack and oil refining we moved it to the assembly table since those recipes weren’t the issue, just the table to produce it on.

**Comment by springphul** [comment]
This issue is closed.. so what's is the result? Will be the fix in an upcoming Hotfix? I am waiting for 5 days now, to actually be able to progress in the game.

**Comment by Deantwo** [comment]
@springphul, 7.6.1 was released yesterday. I assume the bug is fixed in that, but it is not exactly mentioned in the patch notes. Maybe it is just part of "Misc fixes, but I haven't had a chance to play and find out yet.
