### ISSUE TITLE
Crashing when joining without message/crash log

### ISSUE THREAD

**Issue by MightyPiggie** [StrangeLoopGames/EcoIssues#8453]
When I join a new server when I just downloaded the game I keep crashing without a message or crash log as shown in the video
https://youtu.be/PortnIdMSBU
Anyone that can help me?

**Comment by BlazeGuy2** [comment]
Are you currently running 7.5.1?  That is a known issue on that version.  We are about to release 7.6.0 to the public, let me know if it gets fixed on that.

**Comment by MightyPiggie** [comment]
After doing more research I found a solution. You can fix it with applying
windows 8 compatibility mode to the game.
