### ISSUE TITLE
0.7.6 USER ISSUE: campsite crafting is not see internal inventory

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8456]
**Version:** 0.7.6.0 beta staging-d839db67
![20180713194644_1](https://user-images.githubusercontent.com/4980243/42703596-aab45456-86d5-11e8-99e4-e27bfebd721b.jpg)
![20180713194649_1](https://user-images.githubusercontent.com/4980243/42703597-aad37b7e-86d5-11e8-9437-1195b39db579.jpg)

As one of results - https://github.com/StrangeLoopGames/EcoIssues/issues/8454

**Comment by craig-jong** [comment]
You shouldn't even be able to put carried items into its internal inventory...

I swear I added that. I have no idea where that requirement went...

**Comment by elfl0rd** [comment]
:'D

**Comment by OtherMike** [comment]
Note that this is a problem the other way as well - when crafting something at the campsite, it cannot put the products into its own inventory even when there is space

**Comment by craig-jong** [comment]
fixed in above pr, will be in next non-hotfix release.
