### ISSUE TITLE
0.7.6 USER ISSUE: wheelbarrow replaced back to small wood cart?

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8457]
**Version:** 0.7.6.0 beta staging-d839db67
Wheelbarrow now not have reciepe, workbench contain small wood cart.
![20180713195001_1](https://user-images.githubusercontent.com/4980243/42703726-10dbadc4-86d6-11e8-803e-32df9562662f.jpg)

**Comment by SeanAtr0n** [comment]
we are letting ppl have the option to use either until wheelbarrow gets polished a bit more

**Comment by elfl0rd** [comment]
Okay, but small woden cart is not have icons. :(

**Comment by SeanAtr0n** [comment]
could get rid of the small cart now
