### ISSUE TITLE
0.7.6 USER ISSUE: no food intro and no food UI after tutorial complete.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8458]
**Version:** 0.7.6.0 beta staging-d839db67
![20180713195243_1](https://user-images.githubusercontent.com/4980243/42703845-6b09df64-86d6-11e8-84c5-072cb92a3487.jpg)

**Comment by johnkslg** [comment]
Could not repro in staging:
- The Forage Food tutorial came up when I ran out of food
- Then when I picked up food it showed the food tutorial.
Please reassign if this is not happening for you

**Comment by elfl0rd** [comment]
Looks like deadlock in tutorial, i cant repro (I do not remember all the actions that led to the error)
But I'll try this weekend

**Comment by elfl0rd** [comment]
gotcha!
![20180714050006_1](https://user-images.githubusercontent.com/4980243/42719705-f7ec4506-8722-11e8-990f-99fdb0531206.jpg)
if you close (press [x]) on foliage for food tutorial section - food ui is not show.

**Comment by johnkslg** [comment]
Will be in next hotfix!
