### ISSUE TITLE
Sales tax apply to Credit

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#8459]
Sales tax should not affect player credit.

It makes bartering harder to do with credit when there is a sales tax in place to tax the minted currency.
For example, "trade 1 log for 2 hewn logs" shops are super hard to do if you have to account for the sale tax percentage.
See: https://github.com/StrangeLoopGames/EcoSuggestions/issues/443

Could also allow the leader to set taxes on individual currencies independently.
See: https://github.com/StrangeLoopGames/EcoSuggestions/issues/454

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#457
