### ISSUE TITLE
Exception on Stuffed Elk: 'Could not find matching method GetWorkorderTooltip on type TableTracker taking 1 parameters.'

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#8463]
![image](https://user-images.githubusercontent.com/6262198/42705102-19230b0c-8687-11e8-8113-2f58e012c5e5.png)

Stack:

>	Eco.Shared!Eco.Shared.Networking.RPCManager.InvokeOn(Eco.Shared.Networking.INetClient client, Eco.Shared.Serialization.BSONObject bson, object target, string methodname) Line 274	C#
 	Eco.Core!Eco.Core.Controller.ControllerManager.HandleViewRPC(Eco.Shared.Networking.INetClient client, int controllerID, string methodname, Eco.Shared.Serialization.BSONObject bson) Line 485	C#
 	Eco.Plugins!Eco.Plugins.Networking.Client.ViewRPC(Eco.Shared.Networking.INetClient client, int id, string methodname, Eco.Shared.Serialization.BSONObject bson) Line 393	C#
 	[External Code]	
 	Eco.Shared!Eco.Shared.Networking.RPCManager.TryInvoke(Eco.Shared.Networking.INetClient client, object target, string methodname, Eco.Shared.Serialization.BSONObject bsonArgs, out object result) Line 307	C#
 	Eco.Shared!Eco.Shared.Networking.RPCManager.InvokeOn(Eco.Shared.Networking.INetClient client, Eco.Shared.Serialization.BSONObject bson, object target, string methodname) Line 271	C#
 	Eco.Shared!Eco.Shared.Networking.RPCManager.HandleReceiveRPC(Eco.Shared.Networking.INetClient client, Eco.Shared.Serialization.BSONObject bson) Line 444	C#
 	Eco.Plugins!Eco.Plugins.Networking.NetworkServer.ReceiveEvent(Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) Line 154	C#
 	Eco.Shared!Eco.Shared.Networking.NetObject.ReceiveEvent(Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) Line 69	C#
 	Eco.Plugins!Eco.Plugins.Networking.Client..ctor.AnonymousMethod__52_1() Line 113	C#

**Comment by johnkslg** [comment]
Fixed
