### ISSUE TITLE
Popup on starter stockpile is too high

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8465]
Easy to miss for newbs
![image](https://user-images.githubusercontent.com/3536496/42705430-22f1f264-8688-11e8-81cf-ffc539909b8a.png)

![image](https://user-images.githubusercontent.com/3536496/42705437-2aa3384c-8688-11e8-909f-41082486288e.png)

**Comment by SlayksWood** [comment]
merged to #10294
