### ISSUE TITLE
Currency Rounding erorrs 

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8466]
There are 0,02 Player's Credits at the Treasury and I whant to pay it to this Player (it's me, the leader).
But it says 'not enough money in Treasury to distribute' when I click Allocate.

With an amount of 0,01 it works one time. But after that, with 0,01 in the treasury, it doea not work again with 0,01.

![image](https://user-images.githubusercontent.com/22961978/42705449-a40d72ce-86d3-11e8-8882-d4b43d2187e4.png)

Just found some nice additon:
Maybe there is some rounding missing, when taking tax on sale before (was 2% tax when it was collected)
![image](https://user-images.githubusercontent.com/22961978/42705929-4c7180c6-86d5-11e8-9216-3b102a039e33.png)

**Comment by beastyn** [comment]
From GDragon
As far as I can see, the logic of this button was broken.
It shouldn't just "substitute" a number, it should send "everything" of the selected (e.g. currency).
In my view, the number should be represented as "All" after it has been pressed.

**Comment by SlayksWood** [comment]
#18578
> We minted 200k coins at the beginning of the game, throughout all the buying and selling of coins the rounding errors have accumulated significantly. As you can see after 7 days of transactions we now have ~535 extra money in circulation.
> ![image](https://user-images.githubusercontent.com/7077730/95032946-0c7d8580-0682-11eb-880e-fc5b4570f84b.png)

**Comment by SlayksWood** [comment]
> Fairly simple request here. Occasionally you will get an error when trying to spend all of a particular currency ("You currently have 1 gjsmo credit but you need 1 gjsmo credit") which has all the hallmarks of being a floating point error where you actually only have 0.9999999999992 credits instead of 1.
> 
> It would be significantly better to store currency as an integer in cents (0.01 credits). This is how the professional financial and banking industry does it and it eliminates this kind of error. It appears that prices in the store cannot be set lower that 0.01 credits, which is perfectly reasonable, so the minimum storable number should be 0.01 or 1 cent. 1.00 credits would be stored as 100 cents, etc.

**Comment by TwixterZ** [comment]
This is no longer an issue on recent patches, thank you for reporting this to us!
