### ISSUE TITLE
USER ISSUE: distribution station, reciepe correct?

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8469]
**Version:** 0.7.6.0 beta staging-d839db67
They looks as metall frame, with wooden floor.
But creates from only hewns logs...
![20180713211332_1](https://user-images.githubusercontent.com/4980243/42707102-c3884120-86e1-11e8-9546-f4caf7cdb947.jpg)
![20180713211316_1](https://user-images.githubusercontent.com/4980243/42707103-c3cea3fe-86e1-11e8-8d99-89209691992b.jpg)

**Comment by craig-jong** [comment]
Yes, this is correct. The art is probably going to get an update. Probably.
