### ISSUE TITLE
Butchery skill broken

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#847]
Eco 5.0

Butchery skill book needs 20 raw meat and 50 board.
But a butchery table is needed to make raw meat.
Butchery table requires Butchery Skill bool to build.

Spawned butchery skill book, built butchery table, but cannot use butchery table as Butchery Lvl 1, 2, 3 and 4 are required, even though Butchery Research is maxed out at Level 1.

![image](https://cloud.githubusercontent.com/assets/6193670/20661531/24de5e6a-b5b4-11e6-8788-c546212471f2.png)

**Comment by craig-jong** [comment]
The first part is definitely a problem; will fix.

The second part is actually intentional. The butchery skill is entirely separate from the research skill. I'm probably going to add a dependency with cooking since otherwise the skill tab may not appear.
