### ISSUE TITLE
[7.5.1] Instanciated Mint switches backing item and Creator for some reason

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8471]
Some days ago I placed a Mint in room claimed by me. I named the currency 'Test Coin', select 'Plant Fibers' as backing item and created some coins. As expected the coins are shown in the 'Your Currencies' list. I was happy my test worked and I turned for other tasks.

A day later I came back to the mint to test some renaming to the minted currency. But then I found the backing item was switched to 'Gold Ingots' and the Creator switched to another Player.

The mint is placed on my property and the mint and the deed is non public and only my Name is on the whitelist. So it is impossible for the other player to use this mint.

I'm absolutely sure, I selected Plant Fibers as the 'never changeable' backing item. And I never had any Gold Ingots, so it is also impossible that I created Coins with that.

![image](https://user-images.githubusercontent.com/22961978/42707192-b17db5f8-86d9-11e8-82c0-8940dc30e901.png)

![image](https://user-images.githubusercontent.com/22961978/42707201-bd4c2356-86d9-11e8-8169-7313c6e3973a.png)

**Comment by D3nnis3n** [comment]
Never seen this since a lot of changes to mints have been made. If this issue occurs again, please open a new issue.
