### ISSUE TITLE
0.7.6 USER ISSUE: you cannot easy remove huckleberry bush

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8474]
**Version:** 0.7.6.0 beta staging-d839db67
Only one way - get shovel and dig block under bush!
(or place block over bush)
![20180713212400_1](https://user-images.githubusercontent.com/4980243/42709018-b841cc22-86e7-11e8-80f3-c5571c277cdf.jpg)

**Comment by johnkslg** [comment]
scythe should do it?

**Comment by elfl0rd** [comment]
Why not?

**Comment by elfl0rd** [comment]
or better - shovel, like camas.
(direct, not dig block under)
