### ISSUE TITLE
AuthComponent.OnAuthChanged not called when object auth mode changes

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8476]
To repro:
- Place workbench
- Change auth mode to 'public' 
- See via breakpoints that no call to OnAuthChanged.Invoke() happens

Tried digging into what is supposed to call this but couldnt figure it out.
The problem caused by this bug is that the economy viewer doesnt update its list of public tables, and possibly other problems.
Note that it sounds like there may be a separate issue related to server restarts.

**Comment by MarjieAVolk** [comment]
Fixed on staging
