### ISSUE TITLE
7.6.0 Oil Drilling Catch-22

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#8478]
You now need a **Robotic Assembly Line** to make **Pump Jacks**, but **Robotic Assembly Line** requires **Petroleum** which requires that you have **Pump Jacks**?

**Oil Drilling** is now  a catch-22.
Impossible to proceed to electronics.

**Comment by Deantwo** [comment]
Duplicates: #8452

**Comment by BlazeGuy2** [comment]
Closing since it's a dup/related.
