### ISSUE TITLE
[7.6.0] Cannot accept Contract, because Contractor doesn't have enough of it's own Credits

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8479]
He has infite of his own Currency, or do I missunderstand 'Deposit'?

![image](https://user-images.githubusercontent.com/22961978/42712274-47f9d78a-86eb-11e8-9b98-fd25c42e4943.png)

**Comment by OtherMike** [comment]
The way this is set up, the person doing the work needs to already have 2 of your credits to take the contract -- try having them sell something to your store, then accept the contract again.

If you are trying to accept your own contract, that shouldn't work either, but if that is what you are trying, the error message is wrong.

"deposit" is a payment the worker makes, that they forfeit if they fail the job.
