### ISSUE TITLE
USER ISSUE: Bison stuck shooting caused crash

### ISSUE THREAD

**Issue by Fearthebearcat** [StrangeLoopGames/EcoIssues#8480]
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
Bision was stuck on a single piece of floating dirt, i shot it, i got a D/C symbol. Game back to main menu.

**Expected behavior:**
Bision should have hopped down and ran.

**Actual behavior:**
The following error message popped up:
```
Connection timed out
```

**Comment by johnkslg** [comment]
Your connection timed out, could it be you just lost connection?

**Comment by BlazeGuy2** [comment]
No response, closing
