### ISSUE TITLE
USER ISSUE: Hewn logs not crafting in Carpenter table

### ISSUE THREAD

**Issue by Fearthebearcat** [StrangeLoopGames/EcoIssues#8483]
![20180713172625_1](https://user-images.githubusercontent.com/7866088/42714666-f1175fe2-86c1-11e8-8fac-e67e9f1d5df4.jpg)
![20180713172713_1](https://user-images.githubusercontent.com/7866088/42714747-2e2effca-86c2-11e8-8d31-d7376ab1a26e.jpg)

**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
Craft Hewn logs, is called "Hew Logs" has a 0 second crafting time. When selected it says time remaining NaN.

**Expected behavior:**
Crafted hewn logs.

**Actual behavior:**
Does not craft hewn logs.

**Comment by craig-jong** [comment]
It's s'posed to be 3 seconds, but I guess something is up with how we're rounding numbers.

Fortunately you can craft them at workbench so this isn't game crippling, but its very unfortunate.

**Comment by pamduncan** [comment]
Per Johk referenceing the following 
 https://github.com/StrangeLoopGames/EcoIssues/issues/8493 
https://github.com/StrangeLoopGames/EcoIssues/issues/8503

https://github.com/StrangeLoopGames/EcoIssues/issues/8496
https://github.com/StrangeLoopGames/EcoIssues/issues/8499
https://github.com/StrangeLoopGames/EcoIssues/issues/8504

**Comment by elfl0rd** [comment]
Oops, wrong link to first report.
https://github.com/StrangeLoopGames/EcoIssues/issues/8401

**Comment by HeimerAlz** [comment]
i found a connection with a specific skill
view the link: #8524

**Comment by Wimiles** [comment]
Any workarounds for this issue as of yet?

**Comment by Wimiles** [comment]
![image](https://user-images.githubusercontent.com/40622216/42737900-8c5d5f4c-882f-11e8-99c5-81360711a065.png)

I think it may be a resource cost issue, rather than a time issue.  As you can see from the attached screenshot, it is showing the incorrect number of materials in the "Missing ingredients" area.  Somewhere in the area of -2,147,484,000.

**Comment by craig-jong** [comment]
fixed in the next hotfix
