### ISSUE TITLE
Player invisible after someone pickup object to which it is attached

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8484]
**Version:** 0.7.6.0 beta
see video.
https://youtu.be/B3fiNBd-oUo
(you need pick up vehicle with player inside)
![20180714011407_1](https://user-images.githubusercontent.com/4980243/42716539-af156e0c-8704-11e8-9f7e-7571d6bfa753.jpg)
![20180714005847_1](https://user-images.githubusercontent.com/4980243/42717052-45f2cb9c-8707-11e8-9847-6675366750da.jpg)

**Comment by elfl0rd** [comment]
Up
https://www.youtube.com/watch?v=dlK_AnS9Opw

**Comment by D3nnis3n** [comment]
Same happens when picking up a furniture where a player sits on. #10233

**Comment by elfl0rd** [comment]
Still happens in latest master

**Comment by elfl0rd** [comment]
@D3nnis3n maybe larger priority?

**Comment by elfl0rd** [comment]
@D3nnis3n need recheck after 0.8.0.2 released, looks fixed at pr.

**Comment by elfl0rd** [comment]
fixed.
