### ISSUE TITLE
Crane needs separate interactable pieces

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#8487]
can easily do this with the specific interactable functionality, just need the mesh broken up into separate parts meant to be highlightable

**Comment by MilenkoTunjic** [comment]
Who wants to enlighten me about this one?
We are talking about the large crane, right?
they are skinned to the skeleton, so breaking them up will be a bit of work to get done right.
Anyhow, let me know.

**Comment by WeaselDog** [comment]
I am going to close this issue as it is a few years old and it is not clear what we want to happen.. If this is a problem, it will be dealt with as we do the crane remake.
