### ISSUE TITLE
Can't tell how large an object will be until you try to place it

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#8488]
hinders planning rooms and stuff (sometimes) for the larger objects like the new electric machines.

Might want to add the dimensions of objects into the tooltips.

**Comment by SeanAtr0n** [comment]
sounds like a job for ecopedia

**Comment by elfl0rd** [comment]
Need it ingame.

**Comment by SeanAtr0n** [comment]
'ecopedia' could be a book-like UI that shows up when you click tooltips for when you want as much info as possible

could even render a preview of the world object and show occupancy info

**Comment by elfl0rd** [comment]
Would be better like additional button on hotbar
