### ISSUE TITLE
7.5->7.6 Localisation degraded.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8490]
e.g.
7.5
![20180714031255_1](https://user-images.githubusercontent.com/4980243/42718687-e74efebe-8713-11e8-8913-c866e9b527b6.jpg)
Translated

7.6
![20180714031742_1](https://user-images.githubusercontent.com/4980243/42718737-89278f26-8714-11e8-818f-1ab46a57b38f.jpg)
Not

@Nanders

**Comment by Nanders** [comment]
fixed
