### ISSUE TITLE
Mortar Production Speed - NaN

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#8493]
Can't make certain recipes because the recipe takes `NaN` time to complete.

This is on Stuffed Elk staging server.

![image](https://user-images.githubusercontent.com/2173684/42719358-9f6be820-8757-11e8-92dd-b3fcc44bd446.png)

![image](https://user-images.githubusercontent.com/2173684/42719368-c23b0462-8757-11e8-9ecf-63b9e797e857.png)

![image](https://user-images.githubusercontent.com/2173684/42719361-ab86cbde-8757-11e8-9e58-bedc5c467210.png)

**Comment by LiaungYip** [comment]
Looks related to #8483.

**Comment by pamduncan** [comment]
Linked to original report  https://github.com/StrangeLoopGames/EcoIssues/issues/8483

**Comment by BlazeGuy2** [comment]
Dup of #8483
