### ISSUE TITLE
USER ISSUE: placing starter camp before "control" tutorial section complete - broke tutorial line

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8494]
**Version:** 0.7.6.0 beta staging-d839db67

**Steps to Reproduce:**
join to new world.
open backpack, select and place starter camp without jumping or moving.

**Expected behavior:**
Tutorial section "starter camp" opens and checked.

**Actual behavior:**
Tutorial section "starter camp" now broken, you cannot drag, select and place requied item.
![20180714044053_1](https://user-images.githubusercontent.com/4980243/42719558-284346ee-8720-11e8-8ec6-40085ddd4e58.jpg)

p.s.
concerns to "restart tutorial" too.

**Comment by Rambo99** [comment]
At me too this task was carried out with errors. The truth is my mistake was that the task did not finish after it was required to make "hewn log".

**Comment by craig-jong** [comment]
Fixed in above PR.
