### ISSUE TITLE
Server crash if you name world like ";1"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8495]
**Version:** 0.7.6.0 beta staging-d839db67
If you try to make new world with ; as first name sumbol - server crash :p 
like ;1
![default](https://user-images.githubusercontent.com/4980243/42719615-4f46fba4-8721-11e8-883d-163f1faa020f.png)
[ServerCrash AggregateException 07144428.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2194570/ServerCrash.AggregateException.07144428.zip)

**Comment by johnkslg** [comment]
Dupe @BlazeGuy2
