### ISSUE TITLE
Weird highlighting on distribution station

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8498]
![animx](https://user-images.githubusercontent.com/3536496/42720370-a801b122-86da-11e8-9b89-d610abe59f77.gif)

**Comment by elfl0rd** [comment]
Confirm... It's terribe :(

**Comment by johnkslg** [comment]
it doesnt highlight when you aim at the wood floor

**Comment by keegan-o** [comment]
Ok, I think I finally fixed this well enough to call the object done. Also touched up the textures/model of the distribution station. In Master, as of 7/27.
