### ISSUE TITLE
USER ISSUE: Carrying icon does not appear in toolbar menu

### ISSUE THREAD

**Issue by Gamestrust-TS** [StrangeLoopGames/EcoIssues#8500]
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
![2018-07-14 1](https://user-images.githubusercontent.com/41223737/42720912-e9b743f6-8730-11e8-8f15-3455b2dffb85.png)

**Expected behavior:**

**Actual behavior:**

the carrying icon does not appear in the toolbar menu so it is impossible to take an object from a stockpile. It works only by clicking on it, but a random object is taken.

**Comment by elfl0rd** [comment]
Do not click, try drag :P

**Comment by Gamestrust-TS** [comment]
as you can see in the picture he also tried to drag but does not appear where to place it, only if you click casually takes a stone or wood type object and appears.

**Comment by johnkslg** [comment]
To confirm, you tried dragging but it didnt appear?

**Comment by elfl0rd** [comment]
> To confirm, you tried dragging but it didnt appear?
Yes, periodically happens to me too.
Trash bin is not show too.
Client restart fix this issue.

**Comment by johnkslg** [comment]
Need a log file if you can get one after it happens

**Comment by elfl0rd** [comment]
ok

**Comment by elfl0rd** [comment]
Have it now...
90mb log 0_o
[output_log - копия.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2203173/output_log.-.zip)

**Comment by elfl0rd** [comment]
> Are you getting this in the latest hotfix now? Just released an hour or two ago?

No, but this is not a frequent problem... (1-2 per day)
If i get it again - I will say.

**Comment by johnkslg** [comment]
Closing for now, please reopen if you get it again, couldnt make it happen myself.

**Comment by elfl0rd** [comment]
only developers can reopen :)
but i cant recieve it after hotfix
