### ISSUE TITLE
[Ubuntu Server] Skipping GUI because you platform isn't supported =Unix!?

### ISSUE THREAD

**Issue by Prototype-Alpha** [StrangeLoopGames/EcoIssues#8501]
[EcoServer.exe run in Ubuntu 16.04.4 x64]

EcoServer.exe reported that "Skipping GUI because your platform isn't supported, platform=Unix"

Originally, before this update, GUI was run fine, shown through the use of TightVNCviewer.
However, after update, GUI doesn't start up as stated earlier.

Anyway, after initiated (without gui), server can be seen in server browser just fine*.

* However, I don't understand why Asian Server find it hard to be seen on server browser despite of low ping/latency. Half of the time it doesn't show up, most of the time, it showed up later than higher ping US or EU servers. Is the browser has its own server in western country? Regardless of the cause, this should be fixed to allow Asian as well as people from other zone can get there best experience. [Hunting with 200+ ping is no joke]

**Comment by pamduncan** [comment]
My understanding is that the ping shown on the browser is the ping from you to the server.  If you are seeing higher pings on the browser than when you ping the server directly that would be good to know

**Comment by Prototype-Alpha** [comment]
This topic point is Server GUI problem, it seem EcoServer.exe misdetected Ubuntu as Unix and stop GUI from being started.

Anyway,
>  If you are seeing higher pings on the browser than when you ping the server directly
@pamduncan 
Hmm, that's misunderstanding. They ping in server browser is equal to ping in the game. However, the point is that Asia server is not really show up (unless bookmarked) or show up late despite of lesser latency (from my pc to server).

So my hypothesis are

- Eco may have server for their browser and located somewhere in Western countries.

- Client retrieves list of server through browser's server

- Both might cause servers that located far from browser server, not appear or appear late in the list

**Comment by SeanAtr0n** [comment]
how do you get the UI working using TightVNC viewer? Maybe we can detect that trick and re-enable the UI

**Comment by SeanAtr0n** [comment]
eric fixed in 7.7
