### ISSUE TITLE
USER ISSUE: Hewn Logs At Carpentry Table Won't Craft

### ISSUE THREAD

**Issue by Killaspazz14** [StrangeLoopGames/EcoIssues#8503]
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
1. Queue Hewn Logs at Carpentry Table.
2. Add Logs to facilitate Hewn Logs Recipe.

**Expected behavior:**
It should produce Hewn Logs.

**Actual behavior:**
It displays Resources: 100%, and Time: NaN, and does not create Hewn Logs.

**Comment by pamduncan** [comment]
Linked to original report  https://github.com/StrangeLoopGames/EcoIssues/issues/8483
