### ISSUE TITLE
USER ISSUE: unable to build hewn logs at carpentry table

### ISSUE THREAD

**Issue by friskyapple** [StrangeLoopGames/EcoIssues#8505]
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
start hewn log project at carpentry table

**Expected behavior:**
began the project	

**Actual behavior:**
shows time to completion as nan and won't proceed even though all requirements are met
![image](https://user-images.githubusercontent.com/41227343/42721948-777f36ee-8786-11e8-8ee5-e4f9e3db8173.png)

**Comment by elfl0rd** [comment]
Dupe - https://github.com/StrangeLoopGames/EcoIssues/issues/8401
