### ISSUE TITLE
Assembly Line missing room requirements

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8506]
Assembly line - no power and room requirement
![default](https://user-images.githubusercontent.com/4980243/42722192-6e7ec82e-8750-11e8-9f05-98b44186a19c.png)

Robotic assembly line - no room requirement
![default](https://user-images.githubusercontent.com/4980243/42722195-7b141dd2-8750-11e8-8ef6-944d9720c825.png)

Electric Stamping press - require room lower than size
(And maybe more high tier materials than 18?)
![default](https://user-images.githubusercontent.com/4980243/42722210-af0878ea-8750-11e8-9a4b-7fe6daf1c14c.png)
![default](https://user-images.githubusercontent.com/4980243/42722203-90a36d10-8750-11e8-8255-ba4eed70b561.png)

Electric Planer - require room lower than size
(And maybe more high tier materials than 18?)
![default](https://user-images.githubusercontent.com/4980243/42722196-82cd8e8c-8750-11e8-9634-dfec09fb70ec.png)
![default](https://user-images.githubusercontent.com/4980243/42722200-8af61944-8750-11e8-99bf-7af26afd65cf.png)

Electric Lathe - require room lower than size
(And maybe more high tier materials than 18?)
![20180714102939_1](https://user-images.githubusercontent.com/4980243/42722254-7eea943a-8751-11e8-8e15-165a9aea0c20.jpg)
![20180714102933_1](https://user-images.githubusercontent.com/4980243/42722255-7f0f4ece-8751-11e8-9396-678ef9b8d249.jpg)

**Comment by craig-jong** [comment]
fixed in master

**Comment by elfl0rd** [comment]
Assembly Line w\o room requiment - planned?
Or you add mechanical power after converter out and steam engine returned to mechanics? :D
