### ISSUE TITLE
Add smog production to Steam Engine

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8507]
Bakery Oven - has pipe connector and not produce smog.
![20180714104806_1](https://user-images.githubusercontent.com/4980243/42722371-999b306c-8753-11e8-9c5e-10ed617dd34d.jpg)
![20180714104757_1](https://user-images.githubusercontent.com/4980243/42722373-99b99124-8753-11e8-9338-267c8826d9f1.jpg)

Cast Iron Stove - has pipe connector and not produce smog.
![20180714105030_1](https://user-images.githubusercontent.com/4980243/42722430-86536460-8754-11e8-92ca-fc252b0747c3.jpg)
![20180714105025_1](https://user-images.githubusercontent.com/4980243/42722431-86728944-8754-11e8-81a6-9e991dcaa5bf.jpg)

**Comment by elfl0rd** [comment]
Steam Engine - has pipe connector and not produce smog.
![20180725090927_1](https://user-images.githubusercontent.com/4980243/43182555-7f33c276-8fea-11e8-9a82-206ef242fdb0.jpg)
![20180725090853_1](https://user-images.githubusercontent.com/4980243/43182556-7f52fa2e-8fea-11e8-8e1c-eb4680f5e5f9.jpg)

**Comment by elfl0rd** [comment]
@D3nnis3n i think you interested about :)

**Comment by WeaselDog** [comment]
Bakery Oven and Cast Iron stove have it now but we still need to add for Steam Engine

**Comment by elfl0rd** [comment]
In my opinion, steam engine should have > than combustion generator.
But in current state, combustion generator pollute more than blast furnace :D

**Comment by keegan-o** [comment]
other issue opened for steam engine ports
