### ISSUE TITLE
USER ISSUE: Housing skillpoints are dropped to zero after the 7.6.0 update

### ISSUE THREAD

**Issue by DrCarsonBeckett** [StrangeLoopGames/EcoIssues#8509]
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
Build a house on 7.5.1 and update to 7.6.0	

**Expected behavior:**
Points should stay.

**Actual behavior:**
points dropped to zero. This is damn annoying, when are you going to fix it?!

**Comment by Voosle** [comment]
… and so all Stores and Tables are disabled. Very annoying.

**Comment by DrCarsonBeckett** [comment]
Yes. So annoying. -.-

**Comment by DrCarsonBeckett** [comment]
Wow, after a Server restart its again at zero.
I dont even want to play that game anymore. That are basic features which should work.

**Comment by Voosle** [comment]
I cannot confirm rooms are broken after server restart. After nightly restart of our server, all 'repaired' rooms are still working.

**Comment by johnkslg** [comment]
In and waiting for hotfix!
