### ISSUE TITLE
Coal input consumption for Steel is not reduced by Alloy Smelting Efficiency skill

### ISSUE THREAD

**Issue by Divinicus1st** [StrangeLoopGames/EcoIssues#8510]
I don't have much more to add, it's really all in the title: Coal input consumption for Steel is not reduced by Alloy Smelting Efficiency skill.

I don't know if it is intended or not, I guess/hope not, but files define a fixed (2) value for coal consumption, instead of a variable one.
With the fixed value, you consume more coal than iron to make steel which is very weird.

**Comment by craig-jong** [comment]
fixed in above pr, will be in next non-hotfix release.
