### ISSUE TITLE
Creating world marker on click broken in 7.6

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8512]
(it works before - in 7.5)
If you click on object, or coordinates - in 7.5 scroll minimap and create marker.
Now - only scroll.
It's planned?

**Comment by MarjieAVolk** [comment]
Yes, that was an intended change.

**Comment by MarjieAVolk** [comment]
Do you dislike the change?

**Comment by elfl0rd** [comment]
hm... 50\50
No markers is more clean, but...
marker show 3d position, map scroll - only 2d.
Need a way to fast marker on it (not drop on map, he drop to ground), shift(or ctrl) click maybe?

**Comment by elfl0rd** [comment]
yep, in big sity with stores on multiple levels...
awwww...

**Comment by elfl0rd** [comment]
Hm... what about...
LMB - scroll to position
RMB - drop marker (old style)?
Sounds good for me...

**Comment by elfl0rd** [comment]
I continued to miss fast and accurate label creation :(

**Comment by beastyn** [comment]
1. When Im clicking on the coordinate with CTRL map is scrolling but marker won't appear.
2. In a hint we should replace text "control" with "Ctrl"
![bandicam 2019-12-11 11-20-52-297](https://user-images.githubusercontent.com/27898520/70596956-ed9c9700-1c08-11ea-8b01-a488f77c8ef0.jpg)

**Comment by elfl0rd** [comment]
"Ctrl+click" maybe?

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/70881512-da5d4300-1fdd-11ea-86f0-e14f5dcf1735.png)

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/71953328-f1650e80-31f2-11ea-89a5-18c68fb63b33.png)

**Comment by elfl0rd** [comment]
It's ok, but two string use at same time.
Control+Click and Ctrl+Click
![изображение](https://user-images.githubusercontent.com/4980243/77481885-acd23200-6e35-11ea-8dd0-906b708d0916.png)
I think we need select one.
(Also this can be in 0.9, not 0.9.1?)
