### ISSUE TITLE
[7.6.0] Workbench > Hewn Logs Effiency broken

### ISSUE THREAD

**Issue by frizzero** [StrangeLoopGames/EcoIssues#8513]
after skilling hewn log efficiency and speed the benefits do not reflect in creating hewn logs at workbench
(besides hewn log crafting at carpentry table is broken completely)

**Comment by funnybunnyofdoom** [comment]
I am also experiencing this issue.

**Comment by gregoryl09** [comment]
Same

**Comment by Butterflycat0** [comment]
same!

**Comment by johnkslg** [comment]
Dupe #8483
