### ISSUE TITLE
USER ISSUE: Water bug

### ISSUE THREAD

**Issue by porfirius1983** [StrangeLoopGames/EcoIssues#8514]
**Version:** 0.7.6.0 beta

https://prnt.sc/k6drpk

нет физики?

**Comment by johnkslg** [comment]
Whats the issue?

**Comment by porfirius1983** [comment]
квадратная вода, не растекается.

**Comment by BlazeGuy2** [comment]
Issue is that the square of water isn't spreading properly.

**Comment by D3nnis3n** [comment]
Duplicate of #1424
