### ISSUE TITLE
Campfire Creations Speed [Not Working]

### ISSUE THREAD

**Issue by starcreep48** [StrangeLoopGames/EcoIssues#8515]
Hello,

When I craft charred meat from animal carcasses, it does not apply the speed reduction to the crafting time. I have maxed out skill points in both campfire skill trees. We have refeshed the server many times. This issue arose after the new update to 0.7.6.0

Server current version: 0.7.6.0

![image](https://user-images.githubusercontent.com/41234154/42724500-c8036904-8773-11e8-953b-bff44964416b.png)

**Comment by elfl0rd** [comment]
yes, bison is basic reciepe.
You can not faster it.
Works as intended.
