### ISSUE TITLE
User Issue: Excavator View And Electric Lathe

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#8517]
You always look to the left when you press 1. A little annoying 

And on the Electric Lather has no Recipe on this Crafttable
And on the Electric Stamping Press show no Storage

**Comment by BlazeGuy2** [comment]
Could you post a couple screenshots to show the you always look left when you press 1?

**Comment by Sekor2600** [comment]
That can I do on friday then I have pc again. But I look always left when I have digging mode on in excavator and skid and then press 1 in order to turn off digging mode.
