### ISSUE TITLE
USER ISSUE: Chat window scrolls to center of log

### ISSUE THREAD

**Issue by funnybunnyofdoom** [StrangeLoopGames/EcoIssues#8518]
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
While gathering wood and cutting debris, the chat scrolls to the center of it's log

**Expected behavior:**
remained at the latest messages

**Actual behavior:**
scrolled up to a later conversation

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8248
