### ISSUE TITLE
USER ISSUE: time NaN when crafting hewn logs

### ISSUE THREAD

**Issue by funnybunnyofdoom** [StrangeLoopGames/EcoIssues#8519]
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
Craft any number of hewn logs on the carpentry table	

**Expected behavior:**
Made the logs, and displayed the time

**Actual behavior:**
displayed "NaN" and didn't craft the hewn logs.

**Comment by BlazeGuy2** [comment]
Dup of #8483
