### ISSUE TITLE
after every restart you must setup the storage. Can you fix this

### ISSUE THREAD

**Issue by Lars225** [StrangeLoopGames/EcoIssues#8521]

**Comment by Voosle** [comment]
At the shops the order of all linked storages are mixed up. Or more precise: The configured order I did before migration from 7.5.1. to 7.6.0 are lost. They appear in the order the chests and stockpiles are placed in the past, I assume.

**Comment by MarjieAVolk** [comment]
I haven't checked 7.5.1 > 7.6 migration for this bug yet, but as per the originally filed issue, I don't see any information being lost in storage when I save and reload.  @Lars225 what exactly do you have to set up every time?

**Comment by MarjieAVolk** [comment]
Okay, I do see that whether or not the inventories are expanded is not always saved.  That shouldn't affect the behavior of the table, just how it is displayed.  Is that what you're referring to?

**Comment by MarjieAVolk** [comment]
Okay, I do see settings getting lost on migration, as @Voosle said.  That is odd, as I have migration code written here, not sure what's wrong with it.  I think it might be too late to worry about that though.

**Comment by MarjieAVolk** [comment]
Okay, well the migration issue will be fixed in the next hotfix.  You'll need to re-migrate your saves though if you want to get it.

Can't repro the original issue though.  Going to close for now, until I hear back from @Lars225
