### ISSUE TITLE
USER ISSUE: Will not Craft Pitch using Sand on Masonry Table

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#8522]
**Version:** 0.7.6.0 beta

![snap2290](https://user-images.githubusercontent.com/29383891/42725931-1e2f7fd8-8784-11e8-8d16-06739cc17938.png)

this is a **game killer** for a Mason, i can craft Stone to Sand but cannot craft Pitch from Sand, the time per unit is showing 0 seconds which is then throwing up the Time Glitch at the bottom of the crafting window
Time: NaN Resources: 100%
have tried this on multiple Masonry Tables, still will not craft Masonry Pitch

**Comment by pamduncan** [comment]
Linked this to the orignal bug report about tables with these issues per JohnK
https://github.com/StrangeLoopGames/EcoIssues/issues/8483

**Comment by BlazeGuy2** [comment]
Dup of #8483
