### ISSUE TITLE
Pitch crafting connected with masonry production speed

### ISSUE THREAD

**Issue by HeimerAlz** [StrangeLoopGames/EcoIssues#8524]
Hey, i found a connection with the pitch crafting and the skill masonry production speed.
i did test it with lvl 5 and 4 both dont work but unskilled it works.

the same issue can be seen at the carpentry table with hewns logs but i didn't test the connection with its skill yet.

**Comment by pamduncan** [comment]
Think this is connected with the issue reported here and is also occurring with multiply tables and several recipes  https://github.com/StrangeLoopGames/EcoIssues/issues/8483

**Comment by HeimerAlz** [comment]
UPDATE 
masonry production speed level 4 should work, just made a mistake.

i referred this problem with the stone road. crafting timer is ticking down if u craft multible types but u get no product, but the precentage are counting.

but still i see lvl 5 as the problem
