### ISSUE TITLE
[7.6.0] Interaction Hint is shown way before object is accessible

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#8525]
![interaction1](https://user-images.githubusercontent.com/38510829/42727028-da6bb72e-879e-11e8-928b-41ae030ea2ed.PNG)
![interaction2](https://user-images.githubusercontent.com/38510829/42727031-dffbd93a-879e-11e8-9ca1-287d886d1a1a.PNG)

**Comment by MarjieAVolk** [comment]
Fixed in next major release
