### ISSUE TITLE
USER ISSUE: Paper Project

### ISSUE THREAD

**Issue by zenoftheyatta** [StrangeLoopGames/EcoIssues#8526]
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
Attempt to make paper of any QTY.

**Expected behavior:**
To make paper of requested amount.

**Actual behavior:**
Time says NaN for any amount of paper trying to be made. Time limit beside desired amount is 0s.

**Comment by johnkslg** [comment]
Dupe #8483
