### ISSUE TITLE
[7.6.0 bug] cannot make hewn logs - carpentry table

### ISSUE THREAD

**Issue by Butterflycat0** [StrangeLoopGames/EcoIssues#8527]
![20180715052719_1](https://user-images.githubusercontent.com/41241968/42728197-de2f6026-87ef-11e8-9dbe-3c286169817a.jpg)
![20180715052731_1](https://user-images.githubusercontent.com/41241968/42728198-e21d1cb4-87ef-11e8-805e-07d4d7434c8f.jpg)
![20180715052948_1](https://user-images.githubusercontent.com/41241968/42728208-26ca01d8-87f0-11e8-852e-c8986694ee9f.jpg)

**Comment by Butterflycat0** [comment]
#8401

**Comment by pamduncan** [comment]
You can make the hewn logs at the workbench until they get a fix for this in

**Comment by BlazeGuy2** [comment]
Being dealt with in #8483
