### ISSUE TITLE
[7.6] Crash in UpdateSkinPoseBuffer 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8528]
Reported by EcoBuilder13, shortly after character creation.  He's on Discord if you need to follow up. 
Dump: https://drive.google.com/open?id=14MaEZJqZ7WdAfWxmJYQ8ezpufblPx9iq
[error (1).log](https://github.com/StrangeLoopGames/EcoIssues/files/2195331/error.1.log)

>	CContext::TID3D11DeviceContext_Map_<4>()	Unknown
 	StreamOutSkinPoseBuffer::Update()	Unknown
 	GfxDeviceD3D11Base::UpdateSkinPoseBuffer()	Unknown
 	GfxDeviceWorker::RunCommand()	Unknown
 	GfxDeviceWorker::RunExt()	Unknown
 	GfxDeviceWorker::RunGfxDeviceWorker()	Unknown
 	Thread::RunThreadWrapper()	Unknown

**Comment by SlayksWood** [comment]
Seems fixed.
