### ISSUE TITLE
When you right click a vehicle it should take the items first from the storage

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8529]
Instead of fuel

**Comment by MarjieAVolk** [comment]
Hm, we don't have any kind of prioritization system right now.  Presumably you would want to put items into the fuel inventory first (if they fit), which is the opposite prioritization, so it seems like we would need different priorities per function.

**Comment by GokouZWAR** [comment]
Would be better if there was a “fuel  point” on the vehicle to allow people to put fuel into the vehicle, pull from the vehicle as well, that’s separate from the storage point.

**Comment by MarjieAVolk** [comment]
That's a good idea

**Comment by GokouZWAR** [comment]
Thanks. Good to hear something I’ve come up with is useful around here lol.

**Comment by springphul** [comment]
Actually it works that way in the game. I even arrange the materials, i want to use in the order, so I just click on the car and get it in the set order. v0.7.6. I don't have this problem.

**Comment by SlayksWood** [comment]
Seems fixed
![image](https://user-images.githubusercontent.com/45708377/74314769-17984400-4d87-11ea-81e1-99bcf823e127.png)
![image](https://user-images.githubusercontent.com/45708377/74314783-20891580-4d87-11ea-9278-2b0c2e7a0de7.png)
