### ISSUE TITLE
Missing Items in the Mint and Store

### ISSUE THREAD

**Issue by ARFFRichT** [StrangeLoopGames/EcoIssues#8531]
Started a new server, downloaded it from Strange Loop. Added the Mint and wanted to choose Gold Bar/Ingot as the currency and noticed that it was not one of the choices.

Started a store and tried to add Copper Bar/Ingot again this choice is not there. Looking over the store there are only about 1/3 of the items listed as there are in game.

Re-downloaded the server and tested again, same issue. Verified my game integrity in steam, grabbed the server from my steam game and started a server using steam. Same issue.

**Comment by funnybunnyofdoom** [comment]
Have you discovered the specialization for them?

**Comment by pamduncan** [comment]
Many items do not show up in store or laws or other lists until they have been discovered and or crafted the first time.  Such as the Mint cannot be included in a law unless someone has made a Mint in game.  Many store items are not available in the store unless they have been learned and made at least 1 time in the world by someone.  That would be the case with the Copper bar, if no one has yet made any they would not be in the list in the store to buy or sell.  That would probably be where most of your store items are - not in game yet so not available on lists.

**Comment by johnkslg** [comment]
By design, it only shows discovered things.
