### ISSUE TITLE
Calorie Efficiency is bugged in 7.6

### ISSUE THREAD

**Issue by FyreAus** [StrangeLoopGames/EcoIssues#8532]
Calorie Efficiency Tooltips say each level reduces calories cost by 5%

However, testing with standing still these are the actual values

Level | Value should be | Value in-game
------|-----------------|-----------
0| 0.83 | 0.83
1| 0.79| 0.83
2| 0.75|0.75
3|0.71| 0.67
4|0.67| 0.67
5|0.62| 0.67

This means the first level does nothing then you get 10% at level 2 and 20% at level 3. levels 4 and 5 do nothing.

**Comment by WeaselDog** [comment]
Thanks for the reporting this. Self-improvement no longer gives passive calorie reductions so this is no longer an issue.
