### ISSUE TITLE
ECO main UI "continue" option not always working - 

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8533]
Log in to Eco
click continue to return to last played game (if singleplayer) and it will give you the load list instead of the game world.  If showing a server it may just fail and put player back to main menu.

Work around is to use "load" and pick the world again or use "join" and pick server from favorites or "Browse"

In some cases this is happening because it seems the player maybe in a bad location (stuck or on broken blocks) and the server will not load them in which case the workaround will not work and you may have to work on the player profile.

If there is no problem with the player location or a player profile issue "load" or "join" through browser will work.  

deleting appdata does not seem to fix this issue

**Comment by pamduncan** [comment]
This maybe related to steam/game not seeing itself shut down.  Not giving a message like before that the game is still running now it just does this but a reboot will solve it

**Comment by johnkslg** [comment]
Dupe @BlazeGuy2

**Comment by BlazeGuy2** [comment]
Dup of #8424
