### ISSUE TITLE
[7.6.0] Owner of store is not equal to owner of property

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8535]
Today I found my stores owned by another Player. It's the first one on the propery's whitelist.

A store should be owned by the owner of the deed from the property the store is placed on. Am I right?
As you can see, it is not.

Another effect: The failing displayed owner cannot change prices but can select the amount to buy, but no Trade button is there... (see 3rd screenshot below)

Maybe that switch occured while migrate the world from 7.5.1 to 7.6.0 the day before.
The Server restarted this night and i'm not sure if this owner switch took place yesterday.

I think it's independent from the migration. I can reproduce this effect: 
- (Delete and) Create a new deed for a room as "Voosle" (the deed and room is owned by Voosle as expected)
- The authority mode is "Whitelist" with an empty list
- Place a Mint in this room
-> The Mint is owned by Voosle. (with the dot!) (see screenshots below)
I have no idea why espacialy my 2nd account is selected in this Situation.

![image](https://user-images.githubusercontent.com/22961978/42732870-4968b156-8829-11e8-9547-9dfcffbb0309.png)
![image](https://user-images.githubusercontent.com/22961978/42732871-4d3b8fc4-8829-11e8-9452-ba838be8c630.png)

![image](https://user-images.githubusercontent.com/22961978/42733452-e92b4214-8831-11e8-802a-da35bf867417.png)

Same Problem with a new created deed an fresh placed mint:

![image](https://user-images.githubusercontent.com/22961978/42735671-c333822a-8858-11e8-8c3d-7ee60e645c7d.png)
![image](https://user-images.githubusercontent.com/22961978/42735675-c713c2ec-8858-11e8-8278-dbd1cc94487a.png)

**Comment by MarjieAVolk** [comment]
So what's the story with the Voosle with a dot?  Are they both your own accounts?  Could you show me /whoami output for both of those accounts?

**Comment by Voosle** [comment]
Voosle. is just my second Steam account. I you it for tests and sometimes to get a third person perspective of my buildings and configurations.

Voosle
![image](https://user-images.githubusercontent.com/22961978/42777683-1fdc609a-893b-11e8-825f-1d7b095f669a.png)

Voosle.
![image](https://user-images.githubusercontent.com/22961978/42777700-25c19534-893b-11e8-9f94-ddc46cb115bb.png)

**Comment by MarjieAVolk** [comment]
Okay, they are not connected at all.  Weird.  Could you share your save file with me?

**Comment by Voosle** [comment]
So, I'm happy that it is mysterious to you, too. ;-)

feel free to dive into it (sorry, 2GB):
https://1drv.ms/f/s!AovZo2hpobmim9dRb76gyxfsNBHmCg

**Comment by Voosle** [comment]
Today we noticed a new issue of this kind: 
When another player "Zerkon" opens a store and the header says "Owned by Willpa." (with a dot!) But his account has the name without a dot.
For the other player "Zerkon" no Trade button appears.
(same save game)

![image](https://user-images.githubusercontent.com/22961978/42813851-99cb585c-89c2-11e8-94a5-417cd260a86e.png)

**Comment by Voosle** [comment]
hmmmm … maybe it's very simple: In the title of store there is a full stop at the end of the sentence?

**Comment by MarjieAVolk** [comment]
Hahahaha, I think that might be the case.  So is there no issue if that's the case?

**Comment by Voosle** [comment]
Without words...

(But why there is no Trade button for the 'not-owner'-player if he's on the deed's whitelist? Is that intended?)

![image](https://user-images.githubusercontent.com/22961978/42837091-56675d96-89fd-11e8-8e51-8e70d1675109.png)

**Comment by MarjieAVolk** [comment]
Yeah that isn't quite right.  What should happen is the person who is whitelisted on the property should see the same thing as the property owner.  I will look at that.  Thanks!
