### ISSUE TITLE
[7.6.0] No seed is picked harvesting huckleberries

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#8536]
I harvested more then 50 huckleberries and not one seed. Has this changed?

**Comment by pamduncan** [comment]
My understanding i that now seeds are made by farmers from the produce itself

**Comment by Nicolausi113** [comment]
Huckleberry seed is needed to research farming skill. If this is intention, so we have a deadlock.

**Comment by craig-jong** [comment]
They should still come from the plants. I'll double check to make sure.

**Comment by craig-jong** [comment]
Well eco sim says they SHOULD drop, but they aren't.

Might be a bigger issue, but it does block progress.

**Comment by craig-jong** [comment]
Should be fixed in the next hotfix (hopefully today)

**Comment by Limelill** [comment]
About 100 huckleberries gave me three seeds in the current build. Might be intentional?
