### ISSUE TITLE
USER ISSUE: Blast Furnace

### ISSUE THREAD

**Issue by EiKiDa** [StrangeLoopGames/EcoIssues#8538]
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
To smelt iron or other ores, you'll get now on the blast furnace TAILINGS, too! 

**Expected behavior:**
No tailings, just air pollution.

**Actual behavior:**
You get tailings AND air pollution!!

**Comment by pamduncan** [comment]
That's the new expected behavior, its not a bug.  Blast Furnace now produces tailings as a by-product of the Blast Furnace process.  Refining will always have a byproduct of left over substances and impurities such as tailing or slag or something-- Eco furnaces have tailings

**Comment by BlazeGuy2** [comment]
Not a bug, closing.
