### ISSUE TITLE
[7.6] Tutorial: Food/Nutrition stuff should be handled before Crafting/Housing

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#8539]
It easily can happen that you are hungry just if the first workbench is crafted. For newbies it can be a deadlock, because he/she don't know how to proceed.
Unlocking nutrition and handling with food should be treated early.

**Comment by Nicolausi113** [comment]
If food-tutorial is skipped, the hole nutrition function and the HUD is disabled – no skill points.
Maybe the same for housing-tutorial, I have not tested yet.

**Comment by johnkslg** [comment]
Its treated as soon as you get hungry or pickup food
