### ISSUE TITLE
USER ISSUE: Food HUD not showing

### ISSUE THREAD

**Issue by CraftYourWay** [StrangeLoopGames/EcoIssues#8540]
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
When tutorials show up in the left top, the food bar dissapears,

Fix: When removing the tutorials the food bar apears

**Expected behavior:**
both apearing

**Actual behavior:**
the food bar dissapears and the tutorials show up

**Comment by Nicolausi113** [comment]
I’m a little confused, have you converted an older version?
Anyway, the food bar is locked and unlocks after executing the food-tutorial (after placing first workbench). Maybe I could help, see also #8539

**Comment by pamduncan** [comment]
When the Food section of the tutorial is completed the sp/food HUD will show up.  If you do not want to do the tutorial you can skip that part or all of the tutorial and the sp/food HUD will then show up.  Some people have reported they had to eat once for it to show up.  If this was an existing world you may have to eat once for it to show up the first time or toggle ALT-Z

**Comment by johnkslg** [comment]
Fix is in for this: Forage Tutorial if skipped will now open food tutorial.
