### ISSUE TITLE
[7.6.0] Server dump: Could not find matching method GetWorkorderTooltip on type TableTracker taking 1 parameters

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8541]
Just found this dump file on our server. I don't know what a player did to Force this…
Maybe same as #8463 ?

--BEGIN DUMP--
Dump Time
07/14/2018 21:17:47

Exception
Exception: Exception
Message:Could not find matching method GetWorkorderTooltip on type TableTracker taking 1 parameters.
Source:Eco.Shared

System.Exception: Could not find matching method GetWorkorderTooltip on type TableTracker taking 1 parameters.
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname)
   at Eco.Plugins.Networking.Client.ViewRPC(INetClient client, Int32 id, String methodname, BSONObject bson)

--END DUMP--

**Comment by johnkslg** [comment]
Fixed awaiting hotfix
