### ISSUE TITLE
Invisible Logs

### ISSUE THREAD

**Issue by TheNameless107** [StrangeLoopGames/EcoIssues#8544]
**Version:** 0.7.6.0 beta

**Steps to Reproduce**:

1. Cut down a tree
2. Cut logs into pieces
3. Grab what you can
4. Walk to your house (away from the logs)
5. Come back to logs
6. Get confused because no logs are visible. but you walk over them and move up and down like there is something there. Then Hover over it with a curser and the curser gives the "Chop" prompt.
7. Disconnect and Reconnect.
8. Grab the now visible logs.
9. Repeat 4-8

**Expected behavior**:
I should still see Logs when I come back to where I cut down the tree.

**Actual behavior**:
Seeing the ground

**Comment by SeanAtr0n** [comment]
Tried to reproduce but haven't been able to so far, did the logs fall far from where the tree was chopped down? Can you reproduce this behavior regularly?

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/6223
