### ISSUE TITLE
[7.6.0] Rounding of costs of materials is off

### ISSUE THREAD

**Issue by Limelill** [StrangeLoopGames/EcoIssues#8546]
Butchering elk at the cost of 0.2 having two elk carcasses only allows me to butcher 9 times instead of 10. See attached image. 
![image](https://user-images.githubusercontent.com/27635053/42738447-1b3e80a2-8884-11e8-8a37-89f3cb2c18ad.png)

**Comment by craig-jong** [comment]
Fixed in master
