### ISSUE TITLE
The new machines/tables

### ISSUE THREAD

**Issue by Myrhaug** [StrangeLoopGames/EcoIssues#8547]
Electric Planer and Electric Stamping Press does not have storage link
Electric Lathe does not have any recieps, but it got storage linking

**Comment by craig-jong** [comment]
Fixed in above PR.

**Comment by elfl0rd** [comment]
No reciepes, latest master.
![default](https://user-images.githubusercontent.com/4980243/46381815-856f2e80-c6b0-11e8-9625-52f7987f8520.png)

**Comment by craig-jong** [comment]
At least the storage linking is in there.

**Comment by elfl0rd** [comment]
yep, only reciepes needed.

**Comment by elfl0rd** [comment]
Just move "Steel Axle" from Electric Planer to Electric Lathe, to compare as Lathe and Shaper.

**Comment by Rambo99** [comment]
> Just move "Steel Axle" from Electric Planer to Electric Lathe, to compare as Lathe and Shaper.

Steel Axle ??? What it is ?!?! This is not in the game. Screenshots please.

**Comment by elfl0rd** [comment]
@Rambo99 

> Steel Axle ??? What it is ?!?! This is not in the game. Screenshots please.

Not in the game? Lol. in 0.7.7.2

![default](https://user-images.githubusercontent.com/4980243/47253232-5818d380-d459-11e8-861e-1e39ef0a843d.png)
![default](https://user-images.githubusercontent.com/4980243/47253261-7b438300-d459-11e8-9b4b-8415a471e110.png)
![default](https://user-images.githubusercontent.com/4980243/47253269-84345480-d459-11e8-902e-574e033a3088.png)

**Comment by elfl0rd** [comment]
@craig-jong can you move "Steel Axle" from Electric Planer to Electric Lathe and close this? lol.
Or maybe you have another plan?

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/52335684-10bc5000-2a14-11e9-91be-6d8330e62082.png)
