### ISSUE TITLE
Update has Screwed the game

### ISSUE THREAD

**Issue by emi285** [StrangeLoopGames/EcoIssues#8553]
I am no longer getting skill points for crafting, I can no longer make pitch from sand (stays at 0 seconds), I can no longer make pitch from fibers in the campfire (stays at 0 seconds), I can no longer shuck clams or urchins (stays at 0 seconds). I really don't want to have to restart again.

**Comment by johnkslg** [comment]
will be hotfixing today if all goes well

**Comment by craig-jong** [comment]
fixed in next hotfix

**Comment by emi285** [comment]
Awesome!

**Comment by emi285** [comment]
Awesome! Thank you for responding quickly! 
    On Monday, July 16, 2018, 3:08:54 PM EDT, craig-jong <notifications@github.com> wrote:  
 
 
fixed in next hotfix
