### ISSUE TITLE
[7.6.0] Lost ownership if placing device on public unclaimed ground

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#8554]
This has changed since last versions and I puzzling for the sense. But removing the chest I’m allowed. Is this really intended?
![unowned](https://user-images.githubusercontent.com/38510829/42772029-68b7d64e-8929-11e8-88d1-ee310b8ed198.PNG)

**Comment by Nicolausi113** [comment]
I see - its not owned

**Comment by MarjieAVolk** [comment]
This sounds like intended behavior to me.  What did it used to do?

If a chest is on unowned land it is unowned, so anyone can pick it up.
