### ISSUE TITLE
USER ISSUE: Time: NaN Resource 100%

### ISSUE THREAD

**Issue by Glorfinnin** [StrangeLoopGames/EcoIssues#8555]
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
Fully level efficiency and speed in many crafting trees.

**Expected behavior:**
It should increase the speed of the crafted items.

**Actual behavior:**
Instead, it prevents the items from being crafted because they say 0 seconds to craft

**Comment by BlazeGuy2** [comment]
What items are breaking?  Potential dup of #8483

**Comment by craig-jong** [comment]
Fixed in next hotfix
