### ISSUE TITLE
USER ISSUE: Can't craft hewn log on carpenter table

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#8559]
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
1. put carpenter table on ground ( room tier 1+ )
2. enter the table ( use "E" key )
3. Add job "craft hewn log" 
4. add logs on carpenter table
5. profit - hewn log not crafted 

**Expected behavior:**
Game version 0.7.6.0

**Actual behavior:**

**Comment by Rambo99** [comment]
The table of the carpenter is in the house on the ground belonging to the player. The bug can be traced as when adding logs after adding a work assignment for the production of the "heawen log", and simultaneously with the addition of the task (logs in the player's inventory or in the stock (stockpile)).

**Comment by BlazeGuy2** [comment]
Dup of #8483; Fix will ship with next hotfix build.

**Comment by Rambo99** [comment]
OKey
