### ISSUE TITLE
USER ISSUE: Canot close ESC menu ingame, even after disconnect and reconnect

### ISSUE THREAD

**Issue by TheNameless107** [StrangeLoopGames/EcoIssues#8561]
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
1. Hit Esc
2. Hit Esc again
3. Menu does not dissapear
4. Disconecting and reconnecting
5. Menu still appears 

**Expected behavior:**
Menu should close

**Actual behavior:**
Menu remains open, can use keys buit not click in game.

**Comment by seccombew** [comment]
Possible dupe

**Comment by MarjieAVolk** [comment]
Were you pressing the escape button rapidly?

**Comment by TheNameless107** [comment]
No, just the once as normal

**Comment by MarjieAVolk** [comment]
Does this happen consistently?  Or only once in a while?  The next time it happens, could you attach your output_log.txt?  On an English Windows computer, it will be at 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by TheNameless107** [comment]
It has only happened once to me, yes i will :)

**Comment by MarjieAVolk** [comment]
Reducing priority for now, since I'm guessing this is not a super common issue, and it might already be fixed in the next release by some related fixes.
