### ISSUE TITLE
Refactor inventory to use immutable ItemStacks

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#8562]
proposed changes:
change ItemStack to be a struct.
change base inventories to be lists of Slots.
Slots will contain an internal ItemStack member.

change changeset application to replace slot itemstack member on apply
change most inventory methods to return itemstack enumerables

**Comment by johnkslg** [comment]
Forwarding https://github.com/StrangeLoopGames/EcoIssues/issues/8542 here
