### ISSUE TITLE
[7.6.0] Form Selector can go beyond screen limits depending on Interface Scale 

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#8563]
Hello.

With the new hotbar Carry Item location, the Form Selector can go beyond the screen size depending on how many forms are available, and the Interface Scale:

![issue](https://user-images.githubusercontent.com/26847645/42788586-cb24f96c-8936-11e8-906a-04166ec121dc.jpg)

As a side note, a [modded] item with 18 forms will only show about 10-11 forms with 75% scale.

Thanks!

**Comment by Kirthos** [comment]
> As a side note, a [modded] item with 18 forms will only show about 10-11 forms with 75% scale.
Here is the example of the mod he speak about
![Example](https://user-images.githubusercontent.com/5023261/42788663-18c92fba-8961-11e8-9102-2f3bac9d1149.png)
I don't really know if it's possible to have a workaround
I found it cool to have the possibility to just change the color by using the form selector with shift key and scroll

**Comment by redwyre** [comment]
Not an issue with the new form selector
