### ISSUE TITLE
AuthComponent.OwnerUser is slow to query now

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8564]
In profiling this was appearing.  It's been changed into a more complex calculation with the new auth changes, but many algorithms are relying on it being a fast query.  Needs caching or storing some other way.

**Comment by MarjieAVolk** [comment]
OwnerUser is just a normal PlayerHandle, so closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8565
