### ISSUE TITLE
Carpentry Table, Hewn logs, time: NaN Resources: 100%

### ISSUE THREAD

**Issue by Shalloa** [StrangeLoopGames/EcoIssues#8566]
Only when crafting Hewn logs inside the Carpentry i receive this error.
anything else inside the carpentry works and crafts.
The Storage is linked, the logs are there but its not doing anything else.

crafting error
![20180717163647_1](https://user-images.githubusercontent.com/17688112/42824432-204c7d8a-89e0-11e8-9762-b4cfd94a4143.jpg)

linked storage
![20180717164107_1](https://user-images.githubusercontent.com/17688112/42824506-430d84b8-89e0-11e8-8ca8-19cf2046cb86.jpg)

i have seen a few other players having the same issue on other servers.
A friend joined my server and has the same problem.

**Comment by BlazeGuy2** [comment]
Dup of #8483.   Will be released with the next hotfix.
