### ISSUE TITLE
Stuck in startercamp between stockpile and tent

### ISSUE THREAD

**Issue by NathanaelMangold** [StrangeLoopGames/EcoIssues#8567]
You can get pretty easily stuck in between the startercamp and the stockpile if it is filled. Only way to get out is with "/unstuck".
Not that important but still I think this should not happen.

![20180717172342_1](https://user-images.githubusercontent.com/41338825/42827822-921483e8-89e7-11e8-9c10-ac2559bdaeff.jpg)

**Comment by SeanAtr0n** [comment]
Another spot you can get stuck while placing campsite: These can both be fixed by using box colliders so reassigning
![image](https://user-images.githubusercontent.com/774628/43029488-84724bf2-8c3b-11e8-9065-e168345271bd.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/43030436-d83c611a-8c44-11e8-8f99-a5f392529ef6.png)
Fixed in master and merged to staging.
