### ISSUE TITLE
Double tabing "Esc" Button will open the Menu multible times

### ISSUE THREAD

**Issue by NathanaelMangold** [StrangeLoopGames/EcoIssues#8568]
If you press the ESC button quickly twice (by incident) the menu will get opened multible times.
You can repeat this until the screen turns completely dark.

You are unable to quit the old menus. So you need to restart.

![20180717174453_1](https://user-images.githubusercontent.com/41338825/42829155-9f944312-89e9-11e8-930e-47d2d860a1d4.jpg)
![20180717174455_1](https://user-images.githubusercontent.com/41338825/42829156-a0150b1e-89e9-11e8-884c-efa014abc11e.jpg)
![20180717174542_1](https://user-images.githubusercontent.com/41338825/42829157-a037ab7e-89e9-11e8-8209-d987501c1edb.jpg)

**Comment by Nicolausi113** [comment]
Agree – but Quit button still works

**Comment by MarjieAVolk** [comment]
This has been fixed but not released.  Will be fixed in the next major release.
