### ISSUE TITLE
SERVER PROBLEM: Missing UI / Disabled since last update

### ISSUE THREAD

**Issue by Simonmicro** [StrangeLoopGames/EcoIssues#8577]
Server, Client or Website?
Linux (Debian 9) Server

    OS/Web Browser?
See above

    Detailed Description of Issue:

    Reproducible? How difficult is it to reproduce?
For me: Easy ;) Install a Eco server under linux using the required mono(-devel) runtime files and e.g. a vncserver (for debian: vnc4server) with minimal desktop envroiment to host the server. After the successfully start the system will block every attempt to open the server UI ("Skipping GUI because your platform isn't supported, platform = Unix"). Because there is an existing vncserver with GUI support and WITHOUT --nogui (and before the update the UI was working) I assume this as an Bug.
(Also the UI has some problems on proper configuration - like admin IDs and other submenues...)

    Steps to reproduce bug/issue:
See above :)

    Additional Comments:
I would love to see the UI working again - maybe with the ability to control the growing time again like in some updates before...

    Client Version? [Alpha .01 for example]
0.7.6

**Comment by metachronism** [comment]
This is from the PR that disabled the UI on unix by default.  Seems it did work on some unix-based os'

**Comment by Simonmicro** [comment]
@metachronism 
It _was_ working before 7.6.0 (I guess). I've wrote a little tutorial for the UI under " https://eco.gamepedia.com/index.php?title=Setting_Up_a_Server&oldid=14548 ". I hope we will get the UI back soon,
Simon
