### ISSUE TITLE
Flying "hanging" signs

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#8578]
All the plates that are hung on the wall (hanging sign) do not attach to the wall, but rather float (fly) in the air.
![20180717194313_1](https://user-images.githubusercontent.com/1098421/42840209-be2ed4a2-8a0e-11e8-8867-e20653c04585.jpg)
![20180717194324_1](https://user-images.githubusercontent.com/1098421/42840210-be5a7422-8a0e-11e8-9a9d-b2c5dc8ea2b9.jpg)
![20180717195105_1](https://user-images.githubusercontent.com/1098421/42840211-be7bb3d0-8a0e-11e8-89bd-9dc2567ec1b8.jpg)
![20180717195118_1](https://user-images.githubusercontent.com/1098421/42840212-bec3c710-8a0e-11e8-8a9d-c20f924bc447.jpg)

**Comment by Voosle** [comment]
please cross check
#8173 #8055 #8442

**Comment by keegan-o** [comment]
Already was another bug that I fixed in master. Hanging signs will return to the back of the meter space, standing signs will stay centered.
