### ISSUE TITLE
Everything dies

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#858]
Lots of servers seeing everything dead after just 1 day of simulation.

**Comment by combatbanana** [comment]
i have also experienced this.  The Aussie server has done the same and I have run a few simulations now with different seeds on my own pc.  

The dialog box does say everything is dead (as does the server gui's "stats" tab - but you can clearly see animals and plants still alive in the attached picture.
![image](https://cloud.githubusercontent.com/assets/20417839/20851090/26add602-b943-11e6-9452-d7a36c98053e.png)

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/1140/animal-population-dropped-in-less-than-a-day-didn-t-even-kill-1 just leaving this here =)

**Comment by combatbanana** [comment]
ive overcome this bug by modifying the calorie consumption of the animals (lowering it).  I now have a pretty stable animal and plant population on the default seed.

I take it that this variable determines how much they need to eat before they multiply?  I assumed they might have been dying of old age before getting to this calorie consumption amount?  Would be nice to be able to see why the animals are dying like in Alpha 4.

Also those pictures i uploaded seem unrelated to the die off events. Every time the server stops/crashes it always shows 0 for a short duration (this is also represented on the web graphs which show everything sharply drops to 0 and then returns to previous amounts a short time later).

**Comment by mauzao9** [comment]
@combatbanana heya, can you describe what stats you changed exactly? I changed all calories stats on the sim config to half and it's still decreasing. 👍

**Comment by combatbanana** [comment]
If you are desperate, Under 'ecosim.eco' change all the calorie consumption values to 10. You will get a 100-300 on the next tick update. I played around with that setting until they stabilized, I'm not home at the moment but I will share the balanced numbers I used when I get home

**Comment by combatbanana** [comment]
Hare 45
Elk 95
Wolf 250
Bison 135
Turkey 35
Fox 45 (this may still need decreasing)

![image](https://cloud.githubusercontent.com/assets/20417839/20878382/76ee4614-bb33-11e6-9b32-8250a7f8a594.png)

also note those sharp drops to 0 indicating when the server was reset as per my previous comment

**Comment by Hed9870** [comment]
Is there a way to do this if you're running a private server? Not that it matters as I can just spawn things but most of my animals are dead after less than 24 hours.

**Comment by metachronism** [comment]
latest hotfix has this fixed (redownload from accounts page)

**Comment by craig-jong** [comment]
I'm going to say this is fixed with the incoming 5.5 changes by Steven. If it isn't, please reopen.
