### ISSUE TITLE
0.7.6: Changed main inventory slot for materials is reducing game play experience

### ISSUE THREAD

**Issue by springphul** [StrangeLoopGames/EcoIssues#8588]
The new main inv slot for building material and such (stone, coal...) was moved from left hand side of the hotbar to the center -top of the hotbar. This is bad for handling inventory windows.
Until now I could drag the window almost over the entire screen. It is helpful to keep track of the inventory items in storages nearby. Now I loose "one storage view". I have to make the inventory window smaller, since the main slot is above the hotbar now. So I loose one line, where a stockpile or a chest could be displayed.

This game is much about managing stuff. So in my opinion, reducing the space for displayed storages minimize the management possibilities; So it is a not well thought game design change. Probably for the greater good of new players to realize the speciality of this inventory slot, idk. But anyway, for an experienced gamer in management games it is limiting the game play.

**Comment by Nicolausi113** [comment]
Yes!
But could be managed if Carrying Window pops up in foreground overwriting all others. Keep in mind, the Form Selector Window appears also left from that window.

**Comment by elfl0rd** [comment]
feedback from ru community
1) Most players like this change
2) But yes, two problems. Slot is not appear periodically and slot can be hidden by another ui elements (chat, etc...)

**Comment by WeaselDog** [comment]
We have had major updates to our UI and more coming in the next update so I am going to close. Let us know if this is still an issue for you.

Thanks for the feedback!
