### ISSUE TITLE
SUGGESTION: Add more server arguements

### ISSUE THREAD

**Issue by Simonmicro** [StrangeLoopGames/EcoIssues#8589]
Hi,
here two ideas for servers UI parms:
--nogui for a start without UI (for linux VNC sessions)
--disablegui for a start without ui and general (for linux shell only)
See you,
Simon

**Comment by Nicolausi113** [comment]
Suggestions should go here:
 https://github.com/StrangeLoopGames/EcoSuggestions/issues
