### ISSUE TITLE
pay improvement

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8594]
**Version:** 0.7.6.1 beta
Need "all" argument, to provide way for send all currency.

**Comment by johnkslg** [comment]
Pay someone in all currencies??  What is that for?

**Comment by elfl0rd** [comment]
e.g. for send all money to friend traveling to store.
"all" really easy versus 185,85

or

remove player currency after minted currency available

**Comment by elfl0rd** [comment]
Pay removed, but cleaning\sending all currency still actual :(
@Quadbro can you look?

**Comment by Deantwo** [comment]
@Quadbro, just to be sure, this doesn't just fill the input field with the amount of money, right?
I believe there is still a chance that you can get a currency amount that is too small to write in the input fields.
At least be a champ and test it. Having `0.00000000042` of sone obcure credit that no uses is just annoying.
See: #9280

PS: Fixed-point currency numbers?

**Comment by Quadbro** [comment]
@Deantwo it fills field with max value, so no "0.0000000100500" values left
