### ISSUE TITLE
USER ISSUE: Unclaim Admin Command

### ISSUE THREAD

**Issue by Wally1169** [StrangeLoopGames/EcoIssues#8596]
**Version:** 0.7.6.1 beta

**Steps to Reproduce:**
1. Go to property to be unclaimed
2. Use /unclaim
3. Crash.  (Note: I was able to successfully unclaim one plot and then not a subsequent one.  Another admin also cannot unclaim after my initial one)
4. Property is still claimed when returning to the server

**Expected behavior:**
Unclaimed the property without crashing

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.PropertyManager.ForceUnclaim(Vector2i pos)
   at Eco.Gameplay.Systems.Chat.AdminCommands.Unclaim(User user)</size>
```

**Comment by MarjieAVolk** [comment]
It looks like this null ref can happen if the plot you're trying to unclaim is already unclaimed.  I'm fixing that.  I'm not sure how it could happen if the plot is actually claimed though.

Maybe the plot in question is actually unclaimed, but didn't send its unclaim update to clients?  Does it disappear if you rejoin or restart the server?

If that's not the case, and this happens consistently for a specific plot, could you send me your save file?

**Comment by Wally1169** [comment]
It was still claimed even after logging back in.  The other admin who was also getting kicked moved his new plot claim tool into his toolbar, and I believe made it the selected tool, and was able to unclaim property without being kicked.  I did the same (including making it my selected tool) and I was also able to unclaim without being kicked.  Not sure if that was just coincidental timing or actually had an effect.

**Comment by MarjieAVolk** [comment]
Hm, that shouldn't have an effect 🤔

**Comment by Wally1169** [comment]
I thought not, but I thought I’d mention it just in case.

**Comment by MarjieAVolk** [comment]
Okay, so I turned in a fix for a crash that was related to this, I am not sure if it will fix your issue.  But turning the priority down until we get more repro cases.

**Comment by MarjieAVolk** [comment]
Looks like it didn't make it in there unfortunately, it will be in the next hotfix, if and when that happens.
