### ISSUE TITLE
[7.7.0] Text for a lot of the UI is broken

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#8597]
![image](https://user-images.githubusercontent.com/6262198/42900566-1077a274-8a7e-11e8-84c3-b429b2a00a2e.png)

**Comment by BlazeGuy2** [comment]
Applies to more of the UI, check the missing letters and broken formatting:
![textproblem](https://user-images.githubusercontent.com/35509188/42912575-f7326c82-8aa4-11e8-8fbe-9fbb43921201.PNG)

**Comment by Nanders** [comment]
Fixed in SVN
