### ISSUE TITLE
[Suggestion] Make Sea Food look Different when Dead (very hard to see the difference) also they are living Creatures not plants

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#8600]
**Version:** 0.7.6.1 beta

Would be nice to notice a real difference between alive and dead Clams, (they look Identical) and the only way to tell is to try and collect and it will either collect or say this plant is dead (which is weird really seeing as Clam and Urchins are not Plants)

Urchins are Blue and Reddy Pink with i think White for being dead

**Comment by Conchipedia** [comment]
![snap2308](https://user-images.githubusercontent.com/29383891/42909403-f1e5a974-8adb-11e8-9211-663d0a51260f.png)
after a conversation in Discord

**Comment by keegan-o** [comment]
I can't change the chat message myself, all I can do is add cracks or something to the dead clams as an indicator. Shall do that... @craig-jong Are you gonna do the chat message change?

**Comment by keegan-o** [comment]
Actually, there already is a difference for dead clams. The dead clams have no clams in the shells, whereas the living ones have clams.

**Comment by keegan-o** [comment]
Added cracks anyways!

**Comment by craig-jong** [comment]
You can harvest dead plants now, I guess so there isn't a chat message.
