### ISSUE TITLE
USER ISSUE: i cannot Press Z to open Skill Menu until ALL tutorials are complete (especially construction one)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#8601]
**Version:** 0.7.6.1 beta

**Steps to Reproduce:**
try pressing Z to open Skill window, will NOT allow you to do this until the "Construction" tutorial has been completed

**Expected behavior:**
i should be able to press Z anytime i like to view Skill menu

**Actual behavior:**
will NOT open window until The SP part of the bottom Left of UI is unlocked by doing Tutorial

**Comment by D3nnis3n** [comment]
Is this issue persisting?

**Comment by elfl0rd** [comment]
Intended behavior, you cannot see skills before you complete\skip tutorial.
Also after update, you get message about skill window unavailability.
