### ISSUE TITLE
Houses not recognised as enclosed rooms after 7.6.1 update

### ISSUE THREAD

**Issue by jammie19** [StrangeLoopGames/EcoIssues#8602]
After migrating my eco server (through steam) to 7.6.1 (17th July 2018), houses were no longer recognised as being enclosed rooms, nor provided any skill points: https://imgur.com/a/lZSSfAa
Server configs before the update (6th July 2018) and just after have been attached.
[ConfigsPostUpdate.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2207228/ConfigsPostUpdate.zip)
[ConfigsPreUpdate.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2207229/ConfigsPreUpdate.zip)

**Comment by Amphysbaenas** [comment]
@craig-jong Medium only really, that bug at each restart kill economy because we have to wait for several hours or days (summer hollidays) to have all shops with a green light again
That bug kill gameplay , kill economy and make angry players

**Comment by Myrhaug** [comment]
This bug should atleast be listed as high priority. As Amphy said, this bug kills economy and gameplay.
This is a bug that occured long time ago, time to fix this once and for all!

**Comment by Amphysbaenas** [comment]
no problems for the new migration from 761 to 762

**Comment by D3nnis3n** [comment]
Old issue, no longer occuring.
