### ISSUE TITLE
USER ISSUE: A server i added by IP and Port will NOT show up in Recent list and i cannot find it with Search

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#8603]
**Version:** 0.7.6.1 beta

**Steps to Reproduce:**
Manually Add 91.205.174.61 : 3000 (ClaysTK Test Server) you can join it and it loads, it will also come up with name in Continue, but will NOT show in recent list, and if i load up another server i have to Manually add the IP and port again to get there

**Expected behavior:**
Manually add IP and Port, when you exit that server it will show up in recent List and give me the option to rejoin on there or add as a favourite. Also no matter what i type into search i cannot find it

**Actual behavior:**
I add IP and port and i can join, It will NOT add to recent list and i cannot find the server by searching

![snap2298](https://user-images.githubusercontent.com/29383891/42905989-97fc74f6-8ad1-11e8-949d-f79a242437f6.png)
as can be seen above It is Not in Recent Server list.
![snap2299](https://user-images.githubusercontent.com/29383891/42905990-981e3f3c-8ad1-11e8-86b7-e426d225f910.png)
as can be seen above i have been on it so it does know its name and i can continue.
![snap2300](https://user-images.githubusercontent.com/29383891/42905991-9842e076-8ad1-11e8-9415-904cea321cdf.png)
and its even on the Eco Server List

Ignore the I cannot search for by name, in 0.7.60 i couldnt find the name in 0.7.6.1 i now can 
![snap2301](https://user-images.githubusercontent.com/29383891/42906141-1bcd4c88-8ad2-11e8-8145-a4b4665ffd9a.png)

**Comment by MarjieAVolk** [comment]
I see in your recents list, the top one is showing up blank.  Is that entry for the server that you joined by ip?

Could you send me your 'recentServers.eco' and 'player.eco' files from AppData right after this happens?  (C:\Users\\{username}\AppData\LocalLow\Strange Loop Games\Eco)

**Comment by Conchipedia** [comment]
[ECO (RecentServers.eco + Player.eco).zip](https://github.com/StrangeLoopGames/EcoIssues/files/2208778/ECO.RecentServers.eco.%2B.Player.eco.zip)

Uploaded Player.eco and recentServers.eco as requested

**Comment by MarjieAVolk** [comment]
Okay, so this test server is the same thing as the one with the blank line?

**Comment by MarjieAVolk** [comment]
So it looks like at least part of the reason this got weird, is because your saved recent server - the messed up one - has a space at the end of the ip address.  That should be trimmed off before it's saved so that's part of the bug at least.

**Comment by MarjieAVolk** [comment]
The reason you are seeing the server appear in LAN is I believe because you have two copies of it in the recent section.  Kind of odd.  I should be able to fix that though.

**Comment by MarjieAVolk** [comment]
Fixed in next major update 👍
