### ISSUE TITLE
USER ISSUE: World not showing in Minimap window, but it will show player and trees

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#8604]
**Version:** 0.7.6.1 beta

![snap2302](https://user-images.githubusercontent.com/29383891/42906324-c2e19556-8ad2-11e8-8e56-6807fb3a3f8d.png)

only way to make the world show again is to totally quite eco and load again, this used to happen to me in Previus versions as well

**Comment by Voosle** [comment]
#8297

**Comment by Conchipedia** [comment]
this isn't a crash as i can still play the game normally just not display anything in map screen

**Comment by SeanAtr0n** [comment]
please attach your output log after seeing this behavior
`%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

Typically this happens if your gpu doesn't support the shader but that should be getting auto-detected

**Comment by SeanAtr0n** [comment]
also lowering your minimap detail in the escape menu will likely make the map appear

**Comment by Conchipedia** [comment]
Minimap detail disappeared 
[output_log(when minmap went).txt](https://github.com/StrangeLoopGames/EcoIssues/files/2220792/output_log.when.minmap.went.txt)
changed detail in escape menu and it came back
[output_log.(after i changed mimap detail in ESC menu).txt](https://github.com/StrangeLoopGames/EcoIssues/files/2220795/output_log.after.i.changed.mimap.detail.in.ESC.menu.txt)

i attatched both (before and after minimap went off and i got it back) just in casde there is some extra info in them

**Comment by Conchipedia** [comment]
this is still happening in 0.7.6.3 (i have always had my Minimap Detail on Max) but if i move slider down in game map comes back then i just slide it back to max.

**Comment by SlayksWood** [comment]
Such a problem exists in 0.9.0 for a one user who plays with us on Alex stream. we investigated this problem, but we didn't find any solution. His step to reproduce:
- He start game. Join to server. Look at minimap:
![unknown](https://user-images.githubusercontent.com/45708377/72511031-7f786f00-385b-11ea-84f3-0e3cc3dbf430.png)
Still if he open big minimap:
![unknown (1)](https://user-images.githubusercontent.com/45708377/72511116-9f0f9780-385b-11ea-8402-2fe32d6fc4c7.png)
- To fix it he should disconnect and connect again.
- If he start game again. and join server minimap will same again. And he needs to disconnect again.

PC:
        Operating System
            Windows 7 Профессиональная 64-bit SP1
        CPU
            Intel Core i5 6500 @ 3.20GHz    41 °C
            Skylake 14nm Technology
        RAM
            16,0ГБ Dual-Channel Unknown @ 1066MHz (14-14-14-32)
        Motherboard
            Gigabyte Technology Co. Ltd. H110M-S2-CF (U3E1)    28 °C
        Graphics
            W2043 (1600x900@60Hz)
            Intel HD Graphics 530 (Gigabyte)
        Storage
            111GB 120GB SSD SCSI Disk Device (SATA (SSD))    48 °C
            931GB Western Digital WDC WD10EZEX-08WN4A0 SCSI Disk Device (SATA )    38 °C
            931GB Western Digital WD Elements 1078 USB Device (USB (SATA) )    33 °C
        Optical Drives
            No optical disk drives detected
        Audio
            Стереоустройство с технологией Bluetooth

**Comment by gzatravkin** [comment]
@SlayksWood  Please attach log file for recent player with issue at 9.00

**Comment by SlayksWood** [comment]
@gzatravkin oh sorry, my bad:
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4075151/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4075152/Player.log)

It's from #14254
```
NullReferenceException: Object reference not set to an instance of an object.
  at GhostCamera.Update () [0x00000] in <00000000000000000000000000000000>:0 
```
