### ISSUE TITLE
[7.7.0] Can't move items between inventories in general

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8605]
Can't drag items hewn logs from tiny stockpile to my inventory
https://youtu.be/Y5VEfB7sVKQ

**Comment by BlazeGuy2** [comment]
Also applies to stockpile generated from /spawnfullstockpile

**Comment by MarjieAVolk** [comment]
Is this for carried items only?  I noticed issues with that earlier.

**Comment by BlazeGuy2** [comment]
Yeah, for carried items.  Impossible to grab hewn logs to finish the tutorial.

**Comment by BlazeGuy2** [comment]
Just reproduced on the staging branch in Unity.  Currently running the server in debug mode.

**Comment by johnkslg** [comment]
Fixed!
