### ISSUE TITLE
[7.7.0] Material Processing Tutorial isn't registering as completed

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8607]
All of the checkmarks are filled in, tut is not disappearing with the Material Processing tutorial.
![tut_bug](https://user-images.githubusercontent.com/35509188/42908306-6f615142-8a95-11e8-92af-0c3f459adf2c.PNG)

**Comment by johnkslg** [comment]
Couldnt make this happen, can you give repro steps and any exceptions you found?

**Comment by BlazeGuy2** [comment]
Didn't repro when I used the user Testalpha

**Comment by BlazeGuy2** [comment]
Couldn't reproduce.  Closing.
