### ISSUE TITLE
Deleting mods does not remove them from an updated server

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8608]
Installing over the top of an old installation will leave around deleted mods. Lots of servers have incorrect mods because of this.  While this could be called 'user error', I would like to take the approach of making updating as easy as possible by addressing it.

Couple ways we could do it:
- Maintain a list of deprecated mods that get ignored on load
- Have a version number on mods (at least on the ones that are part of the base installation) that prevents them loading

**Comment by WeaselDog** [comment]
Fixed with new mods folders
