### ISSUE TITLE
[7.7.0] Issue with world loading

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8610]
This chunk of the world won't load for me.  Gravity doesn't apply here, you can see me rise as I press the space bar here.
https://youtu.be/GPo_BaNk-Bs

**Comment by BlazeGuy2** [comment]
[Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2207525/Game.zip)

**Comment by SeanAtr0n** [comment]
the gravity in this scenario is intentional... no more falling infinitely (as requested)

**Comment by BlazeGuy2** [comment]
Ah, good to know.  Other issue is that the segment I'm walking on that should have loaded in isn't loading.

**Comment by BlazeGuy2** [comment]
Cannot replicate again, closing.
