### ISSUE TITLE
[7.7.0] Can't Access anything browser-based from the game

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8612]
Had a couple of exceptions occur in game so far, tried to use the send to github UI.  Nothing is getting posted to github.  This will cripple some users when they choose to report bugs.

**Comment by BlazeGuy2** [comment]
Also can't reach the laws and general webpages

**Comment by SeanAtr0n** [comment]
Works fine in-editor both with/without steam... seems to be an IL2CPP issue

**Comment by metachronism** [comment]
IL2CPP, reverted for now.  Still want to get it working though eventually
