### ISSUE TITLE
[7.7.0] Picked up stone with crane, crane is showing hewnlog block

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8613]
Inventory of crane doesn't match the visual of what it's holding.

**Steps:**
1. invoke /testcranes
2. grab the stones in the truck that spawned

![cranebug](https://user-images.githubusercontent.com/35509188/42911849-7aca4e92-8aa1-11e8-9311-53ee54480b4a.PNG)

**Comment by BlazeGuy2** [comment]
Does place stone blocks though.

**Comment by elfl0rd** [comment]
like refers https://github.com/StrangeLoopGames/EcoIssues/issues/7889

**Comment by johnkslg** [comment]
Fixed!
