### ISSUE TITLE
Crash to title screen (Server Exception) while trying to set up a currency exchange

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#8615]
While trying to set up a Currency Exchange,

1. Place Currency Exchange into the world.
2. Open Currency Exchange interface.
3. Attempt to change currency in dropdown as shown in picture below.
4. Crash to title screen. Error log attached. (Note: Error log has 55,000 lines!!)
5. Re-join server and attempt again. Same result.

[currency exchange - eco_server_crash_log_2018-07-19_09-04.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2207624/currency.exchange.-.eco_server_crash_log_2018-07-19_09-04.txt)

![image](https://user-images.githubusercontent.com/2173684/42912542-431f5662-8b33-11e8-88f1-7ba60460cea0.png)

**Comment by BlazeGuy2** [comment]
What version of the game is this happening on?

**Comment by LiaungYip** [comment]
@BlazeGuy2 , 7.6.1, on Pam's Big World server.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/8591

**Comment by pamduncan** [comment]
This appears to be the error generated at that time:

--BEGIN DUMP--
Dump Time
07/18/2018 18:07:11

Exception
Exception: Exception
Message:Original type is Object. Cannot convert from Object to Guid
Source:Eco.Shared

System.Exception: Original type is Object. Cannot convert from Object to Guid
   at Eco.Shared.Serialization.BSONValue.get_GuidValue()
   at Eco.Shared.Serialization.BsonManipulator.<>c.<.cctor>b__14_15(BSONValue value)
   at Eco.Shared.Serialization.BsonManipulator.FromBson(BSONValue value, Type type)
   at Eco.Shared.Networking.RPCManager.UnpackArgs(INetClient client, BSONObject bson, RPCMethod[] methods, Object target, RPCMethod& targetMethod)

--END DUMP--

**Comment by LiaungYip** [comment]
Duplicate of #8591 and fix merged in https://github.com/StrangeLoopGames/Eco/pull/3114 . Closing.
