### ISSUE TITLE
[7.7.0] Distribution Station : You can grab the items in it directly, and it highlights badly. 

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8617]
I should only be able to grab 4 seeds, but I managed to grab 8.
![distr_bug](https://user-images.githubusercontent.com/35509188/42913555-7c199e70-8aaa-11e8-96d9-46b990d92576.PNG)

**Comment by johnkslg** [comment]
Something broken with item ownership (says PersonNameHere after being claimed) is causing this issue.

**Comment by johnkslg** [comment]
Also the Item Distribution tab didnt show  up, and a bunch of exceptions appeared when trying to view.
NullReferenceException: Object reference not set to an instance of an object
GetWorldObjectUIScrollbar.ReleaseScrollbar () (at Assets/UI/Scripts/Utilities/GetWorldObjectUIScrollbar.cs:28)
UI.WorldObjectPanel.OnHide () (at Assets/UI/Scripts/WorldObject/WorldObjectUI.cs:31)
UI.StorageUI.OnHide () (at Assets/UI/Scripts/WorldObject/StorageUI.cs:113)

**Comment by MarjieAVolk** [comment]
I don't really know how this thing is supposed to work.  You can take as much as you want if you're the owner?

If there is something wrong with auth... could you send me your save file?

**Comment by MarjieAVolk** [comment]
I've fixed the world object ui, if there's any issues left it's in the distribution station itself.

**Comment by metachronism** [comment]
fixed
