### ISSUE TITLE
[7.7.0] Graphical issue with the server browser window

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8619]
![browsergraphicalerror](https://user-images.githubusercontent.com/35509188/42914174-bc60e274-8aad-11e8-98f9-590fe495cdce.PNG)

**Comment by MarjieAVolk** [comment]
wtf is that 🤔

**Comment by GophTheGreat** [comment]
Server browser was redesigned. Closing.
