### ISSUE TITLE
USER ISSUE: stockpile from campsite can be placed on another player property

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8621]
**Version:** 0.7.6.1 beta
![20180719033353_1](https://user-images.githubusercontent.com/4980243/42914755-c4f188c4-8b04-11e8-8129-072e0e44cb47.jpg)
![20180719033401_1](https://user-images.githubusercontent.com/4980243/42914758-c7d127c0-8b04-11e8-81e8-df4fe469d812.jpg)
![20180719033412_1](https://user-images.githubusercontent.com/4980243/42914760-c96606f0-8b04-11e8-9f3c-742f559a8f6a.jpg)

**Comment by Nicolausi113** [comment]
is it still accessible and removable ?
(would like know- Wiki don't say abut new property behavior)

**Comment by elfl0rd** [comment]
not, after placing - it's another player property
(you can see it on 2rd screenshot)

**Comment by Nicolausi113** [comment]
I see, game should avoid placing but don’t – Tanks!

**Comment by craig-jong** [comment]
Fixed in above PR.
