### ISSUE TITLE
Missing feature - "nickname" marker recolor based on reputation.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8623]
![20180719033040_1](https://user-images.githubusercontent.com/4980243/42915353-1f1dd48a-8b08-11e8-8c32-122862ce499e.jpg)
![20180719033053_1](https://user-images.githubusercontent.com/4980243/42915355-213341ec-8b08-11e8-9c8e-293c972a677b.jpg)

**Comment by pamduncan** [comment]
I add made this as a bug report  per JohnK some time ago - labelled suggestion that color be added.  I am not sure whatever became of it or if it was not doable

**Comment by elfl0rd** [comment]
Hm, it's different.

Here - creating "nickname" marked - use current reputation color.
yellow or green and not change it in after marker created.
If dinamically change is not available need to remove the addition of color based on the current reputation...

Just create "nickname" markers white everytime...
