### ISSUE TITLE
Forest Forager and Wetlands Wanderer don't include Beans and Rice, Respectively

### ISSUE THREAD

**Issue by Wally1169** [StrangeLoopGames/EcoIssues#8624]
Forest Forager doesn't list a Benefit for Beans harvest and Wetlands Wanderer doesn't list a Benefit for Rice harvest.  Is this intended with the changes to seeds?
![image](https://user-images.githubusercontent.com/40220854/42916836-1a229df4-8ad5-11e8-8183-d57b911be06f.png)
![image](https://user-images.githubusercontent.com/40220854/42916846-2ca58130-8ad5-11e8-87c7-d70b14358bc5.png)

**Comment by LiaungYip** [comment]
For completeness, Camas no longer benefits from Grassland Gatherer, either.
