### ISSUE TITLE
Contract - Failed

### ISSUE THREAD

**Issue by Myrhaug** [StrangeLoopGames/EcoIssues#8626]
I made a contract some while ago, and ingame say client can mark it as failed at any time.
There is no function for marking as failed ingame.

![contract-bug](https://user-images.githubusercontent.com/40342749/42934353-3b9130a0-8b47-11e8-8187-faf596782d85.png)
![contract-bug2](https://user-images.githubusercontent.com/40342749/42934354-3bb0f598-8b47-11e8-89c6-efb0bf8637fb.png)

**Comment by johnkslg** [comment]
That should say 'contractor' can mark it failed anytime.
Looks like you are indeed the contractor though?

**Comment by LiaungYip** [comment]
Should either the Principal or the Contractor be able to mark an overdue contract as failed?

(In below example, I have a lot of money held in escrow - if the currency was in limited supply, I would want the money back.)

![image](https://user-images.githubusercontent.com/2173684/43034115-69c0aad6-8d19-11e8-9756-1114fb3ba978.png)

**Comment by Myrhaug** [comment]
Yes, im the one who made the contract. Only way to delete the contract, is mark it as finished (even when its not, and I have to pay him).

**Comment by johnkslg** [comment]
Fixed! Thanks for the details.
