### ISSUE TITLE
USER ISSUE: Can't type in properly in order to login

### ISSUE THREAD

**Issue by petarvasilev91** [StrangeLoopGames/EcoIssues#8629]
**Version:** 0.7.6.1 beta

**Steps to Reproduce:**
When I type in letters for my username the letters are repeated, the same happens even when I try to copy the username. I am running Ubuntu 16.04

**Expected behavior:**
Be able to type in and login without issues

**Comment by SeanAtr0n** [comment]
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3580

there are various ways to make it work mentioned in that thread
