### ISSUE TITLE
USER ISSUE: GroundPollution

### ISSUE THREAD

**Issue by Whimsy85** [StrangeLoopGames/EcoIssues#8630]
**Version:** 0.7.6.1 beta

**Steps to Reproduce:**
This must be a bug. i hope it is.
https://www.youtube.com/watch?v=K9KOP7P-nao

**Expected behavior:**
I understand that if tailings will spread from cart 1-2 or even 3 blocks..

**Actual behavior:**
..but i don't understand if it will spreads like 20-30 blocks -and straight up! and through to stones.

**Comment by elfl0rd** [comment]
do not compress tailings in carts, it flows

**Comment by Whimsy85** [comment]
any pollutions wont "flow" through stone. its not legit!

**Comment by springphul** [comment]
it is the way it is in ECO. it spreads infinity above. If you put a stone ceiling in the height of 10 Tiles above the last stack of tailing it won't spread further/higher. I use my empty stone mine rooms for the, it works perfectly. I just place ceilings at the top and the stockpile on the plane ground.

**Comment by elfl0rd** [comment]
> any pollutions wont "flow" through stone. its not legit!

Balance. You want compressed tailings storage? Okay, it pollute.

**Comment by Whimsy85** [comment]
so, i need to fill and empty bloomers and blast furnaces manually if dont want to pollute whole map!?! im playing singleworld, i really have many other things to do, not have time to camp there and wait many minutes per ingot to empty and fill it again. -.- what i did there, i put that many ingots coming what that cart can handle tailings and then empty it. and now that whole little mountain is polluted for that. so that really sucks if i need to use those manually, if i dont wanna pollute. i dont have time to do anything else then. -.-

**Comment by elfl0rd** [comment]
you can smelt directly to stockpile placed in tailings storage :P

**Comment by Whimsy85** [comment]
can i take that stockpile then in to my pocket and take it there where i need? ..didnt think so.

**Comment by GophTheGreat** [comment]
I don't think this is a bug? Closing for now.
