### ISSUE TITLE
Please check bison and elk mounts collision.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8631]
![20180719135406_1](https://user-images.githubusercontent.com/4980243/42940343-ca3f900c-8b61-11e8-8848-c58ca398d02e.jpg)

**Comment by seccombew** [comment]
Would you please explain the issue further.

**Comment by elfl0rd** [comment]
collision too big, i regular hit bison head instead of wanted block...

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/44283513-78d36b80-a213-11e8-8f66-4f8c9ca058b6.png)
Fixed in master (will be in patch after 7.7)
