### ISSUE TITLE
Targeting Issue

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#8636]
If I stand on or am near a stockpile, have my shovel equipped, and targeting a block of dirt outside of the stockpile, I pick up (goes in carry slot) copper ore from the stockpile and the shovel is automatically unequipped. 

In first person, you can't see that the stockpile is what is highlighted, only that your pointing the reticule at something outside of it, which doesn't seem to matter. 

![dirt1](https://user-images.githubusercontent.com/36867473/42959424-9697d724-8b3d-11e8-95b9-1b8500c78d32.png)
![dirt2](https://user-images.githubusercontent.com/36867473/42959430-9931e100-8b3d-11e8-96b8-37e3b3aebd07.png)

**Comment by metachronism** [comment]
thats because you are targeting the stockpile, as its the closest object to you

**Comment by ShaydenMac** [comment]
I understand that the stockpile is being targeted but the problem is that I'm not aiming the tool I have equipped at the stockpile but the dirt outside of the stockpile. My reticule should target/highlight what it's pointing at not something that is next to me or below me and out of my view.

**Comment by GophTheGreat** [comment]
Is this intended behavior then?

**Comment by D3nnis3n** [comment]
I'd say no.
