### ISSUE TITLE
Doors not have tier and useless until he considered as 0 tier block

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8637]
Doors - not have tier.
You cannot make ideal room even if you use glass doors (glass doors visually as 4 tier)
see screenshot
no door
![20180719211926_1](https://user-images.githubusercontent.com/4980243/42962162-9e518b66-8b99-11e8-90d1-5d071ec474bc.jpg)
glass door
![20180719211934_1](https://user-images.githubusercontent.com/4980243/42962167-a235a0e6-8b99-11e8-869c-085f7d5eb46f.jpg)
no door (solid wall)
![20180719212004_1](https://user-images.githubusercontent.com/4980243/42962174-aa2aac4c-8b99-11e8-8bb1-7c1cc511ef17.jpg)

as result - players make solid rooms, without entrance...

It became even more strange after adding new doors

looks partially like https://github.com/StrangeLoopGames/EcoIssues/issues/7490
and maybe correspond as https://github.com/StrangeLoopGames/EcoIssues/issues/8379

**Comment by craig-jong** [comment]
Fixed in above PR.
