### ISSUE TITLE
Rivets and Steel Rivets Efficiency Not working

### ISSUE THREAD

**Issue by MunroeM** [StrangeLoopGames/EcoIssues#8641]
I have Casting efficiency lvl 5 and when I hover over the rivets or steel rivets it tells me it will take 0.2 iron or 
 0.2 steel to make. 
-for an order of 1 it costs 1 iron or steel (should cost 1 steel or iron) true cost 0.2
-for an order of 2 it costs 2 iron or steel (should cost 1 steel or iron) true cost 0.4
-for an order of 3 it costs 3 iron or steel (should cost 1 steel or iron) true cost 0.6
- 4 for 4 (should cost 1 steel or iron) true cost 0.8 
- 5 for 5 (should cost 1 steel or iron) true cost 1.0
- 6 for 6 (should cost 2 steel or iron) true cost 1.2

**Comment by craig-jong** [comment]
rounding errors should be fixed.
