### ISSUE TITLE
Inventory not showing 'unowned'

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8643]
![image](https://user-images.githubusercontent.com/3536496/42971406-ff77333e-8b60-11e8-9264-90dc44ccd84c.png)
I believe this is causing other auth problems possibly.
Probably related to these exceptions on WorldObjectUI open:

NullReferenceException: Object reference not set to an instance of an object
GetWorldObjectUIScrollbar.ReleaseScrollbar () (at Assets/UI/Scripts/Utilities/GetWorldObjectUIScrollbar.cs:28)
UI.WorldObjectPanel.OnHide () (at Assets/UI/Scripts/WorldObject/WorldObjectUI.cs:31)
UI.StorageUI.OnHide () (at Assets/UI/Scripts/WorldObject/StorageUI.cs:113)
UI.WorldObjectUI.OnHide () (at Assets/UI/Scripts/WorldObject/WorldObjectUI.cs:327)
UI.UIManager.Hide (UnityEngine.GameObject gui) (at Assets/UI/Scripts/Manager/UIManager.cs:420)
UI.UIManager.Close (UnityEngine.GameObject existingGUI) (at Assets/UI/Scripts/Manager/UIManager.cs:218)
UI.UIManager.Close (System.String guiName, Eco.Shared.Serialization.BSONObject bson) (at Assets/UI/Scripts/Manager/UIManager.cs:195)
UI.UIManager.Close (System.String guiName) (at Assets/UI/Scripts/Manager/UIManager.cs:160)
UI.BaseUI.Close () (at Assets/UI/Scripts/BaseUI.cs:76)
UnityEngine.Events.InvokableCall.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:166)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:58)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:36)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:45)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by MarjieAVolk** [comment]
What exactly is the issue?  The 'personnamehere' text?  Who is the owner supposed to be?

**Comment by johnkslg** [comment]
This is placed on unowned ground.  It should say 'unowned'.

**Comment by MarjieAVolk** [comment]
Well, I haven't been seeing that happen, so I'm going to assume that the exception you posted is causing it.
