### ISSUE TITLE
On Hardware with multiple servers getting collisions when multiple servers start up and try to compile EcoMods.dll

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8651]
issues with multiple  servers on same hardware that all are writing EcoMods.dll to <username>/appdata/Local/Temp as on a hosted server.  All the various games servers run under the same user name - that of the Game panel so they have permissions to do things we can't grant to users to do.. so the Game Panel can do it for them,  Problem is that if 2 or more servers are starting up we keep getting collisions of them all trying to write EcoMods.dll to that location.  And then then one or more server is stuck with all the dlls expanded in the /Server/ folder and not compiling to the dll because they were told that file was in use.  that leave the file in a state where it will not run and requires someone to go in and delete all the dlls so the server can try to start again.

**Comment by seccombew** [comment]
Fixed a while ago, no longer an issue.
