### ISSUE TITLE
USER ISSUE: Cannot connect to Master Server

### ISSUE THREAD

**Issue by IRDifferent** [StrangeLoopGames/EcoIssues#8654]
**Version:** 0.7.6.2 beta

**Steps to Reproduce:**
Tried to join on my friend via Steam Friends List	

**Expected behavior:**
Should have loaded me into the game

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

No response from master server.
```

**Comment by seccombew** [comment]
Fixed in 7.7
