### ISSUE TITLE
Game Version Number needs to be Displayed on Main Menu or Browser WIndow

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8656]
It is getting harder and harder for players to determine what version they are running - some for get that they opted into beta and cannot understand why they are being told they have the wrong version when trying to access a sever and assume they got the update.  Right now the main way we have to be sure is to ask them to start up a singleplayer game, open server UI and check the version number.  Often they have not seen an update come through and are confused as to whether they are not updated or the server they are trying to join is not updated even though they can see what it says the server version is they also think they are on the same version.  If the version also showed up on the main menu or on the Browser window so they had a quick reference it would save a lot of confusion and time they waste trying to figure it out as they get more and more frustrated

**Comment by elfl0rd** [comment]
client version available in ESC menu...

**Comment by D3nnis3n** [comment]
Closing out, see GDragons message.
