### ISSUE TITLE
[7.6.1] Unclaiming a public/unclaimed plot causes a disconnect crash

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#8662]
Hello.

Trying to unclaim a plot that is already unclaimed/public causes a disconnect crash to the main menu.

Suggestion: Command to unclaim all plots by a player, i.e.:
/unclaimall Gabeux

Thanks!

**Comment by MarjieAVolk** [comment]
A fix for this has already been written, it will be fixed in the next hotfix.
