### ISSUE TITLE
WorldObject UIs that require scroll bars throw exceptions (7.7 staging)

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#8663]
![image](https://user-images.githubusercontent.com/774628/43027958-e025ffc0-8c31-11e8-8eac-219e13294d53.png)

**Comment by MarjieAVolk** [comment]
duplicate of a bunch of stuff, fixed in https://github.com/StrangeLoopGames/Eco/pull/3130
