### ISSUE TITLE
7.6.2 | Deed sale - no refresh ownership of worldobjects

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8664]
As i see - it's critical. You can sold property, then steal items from it =)
![20180721003221_1](https://user-images.githubusercontent.com/4980243/43028805-b9647f0c-8c8a-11e8-8170-202755ead53b.jpg)
![20180721003403_1](https://user-images.githubusercontent.com/4980243/43028806-b984a32c-8c8a-11e8-88fa-268867ca2bf0.jpg)

https://youtu.be/4tVhRDcwalk

**Comment by elfl0rd** [comment]
i sold deed, but all worldobjects in this deed are mine.
i cant grab it, but i can open storages and grab\transfer items
owner can grab it and can open
if owner pickup and place - i lose acces to picked up and placed storage

**Comment by MarjieAVolk** [comment]
Well I've tried this out a few different ways, and it is looking fine every time here.  Does this happen every time for you?  Any idea how to get it to happen again?

**Comment by elfl0rd** [comment]
hm... yes, everytime.
Tried on random internet server - work same.

**Comment by elfl0rd** [comment]
okay, some time later

**Comment by elfl0rd** [comment]
huh, i cant repro for now xD i try it some time, and reopen if happens.

**Comment by MarjieAVolk** [comment]
lol okay, let me know if you see it again 👍
