### ISSUE TITLE
[Client] Load Fuel function for Stone Brazier and Torch Stand doesn’t work

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#8665]
**Version: 0.7.6.2 beta**

**Expected behavior:**
Carried coal or torch should load fuel with right click (as interaction hint shows) 

**Actual behavior:**
For Torch Stand nothing happens. Stone Brazier is switched on/off but not loaded.

**Steps to reproduce:**
Stable function.

![loadfuel](https://user-images.githubusercontent.com/38510829/43029080-f7d2e3ac-8c83-11e8-8d4a-f1b0a9116bb2.PNG)

**Comment by elfl0rd** [comment]
dupe https://github.com/StrangeLoopGames/EcoIssues/issues/7240

**Comment by D3nnis3n** [comment]
Duplicate
