### ISSUE TITLE
Effeiciency and speed skills are not working

### ISSUE THREAD

**Issue by draconious9** [StrangeLoopGames/EcoIssues#8666]
i understand the trees which have been removed and given to everyone no longer have speed or efficiency skill slots. But all efficiency skills and speed skills no longer work. IE: cooking and hewing logs making the beginning of the game unplayable

**Comment by Nicolausi113** [comment]
confirm

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/43104696-1aa458a2-8e87-11e8-83e4-5324c3f94931.png)
I tested this and efficiency skills do seem to be working fine.

Can you please elaborate on your issue/provide screenshots? If you do so, feel free to reopen this.

**Comment by Nicolausi113** [comment]
Version: 0.7.6.2 beta
Actual behavior:
2 logs used for 1 Hewn Log – after skilled to level 4 still the same.

(can’t reopen the issue, I’ m not the author)

![skill](https://user-images.githubusercontent.com/38510829/43129392-9440f53c-8f34-11e8-990d-723dae85b6d1.jpg)
![workbench](https://user-images.githubusercontent.com/38510829/43129421-a49300ba-8f34-11e8-9064-cec60dca87fb.jpg)

**Comment by Nicolausi113** [comment]
As I now figured out, it seems to be restricted to the workbench crafted at campsite. The carpentry  table for example works as expected and also the tool-tip looks different.

![carpentry menu](https://user-images.githubusercontent.com/38510829/43141761-06f50b82-8f57-11e8-9d1d-12653330b7e9.jpg)
![workbench menu](https://user-images.githubusercontent.com/38510829/43141778-11e3d62c-8f57-11e8-956c-ea6f8176db2c.jpg)

**Comment by draconious9** [comment]
When using the crafting bench for goods or even the campfire for food, the efficiency skill and speed skill do not reduce the cost of materials required and/or reduce the time needed to make products/ food
________________________________
