### ISSUE TITLE
USER ISSUE: Menu Stuck

### ISSUE THREAD

**Issue by Jesse-McDonald** [StrangeLoopGames/EcoIssues#8668]
**Version:** 0.7.6.2 beta

**Steps to Reproduce:**
Press tab and escape at the same time, you may have to spam these keys

**Expected behavior:**
the escape menu should open and the mouse should be available, the menu should close the next time escape is pressed	

**Actual behavior:**
the escape menu opens, and never closes, restarting the game is required to close the menu,. an infinite amount of these permanent menus can be created this way

**Comment by MarjieAVolk** [comment]
This will be fixed in the next release 👍
