### ISSUE TITLE
Dead beets cannot be removed

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#867]
Eco 0.5.0

Cannot remove dead beets with either the scythe or pressing E key

![image](https://cloud.githubusercontent.com/assets/6193670/20855796/2dc46838-b967-11e6-9c5b-80ad4dca10a3.png)

**Comment by noblackthunder** [comment]
have you tried to place a block on top of them? as a workaround?

**Comment by newzealdan** [comment]
Shovel removes the dead beets!
And I also notice that shovel harvest beets, as well as pressing the E key!

**Comment by noblackthunder** [comment]
@metachronism is this a bug or working as intended?

**Comment by newzealdan** [comment]
I don't think your meant to be able to pick these with E?

**Comment by MarjieAVolk** [comment]
You need to use the shovel to harvest beets
