### ISSUE TITLE
USER ISSUE: Missing law action - "nothing"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8670]
**Version:** 0.7.6.2 beta

e.g. for allocating based on condition.
if play hours 2 - allocate 2 coin
otherwise - nothing

currently you need use 0 tax or allocate, it's spam to chat...

**Comment by Deantwo** [comment]
A "do nothing" action would be more clear than "allocate 0" to someone yeah.

**Comment by MarjieAVolk** [comment]
That's what 'allow' is, right?  Or is this specifically for periodic actions? 🤔

**Comment by elfl0rd** [comment]
yes, like allow

**Comment by Deantwo** [comment]
A periodic law doesn't have "Allow" or "Prevent".

**Comment by Deantwo** [comment]
Not fixed/implemented.
