### ISSUE TITLE
0.7.7 - you cannot gather tree debris

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8671]
**Version:** 0.7.7.0 beta staging-89185ed9

**Steps to Reproduce:**
no highligt, axe hit does nothing...
![20180721174136_1](https://user-images.githubusercontent.com/4980243/43036602-a3188530-8d0d-11e8-8d93-29a0d7007390.jpg)

**Comment by johnkslg** [comment]
Fixed!
