### ISSUE TITLE
USER ISSUE: you can place campsite stockpile in air

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8672]
![20180721174411_1](https://user-images.githubusercontent.com/4980243/43036621-d2d5751c-8d0d-11e8-92e0-065bf22c11ff.jpg)

**Comment by craig-jong** [comment]
StarterCamp.cs is a good place to start. Just needs to just the normal stockpile's check to make sure it can't be placed if it has nothing under it.

**Comment by Spydarlee** [comment]
Submitted a fix, pending review. 

This also seems to be an issue for most other objects? As far as I can see only the stockpile does a check for ground? I've moved that check to the base WorldObjectItem class and hooked it up to the tiny + small stockpile as well as the starter camp.

Not sure if other objects should be doing this as well, though? As a random example, the crane can be spawned partially over water as well, so I'm guessing most/everything else can as well?

**Comment by mirasrael** [comment]
Probably it is good to make WorldObject itself aware about these things. Like IsGroundRequired or as alternative nullable required ground area for that who should be partially placed on ground.

**Comment by craig-jong** [comment]
Yea, we have a component for this. We'll be doing a larger change in master for this.

For now, this bug is closed for 7.7
