### ISSUE TITLE
0.7.7 new ramp issues

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8674]
you cannot pickup it as single block
![20180721180442_1](https://user-images.githubusercontent.com/4980243/43037169-12a07df4-8d13-11e8-9102-e284dcc5a852.jpg)

no connection to closest blocks
![20180721180511_1](https://user-images.githubusercontent.com/4980243/43037178-245a9a48-8d13-11e8-8a5f-f261ea9cea10.jpg)

- [x] Fix placing preview.
- [ ] Pickup like solid block.
- [ ] Pickup using correct tool.
- [ ] Connection to another blocks.
- [x] Speed bonus.

**Comment by Sekor2600** [comment]
is in 7.7 Staging too

**Comment by elfl0rd** [comment]
And no speed bonus on them.

**Comment by elfl0rd** [comment]
Okay, ramps now return base material
dirt, stone road, asphalt road.

but... if ramps still pickup like different blocks - need balance, you receive 4 road blocks as ~3 price at max eff.
e.g.
1 stone road - 
1.6 stone
0.8 pitch

1 stone ramp - 
4 stone
2 pitch
and return 4 stone road after pickup, equal 
6.4 stone
3.2 pitch

**Comment by elfl0rd** [comment]
In 0.7.7 release, ramps picked up by shovel...
It's not usefull for asphalt\stone ramps!

**Comment by BlazeGuy2** [comment]
Closing as the other other linked issues have been assigned to craig.

**Comment by elfl0rd** [comment]
@BlazeGuy2 you close issue with unique, not resolved problem.
Ramps are NOT connects to closest world blocks.
dirt, stone, etc.
