### ISSUE TITLE
0.7.7 english letters now fat, like russian

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8675]
![20180721173505_1](https://user-images.githubusercontent.com/4980243/43037184-47884b5a-8d13-11e8-9a4c-714c00c86898.jpg)
![20180721173548_1](https://user-images.githubusercontent.com/4980243/43037185-47aa487c-8d13-11e8-9154-f0cab85e73ee.jpg)

**Comment by elfl0rd** [comment]
Looks refer to https://github.com/StrangeLoopGames/EcoIssues/issues/7115 but now english letters is out from place :D

**Comment by BlazeGuy2** [comment]
Dup of #8597.  Currently being looked at for the 7.7 milestone.
