### ISSUE TITLE
Server Crash - Putting Biodiesel into full Skid Steer

### ISSUE THREAD

**Issue by Stephmos** [StrangeLoopGames/EcoIssues#8676]
Steps to reproduce:

1) Fill all Skid Steer slots with dirt. 
2) Remove biodiesel fuel from Skid Steer using non-shovel tool.
3) Put biodiesel back into Skid Steer by right clicking the Skid Steer.
4) Crash

--BEGIN DUMP--
Dump Time
07/21/2018 11:06:42

Exception
Exception: ArgumentNullException
Message:Value cannot be null.
Parameter name: source
Source:System.Core

System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Components.VehicleToolComponent.WorldObjectInteract(Player player, INetObject obj, InteractionMethod method)

--END DUMP--

**Comment by SlayksWood** [comment]
Checked on 0.8.3.0 staging-1066. Wasn't able to reproduce. Seems fixed.
