### ISSUE TITLE
Missing "put items to container" contract target - braziers, furnaces, etc

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8678]
These need to auto fill it, by players!

**Comment by johnkslg** [comment]
It only shows discovered items, could it be the items were not discovered?  No table was created that could make them?

**Comment by johnkslg** [comment]
doh, ok will investigate.  Got the save file?

**Comment by elfl0rd** [comment]
[Storage.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2226543/Storage.zip)

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/43219231-998ace2e-8ffb-11e8-94b8-9f88dda7061b.png)
Loaded your world and verified braziers are showing up in the latest build.
So, whatever was the problem has been fixed in latest.

**Comment by elfl0rd** [comment]
not fixed, you still cannot select brazier inventory as contract target.

If you say "fixed" - try create contract "put coal to brazier"

**Comment by johnkslg** [comment]
ohh ok I get it now.

**Comment by elfl0rd** [comment]
@Kirthos i cannot see any changes... Not in master, not in bleeding_edge...
and you not miss torch stand? :)

**Comment by Kirthos** [comment]
@elfl0rd The fix is in master (not in staging or release) and like other fuel container the torch stand will be able to be selected by contract too.

**Comment by elfl0rd** [comment]
Fixed in master (not in 7.7.2)
