### ISSUE TITLE
[7.6.2] A Eco process is still active after closing eco console

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#8679]
we remark that after closing the eco cmd window, an eco process is still active and use server ressources:

![image](https://user-images.githubusercontent.com/29807119/43041080-ce07c556-8d55-11e8-82ee-2addbeeb64e4.png)

Only way to remove that process is to restart dedicated server , impossible to kill it!

Thats not normal !

**Comment by pamduncan** [comment]
Any chance you still have the webpage open, like laws or voting?

**Comment by Amphysbaenas** [comment]
perhaps one player was still connected, how to know ....
It's still a new problem that need a solution !

**Comment by Myrhaug** [comment]
When closing the server program on our dedicated server, the process should be "killed" automatic (like all other programs).
As for now, the most easy soltion (and this solution is not even easy!) is to restart the server. and then start eco server when windows server is up and running.

**Comment by SeanAtr0n** [comment]
Why is the process named like this? Are you using a separate program to launch it?

**Comment by Myrhaug** [comment]
We use to rename eco.exe

**Comment by Amphysbaenas** [comment]
i confirm that : 
![image](https://user-images.githubusercontent.com/29807119/43096874-b0aaf4f4-8eba-11e8-8c44-9e9e752c83c2.png)
We can host different eco server, and stagging one on our dedicated server.
It's a way to know exactly what process from which iteration use Ram and % proc

**Comment by pamduncan** [comment]
Actually, you are able to run as many EcoServer.exe as you want on one server without having to rename and causing issues and will know which session is running wish.  The .exe name itself will com conflict with multiple instances and that might resolve many issues.  I run many, many instances of EcoServer.exe on my hardware and its very easy to rename the .exe. I could see where this could lead to many problems in running a program when you rename it that way.  It should be shutting down by process id but that is not always the case, often its called by its location and name.  If you would like instructions on setting up multi instances of the same .exe on a server I can walk you though that.  On a windows servers it is very easy.  It would also mean that you would have less problems with updating etc as you do not have to change the EcoServer.exe name with each update
