### ISSUE TITLE
Perf issues - trading items at stores - scales with count of items being traded

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#8680]
Playing on Pams Big World server, 7.6.2,

Lag spikes occur whenever buying or selling large ( > 50 ) amounts of items at a store.

The length of the lag spike seems to vary directly in proportion to the number of items being bought or sold.

Stats read/write is turned on. It appears that the stats engine writes one row per individual item being bought and sold - i.e. 100 items sold = 100 records in the DB.

This may be worth profiling to see if any optimisation is possible.

![image](https://user-images.githubusercontent.com/2173684/43041473-2c674bb8-8da5-11e8-95db-c8b78482d907.png)

**Comment by elfl0rd** [comment]
yes, trade 2000 items occur 3-5s red disconnect circle for me.

**Comment by johnkslg** [comment]
Need to integrate 'count' into purchases rather than repeating the db entry per count

**Comment by LiaungYip** [comment]
This also occurs on starting a crafting job - same thing - one DB entry gets written per item being crafted, causing severe lag if starting a crafting job with a high item count.

Note: May interact with the crafting stats changes in https://github.com/StrangeLoopGames/Eco/pull/3199 :

 > A "Craft" action is only recorded in stats once an item has finished crafting. Among other things, this significantly reduces inaccurate "Craft" stats due to cancelling a project.

This probably fixes the lag on crafting, but 1 DB entry is still getting written per crafted item. That's not ideal from the perspective of DB size as the game world matures. The DB on large servers reaches sizes in the hundreds of MB.

**Comment by gzatravkin** [comment]
Now we have InsertBulk. Make sure that all actions are inserted via bulk (they should be if it's same gameactionpack)

**Comment by gzatravkin** [comment]
Tested, seems like already fixed (it inserts 1 record with count)
