### ISSUE TITLE
[7.6.2] When dropping Dirt from Crane: Server Dump: ArgumentNullException / Linq.Enumerable.Any / VehicleToolComponent.WorldObjectInteract

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8682]
Drop dirt into water.

--BEGIN DUMP--
Dump Time
07/22/2018 20:03:17

Exception
Exception: ArgumentNullException
Message:Der Wert darf nicht NULL sein.
Parameter name: source
Source:System.Core

System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Components.VehicleToolComponent.WorldObjectInteract(Player player, INetObject obj, InteractionMethod method)

--END DUMP--

**Comment by Amphysbaenas** [comment]
i have problem too with excavator , when you dump partially excavator dirt in a stockpile you need to disconnect reconnect to be able to use again excavator to dig again ! perhaps its linked

**Comment by Amphysbaenas** [comment]
+ crash on client side with excavator ( linked )?

**Comment by johnkslg** [comment]
Couldnt get this to happen:
![image](https://user-images.githubusercontent.com/3536496/43111625-e8e6ab42-8ea6-11e8-89f1-6b7a53f88dcb.png)
Any more details?

**Comment by johnkslg** [comment]
Fixed! In 8.0
