### ISSUE TITLE
[7.6.2] New icon for Bear Supreme (to differ from Prepared Meat)

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8683]
Please create a new icon for Bear Supreme, mybe simply put tiny Bison overlay on it. Currently it is same as Prepared Meat, what it makes hard to seperate in stores e.g.

**Comment by RobertMangano** [comment]
New icon for bear supreme
actual size 64x64
![bear supreme.jpg](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/212f2cfa-1108-4ec4-8880-e1be1493ebd6)

512x512
![bear supreme2.jpg](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/898d2ffc-50e5-436d-b747-f448c363d759)

**Comment by RobertMangano** [comment]
committed this change to staging

**Comment by beastyn** [comment]
Check please, do not see changes
![bandicam 2020-08-12 14-55-26-952](https://user-images.githubusercontent.com/27898520/90002405-0daabb80-dcac-11ea-8f0a-c097a6702441.jpg)

**Comment by RobertMangano** [comment]
![image.png](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/159f0615-61e3-4cef-a40a-3cf204264cbe)

after updating svn bear supreme already has new icon assigned? not sure why it is not appearing?
