### ISSUE TITLE
FEATURE REQUEST: Quality of Life inventory management

### ISSUE THREAD

**Issue by carsonbarlow** [StrangeLoopGames/EcoIssues#8686]
**Version:** 0.7.6.2 beta

**Steps to Reproduce:**
Open an storage unit that has access to another storage unit.  And put multiple stacks of any item in one unit.  While holding down the shift key, move one stack from one unit to another.

**Expected behavior:**
The rest of the same item move to the destination automatically as room permits.

**Actual behavior:**
Just the one stack is moved.

**Comment by GophTheGreat** [comment]
Moving to our suggestions repository: https://github.com/StrangeLoopGames/EcoSuggestions/issues/478
