### ISSUE TITLE
[7.6.2] New icon for Fur Pelt (to differ from Leather Hide)

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8687]
Please create a new icon for Fur Pelt. Currently it is same as Leather Hide, what it makes hard to seperate in stores e.g.

**Comment by Amphysbaenas** [comment]
i agree !

**Comment by rachaelfosner** [comment]
CLOSED AND FIXED. New icons made for both, 
SUCK IT NERDS; gimmie that elk.

**Comment by keegan-o** [comment]
Um, I plugged these in, but I'll let rachael take it since she made the icons! Thanks Rachael!

![image](https://user-images.githubusercontent.com/14983165/43168574-adc26112-8f52-11e8-8648-71d14d7e04d4.png)
