### ISSUE TITLE
[7.6.2] Law feature request Important for economy and world management

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#8688]
We need a tool to calculate population in law:
-number of plant
-number of animals
-number of every things

Exemple:
We want to pay a player with treasury if he kills and harvest a turtoise if total number of turtoise in the world is >= 800 (law for animals regulation)

So:
OnPlayerAction When attempting to Harvest Where (Species is Turtoise) +
Condition
If Numeric comparison "Population of" Turtoise >= 800
Then Allocate
Currency Name of currency Amount
Otherwise Prevent (or Tax or anything else)

It's important to manage world and quantity of things!

![image](https://user-images.githubusercontent.com/29807119/43075247-83728dec-8e80-11e8-9138-f6b43d335358.png)
On the screenshot you can see that we can not calculate population number and allocate an amount of money from treasury of course

**Comment by Deantwo** [comment]
Your old bug report isn't good enough?
See: #8114

**Comment by Myrhaug** [comment]
@Deantwo Im the one who proposed a law function about it.
But it is still an good idea to have this.

**Comment by Deantwo** [comment]
But why make a report about the same thing again?

**Comment by Myrhaug** [comment]
I did not.
Our avatars is the same but we are 2 diffrent people. Look on my name and reporters name.

**Comment by Deantwo** [comment]
Ok, i feel stupid now. 😓

**Comment by MarjieAVolk** [comment]
Hahaha this doesn't happen every day.  Okay closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8114
