### ISSUE TITLE
USER ISSUE: Electric Stamping Press does not have Storage

### ISSUE THREAD

**Issue by netray92** [StrangeLoopGames/EcoIssues#8694]
**Version:** 0.7.6.2 beta

**Steps to Reproduce:**
Open up the menu. No storage. Have to collect things yourself

**Expected behavior:**
No storage tab, so it's not connected to chests etc.	

**Actual behavior:**

**Comment by craig-jong** [comment]
dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/8547
