### ISSUE TITLE
Conditions for 'number of players' law value

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#8695]
Eg. "number of players where (play time > 2 hours)"

**Comment by Deantwo** [comment]
Also a condition for "hours since last online", that would be very useful for punishing players for being offline for many hours.

**Comment by Deantwo** [comment]
I am not seeing this v7.7.1, did it not get implemented yet?
Or is it just not as intuitive to made as `number of players where (play time > 2 hours)`?
