### ISSUE TITLE
Exceptions when running workorder tutorial

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8696]
Probably an errant recipe UI still on there.
![image](https://user-images.githubusercontent.com/3536496/43098031-bd4418e6-8e72-11e8-8092-53db504d9d47.png)

NullReferenceException: Object reference not set to an instance of an object
UI.WorkOrderUI.Update () (at Assets/UI/Scripts/ItemOrSlot/WorkOrderUI.cs:44)

**Comment by GophTheGreat** [comment]
Can't reproduce. Closing.
