### ISSUE TITLE
7.6.2 Food Tutorial did not appear after starving

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#8698]
Also did not appear after foraging

**Comment by johnkslg** [comment]
Could not repro, Walker can you help with this?
Nick is referring to the popup sequence, not the 'food' task button.
Nick just to be sure can you clarify what happened? You need to click the 'Food' tutorial before the sequence shows up, did you do that?

**Comment by BlazeGuy2** [comment]
Can't seem to reproduce it.
