### ISSUE TITLE
Plants have Delete but no Harvest animations

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8699]
Make the plant parts move towards the player

**Comment by keegan-o** [comment]
Also, this requires code support. The current code does not succeed at calling 'Harvest' vs. 'Delete'-- it just always calls 'Delete' (that's part of why I made delete animations first). Assigning Craig, who can assign whoever might know how to fix that?

**Comment by SeanAtr0n** [comment]
plant harvests just get sent as chunk updates, there is no info on who harvested

**Comment by keegan-o** [comment]
duplicate now
