### ISSUE TITLE
No fish in the sea?

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#870]
No fish in the sea?
It would be great if there were, that you could fish for off the coast easily early in the game for meat. Just like IRL (in-real-life), perhaps fish can have a very long life cycle and slow maturity rate like the snapper here in the pacific (10-20 years to maturity/legal size, and can live over 100 years). It is foreseeable that you would have to fish further from the shore, further out in the ocean mid-game. Or perhaps, the fish start off large and as they are overfished the catch gets smaller (catching younger fish).
Opportunity for fish farming in late-game (which can be fairly polluting if done on the cheap IRL).
Also opportunity for fresh-water fish like salmon and trout.

Please and thanks,
Dan

**Comment by MarjieAVolk** [comment]
Thanks for the ideas, I'll save your notes :)  We may look into adding more underwater content in a future version!
