### ISSUE TITLE
Wall wouldnt connect to pillar

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8700]
![image](https://user-images.githubusercontent.com/3536496/43100609-b74070a4-8e7a-11e8-88aa-cd4c014ffc50.png)

**Comment by keegan-o** [comment]
If a wall connects to a pillar, there will be a gap between the two-- it doesn't look very good-- any easy solution involves just making a new builder type, basically. I don't think we want to go down the rabbit hole of making every type respond to every other type, it would slow all builders down a lot. Some pillars like this one though perhaps I will alter to fill up the whole meter space, then they could be set to connect. But others like the Lumber Pillar shouldn't ever connect to walls. That would also be a bit weird, having certain pillars connect and others not connect, see what I mean?

**Comment by keegan-o** [comment]
I'm thinking what I'll do is make a new form called 'Post', so posts will be much skinnier like the current Lumber Pillar, and Pillars will be thick pillars that fill up the meter space and can connect to walls. But I think this falls more under feature creation than bug fixing, and there are other much worse builders to fix like roof builders.

**Comment by keegan-o** [comment]
This also goes under the category of 'need better systematic support for rotated block forms' so we can just give players rotations on anything they would likely want to rotate, like thin walls.
