### ISSUE TITLE
Stockpiles filled w/ stacked lumber don't cull inside

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#8707]
On my laptop this mesh is the longest draw call in the scene (3ms)
![image](https://user-images.githubusercontent.com/774628/43108647-b1572440-8e97-11e8-874a-283cb8c375c4.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/43168902-be221a7e-8f53-11e8-8044-d2d4395a783a.png)
Added a fallback cube for when lumber stacked 4 is surrounded on all sides by solids.
