### ISSUE TITLE
Break the technological (technical, production) chain.

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#8712]
Game version 0.7.6.2

**Bug** - Break the technological (technical, production) chain between the "Assembly Line" and the "Electric Machinist Table".

 **_Description_**: after the assembly of the "Line Line" is made and installed in the required place "Electric Machinist Table", further production of any devices (including lasers, trucks, excavators, table lamps and so on) is not possible. The reason is simple and trivial - for all further production chains, ELECTRICITY is required, and it is something to produce something! Because the production of the most simple generator ("Combustion Generator") requires "Electric Machinist Table" which requires ELECTRICITY for its work !!! And the player can not produce electricity due to the fact that it is NOT POSSIBLE to PRODUCE even the simplest generator (what to say about the "Solar Panel" (produced on the "Electronics Assembly" which also needs to be produced on the "Electric Machinist Table" and which also works on electricity) or about "Wind Turbine" (which is produced on the "Robotic Assembly Line" which also needs to be produced on the "Electric Machinist Table" and which also requires electricity)). Simply put, a "dead loop" like "electricity is needed to produce electricity". That is for the release of ANY electricity generator on electricity is required for the "Electric Machinist Table" to produce the simplest generator, and the player can not produce electricity by ANY way !!!

---------- Original message/Russian language ----------------

Версия игры 0.7.6.2

Баг - Разрыв технологической (технической,производственной) цепочки между "Assembly Line" и "Electric Machinist Table". 

Описание : после того как на "Assembly Line" произведен и установлен на требуемое место "Electric Machinist Table" дальнейшее производство каких-либо устройств ( в том числе лазеров , грузовика , экскаватора , настольных ламп и так далее) не возможно. Причина проста и банальна - для всех дальнейших производственных цепочек требуется ЭЛЕКТРИЧЕСТВО , а его-то как раз производить НЕЧЕМ !!! Потому что для производства самого простого генератора ( "Combustion Generator" ) требуется "Electric Machinist Table" который для своей работы требует ЭЛЕКТРИЧЕСТВО !!! А электричество игрок произвести НЕ МОЖЕТ из-за того что НЕ ВОЗМОЖНО ПРОИЗВЕСТИ даже самый простой генератор ( что говорить о "Solar Panel" ( производится на "Electronics Assembly" которую также надо произвести на  "Electric Machinist Table" и которая также работает от электричества ) или о "Wind Turbine" (которая производится на "Robotic Assembly Line" которую также надо произвести на  "Electric Machinist Table" и которая также требует электричества )) . Проще говоря получается "мертвая петля" типа "для производства электричества требуется электричество". То есть для выпуска ЛЮБОГО генератора электричества на требуется электричество для "Electric Machinist Table" чтобы произвести самый простой генератор, а электричество игрок НИКАКИМ способом произвести НЕ МОЖЕТ !!!

**Comment by elfl0rd** [comment]
return steam engine back to provide mechanical power.
Replace combustion engine to steam engine on combustion generator and rename it to steam generator (remove petroleums from accertable fuel list)
make new combustion generator, accepts only fuel.

**Comment by craig-jong** [comment]
The steam generator was moved to produce electricity as a stopgap because we're not going to shove random new art into a release as a hotfix. There is not currently a blocking issue here.

**Comment by elfl0rd** [comment]
> The plan is to return steam generator to mechanical and add a converter.
Super!

**Comment by Rambo99** [comment]
In 0.7.6.3 bug NOT FIXED !!!

**Comment by elfl0rd** [comment]
facepalm. It's not bug.
Read messages above.
