### ISSUE TITLE
USER ISSUE: Growing Trees

### ISSUE THREAD

**Issue by EiKiDa** [StrangeLoopGames/EcoIssues#8713]
**Version:** 0.7.6.2 beta

**Steps to Reproduce:**
Trees are growing too slowly. 100-150 hours in real life whilst staying in game.

**Expected behavior:**
100-150 real life hours in and out game.

**Actual behavior:**
100-150 real life hours IN game.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#480
