### ISSUE TITLE
Remove exception usage from acceptable cases

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8716]
Makes debugging challenging when exceptions are happening as an expected and handled case.
I know this is a pattern used in a lot of APIs, but it would be nice as a general practice to keep exceptions to unexpected problems.

**Comment by MarjieAVolk** [comment]
I think the solution nick was using on stuffed elk is fine - that is, have our own exception subclasses for our own classes of expected exceptions (which we should do anyway), and then people can just toggle off breaking for those.

**Comment by MarjieAVolk** [comment]
That's pretty standard practice afaik

**Comment by MarjieAVolk** [comment]
@Nanders can you just commit the change that you have on stuffed elk?

**Comment by Nanders** [comment]
Yeah I'll clean it up and commit that
