### ISSUE TITLE
[7.6.3] Currency exchange interface is not updating currencies that can be traded.

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8719]
**My account:**
![client_exchange](https://user-images.githubusercontent.com/35509188/43168777-52021236-8f53-11e8-9ade-5e705eefbe66.PNG)

**Exchange owner:**
![owner_exchange](https://user-images.githubusercontent.com/35509188/43168756-42e9b1be-8f53-11e8-9ee4-c3d2c82cc96f.PNG)

[Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2225637/Game.zip)

Should say I'm trading my credits for the minted currency.  Instead it says I'm trading for the owner's credits (Testalpha).

**Comment by johnkslg** [comment]
Fixed in PR
