### ISSUE TITLE
Stuck between door and wall

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#872]
Stuck between door and wall, can't close door or move. /unstuck

Eco 0.5.0

![image](https://cloud.githubusercontent.com/assets/6193670/20856741/bb30bf46-b97b-11e6-9c3a-919bc014bdf6.png)

**Comment by MarjieAVolk** [comment]
More generally, it's easy to get stuck inside world objects, for example if you log out while standing on one and then log back in.  /unstuck does not usually work in this situation.

**Comment by MarjieAVolk** [comment]
This is definitely not fixed and is constantly a problem for me
