### ISSUE TITLE
[7.7.0] Highlight of the cactus turns bright green when looking at it from it's center

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8721]
**Looking at cactus towards the bottom:**
![cacti_normal77](https://user-images.githubusercontent.com/35509188/43171093-6a476e40-8f5d-11e8-8641-bfe0cfef0917.PNG)

**Looking at cactus higher up:**
![cacti_notnormal77](https://user-images.githubusercontent.com/35509188/43171108-7e0aacc6-8f5d-11e8-864f-18cee0cd4183.PNG)

**Comment by GophTheGreat** [comment]
Could not reproduce. Closing.
