### ISSUE TITLE
Tree leaves changing shape

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#8723]
I built some treehouses around tree leaves. 
But later on the leaves will change shape. They don't seem to grow larger. Just change shape. Maybe the direction of the branch's leaves are randomly changing for some reason.

I can tell, because the treehouse walls, used to be flush with the leaves, and later are not.
![treemoving](https://user-images.githubusercontent.com/7343272/43172274-74ace35a-8f63-11e8-8cf9-30747c1954a2.png)

**Comment by metachronism** [comment]
this is intended, trees grow over time.  I double checked and the leaf rotation is fixed and doesnt change either
