### ISSUE TITLE
7.6.3 - Excavator picks up fuel from vehicles including itself

### ISSUE THREAD

**Issue by zytukin** [StrangeLoopGames/EcoIssues#8725]
In dig mode with the left mouse button held down, if the excavator's bucket contacts it's body it will remove it's own fuel.

When picking up stuff from trucks, if there isn't enough stuff to fill the excavators capacity then it will also remove the truck's fuel.

**Comment by SeanAtr0n** [comment]
fixed in https://github.com/StrangeLoopGames/Eco/pull/3167
