### ISSUE TITLE
USER ISSUE: Incompatible Version

### ISSUE THREAD

**Issue by IIcRaShII** [StrangeLoopGames/EcoIssues#8726]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
We open the server 3 Days ago and i dont know about any Updates, i cant join our server and this message show up

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Verbindung fehlgeschlagen</size>

Incompatible version.
```

**Comment by elfl0rd** [comment]
update server

**Comment by BlazeGuy2** [comment]
7.6.3 was released today, you need to update your server to run the game.
