### ISSUE TITLE
Need filter/search for "Choose Contract Destination" target picker

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8729]
It is hard to find the right target for Contract Clause "Put Item in Container". There are hundreds of Stockpiles, Chests, Bookshelfs, Steam Trucks and others on our server.

It whould be very helpful to get an option to filter the list by type of target (e.g. "Show only Stockpiles") and to get an input field for a fulltext search over all existing targets (like the Item selector at the Stores "Add Item").

Thios ist the view:
![image](https://user-images.githubusercontent.com/22961978/43194078-d5ba6dcc-9001-11e8-985b-2f4e1dec9b79.png)

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 develop 279

https://images.zenhubusercontent.com/47210472/09afea57-dd1d-4f7b-9433-a26c70e2c27b/04ce006a38f359abb2a6bc2cb2a58a68.mp4
