### ISSUE TITLE
Wrong Icon for Cast Iron Stove (same as Stove)

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8730]
Wrong icon for Cast Iron Stove (same as Stove)

![image](https://user-images.githubusercontent.com/22961978/43199621-d733a5c2-9012-11e8-97b9-045db3524477.png)
![image](https://user-images.githubusercontent.com/22961978/43199626-df1e9166-9012-11e8-8499-85e12fb63528.png)

**Comment by keegan-o** [comment]
lol, whoops. This got lost in the tides of time. Fixed in master.
