### ISSUE TITLE
excessive ram use 

### ISSUE THREAD

**Issue by smerecz** [StrangeLoopGames/EcoIssues#8731]
so talking with Pam and was told for 4 users we should not be chewing up 13 gigs of  ram on a server and she told me to post it here  so the devs can look at it if a dev can send me an email i will share the game file with them on  on dropbox

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/8702

**Comment by BlazeGuy2** [comment]
Closing as a dup
