### ISSUE TITLE
Lets add a light source to the starter camp

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8734]
Can make it a candle with a built in supply of tallow to last quite awhile.  Will make nights much more pleasant those first couple days and will be a nice easy intro to fuel and such as well.

**Comment by elfl0rd** [comment]
bad idea as i see, lot of tallow from new players...

I prefer "torch stand" with burning torch and two in their inventory.

**Comment by elfl0rd** [comment]
@D3nnis3n added. "Internal" light and torch stand. Maybe can be closed :)

**Comment by D3nnis3n** [comment]
Added.
