### ISSUE TITLE
Actions your Craft where object is(....)

### ISSUE THREAD

**Issue by techop2000** [StrangeLoopGames/EcoIssues#8735]
The law parameter for numeric comparisons of actions your Craft currently adds up all the times you attempted to craft an item. If possible, it should instead add up all the times you successfully crafted an item. 
example:
You pass a law saying you can only craft 50 torches using the actions your craft where item is torch.
If a player cues up 50 torches, then cancels them before they are made, then they will not be able to cue up 50 torches again to actually make them. 

This came about because we backed our minted currency with torches then passed a law limiting how many torches a player could make. A few players ordered multiple torches, (some players before, and some after the law was passed) then cancelled their order. the law calculated their attempts thus making it impossible for them to order any more. They were left without the ability to craft any torches even though they didn't have any.

The second issue with this parameter is that, so far as i can tell, there is no way to have it start counting from the moment the law was passed. Instead it always counts crafting attempts from server start.
example: For the first 10 days the server is active, a player can craft as many torches as they want. 
on day 10 you want to pass a law saying "from now on" players can only craft 5 more torches" in its current state, the game would prevent anyone who made torches before from creating the 5. 
I guess a solution would be to add another parameter that starts the count on law passed.

**Comment by MarjieAVolk** [comment]
Hm, yes you are right, that does sound like an issue.  It shouldn't be tooooo hard to communicate a project being blocked in the middle because it's become illegal 🤔 So I think I can just move this, as you suggest.

With regards to the second issue, this is how you would do it:
```
if your craft actions where (item is torch and time performed (days) > law passed time (days)) > 50
prevent
```

**Comment by MarjieAVolk** [comment]
In 8.0, projects will become blocked based on whether they are legally allowed to craft the next item, rather than being blocked on creation.  The "Craft" action will not be applied until an item is actually crafted.  Thanks for your suggestions!
