### ISSUE TITLE
Scythe Jigglin' Fever

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#8736]
![jiggle](https://user-images.githubusercontent.com/6262198/43226314-5f9c7eb4-9010-11e8-8364-e85e0fdb93a3.gif)

**Comment by keegan-o** [comment]
Not able to repro, I think this is a matter of not having the shader hack for locking FPS tools independent of FOV on the local machine?

**Comment by Nanders** [comment]
This is still happening in bleeding edge, idk if we want to reopen

**Comment by keegan-o** [comment]
Only if we need to hotfix it? I would assume medium pris are not hotfix priority.
