### ISSUE TITLE
Multiple currencies with the same name.

### ISSUE THREAD

**Issue by techop2000** [StrangeLoopGames/EcoIssues#8737]
Currently in the game, you can mint 2 currencies with the exact same name. We decided to make a world wide currency called "bitz". Initially we backed it with gold. Later we decided to make one backed by torches then make a law limiting torch production. We called this new currency "bitz" as well. Our world now has to different currencies called "bitz". I'm not sure but i would assume that would cause problems when trying to use the /pay command. It also adds much confusion when people are trying to set up stores, exchanges, and contracts, as they aren't sure which currency to use. 

I have 2 requests:
1. Don't allow worlds to mint more than one currency with the exact same name
2. Add an Admin Chat Command to completely remove a specific currency. 

we have a small amount of gold backed bitz that none of us ever intend to use that we would just like gone.

**Comment by Kirthos** [comment]
I have a working fix for having 2 currency with the same name. 
That can occurs if the first mint was destroyed.
I'm not sure about adding a command to remove a currency. I don't know if it's wanted.

**Comment by elfl0rd** [comment]
@D3nnis3n can you look? maybe this and linked issue is fuxed, PR merjed.

**Comment by D3nnis3n** [comment]
Fixed.
