### ISSUE TITLE
USER ISSUE: LAN Bug

### ISSUE THREAD

**Issue by XxGruffuddxX** [StrangeLoopGames/EcoIssues#8738]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
1.Create a LAN game 
2.Have a friend try to join the game
3.Repeat step 2 till you're blue in the face

**Expected behavior:**
Been able to join the game your friend is playing on

**Actual behavior:**
will load the game world to 75% and then force send you to the main screen, or you will make it into the game and the game will time out the connection to the host.

**Comment by BlazeGuy2** [comment]
Speak with Pam on discord, open up a different issue if you find the root cause.
