### ISSUE TITLE
Wood carts very broken

### ISSUE THREAD

**Issue by combatbanana** [StrangeLoopGames/EcoIssues#874]
Have experienced multiple bugs with wood carts.
- Wheeling cart between transition of position 0 and 1000 will cause player screen to go blank 
![image](https://cloud.githubusercontent.com/assets/20417839/20879210/916ced70-bb37-11e6-9ec0-93e1b5613ccc.png)

- Carts can get stuck in ground easily with no apparent reason as to why, and not be able to be moved.  The wheels simply spin but the cart remains stationary
![image](https://cloud.githubusercontent.com/assets/20417839/20879195/75e07928-bb37-11e6-81be-56ce92cbab45.png)

- Trying to wheel a cart down underground caused cart to instantly teleport above ground and then become stuck (isn't possible to dig it out - it just slowly floats down a little but still stays above the ground)
![image](https://cloud.githubusercontent.com/assets/20417839/20879175/62731170-bb37-11e6-9b96-749cd4c9e7c3.png)

**Comment by sukar42** [comment]
also moving it near a dirt wall will make it hover.(with the efficiency set to 0 on the dirt the cart will be stuck there )
