### ISSUE TITLE
USER ISSUE: Hewn Log upgrades not working?

### ISSUE THREAD

**Issue by Tyrequis** [StrangeLoopGames/EcoIssues#8742]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
I've upgraded my hewn log skills with skill points but the log to hewn log ratio hasn't changed and it still takes 6 seconds to craft, even though the efficiency is at rank 5.

**Expected behavior:**
Decreased the time to craft hewn logs and increased the yield of hewn logs.

**Actual behavior:**
Nothing changed

**Comment by Deantwo** [comment]
Are you using a Workbench?
The skill only affect the Carpenter Table recipe.

**Comment by elfl0rd** [comment]
@D3nnis3n as intended.

**Comment by D3nnis3n** [comment]
Even if intended i do not really like this. I'll keep it open for the developers to decide what to do with it.

**Comment by elfl0rd** [comment]
You do not like the fact that you can work quickly and effectively only on a special workbench? :)

**Comment by D3nnis3n** [comment]
Sorry, i did not realise the carpentry table also offers hewn logs to craft. Closed.
