### ISSUE TITLE
7.7.0 Cannot sell wooden wheel in store

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8743]
Can manipulate other items, just not the wooden wheel

https://youtu.be/IGpylKL0aUA

**Comment by johnkslg** [comment]
This is because they want to buy 'zero'.  Could add a notice to it though like sold out.

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/43288568-26fc5f34-90dd-11e8-81fe-4d81de1b703e.png)
Added this to make it clearer
Fixed!
