### ISSUE TITLE
[7.7.0] Bug with some of the economy viewer text overlapping in the currency and debt boxes

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8745]
![econviewer](https://user-images.githubusercontent.com/35509188/43233006-a9201024-9028-11e8-8710-4d5e00c8c842.PNG)

**Comment by BlazeGuy2** [comment]
Like this fixed before the next release, but not in a rush for it ATM.

**Comment by MarjieAVolk** [comment]
Fixed
