### ISSUE TITLE
Tax Law creating Exception Violation

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8753]
--BEGIN DUMP--
Dump Time
07/25/2018 19:31:27

Exception
Exception: Exception
Message:A MultiAtomicAction failed in the middle of execution. Which is bad. Error message: You cannot afford to pay a tax of <b><link="Currency:31306fa5-739d-4dd4-a524-d82e574998a5"><style="Currency">2 Pammy</style></link></b>
Source:Eco.Core

System.Exception: A MultiAtomicAction failed in the middle of execution. Which is bad. Error message: You cannot afford to pay a tax of <b><link="Currency:31306fa5-739d-4dd4-a524-d82e574998a5"><style="Currency">2 Pammy</style></link></b>
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Components.CraftingComponent.CreateWorkOrder(Player player, Recipe recipe, Int32 quantity)

--END DUMP--

**Comment by Deantwo** [comment]
Game version?
Picture of the law in question?
