### ISSUE TITLE
Error with compression script naming convention when trying to upload new build to SLG site

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8757]
[![Screenshot from Gyazo](https://gyazo.com/ba256adc4bf3cfa7e4dc9d04821d2bca/raw)](https://gyazo.com/ba256adc4bf3cfa7e4dc9d04821d2bca)

[![Screenshot from Gyazo](https://gyazo.com/bf6d7b7ef011bb756d9ffd1649480309/raw)](https://gyazo.com/bf6d7b7ef011bb756d9ffd1649480309)

**Comment by BlazeGuy2** [comment]
Fixed in the PR above
