### ISSUE TITLE
USER ISSUE: New Update and game wont start

### ISSUE THREAD

**Issue by Ivonator** [StrangeLoopGames/EcoIssues#8769]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
I created a new world. While loading this, the Comuter got frozen.
Restatring the game, Error Message popped up

**Expected behavior:**
Play

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host
```

**Comment by WeaselDog** [comment]
We are not able to reproduce this in the latest version so it appears to be fixed.

Thanks for your report!
