### ISSUE TITLE
My sales didnt show in the welcome message

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8772]
![image](https://user-images.githubusercontent.com/3536496/43346954-3d3caa58-91a8-11e8-843b-247f5e0565ee.png)

**Comment by metachronism** [comment]
See also: #1615
welcome message will quickly get polluted/huge, might be better to have this generalized log component, that world objects can log events to such as purchases/sales or other important events

**Comment by johnkslg** [comment]
Make stores have a tab logs all the sales and to whom.

**Comment by johnkslg** [comment]
Closing this for now, we can do a differnet approach
