### ISSUE TITLE
USER ISSUE: Spamming escape - Screen black

### ISSUE THREAD

**Issue by Officialy** [StrangeLoopGames/EcoIssues#8773]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
Spam ESC

**Expected behavior:**
Just open the escape menu over and over

**Actual behavior:**
Turns the screen black with the escape menu even after escaping the menu. You can move around ingame, but stil see the escape menu

**Comment by Deantwo** [comment]
Same if yiu spam the `G` key. Opens another dialog underneath the existing dialog, over and over again.
Only way to escape is by pressing `ESC` (no pun intended).

**Comment by MarjieAVolk** [comment]
Hm darn I thought this was fixed (https://github.com/StrangeLoopGames/EcoIssues/issues/7807)

**Comment by MarjieAVolk** [comment]
Oh wait, I mentioned there that the fix isn't released yet.  Okay, fixed in 8.0
