### ISSUE TITLE
Property overlay is confusing

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#8774]
![image](https://user-images.githubusercontent.com/18184943/43349612-e43f8da4-91b5-11e8-89bb-afaa650882fd.png)

White line is ambiguous for who owns the area. We should consider making it thinner, removing it, or putting in inside the property.

**Comment by elfl0rd** [comment]
Can you make it vertical? It ideal solution :)

**Comment by metachronism** [comment]
I dont think its ambiguous, its a border - no one owns it

we could double the resolution of the property map, and then make the line half width, or some other solution

**Comment by elfl0rd** [comment]
Corrently, two problems.
1) confusing new players, "claim 5x5 or 7x7?"
2) problem with seeing different claims if they have same color.

Vertical border fix both issues.

**Comment by Conchipedia** [comment]
once i had worked it out that i Don't own the white line (simple test is to walk on the white line, claim name bottom left goes off) all i then do i work out where my claim ends and place a Marker there like Rubble or something that i own so it shows me a physical border (normally i do this in the corner inside where the white lines meet)

**Comment by SeanAtr0n** [comment]
Meta fixed this
