### ISSUE TITLE
USER ISSUE: Cannot build a door.

### ISSUE THREAD

**Issue by SkinnyC** [StrangeLoopGames/EcoIssues#8777]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
Cannot use the carpentry table to build a door, cause the table needs to be contained in a room

**Expected behavior:**

**Actual behavior:**

**Comment by elfl0rd** [comment]
you do not need door to make room.

**Comment by BlazeGuy2** [comment]
Room detection doesn't need a physical door object, just a 2x1 walkway.
