### ISSUE TITLE
Screw Press

### ISSUE THREAD

**Issue by TheKye** [StrangeLoopGames/EcoIssues#8778]
hey guys, just a bit of conflict in the code relating to the items craft-able in the screw press.

IronPlate - Requires Module "Machinist Table" it doesn't work and doesn't recognise the machinist table as a module, this prevents the crafting regardless
Piston - Requires Module "Machinist Table" it doesn't work and doesn't recognise the machinist table as a module, this prevents the crafting regardless

i have fixed both issues by removing the need for the machinist table, but it seems like in the vanilla files that there may be some code missing from the machinist table for it to also act as a module.

Thanks guys.

**Comment by GophTheGreat** [comment]
Module seems recognized now, closing.
