### ISSUE TITLE
High ping results in lag/desync fo player and server as a whole

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8784]
High pings >300 and even more evident >500 not only cause lag and desync  for the player connected to a server but its notable that when that player with a high ping joins a server it causes lag across the server and desyncs are experience by many players.   

I know this is not always something that a game can accommodate for as some high pings are the nature of internet location to server, hardware and other factors outside of the game. 

There have been requests for Eco to have what games like empyrion have and that would be a config setting where the admin of the server can decide what ping level might be too high for the server and set it so that if a player exceeds that ping when they log in the server will not log them in and tell them their ping is too high, or if the ping goes high during game play they can be auto kicked and renew tehir connection

**Comment by KyeEco** [comment]
although this is an issue, i run servers from australia and we have people connect from austria and canada with no lag issues at all, generally those with high ping are based off their network activity and the quality of their connection line, so limiting this is a great idea especially for such high of a ping, but i remember that slg had introduced a system to combat this by making most actions client side then updated to the server to reduce action lag and overall lag, so my guess here may be a server overload? it could have something to do with the server side itself and not the players, but i cant say thats a certainty either

**Comment by johnkslg** [comment]
High ping shouldnt affect other users on the server, something must be weird there. 
Making high priority because its causing problems on large servers.

**Comment by metachronism** [comment]
Need more info.  High ping of single users will not cause any of the issues that are described.  The worst that can happen is laggy appearing physics updates for objects that client is simulating (like if they are cutting down a tree).

Dropping priority for now - we can institute a max ping setting on the server.
