### ISSUE TITLE
Build a house quest didn't work properly

### ISSUE THREAD

**Issue by lunadragnstar** [StrangeLoopGames/EcoIssues#8785]
On a new world, I got to the "build a house" quest. When I finished the house, the quests box in the top left corner disappeared, the pop-up instructions did not appear and the updated navigation in the bottom left corner didn't update. 

I can not see the nutrition, skills or house values. I can't even open the skills tree using Z. 

I also tried /eat command, and /skillpoints xxx commands and nothing updated.

**Comment by lunadragnstar** [comment]
I started a new world and go to the house quest, I finished the house but the quest didn't mark the quest as completed and progress like it should.

**Comment by johnkslg** [comment]
Can you send me your save game and/or images of your house?
Game.eco is the file I need.

**Comment by lunadragnstar** [comment]
I don't have the game file anymore, so I created a new world and tried again, but it worked perfectly.

**Comment by johnkslg** [comment]
Closing, reopen if you can make happen again.
