### ISSUE TITLE
Hewn Logs problems

### ISSUE THREAD

**Issue by sukuyan-fallen** [StrangeLoopGames/EcoIssues#8786]
![20180729074756_1](https://user-images.githubusercontent.com/41862912/43366123-fdec6cd0-9305-11e8-87b2-6be27f10da99.jpg)
![20180729074800_1](https://user-images.githubusercontent.com/41862912/43366124-fdfadbbc-9305-11e8-9758-ee22b38bf828.jpg)
![20180729074820_1](https://user-images.githubusercontent.com/41862912/43366125-fe0794ba-9305-11e8-8935-3f0a7cfff86f.jpg)
![20180729074851_1](https://user-images.githubusercontent.com/41862912/43366126-fe1405f6-9305-11e8-9999-3f0659cc415d.jpg)

When trying to make hewn logs in my carpentry table the time is at 0s and no matter how many I try to make it doesn't start the work order. In my workbench it still shows max time and max logs needed to make them even though I have maxed out the skill points for both of the hewn logs skills. Not sure when or how this happened. Last time I played it was working properly now I can't make anymore hewn logs because I don't want to use my workbench due to it using max resources, and I can't use my carpentry table because it won't make them at all. I included screenshots to help show what I mean.

**Comment by Deantwo** [comment]
Wasn't this fixed in the 7.6.1 hotfix 17/07/2018?

**Comment by BlazeGuy2** [comment]
@sukuyan-fallen should be fixed on 7.6.3.  Are you running that version?

**Comment by BlazeGuy2** [comment]
Reopen if issue resurfaces.
