### ISSUE TITLE
USER ISSUE: Pickaxe always looks like stone

### ISSUE THREAD

**Issue by carsonbarlow** [StrangeLoopGames/EcoIssues#8787]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
equipe a metal pickaxe
Have someone look at you

**Expected behavior:**
The pickaxe in your hand should look metal

**Actual behavior:**
The pickaxe in your hand looks stone

**Comment by GophTheGreat** [comment]
I'm getting the correct models for all pickaxe models in both first- and third-person. Do you need another player looking at you to reproduce this?

**Comment by beastyn** [comment]
Yeap, there is a problem with models in the 3s person view modw.
We actually can make it more diverse
stone pickaxe
![bandicam 2019-06-21 14-50-24-704](https://user-images.githubusercontent.com/27898520/59914566-169b5680-9434-11e9-8b8f-832171e962d1.jpg)
steel pickaxe
![bandicam 2019-06-21 14-50-36-415](https://user-images.githubusercontent.com/27898520/59914588-1e5afb00-9434-11e9-86b2-5a0915888875.jpg)

**Comment by SlayksWood** [comment]
fixed in 0.9.0
