### ISSUE TITLE
[7.7.0] Korean word appears as square in main manu

### ISSUE THREAD

**Issue by Butterflycat0** [StrangeLoopGames/EcoIssues#8788]
![image](https://user-images.githubusercontent.com/41241968/43368140-75318a72-9393-11e8-93a6-30c383854ad2.png)
![image](https://user-images.githubusercontent.com/41241968/43368143-83221ba6-9393-11e8-9881-9b1855fe4c69.png)

**Comment by Nanders** [comment]
I just fixed this in SVN
