### ISSUE TITLE
Signs no longer changing font size with code

### ISSUE THREAD

**Issue by X-ITT** [StrangeLoopGames/EcoIssues#8789]
Sign after saving at 180%:
![image](https://user-images.githubusercontent.com/11493473/43368594-bb9b6f84-932d-11e8-9d84-c024e5e43c90.png)
Sign after saving at 10%:
![image](https://user-images.githubusercontent.com/11493473/43368617-10546382-932e-11e8-8e8d-6fd409c29024.png)

**Comment by BlazeGuy2** [comment]
Tested it on 7.6.3.  Text actually grows larger at 10% than 180%.

**Comment by seccombew** [comment]
This may be by design.

**Comment by keegan-o** [comment]
The way it works is the size is proportional to anything else on the sign. Basically the sign text always expands to fill the sign, but within that your size codes will increase the size relative to anything else on the sign. Or @BlazeGuy2 does that happen when you have both 10% and 180% on the same sign?

**Comment by keegan-o** [comment]
Also much has been shifted around with these in master compared to the build shown, so check stuff out in master.

**Comment by keegan-o** [comment]
Going to close for now because I think we want signs to be as readable as possible by default. You should still be able to use size to customize them how you wish within the given space.
