### ISSUE TITLE
USER ISSUE: Invisible truck

### ISSUE THREAD

**Issue by OrangeStone903** [StrangeLoopGames/EcoIssues#8790]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
cut a tree
cut the truck
he's invisible

**Expected behavior:**

**Actual behavior:**

**Comment by seccombew** [comment]
Need more info

**Comment by BlazeGuy2** [comment]
Can you make a video showing this happen?

**Comment by OrangeStone903** [comment]
I will do it. meanwhile, I found how to remove the invisible trunk, It must unload the chunk where it is, and it will disappear for good

**Comment by OrangeStone903** [comment]
the bug has disappeared o_O
problem resolved!
