### ISSUE TITLE
USER ISSUE: Invisible Blocks

### ISSUE THREAD

**Issue by Rex-Terra** [StrangeLoopGames/EcoIssues#8792]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
Just mine, and at some Point Blocks dont vanish anymore.

**Expected behavior:**
Blocks should vanish if i mine them, and be visibel if i place them.

**Actual behavior:**
Blocks dint vanish if i mine them, and blocks become invisibel if i place them.

**Comment by seccombew** [comment]
Should be fixed in 7.7+
