### ISSUE TITLE
Can't open storages and machine

### ISSUE THREAD

**Issue by sisimonis** [StrangeLoopGames/EcoIssues#8794]
It arrived to a friends one week ago, and today it was my turn.
Now, we can't open storages, we can't open chest, machines as machinist table or electronic table ...
Sometimes we can open one, and in the list of other storages, all appears "public storage".
We supress game, install again, try to fix but impossible. And now we just can't do anything bcs it's destroying all the game play.
Ty

**Comment by seccombew** [comment]
Needs more investigation, repro case

**Comment by BlazeGuy2** [comment]
Need specific item names, game version, game save.

**Comment by BlazeGuy2** [comment]
7.5 is an older version, current live is 7.6.3.  Closing for now, impossible to address bug without a consistent way to reproduce it.  Reopen if it occurs on the current live version.

**Comment by sisimonis** [comment]
ok ...
