### ISSUE TITLE
[7.6.3] Extreme memory consumption (>12GB after 1h)

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8795]
After I expand RAM in my Box from 8 to 32GB I recognised an RAM issue: While playing a server world, the 'commited private memory' for the ECO.exe Windows process ist growing up to 12 GB after about 1-2 Hours (and still growing slowly). 
The Memory will not be released after leaving the world and staying at the ECO welcome screen.

Before expansion RAM, I some times recognized heavy HDD activity. Today I'm sure this was caused by Windows while paging RAM.
Here are some screenshots as evidence for that effect. I don't know how to discover more details to help you.
Hoping you feel this as an issue as well. (What are the RAM requirements für ECO?)

After Start ECO and joining this world (4km size):
![image](https://user-images.githubusercontent.com/22961978/43372138-d3e9c336-939d-11e8-9821-0b6be912471f.png)

Task Manager / Processes
![image](https://user-images.githubusercontent.com/22961978/43371869-587f99b2-939a-11e8-96b5-c0b1a3e63154.png)
TaskManager / Details
![image](https://user-images.githubusercontent.com/22961978/43371887-9881a6b8-939a-11e8-867a-d8bb2312786e.png)
ProcessExplorer (from Sysinternals) / Performance Graph
![image](https://user-images.githubusercontent.com/22961978/43371891-a37925dc-939a-11e8-9bfd-04474a46a8d2.png)
ProcessExplorer (from Sysinternals) / Performance 
![image](https://user-images.githubusercontent.com/22961978/43371912-e16330c2-939a-11e8-8258-045156370198.png)

**Comment by seccombew** [comment]
Fixed in 7.7+

**Comment by SeanAtr0n** [comment]
Sounds like your view range is probably set to max in game?

**Comment by Voosle** [comment]
@SeanAtr0n Yes it is. But it should be possible with 32GB i7 CPU and 1060/6GB GPU or not?
