### ISSUE TITLE
USER ISSUE: Red Tool Background on usable tool

### ISSUE THREAD

**Issue by StealthFundip** [StrangeLoopGames/EcoIssues#8797]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
1. Use a tool until broken (red background)
2. Replace the tool with a newly crafted tool in the same slot

**Expected behavior:**
The background for the new tool should be blue.

**Actual behavior:**
The tool background is unchanged and remains red.

**Comment by BlazeGuy2** [comment]
Does the tool still in the broken state despite the red background?

**Comment by StealthFundip** [comment]
No, the tool works as expected with correct calorie cost per swing.  The only issue is the background remaining red.

Swapping the tool to a different slot, then back to the original slot corrects the background issue, but isn't a permanent fix.

**Comment by elfl0rd** [comment]
Dupe https://github.com/StrangeLoopGames/EcoIssues/issues/2544

**Comment by BlazeGuy2** [comment]
Ah, it is a dupe, closing.
