### ISSUE TITLE
The absence of the "storage" tab from "Electric Stamping Press" and "Electric Planer"

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#8799]
Game version - 0.7.6.3
The absence of the "storage" tab from "Electric Stamping Press" and "Electric Planer".
![20180730120945_1](https://user-images.githubusercontent.com/1098421/43394418-5e5d843e-9403-11e8-8ca2-8dc1864e75f2.jpg)
![20180730134611_1](https://user-images.githubusercontent.com/1098421/43394436-6b9029cc-9403-11e8-841c-961b796f156b.jpg)

**Comment by craig-jong** [comment]
Not blocking, already fixed in master.

It will be fixed in the next release.
