### ISSUE TITLE
Web UI Map: loading behavior when switching to a different map layer is confusing

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#880]
When I switch map layers while the animation is still running for the previous layer, I see the stop watch and progress bar still continuing as usual; meanwhile the map usually gets reset to white and then gets populated with some data from the new layer, but the new layer is not animated.  Then once the animation reaches the end of the selected time period and starts over, the map will be animated correctly the second time through.

From this behavior it would be easy for a user to think there has been no change on this layer over time.  I would imagine what we want is a loading whirligig while the map layer is being loaded.

**Comment by SeanAtr0n** [comment]
Fixed
