### ISSUE TITLE
The absence of manufactured items on the "crafting" tab of "Electric Lathe"

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#8800]
Game version - 0.7.6.3
The absence of manufactured items on the "crafting" tab of "Electric Lathe".

![20180730122647_1](https://user-images.githubusercontent.com/1098421/43394661-2ae5afd6-9404-11e8-99d8-2478cc6526b9.jpg)

**Comment by Nicolausi113** [comment]
in v7.7.2 still the same!

**Comment by elfl0rd** [comment]
Just move "Steel Axle" from Electric Planer to Electric Lathe, to compare as Lathe and Shaper.

**Comment by Rambo99** [comment]
> Just move "Steel Axle" from Electric Planer to Electric Lathe, to compare as Lathe and Shaper.

Steel Axle ??? What it is ?!?! This is not in the game. Screenshots please.

**Comment by elfl0rd** [comment]
@Rambo99 

> Steel Axle ??? What it is ?!?! This is not in the game. Screenshots please.

Not in the game? Lol. in 0.7.7.2

![default](https://user-images.githubusercontent.com/4980243/47253232-5818d380-d459-11e8-861e-1e39ef0a843d.png)
![default](https://user-images.githubusercontent.com/4980243/47253261-7b438300-d459-11e8-9b4b-8415a471e110.png)
![default](https://user-images.githubusercontent.com/4980243/47253269-84345480-d459-11e8-902e-574e033a3088.png)

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/52335629-e8ccec80-2a13-11e9-8ece-8b9bbace348d.png)
