### ISSUE TITLE
Better connection message then 'Failed to connect to master server'

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8801]
Seems like lately the generic message for all failed connections is "Failed to connect to master server".  This makes players think that the SLG server is down, whether the server is not up, whether there are port issues, firewall issues, av blocking etc., and its hard to work through a support issue when the player believes they are told that the SLG 'master server is offline.  Even just a 'Failed to connect" message would be better and then the connection issue could be handled through troubleshooting the various causes then the generic failure always crediting the 'master server' as the failed connection.  I know that its impossible for the server to report what exactly caused the connection to fail every time but when it says that the failure is to connect to the master server its confusing for the player who just wants the master server to be back online so they can connect and does not want to trouble shoot an issue since they believe they are being rightly told the master server is down.

**Comment by MarjieAVolk** [comment]
I glanced at this, and looks like that message is coming from a timeout from the master server, so it is an accurate message.  I'm guessing the master server isn't sending any kind of indication on whether it can't find the server requested or what the deal is -- maybe the master server can send an ack or something, so the client can distinguish between the master server being down and the requested server being down / slow?

**Comment by metachronism** [comment]
There is some loose end connection failures that still display as "master server did not respond", such as singleplayer crashing and some other things, I think.

**Comment by metachronism** [comment]
Looked at this again, and am pretty sure its fixed with the token-connection change made earlier.

**Comment by metachronism** [comment]
(so fixed for 7.7+)
