### ISSUE TITLE
German: Bug beim Steckenbleiben

### ISSUE THREAD

**Issue by VinylScratch1** [StrangeLoopGames/EcoIssues#8802]
German: Hi, ich habe des öfteren ECO gespielt und beim Abbauen von Stein, oder beim Schaufeln von Dirt, musste ich oft feststellen, dass ich stecken bleibe  und immer wenn ich stecken bleibe, dann kommt ein Rauschen und am Ende des Rauschens stöhnt der Charakter. Siehe Video:

https://www.youtube.com/watch?v=-9-fT3wyIjk

Ab 3:14 Minute

**Comment by Nicolausi113** [comment]
The noise is an indication that you stuck. If you wait a few seconds, you will be automatically unstuck.

Das Rauschen habe ich auch bemerkt seit v7.6.x wenn man eingeklemmt ist. Kurz abwarten und man wird frei.

**Comment by GophTheGreat** [comment]
Not a bug. Closing.
