### ISSUE TITLE
Web map time slider doesn't show current position

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#8803]
Should show current position on the bar
![image](https://user-images.githubusercontent.com/774628/43429379-e78a6682-9417-11e8-89fb-c3f9a5954c0a.png)

Also would really like to be able to change current time by clicking on the timeline and adjust speed to go faster than 1/-1

**Comment by j3fffff** [comment]
repeat https://app.zenhub.com/workspaces/eco-5908208d250b520221f72735/issues/strangeloopgames/ecoissues/7848
