### ISSUE TITLE
USER ISSUE: Computer Lab speed benifit

### ISSUE THREAD

**Issue by Veanules** [StrangeLoopGames/EcoIssues#8804]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
Craft Computer Lab

**Expected behavior:**
this benifit should be in "industry engeneering speed" skill

**Actual behavior:**
it is in "electronic engeneering speed" skill

**Comment by WeaselDog** [comment]
For the new specialty we have setup, Computer Lab is produced with Electronics labor. I am going to close because this is now intentional.
