### ISSUE TITLE
7.7.0 Storage Devices create multiple inventory lines for each placing

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#8806]
Version: v0.7.7.0-beta-staging-89185ed9

Steps to reproduce:
Place any storage device or fuel device, remove it and place again.  

Actual behavior:
This will create multiple inventory entries in all devices nearby. If the device is removed finally, the inventory lines stay alive until game new start.

Expected behavior:
Inventory lines should be created one time and disappear if the device is removed.

![mult2](https://user-images.githubusercontent.com/38510829/43476336-a442e246-94f8-11e8-8b90-44b15635f9c0.jpg)

**Comment by MarjieAVolk** [comment]
Fixed in the next major release
