### ISSUE TITLE
USER ISSUE: Objects dissapear when entering Kitchen

### ISSUE THREAD

**Issue by z64555** [StrangeLoopGames/EcoIssues#8809]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
Something about my kitchen makes all objects (chests, furnature, doors, etc.) visually dissapear when I enter it. Leaving the kitchen sometimes works not but always. The floor is T2 materials while the walls and ceiling is T1 materials, not sure if that has anythign to do with it.

Objects included are a Mill, a Brick Oven, An Icebox, a Stone Brazier, a Table, and a Chair.

**Comment by z64555** [comment]
Restarting the client's game seems to temporarily resolve the issue, but other clients have reported similar strangeness with the area.

**Comment by GophTheGreat** [comment]
Closing for now.
