### ISSUE TITLE
USER ISSUE: Furniture Glitch

### ISSUE THREAD

**Issue by ThatEngie** [StrangeLoopGames/EcoIssues#8812]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
1. Make a piece of furniture specific to a room (bedroom, kitchen, etc.)
2. Place in a spot
3. Remove furniture
4. Place back down

**Expected behavior:**
It should have given the skill point bonus again

**Actual behavior:**
Instead it didn't give them back

I did this with the Wooden Bed, not sure if it happens to any other furniture

**Comment by SlayksWood** [comment]
merged with #12780
