### ISSUE TITLE
Web interface: "Humans" graphs not accessible in graphs interface.

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#8814]
On the Graphs interface, the word 'Humans' is shown in 3px font, and can't be expanded to show the usual range of Humans-related graphs.

![image](https://user-images.githubusercontent.com/2173684/43507033-5310c7d2-95af-11e8-816c-13b5b54b3e6b.png)

**Comment by rainfarmer** [comment]
fixed
