### ISSUE TITLE
[7.6.3] Looks ugly when place dirt ramp on top of stone (is not blocking cart)

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8815]
![image](https://user-images.githubusercontent.com/22961978/43517607-a60229c0-9589-11e8-9512-c917420a287d.png)

![image](https://user-images.githubusercontent.com/22961978/43517622-ac21fa10-9589-11e8-9e48-4c594ce0a60f.png)

**Comment by SeanAtr0n** [comment]
in 7.7 ramps become blocks so guess this is fixed
