### ISSUE TITLE
USER ISSUE:Disappearing Lift

### ISSUE THREAD

**Issue by lueckspilz** [StrangeLoopGames/EcoIssues#8816]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
No cause found only random
Just used the elevator in multiplayer 

**Expected behavior:**
The elevator should stay in its vertical tunnel under the engine

**Actual behavior:**
It disappears und moves through the  world and I can only see the cables but my friend can still see and use it.
After a reconnect its often fixed.

![screenshot 1](https://user-images.githubusercontent.com/19553792/43518648-020586ce-958d-11e8-9232-43240399281d.jpg)
![screenshot 2](https://user-images.githubusercontent.com/19553792/43518649-0223247c-958d-11e8-873d-571b736beaf5.jpg)

**Comment by SlayksWood** [comment]
It's related with Zero point. Merged with #12292
