### ISSUE TITLE
Authorizing a stockpile for withe-list leaves it inaccessible

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#8817]
Version: 0.7.6.3 beta

I tried to authorize a large stockpile for both players by withe-list, but was not accepted. After this try the stockpile appeared red and inaccessible.
As I realized then, the stockpile was partially on public unclaimed ground, but could not claim the missing plot nor give up the overlapped claims  ( hoping for meteor impact )

![whitelist](https://user-images.githubusercontent.com/38510829/43535867-5c3f4c5a-95bb-11e8-8bc9-9d2267ebf33e.jpg)

**Comment by Nicolausi113** [comment]
I finally checked it to unclaim the surrounding plots and could proceed. But I think the major problem is the strange behavior with authorization white-list, why did it go red?

So it makes no more sense to upload the current game state, but I’m sure I can create a test-game exact with this situation. Just tell me to do so!

**Comment by Nicolausi113** [comment]
I now can deliver one more cognition – it seems to be no more problem with v7.7.-bleeding.
I tried this situation with a tiny stockpile placing on public ground and tried to authorize to players by whitelist. It was not accepted, was not red, and a message appeared: “You can only edit this” (or similar).
So I think this post can be forgotten and closed!

**Comment by johnkslg** [comment]
Ok great! Yeah weve been fixing auth a lot. Thanks for the report
