### ISSUE TITLE
Water effects look buggy

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8818]
Water can be one of the most graphically beautiful parts of the game, will be worth the time to polish the effects so they dont look janky like this:
![animx](https://user-images.githubusercontent.com/3536496/43545153-f0610496-9589-11e8-8d5a-e89de562955f.gif)

**Comment by keegan-o** [comment]
This is a problem with the builder for spawning the effects.... builders can't look more than one block beyond themselves so it's very difficult/impossible to come up with something that detects waterfalls that doesn't also end up in places like this. We may need new functionality for spawning effects or a new builder type that can look beyond one block (for use only in special situations where we aren't trying to do anything complex, like this one) if that's at all feasible. @metachronism Any thoughts on that? @johnkslg As far a quick fix, I could scale down or nix this effect but then waterfalls would have smaller or no effects, any preference there?
