### ISSUE TITLE
Funny flat textures on corn

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#882]
![image](https://cloud.githubusercontent.com/assets/3536496/20992669/7f3b3134-bc9a-11e6-9497-fea39391c94b.png)

**Comment by metachronism** [comment]
needs normal map

**Comment by D3nnis3n** [comment]
They still look to me like that. But probably i just don't get what is the issue. @elfl0rd Could you make me a screenshot of the fixed view to compare?

**Comment by elfl0rd** [comment]
Not fully flat for me
![default](https://user-images.githubusercontent.com/4980243/49986222-0fc0f200-ff80-11e8-8830-ffb0da945775.png)

**Comment by D3nnis3n** [comment]
I don't see a difference, lol. Probably because it's dark in your shot.

**Comment by elfl0rd** [comment]
Okay, for now it's looks better? :D 
![default](https://user-images.githubusercontent.com/4980243/51084360-21d9b000-1739-11e9-91e0-a4657b6a4834.png)
![default](https://user-images.githubusercontent.com/4980243/51084361-2aca8180-1739-11e9-83ec-31b31649e25b.png)

**Comment by D3nnis3n** [comment]
Yeh, it indeed does. Thanks!
