### ISSUE TITLE
[7.6.3] Bug with Selling stuff at store that I'm authorized at

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8820]
Want to sell 10 iron bars at sean's store on Stuffed Elk.  Don't have the option to make the purchase, probably because I'm authorized on his property.
![store_cantbuy](https://user-images.githubusercontent.com/35509188/43548460-c8218e70-9592-11e8-8bb6-617528c22c1a.PNG)

**Comment by BlazeGuy2** [comment]
Should have the trade button appear

**Comment by wolfgangmeyers** [comment]
@johnkslg @craig-jong is anyone currently looking at this? If not, I can dig into it.

**Comment by johnkslg** [comment]
Players should not be able to buy at other players stores. Bug here is that they shouldn't be able to change quantities, and should be able to change prices. This might not repo anymore with new store

**Comment by johnkslg** [comment]
@wolfgangmeyers all yours

**Comment by johnkslg** [comment]
I think you fixed this all @mirasrael ?>

**Comment by mirasrael** [comment]
With new auth logic if you authorized on property you will have full full access to store just like owner. So still no option to buy anything (like owner can't buy anything from himself). But you can get it from storage directly :)

**Comment by mirasrael** [comment]
Regarding 
> In addition to this, if the person de-authorizes you in an attempt to fix it, you don't get the trade button back until you disconnect and reconnect, or they break the table and re-place it.
It was fixed

**Comment by johnkslg** [comment]
Fixed!
