### ISSUE TITLE
[7.6.3]Bug with cutting down trees

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8823]
Neon Green ran into this issue with trees disappearing as you cut them down while spamming e.

https://youtube.com/watch?v=vgnUurTGhcA&feature=youtu.be

They seem to occasionally reappear when the world reloads.

**Comment by D3nnis3n** [comment]
Happens on Linux / windows and 7.8.5: https://github.com/StrangeLoopGames/EcoIssues/issues/10122

**Comment by elfl0rd** [comment]
Maybe https://github.com/StrangeLoopGames/EcoIssues/issues/4434 happens with same reason.
