### ISSUE TITLE
Claimed property but coloring didnt update

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8827]
![image](https://user-images.githubusercontent.com/3536496/43554824-93bc4b84-95ab-11e8-8fd1-8c106c8cb49e.png)
I just claimed the ground below me. The property popup on the left displays correctly, but I cant see the land claim.

**Comment by johnkslg** [comment]
Here's the game file if it helps

[Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2251525/Game.zip)

**Comment by SeanAtr0n** [comment]
is your property color green? can't see the outline in that image

can you reproduce this behavior reliably?

**Comment by johnkslg** [comment]
Not easily, but fooling around as I test other stuff it seems to happen after awhile reliably enough.  I can call you over if I see it again.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/10286
