### ISSUE TITLE
Cursor still remained on screen after interacting with Escape Menu

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#8829]
Open Escape Menu => press escape to close => cursor will remain, but you're controlling as if you're looking.

**Comment by MarjieAVolk** [comment]
Was this in editor, or in the built game?

**Comment by MarjieAVolk** [comment]
Just checked out release build, and it looks fine.  I'm assuming you saw this in the editor.  The editor has some cursor issues because Unity has some "helpful" different cursor behavior in the editor.  So something like this is alarming only when seen in a build.
