### ISSUE TITLE
USER ISSUE: Minus skillpoints (-2.147.484.000)

### ISSUE THREAD

**Issue by z4bbi** [StrangeLoopGames/EcoIssues#8830]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
1. Connect with the server
2. Play a bit 
3. Having some trouble with the acces to a stockpile (it is public but nobody can use it not even the owner - still there but atm not the main problem)
4. Trying around with commands
5. giving it up and play on
6. realising that i can't skill anything....

**Expected behavior:**
Some skillpoints or anything. And a changing amount of skillpoints, when I'm giving me some via command

**Actual behavior:**
Instead I have -2.147.484.000 skillpoints and can't change it

**Comment by Kirthos** [comment]
I'm working on it. 
I suppose he give himself too many skill point and the number overflow in the UI.

**Comment by D3nnis3n** [comment]
Closing as fixed.
