### ISSUE TITLE
Property is initialized in parallel, can result in duplicate plots getting created

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8832]
Keegan managed to get this problem on his machine:
https://cdn.discordapp.com/attachments/344168599507697674/474393887239176192/unknown.png

I suspect its a race condition, where multiple threads are calling 'GetOrCreatePlot' at the same time. 
Should probably change this to a ThreadSafeDictionary which has an atomic GetOrAdd, instead of ConcurrentDictionary, which does not.

For bonus points we should see if there are any more bad uses of ConcurrentDictionary like this

**Comment by MarjieAVolk** [comment]
Fixed
