### ISSUE TITLE
USER ISSUE: Digging planted bluberry bush.

### ISSUE THREAD

**Issue by ZebZ** [StrangeLoopGames/EcoIssues#8836]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
Get a excavator. place a blueberry bush, try to dig the dirt underneath the bush with the excavator. Boom value gets null.

**Expected behavior:**
The bush should be put in the excavator's inventory or be deleted when excavated.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: ArgumentNullException
Message:Värde får inte vara null.
Parameter name: source
Source:System.Core

System.ArgumentNullException: Värde får inte vara null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Components.VehicleToolComponent.WorldObjectInteract(Player player, INetObject obj, InteractionMethod method)</size>
```

**Comment by BlazeGuy2** [comment]
Dup of #8690, fix will be in next major release.
