### ISSUE TITLE
Wednesdsay and Tuedsay

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#8838]
![image](https://user-images.githubusercontent.com/6262198/43614443-52d7a07e-9668-11e8-960c-2fe5d3988b08.png)

**Comment by Deantwo** [comment]
You mean it is typos?

**Comment by mirasrael** [comment]
Fix provided

**Comment by elfl0rd** [comment]
@Nanders need fix on a crowdin https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#51033
