### ISSUE TITLE
quit broken in master

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#8840]
Tried to quit the built game, nothing happened... hit continue instead and got this popup after entering the world:

![image](https://user-images.githubusercontent.com/774628/43624394-f15d6fde-969b-11e8-9434-c882aae6c0d2.png)

which did let me quit

**Comment by mirasrael** [comment]
Wasn't able to reproduce on staging. Please, provide more detailed steps.

**Comment by Spydarlee** [comment]
Wasn't able to reproduce this on master either.

**Comment by metachronism** [comment]
closing as no repro
