### ISSUE TITLE
[7.6.3]Bug With Cactus

### ISSUE THREAD

**Issue by NeonGreeny** [StrangeLoopGames/EcoIssues#8842]
I found that looking at a cactus seems to bug things out I'm not sure if it is a 1 off kind of thing or a staying bug. (It only happens when holding a axe.)

![20180803211216_1](https://user-images.githubusercontent.com/42076022/43661639-4caee4e0-9763-11e8-92c7-2dfedd38f86a.jpg)

**Comment by Nanders** [comment]
This is an art bug, no?

**Comment by GophTheGreat** [comment]
Could not reproduce. Closing.
