### ISSUE TITLE
I am not authorized on my own property

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#8846]
Happened after syncing master, so might be a migration issue.  I can pick up blocks on my property, and everything else says it is mine and I'm authorized, but I can't access world objects at all, says I'm not authorized

**Comment by techop2000** [comment]
I had this issue with an elevator. For me it was because one side of the elevator was off of my property. claiming the property next to it gave me access again.

**Comment by johnkslg** [comment]
Fixed!
