### ISSUE TITLE
USER ISSUE: Wateranimation

### ISSUE THREAD

**Issue by EiKiDa** [StrangeLoopGames/EcoIssues#8850]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
I worked with my excavator in creative mode and than it just glitch around and destoried near blocks. Water came in and i put earth on the water. But the animation of flowingwater is just there.
![20180804152250_1](https://user-images.githubusercontent.com/40717821/43676957-d002a2ae-97fa-11e8-9fc7-a509bb1915d8.jpg)
**Expected behavior:**
No animation of flowing water

**Actual behavior:**
There is still the animation of flowing water.

**Comment by seccombew** [comment]
Fixed in 7.7+
