### ISSUE TITLE
issues connecting to web client or trying to make laws 

### ISSUE THREAD

**Issue by rsdworker** [StrangeLoopGames/EcoIssues#8851]
i have host with eco on it but however i noticed when i click laws in game - its opens to my computer but however when i go to web client (make laws) its does not work - i cant log in 
so i am unsure if its bug or server host has issues? or config issue

my world name is rsd earth - (i will open up to public shortly)

**Comment by rsdworker** [comment]
my host is GTXGaming.co.uk

**Comment by MarjieAVolk** [comment]
In what way does it not work?  Are you seeing this error? https://github.com/StrangeLoopGames/EcoIssues/issues/7990

**Comment by rsdworker** [comment]
yeah  and to give you a what was problem in game - when i want create or vote leader - i click on law button and its opens to local files on my computer but however this hasnt happened to me before
also other way around when i try to propse law from web - i get same issue as error #7990  - red bar without words in even i have cleared the laws means unable to create laws or vote leader

**Comment by MarjieAVolk** [comment]
Oh strange - so it opened up your file explorer.  Never heard that one before.  What file path does it open you to?  I wonder if this is a firewall or something doing this.

**Comment by rainfarmer** [comment]
For explorer issue, follow this bug report: https://github.com/StrangeLoopGames/EcoIssues/issues/8942

For empty red bar issue, follow this bug report: https://github.com/StrangeLoopGames/EcoIssues/issues/7990
