### ISSUE TITLE
Can not reconnect to server after getting dropped w/ error msg

### ISSUE THREAD

**Issue by NataSpawN** [StrangeLoopGames/EcoIssues#8854]
3 users were on the server and with no warning were dropped due to the following error...

Login token changed.

Please see the notepad attachment for the full log.
[ECO Error (Login Token Changed) - 080418.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2260062/ECO.Error.Login.Token.Changed.-.080418.txt)

**Comment by seccombew** [comment]
Likely due to steam going down for a moment. @rainfarmer can we add more tolerance to Auth.

**Comment by metachronism** [comment]
dupe of #8835
