### ISSUE TITLE
Teleported Off Map While Traversing Dirt Ramp in Steam Truck

### ISSUE THREAD

**Issue by z64555** [StrangeLoopGames/EcoIssues#8855]
Version: 0.7.6.3 beta

Possibly related to #7715, I was traveling down a dirt ramp in my Steam Truck when suddenly it was teleported across the map and about 2KM up in space... with ME in it!

I managed to back to the spawn area with /unstuck, but my truck was left in space. (If only it was loaded with some explosives we could've used it to blow up the meteor...)

I don't see any object that may have caused the issue to happen, except for maybe a birch tree that I had recently cut down.

**Comment by SlayksWood** [comment]
Checked on 0.8.3.0 staging-1066. Wasn't able to reproduce. Seems fixed. May be It was related to animals. If it happens again please reopen and provide log files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
