### ISSUE TITLE
USER ISSUE: Broken Electric Stamper

### ISSUE THREAD

**Issue by gust0357** [StrangeLoopGames/EcoIssues#8860]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
Open Electric Stamper menu

**Expected behavior:**
Electric Stamper should have a Storage button and should connect to storage inventory

**Actual behavior:**
No button. No connection. Can't process items in the Electric Stamper

**Comment by elfl0rd** [comment]
@D3nnis3n fixed long time ago.

**Comment by D3nnis3n** [comment]
Indeed.
