### ISSUE TITLE
USER ISSUE: Contract options lacking

### ISSUE THREAD

**Issue by gust0357** [StrangeLoopGames/EcoIssues#8862]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
Contract board

**Expected behavior:**
Should be able to include all crops in harvest job. Re-planting should be an option. Permission on land

**Actual behavior:**
Several crops are missing. Actions are limited in contract system.

**Comment by Deantwo** [comment]
I belive this is fixed in the next update already.

**Comment by seccombew** [comment]
Potentially dupe/already fixed.

**Comment by johnkslg** [comment]
I think fixed?  @mirasrael check if its got the right crops listed

**Comment by mirasrael** [comment]
This requests include more than just crops. I added plants without seeds (like Beans) to the list.
But nothing about re-planting and permission on land.

**Comment by johnkslg** [comment]
Permission on land should be working, overriden in ShouldOverrideAuth, is that not working? 
Replanting is a great extra option to add, wouldnt be too hard either.

**Comment by mirasrael** [comment]
May be qualify this part of issue as suggestion? (in EcoSuggestions)

**Comment by johnkslg** [comment]
Yeah can leave for later.
Is the auth working?

**Comment by mirasrael** [comment]
It working only on server. So you can perform actions, but object highlighted in red. I already fixed this, but there also problem with highlight update because check performed asynchronously. So needs more coding.

**Comment by mirasrael** [comment]
OK. Now I also fixed highlighting :)

**Comment by mirasrael** [comment]
@gust0357 can you please move part related to "Re-planting should be an option" to EcoSuggestions?

**Comment by johnkslg** [comment]
Marking fixed for now, please add other part to suggestions as its a good one!
