### ISSUE TITLE
License Plate crashing servers/games

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8863]
- License plates seem to take as much text as you can stuff to them, apparently pages of text and people copy and paste in pages of text and then anyone tried to read the plate crashes the server.   Think we could get a limit on how much text a license plate can have?

**Comment by johnkslg** [comment]
Should include a pass on other passed in text blocks to ensure capped lengths.
We will eventually need to make this part of the basic security of all RPCs.

**Comment by craig-jong** [comment]
fixed in above PR
