### ISSUE TITLE
USER ISSUE: failing to connect

### ISSUE THREAD

**Issue by MrCrowley20** [StrangeLoopGames/EcoIssues#8864]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**

**Expected behavior:**
expect to load in a saved game

**Actual behavior:**
failed to establish connection no response from remote host

**Comment by seccombew** [comment]
Need more info.

**Comment by SlayksWood** [comment]
If it happens again, please reopen and provise log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
