### ISSUE TITLE
USER ISSUE: Can't Get in any server

### ISSUE THREAD

**Issue by Thoomana** [StrangeLoopGames/EcoIssues#8865]
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2263407/error.log)

**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
I just try to get to any server and then the game crashes. Always.

**Expected behavior:**

**Actual behavior:**
It just crash, i unninstall the game, and reinstall it, but it keep crashing. I searched solutions for the problem but nothing works.

**Comment by seccombew** [comment]
Need more information

**Comment by SeanAtr0n** [comment]
could you send us your log file from here? (can paste into explorer)
`%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

**Comment by Thoomana** [comment]
Yes, Here it is.

2018-08-06 19:41 GMT-03:00 Sean Ater <notifications@github.com>:

**Comment by SlayksWood** [comment]
If it happens again, please reopen and provise log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
