### ISSUE TITLE
USER ISSUE: Kicked, then could not reconnect

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#8868]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Verbindung fehlgeschlagen</size>

Login info could not be verified. Our auth servers may be down.

<size=60,00%>Timeout für Vorgang überschritten</size>
```

**Comment by rainfarmer** [comment]
Is this a consistent error?
Sometimes this error is from Steam being down, you can check here: https://steamstat.us/
We will be adding in a special error for when steam is down.
