### ISSUE TITLE
 Just a small Glitch with Objectives window (very low priority i would say)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#8872]
**Version:** 0.7.6.3 beta

As you can see below when you type your Objective it is right up against "Online" status
![snap2340](https://user-images.githubusercontent.com/29383891/43788127-9211cae4-9a64-11e8-9780-6b793d6fff2e.png)
But if you type a space before typing objective it looks much neater
![snap2341](https://user-images.githubusercontent.com/29383891/43788168-ae2f7f3c-9a64-11e8-9cd8-7868951351c7.png)

**Comment by MarjieAVolk** [comment]
Ah yeah, the spacing got reset on all tables due to an earlier change, seems I missed a table when adding it back in.

**Comment by MarjieAVolk** [comment]
Fixed in the next major release
