### ISSUE TITLE
USER ISSUE: sometimes getting stuck and then falling sound kicks in just climbing a single dirt block

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#8874]
**Version:** 0.7.6.3 beta

this is sort of hard to explain, i think its due to the new physics of the players, i can try and jump straight up or even diagonally onto another dirt block that is **ONLY** one block difference, the player gets stuck and then the falling sound kicks in and i hear myself land (all of this is just on top of a single block of dirt) and then i can move again, this i have noticed more as i have a world that has blown up from the meteor and the world is full of craters, so i have to jump around a lot more than normal.

**Comment by SeanAtr0n** [comment]
fixed in 7.7
