### ISSUE TITLE
Finish ramp conversion

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#8876]
Still need to migrate old ramps for 7.7 so they convert to an appropriate grid of ramp blocks or ppl will be pretty unhappy when their roads turn into:
![image](https://user-images.githubusercontent.com/774628/43796359-e731c1b8-9a38-11e8-9043-37f975cd9b06.png)

Also spawn road seems to be broken?

**Comment by metachronism** [comment]
spawn road has been broken for a long time

**Comment by SeanAtr0n** [comment]
yeah but i imagine it'll require an update to account for ramp width changes anyway

**Comment by metachronism** [comment]
done
