### ISSUE TITLE
Escape menu goes offscreen in some aspects

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8877]

**Comment by johnkslg** [comment]
Also need middle button guide

**Comment by SeanAtr0n** [comment]
Also advanced graphics settings disappeared

**Comment by metachronism** [comment]
rename gameplay to general
music/sfx are under graphics options, move to general
move "restart tutorial" to gameplay tab, remove tutorial tab
clambering shouldnt be an option anymore (its unused)
consider adding a button for close/return to game

**Comment by craig-jong** [comment]
when selected, graphics does not highlight
![image](https://user-images.githubusercontent.com/18184943/43867752-5d2fbca8-9b1f-11e8-9eec-49b0b8f55134.png)
![image](https://user-images.githubusercontent.com/18184943/43867755-6054b24e-9b1f-11e8-8a25-117314894dbb.png)

**Comment by MarjieAVolk** [comment]
Missing report a bug button

**Comment by johnkslg** [comment]
Got it, didnt notice that. They're readded now. Fixed!
