### ISSUE TITLE
Exception spam from task ui still, on updated master

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#8878]
![image](https://user-images.githubusercontent.com/23460210/43803868-eb04f1e6-9a4e-11e8-8ab9-4d251ec69342.png)

**Comment by johnkslg** [comment]
Cant repro this, need to know what tutorial its breaking on, can you put a breakpoint and check?

**Comment by MarjieAVolk** [comment]
Well it IS magically working now after all.  O.o
