### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#8879]
Need clean logs on release, these missing icons preventing that

- [ ] CraneItem
- [ ] RubberWheelItem
- [ ] SmallWoodCartItem
- [ ] SteelAxleItem
- [ ] SteelGearItem
- [ ] SteelPlateItem
- [ ] SyntheticRubberItem

**Comment by keegan-o** [comment]
Fixed in staging.
