### ISSUE TITLE
Missing objects

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#8880]
need clean logs on release, this error message preventing that:

- [x] APGenObject
- [x] AtmosphereRegulatorObject
- [x] AtmosphereTesterObject
- [x] BigStorageChestObject
- [x] ButtonObject
- [x] ElkSkypiercerObject
- [x] LogicGateObject
- [x] SwitchObject

**Comment by craig-jong** [comment]
These are all old/unused items. I can fix them.

**Comment by craig-jong** [comment]
fixed in above pr
