### ISSUE TITLE
Environment data missing from minimap

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8882]
![image](https://user-images.githubusercontent.com/3536496/43809846-7dc859fe-9a69-11e8-954c-658870fc8b66.png)

**Comment by MarjieAVolk** [comment]
Have any exceptions?

**Comment by MarjieAVolk** [comment]
Works On My Machine (TM)

**Comment by MarjieAVolk** [comment]
Had several people confirm this works in their editor and in the build, so I'm assuming this is a sync/import problem.
