### ISSUE TITLE
Laws which contain "attempting to pick up" are not working with all objects.

### ISSUE THREAD

**Issue by ecostasiaUser** [StrangeLoopGames/EcoIssues#8884]
**Version:** 0.7.6.3

**Steps to Reproduce:**
Create a district XYZ. Afterwards place a bookshelf in the district.
Create a law which says "When attempting to Pick Up where (in district XYZ) If condition is true Then allow Otherwise prevent".

**Expected behavior:**
It is not possible to pick up the bookshelf because of the law preventing it if the condition is false.

**Actual behavior:**
It is possible to pick up the bookshelf even the law should prevent this action because the condition is false.

This is the case with some machine tables, bookshelfs, stone braziers, all kind of doors and maybe more objects. Building materials like mortared stone or lumber are working like expected and can not get picked up.

**Comment by MarjieAVolk** [comment]
"Pick up" laws don't work with objects currently, only blocks.  In the next release, they will work with both blocks and objects.
