### ISSUE TITLE
7.7 Graphic looks kind of pale and dull compared to v7.6

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#8885]
Version: 0.7.7.0-beta-staging-89185ed9

Not a Bug! Just feedback and notification:
I would regret to loose this vivid magnificent illumination from pre v7.7 versions
(screenshots are made with same settings in main menu)

v7.6.3
![panorama 6 3](https://user-images.githubusercontent.com/38510829/43830434-830e01be-9b01-11e8-9b6f-c8532b923fe8.jpg)

v7.7.0
![panorama 7 7](https://user-images.githubusercontent.com/38510829/43830464-967e44b6-9b01-11e8-92c1-dafe6f2491db.jpg)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#494
