### ISSUE TITLE
Road efficiency broken on ramps

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#8886]
Also I'm guessing whatever contracts uses for road detection is probably broken

**Comment by metachronism** [comment]
craig just needs to update the vehicle templates for the new road types

**Comment by SeanAtr0n** [comment]
sounds like that'll become very verbose?

**Comment by SeanAtr0n** [comment]
also, don't think that'll fix contracts

**Comment by SlayksWood** [comment]
merged to #12205
