### ISSUE TITLE
Travel efficiency is set to low/0.

### ISSUE THREAD

**Issue by sukar42** [StrangeLoopGames/EcoIssues#889]
Carts cannot go off road (even just a wheel ) or will be permanently stuck until moved onto the road because of the efficiency being set to 0, ramps with dirt/0 under them cannot be used either
but you can make ramps work by placing road under it.

**Comment by sukar42** [comment]
wood also stops the carts.

**Comment by metachronism** [comment]
fixed since 5.5.2
