### ISSUE TITLE
PipeEmitterObjects causing many unnescessary chunk changes

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#8891]
the way that pipe emission ports work now causes a lot of frequent spawning/destroying of world objects at the emission point.  This leads to a lot of unnescessary set blocks in the world, and other things.  Just one pipe doing this in my test lead to ballooning the client update packet from 1k/s to 9k/s, due to the constant chunk changes and object spawning update messages.

some possible suggested fixes:
- keep the pipe exit point objects around all the time, even when not emitting things
- make pipe exit objects not have occupancy

**Comment by SeanAtr0n** [comment]
they shouldn't be spawning/despawning quickly... something must have broken them

**Comment by SeanAtr0n** [comment]
pipes are all screwed up emitting negative values

**Comment by SeanAtr0n** [comment]
fixed

**Comment by johnkslg** [comment]
Thanks!
