### ISSUE TITLE
 Little and Small Stockpile giving target size of a normal stockpile

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#8893]
**Version:** 0.7.6.3 beta

as can be seen below the Small Stockpile and the Little Stockpile when targeted with give the size outline of a Normal 5x5x5 stockpile, this can be a little annoying actually putting stuff in (sometimes you have to get right up next to it for stuff to go in or be taken out)

![snap2361](https://user-images.githubusercontent.com/29383891/43865732-45c2c920-9b5b-11e8-96bd-d5d5b69ada3f.png)
![snap2362](https://user-images.githubusercontent.com/29383891/43865733-45dc1fa6-9b5b-11e8-9d53-1ea6fafd50e7.png)

Ignore the weird Field of View Snapshots, tried to make what it is showing as clear as possible, this is most noticeable when in tight space underground

**Comment by seccombew** [comment]
Possibly fixed in 7.7+

**Comment by craig-jong** [comment]
I swear I fixed this, but I'll double check.

**Comment by redwyre** [comment]
This has been fixed for a while
