### ISSUE TITLE
[7.7.0] Unclear how to use the playtimes graph on the main menu

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8894]
Shows the 3 colors, doesn't tell the user which mouse buttons/keyboard keys are needed to change the color.
![playtimes](https://user-images.githubusercontent.com/35509188/43868576-1a144cf0-9b23-11e8-83e8-00ea3cc2a74c.PNG)

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/43925798-263b163e-9bdd-11e8-8c1d-2328b2d964e0.png)
Added mouse images
Fixed
