### ISSUE TITLE
[7.7.0] Options menu UI is messed up in windowed mode

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8895]
UI is not adjusting to different resolutions properly.
Also, Fullscreen box isn't clickable and doesn't reflect if it's in fullscreen mode or not. (Entered windowed mode by changing res to 1280 x 800).

![windowed_mode](https://user-images.githubusercontent.com/35509188/43868688-9d94b272-9b23-11e8-902b-bb3fcc98d7ae.PNG)

**Comment by johnkslg** [comment]
Fixed
