### ISSUE TITLE
[7.7.0] Tutorials can no longer handle changing languages

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8896]
Triggered by changing language from English to something else via the Options Menu.
![canthandlelanguages](https://user-images.githubusercontent.com/35509188/43868834-6faae9fc-9b24-11e8-9106-7f8d2d4097a1.PNG)

**Comment by Nanders** [comment]
They still work/localize. 
They only get messed up if you change languages while you have them open. Might warrant a bump-down in priority

**Comment by Nanders** [comment]
fixed in 7.7
