### ISSUE TITLE
[7.7.0] New Game UI can't handle different resolutions

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8897]
Currently set to 1280x800
![newgameui](https://user-images.githubusercontent.com/35509188/43869469-88802016-9b27-11e8-82d1-5dbd68dfe0a5.PNG)

**Comment by BlazeGuy2** [comment]
![servers](https://user-images.githubusercontent.com/35509188/43916943-d424a180-9bc3-11e8-9439-1f09da440457.PNG)

**Comment by johnkslg** [comment]
Fixed
