### ISSUE TITLE
Individual item crafting causes items to disappear after placing

### ISSUE THREAD

**Issue by Outfenneced** [StrangeLoopGames/EcoIssues#89]
OS: Windows 7
Version: Alpha 3 (Downloaded 4/30/2016)
How to reproduce: 
Clicking craft repeatedly with a quantity of 1 on an item (in my testing I've only done raw stone -> stone in the work bench) allows the crafting, but after retrieving a stack of the stone out of the crafting and placing one (I've only tested while building a building), the whole stack disappears. 

May be related to #62 and #58 , but since they didn't state this method I'm going to report it anyways.

**Comment by metachronism** [comment]
fixed in alpha 4
