### ISSUE TITLE
Cannot research cooking

### ISSUE THREAD

**Issue by EnigmaticTailor** [StrangeLoopGames/EcoIssues#890]
ferns are labelled differently in the recipe then the inventory item

(Eco alpha 5 test server)

**Comment by newzealdan** [comment]
Double check - the research table does ask for fiddlehead fern, which I seem to have plenty of. There may be 2 types of fern in the world?

**Comment by EnigmaticTailor** [comment]
fiddlehead fern does not exist in the Ecosystem list of plants and animals on the server

**Comment by craig-jong** [comment]
the fern plants used to give a "fern" item, however the harvested item has been renamed to "fiddlehead".

**Comment by EnigmaticTailor** [comment]
harvested over 200 units of fern with scyth and shovel still no 'fiddlehead' only fern

**Comment by craig-jong** [comment]
This should no longer be an issue; if it is please reopen or submit a new issue.
