### ISSUE TITLE
loading tree appears behind steam overlay

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#8900]
![image](https://user-images.githubusercontent.com/3150561/43870213-3d5d1cc0-9b2b-11e8-9e6b-66c0858173f1.png)

I think you can either configure steam overlay to be in a different corner, or move the loading tree somewhere else

**Comment by johnkslg** [comment]
Move to left corner

**Comment by mirasrael** [comment]
Somebody already moved this in master :) Fixed
