### ISSUE TITLE
Save and Flush in server not reliable

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8902]
Posted per JohnK request. There has never been an option where the admin/server owner command a save of the world from in game and must depend on the timing of auto save for the last save of the world before stopping.  While, if the owner has access in server UI to'Flush to disk and Save" its not always reliable both from user impatience or sometimes it just does not reliably run.  The exit in the console says its saving but it does not appear that a save is done, just the process killed.

there was a mod for a while that is now out-dated and abandoned that did have a true /save command for in game and it worked well but due to changes since that mod was abandoned it now does not work.

Could a /save command just be added to the Chat Commands that would flush ram to disk,,compress and save and then notify the user that the world save is complete?  that would be a major fix for many complaints of a few minutes of data loss from servers on a  regular basis when the shut down or restart

**Comment by johnkslg** [comment]
Changed title of bug, it should be more reliable, and we can add a /save chat command to trigger it.  

Check out existing chat commands, need to inherit from ChatCommandHandler then tag it with a ChatCommand attribute. Make it an admin only command.

Check out why flush and save on the server isnt working (@metachronism any idea why it would be unreliable?)

**Comment by pamduncan** [comment]
Just as a explanation to what we found happening with flush and save to disk' reliability.  Have a server with a 300 second autosave.  When going to do a restarts or update server, if I go into server UI and use 'flush to disk and save' I am able to see what appears to be compression of a save to the world save but when the server comes back up I get reports that it seems like several minutes have been lost and things that were done just before a player logged off before I ran the command appears to not have happened yet and often they are in a different spot then where they logged off.  It seems like the last save was the last autosave.  To test this we placed world markers down every minute in different locations for 10 minutes prior to logging off.  At the same time we had people putting specific objects in stockpiles and chests at intervals of 1 minute.  At the end of the 10 minutes everyone logged off and I ran a flush to disk and save.  When we logged back in we were missing the last 4 world markers (those apparently places after the last autosave) and objects that had been placed in chests and stockpiles during the last 4 minutes were not in any containers but back in players' inventory.  So while it seems like the autosave worked fine nothing after the autosave ran was saved.

**Comment by mirasrael** [comment]
Fix provided

**Comment by pamduncan** [comment]
Thanks for getting this fixed - this will solve a lot of support issues

**Comment by mirasrael** [comment]
This probably will only go for 8.0 :( unless guys decide to include this in 7.7

**Comment by johnkslg** [comment]
Lets get it in 7.7!

**Comment by johnkslg** [comment]
Fixed
