### ISSUE TITLE
[7.7.0] After meteor tutorial, can't use mouse to move left or right

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8903]
Shown in the video below, meteor may have flown over the horizon prior to completing the tutorial.
https://youtu.be/xj4BEoe6hwY

**Comment by johnkslg** [comment]
Need repro help

**Comment by BlazeGuy2** [comment]
Tried to reproduce a couple times, and it seemed to work fine.  Dropping priority since it did happen, but I can't find a reliable repro condition.

**Comment by BlazeGuy2** [comment]
Repro case: this issue only occurs if I witness the meteor tut with fly toggled on.  Turning fly off removes the mouse issue.

**Comment by johnkslg** [comment]
Fix is to disable fly mode before meteor tutorial

**Comment by johnkslg** [comment]
Did you try this while in fly mode? Push F

**Comment by johnkslg** [comment]
It appears to be fixed!
