### ISSUE TITLE
[7.7.0] Can't pickup bison carcass

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8905]
Killed it with a bow and arrow, can't pickup the carcass.
![deadbison](https://user-images.githubusercontent.com/35509188/43871572-34eed392-9b32-11e8-8766-cf8bbf46cc2c.PNG)

**Comment by SeanAtr0n** [comment]
Looks like this broke along with the auth refactor... PlayerInteract won't interact with things that use IInteractableObjectPosition

**Comment by metachronism** [comment]
I'll take this one
