### ISSUE TITLE
[7.7.0] Stores and the Mint made from spawneconomy have a few issues

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8912]
![storebug](https://user-images.githubusercontent.com/35509188/43925473-2c2492c4-9bdc-11e8-8dad-da1ab6e14b05.PNG)

* Stores a made from spawneconomy have me authorized by default, so I can't test buying items
* I hit the + button when I go to sell an item and they become No More Wanted and can't be changed out, owner can't even fix this (Owner is TestAlpha)

**Comment by BlazeGuy2** [comment]
Mint let my user who wasn't authorized at the mint to craft a new currency.

**Comment by mirasrael** [comment]
I wasn't able to reproduce it on staging. 
Thought I can assume your user was somehow added to claim owners. New authorization system maintains two permission sets:
1. for consumers - in this case you can buy/sell at Store, but can't change prices, limits, add/remove offers;
2. for full access - they are retrieved from Deed permissions and can perform almost same actions as Owner.
I tested it with plain /spawneconomy command and it all works as expected: no way to change prices in store, not able to use Mint.
Then I added my user to Test Client's deed and I was able to configure Shop and mint currency.

There are screen where you can check list of deed's users:
![image](https://user-images.githubusercontent.com/475445/43999757-5e81a9dc-9e1b-11e8-818e-20e56523e6b2.png)

I also added pull request with new admin commands:
/addtodeed [username]
/removefromdeed [username]
They may simplify testing.

**Comment by johnkslg** [comment]
I did fix a bug that was defaulting everything to public, thats probably why you couldnt repro it.
