### ISSUE TITLE
[7.7.0] Can't use Currency Exchange as customer

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8913]
Test alpha owns it, but I can't exchange currencies at it using the other user.  Instead, I'm treated as it's owner for setting exchanges and restrictions.
![exchange](https://user-images.githubusercontent.com/35509188/43926176-4912c4b2-9bde-11e8-9891-58b6a8d62da7.PNG)

**Comment by johnkslg** [comment]
Fixed, was happening because land was defaulting to public.
