### ISSUE TITLE
[7.7.0] Meteor craters are pink

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8920]
[770 default world.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2276084/770.default.world.zip)

Craters are pink in the pics
![meteorimpact](https://user-images.githubusercontent.com/35509188/43929659-c41cb922-9bea-11e8-8a5a-541c9e49c216.PNG)
![impact2](https://user-images.githubusercontent.com/35509188/43929660-c432be98-9bea-11e8-8813-5ae8a34c47df.PNG)

**Comment by keegan-o** [comment]
Fixed in master and staging.
