### ISSUE TITLE
'Show location' in minimap only works when minimap set to 'Follow player'

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#8924]
It does nothing if the minimap is set to 'spin planet' or has all panning disabled.  This is because showing a location is done by spoofing the player's location to be the desired location.

**Comment by Kirthos** [comment]
I wanted to work on this but I'm not sure about what we want to do if the camera is set to 'spin planet'. 
I have a fix with the stationary camera that move if you click on a location.

**Comment by elfl0rd** [comment]
Stationary too

**Comment by SlayksWood** [comment]
If you use stationary and click show in minimap it will change it to Follow player.

**Comment by beastyn** [comment]
Nope. still the problem. It will change camera to the Follow Player if you ckick on coordinates (even if you choose stationary)
