### ISSUE TITLE
Moving full stack of wood pulp causes exception

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#893]
Alpha 0.5.0 hotfix 1 or 2 or 3, i don't know?

![image](https://cloud.githubusercontent.com/assets/6193670/21076818/708bcc4a-bf9a-11e6-924a-0e6df666aac6.png)

If you move 100 wood pump into your hands/carry and try to place it in another workbench, it causes the below exception. Very repeatable.

![image](https://cloud.githubusercontent.com/assets/6193670/21076813/4cc03bac-bf9a-11e6-89ea-4b2f03d4a1c6.png)

If I try moving a stack of wood pump into my inventory, the weight limit flashes a whole bunch, and after some time the stack is split, but it seems to have difficulty with this.

**Comment by newzealdan** [comment]
Also true with a full stack of pitch

**Comment by METALmurderer** [comment]
As of today (2/12/2017), moving Wood Pulp crashes your client back to server select. Have not tested it with Pitch
