### ISSUE TITLE
USER ISSUE: Elevator

### ISSUE THREAD

**Issue by EiKiDa** [StrangeLoopGames/EcoIssues#8933]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
---

**Expected behavior:**
If there is a "normal" elevator, there should be one for vehicles too.

**Actual behavior:**
There is just one type of elevator.

**Comment by elfl0rd** [comment]
This is not issue, place for suggestions here - https://github.com/StrangeLoopGames/EcoSuggestions

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#497
