### ISSUE TITLE
When Dragging a stack Item from any Stockpile Not getting the Carrying window appearing

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#8935]
**Version:** 0.7.6.3 beta
as you can see below i have dragged the Stack from Stockpile and No Carrying Window Appearing
Pressing Shift to take 1 or max Stack doesn't work either

![snap2376](https://user-images.githubusercontent.com/29383891/43960349-a359d73c-9ca9-11e8-9413-0e96f9cd23ff.png)

i also attach Ouput_log.txt file
 (had to put it in a zip as it is a massive117 Meg Biggest one i have ever seen)

[output_log.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2278060/output_log.zip)

also linking a Closed Github
USER ISSUE: Carrying icon does not appear in toolbar menu #8500

Disconnecting does not always help (especially after a Few hours of playing)
Quitting and starting again it works fine

**Comment by Conchipedia** [comment]
[output_log.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2280450/output_log.zip)
Happened again, so another Output_log.txt

**Comment by mirasrael** [comment]
@BlazeGuy2 was you able to reproduce this in the staging build?

**Comment by Deantwo** [comment]
I had this happen in my singleplayer world too at one point, I had been playing a few hours and don't know what caused it those.
Have not seen it happen since.

Reconnect/restart fixes it.

**Comment by johnkslg** [comment]
Need help getting a repro case

**Comment by Conchipedia** [comment]
if i knew how to reproduce this i would let you know, as it doesn't happen very often

**Comment by seccombew** [comment]
Not able to reproduce, reopen if repro case is found.
