### ISSUE TITLE
USER ISSUE: Skid Steer Toggle Key - Ubuntu - Azerty Keyboard

### ISSUE THREAD

**Issue by rrfvtgb** [StrangeLoopGames/EcoIssues#8937]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
1. Run Eco on (k)Ubuntu 
2. Get a Skid Steer
3. Press 1 (or "Amp") to toggle digging mode
- Or -
3. Left click / Right click to the toggle icon

**Expected behavior:**
It should have toggle digging mode

**Actual behavior:**
It does nothing.

**Comment by SlayksWood** [comment]
Thank you for report.
Skid steer haven't digging mode from 8.2.0 and we improved Control settings. Closing for now.
