### ISSUE TITLE
USER ISSUE: large lumber door with windows

### ISSUE THREAD

**Issue by Torskeeen** [StrangeLoopGames/EcoIssues#8941]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**

**Expected behavior:**
should count as a room with this door instaled

**Actual behavior:**
dose not count as a room with this door

**Comment by elfl0rd** [comment]
Screenshot please, it's work fine for me.
![default](https://user-images.githubusercontent.com/4980243/43987358-0598abca-9d28-11e8-8eb7-50243afba73c.png)

**Comment by Torskeeen** [comment]
@elfl0rd 
![before door](https://user-images.githubusercontent.com/42282975/43990738-07bf70cc-9d60-11e8-8cdf-8b853d38e3c5.png)
![afeter door](https://user-images.githubusercontent.com/42282975/43990741-0c0831be-9d60-11e8-9774-fed1c606ff20.png)

**Comment by keegan-o** [comment]
The updating is a code issue that has been around for a while, un-assigning self. @johnkslg You should be aware of this if not already, though! (Issue is sometimes rooms do not update until you remove/re-add a block somewhere)

**Comment by SlayksWood** [comment]
Checked on 0.8.2.9. Wasn't able to reproduce. Seems fixed.
