### ISSUE TITLE
Error when going to web interface from game. Sometimes opens Windows Explorer

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#8942]
https://cdn.discordapp.com/attachments/336975198127652866/473951229421027330/unknown.png
https://cdn.discordapp.com/attachments/336975198127652866/473951294206509056/unknown.png

sometimes it open windows explorer instead of chrome
my default browser settings are still correct

- computer doesn't lag when opening
- disk is not full
- tried eco and computer restart
- happens with chrome open or closed
- happens sporadically

To Do:
- try logging in w/o steam and go to the same server where does its url take you?
- log file might be useful

Reported by at least one other user.

**Comment by SeanAtr0n** [comment]
couldn't reproduce... log file would be useful... guess we reassign these to walker now?

**Comment by Deantwo** [comment]
Duplicate of #9252
