### ISSUE TITLE
Cant create bond/loan offer

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8945]
It thinks amount is wrong, but the owner doesnt set that, the user does. 
![image](https://user-images.githubusercontent.com/3536496/43984762-71fcf63e-9cb7-11e8-8095-e24d61607680.png)

**Comment by mirasrael** [comment]
Can you please add branch where it was discovered? In staging you can create Bond contract, but can't accept it :)

**Comment by johnkslg** [comment]
Fixed!
