### ISSUE TITLE
Singleplayer can't reach web interface to vote

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#8946]
When I try to use these functions and it says "open in browser" I click yes and get directed to my browser.It says "this site can't be reached".

https://media.discordapp.net/attachments/477471548803121159/477577522305957891/Capture.PNG?width=1202&height=677

**Comment by metachronism** [comment]
if the webserver fails to start due to security issues, you wont be able to access it.  This is a windows-specific issue we cant fix, unfortunately, when they decline to grant the permissions
