### ISSUE TITLE
Tailings quantity increase from level up efficiency.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8947]
Big problem after update, leveling efficiency, increase tailing production... It's not right :(

Smelting 20 ore w\o efficiency - 2 ingot and 2 tailing
![20180811052136_1](https://user-images.githubusercontent.com/4980243/43987258-c0721a6e-9d26-11e8-9fed-b0ac2892f2df.jpg)

Smelting with max efficiency - 10 ingot and 10 tailings.
(yes, you give 10 tailings from 20 ore, 10 tailings from 5 world blocks....)
![20180811052145_1](https://user-images.githubusercontent.com/4980243/43987259-c38ccbae-9d26-11e8-9825-3a643388619c.jpg)

**Comment by Deantwo** [comment]
Ah you mean the number of tailing per unit of ore increase.

**Comment by elfl0rd** [comment]
yes, dramatically tailings output increasing - really problem :(

**Comment by mirasrael** [comment]
As quick fix efficiency may reduce number of produced tailing with ceiling.
In example:
- 2 ore = 1 ingot + 1 tailing (1 - 80% = 0.2 ceiling to 1).
- 10 ore = 5 ingot + 1 tailing (1 - 80% * 5= 1 ceiling to 1).

Like it works now for crafting ingredients. If you need 0.2 and will craft only 1 item then it will take whole item.

**Comment by johnkslg** [comment]
Fixed

**Comment by Voosle** [comment]
@johnkslg 
I'm confused… is this in today's 7.7 stage Version? seems not to be

![image](https://user-images.githubusercontent.com/22961978/44608856-b036af00-a7f5-11e8-8aad-643105a86f4c.png)

**Comment by elfl0rd** [comment]
@Voosle try 10

**Comment by elfl0rd** [comment]
i can not see changes nowhere...
@craig-jong ?

**Comment by elfl0rd** [comment]
Bleeding-edge, works cool :p 
![default](https://user-images.githubusercontent.com/4980243/44985643-b9f4ab00-af89-11e8-9b69-52355f9633cd.png)
![default](https://user-images.githubusercontent.com/4980243/44985688-e14b7800-af89-11e8-8ebf-7ddbd3a44775.png)
Now, efficiency work like... efficiency!
