### ISSUE TITLE
Elk Mount and Bison Mount do not fit against a Wall, it has to be a Solid block (also they do Not score if outside)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#8950]
**Version:** 0.7.6.3 beta

![snap2382](https://user-images.githubusercontent.com/29383891/43994332-1a13f7ce-9d93-11e8-97ae-1619f922482a.png)
![snap2383](https://user-images.githubusercontent.com/29383891/43994333-1a2c2eb6-9d93-11e8-9912-f6fcec5e808b.png)

its also a pity that they do not score outside as they look Great either side of a doorway

![snap2384](https://user-images.githubusercontent.com/29383891/43994375-d9f206b2-9d93-11e8-82d4-d6b20bf0017f.png)

also i Love the Stuffed Elk, the Only drawback is i cannot have it part of the Floor as it is Not classed as a building Block so i cannot have a different room underneath or the room being over a hole or water
![snap2385](https://user-images.githubusercontent.com/29383891/43994430-8ba1eec2-9d94-11e8-9d4c-c9fd0412008d.png)
so i have to have it like this
![snap2386](https://user-images.githubusercontent.com/29383891/43994435-ad19ee92-9d94-11e8-9bd2-faf3daeebe99.png)

❤️ ❤️ Please Can we have the Other Animals (and Fish) stuffed like the Elk? ❤️ ❤️

**Comment by metachronism** [comment]
known dupe
