### ISSUE TITLE
USER ISSUE: Material processing task not going away

### ISSUE THREAD

**Issue by JohnnyBNoobe** [StrangeLoopGames/EcoIssues#8951]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
1. Complete tasks from the tutorial (seemingly in a normal way)
2. Complete all the "Material processing" tasks
3. (optional) Try to remove the task by clicking the red cross and clicking "Yes"
4. (optional) Try ticking the box "Skip all tutorials" and clicking yes again

**Expected behavior:**
At step 2, the box should go away and (I suppose) display the next task of the tutorial. At step 3 and 4, it should go away.	

**Actual behavior:**
At step 2, the task stays even if all the items are marked completed. At step 3 and 4, it stays.

**Comment by seccombew** [comment]
@johnkslg May want to reprioritize

**Comment by johnkslg** [comment]
@mirasrael Check for exceptions preventing it, should never happen that way.
You can make the material processing task happen on start to test it, may be easier to get a repro case so you dont have to go through the tutorial each time.  Thats in TutorialTasks.cs

**Comment by JohnnyBNoobe** [comment]
Just adding that relaunching the game did solve the bug. Also, when I join a new server/game, I always get the tutorial, is it normal ?

**Comment by mirasrael** [comment]
Wasn't able to reproduce this on staging.

**Comment by mirasrael** [comment]
@JohnnyBNoobe did you have this every time or it was happened time to time?

**Comment by johnkslg** [comment]
Probably fixed, closing, reopen if you see it again!
