### ISSUE TITLE
USER ISSUE: Connection tiemd out

### ISSUE THREAD

**Issue by Chlorophorm** [StrangeLoopGames/EcoIssues#8952]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
1. Play abaout 15 minutes online on a rented server.

**Expected behavior:**
Nothing should happen.

**Actual behavior:**
The following error message popped up:
Connection timed out
```

**Comment by beastyn** [comment]
Wasn't able to catch this with 0.8.1.4
Seems to be fixed. Please reopen if happens again
