### ISSUE TITLE
Logo takes a long time to login

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8955]
When you open with Steam, the logo takes an appropriate time to display.  However, if you login as an SLG user, that delay is too long, since it happens after the login.

Make it so if the user logs in, the delay on the logo is skipped.  Theres a function in Fader to do this.  Delay should still happen properly in other cases.

**Comment by metachronism** [comment]
dupe
not steam related - release build has the same issues

takes like 20 seconds for the fades to finish

**Comment by seccombew** [comment]
Dupe

**Comment by johnkslg** [comment]
Its supposed to take a long time on steam, and is correct there.
The bug is when youre logging in with SLG only.
