### ISSUE TITLE
USER ISSUE: Server not Showing

### ISSUE THREAD

**Issue by IanHarned** [StrangeLoopGames/EcoIssues#8956]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
pull up server list. it works for others that i play with but not me

**Expected behavior:**
show up the doomland server. funnybunnyofdoom is the admin

**Actual behavior:**
it won't show on the list

**Comment by SlayksWood** [comment]
Checked on 8.1.3. Wasn't able to reproduce. Do you have this problem now?

**Comment by beastyn** [comment]
Please reopen if you still has this issue
