### ISSUE TITLE
USER ISSUE: alot of lag

### ISSUE THREAD

**Issue by rsgodkilla** [StrangeLoopGames/EcoIssues#8957]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
alot of lag even with most of the graphics turned off and i got a i7 processer and 4 gb graphics card, thought might be a good idea to report it 

**Expected behavior:**

**Actual behavior:**

**Comment by seccombew** [comment]
We are actively working on improving performance, thank you.
