### ISSUE TITLE
New Escape Menu formatting broke Screen Resolution / Fullscreen UI

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#8967]
![image](https://user-images.githubusercontent.com/6262198/44125002-fcdcc448-9fe4-11e8-930f-6ef93daa7a81.png)

**Comment by johnkslg** [comment]
Looks like the bug is
- Resolutions arent listed
- Fullscreen doesnt take effect
Is that correct Nick?  You mention formatting but I dont see any formatting problems.

**Comment by Nanders** [comment]
You changed the format of the escape menu, I'm assuming somewhere in that process the Resolution UI broke.

**Comment by mirasrael** [comment]
Working on this

**Comment by mirasrael** [comment]
Fix merged
