### ISSUE TITLE
Create Avatar UI defaults to center of screen

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#8968]
Right in front of your avatar
![image](https://user-images.githubusercontent.com/6262198/44125161-dccb51b4-9fe5-11e8-9b00-7569cbd6f832.png)

**Comment by BlazeGuy2** [comment]
Where is this occurring? Master, staging or release?

**Comment by Nanders** [comment]
Most recent 7.7 build on bleeding_edge

**Comment by metachronism** [comment]
latest release doesnt have this issue
