### ISSUE TITLE
StreetLight shadows missing

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#8969]
Looks like cast shadows got turned off on them for some reason?
![image](https://user-images.githubusercontent.com/774628/44125527-0bfb2a5c-9fe8-11e8-92a8-f8c9dae4a907.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/44234487-8cbb9680-a15b-11e8-90da-ec87a36657c1.png)
Fixed in master.
