### ISSUE TITLE
Very high food consumption

### ISSUE THREAD

**Issue by Boldee** [StrangeLoopGames/EcoIssues#8973]
In the last couple of days my friends and I have noticed that for some reason food consumption has gone through the roof on our pvt server, we are carrying out activities at full efficiency and it is as if we are still at level 1, we are eating pretty high quality food with a good calorie count. 

Nothing has been changed on the server it has been running the same settings for the last month with no food consumption issues.

**Comment by Deantwo** [comment]
Are your tools broken? When a tool is at 0 durability it will consume a lot more calories with every use.

**Comment by BlazeGuy2** [comment]
@Boldee If it wasn't caused by tools being broken, I'll need a reproduction case to fix it.

**Comment by Boldee** [comment]
No tools are fine and when in full repair it still happens.

I was discussing this with the others who play on the server and we figured out that it all started when we had an issue where workstations were inoperable as they were saying they were not in a room never mind that room being the right size or having x amount of tiered building material, we could get around this by picking up and repositioning one workstation in a room after which everything started working again.

Another thing to note is that I am told it happened to one of our players previously but something fixed it without him knowing, he didn't say anything at the time until it started happening to the rest of us. I was considering reinstalling the game to see if that made a difference.

**Comment by Boldee** [comment]
Hi @mirasrael Files attached...

[Eco-Data.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2299515/Eco-Data.zip)

**Comment by beastyn** [comment]
8.2 Can't reproduce. Rooms is operating better now. Close for now. Please reopen if meet again.
