### ISSUE TITLE
Debug build not adding IntegrationTests

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8976]
Wasnt able to run /spawncontracts in debug staging server until I referenced it directly.

**Comment by BlazeGuy2** [comment]
Not in PR, copied wrong bug URL

**Comment by BlazeGuy2** [comment]
Temp fix to make /spawncontracts callable is to build the Eco.IntegrationTests.csproj prior to starting the server app.  It auto clones the .dll to mods folder once it's built.

**Comment by BlazeGuy2** [comment]
Fixed, dll is built in debug mode now as a post-build command.
