### ISSUE TITLE
[Client] Small Wood Sign and Wood Sign icons are the same, hard to differentiate

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#8978]
Version: 0.7.6.3 beta

I want to offer a Small Wood Sign from carpentry table, but the store knows only a (large) Wood Sign.

![woodsign-zoom](https://user-images.githubusercontent.com/38510829/44177053-86da9c80-a0ec-11e8-8eee-a2cf89dca5a4.jpg)

![woodsign2zoom](https://user-images.githubusercontent.com/38510829/44177071-978b1280-a0ec-11e8-8f96-bf701bbb80a0.jpg)

**Comment by Nicolausi113** [comment]
Sorry, it’s my mistake!
There are two icons in store menu for Wood Sign and Small Wood Sign but look exactly the same.
So please close this post, but if the two icons could be made a little different would be helpful.

**Comment by keegan-o** [comment]
Small Wood Sign and Wood Sign are actually legacy items that are replaced with Small Standing Wood Sign and Small Hanging Wood Sign. 
![image](https://user-images.githubusercontent.com/14983165/44234613-e0c67b00-a15b-11e8-8a91-f443ff9fbbda.png) @craig-jong Can we fully migrate world objects to be replaced by others so we can just remove the items entirely?

**Comment by keegan-o** [comment]
Craig is migrating these items away.
