### ISSUE TITLE
Deed Sales and Object Ownership

### ISSUE THREAD

**Issue by MaxInertia** [StrangeLoopGames/EcoIssues#8979]
### Actions

Okay, so this is what me and another player did (player A and B)

1. Player A claims land and grant a second player (player B) access to that deed.
2. Place several objects on the deed, by either player (such as stockpiles and tables). These will carry the name of the owner of the deed, player A.
3. Player A puts the deed for sale at a **Real Estate Desk**.
4. Player B purchases the deed.

### Result

Now **A** doesn't not have permission on the land (which I assume is intended, it's a good idea to wipe the *permitted players* list clear on selling a deed), this is good. The issue is that **A** still has ownership over all objects (stockpiles, tables, etc) placed prior to selling the deed. **A** is able to remove contents of those objects that are containers, rename the objects, or remove the objects entirely.

### Attempts to reproduce

I've tried reproducing this with that player, but we've been unable to do so... We
- Tried with B having and not having access to the deed prior to purchase
- Tried with A and B placing the stockpile, before and after claiming the land it was on

I'm at a loss, my only guesses at the moment are that it may have something to do with
- the server restarting between claiming the land and selling it, or 
- the number of objects in the deed that was purchased

Will try again soon.

**Comment by Conchipedia** [comment]
I'm Player B, We had a Server Restart in between claiming Land and placing objects so this also might have been a contributing factor to us not being able to duplicate this behaviour

**Comment by MarjieAVolk** [comment]
Hmmmm, so do you still have any of the objects that A incorrectly has access to in this bad state?  If so, you could give me the save file and I could try to find why they are getting access.

**Comment by MarjieAVolk** [comment]
Hmmm okay.  Well I'm gonna close this for now then, if we get more information I will look at it.
