### ISSUE TITLE
USER ISSUE: Can't bind fly down

### ISSUE THREAD

**Issue by Ket-SLG** [StrangeLoopGames/EcoIssues#8980]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
1. Go to keybindings
2. Fail to find an option to bind a key to fly down

**Expected behavior:**
An option to change the fly(and maybe even swim) down button

**Actual behavior:**
You can not rebind the fly down key.

**Comment by seccombew** [comment]
Closed by design, fly is a debug command.
