### ISSUE TITLE
Advancing meteor intro just before the 'next' call will make it skip two

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8981]
Need to prevent the former's animation from triggering its end while its still playing (as it fades)

**Comment by seccombew** [comment]
@johnkslg Please prioritize.

**Comment by johnkslg** [comment]
This is in the MeteorIntroUI code
There are two ways to trigger 'next', you can push space or click, or you can wait till it reaches the end of the scene. If you reach the end of the scene and push space just before, the 'end of scene' next call will also trigger and two will be skipped.  Needs to ignore the end of scene one if its already fading to the next scene.
Place that UI in editing scene to test in isolation

**Comment by sidjuego** [comment]
@johnkslg I somehow tried a chat command to show up the meteor in the sky but ended up with the meteor colliding the ground. 
is there any specific way/command to trigger the meteor in the sky?
