### ISSUE TITLE
Mint is Causing a Confusing issue ( a moved Mint to someone Else's property should Not Move Currency with it and give another Player Permision to craft another Players Currency)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#8983]
**Version:** 0.7.6.3 beta

Player A (me)
Player B (friend)

**Step 1:** Player A make 1st Mint on Server and Creates Currency Pebbles backed with Stone

**Step2:** Player B (which has Authority on my Deed) removes Mint and places on their own Deed, and the Mint is Locked to My Currency

**This is how Mint looks when placed on unowned Land** 
(as can be seen the Currency is moving with the Mint)
![snap2408](https://user-images.githubusercontent.com/29383891/44185717-1132f880-a10d-11e8-95d5-b7f70ebfffd4.png)

**Step3:** Player A, then makes a NEW mint and creates Pebbles (backed with Stone) same Spelling, this creates a NEW 2nd Currency Called Pebbles (same spelling as the first)

**Step 4:** Player A renames New Pebbles Currency to Test, then tries to rename it back to Pebbles and gets this message
![snap2407](https://user-images.githubusercontent.com/29383891/44185646-a84b8080-a10c-11e8-859b-79e8935fc7fa.png)
which is what i should have gotten when i tried to Create the 2nd Pebbles Currency

Surely A Mint should not Move the Currency with it, as Mints all look the same when carried, if the Mint is then on someone Else's property its classed as a **NEW** mint and they can **ONLY** create a **NEW** currency without the **SAME NAME**

**Example:** I would Understand the workings of this if the Currency was made with Plates like real money, and i then used the plates from America in the United Kingdom to Make American Dollars, But i am just using a Machine (table) called the Mint which can be bought and sold so is reset to its default blank status and no duplicate Currency can be created on it

**Comment by Conchipedia** [comment]
[MaxStackSize(1)]
    public partial class MintItem : WorldObjectItem<MintObject>
    {
        [Serialized] CurrencyHandle currencyHandle = CurrencyHandle.New;

        public override void OnPickup(WorldObject placed)
        {
            this.currencyHandle = placed.GetComponent<MintComponent>().Currency;
        }

        public override void OnWorldObjectPlaced(WorldObject placedObject)
        {
            placedObject.GetComponent<MintComponent>().InitializeCurrency(this.currencyHandle);
            base.OnWorldObjectPlaced(placedObject);
        }
OnPickup stores the currency of the place mint in the mint object that is carried.

OnWorldObjectPlaced transfers that stored value into a placed mint.

If this is ALL True (then the Mint should not allowed to be moved to another player without Changing the name Mint to Mint(Currency) to let a pl;ayer knows that they are NOT just selling a Mint but selling the right to Create a Currency

**Comment by Conchipedia** [comment]
another thing with having Mint having Currency attached to them is selling them in a store
If i have two Separate Mints with Currency on them like this
![snap2409](https://user-images.githubusercontent.com/29383891/44190423-aa1e3f80-a11e-11e8-9740-d619614ab61e.png)
![snap2410](https://user-images.githubusercontent.com/29383891/44190424-aa1e3f80-a11e-11e8-8ac8-d0cdf41bd921.png)
this is how it is displayed if you hover mouse over Entry (more than one being sold)
![snap2411](https://user-images.githubusercontent.com/29383891/44190458-d33ed000-a11e-11e8-9e35-873bd123d6ec.png)
one being sold
![snap2412](https://user-images.githubusercontent.com/29383891/44190513-1731d500-a11f-11e8-8047-a106f7345be4.png)
and how displayed in Economy Viewer
![snap2413](https://user-images.githubusercontent.com/29383891/44190593-67109c00-a11f-11e8-9456-7c23184f5984.png)

Still No Information about A currency Locked to the Mint.

also if i own both Mints the Original with Pebbles if i Remove from World and Carry or store i can place my other one Back into the World which has test as a currency and then rename it to Pebbles (which is the Wrong currency (duplicate name)
as shown in Economy Viewer, two Identical names two totally different amounts of what i have
![snap2414](https://user-images.githubusercontent.com/29383891/44190718-f322c380-a11f-11e8-9148-ea05f2561eb8.png)

and then there is another possibility an Option For Trolls, make more than one Mint, Create a Currency on it, pick it up, make another place it make same name Currency, and continue on for as long as i want picking up and crafting mints and choosing same name
as you can see from the following snapshots Only the Amount in Circulation is showing the First Created one on server
![snap2415](https://user-images.githubusercontent.com/29383891/44190890-ad1a2f80-a120-11e8-8643-e18e6acaf09f.png)
![snap2416](https://user-images.githubusercontent.com/29383891/44190892-ad1a2f80-a120-11e8-806e-f766cdf19748.png)

Proof that i own two Mints in world at same time on my deed, and they both have the same name
![snap2418](https://user-images.githubusercontent.com/29383891/44190953-eb175380-a120-11e8-8e1a-8d6840bea521.png)

Personally i prefer the OLD way of Mints

**Comment by Conchipedia** [comment]
the list of Trolling goes on, Make law once a Mint is place it cannot be moved, once one Mint is made no more can be crafted (but that can be done normally)

**Comment by seccombew** [comment]
Is this working as intended @johnkslg?

**Comment by MaxInertia** [comment]
### Problem
An issue here is that a new Mint can take on a currency name the same as one previously created, resulting in two currencies which have the same name. This complicates the use of `./pay` (When I tried this, it used the original currency).

### Potential Problem
Players do not know which currency (if any) a Mint for sale in a shop is associated with. 

**However** maybe the intention is that if a Mint is sold, it will no longer be bound to the original currency? I have yet to try this.

**Comment by Conchipedia** [comment]
seems wide open to abuse, someone has a Mint that is the main currency, they accidentally give permission on deed someone else comes and takes the Mint from the Deed, they now have the ONLY mint that can produce this Currency, then they store it in a chest to be never seen again, the person whose Mint it was can no longer create this Currency because the original Mint has, it would be even Possible for Owner to make a Mistake by picking up the Mint and then throwing it in the Trash that Currency is now dead, as it is the ONLY Mint capable of creating this currency, what happened to the Old days when a Player creates a NEW currency then that Currency is locked into the Player themselves, so no matter if they lose a Mint or get a new one they can still make the Currency they first made.

**Comment by Kirthos** [comment]
This issue is a bit like #8737 
The fix I've done is to prevent player to create a currency with a name that already exists.
But yes, if the mint item is destroyed, the currency can't be created.
Maybe, it can be better to have the possibility to link a mint to a existing currency.
If when you enter the name of a currency that exist in a mint, instead of prevent you cause the currency already exists, the mint can link to the currency.
So the mint item don't need to store the currency, you will just need to write the currency name again when you place the mint. 
And you will be able to have 2 mints with that backed the same currency.

**Comment by Voosle** [comment]
Maybe similar to #8471 ?

**Comment by Conchipedia** [comment]
moving Mints around we seemed to have totally managed to NEVER make the same Currency again, because if we try i can Name it the same but it will NOT be the same currency

**Comment by MaxInertia** [comment]
@Kirthos The main (real) issue here is exactly #8737 (albeit it puts it more concisely).

@Voosle I read #8471 and that's not related, we've had no problems with the backing currency changing (as far as I have seen).

**Comment by Deantwo** [comment]
Is this still an issue?
As far as I know a mint is forever locked to produce only one currency once configured. Even if you pickup the mint and place it somewhere else.

**Comment by Conchipedia** [comment]
i think it has been fixed (but not 100% sure as i don't have anything to do with mints anymore)
but i think the main problem was someone with Permission on your property could **move** the Mint to their Deed and then take over  producing the Currency on this mint and i still think that the Mint could be moved to Storage and then **sold** but if i remember correctly it doesn't  show the information that the Mint has currency locked to it when Selling

**Comment by Conchipedia** [comment]
i did like the **old** way when you could just move a Mint and the currency was like locked to the player who created it so nobody else could take over the production of **your own** currency

**Comment by Deantwo** [comment]
But being able to hand over the minting responsible is nice too, such as when the world leader or bank owner changes.

**Comment by Conchipedia** [comment]
i thought that what the Currency exchange was designed for just in case a Bank goes out of Business so a New currency could be brought in

**Comment by Deantwo** [comment]
No... Currency Exchange is used to make currency exchange stores. Anyone can set one up and start selling a currency for another.

Anyway, I guess this bug report can be closed.
The issue about a Mint for sale not showing thst it already has an assigned currency should be reported in a separate bug report.

**Comment by D3nnis3n** [comment]
Working as intended for now, changes in a suggestion by Slayks.
