### ISSUE TITLE
Carrying hewn logs doesnt look as nice as regular logs

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8984]
Regular
![image](https://user-images.githubusercontent.com/3536496/44234086-88db4480-a15a-11e8-9cd0-2b12d5d91d43.png)

Hewn
![image](https://user-images.githubusercontent.com/3536496/44234101-9395d980-a15a-11e8-890c-a9770a626b86.png)

Hewn should match logs, be rotated horizontally like youre carrying them.
Texture and normals look nicer on regular logs

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/44234145-b88a4c80-a15a-11e8-83a2-504eb3a2ce5b.png)
Same with brick, it should look like I have an armful of bricks centered

**Comment by johnkslg** [comment]
Also, just noticed the number of logs doesnt change as you pick up/put them down, like regular logs do. Match their setup to get this behavior.

**Comment by keegan-o** [comment]
I changed the behavior/style of this to show the same mesh as when it is on the ground, so there is a 1:1 correlation visually (only the first person versions have some extra geometry for better lighting/detail) that makes sense.
