### ISSUE TITLE
USER ISSUE: Map Bug

### ISSUE THREAD

**Issue by Gnorantone** [StrangeLoopGames/EcoIssues#8986]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
Hi, i have a problem, every time i open the game map, my connection go to 29 ms a 170 ms and a red belt (connection problem) appear, and even if i slog and relog the problem remain, and i can't play in my friend's server. Thank you for reading, regards.

Umberto.

**Comment by SeanAtr0n** [comment]
Can you join other servers? Could you please send us your output log from here after failing to connect?

`%APPDATA%\..\LocalLow\Strange Loop Games\ECO`  (can paste into explorer)

**Comment by Gnorantone** [comment]
here it is.

[output_log_copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2311842/output_log_copy.txt)

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2311845/output_log.txt)

**Comment by SlayksWood** [comment]
I assume this issue is no longer occurring with new minimap
