### ISSUE TITLE
[SERVER] The namespace 'Eco.Mods.TechTree' already contains a definition for 'SkidSteerObject'

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#8989]
Version: 0.7.6.3 beta Server

Steps to reproduce:
Try to start the server by clicking on EcoServer.exe

Expected behavior:
Expect the server to start properly

Actual behavior:
Crash! 

I get the following message when I try and start version 0.7.6.3 Beta
of the Eco server.  There are no other mods installed or anything 
like that. 

I even tried removing everything from the Eco Server directory 
and unzipping everything from the zip file and still get issues. 

The error that I am getting is bellow

--BEGIN DUMP--
Dump Time
08/16/2018 20:36:32

Exception
Exception: Exception
Message:Error in SkidSteerObject at 19: The namespace 'Eco.Mods.TechTree' already contains a definition for 'SkidSteerObject' (CS0101)

Source:Eco.ModKit

System.Exception: Error in SkidSteerObject at 19: The namespace 'Eco.Mods.TechTree' already contains a definition for 'SkidSteerObject' (CS0101)

   at Eco.ModKit.RuntimeCompiler.HandleCompilerError(CompilerResults results)
   at Eco.ModKit.RuntimeCompiler.LoadOrCompileMods()
   at Eco.ModKit.ModKitPlugin..ctor(ManualResetEvent doneEvent)

--END DUMP--

**Comment by BlazeGuy2** [comment]
Closing due to #9259 being open.
