### ISSUE TITLE
Cancelling order for flour at mill crashed server

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#899]
Eco 0.5.0 hotfix ?

Want to relocate the food mill, so removed the windmill that was powering it. Cancelled the order for 10 flours at the mill, and immediately the server went offline.

Don't know if it is repeatable as I don't want to try again, so am moving the windmill back until the orders complete.

**Comment by MarjieAVolk** [comment]
Not immediately seeing a problem with the Mill - I believe there were some fixes to the Mill in 5.5, so closing for now.  If you see a problem like this again, open another bug and include logs/dumps if possible.  Thanks!
