### ISSUE TITLE
Camera is at neck-height

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#8992]
![image](https://user-images.githubusercontent.com/6262198/44282543-38262300-a210-11e8-8437-22442bedc19e.png)
Makes you feel short

**Comment by SlayksWood** [comment]
Seems fixed.
![image](https://user-images.githubusercontent.com/45708377/72526395-59f95e80-3877-11ea-9f05-fa6a82c420a7.png)
