### ISSUE TITLE
[7.7.0] Changing Resolution from menu doesn't actually change the ingame screen resolution for windowed mode

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8993]
Can't change if from 1920x1080 in the menu, can only do so manually.

Edit: only occurs in windowed mode

**Comment by metachronism** [comment]
seems to work for me

**Comment by metachronism** [comment]
unless you mean when in windowed mode only

**Comment by BlazeGuy2** [comment]
Yeah, windowed only.  My b, shoulda mentioned that.

**Comment by Nanders** [comment]
I'm closing this as intended behavior
