### ISSUE TITLE
[7.7.0] Disabled audio source in log

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8994]
May be tough to trackdown, priority may drop.

(Filename:  Line: 447)

Can not play a disabled audio source

**Comment by BlazeGuy2** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2298937/output_log.txt)

**Comment by seccombew** [comment]
Related to opening escape menu.

**Comment by Nanders** [comment]
Why is this high priority? Bug has existed for like 2.5 years.

Its because the sliders call OnChanged when they are first initialized (as they load the saved settings)

**Comment by WeaselDog** [comment]
Haven't seen this as an issue recently. Please reopen if necessary
