### ISSUE TITLE
[7.7.0] Exception in log w/ AvatarEditingSafetyBubble

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8997]
(Filename: <bdca591c120a4ad8b908fd1c9d4d8dd9> Line: 0)

Setting up 4 worker threads for Enlighten.
  Thread -> id: 4b20 -> priority: 1 
  Thread -> id: 2b20 -> priority: 1 
  Thread -> id: 41c0 -> priority: 1 
  Thread -> id: 2dc -> priority: 1 
NullReferenceException: Object reference not set to an instance of an object
  at AvatarEditingSafetyBubble.OnDisable () [0x00005] in <bdca591c120a4ad8b908fd1c9d4d8dd9>:0

**Comment by BlazeGuy2** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2298932/output_log.txt)

**Comment by SlayksWood** [comment]
Seems fixed.
