### ISSUE TITLE
[7.7.0] Meteor Icon for tut is blank on Spanish Server

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#8998]
Icon is missing for meteor tut when server language is set to Spanish.

![meteoriconmissing_onspanishserver](https://user-images.githubusercontent.com/35509188/44292421-4b011d80-a239-11e8-886f-d6818c59c92d.PNG)

**Comment by johnkslg** [comment]
The icon is found via string lookup. It's probably trying to lookup the localized string and not finding the icon.

**Comment by Nanders** [comment]
This should be fixed via https://github.com/StrangeLoopGames/Eco/pull/3386
