### ISSUE TITLE
Aqueducts look wrong and don't work

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#900]
http://ecoforum.strangeloopgames.com/topic/1167/aquaduct-blocks

**Comment by keegan-o** [comment]
![image](https://cloud.githubusercontent.com/assets/14983165/21202650/15d6f722-c204-11e6-9737-14ef08662028.png)
I fixed the builder and such, but AqueductBlock is still broken in that it does not preserve water flow any differently than other blocks.

**Comment by metachronism** [comment]
craig fixed this, was missing an attribute on aqueductblock

**Comment by IcedForge** [comment]
Seems like its broken down again
https://s28.postimg.org/m705che0d/eco_aqueduct_issue.jpg
Tried having water flow from the same height, and from dropping down into the aqueduct as well, neither is allowing water to flow more then a few tiles.
