### ISSUE TITLE
0.7.7 Assembly Line - no power requiments.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9000]
![default](https://user-images.githubusercontent.com/4980243/44295497-9dcaeb80-a2b2-11e8-94f9-0d50686d2f1c.png)

**Comment by Deantwo** [comment]
Is it supposed to have a power requirement? I thought it was hand cranked.
But I guess it could require some mechanical power.

**Comment by elfl0rd** [comment]
Looks like machinery... Yes, i guess too - mechanical power is better for it.

**Comment by elfl0rd** [comment]
Dupe - https://github.com/StrangeLoopGames/EcoIssues/issues/8388
