### ISSUE TITLE
Elections are buggy as hell

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9001]
About 3/4 of our players can't vote at all - red bar issue.

The ones that can have a problem - as soon as a second guy votes, the votes get reset to 0 again, then i vote again and there shows two votes. Then as soon as someone else votes it's 0/0 again. And so on. And most can't vote, as i said above.
<img width="1321" alt="election" src="https://user-images.githubusercontent.com/25908592/44299617-202ace00-a2fa-11e8-984b-e0fa298a395c.png">

**Comment by seccombew** [comment]
What version is this occurring on?

**Comment by D3nnis3n** [comment]
7.6.3

It also often says i voted for "George". We do not have any George.

**Comment by Voosle** [comment]
#8381

**Comment by johnkslg** [comment]
Should be fixed in 7.7 staging

**Comment by johnkslg** [comment]
@BlazeGuy2 can you verify?

**Comment by BlazeGuy2** [comment]
Seemed fine in our show n' tell

**Comment by SeanAtr0n** [comment]
saw this behavior during show n tell

**Comment by BlazeGuy2** [comment]
Did the vote reset, it seemed fine when 3 people voted?  Thought the issue was the name bug.

**Comment by SeanAtr0n** [comment]
I ran for office then you ran for office then i tried to vote for my self and left you as -, then no matter what I did I couldn't vote and have it show up

**Comment by D3nnis3n** [comment]
It's about the name bug and the election reset of votes, yes.

**Comment by D3nnis3n** [comment]
Both bugs did not occur in three elections since release of 7.7 - you probably can close this issue.

**Comment by D3nnis3n** [comment]
That was fast.

**Comment by BlazeGuy2** [comment]
I have an email subscription to all issues I'm attached to.
