### ISSUE TITLE
Can't creat skill scroll

### ISSUE THREAD

**Issue by timmm298** [StrangeLoopGames/EcoIssues#9002]
I created a Basic Engineering Skill Book, but I can't create Basic Engineering Skill Scrolls out of it. Does anyone know why that isn't possible? I have created several Basic Engineering Skill Books, but with all I have the same problem. With other Skill Books, it is not a problem to create Skill Scrolls.

**Comment by Nicolausi113** [comment]
I’ve done on v7.6.3 and worked, right click the book and get a scroll (maybe you need one inventory slot at least?)

**Comment by timmm298** [comment]
It is limitted to one specific server.

**Comment by Nicolausi113** [comment]
If that server uses mods, could be an explanation, otherwise it’s corrupted.

**Comment by BlazeGuy2** [comment]
Need more info about the server you're on.  If you are running mods, check to see if this occurs on a vanilla version.

**Comment by timmm298** [comment]
The server is ‘Planet of Agartha discord.gg/CuBreNQ EN/NA’

**Comment by elfl0rd** [comment]
@BlazeGuy2 ? Maybe can be closed due to modifications problem?

**Comment by D3nnis3n** [comment]
Likely caused by a mod, reopen if issue persists.
