### ISSUE TITLE
[7.7.0] Countless plants from one seed

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9004]
Version: 0.7.7.0-beta-staging-13e8d143

Planting/sowing seeds does not degrease the count in inventory, you can plant infinitely.

![endless seed2](https://user-images.githubusercontent.com/38510829/44300035-a0ecc880-a300-11e8-9cc4-6f8700e365d2.jpg)

**Comment by BlazeGuy2** [comment]
Reproduced it with the tomato seeds.
