### ISSUE TITLE
Broken Map

### ISSUE THREAD

**Issue by Revirks** [StrangeLoopGames/EcoIssues#9006]
My map has been broken for a couple of days. It does not work on any server, here is a picture on how it looks. 
https://steamcommunity.com/sharedfiles/filedetails/?id=1481994618

I have tried Verifying the game files on steam, reinstalling, different graphic settings, updating drivers on my windows 10 pc. I made sure the .NET is up to date. 
I got some pointers from the very helpful "Pam" on the Eco discord, to delete the eco file under appdata and some other steps. Nothing of that worked either unfortunately.

Hoping i could get some help from you.

//Regards 
/From Revirks

**Comment by SeanAtr0n** [comment]
are your graphics drivers up to date?

Turning down minimap detail in graphics settings should make the lower level map appear

Could you send us your log file from 
`%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

**Comment by Revirks** [comment]
Graphics drivers are up to date.

Turning down the minimap detal in graphic settings did however work! i had them on maximum and i lowered them to aprox half.
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2314299/output_log.txt)

**Comment by D3nnis3n** [comment]
Not reproducable, reopen if it reoccurs.
