### ISSUE TITLE
USER ISSUE: Can see through blocks at certain angles

### ISSUE THREAD

**Issue by NtropicZ** [StrangeLoopGames/EcoIssues#9007]
**Version:** 0.7.6.3 beta

![image](https://user-images.githubusercontent.com/1012441/44306118-a91f2500-a34d-11e8-84aa-5c9cacf2bbd1.png)

**Comment by Nicolausi113** [comment]
I’ve experienced this too, but it disappeared after a short while. Guessing it has to do with junk loading?

**Comment by metachronism** [comment]
fixed in 7.7
