### ISSUE TITLE
Cant dig with Excavator and Skid steer

### ISSUE THREAD

**Issue by Seelm88** [StrangeLoopGames/EcoIssues#9008]
Cant dig with Excavator and Skid steer, ground act as bedrock. The movement of machine works fine but it doesnt pick up or break the ground. Have tried Dirt,Stone and Iron ore. 
Server is public with pw, if wana try and find a fault, Discord : Seelm#0619

**Comment by SeanAtr0n** [comment]
The skidsteer can't dig below itself as that would be fairly unrealistic and leads to some pretty annoying physics problems if we allow it.

The excavator can dig below itself, are you sure you were holding down the left mouse button in the excavator?

**Comment by Seelm88** [comment]
Yeah, i did find the problem. It was the left mouse button. could not find any information about it. And now with the crane, it say click on stock pile. but nothing happens.


//

Fredrik Karlsson

073-8 444 103

________________________________
Från: Sean Ater <notifications@github.com>
Skickat: den 21 augusti 2018 01:39
Till: StrangeLoopGames/EcoIssues
Kopia: Seelm88; Author
Ämne: Re: [StrangeLoopGames/EcoIssues] Cant dig with Excavator and Skid steer (#9008)


The skidsteer can't dig below itself as that would be fairly unrealistic and leads to some pretty annoying physics problems if we allow it.

The excavator can dig below itself, are you sure you were holding down the left mouse button in the excavator?
