### ISSUE TITLE
USER ISSUE: not any jobs

### ISSUE THREAD

**Issue by macgameur** [StrangeLoopGames/EcoIssues#9009]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
in LAN server

**Expected behavior:**
It should have 9 jobs

**Actual behavior:**
but they are 5 jobs

**Comment by BlazeGuy2** [comment]
What do you mean by jobs?  Is this in game?

**Comment by BlazeGuy2** [comment]
No response, closing.
