### ISSUE TITLE
Only Logging in First time for the day (or after totally Quitting Eco and coming back) is the ability to see EcoSystem Tooltip about Species

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9011]
**Version:** 0.7.6.3 beta

![snap2444](https://user-images.githubusercontent.com/29383891/44358286-75a6dc80-a4ac-11e8-8aee-0dba95a6650b.png)
This Window (if i got what you are calling it wrong)
![snap2445](https://user-images.githubusercontent.com/29383891/44358339-9cfda980-a4ac-11e8-9c79-fa2965b0bc78.png)
i like to check how things are growing or dying (i'm sure other player like to also see this information)
(this is a **MUST** if playing in a world where Meteor is due to hit and i need to collect stuff, and then check status **AFTER** meteor has hit)
 its a Real pain to get this window up unless logging in for the first time for the day (because if you play a lot of hours the chat window is full, even after a Disconnect and the Join again)

i think what we need is like a Button to click or a Key Press to bring this up, maybe have other options in it like the ability to sort each column, (Alphabetical, Lowest to highest and + or - (for the last column)
Linking this one as something was mentioned about List Sorting
Welcome Message Ecosystem List Sorting #8761

i tried a Search for this, i know i have Spoken to @MarjieAVolk  at some point, but not sure if it was in  Github or was in Discord (so doing another Github for this)
If i have done a Duplicate feel free to close ❤️

**Comment by Conchipedia** [comment]
Yes, so its not hidden as a piece of text that u can click on (that's if you can find it after trying to filter out text after playing for hours) so we have a little Window for it likr we do Bottom right
![snap2447](https://user-images.githubusercontent.com/29383891/44359103-cae3ed80-a4ae-11e8-8aae-0718857272cf.png)
it might mean a bit of a re-design if a clickable place is made for it on this

**Comment by MarjieAVolk** [comment]
Maybe we should replace the bottom right button (G) that normally takes you to your browser with this.  Then the window can have like a light view of graphs / environment data, and the window would provide the link to view all the graphs in browser.

**Comment by Conchipedia** [comment]
i hate using the Graphs they don;t make any sense what so ever, maybe that's just me being a bit dim, i like to see the Built in window that pops up , so i can work out with numbers going up or down or the green or red in the + - bit

**Comment by MarjieAVolk** [comment]
No that's totally valid, actually I don't think they have worked correctly in a long time, if ever.

**Comment by Conchipedia** [comment]
when i say Graphs not making any sense is something like this one for Ground Pollution (i made A Volcano out of Tailings (they a permanently there) but this graph is say 0 regularly
![snap2448](https://user-images.githubusercontent.com/29383891/44359726-9bce7b80-a4b0-11e8-8e34-971aafe18876.png)

**Comment by MarjieAVolk** [comment]
oooo that's not good, didn't realize that was still an issue.

**Comment by Conchipedia** [comment]
![snap2449](https://user-images.githubusercontent.com/29383891/44360116-b6edbb00-a4b1-11e8-9759-d1bc63b407a7.png)
see how clearer this is 😄

**Comment by MarjieAVolk** [comment]
Moving this to suggestions for now, since this is a big and open ended idea https://github.com/StrangeLoopGames/EcoSuggestions/issues/507

**Comment by Conchipedia** [comment]
Trust your judgement as always @MarjieAVolk  ❤️
