### ISSUE TITLE
Lower Part of Economy Viewer is a Real pain to see (we have a little slider, but could do with an ability to make this lower window bigger or smaller as we can the Whole Window)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9012]
**Version:** 0.7.6.3 beta

![snap2446](https://user-images.githubusercontent.com/29383891/44358862-18ac2600-a4ae-11e8-89b8-917f90b83079.png)
where it shows (Conchita Credit) (Maxinertia Credit) etc is the part of the window i am talking about

**Comment by johnkslg** [comment]
Make this a draggable window

**Comment by elfl0rd** [comment]
and resizable \ movable columns, please!

**Comment by johnkslg** [comment]
Modify this UI to allow resizing the rows

**Comment by johnkslg** [comment]
Fixed!
