### ISSUE TITLE
Dead plant does not look dead

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9016]
![image](https://user-images.githubusercontent.com/3536496/44374097-68d0bb80-a4a1-11e8-9717-2f6a20604c6b.png)

**Comment by BlazeGuy2** [comment]
@johnkslg can you prioritize it?

**Comment by WeaselDog** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4887
