### ISSUE TITLE
USER ISSUE: Invisible Stump

### ISSUE THREAD

**Issue by NtropicZ** [StrangeLoopGames/EcoIssues#9017]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
Chop down a tree and then chop down the stump. An invisible stump will remain. You cannot build on the tile, and you can't get rid of the stump. 

**Expected behavior:**
Stump should be gone?

**Actual behavior:**
Invisible stump remains

![image](https://user-images.githubusercontent.com/1012441/44378625-d7287480-a4c7-11e8-9fcd-53fade225c8b.png)

**Comment by NtropicZ** [comment]
Workaround: Restart game

**Comment by wolfgangmeyers** [comment]
I'll take a look at this one

**Comment by johnkslg** [comment]
@mirasrael was this fixed already?

**Comment by johnkslg** [comment]
May no longer exist @wolfgangmeyers see if you can repro

**Comment by SeanAtr0n** [comment]
nick fixed this
