### ISSUE TITLE
USER ISSUE: Your HIDDEN DRM is not working

### ISSUE THREAD

**Issue by Vassili3** [StrangeLoopGames/EcoIssues#9019]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
1.Launch the game you paid 30€.
2.Be very disappointed by the fact he ask to logon (DRM).
3.Put your username and password you have made on the strangeloopgames website.
4.Be furious because the DRM is not working, like often with DRM...
5.Press the "signal a bug" button.
6.Be more disappointed by seeing you can not report a bug because strangeloopgames ask to create an account on a third party platform (that i do not like, AND are a Microsoft property...).

**Expected behavior:**
WORK, and without DRM bullshit.
I will never buy strangeloopgames again, as they are doing the same thing that Steam (but did not said it on the system requirements).

**Actual behavior:**
The following error message popped up:
```
Invalid username or password.
```

**Expected future behavior:**
Play the game with a crack and saying to do that to everybody.

**Comment by johnkslg** [comment]
Walker can you follow up with @Vassili3 and see why their username is not working? 
@Vassili3 you're certain it's the correct username and password?

**Comment by johnkslg** [comment]
We use the account system to verify users are who they say they are when they login to the server. This is in addition to protecting the game from pirating. Sorry for the problems you ran into with it.  The master server issue I have seen as well, we are trying to track down what is going on there.
