### ISSUE TITLE
Cart get's shooted into atmosphere

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9022]
We had that issue before. It's still there in 7.6.3 - i got launched into atmosphere on getting into a cart twice and another guy got launched once. It happens more rarely, you are not launched that further anymore and you can't fly anymore in the atmosphere but will fall down extremly fast, but you will be somehwere else on the world - in my case on a 16 km² world that can be 5 km away. Not nice. Unfortunateley, i have no idea how this is reproducable.

**Comment by BlazeGuy2** [comment]
The fix is on 7.7

**Comment by D3nnis3n** [comment]
This is NOT fixed on 7.7, just happened on staging. Drive with a cart into another one and it still might happen.

It also happens everytime when you drive somewhere where a cart is standing, but you can't see it as of a bug when it's invisible.

The same applies to trucks and steam trucks.

@BlazeGuy2
