### ISSUE TITLE
[7.7.0] Stairs can’t be placed on a wall in certain direction

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9023]
Version: v0.7.7.0-beta-staging-13e8d143

Steps to reproduce:
Try to build stairs on a wall, because a fourth row can not be reached in height.

Expected behavior:
The stairs should place as direction is selected. This could be done in former versions.

Actual behavior:
The stairs flip direction in the moment of placing and in addition it is depending on point of compass.

before placing
![stairs4](https://user-images.githubusercontent.com/38510829/44401715-d0dddb00-a54f-11e8-83a8-d2ca50378e00.jpg)

after placing
![stairs3](https://user-images.githubusercontent.com/38510829/44401740-e94df580-a54f-11e8-9ab7-b501197d8121.jpg)

**Comment by Nicolausi113** [comment]
It seems fixed with recent v7.7 #b938b54c

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/9292

**Comment by Nicolausi113** [comment]
fixed with v8.x
