### ISSUE TITLE
[7.7.0] Tooltip pops up on left click and hinders work

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9024]
**Version: v0.7.7.0-beta-staging-13e8d143** (and former)

**Steps to reproduce:**
Try to drag an object from a storage slot without hoovering too long over the icon.

**Expected behavior:**
No tooltip should pop up and the objects can be moved quickly.

**Actual behavior:**
Exact in the moment of left click, tooltip pops up instantaneously and in many cases blocks the place meant for dropping. 
In addition, tooltip does not fade out as long left mouse is pressed and the cursor moves within tooltip window (feels like annoying fly's).

Especially for this v7.7 I have experienced a few times, that tooltip did not fade out at all, even if the left mouse button was released. It was steady and blocked a part of the screen until the hole menu was closed!

Tooltip appears on left click and blocks the place to drop
![tooltip2](https://user-images.githubusercontent.com/38510829/44409673-266fb300-a563-11e8-9f6a-387c862003c2.jpg)

**Comment by Nicolausi113** [comment]
Now I see there is another post concerning this #8126

**Comment by BlazeGuy2** [comment]
Closing as dup of #8126
