### ISSUE TITLE
 Annoying way that Room score is updated every time i remove a block in the room

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9026]
**Version:** 0.7.6.3 beta

![snap2459](https://user-images.githubusercontent.com/29383891/44422649-a73aa900-a57b-11e8-8df9-2f0934acf001.png)

as can be seen above in snapshot, i'm digging dirt from an enclosed room and every time i do this the Room Score is showing, when you are doing a LOT of digging/mining this gets annoying fast with the amount of room score spam i see

**Comment by johnkslg** [comment]
Make this notice not show if the change is less than 1 since the last time it was shown, if theres been recent changes.

**Comment by sidjuego** [comment]
@johnkslg 
If I am able to understand it correctly, are you referring to the following?
Notice should not be shown if the change is less than or equals to 1; add the time stamp when the change happened; when ever the next change happens, check the last updated time with the current timestamp, and if the difference is less than or equal to some small value in seconds. 

Are you expecting this functionality?

**Comment by mindforger** [comment]
maybe make it simpler and allow for disabling this chat based info and add in some simple command to check the score manually? I mean, i only want to know the score when i finished building something not while i am building :) 

(maybe except furniture and decorations and other "placeable non-block" entities because their influence is more important and should be displayed instantly)

**Comment by sidjuego** [comment]
@mindforger So If I am understanding it correctly, this message 'Your house now provides..' would also be displayed when there's a change in furniture and decorations?

**Comment by Conchipedia** [comment]
i didn't expect the room score to display every time i removed a block from it, this seems to be more for Miners who have Braziers in this room (as they are counting towards room score in a mine) and its not even made a change, its always the same score as nothing but a block removal has changed it's not as if i just added another item to change the score

**Comment by johnkslg** [comment]
It should display the message only if the amount has changed a lot (more than 1) since the last notice, or if its been more than a few minutes.
If the change is zero, it should not display at all.
