### ISSUE TITLE
Law or/and have double ex buttons

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#9027]
![image](https://user-images.githubusercontent.com/23460210/44427811-6e80dc80-a547-11e8-94ce-3a77a6ca6c67.png)

**Comment by Tigran07** [comment]
![xx](https://user-images.githubusercontent.com/34332277/44942702-26747c00-adc9-11e8-8207-af71f0bae553.png)

**Comment by MarjieAVolk** [comment]
Might only happen on the condition or/ands then, not on the action queries.

**Comment by rainfarmer** [comment]
cant recreate in months
