### ISSUE TITLE
Version Stamping a new build doesn't update properly

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#9032]
Version stamp and hash gets generated on first build, then never updates again unless I purge the old folders on the Marmot machine.

**Comment by BlazeGuy2** [comment]
Also, version stamp crashes build on first run in jenkins.
[log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2308472/log.txt)

**Comment by seccombew** [comment]
Fixed by Metachronism
