### ISSUE TITLE
[7.7.0] Starter camp isn't linking to small stockpile by default anymore

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#9034]
When running through the tutorials, linking inventories isn't explained to players, which may confuse new users.  Either Enable it again or demonstrate how to link inventories in a tutorial.

**Comment by craig-jong** [comment]
duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/9068

**Comment by craig-jong** [comment]
fixed in above pr
