### ISSUE TITLE
Laws: extra newlines on web client

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#9035]
There are extra newlines around conditions for 'on law passed' conditions:
![image](https://user-images.githubusercontent.com/23460210/44433506-721e5e80-a55b-11e8-9622-8db92c665758.png)

Compare to the correct behavior on 'prevent action'
![image](https://user-images.githubusercontent.com/23460210/44436248-0642f280-a569-11e8-9747-2fc595b51bf6.png)

The format strings for these are the same, as far as I know.

**Comment by rainfarmer** [comment]
old issue
