### ISSUE TITLE
Can't vote with special Character in name.

### ISSUE THREAD

**Issue by X-ITT** [StrangeLoopGames/EcoIssues#9038]
If you have a special character (ex. ™) in your name, voting doesn't work.

**Comment by Deantwo** [comment]
What voting? Laws or voting for office?
Voting how? Web interface?

**Comment by X-ITT** [comment]
Voting in both laws and leader through web interface.

**Comment by anatoly-slg** [comment]
verified, issue does not appears in 8.1.4 version.
