### ISSUE TITLE
Laws - Time Performed Hard to Understand

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#9039]
I have never seen anyone use the "Time performed" where clause correctly. It is just too hard to use, and even harder to read for non-programing educated players.
I suggest that it gets changed into something that makes more sense. Or at least some simplified versions added alongside the current.

After talk with @MarjieAVolk on Discord we agreed on a few ideas. This issue is to get it all in writing and get a little more feedback. Feel free to add to this!

Currently to implement a "limit nber of actions per day" law would look like this:
```
When attempting to Harvest where (species is Kelp)
    If your Harvest actions where ((species is Kelp) and (time performed (days) > (current time (days) - 1))) > 5
        Then prevent
    Otherwise allow
```
And if you want to make a law that only count actions done after the law was passed:
```
When attempting to Harvest where (species is Kelp)
    If your Harvest actions where ((species is Kelp) and (law passed (days) > current time (days))) > 5
        Then prevent
    Otherwise allow
```

Make simpler (but less flexible) options, such as:

- [ ] Performed in the last X days

This would simplify the above example law a lot and make it so much easier to understand by a common player.
```
When attempting to Harvest where (species is Kelp)
    If your Harvest actions where ((species is Kelp) and (performed in the last 1 days)) > 5
        Then prevent
    Otherwise allow
```

- [ ] Performed after law passed

Ignore all actions performed before the law was passed.
For example preventing a player from doing an action more than a specific amount of times would currently be a confusing law if you have to perdon all the times they did it before the law was passed.
Instead this would allow for:
```
When attempting to Harvest where (species is Kelp)
    If your Harvest actions where ((species is Kelp) and (performed after law passed)) > 5
        Then prevent
    Otherwise allow
```

- [ ] misc

Change the current "Time Performed" to use something more understandable than `<` and `>`. Maybe `before` and `after` would make more sense.
Maybe instead of adding "(days)" to all the law options that use a timestamp, why not just write "(timestamp)"?

**Comment by Deantwo** [comment]
Just a quick idea that just hit me. Maybe instead of writing anything for the "(days)" thing note, why not add an icon?
Could use 📅 or something to indicate that this value is a timestamp-style value.

**Comment by johnkslg** [comment]
We can basically introduce a new variable that that calculation, 'Days since last login' or some such. It's cool you can construct that query organically but we should also support easy implementations of commonly needed handling, especially as it relates to player activity detection.

**Comment by D3nnis3n** [comment]
Bumping this to semi-high priority. An easier way to do this is wished.

**Comment by Knigge** [comment]
>>High Priority>>

**Comment by johnkslg** [comment]
This has been fully replaced with something that makes sense.
![image](https://user-images.githubusercontent.com/3536496/68906313-b2d23c80-06f8-11ea-9da5-9ed40da7f059.png)
![image](https://user-images.githubusercontent.com/3536496/68906324-b9f94a80-06f8-11ea-9b80-d744d42269f4.png)

Also, 'Active' 'Abandoned' and 'Everyone' are default demographics now that can be configured by admins to determine timings involved.

**Comment by D3nnis3n** [comment]
Yep, looks good now.
