### ISSUE TITLE
USER ISSUE: Electric Lathe doesn't work

### ISSUE THREAD

**Issue by Tomuro86** [StrangeLoopGames/EcoIssues#9040]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
1. Select a Electric Lathe in your house
2. Try to watch the crafting tab
3. The posible items for create doesn't appears

**Expected behavior:**
It shoud have electronic items to create

**Actual behavior:**
Instead it, "craft" options in this machine is empty

**Comment by Tomuro86** [comment]
Thanks @Deantwo , I've compared between the room with the Electric Lathe and without it, but the result is the same, the Electric Machinist Table has same craft items. I've attached an screenshoot.

![image](https://user-images.githubusercontent.com/42614662/44475705-0a891180-a636-11e8-8dfb-c9563896ff5f.png)
 Thank you!

**Comment by Deantwo** [comment]
The **Electric Machinist Table** requires an **Electric Lathe** in the same room before it can make an **Electric Planer**.
![image](https://user-images.githubusercontent.com/2676134/44478380-d0bc0900-a63d-11e8-9545-9d5625214a32.png)

**Comment by Deantwo** [comment]
Anyway, this is a duplicate of #8800.

**Comment by Deantwo** [comment]
It does not look like the **Electric Lathe** has any other use.
It will likely be fixed in the next update.

**Comment by seccombew** [comment]
Dupe

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/8547
