### ISSUE TITLE
Laws: Extra newline on some law clauses

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#9044]
On the demographics branch, I updated some section hierarchy in the law format strings to be more consistent across the different clauses.  This causes the string to display more correctly in the flat string view.  However, it has the opposite effect on the drop down view.

Most look like this:
![image](https://user-images.githubusercontent.com/23460210/44483767-cfb8b680-a600-11e8-8118-819fc8dff210.png)

Prevent action looks like this:
![image](https://user-images.githubusercontent.com/23460210/44483775-d47d6a80-a600-11e8-9398-b8f0365a69c0.png)

As far as I know, the format string section hierarchy here is pretty similar between the two, and has the same depth.

**Comment by WeaselDog** [comment]
Fixed in 9.0
