### ISSUE TITLE
Law: extra newline in new remove demographic clause

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#9046]
There is a mysterious extra newline before 'Citizen' here.  There are no sections there at all.
![image](https://user-images.githubusercontent.com/23460210/44490082-2e3a6080-a612-11e8-8288-f84a8e265149.png)

On all other views of the text, there is no newline:
![image](https://user-images.githubusercontent.com/23460210/44490180-73f72900-a612-11e8-8990-5175583414c5.png)

**Comment by MarjieAVolk** [comment]
It's possible this is just due to wrapping I suppose?  Though there is lots of extra screen width, and there are instances of the window getting wider without wrapping.

**Comment by rainfarmer** [comment]
laws moved to in-game
