### ISSUE TITLE
Brick block next to stone lets you see through the world

### ISSUE THREAD

**Issue by NathanaelMangold** [StrangeLoopGames/EcoIssues#9047]
If you place a brick block next to a natural stone in the world (as in the screenshot) you can see through the world. Not a big issue but I think it still should be fixed.

![20180822231352_1](https://user-images.githubusercontent.com/41338825/44491518-d0ce0000-a661-11e8-8cf3-a4de58d2cbbe.jpg)

**Comment by elfl0rd** [comment]
dupe https://github.com/StrangeLoopGames/EcoIssues/issues/4286

**Comment by NathanaelMangold** [comment]
Sorry, I searched but I was not able to find anything!

**Comment by elfl0rd** [comment]
No problem :)

**Comment by metachronism** [comment]
closing as dupe
