### ISSUE TITLE
Exception on connect

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#9048]
Got an exception on the client on connect, this.connectionAttempt was null:
![image](https://user-images.githubusercontent.com/23460210/44495071-45ce1500-a623-11e8-94f2-612f9863bb3e.png)

Client stuck in 'Connecting' forever after this happened.  Not sure what the issue was, as far as I know I was connecting to my local server the same way as always.  Maybe a race condition?

**Comment by johnkslg** [comment]
Looks like should be high pri?
