### ISSUE TITLE
Roof builder issues

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#9049]
Couple weird cases when using two different roof types together.

![image](https://user-images.githubusercontent.com/23460210/44496137-ec1c1980-a627-11e8-9677-989438ad29a1.png)

![image](https://user-images.githubusercontent.com/23460210/44496144-f3dbbe00-a627-11e8-83b5-607b88130e07.png)

**Comment by SlayksWood** [comment]
merged to #12476
