### ISSUE TITLE
Election: "Voted for George" - No user George!

### ISSUE THREAD

**Issue by MaxInertia** [StrangeLoopGames/EcoIssues#9051]
**Version: 0.7.6.3 beta**

1. Player A runs for office votes for himself,
2. Player B runs for office and votes for himself,
3. Player A removes self from ongoing election and votes for B.

Player B (**MaxInertia**) now sees this in the Government window:
![image](https://user-images.githubusercontent.com/12981415/44497563-d1559f00-a63f-11e8-9cfa-8fbc8552f7c2.png)

B is able to change his vote (back to himself) then it shows this:
![image](https://user-images.githubusercontent.com/12981415/44497586-f5b17b80-a63f-11e8-877a-82cf00c7d181.png)

No one on the server has the username **George**!

**Comment by MaxInertia** [comment]
Fix appears to be in staging, so I'll close this.

https://github.com/StrangeLoopGames/EcoIssues/issues/9001#issuecomment-414553823

**Comment by MarjieAVolk** [comment]
Yeah I don't think it's really a duplicate.  Looks like 'George' is the placeholder text, so this just means there was an exception during the initialization of this UI.  Thanks for the repro steps, I will try it out.

**Comment by LiaungYip** [comment]
Occurring on 7.7.0 Staging as well.
