### ISSUE TITLE
Electric Stamping Press quantity labels not updating in all cases

### ISSUE THREAD

**Issue by MaxInertia** [StrangeLoopGames/EcoIssues#9052]
**Version: 0.7.6.3**

The **Electric Stamping Press** shows incorrect values for the quantity of required items the user has, as well as the number of required items to craft the selected quantity of the recipe product.

Prior to these images I ordered 4 **steel plates**, and since then the table displays that I have 4 **steel** in my inventory.

---

In this image I have no **steel** in my inventory:

![image](https://user-images.githubusercontent.com/12981415/44504176-efcb9280-a65f-11e8-8582-a7392247623f.png)

---

Here I change the quantity to produce to 4, but the requirement remains 1:

![image](https://user-images.githubusercontent.com/12981415/44504213-1db0d700-a660-11e8-8737-c3035e08b4bc.png)

On attempting to craft more (without steel in my inventory) it **does** state in the queue that it requires 4 steel (so this cannot be used to create endless steel plates as far as I can tell).

On returning to the table with 15 steel in my inventory, the value does update to show that. But when I get rid of the steel **it does not drop** to 0.

Also note that the table does not connect to any storage containers; there is no storage tab.

**Comment by D3nnis3n** [comment]
Can confirm this.

**Comment by GophTheGreat** [comment]
Appears to be fine now. Closing.
