### ISSUE TITLE
Population number problem on server setup

### ISSUE THREAD

**Issue by Lucky7Life3** [StrangeLoopGames/EcoIssues#9053]
Hi. 
I've tried to set up a public server and managed it. The problem I always meet seems that the server will not change the number of max player on server no matter what I do.

Difficult settings:
CollaborationPreset:  MediumCollaboration

Network:
PublicServer: True
Password: xxxx
HashedPassword: xxxx
Description:  Noob Friendly - Focus on Co-op - EN/NO in chat only - 4km2 map
IPAdress: Any
GameServerPort: 3000
WebServerPort: 3001
Rate: 10
MaxConnections: 20 

MaxConnections is changed from -1 who was infinitive, had no effect with or 20. The server has only access for 1 person that is the admin.

I saw another forumabout the same problem, and the answer was to send the message here to you ppl. I hope you can help me, and can help you with the game dev.

Mvh
Leo P.

**Comment by seccombew** [comment]
You may need to restart the server for the max connections number to stick.

**Comment by Lucky7Life3** [comment]
I have done that about 10 or more times, with 3 different server created. But thanx for the reply.

**Comment by SlayksWood** [comment]
Checked on 8.2.4 with a small number of people. Wasn't able to reproduce, seems fixed.
![image](https://user-images.githubusercontent.com/45708377/60182185-7a56c280-982c-11e9-8a61-87dea54486cb.png)
