### ISSUE TITLE
USER ISSUE: User does not own Eco

### ISSUE THREAD

**Issue by hamisoulseeker** [StrangeLoopGames/EcoIssues#9054]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
Link Libary (Family)
Start Game
Join Server

**Expected behavior:**
Connect to the world

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>User does not own Eco</size>
```

**Comment by seccombew** [comment]
We don't support Steam's family sharing.
