### ISSUE TITLE
Some users do not see Admin access request to run Netsh command

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9056]
As a result their webserver silently fails to run.  
Ideally we can make the popup always appear.  At the minimum we should detect when it fails and display an error to the user to inform them. 

Marking high priority because it breaks a big set of features for a number of players.

**Comment by metachronism** [comment]
need more info or a repro case.

**Comment by johnkslg** [comment]
Mirasrael, maybe you can help us figure out this one?
Basically to open ports, the server runs a netsh command at WebServer #29 or #65.  This requires admin access to run, which usually Windows will pop up and request, but a lot of users are not getting that popup.  Maybe due to permissions on the machine or something else?  

This will be important for schools especially which have stricter security settings.

**Comment by elfl0rd** [comment]
looks like my old issue.
If i tests some things in local world, after multiple launch i receive rotating gear.
![unknown](https://user-images.githubusercontent.com/4980243/44629422-d96f5080-a957-11e8-8947-76e6541b60cf.png)
This fixes by PC restart, or
`netsh http delete urlacl url=http://+:3001/`

**Comment by mirasrael** [comment]
I wasn't able to reproduce this case (when Admin permissions dialog not appears), but I added more resilient workflow for permissions and better error handling.

**Comment by johnkslg** [comment]
Nice!
