### ISSUE TITLE
"Custom Clause" in law making

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9059]
We would like to have an option for laws where you only put a text into a field, like with the contracts to make custom laws that are voted upon, visible for everyone but must be enforced manually. This will also allow for polls through the Web UI.

For the moment we use a sign to propogate our traffic laws, which include a fine of 10 dollars for blocking roads with vehicles. This is enforced by some players made "State Police" with a car that says this.

It would be much better if such laws and others could just be made with the law tool.

//EDIT:
We also need a way to format these clauses, at the moment you can't make lists and paragraphs are just put together into a single sentence.

**Comment by MarjieAVolk** [comment]
Huh interesting.  Guess that would be easy to support.  Hm, so you could potentially put stuff like that just in the law description box, except that laws that don't have any clauses on them disappear.

You want to move it to suggestions I take it?

**Comment by D3nnis3n** [comment]
Yeh, exactly. I somehow favorited the issuetracker and forgot there are two now :/ Sorry :(

**Comment by MarjieAVolk** [comment]
Nah this is an easy and uncontroversial feature, I'll just put it on the todo list 👍

**Comment by D3nnis3n** [comment]
Haha nice, thank you.
I would have a little question i don't know where to ask, if you have Time, otherwise just forget about them:

With the new titles feature coming is it possible to rename the "Leader" position to e.g. "President"?

Will the government titles shown below the username?

Otherwise that might be things I'd like to suggest.

**Comment by D3nnis3n** [comment]
Thanks for your great kindness.

I read that the user created government titles can be named as wished so i just wanted to see if renaming is possible for the only default position of the leader that is already created when the server starts.

As for the second question i think you understood correctly. I just wanted to know if i can recognize the government title of players when they are in front of me. If that is by an Icon in Front of the name or by the written title below the name is not really important for me, but im really excited vor that feature.

I'd also love to give government titles specific rights by laws. E.g. sales tax can be changed by someone else then the leader; the secretary of Holding being able to seize land or the secretary of state being able to fine people that goes to the treasury.

**Comment by MarjieAVolk** [comment]
No problem :)  Good ideas!  Those actions should probably be added to laws, and add some default laws that limit them to the leader to start with.

**Comment by D3nnis3n** [comment]
Seems i have to afford the missing 85 dollars to get a more direct line to the devs. I love those in-depth systems.

**Comment by MarjieAVolk** [comment]
Yeah, maybe there does need to be a separate government-only action permissions system.

**Comment by D3nnis3n** [comment]
I wouldnt say it Nerds, but it would be a great addition that allows pretty great functioning self-governing System that might be interesting.

**Comment by D3nnis3n** [comment]
Sorry to bug you again, but i have some other "proposals":

I would like a description field for all government offices, where we could write, what that guy does and which powers he has.

And one question:
Will it be possible to create a mix of demographics and government title? E.g. a title "Representative", which are government officals, 5 of them be elected and only them can vote. That'll make discussing laws so much easier.

**Comment by MarjieAVolk** [comment]
Yeah a description for the title is a good idea.

I am not sure what you mean by a 'mix' of demographic and title.  You will be able to references titles in laws, if that's what you mean.  So theoretically you could allow only a certain title to vote.  (The vote action would need some extending in order to really support this, so that you could have different groups of people allowed to vote on different types of things.  But the title feature would support this type of law).

**Comment by Deantwo** [comment]
I would prefer you posted individual ideas as separate issues. They are easier to discuss that way.

**Comment by D3nnis3n** [comment]
Well, i did. But the suggestions issues don't seem to be read much, to be honest.

**Comment by MarjieAVolk** [comment]
Creating separate issues for each topic would indeed be useful, in the future.  If you are worried it won't be seen, feel free to tag me.  If you have questions or want to discuss something more, you can also message/tag me on discord.

**Comment by D3nnis3n** [comment]
Oh, well thanks for that. I already created several suggestion issues but they don't get any discussion nor view it seems. Tagging you i got a warning from Pam - so i probably won't do that, despite you allowed me. Maybe i'll shoot you a message when i feel i got a nice idea again. Thank you all for the great game!

**Comment by MarjieAVolk** [comment]
So regarding your original question, you want to support having multiple people holding the same title.  That is something I have been thinking about also.  It does raise some extra questions, like for example when does one loose a title?  Does each title need to have a term now, after which it will expire?  Can you impeach people?  Etc.  So I will have to think about it more, but I think will will probably want titles that can be held by multiple people, as you say.

**Comment by D3nnis3n** [comment]
Well i also proposed having a time each offical is elected for, that is in this issue:
https://github.com/StrangeLoopGames/EcoSuggestions/issues/513

If government titles get it it would be nice to not only set an amount of people that can be elected or instated, but also a description and a set of government powers (A fine command, restricted law making or whatever else). Also they should be elected for a given set of time. Maybe 7 days for the default, or even less. They would get out of office automatically after that time has passed. You maybe could impeach an offical - but then needing a 2/3 of the votes.

As of now people just try to make an election every day. People shut live with a decision once made for some time, though. The same applies for laws. We got a law and one minute after the people that were not happy with it start one to repeal it again. If the majority is only small that leads to on / off laws, which i personally do not find very good.

**Comment by MarjieAVolk** [comment]
I think you may be right.  Thanks for the suggestions, I will keep all this in mind as I work on titles.

**Comment by D3nnis3n** [comment]
That's all i hoped for. I don't need to be right, but i really love the system around society and would be very grateful if that can be made more in-depth even if that does mean more complexity. I'm there to help players with laws whenever they want to make some. I think most other admins are, too.

**Comment by D3nnis3n** [comment]
Oh, i'd like to add something to this proposal.

If you can make custom clauses, you should at least be able to use newlines. At the moment everthing get's made into one sentence even if written with newlines. No way to make good looking lists.

**Comment by D3nnis3n** [comment]
Uh, milestone was 7.7 but it's not in :(

**Comment by johnkslg** [comment]
You can have user descriptions now for the law as well as each section, hopefully this covers the need mostly? 

A separate bug for 'better rich text editing' could be pushed to a later date.

**Comment by beastyn** [comment]
Hmm, I don't thing that descriprion is a soulution.
Actually, you can't make trigger or effect as empty fields.
And in custom law you sould just write some text for trigger and effect.
@D3nnis3n can tell if im getting it wrong. Still. pushing it for the discussion.

**Comment by D3nnis3n** [comment]
When i talked with john he created this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/14053

This was meant for having simple only-text laws without clauses.
In general that's all we need for now. A rich-text editor for that can be done in its own issue for a later date.

**Comment by beastyn** [comment]
ok. closing
