### ISSUE TITLE
Leader Objective is not shown in the entering field when too long

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9060]
When you write in a long objective, eg. several sentences only the first words can really be seen in the field where you type them, the rest of the typed in words are there, but invisible, so it's very hard to e.g. find a typing error in the last sentence.

**Comment by johnkslg** [comment]
Can you make this dialog autoexpand to fit longer sentences?  Use content size fitter/vertical layout/etc

**Comment by D3nnis3n** [comment]
Seems fixed.

**Comment by Deantwo** [comment]
This was still an issue in v0.7.9.x, might need to check again.

**Comment by SlayksWood** [comment]
It's fixed in 8.2: #12221
