### ISSUE TITLE
Add Item Tags

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9061]
![image](https://user-images.githubusercontent.com/3536496/44557709-c3158a80-a6f4-11e8-91d5-16945b071b5d.png)
The Filter dialog now has item tags that let you choose items.  Apply useful item tags to everything.
You can put the tag on the item, the worldobject it creates, or a component on that world object, and it will find it. Use the ItemTags attribute.

Also, assign tiers to every item.  Tiers can be decimal and it will put it into the next lowest integer tier.

You can also make different tag categories, for tags that overlap.  Right now there is just one tag category (Tiers) and every other tag goes into the 'none' category.  When filtering, you can select up to one tag from each category.

**Comment by metachronism** [comment]
wait for PR approval
