### ISSUE TITLE
Number of claims when being elected is wrongly displayed

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9065]
The Web UI says you get 15 claims, but you get 25.

**Comment by johnkslg** [comment]
When a player wins an election, they get a number of claims, apparently the amount is displayed wrong, should be 15.  Test with /leader

**Comment by D3nnis3n** [comment]
Oh well, then it’s the other way round – it shows 25 ingame. Did never really check how many you really get.

Gesendet von Mail für Windows 10

Von: John Krajewski
Gesendet: Freitag, 31. August 2018 21:52
An: StrangeLoopGames/EcoIssues
Cc: D3nnis3n; Author
Betreff: Re: [StrangeLoopGames/EcoIssues] Number of claims when being electedis wrongly displayed (#9065)

When a player wins an election, they get a number of claims, apparently the amount is displayed wrong, should be 15. Test with /leader

**Comment by D3nnis3n** [comment]
Just checked it, you do get 25 papers, it Shows 25 in game, but only 15 in the web interface.

Von: John Krajewski
Gesendet: Freitag, 31. August 2018 21:52
An: StrangeLoopGames/EcoIssues
Cc: D3nnis3n; Author
Betreff: Re: [StrangeLoopGames/EcoIssues] Number of claims when being electedis wrongly displayed (#9065)

When a player wins an election, they get a number of claims, apparently the amount is displayed wrong, should be 15. Test with /leader

**Comment by sidjuego** [comment]
@johnkslg I have tested this scenario, it shows 25 in game and it shows 25 in the chat of Eco server debug master window. Are there any constants defined ? Probably can we check from where this value is coming?

**Comment by sidjuego** [comment]
Ahh, found it. The value was hard coded to 25 directly into the scripts.
Please do let me know how much is the user supposed to get; 15 or 25? 
@johnkslg

**Comment by johnkslg** [comment]
15!
