### ISSUE TITLE
Minted Currency should be able to go to treasury or leader should be able to pay to treasury

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9066]
I want to expand on this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/9055

It would be great if the leader was able to mint currency directly into the treasury as means of central banking or at least transfer it to it. That would stop people think the leader is making money all for himself and he could issue it to people by those server shops easily without being involved.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#509
