### ISSUE TITLE
Elseif for laws

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9067]
Is there any possibility to have something like an elseif?

We want to do:

Under 200 Dollars give 40 each day
Above 200 tax 1%
Above 2500 tax 2%
Above 5000 tax 4%

And so on.

At the moment i'm adding up taxes, eg. tax again the difference between the values.

**Comment by MarjieAVolk** [comment]
Yes, you can already do this :D

Click here:
![image](https://user-images.githubusercontent.com/23460210/44600435-21db1280-a78e-11e8-848b-7e8f89ba9680.png)

![image](https://user-images.githubusercontent.com/23460210/44600449-2b647a80-a78e-11e8-8f1a-c03fd646f0f3.png)

Let me know if there's a way to make this more clear.
