### ISSUE TITLE
[7.7.0] Contracts not giving me permission to work on property for house and road contracts

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#9069]
Took contract build road from the /spawncontracts command.  Don't have authorization to build a road.

https://youtu.be/l9ECQl24Lek

**Comment by BlazeGuy2** [comment]
Same applies for building a house on the property

**Comment by BlazeGuy2** [comment]
Also applies to mow lawn contract

**Comment by johnkslg** [comment]
Fixed all!
