### ISSUE TITLE
[7.7.0] Plow contract issue with field size

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#9070]
/spawncontracts should auto generate land that meets the plow requirement.  Either command is broken or contracts land detection is broken.
![plowcontract](https://user-images.githubusercontent.com/35509188/44601173-81d2b880-a790-11e8-8752-78cc6d43320d.PNG)

**Comment by johnkslg** [comment]
Fixed!
