### ISSUE TITLE
[7.7 stage] remove stone ramp: with shovel?  and get dirt?

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#9072]
A stone ramp should not be removed by shovel but by Pickaxe. And it should not bring back dirt but Stone

![image](https://user-images.githubusercontent.com/22961978/44609029-5edaef80-a7f6-11e8-86e4-b91678b8d4ae.png)

**Comment by elfl0rd** [comment]
part of - https://github.com/StrangeLoopGames/EcoIssues/issues/8674#issuecomment-415888443

**Comment by seccombew** [comment]
Dupe
