### ISSUE TITLE
[Suggestion] Indicator showing something is already researched

### ISSUE THREAD

**Issue by NtropicZ** [StrangeLoopGames/EcoIssues#9074]
Title speaks for itself. I'm playing singleplayer and want some sort of indication that research is already completed. Also, if I have a collection of research books, any of them that have been researched by me should be greyed out in some way.

**Comment by Nicolausi113** [comment]
Suggestions should be made here:
 https://github.com/StrangeLoopGames/EcoSuggestions/issues
But we are not the only struggling on this. 
See also
 https://github.com/StrangeLoopGames/EcoSuggestions/issues/10
and
 https://github.com/StrangeLoopGames/EcoSuggestions/issues/43

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#515
