### ISSUE TITLE
USER ISSUE: Modules disappear

### ISSUE THREAD

**Issue by kotoroshinoto** [StrangeLoopGames/EcoIssues#9075]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
Reclaim a tractor with a module installed

**Expected behavior:**
refuse to give tractor if my inventory doesn't have enough room for the module AND the tractor, otherwise give me both

**Actual behavior:**
deleted the module

**Comment by LiaungYip** [comment]
https://github.com/StrangeLoopGames/Eco/pull/3284

**Comment by BlazeGuy2** [comment]
Merged into 7.7.0, should be fixed on next release.  Reopen if it's reoccurring.
