### ISSUE TITLE
Serverpassword-Dialog on wrong layer.

### ISSUE THREAD

**Issue by KonstantinRudolph** [StrangeLoopGames/EcoIssues#9077]
The server password input panel is not focused/seleced and a layer behind the server browser, can't enter a password.

After updating to version 0.7.7.0

![can t enter password](https://user-images.githubusercontent.com/19729823/44621802-103c5c80-a8ad-11e8-95ad-1de0aae67a26.PNG)

**Comment by johnkslg** [comment]
@Spydarlee can you look at this one? @mirasrael might be able to weigh in ideas.
