### ISSUE TITLE
Remove deeds when carts are removed

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#908]
http://ecoforum.strangeloopgames.com/topic/1194/carts-are-cancer

Deeds are stacking up.

**Comment by fillion07** [comment]
It's a major problem in our server we have tons of duplicate of carts and those duplicated carts are unusable and cannot be removed. I have to dig in the ground and hide them with pavement.

**Comment by craig-jong** [comment]
duplicate issue https://github.com/StrangeLoopGames/EcoIssues/issues/905
