### ISSUE TITLE
Block a person in chat

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#9080]
Version: 0.7.6.3 beta

Steps to Reproduce:
Try and ignore a player's chat in the chat window

Expected behavior:
That there would be a way to be able to ignore a player's chat if they choose
to do so. 

Actual behavior:

Well right now there is no way to be able to ignore a specific player 
and what they are saying in the chat Window. 

No matter what type of game it is if it is an online game where people
have to interact with each other there are always going to be problems

There is always going to be that one pig out there who messages
the female players out there that says "hey baby want to come over to my 
house and have some fun" 

Or just for that matter even an annoying player that you can't stand 
that is on chat. 

I don't see how the developers could have missed this and there should 
be a way to be able to ignore or block a player in chat. 

What I would say is that there be 3 commands to manage the block list.

/block "playername"   - This adds a player to the block list 
/blocklist  - This shows you who is currently listed in your block list
/blockdel  "playername" - This would delete a player from your block list 

The "playername" is of course the name of the player that you would
want to either block or remove from the block list. 

IE: /block dummy  or /blockdel dummy

No matter what if you put a group of people together on an online game 
like this there are always going to be some issues.

And a lot of times on these private servers there are NO admins around
to be able to ban an individual either.  I have played on servers where
the admin doesn't log in for weeks! So banning the person from the server
is not an option. 

There should be a way to be able to ignore / block a person in the chat
and make it so that the chat for that blocked player does not show up.

By not having something like this is a huge oversight on the part of the 
developers of this game.  This really needs to be added immediately! 

How did we even get to version 0.7.6.3 and be this far into
development without adding something like this?

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#519
