### ISSUE TITLE
7.7 - Ramp issues?

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9081]
1) If you walk on the lowest level of an ramp you hear the grass sound, not the one for the ramp.
2) All ramps have no speed bonuses
3) Removed ramps give dirt back - is that intended, e.g. are they no longer reusable (which would be quite realistic, but maybe a bit against quality of life)

**Comment by elfl0rd** [comment]
partially dupe https://github.com/StrangeLoopGames/EcoIssues/issues/8674

**Comment by keegan-o** [comment]
In repro-ing the sound error with the bottoms of the ramp I determined it is a code issue after ensuring the right SFX was attached to all the blocks. To see it, place some ramps down then delete the blocks underneath them. You will notice the bottom two ramp blocks do not play any footstep sound at all when walking on them. Something is going wrong with the smaller than half-meter size blocks and the SFX system. @Nanders
