### ISSUE TITLE
7.7 - Skidsteer camera is bugged

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9082]
The skidsteerer camera is bugged in 7.7 staging (maybe even in versions before, haven't got one there yet), it seems like you stay on a fixed point with your camera and see the skidsteer drive in somewhat a third person mode, see screenshot. You can drive it out of the camera, also.

<img width="1920" alt="skidsteer" src="https://user-images.githubusercontent.com/25908592/44623925-bf912780-a8dd-11e8-9fde-916fe725c196.png">

**Comment by SeanAtr0n** [comment]
fixed again in svn (prev fix got clobbered)
