### ISSUE TITLE
Large Doors cannot be closed from the ground

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9083]
When placing one of the large wooden or corrugated steel doors and you open them, you can no longer close them from the ground, as it's too high and jumping and falling closes the UI window. I don't think the intended behaviour is that you need to build a little stair so you can close it again?

**Comment by SlayksWood** [comment]
In 0.8.2.9 you can close large doors from the ground (a little problem with a large corrugated steel door). Also now you can open / close the door with RMB. You can jump and use RMB at it (in the worst case). Seems fixed.
