### ISSUE TITLE
Vote endings

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9084]
It seems like there is the option to end a vote when at least X percent of the server population have voted on the law. It does not seem this does take into account laws that limit the voting to players with specific playtime but just counts all players. So it's really never possible to have a law passed by just reaching the needed amount of players. It might also could take into account how much players were active in the last X days to calculate the amount of players needed to vote upon the law to have it being passed or canceled immediatly and not after 24 hours. At the moment this feature is not very senseful, i think.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#518
