### ISSUE TITLE
Framed Glass is much to cheap for being T4

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9085]
As of materials needed and skills needed the Framed Glass which is T4 is much too easy to make in comparison with the T3 materials Reinforced Concrete and Corrugated Steel. That makes all people just skip that and go for framed glass, as that can literally be made much earlier.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#517
