### ISSUE TITLE
0.7.7 meteor tutorial lost translate.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9087]
![20180826190830_1](https://user-images.githubusercontent.com/4980243/44630827-4ee51c00-a96c-11e8-91df-b895e6779361.jpg)
![20180826190833_1](https://user-images.githubusercontent.com/4980243/44630828-4f7db280-a96c-11e8-818e-aab0e3047027.jpg)
![20180826190955_1](https://user-images.githubusercontent.com/4980243/44630829-4f7db280-a96c-11e8-91ee-1ace1c2d98bd.jpg)
![20180826190957_1](https://user-images.githubusercontent.com/4980243/44630830-4f7db280-a96c-11e8-8fe1-f46a31426428.jpg)
![20180826191001_1](https://user-images.githubusercontent.com/4980243/44630825-4ee51c00-a96c-11e8-8983-d9aa75b52df3.jpg)

Updated meteor intro Localization strings is not updated!
@Nanders

**Comment by elfl0rd** [comment]
Oops, my bad, correct string is https://crowdin.com/translate/eco-by-strange-loop-games/3/en-ru#36227

**Comment by Nanders** [comment]
I'm going to fix this in master, and have it available for 8.0, along with the other missing strings

**Comment by elfl0rd** [comment]
:( okay

**Comment by Nanders** [comment]
These have been re-added
