### ISSUE TITLE
USER ISSUE: Stockpile "focus grab" range extends outside of stockpile and interferes with non-stockpile use

### ISSUE THREAD

**Issue by Sukasa** [StrangeLoopGames/EcoIssues#9088]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
1. Place stockpile
2. Try to mine block beside stockpile
3. Try to pick up drops beside stockpile, while looking on the half of the block volume closest to the stockpile

**Expected behavior:**
Focused cursor (and key events) on what cursor was pointed at

**Actual behavior:**
Stole focus and opened stockpile

**Comment by seccombew** [comment]
Is this when you are standing inside or outside of the stockpile?

**Comment by Sukasa** [comment]
Standing outside of the stockpile.  If it would be helpful, I can take demonstrative screenshots tonight.On Aug 27, 2018 10:51 AM, Will <notifications@github.com> wrote:Is this when you are standing inside or outside of the stockpile?

**Comment by Sukasa** [comment]
![20180827214232_1](https://user-images.githubusercontent.com/1186656/44701215-7dcdc180-aa42-11e8-8895-b1e2f7bf8b05.jpg)

This is a picture showing off the approximate range "out" that the stockpile's focus hitbox extends.  Aiming even a tiny bit to the right causes the stockpile to take precedence.

Likewise, if you are facing away from the stockpile, then it can still take precedence.  Here are two pictures; I am standing with my back to a stockpile and the only step between each picture is left-clicking.

![20180827214622_1](https://user-images.githubusercontent.com/1186656/44701285-d00ee280-aa42-11e8-8a2b-9be0e903a896.jpg)
![20180827214624_1](https://user-images.githubusercontent.com/1186656/44701286-d00ee280-aa42-11e8-99c9-2d9ba59a081d.jpg)

**Comment by Quadbro** [comment]
was fixed in 8.0 by collision sorting
