### ISSUE TITLE
USER ISSUE: objectives window need title.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9089]
**Version:** 0.7.7.0 beta staging-b938b54c
It's confusing, to move - you need grab it through free space.
![screen shot 08-26-18 at 10 04 pm](https://user-images.githubusercontent.com/4980243/44631989-89ef4b80-a97c-11e8-95d1-5a7cd87f6bc2.PNG)

**Comment by johnkslg** [comment]
Add a title similar to other UIs
