### ISSUE TITLE
USER ISSUE: 7.7 Staging: Stove Efficiency Error

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#9091]
**Version:** 0.7.7.0 beta staging-b938b54c

**Steps to Reproduce:**
Stoves were moved from the Metalworking tree to the Industry tree in 7.6.  There was a mistake when that happened where the efficency stayed with the Metalworking tree, not the Industrial.  Mistake still persists in 7.7 Staging.

**Expected behavior:**
Stove Recipe Efficiency should be using the Industry tree.

**Actual behavior:**
Stove Recipe Efficiency is still tied to the Metalworking Tree.

**Comment by craig-jong** [comment]
fixed in above pr
