### ISSUE TITLE
Land Claim Papers for Mint

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9093]
I want Land Claim Papers to be usable for currency. As of now, even Iron shovels can be used, so why can't the only thing with a real and limited value not be used for Mints?

Land Claim Papers are rare, if you back with them you can secure the economy quite good and bring players to choose between really big loads of land or having currency to trade with. Anyone can get them, but in limited amount. You could also as of 7.7 give them a higher minting value than the value you sell them for as fixed price, so people then can trade their money in for the same price papers are sold to get them to increase their lands. I like that idea, but can't test it :(

**Comment by Deantwo** [comment]
Sadly we can't convert the currency back into the "_backing item_". If we could the idea of using valuable resources as the _backing item_ would be awesome.

**Comment by elfl0rd** [comment]
is not issue, place for suggestions here - https://github.com/StrangeLoopGames/EcoSuggestions/issues

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#516

**Comment by D3nnis3n** [comment]
@Deantwo 
But that is emulated on our server with the "Central Bank" shop, where atm you get the gold back. Don't see a reason why that would not fit.
