### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Alecha23** [StrangeLoopGames/EcoIssues#9094]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60,00%>Token is invalid.</size>
```

**Comment by BlazeGuy2** [comment]
How did you buy the game?  If you bought this through steam, does this occur when you try to launch it through the steam client?  If it's through the SLG site, you need to use your SLG login.

**Comment by BlazeGuy2** [comment]
Reopen when you can send me more info to help me address the issue.
