### ISSUE TITLE
[7.7.0] Possibly authorization Problem: 2 players auth. on a ground except for few objects

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9096]
Version: v0.7.7.0-beta-staging-b938b54c

Situation:
Two players (Rugele & Twin7) are authorized on ground “Rugele Town” (pic. 1)
Player Twin7 is not authorized on the chest, but can access it (pic. 2).

Questions:
It’s not fully clear to me, but intuitively I would think, object authorization should override ground authorization?
Is the object auth. inherited from ground and can not be turned back?

![auth1 snip](https://user-images.githubusercontent.com/38510829/44672164-f3786400-aa27-11e8-9bee-df0eabacf5ad.jpg)

![auth2 snip](https://user-images.githubusercontent.com/38510829/44672113-bb712100-aa27-11e8-849d-b55849e8961b.jpg)

**Comment by metachronism** [comment]
this was possible before by setting auth mode off of inherited

**Comment by Nicolausi113** [comment]
I placed the chest on the ground which was authorized for two players and adjusted authority for one player (Rugele).

**Comment by johnkslg** [comment]
Yes, the owner of the property can always access the objects on their property.  As intended. We can improve the messaging though.

**Comment by MarjieAVolk** [comment]
Players who are authorized on the object will have 'consumer' level rights on the object - they can open and use it.  Players who are authorized on the deed will have 'owner' level rights for all objects on the land - they can change its settings, pick it up, etc, and they can also do anything a 'consumer' could do.

The question marks on the object's Authorization tab also explain this.  We've changed around some terminology and some layout, but overall auth mostly works the same way it did before in this regard.

I'm of course interested in making this as clear as possible, and will continue to do so as I can, but I don't have any specific ideas for how to do this right now.

**Comment by MarjieAVolk** [comment]
If you have any ideas or requests, let me know.
