### ISSUE TITLE
USER ISSUE: fuel supply is not visible through storage tab.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9098]
**Version:** 0.7.7.0 beta master-ec0b88f6 debug
If you open storage trough object with fuel supply
![default](https://user-images.githubusercontent.com/4980243/44685533-5384ff80-aa54-11e8-887b-1425be000bd5.png)

If you open another object in range,
![default](https://user-images.githubusercontent.com/4980243/44685560-68fa2980-aa54-11e8-9725-f9d7d700558b.png)

@MarjieAVolk

**Comment by elfl0rd** [comment]
@MarjieAVolk it's work on bleeding_edge, you fixed it or BE not contain broken changes?

**Comment by MarjieAVolk** [comment]
Hm I just took a look at this, and it seems to be working on staging, but not on master.  So I'm guessing the error just isn't released yet.  Or maybe it's random.  🤔

**Comment by elfl0rd** [comment]
i see you found it :) cool!
