### ISSUE TITLE
StarterCamp vs. Campsite is weird in laws

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#9099]
It seems that StarterCamp shows up in laws, eg. in pick up/place item filters on fresh servers, but Campsite doesn't.  I don't think you can actually 'pick up' a StarterCamp.

In order to show up in these drop downs, an item has to be discovered and has to have a `WorldSpaceItemAttribute` on it.  I thiiiink this can get fixed by making StarterCampItem hidden?  Not sure if that will have other implications.  CampsiteItem should also probably start discovered.

**Comment by D3nnis3n** [comment]
Just to add opinion on this: We ban placing of StarterCamps in a specific district, while placing Campsites is full fine if someone wants to.

**Comment by WeaselDog** [comment]
Dennis makes a very good point. They are different things and in my opinion they should be treated differently by laws.

**Comment by beastyn** [comment]
see them both now
![bandicam 2020-01-15 17-40-48-904](https://user-images.githubusercontent.com/27898520/72434763-450cc480-37be-11ea-916a-af651df9ec4f.jpg)
![bandicam 2020-01-15 17-40-50-897](https://user-images.githubusercontent.com/27898520/72434764-450cc480-37be-11ea-83f0-eec6dd87005d.jpg)
