### ISSUE TITLE
Laws: 'Show All' toggle for item lists

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#9100]
... which are normally filtered based on discovery

**Comment by MarjieAVolk** [comment]
Implementation wise, I think we are going to want the toggle to be web client side only, and the server will just have to send an extra 'discovered' bool along with each drop down option.

**Comment by elfl0rd** [comment]
and old suggestion :P 
https://github.com/StrangeLoopGames/EcoSuggestions/issues/470

**Comment by MarjieAVolk** [comment]
Ah yeah, I should have linked that, thanks

**Comment by WeaselDog** [comment]
It has been added now for stores and laws:
![ShowUndiscovered](https://user-images.githubusercontent.com/47330823/70869070-e4c70080-1f3b-11ea-8cf0-f2e38d71e959.png)
