### ISSUE TITLE
Getting out of a Steam Truck in a Narrow Underground Tunnel or agaisnt a wall Makes me jump to surface

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9101]
**Version:** 0.7.6.3 beta

Create an Underground Tunnel Two blocks wide 3 Blocks high (wide enough for Steam Truck) then Hit E to get out, because there is No space rather than Saying cannot get out, i automatically get Transported to the world Surface which is extremely annoying if i have to walk back to the Truck which can often take me a long time.

The Tunnel doesn't have to be narrow for me to get sent to the surface , if i happen to forget which side of the truck i get out of (in USA you sit on the right of a vehicle, in UK we sit on the left) so sometimes i forget which side of the vehicle **must be away from a wall**

Now if this is like what i have in my Tailings Volcano i forget and park up against the side of the entrance and forget what side i get out i get stuck IN the tailings with Falling sounds, and /unstuck doesn't always work and i get well and truly stuck

we can get into the Truck from any direction it doesn't have to be from the side of the steering wheel, so please can we have a detection that if a side is blocked it will put the player in an open space OR if no space then tell the player they have no space to get out please **MOVE** the Truck

1st Video is in underground tunnel i press E then i appear in the water above where i was
[Eco 28_08_2018 00_24_36.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2325986/Eco.28_08_2018.00_24_36.zip)

2nd Video is me Totally stuck inside Tailings after getting out of the Truck
[Eco 28_08_2018 00_46_09.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2325993/Eco.28_08_2018.00_46_09.zip)

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 0.9.5 Develop-340

In a 3x3 tunnel, character will go out from steam truck on the side that have enough space to stand on. 

When tested on a tunnel that's too narrow (3x2) error message will pop-up stating there is not enough space to go out from
