### ISSUE TITLE
USER ISSUE: Is it a bird? Is it a plane? No! It's a flying fisherman!

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#9102]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
1. Take a step back
2. Run into the water holding W+Shift
3. Not releasing both of the buttons, open up your backpack, holding both W and B pressed. (or releasing shift then B for backpack then back shift for a matter of moments)
4. Profit!

Floating status may disappear among clicking the mouse while in the air

**Expected behavior:**
EVERYTHING IN ORDER

**Actual behavior:**
No emergency here

**Comment by HetNeSS** [comment]
Video coming right up

**Comment by HetNeSS** [comment]
Upon further examination, seems like Shift button is optional and not required. Tested with Ctrl+ W&B

**Comment by HetNeSS** [comment]
https://youtu.be/-umQw1BzJVA

**Comment by HetNeSS** [comment]
https://youtu.be/-umQw1BzJVA

**Comment by seccombew** [comment]
Fixed in 7.7+
