### ISSUE TITLE
Steam Tractor does not show usage of attachment

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9104]
Excavators, Skidsteers, they all got that symbol that makes you press 1 to use it. People asked me today how they could plow, as the symbol that tells you press 1 in the hotbar is not there.

**Comment by elfl0rd** [comment]
dupe
https://github.com/StrangeLoopGames/EcoIssues/issues/8103
https://github.com/StrangeLoopGames/EcoIssues/issues/8101
