### ISSUE TITLE
Steam Tractor Attachment visually not synced

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9105]
While you can see your plower go down when you drive the steam truck, everyone else does not - it's up for them.

**Comment by D3nnis3n** [comment]
Merged with #12049

**Comment by SlayksWood** [comment]
still an issue 8.1.3
https://drive.google.com/file/d/1ZaeZSWnVpRO2JS3cCFkzHS6N5vzd2daH/view?usp=sharing

**Comment by WeaselDog** [comment]
Fixed in 9.5
