### ISSUE TITLE
Distribution Station would be better 5x5x5 it just overaps the other two blocks a bit at 7x7x7

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9108]
**Version:** 0.7.6.3 beta

![snap2527](https://user-images.githubusercontent.com/29383891/44745214-06119c80-aaff-11e8-8291-eb0a16505e07.png)
![snap2528](https://user-images.githubusercontent.com/29383891/44745215-06119c80-aaff-11e8-9340-556803a35090.png)
as you can see above its a bit of a Design issue, only really noticed the size as i placed on blocks on water (5x5) like i do for a stockpile and it said it needed to be on Solid Ground.
![snap2529](https://user-images.githubusercontent.com/29383891/44745386-81734e00-aaff-11e8-9c67-6dd21ad8876c.png)
 i think they would look better if the fitted Snugly against each other

**Comment by D3nnis3n** [comment]
Agree to that, is pretty enerving.
