### ISSUE TITLE
When you pick up garbage with a Shovel it instantly switches to Tool bar Slot 2

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9109]
**Version:** 0.7.6.3 beta

![snap2530](https://user-images.githubusercontent.com/29383891/44746056-483bdd80-ab01-11e8-9bf7-347c40940675.png)
![snap2531](https://user-images.githubusercontent.com/29383891/44746057-483bdd80-ab01-11e8-9830-5f66cc7cc1ee.png)
![snap2533](https://user-images.githubusercontent.com/29383891/44746210-a36dd000-ab01-11e8-9417-7934f207497a.png)
This is OK if you have a tool in Slot 2 But if you have anything else its annoying, You can choose any tool **EXCEPT SHOVEL** (as seen below) to place it down
![snap2534](https://user-images.githubusercontent.com/29383891/44746307-e29c2100-ab01-11e8-8754-de7806b8f85c.png)

**Comment by Conchipedia** [comment]
USER ISSUE: "cant select modern shovels while carrying Garbage" #8377

linking this (mine has a little bit more info about it auto swapping to Toolbar Slot 2)

**Comment by seccombew** [comment]
Fixed.
