### ISSUE TITLE
staging 7.7 - Discussion button/section on elections does not work 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#9114]

**Comment by MarjieAVolk** [comment]
We determined what is going on is that nick thought this was a button, but it is a title:
![image](https://user-images.githubusercontent.com/23460210/44818334-98687d80-ab9d-11e8-9209-834213cd5f77.png)

These titles are styled exactly the same way as buttons, might be causing confusion.

**Comment by rainfarmer** [comment]
ok, well be redesigning all of it eventually.
