### ISSUE TITLE
staging 7.7 - Voted for George

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#9115]
![image](https://user-images.githubusercontent.com/6262198/44756405-65f84b00-aadf-11e8-8635-4d15c98b90fc.png)
I voted for George - George is not a player on this server

**Comment by Nanders** [comment]
![image](https://user-images.githubusercontent.com/6262198/44756469-aa83e680-aadf-11e8-8f15-eafb38852a59.png)
"Note the voted for ." in the chat log

**Comment by BlazeGuy2** [comment]
Dup of #9051
