### ISSUE TITLE
Add server option doesnt type correctly

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#9116]
When adding server in My Worlds section. 
The text I type when entering an ip does not display until i click on the screen or alt tab.

**Comment by Spydarlee** [comment]
Seems to work as expected in the editor on the latest version of staging. Which branch are you getting this on? And was it on a full build or in the editor?

![ecobug9116norepro](https://user-images.githubusercontent.com/553695/44850559-7b8f8100-ac55-11e8-985c-1fc064c61c7f.gif)

**Comment by rainfarmer** [comment]
It's on the client downloaded from the website
![image](https://user-images.githubusercontent.com/7343272/44866214-77556a80-ac39-11e8-87d9-cf8c17daab7d.png)

**Comment by johnkslg** [comment]
Jeff can you verify fixed

**Comment by rainfarmer** [comment]
still not working for me on Beta 7.7.0 #B938b54c

**Comment by rainfarmer** [comment]
nevermind, it works on master
