### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by emadalnomaili111** [StrangeLoopGames/EcoIssues#9117]
**Version:** 0.7.6.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Invalid username or password.
```

**Comment by BlazeGuy2** [comment]
@emadalnomaili111 If you got this game through steam, are you running it through the steam client?  If you're opening up the app directly from it's folder, you'll need to setup/use your SLG username and password.

**Comment by BlazeGuy2** [comment]
No response, closing.
