### ISSUE TITLE
Negative Reputation can't add up

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9118]
Whilst it is possible to give a player another 10 positive reputation on another day, it's not possible to give him another -10 negative reputation on another game - the game will just say "removed 0 reputation" and not take any of your available reputation points. That should definately not be the case, as it allows players to circumvent their red name by having a single friend that gives him 10 positive points each day, even when more other players gave them a negative value of -10.

**Comment by johnkslg** [comment]
It was intentionally capped at a min of -10 so that people couldnt really troll someone.  Perhaps the high end should be capped as well.

**Comment by johnkslg** [comment]
Ill cap the max to 30. Fixed!

**Comment by D3nnis3n** [comment]
Haha, in the case because of whom i reported this - the guy that could no longer be given negative reputation to, was the guy trolling everyone *g* Thanks!

**Comment by D3nnis3n** [comment]
I would have proposed the same limit of 10, though, especially as you can only give a review once that counts for all reputation given instead of a seperate review for every occasion on which you gave reputation.
