### ISSUE TITLE
UI broken after skipping tutorial

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#9119]
Reported through Kayako. Part of the user's UI was missing:
![ecoerror](https://user-images.githubusercontent.com/13459026/44785836-f0679b80-ab2d-11e8-85f6-a7ce680c9272.jpg)

**Comment by johnkslg** [comment]
Walker, can you get a repro on this?
Alec can you get the save game from this user?

**Comment by BlazeGuy2** [comment]
@GophTheGreat What version is this happening on?

**Comment by BlazeGuy2** [comment]
Can't reproduce, bumping down priority until a case comes up.

**Comment by johnkslg** [comment]
Probably fixed by Misasrael's changes, closing.
