### ISSUE TITLE
Allworldobjects command missing lot of worldobjects.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9120]
e.g. electic planer, electric stamping press, and moooooore...

Can you make this command autogenerate too?

**Comment by BlazeGuy2** [comment]
Confirmed, all the 2 worldobjects above are missing.

**Comment by elfl0rd** [comment]
More than 2 missing.

**Comment by elfl0rd** [comment]
e.g. lathe, round pot... And maybe more :)

**Comment by johnkslg** [comment]
This is a development command issued by typing /allworldobjects into chat.  
Need to update this command to find all the world objects, using the WorldObjectManager which should have a full list of types in there.

**Comment by sidjuego** [comment]
@johnkslg 

> This is a development command issued by typing /allworldobjects into chat.
> Need to update this command to find all the world objects, using the WorldObjectManager which should have a full list of types in there.

Are you referring to add all those objects that throw exceptions when this command is triggered?
I found AllWorldObjectTypes that stores AllWorldObjectTypes which is some sort of a lookup table. I believe that is coming from csv file.

**Comment by johnkslg** [comment]
Any objects that throw an exception is a separate bug, can you file it or fix it?  Theres some with garbage being fixed @craig-jong

**Comment by sidjuego** [comment]
Are you referring to add only the objects under WorldObjectTemplate(objects from row no 500-627)
 of EcoTechTree.csv to **allworldobjects** command?
![5](https://user-images.githubusercontent.com/43029943/46473796-dee57380-c7fe-11e8-9be3-5131f4c12d0f.PNG)
 

 Or should we also add from other templates like Vehicle template? Need your inputs on those.

**Comment by sidjuego** [comment]
Are you referring to add only the objects under WorldObjectTemplate(objects from row no 500-627)
of EcoTechTree.csv to allworldobjects command?
![46473796-dee57380-c7fe-11e8-9be3-5131f4c12d0f](https://user-images.githubusercontent.com/43029943/46475802-24f10600-c804-11e8-98a6-7196aa5d16ef.PNG)
Or should we also add from other templates like Vehicle template? Need your inputs on those.

**Comment by craig-jong** [comment]
All of the world objects are found correctly, my guess is that its something to do with the spawning. Should have a fix in a sec.

**Comment by elfl0rd** [comment]
lol, not fixed :D 
No "Large Standing" lumber and hewn log signs :P
