### ISSUE TITLE
Ping and FPS counter not aligned correctly in escape menu

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#9122]
![image](https://user-images.githubusercontent.com/3150561/44816719-eb3f3680-ab97-11e8-893a-3a3084db3e0b.png)

**Comment by metachronism** [comment]
unusable in certain resolutions

**Comment by SlayksWood** [comment]
FPS and Ping is always displayed correctly on my resolution .

**Comment by SlayksWood** [comment]
FPS and Ping is always displayed correctly on my resolution (1680х1050).
I can’t set a resolution other than 16:10.

**Comment by GophTheGreat** [comment]
Couldn't reproduce in any resolution. Closing.
