### ISSUE TITLE
Law Clauses for price regulation

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#9124]
> I'd like to propose a law clause that enables you to prevent a sale if the price is above or below a given number in a law. In our case we want to use that for disallowing the sale of skill scrolls for below 500 $ as we want "Land Claim Papers" to be used in the economy with an fixed value of 100 $. When people now start giving out the scrolls for free, that will not work. Neither can we use them in a mint at the moment.
> 
> Most probably there are many other uses for this, such as regulating the market.
- @D3nnis3n
Copied from https://github.com/StrangeLoopGames/EcoSuggestions/issues/522

Technical notes:
Can be implemented with a new context interface `IHasPriceContext` or something on Buy/Sell actions, which can be used to create a `PriceActionQuery : ActionQuery`

**Comment by Deantwo** [comment]
Duplicate of #9412.

**Comment by IcedForge** [comment]
Closing this as it is possible to do now in 9.0 with changes to law triggers and sub conditions.
![Screenshot_69.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/cef7b34c-9a7f-4870-9453-a9f7019a0129)
