### ISSUE TITLE
Bars or Ingots this is geting confusing (can we just stick to one name for them?)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9126]
in the Older Versions of Eco we just made Ingots (Copper Ingot, Iron Ingot and Gold Ingot) but now we seem to be having mixed recipe tool tips that say we are making both types.
This is what i mean

Copper says this
![snap2545](https://user-images.githubusercontent.com/29383891/44823938-faa39b80-abfa-11e8-874f-7031e121549c.png)
![snap2548](https://user-images.githubusercontent.com/29383891/44823947-01caa980-abfb-11e8-9144-dd560421645a.png)
![snap2549](https://user-images.githubusercontent.com/29383891/44823954-07c08a80-abfb-11e8-807d-ec9a2a8bd8a5.png)
![snap2556](https://user-images.githubusercontent.com/29383891/44823963-0ee79880-abfb-11e8-8bc9-dd87cfa50782.png)
![snap2558](https://user-images.githubusercontent.com/29383891/44824301-b87b5980-abfc-11e8-9d36-44227804973a.png)

Iron say this
![snap2547](https://user-images.githubusercontent.com/29383891/44823980-2d4d9400-abfb-11e8-8454-d9418176e3cc.png)
![snap2552](https://user-images.githubusercontent.com/29383891/44823985-3179b180-abfb-11e8-9b40-d1b309295842.png)
![snap2553](https://user-images.githubusercontent.com/29383891/44823988-35a5cf00-abfb-11e8-9f46-0be5b6ae55fb.png)
![snap2554](https://user-images.githubusercontent.com/29383891/44823993-3a6a8300-abfb-11e8-9e7d-bb00eeba7216.png)
![snap2557](https://user-images.githubusercontent.com/29383891/44824307-c29d5800-abfc-11e8-8d10-2cd0388d823c.png)

Gold says this
![snap2546](https://user-images.githubusercontent.com/29383891/44824014-52da9d80-abfb-11e8-941b-5da1ba2d724e.png)
![snap2550](https://user-images.githubusercontent.com/29383891/44824017-579f5180-abfb-11e8-84cf-8aec10bf93cf.png)
![snap2551](https://user-images.githubusercontent.com/29383891/44824022-5bcb6f00-abfb-11e8-9ab8-e0fc7b0aafda.png)
![snap2555](https://user-images.githubusercontent.com/29383891/44824028-5ff78c80-abfb-11e8-970e-170b9e4e440e.png)
![snap2559](https://user-images.githubusercontent.com/29383891/44824312-c92bcf80-abfc-11e8-971f-8bea7aa68218.png)

and finally A difference between a gold bar and a Gold Ingot

Gold ingots may also be referred to as bars, but they are formed differently than the minted bars which are so popular. With ingots the weight contained can vary, and these bars are poured instead of stamped. This causes them to be thicker than the stamped bars usually. When you buy gold bullion bars you will normally get the stamped version, while purchasing gold ingots means you will get bars which were pored into a cast instead

**Comment by D3nnis3n** [comment]
Yeh, i do agree it would be better to keep to one of the two options in naming. As the bars are most probably poured they should be called "Ingots", despite them looking like stamped ones.

**Comment by elfl0rd** [comment]
It's different reciepes, blast furnace and bloome

**Comment by Conchipedia** [comment]
but one is saying Ingots and one is Bar,  so if we are making Bars then ingots shouldn't be said at all (it is less confusing)

**Comment by Conchipedia** [comment]
If a An Admin wants to spawn these they are called IronIngotObject, GoldIngotObject, and CopperIngotObject so having them called **bars** makes life harder for every in finding the right name

**Comment by D3nnis3n** [comment]
Agree.

**Comment by CobaltEcho** [comment]
I agree, there are actually a LOT of inconsistencies like this.  Probably as a result of changes being made as the game is growing.  I still think everyone should vote on the one month for bug fixes and cleaning up the code/files.  :p

https://ecoauth.strangeloopgames.com/roadmap

Honestly, I think people want a railroad because of minecraft, heh.  I guess that is why we vote though,

**Comment by elfl0rd** [comment]
Heh,
"Hew Logs" and "Hewn Log" reciepes...

**Comment by SlayksWood** [comment]
still an issue 8.1.3
![image](https://user-images.githubusercontent.com/45708377/56270274-6ee56d80-60fe-11e9-9aad-b3f18dd15a5a.png)

**Comment by SlayksWood** [comment]
Seems fixed in 0.9.0:
![image](https://user-images.githubusercontent.com/45708377/70983054-25a05000-20c9-11ea-8225-98631e4b1c4f.png)
![image](https://user-images.githubusercontent.com/45708377/70983077-2d5ff480-20c9-11ea-9539-468aca8615bd.png)
