### ISSUE TITLE
Framed Glass Door needs to be crafted at a Kiln not at a Robotic Assembly Line please

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9127]
**Version:** 0.7.6.3 beta

Here are the Door Recipes and Current Location for Crafting

Door
This can be crafted at a Carpentry table and ingredients logs
![snap2562](https://user-images.githubusercontent.com/29383891/44825269-caabc680-ac01-11e8-9544-bb16940ce145.png)
![snap2569](https://user-images.githubusercontent.com/29383891/44825272-d39c9800-ac01-11e8-8055-f1ea7ab671a5.png)

Stone Door
This can be crafted at a Masonry table and ingredients Stone
![snap2561](https://user-images.githubusercontent.com/29383891/44825319-05adfa00-ac02-11e8-9f3d-79fc4d85aa05.png)
![snap2568](https://user-images.githubusercontent.com/29383891/44825326-0ba3db00-ac02-11e8-8bae-2c5af4da919d.png)

Large Lumber Door
This can be crafted at a Sawmill ingredients Lumber
![snap2564](https://user-images.githubusercontent.com/29383891/44825390-5160a380-ac02-11e8-8dd8-670bf0ae8941.png)
![snap2566](https://user-images.githubusercontent.com/29383891/44825399-5887b180-ac02-11e8-9618-029349a9f68d.png)

Large Windowed Lumber Door
This can be crafted at a Sawmill Ingredients Lumber and Glass
![snap2563](https://user-images.githubusercontent.com/29383891/44825459-97b60280-ac02-11e8-80ce-f8ab68e3cb58.png)
![snap2566](https://user-images.githubusercontent.com/29383891/44825464-9d134d00-ac02-11e8-9dbd-7114d69c9f96.png)

Framed Glass Door
You have this crafting at Robotic Assembly Line
![snap2560](https://user-images.githubusercontent.com/29383891/44825511-cd5aeb80-ac02-11e8-8764-e85ca1223125.png)
![snap2567](https://user-images.githubusercontent.com/29383891/44825518-d3e96300-ac02-11e8-8084-a8755cc0be68.png)

As you can see Framed Glass is made at a Kiln
![snap2570](https://user-images.githubusercontent.com/29383891/44825567-114df080-ac03-11e8-9c09-e2f9070868c5.png)
![snap2572](https://user-images.githubusercontent.com/29383891/44825597-3c384480-ac03-11e8-9387-e38acbe142fb.png)

and seeing as Framed Glass is a Building Block that can make Floors, Walls, Solid Block, Roof, Column, Window and Stairs with a Hammer Please can we Make this Framed Glass Door at a simple Kiln?

**Comment by D3nnis3n** [comment]
I propose the other way round. As i mentioned in another proposal, Framed Glass is T4 and easy and cheap to get compared to Reinforced Concrete and Corrugated Steel. E.g.: Remove Framed Glass from the kiln and add it to the Robotics Assembly.

**Comment by elfl0rd** [comment]
Is not issue, place for suggestions here - https://github.com/StrangeLoopGames/EcoSuggestions

**Comment by Conchipedia** [comment]
to me its an issue i deliberately took Glass and Steel so i could make Framed Glass that especially meant the Framed Glass Door for a Project i was Building
![snap2574](https://user-images.githubusercontent.com/29383891/44851347-e80b7f80-ac57-11e8-91bf-57543ba9bfc6.png)
i would understand it being made on another table if it had special Ingredient requirements (but it just uses Framed Glass from a Kiln) , but All doors can be made on tables that make the Ingredients for them

**Comment by elfl0rd** [comment]
glass doors counts as t4, it's planned move, for balance reason. t4 glass maybe make harder to create soon too.

**Comment by Conchipedia** [comment]
that makes sense that T4 Glass and Glass door be crafted at the same place
