### ISSUE TITLE
USER ISSUE: Repeated Disconnect issues

### ISSUE THREAD

**Issue by Deygus** [StrangeLoopGames/EcoIssues#9128]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
Play game for awhile and it disconnects randomly

**Expected behavior:**
I should be able to play the game without any connection problems because I have really fast internet. I rarely experience this issue in other issues so I am not quite sure why it happens 5 times everyday. I quit playing awhile back because it got so annoying. It's been awhile, thought maybe this was resolved mostly but it would seem not. :(

**Actual behavior:**
The followinging pop up.
```
<size=150%>Connection Failed</size>

No response from master server.
```

**Comment by metachronism** [comment]
fixed with better messaging in 7.7
