### ISSUE TITLE
7.7 - "Unconnected Message too long"

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9129]
I get a crash with the message above after writing a probably too long description into the DetailedDescription Field in the Server UI, i need to shorten it so the server can start up again:

>Your goal on this server is to be creative, cooperativeley build a striving world, create a healthy economy, heek up the ecology and destroy the meteor within 30 days. The server will stay Be cooperative, build a striving world, create a healthy economy, keep up a good ecology and destroy the meteor within 90 days! A cycle lasts until about 60 days after the meteor has been destroyed. The rules and more inforamtion about our server can be found on discord: discord.gg/HhCrDrA <

Which should have been this, but i forgot to remove some old text:

> Your goal on this server is to be creative, cooperativeley build a striving world, create a healthy economy, keep up the ecology and destroy the meteor within 30 days. A cycle lasts until about 60 days after the meteor has been destroyed. The rules and more information about our server can be found on discord: discord.gg/HhCrDrA

It at least shouldn't crash, but ignore the message then.

**Comment by metachronism** [comment]
We should remove the "detailed description" field, which makes for too-long network messages (byte limit of the MTU or around 1400 bytes).  Description is plenty for the server browser.

**Comment by D3nnis3n** [comment]
Uh, should not have reported this then, kinda like that feature as it allows having only really important info in the server name.

**Comment by Spydarlee** [comment]
I've submitted a pull request with the detailed description field removed, as per your suggestion @metachronism.

**Comment by metachronism** [comment]
@Spydarlee hmmm after hearing from @D3nnis3n seems like we should allow it, but ensure the json string of server info is less than the MTU, truncating the string if its too long

**Comment by D3nnis3n** [comment]
Yeah, please keep this feature if you can. It's VERY useful.

**Comment by Spydarlee** [comment]
Capping the regular server description/name as well as the detailed description helps resolve this, but I've always made sure the overall json is truncated if it gets too big.
