### ISSUE TITLE
Building too high corrupts the world?

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9131]
A player of us built a skyscraper on height 100, maybe around 70 blocks high (i don't really know and can't look it up), as he placed down the beginning of another layer that lead to people no longer be able to connect, some minutes later the server crashed and will no longer start up as of this error:

> Unbehandelte Ausnahme: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Exception: Error(s) occurred when loading World
>    bei Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
>    bei Eco.World.PersistentChunkGrid.Load()
>    bei Eco.World.WorldPlugin..ctor()
>    --- Ende der internen Ausnahmestapelüberwachung ---
>    bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
>    bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
>    bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
>    bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
>    bei System.Activator.CreateInstance(Type type, Object[] args)
>    bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
>    bei Eco.Server.PluginManager.<.ctor>b__10_4()
>    bei System.Threading.Tasks.Task.Execute()
>    --- Ende der internen Ausnahmestapelüberwachung ---
>    bei System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    bei Eco.Server.PluginManager.<>c__DisplayClass10_0.<.ctor>b__0()
>    bei System.Threading.Tasks.Task.Execute()
>    --- Ende der internen Ausnahmestapelüberwachung ---
>    bei System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    bei Eco.Server.PluginManager..ctor()
>    bei Eco.Server.Startup.Start(String[] args)
>    bei Eco.Server.MainClass.Main(String[] args)

You can find the save file here: https://www.godsofwar.de/game.zip

The players name is ZiEGE and he should be at the place where the skyscraper is on that save, though not able to connect or start it up.

**Comment by D3nnis3n** [comment]
Additional Notice: I don't know if that IS the reason for the crash, but it was the only markable thing that happened when the crash happened.

**Comment by D3nnis3n** [comment]
I would be happy if you could tell me when you downloaded the save / do not need it at all, so i can remove it. Half a GB on a small SSD is quite some wood *g*

**Comment by metachronism** [comment]
@SeanAtr0n this is a gamesave that hits the world size limit, can we put in a safeguard to make the save fix itself in these instances?

**Comment by D3nnis3n** [comment]
Which limits are there? What do i have to pay attention to, e.g. what is the maximum height for buildings or what was the problem in that save?

**Comment by SeanAtr0n** [comment]
x * y * z needs to be less than 2147483647

so on 4000x4000 you can go as high as 134

**Comment by D3nnis3n** [comment]
I see. Thank you very much!

**Comment by D3nnis3n** [comment]
That issue was fixed, wasn't it?

**Comment by SeanAtr0n** [comment]
yup, fixed
