### ISSUE TITLE
USER ISSUE: Hunted Animals disapear

### ISSUE THREAD

**Issue by humphrey3009** [StrangeLoopGames/EcoIssues#9133]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
1. Find a Animal for example a wulf at an cliff with bushs at its bottom
2. Shot the wulf
3. The wulf falls down the cliff into the bushs and disapears

**Expected behavior:**
dead wulf should be around somewhere

**Actual behavior:**
dead wulf disapears

**Comment by Nicolausi113** [comment]
This is intended as I know, it’s a relatively short time to take up the carcass, I would guess 5 sec., then vanishes.

**Comment by SeanAtr0n** [comment]
the time was ~60-90s for 7.6, 7.7 increases it to 3-5minutes
