### ISSUE TITLE
Footstep SFX don't work with lower ramp blocks/short builders.

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#9136]
Basically to see this, place some ramps down then delete the blocks underneath them. You will notice the bottom two ramp blocks do not play any footstep sound at all when walking on them. The ramp blocks are all assigned the right walking SFX in the blockset. Something is going wrong with the footstep SFX for blocks that are short/don't take up very much of the meter space they are in, like the ramp bottoms.

**Comment by SeanAtr0n** [comment]
there is some code that samples blocks .5m below the player, probably should sample a smaller distance or check multiple blocks

**Comment by Nanders** [comment]
Sean is right, will be an easy fix

**Comment by WeaselDog** [comment]
It makes a sound for me now. Looks like it is fixed but please reopen if it is still an issue.
