### ISSUE TITLE
master - easy way to find Ecko returns!

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9138]
![default](https://user-images.githubusercontent.com/4980243/44882479-25095d80-acbc-11e8-8ecb-6806f98b6697.png)

**Comment by seccombew** [comment]
Need more specifics, but if using fly mode to find dolphin, that is a cheat command and won't fix.

**Comment by elfl0rd** [comment]
> Need more specifics, but if using fly mode to find dolphin, that is a cheat command and won't fix.

Some time ago, coordinates removed from Ecko desc. To prevent finding another by /give or after found one.
