### ISSUE TITLE
Hammer Form Selection Goes Offscreen

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#9139]
![image](https://user-images.githubusercontent.com/14983165/44886943-5cf1b000-ac7e-11e8-9893-f9372555de1a.png)
This makes picking a form feel very sloppy/basically the UI that extends across the screen is not very useful and I just end up looking at the square and going through them one at a time until I get the form I want. I think the form icons should be made much smaller so you can see all of them at once when selecting between them.

Additionally, I would like to add names for the forms that appear to the right of the form as you scroll through, or even that are always there when this selection UI is up. That's a feature though and can be split into another bug if whoever fixes this one prefers it.

**Comment by seccombew** [comment]
Possible dup of old bug

**Comment by Conchipedia** [comment]
i agree about having names for the Blocks so if anyone is having problems with a specific type (either in Placing or Graphic glitch) then everyone is on the same page about which block type is causing an issue so when they say Square Block they can tell whether its the top Floor block or the Solid one 3rd icon below it

**Comment by johnkslg** [comment]
Please add:
- A text field above each block naming what it is
- A GridComponent allowing the box to create additional columns if it goes off screen

**Comment by sidjuego** [comment]
![5](https://user-images.githubusercontent.com/43029943/46019685-4b26ef80-c0fa-11e8-8419-fcd41520ae8a.PNG)
@johnkslg Is this alignment okay?

**Comment by johnkslg** [comment]
Hmm looks a little funky and is weird with scrolling. How a out you make a mask at Max size and the icons rotate into it if there's too many? Or, can shrink them when there are a lot. I would keep it vertical though.

**Comment by sidjuego** [comment]
@johnkslg 



> Hmm looks a little funky and is weird with scrolling. How a out you make a mask at Max size and the icons rotate into it if there's too many? Or, can shrink them when there are a lot. I would keep it vertical though.

like a scroll view?

**Comment by johnkslg** [comment]
Not exactly. Lets just make it cap the max height to keep it from going off the top of the screen, and it shrinks the icons to fit if that happens.

**Comment by sidjuego** [comment]
![8](https://user-images.githubusercontent.com/43029943/46147845-3d9d7100-c284-11e8-9b81-a32502c536c8.PNG)
![10](https://user-images.githubusercontent.com/43029943/46147846-3d9d7100-c284-11e8-9730-2914ed3c6292.PNG)
![7](https://user-images.githubusercontent.com/43029943/46147847-3e360780-c284-11e8-9397-aab29b6a578f.PNG)


@johnkslg please go through the images attached. That's how the view would look with different number of objects. Please note the height is same in all 3 images. Need your input on this.

**Comment by johnkslg** [comment]
Top is best, never want to stretch the icons against their aspect ratio.  Should make sure it only shrinks if its too big.
