### ISSUE TITLE
Cart problems: a few along with some (hopefully) useful observations

### ISSUE THREAD

**Issue by Dimestore42** [StrangeLoopGames/EcoIssues#914]
Problem #1: When the world coordinates roll over from 0 to 1000 or 1000 to 0 the cart glitches. The screen goes blank white and the cart stops moving. The player is able to put the cart down as usual and then the world returns to normal but the cart almost always remains just on the other side of the boundary. It seems to be a matter of both luck and momentum to be able to get a cart to "move" far enough across the rollover that it is possible to pick it up on the other side. 
Moderate workaround: I build a ramp on each side of the boundary with a small flat space between to get some downhill momentum. This gets the cart across with a small number of tries pretty reliably.  
Slight better workaround: If you pilot the cart backwards (cart first) over the boundary then it more reliably ends up on the other side of the boundary when you set it down and pick it up again.

**Comment by Dimestore42** [comment]
Problem #6: Cart ownership doesn't reliably stay with deed holder. It will often change to the land owner if left on someone else's land for a while. It sometimes also clears to "unowned".

**Comment by metachronism** [comment]
most/all of these are resolved
