### ISSUE TITLE
Failed to establish connection (German)

### ISSUE THREAD

**Issue by HazeCavelli** [StrangeLoopGames/EcoIssues#9141]
Verweis auf Steam-Link: [https://steamcommunity.com/app/382310/discussions/4/1735462352488960181/]

`<size=150%>Verbindung fehlgeschlagen</size>

Failed to establish connection - no response from remote host

Log File:
Initialize engine version: 2018.2.0f2 (787658998520)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce 820M (ID=0x1140)
    Vendor:   
    VRAM:     1999 MB
    Driver:   21.21.13.6909
Begin MonoManager ReloadAssembly
- Completed reload, in  0.942 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.639644 ms
Client version: 0.7.7.0 beta staging-b938b54c
Wednesday, August 22, 2018 2:04 PM
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

LocalServer -  Eco Server 0.7.7.0 beta staging-b938b54c
LocalServer -  Server Initialization... 
LocalServer -  Starting LocalizationPlugin... 
LocalServer -  Starting ModKitPlugin... 
LocalServer -  Loading mods... 
LocalServer -  Compiling mods... 
LocalServer -  Mods recompiled with errors.
LocalServer -  Error in ElectroBlastFurnace at 116: Die beste �bereinstimmung f�r die �berladene 'Eco.Shared.Localization.Localizer.Do(System.FormattableString, params string[])'-Methode hat einige ung�ltige Argumente. (CS1502)
LocalServer - Error in ElectroBlastFurnace at 116: Argument '1': Konvertierung von 'string' in 'System.FormattableString' nicht m�glich. (CS1503)
LocalServer - Error in ElectroKiln at 44: 'Eco.Gameplay.Property.RequireRoomMaterialTierAttribute' enth�lt keinen Konstruktor, der 2-Argumente akzeptiert. (CS1729)
LocalServer - )'-Methode hat einige ung�ltige Argumente. (CS1502)
LocalServer - Error in ElectroKiln at 95: Argument '1': Konvertierung von 'string' in 'System.FormattableString' nicht m�glich. (CS1503)
LocalServer - )'-Methode hat einige ung�ltige Argumente. (CS1502)
LocalServer - Error in ElectroKiln at 120: Argument '1': Konvertierung von 'string' in 'System.FormattableString' nicht m�glich. (CS1503)
LocalServer - )'-Methode hat einige ung�ltige Argumente. (CS1502)
LocalServer - Error in ElectroKiln at 206: Argument '1': Konvertierung von 'string' in 'System.FormattableString' nicht m�glich. (CS1503)
LocalServer - )'-Methode hat einige ung�ltige Argumente. (CS1502)
LocalServer - Error in ElectroKiln at 229: Argument '1': Konvertierung von 'string' in 'System.FormattableString' nicht m�glich. (CS1503)
LocalServer - )'-Methode hat einige ung�ltige Argumente. (CS1502)
LocalServer - Error in ElectroKiln at 253: Argument '1': Konvertierung von 'string' in 'System.FormattableString' nicht m�glich. (CS1503)
LocalServer - 
LocalServer -  Loading mods finished in 19.112,0ms
LocalServer -  Server Initialization finished in 35.727,1ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Connection complete.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)`

**Comment by metachronism** [comment]
@HazeCavelli looks like you may have some errant extra files in the mods directory of your install.  Have you tried clean installing per chance?

**Comment by HazeCavelli** [comment]
I have no mods for ECO installed, I've tried several times on Steam for damaged files to look for but nothing came out.

**Comment by elfl0rd** [comment]
try copy your saves, delete game, delete game folder, then install it again.

ElectroKiln it's mod files, not vanilla

**Comment by HazeCavelli** [comment]
But I have not installed a single mod, I would know that. There is only one folder in the mods folder with AutoGen - WordObjects - ElectroKiln and ElectroBlastFurnace

**Comment by elfl0rd** [comment]
https://eco.mod.io/electric-versions-mod

Pirate copy?

**Comment by BlazeGuy2** [comment]
No response since elfl0rd's last msg, closing.
