### ISSUE TITLE
Severe drop in FPS when map is open AMD Radeon

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#9142]
Version: 0.7.6.3 beta

Steps to Reproduce:

1. Close your map and then hit esc to see what your frames per second (FPS) is. 
2. Hit Escape again to go back to the game
3. Hit M to open your minimap 
4. Now hit Esc again and look at your frame rate and cry when you see the huge drop in the FPS

Expected behavior:

The  map would not cause a huge lost in Frames per Second like this
and make the game laggy just by opening the map. 

Actual behavior:

Well the actual behavior appears to be that when the mini-map closed I
will be at  37 - 38 FPS I can sit in the exact same position and then open my
mini-map and hit esc again and watch the FPS be at like 3 - 5 FPS

When I go to move with the map on it is all choppy and laggy but soon as
I turn off the minimap everything is great.

Something is going really wrong with the mini-map here that it is taking that
big  of a drop in the FPS and yes I have my mini-map turned way  way down 
too. 

Here are some screenshots of this issue:

First one is with the map turned OFF  see all good like 37.2 FPS

![eco map off aug 31 2018](https://user-images.githubusercontent.com/38896397/44919885-c7950100-acfb-11e8-8f23-cdfdfa0d1063.jpg)

Now with the minimap on and sitting in the same spot I have not moved all I 
did was hit M and then hit ESC again to get back into the same window again.
Now I am at about 4.6 FPS just by turning my mini map on NO other settings or anything
has been changed.  What the heck why the big frame rate drop? 

![eco map on aug 31 2018](https://user-images.githubusercontent.com/38896397/44920107-4d18b100-acfc-11e8-88c5-4763f7b73bf3.jpg)

Now so you can see my advanced settings as well there is nothing really strange 
there in fact most of it is turned off. 

![advanced settings eco aug 31 2018](https://user-images.githubusercontent.com/38896397/44920277-b993b000-acfc-11e8-9575-cde3d3f31b26.jpg)

I am running Eco at 1920x1080 for the resolution and that is also the same
as my desktop resolution as well. 

Now the video card I am using is an AMD Radeon HD 7700 series card.  (2 GB of memory on it) 

The full specs for this card can be seen at 
https://www.amd.com/en-us/products-site/Pages/desktop-graphics-7700.aspx#

The computer itself is an Intel I7-2600 3.40 GHZ with 16 GB of RAM
running Windows 10 Pro (version 10.0.17134 Build 17134)
The machine is a Dell Optiplex 790. 

There should be no way that it causes this much lagging when you simply 
open the mini map and as I said before my setting for the minimap 
is turn way way down too already something isn't right here.

I have attached a DXDIAG as well so you can see the rest of 
the specs for this machine.

[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2340603/DxDiag.txt)

I had this open in another ticket and it got closed as a dupe and yet you guys are 
complaining that no one is responding to it. 

https://github.com/StrangeLoopGames/EcoIssues/issues/6775

"Reopening this one as a general catch-all for poor frame rate. Since there's no one thing that's 
contributing to it, this but will stay open for awhile as we improve it."

And then it got closed claiming that the ticket was not useful and 
the issue never got fixed in #6775

"closing, this is not useful as a bug - this is an infinite task"

Not useful why didn't the people who were complaining about this
issue get contacted via email to see if the problem was still 
ongoing before closing it off as "not useful" appears that
some one at Strange Loop Games is just closing off 
tickets weather they are fixed or not. 

The other ticket I opened about this same issue in Ticket #7800 (May 16 2018)
https://github.com/StrangeLoopGames/EcoIssues/issues/7800

It got closed as a "dupicate" and then you closed the other ticket
that you said it was a dupliate of #6775 and never fixed the problem! 

I see several complaints along the same line all of which got closed off
and never resolved.

This issue is going back as far as 0.7.3.3 and the issue is still
not resolved. 

https://github.com/StrangeLoopGames/EcoIssues/issues/7392

Please do NOT close this ticket until the issue is fixed this time! 

At least try and work with me on this issue please! I am a very
experienced person when it comes to computers and have
worked in the computer field I am also a trained network admin
and I have done my comp-tia A+ so I do know what I am talking 
about and is probably a good person to help you isolate this issue. 

The game runs perfectly when the map is closed... soon as you open it
boom a huge FPS loss and it is laggy as hell even when you have the 
settings for the map detail turned way way down! 

And you don't even have to be mousing over the map either 
for it to cause the FPS drop you just have to have the map
open to see the frame rate drop. 

Turning down the map detail setting isn't the issue here there is another
problem going on here with the game.  I strongly believe that there
is some kind of an issue here with the map and that this issue is directly
related to the map being open. 

Also this matter is not server dependent either I can go to any 
server and have the same problems. 

Also I don't have to be in a built up or crowded area either to get this lag 
with the mini map in fact when I tested this i was out in some open water 
swimming all by myself.

I will come on the ECO disord if need be and talk to some one and 
we can do some troubleshooting on there if need be. 

https://discordapp.com/invite/eco

Some one really needs to look into this immediately this is a bad bad bug!

**Comment by thereporter42** [comment]
Oh and just so you know I just went on "Stuffed Elk" as well which is the offical test 
server for Eco which is running 7.7.0 Beta Staging-B938B54C 
and got the same issue as described above. 

This was a fresh install of the client downloaded right from the Eco offical 
download area. 

https://s3-us-west-2.amazonaws.com/eco-releases/EcoPC_v0.7.7.0-beta-staging-b938b54c.zip

**Comment by johnkslg** [comment]
Following up

**Comment by thereporter42** [comment]
What do you  mean follow up? do you need more info or what are you looking
for?

**Comment by thereporter42** [comment]
Do you want me to come on the Discord Server one night and talk to one of you and try and troubleshoot 
this issue a bit more. I am on ussally more in the evening hours I am in MST (GMT-0700) Please let me know.

**Comment by johnkslg** [comment]
Sean has done a ton of work on minimap performance, going into 8.0. This is probably addressed then, but will leave to Sean if he wants to resolve it or not.

**Comment by thereporter42** [comment]
Ok well I will wait for 8.0 then and see if it is addressed if they are revamping the
mini map in that version. Any kind of a time frame for 8.0 to be released?

**Comment by SeanAtr0n** [comment]
should be fixed
