### ISSUE TITLE
USER ISSUE: 200% match? how it work?

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9143]
**Version:** 0.7.7.0 beta staging-b938b54c
![default](https://user-images.githubusercontent.com/4980243/44933962-d3bca500-ad73-11e8-9998-a8ea5f4cb79b.png)

**Comment by johnkslg** [comment]
Its a really good match!
Can you change this to read 
Match Score: 200

**Comment by elfl0rd** [comment]
I still do not understand how it should work :)
Maybe % from 0 to 100 is better?

**Comment by Spydarlee** [comment]
I think the idea is just that the higher the score the better, it's not tied to a specific range of values or anything, @elfl0rd.

Submitted a pull request with the loc change you suggested, @johnkslg.

**Comment by elfl0rd** [comment]
"match score" is not a good idea, how players will learn - what is 10 score? it's good? 50? wow, 100... ideal? not.. i see 110...


my opinion - range from 0 to 100 % is ideal, 0% - no match with your settings. 100% - 100% match.
Standart, easy, and good.

**Comment by elfl0rd** [comment]
match scores still not looks as solution =|
