### ISSUE TITLE
USER ISSUE: Crash while fishin'

### ISSUE THREAD

**Issue by NeverGoatWest** [StrangeLoopGames/EcoIssues#9144]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
1. Throw out the line
2. Wait for fish to bite on
3. Get impatient due to glitchy physics and run out towards it while reeling in
4. Server dies in thermonuclear hellfire the moment the electronic fish collides with the positronic fishing pole

**Expected behavior:**
The server not going thermonuclear and crashing, rather me receiving a tasty fishie

**Actual behavior:**
Server dies in thermonuclear hellfire/crashes

**Comment by elfl0rd** [comment]
can you attach more info? server .log, dump files, etc?
