### ISSUE TITLE
Contract, bad currency on server restart

### ISSUE THREAD

**Issue by tom4897** [StrangeLoopGames/EcoIssues#9148]
**Version:** 0.7.6.3 beta & 0.7.7.0 beta staging-7756716e

**Steps to Reproduce:**
1. With a clean game (_/spawnEconomy_, _/give contractboard_)
2. Create a contract and select the currency _Test ClientBills_ for the payment clause
3. Disconnect
4. Load the game and check the contract

**Expected behavior:**
The payment clause should be using the selected currency.

**Actual behavior:**
The user's currency is set for the payment clause.

**Comment by Voosle** [comment]
?!  #8174

**Comment by Voosle** [comment]
https://github.com/StrangeLoopGames/Eco/issues/3252 !

**Comment by elfl0rd** [comment]
you can self close issue :P
