### ISSUE TITLE
Real Estate Disk can't put up deeds for sale

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9149]
I could put up all my deeds up for sale earlier but now - after i enlarged one deed to around 100 claims i can only put up this one for sale, but not my other two ones. We used that feature to distribute claims in the capital that is protected from claiming. Maybe the list don't show other deeds when you got one with very much claims?

**Comment by D3nnis3n** [comment]
Here you can see what i can put up for sale: <img width="1920" alt="otherdeed" src="https://user-images.githubusercontent.com/25908592/44945624-b4625e00-aded-11e8-8085-eeb8f5309588.png">

And here is my other deed i wanted to sell: <img width="1920" alt="possiblesales" src="https://user-images.githubusercontent.com/25908592/44945625-b4faf480-aded-11e8-9649-66c3590f3da1.png">

**Comment by seccombew** [comment]
@MarjieAVolk Did you make a fix for this?

**Comment by MarjieAVolk** [comment]
Hey there - in your first screenshot, it looks like you haven't actually listed your deed for sale yet.  You have to click the 'List' button to put it up for sale.  Is this your problem?  Or did you just take the screenshot before clicking the button?

**Comment by D3nnis3n** [comment]
Oh, i did not get that was an unfinished listing, so you are right. I need to press list before i can make a new listing. Problem is that i did not finish that Listing and didn't want to but could not remove that view, it does not reset when i go away and go to the listing again. (Though ist works like that on other real estate desks in the world) So i need to place and then remove it, that's a bit suboptimal.

**Comment by MarjieAVolk** [comment]
Yeah it would be nice if it reset to the 'create' button when you navigated away.  I can do that.

You should be able to just edit the form though, rather than listing and deleting it.  That is, just change the selected deed in the drop down there.

**Comment by MarjieAVolk** [comment]
Fixed in 8.0
