### ISSUE TITLE
Network issue / crash / power grid / on  tailoring table

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#915]
I have a user having issue with a crash ( on discord "ckchessmaster") he says the following : 

I got the following error and was kicked from my server after trying to place the tailoring table. This is a fresh 5.1 server. After several attempts to place the table and getting kicked the server crashed. Upon restarting the server, I found multiple tables where I was trying to place it. If I picked them up with the hammer I again could not place them and if I tried to store them they caused another exception and got kicked again.

i attached the log files 

[ClientNetworkException 12231144.txt](https://github.com/StrangeLoopGames/EcoIssues/files/670473/ClientNetworkException.12231144.txt)
[ClientNetworkException 12231219.txt](https://github.com/StrangeLoopGames/EcoIssues/files/670476/ClientNetworkException.12231219.txt)
[ClientNetworkException 12231257.txt](https://github.com/StrangeLoopGames/EcoIssues/files/670475/ClientNetworkException.12231257.txt)
[ClientNetworkException 12231344.txt](https://github.com/StrangeLoopGames/EcoIssues/files/670478/ClientNetworkException.12231344.txt)
[ClientNetworkException 12231401.txt](https://github.com/StrangeLoopGames/EcoIssues/files/670477/ClientNetworkException.12231401.txt)
[ClientNetworkException 12231549.txt](https://github.com/StrangeLoopGames/EcoIssues/files/670474/ClientNetworkException.12231549.txt)
[ClientNetworkException 12231800.txt](https://github.com/StrangeLoopGames/EcoIssues/files/670479/ClientNetworkException.12231800.txt)
[ClientNetworkException 12231956.txt](https://github.com/StrangeLoopGames/EcoIssues/files/670480/ClientNetworkException.12231956.txt)
[Crash 12231549.txt](https://github.com/StrangeLoopGames/EcoIssues/files/670481/Crash.12231549.txt)

**Comment by Airidal** [comment]
I just experienced this bug on the SLG server on version 0.5.3.  The error that I received after crashing back to the server selection screen was "Caught exception: Constructor on type Eco.Gameplay.Components.PowerGridComponent not found".

Seeing as I think the server restarted just after my third attempt to place the table I was able to find out about duplicate tables.  There were tables where I had attempted to place it.  I however did not experience the crash again when attempting to store the tables.

**Comment by Z-FiRE** [comment]
Exactly same thing here.

**Comment by phoenixfangor** [comment]
Same thing happened to me on 5.4.

![2017-02-05 08_43_30-eco](https://cloud.githubusercontent.com/assets/1885171/22627028/af2105ae-eb7f-11e6-9fd5-6bea4b679ded.png)

**Comment by kotus78** [comment]
Same Issue, tried building in a log house

**Comment by metachronism** [comment]
was not able to repro this in 5.5.2, likely fixed
