### ISSUE TITLE
electric stamping press has no storage options

### ISSUE THREAD

**Issue by insomniac04** [StrangeLoopGames/EcoIssues#9151]
**Version:** 0.7.6.3 beta

placed electric stamping press after crafting it.

I expected to be able to link all nearby storage's to it.

No storage tab appears anytime the stamping press is accessed
![screenshot 4](https://user-images.githubusercontent.com/42890623/44945820-8822ef00-ada5-11e8-9e87-a451729abee9.png)

**Comment by elfl0rd** [comment]
dupe https://github.com/StrangeLoopGames/EcoIssues/issues/8547

**Comment by craig-jong** [comment]
this is fixed in current 7.7 staging.
