### ISSUE TITLE
USER ISSUE: Where's My Sign

### ISSUE THREAD

**Issue by Spaceferret42** [StrangeLoopGames/EcoIssues#9152]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
Place Large Hewn Log hanging sign in world
Put in text complete with color codes

**Expected behavior:**
Color code show up in text edit in the edited text
words show up after save on sign

**Actual behavior:**
just has the alphanumeric code show up in edited text
Blank sign

**Comment by elfl0rd** [comment]
add screenshot please

**Comment by Spaceferret42** [comment]
![2018-09-01 1](https://user-images.githubusercontent.com/35748070/44949750-c64bfd00-adfd-11e8-9d39-b7ed237c9036.png)
![2018-09-01](https://user-images.githubusercontent.com/35748070/44949751-c77d2a00-adfd-11e8-8f72-01b465ac65b6.png)
Here are two screenshots one of the edit screen and one of the sign itself

**Comment by elfl0rd** [comment]
@Spaceferret42 man... It's back side of sign...
Rotate it...

**Comment by BlazeGuy2** [comment]
Sign placed backwards.  Reopen if text bug is happening on the front of the sign.
