### ISSUE TITLE
World wont load in multiplayer

### ISSUE THREAD

**Issue by wslaghekke** [StrangeLoopGames/EcoIssues#9153]
I'm not sure why but this only happens on the Fatalcraft server with my account, i tried it with a different computer and with  a different internet connection and the same thing happens

Steps to reproduce:
1. Connect to the Fatalcraft server (ip is 107.173.81.146:16115)
2. See the world doesnt load properly

Excepted behaviour:
I join the server and can play

Actual behaviour:
One of the following two things happen:

1A. The game freezes and windows tells me the program isn't responding, i can see the blocks of the world that are near me (around 20 blocks radius) but furnaces and other interactive objects are missing

1B. The game joins the server, but wont load more than the initial 20 blocks radius and interative objects dont load, also the world doesnt load any further and the red disconnected icon appears.

Logs for both:
[1A.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2342683/1A.txt)
[1B.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2342684/1B.txt)

**Comment by Conchipedia** [comment]
Just out of Curiosity connected to this server,  Joined and played without any Problem My world Location (UK)

**Comment by beastyn** [comment]
Should be fixed. If you meet this issues after 8.1 reopen please
