### ISSUE TITLE
Ramps not available in law making item list

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#9156]
We cannot make a law that applies to any type of RAMP. We wanted to tax players for picking up ramps in a specific district.

![image](https://user-images.githubusercontent.com/1503963/44951999-7b53d900-ae41-11e8-93bd-ee7767f508d9.png)

**Comment by elfl0rd** [comment]
fixed in future update.
Currently ramps is not item,
Ramps is worldobject.
