### ISSUE TITLE
Invisible Blocks

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#9157]
Attempting to place blocks in particular spots fails with "Can't place a block there".

This is different from the "invisible tree stump" bug, as there was never a tree here. (The Soil Sampler does not reveal the presence of an invisible tree, either.)

Attempting to fill the space with dirt dropped from above also fails.

7.7 Staging.

![invisibleblock](https://user-images.githubusercontent.com/2173684/44952232-fbb81f80-aebd-11e8-81cd-7a69374dc807.gif)

The conditions to trigger this bug are not known.

World file can be provided for analysis on request. @Valheran.

**Comment by valheran** [comment]
Additional bit of information- this server has a few mods, one of which interrogates the identity of blocks in a column. using this tool through the problem block shows it as a "WorldObjectBlock", instead of the expected "EmptyBlock"

**Comment by LiaungYip** [comment]
It appears that a server restart fixes at least some of these phantom blocks.

**Comment by LiaungYip** [comment]
For what it's worth, we believe this was the same bug as https://github.com/StrangeLoopGames/EcoIssues/issues/9196 - vehicles spawning world objects / occupancy blocks.

**Comment by CobaltEcho** [comment]
Was there a solution found to this?
