### ISSUE TITLE
7.7 Staging - Trucks must be very lightweight

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9158]
<img width="1920" alt="truck" src="https://user-images.githubusercontent.com/25908592/44956365-13de6d80-aec3-11e8-986c-ec619c37277d.png">
Nothing more to say

**Comment by D3nnis3n** [comment]
Falls down as soon as the players gets off the truck.

**Comment by beastyn** [comment]
Seems to be a little havier in 0.8.1
