### ISSUE TITLE
7.7 - Wheelbarrow Animation

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9159]
<img width="1920" alt="wheel" src="https://user-images.githubusercontent.com/25908592/44956801-f3fe7800-aec9-11e8-95fb-a3b522ff6ead.png">
Looks … unnatural :D One should also be able to pull instead of push it. Also, it seems quite slow for it having less weight than a cart.

**Comment by SeanAtr0n** [comment]
fixed in svn, you can also now go up some blocks
![wheelbarrowop](https://user-images.githubusercontent.com/774628/52508895-fcf72200-2baa-11e9-8d9e-53ae8b0bad88.gif)
