### ISSUE TITLE
Butchery Efficiency reduces meat gain as well as animal cost (edit: also speed is not reduced)

### ISSUE THREAD

**Issue by jhadred** [StrangeLoopGames/EcoIssues#916]
Butchery Efficiency reduces meat gain.
Without efficiency, 1 elk gave 10 meat, or 1 buffalo gave 20 meat.  With efficiency 1 elk gives 9 meat.

Also... when choosing to process larger amounts, 10 carcasses elk was going to give 100 meat.  But with a 12% reduction on both sides, I choose to process 11, which uses 10 carcasses but only gives 97 meat.

![image](https://cloud.githubusercontent.com/assets/20424793/21462462/65b75cc8-c92a-11e6-8fda-75ab6562fa8f.png)

![image](https://cloud.githubusercontent.com/assets/20424793/21462522/0200f206-c92b-11e6-9a80-d6e64f20b48a.png)

**Comment by metachronism** [comment]
for craig:

Looks like one of the skills values is going down instead of up

also, the skills should give more meat in the recipe, instead of using less carcasses

**Comment by jhadred** [comment]
Additional screenshots with the skill tooltips over the elk meat, hide and carcass and the skill tree itself indicating all three are modified.
![image](https://cloud.githubusercontent.com/assets/20424793/21463021/595414e2-c931-11e6-8538-13401e487a6e.png)
![image](https://cloud.githubusercontent.com/assets/20424793/21463022/5e4d3c76-c931-11e6-84b1-d8608b688467.png)
![image](https://cloud.githubusercontent.com/assets/20424793/21463024/635fcfee-c931-11e6-9a38-9b1b38e2bbd7.png)
![image](https://cloud.githubusercontent.com/assets/20424793/21463036/86f57544-c931-11e6-97f9-b47c743aa5cf.png)

**Comment by jhadred** [comment]
And small butchery too
![image](https://cloud.githubusercontent.com/assets/20424793/21463041/9ab78c84-c931-11e6-85be-61e7739ef724.png)

**Comment by jhadred** [comment]
Small butchery as well:
![image](https://cloud.githubusercontent.com/assets/20424793/21463049/a92c0006-c931-11e6-8212-0b09524103a7.png)

**Comment by jhadred** [comment]
Also related (should I enter another issue?)  Butchery speed skill does not affect speed.  
![image](https://cloud.githubusercontent.com/assets/20424793/21463059/cb98e9a6-c931-11e6-8b1b-7f8677a1cdd9.png)

**Comment by craig-jong** [comment]
this is fixed
