### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Filimon210490** [StrangeLoopGames/EcoIssues#9162]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Could not create save file: Access to the path "C:/Program Files (x86)/ Eco/Eco_Data\Server\Storage\DefaultWorld" or "C:/Program Files (x86)/ Eco/Eco_Data\Server\Storage\2321312312.eco" is denied.
```

**Comment by Deantwo** [comment]
Looks like a Pathing issue.
Would be helpful to know what operating system you are using.

**Comment by BlazeGuy2** [comment]
@Filimon210490 Need more info on what OS you are using before we can address this issue.

**Comment by BlazeGuy2** [comment]
Reopen when you can send me more info.
