### ISSUE TITLE
7.7 Staging - Connection by server browser not possible / Browser failing

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9163]
I can't connect to any server by the server browser (Connecting screen does never get away), i can without problem connect directly by ip, though.

Also quite often the Server Browser does not show any servers even after searching for half an hour. This can be fixed by restarting several times until it works again.

**Comment by BlazeGuy2** [comment]
This is a known issue on stable staging #9112.  Is this happening on bleeding_edge_staging as well (slightly more up-to-date build)?

**Comment by BlazeGuy2** [comment]
Closing as a dup
