### ISSUE TITLE
Hosted Worlds (Issues)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9164]
**Version:** 0.7.7.0 beta staging-aaf5ba98 (Version was told to use as given download Link)

![snap2617](https://user-images.githubusercontent.com/29383891/44983072-cb30be00-af6f-11e8-899b-df82be79de05.png)

World will **Not Rename.**

This is what i see as name
![snap2613](https://user-images.githubusercontent.com/29383891/44982597-5ad56d00-af6e-11e8-99f8-203597d365a9.png)
this is what i tried renaming to
![snap2614](https://user-images.githubusercontent.com/29383891/44982665-92441980-af6e-11e8-9a12-97a4d4644254.png)
no matter how many times i Press Return key or try and click on the tick,as soon as i refresh this page it defaults back to Original name.

![snap2618](https://user-images.githubusercontent.com/29383891/44983157-22369300-af70-11e8-8856-e7ed102a1fb7.png)

When i try and enter my name or Choose the World i want (even leaving name blank) it comes up with a moving busy symbol to the left but nothing seems to happen no matter how long i leave it going
![snap2615](https://user-images.githubusercontent.com/29383891/44983288-95400980-af70-11e8-84ad-e1504347c5d0.png)
![snap2619](https://user-images.githubusercontent.com/29383891/44983336-b86ab900-af70-11e8-9305-f55d129a81ef.png)

this is what was tested on Web page, now to the game and trying to load the World in.

Would have expected that because i OWN a world it would automatically show up in my world list
![snap2620](https://user-images.githubusercontent.com/29383891/44983439-17c8c900-af71-11e8-9c36-3bb29d6b27ea.png)

Obviously it would **NOT** be in favorites or LAN and joining it manually it doesn't show up in Recent
so i think we need a special One for "Owned Worlds" like we have a special one for "Official Test Servers"

now on to trying to get into the world by using "join Server Directly"
![snap2621](https://user-images.githubusercontent.com/29383891/44983584-96256b00-af71-11e8-97ac-f4e4eb4d80d4.png)

not sure what you changed but trying to type into this is a nightmare, it will **NOT**  show up as you type and the **ONLY** way i managed to work out what it was doing was to keep clicking on the text window with left mouse button.

Finally i joined the world and it loaded, First issue i am **NOT** Admin, which was supposed to happen as i supposedly **OWN** this world.

this is the following steps i tried just in case not being Admin was a glitch, i disconnected after i had typed
/help then /authlevel 
![snap2611](https://user-images.githubusercontent.com/29383891/44983812-75a9e080-af72-11e8-8433-6be00a34bda9.png)

when rejoining i see this
![snap2610](https://user-images.githubusercontent.com/29383891/44983852-9e31da80-af72-11e8-8bae-482eecb8e6bc.png)
which is totally Different from what i thought would appear as the name of the World

Now on Continuing for the 2nd time, My character Creation was reset and i had to set up my avatar again (since disconnecting and continuing after this glitch i am not getting that happen anymore) not sure if it was because i put my name into Citizens Window (have tried to duplicate by doing that and i'm still the character i created)

Did the First Tutorial (as i normally skip everything) as you did say you wanted it to be tested, the movement keys take a while to actually detect.

then i did The Meteor one, ok this is a bit Disappointing as i ONLY got this world showing up after @rainfarmer sorted this bit out for me

![snap2622](https://user-images.githubusercontent.com/29383891/44984219-e00f5080-af73-11e8-9973-fbc8c935d6fb.png)
as you can see this world is **16 days old** 

![snap2612](https://user-images.githubusercontent.com/29383891/44984313-3086ae00-af74-11e8-9bb3-f1c02bf5792d.png)
and i have four Zero populations (Creosote Bush, Bullrush, Pitcher Plant and Rice) and Two that has only 1
population (Saguaro Cactus and Crimini Mushroom)

Not too worried about Creosote Bush, Bullrush or Pitcher Plant (as i don't see a use for those) But Rice (food source) , Saguaro Cactus (important Desert Log yield) and Crimini Mushroom (Spore used to unlock Farming Skill Book). so The World Needs to Have a reasonably Balanced Ratio of Biomes, Plants and Animals (failure to do this Check when world is created will NOT help the Selling point for schools)

That's all i have found so far and that's just in the first 15-30 minutes, there are other glitches i think as this is staging, but not sure which version you are on for latest staging so will **NOT** be checking too much into those, just mentioning that trying to find plants in this version is a bit confusing
![snap2623](https://user-images.githubusercontent.com/29383891/44985173-40ec5800-af77-11e8-9510-d893be37f59c.png)
is the population previous to the name of plant the Plant i want?

Exported CSV looks a mess and all seems to be just under Column A , maybe have a separate Column for each part?
[EcoSubAccounts_login_info.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2345395/EcoSubAccounts_login_info.zip)

When getting a NEW World have we a choice of Size? or is it default?  (didn;t even want to attempt this part yet until asked)

Ideas for when Creating a NEW World
1. give them an option of size required (reason for this, Schools and Classes vary in size and players may want a bigger or smaller world) maybe give information about the difference of different size worlds

2. Create World (after getting size information) Check this world has no Zero population and no missing Biomes

3. Make sure that the person who has this world on their Account (being it a single player or a School/Teacher) that they are Admin, because at the moment does the owner put his/her name down as a Citizen and the Top most one being the Admin? or can we have a Special One so an Admin can be chosen?

**Comment by rainfarmer** [comment]
Great feedback, thanks!
I fixed the server and citizen naming issues.
Working on the no admin bug

I think I accidentally gave you an old world, sorry about that. Assuming that is why plants are wonky.
Hit me up on discord and ill get you a new world.

The ip entering is a staging glitch that is fixed now.
