### ISSUE TITLE
Minimap and UI show different authoriation resp. location naming

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9167]
Version: v0.7.7.0-beta-staging-b938b54c

UI naming is correct, Minimap naming is displaced one plot

![location snip](https://user-images.githubusercontent.com/38510829/44992000-41e0b200-af96-11e8-9603-b51ff1646bb2.jpg)

![location-2 snip](https://user-images.githubusercontent.com/38510829/44992051-6b99d900-af96-11e8-9f92-916d258c8d7c.jpg)

**Comment by beastyn** [comment]
Looks like still an issue with smaller range
![bandicam 2020-09-18 18-07-41-191](https://user-images.githubusercontent.com/27898520/93600992-f1e8b280-f9d9-11ea-8f20-e83e3664066d.jpg)
