### ISSUE TITLE
Maximum in Logging with iron Axe still hits Wood pulp (debris) 3x as much as hitting Tree or Stump

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9169]
**Version:** 0.7.6.3 beta

![snap2636](https://user-images.githubusercontent.com/29383891/44997848-35b22000-afa9-11e8-8642-db5ae4891f2b.png)

As can be seen below i hit a Tree log for 6.1
![snap2635 edited](https://user-images.githubusercontent.com/29383891/44998094-c806f380-afaa-11e8-9714-bba1972a6e00.png)

I then hit Wood Pulp (debris) for 18.3
![snap2634 edited](https://user-images.githubusercontent.com/29383891/44998106-ea007600-afaa-11e8-8b7c-08d1de9e4784.png)

this seems totally broken as the Debris is way smaller than a Tree or a Stump and will not encourage people to clear up behind themselves if it costs 3 times as much to do so.

**Comment by Conchipedia** [comment]
Also another Argument for having the Debris clearing go down in calories like Chopping Trees is to encourage those with Maximum Logging Skill Hire out there Services for clearing Debris.

was going to Edit original to add this at the End but just saw that it went into needs triage so added After

**Comment by craig-jong** [comment]
This is intentional. Basically not a bug that it costs 3 times as much. That value IS reduced by the skills - removing debris costs 3 times as much at all levels.

We are, however, going to change how debris is handled in general.
