### ISSUE TITLE
Logs and other Building Blocks will magically hang in the Air when placed against another Block (except Dirt, Sand, Tailings and Rubble)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9170]
**Version:** 0.7.6.3 beta

If you place a log against any block it will magically just stay there, it should drop to the floor just like rubble does
![snap2637](https://user-images.githubusercontent.com/29383891/44998570-9e4fcb80-afae-11e8-9345-266842d78ec4.png)

**Comment by Conchipedia** [comment]
Same goes for Mortared Stone
![snap2638](https://user-images.githubusercontent.com/29383891/45000054-947f9580-afb9-11e8-88ae-42048ce7b301.png)

so i'm guessing all but Rubble, Dirt, Sand and Tailings will act this way and not fall to the floor by gravity

**Comment by Conchipedia** [comment]
**Version:** 0.8.0.3 beta seems to have fixed the Log problem, they now drop to the Floor, But Clay can be stuck in the Air

**Comment by elfl0rd** [comment]
intended for clay, сlay sticks.

**Comment by SlayksWood** [comment]
merged to #13255
