### ISSUE TITLE
Server browser gets wrong port number

### ISSUE THREAD

**Issue by goertzenator** [StrangeLoopGames/EcoIssues#9171]
My server is running on port 3000, but the server browser is advertising 37824.  As a result noone can connect to my server through the server browser.  Once I give the direct connect information it works instantly.

## Details
- Linux (NixOs), with mono-5.8
- Eco server downloaded from website (7.6.3).  Client is not present on this machine.
- Network config is...
```
{
  "PublicServer": true,
  "Password": "something",
  "Description": "Dan's Terrarium",
  "IPAddress": "Any",
  "GameServerPort": 3000,
  "WebServerPort": 3001,
  "Rate": 10,
  "MaxConnections": 20
}
```
- Pam (who is awesome) helped me out and gave me this line from her favourites file.  Note the totally wrong port number:
`{"Description":"Dan's Terrarium","UniqueIdentifier":3720084779297568767,"Address":"142.161.151.254","GamePort":37824}]`
- My router (pfsense) is forwarding ports 2999-3001 both tcp/udp.
- I ran a server months ago and didn't have issues like this.

## Questions
- I note the server recently got NAT punching.  Should I be turning off all my port forwarding now?
- Is there a way to turn off NAT punching?  I think it is interacting badly with my setup.

**Comment by pamduncan** [comment]
Think this is related to the following.  It has been occurring on Linux as well as Windows servers
https://github.com/StrangeLoopGames/EcoIssues/issues/9228
https://github.com/StrangeLoopGames/EcoIssues/issues/9203
https://github.com/StrangeLoopGames/EcoIssues/issues/9112

**Comment by SlayksWood** [comment]
Relay server was added in 8.3.0. Which solves many connecting issues. If it happens again, please reopen.
