### ISSUE TITLE
Small hanging stone sign offset issue sign won't sit flat on wall

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#9173]
Version: 0.7.6.3 beta

Steps to Reproduce:
1. Craft a smal hangingl stone sign
2. Try and put it on the wall
3. Walk so you are to the side of the sign and look at about the 1/4 to 3/4 of a block gap off of the wall.
4. Cry and put your sign back in your backpack again because it looks so bad

Expected behavior:
That the small hanging sign fit tightly against the wall so that there isn't a huge 
gap behind it. 

Actual behavior:

Well the way it is right now there is some where about a half a block
to 3/4 of a block off the wall when you place a small hanging stone sign some
where. It just looks terrible. 

Now I checked first before opening this ticket and there were too past tickets
about this issue but they are both closed off.

https://github.com/StrangeLoopGames/EcoIssues/issues/8195
https://github.com/StrangeLoopGames/EcoIssues/issues/8055

Now in ticket #8055 it claims to have been fixed in 7.6 

I can tell you that this issue isn't fixed the signs won't sit tightly up 
against a wall.

As you can see I was trying to hang it on the dirt face of the wall just to the
left of the door. 

This screenshot gives you a pretty good reference as to how far it is sticking
out because you can see the blocks on the far side of the sign clearly. 

No matter what I did I could not get the sign to sit flat against the wall it always
seems to be inproperly offset and sticks way out. 

I was testing this with the small hanging stone sign I would also test the other hanging
signs as well because I have a feeling that all of the "hanging" signs are going to be doing
this. IE: Wooden hanging sign.

This is really annoying and it looks like hell can you please fix this. I tested this 
on September 4 2018 at about 3:41 AM MST (GMT-0700) and i was getting this. 

![small stone sign offset issue sept 4 2108](https://user-images.githubusercontent.com/38896397/45023821-afbbc680-aff4-11e8-97f6-37737e13d27b.jpg)

**Comment by seccombew** [comment]
dup

**Comment by thereporter42** [comment]
Dupe of what ticket I could not find any duplicate ticket..  you never listed what ticket number this is a duplicate of which you ussally do.  Please reopen this ticket!

**Comment by thereporter42** [comment]
So I guess this is a dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/8578
responded on another ticket #9185
