### ISSUE TITLE
Devtool Cannot be selected When Shovel is being used

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9176]
**Version:** 0.7.6.3 beta

This Bug has crept back into the game again.

It's a shame that the Shovel is the **ONLY** tool that cannot be swapped while carrying anything

**Comment by SlayksWood** [comment]
more information in issue #11960

**Comment by Conchipedia** [comment]
only workaround i have found of how to use Devtool while carrying dirt or sand is to put shovel in backpack so it is taken out of the equation
