### ISSUE TITLE
Hosted Worlds - admin powers not working in-game /fly

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#9178]
User logged into server with main account, can't use /fly or teleport

But can change servername which does require admin

**Comment by Phlo123** [comment]
neither does /move /teleportplayer or /eat. I haven't tested anything else.

**Comment by Conchipedia** [comment]
i find a normal /help shows me quickly enough if i am Admin, as normally you ONLY see User Commands then i type /authlevel followed by /eat (the last one just to make sure)

**Comment by Conchipedia** [comment]
![snap2645](https://user-images.githubusercontent.com/29383891/45061325-eef12280-b09b-11e8-8c2c-59050e39c5c4.png)

Doesn;t work for me but i did see the name "Free World" appear in continue then i went back to 
![snap2646](https://user-images.githubusercontent.com/29383891/45061361-1c3dd080-b09c-11e8-837f-a95f6b286f89.png)
which is weird as before it said this
![snap2610](https://user-images.githubusercontent.com/29383891/45061411-442d3400-b09c-11e8-92cd-acd9f6b38017.png)
are we getting More than one world at this 
54.213.231.66:3000

**Comment by Conchipedia** [comment]
![snap2647](https://user-images.githubusercontent.com/29383891/45061567-eb11d000-b09c-11e8-8c81-688a4ef7ec41.png)
ok this is weird are we all Using the SAME world??

**Comment by Conchipedia** [comment]
![snap2648](https://user-images.githubusercontent.com/29383891/45061659-59569280-b09d-11e8-91b5-bb2202e43534.png)

now i manged to get this appear, all i did was change into Your Worlds Menu, Pressed ESC to come back now its showing as this, it looks as if we have multiple worlds all on the same IP and Port, as they are all saying different days

**Comment by rainfarmer** [comment]
i think the worlds are different, but might be mixing up names in our db.
from the Worlds page, click the World Dashboard button, and see what name it has

**Comment by Conchipedia** [comment]
![snap2652](https://user-images.githubusercontent.com/29383891/45062089-50ff5700-b09f-11e8-88a9-21e557ae86f8.png)

**Comment by Conchipedia** [comment]
Still cannot rename my World
![snap2669](https://user-images.githubusercontent.com/29383891/45091646-04516580-b10b-11e8-8460-b9c29741612a.png)
as it wants me to login for the First time, i seem to be in Two Worlds by using my IP and PORT But none seems to be mine, If i keep trying to choose One of the Ones that shows up as a different name in continue, still no luck and then will get stuck on connecting screen
![snap2675](https://user-images.githubusercontent.com/29383891/45091723-4084c600-b10b-11e8-9b3e-906af77cdecd.png)
and this i cannot ESCAPE at all and have to shut the game down with ALT F4

Am wondering if the problem i am having is that i have steam running in the background all the time, but i AM using the SLG Version (EcoPC_v0.7.7.0-beta-staging-aaf5ba98) which is the one i was told to use
