### ISSUE TITLE
Testing Hosted Worlds  Continue showing different information

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9179]
**Version:** 0.7.7.0 beta staging-aaf5ba98

Ok this is a weird Bug to try and explain, so bear with me

I connect to My so called Hosted World at my Account Via IP And Port (this is hard to do in this Staging Version as it will not showing typing until you click on it and not always then)

Now to get this part to duplicate be on the screen with Continue on, now go into Your Worlds menu (i did this to check if Recent was updated to MY Hosted Server, Still nothing) Now Press ESC
and nearly everytime you do this the Information in Continue is changing

![snap2655](https://user-images.githubusercontent.com/29383891/45062543-4ba30c00-b0a1-11e8-913b-20107639a13c.png)
![snap2656](https://user-images.githubusercontent.com/29383891/45062560-5c538200-b0a1-11e8-938c-f5cbf1497612.png)
![snap2657](https://user-images.githubusercontent.com/29383891/45062577-6ecdbb80-b0a1-11e8-915d-21664713748e.png)
![snap2658](https://user-images.githubusercontent.com/29383891/45062648-cd933500-b0a1-11e8-9db0-56e350e56ca8.png)
![snap2659](https://user-images.githubusercontent.com/29383891/45062668-e56ab900-b0a1-11e8-8a8f-06037ff305b1.png)
![snap2660](https://user-images.githubusercontent.com/29383891/45062697-0af7c280-b0a2-11e8-9307-16c42127bf5d.png)

stopped adding these snapshots and i still cannot change the name of my world as i am supposed to log in for the first time - and which of the Above worlds is mine???
![snap2661](https://user-images.githubusercontent.com/29383891/45062743-41cdd880-b0a2-11e8-8a70-23132e04d591.png)

to someone without any knowledge this looks like i enter the IP and Port and when Eco loads up and gets the name from the Last Server i played on its getting this information from somewhere (this i worked out because it is working out how many users are online so it must be checking the world somehow)

**Comment by Conchipedia** [comment]
Another quick test , My Account page with my World i click on World Dashboard and i go to a page showing this (web address is http://54.213.231.66:3001/)
![snap2664](https://user-images.githubusercontent.com/29383891/45063081-03391d80-b0a4-11e8-9acf-5871e9e823fb.png)
Now if i load up my game and then choose Run for Office (web address ishttp://18.236.240.159:3001/elections.html?)
![snap2665](https://user-images.githubusercontent.com/29383891/45063134-5b701f80-b0a4-11e8-8658-6dff1f5e6dcc.png)
and the **ONLY** IP and Port i used to join to my world in Eco is
54.213.231.66:3000

**Comment by Conchipedia** [comment]
![snap2667](https://user-images.githubusercontent.com/29383891/45063560-7a6fb100-b0a6-11e8-9435-d637c30b2e5e.png)
![snap2652](https://user-images.githubusercontent.com/29383891/45063604-a1c67e00-b0a6-11e8-99d3-ae0b47f3507f.png)

this time i put in the same 54.213.231.66:3000 
but now in another world as i haven't claimed anything in this one and as you see above two different information windows
now running for Office on this world take me to (this we address http://54.213.231.66:3001/elections.html?)
![snap2668](https://user-images.githubusercontent.com/29383891/45063673-041f7e80-b0a7-11e8-9cf5-5db22ebe39e7.png)
which according to my Account page this is My address but then according to me trying to rename it, i still Haven't logged in for the first time
![snap2669](https://user-images.githubusercontent.com/29383891/45063734-71331400-b0a7-11e8-8b76-87b51533a3f2.png)

**Comment by elfl0rd** [comment]
same as ingame "recent" and "favorites" section.
Works only direct IP connection... everytime... damnit.
Most likely because the id is based on the machine... Then all servers have same.

**Comment by rainfarmer** [comment]
working on it thanks
