### ISSUE TITLE
Some recipes need to add RequireSkill

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#918]
For the store selection dialog (and eventually others), I'm displaying only items with recipes which have discovered skills required. These are the list of items that are available at the start. Some shouldn't be available, like ThermalCrackingUnit, but it's there because it's recipe requires no skills. Can you go through this list and make sure all the high level stuff has a recipe that requires a skill properly?

Coal]</style>}	Eco.Gameplay.Items.Item {CoalItem}
Copper Ore]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.CopperOreItem}
Dirt]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.DirtItem}
Gold Ore]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.GoldOreItem}
Iron Ore]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.IronOreItem}
Log]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.LogItem}
Petrol]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.PetrolItem}
Sand]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.SandItem}
Stone]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.StoneItem}
WaterBlockItem]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.WaterItem}
Industrial Furnace]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.IndustrialFurnaceItem}
Industrial Robot]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.IndustrialRobotItem}
Quality Controller]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.QualityControllerItem}
Smithing Tool Shelf]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.SmithingToolShelfItem}
Thermal Cracking Unit]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.ThermalCrackingUnitItem}
Bean]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.BeanItem}
Beet]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.BeetItem}
Birch Seed]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.BirchSeedItem}
Bullrush Seed]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.BullrushSeedItem}
Bunchgrass Seed]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.BunchgrassSeedItem}
Camas Bulb]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.CamasBulbItem}
Cedar Seed]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.CedarSeedItem}
Corn]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.CornItem}
Creosote Bush Seed]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.CreosoteBushSeedItem}
Ecoylent]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.EcoylentItem}
Fiddlehead]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.FiddleheadItem}
Fireweed Seed]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.FireweedSeedItem}
Fireweed Shoots]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.FireweedShootsItem}
Giant Cactus Fruit]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.GiantCactusFruitItem}
Grass Seed]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.GrassSeedItem}
Huckleberries]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.HuckleberriesItem}
Prickly Pear Fruit]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.PricklyPearFruitItem}
Sagebrush Seed]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.SagebrushSeedItem}
Sugarcane]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.SugarcaneItem}
Wheat]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.WheatItem}
Bison Carcass]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.BisonCarcassItem}
Elk Carcass]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.ElkCarcassItem}
Fox Carcass]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.FoxCarcassItem}
Hardy Beard]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.HardyBeardItem}
Hare Carcass]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.HareCarcassItem}
Nuclear Fuel]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.NuclearFuelItem}
Plant Fibers]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.PlantFibersItem}
Short Beard]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.ShortBeardItem}
Strange Fuel]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.StrangeFuelItem}
Turkey Carcass]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.TurkeyCarcassItem}
Wolf Carcass]</style>}	Eco.Gameplay.Items.Item {Eco.Mods.TechTree.WolfCarcassItem}
Dev Tool]</style>}	Eco.Gameplay.Items.Item {DevtoolItem}
Hydrometer]</style>}	Eco.Gameplay.Items.Item {HydrometerItem}
ElectricLamp]</style>}	Eco.Gameplay.Items.Item {ElectricLampItem}
Pumpjack]</style>}	Eco.Gameplay.Items.Item {PumpJackItem}
Transmission Pole]</style>}	Eco.Gameplay.Items.Item {TransmissionPoleItem}

**Comment by johnkslg** [comment]
Can also add "Hidden" to get rid of them

**Comment by craig-jong** [comment]
What do you want me to do about the items on this list that should be available at the start?
