### ISSUE TITLE
Long name format error in voting graph

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#9180]
long name in election chart https://gyazo.com/335be44fe573ef31238287d27c8c7e3c
Should just hide part of name and stay on one line.
Combo of white-space: nowrap; and overflow:hidden; should do the trick

**Comment by Tigran07** [comment]
Made a commit on branch voting_graph_name
Now only the first 10 letters of the candidate's name will be shown in the table.
