### ISSUE TITLE
Update No Auth mode for Web Interface Builds

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#9181]
Think you could set the user creation debug mode to work in release mode. specifically with a build?
VS and bleeding edge code is too buggy to rely on for external people.
and on web we dont usually need bleeding edge version of game
its working for now, but only a matter of time before master has some weird bug or vs starts acting up again

**Comment by johnkslg** [comment]
Should be working!  Try in a release build of master

**Comment by rainfarmer** [comment]
Works mostly, I'm able to remove citizen law. Run for election and vote. 
But when I go to propose a law page, it crashes the server. 
No crash file returned.

**Comment by johnkslg** [comment]
Filed a separate bug for this: https://github.com/StrangeLoopGames/EcoIssues/issues/9226
