### ISSUE TITLE
Campsite property claim offset

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#9183]
Saw this happen when I placed my campsite, on a feature branch off master:
![image](https://user-images.githubusercontent.com/23460210/45064217-5c369080-b067-11e8-801f-82897460231e.png)

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/73171885-d2cba680-4112-11ea-87fa-3338d14ee732.png)
![image](https://user-images.githubusercontent.com/45708377/73171904-db23e180-4112-11ea-9b3d-623ebb6d7a98.png)
We have separate issue for wrong highlighting with shadowplacement.
