### ISSUE TITLE
USER ISSUE: Log dissapeares after cutting the tree

### ISSUE THREAD

**Issue by SturmGhost** [StrangeLoopGames/EcoIssues#9186]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
When the game is hosted by another player cutted trees somtetime dissapears. A reconnect fixes the issue. So this bug is related to a synchronisation issue between the clients IMHO.

**Expected behavior:**
You guessed it: Cutted tress to not dissappear

**Actual behavior:**
Cutted trees disappear

**Comment by seccombew** [comment]
Dupe
