### ISSUE TITLE
Tooltip hide issue - v.0.7.7.0

### ISSUE THREAD

**Issue by dwujcik** [StrangeLoopGames/EcoIssues#9188]
The tooltip cannot hide, when moving the mouse - version 0.7.7.0

![20180905202957_1](https://user-images.githubusercontent.com/17785084/45113456-ae041700-b14a-11e8-8ed3-8ab3298d97de.png)

**Comment by Nicolausi113** [comment]
reported in #9132

**Comment by metachronism** [comment]
dupe of #9132
