### ISSUE TITLE
Chunk / blocks losing collision / invisible /Voxels missing / invisible on house ( mesh limit? )

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#919]
http://ecoforum.strangeloopgames.com/topic/1208/chunk-lost-collision

**Comment by metachronism** [comment]
if someone runs into this reliably, please attach the game.eco file with coordinates of where it occurs

**Comment by noblackthunder** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/943 duplicate

**Comment by noblackthunder** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/1039
