### ISSUE TITLE
7.7 Graphic artifact in Claim Stake in claimed areas

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#9191]
NVidia 1080 TI
Mid Range in game graphics settings

When Stake is on toolbelt, set it as active and start to use it.  make it active and it looks like:
[![Screenshot from Gyazo](https://gyazo.com/503e06c55d37e1b1ab2a5b649dfad509/raw)](https://gyazo.com/503e06c55d37e1b1ab2a5b649dfad509)

But if you go through an area of previously claimed land, or are working at claiming and reclaiming or anytime the claim stake is active in a claimed plat, including right after claiming the plot the stake has artifacts or distortions iof various sizes and line shapes. This is with default plot color:
[![Screenshot from Gyazo](https://gyazo.com/0fad501bff0d4f4fdd3617a939193cfe/raw)](https://gyazo.com/0fad501bff0d4f4fdd3617a939193cfe)
[![Screenshot from Gyazo](https://gyazo.com/bf9ffe17704408fc911dfa9d9d45ecd4/raw)](https://gyazo.com/bf9ffe17704408fc911dfa9d9d45ecd4)
[![Screenshot from Gyazo](https://gyazo.com/179cff07633101fa71310a078377a137/raw)]
(https://gyazo.com/179cff07633101fa71310a078377a137)

This is with a color change:

[![Screenshot from Gyazo](https://gyazo.com/b01e0abb4c90c1a1fbc07aa529502947/raw)](https://gyazo.com/b01e0abb4c90c1a1fbc07aa529502947)

Adjust graphics settings did not seem to change the amount of artifact.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/72339814-0ef51500-36d8-11ea-8a08-475ef0d018ef.png)
![image](https://user-images.githubusercontent.com/45708377/72339845-216f4e80-36d8-11ea-9800-3026e816fb0d.png)

**Comment by SlayksWood** [comment]
> While holding land claim stake, odd graphic bug can be clearly seen on the stake.
> 
> Possibly caused by lighting effects / land highlight effect
> 
> ![stake ](https://user-images.githubusercontent.com/78054747/122195128-a57ac680-cec8-11eb-8605-818d0624096b.gif)
