### ISSUE TITLE
Suggestion for adds the new things

### ISSUE THREAD

**Issue by dwujcik** [StrangeLoopGames/EcoIssues#9192]
Please add:

**Vehicles**:
- mini digger
- lawn mower to grass

**Weapons**
- guns, sniper rifle, knives, 

**Weather**
- animations of changes the seasons (winter, autum, summer, spring)
- rain, fog, storm, thunders,wind, snow, heat
- animations of player example: coldly, heat, temperatures

**Physics**
- gravitation for all objects
- animations for destroys objects

**Effects**
- fire of forest, houses etc. to reasons of global warming

**Animals**: 
- the chickens (for meat and eggs), 
- horses (for fast travel), 
- cows to produce the milk,
- dogs for protect against of the wolfs,
- sheeps for clothes on the winter ;)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#537
