### ISSUE TITLE
No longer need checkbox for hiding servers because its in the filters for the recommended servers now

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9193]
![image](https://user-images.githubusercontent.com/3536496/45123573-34edcb00-b11c-11e8-8df2-0212512515fa.png)

**Comment by Nanders** [comment]
These two tickets boxes perfom different tasks related to region locking

**Comment by johnkslg** [comment]
How so? Its not clear from the labels

**Comment by Nanders** [comment]
Server filter only filters for servers that your seraching for in the server browser

Config setting hides recommended and suggested servers that do not match your language

**Comment by Nanders** [comment]
Escape menu setting is for this
![image](https://user-images.githubusercontent.com/6262198/45124196-4637d700-b11e-11e8-8048-f076c1138b41.png)

**Comment by johnkslg** [comment]
I added a filter button to this window, it looks like its been since overwritten.  Ill bring it back.

**Comment by johnkslg** [comment]
So I added a filter button to the reccomended listing, check it out here:
https://github.com/StrangeLoopGames/Eco/pull/3346

This does the same thing as the checkbox in the escape menu but has more flexibility, so I'd like to remove that checkbox as we shouldnt have duplicate ways to do the same thing.

**Comment by elfl0rd** [comment]
Filter in recommended server list, is more logic and easy for understand.
but two note.
first. need save filters
second, if saving filters present - change button to show "filters changed"
