### ISSUE TITLE
7.7 - Failure to convert the world

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9196]
Seems, the world is a bit too big, eh?
<img width="1920" alt="error" src="https://user-images.githubusercontent.com/25908592/45127087-fdf8d300-b176-11e8-8b74-118601bb40f4.png">

**Comment by D3nnis3n** [comment]
The world is a 16 km² world. If you need it, i can give you a link once again :)

**Comment by johnkslg** [comment]
@LucasDomberg can you attach your smaller world to this?

**Comment by LucasDomberg** [comment]
I hope you mean this
![ecofailurebigworld](https://user-images.githubusercontent.com/32537640/45226637-aca82b00-b2bf-11e8-9d66-840db22b4d3b.PNG)

**Comment by D3nnis3n** [comment]
He means the Content of your storage Folder.

**Comment by johnkslg** [comment]
@LucasDomberg yes need the game.eco file, though that is helpful too.

**Comment by johnkslg** [comment]
@D3nnis3n yours as well plz!

**Comment by johnkslg** [comment]
Tagging for hotfix

**Comment by SeanAtr0n** [comment]
looks like vehicles were spawning occupancy blocks that they shouldn't have & you had a cart flying several km above the surface, will be fixed in a hotfix soon

**Comment by LucasDomberg** [comment]
Thank you very much :D

**Comment by D3nnis3n** [comment]
@SeanAtron
This is not fixed for my save. Probably has to do with and is unfixable therefore, e.g. my world is fucked up?
I can start it on 0.7.6.3 just fine, though - as of your answer in the other issue it should crash then, like it did.

**Comment by D3nnis3n** [comment]
Should i open a new issue, will you reopen this or is it just unfixable and stays closed therefore?

**Comment by SeanAtr0n** [comment]
i couldn't download your world to verify, should be fixed in 7.7.2

**Comment by D3nnis3n** [comment]
Oh, well probably you tried when the backup ran. It should be downloadable now.

**Comment by CobaltEcho** [comment]
Has this been fixed in a release?  It looks like the excavator is the cause of these invisable blocks on our server.

**Comment by D3nnis3n** [comment]
We didn't have an excavator at that time.
