### ISSUE TITLE
Eco screen only says quit

### ISSUE THREAD

**Issue by p2wguy** [StrangeLoopGames/EcoIssues#9197]
![image](https://user-images.githubusercontent.com/43019205/45127451-52d02580-b146-11e8-8108-1d09b687e8df.png)
I use a mac and it's my first time playing the game.

**Comment by johnkslg** [comment]
That aint good. @p2wguy can you contact me on discord.gg/eco @johnk

**Comment by johnkslg** [comment]
@SeanAtr0n can you help with this one? Will try to follow up with filer on discord

**Comment by SeanAtr0n** [comment]
On my mac I have Continue, Your Worlds and Quit. (No new game button is an obvious problem but looks like a separate issue... filed a separate bug here https://github.com/StrangeLoopGames/EcoIssues/issues/9220)

Could you send us your log file ~/.config/unity3d/CompanyName/ProductName/Player.log

Does the game appear to be frozen or are things in the background moving?

**Comment by SeanAtr0n** [comment]
Nevermind, guess this is the same issue if you haven't connected to a server before

**Comment by p2wguy** [comment]
Things are moving in the background like the windmill.

**Comment by BlazeGuy2** [comment]
@johnkslg NewGameServerBrowser.prefab changes might have been overwritten in latest staging update.  Can you reapply the changes to master?

**Comment by johnkslg** [comment]
Should be fixed I hope.
