### ISSUE TITLE
USER ISSUE: Starter resources

### ISSUE THREAD

**Issue by Skippy224** [StrangeLoopGames/EcoIssues#9199]
**Version:** 0.7.7.0 beta

**Steps to Reproduce:**
Go to distribution station on test server and take more than allocated items

**Expected behavior:**
Limit how much fish etc you can take

**Actual behavior:**
Lets you take whatever you want but says you're not allowed to.

**Comment by johnkslg** [comment]
May be fixed in master already, walker can you repro?

**Comment by D3nnis3n** [comment]
Another of the issues i would really like to get a higher priority. With 25 players online on average resources have been draining out very quickly and i can't just be online 24/7, explaining everyone in depth how he can only take 10 of something and not everything - which in turn leads to people not being able to start out, as they haven't good enough food :(

**Comment by elfl0rd** [comment]
@D3nnis3n fixed in current release as i see.

**Comment by D3nnis3n** [comment]
Indeed fixed.
