### ISSUE TITLE
USER ISSUE: Error when creating Multiple Tree Harvest law

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#9200]
**Version:** 0.7.7.0 beta

**Steps to Reproduce:**
Player action>Harvest>Where>Tree type
Hit the plus
Player action>Harvest>Where>
Both prompts change to "Time performed (days)"

**Expected behavior:**
After second "Where" command, should have been able to select tree type again.

**Actual behavior:**
Both prompts change to "Time performed (days)"

![image](https://user-images.githubusercontent.com/38095046/45135413-e1539f80-b164-11e8-89a4-258ac5639a5d.png)

**Comment by MarjieAVolk** [comment]
Hmmm, I just tried this out on 7.7.1, and it seems to be working for me.

**Comment by MarjieAVolk** [comment]
Do you see this issue every time?  Or did it only happen once?

**Comment by Hydrohawk** [comment]
Sorry for the delayed response.  Real life has been busy.

Yes, I've had this occur more than once.  It seems like every time I try to add a second clause via the plus sign, I get the same issue happening.  Our server is running the current release version of the game.  I'm also running Firefox (62.0 (64-bit)).  Not sure if that impacts anything.

**Comment by Hydrohawk** [comment]
I'll look at it again tomorrow night.  Maybe I missed something.

**Comment by Hydrohawk** [comment]
OK...It kind of works.  Really glitchy though.  It will go to the "Time performed" option every time I add a new line.  I can trick it back into place, but it's more than a little cumbersome.

**Comment by MarjieAVolk** [comment]
I'm going to guess that this is related to firefox, haven't tried it out yet though.

**Comment by WeaselDog** [comment]
I have experienced this issue in 8.3. I do not have this problem in 0.9.0 staging when creating laws.
I think was related to lag when using the web UI for laws on some servers.
