### ISSUE TITLE
Problem with players who did not complete tutorial in existing world when updated to 7.7

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#9202]
Getting complaints from people that some are getting started over on worlds they were on after world updates to an existing world (not a new world) although most players were not back at start and had all their items, inventory, houses, land etc, started over.  It seems like its related to tutorial completion

I started a world in 7.6.3 and created a player and did part of the tutorial, about 6 steps into it.  Then I updated to 7.7 and I was able to load in fine - however I did end up starting over at the player creation screen.  I can see that would definitely be  an issue for someone that might have played for some time but not completed all parts the tutorial and when the world updates they have to start over

A couple of server owners have reported having to remove users that still had a few steps in tutorial to go but the world would not load at all, no dump file and the console gave no error  (after they heard about the tutorial it talked about in support and several players on their severer said they had not yet finished the tutorial)  they said they deleted the profiles of anyone still in the tutorial that the knew of  and said most were close to the end of the tutorial.  Since these crash were not making a crash report not sure if its the same issue or not.  

I am not able to repro that a player with a player with an incomplete tutorial will block a game from loading.   I tried several times, even taking a character right to the last two steps in the tutorial but the only thing that happened was that I was set back to the character creation screen in the updated world.  All the worlds I tried this on the player just started over.  Its possible that this was coincidental with some other problem with the player not the tutorial have to wait and see.  I did not have time to test all the other possibilities that brought up, as they did take tools out of the tent, I had not, some had build houses, I had not and so on.

**Comment by pamduncan** [comment]
Have a user on a singleplayer world - has been playing for a a while, can get in new worlds he creates but not in his old world.  he had a few steps left to comeplete.  I will get him to upload and link his  world

**Comment by johnkslg** [comment]
Fixed the issue blocking players from logging in.  Will be in hotfix.

let me know if any issues persist after that goes out. Thanks!
