### ISSUE TITLE
Server Connect via direct connect/seen in browser/sticks at connecting using broswer

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#9203]
Server is in Russia and you can connect by direct connect  37.205.84.200:3000
You can see the Server in the Browser both as a search and and in the main browse just searching the name
Alex Moon Servers:  NOTE:  The server owner is not able to see his server in the browser although I can

[![Screenshot from Gyazo](https://gyazo.com/53e33a3db04ae5f32b75029e6a494243/raw)](https://gyazo.com/53e33a3db04ae5f32b75029e6a494243)

When I try to connect through the browser this happen either it just goes on connecting forever or gives a 'Failed to connect' error.  If I favorite teh server thsi si what it shows in favorites:
{"Description":"Alex Moon Servers","UniqueIdentifier":-760229629785552300,"Address":"37.205.84.200","GamePort":36671}]

However game port is 3000.  
This is a windows 7 OS on a Virtual Machine, .Net is up to date
Server is set up correctly and configured correctly and it plays fine via direct connect

Maybe related to:  https://github.com/StrangeLoopGames/EcoIssues/issues/9112

**Comment by radical-las** [comment]
I am owner of this server, so addind some new information. Direct connection but after some time server crushes with socket exception: 
`--BEGIN DUMP--
Dump Time
09/06/2018 10:01:25

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Tutorial.UserTask.Opened()

--END DUMP--`

**Comment by metachronism** [comment]
the gameport will be different externally if you are hosting behind a NAT and don't forward ports

**Comment by pamduncan** [comment]
His ports are forwarded.. w went over that during the night

**Comment by radical-las** [comment]
Just to prove that ports are forwarded:
![firewall1](https://user-images.githubusercontent.com/43038955/45197330-6bddf100-b282-11e8-9e03-1d2d72020e5a.jpg)
![firewall2](https://user-images.githubusercontent.com/43038955/45197331-6bddf100-b282-11e8-8cc1-511a83ce81b1.jpg)
![forwarding](https://user-images.githubusercontent.com/43038955/45197332-6c768780-b282-11e8-9c8e-cc4e8924d841.jpg)

**Comment by SlayksWood** [comment]
Relay server was added in 8.3.0. Which solves many connecting issues. If it happens again, please reopen.
