### ISSUE TITLE
USER ISSUE: Glissement

### ISSUE THREAD

**Issue by Ripley2208** [StrangeLoopGames/EcoIssues#9204]
**Version:** 0.7.7.0 beta

**Steps to Reproduce:**

we can not do any maneuver without slipping, not being able to strike with the ax, the shovel, the Scythian, in short all the tools, our character slips away from the target. we do not move fast so:))

**Expected behavior:**

**Actual behavior:**

**Comment by BlazeGuy2** [comment]
Dup of #9205
