### ISSUE TITLE
USER ISSUE: glissement avec les outils

### ISSUE THREAD

**Issue by Ripley2208** [StrangeLoopGames/EcoIssues#9205]
**Version:** 0.7.7.0 beta

**Steps to Reproduce:**
on ne peut pas faire aucune manoeuvre sans glissement , pas capable de frapper avec la hache, la pelle, la scythe, bref tout les outils, notre personnage glisse en s'éloignant de la cible. on n'avance pas vite ainsi : )
(Goggle) traduction,

we can not do any maneuver without slipping, not being able to strike with the ax, the shovel, the Scythian, in short all the tools, our character slips away from the target. we do not move fast so:))

**Expected behavior:**

**Actual behavior:**

**Comment by Ripley2208** [comment]
Hello,
I should do what, I can not use any of my tools properly,
It's not possible to hit a tree, hit a block to remove it or even fish, draw is the same
no matter the tool, since the last update.
My character slides backwards, I make a fall depending on where I am or I go away from the goal,
very unpleasant, I would like to know if I am the only one to have this problem? Thank you.

**Comment by BlazeGuy2** [comment]
Hard to tell what is going on without a video to demonstrate what is going on.  @Ripley2208 Can you record this behavior and post a link to it?

**Comment by elfl0rd** [comment]
no answer for a long time, if you have video ar any additional information - open new issue, please.
