### ISSUE TITLE
USER ISSUE: discord address in server browser

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9206]
**Version:** 0.7.7.0 beta staging-7756716e
if
![default](https://user-images.githubusercontent.com/4980243/45156998-7cda2400-b1e8-11e8-9ebb-8eb339f55404.png)
result
![default](https://user-images.githubusercontent.com/4980243/45157013-895e7c80-b1e8-11e8-8be6-a78769b2f2e8.png)

if
![default](https://user-images.githubusercontent.com/4980243/45157039-9bd8b600-b1e8-11e8-85dd-3a1076115c6d.png)
result
![default](https://user-images.githubusercontent.com/4980243/45157059-aabf6880-b1e8-11e8-8cac-9617a0a5e8fa.png)

**Comment by johnkslg** [comment]
The top one is correct, user should only put the text after the discord url (thats for security, so bad URLs cant be sent through).

**Comment by elfl0rd** [comment]
but top one variant show nothing in server browser...

**Comment by sidjuego** [comment]
@elfl0rd @johnkslg 
Even if the user enters DiscordAddress as 'jsSccVG' or 'discord.gg/jsSccVG' or 'http://discord.gg/jsSccVG';
I will be displaying only 'http://discord.gg/jsSccVG' in server browser. Will it meet the current  requirement? Do you want it to be a http or https?

**Comment by elfl0rd** [comment]
for me - show `discord.gg/jsSccVG` really ok
and please use https in discord link.

**Comment by elfl0rd** [comment]
(and i have QoL request about server config window interface - https://github.com/StrangeLoopGames/EcoSuggestions/issues/535 )

**Comment by sidjuego** [comment]
> (and i have QoL request about server config window interface - [StrangeLoopGames/EcoSuggestions#535](https://github.com/StrangeLoopGames/EcoSuggestions/issues/535) )

Please excuse me but I'm unable to comprehend the actual requirement.

**Comment by sidjuego** [comment]
> for me - show `discord.gg/jsSccVG` really ok
> and please use https in discord link.

@johnkslg Awaiting confirmation on this.

**Comment by johnkslg** [comment]
When setting the discord address for a server, the user should only need to put the end of the discord address in, like in the first image:
![image](https://user-images.githubusercontent.com/3536496/45706575-6b224600-bb31-11e8-80d0-33d6365b2b15.png)


Then on the client it appends this to http://discord.gg/
Can you make sure this all works.

**Comment by elfl0rd** [comment]
@johnkslg yes, i have QoL request about it :)

**Comment by sidjuego** [comment]
@johnkslg 
As per this #9223 I believe the end result should now be 'https' and not 'http'.
