### ISSUE TITLE
USER ISSUE: single distributing item is not shown.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9207]
**Version:** 0.7.7.0 beta staging-7756716e
![20180906153113_1](https://user-images.githubusercontent.com/4980243/45157523-13f3ab80-b1ea-11e8-8d30-188bdc398488.jpg)
![20180906153137_1](https://user-images.githubusercontent.com/4980243/45157522-135b1500-b1ea-11e8-8ef3-1f683188038f.jpg)

**Comment by johnkslg** [comment]
Sid, this might be getting truncated, its supposed to say something like "and 1 other object", see why thats not happening.  The text is built into the ServerInfo class.

**Comment by krithikJuego** [comment]
As per this StrangeLoopGames/EcoIssues/issues/9297 , Could you confirm whether this issue persists in the current build?

**Comment by johnkslg** [comment]
I believe its fixed now
