### ISSUE TITLE
USER ISSUE: duplicated "distributed" line in server browser

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9208]
**Version:** 0.7.7.0 beta staging-7756716e
or what different "Community Supplies for new players" and "Gifts for new players"?
![default](https://user-images.githubusercontent.com/4980243/45157668-7ba9f680-b1ea-11e8-95e7-4351ff1d99a7.png)

**Comment by johnkslg** [comment]
'Significant impact on player experience'?

@sidjuego can you remove the lower field and make sure the code doesnt try to set it there.

**Comment by krithikJuego** [comment]
@johnkslg Could you confirm whether this issue still persists in the current build, please?

**Comment by johnkslg** [comment]
I dont know if its in the current build, can you check?

**Comment by elfl0rd** [comment]
Closing due to fixed.
