### ISSUE TITLE
Shop - Can't use "."

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9210]
Windows 10 - German Keyboard, German Language - English Language in Eco

If i put in a "." and save it vanishes, e.g. 0.75 becomes 75.
A "," can't be put in at all.

**Comment by D3nnis3n** [comment]
This does also apply to treasury, no "." or "," can be used. We had that bug before, i think.

**Comment by metachronism** [comment]
locale/localization issue likely?

**Comment by johnkslg** [comment]
ah there was a manual bug fix in textmeshpro that dealt with this previously....   
The issue was that the number restriction on the text mesh pro object wasnt considering commas for other locales.  See if that behavior is supported now.  If not, we will need to make our own filter or force it all to dots instead.

**Comment by D3nnis3n** [comment]
I got several other players - including myself - affected by this problem, which makes the economy hard to use. I would even beg you, to raise priority on this one. Some players can't really take part in the economy as long as this bug persists, as they can't offer to prices that are reasonable.

**Comment by D3nnis3n** [comment]
A player found a workaround by holding ctrl and clicking + and - in the shop. That will work for now. I somehow have to get that to the players, though. And sureley the player was awarded some money. *g*

**Comment by elfl0rd** [comment]
![r](https://user-images.githubusercontent.com/4980243/47275001-25cfb900-d5b4-11e8-8aee-daf5f2761949.gif)
![r](https://user-images.githubusercontent.com/4980243/47276834-dfce2180-d5c2-11e8-8cc6-d2b510113663.gif)
