### ISSUE TITLE
Trouble with Tooltips

### ISSUE THREAD

**Issue by Ket-SLG** [StrangeLoopGames/EcoIssues#9212]
https://steamcommunity.com/app/382310/discussions/0/2590022385653660254/

When trying to shift items in storage there always pops up the tooltip, which doesnt disappear and occludes part of the screen, so often it occludes the storage where I want to put the item.

Can you please set the tooltip delay to, like, 2s? And make it disappear automatically again?

**Comment by metachronism** [comment]
dupe of #9132
