### ISSUE TITLE
Birds not heard on loading screen

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9213]

**Comment by johnkslg** [comment]
Theres a TitleScreenAudio gameobject that is supposed to be active in the MinimalLoader scene.  There's also one in the game scene, that gets disabled if the loader one is present.  This used to all work, so see why the system is failling now. Also make sure it starts working if you return to the main menu.

**Comment by sidjuego** [comment]
@johnkslg Apparently, I am able to hear the audio. Could you verify whether this issue persists in the latest PR, please?

**Comment by johnkslg** [comment]
ok will check
