### ISSUE TITLE
Fix /spawnroad command

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9214]

**Comment by D3nnis3n** [comment]
Thanks for visiting our server.

But it got worse now as in the spawned ramps can't be removed anymore, now we got 4 unremovable ramps. :D

**Comment by johnkslg** [comment]
oh noeeeees

**Comment by johnkslg** [comment]
dev tool removes it?

**Comment by johnkslg** [comment]
Info on this bug:
Ramps got changed to spawn in one row at a time, but looks like the /spawnroad command needs to be updated to support that.
To test, type /spawnroad in the world.

**Comment by D3nnis3n** [comment]
Tried the dev tool, it's not able to smite the ramp - it smites the block beneath, like as if it is not really there but visible.
I can also place blocks onto it.

**Comment by D3nnis3n** [comment]
A server restart did remove those magic ramps.

**Comment by seccombew** [comment]
Updated bug title. - Fix /spawnroad so that it places ramps correctly.

**Comment by elfl0rd** [comment]
still actual, heh
