### ISSUE TITLE
Can't load game

### ISSUE THREAD

**Issue by Artaazar** [StrangeLoopGames/EcoIssues#9216]
Initialize engine version: 2018.2.0f2 (787658998520)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 970 (ID=0x13c2)
    Vendor:   
    VRAM:     4043 MB
    Driver:   24.21.13.9882
Begin MonoManager ReloadAssembly
- Completed reload, in  1.369 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.612900 ms
Client version: 0.7.7.0 beta
Tuesday, September 4, 2018 2:30 PM

LocalServer -  Eco Server 0.7.7.0 beta
LocalServer -  Server Initialization... 
LocalServer -  Starting LocalizationPlugin... 
LocalServer -  Starting ModKitPlugin... 
LocalServer -  Loading mods... 
LocalServer -  Compiling mods... 
LocalServer -  Loading FZM.Tools...
LocalServer -  Loading mods finished in 1�978,9ms
LocalServer -  Starting NetworkManager... 
LocalServer -  Initializing items... 
LocalServer -  Starting WorldGeneratorPlugin... 
LocalServer -  Starting GameplayStatsPlugin... 
LocalServer -  Starting BackupPlugin... 
LocalServer -  Starting StorageManager... 
Shutting down server
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

**Comment by Artaazar** [comment]
And some data from Windows Events
[ECO CRASH.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2358368/ECO.CRASH.txt)

**Comment by johnkslg** [comment]
Can you message me on discord.gg/eco @johnk

**Comment by johnkslg** [comment]
Determined it was the result of a mod.  Dropping in priority, and finding a way to better show mod errors to users.
