### ISSUE TITLE
Loan Rounding issues?

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9218]
One of our players gave a loan out, got it paid back but it still remains there with 0 in debt.

Is this intended or might it be a rounding issue where not all the money was paid back?
<img width="492" alt="debt" src="https://user-images.githubusercontent.com/25908592/45181595-2e944780-b21f-11e8-9db1-6c179c091888.png">

**Comment by johnkslg** [comment]
Detect tiny amounts and round them to zero when transacting loans.

**Comment by johnkslg** [comment]
Fixed
