### ISSUE TITLE
Alert Chat Command

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9219]
I'd like a command for admins that will allow me to make an announcement everyone really sees - like in other games a message that appears in the middle of the screen or something that everyone at least will definatley notice.

@johnkslg

**Comment by elfl0rd** [comment]
place for suggestions here - https://github.com/StrangeLoopGames/EcoSuggestions/issues

**Comment by D3nnis3n** [comment]
Eh, JohnK specifically told me to report a bug with mention to him, so i hope that was right. Otherwise: Sorry!

**Comment by johnkslg** [comment]
This works thanks D3nnis

**Comment by johnkslg** [comment]
@sidjuego to fix this bug, add a new chat command like Warn, that sends large text (use the text modifiers under Text to enlarge it) to everyoneon the server (theres a function for that, broadcastServerMessage or something similar).

Also while youre there, Warn should send a permanent message to the user, in large text, and not temporary.

**Comment by WeaselDog** [comment]
There is a popup ok box now. It could work nice in this role.

**Comment by D3nnis3n** [comment]
Feel free to add the command :) @WeaselDog

**Comment by gzatravkin** [comment]
This is already done. Preparing PR

**Comment by beastyn** [comment]
Not sure about this button part.
Can be really annoying or is this for somw reaaaally rare cases?
@D3nnis3n what do you think?
![bandicam 2019-11-28 11-34-53-502](https://user-images.githubusercontent.com/27898520/69782555-2f721a00-11d3-11ea-819d-a2ebc8451d2f.jpg)

**Comment by D3nnis3n** [comment]
I think it's up to the admins discretion. Useful uses would be for announcing clearly to everyone that the server will restart in five minutes. I don't have an issue with that, it's at least the best method to make sure everyone actually had the chance to read it - cause chat will not give that possibility.

What we also could do is to show it like the new notifications that show when you can't break a law, but there it would need to be so, that if you put in a rather long text, it is displayed long enough.

**Comment by beastyn** [comment]
Well, now you have /manage alert
Its fine for something important.

And announce should be like error, but in Yellow design and maybe they can go to the right part notifications (like civics notifications). So you can read them and close or leave there.

**Comment by D3nnis3n** [comment]
Has the /warn command be adapted, too? In chat it's pretty much ugly.

**Comment by beastyn** [comment]
@D3nnis3n  With what logic?

**Comment by D3nnis3n** [comment]
Yeh, that would work.

**Comment by beastyn** [comment]
Will make separate issue for warn and announce
