### ISSUE TITLE
Possible to lose items by canceling work order

### ISSUE THREAD

**Issue by Nes112** [StrangeLoopGames/EcoIssues#922]
If a crafting station's private storage is filled (either the inventory is full or the apparent weight limit of 4,000kg is reached), and a work order is canceled, the materials for that work order will not be refunded into private storage.

Suggest adding a prompt that doesn't allow players to cancel work orders when private storage is full.

This is mostly a problem at crafting stations like the Bloomery, where private storage fills up with Tailings very quickly.

**Comment by metachronism** [comment]
This has since been fixed.
