### ISSUE TITLE
Claim Stake Animation preceding other actions

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9222]
This is still the case with many actions. E.g. that it shows the animation when you got the claimstake in number one while carrying something or eating. I had several occasions today, i'll try to list them tomorrow, but need to go to bed now.

**Comment by D3nnis3n** [comment]
One common occasion:
Have something in your carry slot, e.g. lumber.
While that, use your claim stake.
You will now claim AND place lumber down - but if you reconnect, the lumber got back into your carrying slot and is no longer shown in the world.

**Comment by beastyn** [comment]
Now you can't carry something and take land claim stake in one time
