### ISSUE TITLE
Discord link is not https

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9223]
I - as Sysadmin - would consider that a bug, as security and therefore using https is important in my opinion. Probably is only a suggestion for you.

But anyways: Please consider using https for the discord link.

**Comment by sidjuego** [comment]
@johnkslg How would you like to proceed with this one?

**Comment by johnkslg** [comment]
Sure can change the link to https. Should take two seconds :)
