### ISSUE TITLE
Tutorial for rooms might be bugged

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9225]
A player reported to me that he placed down 4 walls each 5 wide on dirt, removed a dirt beneath a wall and got the tutorial "making a room" done - while that definatley has not been a full room without a roof. Lol.

**Comment by johnkslg** [comment]
it happens if someone finishes a room pretty close to you.... yeah its janky for now.

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/17735
