### ISSUE TITLE
Tailings Project instead of ... Ingot Project

### ISSUE THREAD

**Issue by Artaazar** [StrangeLoopGames/EcoIssues#9227]
![image](https://user-images.githubusercontent.com/8035935/45188928-23511400-b23f-11e8-979a-b31dbd1be271.png)

**Comment by BlameTheSystem** [comment]
This is the same for all smelting recipes in the blast furnace even with max eff skills i am getting 1 for 1 on taillings.

**Comment by elfl0rd** [comment]
@BlameTheSystem smelt x2, you receive 1 tailing from 2 ingot.

**Comment by CobaltEcho** [comment]
I can confirm.
![unknown](https://user-images.githubusercontent.com/26211498/45261641-870d4580-b3d5-11e8-9f1b-074a4fa3ab01.png)

**Comment by FalkosTMB** [comment]
![1](https://user-images.githubusercontent.com/43608607/46080117-52510a80-c199-11e8-8f7f-e75c344e0026.jpg)
![2](https://user-images.githubusercontent.com/43608607/46080125-57ae5500-c199-11e8-9717-4d99f03d414d.jpg)

**Comment by FalkosTMB** [comment]
It must be 1 Iron Bar / 0,5 Tailings

**Comment by craig-jong** [comment]
this is not occurring for me on staging, but I'll double check tomorrow on staging.

**Comment by elfl0rd** [comment]
Hm... Staging server is not starting for me...

**Comment by craig-jong** [comment]
Seemed fixed on staging. I'm going to close this, but we should double check this in a release build.

![image](https://user-images.githubusercontent.com/18184943/47522140-9f340980-d849-11e8-83e8-c1af82eac72c.png)

**Comment by elfl0rd** [comment]
Not fixed, it's revert to old TOO BIG tailings production.

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/47529283-343ffe00-d85c-11e8-9160-2ae9658d994d.png)

**Comment by craig-jong** [comment]
we good now

**Comment by elfl0rd** [comment]
Nope :D https://github.com/StrangeLoopGames/EcoIssues/issues/9867
