### ISSUE TITLE
Server won't show up in browser list unless TCP/UDP ports are open to at least 60000

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#9228]
From Kayako:

* The version of the game you were running: 0.7.7.0 beta
* Operating system: Windows Server 2016 Std
* Processor model: Intel Xeon  E5-2620 v4 Octa-core
* Graphics card model: ASPEED AST2400 BMC (onboard card for Supermicro  SYS-6028-TR)
* Amount of RAM: 382GB

One additional thing that you may want to include in your documentation.. especially for people who have 'real' firewalls on their networks.
They need to make sure that they have UDP/TCP ports open to at least 60000.  If they are not open, the server will not show up in the the server browser list.

**Comment by pamduncan** [comment]
We tried this last night to fix the Russian server with this issue and we had all ports open and it still did not work

**Comment by D3nnis3n** [comment]
For me everything works with only 3000 and 3001 open and all the rest blocked.

**Comment by metachronism** [comment]
cant repro
