### ISSUE TITLE
USER ISSUE: All Land Claims cleared

### ISSUE THREAD

**Issue by funnybunnyofdoom** [StrangeLoopGames/EcoIssues#9229]
**Version:** 0.7.7.0 beta

**Steps to Reproduce:**
I went to my property, took out my claim stick and nothing showed as claimed.  Then I received 36 claim papers in my inventory

**Expected behavior:**
Lit up to show my claim

**Actual behavior:**
Claims cleared

**Comment by BlazeGuy2** [comment]
@funnybunnyofdoom Can you record a video showing this happening?

**Comment by elfl0rd** [comment]
No answer, closing.
