### ISSUE TITLE
Calculation when exceeding max carry weight takes too long

### ISSUE THREAD

**Issue by Nes112** [StrangeLoopGames/EcoIssues#923]
The calculation that splits a stack when it is too heavy to be in your inventory seems to take way too long.

For example, if I move a stack of 100 boards into my inventory, but can only carry 30 of them, the current weight figure to the right of the toolbar will flash red for a good 10-15 seconds, before finally splitting the stack between my inventory and the container it was taken from.

It takes a shorter time for smaller stacks, something like 5 seconds for a stack of 50.

Seems like a bug to me.

**Comment by Dimestore42** [comment]
Same problem. If it's a particularly large stack the calculation will eventually finish but I will then be logged out for inactivity.

**Comment by MarjieAVolk** [comment]
Think this was improved a while ago
