### ISSUE TITLE
USER ISSUE: Tool Tips Annoying

### ISSUE THREAD

**Issue by LegionVarus** [StrangeLoopGames/EcoIssues#9230]
**Version:** 0.7.7.0 beta

**Steps to Reproduce:**
1. Drag an item from backpack to chest/stockpile.

**Expected behavior:**
The tool tip boxes should only appear with I hover over the item.

**Actual behavior:**
It appears as soon as I am dragging the item from my backpack to the chest/stockpile. Blocks my ability to move the item to the area.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/9132
dupe, fix provided, pulled soon.

**Comment by seccombew** [comment]
Fixed in 7.7.1
