### ISSUE TITLE
Steel Tool Repair Cost more than creation cost

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#9233]
My steel pick takes 4 steel and 2 boards to craft with my 80% steel working efficiency but it costs 6 steel to repair.

![image](https://user-images.githubusercontent.com/1503963/45196647-4376d800-b22b-11e8-82c3-3026fdb4901e.png)

![image](https://user-images.githubusercontent.com/1503963/45196673-57bad500-b22b-11e8-9b21-cd4af7f16a9f.png)

**Comment by extant1** [comment]
Just a side note, the decrease in materials for repairing is based on the metalworking skill and not metalworking efficiency for iron tools and likely works the same for steelworking.

**Comment by D3nnis3n** [comment]
Same for Iron Tools. I got both Metalworking and Efficiency maxed out - still 5 ingots for a full repair.

**Comment by craig-jong** [comment]
In my tests after the skill overhaul, this is no longer true.

Please reopen this if it still exists.
