### ISSUE TITLE
Tailing Containment

### ISSUE THREAD

**Issue by trevelmike** [StrangeLoopGames/EcoIssues#9234]
Pre patch my tailings were contained underground as of right now however pollution is spreading above ground. The tailing are buried 10 - 20 block underground it should not reach the surface.

**Comment by michaelberthold** [comment]
Same to me. Savegame can be provided.

**Comment by elfl0rd** [comment]
https://ecoauth.strangeloopgames.com/changelog/staging
as i see, it's lost in release changelog, but included.
`Tailings now produce reduced pollution at lower depths instead of a hard cut-off at 10`

**Comment by craig-jong** [comment]
this is intentional.

We'll be adjusting/changing this in the future, but for now consider it an experiment.

**Comment by elfl0rd** [comment]
Not member cannot see pull request in private repo.

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/46585082-b1096480-ca74-11e8-9793-6a74dcc5b4c0.png)
