### ISSUE TITLE
USER ISSUE: Steam Truck Text - no update

### ISSUE THREAD

**Issue by hami88** [StrangeLoopGames/EcoIssues#9235]
**Version:** 0.7.7.0 beta

**Steps to Reproduce:**
1.Change Text at Steam Truck
2.Press Save

**Expected behavior:**
Update to the input

**Actual behavior:**
Not updated (still Eco-Plate for me and you.)

**Comment by Conchipedia** [comment]
Still the same in 0.7.7.1
![snap2795](https://user-images.githubusercontent.com/29383891/45375274-62d78180-b5ec-11e8-82a2-0d26d775e6d4.png)

**Comment by zahnee** [comment]
Still an issue in 0.7.7.2 beta
![image](https://user-images.githubusercontent.com/18610605/47091980-fb68af00-d1f3-11e8-9d1f-b28b9dfec073.png)

**Comment by elfl0rd** [comment]
Wait 7.8
https://github.com/StrangeLoopGames/EcoIssues/issues/9443
https://github.com/StrangeLoopGames/EcoIssues/issues/9333

**Comment by Rambo99** [comment]
Confirmed in 0.7.7.2

**Comment by D3nnis3n** [comment]
Fixed in 7.8, duplicate of the aforementioned issues.
