### ISSUE TITLE
Upgrading from 7.6.3 to 7.7.0 you lose all of your ACL lists on all items

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#9236]
Version: 0.7.7.0 beta

Steps to Reproduce:

1. Install version 0.7.6.3 beta of Eco and then go into the game and play
    setup trunks a door etc with at least 2 people on each of the items. 
    Make sure you have 2 players doing this one person owning the items and
     the 2nd person as a person to able to access the items (IE: a chest) 

2. Upgrade to version 0.0.7.0 beta of Eco 

3. Go back into the game now and have the 2nd character try and and access the chest or door
 ect. 

4. The 2nd person has now lost total access to all to access to the items.

Expected behavior:

That when the server was updated from 0.7.6.3 Beta to 0.7.7.0 that the 
Acess control list (ACL) would have stayed in place. 

Actual behavior:

When you upgrade from 0.7.6.3 beta to 0.7.7.0 beta of Eco you end up 
losing your access control list on all your items! 

Chests, doors, tables, stockpiles and everything the access control list is just totally 
gone and is reset so that no one is on the items. 

I checked all of my items and everyone that did have access to my items
was no longer on there and was removed once the server was upgraded
to 0.7.7.0 Beta. They were in there before the upgrade but not after! 

If you also gave some one access to the property the 2nd person that 
was listed on the deed to have access is also removed. 

Pretty much the whole access list on all the items got wiped in
the update.  I don't know what happened but this is really annoying
now you have to go around to everything you own and redo the ACL
on every item in the game that you own because the ACL is wiped on
all items! 

Please look into this issue and ensure that this is fixed.

**Comment by thereporter42** [comment]
Investigate this is a bug.. it happened to me on a server I am playing on now 
and they upgraded from 0.7.6.3 and prior to that everything was fine I 
was logged in when the server was 0.7.6.3 and the access list on all of 
my items were fine I came back once they upgraded it it to 0.7.7.0 
and the access list on all my items were gone.

And it is really really annoying when you have a huge house with lots of 
items and multiple people on your access list on various items
to come back and find that the access list for everything is all gone. 

This is a bug should at least have a medium status on it maybe 
even high.

**Comment by johnkslg** [comment]
Hey @thereporter42 , sorry for the hassle, unfortunately youll have to re-setup the lists, because we redesigned our auth system and had to clear all the previous settings on server migration.  Should be a one time thing, and all future releases we hope to preserve them.  Thanks for filing the bug.
