### ISSUE TITLE
Server-Information does not work when a steam friend is online.

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9237]
See this, it only looks like that with a steam friend on the server.

<img width="1920" alt="steamfriends" src="https://user-images.githubusercontent.com/25908592/45218616-8a56e300-b2a8-11e8-8d8c-e98cac11479f.png">

**Comment by SlayksWood** [comment]
Checked on 0.8.1.3. Wasn't able to reproduce, seems fixed.
![image](https://user-images.githubusercontent.com/45708377/56424943-dea05780-62ba-11e9-9940-cc309efe8d2d.png)
