### ISSUE TITLE
Highlight of Land claim stake has visual bug

### ISSUE THREAD

**Issue by funnybunnyofdoom** [StrangeLoopGames/EcoIssues#9239]
**Version:** 0.7.7.0 beta

**Steps to Reproduce:**
hold the claim tool and look at the chunk highlighter	

**Expected behavior:**
highlighted the chunk, and retained it's texture

**Actual behavior:**
merged it's texture with the claim chunk highlighter, so it had bright yellow stripes across the model

**Comment by SlayksWood** [comment]
I guess It's about these stripes?
![image](https://user-images.githubusercontent.com/45708377/62464979-896b5180-b796-11e9-9b6a-492230cc3d97.png)

**Comment by WeaselDog** [comment]
This will be fixed in 9.4. Thanks for your report.
