### ISSUE TITLE
USER ISSUE: Muting/Dulling of colors

### ISSUE THREAD

**Issue by CobaltEcho** [StrangeLoopGames/EcoIssues#9240]
**Version:** 0.7.7.0 beta

**Steps to Reproduce:**
Seems to occur more when evening falls, or shadows.

**Expected behavior:**
Colors/world should remain constant.

**Actual behavior:**
Colors/world become extreemly muted/dull.  Immediate disconnect/reconnect seems to reset all the colors/shadows.

![screenshot-shadingweird](https://user-images.githubusercontent.com/26211498/45227723-283db400-b28f-11e8-89f3-9466eff99556.png)

**Comment by Nicolausi113** [comment]
It seems it has to do with Global Illumination set, as work around reset it, but a bug anyway.

**Comment by SeanAtr0n** [comment]
it looks like you had realtime reflections on then turned it off and took the before screenshot?

**Comment by CobaltEcho** [comment]
No, I didn't change any settings.

**Comment by CobaltEcho** [comment]
I think I may have been able to replicate what's going on.  When evening falls and the shadows start appearing, press the "ESC" key. Then return to game.  Shadows seem to appear/change then go away when reconnecting.  I tried this on various shadow quality settings and it seems consistant.

I created a video:
YouTube:  https://www.youtube.com/watch?v=ah_4pwcovH4

**Comment by D3nnis3n** [comment]
Can confirm this issue happening with Global Illumination on.

**Comment by EvinidEden** [comment]
I've run into something similar when toggling the vibrance on and off a few times. It will slowly get duller and duller with each toggle.
Perhaps it has something to do with reapplying the vibrance.
Just like with the other comments, a reconnect to the server fixes the issue.

**Comment by SeanAtr0n** [comment]
seems to be fixed
