### ISSUE TITLE
Real Estate Desk Notice when buying is wrong

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9242]
A player tried to buy plots from me - we first tried where the real estate desk was not in a valid room (as this did work on 7.6.3 somehow). Did not work. Put it into my house and he bought it then there, it worked. But the chat noticed shows he has bought it from himself.

**Comment by MarjieAVolk** [comment]
well this is embarrassing

**Comment by D3nnis3n** [comment]
I did get my money though, so probably only a error in the chat message?

**Comment by MarjieAVolk** [comment]
Yeah just the message.  Order of operations problem.  I changed the deed owner before sending the message. :P

**Comment by MarjieAVolk** [comment]
Fixed in 8.0
