### ISSUE TITLE
Can't place blocks

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9244]
A player reported he has a around 3x3 area where he can't place blocks, see the screenshot:

<img width="1430" alt="cantplace" src="https://user-images.githubusercontent.com/25908592/45231227-a1f39300-b2cb-11e8-95d9-a2e1f7566ac5.png">

**Comment by D3nnis3n** [comment]
That happend on around 10 more places in the meanwhile.

**Comment by beastyn** [comment]
Can't reproduce in 0.1.8.3
Close for now, if meet again please reopen
