### ISSUE TITLE
USER ISSUE: Game Start No Title

### ISSUE THREAD

**Issue by nothughesy** [StrangeLoopGames/EcoIssues#9246]
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**
1. Start game
2. load game
3. Wait

**Expected behavior:**
It should have popped up with the title and the menu options.	

**Actual behavior:**
Instead it showed the eye opening and the background, but nothing appeared. Pressing Esc brings to options window. Can leave using the quit button. Happened after downloading latest update 0.7.7.1 Beta

**Comment by johnkslg** [comment]
@nothughesy still getting this?  Have you been totally blocked from playing? 
@BlazeGuy2 ever seen this?

**Comment by BlazeGuy2** [comment]
Haven't had this issue occur for me at all.

**Comment by johnkslg** [comment]
@nothughesy can you message me on discord.gg/eco

**Comment by johnkslg** [comment]
Dropping in priority till we get a repro

**Comment by nothughesy** [comment]
Apologies @johnkslg college has kept me busy. I seem to have gotten it working by just reinstalling it a second time. Must have been on my end. Thanks for your hard work
