### ISSUE TITLE
Server crashes due to corrupted objects

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9247]
See the screenshot

<img width="1037" alt="crash" src="https://user-images.githubusercontent.com/25908592/45243074-c6169a80-b2f2-11e8-996d-9bb670ba06e1.png">

**Comment by D3nnis3n** [comment]
(Well, server restart caused this, it doesn't work with 7.7. either.)

**Comment by D3nnis3n** [comment]
Thank god, could be fixed by "RemoveObjectsOnException" Setting
<img width="676" alt="remove" src="https://user-images.githubusercontent.com/25908592/45243377-e5fa8e00-b2f3-11e8-87cd-fe0d1415825f.png">

There is the map: https://www.godsofwar.de/game2.zip

**Comment by beastyn** [comment]
Didn't meet in 8.1
Please reopen if meer again
