### ISSUE TITLE
A5.1 Client QoL issue: Dirt and propably other items are invisible

### ISSUE THREAD

**Issue by mortnir** [StrangeLoopGames/EcoIssues#925]
Im using the new macbook pro (Macos Sierra) with the following specifications:
Graphics Chipset - AMD Radeon Pro 460 4GB GDDR5
CPU Type - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz

Dirt and propably other items are invisible and I can see right through them although I can interact with them as normal. This is the same at the loading/intro/server list screen.

I'm guessing it has something with the GPU and the mac version since it looks fine in the windows version on the same laptop.

_Attaching two screenshots (sorry for the quality)._

![15725512_10154704225277349_287559606_o](https://cloud.githubusercontent.com/assets/17793677/21536225/25b3ab0e-cd80-11e6-971b-cfae4a3c3272.jpg)
![15776438_10154704225217349_1804146550_o](https://cloud.githubusercontent.com/assets/17793677/21536226/25b436be-cd80-11e6-9bb6-4eca8ea24371.jpg)

**Comment by MarjieAVolk** [comment]
Fixed as of 5.5
