### ISSUE TITLE
USER ISSUE: can't pick up anything

### ISSUE THREAD

**Issue by abarr054** [StrangeLoopGames/EcoIssues#9250]
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**

**Expected behavior:**
pick up corn 

**Actual behavior:**
nothing

**Comment by BlazeGuy2** [comment]
@abarr054 Need a video showing this behavior.  Hard to address issue without more information.

**Comment by D3nnis3n** [comment]
No answer to Information request in 14 days, reopen if issue persists.
