### ISSUE TITLE
Decimals Point Separator

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#9251]
Version: 7.7.1

I am Danish, we use `,` as a decimals point separator.
I am unable to type `,` into the store's price input fields. Trying to type `0.15` turns into into `15` when changing focus from the input field.

Current workaround is to hold down `CTRL` while pressing the "+" button, this will increase the amount by `0.1`.

Decimal numbers appear with `,` when seen in-game. For example decimal numbers are displayed as `1,75` when I look in a store.

This is a bug that has been fixed at least once before.
See: #8138, #8081, #8035, #8007

**Comment by crazypete79** [comment]
The workaround didn't work for me, so I can't use decimals at all

**Comment by Deantwo** [comment]
@crazypete79, hold down `CTRL` and press this button:
![image](https://user-images.githubusercontent.com/2676134/45261997-81cbed00-b40d-11e8-8043-4b1df38a7664.png)

**Comment by CobaltEcho** [comment]
Can confirm.  A co-player using French is unable to set the decimal place using "." or ",".

On the same store using my english version game, I can set the price to anything.

**Comment by D3nnis3n** [comment]
Dupe ;P
https://github.com/StrangeLoopGames/EcoIssues/issues/9210

**Comment by elfl0rd** [comment]
@D3nnis3n fixed in https://github.com/StrangeLoopGames/Eco/pull/3595

**Comment by D3nnis3n** [comment]
Indeed.
