### ISSUE TITLE
Issue with getting out to the Web Interface

### ISSUE THREAD

**Issue by TheeJudge** [StrangeLoopGames/EcoIssues#9252]
Some players on my server have an issue with getting to the web GUI. When they use any method of opening the web GUI, for instance using the G key. When they click yes to go to the Web Interface they get the following error.

https://i.gyazo.com/f5356e3195c24c2222bf71128d5147ca.png

The players that it does affect it affects them every time. Those that it does not have never had an issue of this happening.

**Comment by SeanAtr0n** [comment]
Could you have them post a log file here after seeing that issue?
`%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

Also, which web browser do they have set as default, which operating system?

**Comment by zeonzaku002** [comment]
So im getting this now.
https://i.gyazo.com/e35b078648d392e8165f75e0a987c633.png

**Comment by SeanAtr0n** [comment]
I'm not seeing any relevant info in the log file... don't suppose your disk was nearly full or you were running the game as an admin?

**Comment by elfl0rd** [comment]
i can confirm it, but this error REALLY rare for me.
as i see - game create file with different name vs try to open.
