### ISSUE TITLE
USER ISSUE: Trees disappear while harvesting

### ISSUE THREAD

**Issue by johntanguysonos** [StrangeLoopGames/EcoIssues#9254]
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**
Harvest tree
Observe that during harvest occasionally tree disappears
NOTE: disconnecting then reconnecting to server causes felled tree to reappear

**Expected behavior:**
Trees should not disappear during harvest

**Actual behavior:**
Trees occasionally disappear during harvest

**Comment by BlazeGuy2** [comment]
Dup of #8823
