### ISSUE TITLE
Leader can crash the server

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9255]
With the current system of preventing too long "out of game" messages the leader is able to crash the server, when he set's a too long objective as if he does that the server will crash with this notice:

> --BEGIN DUMP--
> Dump Time
> 09/08/2018 03:49:37
> 
> Exception
> Exception: NetException
> Message:Unconnected messages too long! Must be shorter than NetConfiguration.MaximumTransmissionUnit (currently 1408)
> Source:Lidgren.Network
> 
> Lidgren.Network.NetException: Unconnected messages too long! Must be shorter than NetConfiguration.MaximumTransmissionUnit (currently 1408)
>    at Lidgren.Network.NetPeer.SendUnconnectedMessage(NetOutgoingMessage msg, IPEndPoint recipient)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.TimerQueueTimer.CallCallback()
>    at System.Threading.TimerQueueTimer.Fire()
>    at System.Threading.TimerQueue.FireNextTimers()
> 
> --END DUMP--
> 

That probably is not a good solution.

**Comment by johnkslg** [comment]
Try to repro by opening the objective viewer from the action bar, then put a ton of text in that box.  

To figure out what the objective viewer is, look at the tooltips on the icons in the HUD

**Comment by sidjuego** [comment]
Apparently, the server did not crash when I had entered a large text that is more than 50k characters but game gets hanged when tried to enter the text that is more 100k characters. I think it can be solved by setting the maximum limit for objective text input. What are your thoughts? @johnkslg

**Comment by D3nnis3n** [comment]
No, as that will not solve the problem, that is based on what you entered as server name and as server description, as that counts towards that limit.

Use this Network.eco config for testing:

```
{
  "PublicServer": true,
  "Playtime": "110000111122222222222211110000111122222222222211110000111122222222222211110000111122222222222211110000111122222222222222222222222222222222222222222222222222222222222211",
  "DiscordAddress": "HhCrDrA",
  "Password": "",
  "Description": "<#0000FF>[EU]</color> <#FF0000>Gods of War</color> <#00FF00>(Capital | Global Currency | Newbie Friendly)</color> <#FFFF00>[Cycle #3]</color>",
  "DetailedDescription": "<b>Be creative and cooperatively establish an emerging society, create a working economy, keep up a healthy ecology and destroy the meteor within 30 days. A cycle lasts until about 60 days after the meteor has been destroyed or until a patch with major changes has been released. The rules and more information about our game server can be found on our discord server.</b>",
  "ServerCategory": "Established",
  "IPAddress": "Any",
  "GameServerPort": 3000,
  "WebServerPort": 3001,
  "Rate": 10,
  "MaxConnections": -1
}
```

Now /leader yourself on the server and type a long objective in, then the server should crash like it did with me.

**Comment by D3nnis3n** [comment]
That means, when the server admin happens to have exactly the limit minus one sign used for the name and the description it is enough for the leader to type two signs to crash the server - a limit on objective length would not really help. Probably a limit for all of these values or a fix that allows the server to not crash, but ignore the text or just handle it someway other so there is no longer a limit at all.

**Comment by sidjuego** [comment]
Using above network config file when i tried to set the long objective it crashed once with ('message too long exception') But when i try to debug, server info json is already capped with the message limit before sending hence it does not crash

**Comment by D3nnis3n** [comment]
Well, no developer, don't know why that is. I justed wanted to show you my setup that leads to reproducable crashes.

**Comment by WeaselDog** [comment]
Fixed. There is now a cap on the length on the length of the objective you can enter.
