### ISSUE TITLE
Crashing on server creation

### ISSUE THREAD

**Issue by Herrumblo** [StrangeLoopGames/EcoIssues#9258]
Game version 7.7.0. When I try to create a new server, I put the name, without selecting any option, I click on create and the game crashes to desktop. I tried to make a clean installation and nothing. It has not left a record of the failure on crash log.

**Comment by BlazeGuy2** [comment]
@Herrumblo Is this occurring on 7.7.1 as well (first hotfix is out)?  Can you post a video showing what is happening?

**Comment by Herrumblo** [comment]
Fixed, it was the anti-spyware.
