### ISSUE TITLE
USER ISSUE: Got stuck in terrain (underground)

### ISSUE THREAD

**Issue by TheLogan** [StrangeLoopGames/EcoIssues#9260]
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**
Create a hole large enough for a stockpile underground.
When full the stockpile should either touch the ceiling, or be 1 block from the roof.
Stand on the stockpile while adding objects
The stockpile will push you up into the dirt above and you will be stuck with no way to get free.

**Expected behavior:**
Should do a collision check and maybe push you to the side or similar

**Actual behavior:**
Pushes you up so you get stuck in the ceiling

**Comment by MrX13415** [comment]
Have you tried to use the command "/unstuck" in the chat?
I should get you free.

**Comment by SeanAtr0n** [comment]
duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/5836
