### ISSUE TITLE
Bloomery invisible

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9263]
Bloomery  get's invisible on smelting, can be fixed by SEVERAL restarts but will happen again fast.

<img width="1319" alt="blastfurance" src="https://user-images.githubusercontent.com/25908592/45254205-b770c780-b374-11e8-93a0-5d99e3790059.png">

**Comment by keegan-o** [comment]
Can't repro on release branch in SVN...

![image](https://user-images.githubusercontent.com/14983165/45376079-c097a980-b5ab-11e8-82db-56e6a94e79b8.png)

**Comment by D3nnis3n** [comment]
Do only seem to get this issue on ground level, somehow. My bloomeries in the house are not affected oO

**Comment by BlazeGuy2** [comment]
![screenshot_bloomery](https://user-images.githubusercontent.com/35509188/45380379-67ce0e00-b5b7-11e8-95e9-3ca80863d203.PNG)

**Comment by D3nnis3n** [comment]
I just had it before i left on my bloomery in the second area, too. I really don't know why it happens, but it does. It also only does happen with the bloomery. No other table ever has this. Could't you check what is different from the bloomery to other things or something like that, as this issue is not only with me, even though it might also not be with many people.

**Comment by tmzasz** [comment]
It seems to happen with my bloomery when its on the ground and the server restarts

**Comment by D3nnis3n** [comment]
It seems to happen - as of the new issues - when you go quite a bit away from the bloomeries and come back. But the issues accumulated the last few days, probably is a worth a deeper look.

**Comment by elfl0rd** [comment]
(another - https://github.com/StrangeLoopGames/EcoIssues/issues/9263)
I can confirm, its regularly happens on release branch. 
Other users report this issue too.

![20181017230808_1](https://user-images.githubusercontent.com/4980243/47114379-55a15880-d264-11e8-87b7-c3cbffc3ca62.jpg)

**Comment by D3nnis3n** [comment]
Yet another one! :D

**Comment by elfl0rd** [comment]
![20181122033551_1](https://user-images.githubusercontent.com/4980243/48875084-d75a4800-ee07-11e8-8c6a-1ae8fd4455f4.jpg)

**Comment by elfl0rd** [comment]
This is still happens with different players and on different servers. Please bump priority.

**Comment by elfl0rd** [comment]
Still happens...
https://steamcommunity.com/sharedfiles/filedetails/?id=1613415864
![1](https://user-images.githubusercontent.com/4980243/50724260-9b4f1e00-10fb-11e9-91aa-4fd4fdebce03.jpg)

**Comment by D3nnis3n** [comment]
This is a long-time issue, on my list!

**Comment by elfl0rd** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1628324778
![1](https://user-images.githubusercontent.com/4980243/51425089-71f8bc80-1be8-11e9-9a13-0e7f185b00fd.jpg)

**Comment by D3nnis3n** [comment]
I wonder if anyone saw that since 8.0? I didnt.

**Comment by D3nnis3n** [comment]
Closing this for now, as i didn't occur that issue anymore. Please open a new one if anyone sees that issue again.
