### ISSUE TITLE
Marker name issue (like with leader objective before)

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9265]
If a marker name get's too long in the field only the first words are shown while the others are invisible but there. Hard to fix typos as you can't see the full name in the field.

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/9060

**Comment by SlayksWood** [comment]
8.2.0 staging-17-n: Still an issue.

**Comment by SlayksWood** [comment]
I can entry a lot of characters in marker name, but only 35 will be shown in the name. Can you limit entering number by 35 char too?
