### ISSUE TITLE
USER ISSUE: Can't connect to any server

### ISSUE THREAD

**Issue by abarr054** [StrangeLoopGames/EcoIssues#9267]
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**

**Expected behavior:**
Log into a sever

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Connection timed out
```

**Comment by BlazeGuy2** [comment]
Which server is this occurring on?  Is this happening on SP?

**Comment by D3nnis3n** [comment]
No answer to Information request in 14 days, reopen if issue persists.
