### ISSUE TITLE
USER ISSUE: Large Lumber Door

### ISSUE THREAD

**Issue by macgofferboy** [StrangeLoopGames/EcoIssues#9269]
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**
Right Click Large Lumber Door

**Expected behavior:**
Opened

**Actual behavior:**
Toggles between on and off and does not open

**Comment by elfl0rd** [comment]
looks same as https://github.com/StrangeLoopGames/EcoIssues/issues/9211

**Comment by macgofferboy** [comment]
yes it is the same issue didnt see the other posr, Thanks.
