### ISSUE TITLE
possible issue with inventory Stacks

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#927]
public virtual IEnumerable<ItemCollection> Stacks => this.Inventories.SelectMany(inventory => inventory.Stacks);

this doesn't have any checks to make sure you are in a thread safe lock.  Should it..?

**Comment by noblackthunder** [comment]
could this cause a crash like this? http://ecoforum.strangeloopgames.com/topic/1303/crash-to-desktop-for-moving-dirt

**Comment by metachronism** [comment]
inventories have been lock-free for a while now (using ThreadSafeLists), closing as fixed!
