### ISSUE TITLE
"if leader" clause

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9270]
I'd like to propose an "if leader" (or in 7.8 a "if XYZ OFFICE") clause, so that things like leader payment once a day is possible. With road building being a governmental job on our server and the future Secretary of Urban Development only doing this, he won't have much income otherwise.

**Comment by Deantwo** [comment]
To be more exact, the periodic action law trigger doesn't have the "world leader" condition, among others.

**Comment by MarjieAVolk** [comment]
Yes, I agree :) I hope to include this along with our new titles and ownership features that are coming in a future update.  The plan would be to support conditions for any title.
