### ISSUE TITLE
Placing a Small Wood Cart, Wood Cart, Steam Truck and Excavator, logging out and then back in, moved Vehicles will leave a Hole where nothing can be placed due to being Blocked

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9271]
**Version:** 0.7.7.1 beta

i was going to do this earlier but logging Off and logging back in Solved the Issue i was having
![snap2684](https://user-images.githubusercontent.com/29383891/45256336-f579e580-b38c-11e8-9725-19615466bbfd.png)
![snap2685](https://user-images.githubusercontent.com/29383891/45256337-f579e580-b38c-11e8-98f2-a472a8d211d0.png)

BUT i had moved my cart lower down the Ramp (so i could try and fill this hole in and do a github)  and Now it created Another nonFillable Place where that cart was left
![snap2686](https://user-images.githubusercontent.com/29383891/45256354-2bb76500-b38d-11e8-8ef8-f9d928613b97.png)

its as if Eco has noted that something is there like the cart, and when you move it while playing and try to fill this space it still thinks the cart is there blocking it

**Comment by Conchipedia** [comment]
just noticed that this happens not just on a Dirt Ramp in the snapshot above i had parked Cart and removed my Large Lumber Door, now when replacing it i cannot as its is Blocked, even if i have moved the cart, BUT if i quit the game and try again the Dorr will go in perfectly this looks like this is something that is happening with Small Carts

**Comment by Conchipedia** [comment]
same happens for a Steam Truck
![snap2696](https://user-images.githubusercontent.com/29383891/45256934-8359ce80-b395-11e8-8b64-fdc6d935a43e.png)
Logged out with Steam Truck in this position
Logged back in and Moved Steam Truck and then tried placing Blocks where the Steam Truck was
![snap2697](https://user-images.githubusercontent.com/29383891/45256938-adab8c00-b395-11e8-8134-1405e8fd7159.png)
The Central most Part of  where the Vehicle was Prior to logging out and then moving is an unfillable space

**Comment by Conchipedia** [comment]
Did a small Test to try and get this to duplicate:

Created Parking Spaces from Left to Right "Steam Truck", "Small Wood Cart" and Wood Cart"
Logged out.
![snap2699](https://user-images.githubusercontent.com/29383891/45257032-1e06dd00-b397-11e8-8dd2-ed0a17231ae5.png)

logged back in and then moved all 3 carts  and placed Mortared Stone Blocks where the Vehicles were
as you can see from following scnapshot, the spaces are where i CANNOT place a block as it says Blocked
![snap2700](https://user-images.githubusercontent.com/29383891/45257058-750cb200-b397-11e8-898a-e68cec81d465.png)

**Comment by Conchipedia** [comment]
finally a test with an Excavator
![snap2701](https://user-images.githubusercontent.com/29383891/45257085-3c210d00-b398-11e8-80fd-4fc0451a4c20.png)
placed it , logged out, logged in and moved it placed blocks down where this was located, still leaves a space where i cannot put a block as its blocked
![snap2702](https://user-images.githubusercontent.com/29383891/45257104-84402f80-b398-11e8-96c9-1731129a0e63.png)

**Comment by Conchipedia** [comment]
Please Note this is tested on my singleplayer world, i think this will be the same for a normal world(but i'm not Admin in any)  So i will upload my World Save
[World used to test on.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2363572/World.used.to.test.on.zip)

**Comment by SeanAtr0n** [comment]
should be fixed in 7.7.2
