### ISSUE TITLE
USER ISSUE: Main screen is active while the Title fills in which has led to missclicks and loding something i didnt intend

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9272]
**Version:** 0.7.7.1 beta
![snap2689](https://user-images.githubusercontent.com/29383891/45256422-3de5d300-b38e-11e8-8918-ddd133847e82.png)
![snap2690](https://user-images.githubusercontent.com/29383891/45256423-3de5d300-b38e-11e8-90ae-3ee013ab1dd4.png)
![snap2691](https://user-images.githubusercontent.com/29383891/45256424-3de5d300-b38e-11e8-8a90-a62a8a105355.png)
![snap2692](https://user-images.githubusercontent.com/29383891/45256426-3de5d300-b38e-11e8-9a38-9190725d4064.png)

if some people are like me and hate Intros and title screens maybe have the window NOT be active until it has finished loading or Get a Mouse Movement detection and jump straight to it when mouse moves?

reason for this is because testing hosted worlds and i have to enter the IP address and NOT click on continue as that is still NOT loading my world but still random ones i have accidentally in my rush to try world out it has continued when i didn't want it to my Clicking on it invisibly

**Comment by johnkslg** [comment]
The title menu shouldnt be clickable till its started to fade in

**Comment by sidjuego** [comment]
@johnkslg Should I disable the mouse clicks until that black pinhole animation gets over?

**Comment by johnkslg** [comment]
Mouse clicks should still jump to the menu.  Just make the menu not selectable (it shouldnt change the cursor) till it starts to fade in.
