### ISSUE TITLE
Contract - Custom Clause - Auto-Accept

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9273]
I personally consider that a bug, but probably is only a suggestion - but i don't know how devs handle that here.

Everytime i create a contract with custom clause it tells me to remove auto accept - as soon as i choose custom clause the box should uncheck itself, though, as that is pretty unintuitive design in my opinion.

**Comment by johnkslg** [comment]
If it auto removes it wouldnt be clear to players that it works differently, I like it to be a conscious decision.  Similary if you remove the custom clause, it shouldnt necessarily add back

**Comment by D3nnis3n** [comment]
While i do agree to the latter, i do not to the first, but that probably is only because i now know that "rule" and when creating 25 contracts with custom clauses it just enerves me *g* So you are most probably right. Maybe a "dismiss" notice for when you finally understood it?
