### ISSUE TITLE
Cannot place coal into Stone Brazier with Right Click all right click will do is turn it on or off even if there is no Fuel Supply

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9274]
**Version:** 0.7.7.1 beta

![snap2703](https://user-images.githubusercontent.com/29383891/45257436-35959400-b39e-11e8-88f4-71b37184c8ed.png)
![snap2704](https://user-images.githubusercontent.com/29383891/45257437-35959400-b39e-11e8-95e0-691fcf297efd.png)

but you can right click on Brazier and it will fill with coal

**Comment by Nicolausi113** [comment]
see #8665

**Comment by Conchipedia** [comment]
This worked in 7.6.3 with no problem this is why i added it for 7.7.1 and in my Server i had loads of Stone braziers which i fill with right click using Coal

**Comment by elfl0rd** [comment]
no, bug still here, if it work for you - you lucky.

**Comment by D3nnis3n** [comment]
Duplicate
