### ISSUE TITLE
Torch gives out more light than 4 Stone Braziers

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9275]
**Version:** 0.7.7.1 beta

![snap2705](https://user-images.githubusercontent.com/29383891/45257475-df752080-b39e-11e8-8c21-97a32c3a9c27.png)
![snap2706](https://user-images.githubusercontent.com/29383891/45257476-e00db700-b39e-11e8-9d81-4deab1367915.png)

this might be to do with Shadows

**Comment by keegan-o** [comment]
braziers should give out more light now
