### ISSUE TITLE
USER ISSUE: tooltip stops stockpile movement

### ISSUE THREAD

**Issue by ResplendentOwl** [StrangeLoopGames/EcoIssues#9276]
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**
open a stockpile. Drag items from a lower linked stockpile up to the stockpike you have open.

**Expected behavior:**
let me move things efficiently between linked stockpiles

**Actual behavior:**
the stupid tooltip stays visually in my way, but more importantly stops me from using the squares behind it, preventing me from dragging upward

**Comment by Conchipedia** [comment]
linking with #9253

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9132
