### ISSUE TITLE
Something changed from 7.6.3 to 7.7.1 with Lighting and shadows underground 

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9277]
**Version:** 0.7.7.1 beta

Before i could work underground and see what i am doing with Shadows at max, now anything that is above
shadow quality set at Fastest is too dark 

![snap2718](https://user-images.githubusercontent.com/29383891/45257789-bf942b80-b3a3-11e8-8d47-f240e0328e64.png)
![snap2719](https://user-images.githubusercontent.com/29383891/45257790-bf942b80-b3a3-11e8-96d9-8f47500b6a00.png)
![snap2720](https://user-images.githubusercontent.com/29383891/45257791-bf942b80-b3a3-11e8-9076-111a4521af15.png)
![snap2721](https://user-images.githubusercontent.com/29383891/45257792-bf942b80-b3a3-11e8-8a20-67991af79314.png)

We had this problem before a long time ago when some stuff was changed

**Comment by Conchipedia** [comment]
linking #9278 to this as it has my Video showing the problems i am having with the New changes to Lighting (shadows) if i set brightness up for below ground the Above ground will be too bright

**Comment by Conchipedia** [comment]
Secondary note, if its Nighttime i can have Shadows to max and i can see above and below ground with absolutely no problem, it ONLY goes pitch black during the day

**Comment by Nicolausi113** [comment]
I have this settings and NO problem. I’ve noticed similar effects with Global Illumination on!

![settings2](https://user-images.githubusercontent.com/38510829/45259249-4c50e080-b3c8-11e8-9825-96c74066a233.jpg)

**Comment by D3nnis3n** [comment]
We also see that issue ABOVE ground. Something has gone very weird with shadows in 0.7.7.1.

**Comment by Nicolausi113** [comment]
Global Illumination ON
![globilluon](https://user-images.githubusercontent.com/38510829/45265419-c9249e80-b44a-11e8-9ea3-17d28cd18ad5.jpg)

Global Illumination OF – same session and nothing else changed!
![globilluoff](https://user-images.githubusercontent.com/38510829/45265427-d6418d80-b44a-11e8-884f-42e9b278f8c8.jpg)

**Comment by SeanAtr0n** [comment]
try turning on realtime reflections

**Comment by Conchipedia** [comment]
before 7.7.0 and 7.7.1 everything was great graphically i had nearly everything max, now i cant be bothered to change graphic settings because something was changed

**Comment by Nicolausi113** [comment]
@Conchipedia : Yes, I have this noticed with first staging 7.7 and reported here
https://github.com/StrangeLoopGames/EcoSuggestions/issues/494
Maybe this is the price for performance improvement.
I’ve tried Realtime Reflection + Global Illumination, for me looks strange and I leave it of and be happy :)

**Comment by Conchipedia** [comment]
we had this issue way back when they changed loads of graphic settings, it got to a point where the game was almost unplayable (even resetting all to default) hoping we are not going back down that path

**Comment by CobaltEcho** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/9240

**Comment by beastyn** [comment]
Check with and withour globall illumination, everything seems to be ok in 0.8.1
Please reopen if meet this again
