### ISSUE TITLE
Standing torch light goes off the closer you get to it but you can see it from a long way off

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9278]
**Version:** 0.7.7.1 beta

![insta](https://user-images.githubusercontent.com/29383891/45257911-ab512e00-b3a5-11e8-892c-610779184fac.gif)

Full Video showing the Distance of Torch and light going off when you get closer and how dark it becomes when you go below Ground and how bright it is when you come back out
[Eco 08_09_2018 19_52_32.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2363655/Eco.08_09_2018.19_52_32.zip)

**Comment by metachronism** [comment]
no repro
