### ISSUE TITLE
USER ISSUE: Tailing Pollution Containment

### ISSUE THREAD

**Issue by johntanguysonos** [StrangeLoopGames/EcoIssues#9279]
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**
Put tailings somewhere

**Expected behavior:**
Ability to contain ground pollution

**Actual behavior:**
Unable to contain pollution despite several different methods attempted.  'Solid block eleventh level above Tailings' does not contain, regardless if stockpiles exist above, empty space, walls against stockpiles of tailings, or separating, etc. Eco Forum does not offer any other advice.

**Comment by trevelmike** [comment]
same here. I really wish they would get around to fixing this issue. Been told it is some kind of experiment. But unless the experiment is to totally pollute the world this needs to be tamped down. I have mine stored 10+  still isn't stopping i'm either going to dig a deeper hole or not play until this is addressed properly.

**Comment by Conchipedia** [comment]
or you can do what i have done and Build with Tailings (be warned they do not count as a wall so inner walls have to be used) it was just an idea i had to actually Pollute one area over the sea with both Ground and Air pollution.
![snap2732](https://user-images.githubusercontent.com/29383891/45313997-728d9200-b528-11e8-88cb-525bf2e46888.png)
![snap2735](https://user-images.githubusercontent.com/29383891/45314071-acf72f00-b528-11e8-889a-779cb4ed6c95.png)
![snap2736](https://user-images.githubusercontent.com/29383891/45314114-cd26ee00-b528-11e8-89ed-914ce2753bc6.png)
The Pipe System is from all over the place and anyone can join in so they all pollute here (and the Volcano will smoke)
![snap2739](https://user-images.githubusercontent.com/29383891/45314481-c351ba80-b529-11e8-863c-1f2bb6bcebbe.png)

The Pipe System are also used as Crash Barriers for the Bridge roads across the Sea
![snap2737](https://user-images.githubusercontent.com/29383891/45314325-52aa9e00-b529-11e8-8369-4f6e37bd255a.png)
![snap2738](https://user-images.githubusercontent.com/29383891/45314326-52aa9e00-b529-11e8-8dfa-13b0ad7630df.png)
and finally a minimap View of Volcano and then Showing Ground Pollution (all nicely safe away from anyone with farms)
![snap2733](https://user-images.githubusercontent.com/29383891/45314413-8c7ba480-b529-11e8-8f80-7a0a9b157b2d.png)
![snap2734](https://user-images.githubusercontent.com/29383891/45314414-8c7ba480-b529-11e8-9c63-927dd51efeb8.png)
m

**Comment by beastyn** [comment]
0.8.1.0 
Underground conrainment is working
