### ISSUE TITLE
I don't even know what happened

### ISSUE THREAD

**Issue by JoBanJo** [StrangeLoopGames/EcoIssues#9284]
was building on top of my house and i looked over and saw another building loading in? even tho there inst anything there.... idk how to explain it. just look at the attached images

![20180909200203_1](https://user-images.githubusercontent.com/43109465/45263417-7e1b8300-b46c-11e8-8b35-574ce9ce9982.jpg)
![20180909200209_1](https://user-images.githubusercontent.com/43109465/45263418-7e1b8300-b46c-11e8-87d3-660608d4d252.jpg)
![20180909200212_1](https://user-images.githubusercontent.com/43109465/45263419-7e1b8300-b46c-11e8-8b9f-0ad7fbda791b.jpg)
![20180909200229_1](https://user-images.githubusercontent.com/43109465/45263420-7eb41980-b46c-11e8-9e73-495a22527469.jpg)
![20180909200232_1](https://user-images.githubusercontent.com/43109465/45263421-7eb41980-b46c-11e8-9427-42ff5a697a9f.jpg)
![20180909200233_1](https://user-images.githubusercontent.com/43109465/45263422-7eb41980-b46c-11e8-9db0-5763418a02b3.jpg)

**Comment by TheeJudge** [comment]
I have seen something like this on a few occasions, where a chunk will copy and paste itself from one location to another. It's like a phantom version of something built somewhere else, possibly close by. Does that mimic a portion of your house possibly? Is it touchable or can you just walk through it?

**Comment by JoBanJo** [comment]
Hey,

So it did exactly as you said,

("where a chunk will copy and paste itself from one location to another. It's like a phantom version of something built somewhere else, possibly close by.")


I could also walk through it.


Thanks
Joel.
________________________________

**Comment by BlazeGuy2** [comment]
@JoBanJo can you zip up and send me your save so that I can try to reproduce this?  Also, can you send me the coordinates on the map where this issue is occurring?

**Comment by JoBanJo** [comment]
Hi, I restarted the game and the glitch stopped happening I also ran a thing on steam called validate integrity of files and had two bad files... I will try and send my save tonight.

Thanks.
________________________________

**Comment by D3nnis3n** [comment]
Does this still occur / have you sent your save in?

**Comment by JoBanJo** [comment]
hi, sorry i completely forgot about this. no it does not still happen and i forgot to send the save.

**Comment by D3nnis3n** [comment]
Duplicate
