### ISSUE TITLE
New reputation colors are ... bad

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9288]
I'm considering that a bug as the new colors do not tell anything about what it means.

With 30 points i got some kind of mayonnaise yellow, which other players funnily call "urine yellow" and really noone gets what that color means.

Green / Red (maybe in different shades per level of reputation) is much more intuitive and understandable. Together with the reputation title being "N/A" for everyone still this makes the reputation feature a bit less valueable then before, as it's not easy to understand, while i'm trying to make people use that feature as it's generally pretty unused.

Also, i still propose that positive reputation should be limited to the same summary amount as negative to prevent trolling. (At the Moment 30 / -10)

Also: Despite my name now being urine yellow it's white in crafting messages and the player list - that just seems very wrong to me.

**Comment by elfl0rd** [comment]
Ugly, yea!

**Comment by D3nnis3n** [comment]
<img width="351" alt="name" src="https://user-images.githubusercontent.com/25908592/45388299-d4c5c000-b618-11e8-9cac-4c88ee33e395.png">
No, this does not seem right.

**Comment by D3nnis3n** [comment]
It seems like the color for bad reputation is still red (we now got the first red guy) - why has the green color be changed and why is only the green color bugged to white? The red works fine.

Something really is wrong here!

**Comment by D3nnis3n** [comment]
Now configurable.
