### ISSUE TITLE
Remote Control bug

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9289]
I got a very funny bug, it allows remote control

I can see a cart which is NOT there. It's 300 metres away in a mine. When i press "e" on it i can also see the linked stockpiles to the cart - which are where the cart is. In the mine 300 metres away. So i can remote control the stockpiles and cart that is 300 metres away - at least until restart. Very funny.

See screenshot 1 and look at the markers to see the distances to capital: There is my remote control cart.
See screenshot 2 and look at the markers to see the distances to capital: There is the REAL cart and the REAL stockpile.

:D

See the screenshot:
<img width="1920" alt="remote control1" src="https://user-images.githubusercontent.com/25908592/45265916-202e7180-b453-11e8-994c-5889bf1d9703.png">
<img width="1916" alt="remote control 2" src="https://user-images.githubusercontent.com/25908592/45265945-8a471680-b453-11e8-9aba-f23d7175f534.png">

**Comment by D3nnis3n** [comment]
Probably some kind of desync issue?

**Comment by D3nnis3n** [comment]
We now also had that problem several times with steam trucks that were not there two times. They show the stockpiles from the place where they have been before instead of the stockpiles available where they are now. So i can remote control, but not easily put in items in the stockpiles where i am now :(

**Comment by D3nnis3n** [comment]
Another info:
Does only happen when you go to the trucks inventory, the stockpiles show the truck only where it is.

**Comment by D3nnis3n** [comment]
This issue is still happening frequently in the last days as in the truck still seeing the storage where it has been before instead of the ones where he is now, which allows remote control - just without duplication of the car, like it was the case in the opening post of the issue.

**Comment by SeanAtr0n** [comment]
How do you get carts to appear where they are not?

**Comment by D3nnis3n** [comment]
This is a weird bug that is hard to reproduce. Every now and then i can see in a vehicle stockpiles that are too far away and remove control them and sometimes i can see carts that actually are not there. How this happens exactly - unfortunately no idea, nur it happens every now and then. The issue with remove control stockpiles happens way more often then a cart that is not there.

**Comment by SeanAtr0n** [comment]
think this was probably resolved w/ the fix to vehicle positions that didn't always update. please reopen if you can make it happen again (and send any relevant log files)
