### ISSUE TITLE
USER ISSUE: Dialog box gets in the way

### ISSUE THREAD

**Issue by OsageSparky** [StrangeLoopGames/EcoIssues#9290]
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**
Open stockpile, grab an item, the dialog box gets in the way and wont dissappear on mouse out.

**Expected behavior:**
Dialog box should dissappear when mouse is moved

**Actual behavior:**
Stays open regardless of mouse move, you must select another item away to force dialog to popup elsewhere

**Comment by Senlarus** [comment]
Confirmed, this is still an issue. The patch did make it a little better, but it is still very much happening and very much a problem.

**Comment by TheeJudge** [comment]
#9276

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9132
