### ISSUE TITLE
USER ISSUE: HUGE glitch World Space Cords: 0,#,# to 2000,#,# and Objects transversing.

### ISSUE THREAD

**Issue by OsageSparky** [StrangeLoopGames/EcoIssues#9294]
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**
Go to 1,#,#
when it Cords resets from 0,#,#  to 2000,#,# anything you are pulling glitches and falls through the world, you have to log out and back in and hope it resets for you

**Expected behavior:**
No glitching behavior

**Actual behavior:**
Game play breaking glitch

**Comment by OsageSparky** [comment]
When selecting the ground at these coords, it goes from 0,#,# to 1999,#,# but walking it goes from 0,#,# to 2000,#,# to 1999,#,# There is a a problem with how the character player moves in world space vs tool selecting world space coors which is creating the glitch

**Comment by SeanAtr0n** [comment]
haven't been able to reproduce this behavior so far

**Comment by D3nnis3n** [comment]
I can drive over that part of the world with a cart just fine. We even had our capital city there the last cycle, many people have driven there, with no problems :O

**Comment by OsageSparky** [comment]
We will test again, we have a ramp over the location

**Comment by OsageSparky** [comment]
If anyone wants to test it's on Beta server Elk, we have 2 mounts of dirt
on. each side of ramp at the location. After glitch cart and rocks that are
in the cart fall from the sky over and over until the person who glitched
logs out and back in. Sometimes cart will land in trees or sideways on
land. We notice the cords where player is standing is different than what
is selected by took on ground.

**Comment by CobaltEcho** [comment]
We had the same exact issue, there was a ramp over the 999-0 cord.  We replaced the ramp with flat road and it seemed to work.  Our ramp was in the East to West orientation.

**Comment by D3nnis3n** [comment]
Oh well, i did not try out with ramps. Only with normal roads.

**Comment by extant1** [comment]
Discovered that if you park your vehicle/cart before crossing and get out, then walk across the zone so the other side loads and you go back and drive across you have zero issues.  So it seems like it's caused by the spontaneous loading of the opposite side.

**Comment by elfl0rd** [comment]
Maybe refers to https://github.com/StrangeLoopGames/EcoIssues/issues/7051

**Comment by SeanAtr0n** [comment]
Pretty sure this one was fixed w/ 7.7 or 7.8

**Comment by elfl0rd** [comment]
nope, actual in 7.8.6

**Comment by SeanAtr0n** [comment]
vehicles fall through the world when crossing in 7.8.6 or are you talking about another issue?
