### ISSUE TITLE
USER ISSUE: Closing Create Contract Window Locks UI

### ISSUE THREAD

**Issue by pcouncil** [StrangeLoopGames/EcoIssues#9295]
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**
Place contract board.
Create New Contract.
Don't do anything with the contract.
Close the window using the X button.

**Expected behavior:**
Enabled mouse to interact with UI after window closes

**Actual behavior:**
Window closes, but mouse clicks and hover no longer works with UI. Game restart required.

**Comment by johnkslg** [comment]
Cannot repro this, tried for a long while. @pcouncil please contact me on Discord.gg/eco @johnk

**Comment by johnkslg** [comment]
It could be due to a contracts mod, do you have one installed?
