### ISSUE TITLE
Own Contracts is MUCH MUCH MUCH too small

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9296]
I got around 25 contracts handed out and can't find any in this little thing there.
<img width="1214" alt="toosmall" src="https://user-images.githubusercontent.com/25908592/45313152-4ffe7780-b52e-11e8-9e62-8fdfdb0a565e.png">

**Comment by johnkslg** [comment]
The bar is now resizeable in 8.0, fixed!

**Comment by D3nnis3n** [comment]
Thank you very much :)
