### ISSUE TITLE
Distribution items in server overwiew is doubled

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9297]
See the screen shot:
<img width="713" alt="doubled" src="https://user-images.githubusercontent.com/25908592/45313200-76bcae00-b52e-11e8-8b10-1e6390a1e27a.png">

**Comment by Conchipedia** [comment]
this was mentioned in #9154

**Comment by elfl0rd** [comment]
Dupe - https://github.com/StrangeLoopGames/EcoIssues/issues/9208
