### ISSUE TITLE
Tables Need Certain amount of Tier to Make them work and accrding to some data its counting whats in stockpiles and also if i place another block or remove it the Room detection is way off

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9298]
**Version:** 0.7.7.1 beta

Examples of this follow
![snap2740](https://user-images.githubusercontent.com/29383891/45314854-cdc08400-b52a-11e8-82ce-18b96cdc32cb.png)
this is what shown about room
![snap2741](https://user-images.githubusercontent.com/29383891/45314899-edf04300-b52a-11e8-8797-a135769e62a7.png)
and typing /testroom gives this
![snap2742](https://user-images.githubusercontent.com/29383891/45314975-14ae7980-b52b-11e8-9c2d-91e5fdb7f1db.png)

also room detection seems way off at times
![snap2745](https://user-images.githubusercontent.com/29383891/45315659-d87c1880-b52c-11e8-844b-899f0695c62d.png)
![snap2746](https://user-images.githubusercontent.com/29383891/45315660-d87c1880-b52c-11e8-95b5-839a05f456de.png)
i know i have Big rooms, but where its deciding to check when i add and replace a piece of glass in the wall is confusing
![snap2747](https://user-images.githubusercontent.com/29383891/45316129-0dd53600-b52e-11e8-8208-8b863e51bb78.png)
i Haven;t got Any Asphalt Road in this room, i have Asphalt Ramps in another part which is too big to be a room so why would they count for in here?

**Comment by Conchipedia** [comment]
Stockpiles themselves Lower Room Tier

**Comment by SlayksWood** [comment]
Checked on 8.1. Wasn't able to reproduce, seems fixed.
![image](https://user-images.githubusercontent.com/45708377/56501235-aeed8b80-6516-11e9-9110-b2b8d28b1217.png)
Iron pipes are no longer taken into calculation of room tier
