### ISSUE TITLE
Detecting Imaginary items in Room lowers Tier of Room

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9299]
**Version:** 0.7.7.1 beta

![snap2754](https://user-images.githubusercontent.com/29383891/45317114-dd42cb80-b530-11e8-95c4-693675571a81.png)
![snap2755](https://user-images.githubusercontent.com/29383891/45317147-fb103080-b530-11e8-9e0b-359eba4e73cd.png)

i have created a Massive Underwater Dome that was flooded (took me hours to get rid of ALL the water) now all the Room is Made of Mortared Stone, Originally it had dirt ramps, but becuase i though that those was counting towards lowering the tier i replaced them all with Stone Ramps
![snap2748](https://user-images.githubusercontent.com/29383891/45316984-8f2dc800-b530-11e8-861f-e37981cc409e.png)
![snap2749](https://user-images.githubusercontent.com/29383891/45316985-8f2dc800-b530-11e8-8ce9-8e9103314fba.png)
![snap2750](https://user-images.githubusercontent.com/29383891/45316987-8fc65e80-b530-11e8-9da8-bf8aabbbbcfb.png)
![snap2751](https://user-images.githubusercontent.com/29383891/45316988-8fc65e80-b530-11e8-97d6-5bb276f5b102.png)
![snap2752](https://user-images.githubusercontent.com/29383891/45316989-8fc65e80-b530-11e8-8586-6510e8dbd49a.png)
outside view using Fly to try and show More about the fact NO dirt inside
![snap2753](https://user-images.githubusercontent.com/29383891/45317173-15e2a500-b531-11e8-976d-b75368228f59.png)

**Comment by Conchipedia** [comment]
i deliberately added 10 more dirt to the room to get that first 116 Dirt reading, i have since removed it and this is what i get now
![snap2757](https://user-images.githubusercontent.com/29383891/45317714-b2597700-b532-11e8-8dc4-0fbf701c7f55.png)
Shouldn't it have gone down by 10? not 14? something is not right

**Comment by Conchipedia** [comment]
![snap2758](https://user-images.githubusercontent.com/29383891/45317787-ea60ba00-b532-11e8-8d52-1fd557628cc4.png)
ONE Dirt added as you can see checked room information, Now its increased this by 3 on Dirt, where is it working this out?

**Comment by Conchipedia** [comment]
this world was created on 7.7.1 Server then Server was closed and copied to my Singleplayer Storage directory for Normal Eco so i could load this as Single player.
This world is here
https://drive.google.com/file/d/1UzBi5uMkxN7fYhnP30uvK7DltptF6E2q/view?usp=sharing

**Comment by Conchipedia** [comment]
Linking to #9298 as Room detection of blocks is effecting Table Requirments

**Comment by torchdragon** [comment]
I'm seeing this behavior on 7.7.2. I can achieve a Tier 2 room only if it is small and isolated from other blocks. ie, a 1x1x2 room with a floor block above the surrounding floor tiles. I can confirm that the room is detecting non-cardinal blocks that are outside of the room volume.

**Comment by torchdragon** [comment]
![image](https://user-images.githubusercontent.com/3497509/46186861-d648e680-c2ae-11e8-8dc5-ccdfb243b2d4.png)

**Comment by beastyn** [comment]
#12036 related
0.8.1.4
If you have volume from stone it still will count dirt

**Comment by beastyn** [comment]
fixed with 0.8.2.X
