### ISSUE TITLE
New Ramps are nice but if you make a mistake and have to remove them they turn into a block this block can not be used in a recipe to remake the ramp

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9301]
**Version:** 0.7.7.1 beta

Make a dirt ramp at a Workbench or Wainright Table, place Ramp, make mistake , you get dirt back and this then can be used to remake the dirt ramp (this is Fine)
![snap2761](https://user-images.githubusercontent.com/29383891/45318861-0ade4380-b536-11e8-8db6-93480d76c5f2.png)

BUT make a Stone Ramp and make a mistake you get back 4 Stone Road which you CANNOT use to remake the Stone Ramp with as there is no Recipe for this using Stone road and its a wasted Block if you don't want to use it
![snap2762](https://user-images.githubusercontent.com/29383891/45319061-a40d5a00-b536-11e8-8416-d7cca6105e9c.png)
![snap2763](https://user-images.githubusercontent.com/29383891/45319062-a40d5a00-b536-11e8-86db-21cb1c05617e.png)

The same goes for the Asphalt Ramp
![snap2764](https://user-images.githubusercontent.com/29383891/45319223-20a03880-b537-11e8-80b2-99271c467a58.png)
![snap2765](https://user-images.githubusercontent.com/29383891/45319224-20a03880-b537-11e8-9947-8c5a42756bb6.png)

reason for this is to save making mistakes as ramps are really expensive to craft more than the Road block, would having a 4xstone road recipe to stone ramp and a 4xasphalt road to Asphalt ramp be the best solution? as no real other workaround as far as i can see

**Comment by D3nnis3n** [comment]
Yep, that is really bad. To be honest, i'd like the old behaviour of world objects back :(

**Comment by CobaltEcho** [comment]
Agreed, I'm not a large fan of the new ramp demolition method.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/8674

**Comment by D3nnis3n** [comment]
Fixed.
