### ISSUE TITLE
floating / levitating cart issue and some other cart issues 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#931]
http://ecoforum.strangeloopgames.com/topic/1224/eco-5-1-dirt-ramp-cart-floating-bug-wheel-lift-off-he-ground-randomly/6

**Comment by L33m4n123** [comment]
The issue happens (at least for me) only, when changing on Y-Axis between 49 and 50. If I place a ramp when my player model is at 49 and move up that ramp.. it gets stuck inbetween. No matter the circumstances arround it. However always fails for us between 49/50 on y axis.
