### ISSUE TITLE
Fish are Swimming through Solid Blocks this also includes underwater rooms

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9311]
**Version:** 0.7.7.1 beta

as i'm underwater this world i have noticed that Fish will swim through Solid world blocks, (Otters have always seemed to do this since i first saw them ingame)
![snap2772 edited](https://user-images.githubusercontent.com/29383891/45324611-8942e180-b546-11e8-9b5b-e885f39a4ca5.png)
they are also swimming through my Underwater Dome (which is void of water)

![snap2776](https://user-images.githubusercontent.com/29383891/45324846-3ae21280-b547-11e8-846d-a6255d0d420c.png)

**Comment by SeanAtr0n** [comment]
fixed in 8.0
