### ISSUE TITLE
USER ISSUE: SStuck

### ISSUE THREAD

**Issue by Dragasama** [StrangeLoopGames/EcoIssues#9317]
**Version:** 0.7.7.1 beta

**Steps to Reproduce:**
1. Build a stright line fast

**Expected behavior:**
it should have worked without being stuck

**Actual behavior:**
instead it made me stuck

**Comment by BlazeGuy2** [comment]
@Dragasama Need more info.  Can you post a link to a video of this?  Need to know what you building, your surroundings, etc.  /unstuck is the command to help you get unstuck in the game.

**Comment by elfl0rd** [comment]
I cannot repro, in addition - no answer for a long time.
