### ISSUE TITLE
Very difficult/Impossible to input server password on Client UI

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#9318]
Open UI and click 'Browse'
Search for server name or sort and find server name in list
Click on server
click join
when password box comes up its behind the search UI and you cannot type in password

(work around:  set server you want to join as favorite.  Go into 'My Worlds" selected Favorited server and join.  Then password can be input into window)

**Comment by BlazeGuy2** [comment]
@johnkslg ConnectionUI.prefab changes might have been overwritten in latest staging update. Can you reapply the changes to master?
