### ISSUE TITLE
Contractor for loans and bonds in tooltips not shown

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9319]
If you hover over a username you see a tooltip showing it's contracts. When you hover over a contract there you can see some information about it, including the contractor. For loan and bond contracts the contractor is ever "`<unknown>`". The other ones work.

**Comment by johnkslg** [comment]
Should be unknown only when its not accepted yet

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/45712091-4a152180-bb40-11e8-94a4-bb3d58910d58.png)
Appears working in master.
