### ISSUE TITLE
Getting unusual A,B.C and D with Numbers driving up and down dirt and Asphalt Ramps on Steam Truck

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9320]
**Version:** 0.7.7.1 beta
this is Ramp system has Asphalt Ramps at the top and Dirt ramps lower down
![snap2786](https://user-images.githubusercontent.com/29383891/45371038-6ca7b780-b5e1-11e8-9928-25616c97f42b.png)
![snap2777](https://user-images.githubusercontent.com/29383891/45370872-15a1e280-b5e1-11e8-94ed-c1a6a9796df8.png)
![snap2778](https://user-images.githubusercontent.com/29383891/45370873-15a1e280-b5e1-11e8-8419-7565136c57f5.png)
![snap2779](https://user-images.githubusercontent.com/29383891/45370874-163a7900-b5e1-11e8-8c77-2977e82f4953.png)
![snap2780](https://user-images.githubusercontent.com/29383891/45370876-163a7900-b5e1-11e8-81ea-fe0f6dfa66bd.png)
![snap2784](https://user-images.githubusercontent.com/29383891/45370950-3cf8af80-b5e1-11e8-98b7-e98996996e18.png)
![snap2785](https://user-images.githubusercontent.com/29383891/45370951-3d914600-b5e1-11e8-91c0-db38d90f2818.png)

This is a Ramp System place elsewhere
![snap2781](https://user-images.githubusercontent.com/29383891/45370877-163a7900-b5e1-11e8-9303-c491354bc86a.png)
![snap2782](https://user-images.githubusercontent.com/29383891/45370878-163a7900-b5e1-11e8-9bca-a3268ae724ed.png)
![snap2783](https://user-images.githubusercontent.com/29383891/45370879-163a7900-b5e1-11e8-95eb-e26d77816ea9.png)

It looks like each section of the Ramp is divided into 4 sections A,B,C and D and where the Vehicle is passing over is the Section that it is showing
![snap2788](https://user-images.githubusercontent.com/29383891/45371268-138c5380-b5e2-11e8-852a-4ad8e08bf098.png)
![snap2789](https://user-images.githubusercontent.com/29383891/45371269-138c5380-b5e2-11e8-974a-e34dd41c0a09.png)
![snap2790](https://user-images.githubusercontent.com/29383891/45371270-138c5380-b5e2-11e8-90da-2ac4bf4fa584.png)
![snap2791](https://user-images.githubusercontent.com/29383891/45371272-138c5380-b5e2-11e8-86c5-7b5f7fdf0f66.png)
some are displaying NO numbers
![snap2792](https://user-images.githubusercontent.com/29383891/45371410-6b2abf00-b5e2-11e8-84b8-e2af0812a207.png)
![snap2793](https://user-images.githubusercontent.com/29383891/45371638-f441f600-b5e2-11e8-8bff-7142793b365a.png)
Think i worked out what the Numbers are meaning

90 = Facing North Ramp Going Up or Facing South Ramp going Down
180 = Facing East Ramp Going Up or Facing West Ramp Going Down
270  = Facing South Ramp Going Up or Facing North Ramp Going Down
NO NUMBER = Facing West Ramp going Up or East Ramp Going Down

they are all multiples of right degree angles 0, 90, 180, 270
not sure how your X,Y,Z is worked out in relation to Compass points (so did my best)

**Comment by WeaselDog** [comment]
Can we confirm this is still an issue? Asphalt ramps are different now.

**Comment by SlayksWood** [comment]
No it was changed. Now material is just being written: 
![image](https://user-images.githubusercontent.com/45708377/96084441-c0bfad00-0ec7-11eb-967e-b631eebbeaf1.png)
![image](https://user-images.githubusercontent.com/45708377/96084458-c917e800-0ec7-11eb-8aca-3eb0036c20d7.png)
![image](https://user-images.githubusercontent.com/45708377/96084473-d0d78c80-0ec7-11eb-8853-6eca886d5041.png)
