### ISSUE TITLE
Placing Dirt,Sand,Tailings from a shovel in real world takes longer than it used to

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9321]
**Version:** 0.7.7.1 beta

i pick up 10 of whatever i am placing from a stockpile or a Steam Truck , now i place them in the real world, sometimes i have to press the RMB more than once as it seems to pause, its not consistent when this will be, but it is getting annoying

**Comment by Conchipedia** [comment]
its NOT my mouse playing up, ran tests on loads of programs

**Comment by Conchipedia** [comment]
trouble this thing is a bit hard to explain, but i noticed it more since we went over from 7.6.3 to 7.7.0 i think when you changed the way clicking works, it's only more noticeable if you are like me and place huge amounts of dirt back into the world to terraform or make a huge Structure from tailings, by picking it back up from a stockpile so you have 10 being carried and can place more back rather than running back and forth getting one block , it would be easier to understand if it did this all the time (at first thought i thought my right mouse button was not working at times, but i can totally rule that out)

**Comment by TheeJudge** [comment]
Maybe he is talking about being able to hold the mouse button down to place dirt down. That stopped working with the 7.7.0 update. I had to click with every peice of dirt I wanted to put down

**Comment by Conchipedia** [comment]
i always click to place dirt, as holding down the mouse button isn't always a viable option as placing dirt this way you can often not be as accurate, so the clicking to place dirt with right mouse button sometimes i have to **DOUBLE CLICK** the right mouse button for it to work, this is on Singleplayer and Normal Servers that i play on

**Comment by D3nnis3n** [comment]
Is this issue still recent, Conchita?

**Comment by Conchipedia** [comment]
i think this issue has been solved so i think it can be closed down, it might sometimes happen with lag, but that is another issue, so i will close this one down
