### ISSUE TITLE
Water looks unrealistic from a underwater house with glass

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9325]
See the screenshot: Looks like if you were above water but you can see some water blocks at the coasts.

<img width="1917" alt="water" src="https://user-images.githubusercontent.com/25908592/45383165-b2c54100-b60a-11e8-99aa-762e7692c3bb.png">

**Comment by elfl0rd** [comment]
water need down\sides texture as i see.

**Comment by elfl0rd** [comment]
Addition, https://github.com/StrangeLoopGames/EcoIssues/issues/8849 (maybe grab into this issue?)

**Comment by SlayksWood** [comment]
merged with #8849
