### ISSUE TITLE
Server connection issues. Details not showing in server browser.

### ISSUE THREAD

**Issue by Birdtalon** [StrangeLoopGames/EcoIssues#9326]
I will outline the story which led up to the problems here.

I hosted an Eco server on my personal machine about 3 days ago. The server ran for 8 hours or so daily, and was taken offline in the meantime.
Today, I transferred the server files to a new, dedicated machine located in a datacentre. I ran the server and I was able to connect along with one other user (my friend).

However, no information is displaying in the detail window from the server browser. -> https://i.imgur.com/9t878rz.png (Only the description)

Also, when I asked for help on discord, Pam#1026 tried to connect to the server and was unable to connect. Yet I am able to connect, and my friend is also able to connect - and no others have joined the server.

Any information required I will be happy to provide.

Game Server: 185.62.86.38:8887

Server Web Panel
http://185.62.86.38:8888/

**Comment by johnkslg** [comment]
Open the server browser, see if you can find this server (turn off 'match version' in the filters so you can see all them).  If it repros, see what data is coming back from Server Info. Likely something is getting culled by the server provider.

**Comment by Birdtalon** [comment]
New information:

I downloaded a fresh install of the server and ran a fresh instance on a different port (UDP 8887, TCP 8888) and the information displayed correctly and users were able to join. This was running on the same machine.

**Comment by Birdtalon** [comment]
New information. I removed the config flag for "Playtime" from the server - and the info now shows up properly. It seems I may have had this set incorrectly and it broke the whole info panel.

**Comment by Birdtalon** [comment]
Server still not reliably showing in the server browser. Sometimes it will show, other times it won't. Players can still connect and play via direct IP and "My Worlds" tab.

**Comment by sidjuego** [comment]
@Birdtalon Thanks for the providing the info. I am unable to repro this issue.
Attaching screenshot below 
![9326](https://user-images.githubusercontent.com/43029943/45952975-501a6f00-c026-11e8-8733-1f97c583dacf.PNG)

Could you verify whether this issue persists in the updated version, please ?

**Comment by johnkslg** [comment]
Can you attach game.eco file to try here?

**Comment by Birdtalon** [comment]
The issue is not a problem since removing the description and playtime config entries.
