### ISSUE TITLE
3 profile corruptions on server at one time

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#9327]
Server was created a few days ago.  Last night 2 people could connect and 3 others get connecting ro connection failed errors.    They created a fresh world to test server and all 5 people could join with no issue.  Sounds like bad profiles but unusual that that many would corrupt at once unless there si a bug somewhere.  
Standalone server, no mods.  Was working fine for several days
Link to world save:  Game.eco

https://drive.google.com/file/d/1WfSC2DTDTUeuDc2JaCVqY5i86lK4VnFu/view?usp=sharing

**Comment by pamduncan** [comment]
The player names with the connection issues are
  SinGuru, Muffledmango and Blabberwocky

**Comment by johnkslg** [comment]
I see 4 users on that server:
Agesen
MuffledMango
SinGuru
Spiroo

I logged in just fine as each one.  
Or am I supposed to be opening 'game.eco corrput'?

**Comment by johnkslg** [comment]
User confirmed problem stopped, closing.
