### ISSUE TITLE
Still can't start my 0.7.6.3 world up after 0.7.7.2 - execption

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9328]
Now, i do not even get to "Converting the world" like described in this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/9196

I before get this error (which is not fixable by "RemoveObjectsOnException":

<img width="854" alt="exception" src="https://user-images.githubusercontent.com/25908592/45393213-32630800-b62b-11e8-8811-1a2f04b5a2ba.png">

Any chance that i can ever use my old world again? ;P

**Comment by BlazeGuy2** [comment]
Error is occurring in with the Modkit, with the WoodSignObject not being installed properly.  You'll need to delete the Mods folder and save a fresh one from the update.

**Comment by D3nnis3n** [comment]
Well, steam gave me that corrupted folder. I did now reinstall and get this:
<img width="931" alt="backup" src="https://user-images.githubusercontent.com/25908592/45393808-f1b8be00-b62d-11e8-850d-74d1d2dce16e.png">
The game file is not corrupt, though. It works on 0.7.6.3 just fine :(

Not that i would need that world anymore, but i wanted to archive it - in working state.

**Comment by BlazeGuy2** [comment]
Can you send me your save?

**Comment by D3nnis3n** [comment]
Well, the world was indeed corrupted, somehow i had left the server online in the state where it bugged out and it seems to have overwritten the backups every hour. I restored the working backup i send you to test in the issue #9196 - the file linked there is what i use and i get the following error when trying to load the world
<img width="1035" alt="error2" src="https://user-images.githubusercontent.com/25908592/45394062-20836400-b62f-11e8-9241-1a7bf4bbe6aa.png">

This is the map again: https://www.godsofwar.de/game1.zip

Sorry for the changing issues, at first steam gave me a corrupted installation, then i had a corrupted world and now with the right world i get the above error when trying to load the world before the converting would happen, probably.

**Comment by BlazeGuy2** [comment]
Currently getting a Network error when trying to download your save.  Could you post a link to it saved in google docs?

**Comment by D3nnis3n** [comment]
Eh, well, the file is definatley online and i can download it. Probably some blocking? It's 500 MB, it will take some time to upload it do google drive, but i'll start now.

**Comment by D3nnis3n** [comment]
https://drive.google.com/open?id=1NPVsQ4ZDRhzQtkFl36S7tzzF8DTm9d_z

There you go, went pretty fast.

**Comment by BlazeGuy2** [comment]
Sweet, got it.  I need to finish a feature doc today, so I'll check it out first thing tomorrow.

**Comment by D3nnis3n** [comment]
Alright, thank you :)

**Comment by BlazeGuy2** [comment]
Getting an exception on steam as well, gonna open it up in a debugger.

**Comment by BlazeGuy2** [comment]
Issue i'm getting on 7.7.2 right now is that your world is exceeding the maximum world volume size.

**Comment by BlazeGuy2** [comment]
![worldsize](https://user-images.githubusercontent.com/35509188/45446655-50a82280-b682-11e8-9d2e-91fc28b15fcd.PNG)

**Comment by D3nnis3n** [comment]
Yeh, that was about the issue why it couldn't convert earlier, but this map works on 0.7.6.3.

**Comment by SeanAtr0n** [comment]
as a temp solution here is your world with the chunk above max y deleted
https://drive.google.com/file/d/0B8xuMqEHE8n3U05tWTAxUlYyd2s/view?usp=sharing

It'll break again if someone builds above 130 so maybe you could convince your players not to do that for a while?

**Comment by D3nnis3n** [comment]
Yes, thanks, sir!

**Comment by SeanAtr0n** [comment]
7.8
