### ISSUE TITLE
Right-click chest while holding dirt causes server exception

### ISSUE THREAD

**Issue by ChronosWS** [StrangeLoopGames/EcoIssues#933]
If you right click on the chest with a shovel which contains dirt (does not repro if there is no dirt), we toss an exception in the server.

Appears to be due to invoking OnActRight twice for the following reasons:  First removal is due to the right-click action on a chest being to accept the carried item into the inventory of the chest.  Second removal is due to the right-click action while holding a block item (dirt) being to drop it into the world.  The second fails because the dirt has already been removed by the first action.

```
Player.cs.PlayerInteract():
case InteractionMethod.Right:
                   context.Target?.OnActRight(context); <-- First action, based on holding dirt while right clicking on the chest, Target == Chest
                   context.InteractableBlock?.OnActRight(context);
                   context.SelectedItem?.OnActRight(context);
                   context.CarriedItem?.OnActRight(context); <-- Section action, based on having a carried item (which has since been removed), CarriedItem == Dirt

```
context.CarriedItem is not aware that the item is no longer being carried at the time of the call, and we throw an exception trying to remove a non-existent item from the player's inventory.

**Comment by ChronosWS** [comment]
Considering a couple of possible fixes:

1. Make InteractionContext.CarriedItem (and SelectedItem) Func<Item> which re-checks the player's inventory on access.  Unfortunately, this would require locks on every access, and for SelectedItem there could be several such locks given its use (and I could see CarriedItem gaining such usage patterns in the future.)
2. Update the InteractionContext after each action invocation.   This still requires locks per invocation (a total of four per user action, given the current pattern in Player.PlayerInteract().
3. Wire in a notification of inventory change back to the InteractionContext causing it to update itself when it becomes out of date.  This is more complex but limits the number of locks to only those necessary due to actual changes.

**Comment by MarjieAVolk** [comment]
This doesn't appear to be happening anymore, as per unreleased changes at least.  I stepped through the code as well and didn't see any issues.  Gonna close this one for now
