### ISSUE TITLE
Blocker on creating a new world on local server.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9330]
When launching the application initially, the game is showing some error and is loading but is unable to generate a new world. And blocker is observed in the new world where I am unable to eat any food. Attaching a video regarding the whole process for better clarity.

Video Link: 
1. https://www.dropbox.com/s/yzm28scipl6hdx0/ScreenCaptureProject1.mp4?dl=0
2. https://www.dropbox.com/s/3un7kltsdjr2vbn/ScreenCaptureProject2.mp4?dl=0

**Comment by beastyn** [comment]
Should be fixed now. Please, reopen if you meet this again.
