### ISSUE TITLE
Steam Truck does not show the inputted text

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9333]
The Steam Truck does no longer show the text you give it. Unlike the Distribution station it at least saves the text correctly and shows it in the UI instead of being empty.

This is what it shows:
<img width="1463" alt="steamtrucks" src="https://user-images.githubusercontent.com/25908592/45440324-3e4ada80-b6bc-11e8-91ae-3511c05c88f8.png">

This is what it should show:
<img width="1172" alt="truck2" src="https://user-images.githubusercontent.com/25908592/45440399-689c9800-b6bc-11e8-91f7-bf595c6e879e.png">

**Comment by OsageSparky** [comment]
Confirmed, Don't work, even on Beta server.

**Comment by craig-jong** [comment]
check https://github.com/StrangeLoopGames/EcoIssues/issues/9443 for close reason

**Comment by Rambo99** [comment]
Confirmed in version 0.7.7.2
