### ISSUE TITLE
Can change the value of contracts - very bad bug

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9336]
We got a contract board in town, claimed by me. Everyone uses this as a central one. I as owner can change the amount in "Payment on completion" when i accept a contract. That probably should NOT be possible.

To reproduce:
1. Have a contract board in claimed zone
2. Let someone else add add a contract with put in cointainer 1 huckleberry and give payment on completion 1 dollar.
3. Open the contract, change 1 dollar to 1000 dollars, accept the contract, get the 1000 dollars in escrow, then finish the job and get your money.
4. Profit.

**Comment by johnkslg** [comment]
Theres calls to SetReadOnly in the contract clauses that should be preventing this, they must be failing somehow.

**Comment by Pradoxzon** [comment]
This should be fixed.
