### ISSUE TITLE
Tent (campsite) missing after partially place on another player property

### ISSUE THREAD

**Issue by Cosmicshoelace** [StrangeLoopGames/EcoIssues#9337]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Place tent half on someone else's land
Viola Gone

**Expected behavior:**
It Should Have Stayed there

**Actual behavior:**
Instead It dissipated and i don't have anything. 
**Do you have mods installed? Does issue happen when no mods are installed?:**
there are custom mods on the server. Though they are only for objects.

**Comment by elfl0rd** [comment]
Raising priority due too many users with this issue.
