### ISSUE TITLE
The stones respawn issue

### ISSUE THREAD

**Issue by dwujcik** [StrangeLoopGames/EcoIssues#9338]
Stones are respawn from the sky.
Version 0.7.7.2 beta
![20180913005441_1](https://user-images.githubusercontent.com/17785084/45457619-2725e000-b6f0-11e8-9dd6-0e6828ee9570.png)

**Comment by D3nnis3n** [comment]
Yeh we have that issue sometimes, too. But they're not respawning, it's just the same stone that falls down, ports up, falls down again - for no known reason.

**Comment by SeanAtr0n** [comment]
probably fixed with https://github.com/StrangeLoopGames/Eco/pull/3502

btw, repair your tools please :)
