### ISSUE TITLE
PERF: Use of IEnumerable.Count() where IEnumerable.Any() should be used

### ISSUE THREAD

**Issue by ChronosWS** [StrangeLoopGames/EcoIssues#934]
There are a number of places in the code where the pattern enumerable.Count() > 0 is used.  This could potentially be an expensive operation if the implementation of IEnumerable for the object is not constant.  A more efficient pattern would be to use the .Any() extension method.

**Comment by metachronism** [comment]
closing without specific instance where this is an issue / open new issues for specific cases
