### ISSUE TITLE
USER ISSUE: no "belt" slot in clothing.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9341]
belt is clothing item, but not have their own slot.
![default](https://user-images.githubusercontent.com/4980243/45464442-45ec9c80-b719-11e8-8c3f-d514869cb0f5.png)

**Comment by D3nnis3n** [comment]
Haha ever wondered where to place them, that noone has yet made a bug report for this, lol.
