### ISSUE TITLE
Pressing SHIFT types |

### ISSUE THREAD

**Issue by Katorone** [StrangeLoopGames/EcoIssues#9342]
Version: beta 7.7.2 downloaded from the SLG website
It's a clean install of the game, on a new computer.  OS: kubuntu 18.04, keyboard layout NL-BE (azerty).

This started happening as soon as I opened the game and tried to enter my credentials.

Screenshot: https://i.imgur.com/NTYVhNC.png

**Comment by SeanAtr0n** [comment]
Have you noticed similar issues in other games? Are you using steam?

reducing priority as this doesn't appear to be a widespread issue

**Comment by barcc** [comment]
OS: Ubuntu 18.04
* using Steam
* Not only Shift, any modifier key (alt,ctrl) types a weird Character, also caps-lock, win-key, F1-F12 (but the shift key really annoying)
* Not affected by keyboard layout
* Never seen this in other games nor in Eco versions prior to 0.7.7
* Not only chat window affected, every where you enter text

**Comment by SlayksWood** [comment]
Closed for now as not reproduced. If you still have this problem please reopen and provide new information
