### ISSUE TITLE
USER ISSUE: entering the world 

### ISSUE THREAD

**Issue by Tchounky** [StrangeLoopGames/EcoIssues#9343]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
connection to world

**Expected behavior:**
it should have connection to my server

**Actual behavior:**
The following error message popped up:
```
Connexion échouée
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Connexion échouée
```

**Comment by beastyn** [comment]
Should be fixed in 0.8.1
