### ISSUE TITLE
Empty inventory slot remembers last content

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9344]
Version: v0.7.7.2-beta

Steps to reproduce:
- after game start open a storage which already contains some objects
- move an object to another place
- hoover cursor over last location where the object came from

Expected behavior:
should show nothing since this slot is empty

Actual behavior:
a tooltiip comes up showing what was in there.

Guessing it’s a malfunction of inventory logic, not tooltip and the effect is gone after game restart.
It’s surly not a major problem, but might cause dubious side effects in other functions.

![pile](https://user-images.githubusercontent.com/38510829/45486258-ba93fb00-b75a-11e8-85d5-42dc1998da88.jpg)

**Comment by beastyn** [comment]
Still actual for 0.8.1.4

**Comment by SlayksWood** [comment]
> I think there is some weird caching going on that generally gives you tooltips for items that used to be in a given spot, rather than the items that are in that spot now:
> 
> ![image](https://user-images.githubusercontent.com/964559/80484737-11891c80-890d-11ea-9063-c19803856d20.png)
> 
> ![image](https://user-images.githubusercontent.com/964559/80484902-5614b800-890d-11ea-9598-b35f2a882f0b.png)
> 
> 1. Version
>    0.9 Staging-1526
> 2. Steps to reproduce
> 
> * Have an item in an inventory slot
> * Move the item or replace the item in the slot with something else
> * Hover over the old item's slot
> * You will get a tooltip for the old item, rather than a blank or the new item's tooltip
> 
> 1. Expected behaviour
>    Tooltips should display for items that are in the spot, not the items that were in the spot.
> 2. Actual behaviour
>    Tooltips for an old item are displayed instead.

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/7094
