### ISSUE TITLE
USER ISSUE: Large Corrugated Steel Door

### ISSUE THREAD

**Issue by Malenkei** [StrangeLoopGames/EcoIssues#9346]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Incorrectly displayed animation "Large Corrugated Steel Door" when opened.

**Expected behavior:**
Should open slowly and close properly.

**Actual behavior:**
Periodically disappear when opened. The animation sometimes disappears.n
**Do you have mods installed? Does issue happen when no mods are installed?:**
Periodically disappear when opened. The animation sometimes disappears.

**Comment by SeanAtr0n** [comment]
fixed in svn
