### ISSUE TITLE
Moving object away from player while inventorys open causes game to be unresponsive 

### ISSUE THREAD

**Issue by extant1** [StrangeLoopGames/EcoIssues#9347]
Version 7.7.2

I had a wooden cart on an elevator and was accessing the storage inventory (perhaps even moving objects from it) when someone moved the elevator up away from me causing the storage inventory to close. I could not do anything except use the mouse to look around. Movement, main menu, etc. were all unresponsive and I had to Alt-F4.

**Comment by SlayksWood** [comment]
Can't reproduce in 0.9.0 staging-1586. Seems fixed.
