### ISSUE TITLE
0,5 Tailings with max efficiency on blast furnace does NOT work

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9349]
See the screenshot:
<img width="1413" alt="tailings" src="https://user-images.githubusercontent.com/25908592/45501755-6bfa5700-b782-11e8-87e9-a0ce3303814f.png">
I smelt 20 ore and 20 gold ore - the iron ore at once. And still get 40 tailings out of half of it.

**Comment by D3nnis3n** [comment]
My efficiency: 
<img width="754" alt="tailings2" src="https://user-images.githubusercontent.com/25908592/45501929-edea8000-b782-11e8-9772-18adc4119bda.png">

**Comment by D3nnis3n** [comment]
Additional information:
When typing in 100 for ion bars to smelt, it shows correctly on the left side at the icons that you get 50 tailings and 100 iron bars. But when you then look at the project you get 1/1 and in the end you got 100 iron bars and 100 tailings in the storage. Probably this 0,5 does not work or the "Tailings Project" is the problem?

**Comment by craig-jong** [comment]
The issue is with how the game handles fractional items.

I've temp fixed this in a PR by doubling everything in the affected recipes, but we'll figure a better fix out in a later release.

**Comment by D3nnis3n** [comment]
E.g. you can only smelt 2 ingots at once now?
