### ISSUE TITLE
Shop UI bug with removing of "for sale items"

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9350]
I very often get the problem that when i remove a for sale item with the "x" out of my shops, the "x" disappears for all other for sale items so i cannot delete another one without reopening the UI. This problem did not happen for "to buy" items yet.

**Comment by D3nnis3n** [comment]
Shop UI was changed.

**Comment by D3nnis3n** [comment]
Still happens sometimes.

**Comment by TwixterZ** [comment]
No longer an issue with the rework of store in 9.5
