### ISSUE TITLE
Missing strings - "Land Claim Stake" and he description "Used to claim, unclaim, and examine property."

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9355]
- [ ] "Land Claim Stake"
- [ ] "Used to claim, unclaim, and examine property."
![default](https://user-images.githubusercontent.com/4980243/45509457-4d0abd80-b7a0-11e8-8dd0-f2496b3c5f91.png)
@Nanders

**Comment by Nanders** [comment]
Have you tried restarting the server? These are in and working as far as I can tell.

**Comment by elfl0rd** [comment]
Yep, i found it :)
Sorry!
