### ISSUE TITLE
Loc. strings is not used in "benefits from" section.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9356]
![default](https://user-images.githubusercontent.com/4980243/45509809-36b13180-b7a1-11e8-9f08-4e56252e932b.png)
![default](https://user-images.githubusercontent.com/4980243/45509828-42045d00-b7a1-11e8-8e8e-535d7bf8f8f2.png)
etc...
@Nanders

**Comment by Nanders** [comment]
This is fixed
