### ISSUE TITLE
Missing\or not used strings in skills tree.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9357]
![default](https://user-images.githubusercontent.com/4980243/45510462-f5ba1c80-b7a2-11e8-96e9-aa576906f9e3.png)
![default](https://user-images.githubusercontent.com/4980243/45510474-0074b180-b7a3-11e8-93cd-8685c190c1c5.png)
etc...
@Nanders

**Comment by Nanders** [comment]
This has been changed for 8.0
