### ISSUE TITLE
Saved ViewDistance doesn't take effect until opening the Escape Menu

### ISSUE THREAD

**Issue by ChronosWS** [StrangeLoopGames/EcoIssues#936]
Noticed while verifying another fix with the the Scene viewer open, chunks beyond the default (minimum) view distance do not start spawning in until the escape menu has been opened once, even if the saved view distance differs (in my case using max distance.)  I have not verified if this is the case in the release client.  Once opening and closing the escape menu, chunks beyond the minimum start to stream in.

**Comment by metachronism** [comment]
this is only true when running the editor, for performance reasons.  Unity editor runs quite a bit slower than the release build, and if you want to test view distance you can just adjust as you describe
