### ISSUE TITLE
Picking up a multi-order says the message many times

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9361]
![image](https://user-images.githubusercontent.com/3536496/45522022-88dc5d80-b775-11e8-82f6-a1ae7d7e6007.png)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/71444712-6e3cb680-2724-11ea-9621-9d9f2556f840.png)
