### ISSUE TITLE
USER ISSUE: Able to see through the world

### ISSUE THREAD

**Issue by Paendragoon** [StrangeLoopGames/EcoIssues#9362]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. place any material cube other than framed glass, or normal glass
2. place brick column or floor next it, corrugated steel, flat steel columns also cause it
only happens when columns are 1 block high

**Expected behavior:**
The material that is connected to the brick column/floor should have a side visual

**Actual behavior:**
The material that is connected to the brick column/floor does not have a visual and you can see through the world

**Do you have mods installed? Does issue happen when no mods are installed?:**
I do not have any mods installed
![see through world brick](https://user-images.githubusercontent.com/38334519/45529111-7718ab80-b7b1-11e8-8c1d-292bef2cc9f8.png)
![see through world corrugated steel](https://user-images.githubusercontent.com/38334519/45529113-78e26f00-b7b1-11e8-8b41-e2a9b5dd8d84.png)
![see through world flat steel](https://user-images.githubusercontent.com/38334519/45529116-7aac3280-b7b1-11e8-80b2-05741fd4d1dc.png)

**Comment by seccombew** [comment]
Dupe

**Comment by seccombew** [comment]
@BlazeGuy2 Find dupe please, and list.
