### ISSUE TITLE
USER ISSUE: Fortfahren geht nicht

### ISSUE THREAD

**Issue by JannLP** [StrangeLoopGames/EcoIssues#9363]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Sowie ich auf Fortfahren drücke läd es aber es passiert nichts

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Verbindung fehlgeschlagen
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Verbindung fehlgeschlagen
```

**Comment by SlayksWood** [comment]
Do you have this problem now?
If it happens again, please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Checked on 8.1.4. Wasn't able to reproduce, seems fixed.
