### ISSUE TITLE
Player animation being static in 3D view for walking and jumping.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9364]
Description: After creating the world, when switching back to 3D view, there is no character animation for movement.

STR:
1. Launch the game.
2. Create a world.
3. Open the view to third person view.
4. Move around and observe the issue.

Actual Result: The player movement is static and is not animated.

Expected Result: The player movement should be animated for all kinds of player interactions.

Video Link: https://www.dropbox.com/s/v71qakwpre74vep/Unity%202018.2.3f1%20Personal%20%2864bit%29%20-%20Game.unity%20-%20Client%20-%20PC%2C%20Mac%20%26%20Linux%20Standalone%20_DX11_%2014-09-2018%2016_12_20.mp4?dl=0

**Comment by SeanAtr0n** [comment]
couldn't reproduce, appears to be a problem w/ their unity checkout
