### ISSUE TITLE
Improper functionality observed with the tutorial.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9365]
Description: If the user completes the actions of a tutorial before selecting it and then selects it, the tutorial is not disappearing.

STR:
1. Start the game.
2. Create a world or rejoin a previously created world.
3. Complete the actions of a tutorial before selecting it. (Issue observed with material processing tutorial)
4. Now select the tutorial and observe that even though all the tickmarks are selected, it is not closing.
5. Observe that manually trying to skip the tutorial is also not closing the tutorial.

Actual Result: If a tutorial is completed before it is selected, it is getting stuck upon selection.

Expected Result: If the progression is completed and then the tutorial is selected, once all the tick marks appear the tutorial should automatically close.

Screenshot: 
![screenshot 375](https://user-images.githubusercontent.com/43132426/45548190-13d65a00-b841-11e8-8e50-19d2facf418c.png)

**Comment by johnkslg** [comment]
Something with the Opened state preventing a tutorial from closing perhaps?
