### ISSUE TITLE
The water is appearing on the land and the player is able to swim on land.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9367]
Description: If the player digs near the water area, sometimes the water is not visible in that area and the player floats in that spot. Sometimes the water is isolated and still is appearing to be flowing in a specific area.

STR:
1. Start the game.
2. Create/join a world.
3. Dig near a water source. (Preferably a waterfall)
4. Observe that the player floating on land near the water source.

Actual Result: The player is able to float when there is no water visually displayed. The water is also isolated and is continuing to flow.

Expected Result: If the player digs near a water source, the water should visually flow to that area as well depending on the height. The water should stop or disappear if it has been isolated from its source.

Video Link: https://www.dropbox.com/s/66cr6pqsee67bp5/Unity%202018.2.3f1%20Personal%20%2864bit%29%20-%20Game.unity%20-%20Client%20-%20PC%2C%20Mac%20%26%20Linux%20Standalone%20_DX11_%2014-09-2018%2019_22_39.mp4?dl=0

**Comment by beastyn** [comment]
Wasn't able to reproduce exactly this one in 0.8.1 but water still needs improvement
