### ISSUE TITLE
Wooden shovel is not responding properly for a single selection.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9368]
Description: If the user uses the wooden shovel and performs a single selection to unearth dirt, it is not responding unless the player changes the angle or location but if the player repeatedly taps it, then it is getting collected.

STR:
1. Start the game.
2. Create/join a world.
3. Use the wooden shovel.
4. Try collecting dirt on a single click.
5. Observe that it doesn't always work.
6. Repeatedly click and it generally works on the 2nd or 3rd click.

Actual Result: The wooden shovel doesn't always respond when selected a single time.

Expected Result: The wooden shovel should work accurately on a single click, same as the multiple clicks.

**Comment by Nicolausi113** [comment]
A short click in most cases doesn't work – this is ECO-behavior since I know.
Maybe it has to do with harvesting camas (blue blooming plants), in this case it needs really a short click, otherwise camas is dug out.

**Comment by seccombew** [comment]
Using the shovel requires clicking and holding. If mouse click is released early, action is canceled.
