### ISSUE TITLE
During the "Building room tutorial", if the player digs a tunnel it is being considered as completion.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9369]
Description: When the user has the building room tutorial, if the player starts digging into the ground and creates the shape of a tunnel with an entrance to it, the room tutorial is getting completed.

STR:
1. Start the game.
2. Create/join a world.
3. Complete the tutorials until the create room tutorial appears.
4. Minimize the tutorial.
5. Start digging using a wooden shovel.
6. Dig a tunnel like path with an entrance to it.
7. Observe that after sometime, the tutorial gets completed.

Actual Result: If the player digs a tunnel or constructs a partially constructed building, the tutorial is getting completed.

Expected Result: The tutorial should get completed only when the expected conditions are met.

Screenshot:
![screenshot 378](https://user-images.githubusercontent.com/43132426/45556897-04afd600-b85a-11e8-9ee8-9da35f21bb03.png)
![screenshot 379](https://user-images.githubusercontent.com/43132426/45556898-04afd600-b85a-11e8-9278-9f91b1649a91.png)
![screenshot 380](https://user-images.githubusercontent.com/43132426/45556900-04afd600-b85a-11e8-9a35-09298915b76b.png)
![screenshot 381](https://user-images.githubusercontent.com/43132426/45556902-05486c80-b85a-11e8-8a9a-185b852eb8ef.png)

**Comment by johnkslg** [comment]
Its cause you made a little room down there :/

**Comment by redwyre** [comment]
I got this after digging a small horizontal shaft
![image](https://user-images.githubusercontent.com/431728/50621383-4a9bc180-0f51-11e9-8607-14496b5069e0.png)

**Comment by elfl0rd** [comment]
My old one :D (still possible)
https://github.com/StrangeLoopGames/EcoIssues/issues/8409

**Comment by johnkslg** [comment]
Thoughts on fixes? Youre technically making a room. We could require the room volume to be over say 5 or 10 volume

**Comment by johnkslg** [comment]
I made it check for volume > 5

**Comment by elfl0rd** [comment]
yes, minimum volume and tier restrictions (not t0 to exclude "natural rooms")
In addition, perhaps this section should be reworked to tell beginners about how room tiers work.
(Build room with tier >0.3? or something like...)

**Comment by Conchipedia** [comment]
it works for me that its a tunnel or a room to complete the tutorial, as i am always Mason and a Masonry Table needs a room, and i normally just dig a hole into the ground or cliff to get a room
