### ISSUE TITLE
Room Volume or Deed Ownership not changing on description when entering another room and hovering mouse over this no longer works

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9371]
**Version:** 0.7.7.2 beta

this is not changing when i go from room to room and last time i checked in previous version hovering mouse over this game room information on blocks
![snap2832](https://user-images.githubusercontent.com/29383891/45558767-973f7d80-b838-11e8-8b5e-fb5d728ed016.png)
Eco does know I'm in other rooms because if i type /testroom i get this information for the room i am in
![snap2833](https://user-images.githubusercontent.com/29383891/45558906-ed142580-b838-11e8-8330-a15d8c8fb08a.png)
![snap2834](https://user-images.githubusercontent.com/29383891/45558937-06b56d00-b839-11e8-8e8e-5912b230a3c8.png)
![snap2835](https://user-images.githubusercontent.com/29383891/45559024-4c723580-b839-11e8-81db-dc92c7e4c2c9.png)

i Disconnected outside a room now, and coming back it just showing this so it looks like this part is broken entirely
![snap2836](https://user-images.githubusercontent.com/29383891/45559139-95c28500-b839-11e8-9547-82d299112a94.png)

The Tables are detecting the Correct Information
![snap2837](https://user-images.githubusercontent.com/29383891/45559249-dcb07a80-b839-11e8-99a4-57961204cc64.png)
because if i type /testroom in the one with the above Store ALL information matches
![snap2838](https://user-images.githubusercontent.com/29383891/45559290-ffdb2a00-b839-11e8-9e89-3cfeae402f06.png)

**Comment by Conchipedia** [comment]
found out its NOT time based, as soon as i get off any part i own and go to anyway that i do not own and come back it all switches back on

**Comment by Conchipedia** [comment]
slightly different behavior on a singleplayer world
I logged out on this spot and then loaded it back in NO Deed name appears
![snap2846](https://user-images.githubusercontent.com/29383891/45561444-abd34400-b83f-11e8-97fd-56d6d964ab11.png)
i move to the right deed name appears
![snap2847](https://user-images.githubusercontent.com/29383891/45561445-ac6bda80-b83f-11e8-945d-dd1dcbd09fe6.png)
i move to the left of the door and the room size disappears (think this bit is ok as it really is classed outside of the room)
![snap2848](https://user-images.githubusercontent.com/29383891/45561446-ac6bda80-b83f-11e8-90f1-3771b4d13d9c.png)
if i move back to where i had logged out deed name is there proving that something is not detecting when loading in world
![snap2850](https://user-images.githubusercontent.com/29383891/45561835-97437b80-b840-11e8-83a9-7ad09b862e6c.png)

**Comment by SlayksWood** [comment]
There were many changes to the calculation of the room and the claiming of the territory. 
Almost all issues described in the latest versions were not observed.
merged with #12130. It was discovered while checking your issues.
If it happens again, please reopen
