### ISSUE TITLE
Graphical issue is observed with the camera when going to cliff edges.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9372]
Description: If the player goes to cliff edges with plants or flowers near it, the camera zooms in very close to the player showing from the internal view.

STR:
1. Start the game.
2. Create/Join a world.
3. Move to cliff edges that have flowers or plants near it.
4. Tilt the camera angle a little lower.
5. Observe the camera angle corruption issue.

Actual Result: The camera angle looks corrupted when standing on cliffs near flowers or plants.

Expected Result: There camera angle should only come so much closer to a character as near the backpack and not any further.

Screenshot:
![screenshot 387](https://user-images.githubusercontent.com/43132426/45559811-1b0d6000-b861-11e8-9d46-5b6fe0c3f9bd.png)
![screenshot 388](https://user-images.githubusercontent.com/43132426/45559812-1b0d6000-b861-11e8-88c1-c5f0d21b273c.png)
![screenshot 389](https://user-images.githubusercontent.com/43132426/45559813-1b0d6000-b861-11e8-93f3-c2ba2deacd77.png)
![screenshot 390](https://user-images.githubusercontent.com/43132426/45559814-1b0d6000-b861-11e8-9402-a1cdfca8cf97.png)

**Comment by SlayksWood** [comment]
Can't reproduce. Seems fixed.
