### ISSUE TITLE
The arrow is appearing to be stranded when the player uses the bow

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9373]
Description: When the player has a bow and arrow and quickly makes a selection without completely drawing the bow, the arrow is appearing to be standing alone and out of the picture.

STR: 
1. Start the game.
2. Create/Join a world.
3. Get the bow & arrow and select the bow.
4. Single click the left mouse button.
5. Observe the arrow appearing to be stranded.

Actual Result: The arrow is appearing to be stranded like a graphical corruption.

Expected Result: The arrow should appear near the player like a bow with a quiver or the arrow should not be appearing until the player has completely drawn the bow.

Screenshots: 
![screenshot 391](https://user-images.githubusercontent.com/43132426/45562282-a4c02c00-b867-11e8-81a4-c773a07d17c0.png)
![screenshot 392](https://user-images.githubusercontent.com/43132426/45562283-a558c280-b867-11e8-8af7-058723f4f528.png)

**Comment by SeanAtr0n** [comment]
fixed in svn
