### ISSUE TITLE
Law propose button does nothing

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#9376]
When I open the law propose, after filling out the law to propose a new demographic, the propose button does nothing.  If I refresh the page, then the button works.

**Comment by seccombew** [comment]
@rainfarmer @Tigran07 Please used "Fixed" tag rather than "Complete". Also confirm if fix has been PR'ed in and approved. Then please close issue. Also link back to issue in PR.

**Comment by seccombew** [comment]
@rainfarmer Can you confirm re: above message.

**Comment by rainfarmer** [comment]
havent been able to repeat this error
