### ISSUE TITLE
Targeting has some dead zones while building

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9378]
![animx](https://user-images.githubusercontent.com/3536496/45576444-12e6fd80-b82c-11e8-8335-10329977ae9e.gif)
Looks like pipes should be buildable at some of these selection points.

**Comment by SeanAtr0n** [comment]
there used to be an arrow on the pointer that clarified whats going on there

**Comment by elfl0rd** [comment]
Confirm.
In addition - building bridges is harder in eco.

Build bridge in Eco
https://youtu.be/iq9Qus9oJy4

As idea - zones on existing block, if you target it - you place new block close to selected zone.
![default](https://user-images.githubusercontent.com/4980243/45581490-d527ba80-b8a7-11e8-97e8-b2c050e683b2.png)
![default](https://user-images.githubusercontent.com/4980243/45581498-f4264c80-b8a7-11e8-8581-935f83c7dfa2.png)
![default](https://user-images.githubusercontent.com/4980243/45581501-fab4c400-b8a7-11e8-8e64-94aa40059000.png)


And if it possible - copy crouch clipping feature from minecraft, where you can not drop from block if you crouch.

**Comment by MazonDel** [comment]
Video demonstrating current behavior: https://drive.google.com/file/d/1UForTdP0iy9TR3XI9jeMpC0O5X1qHhTi/view?usp=sharing
