### ISSUE TITLE
USER ISSUE: Starting camp disapear

### ISSUE THREAD

**Issue by Ysaelya** [StrangeLoopGames/EcoIssues#9379]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
While I was trying to put my starting camp in a nice place, It disapeared. I must have clicked a bit too much.

But please How can I keep playing without it ?

**Expected behavior:**

**Actual behavior:**
n
**Do you have mods installed? Does issue happen when no mods are installed?:**

My pseudo in game is :  ?Wanheda?

**Comment by BlazeGuy2** [comment]
Hard to fix bug w/o consistent repro case.  Can you find a way to consistently cause the camp to disappear again?

**Comment by elfl0rd** [comment]
Fixed.
