### ISSUE TITLE
PERF: BehaviorUpdate contributing heavily to long view distance frame time

### ISSUE THREAD

**Issue by ChronosWS** [StrangeLoopGames/EcoIssues#938]
While reviewing perf at large view distances, I note the following in the unity Profiler:

BehaviorUpdate:

- PlantGrowth.Update(): Total 17.7%, Calls: 49057, Time: 18.3ms
- WorldObserver.Update(): Total: 13.5%, Calls: 1, Time: 13.81ms
- AmbienceController.Update(): Total: 3.1%, Calls: 8492, Time: 3.15ms

It seems unlikely that most of these PlantGrowth or Ambience calls really need to be made, so it's worth some investigation into optimizing these a little bit.

**Comment by ChronosWS** [comment]
Looks like much of PlantGrowth is due to UnityEditor-specific code.  Commenting it out still leaves AmbienceController but reveals LateBehaviorUpdate contributing significantly to frame time as well, particularly:

- HighlightableObject.LateUpdate(): Total: 23.2%, Calls: 50496, Time: 16.18ms

**Comment by ChronosWS** [comment]
AmbienceController does not need to be called every update.  Instead it can be called via Invoke since we know the next time when it should run.  This will eliminate its per-frame load.

**Comment by metachronism** [comment]
a lot of these scripts running on the plant objects can be moved to the different LODs probably, so they will automatically not be active with the plant is LOD'd out

**Comment by metachronism** [comment]
closing this out as seems to mostly be fine now
