### ISSUE TITLE
USER ISSUE: Crash when dumping dirt from skid steer

### ISSUE THREAD

**Issue by SereneRebel** [StrangeLoopGames/EcoIssues#9380]
**Version:** 0.7.6.2 beta

**Steps to Reproduce:**
using skidsteer to fill area with dirt using right click, once dirt runs out it crashes

**Expected behavior:**
no crashed

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: ArgumentNullException
Message:Value cannot be null.
Parameter name: source
Source:System.Core

System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Components.VehicleToolComponent.WorldObjectInteract(Player player, INetObject obj, InteractionMethod method)</size>
```

**Comment by BlazeGuy2** [comment]
This bug is on 7.6.2, current live is 7.7.2.  Reopen if this bug is occurring on the current live version.
