### ISSUE TITLE
SUGGESTION: Law Managment

### ISSUE THREAD

**Issue by CobaltEcho** [StrangeLoopGames/EcoIssues#9381]
It would be great if there was a way to Save/Load or Import/Export laws.  They don't even have to be "completed" laws, but when you "load" them, it has the law completed so you can make small changes and then submit.  It really sucks when you make a really complicated law and find a small error, then you have to start all over.  Or when you start a new world and everyone has laws they like, but you have to spend hours and hours recreating them (and hope you dont make a small error!).

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#583

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4090

(I closed the suggestion also)
