### ISSUE TITLE
Teleporting to top

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9382]
When you drive a steamtruck in a mine, with the driver side to a wall and then exit the truck you will be teleported to the top block of the mine, e.g. the top of the mountain.

**Comment by BlazeGuy2** [comment]
Dup of #9383

**Comment by D3nnis3n** [comment]
@BlazeGuy2 
Not a duplicate as of two things:
1. My issue was first.
2. That issue talks about the CAR being teleported up. I talk about the PLAYER being teleported up ;)
