### ISSUE TITLE
USER ISSUE: Teleporting Vehicles

### ISSUE THREAD

**Issue by OrneryIke** [StrangeLoopGames/EcoIssues#9383]
![underground mine](https://user-images.githubusercontent.com/22848917/45588396-29e82700-b8e2-11e8-8f2a-4f0853d18755.png)
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
I have the underground mine shown. Whenever I leave a vehicle here unattended, or log off, the vehicle teleports to the surface. Sometimes. Currently there's a steam truck missing and I assume it's stuck in the ground between here and the surface somewhere.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods

**Comment by OrneryIke** [comment]
UPDATE: The truck has reappeared.
![truck is back](https://user-images.githubusercontent.com/22848917/45588478-6cf6ca00-b8e3-11e8-81c1-44a0046fc49d.png)

**Comment by SeanAtr0n** [comment]
7.8
