### ISSUE TITLE
Forgiven loan contracts stay there as active contract with insane length

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9384]
<img width="525" alt="loan" src="https://user-images.githubusercontent.com/25908592/45590515-326c4c00-b93a-11e8-9a6c-ff7b819016df.png">

**Comment by Pradoxzon** [comment]
I can't reproduce this bug. When I forgave a loan to another player, the time left on the contract stayed the same.
The other player was then able to open the contract and finish it without trouble. The contract didn't show as active after that.

**Comment by D3nnis3n** [comment]
The player did not close the contract, as he became inactive - the loan was forgiven as he did not pay. The contracts should vanish nevertheless and not switch to 419 days left :D

**Comment by Pradoxzon** [comment]
![temp2](https://user-images.githubusercontent.com/25668381/45851046-cfe2c980-bd06-11e8-9f59-bfdba39631ed.png)

**Comment by Pradoxzon** [comment]
Ok, that makes more sense then.

**Comment by D3nnis3n** [comment]
Sorry, that i missed that bit of information :(

**Comment by Pradoxzon** [comment]
Was he unable to mark the job as failed?

**Comment by D3nnis3n** [comment]
He had no such option, afaik.

**Comment by D3nnis3n** [comment]
Well, then this probably is one of these sad causes where you just can't find why something happened - but as you can see, i got a screenshot of this everlasting contract. Unfortunatley, i'm out of ideas why this happens, so probably with this issue we are out of luck. But that does also mean, not many people will have it, fortunatley. :)

**Comment by johnkslg** [comment]
Yeah see if you can make it happen again in a later update, I think it is just cosmetic. Thanks for the bug report, will close for now, reopen if it still happens in a future update.
