### ISSUE TITLE
Glass Wall Shelf Cabinet Bug 7.7.0

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#9385]
When placing a Shelf Cabinet next to a glass wall, it will sometimes place into it. Upon removeing the shelf cabinet there is a hole in the wall. This hole will not allow any blocks be placed in it and simply gives the message: "Can't place a block there."

**Comment by SlayksWood** [comment]
Can't reproduce in staging-1568, I can't place shelf cabinet in glass wall. Closed for now.
![image](https://user-images.githubusercontent.com/45708377/83009708-d0754c80-a01f-11ea-950c-f69e8bf9460e.png)
