### ISSUE TITLE
game balance and smithing

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#9386]
Version: 0.7.7.2 server beta

Steps to Reproduce:

N/A

Expected behavior:
That there should be a way to deal with tailings and there should be
a better game balance. 

Actual behavior:

This is being posted on September 15 2018

The tailings system in this game is an absolute failure.  So far the game
is so unbalanced and it seems more like you are punished for being a smith
and using a Bloomery and a Blast Furance. 

The Smith is the ONLY job in this game that has a by product which will
actually destroy the world NO other profession has anything like that! 

Even a Cook which produces a Tallow has a use and they can still
use them for stuff like a Tallow Candle and in other recipies.

So really the smith is the ONLY one that produces a tailing that
will destroy the world and that is unfair.

You need to get a better game balance either you need to have
every profession produce some kind of tailing or byproduct 
to their skills or find a way to be able to use the tailings 
and get rid of them perminately. 

Why is it that you are punishing smiths so heavily and make them 
the only profession that has a byproduct which can destroy a world
every profession should have a byproduct that they need to deal with
or find a way to use those byproducts so they are no longer a threat. 

Right now you are not doing that and smiths get the raw end of the
deal here.

For a Smith there is NO use for tailings what so ever and the only
thing you can do with them is bury them and hope that 
you don't run out of room. 

at one point a blast furance as well never produced tailings 
then the developers of the game changed that as well 
so now a Bloomery produces 2 tailings per ingot made and
a Blast Furance produces 1 tailing per ingot made. 

So now you have actually made it worse because at least 
before you would be able to get to a point where you got
a blast furance and then no longer produced any more tailings.

Now we have an item (tailings) that has NO use that every time
you produce and ingot you are always going to produce tailings. 

This needs to be immediately fix you need to get a better game balance
here and stop punishing the smiths! 

There should be no way that the smiths are the only job in the game that is
producing a harmful byproduct in this game and the only one that 
can actualy destroy the world and the fact that the tailings have no 
use again is absolutely horrible! 

The whole tailings system the way it currently is, is an absolute mess! 

Now one thing I have seen people do with tailings is turn them into
a currency and make it so that tailings can be set as a currency and then
when you use the mint the tailings can be turned into a currency there
is an addon for that called "Dirty Money 1.0" that would be one idea 
for a use for the tailings. 

https://eco-mods.com/resources/dirty-money.65/

I think that something like this is a very cleaver way to be able
to deal with the tailings problem let them be turned into
a currency.  something like this needs to be immediately 
implemented.

This is not just a suggestion but this is high level issue that
needs to be immediately adressed the game balance with 
Eco is extremely unbalanced when it comes to smith and this
needs to be immediately addressed! 

Find a solution to this problem immediately!  The way it is
now is absolutely horrible!

**Comment by TheeJudge** [comment]
While I don't argue that it is a little rough but really man. This is for issues like bugs that are breaking the game. And I mean breaking as in unplayable or really messed up. I feel as though this is more of an issue for one.

Use teamwork to take care of the problem. What harmful byproduct do you suggest for other perfessions?

Also, in the real world dynamic what do you expect tailing to be used in?

If your so bent out of shape about it edit the .cs for asphalt as we have done on our server to use tailings. Takes like 5 seconds and then you can be happy again.

**Comment by extant1** [comment]
This is certainly posted in the wrong place but I agree.

Even with efficiency five and a blast furnace there is a tremendous amount of tailings that is produced and while having it as a burden makes the game interesting its a little too burdening. At minimum allow a stockpile to hold more tailings by increasing each slot to 10 instead of 5.  I'd like to see tailings decay after a week while in stockpiles as well so a server doesn't need to have a super massive underground cavern full of stockpiles.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#582
