### ISSUE TITLE
USER ISSUE: electric Lathe v.7.7.2

### ISSUE THREAD

**Issue by evinette11** [StrangeLoopGames/EcoIssues#9387]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**

**Expected behavior:**
after having a electric stamping press i should be able to create a electric lathe

**Actual behavior:**
does not let me create one, now im stuck in my world :(
**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by elfl0rd** [comment]
?
create room.
![20180917073527_1](https://user-images.githubusercontent.com/4980243/45606264-5c159800-ba4c-11e8-9a8b-877544ea251b.jpg)
![20180917073535_1](https://user-images.githubusercontent.com/4980243/45606263-5c159800-ba4c-11e8-885e-7a194f329ce9.jpg)

place electric machinist table+electric stamping press in it.
![20180917073546_1](https://user-images.githubusercontent.com/4980243/45606265-6041b580-ba4c-11e8-952d-c27c9560021b.jpg)
![20180917073555_1](https://user-images.githubusercontent.com/4980243/45606266-6041b580-ba4c-11e8-9788-2910723fd0ab.jpg)


fine.
