### ISSUE TITLE
USER ISSUE: Connect Failed

### ISSUE THREAD

**Issue by Zazus** [StrangeLoopGames/EcoIssues#9389]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
The client can't connect, no Ping. If i make a ping from my computer to the server: 73.190.174.211 i got 143ms.
The server can't even see me trying to connect

**Expected behavior:**
Connect to server

**Actual behavior:**
The following error message popped up:
Initialize engine version: 2018.2.0f2 (787658998520)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 970 (ID=0x13c2)
    Vendor:   
    VRAM:     4043 MB
    Driver:   24.21.13.9924
Begin MonoManager ReloadAssembly
- Completed reload, in  0.065 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.343121 ms
Client version: 0.7.7.2 beta
Tuesday, September 11, 2018 12:08 PM
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

**Comment by SlayksWood** [comment]
Checked on 8.2.7. Wasn't able to reproduce. If it happens again, please reopen.
