### ISSUE TITLE
USER ISSUE: rgergdsg

### ISSUE THREAD

**Issue by AWPmik** [StrangeLoopGames/EcoIssues#9392]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
dgdgsdg

**Expected behavior:**
gdsgsdgdgds

**Actual behavior:**
The following error message popped up:
```
Failed to login

... Just a Joke ;)
-= Cracked by WhiteLion & Ported by Miniwinz.fr =-
Stop steal the crack without credit FUCK NeO-Team! 
```

**Comment by AWPmik** [comment]
efref

**Comment by elfl0rd** [comment]
Lol, stop using pirate copy!
