### ISSUE TITLE
7.8 bleeding: Minimap broken

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9394]
Version: v0.7.8.0-beta-staging-06184de3
![7 8](https://user-images.githubusercontent.com/38510829/45598639-8846ff80-b9df-11e8-987e-d183fe23711c.jpg)

**Comment by BlazeGuy2** [comment]
Just reproduced this in Unity.

**Comment by BlazeGuy2** [comment]
Issue is with minimap prefab having the filter panel toggle being set to none.

**Comment by MarjieAVolk** [comment]
Already fixed that here, I will move the PR to staging since it hasn't gone in yet: https://github.com/StrangeLoopGames/Eco/pull/3393

**Comment by johnkslg** [comment]
Fixed by marjie
