### ISSUE TITLE
Player can't connect to our server anymore

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9397]
Crosslinking this issue placed in the suggestions: https://github.com/StrangeLoopGames/EcoSuggestions/issues/578

It's my server. He is admin on my server. He played there for ages. It's online. Other people are online. WTF.

**Comment by Nicolausi113** [comment]
If it is this one, I could login, but very bad performance and no ping time shown.
![godsofwar](https://user-images.githubusercontent.com/38510829/45609101-c16e8680-ba56-11e8-91ea-bc00d532771c.jpg)

**Comment by D3nnis3n** [comment]
For me and the others it works well. Where are you from? Server is in Finland.

**Comment by D3nnis3n** [comment]
Well, i'm from bavaria so that should be okay. Why the ping is not shown - no idea. 
<img width="1188" alt="worksforme" src="https://user-images.githubusercontent.com/25908592/45620554-a105f280-ba7d-11e8-9992-73de6ee071c0.png">

**Comment by D3nnis3n** [comment]
This is still the case for him and i don't have any idea why.

**Comment by Nicolausi113** [comment]
Guessing this was not meant for me, I’d like to help you guys but I even have no clue.
Possibly it could be helpful to attach the file output_log.txt located in %appdata% in case exceptions were throne.

**Comment by D3nnis3n** [comment]
This problem is fixed, but the reason still unknown. Our firewall configured to migitate several kinds of attacks blocked some players. Did not even think of this being possible so i did not look. I changed it a bit and hope this will not happen again, but if it does, i at least know, where to search. I'll close this issue therefore as it probably has nothing to do with the game at all. Sorry for using your time! :(
