### ISSUE TITLE
The tool swap animation is not working properly when moving.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9398]
Description: If the player tries to swap tools when moving around, the animation is not appearing to be working as intended.

STR:
1. Start the game.
2. Create/join a world.
3. Set some tools in the quick-slot.
4. Have the player move around and start swapping tools.
5. Observe the animation issue.

Actual Result: The tools swapping is not properly animating when the player is moving around.

Expected Result: The tool swapping animation should be smooth when moving around as well.

Video Link: https://www.dropbox.com/s/3qa84m06soztat9/Unity%202018.2.3f1%20Personal%20%2864bit%29%20-%20Game.unity%20-%20Client%20-%20PC%2C%20Mac%20%26%20Linux%20Standalone%20_DX11_%2017-09-2018%2015_10_51.mp4?dl=0

**Comment by SeanAtr0n** [comment]
fixed 8.2
