### ISSUE TITLE
Able to use tool even after it has reached its usable limit.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9399]
Description: The user is able to continue using the mining tool even after it has reached its limit and needs to be repaired.

STR:
1. Start the game.
2. Create/Join a world.
3. Select a tool and start utilizing it. (Mining tool was used for me)
4. Once it has reached its limit, (highlighted with red tone) continue using it.
5. Observe that the user is able to use it indefinitely.

Actual Result: The user is able to use the tool indefinitely even after it has reached its limit.

Expected Result: The player should get an error response when trying to use the tool that has reached its limit or it should break after some usage.

Video Link: https://www.dropbox.com/s/cdi7yxbj7rntzum/Unity%202018.2.3f1%20Personal%20%2864bit%29%20-%20Game.unity%20-%20Client%20-%20PC%2C%20Mac%20%26%20Linux%20Standalone%20_DX11_%2017-09-2018%2015_34_27.mp4?dl=0

**Comment by Nicolausi113** [comment]
It’s intended, but consumes more calories if using worn out tools. I’ve read it somewhere but can’t find it yet.

**Comment by vigneshjuego** [comment]
It mentions that the efficiency of the product will be reduced but there appears to be no difference even after the tool has reached its usage limit.

**Comment by Nicolausi113** [comment]
Calorie consumption is 5 times higher.
![calories2](https://user-images.githubusercontent.com/38510829/45639359-15598980-bab0-11e8-8eaa-b2a70e6ee08c.jpg)

**Comment by BlazeGuy2** [comment]
Broken tools working as intended.
