### ISSUE TITLE
USER ISSUE: Wheelbarrow in cave

### ISSUE THREAD

**Issue by ToG-128** [StrangeLoopGames/EcoIssues#9401]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
take a wheelbarrow down a single block wide tunnel without ramp. Attempt to build ramp under wheelbarrow.  attempt to move wheelbarrow. 

**Expected behavior:**
slim hope my mistake was correctable

**Actual behavior:**
stuck in wall multiple times until unable to be unstuck... To be expected really.

**Do you have mods installed? No 
Does issue happen when no mods are installed?:** yes
stuck in wall multiple times until unable to be unstuck... To be expected really.

**Comment by SeanAtr0n** [comment]
fixed
