### ISSUE TITLE
Once a crafting has started, there is no option to cancel.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9402]
Description: Once the player has set any projects for creation in the campsite, there is no option to cancel it. There is also no mention that shown anywhere that it can be cancelled.

STR:
1. Start the game.
2. Create/Join a world.
3. Place a campsite and start a project in it.
4. Observe that the project cannot be cancelled once started.

Actual Result: The project cannot be cancelled once started.

Expected Result: There should be an option to cancel the project or there should be warning message shown somewhere before starting a project that once started, it cannot be cancelled.

Screenshot:
![03677a78-942e-4a25-b81e-5331dbee7c0f](https://user-images.githubusercontent.com/43132426/45619506-1e8a2c80-ba97-11e8-8525-c4a7cb4ed371.png)

**Comment by TheeJudge** [comment]
While not explained and maybe that is the real issue here. Can you not left click/right click (forget which it is) the project and cancel it that way?

**Comment by vigneshjuego** [comment]
Yeah, i am able to cancel it by right clicking on the icon of the ongoing production and then cancel it. Can this be shown somewhere?
