### ISSUE TITLE
When trying to set the roof option on top of the wall edges, it is not responding properly.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9403]
Description: The user is unable to detect the roof option on top of a wall. The cursor is not accurately detecting the option of placing a roof on top of the wall.

STR:
1. Start the game.
2. Host/Join a world.
3. Harvest some log and produce some hewn log.
4. Select the hammer tool and start constructing a wall. 
5. Try to project the cursor when the hammer is selected with the roof option, on top of a wall.
6. Observe that the roof is not properly being detected.

Actual Result: The cursor is not accurately detecting the placement of roof.

Expected Result: The cursor should accurately show where the roof or other options available can be placed.

Video Link: 
https://www.dropbox.com/s/3zq5yl2ex7zklhq/Unity%202018.2.3f1%20Personal%20%2864bit%29%20-%20Game.unity%20-%20Client%20-%20PC%2C%20Mac%20%26%20Linux%20Standalone%20_DX11_%2017-09-2018%2017_14_27.mp4?dl=0

**Comment by Conchipedia** [comment]
works fine in 1st person view, not sure why you are doing things in 3rd person as its the hardest thing ever to play like this

**Comment by SlayksWood** [comment]
Have same behavior in 0.9.0. But we still need some improvements: #13110
merged to #13110
