### ISSUE TITLE
If the player clicks and holds the scythe tool, the animation stops.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9404]
Description: The sythe useage animation stops working if the user clicks and holds the left mouse button when a scythe tool is selected. 

STR:
1. Start the game.
2. Create/Join a world.
3. Obtain the scythe tool.
4. Select it and click and hold the left mouse button.
5. Observe that the animation only plays the first time.

Actual Result: The animation is not looping if the player clicks and holds the left mouse button with the scythe tool selected.

Expected Result: The scythe animation should loop when the left mouse button is click and held.

Video Link:
https://www.dropbox.com/s/876xyhiq97guiyp/Unity 2018.2.3f1 Personal (64bit) - Game.unity - Client - PC%2C Mac %26 Linux Standalone _DX11_ 17-09-2018 18_01_04.mp4?dl=0

**Comment by SlayksWood** [comment]
move to #11861
