### ISSUE TITLE
Link to show Change list is broken on website

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9405]
When going to this page
https://www.strangeloopgames.com/eco-7-7-is-live-loans-bonds-recommended-servers-story-sequence-and-more/

when you get to bottom part there is a link to show Complete Change list
![snap2863](https://user-images.githubusercontent.com/29383891/45623651-f216e600-ba7f-11e8-899e-dbf5d9faac49.png)
when clicked on it goes to
http://click.mailerlite.com/link/c/ 
and shows this
![snap2864](https://user-images.githubusercontent.com/29383891/45623695-15da2c00-ba80-11e8-92dd-344a46516213.png)

**Comment by rainfarmer** [comment]
old blog with broken link. old blog will be removed with site redesign anyway
