### ISSUE TITLE
Issue with collision. Carts and powered vehicles.

### ISSUE THREAD

**Issue by Knigge** [StrangeLoopGames/EcoIssues#9406]
When traveling with carts, trucks and other powered machines there will be collisions with animals. Now this results in a spectacular show of force by nature - and the consequences are vehicles launched into lower earth orbit. Could Eco instead drain energy while also killing the animal. Eg. if hitting a deer while pulling cart - drain x amount of energy from the character, and while hitting it in a powered vehicle - drain y amount of energy from the engines stored energy or load.

**Comment by SlayksWood** [comment]
Now vehicles don't collide with animals. Fixed.
