### ISSUE TITLE
When a player plants some crops, it is not properly visible.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9407]
Description: When the player has planted some crops (Beet seeds, fireweed seed etc) are either not visible or only visible when nearby.

STR:
1. Start the game.
2. Create/Join a world.
3. Use the hoe tool and till the land.
4. Obtain some seeds (beet seed or fireweed seeds) and plant them in the tiled field.
5. Observe the visibility issue.

Actual Result: The seeds are not properly visible when planted or only visible when very close by.

Expected Result: The planted fields should appear to be used visually, in-case if the seeds are not visible unless properly grown.

Screenshots:
![18835bce-e49d-4a19-a2a5-1fedc015587d](https://user-images.githubusercontent.com/43132426/45626907-518bea80-baae-11e8-951e-fcc30ac96632.png)
![c9177d45-d17f-4959-b08b-d73471de5f5c](https://user-images.githubusercontent.com/43132426/45626908-518bea80-baae-11e8-833e-d0e7e2de4127.png)
![f73a4e62-5eef-4ad9-a397-c34fef17910b](https://user-images.githubusercontent.com/43132426/45626909-518bea80-baae-11e8-860d-44ed0b496754.png)
![fa3e8a15-3fde-4280-9751-ab088ccb54cd](https://user-images.githubusercontent.com/43132426/45626910-52248100-baae-11e8-838d-7b71b0bd1c33.png)

**Comment by Conchipedia** [comment]
probably because you are in 3rd person view all the time, its the hardest way to see things or gauge distances to do things with

**Comment by SlayksWood** [comment]
Checked on 0.8.3.0 staging-1066. Wasn't able to reproduce:
![image](https://user-images.githubusercontent.com/45708377/62517602-655c4e80-b830-11e9-9417-722882fbc601.png)
Maybe you set low foliage quality?
![image](https://user-images.githubusercontent.com/45708377/62517699-99377400-b830-11e9-98ce-843e8ef591b7.png)
![image](https://user-images.githubusercontent.com/45708377/62517647-7c9b3c00-b830-11e9-90d8-6d1db59077c6.png)
Closed for now.
