### ISSUE TITLE
USER ISSUE: не работает

### ISSUE THREAD

**Issue by vbif123** [StrangeLoopGames/EcoIssues#9410]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Could not create save file: Access to the path "C:/Program Files (x86)/ Eco/Eco_Data\Server\Storage\DefaultWorld" or "C:/Program Files (x86)/ Eco/Eco_Data\Server\Storage\12356789.eco" is denied.
```

**Comment by elfl0rd** [comment]
Обнови игру, в новой версии исправлено.

Fixed in newest releases.

**Comment by BlazeGuy2** [comment]
Reopen if this occurs for you again on 7.7.2
