### ISSUE TITLE
The chainsaw animation is not working in third person view

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9411]
Description: When the user uses the chainsaw in first person view, it is working as intended where as when using it in third person view, there is no animation displayed for the chainsaw.

STR:
1. Start the game.
2. Create/Join a world.
3. Obtain a chainsaw.
4. Select the left mouse button in first person shooter and observe that the animation is working as intended.
5. Switch to third person view and observe that the animation is not working.

Actual Result: The chainsaw animation is not working in the third person view.

Expected Result: All the tool's animation should work as intended in both the first person and third person views.

Video Link: 
https://www.dropbox.com/s/mwmph7s993skhd1/Unity 2018.2.3f1 Personal (64bit) - Game.unity - Client - PC%2C Mac %26 Linux Standalone _DX11_ 17-09-2018 22_38_05.mp4?dl=0

**Comment by SlayksWood** [comment]
0.8.1.4 Animation available
