### ISSUE TITLE
Buy and Sell actions: Add more parameters

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#9412]
Namely 'currency' and 'cost'

**Comment by Deantwo** [comment]
Maybe also a way to see if the store belongs to the government?

**Comment by MarjieAVolk** [comment]
You should be able to do that already, eg. 'when attempting to buy/sell, if you are the world leader [...]'

**Comment by MarjieAVolk** [comment]
Is that new in my PR?  I can't even remember what I have been doing all this time.

**Comment by Deantwo** [comment]
No I mean the other other way around.
Want to know if the owner of the property that the store is on belongs to the government.

At least I am assuming that the "buying" and "selling" laws are seen in context of the player interacting with the store. Is it from the point of view of the store?

Maybe rename the "buy" and "sell" to "buy from store" and "sell to store" so it is more understandable.

**Comment by MarjieAVolk** [comment]
When you buy from a store, the law gets checked once for yourself buying, and once for the store (that is, the store owner) selling.  Same with selling (but inverted).  So both.

**Comment by Deantwo** [comment]
Oh my... that is even more confusing to use than I thought then. Would be nice if those were separate.

- Sell to store
- Buy from store
- Store buying
- Store selling

**Comment by Deantwo** [comment]
But if the action is checked in both ends with a simple "sell", how would you allow selling but not buying in a specific district? I have had people ask about this.

**Comment by MarjieAVolk** [comment]
Ah, hmmm that is a good point.

Well, it's a little convoluted, but you could use 'on own property' to do it.  The store will always be on its own property, and the player will not.

**Comment by Deantwo** [comment]
Or a where condition to indicate the direction?
"Shopper" and "Store owner"
I mean it needs to be understandable by the average player. So either separate them or add a where condition likely that.

**Comment by D3nnis3n** [comment]
Probably this can be done with upcoming government property and bank accounts? It seemed like it would be possible to do government shops and contracts with it and you could check if its on a property owned by government?

**Comment by Binarymort** [comment]
The difficulty here is understanding the focus, for example if I use a clause "When attempting to Buy where item (is aThing) allocate 0.3 Bucks" the buyer has triggered this clause so logically it would seem that the buyer should receive Bucks, This is not the case, any subsequent comparisons using "your" or "allocate" commands are put against the store owner.

**Comment by Deantwo** [comment]
Addition to this, options for "Any Credit" and "Any Minted Currency". I guess only one is needed since we can do "Not Any Credit".

**Comment by D3nnis3n** [comment]
Adding this to my list and giving it high priority as i heard many requests of players wishing to control the economy more - which should definatley be in the scope of the game.

**Comment by F3UR10** [comment]
is there still any progress on this task?

**Comment by johnkslg** [comment]
Lots more context for you now:
![image](https://user-images.githubusercontent.com/3536496/68906239-84ecf800-06f8-11ea-872c-97d66e290695.png)
![image](https://user-images.githubusercontent.com/3536496/68906251-8a4a4280-06f8-11ea-819c-ca314a735db9.png)
![image](https://user-images.githubusercontent.com/3536496/68906261-91715080-06f8-11ea-9a60-4cf8e7e489cd.png)

Go nuts!

**Comment by D3nnis3n** [comment]
Keeping open, i have test sessions with community members open for the law issues that were assigned to me. Dont close them

**Comment by WeaselDog** [comment]
I tested all the values from trade and they work now.
