### ISSUE TITLE
When the backpack is removed from being equipped, the equipment are appearing to hanging in air.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9414]
Description: If the user removes the backpack from the equipment and has some set of tools that is swapped, it is appearing to be odd and floating in air instead of being attached to the player.

STR:
1. Start the game.
2. Create/Join a world.
3. Open the backpack by selecting the B button.
4. Remove the backpack from the equipment and put inside the backpack.
5. Switch tools and observe the issue.
6. For better view, select the edit button in the backpack and rotate the view to see the issue.

Actual Result: The tools are appearing to be floating instead of being attached to the player.

Expected Result: The tools could not be displayed if the backpack is removed or the tools can be placed close the player when the backpack is removed.

Screenshots:
![2](https://user-images.githubusercontent.com/43132426/45683260-a6883900-bb60-11e8-8727-f7183901809b.png)
![3](https://user-images.githubusercontent.com/43132426/45683261-a6883900-bb60-11e8-944e-42ba96bf2a14.png)

**Comment by SlayksWood** [comment]
merged with #12382
