### ISSUE TITLE
When the player selects the land claim stake in third person view, it is showing a hammer.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9416]
Description: If the player selects the land claim stake in third person view, it is showing a modern hammer where as when seen through first person view it is showing the stake.

STR:
1. Start the game.
2. Create/Join a world.
3. Obtain all the basic tools and place it in the quickslot.
4. Switch to third person view and select the land claim stake.
5, Observe the issue, now revert back to first person view and observe that it is working as intended.

Actual Result: The hammer is appearing in third person view for selecting land claim stake.

Expected Result: Both the hammer and the land claim stake should appear individually in each hand when in third person view.

Screenshots:
![6](https://user-images.githubusercontent.com/43132426/45684061-d2a4b980-bb62-11e8-8fad-468c5b0f912f.png)
![7](https://user-images.githubusercontent.com/43132426/45684281-6e362a00-bb63-11e8-89f4-a7f29281d47c.png)
![8](https://user-images.githubusercontent.com/43132426/45684286-71c9b100-bb63-11e8-81b3-5577df045e76.png)

**Comment by SeanAtr0n** [comment]
duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/8475
