### ISSUE TITLE
Only some tools are appearing in the backpack.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9417]
Description: When the player has set all the tools in the quickslot and keep swapping them, only certain tools are visually appearing to be held on the player.

STR:
1. Start the game.
2. Create/Join a world.
3. Get all the basic tools used in the game and place them in the quickslot.
4. Keep selecting them one by one and observe the issue.

Actual Result: Only tools like"Axe, stone hammer, wooden shovel and bow" is appearing to be visually held.

Expected Result: All the tools kept by the player in the quickslot, when not selected can be visually displayed as being held by the player.

Video Link: 
https://www.dropbox.com/s/cik5f0plnw1c8i0/Unity%202018.2.3f1%20Personal%20%2864bit%29%20-%20Game.unity%20-%20Client%20-%20PC%2C%20Mac%20%26%20Linux%20Standalone%20_DX11_%2018-09-2018%2016_52_08.mp4?dl=0

**Comment by SeanAtr0n** [comment]
fixed a while back
