### ISSUE TITLE
If the view is switched from thirst person to first person and reverted back, the tools displayed disappears.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9418]
Description: If the user has some tools displayed visually in the third person view, if the player toggles the first person view and back to third person view, unless an equipment is selected the disappeared items will not appear.

STR:
1. Start the game.
2. Create/Join a world.
3. Have some of the tools placed in the quickslots.
4. Switch the view from 3rd person to 1st person and back to 3rd person.
5. Observe that the disappeared tools appear if a tool is selected.
6. Repeat the same step without any tools selected and observe that the tools are not visually displayed.

Actual Result: The tools visually disappear if the view is toggled.

Expected Result: The tools should be consistently displayed in third person view.

Video Link:
https://www.dropbox.com/s/hvw987mo87ome88/Unity%202018.2.3f1%20Personal%20%2864bit%29%20-%20Game.unity%20-%20Client%20-%20PC%2C%20Mac%20%26%20Linux%20Standalone%20_DX11_%2018-09-2018%2017_04_56.mp4?dl=0

**Comment by BlazeGuy2** [comment]
Video seems to show intended behavior.  User has a tool in 3rd person out, switches to 1st holding tool, then switches back to 3rd person and pulls tool back out again.
