### ISSUE TITLE
The hammer tool when simply selected, is not animating in 3rd person view.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9419]
Description: When the hammer tool is selected without any crafting material and the left mouse click is selected and held, it is animating in the 1st person view but is not animating in the 3rd person view.

STR:
1. Start the game.
2. Create/Join a world.
3. Obtain the hammer tool and select it.
4. Switch to 1st person view and click and hold the left mouse button.
5. Observe that it is animating. Now switch to 3rd person view and perform the same action.
6. Observe that there is no animation happening.

Actual Result: The hammer tool is only animating in the 1st person view.

Expected Result: All the tools should work and animate as intended in all the views.

Video Link:
https://www.dropbox.com/s/yk0jlkt20iswzgx/Unity 2018.2.3f1 Personal (64bit) - Game.unity - Client - PC%2C Mac %26 Linux Standalone _DX11_ 18-09-2018 17_26_12.mp4?dl=0

**Comment by SlayksWood** [comment]
Checked on 0.8.3.0 staging-1066. Wasn't able to reproduce. Seems fixed.
