### ISSUE TITLE
When the user tries to equip different costumes, sometimes the user is unable to.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9420]
Description: When the user tries to change a different costume, (Backpack in this case) the description content is appearing when hovering the mouse on the existing costume and once this happens the user is unable to swap them.

STR:
1. Start the game.
2. Create/Join a world.
3. Have two costumes for the same slot.
4. Have one costume equipped and have the backpack opened.
5. Select an drag the other costume on top of the equipped one.
6. Observe that sometimes, the description of the quipped costume is appearing.
7. Now drop the dragged costume into equipment section and observe the issue.

Actual Result: When the description content is appearing, the user is unable to switch costumes.

Actual Result: Either the description should not appear when any content is selected or even if the description is appearing, the content should be transferable.

Video Link: 
https://www.dropbox.com/s/z50501wrrc2eez5/Unity 2018.2.3f1 Personal (64bit) - Game.unity - Client - PC%2C Mac %26 Linux Standalone _DX11_ 18-09-2018 17_47_11.mp4?dl=0

**Comment by SeanAtr0n** [comment]
you dropped it on the tooltip when it failed... might already be fixed by @MarjieAVolk ?

**Comment by MarjieAVolk** [comment]
Yeah I fixed tooltips staying open while dragging a little bit ago (see https://github.com/StrangeLoopGames/EcoIssues/issues/9132)

Are you on the most recent version?
