### ISSUE TITLE
USER ISSUE: Speed skill doesn't work

### ISSUE THREAD

**Issue by crazypete79** [StrangeLoopGames/EcoIssues#9422]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Upgrade speed in the skill tree then look at the crafting times

**Expected behavior:**
Time in the crafting table should be less 

**Actual behavior:**
Time in crafting table is the same as before
**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods

**Comment by Deantwo** [comment]
Would help with an example. Maybe a picture.
What are you looking at specifically that isn't changing?

**Comment by BlazeGuy2** [comment]
Need more information about what recipes are affected by this issue, or we can't fix it.  @crazypete79 can you send images demonstrating this problem?

**Comment by BlazeGuy2** [comment]
Speed works, just doesn't update until reconnecting.

**Comment by SlayksWood** [comment]
merged with #12042 12362
