### ISSUE TITLE
Gain calories while working with efficiency

### ISSUE THREAD

**Issue by TheeJudge** [StrangeLoopGames/EcoIssues#9424]
A player on my server maxed out his calorie efficiency. As a result he has started to gain calories from working. This has allowed his calories to go above the limit. It has also made it so that he can't eat and now gets only 12 skill points a day when he should be getting much more with food available.

https://cdn.discordapp.com/attachments/416034541115801612/491654250426793985/Eco_9_18_2018_10_47_20_AM_2.png

Hard to see but above is an image of him getting +0.04 calories from just existing.

**Comment by TheeJudge** [comment]
So would like to apologize. This is not actually an issue on our server. I mean it was, but not your fault. I totally understand modifications and how errors shouldn't be reported on servers of this sort. I try to be very careful to look at everything before posting issues. I, however, was not in the loop on a change that was made to the 'Calore Efficiency' skill. This change in percentage to 85 percent combined with another to bring it over 100% causing the issue of gaining vise losing.

Again I apologize for bringing up an issue that was our fault. I will be more careful in the future. 😄

**Comment by D3nnis3n** [comment]
Closed for Third-Party-Issue.
