### ISSUE TITLE
Changing languages breaks currencies

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9425]
Currencies are localizing the names of players (It gibberishified my name in the currency name field) and changing the language makes them invalid and not found, causing exceptions. 

Should store a separate string for the display name of currencies, so the currency name (which is currently used as both an identifier and a display string) is never localized and never changes.

**Comment by johnkslg** [comment]
Currency names are assigned by the user and should never be localized.  So, just need to make sure theyre never called by the localizer.  You can verify this by making sure that currency names added to the game never become part of the string table after load reset.

**Comment by Spydarlee** [comment]
Did some testing and this seems to be working as expected now. No attempts at translating currency names, nor any exceptions resulting therefrom!

**Comment by elfl0rd** [comment]
Just change _server_ lng on for existing world.
It make 2 currency for you, lol.
![default](https://user-images.githubusercontent.com/4980243/51346012-93a15900-1aad-11e9-8407-adc789747ef3.png)
