### ISSUE TITLE
Flat steel does not connect to dirt

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9426]
See the picture
<img width="1301" alt="steel" src="https://user-images.githubusercontent.com/25908592/45752100-b5c8be80-bc14-11e8-92dd-bf08e34e13fa.png">

**Comment by elfl0rd** [comment]
dupe - https://github.com/StrangeLoopGames/EcoIssues/issues/8441

**Comment by keegan-o** [comment]
Fixed in master.
