### ISSUE TITLE
Framed Glass is a X-Ray Device

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9428]
See screenshot, there is only ONE framed glass block. the rest is dirt road and the house. You can see inside.
<img width="1481" alt="xray" src="https://user-images.githubusercontent.com/25908592/45753109-04c42300-bc18-11e8-8d9a-c18469c25fb3.png">

**Comment by SlayksWood** [comment]
merged with #11814
