### ISSUE TITLE
Opening the chat should disable the controls

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9429]
At the moment, when chatting while in a car, pressing S will make you go backwards and so on - probably these keys should not work while in chat so you don't drive off a bridge just because of chatting. Which happened … quite often :D

**Comment by D3nnis3n** [comment]
I would like to add on this, that sometimes it even happens that you can open e.g. the currency menu when typing a y. I could not yet really reproduce this issue, but i try to get more information on that.

**Comment by redwyre** [comment]
@D3nnis3n menus coming up is a separate issue (might have also just been lag?)

**Comment by D3nnis3n** [comment]
I didn't experience that since the lag issues got a bit better, so probably that was it. Could somehow ensure that this doesn't happen nayway if possible.
