### ISSUE TITLE
Chunk Blocks / Loosing Collision

### ISSUE THREAD

**Issue by shortybsd** [StrangeLoopGames/EcoIssues#943]
When walking in front of the house you will fall through the ground. You can control while falling (moving to a non glitched block) so you can land. Also if you walk inside the house you will hit those glitched blocks. 
A player said the issue went away when he took off part of the top floor so building height might seem to be the issue.
Game.eco - http://www.shortybsd.org/eco/Game.eco

**Comment by noblackthunder** [comment]
closing this since its a dublicate to issue 919 .. linked this to that issue

**Comment by noblackthunder** [comment]
@shortybsd could you add where the chunks are that had no collision so eric can find it easier?

**Comment by shortybsd** [comment]
Sorry about that - 716, 56, 498
