### ISSUE TITLE
Play Time for Server-matches can’t be set as supposed

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9430]
Version v0.7.7.2-beta
How to set these yellow “Sometimes”?
And typo findings.
![playtime2](https://user-images.githubusercontent.com/38510829/45755812-a4d17a80-bc1f-11e8-96ed-e1e5440bc634.jpg)

**Comment by BlazeGuy2** [comment]
Sometimes is set by the middle mouse button.

**Comment by Nicolausi113** [comment]
Yes, that works, I didn't realize that small middle button – Thanks.
The issue may be closed then.

**Comment by johnkslg** [comment]
@MilenkoTunjic can make the middle button more clear?

**Comment by Nicolausi113** [comment]
A little wider and yellow colored I would suggest

**Comment by SlayksWood** [comment]
typo findings in 0.8.1.3 
![image](https://user-images.githubusercontent.com/45708377/56359477-5a7e9f00-61ea-11e9-9ba2-0e03e617e25a.png)
