### ISSUE TITLE
Few graphical corruption were observed in the objects.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9431]
Description: While validating if all the objects are looking properly, below are some of the issues observed.

![9](https://user-images.githubusercontent.com/43132426/45760523-e4ac5800-bc47-11e8-90f4-8b7d412f144b.png)
![10](https://user-images.githubusercontent.com/43132426/45760524-e4ac5800-bc47-11e8-97ff-1ae418d71df9.png)
![11](https://user-images.githubusercontent.com/43132426/45760526-e4ac5800-bc47-11e8-93a3-236f390426dc.png)
![13](https://user-images.githubusercontent.com/43132426/45760527-e4ac5800-bc47-11e8-860c-3b30ff9b4fdc.png)
![14](https://user-images.githubusercontent.com/43132426/45760528-e544ee80-bc47-11e8-8dd1-b55420e6737a.png)
![15](https://user-images.githubusercontent.com/43132426/45760529-e544ee80-bc47-11e8-8709-d8c43d466374.png)

**Comment by keegan-o** [comment]
First issue is texture stretching on the mesh, addressing this will be part of updates to block art, second issue is the face remover affecting stone ramp meshes poorly, this has been resolved as well. (It could also be a chunk building issue)
