### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9432]
In the last days we had several server crashes occur out of nowhere with these dumps, i would love to have them fixed :):

CRASH 1
```
 --BEGIN DUMP--
Dump Time
09/19/2018 17:51:46

Exception
Exception: InvalidOperationException
Message:Changes could not be applied, the requested operation would result in an invalid inventory state.
Source:Eco.Gameplay

System.InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state.
   at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
   at Eco.Gameplay.Items.Inventory.Modify(Action`1 callback, User user)
   at Eco.Gameplay.Items.WorkOrder.TryToContributeItems(User actor, Inventory inventory)
   at Eco.Gameplay.Components.CraftingComponent.AddResourcesToWorkOrders(User owner, User actor, Inventory source)
   at Eco.Gameplay.Components.CraftingComponent.FindAndAddResourcesToWorkOrders(User actor)
   at Eco.Gameplay.Components.CraftingComponent.Tick()
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

--END DUMP--
```
CRASH 2
> --BEGIN DUMP--
> Dump Time
> 09/17/2018 10:57:59
> 
> Exception
> Exception: NullReferenceException
> Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
> Source:Eco.Gameplay
> 
> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>    at Eco.Gameplay.Components.VehicleComponent.Tick()
>    at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
>    at Eco.Gameplay.Objects.WorldObject.Tick()
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
> 
> --END DUMP--

We also got quite a lot of these dumps here:
ClientReceiveException TargetInvocationException 09170758

> --BEGIN DUMP--
> Dump Time
> 09/19/2018 13:37:54
> 
> Exception
> Exception: NullReferenceException
> Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
> Source:Eco.Core
> 
> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>    at Eco.Core.Serialization.ZipBlob.Delete()
>    at Eco.Gameplay.Objects.EcoObjectManager.Remove(IEcoObject ecoObject)
>    at Eco.Gameplay.Objects.RubbleObject`1.TryPickup(Player actor, Inventory inv)
>    at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
>    at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
> 
> --END DUMP--
>

**Comment by D3nnis3n** [comment]
I upload you all of them, here: 
[dumps.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2398417/dumps.zip)

**Comment by craig-jong** [comment]
I know this is kinda of late, but can you provide any extra information on what you were doing when these exceptions occurred?

**Comment by D3nnis3n** [comment]
Unfortunatley not. It's not even a long time ago, it also happened while i was not there (we got autorestart activated), so i just thought i give you all those crash reports in the hope you could probably find out what is wrong and fix at least some of them.

**Comment by D3nnis3n** [comment]
Here are some more dumps since then:
[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2489643/Dump.zip)

If they do not really give you information you should either stop creating them at all or give them more information. I can't be online all day to get to know every crash, that's why i made the server a service that autorestarts.

**Comment by johnkslg** [comment]
@D3nnis3n is this still an issue?

**Comment by D3nnis3n** [comment]
None of these issues occured again since then.
