### ISSUE TITLE
USER ISSUE: Can't connect

### ISSUE THREAD

**Issue by Irishghostgirl** [StrangeLoopGames/EcoIssues#9434]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1)Attempt to join server
2)Sit and watch the wheel turn.

**Expected behavior:**
Should have joined the server

**Actual behavior:**
The following error message popped up:
`Connection Failed`` In the server GUI, it shows up as "newclient" and will not let me load in.  Multiple attempts needed to get in
**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods

**Comment by elfl0rd** [comment]
Still happens on latest version?
