### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by Hexamentia** [StrangeLoopGames/EcoIssues#9437]
server is active and i can see 11/256 players online. talking in discord to confirm players are online.   

click join..
connecting...

time out.

things I know:

most players can connect
specific players including myself cannot join
a server reset resolves the issue
when viewing the server from the worlds menu, ping is a " - "
the server cant see me try to join

here's the thing:

<size=150%>Connection Failed</size>

Failed to connect - connection timed out.

Log File:
Initialize engine version: 2018.2.0f2 (787658998520)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 970 (ID=0x13c2)
    Vendor:   
    VRAM:     4043 MB
    Driver:   23.21.13.9124
Begin MonoManager ReloadAssembly
- Completed reload, in  0.283 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.949853 ms
Client version: 0.7.7.2 beta
Tuesday, September 11, 2018 12:08 PM
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

**Comment by BlazeGuy2** [comment]
@Hexamentia Need the server's IP address.

**Comment by D3nnis3n** [comment]
No answer to Information request in 14 days, reopen if issue persists.
