### ISSUE TITLE
USER ISSUE: white squares in new game screens.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9438]
**Version:** 0.7.8.0 beta staging-b7709677
![20180920094450_1](https://user-images.githubusercontent.com/4980243/45800577-00e8dd00-bcba-11e8-8501-9764ea7c076c.jpg)
![20180920094447_1](https://user-images.githubusercontent.com/4980243/45800578-00e8dd00-bcba-11e8-826d-5c4b2d83d47b.jpg)

**Comment by Spydarlee** [comment]
Also happening on master so submitted a fix there, will need to pull over to staging afterwards.

**Comment by johnkslg** [comment]
Great, yes can you go ahead and redo the fix in staging?  We dont pull from master to staging (only from staging to master, and if theres a prefab conflict we have to redo it)

**Comment by Spydarlee** [comment]
New pull request submitted for staging, and I've updated the previous pull request with an updated post-merge fix for master, too.
