### ISSUE TITLE
Loc. strings is not used or\and duplicated.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9439]
**Version:** 0.7.8.0 beta staging-b7709677
![default](https://user-images.githubusercontent.com/4980243/45800841-ccc1ec00-bcba-11e8-823a-c10151b9963c.png)
https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#49363
https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#51423
@Nanders

**Comment by Nanders** [comment]
This is because the tutorial text serializes with the tasks themselves. If you restart the tutorial you should see that it displays in the correct language

**Comment by elfl0rd** [comment]
yep, my bad... but dupe still possible :P
