### ISSUE TITLE
Chair cause server crash 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#944]
http://ecoforum.strangeloopgames.com/topic/1250/client-chair-placement-causing-server-softwater-to-crash-to-desktop

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/1243/server-crashing-when-certain-people-connect

**Comment by midn8t** [comment]
[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/681444/Dump.zip)


my dump for the server has about 15 or so crash files in it.

**Comment by noblackthunder** [comment]
Btw this might already be possible fixed in the next server version!

**Comment by midn8t** [comment]
just thought i share the dump files... took me for ever get winzip on here usually use winrar... there is anther guy having crashes to desktop when clients connect I had that issue also, with other clients connecting right away it would crash, - I think might be related but not sure, my girl friend had a rabbit she picked up off of the game world or something like that anyways it gave her exception error and crashed client when she tried connect to server whole server would crash to the desktop but only after that item went into her inventory.

**Comment by shortybsd** [comment]
midn8t, I suggest you try 7zip. It replaced my paid versions of WinZip and Winrar. By far the best compression tool I have used. I even have the command utility that my rack servers run in background via crontab event to auto zip/backup certain programs and data.

**Comment by midn8t** [comment]
ill give it shot - anyways update on this i cant run server any more it crashes to desktop every time i log in now

**Comment by midn8t** [comment]
[Dump01-03-17.zip](https://github.com/StrangeLoopGames/EcoIssues/files/682590/Dump01-03-17.zip)

**Comment by shortybsd** [comment]
Also grab Notepad++ then you can simple right click on all those dump files to view them. I see most of your errors are 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary. and
Eco.Gameplay.Items.InventoryException: Cannot remove item from inventory which does not contain it.

**Comment by shortybsd** [comment]
System.NullReferenceException: Object reference not set to an instance of an object.
They need more debugging for the Roomchecker function with an if check which will cease these common erros

**Comment by midn8t** [comment]
yah I have no idea what any of that means but they are created every time the server crashes which is every time i try to join it now.

**Comment by shortybsd** [comment]
The new version fix you up brother?

**Comment by midn8t** [comment]
i had wipe game world and start it over so see how this works

**Comment by shortybsd** [comment]
Did you convert the world or perform the world conversion? I can help you with that if needed if Game.eco is provided. Also try looking here http://ecoforum.strangeloopgames.com/topic/1263/alpha-5-2-released under the section labeled Migrating prior save files. You may be able to recover your old world file. :)

**Comment by midn8t** [comment]
well we also wanted a smaller world and we figured out how to get the world to populate correctly at smaller sizes so we made a 60 by 60 world the default seed is 0 but the game does not populate anything correctly below 100 by 100 whit that seed number so we played with the seed numbers till we found number that worked with 60 by 60

**Comment by MarjieAVolk** [comment]
I am going to close this issue as there is way too much going on in here, some or all of which may already be fixed in 5.5.  Please keep issues to one topic, and don't use issues for chatting.
