### ISSUE TITLE
Selling a Deed does not trigger a claim action

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9444]
When you sell a deed at an Real Estate Table this does not trigger a claim action, what makes this law impossible:

We got a capital district where all plots are claimed by me as only administrators can claim there. I sell deeds for the capital. We provide ("abusing" the "stealing" feature) electricity by the government for the complete capital and want to tax players having property in the capital for the electricity. This could work, if i could use a law clause like

"if in district Capital, condition where your claimed property - your unclaimed property > 1 then tax 50 Dollars".

This is not possible as of now, as the the deed sale does not trigger a claim action - we tested that by selling the deed and seeing if the buying player has to pay a tax (as we got a property claim tax) - but no tax was triggered.

The behaviour it should have is that it trigger as much claim actions for the buyer as he got claims in the new deeds and also triggers as much unclaim actions on the seller as the deed had claims.

**Comment by D3nnis3n** [comment]
Another, even better solution would be to implement "Sell Deed" and "Buy Deed" stats, as this would also allow to tax the sales of deeds in at least someway as the treasury unfortunatley has no tax for this and no tax is applied to the sale.

**Comment by johnkslg** [comment]
Pushing from this milestone to next

**Comment by Deantwo** [comment]
While a `Sell deed` and `Buy deed` statsic would be nice, it should probably still do the `Claim` and `Unclaim` actions so `(Claim actions - Unclaim actions)` is still equal to number of claims the player has.

But really a way to count current number of claims rather than reliying on action counts would be nice. Since the action counts can quickly become unreliable.

**Comment by D3nnis3n** [comment]
Adding this to my list as it prevents laws to be made that govern areas with cities where plots must be bought - which is quite a nice game possibility.

**Comment by Deantwo** [comment]
Would be nice if admin uncliming commands also gave `unclaim` actions to the plot's owner.
I'll bug report it separately.

**Comment by Deantwo** [comment]
Should this issue maybe get a law label?

**Comment by D3nnis3n** [comment]
Can be pushed if there is a "owns property" clause.

**Comment by johnkslg** [comment]
How about a Property Transfer action
- Triggers when a deed is sold via realestate desk
- Triggers when a deed is transferred via the transfer dialog in the deed itself. 

And while we're at it, a 'Transfer Money' action that is triggered when the transfer money dialog is used. 

These are easy enough they could go into 9

**Comment by Deantwo** [comment]
@johnkslg, as long as we got an option for getting the count of claims a player has, it doesn't matter too much what the action is for transferring deeds.

**Comment by beastyn** [comment]
Didn't work. 
The law like this
![bandicam 2019-12-16 15-54-55-911](https://user-images.githubusercontent.com/27898520/70901380-79a12b00-201c-11ea-90ce-c11cabc9860b.jpg)

Tax won't be collected
Seems like cliam action won;t trigger
![bandicam 2019-12-16 15-36-06-759](https://user-images.githubusercontent.com/27898520/70901575-e0bedf80-201c-11ea-9221-315c48905a65.jpg)
![bandicam 2019-12-16 15-36-13-128](https://user-images.githubusercontent.com/27898520/70901577-e1577600-201c-11ea-8ace-474a211af3f8.jpg)

**Comment by olegshegai** [comment]
Yeah, taxes are in my today's list
About the trigger - I added a couple of new which were requested by John above.

**Comment by SlayksWood** [comment]
It doesn't work for real estate desk: not "transfer property" trigger, not "claim" trigger.

**Comment by olegshegai** [comment]
![image](https://user-images.githubusercontent.com/56091594/72163807-8f183380-33d5-11ea-992b-7e1626328c09.png)

**Comment by beastyn** [comment]
How can I dustinguish selling and buying person?
If I want to tax the one who is buying and pay to the one who is selling?

**Comment by olegshegai** [comment]
> @beastyn 
> How can I dustinguish selling and buying person?
> If I want to tax the one who is buying and pay to the one who is selling?

`PropertyTransfer` has `CurrentOwner` and `NewOwner` fields. But for taxation it's better to track `TransferMoney` action with its `CurrencyAmount` and other financial information. Should be something like this:
> On `TransferMoney` where `Reason` is `DeedSales`
> tax `Citizen` 
> pay `Receiver`
