### ISSUE TITLE
The game crashed when trying to re-launch the build in unity.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9446]
Description: The game crashed when the game was closed and re-opened in unity. The screenshot is displayed below to show the cause of the 
![screenshot 444](https://user-images.githubusercontent.com/43132426/45821250-564adb80-bd06-11e8-808b-409489ddc5ca.png)
issue.

**Comment by D3nnis3n** [comment]
Old issue.
