### ISSUE TITLE
If the player uses the powered cart and exits it, the player gets stuck in the sitting position.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9447]
Description: When the player tries to ride the powered cart and exits it, the player is visually getting stuck in a seated position.

STR:
1. Start the game.
2. Create/Join a world.
3. Obtain a powered cart and place it.
4. Enter the riders position.
5. Exit the riders position and observe the issue.

Note: This issue is also observed with truck.

Actual Result: The player position is getting fixed to seated position even after exiting the vehicle.

Expected Result: The player position should be reverted back to normal after exiting the vehicle.

Video Link:
https://www.dropbox.com/s/kd1kjrojuhliqka/Unity%202018.2.3f1%20Personal%20%2864bit%29%20-%20Game.unity%20-%20Client%20-%20PC%2C%20Mac%20%26%20Linux%20Standalone%20_DX11_%2020-09-2018%2019_30_03.mp4?dl=0

**Comment by SeanAtr0n** [comment]
This isn't what happens on my screen and my avatar walks around in thirdperson where yours is broken. 

Looks like there are problems with your unity setup, you may need to revert any unintended changes.
