### ISSUE TITLE
When generating the objects, the crane is appearing to have graphical corruption.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9448]
Description: The crane's cable is appearing to be too big and is appearing to be graphically corrupted.

STR:
1. Start the game.
2. Create/Join a world.
3. Have a crane generated and place it.
4. Observe the crane cable issue.

Actual Result: The crane cable is appearing to be graphically corrupted.

Expected Result: There should be no graphical corruption with any of the objects.

Screenshots:
![screenshot 440](https://user-images.githubusercontent.com/43132426/45831285-94eb9080-bd1c-11e8-8463-de263a04f535.png)
![screenshot 441](https://user-images.githubusercontent.com/43132426/45831286-95842700-bd1c-11e8-8147-d00109c90d36.png)
![screenshot 442](https://user-images.githubusercontent.com/43132426/45831287-95842700-bd1c-11e8-93a9-296bc4b79f3d.png)

**Comment by WeaselDog** [comment]
I followed the reproduction steps and I was not able to reproduce. It appears to have been fixed since being reported. Thanks for your contribution.
