### ISSUE TITLE
Skid Steer Backwards driving inverted

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9451]
I really hate skid steer being the only car that when you press S+D drives left and S+A drives right, while with W+D it drives right and with W+A drives left - like any other car. Could that be fixed or is that working as intended?

**Comment by SeanAtr0n** [comment]
It's somewhat intended, but yeah I'm not completely satisfied with the backup behavior either.

**Comment by D3nnis3n** [comment]
Well, it's already hard to steer. It's not making good turn but very fast so you drive of a cliff you want to fill lel.

**Comment by SeanAtr0n** [comment]
real skid steers are also pretty hard to steer... they aren't designed to turn at high speeds so you need to slow down to turn.

**Comment by Aryathal** [comment]
If you really change that, could you give the player an option to set it? I already got used to how the Skid Steer moves backwards.

**Comment by elfl0rd** [comment]
I really like the way Skid Steer moves.
I drove a loader and in eco it is implemented very close to reality!
