### ISSUE TITLE
Trees can grow on stickpiles full of dirt? lel.

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9453]
<img width="1226" alt="treeonstockpile" src="https://user-images.githubusercontent.com/25908592/45843419-dd587d80-bd1f-11e8-8e41-95f8d05e8d4d.png">

**Comment by elfl0rd** [comment]
dupe https://github.com/StrangeLoopGames/EcoIssues/issues/6902

**Comment by D3nnis3n** [comment]
Very old issue though so i wait for someone else to close it if needed.

**Comment by seccombew** [comment]
Dupe
