### ISSUE TITLE
Skidsteers can remove Dirt roads and asphalt roads but no stone roads

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9455]
Seems like a bug to me. Either it should be able to remove stone roads, or it shouldn't be able to remove asphalt roads.

**Comment by elfl0rd** [comment]
As i see, stone and dirt roads can be removed using showel...

**Comment by WeaselDog** [comment]
Stone roads can no longer be removed with a shovel
