### ISSUE TITLE
Pipes should fail if they have no outlet

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9456]
![image](https://user-images.githubusercontent.com/3536496/45844503-7c0cbc00-bcd7-11e8-99b3-449ab9f89abc.png)

**Comment by elfl0rd** [comment]
hmm... as i see - it works logicaly.
pipes have internal space, and fail after he end...

**Comment by johnkslg** [comment]
Yeah this is in master, I updated pipes.  Release is currently working properly.
