### ISSUE TITLE
Weird behaviour with private messages

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9457]
We often miss private messages as sometimes they seem to be shown in general chat and sometimes not. I could not find any way to reproduce when which of this is the case. Most time we don't see them, as they are not streamed in general chat, but sometimes they are. Testing was with no clicking on the private chat channels at all, so we did neither enable nor disable them. Probably worth a look.

**Comment by beastyn** [comment]
There were some updates in chat. Can't reproduce it for 8.2 Feel free to reopen

**Comment by D3nnis3n** [comment]
![chat](https://user-images.githubusercontent.com/25908592/59952986-846c7000-947e-11e9-9870-597a3dcce193.png)
As you can see he sent me three messages, but i only ever saw one in general. In the other chat i need to scroll too much.

**Comment by WeaselDog** [comment]
Fix with https://github.com/StrangeLoopGames/EcoIssues/issues/6759
