### ISSUE TITLE
Server not showing in server browser. 

### ISSUE THREAD

**Issue by Eavrusm** [StrangeLoopGames/EcoIssues#9462]
its been almost 3 days now and my server hosted by kill servers 

23.111.153.26:25200
 Planet harmony.

 stopped showing in the server browser, both in  recommended and in search under browse all. the only way the community can connect is via direct connect with IP.  

Server is set to public. The issued started after the host restarted the OS on the server. I was just on prior and the server was showing. once the restarts completed Myself nor my community were able to see the server in server browser.

Server is public and does not have a password. I also posted this is ECO discord support and no resolution was found. 

We have a very active and growing community. I hope this can be sorted out so we can continue to grow!

**Comment by Eavrusm** [comment]
I have recently found that when preforming a search for the server it will not show but as soon as I hit ESC to go back to the main screen the server shows for a second in the browser before going back to the main screen. I don't know if this helps but I figured id add.

**Comment by mirasrael** [comment]
Hi @Eavrusm Do you still have this problem?

**Comment by Eavrusm** [comment]
this issue was from months ago. it was fixed. we no longer have that server right now. waiting for next update to redeploy. 

Chris P.
parsons.chris85@gmail.com

**Comment by mirasrael** [comment]
Thanks for confirmation @Eavrusm! Closing then
