### ISSUE TITLE
USER ISSUE: No buttons on main screen

### ISSUE THREAD

**Issue by jeezyrae** [StrangeLoopGames/EcoIssues#9463]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Play game	

**Expected behavior:**
Had buttons like play or exit

**Actual behavior:**
No buttonsn
**Do you have mods installed? Does issue happen when no mods are installed?:**
No buttons

**Comment by Nicolausi113** [comment]
“Play” and “Exit” I’ve never seen too, can you add screenshot, or is it like this #5749 ?
![main2](https://user-images.githubusercontent.com/38510829/45884323-e72bc080-bdb3-11e8-9974-4827666fde3a.jpg)

**Comment by pamduncan** [comment]
In most cases I have seen in support deleting the Eco appdata folder and then restarting Eco solves this.  Occasionally you have to restart steam 

To my knowledge there has never been a "play" or "exit button.  There has been "Load" and "Quit" in older versions now replaced by :New Game" or "My Worlds"  and "Quit" is still quit

**Comment by johnkslg** [comment]
@pamduncan next time this happens, can you collect the config files in games/eco folder and paste here so I can debug? Thanks so much!

**Comment by johnkslg** [comment]
Reducing priority because theres a workaround

**Comment by johnkslg** [comment]
Seems better lately
