### ISSUE TITLE
Unclaimed Carts?

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9464]
How can this even happen? A cart full of tailings in a ocean with no owner:
<img width="1676" alt="unclaim" src="https://user-images.githubusercontent.com/25908592/45881008-26551400-bdaa-11e8-88bd-0595babb7b45.png">

**Comment by elfl0rd** [comment]
Intended, you can remove deed associated with transport.

**Comment by D3nnis3n** [comment]
Could this somehow be prevented? As you see, the only usage for that is to put tailings into it, dump it in a sea, unclaim it and laugh that the admin cannot find out who he has to ban for that griefing.

**Comment by johnkslg** [comment]
That's interesting.  Perhaps we display 'created by' somewhere.

**Comment by D3nnis3n** [comment]
That would be a viable solution, as only the owner can remove the deed.

**Comment by johnkslg** [comment]
Next to 'is owned by' you could add 'Created by', perhaps only if its unowned.

**Comment by Spydarlee** [comment]
![image](https://user-images.githubusercontent.com/553695/46619555-4448a580-cb1a-11e8-80fd-562a72018edf.png)

**Comment by elfl0rd** [comment]
Okay, what about deed trading for placed objects?

**Comment by johnkslg** [comment]
Fixed!
