### ISSUE TITLE
The user is unable to carry the steam tractor back into the inventory.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9465]
Description: When the user tries to use the hammer to get the steam tractor back into the inventory, it is showing the message "Not enough room in the inventory".

STR:
1. Start the game.
2. Create/Join a world.
3. Obtain and place the steam tractor.
4. Select the hammer in the quick slot and left click on the steam tractor.
5. Observe that the user is unable to pick it up.

Actual Result: The user is unable to pick up the steam tractor.

Expected Result: Like the other objects, the user should also be able to pick up the steam tractor.

Screenshot:
![screenshot 445](https://user-images.githubusercontent.com/43132426/45884718-43054200-bdd2-11e8-9033-7863390a4617.png)

**Comment by Nicolausi113** [comment]
You can carry it if you ease your inventory/backpack

**Comment by seccombew** [comment]
Intended, you need some levels in the strong back skill to carry it.
