### ISSUE TITLE
Can't private message users with names on the profanity list

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9466]
See the screenshot.
It's impossible to write the user "shithead" (i don't know why he calls himself like that, it's none of my business, i do not know him or her) a message, as the profanity filter changes it to "********" before sending the message, so the user is unknown. So you should either disallow people with those names at all or make an exception for this command like you do on signs and in treasury allocation reasons. You can type in filtered words there - they will be shown.

Also, obviously, you can't mention these players in the game, as their name is censored in chat. Something should be done about this.

<img width="610" alt="profanityfail" src="https://user-images.githubusercontent.com/25908592/45888024-5659e280-bdbd-11e8-822c-4e9b1213d56b.png">

**Comment by D3nnis3n** [comment]
Their names are also displayed in crafting messages and other things anyway, so, well. Useless *g*

**Comment by craig-jong** [comment]
fixed in pr
