### ISSUE TITLE
When pointing on the construction post icon, the spelling in the description for construction is incorrect.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9468]
STR:

1. Start the game.
2. Create/Join a world.
3. Place a camp site and access it.
4. Select the construction post and point the cursor over it.
5. Observe the spelling mistake with it.

![eco 21-09-2018 16_11_19](https://user-images.githubusercontent.com/43132426/45890059-a6e23780-bddf-11e8-86dc-8553f80af523.png)

**Comment by johnkslg** [comment]
Why is this high priority?

**Comment by craig-jong** [comment]
fixed in pr
