### ISSUE TITLE
Construction Posts Map Marker

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9469]
This is not really a bug, but probably could be seen as one - anyway, just move it if you don't like it here, it's a small thing.

I would like the Construction Posts Marker also to be visible with "Misc" activated, instead of only with "economy".

Reason: We do rearely use it for economy, but we do use it to block off roads in upgrade, marking closed roads as of there people work with excavators and disturbing could couse some issues like blocking or flipping over cars. So we close roads when something major is done. The map icon enables everyone to see if a road is closed in before driving there or using this road, so they can plan ahead.

Using construction posts for this, especially as of the map icon, seems very useful and makes sense.

**Comment by WeaselDog** [comment]
Agree this should be moved and we need some other re-categorization of map marker filters

**Comment by WeaselDog** [comment]
This issue needs to be fixed before this can be fully play-tested: https://github.com/StrangeLoopGames/EcoIssues/issues/14724
