### ISSUE TITLE
USER ISSUE: empty campsite

### ISSUE THREAD

**Issue by Markitta** [StrangeLoopGames/EcoIssues#9470]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
got to the quest "getting equiped"

**Expected behavior:**
there should be tools in storage

**Actual behavior:**
its emptyn
**Do you have mods installed? Does issue happen when no mods are installed?:**
its empty

**Comment by BlazeGuy2** [comment]
@Markitta Need screenshots.

**Comment by Markitta** [comment]
![20180921193839_1](https://user-images.githubusercontent.com/43478779/45897012-3682e880-bdd6-11e8-8b34-0a4d1ad9f9d1.jpg)

**Comment by BlazeGuy2** [comment]
![startercamp](https://user-images.githubusercontent.com/35509188/46625530-2f9fe980-cae9-11e8-9896-2430175cfdf9.PNG)
Couldn't repro on 7.7.2.

**Comment by D3nnis3n** [comment]
Closed as it has not gotten an answer in the last 14 days.
