### ISSUE TITLE
USER ISSUE: Steam Truck Clipped Through World

### ISSUE THREAD

**Issue by jammie19** [StrangeLoopGames/EcoIssues#9471]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Drive steam truck over ramp (I was driving on sand and down stone road, one block above sea level, with lots of dirt in the truck storage).

**Expected behavior:**
It should have driven smoothly over ramp.

**Actual behavior:**
Instead it dropped both me and the truck through the sea, into a black screen (middle of planet?) with the truck spinning and end up on opposite side of planet, underwater.
![20180921225101_1](https://user-images.githubusercontent.com/12836572/45908178-1f062880-bdf3-11e8-9876-57946e73cd48.jpg)

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed.

**Comment by jammie19** [comment]
After attempting to repeat issue, I've found this happens every time I drive over a specific block in the steam truck. The car is firstly thrown into the air and if I exit straight away, the car and I fall back to the ground.

**Comment by jammie19** [comment]
![20180923155130_1](https://user-images.githubusercontent.com/12836572/45929551-47a13600-bf4b-11e8-8d63-c3463833a3c8.jpg)

**Comment by beastyn** [comment]
Won`t be able to reproduce
