### ISSUE TITLE
Signs going black

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9474]
As i mentioned in the live-stream today, i quite often get this:

<img width="1711" alt="signbug" src="https://user-images.githubusercontent.com/25908592/45909046-1700b580-be00-11e8-98d9-62c71dcb883b.png">

It appears, disappears and appears again - i really don't know why.

An example text from one of the signs:

> <color=#FF0000><u>Rules #1 - Traffic</u></color>
> <color=#000000>1. Roads are funded and claimed by government. (Private roads must be inacessible to anyone but you!) Please talk and plan with it before building roads, as they need to be exactly 5 wide, have 5 free block spaces above them and must fit into one claim.
> 
> 2. This is an european server - we drive on the right side. Offending this can lead to a fine of up to 50$.
> 
> 3. Obstructing the roads with your vehicles disturbs other players - do not park on a public road longer than 3 minutes. Offending this rule can lead to a fine of up to 50$.</color>

**Comment by CobaltEcho** [comment]
D3nnis3n, do you have Global Illumination on?  Does turning this setting on/off fix or change the issue?

**Comment by D3nnis3n** [comment]
Yes and yes. I also got the same problem that is mentioned in the linked issue you put in here.

**Comment by CobaltEcho** [comment]
Well, at least we know they are related now, and I'm not the only one going crazy!

**Comment by D3nnis3n** [comment]
Yeh, in my opinion there is definatley something wrong with Global Illumination since patch 7.7 - i could several times reproduce this effect and the other linked ones of pale and dull graphics underground with Global Illumination on and the vanishing of these problem when switching it off. Both problems did not occur in 7.6.

**Comment by beastyn** [comment]
Didn't meet in 0.8.1
Please reopen if need
