### ISSUE TITLE
Servers not in browser but can direct connect

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#9476]
There are people with servers that can connect without issue by direct connect to the IP but the servers do not show in browser (in categories or in search).

Have tried deleting and recreating appdata,  as well as reinstall and trying different ports.  The firewall is configures correctly, but have tested with firewall turned off.. No one looking for the server can see it although they can all direct connect without issue. Some of these are servers that have been around for a while and used to show up in the browser without issue. In one case the server was not showing up, then did show up and now is not showing up again.

If you need to see a server that is up and running and doing this where you can join by IP but not seen in browser  I have one here:  23.111.153.26:25000  Name: EcoGS Server Config testing

This happens to be on the same machine as this server and was set up and configured the same way but you can see it in the browser and join it  23.111.153.26:26800  Name:  PAM's BIG WORLD by Killservers. Quad World Active Community Discord - https://discord.gg/jrQFfFA! New World for 7.7

[Can connect to server via direct connect but server does not show in browser.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2407504/Can.connect.to.server.via.direct.connect.but.server.does.not.show.in.browser.txt)

**Comment by pamduncan** [comment]
There are many servers up and online but are not showing up in browser categories or in the Browse all page:  
[![Screenshot from Gyazo](https://gyazo.com/1c43bf0e676b20d03f5f3a70b4bffb07/raw)](https://gyazo.com/1c43bf0e676b20d03f5f3a70b4bffb07)
[![Screenshot from Gyazo](https://gyazo.com/250d561337e2c1be2effc64e90133a56/raw)](https://gyazo.com/250d561337e2c1be2effc64e90133a56)
[![Screenshot from Gyazo](https://gyazo.com/05e27b9278e33c30439e7553f55dfa35/raw)](https://gyazo.com/05e27b9278e33c30439e7553f55dfa35)
[![Screenshot from Gyazo](https://gyazo.com/77dd16b3933026a258d8dad121708a4d/raw)](https://gyazo.com/77dd16b3933026a258d8dad121708a4d)
[![Screenshot from Gyazo](https://gyazo.com/1da46d6635e582cad8a76cec4400e8df/raw)](https://gyazo.com/1da46d6635e582cad8a76cec4400e8df)

The above screenshots are taken with the default of matching the version to the current release of 7.7.2, on a client with 7.7.2 running and all other selection set for everything:  

[![Screenshot from Gyazo](https://gyazo.com/275737f31ec1bf7daa3e964f806522b3/raw)](https://gyazo.com/275737f31ec1bf7daa3e964f806522b3)

**Comment by D3nnis3n** [comment]
There seem to be some issues with the master server right now, since yesterday most servers have vanished from the lists - pretty empty, can only find around 10 or so, even the "Continue" Button is empty, i can only connect to my server by favorites and recently played. This should be fixed asap.

**Comment by LucasDomberg** [comment]
I have the same problem with my dedicated Server game!

**Comment by pamduncan** [comment]
Direct connect works consistently.  Sometimes favorites or recents will work and sometime its will not.  The only favorites that seem to work are of you had the server as a favorite before 7.7.0 - but if anything change like a port or the IP and you try to get a new favorites link you cannot do that in most.  Sometimes if you direct connect to a server and it does show up as a recent server after that you can then  mark it as a favorite and it may work.   I never saw this issue before last week but now seeing it even on servers running 7.5 and 7.6 as well as 7.7

**Comment by pamduncan** [comment]
[![Screenshot from Gyazo](https://gyazo.com/a9f762dc11b3677e75032e90be42fab6/raw)](https://gyazo.com/a9f762dc11b3677e75032e90be42fab6)
[![Screenshot from Gyazo](https://gyazo.com/cdcf96dad194638bcff8bb973704e65b/raw)](https://gyazo.com/cdcf96dad194638bcff8bb973704e65b)
[![Screenshot from Gyazo](https://gyazo.com/cdcf96dad194638bcff8bb973704e65b/raw)](https://gyazo.com/cdcf96dad194638bcff8bb973704e65b)

**Comment by LucasDomberg** [comment]
I can see my dedicated server again. problem is solved for me :)

**Comment by pamduncan** [comment]
In some cases the servers will show up in search after a few hours or even a day or so.  Some issues with the recommended listings not showing the server but they can be found in browser search is solved by setting a server category.  But if not found in a search even if a category is set the server will not show.  Its better to see if they show up on a browser search as sometimes a user cannot see their server in the recommended categories as they don't match the server recommendations so do not get shown the server.  If you can do a browser search and the server pops up most times they will show in the recommended windows once the Network configurations is updated with playtimes that are consistent with the server owner, the server category is selected and so on,.
 But if direct connect will not work then it usually is a port forwarding issue.  If it does work there is a high likelihood it will show up in the browser list after a wait of a few hours.  It may still not show in 'recommended' unless network config is updated.

**Comment by TheKrush** [comment]
This is happening to me.

**Comment by D3nnis3n** [comment]
Considering this issue is causing quite some fuss and is pretty much the most-discussed support issue on discord at the moment, i give it high priority. I've been tasked by John to give some issues a priority boost that would improve polishing and playability from the view of players.

**Comment by TheKrush** [comment]
I've tried all the workarounds and nothing seems to fix the issue for my server.

Including by not limited to changing from ports 3000,3001 to 25000,25001. Renaming the server. Trying to forward UDP/TCP ports only to the specific ports that require them instead of opening both to all ports.

**Comment by johnkslg** [comment]
@mirasrael can you investigate?

**Comment by mirasrael** [comment]
Hi @TheKrush Do you still have this issue after 7.8.0 release?

**Comment by mirasrael** [comment]
Closed it due to no response for a week. Feel free to re-open this issue if this still present.
