### ISSUE TITLE
String "Lumber" used on 2 different position.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9478]
First - Speciality name, "Lumber"
Second - Material name, "Lumber"

Need split, these require different translation.
![default](https://user-images.githubusercontent.com/4980243/45913522-ad52cc80-be3c-11e8-8701-a8c5af23a347.png)
![default](https://user-images.githubusercontent.com/4980243/45913525-c8254100-be3c-11e8-8ce7-3b357bf046e4.png)

@Nanders

**Comment by Deantwo** [comment]
Long time issue, would indeed love to see it fixed.
