### ISSUE TITLE
Commenting on laws with identical names

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#9481]
Someone proposed two new laws with the same name.
The laws are named `Motivate newbies` and `motivate newbies`.

When commenting on one law, the comment appear on both laws.

**Comment by Deantwo** [comment]
Yeah, I figured it had something to do with that.
That is why I included the law names in my report.

**Comment by Deantwo** [comment]
Commenting on laws via the in-game chat just doesn't seem like a very good idea. At least that is what I assume is the cause of this.
Remove that and you remove the need for referring to a law by name when commenting. Simply use the law's GUID instead.

**Comment by beastyn** [comment]
0.8.1.3
Still an issue

**Comment by johnkslg** [comment]
Renaming is case insensitive in latest by my check.
![image](https://user-images.githubusercontent.com/3536496/68906202-6686fc80-06f8-11ea-9d51-aa9a912768cb.png)

**Comment by D3nnis3n** [comment]
Fixed.
