### ISSUE TITLE
USER ISSUE: bug?

### ISSUE THREAD

**Issue by mrsaminus** [StrangeLoopGames/EcoIssues#9483]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
harvested 20 beets and 12 tomato plant. Clarly ready for harvest. did not get a single fruit or seed

**Expected behavior:**
given fruit or seed

**Actual behavior:**
just removed itn
**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods installed

**Comment by Nicolausi113** [comment]
This might be fixed but not released yet? related #9095

**Comment by elfl0rd** [comment]
@D3nnis3n really looks as fixed... And not answered :)
