### ISSUE TITLE
Excavators big smoke goes through anything.

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9484]
I just don't like that.
<img width="1920" alt="meh" src="https://user-images.githubusercontent.com/25908592/45916842-8ad8a780-be6c-11e8-9727-8358d243092e.png">
Should smoke the interior first, making view worse and then spill out at the entrance.

Also, i think that amount of smoke is quite a bit too much.

**Comment by keegan-o** [comment]
Switched it out to the smoke the steam truck uses and added collision (added collision to the skidsteer and steam truck smoke too)
![image](https://user-images.githubusercontent.com/14983165/50306892-9461b380-044b-11e9-8a44-43ac190d6382.png)
