### ISSUE TITLE
"has for sale" spam

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9488]
When you are selling Iron ore, but do not have one for sale, then start a steel project with 100 steels and then start to make iron, 100 bars and use the same storage for your shop and your blastfurnace the following will happen.

1 Iron Bar is finished
Shop says iron is now sold again
Steel Project takes the iron bar in - no iron for sale anymore
1 Iron Bar is finished
Shop says iron is now sold again
.
.
.

and so on.

Any possibility to have the shop delay it's checking a bit, so the iron bar would go into the steel project before or just have the projects take ingredients from chests faster or before the shop notices them?

It's enerving.

**Comment by elfl0rd** [comment]
Yep, it's terribe...

**Comment by johnkslg** [comment]
@sidjuego Can add a throttle like for the room value task.  It happens here:

![image](https://user-images.githubusercontent.com/3536496/46230331-28c0ec00-c31d-11e8-8b8d-0d669570ab52.png)

**Comment by sidjuego** [comment]
Won't adding a throttle add a bit of an overkill if I were to couple it with a for each loop?
I could do this though..

```
if(playerChange && timeDifference(120)){
for each....
}
```
what would you prefer?

**Comment by johnkslg** [comment]
Well yeah do it outside the foreach loop of course
