### ISSUE TITLE
Possible length for currencies is too short

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9491]
I wanted to implement "Emission Allowance(s)" as a currency and use them like the EU does. (E.g. you get allocated some and can trade unused ones with other players, you get taxed some when polluting somehow and allocated when cleaning) Unfortunatley i can't type that in as "Emission Allowa" is all that can fit in. I also don't know of any other short name that would describe what i want them to be. Using their abbreviation EAU would not explain what it is as most probably even 99% of the european players don't know what an EAU is, either - so how should foreign players do?

**Comment by D3nnis3n** [comment]
I found a name for the currency that does EXACTLY fit, but am still unhappy: Emission Permit

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/46826644-5bbaa500-cd4b-11e8-9618-8d68c7439120.png)

I've increased the possible length of currency names by double. Should cover it, but we can't really make it unlimited.
