### ISSUE TITLE
How does CO2 Pollution tax work?

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9492]
Someone could explain how it works? I got taxed once i got into my steam truck and drove around half an hour but i was not taxed again? I got out of the car and in again, also no tax. So it seems to be not per use, and also not per time. How does it work? Does it work at all or does it just take a one-time fee per object ever used? Is it applied per ton? Will one then be charged again when the vehicle had to be picked up because of an accident and need to pay the full price again? Would there be any change to change it to lower increments of a ton then so people have to pay the tax more regulary and not for a long time in advance? Could we even define the amount of pollution you need to create to pay a dollar?

**Comment by D3nnis3n** [comment]
I want to bump this up, additionally to these issues:
https://github.com/StrangeLoopGames/EcoIssues/issues/9834
https://github.com/StrangeLoopGames/EcoIssues/issues/9828

Those issues, together with this one:
https://github.com/StrangeLoopGames/EcoIssues/issues/9850

Make ANY treatment of co2 by the law system impossible at the moment - too much co2 is not handleable therefore.

**Comment by johnkslg** [comment]
This should be easy in new civics system. Let me know if not.  Marking fixed.

**Comment by beastyn** [comment]
will check tax in #9944
