### ISSUE TITLE
USER ISSUE: Lost ownership of my house

### ISSUE THREAD

**Issue by amboo515** [StrangeLoopGames/EcoIssues#9495]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**

**Expected behavior:**
I should retain my property (three story house)

**Actual behavior:**
It is now public propertyn
**Do you have mods installed? Does issue happen when no mods are installed?:**
It is now public propoerty

**Comment by seccombew** [comment]
Needs more info about how this occurred.

**Comment by D3nnis3n** [comment]
No answer to Information request in 14 days, reopen if issue persists.
