### ISSUE TITLE
opening Eco brower results in opening local files

### ISSUE THREAD

**Issue by rsdworker** [StrangeLoopGames/EcoIssues#9496]
i had experinced the issue with direct links from eco server to their eco web page
sometimes its opens my local files - its seems resulting possible bug with LAN-WAN bug.
its occurs on steam however takes few clicks to get through to eco page

steps to reproduce
1: click laws or ecomcony viewer buttons
2: local files open 

what i should expect
1: click laws button
2: eco server  webpage opens

my browser is Firefox 

window 7 with AVG virus killer

i will add any info if you need

**Comment by seccombew** [comment]
Can you either post a video or post pics to show what you are talking about?

**Comment by rsdworker** [comment]
i have two videos 

one captures the error messages the second one shows the local files opening after clicking it
its on Greenleaf server - but issue is exact same across on local or other server on my client viewer
i use steam verison one

**Comment by TheeJudge** [comment]
#9252 Same Problem

**Comment by rsdworker** [comment]
i have zip files but this GIT wont accept them but its said its accepting zip - its odd so i will try use other ways

**Comment by BlazeGuy2** [comment]
Dup of #9252
