### ISSUE TITLE
USER ISSUE: Tooltip mishap

### ISSUE THREAD

**Issue by EmpressJacquelyn** [StrangeLoopGames/EcoIssues#9497]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Press Z View Mining and Mining Efficiency toolips. 

**Expected behavior:**
Mining Efficiency should display expected calorie consumtion decreses. and Mining-unlocks efficiency

**Actual behavior:**
they appear to be reversed, you have to hover over Mining, instead of Mining Efficiency, to view your current calorie % decresen
**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods Pure Vanilla

**Comment by EmpressJacquelyn** [comment]
Didn't want to open another issue.. but it seems Logging and Logging Efficiency Are backwards as well. but Digging and Digging Efficiency are good!

**Comment by Deantwo** [comment]
Duplicate of #8241.

**Comment by EmpressJacquelyn** [comment]
rgr, thanks for doing mah leg work
