### ISSUE TITLE
Backup Frequency broken?

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9498]
Hello,
with the settings shown in the screenshot i earlier got 24 backups per day, one every hour. (That's what i wanted) Somehow this has changed - i only have four backups now, where only two are hourly ones and the others are from the last day. Also, some explanation about these backup settings would be great, as i don't know what "NumberOfTenMinuteBackups" and the other similar settings is supposed to do. I just had found out, that setting them all to 24 did give me the wanted result.
<img width="1462" alt="backups" src="https://user-images.githubusercontent.com/25908592/45928733-d5c7ed00-bf48-11e8-876f-45ac06b05ec5.png">

Also, a little suggestions: Any way to compress at least the backups to save space? 24*1,5 GB is quite a bit for little NVME SSD *g*

**Comment by Pradoxzon** [comment]
Was your server running continuously with those backup settings during the time period shown in your picture?

**Comment by D3nnis3n** [comment]
Yes. (I know that the backup cycle restarts with a server restart)

I also found the mistake in the meanwhile (it was obvious though, but didn't see it), but don't know why: MaxTenMinuteBackups must be set to "24" too.

Could you probably explain what these different values do? They were new as of some of the latest patches.

As of how it stands i would expect the following to happen:
When i use BackupFrequencyInHours "1" and MaxHourlyBackups "24" i should get 24 backups a day where the server runs fully. This does not seem to happen, though, as i also need to have the settings of all other values set to 24, despite i'm not doing any backups in 10-minute cycle. For Daily and Weekly Backups i could imagine that you mean how many per day and week are kept for a longer time? This really needs some explanation, i think.


Anyway, as i do get hourly backups again - but with a quite odd configuration - you can probably drop the priority, as it's not "broken".

**Comment by Pradoxzon** [comment]
I'm looking at changing the names of the settings to make it more user friendly. Also looking at tweaking the way the server decides which backups to keep or toss.
Hopefully this will make things easier to use. :)

**Comment by Pradoxzon** [comment]
Fixed in PR
