### ISSUE TITLE
Crane, excavator, Skirt Skeer

### ISSUE THREAD

**Issue by trevelmike** [StrangeLoopGames/EcoIssues#9499]
![20180914235148_1](https://user-images.githubusercontent.com/42901466/45930789-02204100-bf2a-11e8-9b0f-10a19c477ae6.jpg)
![20180914235159_1](https://user-images.githubusercontent.com/42901466/45930790-02204100-bf2a-11e8-8cc6-6a0f8671a4b6.jpg)
![20180917115141_1](https://user-images.githubusercontent.com/42901466/45930791-02204100-bf2a-11e8-9c78-264411bb4215.jpg)
![20180917115142_1](https://user-images.githubusercontent.com/42901466/45930792-02204100-bf2a-11e8-894a-fb25767e7ee4.jpg)
![20180922205057_1](https://user-images.githubusercontent.com/42901466/45930793-02204100-bf2a-11e8-8941-803186ab46ca.jpg)

I brought this up earlier but i thought i would also post some pictures of what is going on in 7.7. Excavator and skirt steer 9 i know i am spelling that wrong) may sometimes by approach fall through the ground and when you look up fall and then go back into the ground again. 
The crane has it's own issues with the wiring going all over the place.

**Comment by mirasrael** [comment]
Seems like a zero-coordinate issue. Should be fixed in 8.1 Re-open if still a case.
