### ISSUE TITLE
USER ISSUE: Trash bag bug

### ISSUE THREAD

**Issue by Tijwss** [StrangeLoopGames/EcoIssues#9500]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
One player empty a trash bag while another one still has it open. The trash bag disapear but the player that has the bag open can still put things in it but it crash.

**Expected behavior:**
Either recreate a trash bag either not being able to see the interior of the trash bag

**Actual behavior:**
The following error message popped up:
``` 

Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.Inventory.MoveSomeItems(Player player, ItemStack sourceStack, ItemStack targetStack, Int32 quantity)</size>
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
``` 

Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.Inventory.MoveSomeItems(Player player, ItemStack sourceStack, ItemStack targetStack, Int32 quantity)</size>
```

**Comment by craig-jong** [comment]
fixed in pr
