### ISSUE TITLE
USER ISSUE: Unable to view Server data while running Server

### ISSUE THREAD

**Issue by trackman1997** [StrangeLoopGames/EcoIssues#9502]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Single Player Automatically created Desktop Server.
2. Open up data while in game.

**Expected behavior:**
Allowed me to view the graphs and data as long as desired.

**Actual behavior:**
I was kicked out of the server and the following error message popped up: Connection timed out.

No mods

**Comment by seccombew** [comment]
Did it break using the /openserverui command?

**Comment by trackman1997** [comment]
No

**Comment by SlayksWood** [comment]
Command /openserverui works.
Do you have this problem now?

**Comment by D3nnis3n** [comment]
Closing for  now, reopen if this issue reoccurs.
