### ISSUE TITLE
The excavator when used in the game is breaking when continuously digging in the same place.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9503]
Description: When the user tries to use the excavator and digs in the same spot, the game starts to break.

STR:

1. Start the game.
2. Create/Join a world.
3. Obtain an excavator.
4. Start digging in the same place.
5. Observe that the game breaks after some time.

Actual Result: The game starts to breaking when digging in the same place.

Expected Result: The excavator should stop breaking the game when used in the same place.

Video Link:
https://www.dropbox.com/s/gyg664060m7fofp/Unity%202018.2.3f1%20Personal%20%2864bit%29%20-%20Game.unity%20-%20Client%20-%20PC%2C%20Mac%20%26%20Linux%20Standalone%20_DX11_%2024-09-2018%2017_43_03.mp4?dl=0

**Comment by beastyn** [comment]
Can't recreate this issue, There are some other strange things, but game wasn't broken

**Comment by mirasrael** [comment]
@beastyn it was about breaking *excavator*, not the game.

**Comment by beastyn** [comment]
well, it still wasn't broken ) There are some other issues, but not with excavator
