### ISSUE TITLE
Can't place Wall Lamps AT other peoples property, despite the Wall Lamp being IN my property

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9505]
See the screenshot:
While i CAN place a building block there that will connect with the other property, i cannot place a lamp there that would connect with the other property and - like the building block - be in my property.

That's bad, i can't make nice looking streetlights when i'm not authorised to place them at the houses on MY property, while i can do so with blocks. Now i need to use the block solution and waste 150 Power for the wooden lights hanging in the middle of the street and using framed glassl to simulate a cable - very pricey thing when compared to some wall lamps.

<img width="962" alt="lamp" src="https://user-images.githubusercontent.com/25908592/45952642-ed19df80-c007-11e8-85b4-4becbd827062.png">

**Comment by D3nnis3n** [comment]
It get's even funnier, read that chat:
<img width="644" alt="chat32" src="https://user-images.githubusercontent.com/25908592/46078333-1f584800-c194-11e8-8dc4-20c0e1bd66be.png">

**Comment by SlayksWood** [comment]
Check on 0.9.0 staging-1293. Wasn't able to reproduce. Seems fixed.
![image](https://user-images.githubusercontent.com/45708377/70798807-f92ec000-1db8-11ea-9aa7-f31174d16b48.png)
