### ISSUE TITLE
Signs Content does not come back after removing and leaving the UI without saving

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9506]
I accidentially deleted all content of a sign today while trying to edit it, saw that i did so and did NOT save the change (e.g. i just left the UI without pressing "Save"=. I got into the UI again, expecting that the text of the sign - that still has the contents shown on it - would be in the text field again, but no:
<img width="1672" alt="signs" src="https://user-images.githubusercontent.com/25908592/45953219-b47b0580-c009-11e8-9ff6-9a644a6c2ffa.png">

It will be back after a disconnect, though.

**Comment by Pradoxzon** [comment]
Fixed
