### ISSUE TITLE
When a bison is killed, the death animation is improper.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9509]
Description: When the user kills a bison, it appears to be lying down and vibrating. It is also slowly moving around because of the vibration.

STR:
1. Start the game.
2. Create/Join a world.
3. Obtain bow & arrows and equip it.
4. Find a bison and start shooting arrows at it.
5. Observe the issue when it dies.

Actual Result: The bison starts vibrating when it dies.

Expected Result: The bison should appear to be static without any graphical corruption when it dies.

Screenshot:
![screenshot 452](https://user-images.githubusercontent.com/43132426/45954550-f36d8300-c02a-11e8-9046-e4f1ab5c4b84.png)

**Comment by seccombew** [comment]
Intentional
