### ISSUE TITLE
Fuel supply needs to tell total burn time for full inventory

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#951]
It only shows for the current item, should say both.

**Comment by metachronism** [comment]
this isn't determinable from the contents without knowing the burn rate, which varies depending upon what is being crafted.

**Comment by johnkslg** [comment]
It should show for the current rate and say "At current rate: x time remaining"

**Comment by metachronism** [comment]
marjie already added this
