### ISSUE TITLE
When fast animals are trapped in deep holes, they are able to easily climb out.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9512]
Description: The animals that have very fast movement speed are able to dodge and get out of any space. 

STR:
1. Start the game.
2. Create/Join a world.
3. Create some deep space that cannot be escaped by normal means.
4. Spawn some fast animals like foxes in it.
5. Observe the issue.

Actual Result: The animals are able to escape spaces that are not logical.

Expected Result: The animals should not be able to escape hard spaces and should not look unnatural.

**Comment by seccombew** [comment]
Might already be intended behavior.  Can you post a video demoing this issue?

**Comment by SlayksWood** [comment]
Checked on 8.1. Wasn't able to reproduce, seems fixed. Any animal can not jump above 3 blocks. Sometimes it looks sharp.
https://drive.google.com/file/d/1VwB8DhIMhiuM2LZitZ8dt4LVuT3VLFJu/view?usp=sharing
If it happens again, please reopen issue.
