### ISSUE TITLE
If the user draws a bow, there is no option to cancel it.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9513]
Description: There is no option to cancel the action of drawing arrows. There is also no option to pick up arrows that have been used.

STR:
1. Start the game.
2. Create/Join a world.
3. Obtain bow and arrow and equip it.
4. Draw the bow and observe the issue.

Actual Result: There is no option to cancel a bow that has been drawn.

Expected Result: There should be an option to cancel a drawn bow.

**Comment by MrYoshii** [comment]
hi :D you can scroll with your mousewheel to cancel the Draw :)

**Comment by CobaltEcho** [comment]
As a note, if you press a hotkey to equip another item (like a Hammer) while the Bow is drawn it will cancel the Bow and equip the other item, then you can reselect the Bow.
