### ISSUE TITLE
Server is online with players on server  - odd blank window on desktop related to EcoServer and then others cannot log in

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#9514]
There are some servers that are up and running just fine and people are connected and playing and then a blank window opens up at some random time while the server is running and after it shows up no one else can log into the server.  Those already in have no issue unless they log out - then they cannot log in again.  Closing the window causes the server to shut down.  After restart everyone can log in.  There are no dump files generated and nothing is shown in the window.. its just blank.  I assume its trying to report an error of some sort but not seeing anything in the dump folder and not seeing anything in windows logging

[![Screenshot from Gyazo](https://gyazo.com/2088c73d8e6c9d3362d53fe44e440455/raw)](https://gyazo.com/2088c73d8e6c9d3362d53fe44e440455)

**Comment by SlayksWood** [comment]
Wasn't able to reproduce in latest versions. Seems not actual.
