### ISSUE TITLE
Eco server keeps crashing

### ISSUE THREAD

**Issue by MrYoshii** [StrangeLoopGames/EcoIssues#9515]
Hi so i have talked with a supporter in discord and he told me to come here.. 
my eco server keeps crashing without any dump files. but i will add some screenshots.

![image_2018-09-24_16-54-34](https://user-images.githubusercontent.com/8422439/45961144-22c9c300-c01e-11e8-817c-f46e525c67cb.png)
![image_2018-09-24_16-53-13](https://user-images.githubusercontent.com/8422439/45961145-22c9c300-c01e-11e8-98a4-7012c1872380.png)
![image_2018-09-24_16-35-17](https://user-images.githubusercontent.com/8422439/45961146-23625980-c01e-11e8-83a6-5f09e8db5209.png)
![image_2018-09-24_16-34-30](https://user-images.githubusercontent.com/8422439/45961147-23625980-c01e-11e8-8687-12fa3629bce5.png)
![image_2018-09-24_16-33-32](https://user-images.githubusercontent.com/8422439/45961148-23625980-c01e-11e8-8bd1-bc2605d6d952.png)
![image_2018-09-24_17-18-43](https://user-images.githubusercontent.com/8422439/45961149-23625980-c01e-11e8-849f-48c904f095df.png)
![image_2018-09-24_17-18-22](https://user-images.githubusercontent.com/8422439/45961151-23faf000-c01e-11e8-8302-9bccf58b8e41.png)
![image_2018-09-24_17-16-58](https://user-images.githubusercontent.com/8422439/45961152-23faf000-c01e-11e8-99cd-1ade51759c2e.png)
![image_2018-09-24_17-16-48](https://user-images.githubusercontent.com/8422439/45961153-23faf000-c01e-11e8-9985-23209acb491e.png)
![image_2018-09-24_16-57-02](https://user-images.githubusercontent.com/8422439/45961154-23faf000-c01e-11e8-8725-1f8614588fad.png)

my map https://download.darkside-gaming.at/Data/Storage.rar

**Comment by MrYoshii** [comment]
and this is the error log from the guy that causes the server crashes.
[Eco_error.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2425661/Eco_error.txt)

Pls could it get a higher priority because nobody can play on my server and the people are getting mad!!!

**Comment by beastyn** [comment]
Should be fixed for now
