### ISSUE TITLE
Mod Commands hidden amongst others (so hard to find them unless you know exactly what to look for)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9516]
**Version:** 0.7.7.2 beta

I play on servers using CTK Mod, sometimes i also test this mod it would be much simpler if there was a way that Modded Commands have their own special header when typing /help
![snap2947 edited](https://user-images.githubusercontent.com/29383891/45962143-13e01200-c018-11e8-80f2-4a0894fc324b.png)

I think maybe adding MOD Admin Commands and MOD User Commands as extra lists cannot hurt

**Comment by ClayC90** [comment]
Preferably allowing the modder to set the header of the commands and group them by that, would be ideal, so in CTK case, I could throw them all under Clay's Toolkit Commands.

**Comment by Conchipedia** [comment]
if we had separate Headers for example Mod-Admin Mod-user (or CTK Admin /CTK User) so much easier to work out
then if someone does a screw up and uses a command that is Under the MOD User/admin part they Know that's its MOD related NOT game related

**Comment by WeaselDog** [comment]
Chat commands have categories now so there is a solution for this.
