### ISSUE TITLE
USER ISSUE: Connection timed out 

### ISSUE THREAD

**Issue by RebelDarkOmen** [StrangeLoopGames/EcoIssues#9518]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection timed out
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Connection timed out
```

**Comment by D3nnis3n** [comment]
Closed as it has not gotten an answer in the last 14 days.
