### ISSUE TITLE
Functionality issue is observed in the UI screen.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9520]
Description: When the user tries to scroll in the recommended section for the world, the scrolling arrows disappear.

STR:
1. Start the game.
2. Select the new game option.
3. Tap on browse all.
4. Select browse recommended.
5. Scroll around by selecting the left/right arrow keys.

Actual Result: The arrow keys disappear.

Expected Result: There should be no functionality issues in the game.

Video Link:
https://www.dropbox.com/s/jkw32uyj0xus5fy/Eco%209_25_2018%202_51_38%20PM.mp4?dl=0

**Comment by sidjuego** [comment]
This issue seems to be fixed now. Verify once?
