### ISSUE TITLE
The servers displayed in choosing a world to join, is randomly fluctuating.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9522]
Description: When the user tries to join a world that has already been hosted, it is not always being displayed and the player was to re-visit consistently for it to re-appear again.

STR:
1. Start the game.
2. Select the new game option.
3. Scroll around to see if there are any other hosted worlds being generated.
4. If any worlds are being displayed, select the browse all and select browse recommended.
5. Observe the displayed world is not showing again until refreshing the page multiple times.

Actual Result: The hosted world is not consistently being displayed.

Expected Result: The hosted world should be displayed sooner and should appear more frequently.

Video Link: 
https://www.dropbox.com/s/t8n2vmggd80336u/Eco%209_25_2018%203_22_27%20PM.mp4?dl=0

**Comment by johnkslg** [comment]
Not sure what the problem is. Can you post screenshots of expected behavior and what happened instead?
