### ISSUE TITLE
Players are not able to detect locally hosted worlds.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9523]
Description: The users who are locally connected are not able to detect the locally hosted server by other players.

1. Start the game.
2. Create a world.
3. Have another lan player access the game with a different system.
4. Try to search for the locally hosted server.
5. Observe that it is not being displayed.

Actual Result: The lan players are not able to detect locally hosted world.

Expected Result: The players should be able to detect and join the locally hosted world.

**Comment by WeaselDog** [comment]
This has been fixed in the latest version. Thanks for your report.
