### ISSUE TITLE
The settings are reflecting directly.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9525]
Description: The changes made in the settings are reflecting directly without the need of selecting the apply button.

1. Start the game.
2. Create/Join a world.
3. Select the escape button and make some changes in the settings.
4. Select the escape button again and observe the issue.

Actual Result: The changes are affecting directly.

Expected Result: Either the changes should reflect only if the apply button is selected or the apply button can be removed since the changes are reflecting directly.

Screenshot:
![screenshot 74](https://user-images.githubusercontent.com/43132426/46009575-a0083d00-c0dd-11e8-8fb3-5e24a41b362c.png)

**Comment by Conchipedia** [comment]
personally i like the way the changes are real time and i thought Apply was only for the resolution change

**Comment by seccombew** [comment]
Intended.
