### ISSUE TITLE
If the player immediately swaps tool, it is showing the wrong tool for the current action.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9526]
Description: If a user is cutting tree with an axe and immediately swaps to a pick axe and starts clicking, the player is doing the mining animation when cutting a tree. When initially selecting, sometimes the item is incorrectly selected and is appearing to be the wrong tool indefinitely until changed.

STR:
1. Start the game.
2. Create/Join a world.
3. Place a campsite.
4. Obtain and place the tools in the quickslot.
5. Quickly swap between them and observe the issue.

Actual Result: The tool in hand and the tool in the selected quick slot is not matching and the animation performed when clicking the mouse button.

Expected Result: As soon a tool is selected, the swapping should work ignoring other actions.

Screenshot:
![screenshot 75](https://user-images.githubusercontent.com/43132426/46010989-19a22a00-c0e2-11e8-9ebd-0c3ad4de76c7.png)
![screenshot 76](https://user-images.githubusercontent.com/43132426/46010991-19a22a00-c0e2-11e8-964d-4b944067ee8f.png)

**Comment by SlayksWood** [comment]
Checked in 8.3.0 staging-1066. Wasn't able to reproduce. It was fixed in 8.2.0
