### ISSUE TITLE
When the land claim papers are being depleted, it is not disappearing from inventory.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9527]
Description: When the user uses up the land claim stake and consumes all the land claim papers, it is still appearing to be displayed in the quick slot.

STR:
1. Start the game.
2. Create/Join a world.
3. Obtain and equip the land claim stake and papers in the quick slot.
4. Completely use them up and observe the issue.

Actual Result: Even though all the land claim papers are used up, it is still being visually displayed.

Expected Result: Once the items are used up, it should disappear from the inventory.

Screenshot:
![screenshot 78](https://user-images.githubusercontent.com/43132426/46011937-25432000-c0e5-11e8-8c5e-d56ef295866d.png)

**Comment by seccombew** [comment]
@Pradoxzon Take point on this, @craig-jong you can monitor.

**Comment by Pradoxzon** [comment]
As Land Claim Papers are used, they are being removed from the inventory without being updated visually. The action of unclaiming works as intended, this is only happening when claiming land.

**Comment by Pradoxzon** [comment]
Added an additional call to Inventory.OnChanged.Invoke() in the MultiAtomicAction when the claim paper is removed from the user's inventory. Might be overkill, but it appears to have fixed the issue.
