### ISSUE TITLE
The user is able to cut the stump using the basic axe.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9528]
Description: The user is able to use the basic axe which is obtained from the base camp and after some cutting done with it, the stump disappears.

STR:
1. Start the game.
2. Create/Join a world.
3. Place the camp site and obtain and equip the axe from it.
4. Cut down a tree and start cutting at the stump.
5. Observe that the stump is getting destroyed.

Actual Result: The stump is getting destroyed with the basic axe.

Expected Result: The stump can only be destroyed with an advanced tool.

Screenshot:
![screenshot 79](https://user-images.githubusercontent.com/43132426/46012544-3c830d00-c0e7-11e8-98c1-401872b64194.png)

**Comment by elfl0rd** [comment]
Advanced tools lower caloria consumption, NOT provide additional features.

**Comment by D3nnis3n** [comment]
This change would hurt the game so much, when people can no longer remove their debris … Please no.
