### ISSUE TITLE
USER ISSUE: settings tabs works strange.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9529]
**Version:** 0.7.8.0 beta staging-b7709677
![r](https://user-images.githubusercontent.com/4980243/46014590-844e6800-c0d8-11e8-854c-05f57b199aeb.gif)

**Comment by Nanders** [comment]
Bumping from high priority

**Comment by elfl0rd** [comment]
As i see - it's fixed on master.
![default](https://user-images.githubusercontent.com/4980243/47561978-a3355980-d925-11e8-91f0-027d41b84b0e.png)
