### ISSUE TITLE
Server browser - no space to translate.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9532]
![default](https://user-images.githubusercontent.com/4980243/46015233-739ef180-c0da-11e8-81e6-e149d0b2dce4.png)

**Comment by johnkslg** [comment]
Can you help with this one?  I think the table layout should resize them, maybe thats not working with localization?

**Comment by johnkslg** [comment]
These need to be autosize, and could be bigger anyway.

**Comment by Spydarlee** [comment]
Having some trouble pushing changes so this might not get in 'till tomorrow, but how does this look @johnkslg, @elfl0rd?

![image](https://user-images.githubusercontent.com/553695/50777739-56122400-1294-11e9-8a96-371814c15919.png)

Increased the width of the columns; the text auto-shrinks down to fit more in; and if that's not enough it wraps to another line as well as shown here.

We could reduce the minimum font size even further to limit wrapping but it gets quite hard to read if it goes much smaller than this!

**Comment by elfl0rd** [comment]
hmm... can you expand match column to fit this 2 symbol? Then fully fine for me.
