### ISSUE TITLE
Room types is not available to translate.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9534]
![default](https://user-images.githubusercontent.com/4980243/46016529-b44c3a00-c0dd-11e8-932d-14476b686666.png)

**Comment by Nanders** [comment]
![image](https://user-images.githubusercontent.com/6262198/46039625-0df33b00-c0c3-11e8-8c33-fa8c2fa4855a.png)
This is working as expected with the most recent strings from crowdin
