### ISSUE TITLE
The loading animation is not smooth when producing any product in the work bench.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9536]
Description: When the player tries to make any production in buildings like work bench etc, the animation is not appearing to be smooth and consistent in it.

STR:
1. Start the game.
2. Create/Join a world.
3. Place the camp site and collect some logs.
4. Construct and place a work bench.
5. Start producing any product in it that require short amount of time like hewn log.
6. Observe the loading animation issue.

Actual Result: The production animation is not proper.

Expected Result: The production animation should be smooth.

Screenshot:
![screenshot 80](https://user-images.githubusercontent.com/43132426/46021266-e7062a80-c0fd-11e8-9397-4e08a6589400.png)

**Comment by WeaselDog** [comment]
The crafting UI has been updated since the original report and it is smoother now. There are still some ticks for items with a shorter craft time, but this is because it updates every second.
