### ISSUE TITLE
The player is able to build a wooden wall on top a tree stump.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9537]
Description: The player is able to place on top of the wooden roots of a tree stump.

STR:
1. Start the game.
2. Create/Join a world.
3. Obtain some hewn wood and have the hammer equipped.
4. Start placing the wooden wall near a tree stump.
5. Observe the overlap issue.

Actual Result: The player is able to place the wooden wall on top of tree stump.

Expected Result: The player should get an error message when trying to place on a tree stump.

Screenshot:
![screenshot 81](https://user-images.githubusercontent.com/43132426/46027092-a5c84780-c10a-11e8-89a8-869880108bbe.png)

**Comment by seccombew** [comment]
Intended behavior.
