### ISSUE TITLE
USER ISSUE: Tile disapearing

### ISSUE THREAD

**Issue by Snufx** [StrangeLoopGames/EcoIssues#9538]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
move around the world and some chunk are not load

**Expected behavior:**
all chunk load around the player

**Actual behavior:**
some chunk are not load and never loadn
**Do you have mods installed? Does issue happen when no mods are installed?:**
some chunk are not load and never load

**Comment by BlazeGuy2** [comment]
Couldn't reproduce
