### ISSUE TITLE
Bobbing up and down in the water is a weird automated thing which might cause issue for people susceptible to flashing 

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9540]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
float in water and do nothing

**Expected behavior:**
just sit there doing nothing

**Actual behavior:**
it seems to run a weird animation, you start off stationary then you bob up and down above the water then that stops goes back to stationary then you bob up and down under the water, then this all repeats.

![insta](https://user-images.githubusercontent.com/29383891/46026340-08a5e880-c0e3-11e8-9ed7-a0ed4d45f143.gif)

Fullsize video is also available 
https://drive.google.com/file/d/1Gumpmb77s-jZRTrMni1xTEI_bVOtupGU/view?usp=sharing

**Comment by D3nnis3n** [comment]
This probably simulates waves.

**Comment by Conchipedia** [comment]
have noticed this seems to have gotten worse slightly the more i travel in the water from island to island, luckily for me i don't suffer from epilepsy but at times it does get really close to the type of flashing that may bring on seizures

**Comment by SlayksWood** [comment]
8.1.3 
The wave effect has remained, but you rarely get under water during a swimming. You can also hold the spacebar clamped to never go under the water while swimming.
Seems fixed.
