### ISSUE TITLE
If the user uses any tool on a stockpile, the resource is getting collected automatically.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9541]
Description: When the user selects any tools and left clicks on the stockpile and if it has any resource in it, it gets collected automatically.

STR:
1. Start the game.
2. Create/Join a world.
3. Place a stockpile and put any resource in it.
4. Equip any tool in your quickslot.
5. Left click on the stock pile and observe the issue.

Actual Result: The player is getting the resources stored in the stockpile when a tool is used.

Expected Result: Nothing should happen unless the player interacts with it manually.

Screenshot:
![screenshot 83](https://user-images.githubusercontent.com/43132426/46029278-92b87600-c110-11e8-89ec-97054a672c6e.png)

**Comment by seccombew** [comment]
By design.
