### ISSUE TITLE
Randomly, the butterfly sometimes passes through objects.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9542]
Description: It has been observed that the butterfly sometimes passes through buildings and structures.

STR:
1. Start the game.
2. Create/Join a world.
3. Place or construct a building/structure.
4. Have a butterfly spawn near it.
5. Observe the issue.

Actual Result: The butterfly has no collision and is able to pass through objects.

Expected Result: The butterfly acts as part of the world environment but for giving a realistic feature it should not be able to pass through things.

**Comment by johnkslg** [comment]
We'll just accept this for now.
