### ISSUE TITLE
The world breaks after playing sometime.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9545]
Description: The world breaks as certain areas disappear and it appears as though the player is walking on air. This stops if the player restarts the game.

STR:
1. Start the game.
2. Create/Join a world.
3. Play the game for sometime.
4. After sometime, (2+ hours) the world starts to break.

Actual Result: After some playtime, the world has some portions of it disappear.

Expected Result: The world/connection should refresh as this may happen due to network fluctuation or poor network connection.

Screenshot:
![eco 25-09-2018 22_56_12](https://user-images.githubusercontent.com/43132426/46031767-7835cb00-c117-11e8-8c78-639d6aa18fea.png)
![eco 25-09-2018 22_56_29](https://user-images.githubusercontent.com/43132426/46031768-78ce6180-c117-11e8-897c-28ce836c7990.png)
![eco 25-09-2018 22_56_38](https://user-images.githubusercontent.com/43132426/46031769-78ce6180-c117-11e8-8402-09470dd8693a.png)

![eco 25-09-2018 23_09_17](https://user-images.githubusercontent.com/43132426/46032139-6acd1080-c118-11e8-8819-b6ca10f0f2e4.png)
![Uploading Eco 25-09-2018 23_10_07.png…]()

**Comment by beastyn** [comment]
@vigneshjuego is this still actual for you?
Looks like chunk loading problem.
Please reopen if this is actual and provide your log files
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files
Thank you!
