### ISSUE TITLE
USER ISSUE: "none" in environment data cetegories

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9554]
**Version:** 0.7.8.0 beta master-fc837d29 debug

![default](https://user-images.githubusercontent.com/4980243/46082302-79163d80-c1a7-11e8-91a5-a0a0158a502d.png)

Same on
**Version:** 0.7.8.0 beta staging-b7709677
![default](https://user-images.githubusercontent.com/4980243/46082473-d8744d80-c1a7-11e8-9a0e-7617cc87934c.png)
![default](https://user-images.githubusercontent.com/4980243/46082503-ea55f080-c1a7-11e8-80d0-d838fa60c293.png)

**Comment by elfl0rd** [comment]
Happens periodically, not every time

**Comment by SeanAtr0n** [comment]
still happening on staging

**Comment by BlazeGuy2** [comment]
Note: Skipping Tutorials fixes this, looking into why.

**Comment by BlazeGuy2** [comment]
Merged in fix
