### ISSUE TITLE
[beta 7.8.0 b7709677] Error message when trying to log into the same server with two clients open should be more informative

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9557]
Screenshot: 
<img width="1357" alt="bug1" src="https://user-images.githubusercontent.com/25908592/46101331-f0f65f00-c1cb-11e8-9cf5-8ae3ebaf6646.png">

**Comment by sidjuego** [comment]
This bug is also related to #9585 as it is the same popup. I have fixed it so the changes should reflect here too.

**Comment by johnkslg** [comment]
Marking fixed!
