### ISSUE TITLE
[beta 7.8.0 b7709677] Sorting for match does not work

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9561]
When you sort for the "match" of an server this will not work, the other sorting features do work.

**Comment by johnkslg** [comment]
This is in the server browser when you do New Game, youll see match scores on servers, and should be able to sort them by clicking them.

**Comment by sidjuego** [comment]
@D3nnis3n 

**Disable the filter for "same version" on your testing client** -> Should public server set to true under Network->Config?

**Comment by D3nnis3n** [comment]
You don't need your own server to test this. When you use your client and disable the filter for "same version" you should be able to see all the public servers available for eco on other servers - which should be enough to see some with a match that you can sort and see it does not work.

**Comment by D3nnis3n** [comment]
Here, a video: https://drive.google.com/open?id=1csbYPA8yrLmiyT75HvgA3LLziCxeSoWy

**Comment by sidjuego** [comment]
Ah that makes it even more trickier to find out. Probably @johnkslg could shed some light in here.

**Comment by seccombew** [comment]
@D3nnis3n informed us issue is not resolved.

**Comment by BlazeGuy2** [comment]
Fix merged in.
