### ISSUE TITLE
[beta 7.8.0 b7709677] Can't get items with left click

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9563]
1. Put the starter tomatoes into your empty starter stockpile
2. Try to get them back with left click as the game suggests you can
3. See it doesn't work.

Does not work for any items as far as i can see.

**Comment by Spydarlee** [comment]
What's the desired behaviour here, @johnkslg? The previous code only tried to add storage items to the Carried inventory despite the UI tooltip suggesting anything can be picked up with a left-click.

I've submitted a pull request that also tries to add items to the Backpack inventory if possible, which works for tomatoes, etc. But let me know if that's not how we want to handle this.

**Comment by johnkslg** [comment]
Fixed
