### ISSUE TITLE
Items falling through ground

### ISSUE THREAD

**Issue by goose2821** [StrangeLoopGames/EcoIssues#9564]
Steps to Reproduce:
1. Go underground (Might work above ground, haven't tried yet)
2. Mine a lot of blocks without picking anything up
3. Watch as items disappear
4. Go above ground to see items falling from the sky

Expected Behavior: Items fall on ground and nothing special happens

Actual Behavior: Item rain that never seems to stop, items occasionally land on ground and are able to be picked up

**Comment by SeanAtr0n** [comment]
7.8

**Comment by espoire** [comment]
This problem is happening again as of 0.8.0.4.

**Comment by espoire** [comment]
It also rarely happens with felled trees (typically small discs of old growth redwood, in my experience.)
