### ISSUE TITLE
[beta 7.8.0 b7709677] Environment Categories are named "none"

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9566]
All environment categories are marked "none" instead of "Animals", "Pollution" and so on.

<img width="322" alt="bug2" src="https://user-images.githubusercontent.com/25908592/46104674-4171ba80-c1d4-11e8-9a41-a545b4238a9a.png">

**Comment by D3nnis3n** [comment]
After several restarts this suddenly works again. :/

**Comment by elfl0rd** [comment]
dupe https://github.com/StrangeLoopGames/EcoIssues/issues/9554

**Comment by Nanders** [comment]
duplicate of #9554
