### ISSUE TITLE
[beta 7.8.0 b7709677] Claiming Land Tutorial does not work

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9567]
1. Get the Claim Paper and Claiming Stake
2. Use up all your claims, see that it hasn't finished.

I think this is related to this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/9527

**Comment by elfl0rd** [comment]
dupe https://github.com/StrangeLoopGames/EcoIssues/issues/9535

**Comment by D3nnis3n** [comment]
Sorry, just doing the QA sheet and input my issue there, if they want it changed, please leave a note.

**Comment by seccombew** [comment]
Closing as dupe
