### ISSUE TITLE
[beta 7.8.0 b7709677] Foraging tutorial does not show up

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9569]
I tried restarting the tutorial several times but the foraging tutorial did never show up, even though i picked up different kinds of plants and had the other tutorials finished and not finished in another try.

**Comment by elfl0rd** [comment]
as i know you need loose calorias.

**Comment by D3nnis3n** [comment]
Did that, too.

**Comment by D3nnis3n** [comment]
Shows up when you PLANT something.
