### ISSUE TITLE
Proposing when against the law doesnt display error

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9570]
To repro: try to propose a law when youre not a citizen
It will prevent you and the eco server will return a message 'you can not violate law citizenship'
This message is never displayed in the webpage.

**Comment by seccombew** [comment]
@wolfgangmeyers Take point on this, under @rainfarmer 's supervision.

**Comment by johnkslg** [comment]
@rainfarmer This should be something the web team fixes, related to red-bar issue

**Comment by rainfarmer** [comment]
fixed https://github.com/StrangeLoopGames/Eco/pull/3529
