### ISSUE TITLE
[beta 7.8.0 b7709677] Server does not restore backup

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9578]
I did:
1. Set backup time to 0,1 - got a backup after a while.
2. Shut down the server.
3. Create a text file called "Game.eco", made sure the ".txt" is gone and overwrite the original file with it.
4. Started up the server
5. Instead of taking the backup (as he already did serveral times on our 7.7 server) it created a new world.

**Comment by pamduncan** [comment]
Most backups are saved as .eco files not .txt,  If the file was not compressed correctly the server will not recognize it as a game file to load.  You can also use other names for your saved world by changing the name in the storage file so it does not always have to be Gme.eco but can be any name .eco  The .eco files in storage are compressed files and while you can operate on the with winzip as an archive they almost never compress where the server will recognize them if you zip them back up again so 'open archive' is a better method if you need to work on the saved world.  Backups are saved to a folder for each backup and the backup file is a .eco not a .txt file.  If any changes have been made to the .db it will be in the backup folder too.  Sometimes you will have a folder with just the .eco file in there.  Not sure why you had a file with a .txt as extension, never seen that happen but if it was a .txt I wonder if it was not saved correctly to backup.

**Comment by D3nnis3n** [comment]
Hey Pam,
i was deliberatley pretending an empty text file to be the Game.eco file, so that on startup it would be recognised as corrupt and the server should then automatically use the last backup instead. That is the intended behaviour the server did not follow, hence this bug report.

I did not try manually if the backup was okay, though, so i'm going to do that later to verify on this issue.

This is one issue of several ones while doing QA tests for slg which i have been asked for, e.g. nothing is wrong on my own server.

**Comment by D3nnis3n** [comment]
After checking pams suggestion i found out that the backup i used to test was corrupted. I tried again with a new test setup and two new backup available and the server did - as it is expected to do - use the last backup and started successfully.  This issue is probably invalid thereof, so feel free to close it.

(You could probably expand on this though by telling the user that the backup is corrupted, too and cannot be used and there is no working backup found)

**Comment by johnkslg** [comment]
@Pradoxzon can you verify this is fixed with your latest PR? Not sure if its the same problem or not.

**Comment by D3nnis3n** [comment]
@johnkslg No, his pull request was for making the backup descriptions easier to understand and to adapt the backup functionality more to what a user would expect to happen.

This issue here is non-relevant as the server DOES restore a backup - when that is not corrupt, too. If it is, it just creates a new world, so a nice thing to do would be to notice the user that the backups available are corrupted, too.

**Comment by Pradoxzon** [comment]
@johnkslg It is a different issue, but I can make sure this gets fixed.

**Comment by Pradoxzon** [comment]
Added support for restoring from multiple backups if the most recent backup is corrupt.
Also added a log entry to notify players if all the available backups are corrupt.
