### ISSUE TITLE
iron\copper pipe have incorrect placing preview.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9579]
**Version:** 0.7.8.0 beta staging-b7709677
![20180927124128_1](https://user-images.githubusercontent.com/4980243/46137710-e0d59280-c252-11e8-9aeb-d1889b5268c2.jpg)
![20180927124146_1](https://user-images.githubusercontent.com/4980243/46137711-e0d59280-c252-11e8-9376-0f895e28cf75.jpg)

**Comment by seccombew** [comment]
Faded by design.

**Comment by elfl0rd** [comment]
Um, wrong color - design?

**Comment by elfl0rd** [comment]
It looks as placing steel pipes everytime, maybe low prior, but looks strange and incorrect.

**Comment by elfl0rd** [comment]
As i see it's fixed in master.
