### ISSUE TITLE
Building in deep water on Singleplayer or Proper Server gives unusual Problem that a User cannot Stop from happening

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9580]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
swim down to a **DEEP** part in the water and then place blocks of **ANY** type from sea bed to the surface using either a hammer or devtool.

**Expected behavior:**
have no trouble placing or removing blocks

**Actual behavior:**
The blocks placed will **STOP** being able to be placed at a certain point, the blocks below can be removed BUT the last placed block will not remove or any other block can be placed on top of this, but blocks to the side of the Last placed block can be added but they also will **NOT** be able to be removed.

i have found as Admin that if i do /level 5,5,WaterBlock close to the irremovable blocks it wakes up this chunk but not sure **HOW** to get the underwater chunk to wake up as a user.

![snap2976](https://user-images.githubusercontent.com/29383891/46147831-7de9f880-c25e-11e8-8f94-e811ec3c328f.png)
Also i have found that this happens in a Proper Server if i hit the **STUCK** block the Client is detecting that there is a block there and giving me blocks to carry (no limit on how many as you can see above i am carrying 46 when maximum is 15) **BUT** if i try to place these imaginary blocks they just disappear.

This is a very difficult Problem to get around as a user, somehow they have to work out **HOW** to wake up this chunk of Eco and be able to continue building if they are far way from land they will have to make a path of blocks to this point in the world then build down and **HOPE** that this fixes the problem!

**Comment by Conchipedia** [comment]
This is getting more annoying as time goes on, as now i am dropping Tailings into this hole and they sometimes just hang in the water where the sleeping Chunk is (then i'm having to get an Admin come and do a /level 1,1,WaterBlock to wake it up again even a devtool won't wake it up).
Never had this problem before when building underwater pre 7.7, Is there a reason why now Underwater blocks are asleep and not letting players or admins (with devtool) place blocks down?

**Comment by Conchipedia** [comment]
this is the same problem and im dropping tailings into the sea (its our Dump area for them as trying something **new**) and as you can see from this snapshot they drop to the sea bed **BUT** they leave a gap )and they **are** there just invisible)
![snap3075](https://user-images.githubusercontent.com/29383891/47521697-96642780-d88b-11e8-9974-88a02196b06f.png)
now i will take The Top one out of the gap and then post another screenshot (they should reappear)
![snap3076](https://user-images.githubusercontent.com/29383891/47521813-e511c180-d88b-11e8-9b11-4a7f26a49960.png)
![snap3078](https://user-images.githubusercontent.com/29383891/47521842-fa86eb80-d88b-11e8-9d9f-d422baf15f92.png)
![snap3079](https://user-images.githubusercontent.com/29383891/47521862-07a3da80-d88c-11e8-9159-f46d113e4787.png)
![snap3080](https://user-images.githubusercontent.com/29383891/47521925-30c46b00-d88c-11e8-8dd4-30fa3aff4f71.png)
![snap3081](https://user-images.githubusercontent.com/29383891/47521926-315d0180-d88c-11e8-93b0-8884e6dfcddf.png)

this is very annoying and extremely weird

**Comment by SeanAtr0n** [comment]
please post your logfile if you haven't restarted the game client yet

`%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

I'm guessing you have a few broken chunks and there should be some error msgs in the output log

**Comment by Conchipedia** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2516483/output_log.txt)

**Comment by Conchipedia** [comment]
but the chunks seem to fix themselves once i wake them up, by placing stuff near it and removing it again

**Comment by Conchipedia** [comment]
still getting this happen in 0.7.8.8 maybe its just me being the ONLY one that builds in water that is noticing how annoying this is

**Comment by SlayksWood** [comment]
check in 8.1.4 all right. Was fixed in #11408
![image](https://user-images.githubusercontent.com/45708377/56945883-45cad100-6b31-11e9-8641-6e404e2e632c.png)
