### ISSUE TITLE
USER ISSUE: Meteor Blowing up the World gives negative numbers for All types of Trees

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9581]
**Version:** 0.7.7.2 beta

![snap2924](https://user-images.githubusercontent.com/29383891/46148427-f604ee00-c25f-11e8-9f44-39610746e700.png)

**Comment by redwyre** [comment]
Confirmed 0.8.1.4

![image](https://user-images.githubusercontent.com/431728/56878752-fa64e400-6a98-11e9-9ad6-7116d1a5af16.png)

**Comment by TwixterZ** [comment]
tested on 9.3.0 beta staging - 1955 

changes happens to number of species in the world
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/b7e812ee-cfba-49f0-9221-0d93dab42d32)

but no negative tree species number
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/628c5125-de31-4a84-9554-27c438000931)

will close this issue for now, if problem arises again please re-open this issue
