### ISSUE TITLE
USER ISSUE: Can't connect to local server

### ISSUE THREAD

**Issue by xzereha** [StrangeLoopGames/EcoIssues#9586]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Succesfully connect to a localy hosted server
Disconnect from that server
Try to reconnect

**Expected behavior:**
Being connected to the server	

**Actual behavior:**
Infinite connection loop and on the serverside "NewClient xxx" is in the connected list instead of the actual Steam namen
**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods are used

**Additional information**
The server it running on a different port then standard "4000-4001".
The issue has appeared several times in the last two days.
The server can be connected to over the internet and by other computers on the local network just not on the computer that hosts it.
The problem is not constant, I have been able to connect several times and have never been disconnected by the server.

**Potential solution**
Restarting steam seems to fix the problem. Bug with the server authentication?

**Comment by SlayksWood** [comment]
Checked on 8.2.7. Wasn't able to reproduce. If it happens again, please reopen.
