### ISSUE TITLE
[beta 7.8.0 b7709677] Mow contract clause does not detect mown grass correctly

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9587]
See the screenshot, the block the error tells to me that is not mown is indeed mown as i can't cut it anymore. Am i supposed to remove it completly by digging? That's not what "mowing" means.

<img width="1352" alt="mowlawn" src="https://user-images.githubusercontent.com/25908592/46158535-5dca3180-c27e-11e8-9b1e-5ccb565ee066.png">

**Comment by Deantwo** [comment]
Incorrect title, might want to rename it to say "Contract" instead of "Law".
