### ISSUE TITLE
[beta 7.8.0 b7709677] Contract does not automatically fail after it has expired

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9588]
<img width="1055" alt="nofail" src="https://user-images.githubusercontent.com/25908592/46159841-99b2c600-c281-11e8-9e9c-745d60de79e1.png">

**Comment by Pradoxzon** [comment]
Fixed

**Comment by D3nnis3n** [comment]
@Pradoxzon 
Could you look into this, it says the giver of the contract marked the contract as failed, which is not the case:
<img width="871" alt="contractfail" src="https://user-images.githubusercontent.com/25908592/47263653-aedbe700-d505-11e8-902c-47dd114b95ff.png">
