### ISSUE TITLE
Deeds way too many being created and deed zone color issue.

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#959]
way too many deeds being created over and over again every time you place a item down and pick it back up again along with old deeds not disappearing.

even if they did disappear I have 15 storage chest and deed to each one and I cant remember when looking at the deed which one belongs to which one any more the cords do not help for this because i cant remember each cord for each chest in same building.

also I had land markers, and I put my deed in chest but with land markers latter on i for got to pick up the deed but i did pick up the other land markers and use them it created anther deed which i had to unclaim that land on that deed and then get other deed and reclaim the land.

now i am stuck with a land deed that has 0 land attached to it ?

also with the property deeds zones is there way to change the colors- i am color blind and i cant see the green on green very well on the map..

**Comment by L33m4n123** [comment]
To add to this, there is a simliar bug with the wooden carts.

If you place a cart down you will get a deed, however if you pick it back up the deed stays in existence and you will get a new deed once you place down the cart again. With the current issue, that you sometimes can't move the cart and thus have to destroy it and place it down again I currently have arrount 20 deeds for one cart

**Comment by MarjieAVolk** [comment]
Deed problems fixed in 5.5.  I'll create a separate feature request about changing property colors
