### ISSUE TITLE
[beta 7.8.0 b7709677] "Receive Permissions" dropdowns only show "Bucks"

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9590]
See the screenshot, all of the dropdowns only show "Bucks" but after you selected the "correct bucks" you can see the real words. Related to: https://github.com/StrangeLoopGames/EcoIssues/issues/9160
<img width="718" alt="bucks" src="https://user-images.githubusercontent.com/25908592/46160395-e9de5800-c282-11e8-95b7-e9b4d1ae7ef0.png">

**Comment by sidjuego** [comment]
This is occurring as the text component is not referred to that field, as a result it is taking up the default value , i.e, bucks. 
As #9160 has the same symptoms, I have fixed it too.

**Comment by D3nnis3n** [comment]
This issue still is not resolved in 7.9.1 - reopening therefore.
