### ISSUE TITLE
USER ISSUE: Just mining a tunnel and the login token changed

### ISSUE THREAD

**Issue by thimes** [StrangeLoopGames/EcoIssues#9592]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
No idea, I was playing and the game just decided my login token changed. I'm on Steam, so I don't know what the steam sync rocess is, but it seems like it might have a race condition in there somewhere, we'll see what it looks like when I go back in... You have to fix the hand carts, when the terrain blinks in and the cart gets stuck in a tree, that's hilarious but frustrating as hell!	

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Login token changed.

<size=60.00%>Steam is not responding.</size>
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Login token changed.

<size=60.00%>Steam is not responding.</size>
```

**Comment by johnkslg** [comment]
This means someone logged in as you. Change your password?
