### ISSUE TITLE
Server parameter names and values need localizing

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9597]
![image](https://user-images.githubusercontent.com/3536496/46235622-143a1f00-c330-11e8-835c-7292c64f7ead.png)

I imagine this will be done by creating a custom renderer for the PropertySheet control, that localizes the text before displaying it.

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/46235664-4ba8cb80-c330-11e8-9409-46af66034a09.png)
These too

**Comment by Spydarlee** [comment]
Looks like this has mostly been setup already, but there are quite a few bits of text that weren't being passed through the localizer so I've hooked up everything I could find that was missing. 👍 

![image](https://user-images.githubusercontent.com/553695/51332012-d5f97480-1a72-11e9-9db6-d1f966034e79.png)
