### ISSUE TITLE
Admin option to remove claimed land

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#960]
This seems to become a more and more common issue where people grief by claiming land around other players and log off to never come back. I believe that this should be implemented pretty fast since this is becoming more and more common 
 as this example :
http://ecoforum.strangeloopgames.com/topic/1260/server-how-to-remove-players-from-the-land-they-have-claimed-harassement

**Comment by midn8t** [comment]
would be nice to have this ability - it also be nice if for a server option where if people do not log on for x amount of days the land returns to private and the user is wipped

**Comment by noblackthunder** [comment]
working on it .. kick command ., ban command and generally more admin commands right now

**Comment by metachronism** [comment]
a command for this (/unclaim) was added a bit ago
