### ISSUE TITLE
USER ISSUE: heavy stuck

### ISSUE THREAD

**Issue by Tekknolf** [StrangeLoopGames/EcoIssues#9604]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
please unstuck me , the command unstuck doesnt work

**Expected behavior:**
unstuck me

**Actual behavior:**
n
**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by elfl0rd** [comment]
ask your server owners\admins.
