### ISSUE TITLE
USER ISSUE: Constant Timeout Connections

### ISSUE THREAD

**Issue by Deygus** [StrangeLoopGames/EcoIssues#9608]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Join a server
2. Play game for roughly up to 1 hour or longer
3. And at some point the server will disconnect you and say you lost connection
4. Then you rejoin the server later after waiting awhile for it to come back online
5. Same thing happens again within the next 15-30 minutes

**Expected behavior:**
I should be able to play this game most the day without losing constant connection to server. This is still a big issue and has not been solved.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by Deygus** [comment]
PS - No mods are installed

**Comment by SlayksWood** [comment]
Checked on 8.2.7. Wasn't able to reproduce. If it happens again, please reopen.
