### ISSUE TITLE
USER ISSUE: Loading a Save

### ISSUE THREAD

**Issue by Firestar000** [StrangeLoopGames/EcoIssues#9609]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
I started a server, game A,  i exited game A,  and loaded game B (server is still running), even after loading game B, game A loaded up.

**Expected behavior:**
Should have loaded my other map.

**Actual behavior:**
Opened the server map.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Opened the server map.

**Comment by elfl0rd** [comment]
For this, you need different server copy (and config files, ofc.)
singleplayer game ANYTIME use 3000\3001 ports.

**Comment by Firestar000** [comment]
If I am using my computer to run the server and my game.  I changed the
ports to 4000/4001.  When I do this the server doesn't show for anyone.
And I'm using the server from steam and I've also tried the server from
strangloop sight
