### ISSUE TITLE
Typo in SolarPanels (need space)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9614]
![default](https://user-images.githubusercontent.com/4980243/46260432-7771b000-c4ee-11e8-8700-447ba97f9c36.png)
https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#52081

@Nanders

**Comment by Nanders** [comment]
Craig can you change this in the CSV?

**Comment by D3nnis3n** [comment]
This should also probably be called "Solar Generator", as the recipe is called like this?

**Comment by D3nnis3n** [comment]
See this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/9123
