### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by lewismoten** [StrangeLoopGames/EcoIssues#9616]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
0. I am a noob. First time playing... create a new character
1. Play for a 6 hours
2. Wait until 1am eastern time
3. connection times out
4. Hit "Continue"
5. Goes to step 3.

**Expected behavior:**
It should have shown a list of servers.
Can not find a status update on the eco website to confirm it is down.

**Actual behavior:**
The following error message popped up:
```
Connection timed out.
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Connection timed out.
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by pamduncan** [comment]
Can you never connect again or can you connect after a while.  If you can get back on the server are you sure you were not trying during a daily reboot of the server?

**Comment by lewismoten** [comment]
I think this is a noob error. I didn't realize this is what happens when a server reboots for the day... The way that it was presented to me, made it seem like a bug in the program and that no other server was available.
