### ISSUE TITLE
Inventory Bug/Glitch

### ISSUE THREAD

**Issue by Leadenigma** [StrangeLoopGames/EcoIssues#9618]
When opening inventory of an object to move items to/from then moving object to another location and reopening will display previous locations linked inventory.

e.g. using a wood cart to move items from storage area- then moving cart to shop (300m away) when opening cart will display storage area stockpiles and not shop storage (also able to move items around from cart and storage stockpiles while at shop)

Has happened with all trucks & carts

It may be linked to the object/item and not the player as I was helping a friend move items from stockpile A to B via a cart on an elevator. I would be at position A filling the cart then send elevator up to him at pos B. He then was able to access all stockpiles within range of my position.

A disconnect/reconnect usually fixes this issue.

Server/Client Ver 7.7.2

**Comment by Nicolausi113** [comment]
It seems you encountered the same phenomena as I reported  #9293

**Comment by D3nnis3n** [comment]
Probably also related to https://github.com/StrangeLoopGames/EcoIssues/issues/9289

**Comment by Leadenigma** [comment]
Indeed they look like the same issue. Tried to do a search but didn't come across those threads. 
Will leave it up for now in case I can offer any additional info.

**Comment by BlazeGuy2** [comment]
Closing as dup.  Feel free to add any info here though, it is linked to the other open issues.
