### ISSUE TITLE
Alpha 5.2 - Current election panel in the browser show nothing

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#962]
Pre-requirement:
- Having a current election.
- Migrating from Alpha 5.1 to 5.2

Steps to reproduce:

1. Click on the Laws button in the ECO game ![image](https://cloud.githubusercontent.com/assets/7052045/21627876/2de034f6-d1e9-11e6-83d4-b756d19e6b28.png).
2. Click on Run for office button ![image](https://cloud.githubusercontent.com/assets/7052045/21627961/be2992a0-d1e9-11e6-8de4-24a92dbcb16e.png). It will open your browser with the Election page of your server (/elections.html?).
3. When the page is loading, you will see the content of the page for a second.
![image](https://cloud.githubusercontent.com/assets/7052045/21628031/413d7382-d1ea-11e6-99a1-982784d08536.png)
4. When the page is loaded the content of the page disappears. Only the green background and the left menu are still showing.
![image](https://cloud.githubusercontent.com/assets/7052045/21628070/9ccf58c8-d1ea-11e6-92e7-0a44257bbe8f.png)

Note:
1. We are currently having an election with three candidates.
2. Every pages under election.html do not load. (current election)
3. When I click on Update Speech, the Update Speech page will not load.
4. For more details about how the server owner migrate from Alpha 5.1 to Alpha 5.2, contact Bacon on Discord Eco's channel.

**Comment by metachronism** [comment]
fixed in 5.3
