### ISSUE TITLE
Campsite Storage will not take crafted Campfire or Workbench

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9620]
**Version:** 0.7.7.2 beta

When trying to Craft a Campfire or a Workbench it does **NOT** go into the actual Campsite (Storage) it puts it into anything else but this, or just sits waiting to be collected.

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/50541798-445abd80-0bbe-11e9-9579-9aa57ca60f82.png)
Looks fixed in master, but internal campsite inventory has loooooooooooooooooooooow priority to place.

**Comment by elfl0rd** [comment]
(happens is master\0.8, closing to new issue)
