### ISSUE TITLE
Master: wolf whisperer shirt cause break

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9621]
**Version:** 0.7.8.0 beta master-e20af174 debug
If you try equip wolf whisperer shirt - debugger receive break
`                #if DEBUG
                // do more expensive computation in debug
                int calculatedWeight = this.inventory.Stacks.Sum(stack => (stack.Item?.Weight ?? 0) * stack.Quantity);

                if (this.weight != calculatedWeight)
                {
                    Debugger.Break(); // *File a bug* This was probably caused by the previous thing you did with your inventory, not the current thing.
                    this.weight = calculatedWeight;
                }
                #endif`

This shirt looks cool, can i own my permanent copy? lol.

**Comment by Pradoxzon** [comment]
DId you use a command to give yourself the shirt or some other item right before you equipped it?

**Comment by elfl0rd** [comment]
yep, but only shirt generate this break

**Comment by elfl0rd** [comment]
yep, looks like give result, closing.
