### ISSUE TITLE
Master: adding world leader in store Authorization prevent server from startup

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9622]
![default](https://user-images.githubusercontent.com/4980243/46306054-d18c7700-c5bb-11e8-99de-87c4e2fc8707.png)
save
shut down server
try to launch it again
then in debugger

> Obj.data.Government = 'Obj.data.Government' threw an exception of type 'System.NullReferenceException'

@johnkslg ?

**Comment by johnkslg** [comment]
Related to #9583

**Comment by elfl0rd** [comment]
maybe no, in this case i add server leader role, but no one assigned in.

**Comment by elfl0rd** [comment]
yes, world leader role.
![default](https://user-images.githubusercontent.com/4980243/46306298-8757c580-c5bc-11e8-9408-bd94ba84793f.png)
