### ISSUE TITLE
USER ISSUE: Cart Crashed Server

### ISSUE THREAD

**Issue by Fikule** [StrangeLoopGames/EcoIssues#9627]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Cart in a single hole
2. Drop Sand on cart
3. Attempt to pull cart out
4. Crash server

**Expected behavior:**
Cart should pop up out of the hole

**Actual behavior:**
Server dies a fiery deathn
**Do you have mods installed? Does issue happen when no mods are installed?:**
Server dies a fiery death

**Comment by D3nnis3n** [comment]
Cannot reproduce, old issue. Reopen if it persists.
