### ISSUE TITLE
Crafting change issue 

### ISSUE THREAD

**Issue by ApophisUKP** [StrangeLoopGames/EcoIssues#9628]
Im trying to add a new crafting thing at the Mortar station, it keeps crashing my server what have i done wrong?

namespace Eco.Mods.TechTree
{
using System;
using System.Collections.Generic;
using Eco.Gameplay.Components;
using Eco.Gameplay.DynamicValues;
using Eco.Gameplay.Items;
using Eco.Gameplay.Skills;
using Eco.Shared.Utils;
using Eco.World;
using Eco.World.Blocks;
using Gameplay.Systems.TextLinks;

[RequiresSkill(typeof(MortarProductionSkill), 1)] 
public class GrindStoneToSandRecipe : Recipe
{
public GrindStoneToSandRecipe()
{
this.Products = new CraftingElement[]
{

new CraftingElement<SandItem>(1f),
};
this.Ingredients = new CraftingElement[]
{
new CraftingElement<TailingsItem>(typeof(MortarProductionEfficiencySkill), 5, MortarProductionEfficiencySkill.MultiplicativeStrategy), 
};
this.Initialize("Grind Tailing To Sand", typeof(GrindStoneToSandRecipe));
this.CraftMinutes = CreateCraftTimeValue(typeof(GrindStoneToSandRecipe), this.UILink(), 5, typeof(MortarProductionSpeedSkill));
CraftingComponent.AddRecipe(typeof(MasonryTableObject), this);
}
}
}

**Comment by elfl0rd** [comment]
Not game issue, try ask in https://discord.gg/eco `#modding`

**Comment by AlphadoJaki** [comment]
@seccombew This issue is demanded by dev (Ket)
See  here for detail:
https://steamcommunity.com/app/382310/discussions/9/3393916911753180023/

**Comment by seccombew** [comment]
@ApophisUKP @AlphadoJaki Thanks for the heads up. @BlazeGuy2 Would you please give assistance.
