### ISSUE TITLE
USER ISSUE: Constand Dissconnects even on LAN

### ISSUE THREAD

**Issue by Mickey69** [StrangeLoopGames/EcoIssues#9629]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Try to play for a few miniutes

**Expected behavior:**
Stayed connected

**Actual behavior:**
Constant disconnect (lan) after 2-10 mins play time
**Do you have mods installed? Does issue happen when no mods are installed?:**
Constant disconnect (lan) after 2-10 mins playtime

**Comment by SlayksWood** [comment]
@Mickey69 
Do you have this problem now?
If it happens again, please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Closing for now, please reopen the issue when it occurs again.
