### ISSUE TITLE
Spent skillpoints not displaying correctly

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#963]
![image](https://cloud.githubusercontent.com/assets/3536496/21628822/56ba378a-d1d7-11e6-922f-dea0f04a2c5e.png)
Says i spent zero but its wrong

**Comment by metachronism** [comment]
needs subscribe and a refresh, pretty sure the number is there on the client

**Comment by metachronism** [comment]
pretty sure this is fixed now, cant repro
