### ISSUE TITLE
Loc. strings seems not used - Choose a World to Join.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9630]
![default](https://user-images.githubusercontent.com/4980243/46382606-77bba800-c6b4-11e8-9bdc-726bf9e2e3c6.png)
https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#52361

@Nanders

**Comment by Nanders** [comment]
This should work now with https://github.com/StrangeLoopGames/Eco/pull/3442

(I added it to crowdin before the PR went through)

**Comment by elfl0rd** [comment]
Ok! :P
