### ISSUE TITLE
Beds are buggy

### ISSUE THREAD

**Issue by Ket-SLG** [StrangeLoopGames/EcoIssues#9632]
It toggles off the UI in a weird way. 

Also when you try to finish sleeping you can't leave the bed and there are some issues with the text not going away.

https://www.youtube.com/watch?v=HgQdTeCOg_4

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9571

**Comment by johnkslg** [comment]
Fixed in master and staging!
