### ISSUE TITLE
Weird Bug with Coal and Charcoal in Power Tab for Furnace being taken by Furnace as Ingredient

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9638]
**Version:** 0.7.7.2 beta

Just had this appear that the coal that is placed in the Power Tab of a Blast Furnace was being taken by the same Furnace to fill the order for steel which is short of coal as ingredient, This only Fixed itself when another player (gave permission to) placed coal in power tab of the Furnace, (i was having problems getting it to accept the coal i was placing in) now that the Player did it for me this BUG fixed itself

**Comment by Khalysto** [comment]
I definitely need help with this problem as well. Our smith has blast furnaces set up with 999 steel queued, but we can't make any progress because the blast furnace keeps eating its own fuel for the steel recipe. H4LP!

**Comment by Conchipedia** [comment]
had to move Blast Furnace again, bug appeared again, getting someone else putting Coal in Power Tab didn't work this time, Had to have someone tweak Strange Fuel to work in Blast Furnace, sort of covered for now until i can get enough Coal to fill the Order then i can place Coal back in as Fuel.

i think whats happening is that if you look under Storage Tab it sees it's own Power tab there and just takes the coal as it thinks its storage

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/9241

**Comment by elfl0rd** [comment]
Bump =|

**Comment by Conchipedia** [comment]
Coal is still being taken by Blast Furnace as ingredient in latest Steam version
![snap4074](https://user-images.githubusercontent.com/29383891/52262203-bf349800-2923-11e9-9b5b-dd8685732133.png)

**Comment by elfl0rd** [comment]
confirm, but not at first...

**Comment by Splutty** [comment]
Same issue, not been resolved. It's really quite annoying because of the constant breakdown of the furnace, and repeatedly requeuing steel really isn't a solution.

**Comment by Demosthenexx** [comment]
Confirmed in 8.0.3 on our game too. We have a large standing steel order, and it keeps pulling the fuel out of the furnace the job is executing in.

**Comment by Conchipedia** [comment]
as far as i can see what has been happening is that **power** tab of the Blast furnace has been added to the  **storage** search (or however tables looks at storage links) so no matter if you put **charcoal** or **coal** in the power tab, it is automatically detected by the crafting order as being in Storage and available for use, and seeing as you cannot **unselect** the power tab in its own window like you can everything else it will take the items every-time it runs out of them in normal Storage

**Comment by Conchipedia** [comment]
@Quadbro i see this now says fixed any idea when this will appear in Eco?
