### ISSUE TITLE
Servers with version mis-match still allow attempt to join

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#9641]
WHen you click on a server that is running a version different from the one you have installed it does show the server version on the button that would usually say "Join" if the versions matched.  This used to not do anything if you clicked on it and there was a version mismatch because the versions were not the same..  Now it attempts to log you in and then you get a connection error with no mention of the a version error or mismatch.  This has some players confused that there maybe a problem on their client that they cannot get in these servers but see other people in them and since it allowed them to attempt to connect the fact that the versions are not the same is not realized.

**Comment by beastyn** [comment]
fixed
