### ISSUE TITLE
Tooltips on text not working on main chat

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9643]
![image](https://user-images.githubusercontent.com/3536496/46502026-f3644480-c7db-11e8-90fd-991906cc1ac0.png)
Mousing over these text items should display a tooltip but it doesnt.
For comparison, open the chat log and see that it functions properly there:
![image](https://user-images.githubusercontent.com/3536496/46502070-0bd45f00-c7dc-11e8-974b-686a8e0cbeb3.png)

**Comment by SlayksWood** [comment]
Seems added
