### ISSUE TITLE
USER ISSUE: Steam Trucks Fuel and Storage

### ISSUE THREAD

**Issue by frosty939** [StrangeLoopGames/EcoIssues#9644]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. fill storage with items (bricks and roads noticably, but there are other items. maybe related to items produced by stone?)

2. use stone hammer (or any other tool) to hit the storage area

**Expected behavior:**
you pull items out of the STORAGE compartment

**Actual behavior:**
FUEL is pulled out of the FUEL compartment
n
**Do you have mods installed? Does issue happen when no mods are installed?:**
FUEL is pulled out of the FUEL compartment

**Comment by elfl0rd** [comment]
I think the best solution would be
If user interact (place\pickup) with engine - he place\take fuel.
If user interact with "vechicle stockpile" - he place\take cargo.

**Comment by SlayksWood** [comment]
Checked on 8.3.0 staging-1066. It works good at this moment. Seems fixed. 
Last comment will move to suggestions https://github.com/StrangeLoopGames/EcoSuggestions/issues/868
