### ISSUE TITLE
Missing\broken string - species

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9654]
Unwanted "s" after translate.
![default](https://user-images.githubusercontent.com/4980243/46564398-af725c00-c90f-11e8-9d9b-4c2b11327b63.png)
![default](https://user-images.githubusercontent.com/4980243/46564400-b1d4b600-c90f-11e8-96d9-0a51f2a01917.png)

@Nanders ?

**Comment by Nanders** [comment]
This is because its getting passed through the pluralizer, I'll see what the workaround is

**Comment by elfl0rd** [comment]
It would be very nice if it will work with different languages...
for example, it is necessary for Russian in many situations
1 - диван
2,3,4 - дивана
5,6,7,8,9,0 - диванов
etc...

**Comment by Quadbro** [comment]
Disabled word pluralizer for non-english source strings. Best workaround for now, probably there will be multi-language one in future
