### ISSUE TITLE
Put base-game content from "\Mods\" folder into "\Mods\Native\"

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#9655]
Would make sorting through error logs a little easier, especially when it comes to diagnosing bugs related to bugged mods.

**Comment by pamduncan** [comment]
What would really be the answer is that the modders get consistent about installing tehir mods in a folder with their name or the mods name on the folder.  The big problem is that some mods to overwrite the vanilla game files, and no matter where they were put - just in /Mods/ or in /Mods/Native/ if the mod need to change an vanilla object they would still be editing that vanilla game files no matter where they were.  At this time if if the mod needs to change a vanilla game file it has to, it cannot just add another copy of that file with the same name as you then get namespace errors or errors saying there are two files with the same name.  If a mod does change a vanilla file then there is no way to just remove the mod as some of the mod would have updated a vanilla file and the only way to get that faile back to vanilla would be to reinstall the vanilla files.    It works fine if no vanilla files are touched to just remove the folder called "Mods/NameofMod/"  but no matter where you move the vanilla content if a mod overwrites it you still have the problem of not being able to remove it without reinstalling.

For example, a mod that makes all tools that can carry carry more, or work faster the Mod for that will have to overwrite the tools in question.  In those cases the modder just has the copy and paste installation of the mod copy over the tools in question in the vanilla game.  Those types of mods could not just be in a separate folder and work as the server would fail to load because it would have two tools of the same name,  The mod in that case could be removed only b y getting a fresh copy of that tool back in game - if they just deleted it then that tool would not be in the game at all.

Its very often that when they have a mod in, although they find a folder for that mod in their files and deleted  it there are still problems because the mod did, in fact, change the game file or files and the only way to get them back is a reinstall.  The way mods work at this point it would not really matter what folder the vanilla files were in the same issues with removing mods would still be the same.

**Comment by GophTheGreat** [comment]
Being able to specify load order somehow (i.e. mod folders that load "last" override anything that loaded prior) would fix the problem of mods being unable to override vanilla content.

**Comment by mirasrael** [comment]
Seems we have solution with mod files overwriting on updates. We can use `partial` methods for initialization hooks.
In example we wanna to change Recipe and experience for AdvancedCircuitRecipe:
```csharp
    [RequiresSkill(typeof(ElectronicsSkill), 2)]      
    public partial class AdvancedCircuitRecipe :
        RecipeFamily
    {
        public AdvancedCircuitRecipe()
        {
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "AdvancedCircuit",
                    Localizer.DoStr("Advanced Circuit"),
                    new IngredientElement[]
                    {
                    new IngredientElement(typeof(CopperWiringItem), 4, typeof(ElectronicsSkill), typeof(ElectronicsLavishResourcesTalent)), 
                    new IngredientElement(typeof(GoldWiringItem), 4, typeof(ElectronicsSkill), typeof(ElectronicsLavishResourcesTalent)), 
                    new IngredientElement(typeof(GoldFlakesItem), 10, typeof(ElectronicsSkill), typeof(ElectronicsLavishResourcesTalent)), 
                    new IngredientElement(typeof(SubstrateItem), 2, typeof(ElectronicsSkill), typeof(ElectronicsLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
                    new CraftingElement<AdvancedCircuitItem>(), 
                    }
                )
            };


            this.ExperienceOnCraft = 4;  

            this.LaborInCalories = CreateLaborInCaloriesValue(140, typeof(ElectronicsSkill), typeof(AdvancedCircuitRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(AdvancedCircuitRecipe), this.UILink(), 0.8f, typeof(ElectronicsSkill), typeof(ElectronicsFocusedSpeedTalent), typeof(ElectronicsParallelSpeedTalent));
            this.Initialize(Localizer.DoStr("Advanced Circuit"), typeof(AdvancedCircuitRecipe));

            CraftingComponent.AddRecipe(typeof(ElectronicsAssemblyObject), this);
        }
    }
```

Old way you have to overwrite it:

```csharp
    [RequiresSkill(typeof(ElectronicsSkill), 2)]      
    public partial class AdvancedCircuitRecipe :
        RecipeFamily
    {
        public AdvancedCircuitRecipe()
        {
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "AdvancedCircuit",
                    Localizer.DoStr("Advanced Circuit"),
                    new IngredientElement[]
                    {
                        new IngredientElement(typeof(CopperWiringItem), 4, typeof(ElectronicsSkill), typeof(ElectronicsLavishResourcesTalent)),
                    },
                    new CraftingElement[]
                    {
                    new CraftingElement<AdvancedCircuitItem>(), 
                    }
                )
            };


            this.ExperienceOnCraft = 2;  

            this.LaborInCalories = CreateLaborInCaloriesValue(140, typeof(ElectronicsSkill), typeof(AdvancedCircuitRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(AdvancedCircuitRecipe), this.UILink(), 0.8f, typeof(ElectronicsSkill), typeof(ElectronicsFocusedSpeedTalent), typeof(ElectronicsParallelSpeedTalent));
            this.Initialize(Localizer.DoStr("Advanced Circuit"), typeof(AdvancedCircuitRecipe));

            CraftingComponent.AddRecipe(typeof(ElectronicsAssemblyObject), this);
        }
    }
```

But if we change template to add partial method hook before Initialize:
```csharp
[RequiresSkill(typeof(ElectronicsSkill), 2)]      
    public partial class AdvancedCircuitRecipe :
        RecipeFamily
    {
        public AdvancedCircuitRecipe()
        {
            this.Initialize(Localizer.DoStr("Advanced Circuit"), typeof(AdvancedCircuitRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "AdvancedCircuit",
                    Localizer.DoStr("Advanced Circuit"),
                    new IngredientElement[]
                    {
                    new IngredientElement(typeof(CopperWiringItem), 4, typeof(ElectronicsSkill), typeof(ElectronicsLavishResourcesTalent)), 
                    new IngredientElement(typeof(GoldWiringItem), 4, typeof(ElectronicsSkill), typeof(ElectronicsLavishResourcesTalent)), 
                    new IngredientElement(typeof(GoldFlakesItem), 10, typeof(ElectronicsSkill), typeof(ElectronicsLavishResourcesTalent)), 
                    new IngredientElement(typeof(SubstrateItem), 2, typeof(ElectronicsSkill), typeof(ElectronicsLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
                    new CraftingElement<AdvancedCircuitItem>(), 
                    }
                )
            };


            this.ExperienceOnCraft = 4;  

            this.LaborInCalories = CreateLaborInCaloriesValue(140, typeof(ElectronicsSkill), typeof(AdvancedCircuitRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(AdvancedCircuitRecipe), this.UILink(), 0.8f, typeof(ElectronicsSkill), typeof(ElectronicsFocusedSpeedTalent), typeof(ElectronicsParallelSpeedTalent));
            this.BeforeInitialize();
            this.Initialize(Localizer.DoStr("Advanced Circuit"), typeof(AdvancedCircuitRecipe));

            CraftingComponent.AddRecipe(typeof(ElectronicsAssemblyObject), this);
        }

        partial void BeforeInitialize();
    }
```
then you can just add new file to separate directory (i.e. `Mods/My/AdvancedCircuitRecipe.cs`):
```csharp
public partial class AdvancedCircuitRecipe
    {
        partial void BeforeInitialize()
        {
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "AdvancedCircuit",
                    Localizer.DoStr("Advanced Circuit"),
                    new IngredientElement[]
                    {
                        new IngredientElement(typeof(CopperWiringItem), 4, typeof(ElectronicsSkill), typeof(ElectronicsLavishResourcesTalent)),
                    },
                    new CraftingElement[]
                    {
                        new CraftingElement<AdvancedCircuitItem>(),
                    }
                )
            };
            this.ExperienceOnCraft = 2;
        }
    }
```
which will have same effect, but won't be overwritten after update.

**Comment by Thibault-Brocheton** [comment]
Seems cool ! I think you should change the name, including the concept of "custom", so people know they can use these function without causing overlap with default code (and SLG devs make sure they don't use it)

Just wondering if we could have several mods editing the same file, but partial methods allow only one definition.

**Comment by mirasrael** [comment]
@Thibault-Brocheton thanks for feedback. Yes, I'm planning to add hooks where it makes sense. Not only recipes.
For multiple mods modifying same file - I don't think it is good to allow this anyway. It is actually why partial methods only allows to have one implementation (while technically it is possible to have multiple).
For multiple mods there is undefined order of partial method execution. So they can overwrite recipes and other properties multiple times with random mix of final result. If you really wanna to combine multiple mods then you can make partial hooks in one of mods, call them from root hooks and then use these new hooks in other mods :)

**Comment by Thibault-Brocheton** [comment]
@mirasrael on a technical point of view, I think you're right
On a player / admin point of view, I'm not so sure. 

For instance, a player would go on a mod website, find some mods that interest him, and install them!. He won't pay attention if two mods he downloaded are implementing the same ModsPreInitialize of the same object.

But I'm not sure we can do anything about this. Modding a server will still require basic knowledge of c# and ability to fix compilation issues

**Comment by IcedForge** [comment]
Changing this from 9.3 -> 9.4 as per discussion on discord. 
For OP World Objects and upgrade Modules now have their hooks properly working.(9.3 update)
We are still in the situation of that you cannot edit attributes via this system but you can add new ones with partials.

**Comment by SlayksWood** [comment]
I checked a couple of recipes with override, it seems to work well.
@IcedForge Can you check it from your side?

**Comment by IcedForge** [comment]
checked and verified.
