### ISSUE TITLE
Some mined stones seem to teleport themselves to the top

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9656]
See the screenshots, we had stones being spawned in the middle of our capital roads since some days and i noticed that people are digging below and have stones lying there, so the only possible explanation how they got there is they teleported up - especially as you can't move the stones that you still have to "mine" a second time, to get two stones out of them.

<img width="1564" alt="stones" src="https://user-images.githubusercontent.com/25908592/46575497-60cbcd00-c9b6-11e8-8151-9b8f6435db14.png">
<img width="1920" alt="stones2" src="https://user-images.githubusercontent.com/25908592/46575489-41cd3b00-c9b6-11e8-86cc-82165d160b6d.png">

**Comment by Nicolausi113** [comment]
Yes, often experienced – and these #7365 #7575

**Comment by D3nnis3n** [comment]
In opposite to 7365, noone used an exacator there and in opposite of 7575 only very little of the stones teleport to the above, while a hell lot more is lying underground. There seem to be server teleport to top bugs though, including with vehicles and players.

**Comment by seccombew** [comment]
Dupe
