### ISSUE TITLE
Chat gets jammed and unusable while working (mining, scything...)

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9661]
Version: v0.7.7.2-beta

Steps to reproduce:
have chat open and do a work like mining or scything (these are the worst).

Expected behavior:
I should be able to notice the chat while working.

Actual behavior:
Chat gets spammed with notifications and is nearly unusable.

This has changed since v7.6 in any way and is in a fashion I don’t appreciate. The text should appear in a separate window, if at all, or in the middle screen, as it is if chat is switched off. Please improve it to a usable form.

![chat](https://user-images.githubusercontent.com/38510829/46578117-88428a00-c9f6-11e8-9932-4e1f416d32a9.jpg)

Chat off
![chat3 snip](https://user-images.githubusercontent.com/38510829/46578120-aad4a300-c9f6-11e8-9cce-b2f219af4948.jpg)

**Comment by TemporalWolf** [comment]
At the very least adding it as a channel so it can be toggled off would be stellar.

**Comment by elfl0rd** [comment]
Hmm... @D3nnis3n looks refer to https://github.com/StrangeLoopGames/EcoIssues/issues/3067 and https://github.com/StrangeLoopGames/EcoIssues/issues/10295

**Comment by SlayksWood** [comment]
merged with #10295
