### ISSUE TITLE
USER ISSUE: own region bolcked :-(

### ISSUE THREAD

**Issue by Dibbertaler** [StrangeLoopGames/EcoIssues#9662]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
?

**Expected behavior:**
own region can be used

**Actual behavior:**
all own region was blocked (red) :-(n
**Do you have mods installed? Does issue happen when no mods are installed?:**
all own region was blocked (red) :-(

**Comment by Deantwo** [comment]
I think I am missing some context here. What "region" are you talking about?

You mean public servers from your country?

**Comment by Dibbertaler** [comment]
Hello, yes the local "single player mode" I starting my worls and have no access right anymore. I don't know why? Thanks for you support

**Comment by Dibbertaler** [comment]
oh ... no mods .. only the normal standard installation

**Comment by Dibbertaler** [comment]
![ingmars_home](https://user-images.githubusercontent.com/43926169/46913646-b04f6180-cf91-11e8-956c-984cbf7cae34.png)

**Comment by Deantwo** [comment]
@Dibbertaler, you are admin on a single player server, so just use the [`/unclaim`](https://eco.gamepedia.com/Chat_Commands#Admin_Commands) admin command.

**Comment by elfl0rd** [comment]
Steam or slg license?

**Comment by Dibbertaler** [comment]
Steam

**Comment by Dibbertaler** [comment]
@Deantow - /unclaim is working :-) field by field but :-( I don't know why it was set to "red" but anyone - thanks for this option
Ingmar

**Comment by elfl0rd** [comment]
Apparently a rare problem I think can be closed. @D3nnis3n

**Comment by D3nnis3n** [comment]
That's up to @BlazeGuy2, he already took the issue and i have heard of such problems earlier.

@Dibbertaler Please add your game save file.

**Comment by D3nnis3n** [comment]
Closing because of missing information, reopen if it reoccurs and you can provide your savegame.
