### ISSUE TITLE
[0.8.1.4] Some changes world when cross Zero point

### ISSUE THREAD

**Issue by torchdragon** [StrangeLoopGames/EcoIssues#9664]
Definition: Prime Meridian, the mathematical seam in the world where the coordinate system wraps from Max X value to 0.

When the player is on the "high side" of the prime meridian (ie, 2500,50,100) looking towards the "low side" (0,50,100), plant graphics are not rendering for tilled/planted plants. The tilled dirt is visible but the plant graphics will not load until the player steps across the prime meridian. Once across the line, all near by chunks appear to update and render plants properly.

**Comment by Deantwo** [comment]
Picture?

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/56654581-1df2ed80-6699-11e9-8439-e0d54d748791.png)
cross zero point and butterflies is missing
![image](https://user-images.githubusercontent.com/45708377/56654630-36fb9e80-6699-11e9-80b8-91941cb81c00.png)
Sometimes lighting changes
video about birds and buterflies which missing: 
Also you can see when Avatar cross zero point he he makes a minor jump

video about plant growth (it's correct):

**Comment by SlayksWood** [comment]
> 1. Staging 1480
> 2. Go across the border from block 1000 to 0 and screen flickers, happens when going across the "border"
> 3. Expected behavior. - Not flicker?
> 4. Actual behavior. - Flickers
> 
> Engimage was able to replicate the issue with me

**Comment by SlayksWood** [comment]
>Visual Glitch - Black screen flicker when passing world boundary. Ashlar under brace corner block graphical glitch.

> Graphical glitch (little black triangles) with ashlar under brace corner when built across world boundary - where third coordinate flips from 0 to 720:
> ![image](https://user-images.githubusercontent.com/48172405/81861804-b8ea8e00-9560-11ea-8912-3cbcac028dd8.png)
> 
> Walking across the world boundary causes the screen to flash black:
> https://drive.google.com/open?id=1knEGkXkdTbGq5dl0D6fc20hjptDxN2m6
> 
> It appears to be linked to black screen flickers reported here: https://steamcommunity.com/app/382310/discussions/4/1753527228527346293/
> 
> I've not found another ticket reporting this.
> 
> A save, with examples of the block glitch at 71,71,1:
> [Save.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4624416/Save.zip)
> 
> Logs:
> [Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4624423/Player-prev.log)
> [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4624424/Player.log)

> Just checked some more - this doesn't appear to affect any other ashlar block forms (not even the top brace corner), but it does affect other ashlar stone types:
> 
> ![image](https://user-images.githubusercontent.com/48172405/81863738-93ab4f00-9563-11ea-9437-b80f359909b3.png)
> 
> ![image](https://user-images.githubusercontent.com/48172405/81862782-21863a80-9562-11ea-856b-55abb213a49e.png)

**Comment by WeaselDog** [comment]
Fixed in update 9.5. Thank you for your submission.
