### ISSUE TITLE
Missed things in "Unclaimed Carts?"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9666]
https://github.com/StrangeLoopGames/EcoIssues/issues/9464

What about deed trading for placed objects?
e.g.
Player 1 place cart and sold his deed to player 2
Player 2 load tailings into cart, move it, then unclaim.

Unclaimed cart looks as result player 1 actions? lol.

It's really possible on roleplay servers with restricted vechicle pickup.

**Comment by D3nnis3n** [comment]
Well, aren't you able to get master running, so you can check yourself? ;P

But i agree, this should not happen.

**Comment by elfl0rd** [comment]
Haha, yes :D 
![default](https://user-images.githubusercontent.com/4980243/46637969-46852100-cb67-11e8-94ff-2aaa125b3027.png)
![default](https://user-images.githubusercontent.com/4980243/46637952-28b7bc00-cb67-11e8-8f69-1b19251ff1a8.png)

would be better display name of creator AND last owner.

**Comment by D3nnis3n** [comment]
Displaying the one who owned it last would be enough.

**Comment by elfl0rd** [comment]
Who placed object is interested information too.

**Comment by elfl0rd** [comment]
e.g. usefull for placed workbenches and other objects on free land.

**Comment by D3nnis3n** [comment]
Yeh, seems useful. For me the main issue was people being able to craft unlimited cheap cars and then filling them with tailings and dump them in the sea without me having any reasonable possibility to know who caused that. A workbench here and there that i can easily remove is not a problem for me.

**Comment by elfl0rd** [comment]
Okay, bloomery+stockpile on free land...
Who place and use it? :)
If _creator_ removed, ofc.
