### ISSUE TITLE
Ramps don't connect to terrain blocks next to them.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9668]
![default](https://user-images.githubusercontent.com/4980243/46626527-4aea1380-cb40-11e8-87a7-ae5c6f5dee61.png)
![default](https://user-images.githubusercontent.com/4980243/46626584-7240e080-cb40-11e8-8ff4-ddcfe6a34607.png)

![изображение](https://user-images.githubusercontent.com/4980243/70460301-07ce5c00-1ac7-11ea-8520-059bd2fff118.png)
![изображение](https://user-images.githubusercontent.com/4980243/70460325-1452b480-1ac7-11ea-80a7-daeb1845fb25.png)

**Comment by elfl0rd** [comment]
From not resolved and closed - https://github.com/StrangeLoopGames/EcoIssues/issues/8674#issuecomment-427931590

**Comment by Deantwo** [comment]
Related to the old half finished mega ramp issue: #8674

**Comment by Deantwo** [comment]
Not fixed

**Comment by elfl0rd** [comment]
This is not vital, but will significantly improve both perception (in many cases) and quality of life.

**Comment by keegan-o** [comment]
I will try just popping ramps over to 'terrain' type at some point during 9.1 dev but I guarantee there are going to be some ugly results.

**Comment by keegan-o** [comment]
Merging this in with a task to re-factor terrain builders, because if I do this without doing that, it will make optimization later impossible.
