### ISSUE TITLE
Ramp place and pickup have HUGE difference and confuse players.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9669]
For place - you have ramp, and place it.
1 ramp - 4 world block.

For pickup, you can pickup one block with shovel, then you cannot pickup next block
![default](https://user-images.githubusercontent.com/4980243/46626757-f6936380-cb40-11e8-870f-38346b4b7af8.png)
You need pickup all 4 block differently.
You cannot place picked up blocks as ramp back.
etc...

It looks as really, really uncompleted feature.

**Comment by elfl0rd** [comment]
From not resolved and closed - https://github.com/StrangeLoopGames/EcoIssues/issues/8674

**Comment by Impyyy** [comment]
Really can't figure out how to lay ramps , cant get them to line up correctly [https://steamuserimages-a.akamaihd.net/ugc/942833891658132260/1033230CAD6259D4548AE53FC9E5981F833AC540/](url)

**Comment by elfl0rd** [comment]
image from link above
![1](https://user-images.githubusercontent.com/4980243/46766573-08b10580-cceb-11e8-87d7-45a8e998c432.jpg)

**Comment by elfl0rd** [comment]
And yes, you can place new ramps trough another blocks, facepalm.
![20181014032313_1](https://user-images.githubusercontent.com/4980243/46919865-529d3280-cfee-11e8-8ee8-340d58b70019.jpg)
![Uploading 20181014032252_1.jpg…]()
