### ISSUE TITLE
Stuck in falling State

### ISSUE THREAD

**Issue by Ket-SLG** [StrangeLoopGames/EcoIssues#9674]
It's possible to get stuck in a falling state if you hit the edge of a block in the wrong way.

**https://www.twitch.tv/videos/320102699?t=01h21m09s**

**Comment by SlayksWood** [comment]
@Ket-SLG 
Do you have this problem now?
Сan you upload video from issue to another source?

**Comment by D3nnis3n** [comment]
Closing for now, open a new issue if this reoccurs.
