### ISSUE TITLE
Currency Report Window High up on Screen unable to drag it down

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9675]
**Version:** 0.7.7.2 beta

![snap3033](https://user-images.githubusercontent.com/29383891/46703494-2dd84200-cc1f-11e8-97f0-328c10fe0f2e.png)
as can be seen above when Currency Report is Clicked from a Store the Window appears to high on the screen and no matter where i position the Store screen the Currency Report window. is **STUCK** at this position.
![snap3034](https://user-images.githubusercontent.com/29383891/46703613-7bed4580-cc1f-11e8-97ec-56536c81f4ca.png)

by playing about stretching and resizing window the Currency Report window **WILL** pop back out into the game screen as it should do
![snap3035](https://user-images.githubusercontent.com/29383891/46703702-b3f48880-cc1f-11e8-9aaa-81457cab13ba.png)

double checked with another player this might be an intermittent glitch

**Comment by beastyn** [comment]
fixed
