### ISSUE TITLE
Server crashed and does not start up anymore

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9678]
Server crashed some hours ago, today. On trying to restart it only shows me this:
<img width="674" alt="crash" src="https://user-images.githubusercontent.com/25908592/46766017-fb8f1900-cce0-11e8-81d0-5916f4c00ef3.png">

**Comment by D3nnis3n** [comment]
After restarting the whole server the problem is more obvious, one of those boundary limits reached bugs again:

<img width="1920" alt="crash2" src="https://user-images.githubusercontent.com/25908592/46766722-195d7d80-cce3-11e8-9071-f82454188007.png">

Map:
https://drive.google.com/open?id=1WI2JUtl8wEwzu1VQywjtKhRhJc-rRa1D

**Comment by D3nnis3n** [comment]
One player confessed he tried out what the height limit is with ramps ... You should really do something that players cannot crash the server by building too high. Probably disallow placing blocks at heights that would not be okay for that specific mapsize. People can easily crash the server without even knowing. Auto-restart does not work and backup must be restored to fix it. Autoremove on exception was on but didn't do anything. What about letting that setting remove the blocks or things that are too high? So many possibilities! :D

**Comment by SeanAtr0n** [comment]
7.8
