### ISSUE TITLE
No Main Menu

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9679]
I was busy and did not play for several days and when i got into Eco today - poof - my main menu was gone (See https://github.com/StrangeLoopGames/EcoIssues/issues/9463). Deleting AppData did not help at first, but worked when i had steam NOT running. This is my zipped strange loop games folder in appdata, as john requested:

[slg.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2466571/slg.zip)

@johnkslg

**Comment by D3nnis3n** [comment]
This did happen quite often the last days, i ever had to restart steam to get it working again. Probably this is an interaction issue or something like that? It's pretty enerving, though!

**Comment by D3nnis3n** [comment]
I found a way to reproduce this:
This EVER happens when i start another steam game first. E.g. i start "Pathfinder Kingmaker", then in game tab out and start eco to look after what they do on my server, then eco has no main menu, i need to restart steam and then start eco again and it works. I had this issue serveral dozen times the last days.

My hardware is competent enough to run three games at once, so this should reall not be any problem!

**Comment by johnkslg** [comment]
Want to try some repro attempts Walker?

**Comment by BlazeGuy2** [comment]
Tried to repro.  I launched Stardew Valley from Steam and alt-tabbed out and launched Eco from Steam.  Main Menu appeared for me.  @D3nnis3n could you possibly post a video of a repro attempt on your end?

**Comment by D3nnis3n** [comment]
Do you know a good free software for making Videos? The Windows implemented Thing only works in a game, e.g. you can’t tab out to a new one.

**Comment by mirasrael** [comment]
VSDC Free Screen Recorder may work for you

**Comment by D3nnis3n** [comment]
I tried that, it worked, but it seems laggy, despite it has not been for me, probably because of 4K Screen Resolution. Here you go: https://drive.google.com/open?id=1uga5fOANpVxBPUgUPefgH9FSdp0MNiid

I can reproduce this every single time.

**Comment by mirasrael** [comment]
Also tried to reproduce, no success. Can you provide content of your `<USERHOME>\AppData\LocalLow\Strange Loop Games\Eco\output_log.txt` and Crashes directory if it is not empty?

**Comment by D3nnis3n** [comment]
I added the requested data already in the opening post for this issue. There is no crashes folder, so i suppose there weren't any as in if it was empty.

Here is the output_log.txt file when the issue occurs and the error inside is very obvious:
```
InvalidOperationException: Steamworks is not initialized.
  at Steamworks.InteropHelp.TestIfAvailableClient () [0x00019] in <4541e0b3a64a40fa96a17a87af6e7bf6>:0 
  at Steamworks.SteamUser.GetSteamID () [0x00000] in <4541e0b3a64a40fa96a17a87af6e7bf6>:0 
  at NetworkManager.Login (System.String username, System.String passwordOrToken) [0x00021] in <4541e0b3a64a40fa96a17a87af6e7bf6>:0 
  at NetworkManager.Update () [0x001d4] in <4541e0b3a64a40fa96a17a87af6e7bf6>:0 
 
(Filename: <4541e0b3a64a40fa96a17a87af6e7bf6> Line: 0)
```

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2500308/output_log.txt)

**Comment by mirasrael** [comment]
@D3nnis3n yes, sorry, missed that

**Comment by mirasrael** [comment]
It seems like a Steam related bug which also can't be widely reproduced (specific for some local configurations like your). 
But for sure it is not correct behavior for game to just silently fail and don't show anything. So we need at least add handling for this error and inform user about problem with suggestion to close other Steam games (because now we know it may conflict with other games).

**Comment by mirasrael** [comment]
I Googled for this and found it also happened in other games. In some cases it was permanent and some users was able to fix it by cleaning up all caches.

**Comment by D3nnis3n** [comment]
Well, eco is a Administration-heavy game and therefore a pretty Good
example for this case. Despite it being a very specific issue it should
just not happen. We had several reports about missing Main menus in this
Tracker, so ist not that rare. You should definatley give Information like
"restart steam" when this occurs and report this issue to steam maintainers.

Alexander Bondarev <notifications@github.com> schrieb am Mo., 22. Okt.
2018, 16:14:

**Comment by mirasrael** [comment]
@D3nnis3n as I wrote above I'm totally agree with you :)

**Comment by D3nnis3n** [comment]
Which is great!
