### ISSUE TITLE
USER ISSUE: Missing arrow in server selection

### ISSUE THREAD

**Issue by tpajenka** [StrangeLoopGames/EcoIssues#9681]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Main menu, go to New Game
2. Go to "Browse All" while being on the first "page"
3. Go back to "Browse Recommended"
4. Go right
5. The "left" arrow appears and fades, does not appear again

Also "works" from the last "page" with the left arrow

**Expected behavior:**
The navigation arrow does not disappear

**Actual behavior:**
The navigation arrow vanishesn
**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed

**Comment by BlazeGuy2** [comment]
Fixed for 7.8 milestone, open a new issue if this resurfaces in the next release.
