### ISSUE TITLE
World Layer viewer not working

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9682]
Turning on some world layers didnt work

**Comment by metachronism** [comment]
most of them work, and the ones that dont are broken on master as well

**Comment by seccombew** [comment]
@BlazeGuy2 check if broken in staging.

**Comment by BlazeGuy2** [comment]
Broken in staging.

**Comment by SeanAtr0n** [comment]
probably also localization related? @Nanders ?

**Comment by Nanders** [comment]
The ones in the ServerUI?

**Comment by Nanders** [comment]
11 days ago I haven't touched WorldLayers

**Comment by SeanAtr0n** [comment]
it's in game in the minimap panel... in staging the categories are all unknown, I'm not sure whats going on in master... if it doesn't look like a similar issue to staging then toss it back to me

**Comment by elfl0rd** [comment]
> @elfl0rd did you manually add those categories for some reason or did you edit the prefab while the game was running and copy/replace the main minimap prefab?

Most likely it happened for this reason, I'm new to editing prefabs :) can you tell me how to edit prefabs correctly?

**Comment by SeanAtr0n** [comment]
There are lots of ways to do it but editing things while the game is running is a pretty advanced way to do things that can be dangerous for complex prefabs.

The safest way to do it is to edit in edit mode. Drag the prefab into your scene, edit it, hit apply, disable or delete it and then test your changes in play mode.
