### ISSUE TITLE
Localization Issues

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9684]
Did a quick pass and found the following stuff, in the doc here:
https://1drv.ms/w/s!AnNPKT4C9Ig9jn4EHyIfqijptAjd
Getting very close!

Also whats left to get the website localized?

**Comment by johnkslg** [comment]
Removing priority from localization tagged bugs so it doesnt affect other stats.

**Comment by Quadbro** [comment]
All that bugs are fixed in a bunch of small issues, mainly created by @elfl0rd, Many thank's to him!)

**Comment by elfl0rd** [comment]
Yep, i'll focus on client side before server :)
