### ISSUE TITLE
 The process of restarting the game can reach 6-24 hours.

### ISSUE THREAD

**Issue by Malenkei** [StrangeLoopGames/EcoIssues#9686]
Please tell me what is wrong!  The server we are 9 km away. the game File weighs in at 500 MB.  The process of restarting the game can reach 6-24 hours.  Sometimes the same preservation is loaded for 15 minutes in total.  Why such difference?
Our features: 4 CPU 2.40 GHz 16GB RAM
185.180.231.219:3000

**Comment by mirasrael** [comment]
Please provide server logs for both cases.

**Comment by mirasrael** [comment]
You can also upload your save somewhere (like Dropbox) and provide link to it. It will be much easier to investigate this issue then.
