### ISSUE TITLE
Laser Requirements to destroy meteor

### ISSUE THREAD

**Issue by seccombew** [StrangeLoopGames/EcoIssues#9689]
In a recent play through, four lasers were built, thought the energy requirements were only met for one laser. When firing lasers at the meteor, three of the four shut down immediately, but the single laser remaining was able to destroy the meteor by itself.

**Comment by BlazeGuy2** [comment]
@seccombew Do you know what version the meteor was destroyed on?  Can you get the server save from them?

**Comment by elfl0rd** [comment]
hmm... https://github.com/StrangeLoopGames/EcoIssues/issues/7927

**Comment by Spydarlee** [comment]
Nice catch @elfl0rd - looks like this has been fixed in master but the change hasn't yet made its way tino staging. Checking with @johnkslg if we need to pull it over manually.
