### ISSUE TITLE
Alpha 5.2 - After placing one ramp the other ramp items in the same slot disappear

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#969]
Pre-requirement:
- In Alpha 5.2
- Remove at least 2 ramps with the hammer
- Both ramps items has to be in the same slot.

Step:
1. Place one ramp on the ground from the slot containing both ramps.

Results:
1. The ramp is placed on the ground.
2. The other ramp in the slot disappear.

Expected Results:
1. The ramp should be placed on the ground.
2. The other ramp should still exist in the slot.

Note:
I also got an exception when I try to drag the removed ramps from me to the cart
![image](https://cloud.githubusercontent.com/assets/7052045/21629975/c3972be2-d1fa-11e6-8467-bd610891ac2e.png)

**Comment by MarjieAVolk** [comment]
Fixed as of 5.5
