### ISSUE TITLE
Make use of popup dialog for errors

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9692]
Errors sent using SendTemporaryError will display in the chat, which can be missed if its behind a window.  Go through all cases of SendTemporaryError and change them to instead call PopupConfirmBoxLoc on the client, so the error message is properly viewed.

**Comment by elfl0rd** [comment]
Perhaps it would be better to display the chat on top of all Windows when an error occurs?
(Everyone hates popups!)
In addition it would be very good if the errors always will be visible in the chat and not for a short time after the appearance...
In addition, part of the "errors" should be removed by modifying the game mechanics.
For example, contracts for the delivery of items
e.g. need 11 items in a stack 20
it is expected that when you drag a large stack surpluses will be returned, as it happens for example with the production queues
But instead you get an error in the chat and have to split the stack and give the contract strictly specified amount...
A similar problem with the distribution station, if the distribution of a lot of the same things you can not just drag the stack to him and get the part of it that is available.
and etc...

**Comment by InfectedBytes** [comment]
Bringing the chat window in front when an error occurs is a good idea, but should really all error messages be always visible? Or would it be better if some (small) errors are still only temporarily visible?

**Comment by WeaselDog** [comment]
Fixed
