### ISSUE TITLE
7.7.2: Display Error while changing (sound) settings

### ISSUE THREAD

**Issue by LipkeGu** [StrangeLoopGames/EcoIssues#9695]
Version: 0.7.7.2 beta

Steps to Reproduce:

* Play the Game
* Disable Fog in graphics settings
* Press escape and change some settings, like sound, graphics or other settings
* while you change the settings like moving the slider, a fogish graphical error occours
* Restarting the Client fixing this

Expected behavior:
The Game should run normaly
Actual behavior:
Graphical Error...
Do you have mods installed? Does issue happen when no mods are installed?:
Graphical Error...

**Comment by Nicolausi113** [comment]
Could it be related to these ? #9240 #9277

**Comment by BlazeGuy2** [comment]
@LipkeGu Can you send screenshots/videos of this graphical issue?

**Comment by D3nnis3n** [comment]
No answer to Information request in 14 days, reopen if issue persists.
