### ISSUE TITLE
Inventory confusion

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9698]
https://www.twitch.tv/videos/322315563 @6:50

![image](https://user-images.githubusercontent.com/3536496/46971285-6db08680-d070-11e8-8314-8061e333e61c.png)

**Comment by Conchipedia** [comment]
watching this video, i can see why this Player was getting confused, maybe have the first thing that happens after creating/editing Avatar is to pop up on screen something like a message explaining How to toggle between Having the mouse pointer visible to interact with things and getting the Player to move an item from his backpack to his toolbar, this will at least give him a heads up on what the Player should be doing at least if they happen to come upon a Distribution station like this

**Comment by SlayksWood** [comment]
Unable to watch the video now. But according to the last comment I suspect that the new player had problem with using inventory. Good tutorial appeared from that moment. Seems fixed
