### ISSUE TITLE
Rohrer Bug: No suggested servers

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9699]
![image](https://user-images.githubusercontent.com/3536496/46971489-f0394600-d070-11e8-8c18-1c7a99b9d903.png)

Probably due to too-high ping

**Comment by D3nnis3n** [comment]
You have a ping of 650 to my server? We got a lot of US players, but they are at around 150, East Coast though.

**Comment by BlazeGuy2** [comment]
Wasn't autoclosed, PR was merged in for this.
