### ISSUE TITLE
PropertyPlot.Deed returns null if players don't carry their deeds

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#970]
This is part of why web maps broke on our server, I can make the webapi tolerate this better but it'd be nice if there was a better way to get names.

heh, in the code:
                // This is gross. There must be a better way.

**Comment by metachronism** [comment]
I think a lot of this stuff should just clone the deed item (as opposed to saving and relinking with an instance)

might work and solve a lot of this insanity

**Comment by metachronism** [comment]
this code has been reworked at lot, and PropertyPlot.Deed no longer exists.
