### ISSUE TITLE
Minimap UI is broken

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#9700]
![brokenminimapui](https://user-images.githubusercontent.com/35509188/46975107-9ccbf580-d07a-11e8-85bd-f2bf5c3ef0d7.PNG)
On Current staging.

**Comment by BlazeGuy2** [comment]
Environment Data panel has all items listed as none.

**Comment by BlazeGuy2** [comment]
Fixed itself later, only triggered on first time use in world.

**Comment by SeanAtr0n** [comment]
Seems to be related to localization, Animals goes in and 'None' comes out... could you look into it @Nanders ?

**Comment by SlayksWood** [comment]
It isn't actual.
