### ISSUE TITLE
Huge lag spike after world layer tick completes

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#9701]
ask Phlo for more details if needed -

Tick world layers, observe no lag during tick - as soon as tick finishes, huge lag spike and some disconnections

**Comment by Phlo123** [comment]
Found the issue, the ticket can be closed i guess.
After the tick ends, the eco server transfers data at 50mb/s for 3-5 seconds which caps the upload speed on the network. I will most likely upgrade the connection to 400mb/s upload speed and "case closed".

**Comment by johnkslg** [comment]
@metachronism can that be transferred over time with lower priority?  50mb seems very high too, what's being transferred?

**Comment by Quicksilv3r710** [comment]
This is affecting my server as well.  Unfortunately, my ISP will not allow me to go above 40 mb/s upload in my area, I agree with johnkslg, is there a way to cap this at a lower data rate?

**Comment by metachronism** [comment]
its world layer data

**Comment by johnkslg** [comment]
Can we make it not send that data across the network with such gusto?  Space out the update

**Comment by seccombew** [comment]
@metachronism Is this issue obsolete?

**Comment by D3nnis3n** [comment]
@mirasrael Can take a look on if this is still actual?

**Comment by mirasrael** [comment]
Seems fixed in latest version. Please, re-open issue if it still happens.
