### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by RexStar03** [StrangeLoopGames/EcoIssues#9720]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Failed to login

... Just a Joke ;)
-= Cracked by WhiteLion & Ported by Miniwinz.fr =-
Stop steal the crack without credit FUCK NeO-Team! 
```

**Comment by elfl0rd** [comment]
Do not use pirate copy, lol.
