### ISSUE TITLE
Stockpile didnt detect lots of logs added in tut

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9725]
![image](https://user-images.githubusercontent.com/3536496/46987584-acaefe00-d0a9-11e8-9b7d-788a1b192745.png)
May be fixed in staging @BlazeGuy2

**Comment by BlazeGuy2** [comment]
![stockpile_tut](https://user-images.githubusercontent.com/35509188/47034377-0e17b100-d12c-11e8-901a-ac358a4137f6.PNG)
Tutorial worked for me just fine on current staging.
