### ISSUE TITLE
USER ISSUE: No menu at game startup

### ISSUE THREAD

**Issue by Chumannn** [StrangeLoopGames/EcoIssues#9726]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Launch game.

**Expected behavior:**
Show start menu

**Actual behavior:**
No menu listings just background with windmills etc. Nothing to click on. If i hit excape i get the settings menu as normal but n
**Do you have mods installed? Does issue happen when no mods are installed?:**
No menu listings just background with windmills etc. Nothing to click on. If i hit excape i get the settings menu as normal but

**Comment by Deantwo** [comment]
Duplicate of closed/solved issue: #9345

Should be fixed in the next update.
