### ISSUE TITLE
Elections bug out sometimes

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9729]
We now have - once again, as in every few elections - the case that noone can vote on elections as of when you try the right side of the webpage stays empty. Funnily some people could vote before this started suddenly, so i have to declare the election invalid as of the winner probably winning by a bug.

<img width="1877" alt="actualelection" src="https://user-images.githubusercontent.com/25908592/46995883-f08e1b80-d11a-11e8-86ed-1851a8053e7f.png">

If you click on any of the prior elections you will get this screen instead of the results:
<img width="1897" alt="priorelections" src="https://user-images.githubusercontent.com/25908592/46995798-89706700-d11a-11e8-9325-bff455fbc795.png">

**Comment by johnkslg** [comment]
@D3nnis3n can you see if this still repros in master? And if so attach a world and repro case.

**Comment by D3nnis3n** [comment]
Issue did no longer occur.
