### ISSUE TITLE
Controller input detecting and unable to unbind controller 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#973]
need some form of disabling controller input because i am way to lazy to unplug all my 4 controller =P anyway .. this is quite annoying and i think several users share my opinion about not unplugging there controllers but being unable because of that to play.

**Comment by metachronism** [comment]
this has been a unity bug with lots of controllers for quite a while

**Comment by noblackthunder** [comment]
is it possible to write a custom control handler to resolve this ? maybe a good project for me ? mhh

**Comment by SeanAtr0n** [comment]
Just removed some more controller inputs from our vehicle scripts, hopefully that's the last of it? (check the build after today's hotfix build)

**Comment by beastyn** [comment]
should be fine now
