### ISSUE TITLE
Electric Lathe: Crafting tab is empty

### ISSUE THREAD

**Issue by Skepsi** [StrangeLoopGames/EcoIssues#9732]
Game version - 0.7.7.2
The "crafting" tab of "Electric Lathe" is empty.

**Comment by Nicolausi113** [comment]
dupe #8800 #8547

**Comment by Deantwo** [comment]
This is not a bug, there simply aren't any recipes at that crafting station. Place it in the same room as an __Electric Machinist Table__ to unlock the next recipe at the __Electric Machinist Table__.

See: https://github.com/StrangeLoopGames/EcoIssues/issues/9040#issuecomment-415072350

**Comment by elfl0rd** [comment]
Just move "Steel Axle" from Electric Planer to Electric Lathe, to compare as Lathe and Shaper.

**Comment by Rambo99** [comment]
> Just move "Steel Axle" from Electric Planer to Electric Lathe, to compare as Lathe and Shaper.

Steel Axle ??? What it is ?!?! This is not in the game. Screenshots please.

**Comment by Deantwo** [comment]
@Rambo99 he is just suggesting that the developers move the recipe from one crafting station to another.

See the recipes here: https://eco.gamepedia.com/Electric_Planer

**Comment by elfl0rd** [comment]
@Rambo99 

> Steel Axle ??? What it is ?!?! This is not in the game. Screenshots please.

Not in the game? Lol. in 0.7.7.2

![default](https://user-images.githubusercontent.com/4980243/47253232-5818d380-d459-11e8-861e-1e39ef0a843d.png)
![default](https://user-images.githubusercontent.com/4980243/47253261-7b438300-d459-11e8-9b4b-8415a471e110.png)
![default](https://user-images.githubusercontent.com/4980243/47253269-84345480-d459-11e8-902e-574e033a3088.png)

**Comment by Rambo99** [comment]
OK
