### ISSUE TITLE
Balancing Issue - Ramps should have weight and be only carryable

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9733]
Example:
- 100 ramps can be packed in backpack in ONE slot
- place the ramps intermediate on ground and destruct them
- the scattered blocks now have weight and behave like normal dirt, stone road or asphalt road.

No vehicle or stockpile can hold this amount of weightless building material.
Ways for cheating are implemented.

**Comment by D3nnis3n** [comment]
Assigning medium priority and putting it on my list.

**Comment by D3nnis3n** [comment]
Fixed.
