### ISSUE TITLE
"Tims Cart" when you sell deeds

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9734]
I bought two deeds with around 500 claims today, looked in my real estate table and owned Deeds called "Title" with plots that are ALL named "Tim's Wood Cart" instead of their real names and plots with coordinates. That vanished after changing something at the plot, e.g. change name or color.

**Comment by beastyn** [comment]
Something with that Tim is really strange.
0.8.1.4
Put real estate for selling purposes.
Open Deed Sales and see that all you property is Tim's cart
![bandicam 2019-04-23 14-17-54-417](https://user-images.githubusercontent.com/27898520/56570598-b07d8900-65d4-11e9-87ff-5b5c21647448.jpg)

**Comment by SlayksWood** [comment]
Semms fixed in 0.9.0. Closed for now.
