### ISSUE TITLE
Selling Claims takes authorisation with it

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9735]
If you sell a plot with people authorised they stay authorised. Maybe not the best thing to do, especially when you don't know this is happening and people can alter your plots without you knowing.

**Comment by seccombew** [comment]
@johnkslg Seems like a good idea to change this.

**Comment by SlayksWood** [comment]
still an issue 0.8.1.3

**Comment by WeaselDog** [comment]
fixed
