### ISSUE TITLE
: lost in string?

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9745]
![default](https://user-images.githubusercontent.com/4980243/47043888-78197000-d197-11e8-833c-6d9f7cc6fe65.png)

https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#53248
https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#53246

@Nanders ?

**Comment by Quadbro** [comment]
Do you mean ":" is missing?)

**Comment by Quadbro** [comment]
sorry, missclicked closing)

**Comment by elfl0rd** [comment]
yep, different vs other strings.
adding : will be better :)
