### ISSUE TITLE
Balance - charcoal

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9757]
I think now getting the "steel" is too hard
Please, make charcoal reciepe more easy.
1) 50% less lumber
2) craftable from hewn logs too.

**Comment by Conchipedia** [comment]
as of writing this the Blast Furnace is broken and takes the Coal from the Power tab and using it as Ingredients #9638 so i expect that charcoal is being used instead of coal

**Comment by elfl0rd** [comment]
@Nicolausi113 In any case, it takes too much coal to make steel now.

**Comment by Conchipedia** [comment]
we could always have coal turned into Coke then thats used in Blast Furnaces
if you want to read more about Steel making
https://www.worldcoal.org/coal/uses-coal/how-steel-produced

**Comment by Conchipedia** [comment]
Around 150 kg of coal are used to produce 1 tonne of steel in electric arc furnaces, so maybe we can have a **NEW** machine for producing Steel when Electricity is abundant

**Comment by Ketrai** [comment]
Makes me wish there is a low-grade early material to make furniture out of called "cast iron"
