### ISSUE TITLE
Bank - accounts list

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9762]
1) list show over all windows
2) list not hide when user click\make actions outside.
![default](https://user-images.githubusercontent.com/4980243/47061239-4d500b80-d1d9-11e8-93b2-1bf8102bdb97.png)

**Comment by Quadbro** [comment]
it looks that bank account choice dropdown template has override sorting (value= 30000) This problem can be solved removing sorting by canvas component, and adding that spawned dropdown to another transform in parent (with setting as last sibling) it works, but there are some troubles in getting that canvas component from template... some bugged stuff going there :D
