### ISSUE TITLE
Selection out of windows (new item filter)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9765]
![default](https://user-images.githubusercontent.com/4980243/47061689-4aeeb100-d1db-11e8-9b86-3480ad601694.png)

**Comment by elfl0rd** [comment]
Okay, what information you want? :D

**Comment by BlazeGuy2** [comment]
Does clicking on the yellow boxes select items in the window?  Also, could you get a video showing what is occurring here so that it easier to visualize.

**Comment by elfl0rd** [comment]
(This is current master branch)

> Does clicking on the yellow boxes select items in the window?

Yes, except he outside filters window.

**Comment by elfl0rd** [comment]
Fixed in https://github.com/StrangeLoopGames/Eco/pull/3534

**Comment by elfl0rd** [comment]
Merged, fixed, closing.
