### ISSUE TITLE
Powered Cart can drive on every ground after placing but not anymore after an server restart

### ISSUE THREAD

**Issue by JackFHW** [StrangeLoopGames/EcoIssues#977]
Hi,

we placed an Powered Cart and it can easily drive on Rock Stone, Mortared Stone, Dirt Roads etc. But after an server restart it stucks with 0% road efficency. I think it should not be possible to drive on other surfaces beside stone or asphalt roads or ?

If you deconstruct and replace the powered cart you can again drive on other surfaces without an problem until server restart.

Greetings
Desiderius
www.fh-warzone.de

**Comment by metachronism** [comment]
fixed this in 5.3, but you may need to pick up the cart and then place it back down
