### ISSUE TITLE
Trees despawn on singleplayer

### ISSUE THREAD

**Issue by NisseA** [StrangeLoopGames/EcoIssues#9772]
very often the tree Ive chopped down despawns when Ive collected like 20 logs from it and re-apears after a reload of the world.
Nearly every tree I chopped down. Noticed this a couple of months ago and stopped playing. started playing again and still happens.

The world stops loads too. If I walk away from my base the map stops to load and the ground/trees/bushes and others disappears. after a reload of the world I get some type of roleback and I can play for a while (10-15 minutes) before it happens again. this only happens after the tree gets bugged out.
Works fine on servers.

Windows 10 64 bit
16gb ram
i7 3.5Ghz
geforce gtx 1050ti 4gb

**Comment by BlazeGuy2** [comment]
Closing as potential dup of #9186
