### ISSUE TITLE
Bad keymapping for the /fly command

### ISSUE THREAD

**Issue by Mehigh17** [StrangeLoopGames/EcoIssues#9773]
I have an AZERTY keyboard layout, I have remapped my normal walk keys but when I use the /fly command the QWERTY key maps apply so I need to press WASD, but WASD aren't in the same position as on an AZERTY keyboard. And the problem is that I can't remap the fly keys at all... It's very annoying and makes the flying almost impossible for non QWERTY users.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/8980
https://github.com/StrangeLoopGames/EcoIssues/issues/9665

**Comment by SlayksWood** [comment]
merged to #9665
