### ISSUE TITLE
Master - adding any to authorization - server crash.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9781]
![default](https://user-images.githubusercontent.com/4980243/47112283-9302e780-d25e-11e8-9f81-d348f0b11988.png)

![default](https://user-images.githubusercontent.com/4980243/47112277-88e0e900-d25e-11e8-8274-c02d6d0958fd.png)

**Comment by johnkslg** [comment]
@mirasrael can you check out whats going on here? Async exception related.

**Comment by elfl0rd** [comment]
Maybe its result of fixing - https://github.com/StrangeLoopGames/EcoIssues/issues/9583 ?
