### ISSUE TITLE
Master - "Logout" button

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9782]
Please move it onto main screen, close to user name.
e.g.
from
![default](https://user-images.githubusercontent.com/4980243/47114907-bc734180-d265-11e8-93b8-bab58d1aea7b.png)
to
![default](https://user-images.githubusercontent.com/4980243/47114984-f04e6700-d265-11e8-9430-11433c50a0aa.png)

**Comment by Nanders** [comment]
This isnt a localization issue, hes requesting the logout button be moved to the main menu, right now its in the escape menu

**Comment by elfl0rd** [comment]
A couple of reasons for this.
First, you expect to find the logout button next to the user name and not in a separate menu.
Second, the button in the menu appears ugly under the mouse cursor when disconnected from the server.
