### ISSUE TITLE
Sell Restrictions does not work

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9783]
We got this law:
<img width="1345" alt="law" src="https://user-images.githubusercontent.com/25908592/47120233-314a7980-d26e-11e8-9470-785a0319dd9a.png">
It is meant to restrict players from selling gold to me when they have more than 100 dollars.
But it counts MY money for the value check, which is obviously higher and disallows sale of people wehen i have more than 100 dollars and the seller doesn't. But i am BUYING it, not selling it:
<img width="1440" alt="money" src="https://user-images.githubusercontent.com/25908592/47120280-5b03a080-d26e-11e8-9dff-65c4493a598e.png">

**Comment by Deantwo** [comment]
The `Sell` trigger is triggered for both the seller and the store buying the item.
You can add "`not (on own property)`" to the `Sell` trigger's where clause, that way it won't trigger for the shop itself.
See: #9412

**Comment by D3nnis3n** [comment]
Additional Information:
We want to be able to disallow selling TO the bank if the player has more than 100 dollars while the bank itself should still be able to sell to other players regardless of the money the bank-owning player has. All of this should also be restricted to the bank only, e.g. its property "Federal Bank". I'll be great if you adapt your system as such, that this will be possible.

**Comment by Deantwo** [comment]
Are you saying that what we talked about on Discord didn't work?

```
When attempting to Sell where ((item is Gold Ore) and (not (on own property)) and (on property "federal bank"))
    ...
```

**Comment by D3nnis3n** [comment]
Yes, i just noted that down in discord too. The law seems to have no effect at all after this change, people can sell the gold regardless if they have over 100 or less than 100 gold, with no regards to the bank, too.

**Comment by Deantwo** [comment]
@D3nnis3n, looking over old law issues.
But maybe your law there doesn't work because you are checking "sell", but "buy" is triggered for the store?
Like I have said before, there is some backwards logic somewhere in this. Every time I try to make a law that use "buy" or "sell", i get the opposite result then what I wanted.

I need to do sone testing on this, but it isn't something I can test in singleplayer I think. Or how does `/spawneconomy` work?

**Comment by Deantwo** [comment]
Laws label and 9.0 milestone? :crossed_fingers:

**Comment by johnkslg** [comment]
Can you try this one again in the current system? I think it works as you want, but will need you to check.

**Comment by WeaselDog** [comment]
This is working now. Here is test law and debug message:

**Law Tested:**
![SellRestrictionLaw](https://user-images.githubusercontent.com/47330823/69740515-61f61700-10ee-11ea-85ef-129a46068e67.png)

**Debug result:**
![SaleRestrictionDebug](https://user-images.githubusercontent.com/47330823/69740559-6fab9c80-10ee-11ea-9591-f4772c4b9855.png)
