### ISSUE TITLE
USER ISSUE: Stone Ramp Catapult

### ISSUE THREAD

**Issue by MerGatto** [StrangeLoopGames/EcoIssues#9784]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Place some stome ramps
Get a Wood cart
Drive the wood cart up the ramps

**Expected behavior:**
Smoothly drive up the ramp

**Actual behavior:**
You get catapulted in to the sky and possibly into the orbitn
**Do you have mods installed? Does issue happen when no mods are installed?:**
You get catapulted in to the sky and possibly into the orbit

**Comment by MerGatto** [comment]
Always happens when i drive up this slope and always at the same spot

![2018-10-18 13_28_39-eco](https://user-images.githubusercontent.com/2557018/47151404-f2eaa400-d2d9-11e8-8020-96f52b2eff98.png)

**Comment by elfl0rd** [comment]
0 coordinate...

**Comment by MerGatto** [comment]
i see, is there a workaround for this?

**Comment by MerGatto** [comment]
i replace the ramp with some stone roads to prevent upward/downward movement when crossing the 0 coordinate, it still glitches sometimes but far less worse

**Comment by elfl0rd** [comment]
Use flat road on 0 :(
This is old issue, https://github.com/StrangeLoopGames/EcoIssues/issues/7612

**Comment by elfl0rd** [comment]
and https://github.com/StrangeLoopGames/EcoIssues/issues/8374

**Comment by SeanAtr0n** [comment]
likely fixed in https://github.com/StrangeLoopGames/Eco/pull/3502 7.8
