### ISSUE TITLE
Sanding Block does not reduce workbench ressource costs

### ISSUE THREAD

**Issue by JackFHW** [StrangeLoopGames/EcoIssues#979]
Hi,

i place 3 sanding blocks together in an room with work bench and carpentry table. They are correct counted in status tab of work bench. But they does not reduce 3x 20% ressource cost of workbench recipes. 

Greetings
Desiderius
www.fh-warzone.de

**Comment by Nes112** [comment]
I opened an issue on this. It's not just sanding blocks. It's any module that is supposed to reduce craft time or resources used.

https://github.com/StrangeLoopGames/EcoIssues/issues/906

**Comment by craig-jong** [comment]
Modules are currently completely non-functional except for the ones that unlock recipes.
