### ISSUE TITLE
Deed Sales need fixing

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9792]
I updated just about everything to use the new bank account system, except the deed sales.  You can see this interface on the real estate desk, give yourself one (might need to '/spawnbuilding 2' and put it inside to make it function.  In fact if you want to add a chat command /spawn <itemname> that works like /give, but creates a requisite building and places it inside, that would be fantastic).

Hook up the real estate desk so you choose which account youre spending from, like the store does.  Modify the server code so that the transfers happen between the correct accounts.

**Comment by Quadbro** [comment]
It seems like all alias related things are broken now...

**Comment by Quadbro** [comment]
Fixed in https://github.com/StrangeLoopGames/Eco/pull/3538
