### ISSUE TITLE
USER ISSUE: Steam Truck Iron Ore

### ISSUE THREAD

**Issue by Trenix** [StrangeLoopGames/EcoIssues#9797]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Put a stack of 20 iron ore in a steam truck.
2. Get a text message saying you can't put more than 5 iron ore in there, even though it went in.

**Expected behavior:**
No text message appearing.

**Actual behavior:**
Text message appears saying you can't do something which you clearly can.n
**Do you have mods installed? Does issue happen when no mods are installed?:**
Text message appears saying you can't do something which you clearly can.

**Comment by Trenix** [comment]
I did. Had more than enough weight to take the iron and it did. Its just a warning that makes no sense.

**Comment by elfl0rd** [comment]
If you provide a screenshot it will help
