### ISSUE TITLE
[7.8.0 #79e33fd9] Filter Settings are not synced on "Recommended Tabs" and "Browse All"

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9799]
When you change something in the filter in the recommended tabs, e.g. "version match = no" that is not reflected on the filter for "browse" all. Probably this is intended, i found it enerving to have two filters. I'd propose to change the filters to sync, as that is easier to understand and in my opinion the behaviour one would expect. Just close, if you don't think so.

**Comment by SlayksWood** [comment]
move to #12041
