### ISSUE TITLE
[7.8.0 #79e33fd9] Reconnecting to servers does not work sometimes

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9800]
See the video, the issues only arises every so much tries, but then i need to restart the game to be able to get on the server again.

https://drive.google.com/open?id=1xXZEktqZSTmpIy9P03R-QqVbasbK0sAn

If you press "Escape" when in that never-ending loading screen you get the message: "Error or otherwise informative message goes here" - one we know good, eh? :D

**Comment by johnkslg** [comment]
Local server?  New genned world?

**Comment by D3nnis3n** [comment]
Happens on non-local servers, too. (Experienced it several times with my own Server on 7.7) Happens on new and not new worlds.

**Comment by johnkslg** [comment]
Could not repro this, need attached world this is failing in, as well asthe logs of the server and client upon failure.

**Comment by johnkslg** [comment]
Assign back to me if you can get those

**Comment by D3nnis3n** [comment]
I see, i tried creating some other worlds to reproduce and there it is indeed not happening, at least not on all, but when i loaded up this one it happened again and was reproducable as in it happened in half the connection tries: https://drive.google.com/open?id=1wuMuNUD9EYYHh-TjZfVURBrAMRT6PJfA

That's the output_log:
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2509488/output_log.txt)

I don't really know where the client log is located yet as i never had to use one and couldn't also really find where it is? Could you point me to the direction?

**Comment by johnkslg** [comment]
Good find! Ill give it a look.

**Comment by D3nnis3n** [comment]
Hey John,
yes - i started the server seperatley on my LOCAL machine in this case, then connected with the SLG game launcher from bleeding edge (i did not yet set up unity) to it.

The log is correct, that happened on my testing passes and it was also the first time i joined the server, did some QA tasks and then reconnected.

I'll keep this issue assigned to me and try to get more information when it occurs the next time.

**Comment by D3nnis3n** [comment]
Here, another world this happened on, reproducably for me:
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2531597/output_log.txt)

**Comment by D3nnis3n** [comment]
I can no longer reproduce this in 7.8.5 (Probably also this here https://github.com/StrangeLoopGames/Eco/pull/3653 fixed it, i don't know)

I'm closing the issue therefore.
