### ISSUE TITLE
[7.8.0 #79e33fd9] "Error or otherwise informative message goes here" issue persists

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9802]
See this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/9585
Also on other occasions still there, i suppose it's just not merged into the staging branch yet.

@johnkslg or @BlazeGuy2 How should i go on with issues that are still there in a later staging build? Not reporting? Reopening? New issue? What's the way you'd like? It's hard for me to know if you put in the fix for a issue into the version i'm passing. Just give me small headsup and close this issue if you like.

**Comment by seccombew** [comment]
Looking at previous closed issue, this was merged into master, not staging.  Will not show up in Staging for a release cycle.
