### ISSUE TITLE
[7.8.0 #79e33fd9] Land claim papers are still not vanishing from inventory after being used

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9804]
See this issue, it's persisting and marked for 7.8, so i suppose it should have been fixed:
https://github.com/StrangeLoopGames/EcoIssues/issues/9527

**Comment by D3nnis3n** [comment]
I'm not having any in my inventory, i do have 6 in the hotbar i can place, but they don't vanish, but can't be placed down anymore.

**Comment by BlazeGuy2** [comment]
Confirmed bug, replicated on staging in Unity.

**Comment by BlazeGuy2** [comment]
Fix merged in
