### ISSUE TITLE
[7.8.0 #79e33fd9] Placing down a workbench does not fulfill the tutorials requirement anymore

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9805]
I tried several times, it does not tick the objective:
<img width="1920" alt="workbench" src="https://user-images.githubusercontent.com/25908592/47251103-e330a400-d42e-11e8-94ec-0b18606e75a3.png">

**Comment by BlazeGuy2** [comment]
Worked fine on my machine for unity and built version.  @D3nnis3n can you send me the save where this occurs?  Bumping down priority for now.

**Comment by D3nnis3n** [comment]
Reopening as it happened again in 7.8.0 #Be3effa9.
Crafting the hewn logs will check the task of the workbench being placed, though.

**Comment by D3nnis3n** [comment]
This issue is related to https://github.com/StrangeLoopGames/EcoIssues/issues/9877
