### ISSUE TITLE
[7.8.0 #79e33fd9] Distribution station shows weird information

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9807]
At least when using /testdistributionstation the distribution station shows a weird marker with numbers but no icons, and obviously those numbers are also somehow incorrect. But at least this time i can open it, while i couldn't on the last staging build :)

<img width="1920" alt="distribution" src="https://user-images.githubusercontent.com/25908592/47251218-9e5a3c80-d431-11e8-89b0-41d9f4c50dc0.png">

Also, as i am on it i want to tell you that this issue here with the distribution station still persists, despite being marked fixed: https://github.com/StrangeLoopGames/EcoIssues/issues/9221

**Comment by D3nnis3n** [comment]
This no longer happens on the newest bleeding edge build. You can close the issue if that is enough and you don't need to do further testing.

**Comment by D3nnis3n** [comment]
Happened again on newest bleeding edge. It seems to depend on the items that are offered. Some of them seem to have no icon in other languages than english.

**Comment by SlayksWood** [comment]
Icons are displayed correctly, but numbers of items are not always correct. (check english, russian and german)
![image](https://user-images.githubusercontent.com/45708377/56342784-a701b480-61c1-11e9-8b5c-22d8c7027434.png)
![image](https://user-images.githubusercontent.com/45708377/56343270-ee3c7500-61c2-11e9-8741-b10e286db431.png)

**Comment by SlayksWood** [comment]
The number of items sets the owner of the station. Seems fixed.
