### ISSUE TITLE
[7.8.0 #79e33fd9] Taking items out of a storage with left click puts it into inventory, not hotbar slot selected

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9808]
You successfully fixed this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/9563

If you take out the tomatoes with left click though, they go into the inventory, even if the selected hotbar slot when pressing left click is empty - i'd expect them to go there!

**Comment by johnkslg** [comment]
Makes sense to me.  Probably just need to change the order of inventory preference on this interaction, see if you can dig out where that happens.

**Comment by Quadbro** [comment]
So you need to single click one item in some inventory (Chest, etc), and it's moving into our hotbar or our inventory? i can't see, if it's implemented somehow.... I can move stuff only with drag...

**Comment by D3nnis3n** [comment]
Yes, you can now leftclick items out of a storage - see this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/9563

But if you do that while having an empty hotbar slot selected, the item still moves into your backpack and not into that hotbar slot, which is how i would like it. If you can no longer left-click an item into your inventory, that bug has been "unfixed", i'll see this in my QA Pass later this day.

**Comment by D3nnis3n** [comment]
Mistake, sorry.
