### ISSUE TITLE
[7.8.0 #79e33fd9] Weird issue with specialties

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9809]
I had an issue that allowed me to skill all specialties for 0 points until i set the difficulty in the server ui once (e.g. just choosing "high difficulty" and then switching to "medium difficulty" again), after that it worked fine. Probably worth a look? The difficulty was set before, though. Game just didn't seem to recognize until set again.

**Comment by seccombew** [comment]
May close due to upcoming skills refactor.

**Comment by D3nnis3n** [comment]
Reoccured in the latest bleeding edge version on a fresh local server ("new game"):
<img width="897" alt="skills" src="https://user-images.githubusercontent.com/25908592/48199005-0a5a0180-e35b-11e8-8110-fb4ffc1bbfde.png">

**Comment by D3nnis3n** [comment]
Old issue.
