### ISSUE TITLE
Linux issue ( new bug because unitiy 5.5? ) tools are flipped and other minor gui issues 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#981]
http://ecoforum.strangeloopgames.com/topic/1275/linux-0-5-2-tools-are-upside-down

**Comment by noblackthunder** [comment]
Not linux Spesific issue! getting reports from Mac users also

**Comment by SeanAtr0n** [comment]
Should be fixed in 5.4
