### ISSUE TITLE
USER ISSUE: continuous difficulty connecting to servers

### ISSUE THREAD

**Issue by sgtsickness** [StrangeLoopGames/EcoIssues#9816]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1.launch game
2.try to join server.

**Expected behavior:**
join server.

**Actual behavior:**
Connection failed.  Can connect fine after several restarts of the game or verifying game files.n
**Do you have mods installed? Does issue happen when no mods are installed?:**
Connection failed.  Can connect fine after several restarts of the game or verifying game files.

**Comment by johnkslg** [comment]
Dup of https://github.com/StrangeLoopGames/EcoIssues/issues/9931. Raising priority there.
