### ISSUE TITLE
no sound!

### ISSUE THREAD

**Issue by brianjgx118** [StrangeLoopGames/EcoIssues#9817]
hi! i have no sound whatsoever in game, i have sound in other applications running in the background but not in this game, if it helps, the sound doesnt work in a game called EmergNYC either. I am running DirectX12 as a sound driver. any help would be great, thanks!

**Comment by beastyn** [comment]
@brianjgx118 
Do you still have this issue in 0.8.1.3?

**Comment by Nicolausi113** [comment]
I even have no sound and no animation now with 0.8.1.4
I don’t think is an issue but just not produced animation, see also #6878

**Comment by beastyn** [comment]
@Nicolausi113 
What sound and animation did you lost exactly?

**Comment by Nicolausi113** [comment]
To bee honest, I never had any sound or animation since I know ECO. All tables have any animation but not sawmill. I think kind of blurry saw blade and a screeching sound would be adequate.

**Comment by Nicolausi113** [comment]
Sorry, I came to the wrong thread. I mean no sound with sawmill.
This here may be related to the SFX slider?

**Comment by beastyn** [comment]
@Nicolausi113 thanks
I will check this one too, but I suppose there weren't any sounds for it.

**Comment by beastyn** [comment]
Without additional information we can't help. Please reopen the issue if it is still actual
