### ISSUE TITLE
[0.8.1.3] Stockpile and Stack Items reduce room tier

### ISSUE THREAD

**Issue by sgtsickness** [StrangeLoopGames/EcoIssues#9818]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Build a room.
2. watch it fuck up over time.

**Expected behavior:**
room should be the tier that it says the building materials are.

**Actual behavior:**
Some crap that tier 2 drops to 1.99 or whatever and keeps dropping if you add or remove stuff.  Have to add tier 3 stuff to get it back over 2. Tier 1 drops for no reason to .88 even though all building materials are tier 1 or HIGHER!.  Something isn't right with how the average is calculated.  I should add that this is NOT related to pipes although pipes do the same thing.  This example did not have any pipes. It was a room with all mortared stone and lumber.  The tier 2 room did drop due to pipes but they were in a stockpile in the room.  Not actually part of the room just within its volume.
**Do you have mods installed? Does issue happen when no mods are installed?:**
Happens with or without mods.

**Comment by elfl0rd** [comment]
Screenshots? Saves?
You use "optimisation" by cutting edges? Or pipes maybe? Or stockpiles inside?

**Comment by sgtsickness** [comment]
I am not exactly sure what you mean by the first part.  But the tier 1 room has no pipes but does have stockpiles inside due to the way it was built.  Did not know if this was a known thing that stockpiles cause a rooms tier to drop.  Should be something that is excluded from that.  Also the stockpile was filled with lumber which is tier 2 so unless a stockpile is like tier -1 I don;t see why it would drop.  Here is a picture.  replaced all windows in one wall with lumber and drained the stockpile and it went back to tier 1.  This shot is after i started replacing windows and it went from .88 to .92 then .97 then back to 1.  
![20181021003657_1](https://user-images.githubusercontent.com/638321/47263679-41639280-d4d4-11e8-91de-0bf60cbc331e.jpg)

**Comment by craig-jong** [comment]
I'll check stockpiles. It's possible they're using some kind of non-excluded world block.

**Comment by SlayksWood** [comment]
Still an issue 8.1.3
![image](https://user-images.githubusercontent.com/45708377/56503286-b2d0dc00-651d-11e9-85e1-5cda73603847.png)
Stockpile and stack Items reduce room tier

You can build a room like this
![image](https://user-images.githubusercontent.com/45708377/56503390-f0356980-651d-11e9-8181-9476ca2e49d0.png)
![image](https://user-images.githubusercontent.com/45708377/56503445-1eb34480-651e-11e9-9cb7-d0093dea0818.png)
or this
![image](https://user-images.githubusercontent.com/45708377/56503426-13f8af80-651e-11e9-81a3-535da8ad009d.png)
![image](https://user-images.githubusercontent.com/45708377/56503470-312d7e00-651e-11e9-9b68-1501530cbe78.png)

**Comment by craig-jong** [comment]
Stacked blocks (at max cap) are working as intended. We'll have a discussion about changing this behavior.

**Comment by johnkslg** [comment]
Working as intended, stacked blocks to not a room make.

**Comment by johnkslg** [comment]
Propose close @beastyn
