### ISSUE TITLE
[7.8.0 #79e33fd9] Mow contract clause does still not detect mown grass correctly 

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9819]
See this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/9587

The issue still persists on the newest bleeding edge build.

It does recognize the contract to be fulfilled after i took the plow contract and plowed all grass away. But mowing the grass is cutting it to a low level, not removing it entirely. (e.g. using a scythe to pick up all grass that is mature, then it's getting cut down) Either make more clear that players have to dig away the grass or make it so that mown grass works properly.

**Comment by BlazeGuy2** [comment]
Looked into it, fix for it was merged into master.  I'll add this to the 8.0 milestone so that I can check it when it come out.

**Comment by D3nnis3n** [comment]
Is a not working contract clause really that unimportant to fix that it can wait for the next major version? Oof.

**Comment by D3nnis3n** [comment]
I mean the QA pass requires me to test this for each Version i do test. And i have to mark it „not working“ for each Version. So why isn’t it getting fixed for the next staging Version when it is considered a Basic feature that IS in the QA pass? :D

**Comment by BlazeGuy2** [comment]
I can cherry pick the fix, but it will cause some issues when we update the branches on the next release.

**Comment by D3nnis3n** [comment]
It’s surely not my decision. It’s just that i try to learn this QA thingy and i find it odd that i have to check it every Version and probably mark it „not working“, despite there is a fix – but for another Version. I believed Features in this pass list are Basics that are required to work before any Version can get out? So, you don’t need to cherry pick anything – you do it like you are used to do it. I just wanted to know, as this is a bit hard to understand for me. *g*

**Comment by BlazeGuy2** [comment]
Fix for it turned out to be adjusting 1 line of code, safe to cherry pick, merged it in.
