### ISSUE TITLE
Role manager and overhaul chat commands

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#982]
Implementing a basic way of creating a role manager would be nice. Features should be like:
Admin can create roles and give access to different chat commands.
users than can access chat commands depending on there roles. This would be a good feature so that server hosters can as an example create a moderator role where moderators can remove land claim. etc but not spawn animals or or items as an example. This would help batteling griefing later and give a large freedom to players. This would also require rewriting how chat commands are handled etc

**Comment by johnkslg** [comment]
Added a task description for this one: 
https://1drv.ms/w/s!AnNPKT4C9Ig9p2QviWOtOodv4CPb?e=CBcDIx
