### ISSUE TITLE
[7.8.0 #79e33fd9] Server restoring backups is now completley broken

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9820]
See the screenshot. Backups are available. I made sure they do work when manually placed in. I broke the savefile by replacing it with a empty text file with ending .eco and the game just creates a new world instead of restoring the backup. One of the changes to backup seem to have broken this feature completley.

<img width="1891" alt="brokenbackup" src="https://user-images.githubusercontent.com/25908592/47263714-5d345c00-d507-11e8-99d2-bdea12ce333f.png">

**Comment by elfl0rd** [comment]
as i know, 0 file = no file. != corrupted file.
Try random data.

**Comment by D3nnis3n** [comment]
Won't work either, had that tested, too.
As long as the file exists the game MUST see it as corrupted.

GDragon <notifications@github.com> schrieb am Mo., 22. Okt. 2018, 16:54:

**Comment by johnkslg** [comment]
@mirasrael can you investigate this when you dig into backups

**Comment by johnkslg** [comment]
Could not repro this, need attached world this is failing in, as well asthe logs of the server and client upon failure.

**Comment by johnkslg** [comment]
Removing from 7.8 but still hi-pri

**Comment by D3nnis3n** [comment]
@johnkslg There was a message from you needing log and file of "world" from me before, seems deleted. Does this still apply? If yes, i'd like to assign me again, so i find that issue tomorrow when i try to get the things together for the other issue you assigned me.

**Comment by mirasrael** [comment]
@johnkslg It worked for me for corrupted file, but I also added check for empty file. So it will now work in both cases.

**Comment by D3nnis3n** [comment]
Well, i know that empty files caused a restore on the bleeding edge version before this and just used the same file. I now tested again using real corrupted file i still had from my online server by chance (and saved that one for future tests) and that did indeed work as expected.

A empty file in my opinion still is a corrupted file, though, at least as long a file is there. I would even go further and say, that if there is a statistics file it should try to restore a backup, as it can happen you forget copying in one of the files in some occasions and a restore could help then. You can also have the occasion of failed copying and pasting of files, corrupted .zip files and any other things that can give you an empty .eco file  if you have bad luck.

I know of no definition that would make a given file only corrupt if data inside is broken. When you use stats, your save is also corrupt when one of the two parts is missing. I'd rather look at the outcome instead of some limited definitions that someone may have introduced somewhen. The goal is to give the player a working backup if something went wrong and that was not fulfilled. I'm still confused why my text-file with some text inside did also not trigger a restart, but i assume this is fixed now by your newst pull request.

**Comment by D3nnis3n** [comment]
Closing as it has been fixed.
