### ISSUE TITLE
USER ISSUE: Plants

### ISSUE THREAD

**Issue by HyperSpace64** [StrangeLoopGames/EcoIssues#9821]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
World gen doesn´t create any Rice and very low Crimini
If you Create a Random World

**Expected behavior:**
Bioms to spawn in.. World Gen should make Bioms which are large enough to Create a fair amount of Rice and Crimini

**Actual behavior:**
World Gen creates everytime very low Crimini and not a single Rice plantn
**Do you have mods installed? Does issue happen when no mods are installed?:**
World Gen creates everytime very low Crimini and not a single Rice plant

**Comment by seccombew** [comment]
Closing because we are refactoring world gen in 8.0. Reopen after 8.0 if issues persists.
