### ISSUE TITLE
connection timed out on every modded server connection

### ISSUE THREAD

**Issue by exporta22** [StrangeLoopGames/EcoIssues#9823]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
every time i conect to a modded sertver 

**Expected behavior:**
it should connect

**Actual behavior:**
connection timed out without trying to get the server mod
**Do you have mods installed? Does issue happen when no mods are installed?:**
Only when I try to connect to modded server. Vanilla is ok but modded it don't answer the server so the server  wait my computer answer and finally I got disconnected. I tried with a friend and he told me what the server said.

**Comment by WeaselDog** [comment]
Hi. This issue should be fixed in the latest update. Please let us know if you still have issues.
