### ISSUE TITLE
When attempting to emit air pollution does not apply to any crafting tables

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9828]
It's not possible to select any air pollution emitting crafting station in order to prevent air pollution or tax it. Even when you do not choose a where clause like with the limited options in the screenshot below, crafting tables like blast furnaces are not affected. So how are we supposed to stop the sealevel that started to rise from rising further when we have absolutley no way to tax or restrict air pollution but only to prevent crafting at all, which noone wants?

<img width="733" alt="airpollution" src="https://user-images.githubusercontent.com/25908592/47289079-5dad1f80-d5f9-11e8-882b-11a7fc1d98ce.png">

**Comment by Deantwo** [comment]
Also no steam tractor? Or does that not emit air pollution?

**Comment by D3nnis3n** [comment]
It did not in 7.6, but does since 7.7. That means something has been forgotten here.
At least you should give us the law options to fight rising sea level. Sure, i could prevent manually the crafting for all items made in polluting crafting tables - have fun to get all recipes together in one law. It's much easier to just base it on pollution, but not possible atm, it seems.

**Comment by johnkslg** [comment]
Should work in current build

**Comment by beastyn** [comment]
Doesn't have tables in source

**Comment by johnkslg** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/13735
They are missing air pollution component now, opened this bug.  Should auto-fix here when that's fixed, but double check.

**Comment by johnkslg** [comment]
@craig-jong has took this one on.
Also tagging @mirasrael because he's changing how pollution stats work.

**Comment by mirasrael** [comment]
@craig-jong As I mentioned in another issue they shouldn't have pollution component. It may require redesign how pollution emits with pipes. Alternatively, you can remove pollution from SmogItem and generate pollution with pollution component instead.

**Comment by elfl0rd** [comment]
Perhaps the best way to rename general "Emit Air Pollution" to something like "Use car generates pollution".
And add something like "Produce smog" for all tables with it.

**Comment by WeaselDog** [comment]
Crafting tables have been added
Pollution filter:
![PollutionFilter](https://user-images.githubusercontent.com/47330823/72030190-226a3100-323d-11ea-8feb-319887cb5ada.png)
