### ISSUE TITLE
USER ISSUE: input delay after being in game for over 30 mins İ(linux clientİ) 

### ISSUE THREAD

**Issue by dutchuss2016** [StrangeLoopGames/EcoIssues#9829]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. be on linux.
 2 play normally for 1-030 mins
3 input lag should start affecting you 
4 tap w 
5 watch in horror as your character walks 50 meters off a cliff without you touching the keyboard

**Expected behavior:**
input should not be lagging like this

**Actual behavior:**
instead its really bad and it gets worse the longer the client is open restarting the game fixes it temporarilyn
**Do you have mods installed? no Does issue happen when no mods are installed?:** na
instead its really bad and it gets worse the longer the client is open restarting the game fixes it temporarily

**Comment by SeanAtr0n** [comment]
does this happen for you with other games? seems like most input issues for linux end up being issues with the linux distribution and not something we can fix

**Comment by dutchuss2016** [comment]
no this is the only game hat has this issue

**Comment by SlayksWood** [comment]
Perhaps fixed. We have many improvements for MacOS and Linux since that moment. If it happens again, please reopen.
