### ISSUE TITLE
LayerHistory - Make upgrading server easier

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#983]
You can retain the entire history if WebBin/Layers is copied to the new server dir along with the main game file but that seems clunky.

One option would be to store a minimal history (1 image/day) in the main save file and extract it if the Layers dir is missing.

**Comment by metachronism** [comment]
I would suggest storing the GIFs in the server save file, and just extracting them as normal when they are requested
