### ISSUE TITLE
Map API bug

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#9830]
/map/map.json
Should be returning:
WaterLevel
WorldTime

Used to work, but server is not returning these variables anymore.

**Comment by SeanAtr0n** [comment]
works in staging 
![image](https://user-images.githubusercontent.com/774628/47318566-3f4b2200-d601-11e8-8b0d-9b3c661b71f1.png)

I think @johnkslg  last touched the web server, maybe something broke then

**Comment by SeanAtr0n** [comment]
These two fields are get functions that used to get serialized

**Comment by SeanAtr0n** [comment]
might also be localization related?

**Comment by Nanders** [comment]
I dont think its localization related, I dont have these strings in the system

**Comment by Nanders** [comment]
But will check

**Comment by johnkslg** [comment]
Fixed!
