### ISSUE TITLE
Save won't load on user's machine, but works on other machines

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#9832]
Save is attached.

---

Original issue report:

"Hello, I was told to send an email here about the crash and loadup issues I have. I posted this on the steam forums already so I will copy and paste my issue here:

I usually play the game on single player as I am not up for the multiplayer yet
My issue comes from a world I have now played on for 5 days or so. I had to leave the house for about 2 hours and thought I could just queue up a task for that time. It all worked out and when I came back I wanted to restart the game just because. After this the game after loading the world fully, it would first end up in a black screen and after that end up in a white screen aka your game has stopped working.

I restarted the PC and repeated this and it happened again. Now I am here in hope someone knows what to do.

As I said, I restarted the PC already. I also verified the game files already.

One thing I havent done is reinstalling the game as I doubt that it will do anything if I dont delete every single file manually just as well. And since I want to keep the world..."

---

User can load any other save and even start new games, but this one fails to load. They also already tried a full uninstall/reinstall, and tried loading the save in both the Steam and Non-Steam versions of Eco.

Despite this, the save loads fine on my computer.

[Save.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2503553/Save.zip)

**Comment by Deantwo** [comment]
I am no expert on this, but if it only fails on your machine it might be caused by a corrupt client.
__Pam__ normally suggest deleting the mod folder and such, but it might be best if you ask her yourself in the #support channel on the Discord server.

**Comment by SlayksWood** [comment]
I assume that this issue isn't actual. Sorry for not helped in time.
