### ISSUE TITLE
Restricting Air Pollution for vehicles does not work, either

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9834]
When you choose "When attempting to emit Air Pollution" you get "where object is", but that will automatically change to "where time performed (days)" and show other options that are of no use as soon as you set an vehicle - the system seems broken:

<img width="878" alt="problem" src="https://user-images.githubusercontent.com/25908592/47344849-b6d48c00-d6a9-11e8-9a04-ab1e8e122bf2.png">

**Comment by johnkslg** [comment]
Should work in current civics system.

**Comment by beastyn** [comment]
merged with #9944
