### ISSUE TITLE
[ver.0.7.7.2] Incorrect display of the melting process on Blast Furnance

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#9836]
When smelting iron, gold or copper in Blast Furnance, instead of the required resource (iron ingot, gold ingot or copper ingot) in the smelting process, Tailing is displayed with the appropriate name "Tailing project".

---- Original Language - Russian -----

При плавке железа, золота или меди в Blast Furnance вместо требуемого ресурса ( слиток железа, слиток золота или слиток меди ) в процессе плавки отображается Tailing с соответствующим названием "Tailing project".
![20181022193939_1](https://user-images.githubusercontent.com/1098421/47349503-73cfe400-d6bc-11e8-9122-826c1e6e6d80.jpg)

**Comment by Deantwo** [comment]
Duplicate of #9227.

**Comment by Deantwo** [comment]
Duplicate of #9227.

**Comment by seccombew** [comment]
Closing as duplicate.

**Comment by Rambo99** [comment]
Ok.
