### ISSUE TITLE
[ver.0.7.7.2] Wrong recipe Steel in Blast Furnance

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#9837]
When trying to make steel (not to be confused with charcoal steel) in Blast Furnance, coal required for smelting by prescription (Coal) is taken not from the inventory or from the warehouse (Stockpile), but from the fuel supply section for Blast Furnance itself.

------ Original Message - Russian Language --------

При попытке изготовить сталь (не путать с  charcoal steel ) в Blast Furnance необходимый для выплавки по рецепту уголь ( Coal ) забирается не из инвентаря или со склада ( Stockpile ) , а из раздела топлива ( Fuel Supply ) для самой Blast Furnance .

**Comment by Deantwo** [comment]
You could have named this bug report better.
Maybe "Project uses coal from fuel storage" or something.

**Comment by elfl0rd** [comment]
Dupe - https://github.com/StrangeLoopGames/EcoIssues/issues/9638

**Comment by seccombew** [comment]
Dupe

**Comment by Rambo99** [comment]
Ok.
