### ISSUE TITLE
Lasers show wrong power consumption in crafting menu

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9838]
Lasers need 6000 Watts, not 15000 Watts:
![nimeton](https://user-images.githubusercontent.com/25908592/47363501-417fb000-d6d7-11e8-9e6a-427fe5a69e31.png)

**Comment by seccombew** [comment]
@D3nnis3n What version was this?

**Comment by D3nnis3n** [comment]
That happens on version 7.7.

**Comment by BlazeGuy2** [comment]
Fix merged in.
