### ISSUE TITLE
Water Pollution Spread is too insane

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9839]
We had that one guy not caring about tailings and pollution spread into water, a day later all oceans are polluted-red-colored and all fish died. I like challenge, but that is too much. This is a 4 km² planet. One does not simply fuck that up by having one guy having leaking tailings to the ocean, lol.

**Comment by D3nnis3n** [comment]
Here some data from our webinterface:
<img width="790" alt="suddendeath" src="https://user-images.githubusercontent.com/25908592/47544158-f1c30380-d8e5-11e8-992f-d5f3a90a3e8a.png">
Sorry, but fish just don't die that sudden on a 4km² world where someone had tailings in the ocean on one place.

**Comment by johnkslg** [comment]
There is a strong coefficient for flowing on water vs land, just need to reduce this somewhat.

**Comment by D3nnis3n** [comment]
This has actually become the other way, it's been a long time since i've seen ANY effect of pollution on water.

**Comment by WeaselDog** [comment]
Closing due to the problem being the opposite now
