### ISSUE TITLE
Object not spawning / invisible with no collision, Same thing is also used to enter other peoples house because of late spawning of  objects on login 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#984]
http://ecoforum.strangeloopgames.com/topic/1279/placeabel-items-not-shown-v0-5-2

**Comment by metachronism** [comment]
this is basically #678

**Comment by noblackthunder** [comment]
yea, but apparently sometimes they dont spawn at all making them invisible until you change some settings . you wanna close this issue and link it to the other? since this seems to be a duplicated issue here

**Comment by noblackthunder** [comment]
most likely same issue http://ecoforum.strangeloopgames.com/topic/1325/walking-through-objects

**Comment by metachronism** [comment]
closing as dupe of #678
