### ISSUE TITLE
During work order tutorial, exceptions get spammed

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9840]
This is during the tutorial showing work orders, that popup animation. Its probably using a component erroneously on it. 

NullReferenceException: Object reference not set to an instance of an object
UI.WorkOrderUI.Update () (at Assets/UI/Scripts/ItemOrSlot/WorkOrderUI.cs:47)

**Comment by johnkslg** [comment]
Doesnt actually break anything, so removing from 7.8

**Comment by SlayksWood** [comment]
Seems fixed
