### ISSUE TITLE
Districts display wrong when 2nd map in law comments

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#9843]
On proposed law page,
For a districts law, if there is a 2nd map in the comments. Then districts coloring displays wrong.
https://gyazo.com/7113bfeb3860c938b0e5664fd874e156

**Comment by SeanAtr0n** [comment]
hrm can't get it to do this reliably on master... what are the steps?

**Comment by SlayksWood** [comment]
this issue is no longer occurring, because Districts are creating in game now.
