### ISSUE TITLE
Critical Server Crash

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9850]
We have the following laws for "Emission Permits". Since about ten minutes after the enactment of the "Distribution of Emission Permits 2" law the server crashes with this error:
```
--BEGIN DUMP--
Dump Time
10/24/2018 18:18:13

Exception
Exception: Exception
Message:A MultiAtomicAction failed in the middle of execution. Which is bad. Error message: You cannot afford to pay a tax of <b><link="Currency:6fe3eb5b-edf9-4d03-8e5e-52f92867363b"><style="Currency">0,05 Emission Permit</style></link></b>
Source:Eco.Core

System.Exception: A MultiAtomicAction failed in the middle of execution. Which is bad. Error message: You cannot afford to pay a tax of <b><link="Currency:6fe3eb5b-edf9-4d03-8e5e-52f92867363b"><style="Currency">0,05 Emission Permit</style></link></b>
   at Eco.Core.Utils.AtomicAction.MultiAtomicAction.TryApply()
   at Eco.Gameplay.Items.WorkOrder.UpdateCrafted()
   at Eco.Gameplay.Items.WorkOrder.set_Progress(Double value)
   at Eco.Gameplay.Components.CraftingComponent.ProcessWorkOrders(Single dtime)
   at Eco.Gameplay.Components.CraftingComponent.Tick()
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

--END DUMP--
```
It then auto-restarts and crashes again, probably every time someone joins the server or it has something to do with running crafting projects of someone that can not pay the tax, as the error mentions?

Law 1:
<img width="1283" alt="law1" src="https://user-images.githubusercontent.com/25908592/47445991-7ca6df80-d7ba-11e8-8a34-1e08c3bb4105.png">

Law 2:
<img width="1327" alt="law2" src="https://user-images.githubusercontent.com/25908592/47446001-816b9380-d7ba-11e8-9a7e-14b22c954d6d.png">

All Crash reports up to now:
[dumps.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2511374/dumps.zip)

Game save: https://drive.google.com/open?id=16oSQNLK_uVwHtgt-Patn5l7u10-hLlVB
(Already deleted the distributing law in hope it would fix the issue, but it doesn't.)

**Comment by SHviid** [comment]
We had this problem. It was due to someone not having enough currency in their account, thus the server kept crash looping. I identied the user trying to craft, and quickly after a restart gave him currency to continue crafting. Then i removed the law and added something new to it: If your currency balance >50 then allow crafting tailings, if not prevent. This fixed it for us.

**Comment by D3nnis3n** [comment]
Well, if someone has not enough currency he should not be able to craft, that is pretty much the sense of the law and the expected output. It works with other things, so why the server goes into crash loop instead of just blocking the crafting as expected - ooof.

**Comment by D3nnis3n** [comment]
Same issue here: https://github.com/StrangeLoopGames/EcoIssues/issues/9485
Probably my save helps, though.

**Comment by johnkslg** [comment]
Added saves to other bug, closing this one.
