### ISSUE TITLE
Master: opening laws window crash server

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9854]
**Version:** 0.7.8.0 beta master-1f96455b debug
![default](https://user-images.githubusercontent.com/4980243/47449869-643fc080-d7cc-11e8-96aa-f6d87b8b4447.png)
![default](https://user-images.githubusercontent.com/4980243/47449882-6bff6500-d7cc-11e8-9826-0ba356d8d4ff.png)
![default](https://user-images.githubusercontent.com/4980243/47449805-3f4b4d80-d7cc-11e8-9a2b-83e0934e4a71.png)

**Comment by Quadbro** [comment]
Is this still reproducible? I can't get any crashes..)

**Comment by elfl0rd** [comment]
yep, looks fixed.
