### ISSUE TITLE
USER ISSUE: Camas Paste Wrong Icon in Economy Viewer

### ISSUE THREAD

**Issue by Trenix** [StrangeLoopGames/EcoIssues#9855]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Check economy viewer.
2. See someone who's buying or selling camas paste.
3. Realize it's the same icon as sugar and such, even though camas paste has it's own icon already in-game.

**Expected behavior:**
Camas paste should have it's own icon in the economy viewer.

**Actual behavior:**
Camas paste has a similar icon to items such as sugar.
**Do you have mods installed? Does issue happen when no mods are installed?:**
No.

**Comment by johnkslg** [comment]
The economy viewer pulls the 'foreground' texture out and omits the rest, it treats icons specially, just need to rearrange the icon definition for this one.

**Comment by WeaselDog** [comment]
This is fixed now
