### ISSUE TITLE
USER ISSUE: Random Skid Steer Acceleration

### ISSUE THREAD

**Issue by Trenix** [StrangeLoopGames/EcoIssues#9856]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Use Skid steer
2. Go into dig mode by pressing 1.
3. Use arm and press forward to move yourself up a block.

**Expected behavior:**
I should drive up normally.

**Actual behavior:**
I drive up and accelerate until I press forward to stop myself.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No

**Comment by SlayksWood** [comment]
merged to #12620
