### ISSUE TITLE
Hosted worlds - notification when removing items

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#9857]
When removing items from hosted worlds subscription. and not also adding items to subscription.
Successful paypal update sends user back to eco website, and notification says. "Purchase successful. please wait a few minutes for servers to start"

Should detect that no purchase is made, and just display notification "Your subscription has been updated."

**Comment by Tigran07** [comment]
https://github.com/StrangeLoopGames/Eco-Accounts/pull/44
