### ISSUE TITLE
Redefining Demographic Doesn't Start With Current Demographic Logic

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9859]
Look the screenshot, that is hilarious. Shouldn't it show the real clauses that define it at the moment?

<img width="425" alt="default citizenlaw" src="https://user-images.githubusercontent.com/25908592/47494553-3dc46880-d852-11e8-8710-304c97c24364.png">

**Comment by Deantwo** [comment]
What you did in that picture does not look correct, what are you trying to to remake? Picture if the default?

**Comment by D3nnis3n** [comment]
When you propose a law, choose "on law" passed, then "redefine demographic" and then choose "citizen" this is what you see. You should not see this, but the REAL clauses which is something along if player has played for more than two hours in the last 5 days.

**Comment by Deantwo** [comment]
Ah that is what you mean. Ok I understand and I agree. :+1:

**Comment by D3nnis3n** [comment]
It's so you can edit the current requirements with seeing them instead of this, which is just hilarious as i'm pretty sure if i do propose THIS law it will break. "You are a citizen if you are a citzen, and you are a citizen when you are a citzen, and you are that citizen if you are a citizen" - endless loop.

**Comment by johnkslg** [comment]
See why its defining it this way, it should be a complex query about playtime.

**Comment by Quadbro** [comment]
Is this issue located in web part of eco?)

**Comment by Quadbro** [comment]
probably i'll need  help from web developers, because it may take a lot of time to firstly dive into eco web-server ;)

**Comment by Deantwo** [comment]
Add [Laws](https://github.com/StrangeLoopGames/EcoIssues/labels/Laws) label for good measure please.

**Comment by johnkslg** [comment]
Sure does now!
