### ISSUE TITLE
/give claim,X does not longer work in 7.8

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9860]
I need to type /give PropertyClaimItem,X now which is just longer and tedious. Did some of the short cuts got removed?

**Comment by elfl0rd** [comment]
You use any localization?

**Comment by D3nnis3n** [comment]
Bleeding Edge, german localisation, did work in 7.7.

**Comment by elfl0rd** [comment]
Try "claim" in german (as it translated)

**Comment by elfl0rd** [comment]
and read this - https://github.com/StrangeLoopGames/EcoIssues/issues/9722

**Comment by D3nnis3n** [comment]
So you mean i should add " in front and end?

**Comment by elfl0rd** [comment]
no, enter claim as it translated on german

**Comment by D3nnis3n** [comment]
There really is no german translation for "claim", it's just the same thing as in english. Any translation that could be made would be a bad translation.

**Comment by elfl0rd** [comment]
yea, i see - https://crowdin.com/translate/eco-by-strange-loop-games/24/en-de#52171 looks as bug.
but it's fixed, read #9722

**Comment by D3nnis3n** [comment]
I keep the issue open, as i think that should be fixed in 7.8 if it was working in 7.7. If they don't want to, devs can close it themselves.

**Comment by elfl0rd** [comment]
It's fixed on 7.8 master branch, you can check it.

**Comment by D3nnis3n** [comment]
If there is an 7.8 master branch i have no access to it. It's not in staging, but in master and the latter contains many features not in 7.8, but probably 8.0. As it was also not in the bleeding edge version, like some other things haven't been that should have been there and were merged after my request, i'll keep it open until a dev closes it. I don't know from which branch they build the bleeding edge or minor versions released, i'm no developer.

**Comment by johnkslg** [comment]
Should be fine in master.
