### ISSUE TITLE
Effective Date for laws

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9861]
Yes, i know, this is a feature request. But not having this feature has an effect that could be considered bad game balance and can fuck up servers quite much.

You have a tax law. You want to change it. Someone proposes a change. Unfortunatley, he proposes the change just a little after the old tax did it's taxing. The new law passes. Now you get taxed twice, which, depending of the content of the laws can destroy the economy.

It would be insaneley good if you could set an effective date for every law when it has passed.
For example:

The old tax law went in place at day 3, 2:00. The new one is proposed day 4 2:15.
To evade the aforementioned problem i set the law to come into effect on day 6, 0:00.
The law will not be in effect immediatly after voting - but it will evade the double-taxation.

This feature can be useful for MANY other things, too.

Now think about you changing the tax laws quite frequently to adapt to things happening and get double taxed in only half of the occasions. ;)

**Comment by Deantwo** [comment]
Nah, don't close it. Like I said, I would love a way to set a "start time of day" for periodic laws.

**Comment by D3nnis3n** [comment]
Reopen, shall the developers decide what to do with it.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#617

**Comment by D3nnis3n** [comment]
As i said, Deantwo *g*

>
