### ISSUE TITLE
Flooding works strangely in the case of trees

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9863]
**Version:** 0.7.7.2 beta
![20181025192409_1](https://user-images.githubusercontent.com/4980243/47515497-b7c51380-d88b-11e8-8175-3fd165443f7e.jpg)
![20181025192401_1](https://user-images.githubusercontent.com/4980243/47515498-b7c51380-d88b-11e8-9be8-6ce651b0d943.jpg)

Terribe water hole nearby tree.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#616

**Comment by BlazeGuy2** [comment]
Reopening, issue mover tool has bugged out today.

**Comment by metachronism** [comment]
by design/wont support

**Comment by elfl0rd** [comment]
@D3nnis3n do you think? I know, this maybe not easy to fix and not high priority, but ignoring issues is not a right way...
Why "fill" available for bricks and not available for trees?
![default](https://user-images.githubusercontent.com/4980243/50826651-44d91e00-134d-11e9-8a93-0f27b8837710.png)

**Comment by D3nnis3n** [comment]
That's a good question i don't have an answer for. Maybe @metachronism knows more?
