### ISSUE TITLE
Dying trees - instantly disappears without stages of dying.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9864]
Currently, "dead" trees looks as live, the only difference is in the information.

I would like to see the stages.
1) yellowing foliage (e.g. when contaminated)
2) the leaves have fallen, branches still on tree
3) some branches fell off
4) the tree trunk falls, leaving a log, stump, and debris contaminating the surrounding area
5) log and stump disappear.

It's more of a proposal, but it's about refining existing content, so I'm not sure where to put it.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#615
