### ISSUE TITLE
Treasury Show Unused Currencies

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#9865]
Version: 7.7.2

The Economy window was changed to only show currencies that actually had some circulation. It would be very nice if this was applied to the treasury management too.

![image](https://user-images.githubusercontent.com/2676134/47524859-0da1b780-d89c-11e8-8883-64fd2876762b.png)

I don't know if this is changed in >v7.7.2 already.

**Comment by D3nnis3n** [comment]
I'd absolutley appreciate this for ease of use.

**Comment by johnkslg** [comment]
Treasury will be getting an overhaul so removing this for now.
