### ISSUE TITLE
Possible bug with sea level rising?

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9866]
We had high co2 values (up to 384), that raised sealevel to 43. Despite now being at 352, the sealevel has not fallen a bit.

<img width="799" alt="co2" src="https://user-images.githubusercontent.com/25908592/47544495-9db91e80-d8e7-11e8-9c29-1a866cd400b8.png">

**Comment by D3nnis3n** [comment]
Another server owner sent me this: They have gone from very high to no pollution and stayed there for quite a long time - no sealevel has fallen. This MUST be bugged.

<img width="875" alt="eco2" src="https://user-images.githubusercontent.com/25908592/47620711-a0856080-daed-11e8-9424-2178ccb7d1fa.png">

**Comment by SeanAtr0n** [comment]
afaik sea level never goes down as an intentional design decision

**Comment by SeanAtr0n** [comment]
you can use devfloodtool to remove layers of water 1 by 1 though

**Comment by johnkslg** [comment]
Sea level doesnt go down atm by design.
