### ISSUE TITLE
USER ISSUE: Efficiency causes duplication

### ISSUE THREAD

**Issue by draco89349** [StrangeLoopGames/EcoIssues#9868]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Build dirt ramp with 2 dirt, level 4 efficiency.
Place ramp and dig back up.

**Expected behavior:**
Gain only 2 dirt.

**Actual behavior:**
Gain 4 dirt.n
**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods are installed.

**Comment by elfl0rd** [comment]
dupe - https://github.com/StrangeLoopGames/EcoIssues/issues/9667
