### ISSUE TITLE
Builders dont consider transparent blocks 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#987]
![image](https://cloud.githubusercontent.com/assets/3536496/21666395/45736940-d2a6-11e6-93dd-3a4aee445733.png)

These windows face a rock wall, but the builder doesnt create it because it thinks its hidden

**Comment by metachronism** [comment]
This is a Keegan issue

**Comment by metachronism** [comment]
fixed a few days ago actually!
