### ISSUE TITLE
Devtool cannot destroy something like middle debris and uncut logs.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9874]
![default](https://user-images.githubusercontent.com/4980243/47562497-56528280-d927-11e8-8987-f3c9923cc27a.png)
split from - https://github.com/StrangeLoopGames/EcoIssues/issues/8128

**Comment by Deantwo** [comment]
Same with uncut logs, as discussed in #10114.

**Comment by D3nnis3n** [comment]
Those can not even be targeted, though. You won't get such a highlight as in the screenshot above. Not sure if that is the same issue.

**Comment by elfl0rd** [comment]
I don't think it makes sense to do 2 problems on similar behavior.

**Comment by BlazeGuy2** [comment]
PR is merged in
