### ISSUE TITLE
USER ISSUE: Password and Whitelisting

### ISSUE THREAD

**Issue by Mrkuff** [StrangeLoopGames/EcoIssues#9875]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
On a server i got : 
Network\Config\password = Something
Users\Display = 1 users / kuff_
Users\Config\Whitelist\String Collection = kuff_  (on 1 line, whitout white space at the end)

**Expected behavior:**
Should not ask for a password when clicking join button

**Actual behavior:**
Ask for a password, and the password work.  But should not ask for a password since i've got the name on whitelistingn
**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed

**Comment by elfl0rd** [comment]
You need use SLGid or SteamID64 in this field.
You can see it in description.
![default](https://user-images.githubusercontent.com/4980243/47564779-d4665780-d92e-11e8-8516-d9e0cea8af21.png)

**Comment by elfl0rd** [comment]
SLGID is NOT account name, you can see it on site, or use /whoami ingame.

**Comment by Mrkuff** [comment]
Ok.  And when I'm typing /whoami this give me a STEAMID64 of 17 numbers, that I can't select/copy from the UI who disapear after 10 secs !!!  and i need to ask that to all my remote user to update my whitelist ?  C'mon!  Then we need to change the User display with this ID.  "kuff_ 12345678901234517" !

**Comment by Mrkuff** [comment]
If this ID is secret, then change the whitelisting for using the UserName instead of the STEAMID64

**Comment by elfl0rd** [comment]
:D you can get your steamid64 trough any site like https://steamidfinder.com/

**Comment by elfl0rd** [comment]
Username can be changed, especially steam. ID - not.

**Comment by Mrkuff** [comment]
Ok then Im asking for a request of change ! Add the ID right after the user name on the Users\Display tab

**Comment by elfl0rd** [comment]
Agreed, but create new suggestion here - https://github.com/StrangeLoopGames/EcoSuggestions/issues

**Comment by Mrkuff** [comment]
thanks for the quick reply

**Comment by elfl0rd** [comment]
No problem :)
