### ISSUE TITLE
Localization: Lot of tutorials broken if server language not english

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9877]
(Master branch)
e.g. Setting Up Camp
![default](https://user-images.githubusercontent.com/4980243/47565531-72f3b800-d931-11e8-829e-c78c9cdc2cd1.png)
etc...
@Nanders ?

**Comment by elfl0rd** [comment]
Stockpiles, work orders, etc... - not fixed.

**Comment by elfl0rd** [comment]
It looks as fix is not applied onto release branch, please reopen. @D3nnis3n @Nanders

**Comment by D3nnis3n** [comment]
Reopened, not fixed.

**Comment by D3nnis3n** [comment]
The issue linked there seems to be the same - using a english server it works.

**Comment by D3nnis3n** [comment]
Seems fixed on my test, reopen if not.
