### ISSUE TITLE
Master: some tabs not shown (Critical!)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9878]
Authorization?
![default](https://user-images.githubusercontent.com/4980243/47565877-9703c900-d932-11e8-88cb-80353bc06e42.png)

Mint?
![default](https://user-images.githubusercontent.com/4980243/47565971-dcc09180-d932-11e8-9423-a61ec6b9ca2c.png)

Etc...

**Comment by johnkslg** [comment]
Look for what exceptions are happening in the client, probably something excepting and preventing the tabs from fully building.

**Comment by Quadbro** [comment]
Fixed in https://github.com/StrangeLoopGames/Eco/pull/3536

**Comment by elfl0rd** [comment]
@Quadbro you can add fixed issues into **Bugs Fixed:** section in request :P

**Comment by elfl0rd** [comment]
Hm... Can you check? No "cost" field in repair table interface. But tabs fixed, yes.
![default](https://user-images.githubusercontent.com/4980243/47642980-2dc2c680-db7b-11e8-80c0-f25c6d59dd99.png)

**Comment by Quadbro** [comment]
Repair desk is broken by another reason, i know it ;( 
Will fix it with adding repair fees, but you can make a dedicated issue for this)

**Comment by elfl0rd** [comment]
Okay, now in master - fixed, closing.
