### ISSUE TITLE
USER ISSUE: Fault tolerance issues

### ISSUE THREAD

**Issue by BlackWyvern** [StrangeLoopGames/EcoIssues#9882]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Have a terrible ISP.
Have a single ping over 200ms once every 40 seconds.
Try to exist.

**Expected behavior:**
Existence.
Expected some connection fault tolerance to prevent DC's or at least seamlessly catch back up.

**Actual behavior:**
Not existing.
Connection times out.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No.

**Comment by johnkslg** [comment]
Connection timeout is 10 seconds, if your ISP is that bad its dropping for 10 seconds at a time theres not much we can do, unless something else is happening?

**Comment by BlackWyvern** [comment]
No, it's not dropping connection nearly that long. I'll be in the middle of doing something, get the red connection symbol for 1-2 seconds, get kicked to main menu, then immediately able to reconnect. Total downtime, less than 5 seconds.

It just happens to co-inside with the 200+ms ping spike that I see come in at the exact same time on my pingplotter.

Kills discord too, but that's not yer thing.

**Comment by elfl0rd** [comment]
@johnkslg will be better if game try to restore connection multiple times, before "connection lost" error...

**Comment by D3nnis3n** [comment]
I agree, many people get kicked out of the game for this every day on our server.

**Comment by elfl0rd** [comment]
Yes, it really annoys many people. Moreover, periodic disconnects (red circle without throwing from the server) occur in some players and with normal Internet.

**Comment by SlayksWood** [comment]
@BlackWyvern 
Is there a issue in the latest versions? many improvements have been made to the connection. If it happens again, please reopen.
