### ISSUE TITLE
Master: rooms indicator work strange.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9883]
**Version:** 0.7.8.0 beta master-fc06dc16 debug
After removing all rooms, still on screen until server restart. Relogin - not helped.
![default](https://user-images.githubusercontent.com/4980243/47604790-f206f000-da06-11e8-9ab2-72599af44c8c.png)
And this color used for ANY first room.
General
![default](https://user-images.githubusercontent.com/4980243/47604963-211e6100-da09-11e8-9fe4-9d332111a84c.png)
Kitchen
![default](https://user-images.githubusercontent.com/4980243/47604967-2f6c7d00-da09-11e8-9467-8959f61422fb.png)

etc...

**Comment by johnkslg** [comment]
related to https://github.com/StrangeLoopGames/EcoIssues/issues/9884

**Comment by elfl0rd** [comment]
Happens on 7.7.2 too
