### ISSUE TITLE
Master: room indicator show wrong colors

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9884]
**Version:** 0.7.8.0 beta master-fc06dc16 debug

UI rooms colors not counts to Tutorial rooms colors (maube happens from - #9883)
![default](https://user-images.githubusercontent.com/4980243/47604941-dac90200-da08-11e8-8df5-997ea15e61d1.png)

![default](https://user-images.githubusercontent.com/4980243/47604928-a5bcaf80-da08-11e8-9af7-3042c01295ce.png)

Biggest - general, but have kitchen color, etc...

**Comment by johnkslg** [comment]
Make the titles of the rooms in the tooltip match the colors that the represent. Rearrange the tutorial so the colors line up with what theyre representing.  Do the same for food.

**Comment by johnkslg** [comment]
Could also make the background of food and furniture tint the color of the nutrient/room theyre associated with? not sure on that yet though, I think we'd need to tune the nutrient colors to be more similar for that to work.

**Comment by elfl0rd** [comment]
Happens on 7.7.2 too
