### ISSUE TITLE
Refund request

### ISSUE THREAD

**Issue by Weatt** [StrangeLoopGames/EcoIssues#9885]
It's been 23 days and nothing has happened to either of my bug reports and I'm unable to play the game until it's fixed. 
https://github.com/StrangeLoopGames/EcoIssues/issues/9645
https://github.com/StrangeLoopGames/EcoIssues/issues/9755

At this point I've given up, can I just get a refund because it's not worth it to check every day on a bug report only to see nothing has happened. I want to enjoy this game but at this point it's turned sour and I just want my money back.

**Comment by johnkslg** [comment]
Hey Weatt, sorry I will make sure these get looked at asap.

**Comment by johnkslg** [comment]
User has filed this review as well:
https://steamcommunity.com/id/Weatt/recommended/382310/#developer_response

**Comment by Spydarlee** [comment]
Hey @Weatt - I'm not having any luck connecting to SendSpace.com to download your save file. It seems the whole site is down right now - I'll keep trying, but if you see this before I get any further would you be able to upload the file anywhere else, please? Sorry/thanks!

**Comment by D3nnis3n** [comment]
@Spydarlee
https://drive.google.com/file/d/1EWmKZyQ9rldH16V7aa5rndPh60MjcCth/view?usp=drivesdk

**Comment by Spydarlee** [comment]
I haven't yet been able to track down the original cause of this problem, but I was able to fix the save manually: https://drive.google.com/file/d/1CFC2KX2Xnd8E4BPqfh4BAPAFXJsgR5XZ
