### ISSUE TITLE
USER ISSUE: World not loading competely 

### ISSUE THREAD

**Issue by gamenameign** [StrangeLoopGames/EcoIssues#9889]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Start the game and play for x amount of time.
2. disconnect
3. rejoin
4. world not fully loaded 

**Expected behavior:**
Been open world 

**Actual behavior:**
Missing chunks, able to float in the void n
**Do you have mods installed? Does issue happen when no mods are installed?:**
Missing chunks, able to float in the void

**Comment by seccombew** [comment]
Can you post your save?  Also, what OS are you running (Windows, Mac, Linux)?

**Comment by SlayksWood** [comment]
Are you having this problem now?
If it happens again, please provide your save file.

**Comment by SlayksWood** [comment]
Checked on 8.1.4. Wasn't able to reproduce, seems fixed.
