### ISSUE TITLE
Remove icon auto-guess

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#989]
![image](https://cloud.githubusercontent.com/assets/3536496/21668324/8eec5d20-d2b5-11e6-9573-a7dc59ad19be.png)

There are dozens of crazy icons in there because it guesses so badly. Make it match an exact string or an 'error' icon otherwise so we can identify these

**Comment by metachronism** [comment]
there is no icon auto guess...  you import them and set them up with a tool

**Comment by johnkslg** [comment]
Steven did not choose 'glue' for the 'shoes' item, that was auto assigned somehow.  Whatever auto assigned that needs to instead assign an empty/error icon rather than a bad guess.

**Comment by metachronism** [comment]
yes, this is keegans realm and afaik everything here is working as intended in the toolset.
