### ISSUE TITLE
No law trigger for creating dirt roads

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9890]
With all these fancy automatic road laws - why can't we also allocate people for doing early roads with the road tool? Only people skilled in can repair it and they use a hell lot of calories, but we can't even allocate them money, despite they have the hardest road job of all.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/8380

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/8380
