### ISSUE TITLE
New Behaviour of ramps make some road laws impossible.

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9891]
Earlier:
If you place a dirt ramp = allocate 1 dollar
If you remove a dirt ramp = tax 1 dollar
Noone would abuse or grief.
Everything is fine.

Now:
If you place a dirt ramp = allocate 1 dollar
if you remove dirt = tax 0,25 dollar (so if you dig away the complete ramp you have made no profit)

STOP - people often need to dig out dirt to make a road, so we now need to tax them for this which is insane, not giving dollars for dirt ramps anymore or just accept that people will go on a road, place dirt ramps and remove them until they are millionaires or an admin sees them and bans them.

Together with all the other issues this change has caused i would really recommend reverting it.
(Especially the broken recipe that encourages people to only build ramps, then dig them up, to get more of the road item out than they would have if they had made the roads directly instead of the ramps; but also the inconsistent methods of removing the ramps and some of the other issues that have been posted earlier)

This change was inconsistent with road blocks and is discouraging to use laws for automation. Probably not what you wanted. While one-block wide ramps are good, this causes more problems then it has use for.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/8380

**Comment by D3nnis3n** [comment]
That's an entirely different issue.

**Comment by D3nnis3n** [comment]
Fixed.
