### ISSUE TITLE
Demographics - Who is in which group? - Am i in this group?

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9893]
So we have demographic groups now and can see the requirements in the game. But how am i supposed to know if i did play exactly 10 hours in the last two days? How am i supposed to know if i claimed land 100 times? How am i supposed to know who did that at all?

Neither in the webinterface (where there seems to be no demographic overview at all oO) nor in the game i can see who is part of which group - i can't even see if i am in a specific group. That makes planning on laws and giving access to groups a bit less intuitive, as the information could be very useful.

I'd propose to at least add to the demographics list in the law tab IF you are member or not.
Probably by adding a green or red text to the group that says "MEMBER", "NOT A MEMBER".

Additionally you could add which requirements you do have reached and which not, probably even with numbers. Like showing 9/10 hours played in the last two days.

And for making it perfect you could also show a list of who is part of that group. Probably by a button that hides and opens the list.

**Comment by Deantwo** [comment]
When implemented a webpage for this, it might be useful to keep in mind that we would like players with specific government titles to maybe have manually managed demographic groups. If the webpage is made with this in mind, it might be simpler to implement later.

**Comment by TheKrush** [comment]
I would also like to see some additional information to know who and/or how many people are in each demographic in-game and/or through the web interface.

**Comment by D3nnis3n** [comment]
Same for titles.

**Comment by SlayksWood** [comment]
Now you can watch  it in the Government. Seems ficed.
![image](https://user-images.githubusercontent.com/45708377/67391351-29bb6000-f5a7-11e9-89fd-cb7615310d54.png)
