### ISSUE TITLE
New Law Tab in 7.8 is hard to read

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9894]
The new law tab in the game in 7.8 is hard to read as white text is on bright background, i have issues to read this. I'd prefer something else that is easier to read, especially when you have bad eyes like me. It's never a good idea to write white on bright background.

**Comment by WeaselDog** [comment]
It seems to be fixed in 9.0 with new in-game law interface. Please reopen if it is still an issue.
