### ISSUE TITLE
7.8+ Main menu takes forever to fade in

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#9896]
easily 15+ seconds

**Comment by D3nnis3n** [comment]
Cannot reproduce in my testing in 7.8 bleeding edge, main menu is there immediatly.

**Comment by D3nnis3n** [comment]
I did not click.

**Comment by D3nnis3n** [comment]
Can confirm when not Alt-Tabbing all the time, it does indeed take very long on newest bleeding edge.

**Comment by SlayksWood** [comment]
still an issue 0.8.1.3

**Comment by johnkslg** [comment]
This is intentional! Its to set the mood.

**Comment by johnkslg** [comment]
It does require reverting the removal of the fade in sequence though.
