### ISSUE TITLE
loading screen animation takes longer than actual load

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#9897]

**Comment by metachronism** [comment]
the little tree thing that is, on a built version, it takes 5+ seconds to play the animation but the scene load takes considerably less than that

**Comment by SeanAtr0n** [comment]
it can also take considerably more time

**Comment by johnkslg** [comment]
I'd rather let it play than have it cut off early.
Think of it as a time for meditation and reflection...
