### ISSUE TITLE
Looking at the meteor sometimes does not trigger tutorial

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#9898]
I was staring directly at the meteor (the timer was visible), and the tutorial task/introUI was not triggering

**Comment by elfl0rd** [comment]
Yes, as far as I can see you need to run the tutorial and then transfer the camera to the meteor

**Comment by Nanders** [comment]
yeah I had the tutorial open and waiting to trigger

**Comment by D3nnis3n** [comment]
I noticed the meteor had to be near enough to trigger (time being visible seems to be not enough), but it triggered in all my test cases.

**Comment by Quadbro** [comment]
All is okay there, current tutorial mechanics requests to click on tutorial icon, before it get's started (it triggers looking on meteor hooks)
