### ISSUE TITLE
Feature: ability to set color for titles\reputation.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9899]
Before recent changes, nickname color based on reputation. e.g. bad = red and good = green
Now the colors are changed and the owners of the servers can not configure them.

For example, customizing reputation colors would be nice in this section.
![default](https://user-images.githubusercontent.com/4980243/47671097-e1e64080-dbbf-11e8-9aa2-8a8a7a9970af.png)

p.s. by results of a question to JohnK in discord.

**Comment by D3nnis3n** [comment]
Linking related issue https://github.com/StrangeLoopGames/EcoIssues/issues/9288
Colors are not consistently displayed and the new color for good rep is ugly and unintuitive.

**Comment by Quadbro** [comment]
So it's confirmed, and i need to add color field there?

**Comment by elfl0rd** [comment]
Well, I think it's the best place to rep. color settings. :)
and ofc, need store parameters in config and apply selected color ingame.

**Comment by elfl0rd** [comment]
In addition - would be good if you make default colors.
Bad reputation - red
neutral - yellow (or white)
good - green
