### ISSUE TITLE
0.5.3 Severe Lag Within 5 Minutes ( memory leak) 

### ISSUE THREAD

**Issue by Airidal** [StrangeLoopGames/EcoIssues#990]
Type: Client

   OS: Win 7 and Win 8 -  Occurring on two machines,

    Detailed Description of Issue: Ever since the update even if the graphics settings are drastically reduced there is an extreme amount of lag when playing on the SLG server.

    Reproducible: Yes  Difficultly to reproduce: Effortless

    Steps to reproduce bug/issue: Login to server and although it's fine to start with within 5 minutes the lag is severe.

    Additional Comments:  Nvidia graphics cards, both have up to date drivers.  Verified by logging into 5.2 and loading another server that the lag is limited to the 5.3 load.

    Client Version: Alpha 0.5.3

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/1268/memory-leaking/14

**Comment by Airidal** [comment]
Thought you might like the details on one of the machines having the issue that you requested on the linked post.  My husband is having the same issue, but his laptop is an older model.

CPU: Intel Core i7-4810MQ 2.8Ghz
GPU: GeForce GTX 880M
RAM: 32 GB

Eco is maxing at about 3.5 GB usage for me, so nothing drastic and about 25% CPU

I just trekked away from trees, there are none within view and I haven't seen any improvement.
I have also attached a screen shot of my settings at the time of my most recent round of testing.

![eco settings](https://cloud.githubusercontent.com/assets/24929153/21700049/6825964a-d36c-11e6-935c-3cd93fb112d8.gif)

Both myself and my husband have checked on another server, Steplife, and the SLG server we have been playing on and it does seem to be tree related.  On the SLG we have our "home" in a heavily wooded area.  We are okay until we go into a wooded area and then the game doesn't recover even if we leave the wooded area.

I hope some of that information is helpful.

**Comment by noblackthunder** [comment]
There is a known issue with the map. if you do not open the map in your play session  does this also happen then?

**Comment by Airidal** [comment]
This does look to have been the issue, thank you for making that connection =) *hug*

**Comment by noblackthunder** [comment]
that map issue is being worked at =) so there is hopefully a fix for that soon

**Comment by Linrox** [comment]
I don't think the map is the only issue. Both the 32bit and 64bit versions for 0.5.3 use more memory then what is stated it would use.
The 32bit will crash because it uses more than 3.5Gb of ram and the 64bit will also maxout the memory used and lag the whole way.

**Comment by noblackthunder** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/1026
