### ISSUE TITLE
Master: mint broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9902]
Main tab empty.
![default](https://user-images.githubusercontent.com/4980243/47674533-91271580-dbc8-11e8-9432-6c47468325f4.png)
![default](https://user-images.githubusercontent.com/4980243/47674543-971cf680-dbc8-11e8-8a64-4ad0044041ec.png)

**Comment by Pradoxzon** [comment]
![temp](https://user-images.githubusercontent.com/25668381/47874177-80091f00-dde9-11e8-928d-57f4a17fc8ce.png)
I'm not very well versed in Unity, but it looks like something might be off with the prefab for the mint component. The Inspector doesn't show anything when the prefab is clicked.

**Comment by johnkslg** [comment]
This should be fixed now
