### ISSUE TITLE
Rework skillbooks/scrolls

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#991]
Remove skill scrolls.
Add a slot to the user inventory for skill books.  While equipped, the user will start learning the skill (different books can have different times required to read).  Once complete the user learns the skill and can unequip the book to trade/sell/loan to any other players.

**Comment by NafenX** [comment]
Researching a skill in the research table should give you a 'Discovery' item which when consumed will unlock the skill and turn the Discovery into a Skillbook item that the player can then trade or sell to another player who would then have to put the book into the learning slot . Or even maybe add the book to his Bookshelf in a public library type building.

I just feel that the person who puts the resource costs and research time should get the discovery and unlock the skill instantly when the research finishes, but not be able to pass on this instant skill unlock (like with scrolls).

**Comment by metachronism** [comment]
no longer relevant with skill changes
