### ISSUE TITLE
Mint - Disyplaying amount is wrong

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9910]
The mint currency creation screen where you choose the item says "amount" at the bottom, while it should say "item" or something fitting better. Probably, as of this issue i recently closed https://github.com/StrangeLoopGames/EcoIssues/issues/4966 earlier you could choose how many gold ingots make the 10 coins that were not changeable. (Cannot remember that time, though)

So you could either rename this text or add (back) the possibility to choose an amount of gold ingot per amount of coins created. (Which is no longer useful, as when you want 2 gold ingots = 1 coin you could just do 1 gold ingot = 0.5 coins)

<img width="551" alt="mint" src="https://user-images.githubusercontent.com/25908592/47748873-19222380-dc8c-11e8-9673-2fad41fc67fa.png">

**Comment by elfl0rd** [comment]
And this window have another problem, e.g. https://github.com/StrangeLoopGames/EcoIssues/issues/9146
