### ISSUE TITLE
Web API's citizen activity query not sending GUID

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#9912]
On master branch, In web interface, on Citizen Activity page:

When I click on discussion link for Citizenship law. It breaks because the API is not sending a GUID for the discussion.
 https://gyazo.com/9a49368b340a396594f1383ea20fb8dd

This is in query /analysis/discussions/suggest
https://gyazo.com/5ac31808b82665116610c574b6b36f06

**Comment by Spydarlee** [comment]
Apologies, I'm not very familiar with the web interface - where can I find this, @rainfarmer?

I can propose a new law called 'Citizenship' which has a discussion area underneath it (which works as expected) but I can't find the 'Citizen Activity'? Do I have to access it from within Eco? This is what my web interface looks like:

![image](https://user-images.githubusercontent.com/553695/52643536-27abe800-2ed5-11e9-8c8f-3a2b0e1ec03f.png)

**Comment by rainfarmer** [comment]
@spydarlee its removed from game, while we fix and update it

**Comment by Spydarlee** [comment]
I'm gonna assign this back to you for now then, if that's okay? If there's something I can help with game-side please lemme know and assign back, though!

**Comment by rainfarmer** [comment]
feature removed from game for now
