### ISSUE TITLE
USER ISSUE: **Version:** 0.7.0.8 beta

### ISSUE THREAD

**Issue by olehderkath13** [StrangeLoopGames/EcoIssues#9913]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Could not start server: Process has not been started.
```

**Comment by elfl0rd** [comment]
1) Update your game, actual version is 0.7.7.2
2) What OS you use? X64? X32?

**Comment by D3nnis3n** [comment]
Has there ever been a 7.0.8? Probably spelling mistake?

**Comment by elfl0rd** [comment]
> Has there ever been a 7.0.8? Probably spelling mistake?
why not? Public wersion started from 0.6 as i know.

**Comment by D3nnis3n** [comment]
I don't remember so many hotfixes per patch i mean *g*

**Comment by elfl0rd** [comment]
> I don't remember so many hotfixes per patch i mean g

in any case, we do not know because the user is silent :)

**Comment by BlazeGuy2** [comment]
Reopen if issue occurs on 7.7.2, latest version.
