### ISSUE TITLE
Master: Ecko chair? :D

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9915]
![r](https://user-images.githubusercontent.com/4980243/47863577-a25e6500-de08-11e8-9c5d-1987a48c9101.gif)

**Comment by SeanAtr0n** [comment]
so?

**Comment by elfl0rd** [comment]
That the statue could be used as a seat - planned behavior?

**Comment by SeanAtr0n** [comment]
yes planned

**Comment by D3nnis3n** [comment]
Dolphin-Riding, how cool <3
