### ISSUE TITLE
Ecko tribute mechanics broken, lost or removed?

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9916]
E.g. Ecko accepts your tribute of {0} and grants you {1} for your devotion.

(EckoTheDolphinItem.cs)

**Comment by D3nnis3n** [comment]
Well how it works then? i thought when having the statue in inventory it requests a tribute to convert into another item, but that does not seem the case? (You can also answer me on discord, same name there)

**Comment by craig-jong** [comment]
This should still work, but not on the statue. As said earlier the ability to tribute items is only on the tool version, but its kinda overpowered so its not really intended for normal play (yet!)
