### ISSUE TITLE
7.8 Stuffed Elk Law Null Ref

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#9917]
![image](https://user-images.githubusercontent.com/6262198/47869307-de230b80-ddc3-11e8-8a2f-ef22d0088fe7.png)

```>	Eco.WebServer!Eco.Webserver.DataTransferObjects.Law.Law(Eco.Gameplay.Items.Law law) Line 38	C#
 	Eco.WebServer!Eco.Webserver.DataTransferObjects.LawEventSet.LawEventSet(System.Guid lawGuid, System.Collections.Generic.List<Eco.Webserver.DataTransferObjects.LawEvent> events) Line 36	C#
 	Eco.WebServer!Eco.Webserver.Web.Controllers.LawController.ListLawActivity.AnonymousMethod__2_11(System.Linq.IGrouping<System.Guid, Eco.Webserver.DataTransferObjects.LawEvent> x) Line 112	C#
 	[External Code]	
 	Eco.WebServer!Eco.Webserver.Web.Controllers.LawController.ListLawActivity(double startDay, double endDay, bool includeVoteChanges) Line 106	C#
 	[External Code]	
```

**Comment by Quadbro** [comment]
can't  propose any law to get this case sending null ref... webform seems to be broken, or I'm proposing wrong?)

**Comment by BlazeGuy2** [comment]
Found the cause: occurs when a User opens the Citizen Activity Tab from the webpage.
![law_bug](https://user-images.githubusercontent.com/35509188/48101352-76adf700-e1db-11e8-9e46-8cd7da5d998a.PNG)

**Comment by BlazeGuy2** [comment]
Also using the 7.8 stuffed elk save stored in SVN.

**Comment by BlazeGuy2** [comment]
Caused by trying to find a failed law w/o checking the failed law list.  Added fix to an earlier PR of mine.
