### ISSUE TITLE
[7.8.0 #E50965c6] Only one Belt?

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9920]
Is there only one belt in the character creation screen or is it not working, as pressing the buttons does not give any other belt? Remove the buttons if there are no other belts.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/3549 :P

**Comment by D3nnis3n** [comment]
Closing for duplicate :D
