### ISSUE TITLE
[7.8.0 #E50965c6] You can't unequip clothes with right click

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9921]
Moving this from a comment in the QA-Pass-Sheet to an issue. While you can equip clothes with right click you can't unequip them like this, would be much more comfortable than dragging.

**Comment by beastyn** [comment]
@D3nnis3n you can unequip with left left click. Cloth will movw to the tool bar first. Can we livw with that?

**Comment by SlayksWood** [comment]
I think that unequipping item with LMB is more than enough.
Closed for now.
