### ISSUE TITLE
[7.8.0 #E50965c6] I was not able to trigger the foraging tutorial

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9923]
In this run-through i couldn't get the foraging tutorial to trigger.
I tried:

- Eating food
- Harvesting food
- Harvesting food and grass with scythe
- Hoe dirt
- Place seeds on hoed dirt

The latter did work last time. I'm out of luck it seems, i don't really know what i'm supposed to do to get it and really, new players should get tutorials easily.

IMPORTANT: (See comments) I was also NOT able to get the foraging tutorial to trigger with no calories left, either.
****

**Okay i found out what the problem is:
The foraging tutorial only triggers when your stomach is empty, not when you have no calories.
You can have no calories by working but still have stomach contents, though. E.g. Protein and all the other things must be exactly zero for the tutorial to appear. It's not very likeley that this happens.**

**Comment by elfl0rd** [comment]
criteria - "no calories"

**Comment by D3nnis3n** [comment]
Last time i tried it it triggered when i placed a seed. Funny. I think this should not be the trigger. When you are hungry it's already too late for some of the plants that need scythe or digged up. I'd propsoe to change this to something else, e.g. this is a suggestion. I'll just try to confirm that the criteria mentioned by elfl0rd works.

**Comment by elfl0rd** [comment]
Yes, in addition, many players ignore training.
And not cancel it...

There is my old issue - https://github.com/StrangeLoopGames/EcoIssues/issues/8171

**Comment by elfl0rd** [comment]
> Last time i tried it it triggered when i placed a seed

Perhaps you spent the last calories in this?

> When you are hungry it's already too late for some of the plants that need scythe or digged up.

However, when you start, you do not have scythe

**Comment by D3nnis3n** [comment]
Yeh, that probably happened by chance.
Not having a scythe is of no matter, what happens when you spawn in the ice regionwhere only the scythe-able plants grow? People need to be told how to harvest earlier. Trigger the tutorial after the food tutorial or trigger it on harvesting a plant.

**Comment by elfl0rd** [comment]
As far as I understand the logic, food collection training is planned before food training.

However, I agree, food training is made awkward and inconsistent.

**Comment by D3nnis3n** [comment]
But this does not happen - you take the tomatoes out of your tent, eat them, get the food tutorial, eat them. And when you have no more you probably get the foraging tutorial. That's not the way it should work.

How about implementing this "low on food warning" of your mentioned issue and trigger the foraging tutorial when it happens? So you still have some calories and can easily take care of the tutorial? That's probably the best solution.

**Comment by elfl0rd** [comment]
> I don't get what you mean. 

what exactly is unclear?
Adding a food collection tutorial in first tutorials after player join?

**Comment by D3nnis3n** [comment]
I already got that and edited my post.

**Comment by elfl0rd** [comment]
Agree.

p.s.
https://github.com/StrangeLoopGames/EcoSuggestions/issues/620 and https://github.com/StrangeLoopGames/EcoSuggestions/issues/560 Would be cool.

**Comment by D3nnis3n** [comment]
IMPORTANT: I was NOT able to get the foraging tutorial to trigger with no calories left, either.

**Comment by elfl0rd** [comment]
You reset your tutorial before you tried?
As i know, completing "food tutorial" blocking "foraging tutorial" from show :D

**Comment by D3nnis3n** [comment]
Yes. I then completed the food tutorial first, as most players would do.
I just tried with not completing the food tutorial - doesn't trigger either.

**Comment by D3nnis3n** [comment]
Okay i found out what the problem is:
The foraging tutorial only triggers when your stomach is empty, not when you have no calories.

**Comment by elfl0rd** [comment]
> The foraging tutorial only triggers when your stomach is empty, not when you have no calories. 

I can only say
![-this-is-fine](https://user-images.githubusercontent.com/4980243/47915059-b65ea100-deb2-11e8-9ff2-d0dc6d68de2a.png)

**Comment by D3nnis3n** [comment]
But hey, now they finally know whats probably wrong.

**Comment by elfl0rd** [comment]
However, I think it would be good to hear @johnkslg opinion.
