### ISSUE TITLE
[7.8.0 #E50965c6] Auto-generated Deed Names for Vehicles should not be called like "town", "field" or anything related to normal properties

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9924]
See title.

**Comment by elfl0rd** [comment]
In addition, I think that it would be nice to call the deed associated with the transport by the name of this transport.

**Comment by WeaselDog** [comment]
In 0.9.0 staging-1293, they are always called "[Owner]'s Vehicle Deed". The owner can rename it from the authorization tab.
![VehicleDeed](https://user-images.githubusercontent.com/47330823/70734792-c524a380-1cc1-11ea-9624-9c11b8b0adbd.png)
![VehicleDeedRename](https://user-images.githubusercontent.com/47330823/70734798-c786fd80-1cc1-11ea-9f1c-dbff886b8813.png)

**Comment by D3nnis3n** [comment]
Would prefer it to show the type of vehicle instead, as GDragon suggested. Therefore keeping it open.

**Comment by johnkslg** [comment]
good idea, sneaking in a fix

**Comment by D3nnis3n** [comment]
Thanks John!
