### ISSUE TITLE
[7.8.0 #E50965c6] Proposing a law kills the server (Critical!)

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9926]
No dump is generated, the server shows this for a minute and then closes:
<img width="678" alt="stackoverflow" src="https://user-images.githubusercontent.com/25908592/47910940-9d46f780-de94-11e8-955b-1ed62e4038e8.png">

**Comment by D3nnis3n** [comment]
Same happens when running for office.

**Comment by Deantwo** [comment]
Maybe related to #9917?

**Comment by D3nnis3n** [comment]
I can offer the savegame, if you need it, but no dumps or whatsoever unfortunatley.

**Comment by johnkslg** [comment]
Yes please attach save! Thanks

**Comment by BlazeGuy2** [comment]
Was able to repro w/o save, but I'll use the save to test the fix later.
