### ISSUE TITLE
[7.8.0 #E50965c6] Special Characters don't show in the rename menu of world objects

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9927]
<img width="663" alt="picture1" src="https://user-images.githubusercontent.com/25908592/47913260-bbfcbc80-de9b-11e8-8bc6-7fa581282524.png">
Note that they also do net get saved in the rename field (e.g. clicking into it after placing those cars in, you will have a empty field), but are displayed in the name of the stockpile in the inventory screen below correctly.

**Comment by elfl0rd** [comment]
With Russian language was similar: https://github.com/StrangeLoopGames/EcoIssues/issues/7355

**Comment by D3nnis3n** [comment]
Something must have changed, at least the "x" sign in the picture i tested in the other versions and they did work correctly.

**Comment by seccombew** [comment]
@Nanders Moving to 8.0 milestone

**Comment by Quadbro** [comment]
Issue was in text field config
