### ISSUE TITLE
[7.8.0 #E50965c6] Remove debris contract is not working correctly with living trees on it

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9928]
If you put a contract for a propety to remove tree stumps and debris it will want you to also remove the stump of the tree that is still livjng - but you cannot cut the tree down to cut it's stump, even though its green. You just saw for an hour with your chainsaw with nothing happening.

Tree stumps of living trees should not be counted towards this contract.

**Comment by D3nnis3n** [comment]
Screenshot above says no debris in the contract, there is no debris, but there are living trees. Contract doesnt complete. Weird.

**Comment by SlayksWood** [comment]
Fixed in 8.2.x.
