### ISSUE TITLE
7.8.0 Meteor impact text appears over UIs

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#9932]
![image](https://user-images.githubusercontent.com/6262198/47939666-5ca3aa00-dea5-11e8-853b-c6559664e70d.png)

**Comment by BlazeGuy2** [comment]
@Nanders This occurring on staging?  Fix is set to merge into master.

**Comment by Nanders** [comment]
Yes, current staging on steam

**Comment by BlazeGuy2** [comment]
@Quadbro can you apply this fix to staging as well?
