### ISSUE TITLE
Highlight Server Admins

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9936]
In request of johnk, we'd like to add a way to show who is Admin in the server, so players know who they can contact.

**Comment by Quadbro** [comment]
And in what way it can be implemented? Constantly change admin nickname, or some server-world info? User groups?

**Comment by D3nnis3n** [comment]
Probably a special icon displayed in front or as of the eco icon there after the admin user name in all appearances in the game would be enough. (Probably with a red text "SERVER ADMINISTRATOR" in the users tooltip. Recoloring the name would not be working out, as there is reputation. Serverinfo does not help, when the admin is chatting ingame and people need to know he is an offical of that server. I'd also love to have some kind of incognito function to NOT show admin status if needed, that came in handy in other games earlier. Probably wait what @johnkslg has for ideas for this.

**Comment by D3nnis3n** [comment]
I dunno if there are already plans to mark World Leader and Government Officials in some way - that would be handy, too, i had made a suggestion for this earlier - if yes, you probably could re-use this system to show admin-status. But i don't know.

**Comment by johnkslg** [comment]
Can just add an /admins chat command that prints the admin list of usernames, super simple. 
Later we will do an icon pass

**Comment by Deantwo** [comment]
@Quadbro, how was this fixed anyway?
I think I remember reading about a `/admins` command being added, but i see no mention of it anywhere.
For example: https://eco.gamepedia.com/Chat_Commands#Player_Commands

**Comment by Deantwo** [comment]
Found the #codestream entry for it, seem to be called `/ListAdmins` instead of the proposed `admins`.

I can't see more, but here is 
the link: httpsithub.com/StrangeLoopGames/Eco/pull/3577
