### ISSUE TITLE
7.7.2 - Law lagging - amount check

### ISSUE THREAD

**Issue by Knigge** [StrangeLoopGames/EcoIssues#9937]
When this law passed:
Law:
When attempting to Sell
If (your Sell actions = 50)
Then allocate 5 currency
Otherwise allow

The server began having very long delays in trade action, and a simple trade took 1 second, trading two items a bit longer, trading a stack of 20 took longer -etc. It seems that each single item traded counts as one "trade action" and the law might check the sanity for all those instances.

This becomes a problem when you sell huge amounts of items. 
As the law is written, it would imply that its a simple check to see if actions(sell) = 50, but i suspect it counts this variable for every single item sold for every single trade. That might be an issue.

**Comment by Knigge** [comment]
I counted:
Sell:
1 item - 2 sec
2 item  - 5 sec
3 item - 6 sec
4 item - 9 sec
5 item - 9 sec
6 item - 11 sec
7 item - 12 sec
8 item -12 sec
9 item - 16 sec
10 item -18 sec

From that testing it seems that its a counter for each single item in each trade that delays the trade for the check.

**Comment by Deantwo** [comment]
First of all, that law definitely doesn't do what you expect it to do. I can help you with the law in the #law-examples channel on Discord if you want.

Secondly, the issue is probable that you are querying a VERY LARGE datatable.

**Comment by Deantwo** [comment]
Yeah so it is a one-time new-player reward style thing.
I would recommend just using the "logs on for the first time" trigger instead, and then simply take the money away from them again if they are offline for a week.
See: https://cdn.discordapp.com/attachments/469297188909088789/507237650361614337/Abandonment_Tax.png
