### ISSUE TITLE
Able to pollute despite a law preventing Truck/Excavator from polluting unless admin(check tax too)

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#9944]
![unknown](https://user-images.githubusercontent.com/841990/48057470-66ceec80-e1b4-11e8-94e2-3874d3a11e23.png)

![capture-airpollution](https://user-images.githubusercontent.com/841990/48057529-8e25b980-e1b4-11e8-81aa-6ba62776269d.JPG)

**Comment by D3nnis3n** [comment]
I want to crosslink all the other pollution issues that make controlling pollution nearly impossible atm:
https://github.com/StrangeLoopGames/EcoIssues/issues/9828
https://github.com/StrangeLoopGames/EcoIssues/issues/9834
https://github.com/StrangeLoopGames/EcoIssues/issues/9492

Please note - as of it stands now - sealevel does never go back. We need ways to fix this with the law system then!

**Comment by Deantwo** [comment]
To be noted, after a little while the law did take effect and prevent the use of the vehicles, it just didn't affect vehicles right away.

**Comment by johnkslg** [comment]
Should be working in new civics system current build:
![image](https://user-images.githubusercontent.com/3536496/68905910-9b468400-06f7-11ea-9ae6-c359abeec5a9.png)

**Comment by SlayksWood** [comment]
1. Wrong filter. I haven't some vehicles like Excavator, Skid Steer. Haven't world objects with polution (for example Blast Furnace).
![image](https://user-images.githubusercontent.com/45708377/68928823-0f3a6800-079c-11ea-83c4-edb581eac76c.png)
2. Create law for Truck(can create for any vehicles)
![image](https://user-images.githubusercontent.com/45708377/68929012-70623b80-079c-11ea-8c43-3cd1f39ed61f.png)
- pass law and try to use Truck. Server crash. 
![image](https://user-images.githubusercontent.com/45708377/68929152-d2bb3c00-079c-11ea-8348-1e482985cc01.png)
[log_191115111520.log](https://github.com/StrangeLoopGames/EcoIssues/files/3850554/log_191115111520.log)

**Comment by johnkslg** [comment]
good catch, fixed again.

**Comment by beastyn** [comment]
Need to recheck, don't dee vehicles in filter right now

**Comment by WeaselDog** [comment]
The issue is fixed for vehicles and crafting tables. Tax laws work too but behavior is a little strange.
![ExcavatorLaw](https://user-images.githubusercontent.com/47330823/72030051-bb4c7c80-323c-11ea-9d00-2eab3c8867c1.png)

**Comment by WeaselDog** [comment]
Pollution tax works fine too. I found a proper way to do it:
![PollutionLaw](https://user-images.githubusercontent.com/47330823/72035856-edb2a580-324d-11ea-9b9e-1333f81621f7.png)
