### ISSUE TITLE
Fir Seed is not available, producible in game, only by /give-command

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9948]
Version: v0.7.7.2-beta

I wanna remind of this old (maybe forgotten) Issue #5786. It’s a basic function and I would prefer to have before new features and bugs occlude it.

**Comment by D3nnis3n** [comment]
Even though being a reminder this is a duplicate issue, therfore closing it. 
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5786
