### ISSUE TITLE
workbench storage 5.3 bug creating multiple instances of diff storage items ?

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#995]
so here is what my work bench storage is suppose to look like
![workbench 2](https://cloud.githubusercontent.com/assets/15990789/21691684/3fc96172-d33f-11e6-8992-3d7b7e0f7cbf.jpg)

but sometimes when i click on it this is what it will look like

![workbench](https://cloud.githubusercontent.com/assets/15990789/21691697/4ba34256-d33f-11e6-84a5-71483d9d912d.jpg)

my workbench storage seems to swap back and forth between multiple instances displaying diff storage items in diff locations randomly ?

I never know if i am going see the items in pic one or if i am going see stuff in pic 2 ? its magically it seems. - i have collected the items that are in all pictures but some reason some how something is not right.

**Comment by metachronism** [comment]
You might have 2 identical workbenches in the same location, somehow

**Comment by midn8t** [comment]
no idea how that would happen i only was given one ?

**Comment by midn8t** [comment]
so i had to wait long enough to unlock a storage chest and move my stuff and then unlock the hammer. 

somehow the work bench you unlock when i placed it down i guess turned into two work benches - because when i used the hammer on it i have one workbench in my inventory and a work bench still siting in same spot ?

so that has to be some type of bug that happened or glitch i guess ?

**Comment by MarjieAVolk** [comment]
So action items for this bug:
- Can placing a single word object item result in multiple world objects?  (Investigate/fix)
- Prevent world objects from overlapping.

**Comment by metachronism** [comment]
this has been fixed earlier, can no longer place stuff in same place
