### ISSUE TITLE
distribution station + skill scrolls error msg incorrect

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#9951]
I was able to right click to learn several skills at a distribution station, but couldn't read 2 and the error msg said I didn't have enough room in my inventory. (which was basically empty)

Sounds like those 2 weren't in the authorized list.

**Comment by BlazeGuy2** [comment]
Tried to repro it, read several skill scrolls and got the expected error msg of already knowing the skill.

**Comment by D3nnis3n** [comment]
Could reproduce this, @BlazeGuy2, probably you did not understand correctly what Sean meant.

When you put two skill scrolls into the distribution station but only offer one of them to be taken from a user and the user tries to learn the other one with right cklick you get the following error message which is just wrong:

<img width="1482" alt="scrolls" src="https://user-images.githubusercontent.com/25908592/48307286-f6c0bd80-e549-11e8-84f2-b2776b244996.png">

**Comment by johnkslg** [comment]
@Quadbro was this fixed with your changes?

**Comment by Quadbro** [comment]
@D3nnis3n  Can you test this with new inventory tweaks?
