### ISSUE TITLE
Not all species were present

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9955]
It's a QA-Pass Task and for the first time i got several species that haven't even been created (web page shows there never has been one):
<img width="361" alt="species" src="https://user-images.githubusercontent.com/25908592/48198277-9fa7c680-e358-11e8-8dfe-7b7d47c4bf87.png">

**Comment by craig-jong** [comment]
I generated a few worlds and rechecked our force spawning and could not get this to occur. It looks like it happened with a number of plants that occur in a bunch of different areas - did you change any of the world generation settings?

**Comment by D3nnis3n** [comment]
Probably yes, i ususally use my live generation preset that has a lot more land and less ocean. Would be pretty strange if more land and therefore more chances for different land biomes would cause plants to not appear, but i do understand if you only accept reports for default generation. I just use a bit altered generation to also look if this does work. Altered generation settings that only increase plateau size and frequency should not really lead to some plants being extinct, if that is the cause at all.

**Comment by johnkslg** [comment]
Closing as not reproed. Reopen if repros.

**Comment by D3nnis3n** [comment]
Reoccured on 7.9.1 - normal map.

**Comment by elfl0rd** [comment]
It's still happens on freshly generated world at master.
"fresh" ecosystem
![default](https://user-images.githubusercontent.com/4980243/49694761-576f0480-fba1-11e8-951e-9a2d51366fa9.png)

**Comment by craig-jong** [comment]
The old wetlands plants are expected to be absent since wetlands don't exist anymore.

I'll look into the others.

**Comment by D3nnis3n** [comment]
Still occuring as of today. No rice, especially.

**Comment by elfl0rd** [comment]
> The old wetlands plants are expected to be absent since wetlands don't exist anymore.

Removing content is not ok :(

**Comment by elfl0rd** [comment]
What about "Amanita mushroom"?
![default](https://user-images.githubusercontent.com/4980243/51518245-4ebf4e80-1e2e-11e9-96a4-8846021b8085.png)
and 1 turkey from start is not nice too :\

**Comment by D3nnis3n** [comment]
Had no foxes and only 2 turkeys in a random map on 8.0 release preview.

**Comment by elfl0rd** [comment]
Not fixed, still have too low population of foxes, turkeys and wetland plants.

**Comment by akutamatata** [comment]
Getting this issue as well, 2 bisons, 0 foxes, 1 turkey
![nopopulation](https://user-images.githubusercontent.com/37421153/52382062-4845ef00-2a4a-11e9-9da9-f6c23779eca5.png)

**Comment by Quadbro** [comment]
8.0.4 QA pass 
![image](https://user-images.githubusercontent.com/6802030/53710999-934cf980-3e72-11e9-9786-e42a550b36c8.png)
![image](https://user-images.githubusercontent.com/6802030/53711005-9fd15200-3e72-11e9-9600-499e18a25a00.png)

**Comment by D3nnis3n** [comment]
Added Pending High - missing animals and plants is a main issue in the community-

**Comment by D-A-R-K-N-E-S-S** [comment]
Same here on 8.0.7 (no mods, default world). Before day is over zero pop on the following:
-Turkey
-Bullrush
-Sagerush
-Amanita Mushroom
-Buttonbush

**Comment by craig-jong** [comment]
For the last time, wetlands plants will have a population of 0 for now. We COULD remove them entirely, however the plan is to get them back into the game somewhat soon and it's significantly easier for us to leave them at their current (albeit old style) values than to simply remove them until that time. None of them are progression blocking.

As for the foxes and animals, there's a separate bug that was opened for that here:
https://github.com/StrangeLoopGames/EcoIssues/issues/11120

**Comment by D3nnis3n** [comment]
Could you be at least more specific which planst exactly are intended to be
zero and which are not?

craig-jong <notifications@github.com> schrieb am Mo., 8. Apr. 2019, 22:09:
