### ISSUE TITLE
[7.8.0 #Be3effa9] On-Screen Markers show as "My Waypoint"

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9956]
I don't really know how i managed to get this but it appeared after the server crashed on the other issue i reported, since then i have differing names on map and on-screen: (ALL of the markers are shown as "My Waypoint", not only the ones you can see in this screenshot)

<img width="1336" alt="waypoint" src="https://user-images.githubusercontent.com/25908592/48199657-1646c300-e35d-11e8-9298-41d57522b000.png">

**Comment by SeanAtr0n** [comment]
could you send your output log when this happens?

**Comment by SeanAtr0n** [comment]
I'm guessing there was an exception somewhere... that's the default marker text.

Looks like markers use Auto UI so maybe John knows of some reason they might break

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/9957

It happened while this output log was written.

**Comment by SeanAtr0n** [comment]
thought it happened after that log?

**Comment by D3nnis3n** [comment]
No, i had a crash and after this it happened, it was part of this log. This log includes 75% of my testing time for this qa-pass after the crash.

**Comment by BlazeGuy2** [comment]
Can't seem to get this issue to trigger for me.  @D3nnis3n can you help me find a repro case?

**Comment by D3nnis3n** [comment]
Yes, my SLG username is D3nnis3n.

I could not get this to reproduce either when it had occured and tried to do so. Seems to have been a edge case probably related to that crash, never had it before and relogging fixed it. Would propose dropping priority to low or closing it and i open a new issue when i can get this to happen again reproducibly. It's not like this would be a severe bug. Would that fit?

**Comment by D3nnis3n** [comment]
Closed for the reasons mentioned in the comment above.

**Comment by elfl0rd** [comment]
Reopen please, i found repro way.

It happens after localization changed.
![default](https://user-images.githubusercontent.com/4980243/48559958-d0aa6d00-e8fd-11e8-88e4-aa0657606242.png)
![default](https://user-images.githubusercontent.com/4980243/48559973-d902a800-e8fd-11e8-8555-1c11b389a944.png)

**Comment by D3nnis3n** [comment]
Reopened for reproduction case.
