### ISSUE TITLE
Long Server Name/Description interferes with legislation

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9958]
Version: v0.7.7.2-beta

field for name not accessible
![lawbad1snip](https://user-images.githubusercontent.com/38510829/48220866-bcf88700-e390-11e8-8ed0-b2aef40da4d7.jpg)

buttons not accessible
![lawbad2snip](https://user-images.githubusercontent.com/38510829/48220781-8a4e8e80-e390-11e8-830e-30a671f61871.jpg)

what it looks in browser
![browsersnip](https://user-images.githubusercontent.com/38510829/48220816-a05c4f00-e390-11e8-9a2a-5f4edb80b17a.jpg)

short form all ok
![shortform](https://user-images.githubusercontent.com/38510829/48220907-d1d51a80-e390-11e8-9821-72d07e4d67a6.jpg)

**Comment by D3nnis3n** [comment]
Yep, that happens with very small resolutions.

**Comment by elfl0rd** [comment]
For "user name" happens too
![default](https://user-images.githubusercontent.com/4980243/48224789-f12d7100-e3ab-11e8-9c37-fd4ec91ef6f7.png)

**Comment by syuzan-yeranosyan** [comment]
fixed and pushed the changes to  'issue_9958'  branch
