### ISSUE TITLE
Hosted Worlds: Username max. length

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9959]
He show incorrect error message.
![default](https://user-images.githubusercontent.com/4980243/48224872-44072880-e3ac-11e8-89c7-d194d1b115e2.png)
but max acceptable username is 49 characters long.

**Comment by rainfarmer** [comment]
@Tigran07 update max characters and notification to 49

**Comment by Tigran07** [comment]
completed and made a commit on branch
username_max_length
