### ISSUE TITLE
USER ISSUE: World Loading

### ISSUE THREAD

**Issue by JoeyPuntasal** [StrangeLoopGames/EcoIssues#9960]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
walking around can sometimes cause the world to disaper or vanish	

**Expected behavior:**
world would reload

**Actual behavior:**
World does not reload cuasing this to disapear like dead animals and my housen
**Do you have mods installed? Does issue happen when no mods are installed?:**
World does not reload cuasing this to disapear like dead animals and my house

**Comment by JoeyPuntasal** [comment]
it reloads after i reenter the world

**Comment by BlazeGuy2** [comment]
Vid and images would help, but it will be tricky to debug without a reliable/quick repro case.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information, log and if possible saved files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
