### ISSUE TITLE
USER ISSUE: unable to start local server

### ISSUE THREAD

**Issue by Sets** [StrangeLoopGames/EcoIssues#9961]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
when some chunks unable to load, disconnect the game then try to reopen world that happens.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Connection Failed
```

**Comment by Nicolausi113** [comment]
Is your system and graphic up to date with recent updates and DotNet at lest v4.6?
Is system minimum requirement fulfilled?
![minsyssnip](https://user-images.githubusercontent.com/38510829/48302640-4af28000-e4ff-11e8-9c3e-b2490e050249.jpg)

**Comment by SlayksWood** [comment]
Do you have this problem now?

**Comment by SlayksWood** [comment]
If it happens again, please reopen and provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
