### ISSUE TITLE
USER ISSUE: Invisible wall

### ISSUE THREAD

**Issue by Netarion** [StrangeLoopGames/EcoIssues#9962]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1.Grab some building material (or take one of your room)
2.Take the thin wall
3.Make a T shape
4.Put a shelf cabinet on the jonction of the T. It's looks on the direction of one of your wall.
5.The material closest of the ground will desapear but not completly.
6.Remove the shelf.
7.You lost the material and you can't put an other object where the material were.
8.Relaunch the game the material is lost but you can put something where it were.

**Expected behavior:**
A colision, the shelf shouldn't be placed were an object is.

**Actual behavior:**
The shelf is placed on an other object and make a collision for new other object.n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The shelf is placed on an other object and make a collision for new other object.

**Comment by Nicolausi113** [comment]
Weird issue with shelf cabinet, can be broken down to:
Where ever a shelf cabinet have been placed and removed from, nothing else can be placed until game restart.

![shelf1snip](https://user-images.githubusercontent.com/38510829/48302278-1ed50000-e4fb-11e8-9a32-670b3c20e3d5.jpg)

![shelf2snip](https://user-images.githubusercontent.com/38510829/48302284-2ac0c200-e4fb-11e8-8833-7cc1bba1323e.jpg)
