### ISSUE TITLE
Law creation, strange, non-logic behavior.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9964]
e.g.
when adding additional "When attempting to" section with different clause, section(s) lose available parameters.
![screen shot 11-10-18 at 10 40 am](https://user-images.githubusercontent.com/4980243/48298843-4d3fe480-e4d5-11e8-8e66-c590bdb30390.PNG)
![screen shot 11-10-18 at 10 42 am](https://user-images.githubusercontent.com/4980243/48298845-59c43d00-e4d5-11e8-893d-80cfd0460f6a.PNG)

Happens on release and master.

**Comment by elfl0rd** [comment]
e.g.
"in disctrict" parameters loose too.
![screen shot 11-10-18 at 10 53 am 001](https://user-images.githubusercontent.com/4980243/48298955-f509e200-e4d6-11e8-84db-761eae68791d.PNG)
![screen shot 11-10-18 at 10 53 am](https://user-images.githubusercontent.com/4980243/48298956-f6d3a580-e4d6-11e8-959c-e2e519461f2b.PNG)

**Comment by Deantwo** [comment]
Yes this happens very often when adding more triggers to the same law.
I can very easily reproduce this, and it can cause server crashes if a law gets passed with such nonsense logic.

**Comment by Deantwo** [comment]
Isn't this bug still present v0.8x.x?
