### ISSUE TITLE
[0.7.8.0 beta staging-be3effa9] Start EcoServer.exe deletes Old World

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#9965]
Every time i Start the Server with EcoServer.exe the the Old File from the Old World vanish in the Storagefolder and creates a new World.

EcoServer creates no Game.eco but a Game.tmp
![grafik](https://user-images.githubusercontent.com/37456949/48304894-0b895b00-e522-11e8-8877-c8347b56ff0a.png)

![ecosever](https://user-images.githubusercontent.com/37456949/48304916-6c189800-e522-11e8-8c6c-4cf123570c99.gif)

**Comment by D3nnis3n** [comment]
Did you let run a server start until it initialized completley?

**Comment by Sekor2600** [comment]
Yes. I did built on World for Tests. But then i did save and on nest Start new world

**Comment by D3nnis3n** [comment]
Did you try deleting the game.db and trying then to have the server run through one time until initialisation and then try to start the server again?

**Comment by Sekor2600** [comment]
Same Problem. 
![grafik](https://user-images.githubusercontent.com/37456949/48307360-6a16ff00-e54b-11e8-8e94-d2d20da04fcd.png)

EcoServer creates only game.db & game.tmp

**Comment by D3nnis3n** [comment]
Alright, thank you. Devs will surely take a look on this, so please check back here frequently in case they have questions :)

**Comment by D3nnis3n** [comment]
Can you please upload such a save file (Game.db + Game.tmp) after the server has initialised completley once?
You can attach it in this issue as a .zip if it is not too big, otherwise using Google Drive would probably be the best option, considering some of the devs seem to have problem accessing several one-click-hosters.

**Comment by Nicolausi113** [comment]
This is the builtin server within the client and is not meant to be started directly by the user, instead be means of the client like Load game or Create new game. A standalone web server must be downloaded from SLG account separately.
To start the client, set a starter link to this one
![client](https://user-images.githubusercontent.com/38510829/48313153-8ac96e00-e5b8-11e8-962d-377f1f7fd4de.jpg)

**Comment by D3nnis3n** [comment]
That's not correct. I use the "built-in" server for testing purposed without starting from ingame, too and it works very fine. I even use it to test my new cycles before they go on the live-server. I even assume the built-in server is exactly the same like the standalone server, but bundled to be uses from ingame for singleplayer purposes.

**Comment by Sekor2600** [comment]
https://drive.google.com/open?id=15RT5Hdm0qpZZRwxfORJ_7yZgkw2KNG19

Here are the Game.bd and Game.tmp   
Did new Test but Eco doesnt create a Game.eco.

**Comment by Nicolausi113** [comment]
Well, there is a difference in the new version, the file Game.tmp is finally not renamed to Game.eco as in v7.7.2 and server UI doesn't pop up (does it have a reason?). But a world named “Game” can be created through the client without problem.

**Comment by Sekor2600** [comment]
#9978 related

**Comment by D3nnis3n** [comment]
Considering the other issue is now marked fixed i'll close this as duplicate. Thanks for your help!
