### ISSUE TITLE
USER ISSUE: World loading stop

### ISSUE THREAD

**Issue by Alexandre-Frei** [StrangeLoopGames/EcoIssues#9966]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
Just play for like ten or fifteen minutes and then when you want to go away from your base to farm some things, after a hundred meters aprox., the world stop loading and then you fly. So i'm forced to disconnect and reconnect, then the game rollback me to an random place and then i make the world load again.

**Expected behavior:**
It should not happen, because the bug isn't from my PC and my network.

**Actual behavior:**
Instead, it just happens.n
**Do you have mods installed? Does issue happen when no mods are installed?:**
Instead, it just happens.

**Comment by SeanAtr0n** [comment]
Was there a red icon bottom right when this happened? If it happens again could you attach your output_log.txt to this bug? (paste this in file explorer to find it)
`
%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

**Comment by D3nnis3n** [comment]
No answer to Information request in 14 days, reopen if issue persists.
