### ISSUE TITLE
USER ISSUE: FPS drop with time

### ISSUE THREAD

**Issue by Alexandre-Frei** [StrangeLoopGames/EcoIssues#9967]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
After playing for about ten or fifteen minutes (Again yes ...), the FPS tends to drop from 60 FPS to 30-35. Again it's not about my configuration.

**Expected behavior:**
It should not happen but maybe it's a server side bug or an game optimisation problem.

**Actual behavior:**
Instead, it just happens.n
**Do you have mods installed? Does issue happen when no mods are installed?:**
Instead, it just happens.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11357
