### ISSUE TITLE
Long localized expression interferes with data in tooltip

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9968]
![longexpr](https://user-images.githubusercontent.com/38510829/48316285-11467580-e5e2-11e8-9902-f653a1c69cb6.jpg)

**Comment by elfl0rd** [comment]
@Nanders :P

**Comment by Nicolausi113** [comment]
I would suggest modifying tooltip layout  shifting data more to the right, it’s space enough – but thanks for directing it!
