### ISSUE TITLE
USER ISSUE: Server exception when hovering over order in public carpentry table

### ISSUE THREAD

**Issue by msgerbs** [StrangeLoopGames/EcoIssues#9970]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Create a public carpentry table
2. As a different player, put an order in the table (I used Waterwheel)
3. Go to the Public Crafting Stations tab
4. Hover over the Waterwheel icon

**Expected behavior:**
Should show info for the Waterwheel item

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Could not find matching method GetWorkorderTooltip on type TableTracker taking 1 parameters.
Source:Eco.Shared

System.Exception: Could not find matching method GetWorkorderTooltip on type TableTracker taking 1 parameters.
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname, Type& resultType)
   at Eco.Plugins.Networking.Client.ViewRPC(INetClient client, Int32 id, String methodname, BSONObject bson)</size>
```

**Comment by msgerbs** [comment]
Yikes, the github template in the game is _nasty_. Should probably just forward users to the issue template on the web directly.

**Comment by D3nnis3n** [comment]
I used your steps, tried with both players to over the waterwheel icon - both in project as in new project but couldn't reproduce this issue. Issue stays open so devs can look into it.

**Comment by seccombew** [comment]
Close as no repro, reopen if occurs in 7.8
