### ISSUE TITLE
QoL-Fixes for Player Currencies

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9972]
I got a lot of opinions on player credits and propose the following QoL Fixes for this matter

- Allow the world leader to set a default currency for the world that changes the default currency from player credits to the chosen one of any new placed objects that use credits. (Shop, Crafting Tables, as well as new contracts)
- Allow players to either personally hide or even disable player credits as a server setting in general. On big servers with many players it's hard to scroll through a laggy mess of credits that are not used at all in order to choose the currency you want to use.
- Sort the drop down menus for currencies to have backed currencies on TOP instead of buttom and sort the backed currencies for how much they are used.

**Comment by johnkslg** [comment]
@Quadbro 
1. On the treasury object, add a new tab that sets the default currency, this makes all new objects use that currency by default, and only the leader can hit it. 
2. Make the dropdown only show currencies that are 1) backed 2) your own 3) in use, having circulation.  Have a button that expands to show unused currencies.
3. Custom sort sounds good. Could have different icons for backed and unbacked currencies (get one from Milenko)
