### ISSUE TITLE
Negative Shop Values

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9974]
Allow players to set negative values in shops, so they can for example "buy" tailings or garbage while they receive payment for this. This will allow commercial tailings and garbage disposal that also works when the players are not online - a wish i heard quite often.

**Comment by Quadbro** [comment]
that's my wish too)

**Comment by Knigge** [comment]
I think this was possible before? Atleast i had a negative tax law, that paid you to use stores. Good Idea! let servers decide how they want to make laws and implementations. No reason this should not be possible.

**Comment by mvonow** [comment]
Can i upvote this? Would propose allowing negative payments in contracts aswell. Doesn't look like a big change

**Comment by D3nnis3n** [comment]
Added in 8.1.
