### ISSUE TITLE
Being able to differ between input and output storages

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9977]
This should be pretty self-explaining.

**Comment by Quadbro** [comment]
But you can achieve this by dragging input down, and output up in linked storages... or you mean "true only input" etc?

**Comment by D3nnis3n** [comment]
That will at least give problems when the Output is full and it uses Input Storage for Output then.

**Comment by D3nnis3n** [comment]
Players DID expand on this wishing to be able to use filters for better inventory management. But obviously this was out of the scope so i did not add an issue to it. That is something that could be done with conveyor belts or something else later on, but obviously no QoL or polishing improvement.

**Comment by tea** [comment]
> But you can achieve this by dragging input down, and output up in linked storages... 

Let's say I have a masonry table, and it has 2 jobs: grind stone to sand, and make pitch from sand. However I don't want to convert ALL stone to pitch. Instead I want to fill one stockpile with sand, and then convert all overflow to pitch. Can't do it with just priorities.
Same idea with kiln and glass/framed glass. Or I might just want to make sure my job can't overflow input storage with product (so e.g. my shop isn't blocked from buying stuff).

Related wish/idea is being able to place limit on a job same way it is done with buy orders. Stop producing stuff once there is N of product in the storage, and resume if some is taken/sold/used.

**Comment by D3nnis3n** [comment]
Thanks for giving another view and more in-depth Explanation on this, very welcome!

**Comment by johnkslg** [comment]
Closing for https://github.com/strangeloopgames/ecoissues/issues/20585
