### ISSUE TITLE
USER ISSUE: 7.8 Bleeding Edge - Server Reboot Creating new World everytime

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#9978]
**Version:** 0.7.8.0 beta staging-be3effa9

**Steps to Reproduce:**
After the patch this past Friday, it appears that everytime you reboot a server, it's forcing the world to regenerate.

**Expected behavior:**
Just rebooted.

**Actual behavior:**
New world created.n
**Do you have mods installed? Does issue happen when no mods are installed?:**
New world created.

Initially we believed that this issue was in regards to some of the changes we've been doing to the EcoSim file.  However, it appears that the problem isn't tied to that file, but rather something in the restart protocols aren't "remembering" the existing world.  I'm seeing the same issue on both our remotely hosted server and my local LAN server.

I'm still testing and will update this ticket as I can.

**Comment by Hydrohawk** [comment]
OK...I tried to restart my local server about 3 times and every time it regenerated.  I've been hearing reports from our other players and they are encountering the same issue.  So there is definitely an issue with the latest build.

**Comment by Nicolausi113** [comment]
Rename Game.tmp to Game.eco
related #9965
![tmpfile](https://user-images.githubusercontent.com/38510829/48333953-6ffb0600-e659-11e8-9cf8-e14813215baa.jpg)

**Comment by D3nnis3n** [comment]
Could you please look into your storage directory of the server and look if you have a Game.tmp after fully starting up a server? If yes, please close the server after it has been completely initialised and upload the "game.tmp" file in a .zip file here or on google drive.

**Comment by D3nnis3n** [comment]
Okay, after redownloading bleeding-edge that now also occurs to me. World in the attachment.
[Storage.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2572044/Storage.zip)

**Comment by Sekor2600** [comment]
Well then I am no longer alone with the problem.

Ecoserver - > game.tmp
Eco.exe in game - > name.eco

**Comment by johnkslg** [comment]
Woo fixed!
