### ISSUE TITLE
USER ISSUE: Double place

### ISSUE THREAD

**Issue by Sandflakes** [StrangeLoopGames/EcoIssues#9979]
**Version:** 0.7.7.2 beta

**Steps to Reproduce:**
1. Take a stack of blocks in the hands, Logs, dirt, hewn.
2. Place down on the ground as a stack or with hammer.
3. Repeat until bug occurs.

**Expected behavior:**
It should place one block each click.

**Actual behavior:**
Sometimes places two blocks.
**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods, never used mods.

**Comment by Deantwo** [comment]
I am guessing you mean what happens if you try to place a **Log** (or construction material without a hammer) against a wall?
One Log will appear on the floor below the location you placed it, and a fake Log will appear in the air where you tried to place it.

I have been meaning to report that, but didn't know how to put in it into word.

**Comment by Sandflakes** [comment]
> I am guessing you mean what happens if you try to place a **Log** (or construction material without a hammer) against a wall?
> One Log will appear on the floor below the location you placed it, and a fake Log will appear in the air where you tried to place it. It doesn't always happen, it seems to happen mostly if the drop is very far. The fake Log vanishes when another block is placed near it.
> 
> I have been meaning to report that, but didn't know how to put in it into word.

Not exactly, this happens with both the hammer and normal placement. These objects are real and will consume one object from the inventory. Placing the object will place one in the real location and one on top of that, same as if you would click twice.

**Comment by Sandflakes** [comment]
Found an addition to this issue, if this occurs outside the edge of someones claim, that you do not have authorization in, it can place the block inside that claim. Does not allow you to remove it after like normal.

**Comment by SlayksWood** [comment]
Checked on 0.9.0 stagings. Wasn't able to reproduce. If it happens again, please reopen.
