### ISSUE TITLE
land markers - deeds and mini map 5.3

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#998]
have issue its not huge ordeal but mini map does not seem to be updating marked zones, i turned server on and off and logged in and off the marker-ed areas and marked and it says that we own them in the mini map and we can claim and unclaimed  but some reason marked zones just are not color coordinating on the mini map the first 10 did but after that it is no go

![20170105165846_1](https://cloud.githubusercontent.com/assets/15990789/21700899/4ac88192-d368-11e6-80b4-66f6cfa36f8e.jpg)

**Comment by midn8t** [comment]
this seems to not be an issue like it use to be, now it seems only happen due to horrible lag that mini map causes so it ends up just taking a long time for it to start to function sometimes now.

**Comment by midn8t** [comment]
I had issue with land makers and mini map just now.

so i put down some land markers and they did not appear on the mini map.

so i thought maybe i would log in and off so i did, still did not appear.

the land makers no longer in my inventory at this point.

so i went to the server did a force save so it would save in storage
then i shut down the server and restarted it - the mini map was working again but the locations i land claimed are public and I am still missing my markers.

before i shut down server and saved my it said the land belonged to me.

**Comment by metachronism** [comment]
should be working now
