### ISSUE TITLE
Right click to edit text field

### ISSUE THREAD

**Issue by QUEWEX** [StrangeLoopGames/EcoIssues#9981]
**Current Behavior**: Players must click on the small 'crayon' to modify text names (e.g. stockpiles). While this is a basic and obvious option, it is also unnecessarily precise.

**Suggested Behavior**: Allow a right click on any space in a given text field in order to immediately edit the text. The text can either be highlighted in full (current default behavior when editing), or position the text cursor where the right click occurred (or at the end of the text if the field is much larger than the provided text.)

This has little relevance for things like stockpiles (although it would still be more convenient than current edit text icon), but may have more relevance in UI windows that I don't have as much experience with (laws, contracts, stores, signs).

**Comment by D3nnis3n** [comment]
Also moved on my responsibility.

**Comment by elfl0rd** [comment]
It's more of a suggestion than a issue, but I support it.

**Comment by Deantwo** [comment]
On a related note, when you are editing an object's name it is too easy to unselect the edit field.
I very much relay on copy-pasting for easy and quick text texting. Here in is the need to select/mark text in the text field, but left clicking the text field will close the editing.

I would also say that the editing field is very tiny (if you scale the UI down for small window mode), I would almost rather have a text input dialog pop-up than edit that annoying little text field.

**Comment by Spydarlee** [comment]
General UI scaling is probably a wider issue for another time, but making the input field a pop-up is a nice idea. We could revisit that one later if it continues to be an issue here and elsewhere, but for now I've added right-click-to-edit support. :)

![lostwordsrightclickedittitle](https://user-images.githubusercontent.com/553695/49517454-225a6d80-f894-11e8-839b-8bef203ec553.gif)

**Comment by elfl0rd** [comment]
@Spydarlee hmm... why _name_ contain worldobject icon and color? 0_p
