### ISSUE TITLE
Key/modifier for quick-moving items/stacks

### ISSUE THREAD

**Issue by QUEWEX** [StrangeLoopGames/EcoIssues#9982]
I can see this is a frequently suggested option, whether by some means of another. I am not certain whether yet another suggestion in this vein would be useful or helpful, but I wanted to offer my analysis and suggestion regardless.

I had initially posted this under Suggestions, but was advised to close that entry and to repost here under Issues.

**Current Behavior**: The primary method for moving items is to click and drag (with carry inventory also being able to "take" from and "put" into stockpiles). Given the base gameplay Eco seems to be aiming for (i.e. low automation, presumably with little auto-sorting capabilities, especially "early game"), this is extremely tedious and physically hostile due to the repetitive nature of the motions, the frequency that dragging around must be repeated, and compounded by the [snap back](https://github.com/StrangeLoopGames/EcoIssues/issues/9980) due to the constricted landing areas for dragging.

**Proposed Behavior**: Improving the landing areas will alleviate this somewhat, but I suggest adding a modifier key to allow quickly moving items from the player to an inventory, or vice versa. In most games, this is handled by Shift+click, but as Eco uses Shift for splitting stacks, an alternative modifier will need to be found. Note this doesn't necessarily have to specifically be a modifier (shift, alt, ctrl), but likely any held key could work in this respect - for example, hold the letter x and left click.
 - [Key]+Leftclicking items from the player's inventory (hotbar, carry inventory, backpack) would move to the inventory the player has open. [Key]+Leftclicking within an inventory (chests, etc) will move it to the player's hotbar/backpack. 
 - **Items within a stockpile (carry-valid items) should _swap_ with the player's inventory, including empty space!** This is an important distinction to make: my suggested behavior is intended to minimize time spent managing items, and if the player had to move the cursor back and forth between the "taken" stockpile, his carry inventory, and the "target" stockpile, it would not be much improved over dragging. Instead, allowing the key to swap with empty spaces would allow the player to move items between stockpiles in this method without returning to their carry inventory box every transaction.
 - I had initially considered right click as a possibility, but I recall now that this "uses" items (primarily eating food), and this is behavior that I have used myself (accessing a nearby inventory in order to eat food from a link inventory). This could possibly be changed (used items, including food, must be carried by the player to be used) and instead right click used as the default behavior of transferring to/from the player and an inventory. If this is done, modified-right-click could also allow alternative behavior (e.g. transfer from active inventory to linked inventory and vice versa directly, rather than to the player).

**Comment by D3nnis3n** [comment]
Assigned Quadbro as he is already working on something like this, can probably take a look on this and get inspiration.
