### ISSUE TITLE
[Bleeding Edge #be3effa9] Room types mixing

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#9983]
It should not be possible for a **Wooden Latrine** and a **Icebox** to both give SP in the same room.

![2018-11-12 17_57_38-window](https://user-images.githubusercontent.com/2676134/48362750-a316b700-e6a4-11e8-8b87-2631e752f3e9.png)

**Comment by Deantwo** [comment]
I can even add my **Wooden Straw Bed** to the same room and it still works.

![2018-11-12 17_57_38-window](https://user-images.githubusercontent.com/2676134/48363037-4667cc00-e6a5-11e8-8e2c-45507017f037.png)
ed to the

**Comment by elfl0rd** [comment]
Intended.
Room definitions based on furniture with higher SP value, if multiple furniture with same SP value - used first type.

**Comment by Deantwo** [comment]
But a bathroom furniture is not suppose to give SP if in a kitchen.
So it is not the type of room that I am thinking of, but the fact that they all give SP.

By the way, why it is called "Deantwo's House"? Wouldn't "Deantwo's Home" be more generic?

**Comment by elfl0rd** [comment]
> But a bathroom furniture is not suppose to give SP if in a kitchen.
So it is not the type of room that I am thinking of, but the fact that they all give SP.

Why? Just look
![thumb](https://user-images.githubusercontent.com/4980243/48365865-2c39e800-e6bd-11e8-9ab2-fe40e738cf4c.png)
![1478989537119044980](https://user-images.githubusercontent.com/4980243/48365866-2c39e800-e6bd-11e8-95dd-9fc77dffb685.jpg)
![article-2516577-19c162f800000578-920_634x388](https://user-images.githubusercontent.com/4980243/48365867-2c39e800-e6bd-11e8-9e65-04d35924a3ff.jpg)
![dizain_kvartir](https://user-images.githubusercontent.com/4980243/48365868-2c39e800-e6bd-11e8-8bcf-3b84ecae56cb.jpg)
![2735654136796137-590x369](https://user-images.githubusercontent.com/4980243/48365869-2cd27e80-e6bd-11e8-9c68-1055c892133d.jpg)
![studio4_2011-05-17_123847-590x389](https://user-images.githubusercontent.com/4980243/48365870-2cd27e80-e6bd-11e8-94d8-8587a68617b4.jpg)

**Comment by elfl0rd** [comment]
In addition, you offer to significantly reduce the variety of furniture in the rooms. For example, what about the General category? To ban its use in other? Or to make other categories an exception?

**Comment by Deantwo** [comment]
General category (in my experience) has been the exception. General furniture can be in any room.

**Comment by elfl0rd** [comment]
Nevertheless, mixed rooms exist in the real world :) Even such strange as a bathroom-bedroom and a toilet-kitchen.
![vannaya-i-spalnya-v-odnoj-komnate5](https://user-images.githubusercontent.com/4980243/48367694-8db08580-e6c2-11e8-91a9-bde23b699682.jpg)
![bedroom-bathtubs-05](https://user-images.githubusercontent.com/4980243/48367695-8db08580-e6c2-11e8-94bf-30ba117ca05e.png)

**Comment by Deantwo** [comment]
@elfl0rd, i at no point meant that you can't do it in real life. But you didn't used to be able to do it in the game. Hence a bug report about behavior changed weirdly.

Still need to test if industry furniture currently trash the SP from the room.

**Comment by Deantwo** [comment]
Maybe I remember wrong as to how it works in release, let me test it and I'll reopen if I was right.

**Comment by Deantwo** [comment]
I never got to check the stable branch before bleeding edge was merged into. Guess I am too lazy to roll back to an older version just to test this.
