### ISSUE TITLE
7.8.0 Stuffed Elk Takes 10.5 hours to Tick World Layers

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#9985]

**Comment by johnkslg** [comment]
Can you see why this would happen? 
Memory ran out and its paging to the HD?

**Comment by D3nnis3n** [comment]
I think that is the "Make sure a tick doesn't take longer than 30s" task on QA-Pass? I ticked that one with 12s (similar time to the versions before) on my latest pass, using a clock to stop time until it finished the tick in the server manager ui.

**Comment by SeanAtr0n** [comment]
don't think this happens anymore
