### ISSUE TITLE
Performance impacts when world layers are ticking

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9987]
Reports of lag and inability to join the server during sleep (when ticks are happening in succession).  We should change world layer ticking to have a minimal impact on the rest of the game by running the thread with less resource consumption.

**Comment by SeanAtr0n** [comment]
you want it to run as fast as possible.......... but with low priority?

**Comment by johnkslg** [comment]
For normal ticking it should be low priority so we dont get lag spikes.
For ticking during sleeping, I suppose its ok to consume more resources, but not to the point where players cant login.

**Comment by SeanAtr0n** [comment]
I tested with 2 accounts and was able to join while one was sleeping
