### ISSUE TITLE
Multiple sleeping players doesn't work

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#9988]
When multiple players are on a server you can't seem to activate sleep. The message always says 0 of # sleeping even when everyone is sleeping.
![image](https://user-images.githubusercontent.com/774628/48449561-ce0e1300-e757-11e8-9298-a26b4e152496.png)

**Comment by D3nnis3n** [comment]
Added fixed label, afaik it should auto-close on merge? Don't want to close yet, until you want to do.
