### ISSUE TITLE
7.8.0 Minimap Icons off

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#9990]
![minimap](https://user-images.githubusercontent.com/6262198/48451564-ceaaa780-e75f-11e8-84f2-75faa4ba259c.gif)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/72337365-7f4d6780-36d3-11ea-9810-9fa56a3daf22.png)
![image](https://user-images.githubusercontent.com/45708377/72337381-8aa09300-36d3-11ea-8157-08e8a0a08b13.png)
