### ISSUE TITLE
Other players dont animate when walking

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9991]
In current staging
![animx](https://user-images.githubusercontent.com/3536496/48452651-e3d60500-e764-11e8-8fcd-202eb63cc1c8.gif)

**Comment by SeanAtr0n** [comment]
steps to reproduce?

**Comment by johnkslg** [comment]
Hosted a world locally, connected two clients (one Unity and one a built exe), both clients saw the other doing this.

**Comment by SeanAtr0n** [comment]
were you flying at the time?

**Comment by SeanAtr0n** [comment]
more info would be helpful, I'm not seeing this

**Comment by D3nnis3n** [comment]
Not seeing this either, but it's common for flying.

**Comment by D3nnis3n** [comment]
They did animate on my server - as long as it was online - in 7.8, too.

**Comment by johnkslg** [comment]
I was flying for a time, I typed /fly and went in the house, then turned it off. But the issue persisted even after logging out then logging in on each client.

**Comment by SeanAtr0n** [comment]
couldn't easily reproduce... i'll look into it if anyone else runs into it

**Comment by SeanAtr0n** [comment]
probably fixed
