### ISSUE TITLE
Sleep button is disabled despite having auth access

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9992]
![image](https://user-images.githubusercontent.com/3536496/48452711-2bf52780-e765-11e8-8a9a-8a2461cd6e30.png)
![image](https://user-images.githubusercontent.com/3536496/48452719-32839f00-e765-11e8-9ea0-149c1ce8ad59.png)
use /spawnbed to test

**Comment by Quadbro** [comment]
Tested master, it's ok, will test release branch soon

**Comment by Quadbro** [comment]
can't reproduce this with release too... All is working as intended..
