### ISSUE TITLE
Server doesn't start, crashes

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9993]
> --BEGIN DUMP--
> Dump Time
> 11/14/2018 02:09:27
> 
> Exception
> Exception: NullReferenceException
> Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
> Source:Eco.Gameplay
> 
> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>    at Eco.Gameplay.LegislationSystem.LawLogic.Fields.AliasDropDown.IdToDisplayName(String id)
>    at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.RefreshDisplayName()
>    at Eco.Gameplay.LegislationSystem.LawLogic.Fields.DropDown`1.Init()
>    at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
>    at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
>    at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
>    at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
>    at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
>    at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
>    at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
>    at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
>    at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
>    at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
>    at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
>    at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
>    at Eco.Gameplay.LegislationSystem.LawLogic.LawLogicNode.InitializeAndValidate()
>    at Eco.Gameplay.Items.Law.Initialize()
>    at Eco.Gameplay.Legislation..ctor()
> 
> --END DUMP--
> 

Using a world from latest staging build.

**Comment by D3nnis3n** [comment]
This also happens on new world, not only migrated ones:

1. Generate new world
2. /clearlaws
3. Create a district law
4. Create a law prohibiting anyone but admins to claim in the district
5. /passlaws
6. Restart server
7. See the aforementioned crash.

**Comment by johnkslg** [comment]
Hotfix incoming.
