### ISSUE TITLE
Server Crash 0.7.8 on startup

### ISSUE THREAD

**Issue by TheKrush** [StrangeLoopGames/EcoIssues#9997]
```
--BEGIN DUMP--
Dump Time
11/13/2018 18:18:31

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.PropertyManager.GetDeed(Guid deedId)
   at Eco.Gameplay.Utils.PickerProperty.get_Deed()
   at Eco.Gameplay.Utils.PickerProperty.OnDeserialized()

--END DUMP--
```
World: https://drive.google.com/open?id=1M6aOW5e8nVIjl7UNtkiDiEMSj4tLl1zk

**Comment by TheKrush** [comment]
The only mods I had installed were:

- https://eco.mod.io/adminutils1
- https://eco.mod.io/discordlink
- https://eco-mods.com/resources/another-motd-plugin-asphalt-mdk.85/

I removed all and loaded the game in 0.7.7.2 and updated the world linked with that version. None of them should have affected the world itself. 0.7.8 crashes regardless of mods or not.

**Comment by TheKrush** [comment]
These were the mod added files, all of which I removed.

![image](https://user-images.githubusercontent.com/671500/48457041-15a39780-e776-11e8-8c67-7c9541f27390.png)

**Comment by D3nnis3n** [comment]
Game World of Duplicate Issue #9998:

https://drive.google.com/file/d/1szSDZ_TrYC7sl7mFny7x3p2lTH8ctyGN/view?usp=sharing
