### ISSUE TITLE
CRash in 7.8

### ISSUE THREAD

**Issue by bleckman74** [StrangeLoopGames/EcoIssues#9998]

**Comment by bleckman74** [comment]
https://drive.google.com/file/d/1KVKrQQjTt1Ylopq9OMhvRbrUOGPOazhW/view?usp=sharing
https://drive.google.com/file/d/1szSDZ_TrYC7sl7mFny7x3p2lTH8ctyGN/view?usp=sharing
my world is there and crash log

**Comment by D3nnis3n** [comment]
Duplicate of #9997
